### ISSUE TITLE
[Deployment Issue] "repository name must be lowercase" when deploy One Click App

### ISSUE THREAD

**Issue by Morb0** [caprover/caprover#1000]
What is the problem?

I install latest version of Docker by documentation on VPS with Ubuntu 18.04 and when I use `One Click App` to install Redis got a error `invalid reference format: repository name must be lowercase`. Seems CapRover not support last version of Docker `20.10.3`.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

- Install Docker by documentation `Install Docker Engine on Ubuntu` using repository
- Install CapRover
- Create new Redis `One Click App`

Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 18.04
- RAM?
4096MB

**Comment by githubsaturn** [comment]
I just tested it and it works fine. Did you change any of the default parameters? The error indicates that you have a capital letter in the image. Did you change the version?

**Comment by Morb0** [comment]
I checked and it really works. I can’t see the information from that VPS now because I deleted it. Perhaps there was an accidental VPS error because I re-installed it many times.

I use now Ubuntu 18.04 and Docker 20.10.2 and all work perfectly.

Thank you for that great tool.

**Comment by Morb0** [comment]
It seems to have reappeared while trying to deploy app or create `One Click App`.

`Error: Push failed: Error: (HTTP code 500) server error - invalid reference format: repository name must be lowercase`

What additional information can I provide?

**Comment by Morb0** [comment]
I realized this happens when I connect the gitlab registry.
