### ISSUE TITLE
ClusterControl

### ISSUE THREAD

**Issue by Vladimir-Va** [caprover/caprover#1002]
Due to the fact that we cannot create a cluster for the database in caprover, I think it makes sense to add in One-Click Apps [ClusterControl Image](https://hub.docker.com/r/severalnines/clustercontrol)? Or implement in caprover.

**Comment by githubsaturn** [comment]
Not sure how ClusterControl works, but by the looks of it, it has some non trivial configs that are not supported by CapRover one click apps, like:
```
--network db-cluster \
--ip 192.168.10.10 \
-h clustercontrol \
```
Feel free to take a stab at this though. These config may be optional...
