### ISSUE TITLE
Ubuntu 20.04 obstacles?

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#1003]
As per previous mentions and the [Getting Started](https://caprover.com/docs/get-started.html) documentation explains, Ubuntu 18.04 is still the recommended distribution to use. It would be beneficial to document if [this](https://github.com/moby/moby/issues/41825) is the only known issue or if there are other hurdles that are preventing usage as well so that we can understand this landscape better.

**Comment by githubsaturn** [comment]
The reports are scattered, but here is other ones that I am aware of:
https://github.com/moby/moby/issues/41565
https://github.com/moby/moby/issues/41775

They are mostly around networking. But this is just the surface. If simple things that should work right off the bat are this flaky, it kinda tells me there could be more deeper issues that won't surface easily until these fundamentals are fixed. Like it's mentioned in the doc, Ubuntu 18 is well supported for a few years, so it shouldn't be a huge concern for now....
Feel free to add them to to getting started. Docs are editable:
![image](https://user-images.githubusercontent.com/10582082/107160673-b5f0c280-6965-11eb-871d-fc1914b0d8de.png)
