### ISSUE TITLE
Nginx Reverse Proxy to Host

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1004]
I have Code-Server running baremetal on the Server on Port 8053.

I have Caprover on the same System.

I want a Nginx Reverse Proxy inside Caprover, because Port 80 and 443 are already in use

But I dont know which Upstream address i should use, because I cant simply use `localhost` or `127.0.0.1`, because it points to the container itself, I tried the IP-Addresses from `route`, but these ones timeout with `HTTP 504`.

I saw that Caprover uses Upstream addresses like `http://srv-captain--discordbot`, but Code-Server doesn't. Is their any way to fix that?

**Comment by githubsaturn** [comment]
You can try using the public address of the server. Make sure you are opening your port on your firewall, e.g.:
```
ufw allow 8053
```

**Comment by githubsaturn** [comment]
Also, I think the build in Nginx reverse proxy one click app may not support websocket (which is necessary) for Code Server.

Feel free to create a pull request to change that though...

**Comment by kaaax0815** [comment]
Caprover has a button to enable Websocket Support, so I think that shouldn't be a problem, I try using your approach

**Comment by kaaax0815** [comment]
By doing your approach I get a 502 Bad Gateway Error


If you know how to persists packages in a docker container, that would also fix my problem

**Comment by githubsaturn** [comment]
> If you know how to persists packages in a docker container, that would also fix my problem

Docker containers are ephemeral. If you want to persist changes, you can build and deploy a new image, e.g.:
```
FROM youroldimage:tag
RUN apt update && apt install -y curl
```

**Comment by kaaax0815** [comment]
I am bad at writing Dockerfiles and cant even make a Dockerfile for codercom/code-server
