### ISSUE TITLE
Reverse Proxy --net=host Parameter

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1005]
I want to use the Nginx Reverse Proxy to use my service which is running on the host. But I cant use any other reverse proxy, because Caprover is bind to port 80 and 443.

So the only way is to
1. Dockerize my service (which I cant and don't want for some reasons)
2. Use the `--net=host` Parameter, to make the service accessible for the container.

If their isn't a way to do it could you please provide a potential way that works.
My Service is bind to port 8053 and must be behind a reverse proxy. SSH Port forwarding is not a possible way

**Comment by githubsaturn** [comment]
If you want to make custom changes to any app that is deployed via CapRover, you can use [config override](https://caprover.com/docs/service-update-override.html). It allows for any config override that you need.

**Comment by kaaax0815** [comment]
I think you cant change the network unfortunately

>It allows for any config override that you need.

**Comment by githubsaturn** [comment]
Make sure you read the docs here: https://docs.docker.com/engine/api/v1.40/#operation/ServiceUpdate

Just by looking at at, it looks like there is a network array in `TaskTemplate > Networks`
