### ISSUE TITLE
[Deployment Issue] Double curly braces in env var

### ISSUE THREAD

**Issue by Morb0** [caprover/caprover#1007]
What is the problem?

I can't set ``` {{.Container.Config.Hostname}}@`hostname` ``` as env variable I'm getting `Something bad happened.`

In logs `captain` getting this exception:
```Error: (HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = expanding env failed: expanding env "SYSLOG_HOSTNAME={{.Container.Config.Hostname}}@`hostname`": template: expansion:1:12: executing "expansion" at <.Container.Config.Hostname>: can't evaluate field Container in type *template.Context```

Seem like the internal templater try to parse double curly braces.

Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 18.04

**Comment by githubsaturn** [comment]
This is an error thrown by Docker API. It's not being thrown by CapRover.

Suggest you base64 encode your value to get around this.

**Comment by githubsaturn** [comment]
Here is the full error log:
```

    | February 9th 2021, 11:13:58.941 pm    Error: (HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = expanding env failed: expanding env "asfdasdf={{test}}": template: expansion:1: function "test" not defined 
    | Error: (HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = expanding env failed: expanding env "asfdasdf={{test}}": template: expansion:1: function "test" not defined 
    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:331:7)
    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:300:5)
    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:275:14)
    |     at IncomingMessage.emit (events.js:327:22)
    |     at endReadableNT (_stream_readable.js:1327:12)
    |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Morb0** [comment]
thanks, I'll try
