### ISSUE TITLE
How to update one click application? CapRover?

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1008]
I searched for the documentation, but I didn't find the way to:

* update one-click installed application? So, let's say I have PostgreSQL 10.2 and I want to upgrade it to 10.3 - how do I do that?
* how do I keep CapRover itself updated?

Thank you in advance!

**Comment by githubsaturn** [comment]
https://caprover.com/docs/one-click-apps.html#upgrading-one-click-apps

**Comment by githubsaturn** [comment]
> how do I keep CapRover itself updated?
When there is an update available you'll see a banner on the UI to upgrade.

**Comment by alexander-potemkin** [comment]
Shame on me for missing that, thank you very much for your assistance!!!
