### ISSUE TITLE
[Question] How to use subdomains with deployment of CapRover?

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#1010]
I'd like to use CapRover on a server named something like: `caprover1.domain.tld`

My goal is to run multiple projects and other domains' services on this as well via one larger server instance.

When I start the CapRover npm CLI setup and get to the `CapRover server root domain` stage and enter `caprover1.domain.tld` I get:
> Error Code: 1107  Message: Verification Failed

Now in this case I am using a real FQDN and reverse lookup with the correct IP is working, but CapRover clearly doesn't like something going on here.

The full error message (redacted real FQDN of the server + IP, but I'm sure you already understand this):
```
Cannot verify that caprover1.domain.tld points to your server IP.
Are you sure that you setup your DNS to point "*.caprover1.domain.tld" to 111.111.111.111?
Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.

Error Code: 1107  Message: Verification Failed.
```

I'm using CloudFlare here and so I'm not sure if it is going to flatten/work with the wildcard for a subdomain as hoped, but I'm hoping you might be able to point me in the right direction here...

**Comment by githubsaturn** [comment]
Did you use wild card for your A record?

For example, does abcdefg.caprover1.domain.tld resolve to your up?

**Comment by ylluminate** [comment]
There was a nuance that I did not see documented for CloudFlare openly, one must set up the wildcard on the top of the sub via something like making an A record in CloudFlare of literally `*.caprover1.domain.tld` that points to the IP. I think I'm moving in the right direction now since my assumption that it handled this similar to the naked domain. I'll circle back here if this doesn't resolve it entirely.

**Comment by ylluminate** [comment]
Perhaps I closed this too soon. After walking through the rest of the setup and plugging in what I perceive to be the right hostname for the [next step](https://github.com/caprover/caprover/issues/1011), but may be wrong on, and allowed it to setup SSL, I tried to visit CapRover again and upon redirecting to the SSL version (`https://caprover1.domain.tld:3000/`), I encountered failure:
```
This site can’t provide a secure connection
caprover1.domain.tld sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

**Comment by githubsaturn** [comment]
Https doesn't run on port `3000` just drop the port portion and it works.

**Comment by ylluminate** [comment]
Well I tried that too @githubsaturn (ie: `https://caprover1.domain.tld/`) and got:
```
Your connection is not private
Attackers might be trying to steal your information from caprover1.domain.tld (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID
```

**Comment by ylluminate** [comment]
Hopefully you saw this last comment - the issue was closed again and I can't seem to reopen it now.

**Comment by githubsaturn** [comment]
Run this on your server:
```
cat /captain/data/config-captain.json
```
What does it print?

**Comment by ylluminate** [comment]
```
root@localhost:~# cat /captain/data/config-captain.json
{
	"namespace": "captain",
	"customDomain": "caprover1.domain.tld",
	"emailAddress": "my@emailaddress.tld",
	"hasRootSsl": true,
	"forceRootSsl": true,
	"hashedPassword": "$$$$$$$$$$$$$$$$$$$$$$$$$$$"
}
```

**Comment by githubsaturn** [comment]
Run this command on your local machine. Does it print your server IP address?
```
curl -vI http://abcdefg.caprover1.domain.tld
```

**Comment by ylluminate** [comment]
Yes

**Comment by githubsaturn** [comment]
Okay then, that doesn't explain why you're getting cert issue. What if you run these:
```
curl -v http://abcdefg.caprover1.domain.tld
## and
curl -v https://abcdefg.caprover1.domain.tld
```
Do both of these work fine?

**Comment by ylluminate** [comment]
HTTP yes. 

HTTPS, no. Hmm, self signed:
```
$ curl -v https://abcdefg.caprover1.domain.tld
*   Trying 123.123.123.123...
* TCP_NODELAY set
* Connected to abcdefg.caprover1.domain.tld (123.123.123.123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by githubsaturn** [comment]
And I assume `123.123.123.123` is the IP address of your server..

Not sure how you managed to get to this stage. You only get to this stage if HTTPS is not properly set up. A few things to check:

1- 
Try to restart your service:
```
docker service update captain-nginx --force
docker service update captain-captain --force
```

2- Make sure you have the let's encrypt certs:
```
ls /captain/data/letencrypt/etc/live/
## does include "captain.caprover1.domain.tld" directory?
## does the directory has the certs?
```

3- If neither of the above worked, edit the config.json manually and set HTTPS flags to false 
```
	"hasRootSsl": true,
	"forceRootSsl": true,
```
and restart your service. At this point you should be able to access your dashboard using http.

**Comment by ylluminate** [comment]
Yes, my real IP is correct vs the "123" fake I have above. Regarding points:
1) result is the same after refresh, here's output just fyi:
```
root@localhost:~# docker service update captain-nginx --force
captain-nginx
overall progress: 1 out of 1 tasks
1/1: running
verify: Service converged

root@localhost:~# docker service update captain-captain --force
captain-captain
overall progress: 1 out of 1 tasks
1/1: running
verify: Service converged
```

2) `$ ls /captain/data/letencrypt/etc/live/captain. abcdefg.caprover1.domain.tld/` contents:
```
cert.pem  chain.pem  fullchain.pem  privkey.pem  README
```

3) can you send me abbreviated steps for editing `config.json` and restarting the services/container properly?

**Comment by githubsaturn** [comment]
```
nano captain/data/config-captain.json
```
Edit these two values and change them both to `false`:
```
	"hasRootSsl": true,
	"forceRootSsl": true,
```

Then run:
```
docker service update captain-captain --force
```

**Comment by ylluminate** [comment]
Thanks, so yes, HTTP now works and shows the expected `Nothing here yet :/` message, but of course HTTPS has the same failed result.  I guess the problem at this point is why is it self signing or detecting it as such?  Do we need to debug the letsencrypt process?

**Comment by githubsaturn** [comment]
It shows `Nothing here yet :/` ?? There is something fundamentally wrong. You should see the login page.

What is the address you use?

**Comment by ylluminate** [comment]
`http://caprover1.domain.tld/` and yes, tried in multiple incognito Chromium based browsers all the same:

![example](https://p153.p0.n0.cdn.getcloudapp.com/items/6quQxGDz/5053085a-b02a-47e9-b04d-85795373e66f.jpg)

**Comment by githubsaturn** [comment]
You have to go to `http://captain.caprover1.domain.tld`

**Comment by ylluminate** [comment]
Alright, caught up in the moment I guess. Yes that loads the login page for admin.  

So where do we go from here?  We have several production apps to deploy and hoping to use this instance to do so, but obviously SSL is going to be important...

**Comment by githubsaturn** [comment]
Just log in. Go to dashboard, enable https, force https and done.

**Comment by githubsaturn** [comment]
As a matter of fact it was working from the beginning probably .... You were just using an incorrect address

**Comment by ylluminate** [comment]
I believe we're good here now... Thanks so much for the information above, you may be right. I initially did have the problem with the leading `captain` hostname I believe, but there's a possibility it became muddled in the process since we were talking about wildcards and I was testing all of that with CloudFlare.

**Comment by arladmin** [comment]
Hi,

I keep running into this issue as well!
I have tried various methods of installation:
1. DigitalOcean 1-click Caprover instance
2. DigitalOcean Docker droplet and then Caprover manual installation
3. DigitalOcean Ubuntu droplet and then Caprover manual installation

In all my tries, i face the same error:

````
Error Code: 1107  Message: Unexpected output when enabling SSL forcaptain.caprover1.mydomain.tld with ACME Certbot
 Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for captain.caprover1.mydomain.tld
Using the webroot path /captain-webroot/captain.caprover1.mydomain.tld for all unmatched domains.
Waiting for verification...
Challenge failed for domain captain.caprover1.mydomain.tld
http-01 challenge for captain.caprover1.mydomain.tld
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: captain.caprover1.mydomain.tld
   Type:   unauthorized
   Detail: Invalid response from
   http://captain.caprover1.mydomain.tld/.well-known/acme-challenge/Q-fFuQIse9cdHCRDEPbQThQyYkZ8Bqbx0K2_O3LOWG4
   [2a02:2350:5:104:1f:7559:53d7:166e]: 403

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

````

Currently, i'm at the step where i am able to access the Dashboard with ````http://captain.caprover1.mydomain.tld````

But, when i try to Enable HTTPS, i see the above error again.

Kindly advise how to proceed further. Thanks.

**Comment by githubsaturn** [comment]
This is simply a Let'sEncrypt error. Look at this part:
```
   Domain: captain.caprover1.mydomain.tld
   Type:   unauthorized
   Detail: Invalid response from
   http://captain.caprover1.mydomain.tld/.well-known/acme-challenge/Q-fFuQIse9cdHCRDEPbQThQyYkZ8Bqbx0K2_O3LOWG4
   [2a02:2350:5:104:1f:7559:53d7:166e]: 403
```

Potential issues:
- You DNS record hasn't been propagated. Wait 24 hour and try again.
- You haven't set up a proper A record for your DNS. Can you take a screenshot of your A record?

**Comment by arladmin** [comment]
@githubsaturn 

Regarding both these issues, are they still valid if a DNS check at MXTOOLBOX correctly shows the wildcard entry (something.caprover1.mydomain.tld) being correctly mapped to the server IP ?

**Comment by githubsaturn** [comment]
Yes.

**Comment by githubsaturn** [comment]
If both are correct, there is really no reason for Let's Encrypt to fail. Unless you did some customization to your CapRover (any custom routing, port mapping etc...)
