### ISSUE TITLE
Please clarify meaning for setup message "CapRover machine name..."

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#1011]
While it most certainly is verbose, it does not clearly indicate what it means:
```
? CapRover machine name, with whom the login credentials are stored locally
```

Could you please explain this in more detail?  Is this the name of my local workstation that's being used to setup CapRover on the remote server? Or is this the hostname of the remote CapRover server?

**Comment by githubsaturn** [comment]
It's a friendly name for you to remember your server name when you're deploying from your local machine.

You can call it `server123` if you want... It is only being used to reference that server on your own machine. 

You can change it by running `caprover logout` and `caprover login` again if you want....

Also, you can run `caprover login` on another machine and choose a different name.

**Comment by ylluminate** [comment]
Thanks appreciate that clarification. I guess it should just be called a "convenience alias" or such to convey intention further.
