### ISSUE TITLE
[Question] Expor/Import whone caprover configuration

### ISSUE THREAD

**Issue by alfeg** [caprover/caprover#1014]
Hello and thanks for awesome project.

I've done some setup for my own server, and then have a general question on how to reproduce this setup over time?

I'm very like the idea to put apps in git, and how Caprover deploy changes on those apps.
Now I want to put whole Caprover config to git.

Even simple export/import whole Caprover configuration will be enough for my home setup.

As far as I understand, only way to do it is to manually craft script using caprover-cli that will setup identical env

**Comment by githubsaturn** [comment]
Scripting the CLI works fine. But you can also read about backup and restore in the docs.
