### ISSUE TITLE
Edit Default Nginx Configuration Box doesnt close

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1017]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
When I press the Button to edit the Nginx Configuration I cant close it and it shows up forever

If applicable, content of `captain-definition` file:
Works everywhere

Steps to reproduce the problem:
Press Button "Edit default Nginx Configuration"
Edit something
Press Button "Save and Update"

intended behavior:
Hide the Box and show the Button to edit the Configuration again

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 20.04
- RAM? 4GB

**Comment by githubsaturn** [comment]
It's not supposed to close. It'll stay open because it's no longer using the default config. It's using your customized config.
