### ISSUE TITLE
Change Image Version after Installation

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1020]
I have installed Ackee as a OneClickApp and used the default version "2.3.0", then I noticed that the newest version is "3.0.3", so maybe I can change the Image Version, because it wouldnt matter. But I didnt find a way to change the Version.

This would be cool to add

**Comment by githubsaturn** [comment]
You can do that:
https://caprover.com/docs/one-click-apps.html#upgrading-one-click-apps
