### ISSUE TITLE
List in Disk cleanup [Dark Theme] - Not display properly while select all

### ISSUE THREAD

**Issue by chiragshahklc** [caprover/caprover#1021]
While using a dark theme it's hard to see the list in Disk cleanup section when all are selected.

![image](https://user-images.githubusercontent.com/27350823/108055312-d27faf80-7075-11eb-9087-c242bc68c957.png)

### Suggestion
Also dark feels so dark. I think you should change the dark colour to something like #202020

**Comment by githubsaturn** [comment]
Tagging @vitalragaz who worked on the Dark Mode feature.

**Comment by githubsaturn** [comment]
@chiragshahklc 
Not sure how you're seeing this issue. I just tried it on my instances and it seems to be working just fine.

You can try the demo instance: 
https://captain.server.demo.caprover.com   
**password** `captain42`

![image](https://user-images.githubusercontent.com/10582082/108071482-c541d100-7033-11eb-8fa4-a531f563048b.png)

**Comment by vitalragaz** [comment]
Confirming that I couldn't reproduce the bug on my environment. @chiragshahklc Maybe it can be a browser extension or a served cache of the scripts from the old version.

![image](https://user-images.githubusercontent.com/3964460/108072394-20d98200-7067-11eb-8e03-e4f39f408fb7.png)

**Comment by chiragshahklc** [comment]
@vitalragaz 
I reproduced it on your URL as well.
You need to tick check box left to `Image ID` so you will be able to select all images.

Ok, I will suggest theming suggestions on frontend project.
![image](https://user-images.githubusercontent.com/27350823/108075300-38793080-7090-11eb-8ad7-09475fe2207a.png)

**Comment by vitalragaz** [comment]
Thanks. For the reproduction steps. Just created a PR. The items are now shown as follow:

![image](https://user-images.githubusercontent.com/3964460/108078492-0c4cb800-706e-11eb-9a68-fa36733fe612.png)

**Comment by githubsaturn** [comment]
Thanks! We probably don't cut a hotfix for this as this is a minor issue. But it'll be bundled with the next release (hotfix or not).
