### ISSUE TITLE
[Question] Why is caprover frontend using cloudflare?

### ISSUE THREAD

**Issue by cattoshi** [caprover/caprover#1022]
I have noticed on the new release (1.9.0) that caprover frontend introduced a cloudflare cdn dependency. The frontend is able to load only if I allow my computer to connect to the cloudlfare cdn.

My question is, why making caprover frontend (the web management ui) depending on cloudflare instead of self hosting the library (less.min.js 37KB)? Since the caprover frontend is only to be accessed by a few admins why would we need a cdn.

I also wanted to see how can I opt out of cloudflare when using caprover since I never opted in to cloudflare when chosing caprover. Thanks in advance.

**Comment by githubsaturn** [comment]
Tagging @vitalragaz who worked on the Dark Mode feature.

**Comment by vitalragaz** [comment]
You are right, this is indeed not necessary and I wasn't supposed to create a dependency on Cloudflare. I will fix this in the next few hours.

**Comment by vitalragaz** [comment]
Created PR: https://github.com/caprover/caprover-frontend/pull/66

**Comment by githubsaturn** [comment]
Thanks! We probably don't cut a hotfix for this as this is a minor improvement, but it'll be bundled with the next release (hotfix or else)
