### ISSUE TITLE
[Question] Connect to another app/container during build?

### ISSUE THREAD

**Issue by conradfr** [caprover/caprover#1023]
Hi,

That may be a dumb question (I'm clearly not a Docker expert), is there a way to connect to another container during a build ?

For the context on a Php/Symfony project there is a "cache:clear" after a "composer install" (deps) and there is one lib trying to contact the redis instance and throwing a "host not found" error.

To make it works I have to move the "cache:clear" to the CMD / sh script which returns a 502 error until the command complete each time I deploy.

(FWIW the code is here https://github.com/conradfr/ProgRadio/tree/master/tools/docker/www)

**Comment by githubsaturn** [comment]
Depending on apps during the build is an anti-pattern and should be avoided. Build process should be done separately and in isolation. If you want to clear the cache during the application start up you can simply do something like this:
https://serverfault.com/questions/685697/multiple-commands-in-docker-cmd-directive/685758

**Comment by conradfr** [comment]
Sorry if I misunderstood your answer but it seems you're suggesting what I'm already doing and that is causing the 502 errors ?

Is my understanding correct that in CapRover "build" and "deployment" is basically the same thing and you have no control when you switch the active app container ?

Despite the name cache:clear is actually more of a build step with Symfony.

Thanks, I'll continue to investigate on my own.

One solution would be to expose the Redis instance and using the public IP which is not ideal from a security standpoint.

**Comment by conradfr** [comment]
For anyone reading this with the same problem I modified 
"cache:clear ": "symfony-cmd" to "cache:clear --no-optional-warmers": "symfony-cmd" in composer.json, which may suits your project or not.

**Comment by githubsaturn** [comment]
@conradfr  - looks like it's a common question: https://stackoverflow.com/questions/61331153/symfony-cacheclear-when-building-a-docker-container-or-when-running-it-first-ti

Regardless, you should think of your build step in an isolated way. You should be able to build your image on CI/CD pipeline. 


> Is my understanding correct that in CapRover "build" and "deployment" is basically the same thing and the user has no control over when you switch the active app container ?

Yes - when you deploy, one of the steps is "build"

**Comment by derek-adair** [comment]
> Regardless, you should think of your build step in an isolated way. You should be able to build your image on CI/CD pipeline.

Great points.  How would you suggest handling DB migrations during a deploy? Should these be done manually?

**Comment by githubsaturn** [comment]
It depends on your DB migration strategy and framework. If your DB migration script is safe to be called multiple times, you can simply change your CMD line to something like `ensure_db_migrated.sh && start_app.sh`

If on the other hand, your DB migration needs to be done once and only once, then it becomes more tricky. The ultimate goal is to make your migration script to be safe to be executed multiple times. One simple approach is to store the migration progress in a file, and only run the migration if that file doesn't exist, something like:

```bash
if [ ! -f /persistent-dir/db_migrated_v3 ]; then
    migrate_db_to_v3.sh && touch /persistent-dir/db_migrated_v3
fi
```
