### ISSUE TITLE
[Question] use arguments to docker run while deploying / mount a volume

### ISSUE THREAD

**Issue by benoib** [caprover/caprover#1024]
Hello,

I have been looking around but impossible to find how to simply mount a volume to my docker container, deployed via caprover.

I can't do this in the DockerFile given that I want to specify the host and container paths.

To be specific, what I'm asking is how to pass the docker run -v args, via caprover deploy.

Edit: I tried to do this with docker service update, but can't make it work either.

Thanks a lot.

**Comment by githubsaturn** [comment]
You can mount volumes using the UI: https://caprover.com/docs/persistent-apps.html

**Comment by benoib** [comment]
Thanks a lot. Indeed missed that!
