### ISSUE TITLE
Customize Nothing here yet :/ page

### ISSUE THREAD

**Issue by faierbol** [caprover/caprover#1025]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hi all,

How can i customize Nothing here yet :/ page? 
I want to add a custom 404 page

**Comment by faierbol** [comment]
Found it, is under captain/generated/static/default/index.html

**Comment by githubsaturn** [comment]
Generated directories are "generated" and get reset when CapRover resets. 

The proper way to do this is to create an html in nginx-shared directory and edit your root nginx config (in settings) to point to that file.

Read here: https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by faierbol** [comment]
Can you please give me an example of the nginx configuration? i have created an index.html file with custom html, placed it onto nginx-shared directory but i am having troubles editing the niginx inside CapRover Config Location in nginx container on the caprover panel.

**Comment by faierbol** [comment]
tried different configs:

        location / {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }

        error_page 404 /captain/data/nginx-shared/index.html;
        error_page 500 502 503 504 /captain/data/nginx-shared/custom.html;
    }

another example:

        location /captain/data/nginx-shared {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }

        error_page 404 index.html;
        error_page 500 502 503 504 custom.html;
    }

**Comment by faierbol** [comment]
and still the default Nothing here yet :/ page is displayed

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/135101100-1ef6c157-47c5-455b-9ba0-d5cc9d44f10a.png)
> Let's say you place a custom SSL cert in that folder and call it /captain/data/nginx-shared/custom-cert.pem. In order to reference that file in your nginx config, you'll use /nginx-shared/custom-cert.pem

* go to settings
* edit nginx config
* find this block
```
        location / {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /error_generic_catch_all.html;
```
and change it to 
```
        location / {
            root   /nginx-shared/catchall
            index  index.html;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /index.html;
```

Copy your new html file as `/captain/data/nginx-shared/catchall/index.html`

For example, simply run
echo "test" > /captain/data/nginx-shared/catchall/index.html

**Comment by jmuxfeldt** [comment]
[[githubsaturn](https://github.com/githubsaturn) ](https://github.com/githubsaturn) does show a new page, but if I use this technique, I can no longer add domains to my apps. I get a "verification failed"  error.  Any suggestions?

**Comment by githubsaturn** [comment]
Try this:
https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

**Comment by jmuxfeldt** [comment]
> Try this: https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

No, that's not the problem.  I am able to add domains to apps normally. Only if I make the global modification mentioned above, it fails: 
```
location / {
            root   /nginx-shared/catchall;
            index  index.html;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /index.html;
```

**Comment by githubsaturn** [comment]
Yes, I understand, just run these lines on your server and it should work
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by jmuxfeldt** [comment]
Ok, thanks, I'll give it a try.

**Comment by jmuxfeldt** [comment]
works
