### ISSUE TITLE
Editing a docker remote registry does not trigger an authentication check

### ISSUE THREAD

**Issue by simplytech** [caprover/caprover#1027]
### What is the problem?

When editing a registry, if I put the wrong username, password or domain, then Save and Update, I get what seems to be a successful notice saying "Registry updated". I think the authentication check is being incorrectly skipped when editing a registry (but correctly executed when adding a registry).

### Steps to reproduce the problem:

1. Click on **Cluster** on the left sidebar
2. Under **Docker Registries**, click **Add Remote Registry**
3. Enter any dummy invalid values in **Username**, **Password**, and **Domain**
4. Click on **Add Remote Registry** in the popup dialog box
5. I get a red notice saying `1112 : Athentication failed. Either username, password, or domain is incorrect.` (This is good and expected)
6. Under **Docker Registries**, click on **Add Remote Registry**
7. Enter valid values in **Username**, **Password**, and **Domain**
8. Click on **Add Remote Registry** in the popup dialog box
9. I get a green notice saying: `Docker registry successfully added!` (This is good and expected)
10. Now, under **Actions**, click the **Edit** icon for the registry you just added
11. Enter any dummy invalid values in **Username**, **Password**, and **Domain** 
12. Click on **Save and Update** in the popup dialog box
13. I get a green notice saying: `Registry updated.` (This is the bug. I expect to see the same authentication failure as in step 5 above)

### Answers to the following questions where applicable:
- CapRover version?
```
CapRover  1.9.0
```
- Your OS and version?
```
Digital Ocean droplet: caprover-ubuntu-s-1vcpu-1gb-tor1-01

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-132-generic x86_64)
  System information as of Sat Feb 20 00:25:38 UTC 2021

  System load:                    0.16
  Usage of /:                     50.5% of 24.06GB
  Memory usage:                   62%
  Swap usage:                     0%
  Processes:                      124

```
- RAM?

```
1 GB
```

**Comment by githubsaturn** [comment]
Thanks for reporting this!

Fixed here: https://github.com/caprover/caprover/commit/5e490a1384277c29b2938903c7e8e8ee464c59f5
