### ISSUE TITLE
How to deploy apps using sub folder rather than sub domain

### ISSUE THREAD

**Issue by thebreaktop** [caprover/caprover#1030]
I have 3 web apps on domain `app1.domain.com`, `app2.domain.com` and `app3.domain.com`. This is default caprover behaviour as each web app is given the domain `appName.domain.com`.

I'f I want another domain `app1.anotherdomain.com` to point to `app1.domain.com`, I can just set an `A record` and from caprover ui I can connect the domain.

Instead of using subdomain (like above), is there a way to sub folder e.g. `anotherdomain.com/app1` points to `app1.domain.com`.

Is it possible to instead of deploying apps using subdomain, use subdirectories. So instead of deploying apps on domain `app1.domain.com`, it would be `domain.com/app1`

I've had a look at the documentation but could not figure out how to deploy apps using subdirectory rather than subdomain.

**Comment by githubsaturn** [comment]
"sub folder" or routes are not DNS records. 

You can point `anotherdomain.com` to `app1` and manually edit your nginx config to rewrite the URL. It's not possible using the built in config, but nginx config is customizable and you can edit it however you want.

**Comment by thebreaktop** [comment]
Can you give an example of what you mean. How the config file would loom like.

Right now I have an `app1` on domain `app1.domain.com` which is set up by caprover.

What would I have to do so that `anotherdomain.com/app1` points to `app1.domain.com`

**Comment by githubsaturn** [comment]
It's not a very straightforward config. Honestly, if you're not very familiar with nginx config, it'd be better to stay away from it as you might break it. But here are the general things you need to do:
For this: 
> What would I have to do/what changes would I have to make so that anotherdomain.com/app1 points to app1.domain.com.

1- Create a new app and call it `proxy-layer`
2- Assign `anotherdomain.com` as a custom domain to this app.
3- Change your location such that it only listens for `/app1`
* add a trailing slash to $ value
* change `location /` to `location /app1/`
read here: https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass
