### ISSUE TITLE
[Deployment Issue] standard_init_linux.go:219 error on one-click Jitsi deployment

### ISSUE THREAD

**Issue by orcu** [caprover/caprover#1031]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

One click Jitsi deployment does not seem to work ( NGINX 502 Error :/  on web page). All 4 containers of Jitsi (jicofo, jvb, prosody, web) have successful build logs. However all of them outputs the following line continuously in the app logs:
```
...
2021-02-22T11:47:10.256509781Z standard_init_linux.go:219: exec user process caused: exec format error
2021-02-22T11:47:31.054547823Z standard_init_linux.go:219: exec user process caused: exec format error
2021-02-22T11:47:54.218800845Z standard_init_linux.go:219: exec user process caused: exec format error
...
```

Steps to reproduce the problem:
Install Jitsi through one-click apps

Answers to the following questions if applicable:
- Your OS and version?
- RAM?
Ubuntu 18.4, 2GB ram, armv7l

Could this be an arm-related error?

Great project by the way.

**Comment by githubsaturn** [comment]
Yes, see here: https://stackoverflow.com/a/64215125

Not all one click apps are built for all architectures.
