### ISSUE TITLE
I can't write into persistent folders; files already into that folder are ignored

### ISSUE THREAD

**Issue by GiuseppeLateral** [caprover/caprover#1033]
I've setup a php app following the documentation (php-apache with Gitlab CI CD)
Now I am mapping var/www/html to a specific folder on the host
I have two issues:
- I already have files inside var/www/html, for example index.php; when I do the mapping those files are ignored (it'like thery are not there anymore) and in fact if I try to reach the app I see an error from the webserver; the files work again if I remove the mapping, so I can again see my app
- If I try to write a file into the mapped folder I get an error; for example, doing file_put_contents inside the persistent folder fails

**Comment by githubsaturn** [comment]
This is a Docker question. Docker volumes behave this way. See here:
https://stackoverflow.com/questions/47664107/docker-mount-to-folder-overriding-content
and
https://docs.docker.com/engine/reference/builder/#volume

You can define a volume in your Dockerfile that might help with this:
```
FROM ....
....

VOLUME ["/var/www/html"]
CMD ....
```


Also, you probably have to use a named volume (not specify the path the host)
Not too sure about this. You have to check Docker docs.
