### ISSUE TITLE
[Deployment Issue] Docker run command

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1034]
I want to deploy the [Matrix Synapse Docker Server](https://hub.docker.com/r/matrixdotorg/synapse)
The Command to generate the config is this
```properties
docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
```
I created the Volume and the Enviroment Variables and the Deployed via ImageName.
The only problem is the Part after the Image the "Command" `generate`. How do I pass this Command so Caprover knows what to do?

**Comment by githubsaturn** [comment]
You can either run this directly on your server manually (make sure you change your volume to be the correct volume)

Or you can do this via CapRover (slightly more complex):
- Create a dummy app with persistent data
- Set up volume and environmental variable
- Under deployment tab, deploy via Dockerfile and use this dockerfile:
```
FROM matrixdotorg/synapse:latest
CMD generate
```
Once it's deployed, you can remove the app (do not remove the volume).

**Comment by kaaax0815** [comment]
@githubsaturn Thanks for the answer. The problem now is `Unknown execution mode '/bin/sh'` and it seems like it didnt create a container

**Comment by githubsaturn** [comment]
What method did you use? And what do you mean by " it didnt create a container" ?

**Comment by kaaax0815** [comment]
I created a peristent app and copied the dockerfile thing into the dockerfile thing. When doing `docker container ls` I cant see the Docker Container with the right Image

**Comment by githubsaturn** [comment]
`docker container ls` didn't show any container because `generate` is a transient command. The container got generated and got killed immediately. This is totally expected.
