### ISSUE TITLE
[Question] Cloud hosted logging

### ISSUE THREAD

**Issue by petrovalex** [caprover/caprover#1036]
Hello,

Could you please give a hint on how to push logs to cloud-hosted log management systems, for example to Papertrail?

Thank you.

**Comment by githubsaturn** [comment]
There is nothing specific about CapRover when it comes to logging.

For papertrail for example 
1- you can use their official [Docker aggregation image](https://documentation.solarwinds.com/en/Success_Center/papertrail/Content/kb/configuration/configuring-centralized-logging-from-docker.htm)

2- Or, you can just emit the logs directly from your code, [example NodeJS code](https://documentation.solarwinds.com/en/Success_Center/papertrail/Content/kb/configuration/configuring-centralized-logging-from-nodejs-apps.htm#send-events-from-nodejs).
