### ISSUE TITLE
Accuracy of NetData monitor results?

### ISSUE THREAD

**Issue by rylax** [caprover/caprover#1039]
Hello,

I have set up up CapRover on a Digital Ocean droplet (1CPU 2GB RAM) and try to monitor the CPU and RAM – especially during Docker builds. They take up quite some amount of resources.

According to NetData almost 100% CPU and around 91% RAM at peak build. However, after checking the DigitalOcean built in advanced metrics I saw that CPU mainly showed around 51% and RAM around 60% usage. 

I am now trying to find out which one I should trust more and what your thoughts are on this?

**Comment by maietta** [comment]
I believe you should be addressing this topic over at [https://github.com/netdata/netdata](https://github.com/netdata/netdata).

**Comment by rylax** [comment]
I thought it might have something todo with the virtualisation process but you are right. I also SSHed and cross-checked with `htop`. Results are pretty similar to NetData. It seems that the report from Digital Ocean is not that accurate. Seems they are still in beta, so that might be it.

**Comment by githubsaturn** [comment]
I think they both use [/proc/stat](http://www.linuxhowtos.org/System/procstat.htm)  - but they might be averaging differently. You can reach out to them to ask for details if you're interested.
