### ISSUE TITLE
Deploy failed due to dockerfile

### ISSUE THREAD

**Issue by designermonkey** [caprover/caprover#1041]
What is the problem?

```
Deploy failed!
Error: ENOENT: no such file or directory, open '/my-project/temp/image_raw/stg/1/source_files/DockerFile'
```

Using a `Dockerfile` as named in the [docker documentation](https://docs.docker.com/engine/reference/builder/) makes the build break as Caproer is looking specifically for a `DockerFile` on a case sensitive filesystem.

Steps to reproduce the problem:

Use a `Dockerfile` in your project as aposed to `DockerFile`.

Answers to the following questions where applicable:
- Ubuntu 20.04

**Comment by githubsaturn** [comment]
Do you have a `captain-definition` file? What is the content of the file?

**Comment by designermonkey** [comment]
```
{
  "dockerfilePath": "./DockerFile",
  "schemaVersion": 2
}
```

Interesting. That was autocompleted when typed. Would it be possible to normalise this in caprover to make sure it avoids silly mistakes like mine?

**Comment by githubsaturn** [comment]
If you use the normal docker file you don't even need to define a captain definition. 

if you define a captain definition it means that you are working with a very specific spelling of your docker file

**Comment by designermonkey** [comment]
Ok, thanks for the pointer, it's not clear in the docs that that is the case.
