### ISSUE TITLE
Hashing of Private Keys

### ISSUE THREAD

**Issue by designermonkey** [caprover/caprover#1042]
I would like to utilise Caprover in our infrastructure automation to allow the designers and marketers in the company to deploy sites quickly. Because of this and our use of private repositories, I need to be able to automate the app configuration to some degree.

I have found the config file, and can see that the private keys are encrypted.

Is a command available on a cli to encrypt a value using the same algorithm you use? If so I would be able to run this in ansible to generate app configuration.

**Comment by githubsaturn** [comment]
There is a generic `caprover api` [command](https://github.com/caprover/caprover-cli#api) that essentially allows you to send any API request.

What you want is a POST request to `user/apps/appDefinitions/update` endpoint. You can simply inspect network in your browser to see the request content.

**Comment by designermonkey** [comment]
Thanks. Is there any upcoming api documentation?

**Comment by githubsaturn** [comment]
Not anytime soon - unless someone from community build one.

The API is simply enough that Network Inspector plus the [ApiManager class](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts) make it easy to understand the basics.
