### ISSUE TITLE
caprover docker first run silently fails and container restart fails with: This node is already part of a swarm

### ISSUE THREAD

**Issue by allanlaal** [caprover/caprover#1043]
What is the problem?
I'm using a fresh vps instance with Ubuntu 18.04.5 LTS and docker 19.03.6 following the official installation, but caprover install fails with: This node is already part of a swarm

### If applicable, content of `captain-definition` file:

tried with empty and with `{"skipVerifyingDomains":"true"}`

re-emergence of #568, but on the recommended Ubuntu distro

### Steps to reproduce the problem:

follow the steps in https://caprover.com/docs/get-started.html#step-1-caprover-installation
and then:

root@vps:~# cat /etc/issue
	Ubuntu 18.04.5 LTS \n \l

	root@vps:~# aptitude install docker.io
	The following NEW packages will be installed:
	  bridge-utils{a} cgroupfs-mount{a} containerd{a} dns-root-data{a} dnsmasq-base{a} docker.io netcat{a} netcat-traditional{a} pigz{a} 
	  runc{a} ubuntu-fan{a} 
	0 packages upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
	Need to get 0 B/64.2 MB of archives. After unpacking 320 MB will be used.
	Do you want to continue? [Y/n/?] y
	Preconfiguring packages ...              
	Selecting previously unselected package pigz.
	(Reading database ... 34229 files and directories currently installed.)
	Preparing to unpack .../00-pigz_2.4-1_amd64.deb ...
	Unpacking pigz (2.4-1) ...
	Preparing to unpack .../01-bridge-utils_1.5-15ubuntu1_amd64.deb ...
	Unpacking bridge-utils (1.5-15ubuntu1) ...
	Preparing to unpack .../02-cgroupfs-mount_1.4_all.deb ...
	Unpacking cgroupfs-mount (1.4) ...
	Selecting previously unselected package runc.
	Preparing to unpack .../03-runc_1.0.0~rc10-0ubuntu1~18.04.2_amd64.deb ...
	Unpacking runc (1.0.0~rc10-0ubuntu1~18.04.2) ...
	Preparing to unpack .../04-containerd_1.3.3-0ubuntu1~18.04.4_amd64.deb ...
	Unpacking containerd (1.3.3-0ubuntu1~18.04.4) ...
	Selecting previously unselected package dns-root-data.
	Preparing to unpack .../05-dns-root-data_2018013001_all.deb ...
	Unpacking dns-root-data (2018013001) ...
	Preparing to unpack .../06-dnsmasq-base_2.79-1ubuntu0.3_amd64.deb ...
	Unpacking dnsmasq-base (2.79-1ubuntu0.3) ...
	Selecting previously unselected package docker.io.
	Preparing to unpack .../07-docker.io_19.03.6-0ubuntu1~18.04.3_amd64.deb ...
	Unpacking docker.io (19.03.6-0ubuntu1~18.04.3) ...
	Selecting previously unselected package netcat-traditional.
	Preparing to unpack .../08-netcat-traditional_1.10-41.1_amd64.deb ...
	Unpacking netcat-traditional (1.10-41.1) ...
	Selecting previously unselected package netcat.
	Preparing to unpack .../09-netcat_1.10-41.1_all.deb ...
	Unpacking netcat (1.10-41.1) ...
	Preparing to unpack .../10-ubuntu-fan_0.12.10_all.deb ...
	Unpacking ubuntu-fan (0.12.10) ...
	Setting up runc (1.0.0~rc10-0ubuntu1~18.04.2) ...
	Setting up dns-root-data (2018013001) ...
	Setting up netcat-traditional (1.10-41.1) ...
	update-alternatives: using /bin/nc.traditional to provide /bin/nc (nc) in auto mode
	Setting up cgroupfs-mount (1.4) ...
	Setting up containerd (1.3.3-0ubuntu1~18.04.4) ...
	Setting up bridge-utils (1.5-15ubuntu1) ...
	Setting up netcat (1.10-41.1) ...
	Setting up dnsmasq-base (2.79-1ubuntu0.3) ...
	Setting up pigz (2.4-1) ...
	Setting up docker.io (19.03.6-0ubuntu1~18.04.3) ...
	Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
	docker.service is a disabled or a static unit, not starting it.
	Setting up ubuntu-fan (0.12.10) ...
	Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
	Processing triggers for dbus (1.12.2-1ubuntu1.2) ...
	Processing triggers for systemd (237-3ubuntu10.44) ...
		                       
		                                     
	root@vps:~# docker --version
	Docker version 19.03.6, build 369ce74a3c

	root@vps:~# docker run --name caproverd -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover && docker attach caproverd
	Unable to find image 'caprover/caprover:latest' locally
	latest: Pulling from caprover/caprover
	1e987daa2432: Pull complete 
	a0edb687a3da: Pull complete 
	6891892cc2ec: Pull complete 
	684eb726ddc5: Pull complete 
	b0af097f0da6: Pull complete 
	154aee36a7da: Pull complete 
	01e6b0c72136: Pull complete 
	42cbb8df654e: Pull complete 
	9c969f3ebb14: Pull complete 
	623357ef4ba2: Pull complete 
	41f99b50dd8d: Pull complete 
	ff9ca6a81865: Pull complete 
	6ae746d526f8: Pull complete 
	Digest: sha256:84a24b6a814df9572f512a42109e8c0f0797f7f7625dc3349dfe4d3f83566eaa
	Status: Downloaded newer image for caprover/caprover:latest

	> caprover@0.0.0 start /usr/src/app
	> node ./built/server.js

	Captain Starting ...
	Installing Captain Service ...
		 
	 Installation of CapRover is starting...     
	For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
		 
		 
	 
	 
	 
	 >>> Checking System Compatibility <<<
	   Docker Version passed.
	   Ubuntu detected.
	   X86 CPU detected.
	   Total RAM 2147 MB
	Pulling: nginx:1
	Pulling: caprover/caprover-placeholder-app:latest
	Pulling: caprover/certbot-sleeping:v1.6.0
	March 5th 2021, 7:44:13.373 pm    Fresh installation!
	March 5th 2021, 7:44:13.376 pm    Starting swarm at MY_REDACTED_VPS_IP:2377
	Swarm started: tkoriwi3zxxskbyag6wzsz5kr
	*** CapRover is initializing ***
	Please wait at least 60 seconds before trying to access CapRover.

	# this is where && docker attach caproverd kicks in:
	You cannot attach to a stopped container, start it first

	root@vps:~# docker ps -a
	CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS               NAMES
	363c57cd24c0        caprover/caprover   "docker-entrypoint.s…"   About a minute ago   Exited (0) About a minute ago                       caproverd
	root@vps:~# docker logs 363c57cd24c0

	> caprover@0.0.0 start /usr/src/app
	> node ./built/server.js

	Captain Starting ...
	Installing Captain Service ...
		 
	 Installation of CapRover is starting...     
	For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
		 
		 
	 
	 
	 
	 >>> Checking System Compatibility <<<
	   Docker Version passed.
	   Ubuntu detected.
	   X86 CPU detected.
	   Total RAM 2147 MB
	Pulling: nginx:1
	Pulling: caprover/caprover-placeholder-app:latest
	Pulling: caprover/certbot-sleeping:v1.6.0
	March 5th 2021, 7:44:13.373 pm    Fresh installation!
	March 5th 2021, 7:44:13.376 pm    Starting swarm at MY_REDACTED_VPS_IP:2377
	Swarm started: tkoriwi3zxxskbyag6wzsz5kr
	*** CapRover is initializing ***
	Please wait at least 60 seconds before trying to access CapRover.

	# so it seems to have silently died here

	root@vps:~# docker start caproverd && docker attach caproverd
	caproverd

	> caprover@0.0.0 start /usr/src/app
	> node ./built/server.js

	Captain Starting ...
	Installing Captain Service ...
		 
	 Installation of CapRover is starting...     
	For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
		 
		 
	 
	 
	 
	 >>> Checking System Compatibility <<<
	   Docker Version passed.
	   Ubuntu detected.
	   X86 CPU detected.
	   Total RAM 2147 MB
	Pulling: nginx:1
	Pulling: caprover/caprover-placeholder-app:latest
	Pulling: caprover/certbot-sleeping:v1.6.0
	March 5th 2021, 7:46:35.506 pm    Fresh installation!
	March 5th 2021, 7:46:35.508 pm    Starting swarm at MY_REDACTED_VPS_IP:2377
	Error: (HTTP code 503) unexpected - This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one. 
		at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
		at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:331:7)
		at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:300:5)
		at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:275:14)
		at IncomingMessage.emit (events.js:327:22)
		at endReadableNT (internal/streams/readable.js:1327:12)
		at processTicksAndRejections (internal/process/task_queues.js:80:21) {
	  reason: undefined,
	  statusCode: 503,
	  json: {
		message: 'This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.'
	  }
	}
	Installation failed.

### Answers to the following questions where applicable:

Ubuntu 18.04.5 LTS
Docker version 19.03.6, build 369ce74a3c
   X86 CPU detected.
   Total RAM 2147 MB

### Notes:

looks similar to #568, but this time its on Ubuntu

**Comment by githubsaturn** [comment]
Run `docker service ps captain-captain --no-trunc`

**Comment by allanlaal** [comment]
`
root@my-vps.domain:~# docker service ps captain-captain --no-trunc
	ID                          NAME                    IMAGE                     NODE                DESIRED STATE       CURRENT STATE                     ERROR                                                                                                                                                                 PORTS
	b98pydxruhe20aodjdtz2cpev   captain-captain.1       caprover/caprover:1.9.0   my-vps.domain.ee        Ready               Rejected less than a second ago   "error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"   
	eayrn95bdx0el9qlgi5lk57tn    \_ captain-captain.1   caprover/caprover:1.9.0   my-vps.domain.ee        Shutdown            Rejected 5 seconds ago            "error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"   
	20h49a4dfh4t65d1nyzmtdc1r    \_ captain-captain.1   caprover/caprover:1.9.0   my-vps.domain.ee        Shutdown            Rejected 10 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"   
	bc1i4h964i285naxq6uhxwrvd    \_ captain-captain.1   caprover/caprover:1.9.0   my-vps.domain.ee        Shutdown            Rejected 15 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"   
	x12b8vknk8en9nij1j7a5v8p0    \_ captain-captain.1   caprover/caprover:1.9.0   my-vps.domain.ee        Shutdown            Rejected 19 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"
`

**Comment by allanlaal** [comment]
the vps is a Virtuozzo OpenVZ container - perhaps this is conflicting with dockers network overlays or sth?

**Comment by githubsaturn** [comment]
Ah looks like you have some network interface / iptable issues. See here https://github.com/moby/moby/issues/24809

**Comment by allanlaal** [comment]
thank you @githubsaturn ! :)

this seems like a fringe issue not worth the time for me, I'll give dokku a try for now
