### ISSUE TITLE
Temporary open the port for let's encrypt verification

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1044]
Hello, I checked the forum and googled it, but didn't find an answer, so decided I better check with you: I need in one particular setup all of the public traffic to be disabled, so that the server is not visible for the outside world.

That means that at some point in time (in a month, I guess) my Let's Encrypt SSL certificate will expire, causing troubles.

Is there any way, I can add some rule to the process, taking care of the certificate renewal, to do `sudo ufw allow proto tcp on ens3 from any to any port 80,443` and then removing this rule, after the renewal is done?

If not at all (which would be sad), is there any way I can manually provoke/invoke this process, so that I will create some bash script and put in cron?

Any help would be much appreciated!

**Comment by githubsaturn** [comment]
To renew certs you can simply shell into `captain-certbot` container and run `certbot renew` command.

Cert renewals are tried everyday, but it's to avoid random failures, you can probably get away with every two weeks or so.

**Comment by alexander-potemkin** [comment]
Thank you very much.
One more final thing: is there any way to get notified via any means on the certificate expiration? Or any command that I can use to get this date?

**Comment by githubsaturn** [comment]
You can just simply connect to the https://your_address and read the SSL info. This is doable. For example, Chrome does this:

![image](https://user-images.githubusercontent.com/10582082/110716022-5855cd00-81d4-11eb-86e2-0f9b7900a8a8.png)


---------

Alternatively, you can shell into `captain-certbot` and run `certbot certificates`

**Comment by alexander-potemkin** [comment]
Thank you!

**Comment by alexander-potemkin** [comment]
Found a one-liner to do that, sharing in case if someone would benefit from it:

`sudo docker exec -it `sudo docker ps --filter name=certbot -q` /usr/local/bin/certbot renew`
