### ISSUE TITLE
One click Apps list empty

### ISSUE THREAD

**Issue by WillyRL** [caprover/caprover#1046]
Hi, 
Anyone ever got the same problem? the one click apps seems empty

when i try to access it directly through http://mycaprover:3000/api/v2/user/oneclick/template/list, i got something like this : 

```
{
  "status": 1102,
  "description": "Empty namespace",
  "data": {}
}

```
![image](https://user-images.githubusercontent.com/11781111/110644915-23ec0c00-81e8-11eb-988d-8d15a84b2d48.png)

I'm using Ubuntu 18.04 and EC2 from AWS.

Thank You.

**Comment by githubsaturn** [comment]
View your CapRover server logs. What does it say?

**Comment by WillyRL** [comment]
Hi @githubsaturn,

It said something like this. 

```
| March 10th 2021, 6:12:45.830 pm    Error: getaddrinfo EAI_AGAIN api.v2.caprover.com
| Error: getaddrinfo EAI_AGAIN api.v2.caprover.com
|     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
| GET /api/v2/user/system/versioninfo 304 20024.222 ms - -
```

**Comment by WillyRL** [comment]
Problem Solved.
The issue is DNS Configuration on my VPC, and its now working as expected.

Thank You.
