### ISSUE TITLE
[Question] How to move files to persistent directory on deploy?

### ISSUE THREAD

**Issue by uncvrd** [caprover/caprover#1048]
Hi! I would like to deploy an analytics service called [cubejs](https://cube.dev/), of which they provide a docker image. One issue I'm experiencing with deploying to Caprover is that they require the following `docker run` command:

```
docker run --rm \
  --name cubejs-docker-demo \
  --volume "$(pwd):/cube/conf" \
  <YOUR-USERNAME>/cubejs-docker-demo
```
Which appears to transfer files from the current working directory to the `/cube/conf` directory. I've set up a caprover persistent directory with a path of `/cube/conf` and tagged it `analytics-dev-conf`. I am curious how I can perform this volume file transfer action using deployment from caprover since there are no flags I can set? I deploy with the following dockerfile ([per their docs](https://cube.dev/docs/deployment/guide#docker-docker-compose)):

```
FROM cubejs/cube:latest
COPY . .
RUN npm install
```

Nothing too complex. Any guidance would be appreciated, thank you!

**Comment by githubsaturn** [comment]
What do you mean by "volume file transfer" here?

- Are your files sitting on your local machine or on server?
- Do you have to create this volume manually?

You don't need to create a volume separately. Once you create an app, and attach a volume, the volume will be created for you. Note that CapRover volumes are prefixed with `captain--` . So if you create a volume on CapRover that is called `test`, when you run `docker volume ls` you will see it as `captain--test`

**Comment by uncvrd** [comment]
@githubsaturn Let me try to clarify:

- I have a local nodejs project that contains a Dockerfile with the instructions added above for deployment.
- I create a caprover app called `analytics`, define a persistent directory at `/cube/conf` in the app settings on caprover
- In the cli on my local, I run `caprover deploy` inside my project directory which runs the Dockerfile instructions and deploys it to my caprover project

How am I to instruct caprover to reference the root repository of my code and make it accessible to the persistent directory at `cube/conf` within the docker container? This would be accomplished by the following when running the container:

`docker run -v .:/cube/conf`

This might be important...

If memory serves me right, I cd'd in to `/var/lib/docker/volumes/my-persistent-directory-tagname/_data` last night and it did show the the local files in the `_data` directory as expected, but i forgot to deploy an extra `json` file with the project, so I deleted the files inside `_data` and redeployed the app using `caprover deploy` but the files do not show up after deployment like I figured they would. 

Does that help clarify the problem?

**Comment by githubsaturn** [comment]
I think I understand your use case. Check with Cube.js folks, but from what you said, It looks like `docker run -v ...` is a local command to run your instance locally on your own machine to test it out. For pushing it to the server, you shouldn't define any volumes.

To be more specific, volumes are used if your application makes some changes to a directory during its runtime, and you want to make sure that the content won't get deleted when you re-deploy your application.

For example, if you're uploading images and your app stores images in `/upload-files` directory, you would add this directory as a volume.


But in your case, it looks like you want to make some edits to some files. Then deploy the application, and you want your new changes to show up in your image. In this case, you shouldn't use volumes. Just have this Dockerfile and you'll be all set:

```Dockerfile
FROM cubejs/cube:latest

COPY . .
RUN npm install
```

**Comment by uncvrd** [comment]
That's the exact situation - thanks for clarifying and for sharing some of your time to resolve this
