### ISSUE TITLE
How to specify the Stop Grace Period during a deploy?

### ISSUE THREAD

**Issue by xojoc** [caprover/caprover#1050]
In one of my apps I have a Celery instance running and some tasks may take some time to finish.
Is there any way to pass the `--time` parameter to [docker stop](https://docs.docker.com/engine/reference/commandline/stop/) or the `--stop-grace-period` parameter to [docker service update](https://docs.docker.com/engine/reference/commandline/service_update/) when deploying?

CapRover doesn't seem to support all the options of [Docker Compose](https://caprover.com/docs/docker-compose.html) (in this case I need the [`stop_grace_period`](https://docs.docker.com/compose/compose-file/compose-file-v3/#stop_grace_period) one) and the [Service Update Schema](https://caprover.com/docs/service-update-override.html) doesn't seem to provide a similar parameter.

P.S.: thank you for this project, seems well done and easy to  use.

**Comment by githubsaturn** [comment]
You can update your service using plain Docker CLI. CapRover doesn't change the values that are updated using CLI.
For example you can do 
```
docker service update srv-captain--yourappname --stop-grace-period 60s 
```

Another option is to use [Service Update Override](https://caprover.com/docs/service-update-override.html). This is similar to the CLI solution, but you'll get to define everything within CapRover.

**Comment by xojoc** [comment]
I managed to do it by using the Service Update Override:
```
{
"TaskTemplate": {
    "ContainerSpec": {
         "StopGracePeriod": 300000000000
     }
  }
}
````

Thanks
