### ISSUE TITLE
504 Gateway Time-out after 60 seconds

### ISSUE THREAD

**Issue by maxvia87** [caprover/caprover#1051]
Hello, 

I have a rails app connected to a one click Postgres app. The problem I am facing is that I send a post request (using postman) to my rails app, it is doing some scraping that takes over 1 minute to execute and after 1 minutes I receive a "504 Gateway Time-out" error. 
In the background every thing is working fine, the scraping is done and data is persisted to my db but I would like to avoid the server sending me back a time out error. Locally I do not have this problem. 
Any idea what is happening and how I could prevent that?

Thank you !

**Comment by githubsaturn** [comment]
You can edit your app's nginx config to allow for a longer timeout.

- Login to CapRover on web
- Go to your app
- Click on Edit Nginx Config
- Find this part :
```
        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>
```

Change it to:
```

        location / {

            proxy_read_timeout 120s; #### <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>
```

**Comment by maxvia87** [comment]
This is great. Thank you so much!!
