### ISSUE TITLE
[Question] Hidden Service

### ISSUE THREAD

**Issue by kaaax0815** [caprover/caprover#1052]
Can I create a Hidden Service with CapRover? A [Hidden Service](https://en.wikipedia.org/wiki/Tor_(anonymity_network)#Onion_services) is a Onion Address for the Tor Browser. I can use Tor and Nginx but that would use Port 80 which is used by Caprover

**Comment by githubsaturn** [comment]
What's a hidden service?

**Comment by kaaax0815** [comment]
@githubsaturn I edited my question. If you didn't see

**Comment by githubsaturn** [comment]
I didn't see the edit.

Regarding the onion service, there's nothing specific to CapRover. If you can deploy it using docker, you should be okay with CapRover generally. See this for example https://github.com/cmehay/docker-tor-hidden-service
