### ISSUE TITLE
[Question] Is there a way to reuse an existing MongoDB app in a new "one-click" Parse app ?

### ISSUE THREAD

**Issue by ostrebler** [caprover/caprover#1053]
Hello, well everything is in the title. I'm new to CapRover and quite like it so far.
When I create a new Parse app, using one-click creation, it actually creates three apps : MongoDB, Parse and Parse Dashboard.

What if I already have a MongoDB app ? How can I tell my parse app to use it ? Thank you !

**Comment by githubsaturn** [comment]
There are multiple ways to do that. 
- You can take the template and just modify the template such that it does not create a new mongodb container
- Or you can create a new Parse app, then change the env vars to point to another mongodb instance, then remove the unwanted instance.
