### ISSUE TITLE
Docker container periodic restart

### ISSUE THREAD

**Issue by Nauman3S** [caprover/caprover#1055]
**Problem**
I am running a web scrapper using selenium with chromedriver as a docker container using caprover. The issue is regarding memory and processor usage with keeps on increasing incrementally with chromium inside the container and eventually breaks everything and I have to restart my server to return it back to normal usage. To avoid this issue I restart that specific container every 24 hours.

**Solution**
1)There should be a restart button in caprover just like we have in portainer
2)There should be an automatic restart section that allows restarting the container after the specified time interval.
This could eventually become a USP for caprover as I haven't see such a feature-set in any other platform.

**alternatives that I have considered**
For now, I manually restart the container or use portainer to restart it.

**Comment by githubsaturn** [comment]
> 2)There should be an automatic restart section that allows restarting the container after the specified time interval.
This could eventually become a USP for caprover as I haven't see such a feature-set in any other platform.

This one sounds like an issue specific to your application. 

> 1)There should be a restart button in caprover just like we have in portainer

This is already doable. Just click on `Update and Save` button
