### ISSUE TITLE
'Persist' login session separate for every domain

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1056]
It would be really nice if CapRover would 'persist' login session for every domain separately. I'm currently juggling quite a few instances and every time I login in to one, it logs me out of every others (all on separate domains), which is quite annoying.

Any hints/fixes would be much appreciated here!

**Comment by githubsaturn** [comment]
What are the repro steps? I've tried it and it works fine:
- Login to `captain.domain1.com` and select "Use localStorage (Most Persistent)"
- Open a new tab and login to login to `captain.domain2.com` and select "Use localStorage (Most Persistent)"
- Now go back to the first tab and refresh the logged in page on `captain.domain1.com`
- I see that it keeps me logged in. 

Do you see a different behavior?

**Comment by githubsaturn** [comment]
Feel free to reopen if you're still experiencing this issue.

**Comment by alexander-potemkin** [comment]
I would. Apologize for the delay in getting back to you - needs some more time to reproduce.

**Comment by alexander-potemkin** [comment]
<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/2323840/129063784-1036c25c-1c78-4e76-966b-59a5f88e7c4e.png">

I finally got my hands on here, sorry it took so long.

The way it's actually happen is this:
- I open my page, expecting to see admin page
- instead I see the page as per screenshot attached
- I try to click on various pages, but I get more notifications on something bad
- I logout and re-login and everything works like a charm

@githubsaturn , if that's not enough - please, let me know what else I can provide in here?

**Comment by maietta** [comment]
I had a similar issue with Safari on iPad. I didn't have the time to investigate it though but now that I am seeing this issue with the same browser and OS, I am wondering if this is an issue with the front-end on Safari under iOS.

**Comment by githubsaturn** [comment]
Can you reproduce this with the demo site? 

- Go to https://captain.server.demo.caprover.com 
- Choose the last option "Use localStorage (Most Persistent)"
- Enter `captain42` as the password and login
- Close your browser
- Reopen your browser
- Go back to the URL: https://captain.server.demo.caprover.com 

Does it work?

**Comment by githubsaturn** [comment]
Actually I was able to find the issue. 

It is caused when your CapRover service restarts under the hood. In that case, your previous auth token gets invalidated but you are never thrown to logged out page. I fixed this issue in this commit: https://github.com/caprover/caprover-frontend/commit/12d7268e95d51a44b8dc70c5e536995f8aab28fe

It should be available in 1.10.0 release soon

**Comment by alexander-potemkin** [comment]
Yeah, token invalidation sounds just right. Thank you very much, looking forward to update my instances to enjoy this issue fixed :)
