### ISSUE TITLE
HTTPS - non "Let's Encrypt" support

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#1057]
Background:
Currently testing two hosts, behind a NAT to test swarm/cluster. But I can't because of HTTPS.... and because Let's Encrypt is making things difficult. Otherwise, SSL self-signed certs and CloudFlare is adequate for my current need

Can you please stop forcing me to use Let's Encrypt when I am using CloudFlare's HTTPS features?
I'm struggling to enable HTTPS because of the current implementation not being flexible around how I have to set it up:

```
1107 : Unexpected output when enabling SSL forcaptain.captain2.cornerstep.co.uk with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None Obtaining a new certificate Performing the following challenges: http-01 challenge for captain.captain2.cornerstep.co.uk Using the webroot path /captain-webroot/captain.captain2.cornerstep.co.uk for all unmatched domains. Waiting for verification... : 404 To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
```

FYI, here's some logs:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: captain.captain2.cornerstep.co.uk
   Type:   unauthorized
   Detail: Invalid response from
   http://captain.captain2.cornerstep.co.uk/.well-known/acme-challenge/-PQpoI5R_USDfcGOl0F4_FdxUcg_YQUmeNt5DvlKStw
   : 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

March 21st 2021, 7:27:02.186 pm    Error: Unexpected output when enabling SSL forcaptain.captain2.cornerstep.co.uk with ACME Certbot 
 Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for captain.captain2.cornerstep.co.uk
Using the webroot path /captain-webroot/captain.captain2.cornerstep.co.uk for all unmatched domains.
Waiting for verification...
Challenge failed for domain captain.captain2.cornerstep.co.uk
http-01 challenge for captain.captain2.cornerstep.co.uk
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: captain.captain2.cornerstep.co.uk
   Type:   unauthorized
   Detail: Invalid response from
   http://captain.captain2.cornerstep.co.uk/.well-known/acme-challenge/-PQpoI5R_USDfcGOl0F4_FdxUcg_YQUmeNt5DvlKStw
   : 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

Error: Unexpected output when enabling SSL forcaptain.captain2.cornerstep.co.uk with ACME Certbot 
 Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for captain.captain2.cornerstep.co.uk
Using the webroot path /captain-webroot/captain.captain2.cornerstep.co.uk for all unmatched domains.
Waiting for verification...
Challenge failed for domain captain.captain2.cornerstep.co.uk
http-01 challenge for captain.captain2.cornerstep.co.uk
Cleaning up challenges
Some challenges have failed.
```

Using:
```
docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh
```
I am able to curl captain.

**Comment by githubsaturn** [comment]
Not sure what you're trying to achieve here. When you click "Enable HTTPS", here is what it means:
- Obtain SSL certs from LetsEncrypt
- Start listening on port 443 with SSL certs obtained in step 1.

If you want to use self sign SSL, you should use Enable HTTPS built in functionality. You can manually edit nginx config. See here for more details:
https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by voarsh2** [comment]
> Not sure what you're trying to achieve here. When you click "Enable HTTPS", here is what it means:
> 
> * Obtain SSL certs from LetsEncrypt
> * Start listening on port 443 with SSL certs obtained in step 1.

Yes, I get errors (404 specifically from CapRover about that)




> * 
> 
> If you want to use self sign SSL, you should use Enable HTTPS built in functionality. You can manually edit nginx config. See here for more details:
> https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

Any way to just.... let's CloudFlare handle this? Bit of a pain to go through these hoops for some testing.....

**Comment by githubsaturn** [comment]
> Any way to just.... let's CloudFlare handle this? Bit of a pain to go through these hoops for some testing.....

What do you want your architecture to look like? Do you want something like this:

```
         https                   http
User <===========> CloudFlare <========> CapRover
```

**Comment by voarsh2** [comment]
> What do you want your architecture to look like? Do you want something like this:
> 
> ```
>          https                   http
> User <===========> CloudFlare <========> CapRover
> ```

Would certainly make it easier to do some testing.
I've no idea why Let's Encrypt gets 404 when trying to do the challenge.....

**Comment by voarsh2** [comment]
> If you want to use self sign SSL, you should use Enable HTTPS built in functionality. You can manually edit nginx config. See here for more details:
> https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

Just to clarify, if I make a self signed certificate, I completely bypass the issue around using Let's Encrypt?

**Comment by githubsaturn** [comment]
> Would certainly make it easier to do some testing.
I've no idea why Let's Encrypt gets 404 when trying to do the challenge.....

You still didn't answer my question. Do you want the architecture that I plotted above? 
If yes, you do not need to enable HTTPS with CapRover. "Enable HTTPS" button literally means "Enable HTTPS using Let's Encrypt Certificate"

**Comment by voarsh2** [comment]
Also, DNS text confirmation would make things easier:
certbot certonly --manual \
  --preferred-challenges=dns \
  --email xxxxx \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --agree-tos \
  --manual-public-ip-logging-ok \
  -d "*.cornerstep.co.uk"

**Comment by voarsh2** [comment]
> You still didn't answer my question. Do you want the architecture that I plotted above?

That would be the easiest, yes.
But if you're going to say "no", then an easier Let's Encrypt confirmation of adding text to my CloudFlare DNS for their authentication, or something like, that would be easier

**Comment by githubsaturn** [comment]
> That would be the easiest, yes.

Okay then, like I said above, DO NOT ENABLE https using CapRover. That should be it. You don't need to do anything specific.

The only thing that you need to do is to avoid using `caprover serversetup` and just use `HTTP://IP:3000` to set up your instance:
- Assign the domain
- Change the default password

Now you can access your domain using plain HTTP, like `http://captain.something.com`. The rest is just CloudFlare stuff.

**Comment by voarsh2** [comment]
> Okay then, like I said above, DO NOT ENABLE https using CapRover. That should be it. You don't need to do anything specific.
> 
> The only thing that you need to do is to avoid using `caprover serversetup` and just use `HTTP://IP:3000` to set up your instance:
> 
> * Assign the domain
> * Change the default password

Unfortunately I must enable HTTPS for self-hosted registry.....

**Comment by githubsaturn** [comment]
Then you definitely need Let's Encrypt.

**Comment by voarsh2** [comment]
> Then you definitely need Let's Encrypt.

Could you implement the different method of verifying a domain? DNS record, not hostname/IP based?

**Comment by githubsaturn** [comment]
It's not supported right now, but feel free to open a feature request for it

**Comment by voarsh2** [comment]
> It's not supported right now, but feel free to open a feature request for it

Fine. I'll make an issue............... again.
(You could just flag as feat request and reopen.....)

My /etc/nginx/conf.d/captain-root.conf includes:
```
        ssl_certificate     /nginx-shared/fullchain.pem;
        ssl_certificate_key /nginx-shared/privkey.pem;
```
I generated this manually outside of the Let's Encrypt function in CapRover. 
How do I get it to honour this and let me use the self hosted registry?

**Comment by githubsaturn** [comment]
> Fine. I'll make an issue............... again.
(You could just flag as feat request and reopen.....)

This issue contain other irrelevant information. Just created another issue: https://github.com/caprover/caprover/issues/1060

> How do I get it to honour this and let me use the self hosted registry?

You'll have to go to settings and manually override the selfhosted registry section.

**Comment by voarsh2** [comment]
> This issue contain other irrelevant information. Just created another issue: #1060

Okay, thank you. 

> You'll have to go to settings and manually override the selfhosted registry section.

There's no manual override that I can see.
When enabling it, I get: "Root must have SSL before enabling ssl for docker registry."
CapRover root nginx has my ssl cert specified.... It's expecting "Let's Encrypt" process, so what can I do to get marked as valid SSL with my externally added Let's Encrypt cert?

**Comment by githubsaturn** [comment]
Oh I see what you're trying to do. That won't work unfortunately. Having said that, you can do this:
- Create an htpasswd file with a username and password of your choice and place it in ` /nginx-shared/auth` file. You can use [this tool](https://www.web2generators.com/apache-tools/htpasswd-generator) if you're not familiar how to do it.
- Run `cat /nginx-shared/auth` and make sure it outputs something like `username:$apr1$fl08g413$qc6WW59YVEA4PvyTaOQID1`
- Go to One Click apps, and Choose "TEMPLATE" from the list, then copy this content:
```
captainVersion: 4
caproverOneClickApp:
  instructions:
    start: Just a plain Docker Compose.
    end: Docker Compose is deployed.
registry:
  restart: always
  image: 'registry:2'
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /nginx-shared/auth
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - 'registry-data:/var/lib/registry'
    - '/nginx-shared:/nginx-shared'
```
- After your one click app is deployed, go to you app's setting, and map port 5000=>5000
- Now you have a registry that sits on `https://youroneclickappname.domain.com:5000` with the username and password that you chose.

**Comment by voarsh2** [comment]
Interesting, I'll report back on this, thanks.

**Comment by voarsh2** [comment]
Sorry, I've finally had some time to give this some more thought.
I've tried to deploy the template but the deploy button doesn't do anything, no console errors in browser

**Comment by githubsaturn** [comment]
Try this:
```
captainVersion: 4
caproverOneClickApp:
  instructions:
    start: Just a plain Docker Compose.
    end: Docker Compose is deployed.
services:
  my-registry:
    restart: always
    image: 'registry:2'
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /nginx-shared/domain.crt  ### <<<< CHANGE THIS
      REGISTRY_HTTP_TLS_KEY: /nginx-shared/domain.key  ### <<<< CHANGE THIS
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /nginx-shared/auth
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - 'registry-data:/var/lib/registry'
      - '/nginx-shared:/nginx-shared'
```

**Comment by voarsh2** [comment]
That works.
This might seem like a really silly question, but certbot gives me privkey.pem and fullchain.pem

I assume REGISTRY_HTTP_TLS_CERTIFICATE will use:  fullchain.pem? and REGISTRY_HTTP_TLS_KEY privkey.pem?

**Comment by githubsaturn** [comment]
You can look into the official registry docs for information about this. This is the example they have:
```
$ docker run -d \
  --restart=always \
  --name registry \
  -v "$(pwd)"/certs:/certs \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  -p 443:443 \
  registry:2
```

https://docs.docker.com/registry/deploying/

**Comment by githubsaturn** [comment]
If you're using pem files, yes, REGISTRY_HTTP_TLS_CERTIFICATE is fullchain.pem and REGISTRY_HTTP_TLS_KEY is privkey.pem
