### ISSUE TITLE
Leaving swarm breaks CaptRover

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#1058]
I have two nodes.

I want one to be a manager.

The other a worker node.

They're both seemingly part of a swarm with one inside.....

I want one of them to join the other, but it's part of a swarm (with just themselves), using docker swarm leave results in me needing to do: docker swarm leave --force which breaks Caprover.

So, I'm not able to join using this method:
docker swarm join --token SWMTKN-1-5npi4hdgcvvx7zs2qkyf7c0mw2kfl92wwh9rhb4ii99kbfgucj-abk5513jmtrx1aza2t5n83d2e 127.0.0.1:2377

**Comment by githubsaturn** [comment]
> I want one of them to join the other, but it's part of a swarm (with just themselves),

Not sure if I understand this. Are you saying you have a working Swarm Cluster with CapRover, and you are trying to remove of the nodes? Or are you trying to add an extra node to the main node?

**Comment by voarsh2** [comment]
> Not sure if I understand this. Are you saying you have a working Swarm Cluster with CapRover, and you are trying to remove of the nodes? Or are you trying to add an extra node to the main node?

Node 1:
![image](https://user-images.githubusercontent.com/60437695/111920593-b9f52180-8a87-11eb-843f-c17ee699c3af.png)

Node 2:
![image](https://user-images.githubusercontent.com/60437695/111920608-d3966900-8a87-11eb-841a-fc122c060a34.png)

I cannot get node two to join node 1.
"using docker swarm leave results in me needing to do: docker swarm leave --force which breaks Caprover.

So, I'm not able to join using this method:
docker swarm join --token SWMTKN-1-5npi4hdgcvvx7zs2qkyf7c0mw2kfl92wwh9rhb4ii99kbfgucj-abk5513jmtrx1aza2t5n83d2e 127.0.0.1:2377"

**Comment by githubsaturn** [comment]
This is not how Docker swarm works!! You don't need to install CapRover on both machines. Just do this:
- Install CapRover on one machine and set it up
- On the second machine, just install Docker (DO NOT init Swarm, and DO NOT install CapRover)
- Go to your first node and simply add the second node using the UI.

**Comment by voarsh2** [comment]
Um, thanks, shame about the exclamation marks. 👎
