### ISSUE TITLE
Losing access to AWS EC2 instance after deploy Keyclock App

### ISSUE THREAD

**Issue by chrisfritsche** [caprover/caprover#1059]
Hi everybody!
For two times it happen to me:

In a normal AWS EC2 (t2) instance, with just ubuntu 18.04, docker and caprover, after i deploy a Keycloack instance (with latest for keyclock and postgres) i lost complete access to the instance. On the second test it was running for a time, but then, without any reason, i also lost the access. In AWS panel also pointing error on the "Availability check". And obviously, because i lost the access, i have no logs.

I will appreciate any idea on how to find out what may be causing this. Thx a lot in advance!

**Comment by githubsaturn** [comment]
Sounds like a Keycloack issue. One click apps are tested with the versions that are set by default. We explicitly avoid `latest` tag because of these issues.... In this case, looks like latest Keycloack has some issues... 

Try restarting the machine and see if you can restore the logs.

**Comment by chrisfritsche** [comment]
Thx for your answer @githubsaturn . The problem is that the keycloack default version is 6 .. (and the latest is 12.). I try to restart the machine as well but no result. I also will chat with the AWS support. Maybe they can give me some log. After they give me feedback, and i can't find the reason, i will test with older versions of Keyclock, like 11, and write here again. Thx a lot!

**Comment by githubsaturn** [comment]
Yes, without logs, it's impossible to tell what is going on... Most likely case is that Keyclock is just eating up your system resources, RAM/CPU/disk...

Feel free to reopen if logs indicate that this is a CapRover issue.
