### ISSUE TITLE
Allow customization of Certbot command

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover#1060]
Currently certbot commands are built-in. Allowing an override would be helpful as it allows for different methods of domain verification such as DNS.

**Comment by wolfcry0** [comment]
Would love this as well. I can't use certbot http verification on my network, and letsencrypt won't issue wildcard certs with that method either.

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/caprover/issues/1761
