### ISSUE TITLE
[Deployment Issue] VueCLI not receiving env variables set on CapRover

### ISSUE THREAD

**Issue by PabloVSouza** [caprover/caprover#1061]
I'm trying to deploy a VueCLI Frontend application using CapRover. The same application is running on Heroku and Netlify with no problems.

I've set some environment variables on CapRover's interface, but the application appears to be not receiving them during the build process, resulting on multiple errors caused by the lack of those variables.

this is my captain-definition file:

`{
  "schemaVersion": 2,
  "dockerfilePath": "./dockerfile"
}`

this is my "dockerfile"

```
FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app

COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
```

and this is how i've set the env vars on cap rover:
![env](https://user-images.githubusercontent.com/30412188/112001356-a84e6100-8afd-11eb-80eb-62da49dc5bf3.png)

**Comment by githubsaturn** [comment]
See here: https://caprover.com/docs/app-configuration.html#environment-variables

![image](https://user-images.githubusercontent.com/10582082/112079618-e035c280-8b56-11eb-9ada-cfefcbd914a4.png)
