### ISSUE TITLE
One-Click MySQL Error

### ISSUE THREAD

**Issue by samuelcecilio** [caprover/caprover#1062]
Every newly created MySQL 5.7 database does not work. Other apps and One-Click are working normally.

![Captura de Tela 2021-03-22 às 19 09 46](https://user-images.githubusercontent.com/30150045/112065068-ca1e0700-8b42-11eb-918d-e888c1aad0c2.png)

![Captura de Tela 2021-03-22 às 19 10 06](https://user-images.githubusercontent.com/30150045/112065077-cdb18e00-8b42-11eb-80e0-26249eb62845.png)

---
Steps to reproduce the problem:

```
1. Create OneClick MySQL 5.7
```

---
Server:

```
Type: Leader (Main Node)
State: ready
Status: active
RAM: 15.66 GB
OS: linux
CPU: 8 cores
Architecture: x86_64
Docker Version: 20.10.5
Ubuntu 20.04
```

**Comment by githubsaturn** [comment]
Just tried it and works fine.
https://captain.server.demo.caprover.
password: `captain42` 

App name: `test-mysql-db`

The error is specific to your instance. Perhaps some weird permission issue. Do you run docker as root normally or do you have a docker specific sudo user?

**Comment by samuelcecilio** [comment]
Thank you, in fact it is specific.
