### ISSUE TITLE
[Deployment Issue] Unable to use certain images

### ISSUE THREAD

**Issue by Rhys-Woolcott** [caprover/caprover#1064]
What is the problem?
I am trying to publish an app called [PYX-Reloaded](https://github.com/devgianlu/PYX-Reloaded) on caprover using the docker image: [darrenjrobinson/cardsagainsthumanity](https://hub.docker.com/repository/docker/darrenjrobinson/cardsagainsthumanity)
but it needs some startup command commands: `/bin/bash /root/cah.sh` in which it needs to run. how can I run these?

Steps to reproduce the problem:
put the docker image into the container and build. here is the [Blog Post](https://blog.darrenjrobinson.com/virtual-cards-against-humanity-as-an-azure-web-app/) for the image

Answers to the following questions if applicable:
- Your OS and version: ubuntu 20.04.

**Comment by githubsaturn** [comment]
@Rhys-Woolcott 

All you need to build an image with that start up command. Try this:
```
FROM darrenjrobinson/cardsagainsthumanity
CMD ["/root/cah.sh"]
```

Or, this
```
FROM darrenjrobinson/cardsagainsthumanity
CMD ["/bin/bash" , "/root/cah.sh"]
```
Or, this
```
FROM darrenjrobinson/cardsagainsthumanity
CMD ["/bin/bash" , "-c" , "/root/cah.sh"]
```

One of these three should work!

**Comment by Rhys-Woolcott** [comment]
Is that in a docker file?

**Comment by githubsaturn** [comment]
Yes. You can literally copy and paste the content in the deployment tab. One of the deployment methods is called deploy from dockerfile.

**Comment by Rhys-Woolcott** [comment]
> Yes. You can literally copy and paste the content in the deployment tab. One of the deployment methods is called deploy from dockerfile.

![img](https://i.imgur.com/U00Mjnl.png)

**Comment by githubsaturn** [comment]
Looks like there is a permission with this image, try this:
```
FROM darrenjrobinson/cardsagainsthumanity
RUN chmod +x /root/cah.sh
CMD ["/bin/bash" , "-c" , "/root/cah.sh"]
```
