### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.

### ISSUE THREAD

**Issue by codecrust** [caprover/caprover#1066]
What is the problem?

With caprover trying to run uws with Nodejs it is throwing this error unable to access this library
**Error: Error loading shared library ld-linux-x86-64.so.2:** No such file or directory (needed by /usr/src/app/node_modules/uWebSockets.js/uws_linux_x64_88.node)

content of `captain-definition` file:
{
 "schemaVersion" :2 ,
 "templateId" :"node/12.18.0"
}

**Comment by githubsaturn** [comment]
By default, CapRover uses Alpine Linux images since they're smaller. Some particular binaries might be missing from Alpine images. 

You can use a dockerfile to use an Ubuntu based base image. See the docs  https://caprover.com/docs/captain-definition-file.html#use-dockerfile-in-captain-definition
