### ISSUE TITLE
how to get error log file after deploy ?

### ISSUE THREAD

**Issue by webafra** [caprover/caprover#1067]
Hello
I uploaded a simple nodejs project but got an error.
Where is the path to the log file?
2021-03-25T23:06:26.650398917Z npm ERR! /root/.npm/_logs/2021-03-25T23_06_26_643Z-debug.log

i use this but get "not such file or directory":
cd /root/.npm/_logs/

content of `captain-definition` file:
```
{
 "schemaVersion" :2 ,
 "templateId" :"node/14"
}
```

Steps to reproduce the problem:
1 - make .tar file from my nodejs project
2 - select .tar file and click deploy btn

- OS:  ubuntu 18.4?
- RAM: 4GB

**Comment by githubsaturn** [comment]
```
2021-03-25T23:06:26.650398917Z npm ERR! /root/.npm/_logs/2021-03-25T23_06_26_643Z-debug.log
```

This is a build error, right? You should see more context above this line in the logs. If you want to manually run the docker build to see if it's failing, you can simply just use `Dockerfile`
```
```


-------

Most likely the build is failing because you're using an Alpine image. Try using this captain-definition content:
```
 {
  "schemaVersion": 2,
  "dockerfileLines": [
                        "FROM node:14",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./ /usr/src/app",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

Does this work?
