### ISSUE TITLE
Access specific application nginx from shell

### ISSUE THREAD

**Issue by maxvia87** [caprover/caprover#1070]
Hello, 

A few days ago I had a huge bug with an old caprover instance I had. I started messing around, making worse and ended up not being able to log in anymore. My dashboard is not accessible at all.
Anyway what I did is create a new caprover image on a new droplet and added back all my app in it (1 rails app, 1 django etc..). I now have an issue with my rails app, an issue i faced a little bit ago on my old caprover image (issue with websockets not working), but I dont remember how to solve it. I know I had to modify my rails app nginx in order to fix it. 
Since I do not have acces to the dashboard anymore BUT I have access to the shell, I would like to know how I could access the nginx file for the specific app and read it? 

Thank you for you help!

**Comment by githubsaturn** [comment]
Have you tried this?
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by maxvia87** [comment]
I did but it didnt work. I still cant access my dashboard.. Tbh i started messing with many things so I prefered to create a new droplet and start all over again.
Now everythinh on my new caprover image works well except that specific nginx setting for my rails app that I cant figure out. This is why I am trying to look for it from the shell but unsucessfull.

**Comment by githubsaturn** [comment]
I am not sure if I understand what you're saying. 
1- Can you access your dashboard, or not?
2- What is the specific nginx settings for your rails? What is the change you need to make?

**Comment by maxvia87** [comment]
YEs sorry it is a big confusing. 
1- I have two droplets, with one caprover in it. One old droplet and one new. I cannot access the dashboard of the old one old one
2 - in the old caprover i have one rails app for which I modified the nginx. I am trying to access this "nginx" file so I can look at the modification I made from the shell ( I stil have acess to the old caprover shell) Or Where can i find the informations relative to this file from the shell? 
<img width="1112" alt="Screen Shot 2021-03-29 at 14 06 52" src="https://user-images.githubusercontent.com/64636974/112834389-35faf500-9098-11eb-843c-62100acfe951.png">

**Comment by githubsaturn** [comment]
I see. Okay so you're new instance is working fine.

If you ran the nginx fix command that I linked above ([this](https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui)), then you've erased the changes that you made to your nginx config.

Having said that, if you want to view your nginx config, you can always, view it this way:
- Raw values are inside `/captain/data/config-captain.json` file
- You can view the rendered config that is being passed to nginx at `/captain/generated/nginx/conf.d/captain.conf`

**Comment by maxvia87** [comment]
Oh ok then there is no point trying to access it anymore! Thank you for your explanation!

**Comment by maxvia87** [comment]
May be you can help me then. I am trying to update the nginx so that my rails app can use websockets. I am facing the same issue that than the one mentionned here [https://stackoverflow.com/a/60213773](url)

I am not sure I have put the following code at the right place in my nginx config file:

Here is the code I need to add: 

```
        ########################
        # ActionCable specific #
        ########################
        location /cable {
          proxy_pass http://puma/cable;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
        }
```
Here is where I added it: 

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri$is_args$query_string;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;
        ########################
        # ActionCable specific #
        ########################
        location /cable {
          proxy_pass http://puma/cable;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
        }
        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}

```
Does it look like to you that it is at the right the spot?

Thank you for your time!

**Comment by githubsaturn** [comment]
Looking at this:
```
        ########################
        # ActionCable specific #
        ########################
        location /cable {
          proxy_pass http://puma/cable;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
        }
```


This is completely unnecessary. All these websocket lines are already in the nginx config, look here:
```
    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
```

All you need to do is to check the websocket option in the UI.

![image](https://user-images.githubusercontent.com/10582082/112912490-a10ef080-90c5-11eb-944a-c00b8f4076bc.png)

**Comment by githubsaturn** [comment]
Feel free to comment if you still have questions.
