### ISSUE TITLE
[Question] App subdomains work fine, but cant verify / 502 error with certbot for Root Domain

### ISSUE THREAD

**Issue by mrpatg** [caprover/caprover#1071]
Running this on a single exposed computer (ubuntu 20.04) at home, PC has 80/443 forwarded from router to box, and I even put the whole machine in the DMZ.

When I connect via local IP, external IP, or domain I can connect fine, I tried cloudflare (no proxy) and also namecheap. Subdomain wildcards are working fine but its the specific captain subdomain when it generates the file in certbot that url returns 404, the subdomain itself returns 502. Web admin works fine. I've tried tearing down and rebuilding, rebound 0.0.0.0 in nginx config, and tried reading as much as I could, but cant seem to get the main domain validated. DNS propagation check finds the correct IP all over the world. UFW is modified as per docs, and also disabled (confirmed).

Here is logs from cert attempt (domain changed, but it is a .host tld):

```
captain-captain.1.y7k7s1er209b@dellbox2    | Plugins selected: Authenticator webroot, Installer None
captain-captain.1.y7k7s1er209b@dellbox2    | Obtaining a new certificate
captain-captain.1.y7k7s1er209b@dellbox2    | Performing the following challenges:
captain-captain.1.y7k7s1er209b@dellbox2    | http-01 challenge for captain.apps.website.host
captain-captain.1.y7k7s1er209b@dellbox2    | Using the webroot path /captain-webroot/captain.apps.website.host for all unmatched domains.
captain-captain.1.y7k7s1er209b@dellbox2    | Waiting for verification...
captain-captain.1.y7k7s1er209b@dellbox2    | Challenge failed for domain captain.apps.website.host
captain-captain.1.y7k7s1er209b@dellbox2    | http-01 challenge for captain.apps.website.host
captain-captain.1.y7k7s1er209b@dellbox2    | Cleaning up challenges
captain-captain.1.y7k7s1er209b@dellbox2    | Some challenges have failed.
captain-captain.1.y7k7s1er209b@dellbox2    |
captain-captain.1.y7k7s1er209b@dellbox2    | IMPORTANT NOTES:
captain-captain.1.y7k7s1er209b@dellbox2    |  - The following errors were reported by the server:
captain-captain.1.y7k7s1er209b@dellbox2    |
captain-captain.1.y7k7s1er209b@dellbox2    |    Domain: captain.apps.website.host
captain-captain.1.y7k7s1er209b@dellbox2    |    Type:   connection
captain-captain.1.y7k7s1er209b@dellbox2    |    Detail: Fetching
captain-captain.1.y7k7s1er209b@dellbox2    |    http://captain.apps.website.host/.well-known/acme-challenge/0rRykJq-4U_232cQ5oBjlq5wSXVlgjyGvpDEAE8zPHY:
captain-captain.1.y7k7s1er209b@dellbox2    |    Timeout during connect (likely firewall problem)
captain-captain.1.y7k7s1er209b@dellbox2    |
captain-captain.1.y7k7s1er209b@dellbox2    |    To fix these errors, please make sure that your domain name was
captain-captain.1.y7k7s1er209b@dellbox2    |    entered correctly and the DNS A/AAAA record(s) for that domain
captain-captain.1.y7k7s1er209b@dellbox2    |    contain(s) the right IP address. Additionally, please check that
captain-captain.1.y7k7s1er209b@dellbox2    |    your computer has a publicly routable IP address and that no
captain-captain.1.y7k7s1er209b@dellbox2    |    firewalls are preventing the server from communicating with the
captain-captain.1.y7k7s1er209b@dellbox2    |    client. If you're using the webroot plugin, you should also verify
captain-captain.1.y7k7s1er209b@dellbox2    |    that you are serving files from the webroot path you provided.
captain-captain.1.y7k7s1er209b@dellbox2    |
captain-captain.1.y7k7s1er209b@dellbox2    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
captain-captain.1.y7k7s1er209b@dellbox2    |     at /usr/src/app/built/user/system/CertbotManager.js:65:48
captain-captain.1.y7k7s1er209b@dellbox2    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
captain-captain.1.y7k7s1er209b@dellbox2    | POST /api/v2/user/system/enablessl 200 12865.801 ms - 1542
```

The only thing I can think to check is if for some reason it's unable to make the folder/files, a permissions issue, but I am not even sure how to verify that.

**Comment by githubsaturn** [comment]
> Subdomain wildcards are working fine but its the specific captain subdomain when it generates the file in certbot that url returns 404, the subdomain itself returns 502.

I am not sure if I understand this. Let me try breaking it down:
- Can you access your dashboard using `http://captain.yourdomain.com` ?
- Can you access you dashboard using `http://captain.yourdomain.com` from an external network? For example, try "https://labs.play-with-docker.com/" and run `curl http://captain.yourdomain.com`
- Have your enabled HTTPS for your dashboard? Can you access your dashboard using `https://captain.domain.com` ?

**Comment by mrpatg** [comment]
Can you access your dashboard using http://captain.yourdomain.com ? **Yes**
Can you access you dashboard using http://captain.yourdomain.com from an external network? For example, try "https://labs.play-with-docker.com/" and run curl http://captain.yourdomain.com **When I try this is hangs and doesn't output anything, so I'll say no.**
Have your enabled HTTPS for your dashboard? Can you access your dashboard using https://captain.domain.com ? **I cannot, I get an error that I included above.**

**Comment by githubsaturn** [comment]
> When I try this is hangs and doesn't output anything, so I'll say no.

This is the problem. Your instance is not accessible from outside of your network. That's why when you're trying to enable Let'sEncrypt it fails.

Your port forwarding is not working. You need to get the port forwarding working. The exact steps depend on your network and your router.

**Comment by githubsaturn** [comment]
PS: the issue that you're having is not CapRover specific. To test:
- [Uninstall CapRover fully](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain)
- Then simply just run an nginx instance `docker run -p 80:80 nginx`
- Can you access it from outside network?
