### ISSUE TITLE
Deployed latest static files is not reflecting over Caprover instance. 

### ISSUE THREAD

**Issue by contentsr** [caprover/caprover#1074]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
I am deploying my latest code, which is reflecting fine in the local machine, but it doesn't reflect over Caprover app instance. No .js file or .html file. Deploying Statis files.

OS: UBUNTU 18.04 hosted over Digital Ocean Droplet
RAM : 4GB

**Comment by githubsaturn** [comment]
Have you committed those files to git? Uncommitted files won't be deployed.

**Comment by contentsr** [comment]
tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./build/*
caprover deploy -t ./deploy.tar

**Comment by contentsr** [comment]
Docker file is :-
FROM nginx:1.13.9-alpine
ENV NODE_ENV production
RUN mkdir -p /etc/nginx/conf.d
COPY ./default.conf /etc/nginx/conf.d/
COPY ./chatapp.store /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

captain-definition file:-
{
  "schemaVersion": 2,
  "dockerfilePath" :"./Dockerfile"
}

**Comment by contentsr** [comment]
> Have you committed those files to git? Uncommitted files won't be deployed.

Static Web APP and deployed via following command. It was working fine before. Problem started from last 2 to 3 days.
tar -cvf ./deploy.tar --exclude='.map' ./captain-definition ./Dockerfile ./default.conf ./chatapp.store/
caprover deploy -t ./deploy.tar

**Comment by githubsaturn** [comment]
Your dockerfile is incorrect. Your FROM line is using a nodejs base image but your command is using nginx! Are you sure it used to work with this dockerfile?!

**Comment by contentsr** [comment]
> Your dockerfile is incorrect. Your FROM line is using a nodejs base image but your command is using nginx! Are you sure it used to work with this dockerfile?!

Yeah, It's working and still working. Only problem is, now latest .js and .html file is not reflacting over Caprover instance.

**Comment by contentsr** [comment]
> Your dockerfile is incorrect. Your FROM line is using a nodejs base image but your command is using nginx! Are you sure it used to work with this dockerfile?!

if you are mentioning this line "ENV NODE_ENV production" then it was copied accidentally. It wasn't part of the original docker file.

FROM nginx:1.19.9
RUN mkdir -p /etc/nginx/conf.d
COPY ./default.conf /etc/nginx/conf.d/
COPY ./chatapp.store /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

**Comment by githubsaturn** [comment]
Oh I misread it!

Yeah this definitely looks okay. The only possible thing that I can think of is potentially your browser caching the old files. Try force refreshing the page. Or maybe use the incognito mode. 

Also, does your build succeed? Run `docker service ls` before and after a deploy and make sure the version goes up.

**Comment by contentsr** [comment]
> Oh I misread it!
> 
> Yeah this definitely looks okay. The only possible thing that I can think of is potentially your browser caching the old files. Try force refreshing the page. Or maybe use the incognito mode.
> 
> Also, does your build succeed? Run `docker service ls` before and after a deploy and make sure the version goes up.

I tried this in incognito mode and forced refreshing the file but unfortunately didn't succeed. Yeah didn't try yet your last suggestion. Run docker service ls. Will try it also. Hope it will help.

**Comment by githubsaturn** [comment]
If that doesn't help, next step is to shell into the container and see if the new files are there.

**Comment by contentsr** [comment]
> If that doesn't help, next step is to shell into the container and see if the new files are there.

docker service ls Result:-
ntrvn6uxsjqo        srv-captain--chatapp                   replicated          5/1                 registry.wp.scvpl.in:996/captain/img-captain-chatapp:255

**Comment by githubsaturn** [comment]
Looks like your instance is really unhealthy. Docker wasn't able to kill the previous containers. 

Go to settings and clean up old images. Then reboot your server.

**Comment by contentsr** [comment]
> Looks like your instance is really unhealthy. Docker wasn't able to kill the previous containers.
> 
> Go to settings and clean up old images. Then reboot your server.

I tried from dashboard settings to remove old images but didn't succeed. Rebooted the server still same result with docker service ls

**Comment by githubsaturn** [comment]
This is a Docker issue, have a look at these ones:
moby/moby#24394
docker/swarmkit#1372
moby/moby#24670


Previously it's been reported in CapRover a few times, but there is generally nothing that CapRover can do to fix/mitigate the issue:
https://github.com/caprover/caprover/issues/784
https://github.com/caprover/caprover/issues/896

**Comment by githubsaturn** [comment]
Try opening an issue on [Docker's issue tracker](https://github.com/moby/moby/issues), they might be able to help.

**Comment by contentsr** [comment]
> This is a Docker issue, have a look at these ones:
> [moby/moby#24394](https://github.com/moby/moby/issues/24394)
> [docker/swarmkit#1372](https://github.com/docker/swarmkit/issues/1372)
> [moby/moby#24670](https://github.com/moby/moby/issues/24670)
> 
> Previously it's been reported in CapRover a few times, but there is generally nothing that CapRover can do to fix/mitigate the issue:
> #784
> #896

Sure. Thank you for your help and prompt reply.

**Comment by contentsr** [comment]
> Try opening an issue on [Docker's issue tracker](https://github.com/moby/moby/issues), they might be able to help.

sure and again thank you.

**Comment by githubsaturn** [comment]
Feel free to link your issue here for anyone in the future who faces the same problem.

**Comment by cheapestorderconcept** [comment]
I deployed my app via caprover to digital ocean. I have shell into my container and see all changes made were there. However when reloading my web app this changes didn't reflect and they exists inside the container. The version of my caprover images increased. Likewise I have clear my browser do Disk clean up and the issue still persists
