### ISSUE TITLE
[Deployment Issue] Access host port from container

### ISSUE THREAD

**Issue by BetaHuhn** [caprover/caprover#1076]
Due to different unrelated issues I'm not able to deploy an application with Caprover to a docker container and it has to run directly on the host. Now I need another Caprover application to access it from inside the container.

Let's say app1 is running on the host and listening on port 2555, how can I access it from app2 which is running inside a container created by Caprover?

As I understand it, port mapping which can be done in Caprover's UI is only needed in the reverse case when trying to access the container from the host.

Is this something that can be enabled with [Service Update override](https://caprover.com/docs/service-update-override.html)?

Any help would be appreciated!

**Comment by githubsaturn** [comment]
First, make sure your firewall has the port 2555 open. Then from inside the container you can just use `123.123.123.123:2555` to connect to the app outside of CapRover. Replace  `123.123.123.123` with the IP address of your server.

**Comment by BetaHuhn** [comment]
That would definitely work, but I don't want to make app1 accessible from the outside. I just need it to be accessible from inside containers.

**Comment by githubsaturn** [comment]
Your can define custom firewall rules that only allow incoming connections from local IPs. 

See this for example:
https://serverfault.com/questions/210997/only-allow-lan-connections-to-server

It's not a 100% working solution but it gives you the idea. You need to adjust your incoming IP band correctly depending on your network set up.

**Comment by BetaHuhn** [comment]
So there's no way to allow containers to access the host directly via localhost similarly to how it's working with port mapping?

**Comment by githubsaturn** [comment]
That's correct.

**Comment by BetaHuhn** [comment]
Okay, I will give the approach you mentioned a try.

Thanks for help and quick response!
