### ISSUE TITLE
Deploy same app, different CMD 

### ISSUE THREAD

**Issue by jakcharlton** [caprover/caprover#1079]
Have been trying a variety of options from various issues and doc pages, but none seem to work

Basically I need to deploy the same Rails application, but into two different CapRover apps, each with a different CMD. The only difference is the start command, everything else is identical. 

Any pointers?

Firstly I need to deploy the rails web app:

`CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]`

Then the delayed_job app:

`CMD ["bundle", "exec", "jobs:work"]`

Edit:

This may have been a mistake taken from a forked branch, but I cannot find an equivalent in the official caprover repo.

I have tried two different xxx.config.json files using 

`--configFile ./captain-definition-web.config.json`

But it fails with Error: Captain Definition file does not exist!

**Comment by githubsaturn** [comment]
Login to your dashboard, and set up the right path for specific captian-definition.

Deployment tab, the bottom of the page, you'll see this:
![image](https://user-images.githubusercontent.com/10582082/113702754-efb12180-96a7-11eb-80aa-8184106aaba1.png)

All you need to do is to create two captain-definition files, e.g., `captain-definition-web` `captain-definition-job` that have different dockerfiles. Then simply `caprover deploy`.

PS: no need to use `--configFile`. Note that `captain-definition` is not the config file, [config file is a completely different thing](https://github.com/caprover/caprover-cli#server-setup).

**Comment by jakcharlton** [comment]
Brilliant thanks a bunch! Couldn't find that anywhere in the docs, is it in there and I missed it?

**Comment by githubsaturn** [comment]
I don't think so. Just added some info. Feel free to edit or add more
https://github.com/caprover/caprover-website/commit/424d3a2b77e00e2ba0e30fb3dc19b52556aaf131
