### ISSUE TITLE
[Feature-request] Add dropdown in settings to redirect 404 to one of the deployed apps.

### ISSUE THREAD

**Issue by matthewlyons** [caprover/caprover#1084]
**Is your feature request related to a problem? Please describe.**

Customizing the 404 page, per this [issue]( https://github.com/caprover/caprover/issues/1025), requires the use of the file system to access NGINX shared folders. It would be easier to deploy updates to this page if it could be done using the GUI.

Two possible use cases for needing to redirect or regularly update the 404 page would be:

1. If you're hosting only a single app and you want all routes pointed to that app.
2. If your 404 page is a custom page to display links to the apps available and you need to keep it up to date.

**Describe the solution you'd like.**

In settings add a section to customize the 404 page. This section could include a dropdown with options for what the 404 page would show:
```html
<div>
    <label for="appSelect">404 Page:</label>
    <select for="appSelect">
        <option value="default">Default</option>
        <option value="app1">App 1</option>
        <option value="app2">App 2</option>
    </select>
</div>
```

I figure this list would only include the apps which are exposed to the internet to prevent the 404 from being redirected to a database. 

This section could alternatively include a select box and a text field. This would allow the 404 page to be a specific route within an app. However, this doesn't look as clean as the dropdown does. The HTML would look like this:

```html
<div>
    <div>
        <label for="checkbox">Custom 404 page?</label>
        <input type="checkbox" name="checkbox" id="">
    </div>
    <div>
        <label for="text">URL</label>
        <input type="text" name="text" id="">
    </div>
</div>
```
If the checkbox is active, it will use the URL in the text input. Otherwise, it will be ignored and use the default route.

**Describe alternatives you've considered**
One idea I considered is to check if there is an app with the title "404", if so then redirect all 404 traffic to this app. The reason I moved off this idea is that it only covers half of the potential use cases I came up with. For use case 1, it would be slightly annoying to have to deploy to both the main application as well as this additional 404 app.

**Comment by githubsaturn** [comment]
Are you referring to the page that is displayed when you reach to a non existing URL?

<img src="https://user-images.githubusercontent.com/10582082/114285621-9853de00-9a26-11eb-8370-b6b8c71a24b9.png" height=200 alt="404"/>


If so, your don't need to access file system. All you need to do is to go to settings:
* Click on edit NGINX
* Find this part:
```
        location / {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }
```
* Change it to this:
```
        location / {
            return 302 http://your404.domain.com
        }
```

<img src="https://user-images.githubusercontent.com/10582082/114285649-ccc79a00-9a26-11eb-80e2-59fa603e169a.png" height=300 alt="nginx"/>

**Comment by id3vz** [comment]
I tried the same solution but it breaks everything everytime.

**Comment by psanghvi17** [comment]
> location / {
>             return 302 http://your404app.domain.com
>         }

@githubsaturn When I did this looks like I am unable to get into Captain anymore. Can you please suggest a fix for this ASAP.

**Comment by githubsaturn** [comment]
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui
