### ISSUE TITLE
What is the point of swarm if CapRover is down, worker nodes won't work?

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#1086]
Am I missing something besides having more instances of the application, with "zero downtime" when an update is deployed because of a worker node serving the old version?

Why is there no concept of having two manager nodes?
I'm writing up a document about needing 99.99% availability, while I like CapRover, I do worry about a fact of it all falling apart (the applications) when the only CapRover manager node goes down (doesn't matter if there's node workers, they're kaput when it's gone...….)

But then, the thought of working with Kubernetes, Puppet, Chef, etc are beastly systems that takes time to learn.
At least if this project were moving to Kubernetes and were to keep it simpler, the issue around fail over would give me more of a glowing report on why I should use CapRover - if I can, I really don't want to use overly complex systems that takes time to learn at this point.

Are there plans to move to Kubernetes but try and keep it simple, with added high availability into the mix in future?

**Comment by githubsaturn** [comment]
> I'm writing up a document about needing 99.99% availability, while I like CapRover, I do worry about a fact of it all falling apart (the applications) when the only CapRover manager node goes down (doesn't matter if there's node workers, they're kaput when it's gone...….)

Yes, certainly CapRover is not the right fit for this use case. 

> But then, the thought of working with Kubernetes, Puppet, Chef, etc are beastly systems that takes time to learn.

Again, you hit the nail in the head. The reason that they are not integrated in CapRover is that they can't really be simplified. A true 99.99 HA system is complex by nature. There is a lot of details in setting up a system that can support "persistent data" replication and provide high availability. 


Regarding move to k8s, it is always an option. But not in short terms. Just "moving to k8s" won't solve the availability issue. There is a lot more that needs to be done, dynamic DNS, live snapshots, etc etc... 

But all this doesn't mean that swarm is useless, it's super useful if you need to attach temporary worker nodes for intensive work every now and then, also, if the worker nodes go down, all non persistent apps will automatically get recreated.

**Comment by voarsh2** [comment]
Yes, thanks for the reply.

I suppose, if the manager node (CapRover) were restored from a backup it might be close to a 10-20 minute "SLA" at a different location or something of the sorts, provided SSD's were used, fast cabling, etc.

I will need to mention all this in my report and mention the complexity of Kubernetes (I really... urgh. simple things like changing environment variables after you've created your pod.... can't be done... it's so rigid.)  and if it really is worth all the complexity than maybe saying to our potential clients " we can be up within 30 minutes" - should the manager node die/crash. Although, if it just crashes Docker itself can just be restarted.

(inner monologue) If the prospect of under 30 minutes doesn't sit right, then it looks like more complex systems are needed.

**Comment by githubsaturn** [comment]
Yea I think that's fair. If you need more complex systems, perhaps look into rancher.com - it's a tad more complex than CapRover, but it's meant for larger systems.
