### ISSUE TITLE
Check size of each app

### ISSUE THREAD

**Issue by maxvia87** [caprover/caprover#1087]
Hello, 

I have mutliple apps running on one caprover image. I am trying to check what is the size of each apps on it. 
I couldnt figure it out using the data monitoring tool?

Thank you!

Maxime

**Comment by githubsaturn** [comment]
"Size of each app" is very misleading. App consists of:
- Image
- Runtime container stuff
- Volume

For images, you can run `docker images` to see all images and their size.

For containers, you can run `docker ps --size`

For volumes, you can run `du /var/lib/docker/volumes/* -sh`
