### ISSUE TITLE
Second DB App using same persistent directory as first one

### ISSUE THREAD

**Issue by EduBeghe** [caprover/caprover#1088]
Hello 
I am trying to create my second postgres database app using the one click create app button. 
I already have a working version of this DB, but it need a second one.
After i set user, password, postgres version to 13 the database is successfully deployed but its deployed on the same persistent directoy as the first database.
If i try to connect a pgadmin client to this new database i see nothing on the new app logs, but on the first database app logs i can clearly see the connection i just tried to make.
How should i fix this?

First DB app persisten node id:
![image](https://user-images.githubusercontent.com/13985047/115417090-b65fd200-a1ce-11eb-91d3-78fdfe4f8ba3.png)

New DB app persistent node id:
![image](https://user-images.githubusercontent.com/13985047/115417197-ce375600-a1ce-11eb-9970-b3daf14c8af6.png)

First DB app logs:
![image](https://user-images.githubusercontent.com/13985047/115417408-f7f07d00-a1ce-11eb-95d9-bd1c3f213440.png)

New DB app logs:
![image](https://user-images.githubusercontent.com/13985047/115417510-0d65a700-a1cf-11eb-88a1-4fb284591e7d.png)

I have deleted and recreated the app a couple of times and the result is the same, all the requests go to my first DB app.
Thanks in advance!

**Comment by githubsaturn** [comment]
>  but its deployed on the same persistent directoy as the first database.

Your screenshot shows the node where these apps are deployed. 


How are you trying to connect to your database? Are you using a pgadmin client on the same CapRover instance and using `srv-captain-postgress....` as the URL? or you're using port mapping and connect to it from your local machine?

**Comment by EduBeghe** [comment]
Hi,

I have used the button to expose the app publicly at the Http Settings tab. With the first DB App i was able to connect normally from pgadmin, but for the new DB App i couldn't and every request reaches the first DB instead of the new one, i can't understand why?

![Screenshot from 2021-04-20 23-05-28](https://user-images.githubusercontent.com/13985047/115486763-b2af6800-a22d-11eb-87c4-ad5559c3121f.png)

**Comment by githubsaturn** [comment]
> expose the app publicly at the Http Settings tab

Postgres is not a web app. It is a database and does not use HTTP protocol. 


> With the first DB App i was able to connect normally from pgadmin

Again, what is the database URI that use to connect to your database?

**Comment by githubsaturn** [comment]
Read here for more details on how to connect to your databases: https://caprover.com/docs/database-connection.html

If you still have questions, feel free to ask.

**Comment by EduBeghe** [comment]
Hello @githubsaturn , i am here because i read your Docs and couldn't find a proper answer.

> Postgres is not a web app. It is a database and does not use HTTP protocol.
PgAdmin allows you to connect to an IP, with the exposed URL that gets translated to an IP, so yes, it allows you to use HTTP.
With the first database i was able to connect myself to the DB using several means included pgadmin and with the second application i could not connect by any mean.
> Again, what is the database URI that use to connect to your database?
I didn't to expose them but here they are:
- First DB APP Public URL: http://db-dev.vezagaming.com or internally srv-captain--db-dev
- New DB APP Public URL: http://db-prod-db.vezagaming.com or internally srv-captain--db-prod-db

Again we didn't configure any of this, this was automatically created with the one click create app button so there was nothing configuration done on our end.

**Comment by githubsaturn** [comment]
> Again we didn't configure any of this, this was automatically created with the one click create app button so there was nothing configuration done on our end

When you create a database using one click app, the checkbox is checked for "Do not Expose as WebApp":
![image](https://user-images.githubusercontent.com/10582082/115640907-0087a700-a2e6-11eb-9fb2-bddcf01bf86e.png)

You can see [here for postgres](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/postgres.yml#L13-L14) specifically. In general, you shouldn't use HTTP for databases.

To connect to your first database, enter
- Host:  srv-captain--db-dev
- Port: 5432

To connect to your second database, enter
- Host: srv-captain--db-prod-db
- Port: 5432

Like this: 
![image](https://user-images.githubusercontent.com/10582082/115641401-003bdb80-a2e7-11eb-9f59-7781967f38be.png)

**Comment by EduBeghe** [comment]
Hello @githubsaturn,

I tried what you suggested but i'm getting this
![image](https://user-images.githubusercontent.com/13985047/115794017-9e8d7700-a3a3-11eb-84ba-04aadadfcdfb.png)

I supose it is because, as the [docs](https://caprover.com/docs/database-connection.html) you sent me explain, if you use `srv-captain--db-prod-db` it should be internally, not from outside, from outside you should use the exposed URLS i sent you

> * First DB APP Public URL: http://db-dev.vezagaming.com
> * New DB APP Public URL: http://db-prod-db.vezagaming.com

But here is where i found the problem i am talking about. The First DB URL works as expected and i can connect to the DB without problems, but the second URL doesn't connect to the DB and tries to connect to my First DB, its like the second DB redirects all requests to the First DB.

Thanks for time!

**Comment by githubsaturn** [comment]
What does this print?
```
docker service inspect srv-captain--db-dev-db --pretty
```

Assuming that `srv-captain--db-dev-db` is the one that works.

**Comment by githubsaturn** [comment]
Here is a demo of how it works:


https://user-images.githubusercontent.com/10582082/115805873-d00e3e80-a3b3-11eb-92e6-d479037af1b3.mp4

**Comment by EduBeghe** [comment]
Hello @githubsaturn,

Amazing, video, really helpful. The links you have automatically generated give me this error:

https://user-images.githubusercontent.com/13985047/115924937-c8ec3c80-a456-11eb-8fe5-6c27f06831c0.mp4

This is the actual error:

https://vimeo.com/540816138/445214d029

Here are the 2 outputs of the command you requested. I changed the URI so it worked for each server
> ```
> docker service inspect srv-captain--db-dev-db --pretty
> ```

- srv-captain--db-dev
`Mounts:                                                                         
 Target:        /var/lib/postgresql/data                                        
  Source:       captain--db-db-data                                             
  ReadOnly:     false                                                           
  Type:         volume                                                          
Log Driver:                                                                     
 Name:          json-file                                                       
 LogOpts:                                                                       
  max-size:       512m                                                          
                                                                                
Resources:                                                                      
Networks: captain-overlay-network                                               
Endpoint Mode:  vip                                                             
Ports:                                                                          
 PublishedPort = 5432                                                           
  Protocol = tcp                                                                
  TargetPort = 5432                                                             
  PublishMode = ingress                                                         
 PublishedPort = 5432                                                           
  Protocol = udp                                                                
  TargetPort = 5432                                                             
  PublishMode = ingress                                             
`

- srv-captain--db-prod-db ( the one not working )
` Parallelism:   1                                                               
 On failure:    pause                                                           
 Monitoring Period: 5s                                                          
 Max failure ratio: 0                                                           
 Rollback order:    stop-first                                                  
ContainerSpec:                                                                  
 Image:         postgres:13                                                     
 Env:           POSTGRES_USER=veza POSTGRES_PASSWORD=iBJ3FDCtbMCSAi$y POSTGRES_D
B=veza POSTGRES_INITDB_ARGS=                                                    
Mounts:                                                                         
 Target:        /var/lib/postgresql/data                                        
  Source:       captain--db-prod-db-data                                        
  ReadOnly:     false                                                           
  Type:         volume                                                          
Log Driver:                                                                     
 Name:          json-file                                                       
 LogOpts:                                                                       
  max-size:       512m                                                          
                                                                                
Resources:                                                                      
Networks: captain-overlay-network                                               
Endpoint Mode:  vip`

The docs say that if i get the 502 maybe i should manually restart the DB from the console. I will try that, in the meantime this is all the info you requested.

Thanks again!

**Comment by githubsaturn** [comment]
A few things:

**First:**
The video you shared shows you click on the HTTP link of the database. As I said above, Postgres is not an HTTP app. You shouldn't use "Expose as HTTP". The 502 Error that you see is totally normal because you're trying to open an HTTP link for your database that is not an HTTP app.

**Second:**
The output that you shared indicates that you have port mapping enabled for your database:
![image](https://user-images.githubusercontent.com/10582082/115937097-fcce5e80-a464-11eb-9fa6-4c79507f1eb7.png)

When you have two databases, you cannot use the same port mapping.

For your first database, you can use:
Server Port 5432 ==>> Container Port 5432

For your second database, you need to use a different server port, for example:
Server Port 5050 ==>> Container Port 5432

Then, when you want to connect to your second database, you need to change the port in postgres database to 5050. You can see the port in the screenshot below:
![image](https://user-images.githubusercontent.com/10582082/115937212-53d43380-a465-11eb-917c-c0b21cf298ec.png)

**Comment by EduBeghe** [comment]
Hi @githubsaturn,

Amazing! The port mapping did the trick, I had already tried this but in the wrong order.
Thank you for your great help!

Have a good weekend!
Regards,
