### ISSUE TITLE
Certificate renewal fail made the domain unusable

### ISSUE THREAD

**Issue by Ratatinator97** [caprover/caprover#1089]
What is the problem?
The 20 April 2021 one of my certificates was expiring => api.pictalk.xyz
I has this domain running since approx 6 months, all running smoothly. 
But Namecheap (my DNS provider) did a maintenance upgrade at the exact same time cartbot wanted to renew the certificate !
Even 24h after that fail, it isn't working.
Here is the message I have:
```
1107 : Unexpected output when enabling SSL forapi.pictalk.xyz with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None Obtaining a new certificate Performing the following challenges: http-01 challenge for api.pictalk.xyz Using the webroot path /captain-webroot/api.pictalk.xyz for all unmatched domains. Waiting for verification... [31mChallenge failed for domain api.pictalk.xyz[0m http-01 challenge for api.pictalk.xyz Cleaning up challenges [31mSome challenges have failed.[0m [1m IMPORTANT NOTES: [0m - The following errors were reported by the server: Domain: api.pictalk.xyz Type: dns Detail: DNS problem: SERVFAIL looking up A for api.pictalk.xyz - the domain's nameservers may be malfunctioning 
```

Here is the log of the certbot fail:

[certbot_failed_logs.txt](https://github.com/caprover/caprover/files/6349217/certbot_failed_logs.txt)

Things I have tried:

- Cleaning the cache of the host machine
- Delete the certificate (with certbot & deleting files in the filesystem)
- Rebooting the host machine
- Adding the domain to another container and test if certificate could be created (it wasn't)
- Wait for DNS changes ... ( api.pictalk.yz has the right IP addr)
- `echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json` and then `docker service update captain-captain --force`

Steps to reproduce the problem:

- Install caprover
- Buy a domain name on Namecheap
- Try to renew your certificate at the exact same time Namecheap does maintenance.
- Domain broke...

Answers to the following questions where applicable:
- Your OS and version: Ubuntu 18.04
- RAM: 2GB
- Caprover Current Version: 1.9.0

**Comment by githubsaturn** [comment]
It's not something that you can resolve on CapRover side. It's only related to your DNS settings... Looks like your domain cannot be resolved at all. You can even try it here: https://www.nslookup.io/dns-records/forapi.pictalk.xyz

Until you get the DNS resolution issue fixed, there is nothing that CapRover can do to fix the issue.

PS: CapRover performs cert updates every day, so just one failure wouldn't break your renewal process.

![image](https://user-images.githubusercontent.com/10582082/115553982-034db200-a27c-11eb-842f-252bc662e4d9.png)

**Comment by Ratatinator97** [comment]
> 
> 
> It's not something that you can resolve on CapRover side. It's only related to your DNS settings... Looks like your domain cannot be resolved at all. You can even try it here: https://www.nslookup.io/dns-records/forapi.pictalk.xyz
> 
> Until you get the DNS resolution issue fixed, there is nothing that CapRover can do to fix the issue.
> 
> PS: CapRover performs cert updates every day, so just one failure wouldn't break your renewal process.
> 
> ![image](https://user-images.githubusercontent.com/10582082/115553982-034db200-a27c-11eb-842f-252bc662e4d9.png)

domain: api.pictalk.xyz and not forapi.pictalk.xyz
[https://dnschecker.org/#A/api.pictalk.xyz](https://dnschecker.org/#A/api.pictalk.xyz)
It appears on other websites !

**Comment by githubsaturn** [comment]
Ah okay, that's better... This looks like a serious Certbot issue. 

The error is you're getting is not thrown by CapRover, it's thrown by Certbot's servers when they try to reach api.pictalk.xyz.

Try this:
- Shell into your certbot container
```
docker exec -it $(docker container ls --filter name=captain-captain | awk 'FNR == 2 {print $1}') /bin/sh
```
And try to run the command manually for renewal:
```
certbot renew
```

Then collect all the data and open an issue here: https://github.com/certbot/certbot

**Comment by Ratatinator97** [comment]
> Ah okay, that's better... This looks like a serious Certbot issue.
> 
> The error is you're getting is not thrown by CapRover, it's thrown by Certbot's servers when they try to reach api.pictalk.xyz.
> 
> Try this:
> 
>     * Shell into your certbot container
> 
> 
> ```
> docker exec -it $(docker container ls --filter name=captain-certbot | awk 'FNR == 2 {print $1}') /bin/sh
> ```
> 
> And try to run the command manually for renewal:
> 
> ```
> certbot renew
> ```
> 
> Then collect all the data and open an issue here: https://github.com/certbot/certbot

As I deleted the certificate it won't appear on `certbot renew`. How can I add it "like caprover"

**Comment by Ratatinator97** [comment]
And do you know how can I hard reset the certbot of my CapRover ? Because the issue occurs too with all .pictalk.xyz domains ...
i.e : apiprod.pictalk.xyz is affected too !

**Comment by githubsaturn** [comment]
what do you mean by hard reset?
