### ISSUE TITLE
[Question] Caprover "Something bad happend"

### ISSUE THREAD

**Issue by vacoup95** [caprover/caprover#1090]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

I had a VPS a while ago it was running smoothly for almost an entire year, then I updated Caprover on it. "Something bad happend". looking in the console at XHR requests gives no useful information either. So I migrated all my data to a new more powerful VPS with more storage. Because I just couldn't get it to work anymore on the old one. Now after a few weeks of usage it is giving me the same problem: "Something bad happend". 

This error happens when deploying an application I am running a VPS with 4GB ram, 3 VCPU (shared) and 80GB of storage space. I've verified there's enough space, I have no idea idea what the issue is.

How do I figure out what's underneath the "Something bad happend" error and how do I fix this? Because it seems like this is due to the Caprover update I never had any issues before and I am not running more or less docker containers on it now.

**Comment by githubsaturn** [comment]
Something bad happens is an unannotated error. To get more info, when this happens, just get the logs from your CapRover instance:
```
docker service logs captain-captain --since 5m
```

**Comment by githubsaturn** [comment]
Feel free to reopen when you have more logs.
