### ISSUE TITLE
Web Terminal Interface per app

### ISSUE THREAD

**Issue by rafaelstz** [caprover/caprover#1092]
**Is your feature request related to a problem? Please describe.**
The complexity to access quickly each project via SSH to verifications or tests.

**Describe the solution you'd like**
A web terminal interface to access each application using the same method that we have the logs in real-time per app.

**Describe alternatives you've considered**
A general SSH panel to the main server.

**Comment by githubsaturn** [comment]
See https://github.com/caprover/caprover/issues/705
