### ISSUE TITLE
Use Github access token to pull repo because of deprecation notice

### ISSUE THREAD

**Issue by s-kris** [caprover/caprover#1096]
From August 2021, github won't allow password-based access to repos. 
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

It'd be nice to have a token-based git-deploy option instead of a username/password combo.

Thank you

**Comment by githubsaturn** [comment]
Token based clones are no different that password based clones. 

https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token#using-a-token-on-the-command-line

You just need to use your Personal Token instead of your password.

**Comment by s-kris** [comment]
Oops. This should work!!
Do you have any plan to authenticate with github or pull in repos using token?

**Comment by githubsaturn** [comment]
Typically we don't introduce vendor specific logic as part of the core. We may introduce ability for plugins and such to make the integration easier, but definitely not part of the core due to cost of maintenance and continuously chasing API changes.

**Comment by s-kris** [comment]
Perfect, I will be waiting for plugin architecture and the things community will build.
