### ISSUE TITLE
Port 3000 check fail

### ISSUE THREAD

**Issue by polotto** [caprover/caprover#1099]
What is the problem?

- When I try execute the start command the port 3000 check always fail:

```
> caprover@0.0.0 start /usr/src/app
> node ./built/server.js

Captain Starting ...
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
     
 
 
 
 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 8349 MB
 
 
Are your trying to run CapRover on a local machine or a machine without public IP?
In that case, you need to add this to your installation command:
    -e MAIN_NODE_IP_ADDRESS='127.0.0.1'   
 
 
 
Otherwise, if you are running CapRover on a VPS with public IP:
Your firewall may have been blocking an in-use port: 3000
A simple solution on Ubuntu systems is to run "ufw disable" (security risk)
Or [recommended] just allowing necessary ports:
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp; 
     
     
See docs for more details on how to fix firewall issues
 
Finally, if you are an advanced user, and you want to bypass this check (NOT RECOMMENDED),
you can append the docker command with an addition flag: -e BY_PASS_PROXY_CHECK='TRUE'
 
 
Installation failed.
Error: Port timed out: 3000
    at Timeout._onTimeout (/usr/src/app/built/utils/CaptainInstaller.js:137:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`
```

Steps to reproduce the problem:

- Execute the starting command:

```
sudo docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

Answers to the following questions where applicable:
- Your OS and version?: Ubuntu Server 18 LTS (Azure)
- RAM?: 8Gb

Is that port check working correctly? I checked all my firewall rules and the port 3000 is opened.
What's the port 3000 is needed?

**Comment by githubsaturn** [comment]
During the installation CapRover tries to prechecks all the requirements. One of these requirements is port checking. Port 3000 is used for initial installation. 

This check failing shows that either that port is blocked on a firewall or your network setup doesn't allow the container to dial back to itself. The second case is not a blocker, that's why the installation process allows you to bypass this check via `BY_PASS_PROXY_CHECK`.

Having said that if your port 3000 is actually blocked by a firewall, you won't be able to perform the initial setup of CapRover

**Comment by githubsaturn** [comment]
Those are used by nginx container. For the initial setup, user needs to talk to the main container directly without nginx being in the loop.

**Comment by polotto** [comment]
Can this be a security risk in Caprover?

**Comment by githubsaturn** [comment]
Why would it be?

**Comment by polotto** [comment]
Some intruder can use the 3000 port to setup the server too. Is that blocked after first configuration?

**Comment by githubsaturn** [comment]
It's redirected to https after the first installation. Also, your password is no longer captain42 after the initial setup

**Comment by polotto** [comment]
Why there is other ports in the firewall configuration? Like 996,7946,4789,2377.

**Comment by githubsaturn** [comment]
https://caprover.com/docs/firewall.html
