### ISSUE TITLE
Add support for `--cap-add` arguments

### ISSUE THREAD

**Issue by dramikei** [caprover/caprover#1100]
**Is your feature request related to a problem? Please describe.**
Yes, currently Caprover does not support parsing of `--cap-add` in its yml mainly because support for `--cap-add` was missing in `docker swarm` which caprover uses (refer: #683). Adding `--cap-add` would enable many more one-click-apps to be built for CapRover such as caprover/one-click-apps#222 and Wireguard.

**Describe the solution you'd like**
Support for `cap-add` was added in `docker swarm 20.10.0` refer: docker/cli#2687. Therefore, CapRover only needs to implement the parsing of `cap-add` in the one-click-apps yml and implement the necessary functions to get it working.

**Describe alternatives you've considered**
Alternative solutions to this prior to docker/cli#2687 were running the apps in a 'hacky' way which were more mere workarounds and probably had security concerns (And therefore were not promoted). 

**Additional context**
docker/cli#2687
moby/moby#25885
[how to set linux capabilities on docker swarm mode](https://serverfault.com/questions/824516/how-to-set-linux-capabilities-on-docker-swarm-mode-service-invocations/824548) (Check the 2nd answer)

**Comment by dramikei** [comment]
Okay
Would be a bit user-unfriendly until CapRover updates API but that shouldnt hinder one-click-apps development :)

**Comment by amircloner** [comment]
can use --cap-add  in 
Pre-Deploy Script
or
Service Update Override

**Comment by Alfagun74** [comment]
> CapRover currently uses v1.40 API to talk to Docker. `CapabilityAdd` is [added in 1.41](https://docs.docker.com/engine/api/version-history/#v141-api-changes).
> 
> Until we make a breaking change and up the requirement to 1.41, users can manually add the capability using cli:
> 
> ```
> docker service update --cap-add SOMETHING srv-captain--yourappname 
> ```

Is this a permanent solution? Does the Cap-Add Still exist on restart etc.?

**Comment by Alfagun74** [comment]
I just tested and it is not a permanent solution. How would you solve this forever @githubsaturn ?
Why wont we just update Caprovers Docker Swarm API to 1.4.1 to support this feature?

**Comment by githubsaturn** [comment]
`--cap-add` should persists after restarts. Did you double check after running `docker service inspect` ?

**Comment by Alfagun74** [comment]
as soon as i update an environment variable or my app the cap-add is gone. The update to 1.4.1 API would really help me.

**Comment by ronaldloyko** [comment]
> can use --cap-add in Pre-Deploy Script or Service Update Override

Unfortunately, using Service Update Override does not work for me.

I did the following steps to test:

1) Go to [Your App Name] > App Configs
2) Add following content to **Service Update Override**:

```json
{
  "TaskTemplate": {
    "ContainerSpec": {
      "Env": ["A=1"],
      "CapabilityAdd": ["CAP_NET_ADMIN", "CAP_SYS_ADMIN"]
    }
  }
}

```

3) Run command `docker service inspect [Your App Name]`

The `Env` is added but **not** `CapabilityAdd`.
Docker version is `Docker version 20.10.18, build b40c2f6`.

**Comment by Alfagun74** [comment]
> > can use --cap-add in Pre-Deploy Script or Service Update Override
> 
> Unfortunately, using Service Update Override does not work for me.
> 
> I did the following steps to test:
> 
> 1) Go to [Your App Name] > App Configs
> 2) Add following content to **Service Update Override**:
> 
> ```json
> {
>   "TaskTemplate": {
>     "ContainerSpec": {
>       "Env": ["A=1"],
>       "CapabilityAdd": ["CAP_NET_ADMIN", "CAP_SYS_ADMIN"]
>     }
>   }
> }
> 
> ```
> 
> 3) Run command `docker service inspect [Your App Name]`
> 
> The `Env` is added but **not** `CapabilityAdd`.
> Docker version is `Docker version 20.10.18, build b40c2f6`.
> 

Yeah because the API Caprover uses is still outdated. It doesn't know CapAdd yet.

**Comment by githubsaturn** [comment]
That's correct. But you can manually change the API version via [config override](https://caprover.com/docs/troubleshooting.html#customize-config-settings).

The variable to update is `dockerApiVersion`

**Comment by Alfagun74** [comment]
What is keeping you from updating it for everyone?

**Comment by githubsaturn** [comment]
I will in the next version. What kept me from updating it so far: the chaos it caused as lots of instances across the globe went offline because people didn't read update notes and they had an outdated Docker engine. 

We should be fine in the next version as it's been almost 2 years since 1.41 is released

**Comment by ronaldloyko** [comment]
Hi @githubsaturn 
Thanks for clarifying.

I'm currently creating several one-click-apps that would require `CapabilityAdd` (like OpenVPN, Mailu etc.)
I would add a warning to `instructions.start` indicating that API `v1.4.1` is required and also briefly explain how to set it via the config override. And in `instructions.end` I would instruct to add the `CapabilityAdd` bit to the Service Update Override.
Are you ok with already adding them to CapRover's one-click-apps repository?

Otherwise, I would set up a seperate repository that users can add in the meantime until the API is updated.
Once it is updated, I would then transfer the apps to the official repository.

**Comment by ronaldloyko** [comment]
> > Hi @githubsaturn
> > Thanks for clarifying.
> > I'm currently creating several one-click-apps that would require `CapabilityAdd` (like OpenVPN, Mailu etc.)
> > I would add a warning to `instructions.start` indicating that API `v1.4.1` is required and also briefly explain how to set it via the config override you mentioned. And in `instructions.end` I would instruct to add the `CapabilityAdd` bit to the Service Update Override.
> > Are you ok with already adding them to CapRover's one-click-apps repository?
> > Otherwise, I would set up a seperate repository that users can add in the meantime until the API is updated in CapRover.
> > Once it is updated, I would then transfer the apps to the official repository.
> 
> Instead of building all kind of warnings and crutches into the next Version, it would be smarter to make it work with 1.41 wouldn't it?

I was talking about the one-click-apps, not CapRover itself.

**Comment by githubsaturn** [comment]
> Hi @githubsaturn Thanks for clarifying.
> 
> I'm currently creating several one-click-apps that would require `CapabilityAdd` (like OpenVPN, Mailu etc.) I would add a warning to `instructions.start` indicating that API `v1.4.1` is required and also briefly explain how to set it via the config override you mentioned. And in `instructions.end` I would instruct to add the `CapabilityAdd` bit to the Service Update Override. Are you ok with already adding them to CapRover's one-click-apps repository?
> 
> Otherwise, I would set up a seperate repository that users can add in the meantime until the API is updated in CapRover. Once it is updated, I would then transfer the apps to the official repository.

Yea that sounds good. Once the API is leveled up, we can change the instructions.

**Comment by marcusique** [comment]
@ronaldloyko, it looks like `CapabilityAdd` isn't getting added even after I've bumped the Docker API version to v.1.41
```
cat /captain/data/config-override.json 
{"dockerApiVersion":"v1.41"}
```
Here's the service inspect:

```
> docker service inspect srv-captain--ovpn
> [
>   {
>     "ID": "52otl5lte66fr2i4lfwa9pn6b",
>     "Version": {
>       "Index": 6402
>     },
>     "CreatedAt": "2023-01-05T11:37:25.779756935Z",
>     "UpdatedAt": "2023-01-05T11:37:36.294349371Z",
>     "Spec": {
>       "Name": "srv-captain--ovpn",
>       "Labels": {},
>       "TaskTemplate": {
>         "ContainerSpec": {
>           "Image": "linuxserver/openvpn-as:2.9.0-5c5bd120-Ubuntu18-ls124",
>           "Labels": {
>             "randomLabelForceUpdate": "50a3845d-5371-4424-a6c9-008ef9d18ed7"
>           },
>           "Hostname": "ovpn.myhostname.io",
>           "Env": ["PUID=1000", "PGID=1000", "TZ=UTC", "INTERFACE="],
>           "Mounts": [
>             {
>               "Type": "volume",
>               "Source": "captain--ovpn",
>               "Target": "/config"
>             }
>           ],
>           "StopGracePeriod": 10000000000,
>           "DNSConfig": {},
>           "Isolation": "default"
>         },
>         "Resources": {},
>         "RestartPolicy": {
>           "Condition": "any",
>           "Delay": 5000000000,
>           "MaxAttempts": 0
>         },
>         "Placement": {
>           "Constraints": ["node.id == zjbg2gipiq46j5vfqrj1egjes"]
>         },
>         "Networks": [
>           {
>             "Target": "5um98fiwm2su954poz08cew3s"
>           }
>         ],
>         "LogDriver": {
>           "Name": "json-file",
>           "Options": {
>             "max-size": "512m"
>           }
>         },
>         "ForceUpdate": 0,
>         "Runtime": "container"
>       },
>       "Mode": {
>         "Replicated": {
>           "Replicas": 1
>         }
>       },
>       "UpdateConfig": {
>         "Parallelism": 0,
>         "FailureAction": "pause",
>         "Monitor": 5000000000,
>         "MaxFailureRatio": 0,
>         "Order": "stop-first"
>       },
>       "RollbackConfig": {
>         "Parallelism": 1,
>         "FailureAction": "pause",
>         "Monitor": 5000000000,
>         "MaxFailureRatio": 0,
>         "Order": "stop-first"
>       },
>       "EndpointSpec": {
>         "Mode": "vip",
>         "Ports": [
>           {
>             "Protocol": "tcp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "tcp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           }
>         ]
>       }
>     },
>     "PreviousSpec": {
>       "Name": "srv-captain--ovpn",
>       "Labels": {},
>       "TaskTemplate": {
>         "ContainerSpec": {
>           "Image": "img-captain-ovpn:0",
>           "Labels": {
>             "randomLabelForceUpdate": "0385014b-851c-4afd-9d08-d3b81155a830"
>           },
>           "Hostname": "ovpn.myhostname.io",
>           "Env": ["PUID=1000", "PGID=1000", "TZ=UTC", "INTERFACE="],
>           "Mounts": [
>             {
>               "Type": "volume",
>               "Source": "captain--ovpn",
>               "Target": "/config"
>             }
>           ],
>           "Isolation": "default"
>         },
>         "Placement": {
>           "Constraints": ["node.id == zjbg2gipiq46j5vfqrj1egjes"]
>         },
>         "Networks": [
>           {
>             "Target": "5um98fiwm2su954poz08cew3s"
>           }
>         ],
>         "LogDriver": {
>           "Name": "json-file",
>           "Options": {
>             "max-size": "512m"
>           }
>         },
>         "ForceUpdate": 0,
>         "Runtime": "container"
>       },
>       "Mode": {
>         "Replicated": {
>           "Replicas": 1
>         }
>       },
>       "UpdateConfig": {
>         "Parallelism": 0,
>         "FailureAction": "pause",
>         "MaxFailureRatio": 0,
>         "Order": "stop-first"
>       },
>       "EndpointSpec": {
>         "Mode": "vip",
>         "Ports": [
>           {
>             "Protocol": "tcp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "tcp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           }
>         ]
>       }
>     },
>     "Endpoint": {
>       "Spec": {
>         "Mode": "vip",
>         "Ports": [
>           {
>             "Protocol": "tcp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 9443,
>             "PublishedPort": 9443,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "tcp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           },
>           {
>             "Protocol": "udp",
>             "TargetPort": 1194,
>             "PublishedPort": 1194,
>             "PublishMode": "ingress"
>           }
>         ]
>       },
>       "Ports": [
>         {
>           "Protocol": "tcp",
>           "TargetPort": 9443,
>           "PublishedPort": 9443,
>           "PublishMode": "ingress"
>         },
>         {
>           "Protocol": "udp",
>           "TargetPort": 9443,
>           "PublishedPort": 9443,
>           "PublishMode": "ingress"
>         },
>         {
>           "Protocol": "tcp",
>           "TargetPort": 1194,
>           "PublishedPort": 1194,
>           "PublishMode": "ingress"
>         },
>         {
>           "Protocol": "udp",
>           "TargetPort": 1194,
>           "PublishedPort": 1194,
>           "PublishMode": "ingress"
>         }
>       ],
>       "VirtualIPs": [
>         {
>           "NetworkID": "5um98fiwm2su954poz08cew3s",
>           "Addr": "10.0.1.88/24"
>         },
>         {
>           "NetworkID": "avjjhxr5thl8livdh7rappwif",
>           "Addr": "10.0.0.41/24"
>         }
>       ]
>     },
>     "UpdateStatus": {
>       "State": "paused",
>       "StartedAt": "2023-01-05T11:37:31.573063992Z",
>       "Message": "update paused due to failure or early termination of task xvwg6y39zi8skdz364y5ouamw"
>     }
>   }
> ]
> 
```

I even restarted my server and still nothing.
I'm using `caprover/caprover-edge:latest`
@githubsaturn maybe that has something to do with it?

**Comment by guilh22** [comment]
I added cap_add ability to caprovere. It is under review
https://github.com/caprover/caprover/pull/2103
https://github.com/caprover/caprover-frontend/pull/151
