### ISSUE TITLE
Batch enabling of https

### ISSUE THREAD

**Issue by janericwinkelmann** [caprover/caprover#1101]
We have quite a few clients with a lot of domains. Therefore we need to link a lot of them in Caprover. Either on the app itself or on an nginx-redirect app. If you have to connect about 30 - 40 domains (or subdomains like www.) to the app this becomes quite a time consuming task to do. Wouldn't it be great to make some kind of batch processing possible inside the HTTP settings?

**Comment by githubsaturn** [comment]
First thing first, there are limits that are imposed by Let's Encrypt. Make sure you don't hit those: https://letsencrypt.org/docs/rate-limits/


Second, for scripting and automation, you can use `caprover api` [command](https://github.com/caprover/caprover-cli#api). It's not well documented. But it's not too hard to understand if it's something that you need.

**Comment by vohzd** [comment]
If it helps, here's some NodeJS code which I use for this. It's just some functions which wrap the caprover api

```
async function registerSubdomain(domain){
  try {
    const { stdout, stderr } = await exec(`caprover api \
      -u  ${process.env.CAPROVER_URL} \
      -p ${process.env.CAPROVER_PASSWORD } \
      -t "/user/apps/appDefinitions/customdomain" \
      -m "POST" \
      -d '{ "appName": "${ appName }", "customDomain": "${domain} }' \
    `);
    return stdout
  }
  catch (e){
    console.log(e);
    throw e
  }
}

async function removeSubdomain(domain){
  try {
    const { stdout, stderr } = await exec(`caprover api \
      -u ${process.env.CAPROVER_URL} \
      -p ${process.env.CAPROVER_PASSWORD } \
      -t "/user/apps/appDefinitions/removecustomdomain" \
      -m "POST" \
      -d '{ "appName": "${appName}", "customDomain": "${domain} }' \
    `);
    return stdout
  }
  catch (e){
    console.log(e);
    throw e
  }
}

async function enableSSL(domain){
  try {
    const { stdout, stderr } = await exec(`caprover api \
      -u ${process.env.CAPROVER_URL} \
      -p ${process.env.CAPROVER_PASSWORD } \
      -t "/user/apps/appDefinitions/enablecustomdomainssl" \
      -m "POST" \
      -d '{ "appName": "${appName}", "customDomain": "${domain}" }' \
    `);
    return stdout
  }
  catch (e){
    console.log(e);
    throw e
  }
}
```
