### ISSUE TITLE
Any way to do quick setup via preconfigured files?

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1104]
**Is your feature request related to a problem? Please describe.**
I'm setting up CapRover quite often and it's quite a common things to do - install it, assign DNS name, make it HTTPS, create quick app or setup up app from the GitHub. It's all repetitive boring stuff - is there any way to automate that?

**Describe the solution you'd like**
Ideally, something like `--with-config=config.[yml|json|md|...]` option would be a wonderful thing - where I keep a number of config files, for a typical tasks, where I just change the DNS name, etc.
If automated configuration fails, it just rolls back or something like that.

**Describe alternatives you've considered**
Documenting things - I have a doc, that describes step by steps things to do.

**Additional context**
I'm running CapRover mostly as a local Heroku, installing MinIO & database as required; sometimes - just as a host for one-click apps.

**Comment by githubsaturn** [comment]
This is already available, you can see the docs here:
https://github.com/caprover/caprover-cli#server-setup


Any further automation such as DNS changes and etc require some vendor-specific logic. CapRover is completely vendor agnostic. While it is completely doable to automate everything from the get-go, vendor-specific scripts will not be part of CapRover core.

**Comment by alexander-potemkin** [comment]
It’s lovely, thank you!
