### ISSUE TITLE
Caprover instance exited on shutdown

### ISSUE THREAD

**Issue by koolamusic** [caprover/caprover#1105]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I am running `caprover/caprover    1.6.1 ` on GCP, I shutdown my servers and made some network updates. (IP and VPC network stuff) none directly on the instance as it was shutdown the whole time. This server mostly had `mysql, wordpress, nginx` related projects. no custom configurations or anything just out of the box use as they came installed. 

So at the moment restarting this server instance (compute engine) I no longer see a caprover service running, so I am confused as to why that is the behaviour. 

- there are no containers with `docker container ls -a`
- There are no services running with `docker service ls` I get the error 
```sh
Error response from daemon: This node is not a swarm manager. 
Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```
However all the docker images are present, so I'm certain I am still on the right machine, as to how to recoup the configurations for this server I dont know I can recover the projects tbh. 

My last trial was to `re-run` the docker image for caprover to do a fresh install. and see if any configuration files maybe in-memory could be re-used, not even sure how the mapping is, but I just took the risk anyway. This is the error I get. 

```sh
 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 1774 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v0.29.1
May 14th 2021, 9:14:54.066 am    Fresh installation!
May 14th 2021, 9:14:54.069 am    Starting swarm at 34.83.175.98:2377
Installation failed.
{ Error: (HTTP code 503) unexpected - This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one. 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: undefined,
  statusCode: 503,
  json:
   { message:
      'This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.' } }

```

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

**Comment by koolamusic** [comment]
output of `uname -a` 
*4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux*

**Comment by koolamusic** [comment]
In another machine where I can still see the container images.
I get this error when trying to start `caprover` 


```
Error response from daemon: network cyz8lja0omtu72ha3ks6734vb not found
Error: failed to start containers: captain-captain.1.q69t6t0tfj8eetl7wuksl1plw

``

**Comment by koolamusic** [comment]
So it seems I may manually need to revive caprover / docker here, just not sure how I would approach this though.

**Comment by koolamusic** [comment]
A total 6 VMs were affected in this update. 
There are also spread across asia-northeast, europe-west.... so it' not a single region failure or something. 

two out of all 6 were affected in this manner.

**Comment by githubsaturn** [comment]
It doesn't seem like this is CapRover related. 

The first error that you saw, "this node is not a swarm manager", is the root cause. Something that you changed caused this node to get kicked out of swarm as a manager. 

If you are able to reproduce the issue, you can file an issue with docker swarm at github.com/moby/moby

**Comment by githubsaturn** [comment]
Feel free to reopen if this turns out to be a CapRover issue.

**Comment by nmitra6** [comment]
Facing similar problem. Server was stopped for a while. When restarted, docker info shows that the let's encrypt certificate expired. Error message shows

Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

How to remove the old certificate and add a new one from cli

**Comment by githubsaturn** [comment]
> docker info shows that the let's encrypt certificate expired

`docker info` has nothing to do with let's encrypte certificates. The expired note refers to Docker's internal certificate. 

As mentioned above, this is a Docker swarm question:
https://stackoverflow.com/questions/59072770/swarm-certificates-have-expired

**Comment by githubsaturn** [comment]
Keep in mind that leaving and re-initializing swarm may result in data loss.
