### ISSUE TITLE
Feature Request: Restart / Stop / Start an Application / Container

### ISSUE THREAD

**Issue by helmiatincrypto** [caprover/caprover#1107]
**Is your feature request related to a problem? Please describe.**
This problem isn't happening yet to me, But It would be nice if there is a button to Restart / Stop / Start an application/container.
In some cases, if the application uses many of ram, We could stop it immediately using a button to stop the application/container.

**Describe the solution you'd like**
Add button to restart / stop / start an application / container

**Comment by githubsaturn** [comment]
It's already possible.

You can set the instance count to zero to effectively stop the app.

To restart, you can simply click on save and update button.
