### ISSUE TITLE
Ability to bind (persistent data) application to a specific server in cluster

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1108]
Hello and thank you again for creating CapRover. I'm considering using CapRover in the following configuration:
* 1 CapRover instance
* 3 servers (added to the CapRover cluster)
* 3 applications, with the same Docker image, but running and available under a different sub-domain names - app1.sub-domain.server.com, app2.sub-domain.server.com, app3.sub-domain.server.com

This app has persistent data and to make sure it won't get lost + to make sure a proper resource allocation, I would love to bind app1 to server1, app2 to server2, and app3 to server3.

Is that a possible scenario to implement with CapRover?
If not, any recommendations? I'm serving a custom-created app on per user basis (1 app instance = 1 user) and would like to make sure there are no conflicts and have all of the benefits of CapRover managing the rest.

**Comment by alexander-potemkin** [comment]
And a sub-question here: if I have a two servers cluster running one app, will my app (with persistent data) be restored in a second cluster, if the first one is failing?

I guess it wouldn’t, because the data is not shared; if that’s the case, would it be restored on my second node, if the app is stateless?

**Comment by githubsaturn** [comment]
> Is that a possible scenario to implement with CapRover?

Yes, to do so:
- Create an app with Persistent Data checkbox checked
- Go to your app configs > Config tab > Node ID and change the Node ID to a specific server. You can view your node IDs from the Cluster tab in CapRover.


> if I have a two servers cluster running one app, will my app (with persistent data) be restored in a second cluster, if the first one is failing (fail-over scenario)?

As you guessed, that's not possible. Apps with persistent data should reside on one node.

**Comment by alexander-potemkin** [comment]
Thank you!
