### ISSUE TITLE
[Question] Github Deployment with Additional Data

### ISSUE THREAD

**Issue by jcuenod** [caprover/caprover#1109]
I have a github repo that I want to deploy on my caprover instance but it's a public repo that I don't push a data file to (it's a postgres docker image but it has extra bells and whistles that the default pg images don't support). I'm seeding the db with:

```Dockerfile
ADD ["my_data.sql.gz", ..., "/docker-entrypoint-initdb.d/"]
```

Is there a way (e.g. in the captian-definition) to tell Caprover to fetch `my_data.sql.gz` from somewhere (secret/authenticated) before building?

The alternative I have in mind is to fork my public repo into a private one, upload the data there and then connect that one to caprover.

**Comment by githubsaturn** [comment]
You can enter your repo information in CapRover, for public repos, you can use fake username and password.

And to trigger the build, you can simply click on "Force Build" button. It fetches the repo and does exactly what you need it to do.

**Comment by jcuenod** [comment]
Actually, this doesn't answer my question.

I know how to trigger builds. I'm wondering if there's a way to get additional data that is *NOT* already in the repo and, preferably, stored somewhere that requires secrets to access.

**Comment by githubsaturn** [comment]
Multiple ways you can do that. But there are not specific to CapRover. 
1- You can do that via an `ADD` [command](https://docs.docker.com/engine/reference/builder/#add). You can use http resources in your `ADD` argument. Like this:
```
ADD https://www.domain.com/file.gzip /files/
```

2- Use wget or curl
```
RUN wget https://www.domain.com/file.gzip
```

**Comment by githubsaturn** [comment]
Depending on how you do the secret, you can use either of these methods. If your secret is passed as a query parameter you can use either. If your secret is a header value, you'll have to use a more complex curl command, like this:
```
RUN curl  https://example.com/file.gzip
  -H 'x-secret: 123412341234' \
  --output file.gzip
```

**Comment by jcuenod** [comment]
So there's no way for caprover to pass a secret into a repo deployment?

**Comment by githubsaturn** [comment]
Yes, you can use env vars for this purpose. Read [here](https://caprover.com/docs/app-configuration.html#environment-variables).

In short create an env var called `CAPROVER_SECRET` with the proper value in your dashboard. Then add this bit to your Dockerfile:
```
ARG CAPROVER_SECRET=DEFAULT_WRONG
ENV CAPROVER_SECRET=${CAPROVER_SECRET}

# At this point, in your build process, CAPROVER_SECRET env var is available.
```
