### ISSUE TITLE
"Nothing here yet" after domain attach

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1111]
Latest CapRover version, steps to reproduce:
- install CapRover 1.9.0
- enter into web dashboard
- link the DNS name
- got redirected to the dashboard under HTTP**S** (https://captain.sub.sub.domain.name)
- see nothing is here page

To fix things:
- remove config-captain.json, which only contains:
```
{
        "namespace": "captain",
        "customDomain": "subdomain.subdomain.domain.io"
}
```
- restart caprover
- get into IP configuration phase again (and if you add DNS name again, it happens exactly the same way).

**Comment by alexander-potemkin** [comment]
Same on 1.8.2...

**Comment by alexander-potemkin** [comment]
Same if I remove subdomain of sub-domain, leaving just subdomain.domain.io.

I'm also concerned, why I got redirected to HTTPS automatically...

**Comment by alexander-potemkin** [comment]
Tried with a completely different domain name (to check it's not some specific DNS issue of AWS), but got exactly the same issue.

**Comment by alexander-potemkin** [comment]
Managed to make it work with `caprover serversetup` under a different domain name (the one I don't need); but I can't get my desired DNS name configuration.

It could be related to the fact, that letsencrypt is not issuing SSL certificate under desired name - it feels like, if SSL certificate can't be issues, the DNS name mapping won't happen either.

If that's the case, any quick work-around would be much appreciated (until my limits on let's encrypt will be available back)!

**Comment by githubsaturn** [comment]
You enter `http://captain.sub.sub.domain.name` and you get redirected to `https` version? If so, it's not CapRover unless you've enabled HTTPS which appears to be not the case. 

The only way it happens is that you've previously enabled FORCE HTTPS and your browser has it cached.

**Comment by perzeuss** [comment]
Sounds like an DNS configuration issue. 
Fyi Some DNS providers have HTTPS redirects enabled by default.

**Comment by alexander-potemkin** [comment]
@githubsaturn , I definetely didn't enable force HTTPS and it doubt it could get cached in browser - I can't recall I ever visited it via HTTPS.

@perzeuss , I doubt that's possible, just per DNS protocol definition, but to ensure I'm not missing anything I checked (AWS DNS) and nothing like that, and checked the documentation it doesn't seem to be possible on they side neither.

I have a feeling or fantasy that CapRover was never thoroughly tested in the cases, when Let's Encrypt doesn't issue the certificate, so it feels that something goes wrong when SSL certificate is not issued.

I'm sorry for such a loosy description, but it's all I've got for now.

**Comment by githubsaturn** [comment]
It's not the issue with Let's Encypted failing. You're captain config file shows that CapRover doesn't believe you have SSL. So it's working as excepted. Feel free to reopen if this happens to you again and if you have a reproducible case for this.

**Comment by alexander-potemkin** [comment]
@githubsaturn , I'm not sure I understand why it's not an issue.

1. I setup Captain
2. I attached domain
3. I tried to enable SSL -> it failed
4. When I tried to enter the domain, which was working on step 2, I'm seeing 'Nothing here yet', instead of the proper captain's page.

I hope this will never re-occur, because I had to reconfigure my instance quite a few times, before I figured out it's failing on let's encrypt, but it shall be quite easy to reproduce as well, I guess (by making let's encrypt script to fail on purpose)?

**Comment by githubsaturn** [comment]
> When I tried to enter the domain, which was working on step 2, I'm seeing 'Nothing here yet', instead of the proper captain's page

Two possibilities:
1- Either your browser had cached HTTPS 
2- Or, you were mistakenly copy pasting a link with HTTPS

I did try failing the Let's Encrypt process, but things are working fine. You can easily reproduce the Let's Encrypt failure if you try to setup a CapRover instance on https://labs.play-with-docker.com

Next time it happens, make sure you do this:
- Restart your server to make sure nothing is cached on the server
- Run `curl http://captain.your.domain.com -v` and paste the results here. Make sure you use `http` without "s".

**Comment by alexander-potemkin** [comment]
Thanks, especially for the `curl` thing - I didn't consider it for some reason, appreciate that!

**Comment by kamzata** [comment]
Same here. Just installed. I've got HSTS enabled on my entire domain, so it always redirects on https. How can I solve?

**Comment by githubsaturn** [comment]
You shouldn't enable HSTS until your setup is finalized.

**Comment by kamzata** [comment]
> You shouldn't enable HSTS until your setup is finalized.

The HSTS Preload is set on the entire domain. Now I'm using a subdomain for testing. So, doesn't Caprover work with HSTS enabled?

**Comment by githubsaturn** [comment]
Correct. The initial installation process needs to be done through HTTP because at that point there is no SSL cert issued to your domain, hence HTTPS doesn't work.

**Comment by githubsaturn** [comment]
Post installation, HSTS can be enabled.

**Comment by kamzata** [comment]
> Post installation, HSTS can be enabled.

I cannot disable HSTS for this domain (it's in production now). I'm using Cloudflare to manage the DNS. Could I use DNS challenge for the cert issue?

**Comment by kamzata** [comment]
> No. CapRover is not your dns provider. It doesn't receive the ping for dns challenge

Doesn't Caprover use Certbot?

**Comment by githubsaturn** [comment]
What does it have anything to do with being a DNS provider? Certbot is just tool for interacting with LetsEncrypt API.

**Comment by kamzata** [comment]
> What does it have anything to do with being a DNS provider? Certbot is just tool for interacting with LetsEncrypt API.

Because Certbot can use the [Cloudflare plugin](https://certbot-dns-cloudflare.readthedocs.io/en/stable/) which uses the DNS challenge to get the cert, so there's no need to have the port 80 opened. Am I wrong?

**Comment by githubsaturn** [comment]
I see what you're saying. No CapRover manages your SSL certs using the basic challenge.
