### ISSUE TITLE
[Question] Re-initialize Caprover (local -> public)

### ISSUE THREAD

**Issue by marcusique** [caprover/caprover#1115]
I installed Caprover locally on my Raspberry Pi (Ubuntu) for testing purposes with the following command:

`sudo docker run -p 80:80 -p 443:443 -p 3000:3000 -e MAIN_NODE_IP_ADDRESS='127.0.0.1'  -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-edge`

I already have some apps running there that obviously don't accept inbound connections, but now I want to move forward and make them publicly available. I have a domain name registered and I want to point it to my IP address. As far as I understand I need to re-initialize Caprover in the following way:
- Terminate current installation
- Re-initialize with `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`
- Then continue with `caprover-serversetup`

The thing is that I don't want to lose the apps I already have running there as some of them contain persisnent data – backing it up and restoring will be a bit of a pain (not sure if it's even possible with docker images). I can of course manually re-deploy everything, but I was wondering if there's any way I can turn my local installation into a public one without re-building everything from scratch? It would be really great and would save me a whole lot of time.
Thanks you in advance!

**Comment by githubsaturn** [comment]
You don't need to redeploy everything. Just update your image to none edge:
```
docker service update captain-captain --image caprover/caprover:latest
```

Then port forward from your router to your raspberry pie and run `caprover serversetup` from your machine.
