### ISSUE TITLE
issue with prune preventing services from starting

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#1119]
I ran into an issue on 1.9.0 today.  I restarted the box the other day after a long uptime, and did a `docker system prune`.  It apparently removed some of the necessary build artifacts for some apps.

For some, I had to just smash the force build button, and they rebuilt okay from git.  (The build queue is a bit frustrating - I have a big multicore machine with tons of ram and a dozen fast flash disks, I should be able to do many parallel builds of apps.)  Some were apps I'd created in CR (so I could make persistent volumes) then pasted in a short captain-definition file with an `imageName` to deploy an existing DH image. (Thanks for adding the method six "deploy image" stanza, btw, this is a nice timesaver.) 

The problem with this is that in the deploy log, it lists it as `img-captain-$APPNAME:$n`, not the actual deployed image.  Months later, I don't have any record of which specific image I deployed.  When deploying from pasted-in captain-definition file, or via imageName (methods 5/6), would it be possible to set the image name in the version history to the upstream image instead of the opaque name it uses now?

In any case, doing a prune totally broke a number of my apps, because of this weird sub-image architecture when deploying a specified image into an existing CR app (it does a null rebuild to make a derived image, it looks like).  I'm not sure what an appropriate fix is, I just wanted to give some feedback on the issue I ran into.  I probably just won't prune the CR box anymore.

**Comment by githubsaturn** [comment]
> In any case, doing a prune totally broke a number of my apps, because of this weird sub-image architecture when deploying a specified image into an existing CR app (it does a null rebuild to make a derived image, it looks like). I'm not sure what an appropriate fix is, I just wanted to give some feedback on the issue I ran into. I probably just won't prune the CR box anymore.

3 years ago, when I started this project I noticed this bug, and I opened an [issue on Docker's github](https://github.com/moby/moby/issues/36295). But they haven't fixed it yet. They are arguing that it's working as expected. That's a while ago I decided to go and implement a basic image pruning feature within CapRover (settings > delete unused images). The CapRover one is safe and it preserves the images. 



> The problem with this is that in the deploy log, it lists it as img-captain-$APPNAME:$n, not the actual deployed image. Months later, I don't have any record of which specific image I deployed. When deploying from pasted-in captain-definition file, or via imageName (methods 5/6), would it be possible to set the image name in the version history to the upstream image instead of the opaque name it uses now?

Can you open a separate issue for this? I think it should be possible.

**Comment by itsam** [comment]
Hello, 
do you believe it's safe now (v 1.10.1) to execute the following in the hosting machine
`docker image prune`

For a reason the "Remove Unused Images" button gives an error after a while (I have a very long list > 200)

Thank you in advance

**Comment by githubsaturn** [comment]
@itsam 
This issue has nothing to do with caprover. It's a docker issue.

**Comment by itsam** [comment]
Thanks @githubsaturn !
Eventually after updating my host VM the "Removed Unused Images" finished without errors. Indeed my physical space is actually reduced. Also after taking a backup also docker image prune worked correctly. My question now though is:

Is it normal to keep seeing in Version History (tab: Deployment) all my deployments? I would assumed that only the last 2 to be there and not all of them.
Am I missing something here?

**Comment by githubsaturn** [comment]
That's correct. The version history is there, but the images may not be.
