### ISSUE TITLE
[Question] Multiple Caprover Servers on one Domain

### ISSUE THREAD

**Issue by tschannik** [caprover/caprover#1120]
Hi, 

This might be a strange question but is it possible to run multiple "Caprover-Servers" on one Domain?

Clarification:
I'm evaluating to use Caprover as the main software to host my  applications. So i might get the request of a customer to host his app on a dedicated server. As far as i understand it clustering caprover just deploys all applications in parallel which is not what i would want in that case.
Instead i'd order a second server and install caprover. But i have only one domain available for my services -> sample.xyz. 
So would it be possible to have two caprover instances available at `captain.1.sample.xyz` and `captain.2.sample.xyz` and specify a dns A entry for the dedicated application to `app.2.sample.xyz` or `app.sample.xyz` and route * to `1.sample.xyz?`

Thanks

**Comment by githubsaturn** [comment]
It definitely is possible. When you're setting up your "root domain" in CapRover, use `*.server1.domain.com` as your first root domain and use `*.server2.domain.com` as your second root domain. Of course, you need to make proper changes to your DNS such that:
-  `*.server1.domain.com`  points to IP address of the first server
-  `*.server2.domain.com`  points to IP address of the second server
