### ISSUE TITLE
Keep most recent value not being saved

### ISSUE THREAD

**Issue by SpaceIgniter** [caprover/caprover#1121]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Keep most recent value not being saved.
The default is 2. Changing it has no effect.

If applicable, content of `captain-definition` file:
Steps to reproduce the problem:

Go to setting and attempt to change Keep most recent value.

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 18 .04 LTS
- RAM?
1GB

**Comment by githubsaturn** [comment]
The value not being saved is expected. The deletion process is on-demand, not automated. You first set the number, get the list, and then purge the unused images.
