### ISSUE TITLE
network_mode selection must have.

### ISSUE THREAD

**Issue by Rhys-Woolcott** [caprover/caprover#1122]
**Is your feature request related to a problem? Please describe.**
I am frustrated with how mail servers almost require `network_mode: host` but cannot change this with caprover.

**Describe the solution you'd like**
I would like some sort of `network_mode` selector in the `app configs` section of an app.

**Describe alternatives you've considered**
I have considered just deploying all of my applications with `docker-compose` but I do not currently have time to transfer all 43 apps have deployed with caprover.

**Additional context**
Something like the image attached could be an example

![](https://i.imgur.com/zod0MpF.png)

**Comment by Rhys-Woolcott** [comment]
A drop down menu with all the valid values may also be a viable option

**Comment by githubsaturn** [comment]
It can be changed using CapRover. But it doesn't have a specific UI widget. See [here](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope) why we don't add specific UI widgets for all Docker params.

You have two ways to change this:
- Use `docker service update` 
- Use [service override](https://caprover.com/docs/service-update-override.html).

**Comment by Rhys-Woolcott** [comment]
> It can be changed using CapRover. But it doesn't have a specific UI widget. See [here](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope) why we don't add specific UI widgets for all Docker params.
> 
> You have two ways to change this:
> 
> * Use `docker service update`
> * Use CapRover [service override](https://caprover.com/docs/service-update-override.html).

I understand this but I think it may improve the ease of use in caprover

**Comment by githubsaturn** [comment]
Then it means that docker doesn't provide the config for swarm perhaps. 

Unless by network mode, you're referring to port mapping modes. In that case, both docker update and service override provide ways to do this. 


Regarding the specific UI widget, as i mentioned above, it's beyond CapRover scope.

**Comment by Rhys-Woolcott** [comment]
> Then it means that docker doesn't provide the config for swarm perhaps.
> 
> Unless by network mode, you're referring to port mapping modes. In that case, both docker update and service override provide ways to do this.
> 
> Regarding the specific UI widget, as i mentioned above, it's beyond CapRover scope.

I am referring to allowing the container to view the host's ip so it does not come up as 10.0.0.2 inside of the container which can cause all sorts of security issues

**Comment by githubsaturn** [comment]
Have you seen this? https://docs.docker.com/network/host/

Why can't you do something like this in service override?

```
TaskTemplate:
  Networks:
    - Target: host
```

**Comment by githubsaturn** [comment]
Feel free to comment if you're still having trouble with this
