### ISSUE TITLE
Dockerfile lines in definition file

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#113]
Instead of putting the dockerfile lines directly within `captain-definition` as an array, would it be a nice idea to be able to just have a separate dockerfile, so that we don't have to add double quotes and commas, and escape existing double quotes (which all make it less readable)?

    {
      "schemaVersion": 1,
      "dockerfile": "mydockerfile"
    }

And then `mydockerfile` can just be a plain old docker file that can be more easily edited and read?

**Comment by githubsaturn** [comment]
It would be misleading. See "Important Note" here: https://github.com/githubsaturn/captainduckduck/wiki/Captain-Definition-File

Captain copies your source file into a `src` folder whereas if you want to build your dockerfile directly on a machine they are aim to the "current directory". I will have a plan in place to automatically add `./src` to the docker files. But before that, it would be confusing to directly point to a dockerfile.

**Comment by derek-adair** [comment]
I'm willing to help develop this feature in whatever way I can.  This seems rather important.

I have a curated set of images that I would LOVE to throw in duckduck.

**Comment by cooperaj** [comment]
> Captain copies your source file into a `src` folder whereas if you want to build your dockerfile directly on a machine they are aim to the "current directory". I will have a plan in place to automatically add `./src` to the docker files. But before that, it would be confusing to directly point to a dockerfile.

Surely the solution here (since all my projects build this way) is to just have 
```
{
  "schemaVersion": 1,
  "dockerfile": "src/mydockerfile"
}
```

Most all my Dockerfiles operate on the basis that they live at the root of my source anyway.

**Comment by githubsaturn** [comment]
It's almost ready. With the release of version v1.0 (early 2019), we will have this feature implemented.

**Comment by pedrobracho** [comment]
One question, I have my app ready running with docker-compose, im trying with effort make it run with captainduckduck because im enloved with this project, the problem is that it contious failing on the command captainduckduck deploy.

Right now it says it says

Error: Error: (HTTP code 400) unexpected - No build stage in current context

And im pretty sure because im not sending from dockerfile all lines that i need, specially the one that says 

build: .

How can i achive this? with the "tool" porposed on documentation fails also so im trying to write it my own captain-definition file but im lacking the entire knowledge and i can not find a light on internet. 

Thaks a lot

**Comment by pedrobracho** [comment]
> One question, I have my app ready running with docker-compose, im trying with effort make it run with captainduckduck because im enloved with this project, the problem is that it contious failing on the command captainduckduck deploy.
> 
> Right now it says it says
> 
> Error: Error: (HTTP code 400) unexpected - No build stage in current context
> 
> And im pretty sure because im not sending from dockerfile all lines that i need, specially the one that says
> 
> build: .
> 
> How can i achive this? with the "tool" porposed on documentation fails also so im trying to write it my own captain-definition file but im lacking the entire knowledge and i can not find a light on internet.
> 
> Thaks a lot

Hi good evening, im trying to convert this docker file:

version: "2" services: mobileappch-api: build: . command: yarn dev -- -L environment: - NODE_ENV=development volumes: - .:/app ports: - "3000:3000" depends_on: - mongodb mongodb: image: mongo environment: - MONGO_URI=mongodb://mongodb:27017/test ports: - "27017:27017"

Into a captain-definition file but im lacking experience on this and has been taking me a lot of time and a lot of dead ends.

This is how it goes till now

{ "schemaVersion" :1 , "dockerfileLines" :[ "RUN yarn dev -- -L", "ENV NODE_ENV dev", "ENV PORT 80", "EXPOSE 80", "CMD [ \"npm\", \"start\" ]" ] }

But its incomplete and fails the deployment, any light on this tunnel?

**Comment by githubsaturn** [comment]
@pedrobracho 
The one that you posted is not a dockerfile, it's a docker-compose file which is a full instruction of one or multiple apps (in your case two apps, a nodejs app and a MongoDB database.)

You must have a `Dockerfile` inside your directory sitting next to this docker-compose file. Dockerfiles start with `FROM imagename` line. 

Convert your Dockerfile using [this tool](https://githubsaturn.github.io/dockerfile-to-captain/). Also pay attention to the IMPORTANT NOTE section here about `src` directory.

**Comment by derek-adair** [comment]
@pedrobracho - While i understand why you posted in this thread, you should open a new issue with new questions and reference this issue.

**Comment by githubsaturn** [comment]
See https://github.com/caprover/caprover/releases/tag/v1.0.0

`captain-definition` now accepts `dockerfilePath`. For example:

``` 
{
  "schemaVersion" :2 ,
  "dockerfilePath" :"./myDockerFile"
 }
```
