### ISSUE TITLE
Feature Request - 2FA Validation before pull from private repository

### ISSUE THREAD

**Issue by incryptoid** [caprover/caprover#1130]
**Is your feature request related to a problem? Please describe.**
I had a problem deploying using username and password from Github private repository if 2FA is active. I don't know how between Capprover and github comunicate using 2FA process.

**Comment by githubsaturn** [comment]
You have to use SSH keys if you have 2FA. 

On Github, go to your repository, then click on SETTINGS, then click on DEPLOY KEYS.
