### ISSUE TITLE
[Question/Possible Bug] Cannot route to custom domains via HTTPS is HTTPS uses non-Let's Encrypt certificate

### ISSUE THREAD

**Issue by marcolussetti** [caprover/caprover#1134]
- I am trying to enable HTTPS with a non-Let's Encrypt certificate (this is an internal service).
- I have enabled it just fine via the nginx configuration, however I the HTTPS still looks disabled from Caprover's point of view.
- This affects routing via alternate domain because I get the generic "Nothing here yet" screen when accessing it over HTTPS, but it works over HTTP.
- Clicking enable HTTPS on the alternate domain or the primary address yields a "You must enable SSL on the root domain" error.
- HTTP routing to the alternate domain works fine.

**Comment by githubsaturn** [comment]
When you go down the route of manually setting up your nginx config, you should configure everything, not just partial changes. 

In this case, you've potentially set the path of the certs and etc, but you're not activating the https listening itself.

In your app's NGINX configuration, find `    if (s.hasSsl) {` and change it to `    if (true) {`
