### ISSUE TITLE
[Question] Deploy same image multiple apps

### ISSUE THREAD

**Issue by Satont** [caprover/caprover#1137]
Hi, i have about 10 apps with same docker image.

How i can easy deploy them to latest docker versions? I know i can connect github/gitlab, but it will build 10 of that applications in separated way, right? So it's something what i wont.

Curently i just opening them one by way and clik on `Method 6: Deploy via ImageName` manually... Which is shame, to be honest.

**Comment by githubsaturn** [comment]
Why do you have 10 apps with the same image? Trying to understand the usecase.

Regardless, CapRover is scriptable, you can definitely use some scripting to automate this:
```
caprover deploy --caproverUrl xxxx --caproverPassword xxxx --caproverApp xxx --imageName YOURIMAGENAME
```

**Comment by Satont** [comment]
> Why do you have 10 apps with the same image? Trying to understand the usecase.

Well, it's rare, right. But it still might be. In my use case i have 1 application for livestream channel. It's an chat helper bot.

> Regardless, CapRover is scriptable, you can definitely use some scripting to automate this

It's was something in my mind, thinked about some bash loop, but it will require manualy update some env variable. But yea, it will work. 

---

Thank you for the answers, i just though there can be more beautiful way.

**Comment by Satont** [comment]
Maybe, it least, flag `--imageNames` can be implemented for cli, so in rare case of some other ppls it will helps?

**Comment by Satont** [comment]
Ok, as i can see, i can call the api `/user/apps/appDefinitions`. Guess will write some application on nodejs and just pkg it.
