### ISSUE TITLE
No such image: img-captain-redis-server:1

### ISSUE THREAD

**Issue by maxvia87** [caprover/caprover#1138]
Hello, 

I have a caprover app that is running 6 img. For some reason I have been struggling for a week. I havent changed anything but my caprover client is not working anymore. 

When I enter `docker service ls` I have 2 img and the nginx that get the status 0/1 under replicated (see img)

<img width="430" alt="Screen Shot 2021-06-26 at 14 52 24" src="https://user-images.githubusercontent.com/64636974/123513658-84676200-d68e-11eb-9ac4-769529aa95a0.png">

For example this is the case of `srv-captain--new-rails-api`, I tried to enter `docker service ps srv-captain--new-rails-api`
I get the error message `No such image: img-captain-ne…`. i dont understand how this is possible and what I should do?

<img width="742" alt="Screen Shot 2021-06-26 at 14 58 20" src="https://user-images.githubusercontent.com/64636974/123513757-28510d80-d68f-11eb-899b-0b539d4997ec.png">

Any tips/help is appreciated

Thank you

Maxime

**Comment by githubsaturn** [comment]
Did you manually ran `docker prune` ?

**Comment by maxvia87** [comment]
no I didnt

**Comment by githubsaturn** [comment]
Run `docker service ps captain-nginx` and `docker service ps captain-captain` what are the outputs?

**Comment by maxvia87** [comment]
thanks for the help @githubsaturn here is a screenshot of what I get when I run `docker service ps captain-nginx` 

<img width="1046" alt="Screen Shot 2021-06-26 at 18 59 32" src="https://user-images.githubusercontent.com/64636974/123520387-c1445080-d6b0-11eb-9546-2b08006e2327.png">

and for `docker service ps captain-captain`

<img width="1101" alt="Screen Shot 2021-06-26 at 19 00 42" src="https://user-images.githubusercontent.com/64636974/123520424-e0db7900-d6b0-11eb-9af6-3a366488243d.png">

**Comment by githubsaturn** [comment]
Looks like a docker bug... Get logs for your nginx to see why it's restarting

**Comment by maxvia87** [comment]
after running `docker service logs captain-nginx` I get the following error 

<img width="1211" alt="Screen Shot 2021-06-26 at 19 15 31" src="https://user-images.githubusercontent.com/64636974/123520868-55afb280-d6b3-11eb-8e2c-7c3a54de79a3.png">

**Comment by maxvia87** [comment]
may be `nginx: [emerg] host not found in upstream "puma" in /etc/nginx/conf.d/captain.conf:97`?

**Comment by githubsaturn** [comment]
What is puma?? Is it one of your apps? Did you change your nginx config manually?

**Comment by githubsaturn** [comment]
Run this to remove all custom nginx configs:
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by maxvia87** [comment]
puma is used in one of the imgs that keeps restarting. I havent changed anything in my app nginx in weeks. ok will try to remover the customs nginx configs

**Comment by githubsaturn** [comment]
Just run this:
```
docker service scale captain-captain=0 && \
docker run -it --rm -v /captain:/captain  caprover/caprover /bin/bash -c "wget https://raw.githubusercontent.com/caprover/caprover/master/dev-scripts/clear-custom-nginx.js ; node clear-custom-nginx.js ;" && \
docker service scale captain-captain=1 && \
echo "OKAY"
```
It automatically removes all custom nginx configs.

**Comment by maxvia87** [comment]
still facing the same issue. cant connect to the caprover client. when I had access to the client. I had the choice to change the image associated to a specific app. 

For example on the image below, i see that `srv-captain--new-rails-api` is associated with the image `:125`. Is there any way to see all the images I can you for this specific captain and change it? I could do it directly from the client

<img width="815" alt="Screen Shot 2021-06-26 at 19 38 08" src="https://user-images.githubusercontent.com/64636974/123521365-7e857700-d6b6-11eb-847b-599c4fd9cd34.png">

**Comment by githubsaturn** [comment]
You can run `docker images` to view all images on your host.

But before that, just change them to something that you know it works, like nginx:
```
docker service update srv-captain--new-rails-api --image nginx:alpine
docker service update srv-captain--redis-server --image nginx:alpine
```

**Comment by maxvia87** [comment]
Ok everything is now working. I was having an issue with my redis-server. After resetting the nginx i was able to access the client and re-create a new one click redis app.
Thanks a lot @githubsaturn
