### ISSUE TITLE
Adding port to repo url doesn't work if you don't prefix the repo with git@

### ISSUE THREAD

**Issue by virtualcodewarrior** [caprover/caprover#1139]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
A while back the possibility to add a custom port for the git repo was added, but this currently only works if you also manually add the `git@` prefix to the repo path.

So this works: `git@my_git_repo.com:223/myname/myrepo`
But this doesn't work: `my_git_repo.com:223/myname/myrepo`

Looking through the code of caprover/src/utils/GitHelper.ts

I found the following at lines starting at 112: 
```
if (!input.startsWith('git@')) {
            // If we get here, we have something like github.com/username/repository.git
            input = input.replace('/', ':')
            input = `git@${input}`
        }
```
If I read this right, this code would replace the first '/' in the repo url with a ':' but only if it doesn't start with git@ so this means that `my_git_repo.com:223/myname/myrepo` becomes `my_git_repo.com:223:myname/myrepo`. This will then fail at lines 123-124 with this code:
```
        const split = input.split(':')
        if (split.length == 2) {
```
The split length will now result in 3 and this check will return false and will fall through to the error message 'malformed url'
From you comments it seems that this was unintended.

It looks like you would want to change the code at line 112 to include a test to see if it already has a colon e.g.

```
if (!input.startsWith('git@')) {
            // If we get here, we have something like github.com/username/repository.git or github.com:22/username/repository.git
            if (!/:/.test(input)) {
                input = input.replace('/', ':')
            }
            input = `git@${input}`
        }
```

**Comment by githubsaturn** [comment]
I think `my_git_repo.com:223/myname/myrepo` is ambigious, it can both be a git (SSH) address, or an HTTP address, hence we can't assume it's always git. Typically http prefixes can be dropped by users, whereas `git@` prefixes aren't usually missed.

**Comment by virtualcodewarrior** [comment]
They might be ambiguous but at this point of the code you are already assuming that it should have `git@` as a prefix since you will be adding it if it doesn't have it. 
The only problem here would be that you replace the first slash with a colon regardless if there is a colon in the address already, which will make the address invalid for the following code. Just skipping the replacement of the first slash with a colon if a colon already exists should fix that problem.

**Comment by githubsaturn** [comment]
Ah gotcha! It does make sense! I'll update!
