### ISSUE TITLE
How to use Caprover in my local area networks？

### ISSUE THREAD

**Issue by whenSunSet** [caprover/caprover#1143]
i want to use Caprover in my local area networks.

for example i have two computer in my local area networks，A and B。

Caprover deployment in computer A，their have some service。

I want to computer B can visit service in computer A, and it could not accessible by the external network

Now i was configured computer A according to this page：https://caprover.com/docs/run-locally.html

but computer B cannot access the service on computer A，which domian name like：http://wiki.captain.localhost

What should I do?

**Comment by githubsaturn** [comment]
You have to assign a local domain. 

1- 
If you router supports this, you can add a local DNS record like `captain.mycaprover.loc` that points to IP address of computer A.


2-
If your router doesn't support it, you'll have to create your DNS record, locally on computer B `/etc/hosts` file

**Comment by whenSunSet** [comment]
thanks

but i still meet some problem

i add a local DNS record like 

192.168.123.224  captain.mycaprover.loc 

in my router host file

my router system is Padavan，192.168.123.224 is computer A's ip

then i go to computer A, login to CapRover and change the root domain to mycaprover.loc

Now i can access captain.mycaprover.loc in computer B and the content is Caprover's page

but when i want to access other service like **wiki.mycaprover.loc**  which use wiki.js to deployment

something wrong with **DNS_PROBE_FINISHED_NXDOMAIN**

**i can not access my wiki service in Computer B**

@githubsaturn

**Comment by githubsaturn** [comment]
You have to add `wiki.mycaprover.loc` as a DNS record to your router as well. Some routers allow wildcard DNS entry, some don't. If your router allows you to do that, you can use `*.mycaprover.loc`

**Comment by whenSunSet** [comment]
thanks
you are right
