### ISSUE TITLE
What if a container have two web applications at the same time

### ISSUE THREAD

**Issue by pi-kei** [caprover/caprover#1145]
Is it possible to deploy a container that have two web applications on a different ports?
For example, I'm trying to deploy a container with [heroiclabs/nakama](https://hub.docker.com/r/heroiclabs/nakama) which have HTTP API server running on port 7350 and developer console web-application running on port 7351 both at the same time.
For now I just ignore dev console and map only port 7350. But I would like to be able to access dev console via HTTPS and specific domain. Is it possible to achieve this? What should I do to achieve this?
CapRover version 1.9.0

**Comment by githubsaturn** [comment]
You can use `Nginx Reverse Proxy` app and set the "Upstream address" to `http://srv-captain--yourappnamehere:7351`

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/125087383-4bad8c80-e081-11eb-9d35-bb89523018e6.png)
