### ISSUE TITLE
[Question] How to remove persistent data from app?

### ISSUE THREAD

**Issue by jeffersonmoreira-zukt** [caprover/caprover#1147]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Is it possible to remove persistent data from the created app?

**Comment by githubsaturn** [comment]
The persistent data is a mapped volume, You can go to app configs and remove the mapped volume and click on Save & Update.
