### ISSUE TITLE
[Question] Is it possible to have the caprover server installed at a root subdomain ?

### ISSUE THREAD

**Issue by thomascenni** [caprover/caprover#1148]
Hello,
I have "mydomain.com" and would like to install Caprover at "captain.mydomain.com" or "whatever.mydomain.com", instead of the "best practice" "captain.capserver.mydomain.com" suggested in the docs.

This because I can use Cloudfare on the subdomain "captain.mydomain.com" to avoid exposing the IP address of the Caprover installation; with "captain.capserver.mydomain.com" Cloudfare is not able to proxy unless you buy a Dedicated SSL certificate (https://www.cloudflare.com/ssl/dedicated-certificates/). Thanks.

**Comment by githubsaturn** [comment]
Yes, you can use `domain.com` as your root domain.

**Comment by thomascenni** [comment]
> Yes, you can use `domain.com` as your root domain.

But the server is already installed, and when I try to setup the new domain in this way:
![Screen Shot 2021-07-15 at 19 50 16](https://user-images.githubusercontent.com/33039107/125867598-5ee8fbc3-d9a0-4151-bd29-205b192782d8.png)
I got an 1107 error.
DNS are OK in Cloudfare with captain.mydomain.com.
Any hints?

**Comment by githubsaturn** [comment]
Have you set up wildcard for your DNS or just `captain.domain.com`? If it's the latter, you'll have to disable domain check:
https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

**Comment by thomascenni** [comment]
> Have you set up wildcard for your DNS or just `captain.domain.com`? If it's the latter, you'll have to disable domain check:
> https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

Just captain.domain.com. I'll have a deeper look at the docs, thanks !
