### ISSUE TITLE
[Question] How to bind CapRover to a specific public IP address.

### ISSUE THREAD

**Issue by benbehringer** [caprover/caprover#1152]
I have two public IP addresses and I want to declare explicitly which I use to expose CapRover. Is there a best practice to achieve this? I already tried the following without any success:

```
docker run -e MAIN_NODE_IP_ADDRESS=23.22.1.21
-p 23.22.1.21:80:80 -p 23.22.1.21:443:443 -p 23.22.1.21:3000:3000
-v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

It still binds `*:3000->3000/tcp` and fires up `caprover/certbot-sleeping:v1.6.0` with `80/tcp, 443/tcp` instead of `23.22.1.21:80->80/tcp` and `23.22.1.21:443->443/tcp`. Before I implement a workaround, I wanted to know whether there is a smart way ;)

Thanks, Ben

**Comment by maietta** [comment]
I could be way off base here, but my first thought is that wouldn't it be better to bind Docker engine? As far as I can tell and understand it, Caprover is essentially a wrapper around Docker Engine and Docker Swarm tooling. It stands to reason at least for me that if you want to prevent Caprover from attaching to all interfaces available, you would want to do this at the Docker engine level.

**Comment by benbehringer** [comment]
Agree, would be a good solution, but unfortunately, not possible in this setting. The other IP is used for a legacy traefik container.

**Comment by maietta** [comment]
> Agree, would be a good solution, but unfortunately, not possible in this setting. The other IP is used for a legacy traefik container.

Darn.

**Comment by githubsaturn** [comment]
I don't think it's supported in Docker swarm at all: https://github.com/moby/moby/issues/26696

But if it is, then you can try doing something like this after initial installation
 
```
docker service update captain-nginx --publish-rm 80 --publish-rm 443

docker service update captain-nginx --publish-add .... custom stuff here

```
