### ISSUE TITLE
[Feature Request] Assign Domain to an app via API/CLI or CNAME support

### ISSUE THREAD

**Issue by vitali-korezki** [caprover/caprover#1153]
Dear Caprover team,

I'm working on a workflow to assign custom domain programmatically to an app, without human interaction. At the moment I couldn't find any solution yet, but I can imagine two possible ways to solve it:

1. Add API or CLI function which can be executed via script to assign a new custom domain to an app
2. Alternatively add support for CNAME DNS entries, so the domain for the app can stay the same

Thanks!

**Comment by githubsaturn** [comment]
Not all CapRover commands are exposed to CLI. This is done intentionally to keep the code base small and maintainable. 

Having said that, there is a specific command for these use cases: `caprover api`. You can use this command to run any unexposed CapRover command, see https://github.com/caprover/caprover-cli/issues/90 and https://github.com/caprover/caprover-cli/issues/55 and https://github.com/caprover/caprover-cli/issues/47
