### ISSUE TITLE
can't verified .pk domains

### ISSUE THREAD

**Issue by ranaharoon3222** [caprover/caprover#1155]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

i cannot verified .pk domains like here http://elitekids.com.pk/

If applicable, content of `captain-definition` file:

no

Steps to reproduce the problem:

just tried to connect domain and said 1107 error

Answers to the following questions where applicable:
- Your OS and version? ubuntu 18.04 LTS
- RAM? 4gb

**Comment by githubsaturn** [comment]
Can you get the logs from your server when this verification fails?

You can view logs by running this:
```
docker service logs captain-captain --since 5m
```

**Comment by ranaharoon3222** [comment]
i have fixed it
