### ISSUE TITLE
Nuxtjs Captain Definition File

### ISSUE THREAD

**Issue by germanllop** [caprover/caprover#1156]
Just in case anyone needs it, here is a captain-definition file example for deploying a Nuxt.js App:

> {
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM node:lts",
    "WORKDIR /usr/src/app",
    "COPY . /usr/src/app",
    "RUN npm install",
    "EXPOSE 80",
    "ENV HOST 0.0.0.0",
    "ENV PORT 80",
    "ENV NODE_ENV production",
    "RUN npm run build",
    "CMD [ \"npm\", \"run\", \"start\" ]"
  ]
}

**Comment by githubsaturn** [comment]
Thanks, feel free to add a fully working application here if you'd like 
https://caprover.com/docs/sample-apps.html#community-apps
