### ISSUE TITLE
Reverse SSH Tunneling

### ISSUE THREAD

**Issue by kaleidotech** [caprover/caprover#1157]
## The Problem
Trying to set up reverse SSH tunnel. I know that it might be better using a service but it worked totally fine with nginx on ubuntu that I had before Caprover so I'd like to keep it. 

## Steps I've done
1. Create a dummy app.
2. Add server block to nginx file that I used previously.

```
server {
    server_name app.domain.com; # note -> this is a different domain tied after creating the app through Caprover

    location / {
        proxy_pass http://localhost:3434/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}
```

I've tried removing everything below proxy_pass and I've tried substituting localhost for docker0 inet, etc. Nothing worked so far. So, it worked just fine on nginx service + ubuntu. I've also allowed the port via ufw. 

Any help would be highly appreciated.

**Comment by githubsaturn** [comment]
This is not SSH tunneling? It's just simply using some reverse proxy for HTTP requests, not SSH... What's your intention?

**Comment by kaleidotech** [comment]
Perhaps I was not clear enough. It's what ngrok basically does. What I had set up is a tunnel where when I serve an app locally and tunnel through to the nginx (domain connected) I can then test it by going to the selected url. Does this explain it better?

**Comment by githubsaturn** [comment]
I'm still unsure what you're trying to do. Try posting this in our Slack channel to see if anyone is familiar with what you're trying to do. I'll leave this issue open for a few more days in case anyone can help you with this.

**Comment by kaleidotech** [comment]
I think that was pretty clear. Just in case it wasn't, check
[this link](https://serverfault.com/questions/244396/reverse-ssh-tunnel#244409). So tunnel from localhost through nginx and be able to test the app. Worked just fine on nginx before Caprover. I want to try to make it work now as well.

**Comment by githubsaturn** [comment]
I see. 

1- You'll have to map port 3434 of your app to 3434 of your server. Go to app config and add this mapping. 
2- Depending on your network topology, `http://localhost:3434` might or might not work. If it does't work, try replacing it with: `:http://127.0.0.1:3434`  or replace 127.0.0.1 with the local ip address of the container, you can get it from:
```
docker container inspect  $(docker container ls --filter name=captain-nginx | awk 'FNR == 2 {print $1}')  | grep IPv4Address
```

**Comment by kaleidotech** [comment]
Thanks for that! 

In theory, yes, it should have worked. In practice, however, it doesn't. I mapped the ports:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/86684243/127765776-a15cc658-7804-442c-9cbf-9e359761229a.png">

Added upstream to be localhost, then tried 127.0.0.1, then the ip address I got by inspecting the container as you suggested. Nothing seems to be working unfortunately.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/86684243/127765865-c388e422-480c-407c-b427-ce0d028e9518.png">

The weirdest part is that my logs don't show anything.

**Comment by githubsaturn** [comment]
You'll have to shell into your nginx container, then run curl to `http://localhost:3434` to see if it works.

**Comment by githubsaturn** [comment]
I just went over this again, and realized that you're editing the nginx config in the CapRover's nginx file, not your app's nginx file. That is why it's not working. 

The port mapping that you've added is on the app container. But your nginx config is for the nginx container.

**Comment by kaleidotech** [comment]
I've tried spinning up nginx reverse proxy, a custom nginx docker image but got nowhere. I'll give it a couple of days more and if I can't make it work, I'll simply go back to the nginx config on the server I had before Caprover, it's proving to be quite a headache. Thanks for all your help, I appreciate it.

**Comment by githubsaturn** [comment]
After spinning up a custom nginx image, you can shell into that container and use curl to debug your method.

Another method is just to SSH into the nginx container. You can map a random port on host (like 2424) to port 22 of the container, then reverse SSH proxy to port 2424 which will be port 22 on the container.
