### ISSUE TITLE
[Question] Connection between Manager and Worker

### ISSUE THREAD

**Issue by eric-mathison** [caprover/caprover#1158]
While trying to troubleshoot a connection issue on a container on a worker node, I saw that the communication between the manager node and worker node is over the public ip addresses. Even if I join the worker node to the private ip address of the manager, communication is over the public network. I can verify this by blocking port 2377 on our outside network firewall. 

I can't find any information on what causes this so I'm assuming its from caprover using the public ip to advertise. I could be 100% wrong, as I said, I can't find any information to explain which networks docker uses to communicate and how to influence them. 

Any information is helpful here as I'm trying to avoid needing to encrypt the overlay network.

**Comment by githubsaturn** [comment]
That's correct. By default the advertising IP is the public IP of your machine. You can override this by passing `-e MAIN_NODE_IP_ADDRESS=IP_ADDRESS` to the installation command, e.g.:
```
docker run -e MAIN_NODE_IP_ADDRESS=123.123.123.123 -p 80:80 -p 443:443 -p 3000:3000 \
             -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

```
