### ISSUE TITLE
CapRover Root Domain Configurations hides the Dashboard (same thing happens in the official Demo Server)

### ISSUE THREAD

**Issue by jbmorgado** [caprover/caprover#1161]
What is the problem?
After installing (or even in the Demo that can becessed from CapRover official page), there is some banner about `CapRover Root Domain Configurations` covering all functionality from the dashboard.
There is no obvious way to get rid of it.

Steps to reproduce the problem:
Just install CapRover or even login to the Demo on CapRover's official website.

<img width="953" alt="Screenshot 2021-08-05 at 20 04 58" src="https://user-images.githubusercontent.com/11217179/128406793-7265be49-cea3-430a-b4a7-21b2174c9ea3.png">

**Comment by githubsaturn** [comment]
What do you mean by "covering all functionality from the dashboard"?

Apps tab is where you should spend most of your time. When you log in you automatically get redirected to the apps page.

**Comment by jbmorgado** [comment]
> What do you mean by "covering all functionality from the dashboard"?
> 
> Apps tab is where you should spend most of your time. When you log in you automatically get redirected to the apps page.

Thank you @githubsaturn so, there is no functionality in the dashboard other than Changing the Root domain (as shown in the screenshot)?

I came to this by searching how to add a docker container to CapRover (Something I am still trying to figure out) and the comments about it say that it "should be added in the dashboard", that was when I realized there's just this Congratulations banner there.

**Comment by githubsaturn** [comment]
Dashboard is often used to refer to the entire GUI frontend tool. If you link the comment, I can help you where to find that info. But other than that, the dashboard tab only has the information that your screenshot displays.
