### ISSUE TITLE
Use a random password instead of `captain42`

### ISSUE THREAD

**Issue by ejose19** [caprover/caprover#1162]
**Is your feature request related to a problem? Please describe.**
As stated in the https://caprover.com/docs/best-practices.html, the default password of `captain42` can be a security risk and it's a problem that can be improved.

**Describe the solution you'd like**
`caprover` can instead generate a random password (`tr -dc 'a-f0-9' </dev/urandom | head -c32` in SHELL context or `crypto.randomBytes(16).toString('hex')` in JS context), it would be displayed and only known to the deployer during installation (as opposed to `captain42` which is already known by everyone). This could be a good middle point to making installation a bit more secure without forcing everyone to set the password env.

**Describe alternatives you've considered**
User must explicitly set `DEFAULT_PASSWORD`

**Additional context**
N/A

**Comment by githubsaturn** [comment]
The option to set an explicit password is there. You're suggesting we change the default behavior. We won't be doing that since it goes against CapRover design principles. CapRover is designed to be as simple as possible, but allowing more advanced users to customized however they want.

**Comment by ejose19** [comment]
I'm just suggesting to make the default options to be safe, if a random password is used by default, then the best practices entry won't need to be there. Also, it shouldn't be an issue for users since they will see the random generated password on the deployment logs.

If you change your mind, I'm interested in contributing this feature to caprover.
