### ISSUE TITLE
Deploy failed for Method 3 - Github

### ISSUE THREAD

**Issue by jersomoreira** [caprover/caprover#1164]
This error message is return deploy using Method 3.

```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
```

Github removed support to deploy using password authentication.

Caprover support will deploy using authentication token?

**Comment by githubsaturn** [comment]
Yes.

Authentication tokens are just Github concepts, they are [nothing more than one off passwords](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line
).


You can also use [deploy keys](https://docs.github.com/en/developers/overview/managing-deploy-keys#setup-2)
