### ISSUE TITLE
Support for `--device`

### ISSUE THREAD

**Issue by gedemagt** [caprover/caprover#1165]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**
I wanted to host an OctoPrint instance, but I can not easily forward the USB-connections needed via the `--device` flag with Docker. 

**Describe the solution you'd like**
The possibility to choose device mapping just like you can do with Environmental Variables and Port Mapping currently.

**Additional context**
The requirements for USB connections and camera connections are described here for OctoPrint: https://hub.docker.com/r/octoprint/octoprint

**Comment by githubsaturn** [comment]
Devices aren't supported by Docker in swarm mode: https://docs.docker.com/compose/compose-file/compose-file-v3/#devices

There is nothing that CapRover can do to add this support.


However, if you want to assign a subdomain and potentially use HTTPS, there is a workaround. You can manually install octroprint on your machine and expose a free port, e.g.:

```
docker run -d -v octoprint:/octoprint --device .......... -p 8080:80 octoprint/octoprint
```

Then on CapRover, deploy a one click app "Nginx Reverse Proxy". In the form, enter `http://IP_ADDRESS:8080` for "Upstream address" where IP_ADDRESS is the local IP address of your machine.
