### ISSUE TITLE
[Question] Possible to run Caprover behind an nginx reverse proxy?

### ISSUE THREAD

**Issue by billyjacoby** [caprover/caprover#1166]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

I've been looking everywhere and can't seem to find a concrete answer to this questions, or a tutorial for how to set it up. So I'm assuming it's impossible, or i'm grossly overlooking something.

I am trying to setup Caprover on a local machine that will not have its own public facing IP. I host a number of other apps via nginx reverse proxy, and have tried setting up Caprover like this as well however it fails to start. 

So, is it possible to run Caprover behind a reverse proxy like nginx? And if so are there any resources that someone could point me to in order to get it up and running?

Thanks in advance!

**Comment by githubsaturn** [comment]
Correct. It's not possible. 

CapRover requires either direct public IP, or full port forward (80/443) from your router to your local machine. It's due to the fact that CapRover manages your domains and your SSL certificates for you.

**Comment by billyjacoby** [comment]
> Correct. It's not possible.
> 
> CapRover requires either direct public IP, or full port forward (80/443) from your router to your local machine. It's due to the fact that CapRover manages your domains and your SSL certificates for you.

Shouldn't it be possible then to use a dedicated subdomain and wildcard redirect all traffic for that subdomain to Caprover through the reverse proxy though?

That's what I'm currently doing with @getmeli, but I was really hoping to switch to Caprover.

**Comment by githubsaturn** [comment]
> use a dedicated subdomain and wildcard redirect all traffic for that subdomain to Caprover

If want to manage the SSL cert yourself, it's possible. But you have to install CapRover in a VM (or a separate machine) as CapRover needs port 80/443. So you'll have something like this:

```
                           ┌─────────────────────────────────────────────────────────────────────────────────┐
                           │                                                                                 │
                           │                                                                                 │
                           │  ┌─────────────────┐                                                            │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  │                 │                       VM or separate machine               │
                           │  │                 │                   ┌─────────────────────────────────┐      │
┌────────────────┐         │  │                 │                   │                                 │      │
│                │ 80/443  │  │                 │                 80│                                 │      │
│  Outside world ├─────────┼─►│ Your own Nginx  ├──────────────────►│   CapRover (nginx + other apps) │      │
│                │  *.*    │  │                 │ *.caprover.ab.com │                                 │      │
└────────────────┘         │  │                 │                   └─────────────────────────────────┘      │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  │                 │                                                            │
                           │  └─────────────────┘                                                            │
                           │                                                                                 │
                           │                                                                                 │
                           │                                                                                 │
                           │                                                                                 │
                           └─────────────────────────────────────────────────────────────────────────────────┘
```


As long as you forward all requests to *.sub.domain.com to your CapRover VM, you can just follow the regular installation steps. Just make sure you don't enable SSL or force SSL at CapRover level as it breaks your system.

**Comment by billyjacoby** [comment]
Okay terrific, this is exactly what I’m trying to do.

My original attempt wasn’t on its own dedicated VM though, so I think that’s where I went wrong. I’m spinning up a dedicated one now and ill give this a try. 

Thanks so much for your help!

**Comment by githubsaturn** [comment]
```bash
mkdir -p /captain/data/

echo  "{\"skipVerifyingDomains\":\"true\",\"nginxPortNumber80\":8080,\"nginxPortNumber443\":8443}" >  /captain/data/config-override.json

docker run  -p 3000:3000 \
  -e ACCEPTED_TERMS=true \
  -e BY_PASS_PROXY_CHECK=true \
  -e MAIN_NODE_IP_ADDRESS=127.0.0.1 \
 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-edge
```


Try this and let me know if it works.

**Comment by nikochiko** [comment]
Yup! This works. Thank you so much!

**Comment by carnivash** [comment]
> Yup! This works. Thank you so much!

How did you mange to do it? i tried everything, but Caprover always responds with 502 bad gateway when trying to access behind a reverse proxy. Traefik, Caddy, Haproxy, even Zoraxy, i tried them all but no luck :-(

**Comment by erikdemarco** [comment]
> mkdir -p /captain/data/
> 
> echo  "{\"skipVerifyingDomains\":\"true\",\"nginxPortNumber80\":8080,\"nginxPortNumber443\":8443}" >  /captain/data/config-override.json
> 
> docker run  -p 3000:3000 \
>   -e ACCEPTED_TERMS=true \
>   -e BY_PASS_PROXY_CHECK=true \
>   -e MAIN_NODE_IP_ADDRESS=127.0.0.1 \
>  -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-edge
> Try this and let me know if it works.

why when i install wordpress via 1click app, its not working? Do I need to manually add setting in my router to port forward all trafiic from 8080 to my local caprover installation? how to find this local caprover installation ip?
