### ISSUE TITLE
[Deployment Issue] HTTPS webhook error on internal network deployment

### ISSUE THREAD

**Issue by jgeisslinger** [caprover/caprover#1168]
**What is the problem?**
Using caprover within an isolated network together with an own-hosted git system leads to a build fail using webhook functionality due to missing HTTPS. Caprover ignores the URL insert into the "Repository" field on the deployment tab.

**Steps to reproduce the problem:**
- Install CapRover on internal network without open-world access (only http)
- Install git system (e.g. gitea) on the same network (only http)
- Create deployment webhook by passing git repo information with HTTP URL in caprover and insert information to gitea
- push app to gitea
- watch build log

Caprover tries to connect to the git repo via HTTPS despite the URL provided is only HTTP. 

`Deploy failed!
Error: Cloning into '/captain/temp/image_raw/****/3/source_files'...
fatal: unable to access '**https**://*****@10.10.0.202:3000/********.git/': gnutls_handshake() failed: An unexpected TLS packet was received.`

**Expected**: 
Respect the URL in the repo field and connect via HTTP.

Could you please advise how to change configuration on caprover server to ignore HTTPS or add fix on source code?

**Comment by githubsaturn** [comment]
Thanks for the report. It's fixed and will be released in the next update. Workaround until then.
- Update to use [edge version](https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version) (edge version will be ready 1hr after the commit)
- Use SSH keys to clone your git repo
