### ISSUE TITLE
Having problems adding Google Container Registry as a remote registry

### ISSUE THREAD

**Issue by Olabayo** [caprover/caprover#1171]
Hi everyone,

I cannot seem to be able to add my remote registry (1112 : Authentication failed ...), would like to know what settings anyone has tried that as worked.

Username: {my@gmail.com}
Password: {mypassword}
Domain: gcr.io
Image Prefix: {projectId}

Thanks all.

**Comment by githubsaturn** [comment]
Are you sure you're using the right credentials and URL? Can you log in using the exact same values by running this command:

```
docker login -u my@gmail.com -p yourpassword gcr.io
```

**Comment by Olabayo** [comment]
> Are you sure you're using the right credentials and URL? Can you log in using the exact same values by running this command:
> 
> ```
> docker login -u my@gmail.com -p yourpassword gcr.io
> ```

When i run that I get `Error response from daemon: Get "https://gcr.io/v2/": unauthorized: Not Authorized.`

Doing a light search it seems I might need to do some extra configurations :
https://cloud.google.com/container-registry/docs/advanced-authentication#methods

> You must configure any third party clients that needs to access Container Registry.

**Comment by Olabayo** [comment]
Was able to resolve this by creating a service account, and generating a keyfile and using that to authenticate. Essentially following this explanation  here https://cloud.google.com/container-registry/docs/advanced-authentication#json-key

**Comment by jogiji** [comment]
@olragon what steps did you take while configuring remote registry in caprover setup... essentially i am trying to do a clister setup on a local environment and i am trying to setup google container registry... i was able login via docker commandline.. but when entering the values in caprover setup on dashboard..it is not able to logon.
