### ISSUE TITLE
one click app proxy pool doesn't start

### ISSUE THREAD

**Issue by ravilushqa** [caprover/caprover#1172]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
one click app proxy pool failed on the start
error:
standard_init_linux.go:228: exec user process caused: exec format error

If applicable, content of `captain-definition` file:
-

Steps to reproduce the problem:
install one click app proxy pool

Answers to the following questions where applicable:
- Your OS and version?
Oracle Linux Server release 7.9
- RAM?

**Comment by githubsaturn** [comment]
One click apps are community managed, please post the issues on the PR that introduced the one click app. Proxy pool was added here: https://github.com/caprover/one-click-apps/pull/432
