### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [caprover/caprover#1178]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/blob/0e8656213da1bbba1b8cc5ecdde93416924790ec/CONTRIBUTING.md#security-issues

**Comment by githubsaturn** [comment]
I've also added the SECURITY.md file. Let me know if you're still having trouble finding the contact info.
