### ISSUE TITLE
[Deployment Issue] App token deploy

### ISSUE THREAD

**Issue by Fabian9799** [caprover/caprover#1181]
What is the problem?
I tried to test the new token deploy feature with the cli but the console still shows "building your source code" after its already successfully deployed

Steps to reproduce the problem:
1. Install the cli with `npm install -g caprover`
2. create a simple node app and push it to git 
3. deploy with `caprover deploy --appToken TOKEN --caproverUrl URL --appName APP_NAME`

The app gets deployed successfully but the console still shows this after the successfull deploy:
![image](https://user-images.githubusercontent.com/19490891/132094566-deab3c00-8907-4f7b-8bd7-ab017efe18f9.png)

I tried it on windows sandbox with nothing preinstalled to make sure its not using my login information and that im using the newest version of node, git and the cli (v 2.2.2)

Answers to the following questions if applicable:
- Your OS and version: Windows 10 sandbox
- RAM: 4gb

**Files used:**
captain-definition
```json
 {
  "schemaVersion": 2,
  "templateId": "node/8.7.0"
 }
 ```

package.json
```json
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

index.js
```js
console.log("Test App running!")
```

**Comment by githubsaturn** [comment]
Thanks for the report! `appToken` is mostly to be used on CI/CD machines with `imageName`. Hence the app build logs aren't available when using appToken. 

I've uploaded a [new version of CLI](https://github.com/caprover/caprover-cli/commit/cfd9c87d3769fc021ddd55a3728b7992d2865307) and fixed this. Please let me know if the builder still gets stuck.

update your CapRover CLI:
```
npm i -g caprover
```

**Comment by Fabian9799** [comment]
Everything works now. Thanks for the quick fix.
Is it planned to recieve build logs in the future? It could be useful if someone wanted to give access to only one project to a person and that person could see if the deploy was successfull or not

**Comment by githubsaturn** [comment]
Getting build logs is a different end point. Intentionally, I only whitelisted one endpoint for appToken to keep the scope as small as possible. But the use case that you described makes sense. I'll add it.
