### ISSUE TITLE
Portainer comparison?

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#1184]
Is there any friendly review or biased opinion(s) about Portainer (in Docker mode) comparison with CapRover?

I love using CapRover, enjoy the product, exploring Portainer for a bigger cluster and would appreciate any feedback and opinions on that.

Thanks in advance!

**Comment by githubsaturn** [comment]
Different products.

Portrainer is simply a Docker GUI. On the plus side, it has pretty much everything that Docker offers. It'll give you tens, if not hundreds, of configurations to play with and tune your application. This has a downside, it's not simple, you'll have to manually deploy Let'sEncrypt, nginx, and manually add/remove configurations for them. You'll have to write SSH hooks to push your application and deploy them. If this is something that you're comfortable with, go with Portrainer. If you want all that complexity abstracted away from you, choose CapRover. 

My own personal preference: 
For cloud webservers: I only install CapRover, and it'll do more than enough. If it can do everything that Heroky does, there is no reason for adding something else.

For home servers: I install CapRover and I install Portrainer as a one-click app on CapRover. I use CapRover for simple stuff. But I use Portrainer for more customized stuff such as installing applications that cannot be installed on Docker Swarm, like VPNs, network managers, etc.

**Comment by alexander-potemkin** [comment]
Thank you very much, that makes a lot of sense!
