### ISSUE TITLE
Generated letsencrypt folder has a typo

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1187]
The generated letsencrypt folder in /captain/data/ is caled "letencrypt". Theres a s-letter missing in there.

**Comment by githubsaturn** [comment]
It's a known typo. Unfortunately it can't be fixed as it'll break the older builds. It's like this:
https://stackoverflow.com/questions/3087626/was-the-misspelling-of-the-http-field-name-referer-intentional
