### ISSUE TITLE
Max domains per app, scaling out

### ISSUE THREAD

**Issue by negati-ve** [caprover/caprover#1191]
Hi,

first off, love the work that is being done on this repo/project by @githubsaturn and rest of the contributors

I have a couple of questions regarding domains per app, hoping the community can help me out with this
1. Is there a max domain per app limit?
2. How well will this scale? 
from the first look it doesn't look like caprover's  interface is meant to manage thousands of domains attached to a single app(say in case the app is a multi tenant saas setup)
3. In caprover world, whats the recommended way to manage say a 1000 domains attached to a single app

Thank you

**Comment by githubsaturn** [comment]
1- No limits exposed by CapRover. You may hit limits for Let's Ecnrypt and Nginx.

2- CapRover is not a multi-tenant app. 

3- You can try directly hooking into the api and automating it. But API is undocumented and it's not on the roadmap to document it.
