### ISSUE TITLE
[Question] Trouble proxying through Nginx Proxy Manager

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#1194]
We're using CapRover for production deployment on a Linode server quite nicely, but decided we want to create a secondary CapRover server for development and experimentation on our LAN that is also passed through our [Nginx Proxy Manager](https://github.com/jc21/nginx-proxy-manager) instance.  

No problems setting up the normal things (Ubuntu, Docker, etc.), but started running into trouble with trying to get CapRover @ port 3000 to respond.  First we installed it with this:
```
docker run -e BY_PASS_PROXY_CHECK='true' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
That seemed to allow proper installation, but then we go to `http://192.168.1.211:3000` (the IP on the LAN) CapRover doesn't respond. Similarly with any other ports (80,443). I then set it up on Nginx Proxy Manager such that the public IP passes on over with our sub.domain.tld and have http (80) pointing at 3000 to simply see if I could get it to respond. That didn't work, but if 80 is pointed at 80 then the "Nothing here yet :/" renders fine.

Any thoughts on what a proper setup might look right in this situation to get port 3000 working?

**Comment by githubsaturn** [comment]
if `http://192.168.1.211:3000` doesn't work, it means that something is blocking that port on that machine. You can simply confirm this by SSHing into that machine and run `curl http://127.0.0.1:3000`

But regarding your use case in general, I'm not sure how you want to proxy through nginx proxy manager. Are you planning on making your internal instance accessible from the outside?

**Comment by ylluminate** [comment]
Yes, the goal is to run it through NPM (Nginx Proxy Manager) to the outside world for dev and staging purposes. Obviously there's simply something that's not clear for me yet with regards to the advanced Nginx configuration that should allow multiple ports to be passed through.

**Comment by githubsaturn** [comment]
That's not doable - at least not easily and not cleanly. Nginx Proxy Manager and CapRover have a conflicting responsibility which is to manage your domains and proxy. 

For local installations, I suggest simplying following this guide: 
https://caprover.com/docs/run-locally.html#installation


All you need is a local DNS server that maps `*.staging.company.local` to the IP address of your CapRover box. 

If you want to allow access to outside world, you can use a proxy manager like NPM as mentioned above.

But if you want to enable HTTPS through CapRover built-in Let's Encrypt, you cannot use proxy manager, you have to use port forwarding. i.e., port forward 80 and 443 from your router to your CapRover instance.

**Comment by ylluminate** [comment]
So @githubsaturn please correct me if I'm misunderstanding here - and perhaps you can elaborate further:

You seem to be recommending using the "Run Locally" section and use the `192.168.1.211` IP address internally for all local development and `:3000` admin and then use NPM to forward 80 or 443 traffic to the server housing that?

This seems to then also not verify domain names, which seems to be beneficial, but I suspect somehow CapRover will still differentiate various inbound subdomains like `someappname1.staging.domain.tld`, `someappname2.staging.domain.tld`, etc?

**Comment by githubsaturn** [comment]
Let me explain this through an example that people use frequently:

Imagine you have this network:
```
┌───────────────────────┐
│    Your Router        │
│                       │
│     public IP         │
│    11.22.33.44        │           your private network
├───────────────────────┴─────────────────────────────────────────────────────────────────────┐
│                                                                                             │
│ ┌────────────────┐      ┌──────────────────┐        ┌──────────────────┐                    │
│ │                │      │                  │        │                  │                    │
│ │    PC1         │      │     PC2          │        │       PC3        │                    │
│ │                │      │                  │        │                  │                    │
│ │  192.168.1.10  │      │    192.168.1.11  │        │    192.168.1.12  │                    │
│ │                │      │                  │        │                  │                    │
│ └────────────────┘      └──────────────────┘        └──────────────────┘                    │
│                                                                                             │
│                                                                                             │
│                                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────┘
```

You can install CapRover on PC3 by simply running this command:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker run -e MAIN_NODE_IP_ADDRESS=192.168.1.12 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

The only extra bit is this: ` -e MAIN_NODE_IP_ADDRESS=192.168.1.12` and also disabling domain verification on CapRover.


At this point, you should be able to access your CapRover dashboard from PC1 and PC2 via `http://192.168.1.12:3000` on your browser. 

Still you aren't able to deploy apps, but the dashboard should be accessible.
If the dashboard isn't accessible, you have an internal firewall that prevents PC1 from accessing PC3.

If the dashboard is accessible, move on to the next stages.


### option 1 - only internal usecase:

You can install CapRover on your internal network so that it's only accessible from your private network. If you want to do that, you have to assign `*.caproverinstance.local` or something similar in your local DNS server to point to `192.168.1.12`. If you don't have a local DNS server you cannot do this. 

Some local DNS servers, like PiHole, don't allow wildcard in the local DNS entries, in that case, you have to add `captain.caproverinstance.local` to point to the IP. and in the future, add your apps names one by one. It's tedious but doable. 

Now, go to the dashboard via  `http://192.168.1.12:3000` and update the root domain to `caproverinstance.local`. 

At this point, you should be able to access the dashboard via `http://captain.caproverinstance.local` in your browser. 
If you are having problem here, it means your local DNS server isn't working as expected. You'll have to fix it.

Note that you should not (cannot) enable HTTPS for internal domains.

### option 2 - make the instance accessible from the outside.

requirement: your public IP address must be a static IP address. 

This is very similar to how you install CapRover on a publicly available VPS. All you need to do is to enable port forwarding on your router:
```
port 80 of router => port 80 of 192.168.1.12
port 443 of router => port 80 of 192.168.1.12
```
Now use your regular DNS provider and map `*.domain.com` to the public IP address of your network. 

Now, like a normal installation, just login to `http://192.168.1.12:3000` and update the root domain to `domain.com`

At this point, your instance should be accessible from `http://captain.domain.com`. You can enable HTTPS and deploy your apps.

**Comment by ylluminate** [comment]
Thanks very much @githubsaturn for the presentation there with solid options and clarity.  I went ahead and uninstalled caprover as per:
```
docker service rm $(docker service ls -q)
rm -rf /captain
docker swarm leave --force
docker system prune --all --force
```
I then reinstalled via:
```
mkdir -p /captain/data
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker run -e MAIN_NODE_IP_ADDRESS=192.168.1.12 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
This seemed to install fine, however I can't hit port 3000 now.

Services seem to be up:
```
$ docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                      NODE                  DESIRED STATE   CURRENT STATE                  ERROR     PORTS
fytw6pg141nhdo4x2ootrejnf   captain-captain.1       caprover/caprover:1.10.0   r710-1-pve-caprover   Running         Preparing about a minute ago
1tpa8jr6rjyqtzgamxw287tr3    \_ captain-captain.1   caprover/caprover:1.10.0   r710-1-pve-caprover   Shutdown        Shutdown about a minute ago
```

I don't really see any errors in the log per se...

` curl localhost:3000 -v` fails though (same for the actual IP):
```
*   Trying ::1:3000...
* TCP_NODELAY set
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* connect to 127.0.0.1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused
```
`ufw` is inactive.

Any thoughts?

**Comment by githubsaturn** [comment]
Not sure what's going on here. What's the output of `docker ps`? Do you see the mapped ports?

**Comment by ylluminate** [comment]
```
$ docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                                                                      NAMES
f73485c521d8   caprover/certbot-sleeping:v1.6.0   "/bin/sh -c 'sleep 9…"   15 minutes ago   Up 15 minutes   80/tcp, 443/tcp                                                            captain-certbot.1.np6f9yu1hx00dd8yoiwug8btu
ae587d27873c   nginx:1                            "/docker-entrypoint.…"   16 minutes ago   Up 16 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   captain-nginx.1.9dj5kg6xjjq68byrdzk2s6fnv
b82682034478   caprover/caprover:1.10.0           "docker-entrypoint.s…"   17 minutes ago   Up 16 minutes   3000/tcp                                                                   captain-captain.1.qjiv0v9gvftldx3je6fjkjirh
```

**Comment by githubsaturn** [comment]
Looks like your port 3000 is correctly mapped. My only guess is that you have multiple network interfaces and it is bound to another one, but I don't undestand why localhost:3000 wouldn't work. You can also try:
```
curl -v http://192.168.1.12
```
from the same machine.

**Comment by ylluminate** [comment]
Huh, crazy, yeah, `curl -v http://192.168.1.12` locally works and I can even hit it with any other workstation on the network. The `Nothing here yet :/` is returned.  But yeah, `3000` does not work. Hrmmm. 

Just to give you a complete picture:
```
$ ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 4480  bytes 189419 (189.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5630  bytes 8735732 (8.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker_gwbridge: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 2670  bytes 119842 (119.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3319  bytes 5243314 (5.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.240.0  broadcast 192.168.15.255
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 11239702  bytes 3924415628 (3.9 GB)
        RX errors 0  dropped 57142  overruns 0  frame 0
        TX packets 427142  bytes 27790517 (27.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 28  bytes 1676 (1.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28  bytes 1676 (1.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth3794087: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 24  bytes 11983 (11.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 44  bytes 3996 (3.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth41b3f7c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27  bytes 2022 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth5c8a651: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 800  bytes 43985 (43.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1095  bytes 1746975 (1.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vetha589531: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1436 (1.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by githubsaturn** [comment]
Okay cool, yea this usually happens when you have multiple network interfaces.

Anyways, you can simply map `captain.captain.localhost` to `192.168.1.12` and start configuring your instance. You can simply do this by adding this line to your `/etc/hosts` file on your local machine:

```
192.168.1.12   captain.captain.localhost
```

**Comment by ylluminate** [comment]
So I think you're saying I need to bind CapRover to either the correct interface or all interfaces... Right?  I thought `0.0.0.0` would listen to all interfaces, but apparently this is not the case for port 3000.  So, if so, where do I do this for CapRover?

**Comment by githubsaturn** [comment]
It's a bit different. Port 3000 is on Docker ingress network, whereas your port 80/443 are on host network. I don't know how you would change this. You can ask this in a Docker forum. But chances are that the following curl would work on your server:
```
curl 172.19.0.1:3000
```

**Comment by githubsaturn** [comment]
Also, FYI https://github.com/caprover/caprover/issues/1206#issuecomment-927197118

**Comment by ylluminate** [comment]
@githubsaturn thanks for annotating your effort on #1206. I gave it a shot by switching to edge:
```
docker pull caprover/caprover-edge:0.0.1
docker service update captain-captain --image caprover/caprover-edge:0.0.1
```

I assume that will restart everything alright. Unfortunately 80 and 443 still are available (well 443 of course has an invalid cert), but 3000 is still `ERR_CONNECTION_REFUSED`.

**Comment by githubsaturn** [comment]
Ah sorry - the port binding happens at the installation time, so you'd have to use the edge image for the installation script:

First, [uninstall your instance](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain), then run
```
docker run -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-edge:0.0.1
```

**Comment by ylluminate** [comment]
I think you mean `192.168.1.12` instead of localhost/127.0.0.1, right?

**Comment by githubsaturn** [comment]
Yes

**Comment by ylluminate** [comment]
Alright! YOU FIXED IT!!!!! It worked:
```
mkdir -p /captain/data
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker run -e MAIN_NODE_IP_ADDRESS= 192.168.1.12 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-edge:0.0.1
```
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/p9ukJPmG/ecc3f72f-50cc-4040-b68b-6c4db52b6a37.jpg?v=ef938c6cb49e49382333ade0ff5610d6)

Thank you!

Could you please advise, how will I switch back to non-edge once this is released? Do I need to uninstall/reinstall yet again or can I simply `docker service update captain-captain --image caprover/caprover:latest` since the proper port is already bound since install?

**Comment by githubsaturn** [comment]
You can simply update the image:
```
docker service update captain-captain --image caprover/caprover:latest
```

**Comment by ylluminate** [comment]
Great, thanks again. Really appreciate your help here. 

I still need to do some research here in that I really need to be able to run Nginx Proxy Manager in conjunction with CapRover. I realize what you've said above, but I'd prefer to not give up yet insomuch that both services are critical to our needs currently.  I guess there must be a way to do it via the server directive (https://github.com/jc21/nginx-proxy-manager/issues/689) and it might be clunkier in some aspects, but I feel as though it's essential to do this presently.

**Comment by allahcurse** [comment]
@ylluminate 

Were you able to resolve this issue?

I'm stuck on the same thing, I need to run caprover behind Nginx Proxy Manager

**Comment by ylluminate** [comment]
I had some more trouble trying to figure it out and then some other things derailed me. I still want (*need*) to do it, but have had to deprioritize my research/effort. It's such a shame that it's not a standard setup since the projects are perfect companions.

**Comment by dangxunb** [comment]
Does anyone have an alternative solution for this? I've tried a day to solve https problem between Nginx Proxy Manager and caprover before I found this issue. I need to setup 2 caprover instance in my home network too. Only direct forward port 443 from router to caprover instance work.

**Comment by mgutt** [comment]
Port 3000 is used by Nginx Proxy Manager itself. Not sure why it is not documented.

![image](https://user-images.githubusercontent.com/10757176/216772703-30c1830e-1ea9-4d07-b2e9-d9dc2bcdc4fc.png)

Solution:
Change the port 3000 in the target container if possible and if not, change the network of the target container or Nginx Proxy Manager. For example if Nginx Proxy Manager runs in bridge network, it does not expose (block) port 3000.

**Comment by sumersm7** [comment]
I have a solution (kind of) need more testing to be sure.

Iam a beginner in DevOps, docker, web security and nginx and proxy 

The solution is inspired by the self hosting, home lab community. They use portainer or proxmox for docker/server management and expose port.

My setup 
1. Cheap VPS for static IP nginx proxy manager
2. Tailscail as VPN (both machines)
3. Local machine (docker on windows)
4. [Acrylic DNS Proxy](https://mayakron.altervista.org/support/acrylic/Home.htm)
5. 2 sub domain both pointing to VPS static IP, example 
    A. *.Local.domain.tld (for caprover)
    B. *.vps.domain.tld (for nginx proxy manager)


### Step 1
Install nginx proxy manager and point dash.vps.domain.tld to xxx.xxx.vps.ip:81 for nxpm dashboard for easy access.

### Step 2
Install tailscail on both the machine and connect.

### Step 3
Install Acrylic DNS Proxy coz windows Host file doesn't let u create wild card domains. And add 192.168.xx.xx *.local.doamin.tld or whatever ip of the machine is ,( i tired with 127.0.0.1 it didn't work maybe I did something wrong feel free to try urself)

Check if dns is working or not by power shell/cmd command nslookup captain.local.domain.tld point to 100.100.xx.xx(tailscail ip) and port 3000(caprover port)

### Step 4
Install docker on windows and caprover with Main Node IP=192.168.xx.xx env variable from the docs for locally run. 
And then cli server setup like normal 

### step 4.5 (what i have tried, need to try with more apps to be certain if it works)
Install WordPress with database 
Go to installed wordpress, App settings tabs , add port mapping for any port external port XXXX : 80(to wordpress port)
Do not open domain and install WordPress at this step

### step 5
In proxy manager www.local.domain.tld : XXXX (port number entered in previous setup)

And then open the link and wordpress will normally install 


If u have any query or suggestions, feel free to tag me.
