### ISSUE TITLE
Play with CapRover Error

### ISSUE THREAD

**Issue by liquidpeachy** [caprover/caprover#1195]
I'm trying to play with CapRover with Docker Hub and Lets Play with Docker. I followed the instructions here exactly:
https://caprover.com/docs/play-with-docker.html

But I'm getting this error on Docker Hub:

`docker: failed to register layer: Error processing tar file(exit status 1): write /usr/share/locale/pt_BR/LC_MESSAGES/sed.mo: no space left on device.`

And then this error:

```==============================================
==============================================
Waiting for CapRover to finish installation...
==============================================
==============================================
 
 
 
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.```

**Comment by githubsaturn** [comment]
I just tried it and it succeeded.

There are a bunch of space related issues on PlayWithDocker. After all, it's a free service from Docker and nodes run of space from time to time. 
https://github.com/play-with-docker/play-with-docker/search?q=No+space+left+on+device&type=issues

![image](https://user-images.githubusercontent.com/10582082/133360967-f725e17a-13d2-4ce6-8336-f98da44b642f.png)
