### ISSUE TITLE
Can this coexist with webmin/virtualmin

### ISSUE THREAD

**Issue by FireRedDev** [caprover/caprover#1196]
I use virtualmin to host wordpress instances for multiple users and domains on a vps. Can caprover coexist with it? Could it even maybe make use of the seperate domain spaces in virtualmin?

**Comment by githubsaturn** [comment]
Short answer: No.

More details:
CapRover needs your port 80 and 443 to be controlled by it. Its responsibility of managing domains and SSL conflicts with virtualmin.
