### ISSUE TITLE
Commit SHA does not propagate to built demo app

### ISSUE THREAD

**Issue by nickdbush** [caprover/caprover#1198]
I've upgraded my instance of Caprover to 1.10.0 (confirmed in the settings page) and deployed the test app from your git repo -- however, the sha does not seem to be propagating: http://test-git.fabric.studentnewspaper.org/

I have made no other changes to the app config (no other environment variables). I'm not sure what sort of information would be helpful in tracking down the issue, but am happy to provide whatever may be needed.

Thanks for getting the PR into Caprover though, this will be really helpful for a project I'm working on!

_Originally posted by @nickdbush in https://github.com/caprover/caprover/issues/1049#issuecomment-922519516_

**Comment by githubsaturn** [comment]
How do you deploy your app? What argument do you pass to `caprover deploy`? Do you use image name, tarfile, or such? Or you just use bare `caprover deploy`?

**Comment by githubsaturn** [comment]
Also, keep in mind that this env var is only available during the build process. If you want to make it available in the runtime, you have to add these two lines in your Dockerfile:
```
ARG CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}
ENV CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}
```

**Comment by TobiasWehrum** [comment]
I might have the same problem (with my own app, not the demo app). If I set CAPROVER_GIT_COMMIT_SHA manually in "Environmental Variables", I can read that in `RUN echo` commands, during app building and while my app is running, but without adding CAPROVER_GIT_COMMIT_SHA manually as an environment variable, CAPROVER_GIT_COMMIT_SHA stays completely empty.

Here is my Dockerfile:

```
FROM node:14-alpine

ARG CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}
ENV CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}

RUN echo SHA is: $CAPROVER_GIT_COMMIT_SHA

RUN apk update && apk upgrade && apk add --no-cache git
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app/
COPY ./package-lock.json /usr/src/app/

RUN npm install && npm cache clean --force

COPY ./ /usr/src/app

RUN npm run build

ENV NODE_ENV production
ENV PORT 80
EXPOSE 80

CMD [ "npm", "start" ]
```

I'm using "Method 3: Deploy from Github/Bitbucket/Gitlab".

**Comment by githubsaturn** [comment]
@TobiasWehrum  - thanks for the additional info!

You're correct. Previously `CAPROVER_GIT_COMMIT_SHA` was only implemented for `caprover deploy` command. This diff adds the functionality for "Method 3: Deploy from Github/Bitbucket/Gitlab" as well. 
https://github.com/caprover/caprover/commit/d7eefe6835938cb4be7e2403a781c5c6872abd3f
