### ISSUE TITLE
How to deploy a static site?

### ISSUE THREAD

**Issue by therohitdas** [caprover/caprover#1200]
Please clearly state your question:
I want to deploy a static site. I used the ViteJs cli tool to generate it. ( VanillaJS template )

when you run `npm run build`

It outputs the built static site in the `./dist` directory.

- How can I deploy it ? 
- What will be the captain-definition file?

Also if I added my root domain while installing Caprover, e.g. - and the running instance is at `https://captain.therohitdas.com`
How can I deploy an app to `https://therohitdas.com` ?

**Comment by githubsaturn** [comment]
For static websites, there are multiple ways. You can use [this technique](https://caprover.com/docs/recipe-deploy-create-react-app.html) to build the website on your machine and then deploy the built artifact. This is good for low end servers without much RAM and CPU. Or you can just have your own `Dockerfile` , like [this](https://mherman.org/blog/dockerizing-a-react-app/)


Regarding the root domain, all you need to do is to add the root domain as a custom domain to your app:

![image](https://user-images.githubusercontent.com/10582082/134438605-da57d7b5-9245-4e6d-b791-fd3cffd7af20.png)
