### ISSUE TITLE
[Question] Leantime folder seems to be missing, only mysql is available in /volumes

### ISSUE THREAD

**Issue by ebecaf** [caprover/caprover#1201]
I setup Leantime as 'pm' so there should be a folder /var/lib/docker/volumes/srv-captain--pm, but there isn't, there is only one for the mysql (srv-captain--pm-mysql)

I would like to access the Leantime files. I can see volume folders for all my other CapRover apps except this one.

Can anyone advise where these files might be? I've tried looking at the Leantime docker and [/leantime/leantime](https://github.com/Leantime/leantime/) with nothing helpful. I can't post there as this seems to be a CapRover issue.

Thank you.

_Update_ I've used `grep` and got my container string, I've opened /docker/containers/[mycontainer] and /docker/volumes/[mycontainer] but neither holds the Leantime files.

**Comment by ebecaf** [comment]
Okay I found them in find /var/lib/docker/overlay2/[mycontainer]/merged and /overlay2/[mycontainer]/diff (several versions of this).

I'm not sure which to edit. I tried /merged as there was only one of these which seems to have worked.

_(FYI I'm only editing the language files)_

**Comment by githubsaturn** [comment]
One click app Leantime doesn't expose a persistent directory:
https://github.com/caprover/one-click-apps/blob/6f2f6840f301e5fe7a99ead589984ccbd9c0ab77/public/v4/apps/leantime.yml#L15-L23

This is in accordance with their official docker compose file: https://github.com/Leantime/docker-leantime/blob/master/docker-compose.yml
