### ISSUE TITLE
Change the IP of the manager/leader of the swarm [Question]

### ISSUE THREAD

**Issue by pixply** [caprover/caprover#1202]
I have a server that has two ethernet interfaces. eth0 for the public address and eth1 with a private address of 192.168.0.1 which is connected to a vlan with my worker nodes (192.168.0.2). During the caprover installation it automatically initiates the swarm with the public ip. How can I change this to the private one for the communication with the workers. Normally with docker it would be `docker swarm init --advertise-addr 192.168.0.1` and then add the nodes `docker swarm join --token xyz 192.168.0.2:2377`

**Comment by githubsaturn** [comment]
You can pass it as `MAIN_NODE_IP_ADDRESS` to CapRover installer, e.g.:
```
docker run -e MAIN_NODE_IP_ADDRESS='192.168.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

**Comment by pixply** [comment]
thank you very much
