### ISSUE TITLE
[Question] Limit/Allocate App Disk Space

### ISSUE THREAD

**Issue by chriskol** [caprover/caprover#1203]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Hey I'm a newbie to docker and all this and in some aspects of server admin.  I was wondering if there was a way I could limit the amount of disk space an app took up.  In this particular case, I'm looking at a wordpress app so persistent.  Use case would be if I hosted a friend's Wordpress I could limit the amount of total disk space they could take up with uploads beyond just limiting the size of each upload (which I believe is what client_max_body_size does?).

Thank you

**Comment by githubsaturn** [comment]
`client_max_body_size` is different. It's used to limit size of each request, not the total space used on disk.

If you want to limit the size on the disk, you can do that by create a partition that has a limited size, then map it to your wordpress directory. It is a relatively complex process and requires some level of understand of disk management and linux. So I wouldn't recommend it if you're new to the field.
