### ISSUE TITLE
After removing node, I get "1000 : Cannot find the service. Try again in a minute..." when trying to "Save & Update" a new app [Question]

### ISSUE THREAD

**Issue by pixply** [caprover/caprover#1207]
This all seems to be a result of me removing one of the nodes from the cluster... The node was empty with no apps deployed. I removed it with `docker swarm leave` on the worker and `docker node rm <nodeid>` on the leader/master.

It seems like caprover/docker still tries to deploy to the old node. Although in the cluster page it only shows the master.  

I created a blank new app and I am trying to edit the settings of the app. When I want to save it, I get this message:

`1000 : Cannot find the service. Try again in a minute...`

There is no `Node ID` in the new app. And when I try to set it manually i get

`1110 : ImageName for deployed version is not available, this version was probably failed due to an unsuccessful build!`

The deployment log show an error for the initial blank deployment:

```
------------------------- Mon Sep 27 2021 09:52:42 GMT+0000 (Coordinated Universal Time)
Build started for devtest
Step 1/1 : FROM caprover/caprover-placeholder-app:latest

---> 895d05795b96
Successfully built 895d05795b96
Successfully tagged img-captain-devtest:latest
Pushing to remote: registry.cr.globalcomparison.net:996/captain/img-captain-devtest:0
Server: registry.cr.globalcomparison.net:996
This might take a few minutes...
{"message":"no basic auth credentials"}
no basic auth credentials
Push failed...
Build has failed!
----------------------
Deploy failed!
Error: Push failed: 
{"message":"no basic auth credentials"}no basic auth credentials
```

Do I have to change any configuration?

**Comment by githubsaturn** [comment]
You don't need to change any configuration. Do you see your newly created app in `docker service ls` output?

**Comment by pixply** [comment]
Unfortunately not. It really doesn't get deployed at all:

```
------------------------- Tue Sep 28 2021 15:27:46 GMT+0000 (Coordinated Universal Time)
Build started for testapp
Step 1/1 : FROM caprover/caprover-placeholder-app:latest

---> 895d05795b96
Successfully built 895d05795b96
Successfully tagged img-captain-testapp:latest
Pushing to remote: registry.cr.globalcomparison.net:996/captain/img-captain-testapp:0
Server: registry.cr.globalcomparison.net:996
This might take a few minutes...
{"message":"no basic auth credentials"}
no basic auth credentials
Push failed...
Build has failed!
----------------------
Deploy failed!
Error: Push failed: 
{"message":"no basic auth credentials"}no basic auth credentials
```

**Comment by githubsaturn** [comment]
This is a whole different issue. Go to your CLUSTER tab and change the default PUSH REGISTRY to DISABLED.

![image](https://user-images.githubusercontent.com/10582082/135284787-4cb24ca8-dc3d-4d36-93be-b7874b3ca5ce.png)
