### ISSUE TITLE
[Question] How to remove the default subdomain when adding a custom domain?

### ISSUE THREAD

**Issue by aaron5670** [caprover/caprover#1214]
# How to remove the default subdomain when adding a custom domain?
I attached a custom domain to a app, but how can I remove the default subdomain in Caprover?

![image](https://user-images.githubusercontent.com/17295145/136266059-0a1b6416-0fb0-4180-87e8-e3e084d3779d.png)

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/issues/642#issuecomment-654960663
