### ISSUE TITLE
deploy from self-hosted gitlab, building failed due to cert fail.

### ISSUE THREAD

**Issue by g05357005** [caprover/caprover#1215]
I have a caprover 1.10.0 on centos 7.
one of my app is set to deploy from a self-hosted gitlab, which is using lets encrypt on ssl.

seems facing to letsencrypt's Sep29 root cert problem, 
now I can't build from the gitlab webhook.

the caprover log says

```
captain-captain.1.gpzdf5sqckbl@lineauth    | Error: Cloning into '/captain/temp/image_raw/linebot/157/source_files'...
captain-captain.1.gpzdf5sqckbl@lineauth    | fatal: unable to access '{MY-GITLAB-GIT-REPO-WITH-PASSWORD}': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
captain-captain.1.gpzdf5sqckbl@lineauth    | 
captain-captain.1.gpzdf5sqckbl@lineauth    |     at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45
captain-captain.1.gpzdf5sqckbl@lineauth    |     at new Promise (<anonymous>)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at Generator.next (<anonymous>)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at runMicrotasks (<anonymous>)
captain-captain.1.gpzdf5sqckbl@lineauth    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The self-hosted gitlab server is using ISRG Root chained to DST Root 

```
Common name: R3
Organization: Let's Encrypt
Location: US
Valid from September 3, 2020 to September 15, 2025
Serial Number: 912b084acf0c18a753f6d62e25a75f5a
Signature Algorithm: sha256WithRSA
EncryptionIssuer: ISRG Root X1 |  
-- | --
Common name: ISRG Root X1
Organization: Internet Security Research Group
Location: US
Valid from January 20, 2021 to September 30, 2024
Serial Number: 4001772137d4e942b8ee76aa3c640ab7
Signature Algorithm: sha256WithRSA
EncryptionIssuer: DST Root CA X3
```

please advice.

**Comment by g05357005** [comment]
update:

after running 
```
git config --global http.sslverify false
```
in caprover container fixed this problem.

**Comment by Alfagun74** [comment]
I have the same problem, thanks @g05357005 for the hotfix but we definitely need a persistent solution

**Comment by githubsaturn** [comment]
This seems like a very broad issue after Let's Encrypt root certificates expired. A few other instances:
- https://community.letsencrypt.org/t/lets-encrypt-certificate-verification-failed-with-jenkins/161862/7
- https://forum.gitlab.com/t/gitlab-runner-server-certificate-verification-failed/59450


 I'll have to look into this further. But, probably, we need to issue a hotfix with the new root certificate.


PS: Be extremely careful about running `git config --global http.sslverify false` - it allows MITM attack. Do not use it unless you are really sure about this.

**Comment by githubsaturn** [comment]
This is really bad actually. Looks like the root certificate wasn't built in the base image where the latest CapRover image was branch off. 

A simple curl request for any website that uses LetsEncrypt returns an error
```
docker run caprover/caprover:1.10.0 curl -I https://stackoverflow.com
```

This means in near future self healthcheck for CapRover instances may start to fail and that'll result in constant restarts of instances. I'm working on a fix right now.

**Comment by githubsaturn** [comment]
Okay - it is fixed by just [rebuilding](
https://github.com/caprover/caprover/commit/e7ef9261ef3dc666ed11b6ea5d7b1e7b0888c1ad) the image. I'll have to deploy a new build and the issue will be fixed. To verify you can simply run the edge image to confirm:
```
docker run caprover/caprover-edge:latest curl -I https://stackoverflow.com
```

I'll be release 1.10.1 hotfix shortly.
