### ISSUE TITLE
[Deployment Issue] Deploying of private images from docker registry always ends with a 404

### ISSUE THREAD

**Issue by DanEEStar** [caprover/caprover#1224]
What is the problem?

I cannot not deploy a private image which is stored on the docker registry. The command always ends with a 404.

This happens on the command line but also when I want to do it on from the web GUI with "Method 6"

```
> caprover deploy -i iterativ/coopgames


Preparing deployment to CapRover...

Deploying coopgames to captain-iterativ...

Building your source code...

------------------------- Tue Oct 12 2021 13:36:06 GMT+0000 (Coordinated Universal Time)
Build started for coopgames
An explicit image name was provided (iterativ/coopgames). Therefore, no build process is needed.
Pulling this image: iterativ/coopgames This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 404) unexpected - pull access denied for iterativ/coopgames, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Something bad happened. Cannot deploy coopgames at captain-iterativ.
```

![CleanShot 2021-10-12 at 15 39 37](https://user-images.githubusercontent.com/1432939/136966886-e6db61c1-fb5d-4349-a78b-b2bb03e241ed.png)

I added the credentials to "Cluster / Docker Registry Configuration"

![CleanShot 2021-10-12 at 15 40 11](https://user-images.githubusercontent.com/1432939/136967093-105559d3-86f3-4c86-8c5b-222df28425c2.png)

With the very same credentials as in the "Cluster / Docker Registry Configuration" I can pull the docker image without problems directly from within the server:

```
root@caprover-ubuntu1808:~# docker pull iterativ/coopgames
Using default tag: latest
latest: Pulling from iterativ/coopgames
Digest: sha256:45badac553c0ed8a86abb145008080e21952034bb0aa6123cd14ce20757e76cd
Status: Image is up to date for iterativ/coopgames:latest
docker.io/iterativ/coopgames:latest
```

Maybe this is somehow related to #1189 ?

When the same image is "public" and not "private" it will work without problems...

### Workaround

After downloading the docker image directly within the server with the docker CLI I can at least deploy it via "Method 4: Deploy plain Dockerfile". But it is pretty annoying to do this extra steps...

```
FROM iterativ/coopgames
```

**Comment by githubsaturn** [comment]
Docker CLI uses docker.io as the default registry behind the scene. All you need to do is to use `domain/user/image` format.

So, in your case, `docker.io/iterativ/coopgames`

**Comment by githubsaturn** [comment]
exacly same results? that's not possible.... port 996 bypasses nginx. It's not possible to see an nginx error page

**Comment by githubsaturn** [comment]
okay, yea that's different.Two things:
- the built-in registry is only made to work with CapRover internal workings by default, you shouldn't need to manually push images to it
- having said that, it should be doable to manually push to it for experimentation purposes. You just need to make sure that the port is open and your registry is running. Run:
```
docker service ls # to check if registry is running and the port is mapped

ufw status # to check the port status
```

**Comment by ashutosh-elivaas** [comment]
And I am facing the same issue, even I have configured everything correctly;
