### ISSUE TITLE
caprover-caprover service not working after update to v1.10.1

### ISSUE THREAD

**Issue by BetaHuhn** [caprover/caprover#1230]
Hey, I just updated Caprover to the latest version v1.10.1 but after waiting for a few minutes the dashboard still hasn't come back to life. I ssh into my server and checked the logs. The CPU jumped to 70% and inbound bandwidth to ~363 Mbps (before it was at 4 kb/s).

Running `docker service ps captain-captain --no-trunc` returns:

```
ID                          NAME                    IMAGE                      NODE                 DESIRED STATE       CURRENT STATE             ERROR                                       PORTS
i9k4hkg2bj4mjnbykhe2sy7ej   captain-captain.1       caprover/caprover:latest   MaxServerFrankfurt   Ready               Rejected 3 seconds ago    "No such image: caprover/caprover:latest"
pv15txe617eq6mpv6q1cvio1q    \_ captain-captain.1   caprover/caprover:latest   MaxServerFrankfurt   Shutdown            Rejected 8 seconds ago    "No such image: caprover/caprover:latest"
8ee223mryht3gj70m6qae0rk6    \_ captain-captain.1   caprover/caprover:latest   MaxServerFrankfurt   Shutdown            Rejected 13 seconds ago   "No such image: caprover/caprover:latest"
78r8q2273siyr21279ga8na8k    \_ captain-captain.1   caprover/caprover:latest   MaxServerFrankfurt   Shutdown            Rejected 18 seconds ago   "No such image: caprover/caprover:latest"
45z520ri9rmhra2hv3g9siotq    \_ captain-captain.1   caprover/caprover:latest   MaxServerFrankfurt   Shutdown            Rejected 23 seconds ago   "No such image: caprover/caprover:latest"
```

The important part is `No such image: caprover/caprover:latest`.

To test if this was an issue with my machine I ran `docker pull caprover/caprover:latest > /dev/null` and got the following error:

`Error response from daemon: toomanyrequests: You have reached your pull rate limit.`

I guess the server tried to pull the image it didn't find too often and got rate limited. It is currently still trying to start the service but always failing when pulling the image and returning the same error.

I tried to restart Caprover with `docker service update captain-captain --force` and got the following:

```
captain-captain
overall progress: 0 out of 1 tasks
1/1: preparing [=================================>                 ]
service update paused: update paused due to failure or early termination of task rlxw7m8555p94d36h920xxwg6
```

Any ideas what might have caused this issue and how I can resolve it?

<details>
<summary>

Output of `uname -a && lsb_release -a && free -h`:

</summary>

```
Linux MaxServerFrankfurt 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:           981M        414M        117M        1.6M        448M        457M
Swap:          499M        197M        302M
```

</details>

**Comment by githubsaturn** [comment]
This is a Docker Hub issue. Some images that fail, constantly ping DockerHub and that'll use up all your allowable quota.

**Comment by githubsaturn** [comment]
I suggest try manually pulling the new image, then try to update.
