### ISSUE TITLE
[Question] Is forcing https disabling internal container hostname access ?

### ISSUE THREAD

**Issue by alexisvisco** [caprover/caprover#1238]
Hi :)

Is forcing https is breaking the internal hostname auto-generated by caprover ? 

I have a server api deployed and I have forced https on it, when in another container I want to reach the api container with it's hostname (http://srv-captain--name:port) it does not works.  (BTW i got a `getaddrinfo ENOTFOUND` and not a redirect)

**Comment by githubsaturn** [comment]
> Is forcing https is breaking the internal hostname auto-generated by caprover ?

No, force HTTPS is applied on the nginx layer and that layer is not used when you're using internal `srv-captain--appname` format. 

Most likely you have a typo in your host name. Make sure you have the "two" hyphens after `srv-captain`. Check and if you don't have any typo, try to manually debug:

- Shell into your container and manually run a curl command: `curl -v http://srv-captain--appname`
- Does this work?

**Comment by alexisvisco** [comment]
In reality, it was because I  reach this hostnames on build time (for building a nextjs application) so because you I am not in a container network I think the hostname are not availables but the https domain works).

**Comment by githubsaturn** [comment]
That's correct! Docker swarm doesn't use the ingress network during the build time. However, they are available in runtime.
