### ISSUE TITLE
[Deployment Issue] Can't run AppSmith

### ISSUE THREAD

**Issue by ebecaf** [caprover/caprover#1250]
I have tried to run AppSmith using various versions (docker tags).

I have added a MongoDB (also running on CapRover) to the configuration.

AppSmith runs in terms of giving me a webpage, but there is no login, no setup. 

I get this error popup on the appsmith page: "Appsmith server is taking too long to respond. Please try again after some time"

I also get this in the console:
"Failed to load resource: the server responded with a status of 502 (Bad Gateway)          /api/v1/users/me:1 Failed"

I've also added some extra Environmental Variables to reference the MongoDB but it's not doing anything.

Am I missing something? Can anyone else get AppSmith working at all?

Thank you.

**Comment by githubsaturn** [comment]
One click apps are community managed. You can find the PR / issue related to them and discuss with other people who might have expertise. See this one: https://github.com/caprover/one-click-apps/issues/280
