### ISSUE TITLE
[Question] Clusters, specs, thoughts

### ISSUE THREAD

**Issue by Propaganistas** [caprover/caprover#1251]
Hi

I've been reading through the docs with lots of interest. Thank you for open sourcing Caprover. I've got a few questions about the scaling/cluster feature.

When scaling an app's instances, is it possible to configure the target servers? For example, if you have 3 servers, deploy all instances of a specific app on 1° and 2° and never use 3°.  Or will Caprover always take all servers into account when distributing the instances?

I'm planning to deploy multiple apps with the same codebase. Each app will have a specific job (serving web, running queue, ...). Do you have any advice regarding the codebase's location? Replicated inside each app (default)? Or perhaps on a shared attached volume, similar to persisted data such as web uploads?

I guess the next questions are only valid if target servers can be selected.

Would it make sense to deploy all instances of, let's say, a database app onto one server? I would presume not, because of introducing a single point of failure (the server itself).

Imagine that a specific server has lower overall specs (less RAM, less powerful vCore, ...). Would it make sense to use this server solely for the purpose of "manager" node and deploy app instances on other servers?

Looking forward to your insights!

**Comment by githubsaturn** [comment]
> When scaling an app's instances, is it possible to configure the target servers? For example, if you have 3 servers, deploy all instances of a specific app on 1° and 2° and never use 3°. Or will Caprover always take all servers into account when distributing the instances?

Yes, and No. CapRover doesn't have built in UI for it. But you can do that via docker command, and CapRover fully respects those changes and don't override them. See [here](https://docs.docker.com/engine/swarm/services/#placement-constraints)

> I'm planning to deploy multiple apps with the same codebase. Each app will have a specific job (serving web, running queue, ...). Do you have any advice regarding the codebase's location? Replicated inside each app (default)? Or perhaps on a shared attached volume, similar to persisted data such as web uploads?

Nothing too specific here. If you have one repo that hosts multiple apps, you can create multiple `captain-definition` files and go to your app config > deployment and change "captain-definition Relative Path" for each app.

> Would it make sense to deploy all instances of, let's say, a database app onto one server? I would presume not, because of introducing a single point of failure (the server itself).
Imagine that a specific server has lower overall specs (less RAM, less powerful vCore, ...). Would it make sense to use this server solely for the purpose of "manager" node and deploy app instances on other servers?

Overall, things are a lot simpler, you can stick to one heavy duty server. Creating multiple nodes doesn't necessarily make your app automagically more stable. If database is on one node, and the node gets destroyed, your data is lost. Having a true Highly Available system is really complex. CapRover is not the right tool if that's what you're looking for.
