### ISSUE TITLE
Run node app and specify docker network for sending metrics to datadog

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1253]
I'm playing around with [datadog](https://www.datadoghq.com/) for monitoring of metrics within my various node.js apps deployed using CapRover.

So far as I can understand (which isn't very far at present), to set this up in a docker environment I need to start [this agent](https://app.datadoghq.eu/account/settings#agent/docker) on the main server, which is fine.

But for collecting data within a node app specifically, I think I also need to so some further configuration:

https://docs.datadoghq.com/agent/docker/apm/?tab=linux

Further, for metrics collected from within an app deployed by CapRover, I think that it is not ["Tracing from Host"](https://docs.datadoghq.com/agent/docker/apm/?tab=linux#tracing-from-the-host) that I need, but rather ["Tracing from Containers"](https://docs.datadoghq.com/agent/docker/apm/?tab=linux#tracing-from-other-containers).

The latter requires creation of a network, and using that subsequently to set up an agent (another agent??) as follows:

	docker network create <NETWORK_NAME>

	# Datadog Agent
	docker run -d --name datadog-agent \
				  --network <NETWORK_NAME> \
				  -v /var/run/docker.sock:/var/run/docker.sock:ro \
				  -v /proc/:/host/proc/:ro \
				  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
				  -e DD_API_KEY=<DATADOG_API_KEY> \
				  -e DD_APM_ENABLED=true \
				  -e DD_SITE=<DATADOG_SITE> \
				  -e DD_APM_NON_LOCAL_TRAFFIC=true \
				  gcr.io/datadoghq/agent:latest

And finally I need to run the app itself, *while specifying the network name*:

	# Application
	docker run -d --name app \
				  --network <NETWORK_NAME> \
				  -e DD_AGENT_HOST=datadog-agent \
				  company/app:latest

How do I do this last bit, i.e. specifying a network name, when deploying my app?  (Any other insight you can offer into the whole process would be useful too.)

**Comment by githubsaturn** [comment]
CapRover uses its own ingress network `captain-overlay-network`. If you want to add more networks, you can try [Service Override](https://caprover.com/docs/service-update-override.html) hook and add a new network to your service. I haven't tried it, but it may work:

```
TaskTemplate:
  Networks:
    - Target: captain-overlay-network
    - Target: your-other-network

```

**Comment by drmrbrewer** [comment]
Thanks.  For the benefit of anyone else who is trying to do this in future, what I've found is that you don't need to add a new network, you can just use the existing `captain-overlay-network`.  

So, set the agent running on your server (just another docker container) to collect/send metrics from your various node apps/containers that have [tracing set up](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers) with:

    docker run -d --name datadog-agent \
			  --network captain-overlay-network \
			  -v /var/run/docker.sock:/var/run/docker.sock:ro \
			  -v /proc/:/host/proc/:ro \
			  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
			  -e DD_API_KEY=<DATADOG_API_KEY> \
			  -e DD_APM_ENABLED=true \
			  -e DD_SITE=<DATADOG_SITE> \
			  -e DD_APM_NON_LOCAL_TRAFFIC=true \
			  gcr.io/datadoghq/agent:latest

If you're just tracing your node apps, the above is the *only* agent required... no need to install any other docker or Ubuntu agent etc... just the above.  And then, set up tracing within your node app as per [this page](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers), deploy the app with CapRover, and away you go!

However, just spotted the pricing for these node tracing metrics... may not continue with this anyway :-/
