### ISSUE TITLE
Deployment ISSUES

### ISSUE THREAD

**Issue by streamlifetv** [caprover/caprover#1255]
I was able to install wordpress site for the server domain name.

But, I was not able to install these streaming servers.  Not sure if there are webpages for these servers but this is what I get: https://nginxvideoserver.s1.streamcloud.us/, and https://ovenmediaengine.s1.streamcloud.us/, do I need to create captain-definition files?  Any help would be much appreciated.

Thanks!

What is the problem?

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

**Comment by githubsaturn** [comment]
The pages that you have shows the default placeholder. You need to deploy your application.

**Comment by streamlifetv** [comment]
I thought I did deploy the application, every one of my services that I launched have the same message. I used the docker image deployment.  What am I missing?  I love Caprover, but this is very hard to figure out.  I only have the wordpress site working.  Everything else is not loading anything.  I had some port issues, going to look again at each container, but these containers should just load up something once launched should load up a user interface right?

**Comment by streamlifetv** [comment]
Please do not close this until I get this deployment issue figured out!

Here is server info requested above:
root@NY-1281:~# uname -a && lsb_release -a && free -h
Linux NY-1281 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:            15G        1.3G        2.0G         24M         12G         13G
Swap:           88M          0B         88M

**Comment by streamlifetv** [comment]
docker ps:

8e038079da60   caprover/certbot-sleeping:v1.6.0                                        "/bin/sh -c 'sleep 9…"   45 hours ago   Up 45 hours   80/tcp, 443/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                       captain-certbot.1.tm86tlvbmfo8tddu5bbp9eu8p
a83e0c6f795c   registry:2                                                              "/entrypoint.sh /etc…"   45 hours ago   Up 45 hours   5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                              captain-registry.1.6f1v03yby8guv5hm10ro9n644
9eb41e30be97   nginx:1                                                                 "/docker-entrypoint.…"   45 hours ago   Up 45 hours   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                                                                                                                                                                                                                                                                                                                                              captain-nginx.1.tcwifq4hgqf2wgvdtuvwnox68
976f372bd364   nginx                                                                   "/docker-entrypoint.…"   45 hours ago   Up 45 hours   0.0.0.0:81->80/tcp, :::81->80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                     webserver
3fcbf4b3dcc2   caprover/caprover:1.10.1                                                "docker-entrypoint.s…"   45 hours ago   Up 45 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                                                                                                                                                                                                                                                                                                                                             captain-captain.1.r4ri67qndhgbtgxhh4cawvf6f
35b8c566c1d1   mysql:5.7                                                               "docker-entrypoint.s…"   45 hours ago   Up 45 hours   3306/tcp, 33060/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                   srv-captain--streamcloud-db.1.uigmuzhhk2dmbpqmjbtionsvj
8f2a9a117e48   wordpress:4.9                                                           "docker-entrypoint.s…"   45 hours ago   Up 45 hours   80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--streamcloud-wordpress.1.6l2j5gfijdq3svlw1at26omdo

**Comment by githubsaturn** [comment]
I don't understand the issue here. Your `docker ps` only shows that you have two apps `streamcloud-wordpress` and `streamcloud-db`

Are you saying you have an app called `nginxvideoserve` in your caprover instance? 

1- Take a screenshot of your app list on your CapRover instance.
2- Run `docker service ls` and paste the output here.

**Comment by githubsaturn** [comment]
Closing as stale, feel free to provide more info if the issue still persists.
