### ISSUE TITLE
[Question] Is it possible to create backup programmatically?

### ISSUE THREAD

**Issue by melalj** [caprover/caprover#1256]
I'd like to automate the backup process and have a cron script that would generate the `backup.tar` periodically.
Is it something that is possible?

**Comment by maietta** [comment]
Yes.

**Comment by melalj** [comment]
Ok, this is to trigger action periodically.
But my original question is what command should I execute to create a backup programmatically?

**Comment by githubsaturn** [comment]
> Is it possible to create backup programmatically?

Yes, and no. The backup is highly experimental and it's not stable. It currently only stores the config. Hence we don't want to advertise that it's a really full-fetched backup solution. If considering all this, you still want to go ahead and create your own periodic backup solution, yes, you can do so, it's simply a few http calls:
* `/api/v2/login` to fetch the auth token
* `/api/v2/user/system/createbackup` to create the backup and retrieve the download link


Just inspect your network traffic in your browser and you'll be able to exact payload that is being passed to the endpoints. You can also use `caprover api` command which takes care of populating the auth token and namespace header automatically for you.

https://github.com/caprover/caprover-cli#api
