### ISSUE TITLE
Can't create One-click app after adding CI/CD Integration

### ISSUE THREAD

**Issue by ugened47** [caprover/caprover#1258]
I was amazed by Caprover and sucessfully deployed my Next.js app using it without any problem using CI/CD by GitLab configured according to the docs https://caprover.com/docs/ci-cd-integration.html.

However now when trying to quickly any One-click app the error is thrown by the API
```
https://captain.paas.myapp.com/api/v2/user/apps/appDefinitions/register

{
  data: {}
  description: "Push failed: \n{\"message\":\"denied: requested access to the resource is denied\"}denied: requested access 
  to the resource is denied"
  status: 1000
}
```

The error is gone only if I select `disabled push` as the Default Push Registry section at the Cluster tab. I'm having multiple nodes in the cluster and don't want to always have `disabled push` to be my option.

Is this an expected behavior as I don't see it's documented somewhere?

Thank you!

**Comment by githubsaturn** [comment]
Are you saying that the regular apps can be pushed to the default registry, but one click apps fail?

* Create a app `test-app`
* Go to deployment tab and under "Method 4: Deploy plain Dockerfile", deploy this content:
```
FROM nginx:alpine
RUN touch /test-custom-image
```

Does this work? Or you see the same "Push failed" error?

**Comment by ugened47** [comment]
@githubsaturn Thank you. You saved my day. The problem was because `Image Prefix` for GitLab registry was missing the project namespace in addition to a username. Now everything is clear and works fine 🎉
