### ISSUE TITLE
[Question] How to change IP address?

### ISSUE THREAD

**Issue by tim-hub** [caprover/caprover#1261]
Hi Caprover team,

I am reading the set up document, it talks about how to set up a server, but not about how to change it. https://caprover.com/docs/cli-commands.html#server-setup

I am thinking migrating my caprover instance from one server to another, (server linux backup and restore through AWS AMI).

 the server IP will be changed.

How can I do to make the new instance work? Besides changing DNS record. Or is it all I need to do (change dns record)

Thanks

**Comment by githubsaturn** [comment]
IP address is not stored anywhere in CapRover config. But by the virtue of moving your instance to a new server (depending on the snapshot and the hardware) your Docker swarm might stop working. 

To make sure it works, first, copy the server into a new instance, then run `docker service ls` and make sure all services are running (1). Then, change the DNS entry, wait for a few hours, and then kill the old instance.


(1) You `captain-captain` instance will keep getting restarted as it fails the healthcheck, but that's okay. Make sure you other services are running fine.

**Comment by tim-hub** [comment]
> IP address is not stored anywhere in CapRover config. But by the virtue of moving your instance to a new server (depending on the snapshot and the hardware) your Docker swarm might stop working.
> 
> To make sure it works, first, copy the server into a new instance, then run `docker service ls` and make sure all services are running (1). Then, change the DNS entry, wait for a few hours, and then kill the old instance.
> 
> (1) You `captain-captain` instance will keep getting restarted as it fails the healthcheck, but that's okay. Make sure you other services are running fine.

thanks

**Comment by aychernov** [comment]
> IP address is not stored anywhere in CapRover config. But by the virtue of moving your instance to a new server (depending on the snapshot and the hardware) your Docker swarm might stop working.
> 
> To make sure it works, first, copy the server into a new instance, then run `docker service ls` and make sure all services are running (1). Then, change the DNS entry, wait for a few hours, and then kill the old instance.
> 
> (1) Your `captain-captain` instance will keep getting restarted as it fails the healthcheck, but that's okay. Make sure you other services are running fine.

how to kill and restar old instance?

**Comment by tim-hub** [comment]
> > IP address is not stored anywhere in CapRover config. But by the virtue of moving your instance to a new server (depending on the snapshot and the hardware) your Docker swarm might stop working.
> > To make sure it works, first, copy the server into a new instance, then run `docker service ls` and make sure all services are running (1). Then, change the DNS entry, wait for a few hours, and then kill the old instance.
> > (1) Your `captain-captain` instance will keep getting restarted as it fails the healthcheck, but that's okay. Make sure you other services are running fine.
> 
> how to kill and restar old instance?

In my case, it is just simply restart / shutdown EC2 isntance on AWS dashboard. 

It is not a caprove command, it is a OS command

**Comment by jumus-jumbuck** [comment]
I have added a new ip to my server and want to use this as the main ip, do I just need to update the DNS? Do I not need to run caprover serversetup?
