### ISSUE TITLE
real IP address problem

### ISSUE THREAD

**Issue by pupazze** [caprover/caprover#1262]
Hi, I got a problem with getting the real IP address of my visitors in my containers.
I found some cases already in here, but none of them worked for me.

I got a completely fresh Caprover installation up and running on a clean Ubuntu 18.04 with Docker 19.03 as specified in the docs.
In this fresh installation with https activated I created an app using "One-Click App" function.
I selected the Wordpress app - no special settings. Thats it - checking the IP address in the access log just show me the internal 10.x.x.x IP.

I checked the nginx configration part that should be responsible for that and I which I know from my past nginx experience.
To check it I opened the previously created wordpress app, and clicked on Edit Default Nginx Configurations.

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

And there I see it, but it seams not executed in my case. Any idea why?

Thanks
pupazze

**Comment by maietta** [comment]
You can add the following Pre-Deploy script to expose the IP into the container that runs your service. You can then look for the IP from the environment inside your application like normal.

var preDeployFunction = function (captainAppObj, dockerUpdateObject) {
  var ports = dockerUpdateObject.EndpointSpec.Ports || [];
  ports.forEach(function (port) {
    port.PublishMode = 'host';
  });
  return Promise.resolve(dockerUpdateObject);
};

**Comment by githubsaturn** [comment]
@pupazze - access log in wordpress shows the connection IP address. CapRover uses nginx as a proxy server. Hence the IP address that you're seeing is the IP address of the nginx container. Nginx correctly passes the original IP as the `x-forwarded-for` header, but the logs that you're seeing seems to use the connection IP. For WordPress, a quick search seems to suggest that there are some workarounds, like [this](https://webapplicationconsultant.com/docker/passing-real-ip-in-wordpress-behind-proxy-or-in-docker/) solution. Also see this issue: https://github.com/docker-library/wordpress/issues/383
Regardless, this is not a CapRover question, it's mostly a wordpress question, you probably find a better answer in a wordpress specific forum. 


@maietta  - your solution is correct if the user wants to directly map a port from the app container to the outside world:
```
[App/Container]  =====[mapped port]=====> internet
```
If fact this is how nginx container is set up in CapRover to be able to fetch the real IP of the user and pass it to the clients:
https://github.com/caprover/caprover/blob/26c9a8215c801b01a3f56b3f216b50ace8ea1e45/src/user/system/LoadBalancerManager.ts#L564-L577

Having said that, in case, the user wants to have their app sit behind the CapRover managed nginx container. Hence the port mapping solution won't be able to resolve this issue.
