### ISSUE TITLE
Custom vscode deploy

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1266]
The Cloud9 IDE ([deployed via CapRover](https://github.com/caprover/caprover/issues/186)) has served me well, but is starting to show its age (mainly in terms of eslint being out of date and being difficult/impossible to configure/update).

So, I'm looking as vscode, which seems like a good alternative even for javascript/node.js... out of interest, do you use this as your own personal IDE for developing CapRover (I can see lots of `.vscode` folders in the CapRover repo)?

I have tried installing vscode via the [one-click app](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/vscode-coder.yml), and it installs and works fine.

But I note that the internal environment is based on Debian... the following is from a terminal within the IDE:

    # lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 11 (bullseye)
    Release:        11
    Codename:       bullseye

Whilst Debian is of course great, I'm more used to working with Ubuntu, and it's everything else in all my apps starts with Ubuntu.  I also note that CapRover itself [favours Ubuntu](https://caprover.com/docs/get-started.html#b2-server-specs).  And yes, I know that Ubuntu is closely related to (is based on) Debian, so I could probably adapt, but still...

So I've been trying to figure out how to deploy a version of vscode in which the internal environment is Ubuntu.  My usual approach is to base the Dockerfile on an Ubuntu image and install other stuff (e.g. the IDE) after that.

What I have at the moment is:

	FROM ubuntu:18.04
	RUN apt-get update && apt install -y curl systemd
	# -------------------------------------------------------------
	# Install vscode based on:
	#   https://coder.com/docs/code-server/latest/install#installsh
	RUN curl -fsSL https://code-server.dev/install.sh | sh
	# -------------------------------------------------------------
	RUN apt-get clean && rm -rf /var/lib/apt/lists/*
	EXPOSE 80
	ENTRYPOINT ["systemctl", "enable", "--now", "code-server@$USER"]

In the app's config in CapRover I have also set:

![image](https://user-images.githubusercontent.com/9009792/142621895-6d3ecb35-b8d4-4bb0-8aec-ebceeef7ca44.png)

![image](https://user-images.githubusercontent.com/9009792/142621986-ea31b5a8-12f9-43f9-a489-599ffd541ec0.png)

(I will also add custom volumes as per the one-click app in due course.)

But the service fails to start, with the following repeatedly output to the logs:

    Created symlink /etc/systemd/system/default.target.wants/code-server@root.service → /lib/systemd/system/code-server@.service.
    System has not been booted with systemd as init system (PID 1). Can't operate.
    Failed to connect to bus: Host is down

Any idea how to do this properly?  Doesn't seem to make a difference if I use the exec form of `ENTRYPOINT` or not.  I have a feeling that [this issue](https://stackoverflow.com/a/62489079/4070848) might be relevant but I don't know how it can be applied within a CapRover context.

I'm also not entirely sure that this would end up with Ubuntu internally, or whether vscode is fundamentally always going to be Debian inside.

**Comment by githubsaturn** [comment]
> out of interest, do you use this as your own personal IDE for developing CapRover (I can see lots of .vscode folders in the CapRover repo)?

I use local VSCode. Not the cloud version.


Regarding the issue with the custom build, I'm not sure what's happening. `code-server` official image is based on Debian, and that's what we're using for default one-click app. Do they support Ubuntu? If so, probably reach out to their forums to see if you can get some insight as to what's going on. This issue seems to very code-server specific. See this issue: https://github.com/cdr/code-server/issues/2713

**Comment by drmrbrewer** [comment]
I'll see if their forums can help, thanks.  I did have some success with using `FROM linuxserver/code-server:focal`... may just go with that rather than starting with Ubuntu... slight issue is that the image doesn't seem to allow you to log in as `root` (see [here](https://github.com/linuxserver/docker-code-server/issues/79)).  You have to use `sudo`, which I could adapt to, but I'm more used to having `root` permissions without having to bother updating all my scripts etc.

**Comment by githubsaturn** [comment]
If you want to run commands as ROOT simply add this line to your Dockerfile:
```
USER root
```

**Comment by drmrbrewer** [comment]
I did already have that in the Dockerfile (left over from what was in your one click Dockerfile), but you still log in as a non-root user with that docker image.

**Comment by githubsaturn** [comment]
Ah I see. Yes. That's due to the customized ENTRYPOINT or CMD that the image is using.
