### ISSUE TITLE
[Deployment Issue]: Nextjs build fails on caprover but succeeds on others

### ISSUE THREAD

**Issue by s-kris** [caprover/caprover#1267]
What is the problem?
I changed the `strict` value from `false` to `true` in `tsconfig.json`. My nextjs app builds successfully on my local machine, render.com, vercel.com. But it fails with type error on caprover machine (aws). 

If applicable, content of `captain-definition` file:

```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./dockerfile" 
 }
```

```
FROM node:14.14.0 as builder

COPY package.json /tmp/package.json
RUN cd /tmp && yarn install --ignore-engines
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app/

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY . /usr/src/app
RUN yarn build
ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000
CMD ["npm", "start"]
```

Steps to reproduce the problem:
1. Create a typescript nextjs project 
2. Set strict mode set to true
3. Declare a variable with a type in the function
4. Set `implicit-any:off`
5. Deploy to caprover using the above docker file

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
No LSB modules are available.
Distributor ID:Ubuntu
Description:Ubuntu 18.04.1 LTS
Release:18.04
Codename:bionic
              total        used        free      shared  buff/cache   available
Mem:            15G        2.2G        2.2G         12M         11G         14G
Swap:            0B          0B          0B

**Comment by githubsaturn** [comment]
1- Are you sure that you've committed your changes. CapRover only builds what's committed to git.
2- What's the error?
3- Please create a public repository on Github that can show the problem and link it here.

**Comment by s-kris** [comment]
Thank you!

1. Yes! I triple-checked. 
2. `Type error: Parameter 'props' implicitly has an 'any' type.` (this doesn't happen outside of caprover)
3. Okay
