### ISSUE TITLE
[Question] trailing slash

### ISSUE THREAD

**Issue by maietta** [caprover/caprover#1268]
I've done my due diligence to research my problem and have now come to the conclusion my problem is caused by the default configuration within my production environment. I am using Caprover's latest stable version as of this writing, which is version 1.10.1.

Quick explanation of my deployment strategy as I believe it's pertinent:

Every project I work on includes at least one Dockerfile and a Docker Compose stack instruction file. The Dockerfile is used for both local development as well as production. The docker-compose.yml file is used exclusively for local development or in some cases, used to deploy the stack on a standalone server. Nevertheless, the use of a single Dockerfile is important, as it means that my application environment is exactly the same between development and production. What's different is that in development, I run the Traefik reverse proxy to route traffic on port 80 to my local container running my app. I don't have any issues at all with this.

Where my problem seems to lie is in Caprover's Nginx reverse proxy.

The problem:

I am fighting a SEO trailing slash problem where only in production (Caprover's Nginx reverse proxy), the trailing slash is removed before reaching my container's webserver, which is also using Nginx but as my webserver of choice, using a stock config.

For example:

When a request is made to example.com/books/, it seems that the trailing forward slash is stripped before reaching the container so in my application, it appears as example.com/books.

I would like to preserve this foward-slash.

Any insight or solution would be greatly appreciated. Thanks!

**Comment by githubsaturn** [comment]
That's weird. I just tried this and it seems to work fine:
![image](https://user-images.githubusercontent.com/10582082/142774567-5c24d0a7-1ee3-42f5-9439-4962142ab759.png)
![image](https://user-images.githubusercontent.com/10582082/142774582-6323e526-9045-4d0a-8971-bd2de78068f1.png)


You can try it yourself:
- Login to demo instance: `https://captain.server.demo.caprover.com` password: `captain42`
- Go to `test-nginx` app and under the deployment tab, view the logs
- Run `curl -v http://test-nginx.server.demo.caprover.com/test/123/456/` in  your terminal
- You'll be able to see the trailing slash in the logs of the container.

**Comment by maietta** [comment]
Thank you for testing this, @githubsaturn. Now I am really stumped!

**Comment by maietta** [comment]
Finally found the issue. It was the PSR-4 autoloader, not directly related to Caprover. Somehow, despite the containers being identical between development and production, the file system is seen differently inside the containers. In production, I cannot use CamelCase autoloading class names in my PHP project but in development, I can.

I am totally stumped how there can be any difference at all between Ubuntu 18 used with Caprover and my Windows Subsystem for Linux (WSL2) running Ubuntu 18. The file systems are treated the same as far as I can tell. There is no difference. Perhaps NTFS for Windows underneath all of it is somehow more tolerant than the Host filesystem in my production environment. At this point it's "magic".

So, with a small change from CamelCase to lowercase for my class name and filenames, the project is now complete and working.

¯\_(ツ)_/¯

**Comment by githubsaturn** [comment]
Glad you sorted it out. 

WSL has many quirks. Filename sensitivity is one of them: https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity

**Comment by maietta** [comment]
> Glad you sorted it out.
> 
> WSL has many quirks. Filename sensitivity is one of them: https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity

I appreciate you're help and pointing me to this document. This is yet another reason it may be easier for my team to focus on using a Linux machine for development instead of setting up a WSL environment.

Thanks!
