### ISSUE TITLE
[Question] How to specific docker swarm port during installation?

### ISSUE THREAD

**Issue by Raymondo-C** [caprover/caprover#1269]
Hi, 
How to specific docker swarm port during installation?

In some use-case, alibaba cloud classic network for example, the cluster's nodes maybe behind firewall/NAT device, or 4789/udp port be blocked.

Like this issue, https://github.com/moby/moby/issues/33416

I've tried create swarm first, but it will fail during caprover installation.

Also tried install caprover first, then recreate docker swarm, also don't work.

Pls help, Thanks

**Comment by githubsaturn** [comment]
CapRover currently doesn't support passing options to Swarm. But you can specify the advertising IP using this:
```
docker run -e MAIN_NODE_IP_ADDRESS=123.123.123.123 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
