### ISSUE TITLE
Unexpected output when enabling SSL

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1272]
I'm getting the following slightly confusing error when enabling SSL on my new app:

![Screenshot 2021-11-25 180734](https://user-images.githubusercontent.com/9009792/143493725-7ae16dfc-327c-4072-b113-8a3c217a40ba.png)

I suspect that I may have enabled SSL for this domain in the past in CapRover, deleting the app and not re-creating it until now.  Maybe that's it?  The error also refers to "too many requests of a given type"... with a link to something about rate limits... certainly I haven't been enabling SSL on loads of apps... just a couple in the last couple of days, nothing excessive or bot-like.  There is no `/var/log/letsencrypt/` folder per the message.

I did have a dig around in `/captain/data/letencrypt/` and couldn't see any logs... but I did notice that there is a `.conf` file in `/captain/data/letencrypt/etc/renewal/` that matches this domain name, dated 3 Jan 2020 (which seems about right).  Maybe I can delete this `.conf` file and try again?

Also there is a matching folder for this domain in `/captain/data/letencrypt/etc/archive/`... again, maybe delete this folder?

**Comment by githubsaturn** [comment]
There is an active incident with Let's Encrypt. There is nothing that you can do on your side. Just have to wait until they fixed the issue. Millions of websites are being affected by this, so hopefully they'll fix this soon

https://letsencrypt.status.io/

![image](https://user-images.githubusercontent.com/10582082/143499518-7ac5d982-bae9-4f4d-be8c-29722093d1cb.png)

**Comment by githubsaturn** [comment]
Feel free to reopen if you're still having issues after this incident is resolved.

**Comment by drmrbrewer** [comment]
Oh, OK thanks 🙂

**Comment by drmrbrewer** [comment]
I can confirm that this problem has gone away now, so it must have related to the incident.

**Comment by githubsaturn** [comment]
Thanks!
