### ISSUE TITLE
[Deployment Issue] Port 80 being closed in a clean Debian VM

### ISSUE THREAD

**Issue by Midou36O** [caprover/caprover#1273]
What is the problem?

Port 80 seems to be closed even on a fresh debian VM with nothing installed (not even a DE, just the bare minimum).

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1. run the docker command
2. whines about the port 80 being closed

Output of the following command on your server:

```
~# uname -a && lsb_release -a && free -h
Linux CapRover 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
               total       utilisé      libre     partagé tamp/cache   disponible
Mem:           7,8Gi       203Mi       4,4Gi       0,0Ki       3,2Gi       7,3Gi
Partition d'échange:      974Mi          0B       974Mi
```

**Comment by githubsaturn** [comment]
Do you have all the requirements [listed here](https://caprover.com/docs/get-started.html#b1-public-ip)?

Specifically, does your VM have a **public** IP address? And do you have your port 80 open?

**Comment by Midou36O** [comment]
I defenitely meet those requirements.
My VM have a public ip address, but nginx (in another VM is managing all of my services), using the local option mentionned before the error it runs then exit instantly.

**Comment by githubsaturn** [comment]
1- Please copy the entire command and the output you're seeing.
2- Instead of the install command, what happens if your run this command `docker run -p 80:80 nginx:alpine` ? Can you see the default nginx page via `http://IP-ADDRESS:80` ?
3- Are you using a cloud VPS or a self hosted VM behind some sort of NAT?

**Comment by Midou36O** [comment]
1- `docker run -p 80:81 -p 443:444 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover -e MAIN_NODE_IP_ADDRESS=\'127.0.0.1\'` outputs nothing, checking `docker ps -a` shows `Exited (0)`
 without `-e MAIN_NODE_IP_ADDRESS=\'127.0.0.1\'`` it tells ip 80 is closed.
 2- 
![image](https://user-images.githubusercontent.com/45198486/143785137-4b689ab0-17a6-48ef-ae96-b85e1f65c2e3.png)
yes it works.
3- Self hosted VM behind a Server Rack, precisely running Proxmox VE.

**Comment by githubsaturn** [comment]
`docker run -p 80:81` - why 81?

Also, the ip address showing in your browser **is not** a public IP address.

**Comment by Midou36O** [comment]
> why 81?
i just tried troubleshooting myself but 80:80 have the same effect
> the ip address showing in your browser is not a public IP address
i am aware of that, i plan to use nginx to reverse proxy it to my domain/public IP.

**Comment by githubsaturn** [comment]
1- CapRover needs to be installed on machine that has a public IP address. You cannot reverse proxy to CapRover. It won't work.

2- When you see the error about "port 80 being closed" it just means exactly that. CapRover tries to ping itself from `http://IP-ADDRES:80` and if it cannot reach itself it assumes that port 80 is closed. 

To fix, just follow **the exact requirements** and you'll be able to get it up and running.

**Comment by Midou36O** [comment]
What about this?
![image](https://user-images.githubusercontent.com/45198486/143785514-16a66212-8d3f-456b-9c5c-054dc948e936.png)

**Comment by githubsaturn** [comment]
You can, but you won't work out of the box. You have to have port forwarding enabled. From your set up, it appears that you're planning to reverse proxy. Port forwarding is different from reverse proxy. 

Do you have port forwarding enabled? Can you reach your VM via `http://public-ip:80` ?

**Comment by Midou36O** [comment]
Yes i can, all of my vms can be reached via its public ip

**Comment by Midou36O** [comment]
i could temporarily open port 80 for the specific VM for it just to install it
![image](https://user-images.githubusercontent.com/45198486/143785907-4365bb6a-753b-4874-aa2c-34bd03dcb214.png)

**Comment by githubsaturn** [comment]
Alright, this is good progress.

You need to open port 80,443, and 3000 for the installation to complete. [Other ports](https://caprover.com/docs/firewall.html) are needed if you use specific functionalities. But at very least, you need 80, 443, and 3000.

Also:
> i could temporarily open port

You should permanently open the port, if you close it after installation, CapRover healthcheck will fail and CapRover engine will manfunction.

**Comment by Midou36O** [comment]
Ah. I tought i could run CapRover alongside my other services but seems like it's impossible unfortunately. Thanks for the help.

**Comment by githubsaturn** [comment]
Correct. CapRover is an all-in-one solution and it requires a dedicated public IP. If your public IP ports are consumed by other applications, you cannot use CapRover.

**Comment by Claudio9701** [comment]
Hello! 

In my case I can run `docker run -p 80:80 nginx:alpine` and access `http://IP-ADDRESS` without problem. But Caprover still says that port 80 is closed. 

I think my problem could be I'm running this on Ubuntu 16.04 LTS, but I'm not sure. 

I enabled the firewall with the commands given but still doesn't work. When I use BY_PASS_PROXY_CHECK it loads but I can access `http://IP-ADDRESS:3000` it keeps loading and raise an error. but  and `http://IP-ADDRESS` loads to the CapRover "parking" html. 

When I run the commands from troubleshooting. It gives me this:

![image](https://user-images.githubusercontent.com/24416566/215799165-9ab1cfd6-f922-41d9-ac29-bb9350ea5770.png)


![image](https://user-images.githubusercontent.com/24416566/215799806-4eabcca7-d8e3-436d-926e-427f47cb321e.png)
With the following error at the last line: 
`error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: task uez1u43ybo7l6931tgry86n2a has not been scheduled`

**Comment by Claudio9701** [comment]
Thanks for your answer! 

The server is managed under a VPN so the solution was to ask the system management team to open port 3000 😅. Everything it's working fine now, even https enabling. 

Nevertheless, it is weird that the port 80 error raises when I don't use the BY_PASS_PROXY_CHECK.
