### ISSUE TITLE
Limiting app resources

### ISSUE THREAD

**Issue by Divkix** [caprover/caprover#1275]
First of all thanks a lot for this project, it really helped me as earlier I got no place to host my apps but CapRover does a great job 🚀

I have a suggestion, I don't know if it can be added, but it's just a thought which came to my mind.

**Is your feature request related to a problem? Please describe.**
It sometimes happen when I'd like to limit resource such as CPU or RAM for an app, because I don't want the ap to overuse resources and make other apps crash.

**Describe the solution you'd like**
Can a UI function like managing CPU limit can be implemented? I've seen this is on Portainer so maybe the docker api supports this.
This would be really great because on heroku we are limited to resources and the app gets killed if the resources are exceeded, the free plan takes time to restart the app if it crashes occassionally, like first app is restarted immediately first time, then after 10 mins, then after 60 mins. However, docker can the restart the app instantly.

**Describe alternatives you've considered**
I've tried Portainer to limit the specific service for app and it works pretty well, but would be great if the Caprover interface shows that itself.

**Comment by githubsaturn** [comment]
You can do that simply via the [override config](https://caprover.com/docs/service-update-override.html#sample-use-case)

This is why it's not added to the GUI: https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
