### ISSUE TITLE
[Deployment Issue] Problem instaling Nextcloud

### ISSUE THREAD

**Issue by aaxyat** [caprover/caprover#1283]
What is the problem?
When I try to setup nextcloud after deployment, The setup process fails with error "Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE."

```
Linux caprover 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
               total        used        free      shared  buff/cache   available
Mem:           971Mi       358Mi       169Mi        13Mi       443Mi       445Mi
Swap:          7.9Gi       112Mi       7.8Gi

```

**Comment by githubsaturn** [comment]
This is an application error specific to NextCloud and it's not specific to CapRover. You'd have to reach out to their team for the resolution. Example case:
https://help.nextcloud.com/t/update-to-next-cloud-21-0-2-has-get-an-error/117028
