### ISSUE TITLE
[Question] Can I expose service directly using ip

### ISSUE THREAD

**Issue by radud** [caprover/caprover#1284]
Hi there, 

We have a setup where we have a load balancer/reverse proxy in front of multiple caprover installations. 
Is it possible to expose services by their IP&Port to the internet? We would like to skip the embedded Nginx proxy since we already have our own reverse proxy installation. 

Many thanks, 
Radu

**Comment by githubsaturn** [comment]
You can expose the port and use the mapped port. For example you can have port 80 to be mapped to port 3232 and use `http://your-server-ip:3232` to access your app

![image](https://user-images.githubusercontent.com/10582082/146105372-fa4eb6a4-eb17-439c-9158-b49768300698.png)

**Comment by radud** [comment]
Thank you @githubsaturn for the quick reply. This is exactly what we need.

Thank you for this great tool!!!
