### ISSUE TITLE
[Question] use nginx http/3 in caprover

### ISSUE THREAD

**Issue by ariaieboy** [caprover/caprover#1286]
hello everyone 
I want add http/3 support for one of my projects. 
for having this we need to build and use a custom nginx docker image according to this page : https://quic.nginx.org/readme.html
I've find a good docker image "ranadeeppolavarapu/nginx-http3" and i managed to change caprover base nginx image by changing the "/captain/data/config-override.json" and updating the captain container 
but caprover running the nginx container on ports 80 and 443 over tcp and since http/3 uses 443/udp we need to open that port on nginx container.

now i want know that can we open 443/udp port on nginx container using sth like this "config-override.json" file or not ?

**Comment by githubsaturn** [comment]
Post installation you can manually use `docker service update` to update your nginx service to add UDP.

CapRover only sets the ports during the [initial creation of nginx](https://github.com/caprover/caprover/blob/6fdcb8b1e4aa4e2acafb02ec5914b3e9bfba4c4e/src/user/system/LoadBalancerManager.ts#L560-L576) service and does not modify it later.
