### ISSUE TITLE
docker system prune deletes running git-built containers and they wont restart

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1290]
What is the problem?
I am running containers based on files i have in my git repo. (Deployment Method 3)
I run "docker system prune" to clean up the server the container. It should not break things.
The Container is not running anymore and i now have to run a force build to get the container running again.

Steps to reproduce the problem:
- Deploy a Container using Method 3.
- ``docker system prune`` on Server
- ``docker ps -a``

```
Linux HADES 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        unstable
Codename:       sid
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:      141Gi       5,3Gi       1,2Gi        12Mi       135Gi       135Gi
Swap:          974Mi       367Mi       607Mi
```

**Comment by githubsaturn** [comment]
This is a Docker bug: https://caprover.com/docs/disk-cleanup.html#docker-images
