### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1292]
**Is your feature request related to a problem? Please describe.**
I would like to setup a cronjob to backup the caprover configs to a specific location, is there any way to achieve this?

**Describe the solution you'd like**
Caprover cli could have a backup command with desired location as a parameter

**Describe alternatives you've considered**
Configuring Backup Location & Frequency in config-captain.json

**Comment by githubsaturn** [comment]
See https://github.com/caprover/caprover/issues/1256#issuecomment-963693626
