### ISSUE TITLE
Letsencrypt SSL does not auto-refresh

### ISSUE THREAD

**Issue by colinrim** [caprover/caprover#1293]
Certificate expired August 14, 2021 and app did redeploy plenty of times since. 
Caprover v.1.10.1 hosted on VultrVM.
 docker service ls
```
14ga7vczye15   captain-captain            replicated   1/1        caprover/caprover:1.10.1           *:3000->3000/tcp
ordau22pkbzw   captain-certbot           replicated   1/1        caprover/certbot-sleeping:v1.6.0
ha1vijmy8jg8   captain-nginx                 replicated   1/1        nginx:1

```
Could try to delete/re-create app, but was hoping for a more pretty fix/workaround.
Thanks plenty for any hints.

**Comment by githubsaturn** [comment]
CapRover [automatically renews](https://github.com/caprover/caprover/blob/6fdcb8b1e4aa4e2acafb02ec5914b3e9bfba4c4e/src/user/system/LoadBalancerManager.ts#L802-L811) your close-to-be-expired certificates. If you're seeing an expired certbot certificate, it means that Certbot wasn't able to renew your certificate.


To see what's happening, shell into your certbot container and try to manually renew certificate of your domain.

```
docker exec -it $(docker ps --filter name=captain-certbot -q) certbot renew
```

**NOTE:** You may see some errors for some domains/app that you **previously removed**. You can ignore those as they won't cause any harms. Just look for the domain that is still supposed to work, but it doesn't.

**Comment by colinrim** [comment]
```
Domain: app.sandbox.example.com
   Type:   unauthorized
   Detail: Invalid response from
   http://app.sandbox.example.com/.well-known/acme-challenge/8fsPfADqhFOE_gywR61x3nWobVc_ejt9go6SAtE-o8Q
   [45.32.123.8]: "<!doctype html>\n<html>\n\n<head>\n    <meta
   charset=utf-8>\n    <meta
   content=\"width=device-width,initial-scale=1.0,minimum-scale=1."

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```
I'm assuming the DNS move to Netlify did not work correctly for the wildcard/subdomain entries.
Adjusting/verifying this now...

**Comment by colinrim** [comment]
I'll go ahead and close this issue as the problem was related to not supported wildcard DNS entries. After fully specifying the full subdomain the certificates are refreshed properly.

This helped to gain insights of the underlying problem:
`docker exec -it $(docker ps --filter name=captain-certbot -q) certbot renew`
