### ISSUE TITLE
[Question] Connect to host network

### ISSUE THREAD

**Issue by krypticallusion** [caprover/caprover#1295]
Hi, I want to connect my containers created by caprover to the host network so I can access services than run on the host network.

Is there any way to do a --network="host" or any of it's equivalents within caprover?

Thanks!

**Comment by githubsaturn** [comment]
Sort of. Overall, all commands that can be done via `docker service update` are also doable with CapRover.

But CapRover doesn't use Docker CLI. Instead, it uses [Docker's HTTP API](https://docs.docker.com/engine/api/v1.40/#operation/ServiceUpdate).

See here for the details on how to override the default options: https://caprover.com/docs/service-update-override.html

Note that the YAML example in the link above is just an example and it doesn't include all available options. See Docker's API doc for the full list of all available flags.
