### ISSUE TITLE
my servers are all crashed a

### ISSUE THREAD

**Issue by polatonur** [caprover/caprover#1296]
i 'm unable to use my servers and can not  connect to my gui dashboard.  I keep receiving This site can’t be reached. I tried with cli but some problem."Error: connect ECONNREFUSED 159.65.119.7:443" 
I don't know what to do.

my domain = https://captain.api.dotonur.dev/

**Comment by githubsaturn** [comment]
Lots of different factors can contribute to system failure. It can be a hardware problem or it could be a disk overload problem. 

Run `docker service ls` on your server to see the status of your docker services.

**Comment by polatonur** [comment]
after restarting my droplet on DigitalOcean, everything works fine now.
