### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by User9684** [caprover/caprover#1298]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: Is there any sort of way to detect when an app crashes? I am trying to make caprover post a message to a Discord Webhook upon app crashing, but it seems like there is no real way to do this without directly adding it to the docker.

**Comment by githubsaturn** [comment]
Short answer: no.

More details:
CapRover is completely out of the loop after you deploy your application. The deployment and orchestration is managed by Docker. When you app crashes, Docker swarm restarts a new instance of your container. CapRover doesn't get notified when this happens.

Generally, for monitoring, you should use other services such as Sentry, Raygun, etc...

**Comment by FxllenCode** [comment]
@githubsaturn thanks for the clarification! 

How's the best way to install Sentry for CapRover? I see there is a one-click app, but I'm not sure how that works. Thanks!
