### ISSUE TITLE
[Question] HTTP Status for Nothing here yet :/

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1299]
I would like to monitor the uptime of my services via Uptime-Kuma and set up a bunch of HTTP Requests to my Caprover-Containers.

Unfortunately my Uptime Monitor is only looking for HTTP-Return-Statuscode "200 OK" and the "Nothing here yet :/" Page, which basically means my app is currently down/restarting, returns status 200 instead of something like 404 or 503.

Is there a way to configure the HTTP-Status for the Nothing here yet page?

![image](https://user-images.githubusercontent.com/22225051/148302375-f26f18b1-950f-46f6-8e12-e7ac92a45698.png)

**Comment by githubsaturn** [comment]
Navigate to settings > Edit nginx config, find this section:
https://github.com/caprover/caprover/blob/6fdcb8b1e4aa4e2acafb02ec5914b3e9bfba4c4e/template/root-nginx-conf.ejs#L29-L35

change it to
```diff

        location / {
            root   <%-captain.defaultHtmlDir%>;
-           index  index.html index.htm; 
+           index  somethingelse.html;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /error_generic_catch_all.html;

```

**Comment by githubsaturn** [comment]
Also, most uptime monitors support using the keyword or lack of keyword, if your monitor supports such a scenario, you can simply use existence of `powered by CapRover` as a sign that this page is an error page.
