### ISSUE TITLE
[Question] how to deploy local image

### ISSUE THREAD

**Issue by khoshbin** [caprover/caprover#1302]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Hi there , I've a docker image 'sampleapp' in my system , but when I provide its name, It is looking in hub registry. How is it possible to deploy an already built and ready docker image?

Thanks

**Comment by githubsaturn** [comment]
You can deploy a singleline Dockerfile `FROM sampleapp`  and it'll work fine. More details here:

Related https://github.com/caprover/caprover/issues/611#issuecomment-595481112
