### ISSUE TITLE
Axios GET response delayed

### ISSUE THREAD

**Issue by 7aklhz** [caprover/caprover#1305]
Hi, 

I'm running a javascript function in a loop. In that loop, I'm calling an API using Axios GET. When I run the function (all day) on my local computer, it works fine. However, when I push my code to Caprover, my Axios call randomly freezes for up to couple of minutes before returning the response. I'm trying to find the cause if this behavior (docker setting or my cloud provider) (I contacted the API provider so I know it's not an API limitation). 

So my question is : does Caprover apply a limitation or simply does docker have some kind of limitation that can cause the api response to be delayed (network limitation, CPU, etc.) ?  

For information, the expected response size is 5497380b and the API gets called more or less every 20 seconds. 

Thanks

**Comment by githubsaturn** [comment]
Short answer: No, CapRover doesn't impose anything.

Longer answer:
All CapRover does is to build your Docker image and deploy it as a docker container. Once your application is running, you can even completely remove CapRover from your system `docker service scale captain-captain=0` and your app will run just fine. 

So what's happening in your case is probably specific to your use case. Does the API call just hang or does it cause the container to restart? You can run `docker ps` to check the uptime to see if the container restarted or just the API call hangs. 

Another possibility is the network connection of your VPS. Maybe change the API call to something else like `GET https://caprover.com` to see if it solves the issue or not.

But regardless, CapRover doesn't impose any limitations on network, CPU or RAM by default.
