### ISSUE TITLE
successfully push to git branch but on Caprover it doesn't automatically deploy that branch

### ISSUE THREAD

**Issue by Trung229** [caprover/caprover#1307]
Hi everyone,

I'm trying to sync deploy on git with Caprover, which means whenever I merge another branch into master branch,

Caprover will automatically deploy that branch to server, but I'm getting that error is that when I merge the pushed branch 
(eg: feature/something) into master, 

The github's webhooks says it was successful ( status code: 200), but the Caprover doesn't update, even though I followed the Caprover's [instructions](https://caprover.com/docs/deployment-methods.html).

here is the log of github webhooks:

##  Request

![image](https://user-images.githubusercontent.com/52306399/149119345-1d13fddf-0eb7-4c7f-9a05-7b944867924b.png)

##  Response

![image](https://user-images.githubusercontent.com/52306399/149119453-7d321f79-6a7b-45c5-b57f-f25b669db1dc.png)

The pictures above return the event that was fired, but my Caprover didn't change

This is log of Caprover's deployment:

![image](https://user-images.githubusercontent.com/52306399/149118912-f95901b5-6c61-4c2f-8665-2e17f5a9b182.png)

I hope everyone can help me, thank you.

**Comment by githubsaturn** [comment]
@Trung229 - do you have the correct branch in your git configuration on CapRover deployment tab?
