### ISSUE TITLE
[Question] How to get instance number?

### ISSUE THREAD

**Issue by itxtoledo** [caprover/caprover#1311]
I need certain code in my application to run only in one instance, for that I thought of getting the instance number, example: only running the code in instance 0.

How can I get this instance number?

**Comment by githubsaturn** [comment]
This goes against the philosophy behind Docker swarm service design. See [here](https://forums.docker.com/t/unique-env-var-value-per-swarm-replica-instance/29625).


There are some hacky ways that are mentioned in the link above that you can use. But you need to install Docker inside the container and bind the docker socket... It's not a straightforward task.

A good practice is to move the code out to a separate app.

**Comment by itxtoledo** [comment]
Thanks for the quick response, I love Caprover. I thought of solving it in two different ways that are a tip for those who research about it:

Create a separate app inside Caprover that is the same as the original app but here we are going to pass an environment variable telling our app that it should run only the services that should run in a single instance, something like JOBS=true.

Another way to solve it is using Bull ( nodejs library ) and using "Repeatable"

**Comment by githubsaturn** [comment]
Yup. First one is probably way simpler. If you really have to make sure that there is only 1 instance of that app running, create that app as a persistent app. By default, non-persistent apps use `start-first` and persistent apps use `stop-first` update strategy.

`start-first` means that, when you deploy new code, Docker first starts a new container with the new code, then after it starts up, it kills the old container. For a few seconds, both containers are alive.
