### ISSUE TITLE
Using custom config templates at deployment time (ejs)

### ISSUE THREAD

**Issue by k3tju** [caprover/caprover#1313]
Hello! 

First of all, thank you very much for creating maintaining this project! 

I am attempting to get a custom configuration passed through `nginxBaseConfig` and `nginxCaptainConfig` in:
https://github.com/caprover/caprover/blob/0e8656213da1bbba1b8cc5ecdde93416924790ec/src/datastore/DataStore.ts

There is no existing documentation for that but I could find in some tickets that you were talking about providing these in `captain-config.json`. Currently mine looks like this:

```
{
        "namespace": "captain",
        "customDomain": "something.com",
        "emailAddress": "something@example.com",
        "nginxBaseConfig":"/captain/data/base-nginx-conf-override.ejs",
        "nginxCaptainConfig":"/captain/data/root-nginx-conf-override.ejs"
}
```

I am clearly doing something wrong because the nginx contain keeps crashing with this error:
```
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/01/20 06:44:53 [emerg] 1#1: unexpected end of file, expecting ";" or "}" in /etc/nginx/nginx.conf:1
nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/nginx.conf:1
```

No wonder since the templates checked inside the GUI look like these:
```
/captain/data/base-nginx-conf-override.ejs
```
and
```
/captain/data/root-nginx-conf-override.ejs
```

I am perhaps attempting something not intended but is there a way for me to put a custom template via a file? Putting it straight into the JSON seems complicated with the escaping.

**Comment by githubsaturn** [comment]
> I am attempting to get a custom configuration passed through nginxBaseConfig and nginxCaptainConfig in:
https://github.com/caprover/caprover/blob/0e8656213da1bbba1b8cc5ecdde93416924790ec/src/datastore/DataStore.ts


You should be using the GUI for this. Just log in to the web GUI, navigate to SETTINGS and change these configurations.

**Comment by githubsaturn** [comment]
If you're trying to link to a file instead of a GUI, no, it's not possible.
