### ISSUE TITLE
[Question] Sentry deployment failed (0.0.0.0 connection refused, possibly related to CapRover's Docker implementation?)

### ISSUE THREAD

**Issue by FxllenCode** [caprover/caprover#1317]
Hey there!

I've been debugging an issue with Sentry for multiple days now and I am at a loss for what is happening. I know that the issue has to do with the Dockerization of this project as it works fine hosted locally. However, I cannot figure out any setting in Docker that is causing this, so I believe the issue might have to do with CapRover's implementation of Docker. 

![image](https://user-images.githubusercontent.com/40151425/151089304-00a873bb-752e-4fb9-a943-248820ee8635.png)

This is the error I am getting in my CapRover logs on initiation of my project. Everything else works fine, no issues, except for this. 

As I have said, everything works fine code wise when I local-host it, but here it is just in case:

**(logging/sentry.js)**

```js
const Sentry = require("@sentry/node");
const Tracing = require("@sentry/tracing");

Sentry.init({
  dsn: [REDACTED],
  tracesSampleRate: 1.0,
  attachStacktrace: true,
  debug: true,
  environment: process.env.VERSION
});

module.exports = Sentry
```

**(index.js)**

```js
const Sentry = require('./logging/sentry.js')


try {
    doSomeFunction();
} catch(error) {
    Sentry.captureException(error);
}
```

It is not a Web App, so I am not exposing it as one:

![image](https://user-images.githubusercontent.com/40151425/151089562-f4d1a4ae-efc9-4474-b33d-6802fc9a7eaf.png)

This is the captain-definition file:

```json
{
    "schemaVersion" :2 ,
    "dockerfileLines": [
        "FROM node:16",
        "WORKDIR /usr/app",
        "COPY ./package.json ./",
        "RUN npm cache clean --force",
        "RUN npm install",
        "COPY ./ ./",
        "RUN git init",
        "RUN git clone https://github.com/Status-Plus/Status-Plus-Translation.git --recursive",
        "RUN git submodule update --recursive --remote --init",
        "ENV NODE_ENV production",
        "CMD [ \"npm\", \"start\" ]"
    ]
}
```

I really believe this is related to CapRover, hopefully someone can help me out! Thanks!

[Here's the StackOverflow post if you want the bounty,](https://stackoverflow.com/questions/70807401/sentry-logging-error-whats-wrong-with-my-config-and-how-can-i-get-more-detaile/70850286#70850286)

**Comment by githubsaturn** [comment]
> CapRover's implementation of Docker

There is no "CapRover's implementation of Docker". This appears to be a Sentry bug. I think what happens is that Sentry somehow wants to connect to 0.0.0.0:443. 

It is possible that the DNS is blocking this request. 

- Are you running a cloud VPS or a self-hosted machine?
- Have you tried manually running the docker image without CapRover?

**Comment by FxllenCode** [comment]
We are running a self hosted machine, and I have not tried running the image without CapRover, I will try that now however.

**Comment by FxllenCode** [comment]
It works fine on my own machine. How can we change the DNS? I know you can change the DNS using `docker run --dns` but can this be applied for CapRover? iirc it's not possible to change the run command.

**Comment by githubsaturn** [comment]
You don't need to run specific DNS command unless you manually changed the config on your host machine. 

Did you try running the image on your server or your own machine? You should try running it on the server. My guess is that the DNS is being intercepted by a DNS blocker and that's why you're getting 0.0.0.0

**Comment by FxllenCode** [comment]
I had run the image on my own machine, which worked fine. 

I will try changing the DNS on the server, hopefully that does it!

**Comment by githubsaturn** [comment]
> I will try changing the DNS on the server, hopefully that does it!

I don't fully understand what you're trying to achieve. You should run the image directly on the server. So something like this:
```
docker run --name my-test-container img-captain-myapp:3
```

**Comment by FxllenCode** [comment]
It looks like that might have worked! However, we much before running it through the panel, since we cannot access other information that we usually can see through CapRover, but it does seem like adding a `--dns` flag at the end of our docker run command has gotten it to work. I'll have to confirm this, though, as it does require using env variables to work, and in this case there were not env variables.

**Comment by FxllenCode** [comment]
Yep, running it with that flag did get it working:

![image](https://user-images.githubusercontent.com/40151425/151106659-99f8233d-413b-4791-b163-0153d958d0fb.png)

**Comment by githubsaturn** [comment]
Why would you need to add `--dns`? is your server using a bad DNS server by default. `--dns` overrides the server's default DNS server. 

The only reason you would need `--dns` is that your server's DNS server is bad. I suggest you fix the root cause.
![image](https://user-images.githubusercontent.com/10582082/151106815-1615cbe5-05ee-4ecc-b7ad-1e194fda264b.png)

**Comment by githubsaturn** [comment]
Do you happen to have anything like PiHole server running? That might be blocking the DNS.

**Comment by FxllenCode** [comment]
How can we fix the default DNS server in that case? 

We do not have anything like PiHole running on the server.

**Comment by githubsaturn** [comment]
It really depends on what your server is doing. You can try using `dig` command to see what's going on.

Regardless, this is definitely an issue with your server set up and not Docker / CapRover.

**Comment by githubsaturn** [comment]
I suggest you run a plain Ubuntu image, and then try `dig your-sentry-url` and see if it works. Then take it from there.

**Comment by FxllenCode** [comment]
I still believe this issue is with CapRover (possibly the way the web panel is deploying it?) As I just tried again without the DNS flag and it is working as intended. I'm not sure why it works fine when I run it with the Docker command, but when I deploy the image via CapRover, it does not work.

**Comment by githubsaturn** [comment]
> I still believe this issue is with CapRover (possibly the way the web panel is deploying it?) 

Web panel just uses pure docker behind the scene. There is not customization. 


> As I just tried again without the DNS flag and it is working as intended

Okay, so even without the DNS flag it works fine? In that case, run this command:
```
docker exec -it $(docker ps --filter name=srv-captain--status-plus-canary -q) curl -v YOUR_SENTRY_URL
```

**Comment by FxllenCode** [comment]
Hm, it didn't like that:

```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22id%22%3A%7B%220bf659881451%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
Error: No such container: curl```

(with sudo permissions) 

I am going to look into changing the DNS of the server still as I do believe that is probably the root cause (even though it presumably worked fine without the `--dns` flag, and dig command didn't show any errors after digging the sentry DSN from the server)

**Comment by githubsaturn** [comment]
That's essentially what you have to do. Shell into your container and manually run `curl` or `dig` command... 

https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container

**Comment by FxllenCode** [comment]
Looks like you have gotten it down to that issue! I was able to curl successfully to google.com within the container, but the connection was refused when I did the sentry DSN.

**Comment by githubsaturn** [comment]
There you go. You have something on your network that blocks that request. Now you just have to find out what that is.

**Comment by FxllenCode** [comment]
Yep, you were right, after some playing around with DNS servers I was able to get it to work, thank you so much! Great project by the way, I very much appreciate your patience with me 🙂
