### ISSUE TITLE
Cannot login to Caprover BLUE DOC link screen

### ISSUE THREAD

**Issue by streamlifetv** [caprover/caprover#1320]
I had Caprover running smoothly on one main and one worker server.  We had just changed the password and now the entire front end of CAPROVER  does not load up we only get a blue DOCS link screen.  How do we fix this?  We had a working containers and we wanted add a back up server and another main server for development.  Please advise.

John

**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

**Comment by githubsaturn** [comment]
Most likely your service has stopped working. Run these commands and copy the output here.
```
docker service update captain-captain --force
docker service ls
docker ps
docker service logs captain-captain --tail 100
```

**Comment by streamlifetv** [comment]
root@NY-1281:~# docker service logs captain-captain --tail 100
captain-captain.1.konzn341il2q@NY-1281    | Captain Starting ...
captain-captain.1.konzn341il2q@NY-1281    | Overriding skipVerifyingDomains from /captain/data/config-override.json
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.036 pm    Emptying generated and temp folders.
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.046 pm    Ensuring directories are available on host. Started.
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.051 pm    Ensuring directories are available on host. Finished.
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.055 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.060 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.061 pm    Migration not needed, skipping.
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.065 pm    Copying fake certificates...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.068 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.069 pm    Locking NGINX configuration reloading...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.084 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.086 pm    Captain Nginx is already running.. 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.088 pm    Updating NGINX service...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:56:56.170 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:01.175 pm    Pruning containers...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:01.178 pm    NGINX is fully set up and working...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:01.185 pm    Captain Certbot is already running.. 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:01.192 pm    Updating Certbot service...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:01.304 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:04.792 pm    Ensuring Docker Registry is running...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:04.895 pm    Captain Registry is already running.. 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:04.897 pm    Updating Certbot service...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:04.982 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:06.298 pm    Pruning containers...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:09.980 pm    Pruning containers...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:17.800 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:20.807 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:23.816 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:23.822 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:28.479 pm    executeCommand Container: captain-certbot certbot renew --non-interactive 
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:42.842 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:42.842 pm    Locking NGINX configuration reloading...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:42.859 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:42.859 pm    sendReloadSignal...
captain-captain.1.konzn341il2q@NY-1281    | February 2nd 2022, 9:57:42.861 pm    Kill HUP Container: 45564af3e09685699b24eb0e9eb1bfdfe994d487ea01d0967682f1976d8e3e8c
root@NY-1281:~#

**Comment by streamlifetv** [comment]
root@NY-1281:~# docker service update captain-captain --force
captain-captain
overall progress: 1 out of 1 tasks 
1/1: running   
verify: Service converged

**Comment by streamlifetv** [comment]
https://streamlcloud.us/   was coming up now just dead.  captain: Nothing here yet :/ not sure why caprover appears to be not functioning.  Will post the results again.

root@NY-1281:~# docker service ls
ID             NAME                                         MODE         REPLICAS   IMAGE                                                                    PORTS
tnc41i9jx3ck   captain-captain                              replicated   1/1        caprover/caprover:1.10.1                                                 
w7oqlksvb76z   captain-certbot                              replicated   1/1        caprover/certbot-sleeping:v1.6.0                                         
e3x9q4ugl6vr   captain-nginx                                replicated   1/1        nginx:1                                                                  
3d6cits4pcvd   captain-registry                             replicated   1/1        registry:2                                                               *:996->5000/tcp
vq5f80iap1s1   srv-captain--adminer                         replicated   1/1        adminer:4                                                                
3xspney2qsdr   srv-captain--docker-nginx-live               replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-docker-nginx-live:0   
mgnf91oi9xjr   srv-captain--mynet                           replicated   1/1        nextcloud:21.0.1                                                         
3xu99gjk61ak   srv-captain--mynet-cron                      replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-mynet-cron:1          
ftydthgnwyub   srv-captain--mynet-db                        replicated   1/1        mariadb:10.5.9                                                           
vi48by7spr44   srv-captain--mynet-redis                     replicated   1/1        redis:6.2.2                                                              
t76stonn9ppd   srv-captain--nginx-rtmp-live                 replicated   1/1        caprover/nginx-reverse-proxy:1-ef5ffcb                                   
c6klc7i10z5g   srv-captain--nginxvideoserver                replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-nginxvideoserver:4    
46wpq140rsa3   srv-captain--ovenmediaengine                 replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-ovenmediaengine:2     
p2pb07j1qq23   srv-captain--portainer                       replicated   1/1        portainer/portainer-ce:2.0.0                                             
ioj1xqzzqh6i   srv-captain--spreedwebrtc                    replicated   1/1        spreed/webrtc                                                            
pti2d1f2payv   srv-captain--streamcloud-db                  replicated   1/1        mysql:5.7                                                                
pichdrsdlgm3   srv-captain--streamcloud-wordpress           replicated   1/1        wordpress:4.9                                                            
c2wfl1v2jmjg   srv-captain--streamlife-deleteme-db          replicated   1/1        mysql:5.7                                                                
4243igl3gwdn   srv-captain--streamlife-deleteme-wordpress   replicated   1/1        wordpress:4.9                                                            
jbkwlxmpkk0z   srv-captain--streamlifetube-db               replicated   1/1        mysql:5.7                                                                
aw0qcx0xs78s   srv-captain--streamlifetube-wordpress        replicated   1/1        wordpress:4.9                                                            
g1oz8nphc974   srv-captain--stube-db                        replicated   1/1        mysql:5.7                                                                
hhs063oifwoe   srv-captain--stube-wordpress                 replicated   1/1        wordpress:4.9                                                            
7uxk97vkpbee   srv-captain--videototelegram                 replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-videototelegram:4     
i9s96nns51bx   srv-captain--videotube                       replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-videotube:2           
v21tiw974ejx   workerservers_agent                          global       2/2        portainer/agent:latest                                                   
root@NY-1281:~# 
root@NY-1281:~# docker service ls
ID             NAME                                         MODE         REPLICAS   IMAGE                                                                    PORTS
tnc41i9jx3ck   captain-captain                              replicated   1/1        caprover/caprover:1.10.1                                                 
w7oqlksvb76z   captain-certbot                              replicated   1/1        caprover/certbot-sleeping:v1.6.0                                         
e3x9q4ugl6vr   captain-nginx                                replicated   1/1        nginx:1                                                                  
3d6cits4pcvd   captain-registry                             replicated   1/1        registry:2                                                               *:996->5000/tcp
vq5f80iap1s1   srv-captain--adminer                         replicated   1/1        adminer:4                                                                
3xspney2qsdr   srv-captain--docker-nginx-live               replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-docker-nginx-live:0   
mgnf91oi9xjr   srv-captain--mynet                           replicated   1/1        nextcloud:21.0.1                                                         
3xu99gjk61ak   srv-captain--mynet-cron                      replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-mynet-cron:1          
ftydthgnwyub   srv-captain--mynet-db                        replicated   1/1        mariadb:10.5.9                                                           
vi48by7spr44   srv-captain--mynet-redis                     replicated   1/1        redis:6.2.2                                                              
t76stonn9ppd   srv-captain--nginx-rtmp-live                 replicated   1/1        caprover/nginx-reverse-proxy:1-ef5ffcb                                   
c6klc7i10z5g   srv-captain--nginxvideoserver                replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-nginxvideoserver:4    
46wpq140rsa3   srv-captain--ovenmediaengine                 replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-ovenmediaengine:2     
p2pb07j1qq23   srv-captain--portainer                       replicated   1/1        portainer/portainer-ce:2.0.0                                             
ioj1xqzzqh6i   srv-captain--spreedwebrtc                    replicated   1/1        spreed/webrtc                                                            
pti2d1f2payv   srv-captain--streamcloud-db                  replicated   1/1        mysql:5.7                                                                
pichdrsdlgm3   srv-captain--streamcloud-wordpress           replicated   1/1        wordpress:4.9                                                            
c2wfl1v2jmjg   srv-captain--streamlife-deleteme-db          replicated   1/1        mysql:5.7                                                                
4243igl3gwdn   srv-captain--streamlife-deleteme-wordpress   replicated   1/1        wordpress:4.9                                                            
jbkwlxmpkk0z   srv-captain--streamlifetube-db               replicated   1/1        mysql:5.7                                                                
aw0qcx0xs78s   srv-captain--streamlifetube-wordpress        replicated   1/1        wordpress:4.9                                                            
g1oz8nphc974   srv-captain--stube-db                        replicated   1/1        mysql:5.7                                                                
hhs063oifwoe   srv-captain--stube-wordpress                 replicated   1/1        wordpress:4.9                                                            
7uxk97vkpbee   srv-captain--videototelegram                 replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-videototelegram:4     
i9s96nns51bx   srv-captain--videotube                       replicated   1/1        registry.s1.streamcloud.us:996/captain/img-captain-videotube:2           
v21tiw974ejx   workerservers_agent                          global       2/2        portainer/agent:latest                                                   
root@NY-1281:~# docker ps
CONTAINER ID   IMAGE                                                                   COMMAND                  CREATED         STATUS         PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                 NAMES
6ee97a60a796   caprover/certbot-sleeping:v1.6.0                                        "/bin/sh -c 'sleep 9…"   4 minutes ago   Up 4 minutes   80/tcp, 443/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                       captain-certbot.1.uclk6hw0ym882tmisdcagnxd7
d60c73995c64   registry:2                                                              "/entrypoint.sh /etc…"   4 minutes ago   Up 4 minutes   5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                              captain-registry.1.abaqjm3hjzodvvmajozgdsl9q
5c4fb29d38de   nginx:1                                                                 "/docker-entrypoint.…"   5 minutes ago   Up 4 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                                                                                                                                                                                                                                                                                                                                              captain-nginx.1.mvmijsjq91k1wt7hz8dfufbd8
a785ff5024ed   caprover/caprover:1.10.1                                                "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                                                                                                                                                                                                                                                                                                                                             captain-captain.1.l804p5kbg97jgj53iuvcj6us0
ecbfe6f2eca4   caprover/netdata:v1.8.0                                                 "/run.sh"                12 days ago     Up 12 days     19999/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                             captain-netdata-container
33efa21bc53a   wordpress:4.9                                                           "docker-entrypoint.s…"   2 weeks ago     Up 2 weeks     80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--streamlife-deleteme-wordpress.1.wc557518gmd27nzytgwol40mk
6f2be6d06aaa   wordpress:4.9                                                           "docker-entrypoint.s…"   3 weeks ago     Up 3 weeks     80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--streamlifetube-wordpress.1.yivdsnumugwyce76lavxmoszu
54bbec3337ea   mysql:5.7                                                               "docker-entrypoint.s…"   3 weeks ago     Up 3 weeks     3306/tcp, 33060/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                   srv-captain--streamlifetube-db.1.wjrvo8mqf90pkm4o06y7j7mnr
adabafeb7db5   caprover/nginx-reverse-proxy:1-ef5ffcb                                  "/docker-entrypoint.…"   4 weeks ago     Up 4 weeks     80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--nginx-rtmp-live.1.m0mggicy2o2dyao086z9ivcki
57ff09deda67   spreed/webrtc:latest                                                    "/bin/sh /srv/entryp…"   2 months ago    Up 2 months    8080/tcp, 8443/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                    srv-captain--spreedwebrtc.1.8227squ2x725k82fd06qi5y9o
4ea1b9b7d988   registry.s1.streamcloud.us:996/captain/img-captain-mynet-cron:1         "/cron.sh"               2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--mynet-cron.1.grllqgc5ytg1wdp5i3vdas3b0
29fc121fcda7   nextcloud:21.0.1                                                        "/entrypoint.sh apac…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--mynet.1.xulto2umm4zea6893qwpo1szz
a5c48fcbea6c   redis:6.2.2                                                             "docker-entrypoint.s…"   2 months ago    Up 2 months    6379/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                              srv-captain--mynet-redis.1.hwf0l0qvdds2lx933001n1bkk
f5443d9f115e   mariadb:10.5.9                                                          "docker-entrypoint.s…"   2 months ago    Up 2 months    3306/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                              srv-captain--mynet-db.1.q30vdprayhgi7xh3rdqkya1c8
215302c6b775   wordpress:4.9                                                           "docker-entrypoint.s…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--stube-wordpress.1.ok6pl0xjqnxgbg0b6dsudhet9
d1496559e565   8b43c6af2ad0                                                            "docker-entrypoint.s…"   2 months ago    Up 2 months    3306/tcp, 33060/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                   srv-captain--stube-db.1.g2uhufm77dyzee3hrnfelo5sj
4ca4da6529e9   adminer:4                                                               "entrypoint.sh docke…"   2 months ago    Up 2 months    8080/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                              srv-captain--adminer.1.pqjg44q39sv4gbvbeai81as8j
e3eb7e0d36b9   registry.s1.streamcloud.us:996/captain/img-captain-nginxvideoserver:4   "nginx -g 'daemon of…"   2 months ago    Up 2 months    1935/tcp, 8080/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                    srv-captain--nginxvideoserver.1.wtq9o4afv5yqfq2nmweew6kqu
c3ae5e36237d   portainer/agent:latest                                                  "./agent"                2 months ago    Up 2 months    0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                                                                                                                                                                                                                                                                                                                                                                                             workerservers_agent.tvezps2srmbqty7px7i673c51.dm0t4ukn06wzobbu2ab7sm1n2
ffdbae74c5c1   portainer/portainer-ce:2.0.0                                            "/portainer"             2 months ago    Up 2 months    8000/tcp, 9000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                    srv-captain--portainer.1.0z68plj43w482rk1txo27g97b
2d16a2c322a4   registry.s1.streamcloud.us:996/captain/img-captain-videototelegram:4    "/docker-entrypoint.…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--videototelegram.1.dv7qw544iitg2k41n7k91lwtn
0932020af8ac   registry.s1.streamcloud.us:996/captain/img-captain-videotube:2          "/docker-entrypoint.…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--videotube.1.ma1ttxd8d30b0lwkvtt95q52l
0e70bb24298f   registry.s1.streamcloud.us:996/captain/img-captain-ovenmediaengine:2    "/docker-entrypoint.…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--ovenmediaengine.1.ywwm8dh8ag97bvbv95x8vl92j
2d1397cff73d   registry.s1.streamcloud.us:996/captain/img-captain-nginxvideoserver:2   "/docker-entrypoint.…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--nginxvideoserver.1.o1wak6mz8ih0gz7ddc5d64o36
1d391500a767   airensoft/ovenmediaengine:latest                                        "/opt/ovenmediaengin…"   2 months ago    Up 2 months    0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 80/tcp, 0.0.0.0:3333->3333/tcp, :::3333->3333/tcp, 0.0.0.0:3478->3478/tcp, :::3478->3478/tcp, 3334/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:4000-4005->4000-4005/udp, :::4000-4005->4000-4005/udp, 0.0.0.0:9999->9999/udp, :::9999->9999/udp, 8090/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:10006-10010->10006-10010/udp, :::10006-10010->10006-10010/udp, 10000-10005/udp   ovenmediaengine
976f372bd364   nginx                                                                   "/docker-entrypoint.…"   2 months ago    Up 2 months    0.0.0.0:81->80/tcp, :::81->80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                     webserver
35b8c566c1d1   938b57d64674                                                            "docker-entrypoint.s…"   2 months ago    Up 2 months    3306/tcp, 33060/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                   srv-captain--streamcloud-db.1.uigmuzhhk2dmbpqmjbtionsvj
8f2a9a117e48   wordpress:4.9                                                           "docker-entrypoint.s…"   2 months ago    Up 2 months    80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                srv-captain--streamcloud-wordpress.1.6l2j5gfijdq3svlw1at26omdo

**Comment by githubsaturn** [comment]
Your domain DNS is not working, this is before the request even reaches caprover 

![image](https://user-images.githubusercontent.com/10582082/152263090-7abf6653-285a-4225-a4db-402dd1ff7f95.png)
