### ISSUE TITLE
Running docker-in-docker dind (and eventually Sentry) as an app deployed via CapRover

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1321]
I'm taking baby steps towards trying to get Sentry working as an app deployed via CapRover (it's a already a one-click app but only based on a deprecated docker image... [see here](https://github.com/caprover/one-click-apps/issues/352)).

It seems that the [new official method](https://develop.sentry.dev/self-hosted/) for installing and running Sentry requires docker and docker-compose, which effectively limits it to running on the host server, or perhaps within a docker-in-docker (dind) container.

For the dind approach, I'm failing even to get a dind app running (and staying running... the plan then being to try and get Sentry running within `dind`)... just using a Dockerfile with `FROM docker:dind` doesn't work.  It seems that dind needs to be run with `privileged` flag... see [here](https://hub.docker.com/_/docker).  Now, [this issue](https://github.com/caprover/caprover/issues/909) seems related but specifying a persistent app with mapping from `/var/run/docker.sock` to `/var/run/docker.sock` doesn't work either, with the logs showing:

	2022-02-02T19:31:02.391006836Z /certs/client/cert.pem: OK
	2022-02-02T19:31:02.452637332Z ip: can't find device 'ip_tables'
	2022-02-02T19:31:02.454532230Z ip_tables 28672 3 iptable_mangle,iptable_filter,iptable_nat
	2022-02-02T19:31:02.454568184Z x_tables 40960 11 xt_REDIRECT,xt_ipvs,iptable_mangle,xt_mark,xt_nat,xt_tcpudp,xt_conntrack,ipt_MASQUERADE,xt_addrtype,iptable_filter,ip_tables
	2022-02-02T19:31:02.455089151Z modprobe: can't change directory to '/lib/modules': No such file or directory
	2022-02-02T19:31:02.460851697Z mount: permission denied (are you root?)
	2022-02-02T19:31:02.461072691Z Could not mount /sys/kernel/security.
	2022-02-02T19:31:02.461078730Z AppArmor detection and --privileged mode might break.
	2022-02-02T19:31:02.465803390Z mount: permission denied (are you root?)

Any hints about how to get `dind` or even Sentry itself running within a CapRover app would be awesome.

**Comment by githubsaturn** [comment]
Gitlab OCA does the same thing... It binds to Docker API... 
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/gitlab-runner.yml

I personally haven't had much success with DIND either. 

But specific to your question regarding running privileged containers, you can always run `docker service update --cap-add....` to add capabilities if Docker swarm supports that.

**Comment by githubsaturn** [comment]
CapRover won't mess with anything that it doesn't control.

**Comment by drmrbrewer** [comment]
> you can always run `docker service update --cap-add....` to add capabilities 

Can this be used to add 'privileged' capability to a service, equivalent to `docker run --privileged`?

**Comment by githubsaturn** [comment]
`docker run` is for containers. CapRover uses docker swarm, so no, they are somewhat different. 

See here for a long.... discussion: https://github.com/docker/swarmkit/issues/1030

**Comment by drmrbrewer** [comment]
Yep, I know that `docker run` is for containers, so I was wondering whether `cap-add` could replicate 'privileged` mode for a service (because it's not possible to set that directly on a service).  But even after `docker service update --cap-add ALL` it doesn't seem to work.  Time to try another approach, or give it up as a lost cause :(

**Comment by drmrbrewer** [comment]
@githubsaturn I wonder whether you can comment on the interaction between the host and a service deployed via CapRover, where the service is "linked" to the host via `/var/run/docker.sock`, particularly regarding use of HTTPS set up for the service via CapRover?

I've just about got something working along the following lines... it's really far from ideal, but it's progress of sorts:

(1) set `Container Port` of new `sentry` app to `9000`

(2) set persistent volumes of the app as:

    /var/run/docker.sock --> /var/run/docker.sock  (to use docker daemon from host rather than using DIND)
    /root/sentry --> /root/sentry  (so that the sentry installation files and folders are available in the host during installation)

(3) Dockerfile: deploy a basic app based on `FROM ubuntu`, installing `docker` and `docker-compose`, and keep the service running with `ENTRYPOINT [ "tail", "-f", "/dev/null" ]` at the end

(4) after it's deployed, open a `bash` into the container and install sentry based on the [official guide](https://github.com/getsentry/self-hosted/)... this needs access to the host's docker daemon via `/var/run/docker.sock` and uses an installation folder cloned into `/root/sentry` (i.e. on host and in container)

(5) when that completes, in the bash shell start sentry running with `docker-compose up -d`

That's pretty much it.  Sentry is now running in the container... *or is it really*?  

So far as I can understand, because we're using the *host's* docker daemon, all the sentry containers are spun up as sibling containers in the *host*, so really we have Sentry running on the host and not really in the container as such?  

Is there really any benefit in having the sentry app at all deployed via CapRover, if everything is just running on the host... may as well just install sentry directly on the host without any involvement from CapRover?

In particular, I was hoping to be able to take advantage of the easy HTTPS config through CapRover.  Sentry itself seems to run on port `9000`, and hence by setting the Container Port of the app to `9000` I was hoping to be able to access Sentry via e.g. `https://sentry.myserver.com/`.

But this doesn't work.  Instead, I have to use `http://sentry.myserver.com:9000/`... i.e. not HTTPS and also with the port specified explicitly.

Do you have any insight as to how I can get this working on `https://sentry.myserver.com/`?

**Comment by githubsaturn** [comment]
> Is there really any benefit in having the sentry app at all deployed via CapRover, if everything is just running on the host... may as well just install sentry directly on the host without any involvement from CapRover?

Doesn't matter either way. Containers are isolated environments - regardless of whether they are created by Sentry in another container or Sentry on the host.

> Do you have any insight as to how I can get this working on https://sentry.myserver.com/?

This is bizarre. The only potential reason that I could think of is how Sentry listens to port 9000. In order to be able to be pinged by other containers (specifically, by nginx container), Sentry needs to listen to 0.0.0.0:9000, but some applications have a default interface of localhost, e.g., 127.0.0.1:9000 - it might be able case with Sentry and you'll have to explore if Sentry allows you to change listening interface to 0.0.0.0

**Comment by drmrbrewer** [comment]
> Sentry needs to listen to 0.0.0.0:9000, but some applications have a default interface of localhost, e.g., 127.0.0.1:9000

It's hard to unpick the docs on this.  The [overview page](https://develop.sentry.dev/self-hosted/) has the following:

![image](https://user-images.githubusercontent.com/9009792/152636869-4c155c71-5b7f-4977-b4b2-0711875c9e8f.png)

But the [more detailed docs](https://develop.sentry.dev/config/) has the following:

![image](https://user-images.githubusercontent.com/9009792/152636904-19a73637-0b04-4489-aee4-5427126354f1.png)

It refers to the default being `localhost` but the value (in the actual config file) is `0.0.0.0` (as above).

A recursive grep search within the content of all files in the repo reveals none with any meaningful reference to `127.0.0.1`.

**Comment by drmrbrewer** [comment]
Here is the output of `docker container ls` (including some of the many sentry containers and also the container for the sentry app `srv-captain--sentry` itself):

	CONTAINER ID   IMAGE                                                                              COMMAND                  CREATED          STATUS                    PORTS                                                                      NAMES
	7509e409e8ed   registry:2                                                                         "/entrypoint.sh /etc…"   40 minutes ago   Up 40 minutes             5000/tcp                                                                   captain-registry.1.bt1anj7aweqnrfh62exq788yo
	6c34f01aaa51   caprover/certbot-sleeping:v1.6.0                                                   "/bin/sh -c 'sleep 9…"   40 minutes ago   Up 40 minutes             80/tcp, 443/tcp                                                            captain-certbot.1.833m3vbm9ij3qlhfpg24fcnqw
	6dd605bfb217   nginx:1                                                                            "/docker-entrypoint.…"   40 minutes ago   Up 40 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   captain-nginx.1.g4v13qnql2mmnff5v5x3f7i35
	b134c6ffbcbe   caprover/caprover:1.10.1                                                           "docker-entrypoint.s…"   41 minutes ago   Up 41 minutes             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                  captain-captain.1.obgm95oy7lya2d62omushvu3y
	97787ce3c8f7   nginx:1.21.5-alpine                                                                "/docker-entrypoint.…"   43 minutes ago   Up 43 minutes             0.0.0.0:9000->80/tcp, :::9000->80/tcp                                      sentry-self-hosted_nginx_1
	c3a63afbfa00   getsentry/relay:nightly                                                            "/bin/bash /docker-e…"   44 minutes ago   Up 43 minutes             3000/tcp                                                                   sentry-self-hosted_relay_1
	59541760d483   sentry-cleanup-self-hosted-local                                                   "/entrypoint.sh '0 0…"   45 minutes ago   Up 45 minutes             9000/tcp                                                                   sentry-self-hosted_sentry-cleanup_1
	3798bdae2810   getsentry/sentry:nightly                                                           "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes             9000/tcp                                                                   sentry-self-hosted_worker_1
	e1111492b697   getsentry/sentry:nightly                                                           "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes             9000/tcp                                                                   sentry-self-hosted_subscription-consumer-transactions_1
	1197c3fa888b   registry.xxxxxxx.yyyyyyyyyyyyy.com:996/captain/img-captain-sentry:68               "/root/entrypoint.sh"    52 minutes ago   Up 52 minutes             9000/tcp                                                                   srv-captain--sentry.1.9uhbx3sdqam8m3p4wvwp1yuql

Includes a `sentry-self-hosted_nginx_1` container.  It doesn't help if I remove the `9000/tcp` port config for `srv-captain--sentry`.

**Comment by githubsaturn** [comment]
Which container is the one that you want to use their 9000? There are many here...

You can verify the listening interface by shelling into the container and run
```
lsof -i -P -n | grep LISTEN
```

inside the container.

**Comment by drmrbrewer** [comment]
But there's only one container (i.e. `sentry-self-hosted_nginx_1`) with a port mapping from host port `9000` to a container port, isn't there?  Similarly, I also have many (many) containers in this list (deployed via CapRover) with port `80/tcp` but only one container (i.e. `captain-nginx`) that maps from host port `80` to a container port.

**Comment by githubsaturn** [comment]
All these containers have their port 9000 listed as LISTENING port
```
59541760d483   sentry-cleanup-self-hosted-local                       "/entrypoint.sh '0 0…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_sentry-cleanup_1
3798bdae2810   getsentry/sentry:nightly                               "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_worker_1
e1111492b697   getsentry/sentry:nightly                               "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_subscription-consumer-transactions_1
1197c3fa888b   registry.xxx.yyy.com:996/captain/img-captain-sentry:68 "/root/entrypoint.sh"    52 minutes ago   Up 52 minutes  9000/tcp                                                                   srv-captain--sentry.1.9uhbx3sdqam8m3p4wvwp1yuql

```

**Comment by drmrbrewer** [comment]
If you're confused, I'm *really* confused!  In my container listing, `img-captain-sentry` is the only one I have deployed via CapRover (as an app called `sentry`).  And within that I have bind mounted `/var/run/docker.sock` and installed the self-hosted sentry stuff into that container... it uses docker-compose to spin up multiple sentry-related containers... i.e. all the other ones you see in the listing... which are both on host and in sentry container... I haven't changed the config of the sentry installation at all, so if there are lots listening on port 9000 then that's just how they've set them up.  What I'm really hoping is that I can access the self-hosted sentry stuff via the sentry app itself (to take advantage of https).

**Comment by githubsaturn** [comment]
Ah, I think I know what you're trying to do. Is the following correct?

You want to use HTTPS to connect to a container that is NOT deployed directly via CapRover.

**Comment by drmrbrewer** [comment]
Well the sentry app *is* deployed by caprover, and the sentry server is deployed "within" that... except that it's not really within the container because it's using the host's docker daemon.

**Comment by githubsaturn** [comment]
> the sentry server is deployed "within" that

No, there is no "within that". Containers are siblings. So if all these 4 containers below are deployed "outside of CapRover"
```
97787ce3c8f7   nginx:1.21.5-alpine                                    "/docker-entrypoint.…"   43 minutes ago   Up 43 minutes  0.0.0.0:9000->80/tcp, :::9000->80/tcp                                      sentry-self-hosted_nginx_1
c3a63afbfa00   getsentry/relay:nightly                                "/bin/bash /docker-e…"   44 minutes ago   Up 43 minutes  3000/tcp                                                                   sentry-self-hosted_relay_1
59541760d483   sentry-cleanup-self-hosted-local                       "/entrypoint.sh '0 0…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_sentry-cleanup_1
3798bdae2810   getsentry/sentry:nightly                               "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_worker_1
e1111492b697   getsentry/sentry:nightly                               "/etc/sentry/entrypo…"   45 minutes ago   Up 45 minutes  9000/tcp                                                                   sentry-self-hosted_subscription-consumer-transactions_1
```

**Comment by drmrbrewer** [comment]
Sure, so there is no way of achieving what I am aiming for?

**Comment by githubsaturn** [comment]
Nothing out of the box, but it's not impossible. You'd have to do this
- Attach the target container to captain-overlay-network (not sure if Sentry installation allows you to do that)
- Create a reverse proxy one click app and internally route to that container.

**Comment by drmrbrewer** [comment]
> Attach the target container to captain-overlay-network

Since the sentry install process just uses docker-compose, it looks like adding the following lines to the `docker-compose.yml` file does the trick (see e.g. [here](https://stackoverflow.com/a/42750687/4070848)):

    networks:
      default:
        external:
          name: captain-overlay-network

This attaches all of the sentry containers to the existing `captain-overlay-network` rather than creating a separate network and using that.

> Create a reverse proxy one click app and internally route to that container

I hadn't known about this one-click app (and I can see uses elsewhere), thanks.  The following note appears in the one-click app config:

![image](https://user-images.githubusercontent.com/9009792/152761436-bdd4612c-f7bd-451a-bc7e-a6992311d61a.png)

So, as well routing internally to other CapRover apps as stated above (using service name starting `srv-captain--`) it seems that it's also possible to specify the *container* name instead (so long as the container is on the same network... hence your first point).  

So in this case there is a sentry container called `sentry-self-hosted_nginx_1` which appears to be the entrypoint to the sentry server, so I specify the following as the `UPSTREAM_HTTP_ADDRESS` in the reverse proxy app:

    http://sentry-self-hosted_nginx_1

(thanks for the tip about not including a trailing slash... that bit was crucial!)

And sure enough, it seems to work, providing HTTPS access to the self-hosted sentry server.  Thanks!  I'm sure there's still a lot more work to do, to get it all properly working, but I'm making progress!  One key learning is that it's pointless creating a `sentry` CapRover app and installing sentry inside that, because actually it achieves nothing because the docker containers end up being hosted on the host server, and we end up needing a separate reverse proxy anyway, so we may as well just install sentry directly on the host server.

**Comment by robgraeber** [comment]
The best way to do dind for a caprover app is by sharing the top level docker.

In your persistent directories settings set:
```
/var/run/docker.sock -> /var/run/docker.sock
/usr/bin/docker -> /usr/bin/docker
```

And on your caprover server you need to run:
`sudo chmod 666 /var/run/docker.sock`
