### ISSUE TITLE
remote repository configuration not used in deployment

### ISSUE THREAD

**Issue by Rdonn** [caprover/caprover#1323]
What is the problem?

When attempting to deploy an application using a docker hub image, authentication is not used. It also looks like the pre-deploy hook is running after attempting to pull the image.

I have verified that the credentials/PAT are configured correctly for read/write by having caprover use a private repository.

If applicable, content of `captain-definition` file:

NA

Steps to reproduce the problem:

create private repo in docker hub, provide credentials in caprover cluster config and attempted to deploy app with image name

Output of the following command on your server:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by githubsaturn** [comment]
Not sure if I understand why you're intending to do. All you need to do is to add your credentials and then you can go to deploy tab and deploy a private image. Here is an example. I just tried with a private repository on ghcr.io and it works completely fine.

You're probably not using the correct credentials.

![image](https://user-images.githubusercontent.com/10582082/152465593-18fc9681-4c0e-4cde-bf0a-633dfdc1abd0.png)

![image](https://user-images.githubusercontent.com/10582082/152465669-bef4d2bf-dfb0-4eb3-ac7a-481397072b3d.png)
