### ISSUE TITLE
Connect new domain

### ISSUE THREAD

**Issue by ashkaptsov** [caprover/caprover#1331]
I would like to "transfer" website from the root domain to another domain. I try to use "Connect New Domain" filed in HTTP settings.

<img width="417" alt="Schermata 2022-02-08 alle 13 55 07" src="https://user-images.githubusercontent.com/70571543/152991484-bdd39690-94f8-4a73-8a7a-b979c7d3d8b2.png">

I use cloudflare and point A to my server address. 
But unfortunately the "transfer" doesn't work. Getting this image. 

<img width="414" alt="Schermata 2022-02-08 alle 13 55 20" src="https://user-images.githubusercontent.com/70571543/152991755-4621e435-7da2-4e57-b4ef-74a62870f5cb.png">

I tried with other apps and other domains and it has the same issue. 
Any ideas how I can make it work?
Thanx

**Comment by githubsaturn** [comment]
You DNS set up is incorrect. A Record points to Cloudflare not your VPS. You'll have to use Cloudflare as a DNS provider, not proxy.

![image](https://user-images.githubusercontent.com/10582082/153018676-bb709db3-b1d0-4997-b212-b284b8a34904.png)
