### ISSUE TITLE
Is there a way to limit or not keep old images/version history?

### ISSUE THREAD

**Issue by haizalio** [caprover/caprover#1337]
I tried searching for a recent solution to this but couldn't. Pardon me if the solution has already been answered.

For me, old images take up too much space and having to manually clean up is tedious. Some apps break without notice when the server's storage is full making it a serious issue.  I do not have a need to rollback up to 50 versions in Caprover.

Could you advise me on how I may go about solving this issue? Thank you.

**Comment by githubsaturn** [comment]
See https://github.com/caprover/caprover/issues/457#issuecomment-532245598
