### ISSUE TITLE
Caprover doesn't load after reboot!

### ISSUE THREAD

**Issue by uhlhosting** [caprover/caprover#1339]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem? We got no containers running after reboot.

We runned this on same server after reboot:

```
pac@pac:~$ docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          46        20        22.25GB   10.35GB (46%)
Containers      20        0         875.3MB   875.3MB (100%)
Local Volumes   48        15        2.012GB   410MB (20%)
Build Cache     0         0         0B        0B

root@pac:/home/pac# docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          0         0         0B        0B
Containers      0         0         0B        0B
Local Volumes   0         0         0B        0B
Build Cache     0         0         0B        0B
```

This is very frustrating as it seems to get stuck like this, and it works when it wants while today I had over 5 system restores, only to see 1 of them working.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem: Rebooted server.

Output of the following command on your server:

```
root@pac:/home/pac# uname -a && lsb_release -a && free -h
Linux pac 4.15.0-167-generic #175-Ubuntu SMP Wed Jan 5 01:56:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:            15G        282M         14G        1.0M        861M         15G
Swap:          4.0G          0B        4.0G
root@pac:/home/pac# 
```

**Comment by uhlhosting** [comment]
On the console of VPS we got;
<img width="556" alt="image" src="https://user-images.githubusercontent.com/6324047/153303422-34ea9a4c-f3f5-4bab-a67f-a9f20368722e.png">

**Comment by uhlhosting** [comment]
@githubsaturn yes we use a Proxmox Snapshot from 5 days ago. Funny that it worked fine with a restore from a few months.
It failed after several minutes later. We had the caprover in a swarm cluster, yet this was removed before it broke or the issues occured. 

We have all these snapshots:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/6324047/153368532-97138874-ca5f-457f-86a3-2debc3558817.png">

Its terrible that now this doesnt work anymore.

**Comment by uhlhosting** [comment]
Made now a fresh restore, I got it to the point where it revived all the apps and they run on server side, yet the UI in Web has failed me to login to caprover:

https://captain.pac.uhl.cloud/#/login

1001 : Captain is not ready yet...
and Something bad happened.

Yet now in the server all processes are up. 140+ compared to 30+ when it fails to load at all. Again in reality it should be no cluster swarm enabled, since I disabled it once in past.

If you want to debug / help me troubleshoot this, I could add you ssh key to our server to take a look, I do have a feeling somewhere is a bug or something.

**Comment by githubsaturn** [comment]
> 1001 : Captain is not ready yet...
and Something bad happened. or a 504 Gateway Time-out from nginx that usually gets back at every 2/3 refresh.


Run `docker service logs captain-captain --tail 100` to get the logs of CapRover, what do see?

Also run `docker service ls` - what's the output?

**Comment by githubsaturn** [comment]
Yup, as I thought, this is a definitely a Docker issue and it's unrelated to CapRover:
```
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

Suggest [asking a Docker forum](https://github.com/moby/moby/issues).

Make sure to post the output of `docker info` and also mention that you have snapshotted the server. I think snapshoting is what caused the issue. Live Docker swarm clusters, as far as I know, should not be backed up via snapshots.

**Comment by uhlhosting** [comment]
@githubsaturn I did mentioned above that my server was not in a swarm. I am really confused now, is there a paid support for caprover at least we can try ? I doubt this is a docker issue when there was no swarm made and it seems all applications we had are up, over 10. Only caprover fails. In what I noticed this could be a bug between caprover and running docker in ubuntu via snap.

**Comment by githubsaturn** [comment]
> my cluster is not in a swarm... i dont get it. all apps work only caprover fails, i dont see how this is docker.

By installing CapRover, your node turns into a swarm manager. Here is more details for you:

When you run `docker run ..... caprover/caprover`, CapRover initializes a Docker swarm and a docker overlay network for you in the background. Then it spins up 3 Docker swarm services `captain-nginx` `captain-cerbot` and `captain-captain` . Subsequently, when you deploy an app, it spins up a Docker swarm service for that app.

With a healthy CapRover instance, you can run `docker service ls` and see all your apps. 


Docker swarm services are an "orchestration" layer over the containers. So that's why your apps still work, but CapRover doesn't work.


----

Here is how you can emulate the broken stage of your system:
- Install CapRover on a healthy fresh system and set it up as usual by setting root domain and SSL.
- Deploy a few apps
- Run `docker service ls` and you will see your apps
- Run `docker ps` and you will see your apps
- Now, run `docker swarm leave --force` to break the instance
- Now if you run `docker service ls` you'll see an error
- But if you run `docker ps` you'll see that your old containers are still running.

**Comment by uhlhosting** [comment]
@githubsaturn found the issue, it seems a snap docker deplpoymet was taking over my docker cli, so therefor this was blocking from showing anything. The moby team never implied that a swarm cannot be restored from a snapshot. I had to stop the snap docker, remove it, and has the current docker cli to run. Simply all is up after restarting docker.socket. This seems to be slipped in somehow no clue how and when, since I removed all docker images added docker repo and installed. Since was working well for months, while at once just to fail was a bit too much. Luckyli is all good now.

**Comment by githubsaturn** [comment]
Nice! Glad to hear you sorted it out. Yea I figured, there must be an issue with Docker...

Regarding restoring from snapshot, I am fairly certain that it won't work if your snapshot is old enough that its key is expired by the time you want to restore. By default, swarm cert is valid for 90d and it automatically gets renewed as long as your cluster is live. But I am not sure how long before it expires, it gets renewed. So if you took a snapshot before it was renewed, and you want to restore it after the expiration date. It shouldn't work.
