### ISSUE TITLE
[Question] Caprover always at 100% CPU consumption

### ISSUE THREAD

**Issue by murratore** [caprover/caprover#1342]
Hello

I set up a new Caprover instance on digital ocean. Everything worked fine. I also set up a swap drive (as linked in the howto).
Without a created app, performance monitor shows cpu consumption of 1-10%. 

After creating two (empty) apps. Still 1-10%. 
Then deployed two dot net apps (as docker images) from the command line wie "caprover deploy". On the first deployment with one of the dot net apps there was a problem with a wrong Dockerfile. Fixed this and both apps now work.

Now the point. Since then - even with no usage of these two apps the dropplet has a cpu consumption of 100% - all the time. When I ssh into the droplet I see that there are a couple of "cloud-init" process which eats a lot of cpu. 
In the netdata monitoring I see that most of the CPU ist consumed by the root user.

Am I doing something wrong?

Thank you

**Comment by githubsaturn** [comment]
Must be an OS bug. Try removing your apps and see if the CPU returns back to normal. In NetData you can also view the CPU usage per container.

**Comment by murratore** [comment]
After some hours it "magically" stopped the CPU consumption. No clue what the problem was.
