### ISSUE TITLE
Certbot node 'is not available' even though node ID is correct.

### ISSUE THREAD

**Issue by ebecaf** [caprover/caprover#1344]
To follow on from #1310, I restored a backup of my server (full VPS disk restore).

After which (for the second time, but on a different server) Certbot does not run and creates error 1107 (see here for full error details https://github.com/caprover/caprover/issues/1310#issuecomment-1041490675).

This time however, I have noticed two things:
1. In all of my apps I get the same message in the App Logs box:
`Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node v2o9ita4nj********a3zhb6c is not available`
2. I have Portainer running so I can see that the 'com.docker.swarm.node.id' is the same as it was before the Restore (ending zhb6c).

Is anyone aware of this issue, and is there anything I can do to 'reconnect' the certbot node?

Thank you.

**Comment by githubsaturn** [comment]
> Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node v2o9ita4nj********a3zhb6c is not available

This error is thrown by Docker, not CapRover. There are hundreds, if not thousands of reasons that could cause this. It could be a bad kernel (OS), or a disk or network problem. See this issue for example: https://github.com/moby/moby/issues/35011

**Comment by githubsaturn** [comment]
Does this work `docker service logs srv-captain--yourappname` on your system?

**Comment by ebecaf** [comment]
> docker service logs srv-captain

It 'works' but I get the same error. The node that is apparently unavailable is the CapRover Certbot (`captain-certbot`), which is the one that is having issues.

At this time, no other app seems to have any issues, and what is more concerning, is that the Certbot container has presented the same issue after a backup restore on two different VPS (Ubuntu 20.04 and 21.10), which is why I rebuilt it in the first place because I could no longer create TLS certs after a backup restore.

I've checked with Linode and they are seeing no issues with the restore or backups (and as mentioned I have no other (obvious) issues) so I assume it might be something to do with the Certbot container itself after a restore (does it change ID or permissions?)

**Comment by ebecaf** [comment]
On Portainer it says the ownership is 'administrators', should this be something else?

Also, should the `captain-certbot` container be part of 'captain-overlay-network' ? Currently it's just 'bridge'.

Thank you.

**Comment by ebecaf** [comment]
New error, so I ran `docker service update captain-captain --force`

Now when I try to get an SSL, I get this in the logs:

`February 17th 2022, 7:54:56.911 pm    Verifying Captain owns domain: test2-wordpress.example.com
February 17th 2022, 7:54:57.917 pm    Enabling SSL for: test2-wordpress
February 17th 2022, 7:54:57.919 pm    Enabling SSL for test2-wordpress.example.com
February 17th 2022, 7:55:00.924 pm    Retrying to get containerId for captain-certbot retry count:0
February 17th 2022, 7:55:03.929 pm    Retrying to get containerId for captain-certbot retry count:1
February 17th 2022, 7:55:06.934 pm    Retrying to get containerId for captain-certbot retry count:2
February 17th 2022, 7:55:09.938 pm    Retrying to get containerId for captain-certbot retry count:3
February 17th 2022, 7:55:12.944 pm    Retrying to get containerId for captain-certbot retry count:4
February 17th 2022, 7:55:15.948 pm    Retrying to get containerId for captain-certbot retry count:5
February 17th 2022, 7:55:18.955 pm    Retrying to get containerId for captain-certbot retry count:6
February 17th 2022, 7:55:21.961 pm    Retrying to get containerId for captain-certbot retry count:7
February 17th 2022, 7:55:24.965 pm    Retrying to get containerId for captain-certbot retry count:8
February 17th 2022, 7:55:27.969 pm    Retrying to get containerId for captain-certbot retry count:9
February 17th 2022, 7:55:27.972 pm    Error: No containerId is found
Error: No containerId is found
    at /usr/src/app/built/docker/DockerApi.js:683:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
POST /api/v2/user/apps/appDefinitions/enablebasedomainssl 500 31069.557 ms - 21
`

Also I have noticed via Portainer that I have THREE captain-certbot containers!? They all have the same id ending `zhb6c` as mentioned before.

I don't know what is going on! It's really strange. I really like CapRover but I'm not sure if I can keep using it, because if I happen to need to do a backup restore, certbot basically stops working, meaning ALL new and re-newal SSLs fail. :(

**Comment by githubsaturn** [comment]
`captain-certbot` doesn't need to be on any network.

> It 'works' but I get the same error. The node that is apparently unavailable is the CapRover Certbot (captain-certbot), which is the one that is having issues.

This is clearly indicating that your Docker swarm engine is busted. Post the complete output from these two commands on [Docker's github](https://github.com/moby/moby/issues) for them to look into.
```
docker service ls
docker service logs srv-captain--yourappname
```
