### ISSUE TITLE
[Deployment Issue] Cannot change git branch from master when deploy on Windows 10

### ISSUE THREAD

**Issue by mrlinnth** [caprover/caprover#1350]
What is the problem?

![image](https://user-images.githubusercontent.com/4952597/154829607-d7dbf96b-cbe0-43ff-9abf-484592e55afa.png)

If applicable, content of `captain-definition` file: Don't think it is related to cap-definition file, so I'll skip. I am using the laravel template.

Steps to reproduce the problem:

Try to do caprover deploy from my local PC windows 10.  Can sign in to my caprover server. Can select app. But cannot change the branch from master to other branch. 

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

![image](https://user-images.githubusercontent.com/4952597/154829910-4ec86f2d-039a-4be9-bb76-02c55e804c98.png)

---

Remarks:

I do not have this issue on my Linux and Mac. My colleague who is using Windows 10 also face this issue.

My screenshot has my node version and npm version.

**Comment by githubsaturn** [comment]
There is an existing bug report: https://github.com/caprover/caprover-cli/issues/88

Does it go away if you press on ENTER one more time?

**Comment by mrlinnth** [comment]
Sorry for the late response. 
Yes it goes away upon second ENTER.

I wasn't looking at cli repo's issues. I will close this issue.
