### ISSUE TITLE
Port map 443/udp in nginx service to allow HTTP3

### ISSUE THREAD

**Issue by jonaskuske** [caprover/caprover#1354]
**Is your feature request related to a problem? Please describe.**

I'm using the `macbre/nginx-http3` image for the nginx service so my apps can use HTTP3:

```json5
// config-override.json
{
  "nginxImageName": "macbre/nginx-http3:1.21.6"
}
```

Unlike HTTP1 and 2 which are based on TCP, HTTP3 uses the UDP protocol. Unfortunately, HTTP3 connections can't be established because no UDP port is mapped to the nginx container: https://github.com/caprover/caprover/blob/master/src/user/system/LoadBalancerManager.ts#L564-L577.

**Describe the solution you'd like**

Either add `443/udp` to the array of mapped ports, or make the ports array configurable via `config-override.json`.

**Describe alternatives you've considered**

Remember to manually update the port config every time the nginx service is created using
`docker service update --publish-add published=443,target=443,mode=host,protocol=udp captain-nginx`. Error-prone and tedious 😅

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/pull/1355#issuecomment-1050377027
