### ISSUE TITLE
1001 captain not ready and the caprover/certbot-sleeping:v1.6.0 is shutting down 

### ISSUE THREAD

**Issue by Panhara28** [caprover/caprover#1359]
I try to docker  pull caprover/certbot-sleeping:v1.6.0

I follow the issue https://github.com/caprover/caprover/issues/377
but still not fixed the error 

![image](https://user-images.githubusercontent.com/20127811/155877910-7f88b818-8ee6-402d-b816-4c2640120392.png)

**Comment by githubsaturn** [comment]
What's the problem here? CapRover not starting? Or certbot keeps restarting?

If it's certbot restarting, try running this:
```
docker run caprover/certbot-sleeping:v1.6.0
```

Does this block your terminal? Or does it exit after a minute?

**Comment by aneksa** [comment]
Hello, i have this problem to.
my certbot keeps restating.

`docker run caprover/certbot-sleeping:v1.6.0`
doesn't give any response

<img width="613" alt="Screen Shot 2023-01-13 at 18 26 23" src="https://user-images.githubusercontent.com/20569791/212310134-471cd077-f472-464c-9996-0c1590593bc3.png">

**Comment by Smyja** [comment]
> Hello, i have this problem to. my certbot keeps restating.
> 
> `docker run caprover/certbot-sleeping:v1.6.0` doesn't give any response
> 
> <img alt="Screen Shot 2023-01-13 at 18 26 23" width="613" src="https://user-images.githubusercontent.com/20569791/212310134-471cd077-f472-464c-9996-0c1590593bc3.png">

how did you resolve this?

**Comment by githubsaturn** [comment]
`caprover/certbot-sleeping` is not supposed to generate any output. It's working as intended. CapRover runs the certbot commands through an `exec` command via Docker.
