### ISSUE TITLE
Suggest current branch name

### ISSUE THREAD

**Issue by louis77** [caprover/caprover#1367]
**Is your feature request related to a problem? Please describe.**

When deploying using the Caprover CLI, it is always "master" branch that is suggested as the default branch name. Most of the time, I do either have "main" (which is the common default with GitHub and others) or some other branch I'm currently working on.

The current branch can usually fetched with this command: 

`git rev-parse --abbrev-ref HEAD`

**Describe the solution you'd like**
It would be extremely comfortable if Caprover CLI could detect the current branch and automatically suggest that one.

**Describe alternatives you've considered**
If that is not possible, at least change the default from `master` to `main`.

**Comment by githubsaturn** [comment]
You can set up an env var `CAPROVER_DEFAULT_BRANCH=main` on your machine.
