### ISSUE TITLE
[Question] List of Apps?

### ISSUE THREAD

**Issue by ebecaf** [caprover/caprover#1369]
Hi,

I want to be able to show people (internally at work and personally) the benefit(s) of CapRover.

It is quite difficult when there is no list of apps like on Cloudron.io, or Sandstorm.io

I am a web designer and can help with this if needed, but it should not be too hard as there is obviously already a list on the CapRover dashboard, it would just be great for that information to be made publicly accessible, without having to login to the demo.

Thank you.

**Comment by maietta** [comment]
Hi ebecaf,

I agree! The official current list of apps published are available for inspection here:

https://github.com/caprover/one-click-apps/tree/master/public/v4/apps

But it could be a nice feature request to have a new page added to the main website like so:

![image](https://user-images.githubusercontent.com/11745020/158232505-1ba120ee-a6ad-4f97-8887-0284e6dcc872.png)

If I wasn't so busy on another project, I'd be working on a pull request to implement this in a way that is automatically fetched from the repo.
