### ISSUE TITLE
110: Connection timed out

### ISSUE THREAD

**Issue by ashkaptsov** [caprover/caprover#1376]
Hey,

many times I get errors with timeout. Check the nginx logs and get this message:

`2022/03/19 19:05:39 [error] 235#235: *1494126 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 194.230.145.160, server: noco.admin.esperto.ch, request: "GET /dashboard/auth/type HTTP/2.0", upstream: "http://10.0.1.236:8080/dashboard/auth/type", host: "noco.admin.esperto.ch", referrer: "https://noco.admin.esperto.ch/dashboard/"`

Is it a bug or there is something I can change?
Thanx

**Comment by githubsaturn** [comment]
This is just a timeout. If your application is exteremly slow and you need to override defaul timeout config provided by nginx, you can do so like this:
https://stackoverflow.com/a/46205792/3236788

**Comment by ashkaptsov** [comment]
yes, I already red this and apply, but it doesn't resolve anything
this is my  CapRover nginx config:

`
# Default catch-all page. e.g. if you enter SOME-RANDOM-CHARS.captainroot.domain.com
    server {

        # Catch all HTTP
        listen       80;

        # Catch all HTTPS
        listen              443 ssl;
        ssl_certificate     <%-fake.crtPath%>;
        ssl_certificate_key <%-fake.keyPath%>;

        server_name  _;

        location /nginx_status {
            stub_status on;

            access_log off;

            # This can be improved by adding authentication as well.
            # CIDR Range IPs:
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            
            deny all;
        }

        location / {
             
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /error_generic_catch_all.html;
    }


# Captain dashboard at captain.captainroot.domain.com
    server {

        listen       80;
        client_max_body_size 300m;

    <%
        if (captain.hasRootSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-captain.crtPath%>;
        ssl_certificate_key <%-captain.keyPath%>;

    <%
        }
    %>

        server_name  <%-captain.domain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-captain.serviceName%>:<%-captain.serviceExposedPort%>;

        # IMPORTANT!! Except proxy_read_timeout, this block should be same as location /api/v2/user/apps/appData
        location / {
            
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # temporary until build process becomes an asynchronous process
        location /api/v2/user/apps/appData {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600;
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-captain.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-captain.staticWebRoot%>;
        }
    }



# Built-in Docker Registry at registry.captainroot.domain.com
# Port 80/443 is used by Let's Encrypt to support HTTPS
# But the Registry engine runs on port 996
    server {

        listen       80;
        client_max_body_size 500m;

    <%
        if (registry.hasRootSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-registry.crtPath%>;
        ssl_certificate_key <%-registry.keyPath%>;
    <%
        }
    %>

        server_name  <%-registry.domain%>;

        location / {
            root <%-registry.staticWebRoot%>;
        }
    }
`

**Comment by githubsaturn** [comment]
This is for CapRover dashboard itself. You need to add this to your server block for your specific app that is slow. Go to Apps > Your app > Edit nginx config.

Please know that nginx configuration is very sensitive and CapRover cannot validate your nginx configuration. If you make a mistake, you might break your entire instance. If that happens, you can revert back by [using this](https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui)

**Comment by ashkaptsov** [comment]
this are nginx settings for NocoDB App but anyway have the same problem

`<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {
           
    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>
            proxy_read_timeout 3600;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
`

**Comment by ashkaptsov** [comment]
All right, will try that. Could you just write how to di it?

**Comment by githubsaturn** [comment]
Apps > nocodb > App config (second tab) > Ports: `4321 to 8080` - `8080` is the default port for NocoDB, but you can pick whatever you want for `4321`

Then you can access your instance at `http://noco.admin.esperto.ch:4321` (No HTTPS)

![image](https://user-images.githubusercontent.com/10582082/159588984-8ee1e1aa-a935-4478-bc05-7c78f54187e0.png)

**Comment by ashkaptsov** [comment]
Unfortunately still have the same problem...

The thing is that I have setup a webhook on Noco that after insert it should send a message to telegram. It works if I insert it manually but it doesn't work if I insert the record via API. 
Developers of Noco after checking my set up and server logs told me that is Server/CarRover's issue.
They suggested to check the outbound settings & logs in CapRover.

**Comment by githubsaturn** [comment]
> Unfortunately still have the same problem...

What problem? Still nginx problem? If you did what I mentioned above, you are not even routing through nginx.
