### ISSUE TITLE
No matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by OmerSabic** [caprover/caprover#1378]
### What is the problem?

Deploying any app is returning the error
`Deploy failed!
Error: {"message":"no matching manifest for linux/arm64/v8 in the manifest list entries"}
no matching manifest for linux/arm64/v8 in the manifest list entries`

### If applicable, content of `captain-definition` file:
`{
  "schemaVersion": 2,
  "templateId": "node/8.7.0"
}`

### Steps to reproduce the problem:

Running on ARM server. I have tried both the edge and latest version, same results.

### Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux instance-20220325-1947 5.4.0-1064-oracle #68~18.04.1-Ubuntu SMP Wed Feb 9 22:37:05 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:            17G        341M         12G        2.3M        4.8G         16G
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
This is unrelated to CapRover. Node 8.7.0-alpine is only built for amd64
https://hub.docker.com/_/node?tab=tags&page=1&name=8.7.0-alpine

You can just use a newer version of node, example:
```
{ "schemaVersion": 2, "templateId": "node/14" }
```
