### ISSUE TITLE
JsonWebTokenError: jwt must be provided

### ISSUE THREAD

**Issue by ylluminate** [caprover/caprover#1382]
Loading CapRover's dashboard, etc. gave a message about "something bad happened" and if I looked in the logs, I saw the following:
```
captain-captain.1.h1dzeuna3czx@cr1    | March 31st 2022, 3:39:29.464 am    TokenExpiredError: jwt expired
captain-captain.1.h1dzeuna3czx@cr1    | TokenExpiredError: jwt expired
captain-captain.1.h1dzeuna3czx@cr1    |     at /usr/src/app/node_modules/jsonwebtoken/verify.js:152:21
captain-captain.1.h1dzeuna3czx@cr1    |     at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:90:14)
captain-captain.1.h1dzeuna3czx@cr1    |     at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:94:10)
captain-captain.1.h1dzeuna3czx@cr1    |     at /usr/src/app/built/user/Authenticator.js:78:17
captain-captain.1.h1dzeuna3czx@cr1    |     at new Promise (<anonymous>)
captain-captain.1.h1dzeuna3czx@cr1    |     at Authenticator.decodeAuthToken (/usr/src/app/built/user/Authenticator.js:77:16)
captain-captain.1.h1dzeuna3czx@cr1    |     at /usr/src/app/built/injection/Injector.js:43:14
captain-captain.1.h1dzeuna3czx@cr1    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
captain-captain.1.h1dzeuna3czx@cr1    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
captain-captain.1.h1dzeuna3czx@cr1    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
```

I attempted to run `docker service update captain-captain`, but that didn't seem to do anything. I then did this to make sure I was set to the latest and see if it would force any update `docker service update captain-captain --image caprover/caprover:latest`, but this also didn't do anything.

Finally I ran `docker service update captain-captain --force` and then refreshed the admin interface and it seemed to have kinda resolved it, and the apps all show up, but the dashboard has the congratulations message:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/eDu5jgoo/8017f61d-3e38-4bf4-9b24-038cbd808136.jpg?v=52a90f33e375a5064f20dba6a25a8c21)

If I click "Change Root Domain Anyways" I get the "CapRover Root Domain Configurations" dialogue and it says:
>Force Change Root Domain
> You have already enabled SSL for your root domain. Changing the root domain URL will invalidate HTTPS on root domain and all default subdomains for apps if you have any apps.
>
> You can still re-enable HTTPS after changing the root domain.

So I'm not sure what to do at this point.  All of our apps are showing up under "Apps" and they appear to be running, BUT we don't want to have problems with name resolution or SSL renewals...

Did I blow away some config info by running the `docker service update captain-captain --force` command and, if so, can I recover from this?

What should I do next here?

Server info:

```
$ uname -a && lsb_release -a && free -h
Linux cr1 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           7.8G        2.3G        1.6G         20M        3.8G        5.2G
Swap:          511M          0B        511M
```

**Comment by githubsaturn** [comment]
The dashboard screenshot that you have is totally fine. I am not sure what you're trying to do, your instance is fully functional. What's the problem here?

**Comment by ylluminate** [comment]
Thanks for the quick reply. Obviously my initial concern and problem was the `JsonWebTokenError: jwt must be provided` message from the logs and error message on the app.  Was my `docker service update captain-captain --force` the appropriate method for resolving this?  

I have to think that something was out of date / had not been automatically updated and this `--force`'d update may have resolved it?  

Otherwise I guess I still need to be hunting.  I'm glad to hear that the "Dashboard" looking that way is right.  Normally when I was logging in I was getting the "Settings" tab, but now it's heading to "Dashboard" right away after the forced update.

**Comment by githubsaturn** [comment]
"JsonWebTokenError: jwt must be provided" is probably due to a temporary frontend error. Typically just force refreshing the page / logging out and in again would resolve the issue. `docker service update captain-captain --force` has no negative impact. It's equivalent of rebooting your machine.

**Comment by ylluminate** [comment]
Interesting and strange. This happened for three of us with different browsers and even in Incognito in Chrome/Brave.

**Comment by ylluminate** [comment]
Yes.

**Comment by ylluminate** [comment]
Sure thing - it was quite a panic situation since we have several apps in production and when we hopped in to check some logs on an app that needed some debug work, this popped up. Quite a panic since we didn't know how / if it would affect deployed apps.

One thought that really drove us a bit nutty: it would be nice if the logs were named with some other identifying feature vs a long app ID from Docker. For example, the normally suggested method for tailing a log (eg, `docker service logs srv-captain--app-name --since 96h`) is less useful when hunting for a precise occurrence of a problem from several hours or days before. I ended up finding a production.log, it appears, but it was only from the same day:
`/var/lib/docker/containers/437980eb37372d07c50f447cf35d5d28ab1e99bfc85fb767de0b9550d22242c4/437980eb37372d07c50f447cf35d5d28ab1e99bfc85fb767de0b9550d22242c4-json.log`

1. is it possible to lengthen log preservation times to days, weeks, or months?
2. could we please have an app + filename pre or postfix on the filename so as to identify things a little easier?
3. if none of this is possible, what would be the preferred / allowed way to dump logs into a log server?

**Comment by githubsaturn** [comment]
1- Yes, you'll have to run `docker service update --log-driver.......` , read docker docs for the details.
2- Again, this is managed by Docker, not CapRover.
3- Best way for logs is to handle them properly and have them shipped elsewhere such as logzio or datadog.

**Comment by ylluminate** [comment]
Thanks so much - this is exactly what we'll do re: #3. I have been looking for a good replacement for log tracking over the years, but keep hitting walls with various services. I've desired to find a good open source option that we can extend, but again no real good options seem to be out there.
