### ISSUE TITLE
Fail to install CapRover at step 1

### ISSUE THREAD

**Issue by damywise** [caprover/caprover#1387]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I cannot install CapRover with the guide here https://caprover.com/docs/get-started.html#step-1-caprover-installation.
It says:
```
Unable to find image 'caprover/caprover:latest' locally
docker: Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "? <html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n".
See 'docker run --help'.
```
Steps to reproduce the problem:
1. Fresh install Ubuntu 18
2. Install Docker
3. docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
4. Error

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
```
Linux MyServer 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:           985M        134M        252M        732K        597M        680M
Swap:            0B          0B          0B
```

**Comment by Seeker14491** [comment]
Looks like the `docker run` command is failing before CapRover even starts, so I don't think it's a CapRover issue. Are you able to run other docker containers, for example the hello world container?

```
docker run hello-world
```

If that command works, can you try running the caprover command again? Maybe it was a temporary network issue.

**Comment by damywise** [comment]
I've finally fixed it by simply restarting the server.
Silly mistake
