### ISSUE TITLE
SSL with ACME via DNS Validation ?

### ISSUE THREAD

**Issue by JOduMonT** [caprover/caprover#1390]
Hi;

I saw this : https://caprover.com/docs/certbot-config.html
and search (probably badly) for SSL via DNS on this repo and on the website without concrete result.

My ISP, block the port 80 but allow the port 443, it is possible to query an SSL via DNS Validation ?

**Comment by githubsaturn** [comment]
Short answer: No, they are not supported. 

DNS validations are generally vendor specific and CapRover is built for typical use cases where everything is being vendor agnostic. Also, if your port 80 is blocked, then you can't access CapRover from outside world anyways, in that case, there is little to no value in adding certs.
