### ISSUE TITLE
[Question] - Single capover instance for multiple customers' servers

### ISSUE THREAD

**Issue by pianetarosso** [caprover/caprover#1391]
Hi, we have developed a product composed by 3 microservices interacting with a mongodb, redis and minio.
Currently we are looking how to simplify the installation and management on customers machines.

I've seen this [issue](https://github.com/caprover/caprover/issues/634) where is stated that I can 'force' the installation node. 

Managing everything with a single caprover instance, I thought to do this:
- Add the customer's server as a node 
- Install all the microservices, mongodb, redis  and minio
- Move the apps to the customer's node
 
This will leave all the traffic passing thought our machine, but
- The customer will not have access to our source code, but only to the build 
- We will have more control on the deploy process, and simpler management of env variables
- The domain is not a problem, and can be managed by us

What I'm asking is:
- Do you think it's  a feasible idea?
- What wil happen if the customer's node goes down?
- I've seen that socket connection is supported, there can be issues routing it to another node?

Thank you

**Comment by githubsaturn** [comment]
> Do you think it's a feasible idea?

Yes. But it's not a great design. Clusters aren't meant to used for deployment management and access control. 

> What wil happen if the customer's node goes down?

Their apps stop working. As long as you lock them down to that particular node, they won't get recreated on any other nodes.

> I've seen that socket connection is supported, there can be issues routing it to another node?

Sockets across multiple nodes shouldn't be an issue.
