### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by CDarwin7** [caprover/caprover#1394]
I have a fresh install of Caprover via Digital Ocean Marketplace. In Caprover installed Wordpress one click app, with the MarialSQL database. All the while accepting the default setting.

Upon Launching Wordress admin for the first time, I get this PHP Update Recommended 

Your site is running an insecure version of PHP (7.2.12), which should be updated.

I have read all the link it gives me but its more about why I should upgrade for security reasons, not how,

So how do I update PHP to the latest version, or at least the recommended version to avoid the above error, from Wordpress installed via Caprover installed via DigitalOcean?

**Comment by githubsaturn** [comment]
CapRover is simply a wrapper around Docker. When you're installing WordPress, you can pick a newer version other than the default version. 

![image](https://user-images.githubusercontent.com/10582082/165856828-6a9f79d7-77ea-440d-b506-563965151995.png)

**Comment by githubsaturn** [comment]
Post deployment, you can deploy a newer version, by navigating to deployment tab, and deploy a newer version.
