### ISSUE TITLE
I deployed Seatable app but can't make it work with HTTPS

### ISSUE THREAD

**Issue by galacoder** [caprover/caprover#1396]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hi there,

I deployed Seatable app and everything is working just fine till I tried to enable HTTPS. While clicking on a base, it keeps loading without showing anything. But when I switched back to HTTP, it worked again. 

I tried many ways but I couldn't make it work. Please advise!

I am looking forward to hearing from you soon. 
Best Regards,
Sang.

**Comment by githubsaturn** [comment]
See https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md
