### ISSUE TITLE
[Question] Mitigating High Disk Usage?

### ISSUE THREAD

**Issue by FxllenCode** [caprover/caprover#1397]
Hi there!

We've recently noticed a **significant** spike in disk usage in our Caprover Server, with today reaching 100% system disk usage. We ran a simple `docker image prune --all`, however this only removed 9.76gb from our system (50gb storage). None of our containers should be using this, but we have an idea what it could be: we added a self-hosted registry accidently, then removed it. When we ran the Disk Cleanup tool, it did not remove these images.

Few questions:

1. How can we delete all images in the self-hosted registry we made?
2. How can we disable the saving of past versions of our application?
3. Any other generic tips for saving system storage?
Thanks!

**Comment by githubsaturn** [comment]
Self hosted registry resides in `/captain/data/registry` . You can remove all content in this directory.
