### ISSUE TITLE
[Deployment Issue] CAPOVER CRASH SERVER EVERY TIME I DEPLOYED MY APP

### ISSUE THREAD

**Issue by Trung229** [caprover/caprover#1399]
Hi everyone,

I got an error, it's caprover it will automatically crash my server when I deploy my application to the server, as shown below

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/52306399/165240565-0e81c5f2-8463-4be8-a8e9-eaa8c6220c00.png">

I research, when I saw [it](https://caprover.com/docs/troubleshooting.html) that asked me to log caprover on server, but I didn't see any error message on this

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52306399/165241101-17e1f482-327f-40ba-b504-7f79c265221b.png">

I have researched for more days but still can't find a solution, hope everyone can help me

Thank you,

Trung

**Comment by githubsaturn** [comment]
Crashes during build time are most likely due to out of memory server crash. Are you monitoring your ram/cpu usage during the build process?

**Comment by Trung229** [comment]
Hi @githubsaturn, 

Thanks for your reply

I checked my monitoring app captain, but my space is still free 60 mb and my CPU is ok, 

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/52306399/165442434-77168972-3ac5-40ad-b9ef-9d0b1b4f2617.png">

**Comment by githubsaturn** [comment]
This is it. 60mb of free is not nearly enough to keep the OS happy. A 1GB machine is mostly suitable for testing and very tiny applications. Either move to a machine with 2-4gb of RAM, or move your build process to a 3rd party build CI/CD. Read more here:
https://caprover.com/docs/ci-cd-integration.html

**Comment by Trung229** [comment]
ok, now I  understand why my app cant deploy on server

Thank you
