### ISSUE TITLE
[Deployment Issue] Invalid SSL certificate for www.domain.com through Cloudfare

### ISSUE THREAD

**Issue by Ipan1988** [caprover/caprover#1406]
Hello.

I've been trying to deploy Wordpress with CapRover. It worked fine until I tried to use Cloudfare.

I had to change to a shallow root domain because you have to pay if you need certificates for deeper domains.

https://mysite-wordpress.domain.com and https://domain.com work fine.

My issue is that I get an error 526 (invalid SSL certificate) for www.domain.com. If I put Cloudfare SSL/TLS encryption back to Full I get the "Nothing here yet" page from CapRover.

These are my settings in Cloudfare under DNS (have also tried with Proxy turned off)

![image](https://user-images.githubusercontent.com/50809657/166170748-6d2f42f3-6929-4a4b-b341-dd52b538dece.png)

And these are under Edge Certificates

![image](https://user-images.githubusercontent.com/50809657/166170823-d749c8af-8b6a-4414-8a58-a243f7705266.png)

And here are the CapRover settings for the app. It is not possible to add www.domain.com, only domain.com

![image](https://user-images.githubusercontent.com/50809657/166171011-bd513c13-db8e-4530-812e-1aabfafb8420.png)

I think the issue is that it is not possible to add www.domain.com on CapRover because of this error "1104 : Domain name is not accepted. Custom domain cannot be subdomain of root domain." but does this mean that if I use shallow root domain it is not possible to get HTTPS for www?

Can anyone help me please?

**Comment by githubsaturn** [comment]
As you have noticed, this is a cloudflare issues. Your HTTPs must either be managed by CapRover, or Cloudflare, it is not straightforward to use both systems to manage your SSL. There is a way to do that, but it's flaky and it's not officially supported.

It is explicitly called out in the docs: https://caprover.com/docs/get-started#step-2-connect-root-domain

![image](https://user-images.githubusercontent.com/10582082/166243013-a20ab56b-2e44-4afa-88dd-998e3d861e3b.png)
