### ISSUE TITLE
[Deployment Issue] Hedgedoc not allowing sign in after enabling https

### ISSUE THREAD

**Issue by 9j7axvsLuF** [caprover/caprover#1408]
After enabling https on my HedgeDoc deployment (one-click app), I can no longer sign in or register. When I inspect the page I can see the following errors (I just hid my domain name):

> Refused to set the document's base URI to '[mydomain]' because it violates the following Content Security Policy directive: "base-uri 'self'".
> Refused to load manifest from '[mydomain]/icons/site.webmanifest' because it violates the following Content Security Policy directive: "manifest-src 'self'".
> Refused to send form data to '[mydomain]/login' because it violates the following Content Security Policy directive: "form-action 'self'".

As well as warnings about mixed contents, such as:

> Mixed Content: The page at '[mydomain]' was loaded over HTTPS, but requested an insecure element '[mydomain]/banner/banner_vertical_color.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by githubsaturn** [comment]
Similar to https://github.com/caprover/caprover/issues/1407

Please file an issue with the app maintainer.
