### ISSUE TITLE
Can't run install on ARM processor

### ISSUE THREAD

**Issue by aemadrid-twx** [caprover/caprover#1410]
When trying to install I get this error:

```shell
$ uname -a && lsb_release -a && free -h
Linux node.example.com 5.11.0-1028-oracle #31~20.04.1-Ubuntu SMP Wed Jan 26 14:20:52 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
              total        used        free      shared  buff/cache   available
Mem:           22Gi       368Mi        14Gi       4.0Mi       7.4Gi        21Gi
Swap:            0B          0B          0B
```

```shell
$ docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html





 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
   Total RAM 24107 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
May 5th 2022, 11:44:31.497 pm    Fresh installation!
May 5th 2022, 11:44:31.499 pm    Starting swarm at 1.2.3.4:2377
Installation failed.
Error: (HTTP code 500) unexpected - --live-restore daemon configuration is incompatible with swarm mode
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  reason: undefined,
  statusCode: 500,
  json: {
    message: '--live-restore daemon configuration is incompatible with swarm mode'
  }
}
```

Not sure what to do in this situation. I've googled the `--live-restore daemon configuration is incompatible with swarm mode` error but so far have not found how to fix it in Ubuntu. Any suggestions?

**Comment by maietta** [comment]
This stands out:

******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code

I tried to pull the code and build the project on ARM, but I ran into some other issues that prevent me from testing this for you at this time.

**Comment by githubsaturn** [comment]
That message is old and has to be removed. CapRover is now compiled for all arch types (see below).

But this error has nothing to do with CapRover. Your docker swarm installation is using `--live-restore` flag. @aemadrid-twx - how did you install Docker? Did you just follow the standard guide?

There are multiple ways to enable `live-restore` flag, so you'll have to know what you did in order to reverse it.
https://github.com/splunk/docker/blob/master/docs/admin/live-restore.md


![image](https://user-images.githubusercontent.com/10582082/167054843-a95fcb58-f91c-4fa8-bf57-2ba92b3809fe.png)

**Comment by maietta** [comment]
That's right, I forgot those images are built! Thanks @githubsaturn for pointing this out. Hopefully @aemadrid-twx will find them useful.

**Comment by drmrbrewer** [comment]
@githubsaturn re the message:

> ******* Warning ******* Default CapRover is compiled for X86 CPU. To use CapRover on 
> other CPUs you can build from the source code

you wrote:

> That message is old and has to be removed.

FYI, this message is still there:

![image](https://github.com/caprover/caprover/assets/9009792/36a8d7f6-15c5-496d-bead-41d298b70167)

**Comment by githubsaturn** [comment]
Thanks! Removed.

**Comment by khromov** [comment]
@githubsaturn Still got this message when Installing CapRover today on arm64:

```bash
 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
   Total RAM 3999 MB
```

**Comment by githubsaturn** [comment]
We haven't cut an official release since the removal was committed. It's a benign message thought, feel free to ignore.
