### ISSUE TITLE
[Question] Varnish Cache [Digital Ocean]

### ISSUE THREAD

**Issue by yashiel** [caprover/caprover#1413]
How and what is the proper way to use caprover with varnish cache, im using digitalocean droplets.

**Comment by githubsaturn** [comment]
CapRover uses nginx to talk to the containers. If you want to use Varnish, you'll have to manually edit the nginx configurations for the apps and have them being pass through Varnish. 

![image](https://user-images.githubusercontent.com/10582082/167965432-6df177b3-690b-4c59-8ceb-dbb3949ad7c5.png)
