### ISSUE TITLE
[Question] How do I deploy and (repeatedly) run a worker application that is not a web application?

### ISSUE THREAD

**Issue by kincjf** [caprover/caprover#1414]
How do I deploy and (repeatedly) run a worker application that is not a web application?

I am trying to develop a function that reads data from mongodb with nodejs and periodically transfers it to a spreadsheet after ETL.

The developed function will be scheduled run by the operator (airflow, etc.) periodically. So, we plan to develop the code so that it works once and then terminates when it is executed rather than as a webapp, and we plan to deploy it to caprover.

- How to deploy and (repeatedly) run a worker application that is not a web application?
- If worker app deployment and repeated execution are possible, is there a way to restart the app (docker container) from outside the caprover (cli, api, etc.) after completing one execution?
- What state is maintained when worker app execution is completed? In the case of docker, I know that it is in the stop state by default.
- If repeated execution of the worker app is not possible, can I just deploy the first app in caprover and re-execute it with the docker exec or restart command directly in the docker container created by caprover from the second execution?

**Comment by githubsaturn** [comment]
CapRover uses Docker Swarm. Docker Swarm services are long running applications, not just web apps. You have multiple options for this:

1- Create a Docker image whose main process  just waits indefinitely, and you can run sub processes in it. This is in fact how CapRover runs Certbot image under the hood: https://github.com/caprover/certbot-sleeping/blob/master/Dockerfile#L3

2- Although (1) is easy, but it's not the best if you need to pass in some information to your worker. The best way is to create a thin web application that takes the input from the user, and runs a child process with the provided input.
