### ISSUE TITLE
[Question] How can I enable sticky sessions in my app?

### ISSUE THREAD

**Issue by glacasa** [caprover/caprover#1415]
My application needs sticky session to work correctly when I have more than one instance, but I didn't find a way to enable it in Caprover.
Is it possible to enable sticky sessions in a Caprover app ? how can I enable it ?

I found the issue #379, but it seems to be more about websockets than sticky sessions

**Comment by mxdpeep** [comment]
better use Redis and map your sessions to use this KV store

**Comment by githubsaturn** [comment]
CapRover is purely the deployment helper. What you need is sticky sessions using Nginx and Docker swarm, see here for example: 
https://stackoverflow.com/a/45357951

TLDR: it's not easy to do so. I suggest the solution proposed by @mxdpeep

**Comment by mxdpeep** [comment]
thanx for mentioning that

using Redis for session management is just two lines in php.ini (you can
map a ro volume containing the ini changes into your docker image, same way
you can alter anything in the php.ini file like post max size or memory
constraints)

PHP is battle ready for using Redis as session handler and you will find it
easy to setup and use across many instances
Filip Oščádal 🍀📱

**Comment by mxdpeep** [comment]
BTW I don't know anything about the Blazor app, just FYI

Filip Oščádal 🍀📱
