### ISSUE TITLE
High resource consumption[Question]

### ISSUE THREAD

**Issue by webma5ter23** [caprover/caprover#1416]
![WhatsApp Image 2022-05-10 at 9 12 18 PM](https://user-images.githubusercontent.com/41419364/167744508-f890a4a1-db9d-4887-ab94-24c464ead0ce.jpeg)

Hello. I'm just learning how to use CapRover and I love it but in my tests with just a nearly empty WordPress site and MySQL and MariaDB applications it's consuming a lot of CPU, you can see it in the screenshot of an email I got from DigitalOcean.

The installation is on a Basic Premium INTEL server - 1vCPU - 2GB RAM - 2TB transfer

DigitalOcean marketplace image was used Ubuntu 1804 was installed

I would like to solve this since the idea is to add more applications but if it consumes too much it is impossible to pay for a more expensive server.

Please tell me if CapRover is ready to manage many applications or is it just for a test environment?

Regards

**Comment by githubsaturn** [comment]
Why do you think that it's CapRover that is eating up your CPU? Have you confirmed this via `htop` or such?

You can checkout the demo instance below. It's a 1 vCPU and 1GB machine and it barely has 5% of CPU usage. 

URL: https://captain.server.demo.caprover.com
password: `captain42`

**Comment by webma5ter23** [comment]
I don't understand why they sent me that email. The RAM memory is half with 2GB, the server has nothing else.

I attach some images

![Captura de pantalla 2022-05-11 032427](https://user-images.githubusercontent.com/41419364/167783021-20e6ef8c-954a-4ace-8abf-a6db48029e18.png)
![Captura de pantalla 2022-05-11 032554](https://user-images.githubusercontent.com/41419364/167783023-bfd5ce83-bb57-4ebe-8bb2-e33a972bb2ca.png)
![Captura de pantalla 2022-05-11 032753](https://user-images.githubusercontent.com/41419364/167783027-543b275a-ce71-48c6-9af2-bbe8f5ba845a.png)

**Comment by githubsaturn** [comment]
Yea these look normal as you can see. It's not concerning at all. Probably an error on DigitalOcean that they sent you that email.

Or it could be that you were deploying something or a background update was happening. During these processes the CPU could reach 95%+. But they should be temporary. You can avoid deployment time bottleneck by using a CI/CD platform: https://caprover.com/docs/ci-cd-integration.html
