### ISSUE TITLE
Is it possible to edit Caprover code?

### ISSUE THREAD

**Issue by Kirby-Peter** [caprover/caprover#1417]
Is it possible to edit Caprover code without it resetting after you try to update it on Docker?

When I try to update it it just resets to default by itself.

**Comment by githubsaturn** [comment]
CapRover is a Docker image. Changes made in Docker images are transient. Once restarted, the changes are gone.

**Comment by githubsaturn** [comment]
If you want to make a new change, you'll have to make a change and then build a new docker image.

**Comment by Kirby-Peter** [comment]
The new image pulls from the repo automatically and my changes are then deleted though

**Comment by githubsaturn** [comment]
You need to update this: https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L18
