### ISSUE TITLE
[Question] Creating git repository and deploying one-click-apps

### ISSUE THREAD

**Issue by ispmarin** [caprover/caprover#1421]
Hi all, 

How can I create a git repository with file definitions for one-click-apps already provided by caprover, so I can redeploy it in the future? For example, I deployed Ghost, Bitwarden and Joplin using the web frontend, and now I want to create a repository so if I decide to add a new one-click-app, I can copy/create/edit a new file, commit to this repo, and this one-click-app gets deployed on my caprover instance?

Note that I'm not trying to do this for my own Dockerfiles or apps, but only to create a reproducible way to deploying a Caprover instance and deploying the applications inside using git. Thanks!

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps#build-your-own-one-click-app-repository

you can create your own one click app repo.
