### ISSUE TITLE
Setup Google Container Registry / Artifact Registry for local cluster setup.

### ISSUE THREAD

**Issue by jogiji** [caprover/caprover#1425]
@olragon what steps did you take while configuring remote registry in caprover setup... essentially i am trying to do a clister setup on a local environment and i am trying to setup google container registry... i was able login via docker commandline.. but when entering the values in caprover setup on dashboard..it is not able to logon.

_Originally posted by @jogiji in https://github.com/caprover/caprover/issues/1171#issuecomment-1128416668_

**Comment by jogiji** [comment]
Nevermind i managed to get it done.. turns out that Base64 of service account file was using LF to break the long bas64 string.. I tried replacing the LF with nothing so as to form a continuous string and it worked..

FYI I followed this instruction :  https://cloud.google.com/artifact-registry/docs/docker/authentication?hl=en#json-key 

I converted the service account json keyfile into base64 and used that as password and login as "_json_key_base64"

**Comment by mashraf92** [comment]
Hey @jogiji Can you please share the steps you did are working for GCP Artifact registry as well ? I tried to remove the LF from the base64 but still not working giving error
