### ISSUE TITLE
[Question] Cluster

### ISSUE THREAD

**Issue by Tam2** [caprover/caprover#1427]
I've recently created a Caprover Cluster and everything seems to be working as expected

A few questions:

- Is there a quick and easy way to 'Rebuild and redeploy' all applications so the images get pushed to remote registry and the load is split between the nodes, or do we just manually push each app?
- Is there a way to tell which node the app is running on (or nodes if split)
- (this might be a docker question) when deploying and a node is picked, does it take into account cpu/ram usage on the node before picking a node

**Comment by githubsaturn** [comment]
> Is there a quick and easy way to 'Rebuild and redeploy' all applications so the images get pushed to remote registry and the load is split between the nodes, or do we just manually push each app?

I assume you first deployed some apps, then decided to make it a cluster? Yea you shouldn't be doing this. You should first set up your cluster then start deploying apps. In your case, you'll have manually redeploy all apps.


> I've recently created a Caprover Cluster and everything seems to be working as expected

```
docker service ps srv-captain--appname
```

> (this might be a docker question) when deploying and a node is picked, does it take into account cpu/ram usage on the node before picking a node

https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/
