### ISSUE TITLE
Unable to connect mongodb from my app using the "srv-captain--onprem-db" connection string [Deployment Issue]

### ISSUE THREAD

**Issue by jogiji** [caprover/caprover#1429]
I am trying to deploy my NodeJs app using caprover on local cluster. 
So far I am able to deploy mongodb one click app and mongo express and make them work together using the following address of mongodb `"srv-captain--onprem-db".`

I am also able to connect my app when running on my local machine to the mongodb hosted in caprover via this url : `"mongodb://user:pass@srv-captain--onprem-db:27017/gpmicroservices?authSource=admin"`

But when I deploy the same app using Caprover it is not able to connect to the database, I get the following error 

`error: getaddrinfo ENOTFOUND srv-captain--onprem-db {"reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"stale":false,"type":"Unknown"}}`

Fyi My main leader node info is this : 
```
Linux leader 5.10.103-meson64 #trunk.0002 SMP PREEMPT Thu Mar 3 10:28:27 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       874Mi       1.4Gi        10Mi       1.5Gi       2.7Gi
Swap:         1.8Gi       0.0Ki       1.8Gi
```
other devices on cluster are also of same type.

my captain-definition:

```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }

```

my dockerfile : 

```
FROM node:lts
WORKDIR /usr/src/app
ENV NODE_ENV=devdocker
COPY .npmrc .npmrc
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3030
RUN npm run start
```

I don't have any local DNS server running in my LAN so I have modified the hosts file on my Windows machine to connect to Caprover.

**Comment by githubsaturn** [comment]
> But when I deploy the same app using Caprover it is not able to connect to the database, I get the following error
error: getaddrinfo ENOTFOUND srv-captain--onprem-db {"reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"stale":false,"type":"Unknown"}}

1- Is your application and your mongodb on the same instance?
2- Are you trying to connect to mongodb during the build time or runtime?
3- what's the output of `docker service ls` ?

**Comment by jogiji** [comment]
@githubsaturn 

> > But when I deploy the same app using Caprover it is not able to connect to the database, I get the following error
> > error: getaddrinfo ENOTFOUND srv-captain--onprem-db {"reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"stale":false,"type":"Unknown"}}
> 
> 1- Is your application and your mongodb on the same instance? 2- Are you trying to connect to mongodb during the build time or runtime? 3- what's the output of `docker service ls` ?

1 - Problem is my app is unable to run in Caprover.
2 - It tries to connect at runtime.
3 - Output is  : 

```
ID             NAME                         MODE         REPLICAS   IMAGE                                                                    PORTS
zb3vgbn2lwse   captain-captain              replicated   1/1        caprover/caprover:1.10.1
tqgjqoyo9cz4   captain-certbot              replicated   1/1        caprover/certbot-sleeping:v1.6.0
mbnik5417b5l   captain-nginx                replicated   1/1        nginx:1
i4y26968yo8c   srv-captain--example-mongo   replicated   1/1        mongo-express:0.54
l82th0u9vu7p   srv-captain--onprem-api      replicated   1/1        asia-docker.pkg.dev/getparking-development/gp/img-captain-onprem-api:0   *:3030->3030/tcp, *:3030->3030/udp
4x4n5yahg1bg   srv-captain--onprem-db       replicated   1/1        mongo:4.4.14-focal                                                       *:27017->27017/tcp, *:27017->27017/udp
```

**Comment by githubsaturn** [comment]
I assume the app you're talking about is `srv-captain--onprem-api`. In that case, run this:
```
docker exec -it $(docker ps --filter name=srv-captain--onprem-api -q) /bin/sh

# now you are inside "onprem-api" container. Run this:
curl -v http://srv-captain--onprem-db
```

What does `curl` command print?

**Comment by jogiji** [comment]
This is the output:

`root@leader:~# docker exec -it $(docker ps --filter name=srv-captain--onprem-api -q) /bin/sh
/ # curl -v http://srv-captain--onprem-db
*   Trying 10.0.1.9:80...
* connect to 10.0.1.9 port 80 failed: Connection refused
* Failed to connect to srv-captain--onprem-db port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to srv-captain--onprem-db port 80: Connection refused
/ #`

**Comment by githubsaturn** [comment]
Okay, as you can see the DNS was resolved successfully to `10.0.1.9`. CapRover setup and Docker networks are working fine. 
The problem is with your application, you'll have to debug further to figure out what's going on.

**Comment by githubsaturn** [comment]
If you're running out of containers, you can't even connect to the container, unless you have mapped the port. And I see that you've done that. i.e., you've mapped port 27017 of your host to 27017 of your container. 

And I assume you have manually just created a local DNS entry that points `srv-captain--onprem-db` to the IP address of your CapRover server. Is that correct?

**Comment by jogiji** [comment]
> If you're running out of containers, you can't even connect to the container, unless you have mapped the port. And I see that you've done that. i.e., you've mapped port 27017 of your host to 27017 of your container.
> 
> And I assume you have manually just created a local DNS entry that points `srv-captain--onprem-db` to the IP address of your CapRover server. Is that correct?

Yes when connecting from outside I have created local DNS entries in my HOST file .

**Comment by githubsaturn** [comment]
Okay, so that completely bypasses the actual DNS resolution of Docker swarm. 

Try replacing `srv-captain--onprem-db` in your code with `10.0.1.9` and see if it works. If it does, then it means that something off with the DNS resolution of the mongo DB driver that you're using.

**Comment by jogiji** [comment]
> Okay, so that completely bypasses the actual DNS resolution of Docker swarm.
> 
> Try replacing `srv-captain--onprem-db` in your code with `10.0.1.9` and see if it works. If it does, then it means that something is off with the DNS resolution of the mongo DB driver that you're using.

It still doesn't connect. 

```
error: connect EHOSTUNREACH 10.0.1.9:27017 {"reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"stale":false,"type":"Unknown"}}
{"code":1,"message":"The command '/bin/sh -c npm run start' returned a non-zero code: 1"}
The command '/bin/sh -c npm run start' returned a non-zero code: 1
Build has failed!
----------------------
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c npm run start' returned a non-zero code: 1"}
The command '/bin/sh -c npm run start' returned a non-zero code: 1
```

**Comment by githubsaturn** [comment]
Ah... alright! You said you're doing it on runtime! But this is build time!!! You do not have access to local services during build.

**Comment by jogiji** [comment]
Aah ok... so I need to modify this

**Comment by jogiji** [comment]
> Ah... alright! You said you're doing it on runtime! But this is build time!!! You do not have access to local services during build.

Ok I need to fix this.. I hope i get some sample somewhere which allows me to run this at runtime.

**Comment by jogiji** [comment]
@githubsaturn Thank you so much for pointing it out to me.. after looking at the dockerfile I found that i had made a RUN entry at the last, which should be CMD.
