### ISSUE TITLE
Add a new domain

### ISSUE THREAD

**Issue by wilsntn** [caprover/caprover#1430]
Hi guys, i want to put my app to run in http://www.mydomain.com but i cant figure alt how to do that, its currently workin on https://git.caprover.mydomain.me/ and i cant set to just https://mydomain.me .. 

![Captura de tela de 2022-05-23 16-37-23](https://user-images.githubusercontent.com/91102332/169902108-66718ff5-8b56-4262-b8ff-1a3ee073e965.png)

![Captura de tela de 2022-05-23 16-37-34](https://user-images.githubusercontent.com/91102332/169902128-52a4983e-9855-4bad-9f50-1d2c64e6c866.png)

![Captura de tela de 2022-05-23 16-37-44](https://user-images.githubusercontent.com/91102332/169902143-1c9d015a-f452-44bf-9f7e-744ebb4e6eaf.png)

![Captura de tela de 2022-05-23 16-38-02](https://user-images.githubusercontent.com/91102332/169902160-4c3075bb-371b-4f42-b87e-eea37d9379f9.png)

**Comment by githubsaturn** [comment]
Your A record is wrong. You should NOT set it as `ww.easytorrent.me` instead you should just set it as `www`.

It's the "subdomain" not full domain.
