### ISSUE TITLE
AWS ECR

### ISSUE THREAD

**Issue by rubnawazqureshidev** [caprover/caprover#1437]
hi, I am not able to connect the aws ecr container registry, aws ecr do not provide credentails, they authenicate via IAM. how I deploy to caprover server.

**Comment by githubsaturn** [comment]
This is an AWS question, not a CapRover question. Please post in appropriate forum. 

Also looks like they have information here on how to get the password:

https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html

- username: AWS:
- password: get from this command: `aws ecr get-login-password --region region`
