### ISSUE TITLE
nginx will not route requests after restart.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [caprover/caprover#1438]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

After restarting the captain-captain image has dissapeared.

Steps to reproduce the problem:

Install version of caprover from 2018
Update version of caprover to current version in year 2022
Restart your machine
Watch everything implode
Ask nicely in Github issues for someone to help you out

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux localhost 4.4.0-190-generic #220-Ubuntu SMP Fri Aug 28 23:02:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
              total        used        free      shared  buff/cache   available
Mem:           2.0G        773M        297M        6.2M        929M        1.0G
Swap:          2.0G          0B        2.0G

```

```
docker service ps captain-captain --since 60m

root@localhost:~# docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                      NODE                DESIRED STATE       CURRENT STATE             ERROR                                                              PORTS
man5zyccctx1uu234tqh8ykyn   captain-captain.1       caprover/caprover:1.10.1   localhost           Running             Running 7 minutes ago                                                                        
h1gocznisxpxokgw9jm20eqli    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Failed 11 minutes ago     "No such container: captain-captain.1.h1gocznisxpxokgw9jm20eqli"   
lmg1d1puef96h69cugk53lj0n    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Failed 19 minutes ago     "No such container: captain-captain.1.lmg1d1puef96h69cugk53lj0n"   
am8y6aas3ogldxxhyg24ak9jt    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Failed 22 minutes ago     "No such container: captain-captain.1.am8y6aas3ogldxxhyg24ak9jt"   
qck620fextsote97be7pnwl3c    \_ captain-captain.1   caprover/caprover:1.8.0    localhost           Shutdown            Shutdown 22 minutes ago  

```

```
docker service logs captain-captain --since 60m

root@localhost:~# docker service logs captain-captain --since 60m
captain-captain.1.man5zyccctx1@localhost    | Captain Starting ...
captain-captain.1.man5zyccctx1@localhost    | Overriding dockerApiVersion from /captain/data/config-override.json
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.897 pm    Emptying generated and temp folders.
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.902 pm    Ensuring directories are available on host. Started.
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.906 pm    Ensuring directories are available on host. Finished.
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.910 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.915 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.916 pm    Migration not needed, skipping.
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.919 pm    Copying fake certificates...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.922 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.922 pm    Locking NGINX configuration reloading...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.926 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.928 pm    Captain Nginx is already running.. 
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.930 pm    Updating NGINX service...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:35.937 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:40.943 pm    Pruning containers...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:40.944 pm    NGINX is fully set up and working...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:40.951 pm    Captain Certbot is already running.. 
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:40.953 pm    Updating Certbot service...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:40.959 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:41.842 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:45.961 pm    Pruning containers...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:54.848 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:57.853 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:57.857 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:47:58.842 pm    executeCommand Container: captain-certbot certbot renew --non-interactive 
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:48:29.739 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:48:29.739 pm    Locking NGINX configuration reloading...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:48:29.742 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:48:29.742 pm    sendReloadSignal...
captain-captain.1.man5zyccctx1@localhost    | June 4th 2022, 4:48:29.748 pm    Kill HUP Container: 172f3f2b5a9e312d9db4ab372a7583544d7278fc21d10d27c9b7a8869e747bd1

```

**Comment by WriteCodeEveryday** [comment]
Updated my override to docker version to 1.39 and that fixed the captain-captain image issues but the container now stops after 1 minute.


`ID                          NAME                    IMAGE                      NODE                DESIRED STATE       CURRENT STATE                ERROR               PORTS
rbq2wzcr3rxmas85evfl2uakz   captain-captain.1       caprover/caprover:1.10.1   localhost           Running             Running about a minute ago                       
9dvo6hh38teog7l4lbvmvkdod    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Complete 2 minutes ago                           
smbv9svs2ecvg40869bwu2lh6    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Complete 2 minutes ago                           
ki1b9jrwub4eqha6cn67igcz2    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Complete 2 minutes ago                           
zzfx0rlzt2rhnf2k2mm1s5txw    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Complete 2 minutes ago  `

**Comment by WriteCodeEveryday** [comment]
Upgraded to Ubuntu 18.04.6 LTS and the logs show that the 

```
uname -a && lsb_release -a && free -h
```

Linux localhost 4.15.0-180-generic #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           1.9G        843M        199M        7.3M        949M        1.0G
Swap:          2.0G          0B        2.0G

```
docker service ps captain-captain --no-trunc
```

ID                          NAME                    IMAGE                      NODE        DESIRED STATE   CURRENT STATE             ERROR                                                              PORTS
6ivbrqx8azxnnlv1o6ov43ca4   captain-captain.1       caprover/caprover:1.10.1   localhost   Running         Running 3 minutes ago                                                                        
y2h2nivtsmjqx9zntvnzt71rb    \_ captain-captain.1   caprover/caprover:1.10.1   localhost   Shutdown        Failed 3 minutes ago      "No such container: captain-captain.1.y2h2nivtsmjqx9zntvnzt71rb"   
dsgvlwkoyxy1zi84mx6dyd18f    \_ captain-captain.1   caprover/caprover:1.10.1   localhost   Shutdown        Failed 10 minutes ago     "No such container: captain-captain.1.dsgvlwkoyxy1zi84mx6dyd18f"   
ki1b9jrwub4eqha6cn67igcz2    \_ captain-captain.1   caprover/caprover:1.10.1   localhost   Shutdown        Complete 35 minutes ago                                                                      
zzfx0rlzt2rhnf2k2mm1s5txw    \_ captain-captain.1   caprover/caprover:1.10.1   localhost   Shutdown        Complete 35 minutes ago 

```
docker service logs captain-captain --since 60m
```

captain-captain.1.6ivbrqx8azxn@localhost    | Captain Starting ...
captain-captain.1.6ivbrqx8azxn@localhost    | Overriding dockerApiVersion from /captain/data/config-override.json
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.608 pm    Emptying generated and temp folders.
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.641 pm    Ensuring directories are available on host. Started.
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.647 pm    Ensuring directories are available on host. Finished.
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.657 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.669 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.672 pm    Migration not needed, skipping.
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.684 pm    Copying fake certificates...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.693 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.694 pm    Locking NGINX configuration reloading...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.711 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.714 pm    Captain Nginx is already running.. 
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.716 pm    Updating NGINX service...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:23.730 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:28.735 pm    Pruning containers...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:28.737 pm    NGINX is fully set up and working...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:28.742 pm    Captain Certbot is already running.. 
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:28.746 pm    Updating Certbot service...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:32.519 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:34.515 pm    Pruning containers...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:35.522 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:38.527 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:41.531 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:44.535 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:47.537 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:47.539 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:48.659 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:58.664 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:43:59.395 pm    executeCommand Container: captain-certbot certbot renew --non-interactive 
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:44:26.916 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:44:26.917 pm    Locking NGINX configuration reloading...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:44:26.922 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:44:26.922 pm    sendReloadSignal...
captain-captain.1.6ivbrqx8azxn@localhost    | June 4th 2022, 6:44:26.924 pm    Kill HUP Container: 87f5274e8823d2bca689f5245a889b9831d262b446804f9a80e7fad8e4c6342d

**Comment by WriteCodeEveryday** [comment]
So it turns out the containers are still running but routing is dead somehow

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1066583/172023893-64bfa4ff-d98e-4c82-a65d-0a025b82e187.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1066583/172023907-bbed3378-26b6-4027-9624-99fafaf889cb.png">

Not sure what to do here. The containers list includes my own app.

root@localhost:~# docker service ls
ID             NAME                                                MODE         REPLICAS   IMAGE                                                PORTS
4b73jr4qodi2   captain-captain                                     replicated   1/1        caprover/caprover:1.10.1                             *:3000->3000/tcp
92uio0q3cpxk   captain-certbot                                     replicated   1/1        caprover/certbot-sleeping:v1.6.0                     
shb5fs7xoqwl   captain-nginx                                       replicated   1/1        nginx:1                                                                            
ucuxlheyye04   srv-captain--herreratechnologysolutions             replicated   1/1        img-captain-herreratechnologysolutions:2

**Comment by WriteCodeEveryday** [comment]
Additionally all requests for ACME for certbot are failing

captain-nginx.1.ksjdsl66fzsl@localhost    | 3.71.4.13 - - [04/Jun/2022:20:45:18 +0000] "vgsensei.com" "GET /.well-known/acme-challenge/2HYMHQT3m9rST2dVbCwiFJcTzKsM6zqrxq8yD3cNrO8 HTTP/1.1" 404 2401 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
captain-nginx.1.ksjdsl66fzsl@localhost    | 2022/06/04 20:45:18 [error] 21#21: *20 open() "/usr/share/nginx/default/.well-known/acme-challenge/2HYMHQT3m9rST2dVbCwiFJcTzKsM6zqrxq8yD3cNrO8" failed (2: No such file or directory), client: 3.71.4.13, server: _, request: "GET /.well-known/acme-challenge/2HYMHQT3m9rST2dVbCwiFJcTzKsM6zqrxq8yD3cNrO8 HTTP/1.1", host: "vgsensei.com"

**Comment by githubsaturn** [comment]
Is this closed? Did you figure out what caused it?

**Comment by WriteCodeEveryday** [comment]
I'm reopening after fully reinstalling @githubsaturn 

It looks like this is pretty toasty after upgrading docker and ubuntu.

 Ubuntu is now at 18.04 and Docker is at 18.06.2

**Comment by WriteCodeEveryday** [comment]
root@localhost:/# uname -a && lsb_release -a && free -h
Linux localhost 4.15.0-180-generic #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           1.9G        224M        128M        6.9M        1.6G        1.5G
Swap:          2.0G        2.3M        2.0G

root@localhost:/# docker -v
Docker version 18.06.2-ce, build 6d37f41

root@localhost:/# docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                      NODE                DESIRED STATE       CURRENT STATE          ERROR               PORTS
qu7emdnoafy232zyau1dxy3vl   captain-captain.1       caprover/caprover:1.10.1   localhost           Running             Running 3 hours ago                        *:3000->3000/tcp
u8qg4828n3cmqmra4ofolzf8z    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Shutdown 3 hours ago                       
gtho0ro3k8oa2ge6y5jhndv90    \_ captain-captain.1   caprover/caprover:1.10.1   localhost           Shutdown            Shutdown 3 hours ago            
           
root@localhost:/# docker service logs captain-nginx --since 60m
captain-nginx.1.wjkrm88hil2f@localhost    | 104.59.XXX.XXX- - [05/Jun/2022:01:54:22 +0000] "captain.hosting.herreratechnologysolutions.com" "GET / HTTP/1.1" 200 2401 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36" "-"

I'm seriously stumped here but whatever happened, it's completely non-recoverable. 
Requests arrive at nginx but never get routed to the dashboard.

**Comment by githubsaturn** [comment]
Run these commands and copy the output here.
```
cat /captain/data/config-captain.json | grep public

cat /captain/generated/nginx/conf.d/captain.conf | grep server_name

docker exec -it $(docker ps --filter name=captain-nginx -q) curl -v srv-captain--herreratechnologysolutions
```

**Comment by WriteCodeEveryday** [comment]
root@localhost:~# cat /captain/data/config-captain.json | grep public

No output

root@localhost:~# cat /captain/data/config-captain.json
{
	"namespace": "captain",
	"nginxBaseConfig": "",
	"nginxCaptainConfig": ""
}

root@localhost:~# cat /captain/generated/nginx/conf.d/captain.conf | grep server_name

No output

root@localhost:~# cat /captain/generated/nginx/conf.d/captain.conf

No output

root@localhost:~# docker exec -it $(docker ps --filter name=captain-nginx -q) curl -v srv-captain--herreratechnologysolutions

* Could not resolve host: srv-captain--herreratechnologysolutions
* Closing connection 0
curl: (6) Could not resolve host: srv-captain--herreratechnologysolutions

It also looks like the app has gone away. 😱 

root@localhost:~# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
om0q2bf79mjb        captain-captain     replicated          1/1                 caprover/caprover:1.10.1           
7y1cj463yamp        captain-certbot     replicated          1/1                 caprover/certbot-sleeping:v1.6.0   
wtmsiwgc3hfc        captain-nginx       replicated          1/1                 nginx:1  

I am fine with a rebuild but would like to export my app list before nuking everything so I can rebuild them all after I reinstall.

**Comment by githubsaturn** [comment]
Alright then, looks like you had a (most likely) a disk corruption issue during your upgrade that resulted in the configs to be deleted.

At this point, you'll have to clean things up and start adding your apps. There is no way to export your app list at this point, because as you can see your config file is completely empty because of the disk issue or other hardware issues.

**Comment by WriteCodeEveryday** [comment]
Okay, that's fine, I'm gonna grab the domains list, recommended steps being[ follow the troubleshooting steps](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain)?

**Comment by githubsaturn** [comment]
Yes, exactly.

**Comment by WriteCodeEveryday** [comment]
Rebuild worked great, thanks for everything as always :)
