### ISSUE TITLE
Just 2 Persistance Questions

### ISSUE THREAD

**Issue by ToS0** [caprover/caprover#1440]
Thanks for this great tool - its a huge help and works great!

1. I had to install a missing service in an app container. Therefore I created  a little script on a persistent volume. But how can I run this install script on each container restart automatically?

2. I guess the better way would be to build a new image on top of the standard app image. But how to let Docker and/or CapRover know about (or use) the new image name?

**Comment by githubsaturn** [comment]
> I had to install a missing service in an app container. Therefore I created a little script on a persistent volume. But how can I run this install script on each container restart automatically?

That's not the right way to do this. You'll have to "extend" the base image, example:
```
FROM mysql:5
RUN apt update && apt install something
```

> I guess the better way would be to build a new image on top of the standard app image. But how to let Docker and/or CapRover know about (or use) the new image name?

That's exactly right! It's the better way. You can directly copy paste the Dockerfile in CapRover UI. Or if you prefer to build it separately, you can copy paste the image name in CapRover UI. `Apps > your-app > Deployment tab > at the bottom` 

![image](https://user-images.githubusercontent.com/10582082/172640961-2d0381c7-4256-4de4-8924-ee514837af13.png)
