### ISSUE TITLE
[Question] How to install in WSL with public ip 

### ISSUE THREAD

**Issue by kgnfth** [caprover/caprover#1442]
Hi, i am running a Windows rdp which has a public ip addr, i have installed wsl with ubuntu 20.04

when i run the setup 
```
docker run -p 80:80 -p 443:443 -p 3000:3000
-v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

i get the following error

```
June 10th 2022, 4:58:53.994 am    Starting swarm at 136.243.153.219:2377
Installation failed.
Error: (HTTP code 400) bad parameter - must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  reason: 'bad parameter',
  statusCode: 400,
  json: {
    message: "must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified"
  }
}
```

![image](https://user-images.githubusercontent.com/73314940/172993356-93812001-a81f-4331-892b-b15c34971910.png)

![image](https://user-images.githubusercontent.com/73314940/172993080-13057118-64b6-42b7-aa6c-128f1feecc22.png)

![image](https://user-images.githubusercontent.com/73314940/172993409-2c53838e-0a05-49b8-8ffe-ecaf7810e28d.png)

**Comment by githubsaturn** [comment]
CapRover just simply uses the public IP address as you can see above. It's probably a docker limitation here with WSL.

Try manually adding the localhost IP address to the installation script via adding this env var:
```
-e "MAIN_NODE_IP_ADDRESS=127.0.0.1" 
```
This might prevent you from using CapRover as a cluster. But it should be okay for a single node mode.

**Comment by kgnfth** [comment]
It works now. 

Thank you soo much.
