### ISSUE TITLE
How do I deploy using github actions[Deployment Issue]

### ISSUE THREAD

**Issue by Smyja** [caprover/caprover#1447]
How do I deploy with github and not gitlab? I've checked everywhere and I can't find any article on it.

**Comment by maietta** [comment]
Hi. I have crafted a version of a Github Action to deploy to Caprover using App Token method.

See https://github.com/PremoWeb/deploy-to-caprover.

I will be available in around 8am PST tomorrow to respond with any assistance you may need to adopt this utility into your deployment strategy.

I really ought to document this Github Action... as it's quite useful.

**Comment by maietta** [comment]
@Smyja Did you figure out the strategy with this yet or do you need further info?

**Comment by Smyja** [comment]
> @Smyja Did you figure out the strategy with this yet or do you need further info?

I need further info. I am trying to deploy a monolithic app,so I need something like heroku prebuild to build the Frontend folder first before starting the backend. I tried following the gitlab guide and your example repository, I couldn't figure out what the registry would be when using github actions.

**Comment by maietta** [comment]
Hi @Smyja,

Take a look at one of my development stacks **deploy.yml** workflow files as an example:

https://github.com/PremoWeb/Vue3-PHP7-Web-Development-Stack/blob/main/.github/workflows/deploy.yml

In my use case, I haven't figured out how to configure Github Actions to build my dist/ directory (my frontend) prior to deployment, so I am stuck having to build and include my dist/ directory prior to pushing to Github. Once I figure this out, I will modify my deploy.yml file to introduce the build step prior to the Deploy-to-caprover action.

On my project repo settings, I added 3 secrets. I keep a APP_NAME secret with the name of my app in Caprover. I then use the Deploy tab for the app and use Method 1 to generate an App token. I then create a new secret for the repo called APP_TOKEN with that hash. Lastly, I keep a organization-wise secret called CAPROVER_SERVER with the hostname of my caprover instance.

The deploy.yml file has a list of files or directories I want to bundle into my deploy.tar file. Modify accordingly for your situation. Also be sure to change your desired deployment branch to "master" or whatever you use. I'm using default of "main".

**Comment by Smyja** [comment]
> Hi @Smyja,
> 
> Take a look at one of my development stacks **deploy.yml** workflow files as an example:
> 
> https://github.com/PremoWeb/Vue3-PHP7-Web-Development-Stack/blob/main/.github/workflows/deploy.yml
> 
> In my use case, I haven't figured out how to configure Github Actions to build my dist/ directory (my frontend) prior to deployment, so I am stuck having to build and include my dist/ directory prior to pushing to Github. Once I figure this out, I will modify my deploy.yml file to introduce the build step prior to the Deploy-to-caprover action.
> 
> On my project repo settings, I added 3 secrets. I keep a APP_NAME secret with the name of my app in Caprover. I then use the Deploy tab for the app and use Method 1 to generate an App token. I then create a new secret for the repo called APP_TOKEN with that hash. Lastly, I keep a organization-wise secret called CAPROVER_SERVER with the hostname of my caprover instance.
> 
> The deploy.yml file has a list of files or directories I want to bundle into my deploy.tar file. Modify accordingly for your situation. Also be sure to change your desired deployment branch to "master" or whatever you use. I'm using default of "main".
> 
> EDIT:
> 
> For reference, I should mention what my caprover-definition file looks like:
> 
> https://github.com/PremoWeb/Vue3-PHP7-Web-Development-Stack/blob/main/captain-definition
> 
> Another Edit:
> 
> The deploy.yml in my example _should have worked_ but NPM spits out an error in my Vue 3 + Vite setup. This is where I got stuck. I've not figured out how to get NPM to build my front end using Github Actions prior to deploying to Caprover.

thanks, while i was able to deploy it. it kept showing "Your app will be here!
Go ahead and deploy your app now! " at the homepage. i have decided to not use caprover and just deploy with ssh. I doubt this is a great usecase for caprover. I am closing the issue. Thank you for taking your time to respond to me.
