### ISSUE TITLE
[Question]: Bump netdata version on server with caprover:1.10.1

### ISSUE THREAD

**Issue by LWJerri** [caprover/caprover#1449]
Hello. Recently I see a version update for netdata, but how to bump the version on the server?

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/pull/1432

The PR is merged recently. Either wait for the next release cycle, you can use the edge image: 
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version
