### ISSUE TITLE
Add existing container in dashboard

### ISSUE THREAD

**Issue by katistix** [caprover/caprover#1450]
So I have a docker container created manually some time ago running on same server as caprover. My question is: Can I add that speciffic container as an app in caprover dashboard? To simply be able to manage it from there. (I also heard about Portainer but don't know very much about it). Thanks!

**Comment by githubsaturn** [comment]
You can't make the docker container appear on CapRover dashboard unless it's created by CapRover. You can use CapRover to create a duplicate version of that container, once you're happy with the result, you can remove the old container.
