### ISSUE TITLE
[QUESTION] - Clarification on how deploy separate PHP and NGINX docker images to make it work

### ISSUE THREAD

**Issue by mrmaad** [caprover/caprover#1462]
Hey! First of all, thank you all for great job regarding CapRover, it's awesome.

My question regards deploying PHP application in a form of docker image. Situation looks like following:

There is an application docker image, containing php-fpm and exposing port 9000 only:
```
FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    unzip

RUN apt-get install -y libzip-dev libpq-dev libxml2-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql \
    && docker-php-ext-install zip xml opcache

COPY docker/prod/php-fpm/php.ini /usr/local/etc/php/conf.d/docker-php-config.ini

EXPOSE 9000
```
this **deploys correctly**, and results in deployment to log "Ready to handle connections". So far, so good.

### The problem
Since CapRover nginx requires image to expose a HTTP port (and not fpm port), I can imagine the solution would be to create another image with nginx in it, with default.conf containing something like this:
```
server {
    listen       80;
    server_name  localhost;
    root /var/www/symfony/public;

    location ~* \.(png|jpg)$ {
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
    }

    error_log /var/log/nginx/symfony_error.log;
    access_log /var/log/nginx/symfony_access.log;
}
```
Unsurprisingly, it's not working and results in 502 errors. I do see however couple of issues with that config.

First, the `root /var/www/symfony/public;` fragment - this relates to the fact, that files from app are mounted normally in my nginx container in my docker-compose, but since files between apps in CapRover aren't shared, this shouldn't work.

Secondly, the `fastcgi_pass php:9000;` line - I am wondering if this shouldn't be something like `fastcgi_pass srv-captain--app_name:9000;` right?

And last question - is that a correct and supported approach to deploy PHP app with NGINX with those two separated? I would rather not combine PHP and NGINX together in one image. I do realize this is rather advanced way, but all I need is general hints how to approach this.

Also - I had a look in your https://github.com/caprover/caprover/blob/master/captain-sample-apps/nginx-php-advanced.tar but it contains a Dockerimage with `"FROM  webdevops/php-nginx:alpine-php5",` - a solution I'd rather not use.

Thanks in advance for any response and again, thank you for your amazing work.

**Comment by githubsaturn** [comment]
Yea definitely using an image with nginx built in is going to be the easiest. 


Generally speaking, you can’t share file content between containers. Hence the “root” section of nginx can’t access the public directory of your php app. The solution is to use persistent docker volumes. But the drawback is that you cannot change the content of those files when you deploy a new image… technically you can, but requires heavy scripting and combining scp and deploy….

**Comment by maietta** [comment]
Hi @mrmaad. I literally have been solving this kind of problem for all my PHP projects with a Vue 3 frontend. 

I literally ran into this issue today as I was needing a PHP 8.1 image with Nginx as the webserver. I already had a 7.3 version but no amount of careful changes I made would work. So i had to start from scratch. You can see my question here: https://github.com/joseluisq/alpine-php-fpm/issues/9#issuecomment-1200484127 as well as my solution. My solution as added to my SDK I use to build websites. No reason not to be using PHP 8.1.8 or higher nowadays.

I actually have a dedicated lightweight SDK for web development and today I added support for PHP 8.1.8 which includes all available PHP packages on Alpine Linux. The Webserver is Nginx. PHP is operating as via FastCGI using FPM-PHP.

The project works like this:

Your frontend code (Vue 3 in this case) lives in the frontend/ directory.
Your backend code lives in the backend/ directory.

Javascript & CSS dependencies are managed via NPM.
PHP dependencies are managed via Composer.

You must have Node + NPM and Composer installed on your machine. You must also have Docker installed as well as Docker Compose.

Clone the project to your PC, then run in one terminal `npm i` and then in another terminal `composer update`.

Now in the first first terminal again, run `npm run dev`. In the second terminal run `docker compose up`.

In a few seconds, you'll have 2 webservers running. You'll have the Vite build system dev server on port 80 where you can see your changes live as you save changes to anything in frontend/. On the second server on port 81, you have PHP running Fat Free Framework (use whatever you want) and those files are from backend/ directory.

All requests to /api/* on the frontend are proxied to port 81 in development mode.

When you are happy with your code, simply commit and push your code back to Github and then you can use a deploy action provided in .github/workflows/deploy.yml to trigger a build for production of your frontend. The frontend code gets in the container as /var/www/html/dist/ while your API or other php code lives in /var/www/html.

Nginx routes all non-static URLs to /index.php and the PHP script will serve your dist/index.html unless the request is for an API route.

It's almost hacky, but clean. Both compiled frontend and backend code live in the same container in production but you can opt to add a new workflow to push your frontend elsewhere, like a CDN, for example.

The SDK template I've put together for a smooth web development experience:

https://github.com/PremoWeb/SDK-Foundation-Vue
