### ISSUE TITLE
[Question] How to add apps outside one-click?

### ISSUE THREAD

**Issue by kannthus** [caprover/caprover#1463]
Hey everyone,

I was curious on how difficult it-is to add apps/services outside the one-click marketplace? I tried looking for documentation on it, but it all got a little confusing. 

If anyone could give a TLDR on how to add something from Docker, that'd be fantastic ❤️

**Comment by githubsaturn** [comment]
Did you read documentation on docker compose on caprover?

**Comment by kannthus** [comment]
> Did you read documentation on docker compose on caprover?

I did yeah, I figured out I could add an app by "create a new app" then deploying via an ImageName, which feels like it isn't the correct way of doing that.

**Comment by githubsaturn** [comment]
That's exactly how you should do it. Either create a new app then deploy with an image name, or create your own one-click app template as explained in the link above.
