### ISSUE TITLE
How do we publish an app on the base domain.

### ISSUE THREAD

**Issue by voiddaek** [caprover/caprover#1464]
On the website we can read:
`From http://localhost:3000 to https://www.awesome.com in seconds`

I might have missed the part in the documentation, but how do we configure the default app ?
How do we actually get to have https://domain.tld and https://www.domain.tld to deliver some content.

When I create an app, it is reachable at  https://app-name.domain.tld. 
How can we make it the default ?
Should I change the nginx config file myself or there is an option to activate or something else?

Also if I create an app called www then I am getting : `1107 : Verification Failed.`

**Comment by maietta** [comment]
You need to setup Caprover so apps are created with the <app-name>.apps.yourdomain.com pattern, then you can go back into any app and assign your yourdomain.com and www.yourdomains.com, for example.

**Comment by voiddaek** [comment]
I am not so sure I understand.
So I am creating an other server.

Root domain is configured : 
`<.wildcard>.apps.domain.tld`
HTTPS is enabled and forced

So I am able to access caprover ui at https://captain.apps.domain.tld

I am creating a new app: main-www
I would like to have this app accesible at https://www.domain.tld or https://domain.tld
and not at https://main-www.apps.domain.tld
In the app settings:
```
Your app is publicly available at:
https://main-www.apps.domain.tld/
```
I am trying to connect a new domain : www.domain.tld
But I am getting `1107 : Verification Failed.`

Is that correct ?

**Comment by maietta** [comment]
1107 failed just means that the DNS hasn't yet been updated. You probably need to wait a while and try again.

I'm sure you'd set an A name record for www.domain.tld (and non-www) to also also point to the IP of your Caprover server, right?

I've been forced to wait more than 24 hours sometimes before I can get a domain assigned to Caprover, depending on the DNS provider used.

**Comment by voiddaek** [comment]
Ignore the previous comment. It works.
FOr some reson I could verify that www.domain.tld was pointing at the right IP using https://mxtoolbox.com/SuperTool.aspx

But it was always failing to connect the new domain. I guess it was cached somewhere.

Anyway thanks for your help @maietta

**Comment by voiddaek** [comment]
Definitely enjoying it. Awesome product.
