### ISSUE TITLE
Captain UI not working. All websites are stop

### ISSUE THREAD

**Issue by jainsumit12** [caprover/caprover#1466]
root@ubuntu:~# docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                      NODE      DESIRED STATE   CURRENT STATE                 ERROR                                                              PORTS
qiprmjf2z7kh3k0b3830pjw86   captain-captain.1       caprover/caprover:1.10.1   ubuntu    Running         Running 18 seconds ago                                                                           *:3000->3000/tcp,*:3000->3000/tcp
27t1ahqegc3hrwj1cbkvrsbx4    \_ captain-captain.1   caprover/caprover:1.10.1   ubuntu    Shutdown        Shutdown about a minute ago                                                                      
inih1ili7a1zdbrj3wbtd51su    \_ captain-captain.1   caprover/caprover:1.10.1   ubuntu    Shutdown        Failed 5 minutes ago          "No such container: captain-captain.1.inih1ili7a1zdbrj3wbtd51su"   
vcaz53prfpn4eywgr0pkyelbq    \_ captain-captain.1   caprover/caprover:1.10.1   ubuntu    Shutdown        Failed 9 minutes ago          "No such container: captain-captain.1.vcaz53prfpn4eywgr0pkyelbq"

**Comment by amankch** [comment]
Did you try to restart it?
