### ISSUE TITLE
My root domain has expired and due to some reasons, I wasn't able to renew it. Now I am not able to access any apps running with this instance. Please help me to make it live again.[Question]

### ISSUE THREAD

**Issue by amankch** [caprover/caprover#1467]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

My root domain has expired and due to some reasons, I wasn't able to renew it. Now I am not able to access any apps running with this instance. Please help me to make it live again.

**Comment by githubsaturn** [comment]
What do you plan to do? Eventually renew the domain or you want to migrate to a different root domain?

**Comment by maietta** [comment]
If you just need temporary access, you can modify your "hosts" file on your local computer to point the captain.apps.yourdomain to your server IP.

On Windows, the location of the hosts file is  c:\Windows\System32\Drivers\etc\hosts, but it must be edited with Administrator privileges. Alternatively on Windows, a handy little utility called HostMan is nice to have if you make changes often,

Add an entry in your hosts would look like this:

123.456.789.0 captain.apps.yourdomain.com

**Comment by amankch** [comment]
> What do you plan to do? Eventually renew the domain or you want to migrate to a different root domain?

Renew, is not possible because it's not available now. Second option, migrate to a different root domain if all the hosted apps will run without any problems.

**Comment by githubsaturn** [comment]
Do what @maietta suggested. That'll get you temporary access to your domain, then from the dashboard you can change the root domain and go from there. 

Important note:
You may have apps that store the base URL or they rely on the previous URLs. Without knowing what apps you host, it's hard to tell if things will break or not. But for example, wordpress stores the site URL directly in their database, so even if you change the root domain from CapRover dashboard, you'll still need to update the wordpress from wordpress settings page.
