### ISSUE TITLE
[Deployment Issue] Proto.io Error

### ISSUE THREAD

**Issue by SOG-web** [caprover/caprover#1469]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

getting this error exec /init: exec format error after deployment

```
uname -a && lsb_release -a && free -h
```

**Comment by githubsaturn** [comment]
This is an app issue, not CapRover. Please post in their forums. 

CapRover is simply a Docker deployment tool. This error is a Docker container startup bug.
