### ISSUE TITLE
[Question] Help with Invoiceninja

### ISSUE THREAD

**Issue by webma5ter23** [caprover/caprover#1471]
I am migrating the application from another server to the server where I have Caprover installed. Invoiceninja was installed correctly, I also imported the database, I just need to replace the "env" file where it has the installation information. I don't see it over SSH or in hidden files, I also installed the Filebrowser app and I can't find its path.

In the installation of the previous server, the file is found inside the path: /data.

- public (folder)
- public-storage (folder)
- storage (folder)
- .dbsetup (file)
- env (file)
 
Where is the "env" file located in Caprover?

I appreciate the help.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/invoiceninja.yml#L95-L97

Currently only `public` and `public-storage` directories are marked as volumes. Please note that one click apps are community maintained. Please feel free to modify if needed.


Also, for `.env` files, generally speaking, you can just paste the content of the file directly under environmental variable panel on CapRover apps config.
