### ISSUE TITLE
Minio in distributed mode

### ISSUE THREAD

**Issue by raiden076** [caprover/caprover#1474]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when {
Nope, you're awesome for creating and maintaining this project but } I find persistent apps through caprover is a bit limiting. 

**Describe the solution you'd like**

A clear and concise description of any alternative solutions or features you've considered:
So, i was thinking, we already have minio as an oneclick apps, which fortunately is capable of distributed file system,
So, when we enable multiple nodes, wouldn't it be possible to enable distributed minio server and serve the docker volumes from there? (Kinda like built in docker registry, for serving images quickly to different pods). That way, we will be able to gather up a relatively big amount of storage for our persistent apps, and also, should be relatively easy to work with persistent storage apps on different nodes,

I am a pretty newb in all of these, and maybe it's childish, but i was just curious 😅
And also is there a way to deploy minio in distributed mode, even if above suggested setup is stupid, it will be helpful to (ab)use the free oracle servers i gathered from my parents' credit cards 😅😂

**Additional context**
Nope

**Comment by raiden076** [comment]
Okay, i was reading about persistent volume and persistent volume claims on kubernetes, but did not find anything to prevent a situation when multiple pods were writing the same file, kind of deadlock in dbs, apart from that when just reading the same file, couldn't find any reason why this shouldn't work. (maybe when one instance is modifying a file, put some lock, so others can't change it (?) Idk,) 

Please do point out where i am wrong.

**Comment by githubsaturn** [comment]
Distributed storage system is not something trivial that can be added to CapRover. Feel free to explore options like Gluster or Ceph. But they won't be added to CapRover core due to complexity.
