### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by gtsorho** [caprover/caprover#1475]
hello, 
so Im a laravel developer and I am new to caprover iv been able to deploy my vueJs SPAs to caprover successfully, same method fails with laravel, please I need your help. Im really stranded .

#caption-definition file
{
 "schemaVersion" :2 ,
 "templateId" :"php/8.0"
}

**Comment by githubsaturn** [comment]
Please see: https://github.com/jackbrycesmith/laravel-caprover-template

Also, your question is a Docker question. Please ask in stackoverflow or other general forums. It's not specific to CapRover.
