### ISSUE TITLE
[Question] connect to one-click mongo-db from local computer

### ISSUE THREAD

**Issue by benoib** [caprover/caprover#1479]
Hello,

I started commenting on a closed issue (222) but I think it is clearer here.  Problem is simple: I would like to access remotely my one-click mongo db container.

I have "my-mongo-app" (one-click Mongo db).

It is said to be accessible here: https://my-mongo-app.server.beyondmatching.com/ on port 80.

But I do not understand what I should do to simply access the app from my local machine.

I tried

- Finding the IP of https://my-mongo-app.server.beyondmatching.com/, and use port 80: mongodb://dbuser:dbpassword@123.123.123.123:80/admin

- Mapping 27017 of my server to 80 of my container.
- Doing both ufw allow 27017/tcp, ufw allow 80
- Use directly https://my-mongo-app.server.beyondmatching.com/ as the host.
- Configure with: 

When I test the connection, it can't even access the server.

I read the documentation but I must be missing a step there, despite my simple usecase.

Thanks :)

**Comment by maietta** [comment]
I hope I am understanding you correct.

You need access to your MongoDB app from outside the Docker Swarm (even if it's a one node swarm).

In Caprover, you've assigned an external port 27017 to the port 80 of your container, but it's my understanding that MongoDB usually uses port 27017 itself, not port 80.

You've correctly noted that you needed to open up the firewall, but you didn't need 80, just 27017/tcp mentioned.

I'm referencing https://www.mongodb.com/docs/manual/reference/default-mongodb-port/ for additional info on ports.

So I think you need to change your port mapping from Server Port of 27017 to match your Container Port which is really 27017.

**Comment by benoib** [comment]
Thanks a lot for the quick answer.

To precise the question:

- I want to access the db from outside, from my local personal computer. The DB is running on a container, on my server.
- i have no issue accessing the db in prod, from inside my server (caprover app to caprover app) 

You solved the issue with the correct forwarding! Thanks a lot!

**Comment by hatemragab** [comment]
Hi I am happy to see this fix you made my day thanks
i wonder if i can connect using ssl to my mongodb 
my url is 
`mongodb+srv://userName:pass@srv-captain--mongo-1.mongo.weexxx.com/ ` This can't be connected 
it says 
`querySrv ENODATA _mongodb._tcp.srv-captain--mongo-1.mongo.weexxx.com
`
but when connect using without ssl it connected
`mongodb://userName:pass@srv-captain--mongo-1.mongo.weexxx.com:27016/`
iam enable the the https and  `Force HTTPS by redirecting all HTTP traffic to HTTPS` has been enabled
