### ISSUE TITLE
[Deployment Issue] I can't deploy Go app !

### ISSUE THREAD

**Issue by devlamine** [caprover/caprover#1481]
**What is the problem?**
I have message error : NGINX 502 Error :/ 
When I debug with docker service logs captain-nginx --since 1m --follow :
I get message : srv-captain--goapp could not be resolved (3: Host not found),

**`captain-definition` file:**
```
{
 "schemaVersion" :2 ,
 "dockerfilePath" : "./Dockerfile"
}
```
**Steps to reproduce the problem:**

I have 3 apps on the server one in php and one for mysql both apps work well I added another app for golang, to test Go I made a simple example:

Dockerfile :
```
FROM golang:1.16-buster AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY *.go ./
RUN go build -o hello

FROM alpine:3.14
WORKDIR /
COPY --from=builder /app/hello /hello
EXPOSE 80
ENTRYPOINT ["./hello"]
```

Main.go

```
package main

import "fmt"

func main() {
    fmt.Println("Hello server !")
}
```
go.mod
```
module helloworld
go 1.19
```

**Server**
```
Linux  5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       731Mi       226Mi        32Mi       2.9Gi       2.8Gi
Swap:          2.8Gi        60Mi       2.8Gi
```

**Comment by maietta** [comment]
What port is your Go app listening to?

You are exposing port 80 in the container, but that doesn't mean your app is actually listening on that port.

**Comment by devlamine** [comment]
I implemented ListenAndServe to create a simple HTTP server for address port :8080 but the error remains.
I used another web app https://github.com/lealoureiro/hello-world-api to be sure and I got the same error.

**Comment by maietta** [comment]
Port 8080 is certainly a different port than 80. Did you assign port 8080 as the container port in your Caprover app?

**Comment by devlamine** [comment]
Oooh @maietta you saved me thank you very much for your help, I thought port 8080 is the same as port 80 👍 👍 👍

**Comment by maietta** [comment]
> Oooh @maietta you saved me thank you very much for your help, I thought port 8080 is the same as port 80 👍 👍 👍

Glad I could help. But please close this issue if you feel it's been resolved.
