### ISSUE TITLE
After my server is having problem with network connection captain is not working

### ISSUE THREAD

**Issue by Panhara28** [caprover/caprover#1482]
I have try to restart the captain 

```
docker service update captain-captain --force
```

but it still not working.
And then I try to curl my website the result: 
![image](https://user-images.githubusercontent.com/20127811/182982558-965f56fe-44f4-4357-9bae-0921188b086f.png)

Is a problem about my network configuration or my server connection ?

**Comment by maietta** [comment]
Can you reach port 80 or 3000?

Is your server by chance in Cambodia, or your connection to the internet?

**Comment by Panhara28** [comment]
> Can you reach your server via SSH?
> 
> Is your server by chance in Cambodia, or is your connection to the internet? If so, I think I know the reason.


My team not changing the public IP 🗡️

**Comment by Panhara28** [comment]
> Can you reach your server via SSH?
> 
> Is your server by chance in Cambodia, or is your connection to the internet? If so, I think I know the reason.

It was another ISP is down

**Comment by maietta** [comment]
If the problem has been resolved, please close the issue. Hopefully you're able to access your server.

Got some major internet activity going on in the region.
