### ISSUE TITLE
I get error when after successfully deploy some of the one-click app

### ISSUE THREAD

**Issue by SOG-web** [caprover/caprover#1483]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I get this error when after successfully deploy some of the one-click app
```exec /usr/local/bin/docker-entrypoint.sh: exec format error``` or ```exec format error```

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
 **install any of the following apps**

- -- commento
- -- coral talk
- -- elastic search
- -- iredmail
- -- mattermost
- -- moodle lms
- -- poste.io
- -- ohmyform

then check the deployment tab of the app, then the logs

**Comment by maietta** [comment]
Which operating system and docker version engine are you running?

Some installation methods of Docker Engine don't work completely as expected, including the "snap" version of Docker on Ubuntu.

According to the "getting started" page in the official docs, the distribution recommended for the least issues would be Ubuntu 18.04 although I have had no issues with Ubuntu 20.04 LTS and Docker's "convenient script" methods:

https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

**Comment by githubsaturn** [comment]
What @maietta  said is completely correct. See these examples:
- https://stackoverflow.com/questions/36544293/docker-run-9-system-error-exec-format-error
- https://bobcares.com/blog/docker-exec-format-error/
- https://stackoverflow.com/questions/72042794/when-creating-pod-it-go-into-crashloopbackoff-logs-show-exec-usr-local-bin-do
- https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error
- https://stackoverflow.com/questions/69100513/running-bash-script-in-entrypoint-exec-user-process-caused-exec-format-error

If you're using one-click apps, it's not possible that they have any errors in the startup script. So most likely you're running these on a platform/CPU architecture that are not supported by these apps (maybe arm?).


Regardless, this is not a CapRover related issue.

**Comment by SOG-web** [comment]
Thanks so much, I will check out my server.
