### ISSUE TITLE
Connexion Notifications

### ISSUE THREAD

**Issue by sandoche** [caprover/caprover#1487]
**Is your feature request related to a problem? Please describe.**
For security reason, I would like to get notified every time someone connects to the caprover admin panel

**Describe the solution you'd like**
I would like to receive an email or a telegram notification when someone logs in to the interface

**Additional context**
Because there is no 2FA it would be the best way to know if the server's password is compromised

**Comment by githubsaturn** [comment]
Duplicate of https://github.com/caprover/caprover/issues/727
