### ISSUE TITLE
[Question] dockerd eating up RAM

### ISSUE THREAD

**Issue by 7aklhz** [caprover/caprover#1488]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
I've noticed that my RAM is slowly but steadily being eaten up. My VPS has a total capacity of 16 GB RAM. When I run docker stats, I see all my containers are using 4GB. The rest is (more or less) used by usr/bin/dockerd (9.9GB). Is there anything I can do to limit usr/bin/dockerd ram usage and specifically limit that it increases in time ?

**Comment by githubsaturn** [comment]
That's really beyond the CapRover control. `dockerd` is the daemon that Docker uses. Try posting your question on StackOverflow or the official repository of Docker: https://github.com/moby/moby/
