### ISSUE TITLE
[Question]: Replace static pages.

### ISSUE THREAD

**Issue by LWJerri** [caprover/caprover#1489]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hello. How I can modify CapROver error pages? I wanna replace main route page and another status code error pages. Thanks.
![image](https://user-images.githubusercontent.com/50290430/184529694-d05cc9fd-49ba-4544-b52e-6f24a85b5634.png)
![image](https://user-images.githubusercontent.com/50290430/184529702-ae346c5a-6147-409c-92d9-bcf4c8178079.png)

**Comment by maietta** [comment]
There is an existing issue already filed. See the answer:

https://github.com/caprover/caprover/issues/1025#issuecomment-781708322
