### ISSUE TITLE
[Deployment Issue] Incompatible supabase postgres docker image on ARM based systems 

### ISSUE THREAD

**Issue by Fractal-Tess** [caprover/caprover#1497]
Hey there,

The `supabase postgres` one-click app is not compatible with the arm platform of processors.
I used the free tier arm servers provided by oracle cloud to get this behavior. 
The exact error is `2022-08-18T04:57:07.252544254Z exec /usr/local/bin/docker-entrypoint.sh: exec format error`.

**Comment by githubsaturn** [comment]
There is nothing we can do, the official repo only has amd64 docker containers
https://hub.docker.com/r/supabase/postgres/tags
