### ISSUE TITLE
[Deployment Issue] Incompatible Filebrowser docker image on ARM based systems 

### ISSUE THREAD

**Issue by Fractal-Tess** [caprover/caprover#1498]
Hey there,

The `Filebrowser` one-click app is not compatible with the arm platform of processors.
I used the free tier arm servers provided by oracle cloud to get this behavior.
The exact error is `/usr/local/bin/docker-entrypoint.sh: exec format error`.

**Comment by githubsaturn** [comment]
The default version only supported amd64, I've updated the default version to now support arm. Make sure you use this version "v2.22.4" or higher.
