### ISSUE TITLE
phpmyadmin not working

### ISSUE THREAD

**Issue by Emeka212** [caprover/caprover#1499]
please I try to install PHPMyAdmin as a one-click0install, but any time I install it says successfully installed but when I open the link I see a diff thing like the img below, please I need help on this.

Thanks in advance

![screencapture-phpmyadmin-caprover-axxellanceblog-ml-2022-08-18-14_38_25](https://user-images.githubusercontent.com/60589175/185408993-95277550-0932-489c-94b4-c54eb4e293ae.png)

**Comment by maietta** [comment]
I just tested a deployment of phpMyAdmin from one-click apps and it installed in seconds, so I know for a fact that the One-Click-App is working exactly as intended.

Just a note: It's critical to use Caprover on a supported OS, using official docker installation methods (not using a package manager), and using a machine with enough ram to support the applications you intend to run. I've tested Caprover to operate correctly in Ubuntu 18.04, 20.04, and 22.04.

Are you by chance using the Safari browser on macOS?

**Comment by Emeka212** [comment]
I am using ubuntu 20.04 with 4vcpu and 24GB ram, and I am using a window pc with google chrome, I don't really know what is going on, any help will be appreciated.

Thanks.

**Comment by Fractal-Tess** [comment]
> I am using ubuntu 20.04 with 4vcpu and 24GB ram, and I am using a window pc with google chrome, I don't really know what is going on, any help will be appreciated.
> 
> Thanks.

Are you on processor?

**Comment by maietta** [comment]
Strange, but okay. You may need to go ahead and collect some information to help in diagnosing the problem.

Please ssh into your server, or from your VPS console in your provider's control panel, run the following and copy/paste the results here for us to review. (As instructed when you created this issue)

`uname -a && lsb_release -a && free -h`

**Comment by Emeka212** [comment]
> Strange, but okay. You may need to go ahead and collect some information to help in diagnosing the problem.
> 
> Please ssh into your server, or from your VPS console in your provider's control panel, run the following and copy/paste the results here for us to review. (As instructed when you created this issue)
> 
> `uname -a && lsb_release -a && free -h`

Okay so I have run the code you said i should tun on my server and this is the out-put below 

```
Linux appwrite 5.15.0-1016-oracle #20-Ubuntu SMP Mon Aug 8 07:08:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:            23Gi       4.8Gi        16Gi       150Mi       2.5Gi        18Gi
Swap:             0B          0B          0B
```

**Comment by maietta** [comment]
Okay, @Emeka212, thank you.

Like @Fractal-Tess pointed out, some applications don't run on other CPU architectures.

Looks like your running aarch64 / ARM64.

I've looked up the One-Click-App to see where the docker image is coming from.

https://hub.docker.com/r/phpmyadmin/phpmyadmin/

Following that rail to get back to the official Github Repo and looking through tickets, I do see this thread:

https://github.com/phpmyadmin/docker/issues/336

Basically, the image provided by phpMyAdmin project doesn't work for people out of the box. Docker provides their own build that appears to work with ARM64 architectures, which you could give a try:

Looking at the source for the One-Click-App, we can copy/paste to deploy from a template method, but with one tiny change mentioned in the issue thread with the solution:

https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/phpmyadmin.yml

Changing line 4 to use phpmyadmin:latest like so:

```
captainVersion: 4
services:
    $$cap_appname:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_ARBITRARY: '1'
            UPLOAD_LIMIT: $$cap_upload_limit
caproverOneClickApp:
    variables:
        - id: $$cap_upload_limit
          label: File size upload limit
          description: It will override the default value for apache and php-fpm inside the container. Default size is 2M
          defaultValue: 2M
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_pma_version
          label: PHP My Admin Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags/
          defaultValue: 5.0.2
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            PhpMyAdmin is the most popular web interface for MySQL & MariaDB. Simply install PhpMyAdmin and then select what database you want to connect to.
            Enter your PhpMyAdmin Configuration parameters and click on next. It will take about a minute for the process to finish.
        end: >-
            PhpMyAdmin is deployed and available as $$cap_appname. 
            Note: Once deployed you can easily change the upload limit file size by modifying the value in the variable in the menu: App Configs>UPLOAD_LIMIT.
            If you need to upload files bigger than 500M you will also need to modify the option: 'client_max_body_size 500m' by clicking in the menu: HTTP Settings>Edit Default Nginx Configurations.
    displayName: phpMyAdmin
    isOfficial: true
    description: phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web
    documentation: Taken from https://hub.docker.com/r/phpmyadmin/phpmyadmin/
```
I was able to successfully deploy phpMyAdmin on my Raspberry Pi 4 device which is an ARM64 device using this method.

You can find the option to **deploy from template** as the last item in the list of One Click Apps. Just paste that YML code into the text area and you'll be presented with a form, then you should be good.

Let us know here if this is the fix for you. We may need to update One-Click-Apps to reflect this change.

**Comment by Emeka212** [comment]
@maietta

Thanks for taking your time to help I really appreciate that, but I want to ask where will i put this text.

inside Caprover or through my ssh connection if so how do I find this file?

thanks.

**Comment by maietta** [comment]
``You can find the option to deploy from template as the last item in the list of One Click Apps. Just paste that YML code into the text area and you'll be presented with a form, then you should be good.``

**Comment by Emeka212** [comment]
yer glad i was able to help on that one way or the other.

The funny part is that not everyone knows about oracle cloud always free trie, it is pretty much the best out there, just waiting till I have enough then I will love to purchase more from them, they are one of the best.

**Comment by githubsaturn** [comment]
Please refrain from opening duplicates: 
https://github.com/caprover/caprover/issues/1504
