### ISSUE TITLE
[Deployment Issue] MySQL on-click app root passowrd

### ISSUE THREAD

**Issue by Fractal-Tess** [caprover/caprover#1500]
Hey there,

Changing the `MYSQL_ROOT_PASSWORD` environment variable of an already running `MySQL` one-click app  *DOES NOT* change the password required for authenticating the root user when connecting to the database. 

I tried this today with a prisma client.

The password of the root user will remain whatever it is set to be when creating the one-click app. Once created, changing that environment variable does not have any effect.

**Comment by githubsaturn** [comment]
It has nothing to do with CapRover. These env vars are only used in the initialization step. If you want to change the password of your database, you can either use command line or an app like `phpmyadmin` 

See this for example https://stackoverflow.com/a/64442155
