### ISSUE TITLE
[Question] Services keep failing and restarting

### ISSUE THREAD

**Issue by Turab** [caprover/caprover#1503]
Hi.

After a server components upgrade, I needed a restart on the Caprover machine and after the restart, all of the services are constantly failing and restarting. How can I resolve?

By the way containers are working but they restart so many times. Even Caprover interface says "Something Bad happened" along with error "1001 : Captain is not ready yet...", all the time in the UI.

![image](https://user-images.githubusercontent.com/1780719/186877501-64a03ed3-41ca-46f2-b684-92d72aee937f.png)

**EDIT**: It seems to be a firewall issue. Checking out this now: https://caprover.com/docs/run-locally.html but it is for fresh new installations. How can we apply this to an existing installation?

**Comment by Turab** [comment]
Notable entries from the error log:

```
Captain health check failed: #1 at captain.apps.elmacik.com.tr
NGINX health check failed: #1

```
There was also this once or twice, now I don't see:

```
Error: Wrapped: Error        Error: connect ETIMEDOUT 111.111.111.111:80
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at Request.emit (events.js:400:28)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.qk7evcgyejvw@localhost.localdomain    |     at ClientRequest.emit (events
```

"111.111.111.111" is actually the server IP which runs Caprover, I just masked it here.

**Comment by githubsaturn** [comment]
The issue is the loopback. There is no one-size-fits-all solution for this. You have to work with your VPS provider to see what the issue is. But CapRover can't connect to the IP address in your logs. Why it is happening is beyond CapRover's control. 

You can turn off the domain verification check temporarily until your VPS provider resolves the firewall issue:

https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107
