### ISSUE TITLE
Can't find phpmyadmin login details

### ISSUE THREAD

**Issue by Emeka212** [caprover/caprover#1504]
Hello,
So I recently install PHPMyAdmin on Caprover and yes, it installs very well.

![screencapture-phpmyadmin-caprover-axxellanceblog-ml-2022-08-26-11_56_00](https://user-images.githubusercontent.com/60589175/186889043-2f9ee976-0bbb-4ec9-a66f-ef5d63a49419.png)

but when I try to log in I realize that I don't have the login details, even in the project app config, I can see any login details, if I specify one it will give me an error msg in PHPMyAdmin

![screencapture-captain-caprover-axxellanceblog-ml-2022-08-26-11_57_43](https://user-images.githubusercontent.com/60589175/186889333-614f30a8-e1f7-4987-85cc-7d04fa1f37f7.png)

Please I need help on how to get the login details, this is the server name, username, and password.
Thanks  in advance.

**Comment by maietta** [comment]
This is not related to Caprover. The phpMyAdmin software can't magically know what server and database you need to access, so you'll need to supply your own.

If you have a database you've deployed via Caprover, either standalone or included, you can reach the server by the srv-captain--your-app-name and then the credentials you might find in your target database's environment variables. For example, if you deployed a WordPress database that includes a database as "bugkillerz-wordpress", you may have a database instance under the name bugkillerz-wordpress-database. You'll need to gather your credentials from that app's environment tab. The database endpoint will also be accessible under the docker service name of srv-captain--wordpress-database. (note the double dashes in the middle of the app service name)

Again, this is all outside the scope of Caprover.
