### ISSUE TITLE
[Deployment Issue] Re-point/Reconnect Apps Removed from Dashboard But Still Running on Server?

### ISSUE THREAD

**Issue by chriskol** [caprover/caprover#1505]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

So I was tinkering with the nginx.conf file and long story short, after rectifying a situation where I could not even connect to caprover, I find myself in a new problem where all my apps are gone from the dashboard.  That said, the apps themselves are still actually running on my server and all the containers and persistent memory volumes remain.

Is there a way I can simply 'reconnect' or repoint the apps to their respective containers/volumes?  It's a bit strange because I thought I lost everything but one of my chat bots is still running.  However, my wordpress sites are all down.

Just trying to make heads or tails of all this before resorting to downloading all my data off the server and recreating everything from scratch and then having to clean up everything afterwards.

```
uname -a && lsb_release -a && free -h

Linux localhost 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       673Mi        97Mi        12Mi       1.2Gi       1.1Gi
Swap:          511Mi       333Mi       178Mi

```

**Comment by githubsaturn** [comment]
It's possible but it's really cumbersome. Probably easier to just do everything from scratch.
- You have to manually rename the services and add some unique prefix to them, i.e., from `srv-captain-someapp` to `old-srv-captain--someapp` 
- Next you'll create some empty apps
- Next, you'll remove the shell apps' containers (services)
- Next, you'll rename the `old-**` services and remove the prefix that you had added.

**Comment by chriskol** [comment]
Appreciate it.  I actually managed to find what looks like an auto backed up config-captain.json and restored that and everything was ok.  Presumably if I were to 'fill in the blanks' or recreate that file from scratch, it would be a cumbersome but ultimately successful endeavor.  Regardless, glad I didn't have to go down that path and all is good.

Thanks.
