### ISSUE TITLE
[Question] got "client intended to send too large body" from minio 

### ISSUE THREAD

**Issue by thelittlerocket** [caprover/caprover#1506]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hi there,

Would like to know if anyone has ever encountered the same problem when uploading files to minio?
I got a lot of this error in the log of minio
```
client intended to send too large body: 21731733 bytes
```
I tried to add ``` client_max_body_size 10G; ``` to caprover's NGINX Configurations under the settings page, but it won't help after restarting caprover, I also tried to add the same parameter to minio's Nginx setting, but got the same result,

So would like to know if anyone has any idea about this and advises a direction.

Thanks,

**Comment by maietta** [comment]
This is a problem not related to Caprover. In a little bit of Google digging, it appears there's an underlying XML parser used in Minio that's throwing this error.
