### ISSUE TITLE
[Deployment Issue] Error when pandas in requirements.txt

### ISSUE THREAD

**Issue by kenshuri** [caprover/caprover#1507]
Hello everyone,

It's the first issue that I create in this project, and the second issue I've ever created. Please let me know if my question does not belong here of if I can do anything to improve it.

In any case, thanks to all contributors to this project!

## What is the problem?
When deploying my app, it will fail inevitably if [{pandas}](https://pypi.org/project/pandas/) is in the `requirements.txt`

## Content of `captain-definition` file:
```
 {
  "schemaVersion": 2,
  "templateId": "python-django/3.10"
 }
```

## Steps to reproduce the problem:
To easily reproduce the problem, clone my repo which is a simple Django template ready to be deployed to caprover. It's available [here on github](https://github.com/kenshuri/django_tailwind_caprover).

Create a new app on CapRover and deploy to it: it works.

Then install pandas, update the `requirements.txt` file, commit, push and re-deploy
```
pip install pandas
pip freeze > requirements.txt
git commit -m "Add pandas"
git push origin main
caprover deploy --default
```

The deployment will fail. It seems that it never manages to install pandas, see below the build logs:
```
Collecting numpy==1.23.2
Downloading numpy-1.23.2.tar.gz (10.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 57.3 MB/s eta 0:00:00

Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pandas==1.4.4
Downloading pandas-1.4.4.tar.gz (4.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 79.3 MB/s eta 0:00:00

Installing build dependencies: started
Installing build dependencies: still running...
Installing build dependencies: still running...
Installing build dependencies: still running...
Installing build dependencies: still running...
Installing build dependencies: still running...

Something bad happened while retrieving issue-app app build logs.
502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"


Something bad happened while retrieving issue-app app build logs.
Error: connect ECONNREFUSED 164.92.140.20:443


Something bad happened while retrieving issue-app app build logs.
502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"


Something bad happened while retrieving issue-app app build logs.
502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"


Something bad happened while retrieving issue-app app build logs.
Captain is not ready yet...


Something bad happened while retrieving issue-app app build logs.
Captain is not ready yet...


Something bad happened while retrieving issue-app app build logs.
Captain is not ready yet...


Something bad happened while retrieving issue-app app build logs.
Error: connect ECONNREFUSED 164.92.140.20:443


Something bad happened while retrieving issue-app app build logs.
Error: connect ECONNREFUSED 164.92.140.20:443


Something bad happened while retrieving issue-app app build logs.
Error: connect ETIMEDOUT 164.92.140.20:443


Something bad happened while retrieving issue-app app build logs.
Captain is not ready yet...


Something bad happened while retrieving issue-app app build logs.
Captain is not ready yet...


Something bad happened while retrieving issue-app app build logs.
Password is incorrect.


Something bad happened while retrieving issue-app app build logs.
Password is incorrect.


Something bad happened while retrieving issue-app app build logs.
Password is incorrect.
```

I believe that the error `password is incorrect` is misleading and only happens because, as the deployment takes too long (as pandas is not being installed), my credentials expire.

## Output of the following command on my server:

```
uname -a && lsb_release -a && free -h
```

### Output
```
root@droplet-kenshuri-blog:~# uname -a && lsb_release -a && free -h
Linux droplet-kenshuri-blog 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:           985M        433M         85M        1.4M        465M        397M
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
It's most likely because your server is running out of memory and the entire server crashes.

**Comment by githubsaturn** [comment]
Actually, yes, I am now certain that it's the case. 
```
              total        used        free      shared  buff/cache   available
Mem:           985M        433M         85M        1.4M        465M        397M
Swap:            0B          0B          0B
```
You only have 85mb free on your RAM which is definitely not enough to build your app.

**Comment by githubsaturn** [comment]
It is just the build process for your app. Pandas may be a heavier dependency. 

On your local machine, you typically run `pip install pandas` only once, but on server this happens every time you deploy your app. Read Out of Memory when Building
 [here](https://caprover.com/docs/best-practices.html#out-of-memory-when-building). Specially solution 3.

**Comment by kenshuri** [comment]
Thanks again for your fast answer and for providing with some solutions for the long deployment time.
I've been trying solution 3 with github but I was not successful so far, I will let you know if I manage. If I do, I will draft some guidelines that might be useful for a potential new noob facing the same issues that I could share if you're interested :)

**Comment by kenshuri** [comment]
As promised, I came up with some recommendations for solution 3 with django app and github and summarized it in my [blog](https://blog.kenshuri.com/posts/006_from_heroku_to_capRover.md). Please let me know if you'd like me to draft something for the doc.

Also, the main point to speed the deployment was related to the python image used... The image used by default is the python-alpine image which should not be the preferred one as explained in this [post].(https://pythonspeed.com/articles/alpine-docker-python/). Using alpine-slim instead, I was able to speed-up considerably the deployment of my app. If possible, I would advise to modify the template so that it uses the slim image instead of the alpine one.

**Comment by githubsaturn** [comment]
Nice! If you'd like you can add your blog post here: https://caprover.com/docs/sample-apps.html#community-apps

**Comment by kenshuri** [comment]
Thanks! I just created a [PR](https://github.com/caprover/caprover-website/pull/107)
