### ISSUE TITLE
You have to first enable SSL for your root domain - How to generate by terminal command?

### ISSUE THREAD

**Issue by hermesalvesbr** [caprover/caprover#1508]
Guys, I'm installing a caprover under a proxy from my internet provider. But I have a valid public ip. I had to bypass the root domain validation to be able to install, but now I need to generate the certificate manually, by command line, from my root domain. 

How could I generate the https of my root domain by commands in the terminal?

Thanks in advance

**Comment by githubsaturn** [comment]
You can disable the verification done by CapRover by running this script:

https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107

**Comment by hermesalvesbr** [comment]
Yes, I made this. But now, I need to generate the ssl. This is possible?

**Comment by githubsaturn** [comment]
If Let's Encrypt is able to talk to your server, yes. You can either run `caprover serversetup` or go to dashboard and manually add the root domain and click on ENABLE HTTPS at the bottom right.

![image](https://user-images.githubusercontent.com/10582082/188994532-70237a43-a489-4a76-9bb6-e0f1632114ad.png)
