### ISSUE TITLE
caprover deploy: can't enter app name

### ISSUE THREAD

**Issue by girishso** [caprover/caprover#1517]
**What is the problem?**

Can't enter app name in shell.

**Steps to reproduce the problem:**

```
caprover deploy
```

**Output of the following command on local machine:**

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/35009/190629598-b909e851-a696-4e49-b752-3def48c4efbc.png">

**Comment by maietta** [comment]
What terminal are you using?

**Comment by girishso** [comment]
iTerm2 with zsh

**Comment by githubsaturn** [comment]
@girishso  - have you created the app beforehand? Can you take a screenshot of the apps section of your instance?

**Comment by fu-sen** [comment]
```
>caprover deploy
In `caprover deploy`, at this stage it is a list and you select with the arrow keys.

```
Preparing deployment to CapRover...

**** Protip ****
You seem to have deployed (app name) from this directory in the past, use --default flag to avoid having to re-enter the information.

? select the CapRover machine name you want to deploy to: (machine name)
Ensuring authentication...
? select the app name you want to deploy to:
  -- CANCEL --
> (app name)
  (app name)
  (app name)
```

If you don't see your app here, you'll need to create one first. From your CapRover web page.

By the way, if you are logged in to multiple CapRovers, it will be an option at the machine name stage.

**Comment by girishso** [comment]
Thanks @fu-sen.

**Comment by satvikpendem** [comment]
This should be in the [Getting Started page](https://caprover.com/docs/get-started.html), I followed it to the end and couldn't figure out why I couldn't type my app name until I searched online and found this issue.

**Comment by githubsaturn** [comment]
It is:

![image](https://user-images.githubusercontent.com/10582082/192937217-a9bb7cc3-5488-4007-a14f-399bf221b3db.png)

**Comment by satvikpendem** [comment]
Thanks, looks like I skipped that initial paragraph. Is there a way to create the app straight from the CLI?

**Comment by githubsaturn** [comment]
Currently, no
