### ISSUE TITLE
NGINX 502 when trying to deploy python flask apps

### ISSUE THREAD

**Issue by faisalsayed10** [caprover/caprover#1519]
tried deploying this https://github.com/waldisjr/CapRover-flask but it gives me ngnix 502

any help appreciated

**Comment by githubsaturn** [comment]
https://github.com/waldisjr/CapRover-flask/blob/c542a6912a9c36f76ececd18dec7766605395365/captain-definition#L9

The app runs on port 5555. You need to update Container HTTP Port in app settings.
