### ISSUE TITLE
Container stats no longer showing in NetData

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1522]
When I enable NetData in the CapRover console, it used to be the case that I could see stats for individual docker containers, but this is no longer the case.  I think the only thing I've done recently is to start using servers (for main and worker nodes) running Ubuntu 22.04, rather than 18.04.  Might that be the reason, and is there any way to get per-container stats back?

**Comment by githubsaturn** [comment]
Thanks for reporting this. Looks like it's an Ubuntu 22 bug. 

See https://github.com/netdata/netdata/issues/8969

```
netdata    | 2020-05-11 19:44:35: netdata ERROR : PLUGIN[diskspace] : DISKSPACE: Mount point '/run/docker.sock' (disk '_run_docker.sock', filesystem 'tmpfs', root '/docker.sock') is not a directory. (errno 22, Invalid argument)
```


The new version of netdata has fixed the issue. To resolve the issue with CapRover.
- Either update to CapRover edge version
- Or, override the netdata image:

```bash
echo  "{\"netDataImageName\":\"caprover/netdata:v1.34.1\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by drmrbrewer** [comment]
Thanks, I'll give it a go.  Any idea when the next public release of CapRover will land?  And from the related NetData issue, it looks like it's a NetData bug (related to Ubuntu 22) rather than an Ubuntu 22 bug per se.

**Comment by githubsaturn** [comment]
Haven't had much time lately to add more features. So probably towards EOY.
