### ISSUE TITLE
`.dev` domain problem [Question]

### ISSUE THREAD

**Issue by LWJerri** [caprover/caprover#1525]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Good afternoon, I recently changed to a .dev domain that requires an SSL certificate which CapRover does not generate. How can I generate a certificate for the main domain through the console using CertBot?

This is what my domain is now - captain.lwjerri.dev

**Comment by maietta** [comment]
The TLD's like .dev and .app do require SSL's before they will be resolvable in the browser, but that doesn't mean you can't use them exactly the same as any other domain anywhere else.

When issuing SSL's using LetsEnscrypt, they work exactly the same as any other top level domain. You'll want to make sure you've created a wildcard entry such as *.lwjerri.dev to resolve to the A "answer" record for your IP of your CapRover instance. If you'll also be assigning your bare naked domain and the www, you'll also need entries for those. Take note of the TTL values. You can lower or increase the values based on how long you are willing to wait to issue your SSL's in the worst case scenario.

Once you've waited the time denoted in the TTL fields, (usually measured in seconds) then you'll almost certainly be able to issue those SSL's for your apps.

**Comment by LWJerri** [comment]
Hmm. How I can change my root domain back?

**Comment by githubsaturn** [comment]
You have to manually edit the config file.
```bash
docker service scale captain-captain=0
nano /captain/data/config-captain.json
# find "customDomain" and update it - it's probably at the top of the file
# save and exit the editor
docker service scale captain-captain=1
# wait 10-15 sec, now you can access the instance
```
