### ISSUE TITLE
[Question] Discord Bots

### ISSUE THREAD

**Issue by tiudvek** [caprover/caprover#1529]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Can I make discord bots on caprover using libraries like discord.js and discord.py?

**Comment by githubsaturn** [comment]
CapRover is just a deployment platform. As long as you can make a Docker image, you can run whatever on CapRover

See this for example: https://www.youtube.com/watch?v=qp2pgLtb2Cw
