### ISSUE TITLE
[Question] Why should I choose Caprover over Dokku?

### ISSUE THREAD

**Issue by kamzata** [caprover/caprover#1531]
Caprover seems a great project as well as Dokku. My question is: what are the benefits to use Caprover over Dokku? What are the features Caprover have more than Dokku and viceversa?

**Comment by githubsaturn** [comment]
Two projects, two separate approaches to the same problem. You have to try both to see what you like better. CapRover is geared towards providing a simple GUI where majority of actions are exposed through GUI, whereas Dokku is mostly a command line tool. Having said that CapRover does have CLI api tool, but GUI is the more preferred. Dokku also has GUI, but it's a paid feature.

**Comment by kamzata** [comment]
> Two projects, two separate approaches to the same problem. You have to try both to see what you like better. CapRover is geared towards providing a simple GUI where majority of actions are exposed through GUI, whereas Dokku is mostly a command line tool. Having said that CapRover does have CLI api tool, but GUI is the more preferred. Dokku also has GUI, but it's a paid feature.

I've already tried Dokku but I'll try Caprover for sure. I'd like to set up a CI/CD pipeline leveraging Dokku or Caprover and my Gitlab installation. I'd like to simply deploy using a Dockerfile or a git commit. Could I able to do it using Caprover? Could you kindly address me towards some guides? Thanks

**Comment by githubsaturn** [comment]
https://caprover.com/docs/get-started.html#step-5-deploy-the-test-app

Yes, you can do that. By default, CapRover uses Dockerfile, but if you want your dockerfile to be named something different, like `Dockerfile.prod`, you can use a file called `capain-definition` - also in the docs.

**Comment by maietta** [comment]
@kamzata some quick searches could help you more quickly get to your answers.

Gitea is already available in Caprover as a One-Click-App and the docs do show a couple of methods for deploying projects. There are several issues already raised on the subject that are worth searching around for.

**Comment by kamzata** [comment]
Just found out Coolify too. What do you think about that?

**Comment by maietta** [comment]
> Just found out Coolify too. What do you think about that?

Your asking this in a place devoted to issues relating to CapRover.

I've done my own hosting for more than 25 years and specifically chose CapRover for my own preferences and what it offers, knowing that I may have to roll up my sleeves to Taylor things for my use case.

You need to do your own research elsewhere.

This github repo is for CapRover issue tracking.
