### ISSUE TITLE
[Deployment Issue] MINIO one click app client_max_body_size  not working

### ISSUE THREAD

**Issue by clementvp** [caprover/caprover#1534]
What is the problem?
Even after changing the client_max_body_size Nginx option in the ngning app config, Minio throw a  "client intended to send too large body"

Steps to reproduce the problem:

Install a MINIO one click app 
Change ngninx config file to set a client_max_body_size  of 2048M 
client_max_body_size 2048M; under app server block  (Nginx app config) both the minio app and the minio-s3 app 
Log to the minio UI 
Create a bucket 
Try to push an item above 20 Mo 

Getting an "client intended to send too large body" error

Maybe it's because MINIO one click app use a ngninx reverse proxy image under the hood ? 

Can you provide an example to change the file size limit ?

**Comment by githubsaturn** [comment]
That's correct:
`-s3` app is just an nginx reverse proxy app that reroutes to another port. 

You can simply fork this [image](https://github.com/caprover/nginx-reverse-proxy), and build your own custom nginx.
