### ISSUE TITLE
[Deployment Issue] Error: read ECONNRESET

### ISSUE THREAD

**Issue by mlorthios** [caprover/caprover#1535]
**What is the problem?**

When deploying with Github Actions, the error "Error: read ECONNRESET" happens quite often when deploying to the server, it's really random and I don't see where this can come from.
<img width="1410" alt="Capture d’écran 2022-10-18 à 10 05 01" src="https://user-images.githubusercontent.com/31793724/196372707-c58c82a3-3d6a-4978-a2c4-36c3ed32afa5.png">

**Steps to reproduce the problem:**

1. Use app token to do a Github Actions deployment
2. Run the workflows several times, the error will appear at some point

Thanks

**Comment by githubsaturn** [comment]
Most likely your server is getting restarted. The most common reason is that your build process is very heavy on RAM/CPU. 

You can confirm that by SSHing into your instance and run `docker service logs captain-captain --follow` to see the service restart when deploying the app.


Fix: either change your process to build on Github runners and just deploy the docker image to your instance, or increase the RAM of your server.

**Comment by mlorthios** [comment]
There is no reboot of the server and no RAM overload (I have 8GB of ram), it can't be due to the size of the .tar and the nginx configuration? Because it's strange that this appears from time to time

**Comment by githubsaturn** [comment]
Did you get the logs? What it did say?

Next time it happens, get the last 5min logs by running this:
```
docker service logs captain-captain --since 5m
```
