### ISSUE TITLE
[Deployment Issue] Deploy with Github Action show Error authentication.

### ISSUE THREAD

**Issue by mtommyp14** [caprover/caprover#1537]
Hello Guys,

So I tried to deploy my repo with GitHub action to caprover with these yaml:

> name: Deploy staging
> 
> on:
>   push:
>     branches: staging
> 
> jobs:
>   main:
>     runs-on: ubuntu-latest
> 
>     steps:
>       - name: Check out the repo
>         uses: actions/checkout@v2
> 
>       - name: CapRover app deploy
>         uses: AlexxNB/caprover-action@v1
>         with:
>           server: 'https://captain.inc.id/'
>           password: '${{ secrets.CAPROVER_STAGING_PASSWORD }}'
>           appname: 'adm-dev'
>           branch: 'staging'

My image is good and works on my local and another server, but I can't push and run on caprover:
error like these:

![WhatsApp Image 2022-10-20 at 09 52 09](https://user-images.githubusercontent.com/57124961/196845064-c98b83ce-b502-4c31-99ac-e22d03a57657.jpeg)

before this never happened before enabling cloudflare, but recently I used it and got an error like that.
Please help me guys

**Comment by githubsaturn** [comment]
`challenge-error-title` is probably an indication that you're behind cloudflare. It's not a CapRover issue.
