### ISSUE TITLE
Customize the period of logs to show in caprover log manager UI

### ISSUE THREAD

**Issue by RenanZX** [caprover/caprover#1542]
**Is your feature request related to a problem? Please describe.**
Yes, it could be very useful, because caprover UI only shows up the last 30 minutes of logs and expand this time is welcome, mainly because watch it acessing the machine sometimes is very painful.

**Describe the solution you'd like**
Define a command to control the time logs to show in caprover UI, for example:

`caprover set logs -1h -a 'name-app'`

it will set up to show the last hour logs in caprover UI

**Describe alternatives you've considered**
Use paid tools like datadog or perptrail, but it's not too easy to use and install to watch logs from docker. 

**Additional context**
It's a simple feature that just controls the time logs in caprover UI, but I think it's a great addiction to caprover platform.

**Comment by githubsaturn** [comment]
CapRover main UI is designed to be only covering very basic cases while allowing for customization. 

Docker logs are a good example. While CapRover limits logs window, it has one click apps that display richer log information. Try installing Dozzle from one click apps. 

![image](https://user-images.githubusercontent.com/10582082/197345597-7625ccb8-5ada-46b6-b85a-3deb80011b06.png)
