### ISSUE TITLE
Deployment of a docker image from a private repository

### ISSUE THREAD

**Issue by voiddaek** [caprover/caprover#1552]
What is the problem?

The problem happens when trying to deploy a image from a private registry.
I have an image `myregistry.apps.domain.com/readability`.
The registry is protected by Basic auth.
I have added this registry to the Docker Registries section in the cluster config.

But when deploying, I am getting an error.
```
------------------------- Wed Nov 02 2022 16:42:13 GMT+0000 (Coordinated Universal Time)
Build started for readability
An explicit image name was provided (myregistry.apps.domain.com/readability). Therefore, no build process is needed.
Pulling this image: myregistry.apps.domain.com/readability This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 500) server error - Head "https://myregistry.apps.domain.com/v2/readability/manifests/latest": no basic auth credentials
```

If applicable, content of `captain-definition` file:
```
 {
  "schemaVersion": 2,
  "imageName": "myregistry.apps.domain.com/readability"
 }
```

Steps to reproduce the problem:

1. Create a private registry registry:2
2. Protect it with basic auth
3. push an image to it
4. use the imageName in captain-definition
5. Error

Server config:

```
Linux 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       2.2Gi       175Mi        16Mi       1.4Gi       1.3Gi
Swap:         2.0Gi       686Mi       1.3Gi
```

**Comment by voiddaek** [comment]
Just wanted to add that if I am using a docker file to build the FROM close is working with the private repository.
```
FROM myregistry.apps.domain.com/readability AS read
RUN echo "here"

FROM myregistry.apps.domain.com/mail AS mail
RUN echo "there"
```
This has no problem.

**Comment by voiddaek** [comment]
I just tried it. 
```
tt@caprover:# docker login myregistry.apps.domain.com
Username: username
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

Then I tried again:
```
 {
  "schemaVersion": 2,
  "imageName": "myregistry.apps.domain.com/readability"
 }
```
Same error as previously.

Do I need to restart one of the caprover container maybe ?

**Comment by maietta** [comment]
I really don't know. I've used private registries many times but always had to authenticate the host to access the private registries. I didn't have to perform any restarts for it to work. Someone else will have to chime in on this problem as I don't have enough experience with a problem like yours.

**Comment by maietta** [comment]
Wait... I don't think your imageName syntax is right.

I think `myregistry.apps.domain.com/readability` should be in the format of

`myregistry.apps.domain.com@readability:latest`

Your error isn't an authentication one, it's likely a non-existant image by the name you requested.

**Comment by voiddaek** [comment]
Trying:
```
 {
  "schemaVersion": 2,
  "imageName": "myregistry.apps.domain.com@readability:latest"
 }
```

Result:
```
------------------------- Wed Nov 02 2022 17:11:15 GMT+0000 (Coordinated Universal Time)
Build started for mail
An explicit image name was provided (myregistry.apps.domain.com@readability:latest). Therefore, no build process is needed.
Pulling this image: myregistry.apps.domain.com@readability:latest This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 400) unexpected - invalid tag format
```

Also when using the captain definition I am using the WEB UI / Deployment / Method 5. Not the CLI.
Maybe it provides some context.

**Comment by voiddaek** [comment]
For now instead I will just use the WEB UI / Deployment / Method 4 (Plain docker file):
```
FROM myregistry.apps.domain.com/readability:latest AS base
```
It works and it's obviously as simple.

**Comment by frederikhors** [comment]
I can confirm method 4 works (as suggested by @voiddaek), method 6 doesn't. I think this is simply a bug.

**Comment by Kkeller83** [comment]
I dont know why this is closed. I am trying the same and also get the basic auth error. Even after loggin in with docker in the terminal and restarting the node and adding the registry to caprover

**Comment by githubsaturn** [comment]
> I dont know why this is closed

This issue is not closed.

> Even after loggin in with docker in the terminal and restarting the node

CapRover does not use the docker credentials. So this has no effects. 


>  .... and adding the registry to caprover

This on the other hand is what should technically work. My guess is that there is some discrepancies between the domains that you're using in your registry when you're adding it to the cluster and your image format.

Can you please take a screenshot of your registry (username, prefix, and domain) and also a screenshot of a failed deploy?

**Comment by MihailRussu** [comment]
> My guess is that there is some discrepancies between the domains that you're using in your registry when you're adding it to the cluster and your image format.

probably unrelated but fwiw I was running into the same problem trying to pull from a private `hub.docker.com` registry, and although authentication in `Cluster` -> `Docker Registry Configuration` -> `Docker Registries` worked fine when the domain was set to be `docker.io` or  `registry.hub.docker.com`, etc - pulling only worked correctly after chaining the domain to `registry-1.docker.io` (as was initially suggested in the web-form's `placeholder` hint).

**Comment by MihailRussu** [comment]
> My guess is that there is some discrepancies between the domains that you're using in your registry when you're adding it to the cluster and your image format.

+1, fwiw I was running into a similar problem trying to pull from a private `hub.docker.com` registry, and although authentication in `Cluster` -> `Docker Registry Configuration` -> `Docker Registries` worked fine when the domain was set to be `docker.io` or  `registry.hub.docker.com`, etc - pulling only worked correctly after changing the domain to `registry-1.docker.io` (as was initially suggested in the web-form's `placeholder` hint).

**Comment by Blemming** [comment]
Having the same issue with method 6. Our CI-CD already builds images and pushes them to docker hub I juste need caprover to pull and keep the containers updated.

<img width="305" alt="image" src="https://github.com/caprover/caprover/assets/12241815/5bfa0dd1-9ada-4a75-8be7-483edfa9784e">

then
<img width="961" alt="image" src="https://github.com/caprover/caprover/assets/12241815/87c95e5d-3c89-41cf-a76d-b529ab070fd9">

It's like the method 6 is not using the credentials in the cluster section at all 🤔

**Comment by githubsaturn** [comment]
@Blemming  - thanks for the complete logs! It's a lot easier to debug when full logs are provided!

Your image name is incorrect. Instead f `display_rack:staging` you should use `beaulieucanada/display_rack:staging`


Feel free to reopen if the issue still persists.

**Comment by Blemming** [comment]
> @Blemming - thanks for the complete logs! It's a lot easier to debug when full logs are provided!
> 
> Your image name is incorrect. Instead f `display_rack:staging` you should use `beaulieucanada/display_rack:staging`
> 
> Feel free to reopen if the issue still persists.

Wow thanks !, I was sure I had tried that, but it worked. So the image prefix part is only for the pushes not the pulls I'm guessing. Which makes sense if you need to install public containers.

**Comment by benoib** [comment]
For whom may find this useful. I had the issue for a few hours. 

Solution for me was to put docker.io as host. I didn't change the adress of the images I pull from docker, but noticed it was using docker.io. The other adresses did not work.

And disable push for some reason.

I don't use my own image, but push a dockerfile to caprover and have it build on my remote machine.

Also, it is possible that the update of subscription on Docker takes a bit of time.

Alternative solution for people wanting to just pull basic images from docker -> pull from aws public ecr.

**Comment by devakrishna33** [comment]
For anyone else facing the issue the image name should be given as 
`<registry_url>/<username>/<image_name>:<tag>`
for example: registry.demo.com:996/captain/demo:latest. Here my self hosted registry URL is registry.demo.com:996 and "captain" is the username.

**Comment by wingsuitist** [comment]
> I think on the CapRover host, you'll need to authenticate by using the `docker login` command via the console or ssh terminal.
> 
> ```
> $ docker login --help
> Log in to a Docker registry or cloud backend.
> If no registry server is specified, the default is defined by the daemon.
> 
> Usage:
>   docker login [OPTIONS] [SERVER] [flags]
>   docker login [command]
> 
> Available Commands:
>   azure       Log in to azure
> 
> Flags:
>   -h, --help              Help for login
>   -p, --password string   password
>       --password-stdin    Take the password from stdin
>   -u, --username string   username
> 
> Use "docker login [command] --help" for more information about a command.
> ```

Is this possible to be done separately for each user? So different users have different registries with different passwords?

**Comment by maietta** [comment]
> > I think on the CapRover host, you'll need to authenticate by using the `docker login` command via the console or ssh terminal.
> > ```
> > $ docker login --help
> > Log in to a Docker registry or cloud backend.
> > If no registry server is specified, the default is defined by the daemon.
> > 
> > Usage:
> >   docker login [OPTIONS] [SERVER] [flags]
> >   docker login [command]
> > 
> > Available Commands:
> >   azure       Log in to azure
> > 
> > Flags:
> >   -h, --help              Help for login
> >   -p, --password string   password
> >       --password-stdin    Take the password from stdin
> >   -u, --username string   username
> > 
> > Use "docker login [command] --help" for more information about a command.
> > ```
> 
> Is this possible to be done separately for each user? So different users have different registries with different passwords?

As far as I am aware, you can authenticate the docker client from as many machines, with the same user/pass, as you need.

**Comment by githubsaturn** [comment]
Please note that CapRover doesn't have access to creds if you use `docker login`. If you want CapRover to be able to pull your images, you must go to CLUSTER, and add a registry.

**Comment by wingsuitist** [comment]
It would be amazing if it had a similar feature like the Kubernetes imagePullSecret. So you can define an image pull authentication for each and every application separately.

**Comment by githubsaturn** [comment]
CapRover has something similar, but instead of per application, you can define `image prefix` and you can have multiple creds - based on the `image prefix` the correct creds will be used.

**Comment by wingsuitist** [comment]
> CapRover has something similar, but instead of per application, you can define `image prefix` and you can have multiple creds - based on the `image prefix` the correct creds will be used.

Thx for the hint. What about having registry.gitlab.com/groupX/projectY/image:latest used by one user and registry.gitlab.com/groupX/projectZ/image:latest use by another user of the same CapRover and both GitLab Registries need different credentials?

**Comment by githubsaturn** [comment]
> another user of the same CapRover

CapRover doesn't have the concept of "users". But you can do what you mentioned for different apps if you want.

**Comment by rebecamurillo** [comment]
I had trouble with an AWS private registry, I managed to make it work with the following steps : 
1. setup AWS cli `aws configure` (your user should have the appropriate security policies)
2. genetare password and copy the result with  `aws ecr get-login-password --region us-east-1` 
3. In CapRover web console, go to Clusters, then Add Remote Registry. Fill the following information 
```
Username : AWS
Password : paste value from step 2
Domain : ‹your_aws_account_id›.dkr.ecr.‹your_aws_region›.amazonaws.com
Image prefix : leave empty
```
4. Create your app and deploy with  Method 6: Deploy via ImageName : `‹your_aws_account_id›.dkr.ecr.‹your_aws_region›.amazonaws.com/‹your_private_repository›:‹your_image_tag›`


Since the AWS ecr password expires, you would need to repeat steps 2 and 3 (edit cluster) whenever you need to make a new deployment. Ref issue https://github.com/caprover/caprover/issues/1476

I hope this is helpful.

**Comment by CarlosRBK** [comment]
If anyone is experiencing this issue:

In the Caprover dashboard, go to "Cluster" > "Add Remote Registry" and complete the following information:

- Username: GitHub
- Password: GitHub token with the necessary permissions
- Domain: ghcr.io
- Image prefix: Organization name or username, as appropriate.
