### ISSUE TITLE
[Question] Is the project dead?

### ISSUE THREAD

**Issue by FrancocDev** [caprover/caprover#1557]
Hi, I'm searching for an option to deploy my apps, and find caprover, but looking at the repo I saw that the last release was 1 year ago. 
Is currently developed or is dead? 
If is dead, there are any good alternative? Thanks!

**Comment by githubsaturn** [comment]
No it's not dead :) It's mature. Meaning that there is no bugs to be addressed. And we don't bloat the already-working application with rarely-used features.

Having said that, a new release will come soon.
