### ISSUE TITLE
Chaskiq Template BUG

### ISSUE THREAD

**Issue by fabioaraujobh13** [caprover/caprover#1563]
When deploying the frontend, this error message appears:

Failed: Error: {"message":"manifest for chaskiq/chaskiq:9009088 not found: manifest unknown: manifest unknown"} manifest for chaskiq/chaskiq:9009088 not found: manifest unknown: manifest unknown

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![image](https://user-images.githubusercontent.com/10582082/202915289-77a93aa4-b807-4723-8f97-b2a5fc09ce43.png)
