### ISSUE TITLE
All apps disapeared and Caprover reset itself[Deployment Issue]

### ISSUE THREAD

**Issue by julianengel** [caprover/caprover#1566]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

Our entire server went down. It was a very weird thing, but we managed to get back in. Then, there were problems with the resolv.conf missing and all domain lookups failed. I reset the resolv.conf and set it up to use Cloudflare, and server became accessible from the internet again. However, this is when it completely stopped working, and all of our apps were showing Nothing Here Yet. 
We managed to get in through the IP and Port 3000, but this shows an empty install without any apps. Running docker ps shows all the containers and images running correctly. They just don't seem to be seen by captain. 

Steps to reproduce the problem:

1. Server failed
2. Reset root password
3. Added SSH key back 
4. Created resolv.conf in /etc/
5. Accessed via IP:3000

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux caproevr-apps 4.15.0-196-generic #207-Ubuntu SMP Thu Oct 27 21:24:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:           1.9G        1.1G        122M         63M        733M        699M

```

**Comment by githubsaturn** [comment]
Looks like a hardware failure on your server, there is probably nothing CapRover related. Are the underlying services still running?
```
docker service ls
```
what does it  print?

**Comment by julianengel** [comment]
That’s the thing, all the caprover services and images are running. The question on hand is if Caprover configures the resolv.conf in any way? I don’t have my laptop at the moment, but docker service ls shows both the main caprover, certbot and the rest running.My best,Julian Julian EngelOn 24 Nov 2022, at 18:45, Kasra Bigdeli ***@***.***> wrote:﻿
Looks like a hardware failure on your server, there is probably nothing CapRover related. Are the underlying services still running?
docker service ls

what does it  print?

**Comment by githubsaturn** [comment]
> The question on hand is if Caprover configures the resolv.conf in any way?

No, but the fact that this file is corrupted hints me to a hardware failure that might also resulted in CapRover configs to be corrupted at well. You can confirm whether your apps are in CapRover's database by running this:

```
cat /captain/data/config-captain.json
```

If you don't see the apps here, it confirms that there was a disk issue and it caused your data to be corrupted, resolve.conf, caprover's db, and probably many more.

**Comment by julianengel** [comment]
Disk issue it was... which was a shame because Digital Ocean never gave us any problems before. Thank you for your help, I really appreciate it. Can I have one last question? 

We had a few DBs running as images, (analytics mostly), they seem to be still running correctly. Below is the output of the service ls command. Do you have any idea/suggestion if it's possible to restore the running images to the caprover Database?

Other than that, my only idea would be to push all the images of the databases to a registry, pull them to a local machine and then try to extract the data that way. Is there anything I'm not thinking about that could save us from having to pull data out?

Thank you! Love the work you do and really appreciate the help with this.

**Comment by julianengel** [comment]
```
ehrwfdqwh79r   captain-captain                     replicated   1/1        caprover/caprover:1.10.1            *:3000->3000/tcp
vaao86w4jql0   captain-certbot                     replicated   1/1        caprover/certbot-sleeping:v1.6.0    
dqdye6kqyr6h   captain-nginx                       replicated   1/1        nginx:1                             
5g0g5qdovvwu   srv-captain--analytics              replicated   1/1        img-captain-analytics:1             
kprahq2x67xj   srv-captain--analytics-clickhouse   replicated   1/1        yandex/clickhouse-server:21.3.2.5   
9y57ytm3mrci   srv-captain--analytics-mail         replicated   1/1        bytemark/smtp                       
nyta3odqsblp   srv-captain--analytics-postgres     replicated   1/1        postgres:12-alpine                  
zsinhkhuy4o0   srv-captain--downstreaming          replicated   1/1        img-captain-downstreaming:2         
33bklz4juc36   srv-captain--estia                  replicated   1/1        img-captain-estia:16                
tyinzqmt6fyh   srv-captain--estia-brick-submit     replicated   1/1        img-captain-estia-brick-submit:11   
b7q11215nxe7   srv-captain--jenk                   replicated   1/1        img-captain-jenk:1                  
0m1magtok64s   srv-captain--julian-requests        replicated   1/1        img-captain-julian-requests:3       
x5ymedgcz95m   srv-captain--launchpage             replicated   1/1        img-captain-launchpage:21           
izrr1mlaj5ud   srv-captain--m26-links              replicated   1/1        img-captain-m26-links:3             
4v07eoebvne2   srv-captain--pay                    replicated   1/1        img-captain-pay:8                   
rptxyq950c3b   srv-captain--raven                  replicated   1/1        img-captain-raven:6                 
r56lldoxvmo3   srv-captain--status                 replicated   1/1        img-captain-status:1                
pf1ryifafgjz   srv-captain--stocktaking            replicated   1/1        img-captain-stocktaking:44          
rijif64wgqtu   srv-captain--support                replicated   1/1        img-captain-support:1               
cbjmuqcusl57   srv-captain--trello                 replicated   1/1        img-captain-trello:16               
qapwq0i4dte7   srv-captain--uptime                 replicated   1/1        louislam/uptime-kuma:latest   
```

**Comment by julianengel** [comment]
You were right… it was a hardware issue. Managed to ssh into the instance, and using the caprover CLI get into each DB, dump the data and copy it to the host and download via SFTP. Thank you for the help!
