### ISSUE TITLE
Startup order of containers

### ISSUE THREAD

**Issue by delasource** [caprover/caprover#1567]
**Is your feature request related to a problem? Please describe.**
I have caprover running about 30 different apps. Some of which do some CPU heavy work on startup. So when i reboot the host, the startup order of apps seems to be random, depending on how fast the threads do finish. In some cases, apps are started earlier then their respective database containers. This problem did not exist, with just a few apps, but now with 30 containers launching at host startup, is a problem.
In the recent days i had to reboot the host a couple of times (because of stupid things with docker swarm networking, dont get me started) - and in the current situation i have to manually check each app if it had finished their startup tasks correctly.

**Describe the solution you'd like**
I'd like to set container dependencies like it is possible in Kubernetes or even docker-compose, so containers only start if their dependencies are healthy.
This is the same feature request as #813 #807 #795 #793 and i fairly think it is required. I understand app resilience but in some cases there is no perfect solution.

**alternatives**
A "container-startup-order after reboot" would be nice, to reduce the load of the host system. This could also be used to prioritize services, so a reboot has minimal outage on the essential services.

**Comment by githubsaturn** [comment]
The underlying management of services is not by CapRover, but it's done by Docker swarm. Hence there is nothing CapRover can do to change this ordering. You can ask your question in [Docker forum](https://github.com/moby/moby) and there might be able solution for it. 

PS1:
> I'd like to set container dependencies like it is possible in Kubernetes or even docker-compose, so containers only start if their dependencies are healthy.

Docker compose dependency graph only applies to the initial launch. Not the subsequent restarts.

PS2:
All other posts you linked are spams only by one user.

**Comment by delasource** [comment]
i'll link this issue here https://github.com/moby/moby/issues/31333
