### ISSUE TITLE
stub_status not working

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1573]
_My overall goal:_
I want to monitor how many requests every app on the server receives via _Prometheus_ and _Grafana_. I found a [solution](https://www.observability.blog/nginx-monitoring-with-prometheus/) for this by simply using `stub_status` for it. So I will write a bash script that produces an output that `node-exporter` can read via `--collector.textfile.directory`.

_CapRover specific:_
So I want to configure nginx, so that I can append `/nginx_status` on every app url to get the data (like myapp.captain.example.com/nginx_status).

I found out that it is already done via `CapRover Config Location in nginx container: /etc/nginx/conf.d/captain-root.conf` … but it does not seem to work. Is this something different here?

```
#/etc/nginx/conf.d/captain-root.conf

# Default catch-all page. e.g. if you enter SOME-RANDOM-CHARS.captainroot.domain.com
    server {

        # Catch all HTTP
        listen       80;

        # Catch all HTTPS
        listen              443 ssl;
        ssl_certificate     <%-fake.crtPath%>;
        ssl_certificate_key <%-fake.keyPath%>;

        server_name  _;

        location /nginx_status {
            stub_status on;

            access_log off;

            # This can be improved by adding authentication as well.
            # CIDR Range IPs:
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            
            deny all;
        }

     …
```

Where do I have to put the code so that it works?

```
# Example
location /nginx_status {
  stub_status on;
}
```

**Comment by githubsaturn** [comment]
You can get that information by simply calling the nginx service. Just run a GET request to `http://captain-nginx/nginx_status` **from inside one of the containers**.

Example:
```bash
# shell into a container (any CapRover app)
docker exec -it $(docker ps --filter name=captain-captain -q) /bin/bash

# send the request

curl http://captain-nginx/nginx_status
```

**Comment by JonathanDoelan** [comment]
@githubsaturn Thanks for the quick reply. It works … but unfortunately not for every container (Examples: Portainer, Grafana, Prometheus). The reason is that `curl` is not installed on every container. I've tried `wget` but not every container gives permission to it.

So I think it will be best, if I would make `stub_status` available for every app with `/nginx_status`. Of course I could edit every single `Application Specific Config File`, but I was wondering if I could modify it globally? Either the nginx config so that it works for every app, or if I could overwrite the template for the `Application Specific Config File`, so that I don’t have to do add it manually for every single app?

**Comment by githubsaturn** [comment]
Doesn't matter. Nginx stin is always giving you the overall metrics. Regardless of where it sits.

**Comment by JonathanDoelan** [comment]
@githubsaturn What is `stin` or `Nginx stin`?

**Comment by githubsaturn** [comment]
Typo. I meant stub. Stub status.

**Comment by JonathanDoelan** [comment]
@githubsaturn oh! I understand. Is there a way to get the requests per container?

**Comment by githubsaturn** [comment]
Not that i know of.

**Comment by JonathanDoelan** [comment]
@githubsaturn I’ve figured out how to get the requests. By simply viewing the logs of the nginx container:
```
docker logs -f $(docker ps --filter name=captain-nginx -q)
```

**Comment by githubsaturn** [comment]
Yes you can do that, but you have to build your own aggregation. It doesn't calculate the total number of requests for you.
