### ISSUE TITLE
Fluentbit & Fluentd for application log forwarding

### ISSUE THREAD

**Issue by manjeshpv** [caprover/caprover#1577]
- Installed caprover using https://docs.docker.com/config/containers/logging/fluentd/#

###  updated /etc/docker/daemon.json
```
{
   "log-driver": "fluentd",
   "log-opts": {
     "fluentd-address": "localhost:24224"
   }
 }
 ```

###  build docker fluentbit for forwarding logs
```
FROM fluent/fluentd@sha256:7eece00d1bc784ac1e9722b2580911cd3ead5afd740dad6594be945b3b1dd884

RUN /usr/bin/fluent-gem install elasticsearch --version 7.9.0 \

&& /usr/bin/gem install elasticsearch --version 7.9.0 \

&& /usr/bin/fluent-gem install fluent-plugin-elasticsearch \

&& /usr/bin/gem install fluent-plugin-elasticsearch
 ```

 ### Started container

```
docker build -t caprover/fluentd:es7.9.0 .
docker run -it -p 24224:24224 -d -v /opt/fluent.conf:/fluentd/etc/fluent.conf -e FLUENTD_CONF=fluent.conf caprover/fluentd:es7.9.0-leadschool
docker run --log-driver=fluentd -t ubuntu echo "Bangalore sending logs with ❦ ♡ ♥ ❤ 💓 "
```

Started caprover

i can see docker system logs in ELK

but i want to see docker application logs

**Comment by githubsaturn** [comment]
This is not a CapRover question. I recommend you look into fluentd docs and ask in their forum. 

CapRover is simply a deployment mechanism. If you want to change the logging driver for a particular service, you can easily bypass CapRover and update using `docker service update.....`
