### ISSUE TITLE
Save & Update not restarting apps

### ISSUE THREAD

**Issue by alfredvdheide** [caprover/caprover#1583]
### What is the problem?
First of all, thank you for this amazing software I've been happily using it for years now :smile: .
Out of the blue, our dedicated server suddenly started misbehaving in various ways. Whenever we would 'Save & Update' an app, it would no longer restart the app on Docker. Moreover, our replica count is also sometimes not what it should be. These issues never happened until a couple of days ago.
![image](https://user-images.githubusercontent.com/11142450/205878491-435b04c0-3fd4-4308-85d3-80e6152f8ce9.png)
![image](https://user-images.githubusercontent.com/11142450/205878520-7a91000a-45d9-4d6f-b5fa-39aaa757c369.png)

To work around the apps not restarting, we temporarily found a fix to set the instance to 0, and then back to the previous value, which would spin up the containers using the newly built image.

the captain-captain service logs show that whenever we click 'Save & Update', it looks like captain is correctly executing its program, but we think captain is somehow not communicating with Docker properly, or also likely, Docker is misbehaving. As no containers actually end up restarting.
```
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:53.156 am    Updating app started: production-bot-dashboard
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:53.182 am    Ensure service inited and Updated for: production-bot-dashboard
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:53.190 am    Check if service is running: srv-captain--production-bot-dashboard
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:53.195 am    Service is already running: srv-captain--production-bot-dashboard
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:53.200 am    Updating service srv-captain--production-bot-dashboard with image img-captain-production-bot-dashboard:13
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.220 am    Updating Load Balancer - ServiceManager
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.221 am    Locking NGINX configuration reloading...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.300 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.300 am    sendReloadSignal...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.305 am    Kill HUP Container: ae538f4e9adcd21b1671c65f1c67ceeefd98a317545ba6ad038e254a53881ae2
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.362 am    Updating Load Balancer - ServiceManager
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.362 am    Locking NGINX configuration reloading...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.394 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.394 am    sendReloadSignal...
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.398 am    Kill HUP Container: ae538f4e9adcd21b1671c65f1c67ceeefd98a317545ba6ad038e254a53881ae2
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:55.438 am    AppName is updated: production-bot-dashboard
captain-captain.1.0pmfs2juk7x2@athena-master1    | POST /api/v2/user/apps/appDefinitions/update 200 2283.937 ms - 69
captain-captain.1.0pmfs2juk7x2@athena-master1    | GET /api/v2/user/apps/appDefinitions 304 21.691 ms - -
captain-captain.1.0pmfs2juk7x2@athena-master1    | December 6th 2022, 9:44:58.220 am    Pruning containers...
```
### 'fixes' attempted
We've tried various things such as:
running `docker service update captain-captain --force` which caused captain-captain to hang and crash the captain container, but leave the other containers running (the captain admin panel went offline, but other web-apps stayed online).

running
```
docker pull caprover/certbot-sleeping
docker pull caprover/certbot-sleeping:v0.29.1
docker pull nginx
docker pull nginx:1 
```
running:
 `docker service update captain-captain --image caprover/caprover:latest`
`docker swarm ca --rotate`
`sudo systemctl restart docker`
additionally, we also restarted the server completely.

We are unsure how to reproduce this issue, as we do not know what event caused this. The server was running flawlessly until just recently.

We are wondering if anyone has had this issue before and would be very grateful if someone could please provide us with some advice.
Thank you in advance

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux athena-master1 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           125Gi        29Gi       5.9Gi       7.8Gi        90Gi        87Gi
Swap:          4.0Gi        63Mi       3.9Gi

```

**Comment by githubsaturn** [comment]
This problem is not related to CapRover, it's a Docker related issue. CapRover's job is to communicate to Docker what changes need to be made. The fact that the replicas are out of sync shows that there is a problem with Docker.

What's the problem and how you can fix it:
There is not a specific problem that causes this. But generally speaking, it's likely because Docker fails to shut down / start up your services easily. Suggest creating a new service, very simple service to isolate any issues with the code. Probably just a simple nginx container. If the problem still happens with the simple nginx service, it's probably your host that is causing issues.

You can also post your issue in Docker github - they might have a solution for this. 
https://github.com/moby/moby/issues/
