### ISSUE TITLE
SNI Extension

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1585]
One of my apps deployed via CapRover sends request to a remote service to retrieve data.  I recently had a notice from them to say that "we will be requiring that SNI extensions be enabled for all API requests".  I'm slightly lost as to whether any changes will be required when sending requests from an https-enabled CapRover app.  I'm just sending these requests from a node app using the [`request` module](https://www.npmjs.com/package/request), or more recently the [`gaxios` module](https://www.npmjs.com/package/gaxios) since `request` is now deprecated.

**Comment by githubsaturn** [comment]
Not sure what the requirements here are. But generally speaking, "sending requests" has nothing to do with https state of your caprover app. The HTTPS only plays a role for incoming traffic.
