### ISSUE TITLE
[Deployment Issue] "SSH Connection error!!" message while trying to add cluster nodes

### ISSUE THREAD

**Issue by Zulfiqar-Qureshi** [caprover/caprover#1590]
Whenever i am trying to add a new node (DO droplet) into the cluster as a worker node, i am getting status 1000, SSH Connection error!!.

I don't know what i am doing wrong here, the ip is correct as well as the private key ( i used this key to ssh manually and it worked )

**Comment by githubsaturn** [comment]
You can view the error from the logs. What does it show?

```
docker service logs captain-captain --follow
```

**Comment by Zulfiqar-Qureshi** [comment]
I fixed the issue by manually adding nodes to the docker swarm.

I now am facing another issue where i have deployed two apps, one golang and one Nodejs project with proper Dockerfiles and it runs just fine, but the url that caprover is spitting out doesn't let the request reach to the appropriate servers, my requests do not reach the golang and nodejs docker containers

**Comment by githubsaturn** [comment]
Do you have all the required ports open? https://caprover.com/docs/firewall.html

You can debug this by shelling into the CapRover container and verify if your service is accessible or not:

```bash
docker exec -it $(docker ps --filter name=captain-captain -q) curl http://srv-captain--YOURAPPNAME:80  -vI
```

What does this print? (replace `YOURAPPNAME` and port `80` with your correct app name and port)
