### ISSUE TITLE
Installation failed: error creating external connectivity network

### ISSUE THREAD

**Issue by Casal0x** [caprover/caprover#1594]
What is the problem?
I have a brand new vps (Hostinger) with only Docker. I tried to install Caprover multiple times but I always get the error message:
error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied

Steps to reproduce the problem:
Run the command from the documentation:
sudo docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

Answers to the following questions where applicable:

Your OS and version?
Ubuntu 18.04 64bit minimal
RAM?
4GB
Any help is appreciated!
Thank you so much for your attention and participation.

![image](https://user-images.githubusercontent.com/4642925/207335976-9dd2bc9b-bf25-4c7a-aafe-7568a9a409ce.png)

**Comment by maietta** [comment]
Sounds to me like you are trying to deploy a VPS with a pre-installed version of Docker not supported by CapRover. It's likely Docker was installed via SNAP or another way and not using Docker's recommended installation method.

I would recommend installing on Debian 11 or Ubuntu 22.04 using Docker's official installation method found here:

https://docs.docker.com/engine/install/debian/

NOTE: The easiest way to install Docker via the official method is with the convenience script found here: https://get.docker.com/

If you are planning on hardening your system, with a rootless docker installation, I would recommend sticking to the Ubuntu Kernel.

**Comment by Casal0x** [comment]
> Sounds to me like you are trying to deploy a VPS with a pre-installed version of Docker not supported by CapRover. It's likely Docker was installed via SNAP or another way and not using Docker's recommended installation method.
> 
> I would recommend installing on Debian 11 or Ubuntu 22.04 using Docker's official installation method found here:
> 
> https://docs.docker.com/engine/install/debian/
> 
> NOTE: The easiest way to install Docker via the official method is with the convenience script found here: https://get.docker.com/
> 
> If you are planning on hardening your system, with a rootless docker installation, I would recommend sticking to the Ubuntu Kernel.

no is not, it is a clean install of docker following steps in the dockers page. image comes with noting installed
