### ISSUE TITLE
login failed for https://registry.server:996/v2/

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1603]
Hi there, 

i am about to set up a registry on my caprover instance, but cannot figure out how the credentials are  ;) 
i did guess its username: captain and pw is the same as i use to login to the captain gui (captain.server.de)?

no matter how i write it, i get this error: 
`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}`

is there any place where i would set the password?

Cheers and thanks!

**Comment by pcace** [comment]
did find this here - wich also has no answer: https://github.com/caprover/caprover/issues/755
or is it just not possible?

**Comment by githubsaturn** [comment]
self hosted registry password is not meant to be used by the end user, it's managed by CapRover. 

But if you really wanna see the password you'll can run a [caprover api](https://github.com/caprover/caprover-cli#api) with these config:
```
{
  "caproverName": "your-caprover-server-name",
  "path": "/user/registries",
  "method": "GET",
  "data": {
  }
}
```

Note that this is an advanced function and it's only meant for advanced users who know what they are doing. Hence no documentation is provided.
