### ISSUE TITLE
How to reuse the docker image which has been built by Caprover?

### ISSUE THREAD

**Issue by jerinpetergeorge** [caprover/caprover#1604]
Hi,

I'm trying to deploy a [Django](https://www.djangoproject.com/) app along with [Celery](https://docs.celeryq.dev/). As most of us already know, both these services share the _same_ application code, but the run commands (or entrypoints) are different.

* Django start command - `gunicorn path.to.wsgi:application --log-level=DEBUG`
* Celery start command - `celery -A path.to.app worker --loglevel=debug`

**Note**: These two services share a few services like `Redis` and `PostgreSQL` (or `MySQL`) which are also deployed within CapRover.

What I have done so far is,
* Created an app for `Django`, named `myapp-django`
* Created an app for `Celery`, named `myapp-celery-worker`
* Created an app for `Redis` named `myapp-redis`
* Created an app for `PostgreSQL` named `myapp-postgresql`
* set auto-deploy on `master` branch via GH webhook for `myapp-django`. This builds docker image and uploads to (local) registry - something like `registry.my.site.com:996/captain/img-captain-myapp-django:XYZ`

____________________________________

### Question

How can I reuse the ***`registry.my.site.com:996/captain/img-captain-myapp-django:XYZ`*** docker image with **`myapp-celery-worker`** as well?

**Comment by githubsaturn** [comment]
You can't reuse the same image because the command is different anyways.

However, if you are comfortable with override commands on Docker, you can reuse the exact same image, provided that you change the command at the service level:

```
docker service update --entrypoint	/your/new/command srv-captain--yourapp-celery
```

Note that this is an advance usecase and you should only do this if you're familiar with entrypoint vs command for docker.
