### ISSUE TITLE
[FEATURE] Change label from `Save & Update` to `Save & Restart`

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1610]
Change label from `Save & Update` to `Save & Restart` to indicate that it is not just updating but also restarting the container/app.

Maybe `Save & Recreate` is also useful?

It is a great, but hidden feature that clicking this button will restart the app …

**Comment by zenflow** [comment]
Wait a sec.. does it restart the container though?

**Comment by githubsaturn** [comment]
Yes - changing any parameter in a docker container restarts that container. It's done by Docker swarm.

**Comment by zenflow** [comment]
If I click the button without editing any parameter first, does it restart then? No, right?
Or if I edit just the nginx config (which isn't a parameter for the docker container) and then click the button, does it restart then?

**Comment by githubsaturn** [comment]
It does! There is a force update label that gets updated to force restart. There was a discussion at some point to have another option to update only if the docker object is changed, but for the sake of simplicity in the UI we decided to keep it simple.

**Comment by zenflow** [comment]
Then I'm +1 for this suggested change. To me, "update" != "restart". Actually to me "update" ≈ "save" so the current label seems somewhat redundant. Just my 2 cents.
