### ISSUE TITLE
access persistant data from apps?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1611]
hi there, 

what would be the way to go if need to change some data on a app with persistant data?

Cheers and thanks!

**Comment by githubsaturn** [comment]
Assuming you want to access the attached volume:
- Run `docker volume ls` and find the volume that you want to explore
- Run `docker volume inspect <YOUR-VOLUME-NAME>` and record the mounting location
- `cd /your/mounting/location` and change the data as needed.

**Comment by Niek** [comment]
It would be a nice idea though to embed a simple file explorer + editor for the volumes. Maybe by embedding https://github.com/tenox7/wfm?

**Comment by githubsaturn** [comment]
@Niek - Thre is already a number of file explorers available as one click apps. You can simply mount any volumes and access the files. You can check out `filebrowser` app.

**Comment by Niek** [comment]
Good idea @githubsaturn! Although a "deeper" integration (e.g. generating the filebrowser config with paths mapped to the caprover volumes) would be nice, similar to how netdata is integrated.
