### ISSUE TITLE
Port timed out: 80

### ISSUE THREAD

**Issue by bob448** [caprover/caprover#1612]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I can't install caprover. It says "port timed out: 80."
Steps to reproduce the problem:
1. Run the docker run command.
2. Timed out.
Output of the following command on your server:

> `Captain Starting ...
> Installing Captain Service ...
>      
>  Installation of CapRover is starting...     
> For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
>      
>      
>  
>  
>  
>  >>> Checking System Compatibility <<<
>    Docker Version passed.
> ******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
>    X86 CPU detected.
>    Total RAM 12456 MB
>  
>  
> Are your trying to run CapRover on a local machine or a machine without public IP?
> In that case, you need to add this to your installation command:
>     -e MAIN_NODE_IP_ADDRESS='127.0.0.1'   
>  
>  
>  
> Otherwise, if you are running CapRover on a VPS with public IP:
> Your firewall may have been blocking an in-use port: 80
> A simple solution on Ubuntu systems is to run "ufw disable" (security risk)
> Or [recommended] just allowing necessary ports:
> ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp; 
>      
>      
> See docs for more details on how to fix firewall issues
>  
> Finally, if you are an advanced user, and you want to bypass this check (NOT RECOMMENDED),
> you can append the docker command with an addition flag: -e BY_PASS_PROXY_CHECK='TRUE'
>  
>  
> Installation failed.
> Error: Port timed out: 80
>     at Timeout._onTimeout (/usr/src/app/built/utils/CaptainInstaller.js:137:20)
>     at listOnTimeout (internal/timers.js:557:17)
>     at processTimers (internal/timers.js:500:7)
> `

```
uname -a && lsb_release -a && free -h
```

**Comment by mmarkell** [comment]
what was the solution?

**Comment by githubsaturn** [comment]
Port timeout means that your port is closed. It's outside of CapRover, but here are some hints:
> Are your trying to run CapRover on a local machine or a machine without public IP?
In that case, you need to add this to your installation command:
-e MAIN_NODE_IP_ADDRESS='127.0.0.1'
> 
> Otherwise, if you are running CapRover on a VPS with public IP:
Your firewall may have been blocking an in-use port: 80
A simple solution on Ubuntu systems is to run "ufw disable" (security risk)
Or [recommended] just allowing necessary ports:
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;
