### ISSUE TITLE
[FEATURE] Ability to stop app containers

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1617]
In the `HTTP Settings` of our apps, we have the ability to `not expose as web-app`, but it would also be nice to stop an app (container) entirely from running.

**Comment by githubsaturn** [comment]
Simply set the instance count to zero

**Comment by JonathanDoelan** [comment]
Oh I did not know that. How could I?
@githubsaturn Don’t you think it would be better to give users a hint that setting the instance count to zero is equal to stopping the container — like a short line of text below the field or a hint in the documentation? Or to provide a button `Stop Container`?

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/209406484-1a859085-0a74-4c2e-8deb-7a04ab119547.png)

No - CapRover is built on simplicity. We won't be adding buttons here and there just to increase the visibility or else in a year CapRover looks like this:

![image](https://user-images.githubusercontent.com/10582082/209406543-3b13e79b-3ab7-4890-bad7-48d06ec22b41.png)
