### ISSUE TITLE
[FEATURE] Store deployment method

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1619]
Text field contents of the deployment methods are not stored. For example if I insert a caption-definition in `Method 5: Deploy captain-definition file`, the next time I visit the page, the text field is empty. Same goes with `Method 6: Deploy via ImageName`.

This makes it hard to redeploy.

Solution: Store the text inside the deployment method.

**Comment by githubsaturn** [comment]
This is by design. Deploys are ephemeral by design.

**Comment by JonathanDoelan** [comment]
@githubsaturn Is it user friendly too?

**Comment by githubsaturn** [comment]
Yes. It is.
