### ISSUE TITLE
[FEATURE] Add a link to the header of the app detail page

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1620]
Would be nice to have an extra link (maybe an icon) at the header of the app detail page that opens the (exposed) web-app.

Maybe a link-icon close to the rename- and add-description-icon would be nice.

**Comment by githubsaturn** [comment]
There is already a link to the URL. CapRover design philosophy is around simplicity and avoiding duplication as much as possible.

**Comment by JonathanDoelan** [comment]
@githubsaturn I understand, but from a user perspective and compared to other service providers, I would wish to have that option.

**Comment by githubsaturn** [comment]
These are UI designs that were made throughout the history of CapRover. As mentioned in the [other comment](https://github.com/caprover/caprover/issues/1617#issuecomment-1364343244), CapRover is deliberately built to avoid duplications, unless it has a large demand
