### ISSUE TITLE
[Question] When do I have to increase the instance count of an app?

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1624]
When do I have to increase the instance count of an app?

I have read this https://github.com/caprover/caprover/issues/453#issuecomment-510727161, and I was wondering if increasing the instance count only make sense if I want to take advantage of a second cpu core?

**Comment by githubsaturn** [comment]
It's a docker swarm capability that is exposed through CapRover. The discussion is beyond just answering in this comment. But your initial guess isn't correct. Mutlithreaded applications make use of mutliple cores in one instance. If you're interested in this you can read many books that are available, for example this: https://www.amazon.com/Java-Threads-Understanding-Concurrent-Programming/dp/0596007825
