### ISSUE TITLE
Run container as non-root

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1625]
if you `docker exec -it $(docker ps --filter name=captain-captain -q) bash` into the `captain` container and run `whoami` it outputs `root`. Wouldn’t it be better to run the container as a non-root user? There are lot’s of [articles](https://stackoverflow.com/questions/19054029/security-of-docker-as-it-runs-as-root-user) out there.

**Comment by githubsaturn** [comment]
CapRover doesn't control that. Plus Docker uses namespaces and cgroups to control what root can do in a container. Give it a shot. Try rebooting your host from a root from within the container.
