### ISSUE TITLE
[Question] Nginx container fails after restart

### ISSUE THREAD

**Issue by ToS0** [caprover/caprover#1627]
Hello, I had CapRover (CR) with Nextcloud (NC) running for several months. Today I just changed the NC data folder to a backup from last week and restarted the host. Just a simple change. But then the Nginx and the main NC container did not start up. Then I even reverted the whole CR VM back to a working snapshow, but still the same result. This is very strange.

After the following commands, the container finally starts so I can access the CR UI again:
_docker service update captain-captain --force
docker service logs captain-nginx --since 10m --follow_

However, when trying to reach the NC UI, Nginx gives a 502 error. In the logs it says:
_/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
[error] 19#19: *74 srv-captain--nc could not be resolved (3: Host not found)_

I assume, Nginx is somehow not receiving the right configs - but I don't know why - and how to fix it.

Thanks for looking into the issue!

**Comment by ToS0** [comment]
It seems the Nginx container is loading some configs of/for the app containers - and if these are erroneous, the container will fail. However, some magic in "docker service update captain-captain --force" fixed this problem somehow.

The NC container did not start, because the data dir had a different version. After updating the app via the CR UI everything was fine again.

Please correct me, if I am wrong - I am still learning about Docker and CR. Thanks anyway for this beautiful piece of code!

**Comment by githubsaturn** [comment]
This error:
```
[error] 19#19: *74 srv-captain--nc could not be resolved (3: Host not found)
```
was the cause behind your application not starting up. And that's because your container was dead when nginx wanted to boot up. 

Restarting `captain-captain` service fixed the issue because CapRover re-initializes the entire config directory for nginx as it boots up.
