### ISSUE TITLE
[Deployment Issue] Caprover subdomain not working

### ISSUE THREAD

**Issue by tanishqdaiya** [caprover/caprover#1630]
I used the CapRover app on the DigitalOcean marketplace and I'm facing a few issues. Here are my observations
- [x] I can access the CapRover login page on the IP Address of my VPS
- [x] I can log in successfully
- [x] I can see the "Nothing here yet :/" page
- [x] But the CLI still says `Cannot verify that << domain >> points to your server IP. Are you sure that you setup your DNS to point << domain >> to << IP >>?`
- [ ] I can access the captain subdomain
- [x] Pointed my domain to server IP
- [x] Still doesn't work

I am a beginner so, I can't figure out how I can resolve the issue. Thanks

**Comment by githubsaturn** [comment]
It takes some time for the DNS to be propagated (up to 24hr).


If you're sure that you've set up your domain correctly, you can bypass the domain verification check done by CapRover:
Simply run this on your server:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```
