### ISSUE TITLE
Caprover generates wrong ssl certificates?!

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1631]
Hi, 

i have a simple nginx webserver app (deployed via docker image) running here (listening on port 80). if i enable ssl, caprover seems to successfully enable ssl but generates a weird ssl certificate: 

<img width="553" alt="Bildschirm­foto 2023-01-04 um 14 32 30" src="https://user-images.githubusercontent.com/1011875/210566187-99b51ba7-1bb3-405c-a0a8-aa348dda2556.png">

its trange, because on other apps made similarly it works. 

Where can i start looking for the problem? Or is this somehow known?

Thanks a lot!

**Comment by githubsaturn** [comment]
This is the self signed certificate that CapRover uses for catch-all blocks. You should not see this. 

Here is what to try:
1- Create a new app `test-app`
2- Go to deployment tab and under "Method 6: Deploy via ImageName", deploy a new image `nginx:alpine`
3- Open the app and make sure you see the default nginx screen
4- Enable HTTPS
5- Retry the app, does it work?
6- Go to deployment tab and under "Method 6: Deploy via ImageName", deploy a new image, this time your own custom nginx image. Does this work?

If not, take a screenshot of your HTTP settings of your app, and the deployment tab. Also submit the URL of your app.

**Comment by pcace** [comment]
Hi, thank you so much, i did up following this https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui
wich worked.
next time ill try your solution. 
its kind of weird that it happened in the first place.
