### ISSUE TITLE
Caprover API for NODEJS

### ISSUE THREAD

**Issue by merchant862** [caprover/caprover#1632]
Hi folks, I have deployed caprover to a VPS, I want to access all of the caprover features including app creation, app build, domain pointing, and all that stuff programmatically using API in node js, is that possible because I did not find this in the docs and I need that for a project.

Thanks in advance if anyone can help.

**Comment by cudesico** [comment]
I think that at the moment you can deploy APIs managing your own containers from your server, I have not been able to find anything similar to deploy APIs from the same caprever

**Comment by githubsaturn** [comment]
No official nodejs module at this point. But there are other unofficial modules built by the community, for example, here is a python module:
https://github.com/ak4zh/caprover-api


Feel free to create a nodejs module.
