### ISSUE TITLE
[Deployment Issue] NGINX 502 Error when making API requests from Rust app

### ISSUE THREAD

**Issue by SimbaNinja917** [caprover/caprover#1634]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
`NGINX 502 Error :/` after successful deployment of rust app. Deployment log is good, no errors.  The issue is only with the particular route `/play?term=xyz` This route makes API/Fetch request to an external website and return the json. The app and the problematic route `/play?term=xyz` works fine on local computer. Other routes work fine on local and VPS.

If applicable, content of `captain-definition` file:
```
{
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

.Dockerfile
```
FROM rust:alpine3.17
COPY . .
RUN apk add libressl-dev
RUN apk add --no-cache musl-dev
RUN cargo build --release
EXPOSE 3000
CMD [ "cargo","run","--release"]

```

Steps to reproduce the problem:
Deploy the following script: 

Cargo.toml 
```
[dependencies]
tokio = { version = "1.23.1", features = ["full"] }
reqwest = { version = "0.11.13", features = ["json"] } # reqwest with JSON parsing support
actix-web = "4"
serde = { version = "1.0.152", features = ["derive"] }
log = "0.4.17"
easy-http-request = "0.2.13"
```

Main.rs 
```
use actix_web::{ web, App, HttpResponse, HttpServer };
use serde::{ Deserialize };
mod play;

async fn main() -> std::io::Result<()> {
    let server = HttpServer::new(|| {
        App::new()
            .route("/play", web::get().to(do_play)
    });

    println!("Serving now on http://0.0.0.0:3000 ...");

    server.bind(("0.0.0.0", 3000))?.run().await
}

async fn do_play(info: web::Query<Info>) -> HttpResponse {
    let play = play::play(&info.term).await.expect("Error in the request");
    println!("{} -> {}", info.term, play);
    return HttpResponse::Ok().content_type("text/plain").body(play);
}```

Play.rs
```
// play.rs 
use reqwest;
use serde::{ Deserialize, Serialize };
pub async fn play(subtitle: &str) -> Result<String, Box<dyn std::error::Error>> {
    
    // uncomment this following part to reproduce problem
    // let client = reqwest::Client::new();
    // let response1 = client
    //     .get("https://api.someweb.com")
    //     .query(
    //         &[
    //             ("text", subtitle),
    //             ("argument1", "tic"),
    //             ("argument2", "tac"),
    //         ]
    //     )
    //     .send().await?
    //     // .text().await?;
    //     .json::<GETAPIResponse>().await?; 
    // let x = &response1.play[0].text;
    // return Ok(x.to_string()); 

    return Ok("good".to_string()); //returning a dummy string instead of reqwest response // comment this part when uncomment the previous block
}
```

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
```
root@fc344:~# uname -a && lsb_release -a && free -h
Linux fc344 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           9.7Gi       3.6Gi       982Mi        34Mi       5.2Gi       5.8Gi
Swap:             0B          0B          0B
```

**Comment by githubsaturn** [comment]
> The issue is only with the particular route /play?term=xyz

This clearly shows that the problem is with your specific app, not CapRover. 502 is a gateway error, meaning that the downstream failed to respond successfully. 

Unfortunately there is nothing that we can do on CapRover side. I suggest you post your question on stackoverflow. But as a starter, I suggest adding a log before `return Ok(x.to_string()); ` : 

```
println!(x.to_string()); 
```
Make sure that this line prints on your logs.
