### ISSUE TITLE
How to access app sh or bash 

### ISSUE THREAD

**Issue by hatemragab** [caprover/caprover#1635]
How to access app sh from dashboard is this available?

**Comment by wzulfikar** [comment]
I don’t think Caprover allows us to access sh from dashboard. [The docs](https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container) suggests connecting to the container, eg.:
```sh
docker exec -it $(docker ps --filter name=srv-captain--myappname -q) /bin/sh
```

Personally, I have Portainer running and I use its UI to connect to sh/bash/etc of my container.
