### ISSUE TITLE
Limit ram usage of one app?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1638]
Hi is there any way to limit the possible ram usage of one app? 
i have build an api wich can use up a lot of memory. it can (it happened once) crash or lock up the machine and all its containers when using too much ram. 
can it be limited from caprover?

thanks a lot!

**Comment by githubsaturn** [comment]
https://caprover.com/docs/service-update-override.html#sample-use-cases

**Comment by githubsaturn** [comment]
also: https://github.com/caprover/caprover/issues/1068
