### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by maietta** [caprover/caprover#1639]
As it turns out, a NodeJS app that have been built prior to deployment to CapRover cannot pickup any environment variables provided by CapRover. After two full days of trial and error and finally isolating my issue, this is my conclusion.

For a normal NodeJS app that isn't "built" with a built system line Vite, Webpack, Astro, etc, the app will deploy just fine and adding or changing any enviornment variables within the CapRover UI will in fact reflect in the app without trouble.

I am looking at potentially building a Github Action or some other tool to collect up my environment variables set for my app in CapRover and providing them to the build system prior to deployment to CapRover, but this seems like a stupid solution.

My requirements are as follows:
- Do not ship source code to CapRover.
- Avoid vendor lock for my deployment process, if possible. (i.e., avoid need for Github/Gitlab/Bitbucket, etc.)

It's my understanding the app token for deployments is only for deployments. It'd be awesome if I could also use the token to fetch the environment variables as part of my offline build process before my app is built.

I am very much open to ideas.

**Comment by githubsaturn** [comment]
> Vite, Webpack, Astro, 

These are not NodeJS frameworks, these are frontend build systems. The limitation here is not CapRover specific. Frontend JS code can never pickup the environmental variables from the system. During the build process, env vars get picked up by the build system (Webpack etc), and they replace the variable references in the frontend code.

Example:
![image](https://user-images.githubusercontent.com/10582082/213073989-178c4758-1c62-475f-8595-be63c8769e73.png)

https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by maietta** [comment]
Thank you, Karsa. In all my research, i never once discovered this information but it does confirm my observations after extensive testing.

I didn't see a way in Caprover API source code, but can the app token be used to extract environment variables? 🤔 

If not, I wonder if this could be a good feature request and I'd be glad to implement it in a PR.

I started working a primitive deployment tool for my scenario in the meantime.

Thoughts?

**Comment by githubsaturn** [comment]
App token is equivalent to deploy keys. Deploy keys are one-way operations for deployments. The benefit of app tokens is their limited scope (just deployment). Creating a way for app tokens to read the data creates a two-way channel (both for deployment and reading the data) which defeats the purpose of limited scope for app tokens.

For your use-case, the right way is to host your env vars somewhere else and fetch them during build. Typically these variables sit in CI/CD pipeline (for example github actions). If you don't want to use github actions, you can always host your own CI/CD pipeline (Jenkins, etc).
