### ISSUE TITLE
Access an app through a subdirectory of another app

### ISSUE THREAD

**Issue by ThisIsMrAli** [caprover/caprover#1641]
I have 2 apps on my caprover domain.

1. app 1 is accessible on **sample.com**
2. app 2 is accessible on **blog.sample.com**

Instead of accessing app 2 on **blog.sample.com** i would like to access it on **sample.com/blog**.

I've had a look at the documentation but could not figure out how to deploy apps using subdirectory rather than subdomain. Is it possible?

**Comment by githubsaturn** [comment]
CapRover does not perform any additional routing like this. In order to achieve this, you need to manually edit nginx configs. But it's not a beginner friendly process. If you're not familiar with how it works, I suggest staying away from it as it can break all your websites.
