### ISSUE TITLE
Netdata login error. 

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1649]
My problem is, when i enable netdata in monitoring panel and click to open, netdata instantly returns me this.
`
"status": 1106,
"description": "Auth token corrupted",
"data": {}
`

Can anyone help me with this. ?!?!?

**Comment by githubsaturn** [comment]
Very likely your browser has old cached auth token. Log out and log back in. This should fix it right away.

**Comment by DaniHRE** [comment]
No, does not work for me

**Comment by githubsaturn** [comment]
Just to confirm, you'd log in and then go to monitoring, then click and open netdata and it doesn't work?

Do you also see the same error on the demo instance?

Click on live demo on CapRover.com

**Comment by DaniHRE** [comment]
In demo instance I see normally netdata. 
But in my private instance I can't see the panel. I'm stuck in error page. showing me error 1106.
Containing this error message.
{
  "status": 1106,
  "description": "Auth token corrupted"
}

**Comment by DaniHRE** [comment]
I've been tried the incognito window and edge, opera gx and Firefox browser.
Really don't open and I don't know.

**Comment by DaniHRE** [comment]
![image](https://user-images.githubusercontent.com/62768034/215853905-95259bef-57b5-441a-8b8e-4eb73ac63a8e.png)
#### **Are you using version 0.0.1 in CapRover demo instance?. It's correctly?, because the main version is v1.10.1. I'm confused.**
![image](https://user-images.githubusercontent.com/62768034/215854159-f15a3d02-5e51-45f0-ab2f-4d22bad0d3b8.png)

**Comment by DaniHRE** [comment]
**I can't see there cookies in my browser because i'm stuck in this page...**

![image](https://user-images.githubusercontent.com/62768034/216206938-684752dc-81c4-4f4c-a091-d05e38ea86b9.png)

**Comment by githubsaturn** [comment]
Cookies are there, even for this error page. Just click on one of the request, like this one, and you'll see the cookies panel.

![image](https://user-images.githubusercontent.com/10582082/216232514-1d52f9e4-7393-4bfd-b56d-c4861abf6d0f.png)

**Comment by DaniHRE** [comment]
This is the result when i click in "net-data-monitor/".

This screenshot is diferent from the other because i'm in linux now.

![image](https://user-images.githubusercontent.com/62768034/216301351-364141c6-3505-4055-8fb0-9654bccb5286.png)

**Comment by githubsaturn** [comment]
Okay, yea I probably need access to an instance with the issue to be able to debug this. Can you please create an instance with no private information and share the login info with me?

If that's not possible, here is the next step for you to try: check if set-cookie is being sent as part of the response from `/login`
example:
![image](https://user-images.githubusercontent.com/10582082/216502174-862773ab-a34e-4b81-a24d-6ad5918382be.png)

**Comment by DaniHRE** [comment]
I Don't know how to create a private instance and show you to connect.
You have discord, or something like this? to talk more about this error.

When i login in the system, set-cookie is send in reponse header.

![image](https://user-images.githubusercontent.com/62768034/216579976-7c75b7b6-3b8f-42af-ac2d-966f67d57ea4.png)

**Comment by DaniHRE** [comment]
When passing the "cookieAuthLogin" that is passed through the set-cookie for the netdata page cookie manually, the netdata load with sucess.

![image](https://user-images.githubusercontent.com/62768034/216582498-3de613ec-c936-4ebf-b01f-25f4695963d7.png)

**Comment by githubsaturn** [comment]
Ahhh you didn't mention you're running CapRover locally. Of course it doesn't work.

Cookies are set on a domain! That's how HTTP cookies work. You are logging in via `localhost:3000`... And then trying to open netdata on a fulldomain and of course your browser doesn't pass the domain.

To fix, just follow the guides: https://caprover.com/docs/get-started.html#step-2-connect-root-domain

Set up a proper FQDN domain and it will work.  


![image](https://user-images.githubusercontent.com/10582082/216649788-126a6e62-a04f-4fa6-a2c8-49d45fd38c37.png)

**Comment by JustinGuese** [comment]
I have the same problem, I think its occurring when I log in with the "use local storage -> most persistent" option

solution is to logout & log in again, or use the first option right away

**Comment by wout** [comment]
Same here. I am also using a local storage login. The cookie and session storage options both work fine.
