### ISSUE TITLE
Usage of hidden root domain?

### ISSUE THREAD

**Issue by artt** [caprover/caprover#1651]
Trying to figure out how to not make my root domain so obvious. Basically, if someone monitors my API calls to `appname.api.mydomain.com`, they can just change `appname` to `captain` and get to the logon screen.

The [doc](https://caprover.com/docs/best-practices.html#hidden-root-domain) mentioned about hiding the root domain, so the root domain would be something like `captain.something.api.mydomain.com`, but then my API calls would be to `appname.something.api.mydomain.com` so it doesn't really help obscuring things.

One of the ways to fix this is to allow users to change the root domain from `captain` to something the user can specify. Might be worth looking at it again? https://github.com/caprover/caprover/issues/1144

**Comment by githubsaturn** [comment]
You don't need to publish `appname.something.api.mydomain.com`. You can connect many custom domains and publish those.

https://github.com/caprover/caprover/issues/1144 is also fully implemented, you can use it. 

![image](https://user-images.githubusercontent.com/10582082/215681323-dd785494-c551-4aa7-ae7f-f8644d174a24.png)

**Comment by artt** [comment]
@githubsaturn Ah thanks a lot! Given that I've set up my server, could I just change my root domain? I'm a bit scared of this warning. What does it mean exactly?

> You can always update your root domain, but be careful! Your SSL certificates will get revoked because of this domain change.

**Comment by jonaskuske** [comment]
FYI: Imo usage of the "hidden root domain" pattern is much more convenient if you do set `root.com` as root domain, but then configure `captain.something` as `"captainSubDomain"`, currently only possible via `/captain/data/config-override.json` unfortunately.

This way you don't have to change HTTP settings when you create a new app. Apps are automatically exposed on `appname.root.com` and `captain.root.com` is empty, as the dashboard is exposed on `captain.something.root.com`.

**Comment by artt** [comment]
So the inconveniences mentioned in #1144 is fixed when @githubsaturn says it's "fully implemented"?

**Comment by jonaskuske** [comment]
Not sure. Been using this setup for quite some time now and the only issue I encountered was that generated webhook URLs used the wrong subdomain, for which I implemented a fix. If that was the only issue then it's indeed fully implemented, but not fully published as there hasn't been a release for more than a year, so the fix is only available for caprover-edge.

I don't use the caprover CLI though, so can't say anything about that. But I can do some testing in the coming days, if you want.

**Comment by seguri** [comment]
Does anybody know how to customize the captain domain on a caprover instance that is already setup and running? The steps described in 1144 look more like something to do during the first setup, and the [docs](https://caprover.com/docs/best-practices.html#hidden-root-domain) also do not mention existing systems.

**Comment by githubsaturn** [comment]
@seguri - you can always change domain after installation. I just checked and it looks like there is bug that prevents the button from showing up! :man_facepalming: 
I [just fixed it](https://github.com/caprover/caprover-frontend/commit/5c318f9907d053141a2ac72ef52933e82594411c) but it won't be available until the next release. 

In the meantime, if you hover over the button, it'll appear. 
![image](https://github.com/user-attachments/assets/6868fa81-289c-4e7b-90ba-2943202eb060)

**Comment by seguri** [comment]
@githubsaturn thanks for fixing this issue! what I'm asking here though (and I thought it was the topic of the thread) is how to change the `captain.` domain through what is described as "hidden root domain" feature, not how to change the root domain. I just don't want to have `captain.server.example.com`, as it's very easy to guess and prone to being attacked. Thanks

**Comment by jonaskuske** [comment]
Did you try setting `captainSubDomain` in a `config-override.json`?

**Comment by seguri** [comment]
Yes. What now? My server and its apps are now unreachable. I've tried:
- captain-new.server.example.com
- server.example.com:3000
both HTTP and HTTPS.

**Comment by githubsaturn** [comment]
Did you fully delete the file and restart your server?

**Comment by githubsaturn** [comment]
Yes, you cannot edit an existing system as it will mess up with the certificates and healthcheck.
