### ISSUE TITLE
Unable to deploy any application

### ISSUE THREAD

**Issue by imbev** [caprover/caprover#1657]
I'm trying to deploy FreshRSS, however I am unable to enable HTTPS ("Error 1107 Verification failed") and the relevant subdomain returns "Nothing here yet :/".

Steps to reproduce the problem:

- Click "One Click Apps/Databases"
- Click "FreshRSS"
- Enter "freshrss" into the "App Name" field
- Click "Deploy", wait 20 seconds, and click "Finish"
- Click relevant link under the "Open" column and observe "Nothing here yet :/".

The output is the following:
```
Linux 172-redacted-59.ip.linodeusercontent.com 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 15 07:49:10 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
-bash: lsb_release: command not found
```
After removing `lsb_release -a &&`:
```
Linux 172-redacted-59.ip.linodeusercontent.com 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 15 07:49:10 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
               total        used        free      shared  buff/cache   available
Mem:           956Mi       639Mi        83Mi        37Mi       430Mi       317Mi
Swap:          575Mi       399Mi       176Mi
```

I've also tried the following with no change:
- Random app name
- Changing "Environment" field to development
- Manually running the docker image via "Create New App" and relevant configuration

Running the docker image works fine on my PC.

My host distro is AlmaLinux 9 on Linode.

Also tried using several other docker images.

**Comment by githubsaturn** [comment]
- Do you have an arm CPU to X86?
- What's the output of `docker service ls` ?
- When you say "Also tried using several other docker images", does it mean you've tried other apps and none of the apps work?

**Comment by imbev** [comment]
- I'm using an x86 instance
- ```
y6noebcxupyr   captain-captain                    replicated   1/1        caprover/caprover:1.10.1           
tb2ymz0fgqj4   captain-certbot                    replicated   1/1        caprover/certbot-sleeping:v1.6.0   
hgl0pnowoomy   captain-nginx                      replicated   0/1        nginx:1                            
obexivb998a6   srv-captain--freshrss              replicated   1/1        freshrss/freshrss:1.20.0           
u8151e66msve   srv-captain--freshrss-postgresql   replicated   1/1        postgres:15.0                      
6k9vk7xfvuda   srv-captain--nextcloud             replicated   1/1        nextcloud:21.0.1                   
7po53pn02y7a   srv-captain--nextcloud-cron        replicated   1/1        img-captain-nextcloud-cron:1       
x4jlj9knpz8u   srv-captain--nextcloud-db          replicated   1/1        mariadb:10.5.9                     
tx18nvyvvj9p   srv-captain--nextcloud-redis       replicated   1/1        redis:6.2.2                        
sc0kd56jlvzb   srv-captain--www                   replicated   1/1        b4bz/homer  
```
- I've tried running other docker images from dockerhub  such as b4bz/homer.

**Comment by imbev** [comment]
After following some of the troubleshooting steps, Caprover won't start.
The logs show the following:

```
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | February 6th 2023, 2:59:37.613 am    **** Captain is initialized and ready to serve you! ****
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | February 6th 2023, 2:59:38.627 am    Error: Wrapped: Verification Failed for captain.isaacbeverly.net
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | Error: Wrapped: Verification Failed for captain.isaacbeverly.net
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:54:42)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Socket.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at emitErrorNT (internal/streams/destroy.js:106:8)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | February 6th 2023, 2:59:38.628 am    Error: Wrapped: Error        Error: connect ECONNREFUSED 172.104.194.59:80
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | Error: Wrapped: Error        Error: connect ECONNREFUSED 172.104.194.59:80
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at errorize (/usr/src/app/built/utils/Logger.js:7:16)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:55:42)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at ClientRequest.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Socket.socketErrorListener (_http_client.js:475:9)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at Socket.emit (events.js:400:28)
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    |     at emitErrorNT (internal/streams/destroy.js:106:8)
```
There are many retries and health check failures in the log also.

**Comment by githubsaturn** [comment]
I see your nginx container isn't even running:
```
hgl0pnowoomy   captain-nginx                      replicated   0/1        nginx:1                            
```

Are you sure you can even access your dashboard using nginx at all (without port 3000) ? i.e. https://captain.your.domain.com

**Comment by githubsaturn** [comment]
```
captain-captain.1.lrg5o59q4h00@172-104-194-59.ip.linodeusercontent.com    | Error: Wrapped: Verification Failed for captain.isaacbeverly.net
```
Yea this is what the issue is. Your host does not accept incoming traffic from port 80. These ports must be open for CapRover to work:
https://caprover.com/docs/firewall.html

**Comment by imbev** [comment]
> Are you sure you can even access your dashboard using nginx at all (without port 3000) ? i.e. https://captain.your.domain.com/
Until I ran `docker service update captain-captain --force`, yes

**Comment by githubsaturn** [comment]
Ah... Okay... Did you make some nginx changes in the past? Follow this:
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by imbev** [comment]
firewalld is my firewall `Warning: ALREADY_ENABLED: '80:tcp' already in 'public'`

**Comment by imbev** [comment]
I made nginx changes for the nextcloud app to redirect 2 paths another path.

**Comment by githubsaturn** [comment]
yea, that's probably the cause! did you run the fix in the comment above?

**Comment by imbev** [comment]
i somehow skipped that.

after running it, i now have access to the caprover dashboard again

**Comment by imbev** [comment]
that solved my problem, however i now have a different question:

how do i modify my nginx config in a way that doesn't break other apps?

**Comment by githubsaturn** [comment]
nginx modification is an advanced process. Editing it in a way that doesn't break configuration doesn't break other apps. But if you make a mistake in configuration, then your nginx configuration becomes invalid and your entire nginx container fails to load.

> how do i modify my nginx config in a way that doesn't break other apps?

There is no simple answer to this. But generally speaking, all valid commands are mentioned in the official nginx doc.
