### ISSUE TITLE
Development Documentation Status

### ISSUE THREAD

**Issue by dkimot** [caprover/caprover#166]
What is the status of documenting the API? I noticed that it is a TODO in the projects section. Is that still the case? If so, I'd be happy to help. It seems like a good way to familiarize myself with the backend code.

If there is still a need to write the documentation, any formatting requests or examples to model?

**Comment by githubsaturn** [comment]
It was high priority when some people offered to create automated tests for CaptainDuckDuck. It's not high priority anymore, but it's a nice thing to have. 

I don't have any particular formatting in mind. But once you have some smaller parts of it ready, please share it so we can have a look and make modifications in formatting (if necessary)
