### ISSUE TITLE
[Deployment Issue] Discourse app - version 3.1 - 500 error

### ISSUE THREAD

**Issue by KazeroG** [caprover/caprover#1661]
**What is the problem ?**

Issue with deploying Discourse app

**Steps to reproduce the problem:**

Step 1 : ![image](https://user-images.githubusercontent.com/17680194/217356040-6b176e64-0843-41ea-91af-6b35e3100265.png)

Step 2 : ![image](https://user-images.githubusercontent.com/17680194/217356176-539a7643-a2f4-4e13-aa4c-6377172fd21a.PNG)

**Output of the following command on your server:**

![image](https://user-images.githubusercontent.com/17680194/217355507-75b36a9a-4b0d-4653-9d38-3158a8e57973.png)

**Comment by githubsaturn** [comment]
Very likely your server is running out of resources. Try pulling the image first manually and then try one click app:

```
docker pull bitnami/discourse:3.1
```

**Comment by githubsaturn** [comment]
ahhhh actually, it looks like there is no ` bitnami/discourse:3.1` ! That's what causes the issue. 
https://hub.docker.com/r/bitnami/discourse/tags

Try using the default version `2.8.11`. Note that CapRover one click apps are tested with the default version. Even if you use `3.0.1` which exists, there is no guarantee that it'll work. The configurations and environment variables might be different for 3.x.
