### ISSUE TITLE
[FEATURE] App sleep

### ISSUE THREAD

**Issue by rklos** [caprover/caprover#1662]
**Describe the solution you'd like**
Option to put the application into "sleep" mode (after X minutes/hours of inactivity).
Something like the free tier of Heroku: https://blog.heroku.com/app_sleeping_on_heroku
This can be done by reducing the instance count to 0 when there is no traffic through the HTTP proxy. After putting it to sleep, the next request will wake it up.
Yes, some applications may take a long time to wake up, but as the owner of the "environment" you should decide if it is worthwhile to enable this option.
In the meantime, we can display a simple loading page.

It can look like this:
![CleanShot 2023-02-09 at 16 18 44](https://user-images.githubusercontent.com/34719093/217855420-d225a981-da7c-4aab-87b4-5c6c165f179a.png)

**Additional context**
I'm hosting a few "larger" applications. My friends and I only use them from time to time (they don't do any "background stuff"). So, when I know that we won't be using them for a while, I reduce their instance count to 0. After all, I need to restore the previous value to be able to use these applications. It would be nice to do this automatically.

**Comment by githubsaturn** [comment]
While I understand the usefulness behind this feature, it requires re-architecting CapRover. As it stands now, CapRover is just involved during the deployment. 

In fact it's called out as one of the features that CapRover is completely out of the loop post deployment: 
![image](https://user-images.githubusercontent.com/10582082/217985250-161156fa-268e-4ee8-9f19-6754153c6d39.png)
