### ISSUE TITLE
[Question] Is it possible to synchronize the deployment of multiple services?

### ISSUE THREAD

**Issue by gustavotoyota** [caprover/caprover#1663]
I want to deploy multiple services simultaneously in order to prevent data corruption by the communication between services with different versions. Is it possible?

**Comment by githubsaturn** [comment]
No, it's not possible at all. Distributed systems don't work like this. You should design your apps for resiliency to communicate between different versions. 

If you really need this, it's a sign that you don't have a distributed system, you need to bundle them all together in one binary.

Here is a quick read on this: https://stackoverflow.blog/2020/05/13/ensuring-backwards-compatibility-in-distributed-systems/


Also, here is a good book: https://www.amazon.com/Designing-Distributed-Systems-Patterns-Paradigms/dp/1491983647
