### ISSUE TITLE
CapRover Domain Name

### ISSUE THREAD

**Issue by csandreas1** [caprover/caprover#1665]
Hello, I haven't quite understood this section
https://caprover.com/docs/get-started#a-domain-name 

I already own a domain, and setup the below DNS records, how can I serve my app through my domain name without using subdomain wildcard?

e.g. https://webdominar.com

not: https://mywp-wordpress.wd.webdominar.com/2023/02/11/hello-world/

![image](https://user-images.githubusercontent.com/21238024/218254000-c0f50ef1-7179-4116-927d-269523b9519c.png)

![image](https://user-images.githubusercontent.com/21238024/218254775-609fd923-0527-4ab2-9f1d-662ec110a6ad.png)

![image](https://user-images.githubusercontent.com/21238024/218254844-5c7de54d-d331-4aa6-beac-824ac30cd148.png)

**Comment by immersedin** [comment]
@csandreas1 hello, how you resolve this problem?
