### ISSUE TITLE
[FEATURE] Option to start services/containers only if needed

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1667]
Option to start services/containers only if needed. So e.g. when going to `service.captain.example.com` a loading screen could appear while the docker container(s!) start. When they’ve started successfully the loading screen disappears and we can access the service/app. This would be amazing, because we don’t need each app running the whole time! This costs server resources like RAM.

Apps like phpMyAdmin, office apps, file browser, invoicing tools don’t necessarily need to run all the time.

**Comment by maietta** [comment]
Traefik has a community contributed plugin that does this called Sablier. See https://plugins.traefik.io/plugins/633b4658a4caa9ddeffda119/sablier.

CapRover uses Nginx under the hood. Unlike Nginx, Traefik was written with two distict features that makes it a great alternative for proxying traffic to containers. Firstly, it can listen directly to the Docker Events API for updates. Secondly, Traefik was written to hot-reload configurations with no downtime. The two features combined make it possible to detect an incoming request and start up a container and dynamically routing traffic to the new container. The container ID is dynamic and unpredictable unless specifically named.

Sadly, as far as I know, Nginx does not offer any ability for hot-reload or listening to the Docker Events API, thus making it impossible to support such a feature.

With that said, I am slowly, when I can find time, to build a solution to replicate the basic functions of CapRover but using Traefik. This is one of the features I want to support-- the ability to suspend any low traffic services and re-activate them when traffic is received. This was be done per app.

As much as I hate the idea of building and maintaining an alternative to CapRover, I think there's a definite need for people have certain hosting requirements, me being one of that. I do have a project in development for my own needs, but this may expand into a public project in the near future.

Previous mentions or discussions:
https://github.com/caprover/caprover/issues/578
https://github.com/caprover/caprover/issues/779
https://github.com/caprover/caprover/issues/779

**Comment by JonathanDoelan** [comment]
@maietta Thanks. Good to know that there is an existing solution. There are CapRover alternatives like coolify or dokku which use traefik under the hood, but they don't meet all my criteria … that's why I am still here ;)
