### ISSUE TITLE
Permission denied while trying to connect to the Docker daemon

### ISSUE THREAD

**Issue by thomascenni** [caprover/caprover#1670]
Hello,

I'm getting error 1001 from a running Caprover instance and when I do:

```
docker service logs captain-captain --since 5m
```

I get this log:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/services/captain-captain?insertDefaults=false": dial unix /var/run/docker.sock: connect: permission denied
```
```
docker version
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
```

Thanks

**Comment by githubsaturn** [comment]
Looks like your Docker instance has issues. This error is not even thrown by CapRover. It's a Docker error thrown by Docker daemon. Unfortunately, there is nothing on CapRover side to mitigate or provide more context on what this error is. 

Example threads:
- https://stackoverflow.com/questions/47854463/docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socke
- https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue
- https://stackoverflow.com/questions/72684167/why-do-i-still-getting-error-got-permission-denied-while-trying-to-connect-to-t
- https://stackoverflow.com/questions/54523977/docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socke


Most likely you're running docker as a non-root user causing these permission issues.
