### ISSUE TITLE
[Question] root domain VS subdomain

### ISSUE THREAD

**Issue by frelle** [caprover/caprover#1671]
Hi,

Is-it possible to install caprover on a server with the following : 
1) Point @ DNS to a serverA (meaning the root domain will not point to caprover, but somewhere else)
2) Point subdomains (captain,app,....) to a serverB. And I will install caprover into the server B.

In fact, I'm already pointing root domain to a service, but I want to use and create an app with caprover to many other subdomains.

So is it possible to install caprover , saying the root domain is domain.com ( so I can create app.domain.com), but point the root domain to another server?  
I know it's not very logical, but I have a situation like that...

Thank you for the help!!

**Comment by githubsaturn** [comment]
Yes. In fact it's the recommended approach

You can point @ to IP1.

You can point `*.myserver` to IP2.

Now you can install CapRover and it'll be accessible from `captain.myserver.domain.com`
Your apps will be accessible from `app-one.myserver.domain.com`

If you want your app to be available via `app-one.domain.com` you just need to do this:
- Add a new DNS record `app-one.domain.com` to point to IP2
- Go to CapRover dashboard > Apps > app-one > add a custom domain > add `app-one.domain.com`

**Comment by frelle** [comment]
Hi

Thank you for the fast answer, and sorry to reopen the thread.

In your answer, you specified installing caprover in a subdomain. My problem is that I am using Cloudflare, so it will not work with subdomain level 2 ( so for the apps that will be created)

I have made a test on the following use case, and it's working. Can you confirm that caprover will work in such cases: 
Let's say the domain name is : _mydomain.com_ , and the domain where caprover is installed is the _serverA_

- I installed caprover in the _serverA_, and during the step **caprover serversetup** , I specified that the root domain is _mydomain.com_
- I added A record **@** to the _serverB_ (so no caprover installed)
- I added A record **captain** to the _serverA_  (caprover installed)
- I added A record **test** to point to _serverA_
- I installed via caprover an app called _test_

Results : 

1. The URL captain.mydomain.com is working 
2. The URL test.mydomain.com is working

Which is great, but is-it a viable configuration for caprover or I can have some issues in the future? (caprover update or whatelse)

Thank you!!!

**Comment by githubsaturn** [comment]
But you need to disable domain verification by CapRover. 

CapRover checks randomstring.mydomain.com every 5 min to ensure the wildcard dns is working. 


Search for 1107 in the docs to learn how to disable the domain verification.

**Comment by frelle** [comment]
Yes, already did that, it's required to use Cloudflare. 
Thank you for the confirmation!
