### ISSUE TITLE
nodejs project, file upload, it seems that it cannot be stored in the system

### ISSUE THREAD

**Issue by allmors** [caprover/caprover#1673]
The file storage system implemented using nodejs, I don’t know if it’s my problem or the system problem. After the file is uploaded, it cannot be accessed, and it does not prompt 404. The local project is running normally, but it cannot be used normally when it is deployed to caprover.

**Comment by githubsaturn** [comment]
You need to provide more info. It all depends on what you're doing for upload, where the data is stored. Whether the directory is persistent or not. 

Please reopen with more details
