### ISSUE TITLE
Make it easy to delete one-click-installed apps

### ISSUE THREAD

**Issue by delasource** [caprover/caprover#1674]
**Is your feature request related to a problem? Please describe.**
I installed appwrite for experimenting, which consists of so many many images. I had to delete all apps one by one.

**Describe the solution you'd like**
Apps that are installed from the one-click-dictionary and that belong together, should be deletable all at once, including (optionally?) their volumes.

**Describe alternatives you've considered**
Manually deleting (as of now) took me half an hour.

**Comment by borjarobert** [comment]
I've been thinking about it and I would also love to have a way to batch delete images.
It's been particularly hard while writing a new recipe for a one-click-app. Manually deleting 8 or 10 images for every test with a mistake makes the process so much more cumbersome.
Maybe something like a checkbox before every image name and the ability to batch delete all would be a great touch. I haven't looked at the code so I'm not sure of how hard it would be to implement.

**Comment by maietta** [comment]
I recognize the potential usefulness of this feature. However, as a fellow software developer, I see a few challenges that must be addressed.

One of the main issues is that in certain cases, volumes cannot be deleted simultaneously with the application. As a result, a notification would have to be provided for each volume, making a one-by-one approach for app removal preferable.

If a running log is kept that records the actions taken during the removal process, along with any issues encountered (such as failed volume deletions), it could facilitate the batch removal of applications. This could be done either through periodic garbage collection or via manual review and follow-up.

**Comment by Smyja** [comment]
> **Is your feature request related to a problem? Please describe.** I installed appwrite for experimenting, which consists of so many many images. I had to delete all apps one by one.
> 
> **Describe the solution you'd like** Apps that are installed from the one-click-dictionary and that belong together, should be deletable all at once, including (optionally?) their volumes.
> 
> **Describe alternatives you've considered** Manually deleting (as of now) took me half an hour.

how were you able to even delete it?

**Comment by watzon** [comment]
It would be nice if like-services could be grouped, and then those groups could be deleted all in one go. Then one click apps could create a group, and that group could be easily deleted.

Even the ability to delete apps by tag would be better than what we currently have.

**Comment by githubsaturn** [comment]
Yup! There are 2 separate things that need to be done for this feature:
- All services deployed as a one click app should be tagged with a specific tag. e.g. if wordpress is deployed with the name `my-blog`, then the wordpress and the mysql apps should both have `my-blog` tag
- Second thing is to have the ability to delete multiple app at once

These two are fully decoupled, but once they are done, this feature request will automatically be supported!

**Comment by githubsaturn** [comment]
It's done in 1.12 onwards. Simply click on the tag and you can delete multiple apps at the same time.
![image](https://github.com/user-attachments/assets/65aadc2d-a1c7-43d0-b0ed-5fe606f823b8)
