### ISSUE TITLE
Regarding persistent storage

### ISSUE THREAD

**Issue by allmors** [caprover/caprover#1677]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

I am new to dockr. When I use caprover to deploy the image application, I checked the persistent storage option. Due to the mechanism of caprover, the image will be rebuilt every time it is updated. Therefore, the image I uploaded will appear after updating the image. Picture file loss? Please tell me, how can I deal with it, when I update the project to build a new mirror, the image files I have uploaded still exist

**Comment by githubsaturn** [comment]
The persistent directories will be kept during the new deployment. Everything else is wiped. 

Read nore it here:
https://caprover.com/docs/complete-webapp-tutorial.html#persistence-or-not
