### ISSUE TITLE
Restart the container and it will be cloned

### ISSUE THREAD

**Issue by allmors** [caprover/caprover#1680]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

Restart the container, and another container will appear. Is this intentional by caprover? This will take up the system very much, and the cloned ones are running normally after restarting

Steps to reproduce the problem:

Output of the following command on your server:

```
docker restart xxxx
```
![image](https://user-images.githubusercontent.com/93471589/222326453-8c97a71e-072c-4eb7-ab97-a21da96b4b8a.png)

**Comment by githubsaturn** [comment]
This is done by Docker swarm. The only container should die quickly. Also, you need to use docker swarm commands, not docker container commands.

for example, to restart an app, run
```
docker service update srv-captain--myappname --force
```
