### ISSUE TITLE
Bad Gateway 502 One-Click-App pocketbase 

### ISSUE THREAD

**Issue by nadveos** [caprover/caprover#1682]
I have this error  after install OCA pocketbase

`srv-captain--saltita.1.4w8wi2f9kd26@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.nfoz0q67xujv@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.l134zycimrk2@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.zonxcr3jrgwf@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.qgvf6lv21p9e@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.n9g89y5ojv3p@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.a65c903at3lr@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.r7jr1brll3su@meapp    | exec /pb/pocketbase: exec format error
srv-captain--saltita.1.w1u0nxltqh3g@meapp    | exec /pb/pocketbase: exec format error
`
I run i fresh vps in oraclecloud

**Comment by githubsaturn** [comment]
Very likely you're using an ARM cpu and this image is built for x86.

**Comment by nadveos** [comment]
in oficial https://caprover.com/docs/get-started.html#b2-server-specs 
B2) Server Specs
CPU Architecture: CapRover source code is compatible with any CPU architecture and the Docker build available on Docker Hub is built for AMD64 (X86), ARM64, and ARMV7 CPUs.

Recommended Stack: CapRover is tested on Ubuntu 18.04 and Docker 19.03. If you're using CapRover on a different OS, you might want to look at [Docker Docs](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#supported-storage-drivers-per-linux-distribution).

Ubuntu 22.04: The amd64 and aarch64 distributions have been tested by members of the Caprover community to be fully functional since its release. Ubuntu 22.04 will continue to receive security updates until April 2027 at least.

Ubuntu 20.04: There are some issues with Docker on Ubuntu 20, see [this one](https://github.com/moby/moby/issues/41825) and [another one](https://github.com/moby/moby/issues/41775) for example. Use Ubuntu 18.04 to minimize your production issues. Ubuntu 18.04 will continue to receive updates until 2023 at least.

Minimum RAM: Note that the build process sometimes consumes too much RAM, and 512MB RAM might not be enough (see [this issue](https://github.com/caprover/caprover/issues/28)). Most providers offer a minimum of 1GB RAM on $5 instance including DigitalOcean, Vultr, Scaleway, Linode, SSD Nodes and etc.

**Comment by githubsaturn** [comment]
Yes, CapRover runs on ARM CPU, but 3rd party apps (one click apps), may or may not have the ARM variants.

**Comment by githubsaturn** [comment]
Ahh actually, it looks like they do have an arm variant! Try going to app > deployment > Deploy from Dockerfile and use this Dockerfile:
```
FROM alpine:3.16.2
RUN apk add --no-cache unzip openssh
ADD https://github.com/pocketbase/pocketbase/releases/download/v0.13.0/pocketbase_0.13.0_linux_armv7.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/
EXPOSE 8080
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
```


if you're using arm64, replace arm7 with arm64.

**Comment by nadveos** [comment]
thank you so much
