### ISSUE TITLE
[Deployment Issue] Redash

### ISSUE THREAD

**Issue by uhlhosting** [caprover/caprover#1683]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
Redash with default settings fails to deploy.
If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Output of the following command on your server:

```
root@pac:/captain/temp/backup# uname -a && lsb_release -a && free -h
Linux pac 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
              total        used        free      shared  buff/cache   available
Mem:            15G        6.8G        1.7G        364M        7.1G        8.3G
Swap:          4.0G        117M        3.9G
```

**Comment by githubsaturn** [comment]
Feel free to comment on the PR: https://github.com/caprover/one-click-apps/pull/772

https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md#installation-bugs

![image](https://user-images.githubusercontent.com/10582082/222927661-64202039-7e08-46a2-91c8-e80d8d89abab.png)
