### ISSUE TITLE
Congratulations and questions

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1686]
In recent days I discovered Caprover. I tried it and in about 10 minutes I already had 10 apps ready AND WORKING IN PRODUCTION on my new server: like having Heroku but for the price of only one server!

**An incredibly easy user experience and excellent performance.** @githubsaturn your work is **stunning** to say the least!

I say this because these days I've started using kubernetes, k3s, micro-k8s again after years of Heroku and similar.

There is no comparison. And I know that I'm comparing partially different things. But sometimes what small software companies are looking for is to just put their applications into production servers without great demands on scalability, since today's servers may very well be able to handle a heavy load (especially if the code is well written and optimized).

And even if there is a future need to scale **Caprover can very well be used for this too**!

1. So, first point: **ENDLESS CONGRATULATIONS!** 🥳 🎉

1. Second point (_my dream_): a guide on (almost maniacal) safety for Caprover; for example, [here you are talking about a VPN](https://github.com/caprover/caprover/issues/493#issuecomment-592951340) to better secure Caprover and use it only from specific PCs (and IPs).

    It would be great to have these detailed informations on a page of caprover's beautiful and rich website.

    And speaking of security, I can't wait to try out the upcoming 2FA.

1. Third point: it would be great to be able to try the news you're working on offline. Why don't you use `master` branch so we can help you with PR, give you suggestions, test what's new in preview and verify it works?

    Is there any specific reason why you prefer to work offline?

1. Fourth point (_the sore point_): Docker Swarm. I think it's well written software (as opposed to Docker Desktop and the mass of k8s components that even if it's freshly installed and without adding anything can by itself go (after a while) up to over 1.5 GB RAM and over 40% CPU overall: there are dozens of github issues on this).

    But the future of Docker Swarm is uncertain and silence does not bode well.

    An alternative (maybe) can be [Nomad (Hashicorp)](https://www.nomadproject.io). What do you think?

    By the way, they already have [Waypoint](https://www.waypointproject.io) that might (from a distance) look like Caprover.

    The experience of using Caprover on Nomad (and Consul) would make those 10k Github stars reach 100k IMHO!

Again, congratulations @githubsaturn!!! 🥳 🎉

**Comment by githubsaturn** [comment]
1- Thanks
2- Sure thing!
3- Generally I work on master branch, but 2FA is in a draft mode with more changes, so I'm bundling all those together.
4- Yes, I'm aware, but I haven't found a good alternative just yet. K3s could be another option, but requires a massive rewrite. As long as docker swarm is maintained security wise, based on my limited time on this project, I don't want to take on a massive task of rewrite. 

Thanks for the comments!
