### ISSUE TITLE
[Question] Will DigitalOcean one click install app (marketplace) of Caprover update from Ubuntu 18.04 which is near end of life April 2023?

### ISSUE THREAD

**Issue by JeFawk** [caprover/caprover#1687]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

I was looking into installing a new droplet with Digital Ocean's Marketplace installation of Caprover, however i noticed it runs on Ubuntu 18.04, which has the eol 30th April, this year.

Is there any plan to update the Marketplace app to use a higher version of the OS? I saw while looking around that 22.04 seems to be working fine from reports in https://github.com/caprover/caprover/issues/1322

Thank you :)

**Comment by githubsaturn** [comment]
Thanks for the ping! I'll submit the new image to digitalocean today. It'll usually take a few days for them to update the marketplace.

Please feel free to comment again if the image hasn't been updated in a few days.
