### ISSUE TITLE
Why is the master password max 29 characters long?

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1688]
I just found out that Caprover doesn't save more than 29 characters as a master password, is this true?

How come I can't use a longer one?

I'm referring to the master password to access the root domain.

**Comment by githubsaturn** [comment]
The limit is there to make sure the password hashing is not too heavy. CapRover runs on small machines (like raspberry pie). 30 characters is more than enough for a secure password.

If you really want to use a longer password, you can bypass this limit by using the API directly. This limit is only enforced on the frontend as of now.

https://github.com/caprover/caprover-frontend/blob/1ce22b218b89b64e61eab83dd725e57fc0e108dd/src/containers/settings/ChangePass.tsx#L65
