### ISSUE TITLE
`no basic auth credentials` error if I try to deploy using self-hosted registry

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1689]
I have a cluster with two nodes (for now).

### Steps to reproduce:

1. New Caprover setup

1. `caprover setup` on my PC completed

1. I have enabled the self-hosted docker registry on caprover

1. registry's password retrieved with: `caprover api -n [SERVER_NAME] -t /user/registries -m GET -d ""`

1. `docker login -u captain -p [PASSWORD] registry.root.domain.com:996` succeded on my machine (not on caprover server)

1. `docker push registry.root.domain.com:996/app-name/app` from my PC worked!

1. When I try `caprover deploy --caproverName [SERVER_NAME] --caproverApp app-name --imageName registry.root.domain.com:996/app-name/app:latest` it doesn't work with error:

    ```shell
    Preparing deployment to CapRover...

    Ensuring authentication...
    Deploying app-name to server-name...

    Building your source code...

    Build started for app-name
    An explicit image name was provided (registry.root.domain.com:996/app-name/web:latest). Therefore, no build process is needed.
    Pulling this image: registry.root.domain.com:996/app-name/web:latest This process might take a few minutes.
    Build has failed!
    ----------------------
    Deploy failed!
    Error: (HTTP code 500) server error - Head "https://registry.root.domain.com:996/v2/app-name/web/manifests/latest": no basic auth credentials

    Something bad happened. Cannot deploy app-name at server-name.
    ```

So I tried to execute `docker login -u captain -p [PASSWORD] registry.root.domain.com:996` on caprover server too and login succeded.

I tried again to deploy and the error is the same. I do not understand why `no basic auth credentials`?

The `~/.docker/config.json` on caprover server is:

```json
{
  "auths": {
    "localhost:996": {
      "auth": "base64passwordhere"
    },
    "registry.root.domain.com:996": {
      "auth": "base64passwordhere"
    }
  }
}
```

As you can see I tried with localhost too with no success.

**One important thing**: if I execute `docker pull app-name/web` on caprover server it works! It pulls the image!

I think caprover cannot download image because it cannot read registry credentials.

**Comment by githubsaturn** [comment]
Correct. The built in registry, as of now, is only meant to be used to distribute images that are built by CapRover across multiple nodes. It cannot be used as a standalone docker registry. 

Just as a heads up, we might mark the built-in registry as a deprecated feature in upcoming releases. It has so many other issues that makes it not production ready. For example, there is no UI for image clean ups, the disk just keeps growing. And the fact that it sits on the same server as applications makes is useless for "backup" purposes. i.e., if you server encounters a disk failure, you cannot revive your apps, because the registry is also corrupted.

**Comment by frederikhors** [comment]
What do you suggest? An external registry? And if I don't care about disk failures (because I already have external backups) can I create an app with https://hub.docker.com/_/registry image?

**Comment by githubsaturn** [comment]
> Isn't it possible to delete with https://docs.docker.com/registry/spec/api/#deleting-an-image?

Yes, it's certainly possible using the API, but CapRover doesn't have any API interaction with the Docker Registry right now. This is essentially a "net new feature". 

A better approach is to create a one click app for Docker registry with a UI. That way, Docker Registry becomes yet another one-click app and the user will be able to do a lot more. Feel free to create a one click app if you're familiar with Docker registry, there a number of 3rd party GUI frontends for Docker registry that you can integrate.

**Comment by frederikhors** [comment]
Maybe in the coming weeks I'll do this. Right now I'm creating a script that clean every night my server using simple curl calls. I'll work on a "one-click app" ASAP and right in time for your new caprover version that deprecates the registry.

**Comment by githubsaturn** [comment]
Happy to help on this one click app! It's been on my todo list for a long time, but never got around doing it. 

Here are some options from my old notes:
Basic GUI tools: 
- https://github.com/quiq/docker-registry-ui
- https://github.com/Joxit/docker-registry-ui
- https://github.com/parabuzzle/craneoperator

Advanced GUI tools (maybe better, maybe overkill)
- Portus ([example tutoria](https://dockerlabs.collabnix.com/beginners/portus/)l)
- Portainer (already a one click app in CapRover)

**Comment by frederikhors** [comment]
Yeah. But I prefer to script everything and do some automatic cleaning.

I just found out https://docs.docker.com/registry/garbage-collection/#run-garbage-collection.

**Comment by githubsaturn** [comment]
Yup! Automatic cleanup is definitely a must have for registry.

Just keep in mind that "garbage collection" feature is just removing the dangling images. It doesn't delete an old image because it's just too old and not needed anymore.

**Comment by frederikhors** [comment]
Yeah. Thanks. I was reading just now. How much work there is to do! I don't want to use an external registry because I want to limit the dependencies as much as possible.
