### ISSUE TITLE
Using Caprover with a VPN

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1694]
First of all: **everything works**! 🎉😄

Just finished my first server with 10 applications! I'm very happy! Everything works and very, very well!

### The initial setup

On a new linux server:

1. I have a "domain.com" with DNS:
    - A "caprover.domain.com" `82.1.2.3` (fake PUBLIC IP)
    - A "*.caprover.domain.com" `82.1.2.3` (fake PUBLIC IP)

1. I installed a VPN (wireguard) such as:
    - the server has IP `10.10.10.1`
    - my development PC has IP `10.10.10.2`
    - CI machine has IP `10.10.10.3`

1. I installed Caprover the default way. The first time I can enter from http://82.1.2.3:3000 and then I can use "`caprover setup`" on my PC filling questions with "`82.1.2.3`", my email address for SSL and so on...

1. I closed all the ports on my server except for `80`, `443` and the VPN one

Ok. Everything works now.

### A more secure setup

Now I wanted a way to make the whole server more secure by removing everything is possible to remove from the public world.

What I did now I thought it couldn't be done and instead it worked (with a small issue):

1. I removed the public DNS (the two "`caprover.domain.com`" and "`*.caprover.domain.com`")

1. I edited the hosts file on my development PC (and on the CI machine) like this: `10.10.10.1 captain.caprover.domain.com`

And with no changes at all in caprover it worked!

1. I can access the dashboard using "https://captain.caprover.domain.com"

1. I can create new apps using other domains (for example: "new-shiny-app.other_domain.com") (using the proper DNS on that domain)

1. I can also enable HTTPS for that app on "other_domain.com", **it just works!**

## The issue

Before this configuration I tried to install caprover [as explained here](https://caprover.com/docs/run-locally.html#option-1---only-internal-usecase), but the "`caprover setup`" procedure errored on the generation of SSL certificates (after requesting the email address) because the dashbaord was not publicly visible.

And consequently I didn't want to proceed in this way: "among other things, maybe the generation of SSL certificates for the exposed apps can't work now", I thought.

Given my current totally non-public local-only configuration, I would like to avoid having SSL and HTTPS certificates for the dashboard. It would be great to have HTTPS only for public, exposed apps.

I don't know how the Let's encrypt certificate renewal works, but if I stay with this configuration, since the caprover dashboard is not public now, I think the renewal will fail and I will run into problems in a few weeks, am I right?

## The request

Is there a way to install caprover in a "local-only" way? Maybe accessing it only by using the address and a port (`10.10.10.1:3000`) instead of an URL `https://captain.caprover.domain.com`?

**What am I doing wrong?**

All my admiration for the work you have done with caprover: I am delighted with so much wonder!

**Comment by githubsaturn** [comment]
> Is there a way to install caprover in a "local-only" way? Maybe accessing it only by using the address and a port (10.10.10.1:3000) instead of an URL https://captain.caprover.domain.com?

Yes, like what you discovered, you can use http://10.10.0.10:3000/ without SSL. But surely you cannot use httpS://10.10.0.10:3000/ - this is not CapRover, but it's just how SSL works. You need a domain for SSL. 

Unless... you want to enable HTTPS for your apps, but not for your dashboard. In that case, yes, it's possible:
- Install the CapRover normally
- Set `skipVerifyingDomains` to true
- Add a root domain and enable the SSL for dashboard normally.
- After the HTTPS for the dashboard is enabled, **before you add any apps**, you can now remove the domain:
```
nano /captain/data/config-captain.json
# now manually change the domain to a something random, e.g., "this-is-fake-qwerty.com"
# Remove force SSL and enable SSL for root domain
```


Now you can enable HTTPs for your custom domains, and your root domain doesn't work anymore.

**Comment by frederikhors** [comment]
May I ask you to be more specific in explaining the steps to have SSL for apps only?

And then for the step `After the HTTPS for the dashboard is enabled`: doesn't this certificate for the dashboard expire after some time?

**Comment by frederikhors** [comment]
What I don't understand is why we have to enable SSL also on the dashboard if we can add it only for apps (exposed publicly with DNS).

**Comment by frederikhors** [comment]
@githubsaturn I tried your instructions but when I add an app and I click on "Enable HTTPS" the error is as follows:

![image](https://user-images.githubusercontent.com/41120635/223753266-fae235c6-f258-4ecd-b00a-24846c771e3b.png)

**Comment by githubsaturn** [comment]
hmm let me read the code to later today to understand what's going on.

**Comment by githubsaturn** [comment]
okay yea it looks like my instructions here was incorrect: https://github.com/caprover/caprover/issues/1694#issuecomment-1461152868


You should NOT remove enable SSL for root domain. Just remove "force ssl" attribute. 

```
nano /captain/data/config-captain.json
# now manually change the domain to a something random, e.g., "this-is-fake-qwerty.com"
# Remove force SSL 
```

Make `"hasRootSsl": true,` is in the config. Try this again and let me know if it works.

**Comment by frederikhors** [comment]
I'll try in a few hours.

**Comment by frederikhors** [comment]
I tried but the `nginx:1` container keeps shutting down and resarting continuously.

Logs:

```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/12 20:57:52 [emerg] 1#1: cannot load certificate "/letencrypt/etc/live/captain.fake.domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/letencrypt/etc/live/captain.fake.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/letencrypt/etc/live/captain.fake.domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/letencrypt/etc/live/captain.fake.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by githubsaturn** [comment]
Ahh this is giving me headaches now lol 
Trying to cheat the system and it looks like it's picking that up and fighting back! 


Anyways, we're one step closer.... Change your root domain in `/captain/data/config-captain.json` to the correct one so that the nginx container loads fine.

Then, go to the panel > settings  > NGINX Configurations 

Edit nginx and make a change in **CapRover Config Location in nginx container: /etc/nginx/conf.d/captain-root.conf**

Remove this section:

```
    <%
        if (captain.hasRootSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-captain.crtPath%>;
        ssl_certificate_key <%-captain.keyPath%>;

    <%
        }
    %>
```

Now, edit the config and change the root back to fake domain!

**Comment by frederikhors** [comment]
> Trying to cheat the system and it looks like it's picking that up and fighting back!

LOL!!!!

I'll try in a few moments...

Anyway why are you telling me to change the domain to a fake one? I think we can also keep the one with which I activated the SSL as long as we remove the corresponding DNS to turn it off to the public, nope?

**Comment by frederikhors** [comment]
I did it.

If I try to reach captain dashboard with `http://10.10.10.1:3000` I get in browser the error: `ERR_SSL_PROTOCOL_ERROR`.

I'm using fake domain and nginx config changed as you suggested.

**Comment by frederikhors** [comment]
I changed it to `"forceRootSsl": false,` to make it work with 10.10.10.1:3000.

**Comment by githubsaturn** [comment]
> Anyway why are you telling me to change the domain to a fake one? 

I thought you don't want the domain to respond to that particular domain. If someone hardcodes a DNS entry to your IP, they can see the dashboard. 


 > If I try to reach captain dashboard with http://10.10.10.1:3000 I get in browser the error: ERR_SSL_PROTOCOL_ERROR.

I bet you haven't disabled force SSL. An HTTP request should never result in `ERR_SSL_PROTOCOL_ERROR`


What do you see when running this:
```
curl -v http://10.10.10.1:3000
```

**Comment by githubsaturn** [comment]
Perfect!

**Comment by frederikhors** [comment]
> If someone hardcodes a DNS entry to your IP, they can see the dashboard.

Can you please explain this to me?

If I removed all the DNS to my domain? They still can see the dashboard?

**Comment by frederikhors** [comment]
I'm using a VPN. I'm able to see the captain.domain.com only using hosts file and this:

`10.10.10.1 captiain.domain.com`

**Comment by githubsaturn** [comment]
If you don't change your domain to fake domain, yes, they can see the dashboard. 

Let's assume that I know your dashboard used to be available at captain.something.domain.com and I know your public IP.

Even though, you now removed the DNS, I can just hard code `captain.something.domain.com` and your public IP in my `/etc/hosts` file and then I can access your dashboard.

But this requires me knowing your full root domain `captain.something.domain.com` and also your IP address.

**Comment by frederikhors** [comment]
Oh yeah! Because `nginx` on port 80, right?

**Comment by githubsaturn** [comment]
Yes

**Comment by frederikhors** [comment]
I spoke too soon! After a reboot I get:

```
Captain Starting ...
Overriding skipVerifyingDomains from /captain/data/config-override.json
March 12th 2023, 10:26:34.346 pm    Emptying generated and temp folders.
March 12th 2023, 10:26:34.351 pm    Ensuring directories are available on host. Started.
March 12th 2023, 10:26:34.356 pm    Ensuring directories are available on host. Finished.
March 12th 2023, 10:26:34.360 pm    Network captain-overlay-network is already attached to service: captain-captain
March 12th 2023, 10:26:34.365 pm    captain-captain (service) has already been connected to secret: captain-salt
March 12th 2023, 10:26:34.366 pm    Migration not needed, skipping.
March 12th 2023, 10:26:34.371 pm    Copying fake certificates...
March 12th 2023, 10:26:34.374 pm    Updating Load Balancer - Setting up NGINX conf file...
March 12th 2023, 10:26:34.375 pm    Locking NGINX configuration reloading...
March 12th 2023, 10:26:34.383 pm    Error: Bad Domain Name!
Error: Bad Domain Name!
    at CertbotManager.domainValidOrThrow (/usr/src/app/built/user/system/CertbotManager.js:23:19)
    at CertbotManager.getCertRelativePathForDomain (/usr/src/app/built/user/system/CertbotManager.js:28:14)
    at LoadBalancerManager.getSslCertPath (/usr/src/app/built/user/system/LoadBalancerManager.js:239:33)
    at /usr/src/app/built/user/system/LoadBalancerManager.js:304:35
March 12th 2023, 10:26:34.383 pm    Error: UNLocking NGINX configuration reloading...
March 12th 2023, 10:26:34.383 pm    Error: Bad Domain Name!
Error: Bad Domain Name!
    at CertbotManager.domainValidOrThrow (/usr/src/app/built/user/system/CertbotManager.js:23:19)
    at CertbotManager.getCertRelativePathForDomain (/usr/src/app/built/user/system/CertbotManager.js:28:14)
    at LoadBalancerManager.getSslCertPath (/usr/src/app/built/user/system/LoadBalancerManager.js:239:33)
    at /usr/src/app/built/user/system/LoadBalancerManager.js:304:35
```

**Comment by frederikhors** [comment]
I'm using this fake domain:

```json
{
    "namespace": "captain",
    "customDomain": "test.2N6vqrCqgv3tcgxk.com",
    "emailAddress": "mail@mail.com",
    "hasRootSsl": true,
    "forceRootSsl": false,
    ...
}

**Comment by githubsaturn** [comment]
just use small letters in your domain and it should be fine.

**Comment by frederikhors** [comment]
Yeah, I'm rebooting now with lowercase...

**Comment by frederikhors** [comment]
It works amazingly well!

**Comment by frederikhors** [comment]
Just one last question: if I want to reset the nginx configuration to the default one this is the button, right?

![image](https://user-images.githubusercontent.com/41120635/224578091-8acb41d4-bec1-489c-9763-96df68f53a3f.png)

**Comment by githubsaturn** [comment]
Just remove the entire content (all boxes) and hit save.

If you break your nginx config, you can run this script to remove all modifications:
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by githubsaturn** [comment]
Also, just so you know all the things that you did here is just hacking the system to do something that it's not supposed to do.

A better approach for "better security" is use firewalls, or add something like this in your nginx:
```
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            
            deny all;
```

**Comment by frederikhors** [comment]
> A better approach for "better security" is use firewalls

Yeah I know, I closed everything except for 80 & 443.

Firewall doesn't solve the dashboard public visibility issue I think, right?

> or add something like this in your nginx:

> allow 172.16.0.0/12;
> allow 10.0.0.0/8;
> allow 192.168.0.0/16;
> deny all;

Yeah, I would like this, but I don't know `nginx`.

Can you help me figure out where to put them?

Maybe we can start from the default nginx config.

And of course we're only talking about the dashboard because other apps (even on other domains) need to be visible to everyone.

**Comment by frederikhors** [comment]
I must re-open this also because I don't know how to use `caprover` npm cli now that I'm using `http://10.10.10.1:3000`.

**Comment by frederikhors** [comment]
For example this is a `caprover login`:

```
Login to a CapRover machine...

? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": http://10.10.10.1:3000
? CapRover machine name, with whom the login credentials are stored locally: server-1

Something bad happened: cannot save server-1 at https://captain.10.10.10.1.
Error: getaddrinfo ENOTFOUND captain.10.10.10.1
```

How to?

**Comment by frederikhors** [comment]
But do I need it to deploy? Or I can just use the url way?

**Comment by frederikhors** [comment]
If I use:

```
caprover deploy --caproverPassword PASS --caproverUrl http://10.10.10.1:3000 --caproverApp app-name --imageName app-name:1
```

the error is:

```
Preparing deployment to CapRover...

Ensuring authentication...

Something bad happened during authentication to http://captain.10.10.10.1.
Error: getaddrinfo ENOTFOUND captain.10.10.10.1
```

This deployment method is critical for me.

**Comment by frederikhors** [comment]
It would be amazing to have a dashboard working completely "offline" with no port exposed with nginx.

**Comment by githubsaturn** [comment]
As I mentioned:
> Also, just so you know all the things that you did here is just hacking the system to do something that it's not supposed to do.

The issue with the deployment that you're facing is another example of these issues. You can work around this issue by doing this:

- Add an entry to your /etc/hosts file that points `captain.test.2N6vqrCqgv3tcgxk.com` to `10.10.10.1`
- Use `caprover login` and deploy as usual.




> It would be amazing to have a dashboard working completely "offline" with no port exposed with nginx.

But again: as I said above: This setup is not supported by CapRover. All the workarounds discussed in this thread are extremely fragile and can cause issues (as seem multiple times in this thread already)


If you really want your dashboard not be accessible from outside, you need to follow what I recommended here:
https://github.com/caprover/caprover/issues/1694#issuecomment-1465319342

Go to settings > "CapRover Config Location in nginx container" and add these `allow` and `deny` lines just below `proxy_pass $upstream;` lines (2 instances).
