### ISSUE TITLE
[Question] Change overlay network gateway

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1696]
How can i change the `captain-overlay-network` gateway and subnet?
Currently when I try to edit a network in this case removing the connection of services that depend on that network and trying to create a network with the same name to overwrite the settings. I can't, the services keep restarting when I try to change its settings.

I think this is a docker question, but it is directly related to the CapRover project, so I Hope someone can help me.

**Comment by githubsaturn** [comment]
As you mentioned this is a Docker question. 

Unfortunately Docker doesn't offer `docker network update`. So there is no way to update a network that is already created.

Docker only has these verbs for network:
![image](https://user-images.githubusercontent.com/10582082/224468996-9b4298a9-100a-4393-996d-b4cb0f9ac9b7.png)

**Comment by githubsaturn** [comment]
PS: You can try removing and recreating the network, but it's possible that it won't work.

- `docker network rm captain-overlay-network`
- `docker network create ....<your-configs>... captain-overlay-network`

**Comment by DaniHRE** [comment]
> PS: You can try removing and recreating the network, but it's possible that it won't work.
> 
> * `docker network rm captain-overlay-network`

It don't work cause need remove this network to other services and containers.
When I try to remove the network from all containers and services, I have the problem that either the services stop working, or the containers keep resetting and going back to the original network. :/

**Comment by githubsaturn** [comment]
CapRover doesn't use Docker CLI - it directly uses Docker API. Here is the function where the network is getting created: https://github.com/caprover/caprover/blob/e23b3c7d8af103c6c6dc4cea2973737daabf6e22/src/docker/DockerApi.ts#L1162-L1186
