### ISSUE TITLE
How to remove a swarm node?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1703]
Hi there, 

for testing i have added a swarm node to my caprover instance. Now i want to remove it. how do i do that? 
i tried 
```
root@node:~# docker swarm leave --force
Node left the swarm.
```
but it still shows up in caprover. 

Cheers and thanks!

**Comment by maietta** [comment]
My I ask why you are trying to remove Swarm mode? It's my understanding Swarm mode is required to deploy application stacks.

**Comment by maietta** [comment]
If it's still showing in the UI, it means docker swarm never removed it, or that the swarm hasn't realized it was meant to be removed.

Were you having trouble removing the node and thus used --force to do it? You probably had an underlying problem, such as a port not open or something that prevented the worker node(s) from communicating openly with the manager(s).

**Comment by githubsaturn** [comment]
Nick's correct. 

CapRover simply queries docker for the nodes. 

You can run `docker node ls` and you probably see the node being present there as well. This doesn't seem to be a caprover question.

**Comment by pcace** [comment]
Hi, i think its not quite closed. Since there is an option to add a node within caprover - but no option to remove a node. 
So i think there should be at least a hint how to remove one. What would be the way to remove a node? 
I am asking as someone who does not have much experience with docker -wich is also a reason for me using caprover.

**Comment by githubsaturn** [comment]
you can either run `docker swarm leave` on a specific node or run `docker node ls` to get a list of nodes and use `docker node rm <NODE-ID>` to remove it.
