### ISSUE TITLE
No access to the dashboard after install, Debian 11

### ISSUE THREAD

**Issue by Jhereck** [caprover/caprover#1705]
Hi,

I installed Caprover as explained in the tutorial, and cannot get access to it on http://IP_ADRESS:3000 after that.

I checked my firewall and all of the points mentionned in the install tuto : all seems to be functionnal.

- After install :
 
![Capture d'écran 2023-03-15 164115](https://user-images.githubusercontent.com/9906594/225408813-c1d8523e-ae32-453e-9809-7b1f8c19f9c9.png)

- docker service ps captain-captain --no-trunc : 

![Capture d'écran 2023-03-15 164222](https://user-images.githubusercontent.com/9906594/225408860-38f7ef1f-6e57-4fe1-bf92-1b722f47de1f.png)

- docker service logs captain-captain --since 60m : 

![Capture d'écran 2023-03-15 164306](https://user-images.githubusercontent.com/9906594/225364561-78614169-db4b-4515-9737-26cc19afcb25.png)

- curl localhost:3000 -v : 

![Capture d'écran 2023-03-15 164322](https://user-images.githubusercontent.com/9906594/225364858-c81515dd-6a81-40f2-a068-d5055fef4ef5.png)

- Firewall : 

![Capture d'écran 2023-03-15 164417](https://user-images.githubusercontent.com/9906594/225364917-ff92cf1e-095f-46db-bd16-3a549bf3bb1a.png)

As said the server is on Debian 11.

I pretty new to Docker (that's why i wanted to use Caprover :) ) : any idea pls ?

Thanks,

Jh

**Comment by Jhereck** [comment]
Oookkkk pb solved after using the caprover serversetup with domain config !

The only thing left is i made a control + z during the process, witch was stopped at step "CapRover machine name, with whom the login credentials are stored locally" : is it a pb and do i need to uninstall and reinstall, or can i finish the process another way ?

Just don't want to do a mistacke now it's working, and after a whole day of googling :)

Thanks !

![Capture d'écran 2023-03-15 202627](https://user-images.githubusercontent.com/9906594/225422308-2e236b01-5b85-4d54-964c-dac7cc0b9cab.png)

**Comment by githubsaturn** [comment]
You can use `caprover login` to log into your instance and set a name.
