### ISSUE TITLE
[Question] One click apps won't finish loading

### ISSUE THREAD

**Issue by yupix** [caprover/caprover#1708]
# Summary
I am using OracleCloud as my VPN and am port forwarding using Tailscale. The basic operation is fine, but when I press One Click Apps, it does not finish loading and does not show the list. I looked at the network in the developer tools and found that `/api/v2/user/oneclick/template/list` has a 504 gateway timeout. I have confirmed that this problem does not occur without using Tailscale. Do you know of any possible causes?

Port forwarding
```
firewall-cmd --zone=external --add-forward-port=port=80:proto=tcp:toport=80:toaddr=tailscale ip
firewall-cmd --zone=external --add-forward-port=port=443:proto=tcp:toport=443:toaddr=tailscale ip
firewall-cmd --zone=external --add-forward-port=port=3000:proto=tcp:toport=3000:toaddr=tailscale ip
```

## ScreenShot
![image](https://user-images.githubusercontent.com/50538210/226096325-a8c971f0-7c0a-493b-b04e-5197ccce9529.png)

## Environment
OS: Ubuntu Server 22.04
CapRover: 1.10.1

**Comment by githubsaturn** [comment]
`captain-captain` container needs to connect to `https://oneclickapps.caprover.com` to fetch the one click apps. Tailscale is somehow blocking this. Once this is resolved the one click apps will work fine.

**Comment by yupix** [comment]
Thank you for your answer. Does this mean that it is not a problem in my environment, but that it is blocked when using Tailscale in any environment?

**Comment by githubsaturn** [comment]
I don't know how tailscale work. So I cannot say whether it's Oracle or Tailscale.

What I can say is that somehow it's blocking the container from accessing one click apps domain. Also, it's probably blocking the container from reaching out to fetch if there's any updates available. 

You should be able to simply replicate this by shelling into the container and really running simple curl command.

**Comment by yupix** [comment]
Thank you for your reply. I went into the container and checked and noticed that I could not access some of the sites. `https://oneclickapps.caprover.com` seems to be one of them and I will contact Tailscale support as it does not seem to be a CapCrover issue. Thank you!
