### ISSUE TITLE
how to serve static files via http?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1709]
Hi,

i am trying to serve static files via caprover app. what i did is: 
created new app, with persistant data, data directory is `/usr/share/nginx/html/tiles`, to the nginx config i added: 
```
 location /tiles/ {
                autoindex on;
                root /usr/share/nginx/html/tiles
             }
```
within the server section. 
the Problem is, that i always get a 404 even if the file exists checked inside the container. 

what am i missing?

**Comment by githubsaturn** [comment]
nginx runs in a separate container. 

For static files you need to deploy a secondary nginx to service the files.
