### ISSUE TITLE
[Question] SSH Deploy Key

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1710]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

How can i use Deploy Keys to my application?

I'm Trying to use Deploy Key in my app and got this error:
```
Build started for borum
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/borum/5/source_files'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by githubsaturn** [comment]
Read the similar threads: https://github.com/caprover/caprover/search?q=Could+not+read+from+remote+repository&type=issues

## Step 1: 
Generate a key pair:
ssh-keygen -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""


## Step 2:
Add the **public** key to github
![image](https://user-images.githubusercontent.com/10582082/227103787-29b71c92-476d-47cc-8d57-ffa18cceeeca.png)


## Step 3:
Add the **private** deploy key to CapRover
![image](https://user-images.githubusercontent.com/10582082/227104196-455b7e43-e806-4b91-b04e-b08b22424c5c.png)

**Comment by githubsaturn** [comment]
If you still have issues, you likely have a typo somewhere. Common mistakes people make is to just randomly delete the new line at the end of the private key.

See https://github.com/caprover/caprover/issues/1265#issuecomment-973651341


Before opening a new issue, please read other similar issues: https://github.com/caprover/caprover/search?q=Could+not+read+from+remote+repository&type=issues

**Comment by githubsaturn** [comment]
Okay then, this is unrelated to CapRover. 

Looks it doesn't even let you connect via wget. Maybe a dns issue on your VPS? Maybe firewall?

**Comment by maietta** [comment]
Hi @DaniHRE. Why is github.com resolving internally to a loopback IP of 127.0.0.1 at port 3128?

Looks to me like you are being connected through a proxy server. I'd resolve that issue first.

**Comment by DaniHRE** [comment]
I checked my proxy connection, and outside of the container it run normally.
But in caprover containers can't resolve github.com to ssh connection.
All of my network packages runs through my proxy

**Comment by githubsaturn** [comment]
@DaniHRE 
If you can't even resolve github.com from the CapRover container, this is not a CapRover issue. This is a question for Docker and/or your proxy provider.
