### ISSUE TITLE
[Question] Spa application deploy

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1713]
I'm trying to deploy SPA Application using this docker image -> [Static React App](https://caprover.com/docs/recipe-deploy-create-react-app.html#build-on-local-machine)

This is My Dockerfile

```
# Dockerfile
FROM socialengine/nginx-spa:latest

ENV http_proxy=http://172.0.0.1:3128
ENV https_proxy=http://172.0.0.1:3128

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt install nodejs

RUN node --version && npm --version

RUN npm install -g pnpm

WORKDIR /app

COPY . .

RUN pnpm setup-repo

RUN pnpm run build --filter=web-borum

RUN cp -r ./apps/web-borum/dist/* /app

CMD chmod -R 777 /app
```

When i check /app folder using ```docker exect -it {containerid} sh``` i see the builded files inside /app folder but caprover show nginx 502 error.

**Comment by githubsaturn** [comment]
[Shell into your container](https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container) and run `curl -v http://localhost`

What do you see?

PS:
502 just means that your application does not return any response. There is many reasons behind that: https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

**Comment by maietta** [comment]
I don't see an EXPOSE 3128 or other port expose directive for the Dockerfile.

Do you need one? I would think you do.

**Comment by DaniHRE** [comment]
My problem was solved and I managed to do what I needed. I will close the issue feel free to comment anything else. including why this worked lol 😂👌

**Comment by githubsaturn** [comment]
It's because in your first try you had `RUN cp -r ./apps/web-borum/dist/* /app` - but you should have `RUN cp -r /apps/web-borum/dist/* /app`

**Comment by DaniHRE** [comment]
Ohhh that actually makes sense, I made a simple mistake lol, thank you very much 🤞🏻
