### ISSUE TITLE
[Question] Can't connect to redis container

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#1717]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: Basically when I go to connect to my redis container. my authenticating backend container that needs it to store information is unable to connect. returning the following error: "Error: connection timeout.".

But if I enter the container afterwards and execute the connection manually, the connection works.

I'm going crazy over this.

This is my Dockerfile: 

```
FROM danihre/spa-nginx:latest

ENV http_proxy=http://172.0.0.1:3128
ENV https_proxy=http://172.0.0.1:3128

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt install nodejs

RUN npm install -g pnpm

WORKDIR /home

COPY . .

RUN pnpm setup-repo

RUN pnpm run build --filter=auth

RUN cp /home/apps/auth/.env /home/apps/auth/build/.env

RUN node /home/apps/auth/build/index.js
```

**Comment by githubsaturn** [comment]
Is this the line that times out?
```
node /home/apps/auth/build/index.js
```

**Comment by DaniHRE** [comment]
Yes, why when I try to start the server from that line I get the redis timeout error

**Comment by githubsaturn** [comment]
For future context, the reason behind this is that you're running this line in your build process which is a completely different environment from your container. `CMD` line runs in runtime, but `RUN` runs in build time.
