### ISSUE TITLE
[Deployment Issue] Multi-platform docker image support

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1721]
Until now I've been using `amd64` based servers exclusively, so I haven't encountered this before.  But now, there is an option to use an `arm64` based server, so I happened to try and spin up an `arm64` based server and add it to the docker swarm as a worker node, with an existing `amd64` based server as the leader node.  Of course it didn't work.  Or at least it worked up to a point, but the swarm couldn't create new instances of the existing images in the self-hosted registry because they were built on an `amd64` based server (docker service logs shows `exec /usr/bin/tini: exec format error`).

Does the self-hosted registry in CapRover somehow support images for multiple platforms, which seems to be possible in general [as explained here](https://docs.docker.com/build/building/multi-platform/)?  I know that the easiest option is to use matching leader and worker nodes, but I'm curious to know if multi-platform support is even possible... would offer flexibility about what type of worker can be added to the swarm... though presumably at the expense of build time and registry storage.

**Comment by githubsaturn** [comment]
CapRover image registry technically should support multi arch images. But, the problem is that the image is built on the server with `amd64` processor. 

A mix and match swarm network **_might_** work (untested), but you definitely need to build your own CI/CD pipeline and use [buildx](https://docs.docker.com/engine/reference/commandline/buildx/) to build and deploy multiplatform images.

**Comment by drmrbrewer** [comment]
OK so the standard `caprover deploy` (which I believe just creates and sends a tarball of your project to your server and builds from that) will be hardwired to just do a normal `docker build` rather than a `docker buildx build`, and hence the images will just be for whatever architecture your server has (and only that architecture)?

Might be an option for the future to be able to specify what architecture(s) you want for the images, perhaps always in addition to the native architecture of your existing server, in which case it switches to using `docker buildx build`?

**Comment by githubsaturn** [comment]
> OK so the standard caprover deploy (which I believe just creates and sends a tarball of your project to your server and builds from that) will be hardwired to just do a normal docker build rather than a docker buildx build, and hence the images will just be for whatever architecture your server has (and only that architecture)?

Correct.

> Might be an option for the future to be able to specify what architecture(s) you want for the images, perhaps always in addition to the native architecture of your existing server, in which case it switches to using docker buildx build?

Technically yes, but if you get into that stage, your usecase is better suited to utilize a proper CI/CD pipeline.
