### ISSUE TITLE
[Question] Can we enable NGINX ModSecurity WAF

### ISSUE THREAD

**Issue by Tarmik0s** [caprover/caprover#1724]
Hi,

Loving the project!

I just would like to ask if it is possible to enable the ModSecurity WAF in CapRover's Nginx? I was to enable to integrate my Caprover to Cloudflare quite flawlessly but as much as possible I want to route all traffic within my server and not use other's proxies. But upon checking Caprover nginx file directory it doesn't have any modules, may I ask how possibly I can start enabling them Modules? 

Thanks!!

**Comment by githubsaturn** [comment]
CapRover runs nginx in a separate container. By default it uses the official [nginx:1 image](https://hub.docker.com/_/nginx).

If you want, you can build a custom docker image with as many added modules as you want and just override the default image by overriding `nginxImageName` property.

Here is how you can override config values: https://caprover.com/docs/troubleshooting.html#customize-config-settings
