### ISSUE TITLE
Let's Encrypt .pem files path

### ISSUE THREAD

**Issue by eliagentili** [caprover/caprover#1726]
I'd like to update my express app to use https, but for doing so I need to specify the `.pem` files path.

For example something like this:

```js
const httpsServer = createServer({
  key: readFileSync("/path/to/my/key.pem"),
  cert: readFileSync("/path/to/my/cert.pem")
});
```

Where I can find the path for my automatic generated Let's Encrypt Certificate?

Thanks

**Comment by githubsaturn** [comment]
Path on the host is:
```
/captain/data/letencrypt/etc/live/<DOMAIN>/<All cert files including PEM>
```

But you need to make sure you map this directory to your app through volume mapping. Simply you can map `/captain` to `/captain` to use the exact same path as your host.

![image](https://user-images.githubusercontent.com/10582082/232164368-473c86ab-a9ed-4d0e-907f-abb9d17b2343.png)

**Comment by githubsaturn** [comment]
Just to add, you really shouldn't need to use PEM files in your express server app. You can just click on ENABLE HTTPS and it automatically enables HTTPS for your app. CapRover manages the SSL termination for you through nginx as a reverse proxy.

```
[User] ==== https ====> [Nginx] ===== http =====> [srv-captain-your-app]
```

**Comment by eliagentili** [comment]
> Just to add, you really shouldn't need to use PEM files in your express server app. You can just click on ENABLE HTTPS and it automatically enables HTTPS for your app. CapRover manages the SSL termination for you through nginx as a reverse proxy.
> 
> ```
> [User] ==== https ====> [Nginx] ===== http =====> [srv-captain-your-app]
> ```

Yes, that's true if I only use https in my application, but I also want to use socket.io and use a secure protocol. In that case I don't know how to set Nginx to handle boths that's why I asked for the .pem files.

**Comment by githubsaturn** [comment]
This should do the trick:
![image](https://user-images.githubusercontent.com/10582082/232235539-db4ad9f1-d93d-4fb5-87d9-fde3f023cbc2.png)

**Comment by eliagentili** [comment]
> This should do the trick:
> 
> https://socket.io/docs/v3/reverse-proxy/
> 
> ![image](https://user-images.githubusercontent.com/10582082/232235539-db4ad9f1-d93d-4fb5-87d9-fde3f023cbc2.png)

Unfortunately it doesn't.

Even with that enabled I received an error while connecting to socket through https.
