### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by rajmaskey** [caprover/caprover#1728]
I can not open other port than 443 and 80 even though I have opened them from my server-side

Is there a way to change or configure that caprover does not block other ports?

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/232235432-e1c7ee39-2690-49a4-9977-fd414a508aff.png)

**Comment by rajmaskey** [comment]
> ![image](https://user-images.githubusercontent.com/10582082/232235432-e1c7ee39-2690-49a4-9977-fd414a508aff.png)
> 

I think you didn't got what I said, I want to open other ports from my machine while running caprover instance, for example I have a Minecraft server running on the same server but caprover has blocked its port 25565 from the internet. In that case what shall I do? I want to use same node to run different applications

**Comment by githubsaturn** [comment]
Ah I see what you're saying.

> caprover has blocked its port 25565 from the internet

CapRover does not block any ports. What makes you think CapRover blocks ports?

**Comment by rajmaskey** [comment]
> Ah I see what you're saying.
> 
> > caprover has blocked its port 25565 from the internet
> 
> CapRover does not block any ports. What makes you think CapRover blocks ports?
I tried running a few different applications including a Minecraft server, I changed from AWS to Azure and Azure to Oracle Cloud 
After installing caprover the only ports that are open is 80, 443 and 3000

**Comment by githubsaturn** [comment]
There must be something else that you're doing. CapRover cannot possibly block any ports on the host, it's contained in a docker container and has no access to the host configs.

**Comment by githubsaturn** [comment]
Try disabling the firewall... `ufw disable` and see if it works

**Comment by rajmaskey** [comment]
> Try disabling the firewall... `ufw disable` and see if it works

Nope doesn't work, I guess the problem is that caprover routes all unknown traffics to its 404 page

**Comment by githubsaturn** [comment]
> I guess the problem is that caprover routes all unknown traffics to its 404 page

CapRover **only** listens to port 80, 443, and 3000. It cannot possibly route any traffic to any other ports. 

You can verify this simply by running `docker service ls` and look at the port mapping column.

**Comment by rajmaskey** [comment]
> > I guess the problem is that caprover routes all unknown traffics to its 404 page
> 
> CapRover **only** listens to port 80, 443, and 3000. It cannot possibly route any traffic to any other ports.
> 
> You can verify this simply by running `docker service ls` and look at the port mapping column.

What could cause this problem then? I cannot access other ports whatsoever than those listed there.

**Comment by rajmaskey** [comment]
> > I guess the problem is that caprover routes all unknown traffics to its 404 page
> 
> CapRover **only** listens to port 80, 443, and 3000. It cannot possibly route any traffic to any other ports.
> 
> You can verify this simply by running `docker service ls` and look at the port mapping column.

Thank you for clearing out! After a very tedious process of looking around and messing with firewall, I found that uninstalling iptables and disabling firewalld helped
