### ISSUE TITLE
Bug: Plain Dockerfile is not persisted

### ISSUE THREAD

**Issue by gdassori** [caprover/caprover#1729]
**What is the problem?**

```
The custom docker file is lost after deploying. 
The deployment is successful, but once the app is deployed, the textbox goes blank.
```

**Steps to reproduce the problem:**

```
Deploy an app using "Method 4: Deploy plain Dockerfile".
```

**Comment by githubsaturn** [comment]
This is working as expected. 

Deployment methods aren't supposed to be persisted. It's simply a textbox where you enter the information and send it to the server to build the image. It's the same for all textbox entry deployments:
- Deploy plain Dockerfile
- Deploy captain-definition file
- Deploy via ImageName

**Comment by gdassori** [comment]
Hi @githubsaturn, are you willing to discuss this? 
I think it is very useful to browse the last used deployment method of an application, would be ok for you to use at least the localStorage for these textboxes?

**Comment by githubsaturn** [comment]
@gdassori - while I understand the specific usecase, unfortunately this solution will lead to more confusion. Bugs will be reported as to why this is not persisted across browsers.

**Comment by gdassori** [comment]
I see your point. Thanks anyway I'll find another way to track it :-)
