### ISSUE TITLE
[Question] PHP $_SERVER['HTTPS'] is not set when HTTPS is enabled

### ISSUE THREAD

**Issue by benwest** [caprover/caprover#1730]
Maybe I misunderstand something, but my CMS is unhappy because `$_SERVER['HTTPS']` is not set, even though I have HTTPS enabled (and forced) in Caprover.

**captain-definition**
```
{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM php:8.1-apache",
    "COPY . /var/www/html/"
  ]
}
```

**index.php**
```php
<?php echo isset($_SERVER['HTTPS']) ? $_SERVER['HTTPS'] : "\$_SERVER['HTTPS'] is not set";
```

The URL bar shows https://, but the page outputs "$_SERVER['HTTPS'] is not set".

Is there something wrong with my configuration?

**Comment by jonaskuske** [comment]
> Is there something wrong with my configuration?

No, this sounds like the usual setup with reverse proxies. A server/proxy accepts the https connection and does TLS termination (here `captain-nginx`), then internally forwards the request to the actual target server, in your case a PHP server – via http.
Everything is working as intended, you just need to let your CMS know it is. WordPress recommends manually setting `$_SERVER['https'] = 'on'`: https://wordpress.org/documentation/article/administration-over-ssl/#using-a-reverse-proxy

**Comment by benwest** [comment]
Thank you for the explanation! I figured out that setting `$_SERVER['HTTPS'] = 'on'` made things work, and it’s good to know that’s not a kludge. 

I also have a related question which is more specific to CapRover: I’m querying my CMS using HTTP basic auth, which requires HTTPS. The internal `srv-captain—` address is not HTTPS, so the auth fails. I’m using the ordinary public `https://` url instead, but is there a better way?

**Comment by jonaskuske** [comment]
I don't quite understand what you mean. Querying as in using the CMS headless as an API and sending requests from other services or JavaScript code?

**Comment by benwest** [comment]
Sorry, let me clarify:

App 1 is my CMS, the PHP app I've been talking about. It exposes an API requiring basic auth.
App 2 is my frontend, Node/Next.js, which wants to query the API (server side).
So I GET `srv-captain--app1/api`, using Node's `fetch`, but I get an error that basic auth requires HTTPS.
`https://srv-captain--app1/api` doesn't resolve.
`https://app1.public-url.com/api` works! But I'm not sure if using the public URL makes any difference that I should be aware of?
