### ISSUE TITLE
I can't be able to run socket.io and express on 2 different ports

### ISSUE THREAD

**Issue by eliagentili** [caprover/caprover#1732]
My app uses socket.io and express, and exposes both on different ports.

socket.io on 3011
express app on 3012

As you can see, I set the default port of my container to the express port (3012), enabled Websocket support, and enforced https.

![CapRover-Server-Dashboard](https://user-images.githubusercontent.com/1882869/233150234-443447b8-d993-4cbb-a1a2-539c256f3a80.png)

I also mapped the ports.

![CapRover-Server-Dashboard (1)](https://user-images.githubusercontent.com/1882869/233150572-e252eb6e-3aca-4fcf-bc66-5cb32a0e779d.png)

And the server starts well.

![CapRover-Server-Dashboard (2)](https://user-images.githubusercontent.com/1882869/233150779-b69f744b-1972-4114-bf3a-6c5a86aaf946.png)

The Express API works well, but unfortunately, every time I try to connect to socket.io, I get this error in the frontend:
net::ERR_CONNECTION_REFUSED

![Screenshot 2023-04-19 alle 19 19 56](https://user-images.githubusercontent.com/1882869/233151762-61bb3766-b2fa-4ebc-94f6-f509bdf59931.png)

Can someone help me?

**Comment by githubsaturn** [comment]
By using port mapping you're bypassing nginx configuration. Meaning that you can't even use HTTPS.

Without port mapping, when you only have one express app:

```
[user] ==== [https] === > [nginx] === http @ port 3012 of your app
```


When you use port mapping you don't even need to use the domain name as it's only used to resolve the IP.
```
User:

http://<IP-of-Your-Server>:3012 =====> DIRECTLY to your app
```

Now, I am not sure how socket.io is supposed to work. But regardless, this is not a CapRover issue. It's a weird setup to use Socket.io in a different port. Even their official example uses the same port:
https://socket.io/get-started/chat
