### ISSUE TITLE
[Question] Deploy static content through nginx rule instead of creating a nginx container

### ISSUE THREAD

**Issue by zDEFz** [caprover/caprover#1736]
Goal: Serve subdomain.domain.tld through nginx with the folder /public

Steps done:
1. created a app called 'up' with 'has persistent data'
2. map /public to /public
3. in dockerfile, added FROM nginx:latest and hit deploy
4. ssh into server, docker ps --all | grep up
5. docker exec -it containername bash
6. apt update; apt install nano
7. nano /etc/nginx/nginx.conf
8. append into  server block http://ix.io/4uaq

Question: Is that not possible without making a nginx container in a already nginx serving environment? Once I change the 'up' App, the container will be without the changes I manually did and that isnt so clever.

![f53a00b1-710a-4f3b-a550-46d94872862d](https://user-images.githubusercontent.com/24463722/233993943-786d4405-1de1-4f11-87fc-f7822334c133.png)

**Comment by githubsaturn** [comment]
>  Is that not possible without making a nginx container in a already nginx serving environment? Once I change the 'up' App, the container will be without the changes I manually did and that isnt so clever.

No. It's an anti pattern. The default nginx container managed by CapRover is simply a reverse proxy. Adding a second nginx container to any static app is necessary for static content.

There is little to no overhead with the additional nginx proxy, less than a millisecond delay and less than 5mb ram usage.
