### ISSUE TITLE
Recommended way to upgrade redis for an existing 1-click app?

### ISSUE THREAD

**Issue by vishnu-narayanan** [caprover/caprover#1753]
What is recommended way to upgrade redis for an existing 1-click app?

Context: Chatwoot requires redis7+ with the latest release. What is the best way to upgrade redis for existing installations without loosing data?

ref: https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/chatwoot.yml

**Comment by Tivin-i** [comment]
Usually for any type of app upgrade, you can just change the tag for the upgrade.
If you don't have mapped volumes, then the data is lost anyway when you relaunch the container, otherwise everything is stored on the mapped volume.
Upgrading Redis is not different from any other type of app.

**Comment by uhlhosting** [comment]
> Usually for any type of app upgrade, you can just change the tag for the upgrade.
> 
> If you don't have mapped volumes, then the data is lost anyway when you relaunch the container, otherwise everything is stored on the mapped volume.
> 
> Upgrading Redis is not different from any other type of app.

There seems to be procedures to upgrade the DB hence each redis major release have their own dumps that might differ.  So be mindfull the upgrade process is not just changing the redis version, that would also involve using the MIGRATE redis cmd maybe to bring the dump to version 7.x format.

**Comment by Tivin-i** [comment]
You are correct on the major releases, and folks should read the recommended upgrade paths and release notes for such upgrades.
My precious comment would only apply for minor versions majority of the time.

**Comment by githubsaturn** [comment]
https://caprover.com/docs/one-click-apps.html#upgrading-one-click-apps
