### ISSUE TITLE
[Question] How to add page redirect within nginx config

### ISSUE THREAD

**Issue by bobbyZ94** [caprover/caprover#1754]
I am stuck trying to make a page redirect happen within the nginx config.
A page doesn't exist anymore and needs to be permanently redirected (preferably with 301 and "return redirect"), beacuse its still listed on google.

Https is enabled and forced.
Currently only my www to non www redirect is working (I simply added a new server block at the top):

```
server {
    listen 443;
    server_name www.example.de;
    return 301 $scheme://example$request_uri;
}
```

Now i tried this:

```
server {
    listen 443;
    server_name example.de;
    location /home {
        return 301 $scheme://example.com
    }
}
```

But it doesnt work. Even putting the location block inside the preconfigured nginx server block (under the s.hasSSL if statement) or at the bottom did not work.
What am i doing wrong?

**Comment by githubsaturn** [comment]
@bobbyZ94  - please post the entire nginx configuration for your app.

Alternatively: a better approach is to programatically make these redirects as they are much easier to manage and you don't have to modify the existing nginx config.
