### ISSUE TITLE
Email Engine dockerhub image deprecation

### ISSUE THREAD

**Issue by rinshadka** [caprover/caprover#1763]
Hello,

While deploying the Email Engine I could see a deprecation warning in the emailengine dashboard regarding the docker image used.

https://hub.docker.com/r/andris9/emailengine

vs

https://hub.docker.com/r/postalsys/emailengine

How can we replace the first with the second dockerhub image. Or need to do a custom deployment placing the new image in captain definition file etc..

Thanks for the support.

**Comment by githubsaturn** [comment]
You can deploy a new image on the existing app using " Method 6: Deploy via ImageName"

Note that sometimes different images require different setups (different env vars, volumes etc). Be sure to read their documentation before trying to upgrade.

**Comment by rinshadka** [comment]
![image](https://github.com/caprover/caprover/assets/40381766/a01e827a-7741-478c-b6b3-ca456e5b480a)

Hello,  

This is the warfning that I am gettting after installing EmailEngine. pls review 

Thanks.
