### ISSUE TITLE
SSL routines ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by brandonramosv** [caprover/caprover#1764]
When I want to execute the "caprover deploy" command, I cannot validate that the service is active. When I check the log on the server, I get this message

![image](https://github.com/caprover/caprover/assets/12699929/be3b500d-5c5f-4d17-ad8f-27206948001f)

**Comment by githubsaturn** [comment]
Surely you cannot use https with localhost.

This is not how you get the server logs. Get the logs using `docker service logs captain-captain --since 60m`
