### ISSUE TITLE
Why does the connection to the server get disconnected every 60s (Server-Sent Events (SSE))?

### ISSUE THREAD

**Issue by gangal86** [caprover/caprover#1765]
My application is built on express.js and it works fine locally.

After deploying the application on a server managed by Caprover, I started experiencing timeout issues with the request.

I establish a persistent connection using Server-Sent Events (SSE), and the connection is successfully established. However, it gets disconnected every 60 seconds.

Here's my nginx configuration:

```
server {
    <% if (s.forceSsl) { %>
    listen       80;
    server_name  <%-s.publicDomain%>;

    # Used by Lets Encrypt
    location /.well-known/acme-challenge/ {
        root <%-s.staticWebRoot%>;
    }

    # Used by CapRover for health check
    location /.well-known/captain-identifier {
        root <%-s.staticWebRoot%>;
    }

    location / {
        return 302 https://$http_host$request_uri;
    }
    <% } %>

    server {
        <% if (!s.forceSsl) { %>
        listen       80;
        <% } %>
        <% if (s.hasSsl) { %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
        <% } %>

        client_max_body_size 500m;
        server_name  <%-s.publicDomain%>;

        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {
            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            proxy_read_timeout 86400s;
	    proxy_connect_timeout 86400s;
	    proxy_send_timeout 86400s;
	    send_timeout 86400s;

            proxy_ignore_client_abort on;
            proxy_ignore_headers "Connection" "Keep-Alive" "Proxy-Authenticate" "Proxy-Authorization" "Upgrade" "Host";

            if ($http_upgrade = 'websocket') {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
            root <%-s.customErrorPagesDirectory%>;
            internal;
        }
    }
    
    types {
        text/event-stream   sse;
    }
}

```

What could be the problem?

**Comment by githubsaturn** [comment]
@gangal86  - this is an nginx question (not specific to CapRover), but I believe you should start looking into timeouts and keepalive in nginx. Look into these links for some hints:

- https://serverfault.com/questions/777749/how-to-disable-timeout-for-nginx
- https://linuxhint.com/what-is-keepalive-in-nginx/
- https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx
- https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

**Comment by githubsaturn** [comment]
Just briefly looking at your nginx config, it's one of the more complex ones. Not sure if you actually need all of these.

For example for this one:
```
request_method = OPTIONS
```
you can just set the headers and response in your code - you don't need to modify nginx for these sort of things. It's not directly related to the issue you're experiencing, but generally speaking, the simpler your configuration is, the easier it is to debug.

**Comment by githubsaturn** [comment]
Another thing you can try is to try to send events every few seconds to see if the connection drops because it's inactive, or there is something else going on.

**Comment by gangal86** [comment]
> Another thing you can try is to try to send events every few seconds to see if the connection drops because it's inactive, or there is something else going on.

If I send an event with an interval less than 60 seconds then the connection stays active all the time. The connection is disconnected only if it is inactive for more than 60 seconds. Thanks for your answers, I'll try to make the nginx settings more optimal.
