### ISSUE TITLE
[Question] Change network prefix srv-captain--

### ISSUE THREAD

**Issue by Kkeller83** [caprover/caprover#1766]
How can I change the prefix srv-captain-- to something custom please?

Would I need to change the code in utils or is there a config to override that I could use?

   for (let i = 0; i < dockerServices.length; i++) {
                        const element = dockerServices[i]
                        if (
                            element.Spec.Name ===
                            'srv-captain--' + appNameToSearch
                        ) {
                            return element.Spec.TaskTemplate.ContainerSpec.Image
                        }
                    }

Thank you!

**Comment by githubsaturn** [comment]
Changing the prefix has unexpected behavior, CapRover uses these names to search for specific services and making changes. So you should not try to change this prefix.
