### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by davidleebooth** [caprover/caprover#1767]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
Upgrading peertube to 5.X requires some additional configuration in NGINX config for websockets wss:// to connect. The Default NGINX for this change has been provided here:
https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube
from line 115-145 there is the section pertaining to websockets, with the final lines regarding plugin location being new to 5.x
But I cannot or the life of me get the site to respond, I have attempted various different placements, also changed proxy_pass http://backend; to $upstream, replaced the entire NGINX just to see since I know that can mess with ssl and caprover. This error is always returned to the front

360.e3d42fe8da2a6e0a.js:1 WebSocket connection to 'wss://davbot.media/socket.io/accessToken=27401f1c2aa160f56dd9ba5d8d8df47b2436bb20&EIO=4&transport=websocket&sid=j2O0M_fLQm8Vx6WgAAAE' failed: 

Also while streaming, All other instances I am federated with spin, this also just hangs on mobile devices. I have websockets enabled

If applicable, content of `captain-definition` file:
Installed via one-click apps, updated using deploy via image name:
https://hub.docker.com/layers/chocobozzz/peertube/production-bullseye/images/sha256-d0516ca62682cd504621f0bfd0c7cc59fa41938ad89321e4849aedda344428ae?context=explore

Steps to reproduce the problem:
Install Peertube 4.x via one click app
Generate a base64 serial add it to env as PEERTUBE_SECRET to prepare to update to 5.x
Update by deploying via image name to 5.x

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
Linux vps-0e7ffa68 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
              total        used        free         shared      buff/cache   available
Mem:      15G        8.5G        465M        639M          6.4G        5.9G
Swap:         0B          0B          0B

Thank you to anyone for taking the time to look this over.

**Comment by githubsaturn** [comment]
This seems to be related to one click apps. Please see [here](https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md)

![image](https://github.com/caprover/caprover/assets/10582082/9af9320f-1b79-4c6d-9775-39d019e8fb54)


The latest PR touching PeerTube is here: https://github.com/caprover/one-click-apps/pull/897
