### ISSUE TITLE
Caprover serversetup is throwing this message "You may have already setup the server with root domain: ..." 

### ISSUE THREAD

**Issue by alcarazolabs** [caprover/caprover#1769]
Hi dear,
On my first try after run "caprover serversetup" I got an error after set the email for https certs. This error maybe was because previously after  2 minutes of set the record A of the domain for the apps with a TTL of 3600, in this case I should wait one hour but I didn't it.
I decided don't wait much time but after continuing setting the email for the https certs I got one error:

![image](https://github.com/caprover/caprover/assets/7144988/101d4a87-8a4a-4d7e-8346-b600e7d324fa)

ok, then I decided wait more than one hour, and now I did "caprover logout" and unisntalled it by using "npm uninstall -g caprover".
But now after run "caprover serversetup" this is throwing this message that avoid me continue:

`You may have already setup the server with root domain: app.fdaicloud.com! Use caprover login to log into an existing server.
`

![image](https://github.com/caprover/caprover/assets/7144988/81dfa2bf-aeb0-4e61-9f5a-baf785d7bb8b)

I don't know where comes this messages. I have uninstalled caprover in two environments with different nodejs versions and the same message remains.

I also removed the docker images of caprover in my server.

```
docker service rm $(docker service ls -q)
docker swarm leave --force
```

and I have reinstalled this but again the same message remains: You may have already setup the server with root domain:.....xxxx

Now in my windows pc I don't have caprover sessions, I did logout to all, but when I run "caprover serversetup"  all starts fine but after type the ip of the server the message remains. 

I would like to know a way of remove the cache in my windows pc? is possible start from scratch again?
what should I do in this case.

thanks in advance

**Comment by githubsaturn** [comment]
This [error is thrown](https://github.com/caprover/caprover-cli/blob/d6a4e7205e56077c93fe66e91a88188c5c3de65b/src/commands/serversetup.ts#L216-L220) when a redirect to https is detected on port 3000.


This usually means that the server is fully set up and "force https" is enabled. As far as I can see, this must be a local issue as the response might have been cached on your machine. I ran a curl with `http://captain.app.fdaicloud.com:3000` and it seems to be working fine. 



![image](https://github.com/caprover/caprover/assets/10582082/757d74fb-f51c-4ed9-a24c-53e8e844e07b)




Note:
- You do not need to run `npm uninstall -g caprover` - like I said, this is an error due to a redirect.
- Instead, try waiting a few hours and/or restarting your local machine (windows). 
- If none of these work and Windows keeps returning the cache try using `alt.app.fdaicloud.com` as your root domain. Since you have set up a wildcard, this root domain will also work. In fact you can use anything instead of `alt` without changing any DNS settings.

**Comment by alcarazolabs** [comment]
Hi, I tried again, this time a deleted the droplet and I have created another A record with the name .xyz.fdaicloud.com
and after run "caprover serversetup" it throwed this error:

`Error: RequestError: Error: getaddrinfo ENOTFOUND captain.xyz.fdaicloud.com
`
![image](https://github.com/caprover/caprover/assets/7144988/51400160-1226-42f7-8206-b630ab790461)

After it, every time that I try run again "caprover serversetup" it throws this messag:

`You may have already setup the server with root domain: xyz.fdaicloud.com! Use caprover login to log into an existing server. `
http://captain.xyz.fdaicloud.com/ is down and the installation was not successful.

any idea?

**Comment by githubsaturn** [comment]
You have deleted your DNS record:


![image](https://github.com/caprover/caprover/assets/10582082/3b1cc4a2-006d-4aa7-a5b8-3200969114b9)

**Comment by githubsaturn** [comment]
It's step 2 in the guide:
https://caprover.com/docs/get-started.html#step-2-connect-root-domain

**Comment by alcarazolabs** [comment]
> You have deleted your DNS record:
> 
> ![image](https://user-images.githubusercontent.com/10582082/243496286-3b1cc4a2-006d-4aa7-a5b8-3200969114b9.png)

I deleted *.app and I created another A record called *.xyz of this way: xyz.fdaicloud.com

![image](https://github.com/caprover/caprover/assets/7144988/8cd45ddf-b98d-43af-b99a-06ba7bc6e90c)

it Has been passed two hours after created it.
I seems that I will need to delete the droplet again to try with a new ip address because I will start getting this message:

`You may have already setup the server with root domain: xyz.fdaicloud.com! Use caprover login to log into an existing server. `

**Comment by githubsaturn** [comment]
Seems like this is working just fine: http://captain.xyz.fdaicloud.com/#/login

Just login to the dashboard using `captain42` as the password, then:
- Enable HTTPS on the dashboard
- Then Force HTTPS
- Then change the password in Settings
- Then use `caprover login` to login to your server on your terminal

**Comment by alcarazolabs** [comment]
> http://captain.xyz.fdaicloud.com/#/login

Hi thanks for the reply, I did that with my new server, however now I only can access to the website:
https://captain.appxyz.fdaicloud.com/#/login
by using the TOR browser, and by using firefox or google chrome I can't

Chrome:
![image](https://github.com/caprover/caprover/assets/7144988/1d020736-c969-48c9-897d-76a320dc3fc2)

TOR:
![image](https://github.com/caprover/caprover/assets/7144988/a56a9259-f35b-4d0a-9630-f44abf5420bb)

Why happens it?

Also when I try do login by using the CLI I'm getting this error:

`Error: getaddrinfo ENOTFOUND captain.appxyz.fadaicloud.com`

![image](https://github.com/caprover/caprover/assets/7144988/a6b9d6db-0851-4874-8e4e-96d8cc67c5c5)

Any idea why happens it?

thanks

**Comment by githubsaturn** [comment]
You have a local system problem. Either your system is infected or you have a weird network settings (some unusual local DNS set up). I've tried your domain on chrome and it works fine. 

I suggest asking one of your friends (different laptop, different network) to try to see if it works for them. 

![image](https://github.com/caprover/caprover/assets/10582082/5fb2b822-b32d-4040-83f6-315c2d6d01c9)

**Comment by githubsaturn** [comment]
> In my windows machine I can't do ping to the host captain.appxyz.fdaicloud.com
but using a online tool it can:


This is another indication that something is wrong with your machine. Somehow the OS is using some broken DNS settings. I don't know why. But either your machine is infected with virus, or it's misconfigured, or you have some specific firewall or DNS that is blocking your machine from the global DNS providers.

**Comment by alcarazolabs** [comment]
> This is another indication that something is wrong with your machine. Somehow the OS is using some broken DNS settings. I don't know why. But either your machine is infected with virus, or it's misconfigured, or you have some specific firewall or DNS that is blocking your machine from the global DNS providers.

Thanks, definitly this was an issue with my internet provider, I call them and fixed this issue doing something in the router.
Now I am able to do ping, caprover login etc.. 

I learned new things definitle with this issue. Thanks for you time to help me to fix this problem.

**Comment by githubsaturn** [comment]
Glad it was fixed!
