### ISSUE TITLE
Issue: Unable to Use TaskTemplate Override As Documented

### ISSUE THREAD

**Issue by krystofbe** [caprover/caprover#1770]
I am reaching out because I'm having an issue with using a server Docker service override as described in the documentation.

Following the guidelines provided, I've constructed my `TaskTemplate` like so:

```
TaskTemplate:
  ContainerSpec:
    Command: "./mycommand.sh"
```

Unfortunately, this implementation has not been successful, as it returns the following error:

`json: cannot unmarshal string into Go struct field ContainerSpec.TaskTemplate.ContainerSpec.Command of type []string`

Upon receiving this error, I began to wonder if the `Command` field should be formatted as an array. Here's the revised version I came up with:

yaml

```
TaskTemplate:
  ContainerSpec:
    Command:
      - "./mycommand.sh"
```

Could you please confirm if this is the correct approach? I appreciate your time and look forward to hearing back from you.

**Comment by githubsaturn** [comment]
@krystofbe  - thanks for the note! Yes, you're correct. The example is wrong. I'll correct it asap.

For future reference, this is the exact schema that should be used for service override:
https://docs.docker.com/engine/api/v1.40/#tag/Service/operation/ServiceUpdate
