### ISSUE TITLE
App deployed, but container does not restart

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1771]
Hi there, 

i have an app, wich gets updated via gh actions like so:

```
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.DEV_CAPROVER_SERVER }}'
          app: '${{ secrets.DEV_APP_NAME }}'
          token: '${{ secrets.DEV_APP_TOKEN }}'
          image: img-name-${{
            steps.extract_version.outputs.version }}

```

it does work, and it does finish deploying: 
![Bildschirmfoto vom 2023-06-07 15-42-41](https://github.com/caprover/caprover/assets/1011875/7bb00168-01d6-43f4-909b-3214c7af8c9b)

BUT: if i look at the container it did not restart - and so the new version is not running.
Even if i go to App Config and click on Save & Update, the container does not get restarted.  (docker ps still shows that the container is running for hours... but it should show seconds since the deploy)
How and where would i start looking for the problem?? 

EDIT: restarting the whole machine does work... it will load the most recent deploy
Any Help is very appriciated!!!

**Comment by alcarazolabs** [comment]
Try to look at the logs.
`docker service logs srv-captain--my-app --since 60m --follow
`
Replace my-app with caprover app.
https://caprover.com/docs/troubleshooting.html#how-to-view-my-applications-log

**Comment by githubsaturn** [comment]
@pcace - yoru problem is related to your container update.

Next time you see this happening, try running `docker service ls` and see what version is currently running. If that's not the right version, try manually updating the image by running this:
```
docker service update srv-captain--yourappname --image dockerregistry.something.com/youruser/yourimage:yourversion 
```

this should show you the error that resulted in failure during the update process.

**Comment by githubsaturn** [comment]
For example, if the new version crashes on app start up, Docker internally refuse to update the image because it fails to "properly start up"

**Comment by githubsaturn** [comment]
Another example if there is any port being mapped for that service, the previous container must release the ports before the new container can be created.

**Comment by pcace** [comment]
> For example, if the new version crashes on app start up, Docker internally refuse to update the image because it fails to "properly start up"

hm, i cannot find any evidence that it is crashing on startup.

> Another example if there is any port being mapped for that service, the previous container must release the ports before the new container can be created.

that sounds interesting. Since the correct image gets loaded whenever i reboot the whole machine. (so obviousely the port gets freed). How can i assure that this is not the problem or if it is, how can i tell caprover / docker that the old image + port needs to be closed properly?



> @pcace - yoru problem is related to your container update.
> 
> Next time you see this happening, try running `docker service ls` and see what version is currently running. If that's not the right version, try manually updating the image by running this:
> 
> ```
> docker service update srv-captain--yourappname --image dockerregistry.something.com/youruser/yourimage:yourversion 
> ```
> 
> this should show you the error that resulted in failure during the update process.

trying to follow your suggestion i did docker service ls on the current running system. it shows (among others) this line:

`n3hpej3g1dfo   srv-captain--ffy-selfservice            replicated   1/1        dockerregistry.serverserver.com/ffy/img-captain-ffy-selfservice:110       
`
when deploying a new version in gh action it shows this version/image name: 

`img-captain-ffy-selfservice-dev:-0.7.13`
and it gets deployed like this in gh action:
```
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.DEV_CAPROVER_SERVER }}'
          app: '${{ secrets.DEV_APP_NAME }}'
          token: '${{ secrets.DEV_APP_TOKEN }}'
          image: img-captain-ffy-selfservice-dev:${{
            steps.extract_version.outputs.version }}


```
in caprover it builds the new app, and finishes successfully, but shows this: 

```
Successfully built 332a9d8647b7
Successfully tagged img-captain-ffy-selfservice:latest
Pushing to remote: dockerregistry.server.com/ffy/img-captain-ffy-selfservice:112
Server: dockerregistry.server.com
This might take a few minutes...
Push succeeded...
Build has finished successfully!
```


looking now at the docker service ls it shows the new version: 

`n3hpej3g1dfo   srv-captain--ffy-selfservice            replicated   1/1        dockerregistry.server.com/ffy/img-captain-ffy-selfservice:112       `

but looking at docker ps it clearly shows that the old version is running: 

`f91ca1fbd049   dockerregistry.server.com/ffy/img-captain-ffy-selfservice:110       "docker-entrypoint.s…"   15 hours ago   Up 15 hours             3000/tcp                                                                   srv-captain--ffy-selfservice.1.skz4c655rcf0cis5xfemkm1cl
`

so i have two things i dont understand: 

1. why is there the new version in the docker service ls but not in docker ps?
2. i am pushing via gh actions with the image name ```
img-captain-ffy-selfservice-dev:${{
            steps.extract_version.outputs.version }}
``` shouldnt it be the name wich comes up in caprover?

Thanks a lot for help, 

Cheers

**Comment by pcace** [comment]
> 

Sorry, i did forget to post the output of the manual service update: 

```
docker service update srv-captain--ffy-selfservice --image dockerregistry.server.com/ffy/img-captain-ffy-selfservice:113
image dockerregistry.server.com/ffy/img-captain-ffy-selfservice:113 could not be accessed on a registry to record
its digest. Each node will access dockerregistry.server.com/ffy/img-captain-ffy-selfservice:113 independently,
possibly leading to different nodes running different
versions of the image.

srv-captain--ffy-selfservice
overall progress: 0 out of 1 tasks 
1/1: no suitable node (insufficient resources on 1 node) 
```

since i am not really familiar with docker i think i need help here - what does that actually mean?

**Comment by githubsaturn** [comment]
As I imagined, this is a Docker issue (not CapRover specific), try filing a report on Docker's github issues and copy paste the output that you have above.

In the meantime, you can try using this as your [service override](https://caprover.com/docs/service-update-override.html):
```yaml
UpdateConfig:
  Order: stop-first
```

* Then, "Save and Update"
* Then, reboot your machine
* Then, try deploying a new image
