### ISSUE TITLE
[Question] specifying Docker Hub credentials for a private image in a Dockerfile

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1775]
Currently I am basing some of my Dockerfiles on a _public_ image stored in my own Docker Hub account, with e.g. `FROM my-docker-name/my-public-image:v12`.

But if I am now wanting to get the image from my Docker Hub account, but this time from a _private_ repo on my Docker Hub, is it enough just to add my Docker Hub credentials to the "Docker Registries" part of the Cluster page in the CapRover console?  

Then I can start my Dockerfile with e.g. `FROM my-docker-name/my-private-image:v13`?

I am deploying using Method 1, i.e. `caprover deploy`.

Also note that I'm using a self-hosted registry to hold all of the images built by CapRover, so that is already on the Cluster page as `registry.myserver.myhost.com:996`... I can add a second one (i.e. my private Docker Hub credentials)?

And I assume that these Docker Hub registry credentials would survive a backup/restore method based on the backing up and restoring the contents of the `/captain` folder (see [here](https://github.com/caprover/caprover/issues/187#issuecomment-400459678))?

**Comment by drmrbrewer** [comment]
I used the following when adding the new registry in CapRover:

- Domain: `registry.hub.docker.com`
- Username: `my-docker-name`
- Password: my usual Docker Hub password
- Image Prefix: leave blank

Then I pushed a new image to a private repository called `my-private-repo` with tag `v3`.

For the base image in my Dockerfile I used: `FROM registry.hub.docker.com/my-docker-name/my-private-repo:v3`.

And did a `caprover deploy`.

And it worked!

Perhaps I should be using `docker.io` instead of `registry.hub.docker.com` for the Domain, for example based on [this comment](https://stackoverflow.com/questions/34198392/docker-official-registry-docker-hub-url#comment103963151_40483082) and some other answers/comments to that question.

**Comment by githubsaturn** [comment]
That's great! I'm glad that it worked!

Yes, docker.io, specifically `registry-1.docker.io`, is usually used for DockerHub private repos. But perhaps they've made some changes to their DNS and now `registry.hub.docker.com` also works... 

Prefix is also used for credentials. You can see how it's being used here:
https://github.com/caprover/caprover/blob/9a2447d1041a260f8e9624cc12b3261e251ef89b/src/user/DockerRegistryHelper.ts#L118-L134

**Comment by drmrbrewer** [comment]
I tried the second setup above (i.e. with a domain of just `docker.io`) and it didn't work (even with the prefix included in the image base name).  

So it seems that the domain should either be `registry.hub.docker.com` or `registry-1.docker.io`.  I didn't try the latter, because:

- I prefer the former... it just seems more generic... and closer in form to the URL for the repo e.g. `https://hub.docker.com/r/my-docker-name/my-private-repo` (and closer to the URL for the self-hosted registry)
- it seems that they may change away from `registry-1.docker.io` domain in future... [see here](https://github.com/moby/moby/blob/master/registry/config.go#L25-L48)... so clearly they don't think it's a great choice for a domain name either... though they will ensure backward compatibility

And the prefix still needs to be included in the image base name, so it seems that it's just for distinguishing between different registry credentials, which might share the same domain.

So this is my working setup:

- Domain: `registry.hub.docker.com`
- Username: `my-docker-name`
- Password: `my-docker-hub-password`
- Image Prefix: `my-docker-name`
- private repo name: `my-private-repo`
- tag: `v5`
- base image name: `FROM registry.hub.docker.com/my-docker-name/my-private-repo:v5`

**Comment by drmrbrewer** [comment]
@githubsaturn although it works, I think there may be implications for the backup/restore process I have implemented, as described [in here](https://github.com/caprover/caprover/issues/187#issuecomment-400459678)... basically I just backup everything in `/captain` including the `config-captain.json` file, and restore it on the new server.

But when I do the restore, there is some clean-up to do, which I am using the CLI for (in a cloud-init script).  For example, I have to disable the self-hosted registry, and then re-enable it, via the `caprover api` CLI.

I guess that this would also be required for my docker remote registry, because in the config file I see that the password is stored encrypted under `registryPasswordEncrypted`, within `dockerRegistries`, so this wouldn't work after the config is restored on a new server?

Would I do this via [deleteDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L437-L446) and [addDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L415-L424)?  The delete command requires the `id`, which is what is in the `dockerRegistries` entry in the config file?  Would need to figure out how to extract that from the config file and use it in the CLI.

Or maybe I can use [updateDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L426-L435) instead of `deleteDockerRegistry`/`addDockerRegistry`?
