### ISSUE TITLE
[Question] updating docker registry via caprover api

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1777]
This is a follow-up to [this question](https://github.com/caprover/caprover/issues/1775), to avoid going off-topic there...

@githubsaturn although the linked method works (using a private docker repo as the base image), I think there may be implications for the backup/restore process I have implemented, as described [in here](https://github.com/caprover/caprover/issues/187#issuecomment-400459678)... basically I just backup everything in `/captain` including the `config-captain.json` file, and restore it on the new server.

But when I do the restore, there is some clean-up to do, which I am using the CLI for (in a cloud-init script).  For example, I have to disable the self-hosted registry, and then re-enable it, via the `caprover api` CLI.  

Firstly, when there was only one registry present (i.e. just the self-hosted registry), it seemed that the "default push" was also automatically set to the self-hosted registry when it is re-created.  But, with my my docker registry also there, no default is set, and it seems that I need to add an explicit API call to set the id of the default push to the re-enabled self-hosted registry.

Secondly, it seems that I also need to reconfigure my docker registry entry after restore, because in the config file I see that the password is stored encrypted under `registryPasswordEncrypted`, within `dockerRegistries`, so this wouldn't work after the config is restored on a new server?

Would I do this via [deleteDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L437-L446) and [addDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L415-L424)?  The delete command requires the `id`, which I can extract from [getDockerRegistries](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L382-L387).

And maybe I should use [updateDockerRegistry](https://github.com/caprover/caprover-cli/blob/master/src/api/ApiManager.ts#L426-L435) instead of `deleteDockerRegistry`/`addDockerRegistry`?

BTW I _have_ tried using `updateDockerRegistry`, but I'm not sure what structure the posted `data` should be... I've tried both of the following json config files with `caprover api --configFile config.json`:

	{
	  "caproverName": "myname",
	  "caproverUrl": "https://my.example.domain.com",
	  "caproverPassword": "mypwd",
	  "path": "/user/registries/update",
	  "method": "POST",
	  "data": {
		"dockerRegistry": {
		  "id": "7d32f56a-c3fd-46a4-a3ed-8c1128dd5681",
		  "registryDomain": "registry.hub.docker.com",
		  "registryImagePrefix": "my_docker_name",
		  "registryUser": "my_docker_name",
		  "registryPassword": "my_new_password",
		  "registryType": "REMOTE_REG"
		}
	  }
	}

	{
	  "caproverName": "myname",
	  "caproverUrl": "https://my.example.domain.com",
	  "caproverPassword": "mypwd",
	  "path": "/user/registries/update",
	  "method": "POST",
	  "data": {
		"id": "7d32f56a-c3fd-46a4-a3ed-8c1128dd5681",
		"registryDomain": "registry.hub.docker.com",
		"registryImagePrefix": "my_docker_name",
		"registryUser": "my_docker_name",
		"registryPassword": "my_new_password",
		"registryType": "REMOTE_REG"
	  }
	}

But I just get:

	Something bad happened calling API /user/registries/update at https://my.example.domain.com.

	Error Code: 1112  Message: Authentication failed. Either username, password or domain is incorrect.

And yes, I'm sure that the details are correct, because I just took the existing, and changed `registryPassword` to the new one (`my_new_password`).

What am I doing wrong with the `updateDockerRegistry` call?  Should I be passing an array of all registries?  Not just the one I'm trying to update?

**Comment by githubsaturn** [comment]
What's your my_new_password? Did you change your docker hub's password?

That error is thrown when CapRover reaches out to Docker Hub with your provided credentials and makes sure that the API authenticate your credentials. 
https://github.com/caprover/caprover/blob/9a2447d1041a260f8e9624cc12b3261e251ef89b/src/user/DockerRegistryHelper.ts#L343-L355

**Comment by githubsaturn** [comment]
Regarding the structure, it's the second structure. You can always verify the structure by inspecting network traffic and see the payload:

![image](https://github.com/caprover/caprover/assets/10582082/fe4e93da-eba3-45dd-b44a-3b763653bd73)

**Comment by drmrbrewer** [comment]
> What's your my_new_password?  Did you change your docker hub's password?
> 
> That error is thrown when CapRover reaches out to Docker Hub with your provided credentials and makes sure that the API authenticate your credentials.

Ah I didn't realise that it would actually be verifying the credentials with Docker Hub; I assumed that the API call would effectively just be updating the config in CapRover, so was just testing with some random password... and assumed that the authentication was perhaps referring to CapRover.  

Perhaps the error message could clarify this?  e.g. 'Registry authentication failed.  Either username, password or domain is incorrect.'
