### ISSUE TITLE
Save Dockerfile provided in the dashboard

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#1780]
Thanks so much for maintaining this wonderful software over the years!

Can we please have the feature so that caprover persists the dockerfile written here even after deployment?

<img width="762" alt="image" src="https://github.com/caprover/caprover/assets/19492893/526e3d3e-cf9c-4661-8362-6fd0ec59812c">

Makes experimenting with new containers super easy and fun :)

**Comment by githubsaturn** [comment]
Thanks!

Duplicate of  https://github.com/caprover/caprover-frontend/issues/26
