### ISSUE TITLE
[Question] Automatically update nginx config

### ISSUE THREAD

**Issue by Firesphere** [caprover/caprover#1781]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Is it possible either via captain-definition file, or a pre/post deploy hook, to set custom Nginx config settings?

**Comment by githubsaturn** [comment]
No. 

nginx configuration is supposed to be one time update. To update nginx configuration, you need to update the app in the UI.

**Comment by Firesphere** [comment]
> No.
> 
> nginx configuration is supposed to be one time update. To update nginx configuration, you need to update the app in the UI.

Okay.
Not ideal, as almost all my applications require a larger header buffer for Nginx, thus having to do it manually for every app is a tad annoying.

I can live with it though... It's the dev life 😆 
Thanks for the swift response!

**Comment by githubsaturn** [comment]
If you're referring to `large_client_header_buffers` you can put it in `http` block... you don't need to modify every app.

http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers


CapRover > settings > Nginx config > "Base Config Location in nginx container: /etc/nginx/nginx.conf"

**Comment by Firesphere** [comment]
Hi @githubsaturn ,

I've tried that, but it breaks the CapRover interface every time. I think for now I'll just stick with my manual process :)
