### ISSUE TITLE
Can not connect to MariaDB container via SSH

### ISSUE THREAD

**Issue by Firesphere** [caprover/caprover#1782]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

### *This is potentially a Docker or Linuxserver/openssh problem and not CapRover*

---

**What is the problem?**

After deploying the linuxserver/openssh container, I can SSH in and ping my MariaDB container.

However, when trying to connect to the MariaDB container using my local SequelPro with SSH connection, the connection to MariaDB times out

**Steps to reproduce the problem:**

1. Create a MariaDB container from one-click-apps
2. Create an OpenSSH container from one-click-apps
3. SSH To the OpenSSH container, observe it works
    1. Ping the mariadb container at `srv-captain--{app-name}`, observe it works
4. Attempt to connect to MariaDB over SSH with a client, connection times out
5. Deploy a PHPMyAdmin container
6. PHPMyAdmin can connect as expected with the same credentials

**Output of the following command on your server:**

```
$ uname -a && lsb_release -a && free -h

Linuxled 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       933Mi       358Mi        99Mi       2.6Gi       2.5Gi
Swap:             0B          0B          0B
```

**Relevant containers:**
```
ccd472120f46   nginx:1                                                "/docker-entrypoint.…"   16 hours ago        Up 16 hours        0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   captain-nginx.1.x5487kmzaxzvd0ppqyiiexe7e
1ad4ac8047db   caprover/caprover:1.10.1                               "docker-entrypoint.s…"   16 hours ago        Up 16 hours        0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                  captain-captain.1.z13hpi6153fqubn61rpzorqoj
d55b7a09a707   img-captain-maria-db:1                                 "docker-entrypoint.s…"   2 days ago          Up 2 days          3306/tcp                                                                   srv-captain--maria-db.1.g8ja34c8rrg7zkukxiqjdv7dj
eb5332c2b47d   phpmyadmin/phpmyadmin:5.2.1                            "/docker-entrypoint.…"   2 days ago          Up 2 days          80/tcp                                                                     srv-captain--mysqladmin.1.i9839vaw4sssmptnrx1q490w9
fe7455a3433f   lscr.io/linuxserver/openssh-server:version-8.6_p1-r3   "/init"                  2 days ago          Up 2 days                                                                                     srv-captain--ssh.1.istdlhc06iouzay002coamejb
```

**Comment by githubsaturn** [comment]
> This is potentially a Docker or Linuxserver/openssh problem and not CapRover

Yes, it is an SSH/Docker question. But here is more info for your research:


> Attempt to connect to MariaDB over SSH with a client, connection times out

Not sure how you use your connection over ssh. But you need to make sure that you use SSH tunneling as explained here:
https://caprover.com/docs/database-connection.html#external-connections

1- Run the ssh port tunneling command as above
2- From your local machine, try running a simple TCP client to see if the port is even listening
3- Run your db client to connect.


If step 2 fails, confirm that you can connect to `srv-captain--maria-db:3306` from the ssh container. Note that pinging is not enough. Ping just confirms that the IP is accessible, it does not check if the port is listening.

**Comment by Firesphere** [comment]
Ahhhh, okay!

Yes, I did not realise that the documentation you mention applied in that sense. It might be a tad unclear for someone new to this kind of Docker set-up. I think I have enough to go on now :)
