### ISSUE TITLE
Upgrade NetData?

### ISSUE THREAD

**Issue by Firesphere** [caprover/caprover#1786]
**Is your feature request related to a problem? Please describe.**

The version of NetData used is outdated

**Describe the solution you'd like**

Use a newer version of NetData, that also supports Docker container monitoring

**Comment by githubsaturn** [comment]
This is already done. It will be part of the next release

**Comment by Firesphere** [comment]
In follow up...

Would it be possible for me to install my own NetData version, and integrate it manually?

**Comment by githubsaturn** [comment]
Yes, you can run any image and put it behind an nginx reverse proxy:

See this related thread: https://github.com/caprover/caprover/discussions/1785#discussioncomment-6258011
