### ISSUE TITLE
[Question] Is this project dead?

### ISSUE THREAD

**Issue by 9M6** [caprover/caprover#1789]
Hello,

As I see in the changelogs that there's no new development (or rarely any) of features for CapRover, I pose the question: Is this project dead?

Is it safe to use for the foreseeable future?

**Comment by nickreese** [comment]
@githubsaturn Question on this. Been using it heavily and super stably since last year, but wanted to know if we should be building what is on github or just using what is on docker hub? I see there is dev activity and am excited by it. :)

**Comment by githubsaturn** [comment]
Dockerhub version. 

A new release will be out in the next few months.
