### ISSUE TITLE
[Question] Pocketbase 404

### ISSUE THREAD

**Issue by Hertak** [caprover/caprover#1792]
I install 1 click app pocketbase and go to url y get a
`{
    "code": 404,
    "message": "Not Found.",
    "data": {}
}`
the url is https://[backend.af.academia.fischer.com.ar](https://backend.af.academia.fischer.com.ar/)/ 
I need do something more?

**Comment by githubsaturn** [comment]
It's a pocketbase question. See a similar problem here:
https://github.com/pocketbase/pocketbase/discussions/2140

CapRover is simply an installation tool. Pocketbase is literally built using their official github repo:
https://github.com/caprover/one-click-apps/blob/d4aa50cc4ca9a25f2454b242139643c6f0cecc31/public/v4/apps/pocketbase.yml#L7-L12

**Comment by Hertak** [comment]
Hi, thanks for response. It´s not the same problem, i don´t try to autenticate via api i just want enter to pocketbase. See this interface https://pocketbase.io/demo/.
Is the first step

**Comment by githubsaturn** [comment]
It's pocketbase question again... The admin UI is located at `/_` Please see the pocketbase docs:
https://backend.af.academia.fischer.com.ar/_/

![image](https://github.com/caprover/caprover/assets/10582082/004ca3db-2531-4e91-a9e4-aaa7a785ffd7)
