### ISSUE TITLE
[Deployment Issue] - Installation failed. Error: Couldn't find your IP

### ISSUE THREAD

**Issue by AristideBH** [caprover/caprover#1796]
Hello, it's my first time installing Caprover, and even fully setting-up my VPN, and i'm having a problem running the docker script.

## Context
Host : Hostinger VPS-1
OS : Ubuntu 22.04.2 LTS
Docker : Docker version 20.10.24, build 297e128 (also tried with latest 24.0.2 before that)
ufw status (wasn't installed by default, had to give it a few try)
```
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
80,443,996,2377,3000,4789,7946/tcp ALLOW       Anywhere
2377,4789,7946/udp         ALLOW       Anywhere
2222/tcp                   ALLOW       Anywhere
22                         ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80,443,996,2377,3000,4789,7946/tcp (v6) ALLOW       Anywhere (v6)
2377,4789,7946/udp (v6)    ALLOW       Anywhere (v6)
2222/tcp (v6)              ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
```
I manually uninstalled apache2 server that came de facto with the distro, and got nothing when navigating to my server ip address.
And haven't yet put any A records for domain redirection.

## The error
Running : `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` I get the following error : 
```
latest: Pulling from caprover/caprover
af4c2580c6c3: Pull complete
...
Digest: sha256:39c3f188a8f425775cfbcdc4125706cdf614cd38415244ccf967cd1a4e692b4f
Status: Downloaded newer image for caprover/caprover:latest
Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html

 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 1074 MB
Installation failed.
Error: Couldn't find your IP
    at /usr/src/app/node_modules/public-ip/index.js:172:10
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/app/node_modules/public-ip/index.js:199:15
```
The error takes about 5 min or so to appear, staying still on `Total RAM 1074 MB` line.

## What I've tried

Following some other issues, I've run the following commands : 
```
docker service ls
docker service logs captain-captain --since 5m
docker service ps captain-captain --no-trunc
``` 
and get the same answer for them all, giving me no informations : 
`Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.`

Then I ran : `curl -v http://localhost:3000` and got : 
```
*   Trying 127.0.0.1:3000...
* connect to 127.0.0.1 port 3000 failed: Connection refused
*   Trying ::1:3000...
* connect to ::1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000 after 1 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000 after 1 ms: Connection refused
```

Tried running the GetDocker script from here #1759, but that didn't help.

Also read about an issue with KVM VPS /LXD-based VPS, but I am totally ignorant on that part and would like to stay where my VPS currently is.

I'm a bit lost for now and will gladly send more info if needed !

**Comment by AristideBH** [comment]
Edit : 
I also tried `docker run -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` as stated in the page [here](https://gist.github.com/hivivo/20eb5355837533c968ecb9e684f85007?permalink_comment_id=4354454#gistcomment-4354454), although not running locally.

It work better as I get : 
```
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
July 6th 2023, 2:49:51.435 pm    Fresh installation!
July 6th 2023, 2:49:51.439 pm    Starting swarm at 127.0.0.1:2377
Swarm started: s8gcrixkzegjf562hes3ir7kh
*** CapRover is initializing ***
Please wait at least 60 seconds before trying to access CapRover.
```
But navigating to "ip-server:3000" return a Connection refused

**Comment by githubsaturn** [comment]
> Error: Couldn't find your IP

This means that one of the requirements for CapRover isn't fulfilled:

![image](https://github.com/caprover/caprover/assets/10582082/d1fb5cc6-2c6f-4a7f-932a-d5ea7f91dbdb)


Are you installing on a publicly available server with a network interface that has a public IPv4 ?

**Comment by AristideBH** [comment]
After running with the parameter `-e MAIN_NODE_IP_ADDRESS=x.x.x.x`, the install process has been throught the same as with 127.0.0.1

```
docker service ls 
docker service logs captain-captain --since 5m 
docker service ps captain-captain --no-trunc
```
now output this :
```
ID             NAME              MODE         REPLICAS   IMAGE                      PORTS
p2drggozhfq8   captain-captain   replicated   0/1        caprover/caprover:1.10.1
ID                          NAME                    IMAGE                      NODE          DESIRED STATE   CURRENT STATE             ERROR                                                                                                                                                                                            PORTS
s7vzfuwjbmm4m0gb8pav6a8ut   captain-captain.1       caprover/caprover:1.10.1   vps-ari.com   Running         Preparing 6 seconds ago                                                                                                         

jal2p01q14tvdwcihii5n401q    \_ captain-captain.1   caprover/caprover:1.10.1   vps-ari.com   Shutdown        Failed 8 seconds ago      "starting container failed: error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"
ahi5hrya0kql6eihkvbe9bwli    \_ captain-captain.1   caprover/caprover:1.10.1   vps-ari.com   Shutdown        Failed 24 seconds ago     "starting container failed: error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"
cx6yvjqmx6d82xzs7u2ophgwj    \_ captain-captain.1   caprover/caprover:1.10.1   vps-ari.com   Shutdown        Failed 35 seconds ago     "starting container failed: error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"
ujyxs2tnii3bejm7kv1q916z6    \_ captain-captain.1   caprover/caprover:1.10.1   vps-ari.com   Shutdown        Failed 44 seconds ago     "starting container failed: error creating external connectivity network: cannot restrict inter-container communication: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied"
```

**Comment by githubsaturn** [comment]
> open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied

Alright this is useful information. This is the root cause:

https://github.com/swarmpit/swarmpit/issues/554#issuecomment-688709728



VPS providers modify the OS to lower their cost by removing some features from the OS and this is what's happening... 


Use a provider with standard OS. DigitalOcean is a well tested provider by the community.
