### ISSUE TITLE
How to deploy owncloud/oCIS docker in caprover? [Deployment Issue]

### ISSUE THREAD

**Issue by amdg123** [caprover/caprover#1797]
I cannot figure out a way to deploy the owncloud oCIS docker using caprover. It has a two step deployment as follows:

```
docker pull owncloud/ocis
docker run --rm -it -v ocis-config:/etc/ocis owncloud/ocis init
docker run --rm -p 9200:9200 -v ocis-config:/etc/ocis -v ocis-data:/var/lib/ocis -e IDM_CREATE_DEMO_USERS=true owncloud/ocis
```

How can I translate this to a captain-definition file? If not how can I deploy this docker?

**Comment by githubsaturn** [comment]
Step 1:

Run this:
```
docker pull owncloud/ocis
docker run --rm -it -v /ocis-config:/etc/ocis owncloud/ocis init ## <<< I added a leading slash to the volume so that it becomes a physical directory on your host
```

Step 2:
Create an app and make sure you check the "Persistent Data" checkbox

Step 3:
Go to your newly created app settings on caprover and make these changes:
a- change the http port to 9200 (first tab in your app settings)
b- go to app config (second tab on app's settings) and add a persistent directory mapping, Path in App `/etc/ocis owncloud/ocis` Path on Host `/ocis-config` (make sure you set specific path host)
c - add another persistent directory mapping, Path in App `/var/lib/ocis` label `ocis-data` (make sure you let caprover manage path)
d- add an environment variable (second tab in app settings) `IDM_CREATE_DEMO_USERS` value: `true`

Step 4:
Click on Save & Update

Step 5:
go to the 3rd tab (deployment) and use " Method 6: Deploy via ImageName" - deploy `owncloud/ocis`
