### ISSUE TITLE
Domain Verification Failed - Error 1107!

### ISSUE THREAD

**Issue by microchel-git** [caprover/caprover#1798]
What is the problem?

I run CapRover on my linux server by follow command:
```docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover```

When I want to configure CapRover Root Domain, I write api.mydomain.online and get 1107 error. 
But I visit api.mydomain.online I see CapRover UI, so forwarding configured successful.

I tried this to skip domain verification dome by CapRover: 

echo  "{\"skipVerifyingDomains\":\"true\"}" >  -v /captain:/captain/config-override.json
docker service update captain-captain --force

Output:

```captain-captain
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged ```

Then I tried to configure CapRover Root Domain again, but I get same error as at the last time (1107).

Output of the uname -a && lsb_release -a && free -h :

Linux 18094 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:           969Mi       390Mi        89Mi        14Mi       489Mi       398Mi
Swap:             0B          0B          0B

**Comment by githubsaturn** [comment]
You have a typo here:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  -v /captain:/captain/config-override.json
```
Not sure where you got this... but there should not be any `-v` in the command... this is wrong. The correct one is:

```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
```

**Comment by microchel-git** [comment]
> 
I get:
`-bash: /captain/data/config-override.json: Permission denied`

`sudo echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json`

Gives me the same result

**Comment by githubsaturn** [comment]
> Gives me the same result

What do you mean by this? Do you still get 1107? That has to be impossible. Did you restart your service after running this echo line? 

Restart your service by:
```
docker service update captain-captain --force
```

**Comment by microchel-git** [comment]
> 

When I run `echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json`

Terminal gives me this error `-bash: /captain/data/config-override.json: Permission denied`

**Comment by githubsaturn** [comment]
You said you ran it using sudo and it worked.

**Comment by microchel-git** [comment]
> You said you ran it using sudo and it worked.

I mean when I run it using sudo, I get same error as without sudo
` -bash: /captain/data/config-override.json: Permission denied`

**Comment by githubsaturn** [comment]
Run `sudo -s` first, then run it. Does it work?
