### ISSUE TITLE
Limit log file size in container/service

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1800]
I'm not 100% that this is my problem, but I have a suspicion that the logging that I'm generating within each of my caprover apps is gradually building up, to the point where disk space on my server (nearly) fills up.  i.e. the logging that you access via `docker service logs srv-captain--myapp`.

I'd like to explore the possibility of applying a limit to the amount of log data that is stored, and it seems that there is a [`--log-opt` option](https://stackoverflow.com/a/32091923/4070848).  Searching the caprover repo, I see only a reference [in the changelog](https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/CHANGELOG.md?plain=1#L314-L322) to changing this via the command line, but I can't see any way to do this via the caprover console itself, so that it's permanent?

**Comment by githubsaturn** [comment]
The changelog notes are way old. Essentially before that release, CapRover didn't have any max size on the logs. On that release, we added a maximum of 512mb size on the size of the logs. See here: 

https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/src/docker/DockerApi.ts#L754-L759


and

https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/src/utils/CaptainConstants.ts#L17-L23



You can confirm the max log applied to your services by running `docker service inspect --pretty srv-captain--yourapp` towards the end you can see something like this:

![image](https://github.com/caprover/caprover/assets/10582082/e9ec872f-58ab-4f24-8e96-5a9836eabc72)

**Comment by githubsaturn** [comment]
There is a possibility that your containers crash and they keep lingering as dead containers... but CapRover prunes the dead containers after any code updates:

https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/src/docker/DockerApi.ts#L1529-L1544

**Comment by drmrbrewer** [comment]
@githubsaturn I guess my question/suggestion is whether this max size can be customised (reduced) other than by running a command each time the service restarts?

**Comment by githubsaturn** [comment]
I see. Running the command one time should be enough. The only reference to `defaultMaxLogSize` that I can see is at service creation. So just run `docker service update...` and that should do it. Alternatively you can also use the service override option:

**Comment by drmrbrewer** [comment]
OK, so the Service Update Override needs to be configured in each app separately, and no way to do it globally (i.e. to apply a common Service Update Override to every app)?

And how much/little of the YAML is needed, if you just want to change `max-size` and leave the rest alone?  Is the following sufficient/complete?

```
TaskTemplate:
  LogDriver:
    Name: json-file
    Options:
      max-size: 128m
```

or JSON:

```
{
  "TaskTemplate": {
    "LogDriver": {
      "Name": "json-file",
      "Options": {
        "max-size": "128m"
      }
    }
  }
}
```

Will that replace all `TaskTemplate.LogDriver.Options` with what is specified, or merge them?  At present, it looks like `max-size` is the only `Option` set by default, but this may change in future.  I'd rather leave all `Options` alone except `max-size`.

**Comment by githubsaturn** [comment]
> OK, so the Service Update Override needs to be configured in each app separately, and no way to do it globally (i.e. to apply a common Service Update Override to every app)?


Correct. No way to do this globally for existing apps. For new apps, you can simply override the `defaultMaxLogSize` variable. [See here](https://caprover.com/docs/troubleshooting.html#customize-config-settings). 


> And how much/little of the YAML is needed, if you just want to change max-size and leave the rest alone? Is the following sufficient/complete?
TaskTemplate:
  LogDriver:
    Name: json-file
    Options:
      max-size: 128m

Yes. It merges. See here:
https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/src/docker/DockerApi.ts#L1503

**Comment by drmrbrewer** [comment]
What do you mean by a "new app" and an "existing app" in the context of `config-override.json`?  Will a new entry in `config-override.json` only take effect for any new app added to the CapRover apps list, or will it take effect when an existing app is (re)deployed, for example on a completely new server, for the first time (based on a backup of the CapRover config)?

**Comment by githubsaturn** [comment]
> What do you mean by a "new app" and an "existing app" in the context of config-override.json? Will a new entry in config-override.json only take effect for any new app added to the CapRover apps list, or will it take effect when an existing app is (re)deployed, for example on a completely new server, for the first time (based on a backup of the CapRover config)?

The variable `defaultMaxLogSize` in `config-override.json` is only used when the service is first being created. See [this function](https://github.com/caprover/caprover/blob/e92d48d56c09e2fb3bdb2be6f9e97e4f04650802/src/docker/DockerApi.ts#L692-L700) and usage of the variable). It's when you click on "create a new app" button.

**Comment by drmrbrewer** [comment]
And it's then stored in the `config-captain.json`, within the app's specific part of that?  i.e. stored and not configurable thereafter?  Except maybe by editing with `nano`....?

**Comment by githubsaturn** [comment]
> And it's then stored in the config-captain.json, within the app's specific part of that?

No. It's stored in docker swarm db. It's just a parameter that is being passed to the Docker Swarm when it first creates the service. No need to hang on to the value for future updates.

**Comment by drmrbrewer** [comment]
> stored in docker swarm db

OK so what about the case where I spin up and new server, restore my `captain-config.json`, install docker, caprover etc, and get everything up and running, and deploy all my apps again? ... which is what I do (automated) when I spin up a new server... since it's a completely fresh installation (albeit using a previous captain-config), and no pre-existing docker swarm db, so the `defaultMaxLogSize` in `config-override.json` will be taken into account then when these existing apps are deployed to the new server?

**Comment by githubsaturn** [comment]
Yes, the restoration process needs to "create" a new service. At that step the value is being read from the override file.

**Comment by drmrbrewer** [comment]
OK thanks.  Actually I'm not so sure that it's these log records that are consuming lots of disk space (over time), because the current max of `512m` isn't actually that big, when I start off with ~200GB of spare disk space on a fresh server.  Over the course of a couple months, that gradually falls to near nothing, and I can't yet figure out why... I did look into it once and thought I'd pin it down to docker logging, but it may not be the same logging as this.

**Comment by githubsaturn** [comment]
Try running `docker system df` or `docker system df --verbose` to see the data usage.

**Comment by drmrbrewer** [comment]
Several weeks after spinning up and running a new server instance, `docker system df --verbose` shows nothing particularly out of the ordinary, except maybe:

    5000c66927bd   caprover/netdata:v1.8.0      "/run.sh"     1     93.9GB    4 weeks ago     Up 30 minutes      captain-netdata-container

93.9GB seems rather excessive?

**Comment by githubsaturn** [comment]
yikes! yea that definitely looks way too big!!! I just looked at one of my instance that had been running for a week, and it's less than a gig... so something is going on with your netdata... not sure what though...

![image](https://github.com/caprover/caprover/assets/10582082/c1addfb8-9d51-4ed9-a697-26be1999624d)

**Comment by githubsaturn** [comment]
> around 35 services running, so maybe the NetData logs for these will multiply up? 

ah yea that could explain it.

**Comment by drmrbrewer** [comment]
Would it be a good idea to configure the NetData used by CapRover to limit the amount of disk space that is used?  Or make this an option on the Monitoring page?  Personally, I only want NetData to show me what is happening *now* (or maybe in the last hour or so), and I don't care about what happened 4 weeks ago.

Relevant info I can see about this is:

https://github.com/netdata/netdata/#scroll-how-much-retention-can-i-have
https://learn.netdata.cloud/docs/configuring/optimizing-metrics-database/change-how-long-netdata-stores-metrics

**Comment by githubsaturn** [comment]
retention is pretty small for the integrated netdata... You can zoom out and you'll see that it doesn't go past 1hr ago. Something else is going on here.

But yea if you found a way to limit the disk usage, please let me know and we'll get it done

**Comment by drmrbrewer** [comment]
I couldn't see any obvious way to limit disk usage.  Maybe it's just a bug because apparently [by default NetData should use no more than 1GB of disk space](https://learn.netdata.cloud/docs/configuring/how-to-optimize-the-netdata-agent-s-performance#disk-footprint-and-io).  

At least, that applies to the newer versions of NetData, and I appreciate that the current version of CapRover is using an older NetData image v1.8.0... though there is a [newer version](https://hub.docker.com/r/caprover/netdata/tags) 1.34.1 which is used by the [edge version](https://github.com/caprover/caprover/blob/0439be0c7f9e9c698adc5b313bea73d8c6862dbd/CHANGELOG.md?plain=1#L7C49-L7C95).

Perhaps/hopefully this high disk usage is just a bug which will not happen in a later version.

In the meantime, I'm assuming that I can free up the space by stopping NetData in the CapRover dashboard and restarting it?

**Comment by githubsaturn** [comment]
Yes.

**Comment by drmrbrewer** [comment]
I'm trying to script this now (i.e. to perform a regular check on space used by NetData, and take action if e.g. above 1GB).  

Is it enough to restart the container (with `docker restart captain-netdata-container`) to free up the space?

**Comment by githubsaturn** [comment]
Possibly. Try it out.

You also need to run [docker container prune](https://docs.docker.com/engine/reference/commandline/container_prune/).

**Comment by drmrbrewer** [comment]
I did try it out, but at present the size of the netdata container is stable at around 41.5 MB, so there is no change when I restart the container... 41.5 MB before and after.  Restarting the container in this way seems to retain the ID assigned to the container, which make me wonder whether it would really have the intended effect of clearing out used space, or whether it would need to be more drastic than that.

**Comment by githubsaturn** [comment]
Hmm... Yea if it doesn't, then you have to remove and re add it. Just make sure you maintain the same env vars, vols, and Network

**Comment by drmrbrewer** [comment]
OK, I've already got something script to stop and restart NetData using `caprover api` so I'll try that.

**Comment by githubsaturn** [comment]
Yea that's the same. It should also run docker container prune automatically for you.
