### ISSUE TITLE
Rename machine name in Netdata?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1802]
Hi, 

i am very happy about the integration of Netdata to caprover. but is it possible to change the name of the machine? since i am sending alerts to a messenger, the machine name would be great to change ( currently all my caprover instances have cryptic names like d2c087a10a93
![Bildschirmfoto vom 2023-07-12 10-24-24](https://github.com/caprover/caprover/assets/1011875/dbc85927-f453-4031-8f9e-e6cbf9322eaf)

Thanks a lot, and keep up the great work!

**Comment by githubsaturn** [comment]
Unfortunately I don't think that's possible using the built in NetData. You have to deploy your own netdata and map a directory to override the configs.
