### ISSUE TITLE
Providing docker ARG within a captain-definition file

### ISSUE THREAD

**Issue by jourdain** [caprover/caprover#1803]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**

So it is common to have docker file that rely on ARGs to fine-tune them. It would be nice if the `captain-definition` file could provide args. That way, when we want to update a SHA, download url or something specific to a deployment, it can be specified in that meta-file rather than updating the Dockerfile. 

**Describe the solution you'd like**

I would like to be able to do have a captain-definition file like below

```json
{
  "schemaVersion": 2,
  "dockerfilePath": ".deploy/Dockerfile"
  "dockerArgs": {
       "APP_SHA": "9abe328a60553089cd9dd381dd50332ae31babef"
   }
}
```

**Describe alternatives you've considered**

Right now, I need to modify my main Dockerfile. Which does not work if we want several captain files for various deployment/servers... 

**Additional context**

I'm enjoying everyday use of caprover so far! Great job...

**Comment by githubsaturn** [comment]
CapRover does support ARG values (using the env vars) - they are available at build time. See this:

https://caprover.com/docs/app-configuration.html#environment-variables


Specifically for your use case `APP_SHA` - there is a special env var `CAPROVER_GIT_COMMIT_SHA`

**Comment by githubsaturn** [comment]
Having ARGs in `captain-definition` defeats the purpose of ARGs. They are not supposed to be checked in. If you want to check in your ARGs, you can always have a `.env` file and load the fine in your Dockerfile. That way you should be able to update those variables without modifying the Dockerfile.

Something [like this](https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs) should work. Simply add these lines to your Dockerfile:
```
COPY .env ./
RUN export $(cat .env | xargs)
```

**Comment by githubsaturn** [comment]
Feel free to reopen if I misunderstood the requirements here.

**Comment by jourdain** [comment]
So let say I have 2 deployment (release, dev). My idea was to have a `captain-definition.release` and `captain-definition.dev` where they both point to the same docker file but in a git clone command of the docker, I want to pass which branch or sha should be fetched for a library (not my current repo). 
So `CAPROVER_GIT_COMMIT_SHA` won't work. 

Also the .env suggestion won't work.

Basically my thought was about having specific dependency version described within a given captain-definition file.

Also, I'm not looking for runtime options but rather build time options. If I'm not mistaken, the [environment-variables](https://caprover.com/docs/app-configuration.html#environment-variables) only capture the runtime stage.

**Comment by jourdain** [comment]
Maybe the [environment-variables](https://caprover.com/docs/app-configuration.html#environment-variables) could work but I won't have a self-contained docker is such -e is not provided at build time.

**Comment by githubsaturn** [comment]
> If I'm not mistaken, the [environment-variables](https://caprover.com/docs/app-configuration.html#environment-variables) only capture the runtime stage.

That's not entirely true. You can definitely use env vars in build time:

![image](https://github.com/caprover/caprover/assets/10582082/5bcb5663-4407-4efa-97a8-b24bf8fdd79e)


Have you tried this?

**Comment by jourdain** [comment]
I'll try that way but need to find a fallback way for default when the env is not provided.

**Comment by githubsaturn** [comment]
You can surely use env var fallback in your bash script that uses the env var: https://stackoverflow.com/a/2013589

**Comment by jourdain** [comment]
Thanks for the workaround! All good then.
