### ISSUE TITLE
I install chatwoot with cparover, but when I setup the widget the chat don´t work [Question]

### ISSUE THREAD

**Issue by 546451cc** [caprover/caprover#1805]
Hi there, I install ChatWoot with CapRover. All is fine but when I try to install the widget the code in my site don´t work. The code is in the footer and is fine, but seems chatwoot don´t work. Websocket support is active, ssl is enable, any idea?
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

**Comment by githubsaturn** [comment]
![image](https://github.com/caprover/caprover/assets/10582082/7c3f8037-a51c-4e93-b124-3784ddb33ea3)
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md#app-bugs

**Comment by 546451cc** [comment]
> Hi there, I install ChatWoot with CapRover. All is fine but when I try to install the widget the code in my site don´t work. The code is in the footer and is fine, but seems chatwoot don´t work. Websocket support is active, ssl is enable, any idea?

Yes, you are right. I get confused and open in the incorrect place, sorry.

**Comment by githubsaturn** [comment]
No problem! Hope you'll get it resolved!
