### ISSUE TITLE
MongoDB express - Server Status Turn on admin in config.js to view server stats!

### ISSUE THREAD

**Issue by microchel-git** [caprover/caprover#1812]
CapRover one click db
image: 0.54.0
When I sign in to see my mongo db page I see that:
<img width="1138" alt="Снимок экрана 2023-07-21 в 13 28 39" src="https://github.com/caprover/caprover/assets/85747237/a7f2bc29-5aab-4c5a-b3c2-a07df4c7529a">

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![image](https://github.com/caprover/caprover/assets/10582082/1d6d50a5-3f7c-4dc3-a3f0-e5704fb4cd83)

**Comment by githubsaturn** [comment]
In this case, please report in https://github.com/mongo-express/mongo-express
