### ISSUE TITLE
[Question] Run App with specific UID/GID

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1815]
Kindly state your question clearly:
Can a caprover app be setup to run under a specific user?

I'm specifically referring to the equivalent of setting `--user` in `docker run` or `user:` in docker-compose.

**Comment by githubsaturn** [comment]
Not in UI. But use docker CLI command;

```
docker service update --user .... srv-captain--yourapp
```

**Comment by Alfagun74** [comment]
is there a feature request to implement it in ui?

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md


> The goal is to make the common use-cases exposed via simple controls on UI while allowing further customizations to be done through hooks and scripts. If a new feature is doable via the existing features, or a basic tool, do not add it to CapRover. We do not want to bloat this application.

**Comment by Alfagun74** [comment]
It's no surprise that caprover hasn't received updates in two years...

Not to be rude or anything since I really adore this application, but I believe that statement hinders the continuous development of this platform, as it implies, "If you can resolve it using the CLI, we won't add it." Well, the truth is, almost everything can be handled through CLI. Setting the User is an extremely common use case.

I've sparked this discussion in https://github.com/caprover/caprover/discussions/1544 already and you should really consider implementing some sort of voting system instead of relying on your personal perception regarding the assumption of how many people need a feature.

**Comment by githubsaturn** [comment]
@Alfagun74 - when do you plan to submit a PR?

**Comment by githubsaturn** [comment]
FWIW, the voting system is place. The feature requests that receive the moat top votes will be prioritized.

**Comment by githubsaturn** [comment]
But if you have a better system in mind, let me know and submit the PR.
