### ISSUE TITLE
Port Mapping ignored when app exposed

### ISSUE THREAD

**Issue by JustinGuese** [caprover/caprover#1816]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

when setting a port mapping AND exposing the app the port mapping is ignored.
I would need this for internal routing, meaning I expose the Webapp via basic auth, but want other apps to connect to it using the internal node port routing, such that I do not need to add basic auth to every http call.

**Comment by JustinGuese** [comment]
I think it's related to https://github.com/caprover/caprover/issues/1817, because when I manually scale the deployment to 1 it works again

**Comment by githubsaturn** [comment]
You do not need port mapping for internal communications. All containers run on the same mesh layer network. 

For example, you can try this out by deploying a WordPress one click app. Once you do that, you will see that the MySQL database does not have any mapped ports, yet the WordPress app is able to connect to it.


Ports mapping is only needed when you want to expose the port to an external entity, such as your local machine.
