### ISSUE TITLE
[Question] Slow response from web application through CapRover

### ISSUE THREAD

**Issue by LWJerri** [caprover/caprover#1827]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: I have 2 identical servers, 1st managed by CapRover, 2nd managed by Caddy. Sometimes I see in my web apps a 500 error from CapRover when many users use my service, but the server works fine, all good. I install [bombardier](https://github.com/codesenberg/bombardier) and did some tests - run my service on both servers and saw no good results. Here are my command and result stats.

Server with CapRover:
```
ubuntu@production:~$ bombardier -c 100 -n 100000 https://pauperial.p.lwjerri.dev
Bombarding https://pauperial.p.lwjerri.dev:443 with 100000 request(s) using 100 connection(s)
 100000 / 100000 [======================================================================================================================] 100.00% 533/s 3m7s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       533.20     649.11    3558.73
  Latency      187.41ms   137.63ms      1.94s
  HTTP codes:
    1xx - 0, 2xx - 86640, 3xx - 0, 4xx - 0, 5xx - 13360
    others - 0
  Throughput:   583.02KB/s
```

CPU usage:
![image](https://github.com/caprover/caprover/assets/50290430/db052af1-5290-4392-b6c6-6d802cce3f4c)

Server with Caddy:
```
ubuntu@production:~$ bombardier -c 100 -n 100000 https://pauperial.d.lwjerri.dev
Bombarding https://pauperial.d.lwjerri.dev:443 with 100000 request(s) using 100 connection(s)
 100000 / 100000 [======================================================================================================================] 100.00% 2443/s 40sDone!
Statistics        Avg      Stdev        Max
  Reqs/sec      2460.84     846.45    9970.74
  Latency       40.71ms     5.87ms   212.20ms
  HTTP codes:
    1xx - 0, 2xx - 100000, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     2.00MB/s
```

CPU usage:
![image](https://github.com/caprover/caprover/assets/50290430/a4ee8b57-9ffc-4883-91b3-c999a7428c4a)

As you can see from the test results - CapRover performs very poorly compared to Caddy, but still the server load is about the same. Why is it so with CapRover? What else do I need to provide for a complete picture? Thanks.

**Comment by githubsaturn** [comment]
PS: usually for this sort of inconsistency and performance problem the right approach is to isolate the issues to find the problem.
Start with a simple static app. Then play with worker processes and connections and hopefully you'll find a good balance. 

Caddy is a modern webserver and I wouldn't be surprised if it's slightly more efficient than nginx, but the difference that you're seeing is indicative of some other issues. It's too big...
