### ISSUE TITLE
Can I have my already existing apache server be passed through caprover?

### ISSUE THREAD

**Issue by ismail1234j** [caprover/caprover#1828]
Sorry if I don't make sense, I am new to caprover and self hosting websites as a whole, I have been using caprover to manage my docker containers and host some minimal websites online with a domain.

Recently I have wanted to host a website accessible from my servers IP and the root of my domain, both of which are not currently the face of any websites.

I installed apache but the default page does not come up, rather caprover's "nothing here yet" page appears. I would like to see my apache page to show up.

**Comment by githubsaturn** [comment]
Short answer:
No you can't have two applications on the same port (80)

You can, however, run Apache on a different port and build a reverse proxy in CapRover to route the traffic there. But it's not beginner friendly and requires a good understanding of nginx.

**Comment by ismail1234j** [comment]
Oh thats a bummer. Thanks for your help. What would I use to "Build a reverse proxy"? I already have a minimal understanding of Docker if that helps.

**Comment by githubsaturn** [comment]
You have to edit nginx config to route traffic to a different downstream
