### ISSUE TITLE
Locked out from Dashboard Domain Change [Question]

### ISSUE THREAD

**Issue by SimbaNinja917** [caprover/caprover#1829]
Hello,
I have changed the domain A to another domain B of the caprover in the dashboard, and now I am unable to access it. 
Is it possible to reverse to the previous domain A using my terminal ? I've tried to edit the server_name from domain B to domain A in`/captain/generated/nginx/conf.d/captain-root.conf` but it reverses back to domain B.

**Comment by githubsaturn** [comment]
Did you change the root domain? CapRover runs a domain verification step before it allows you to enable, did you turn on `skipVerifyingDomains` ?


Anyways, you can always manually update the config file:

```
cp /captain/data/config-captain.json /captain/data/config-captain.backup

nano /captain/data/config-captain.json 

# edit customDomain to update your root domain
# set hasRootSsl and forceRootSsl to false
```
