### ISSUE TITLE
Enabling subdomain ssl not working for specific domain name

### ISSUE THREAD

**Issue by cbudtz** [caprover/caprover#1833]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I have an app that i deleted and recreated. now i can't enable ssl for that app name. I can choose any other name and activate ssl, but this name is 'stuck'. How do i trace the error? The 
POST to https://captain.4a4b.dk/api/v2/user/apps/appDefinitions/enablebasedomainssl just hangs for 30 secs then throws an 
nginx bad gateway

I guess its an nginx or certbot issue - how can i track this down?

Steps to reproduce the problem:
Create app. Delete it. Re-create. Try to Enable SSL. (Can't reproduce for new apps)

Linux ubuntu-2gb-nbg1-1 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UT            C 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:           3.8G        2.2G        268M         22M        1.3G        1.3G
Swap:          8.0G        2.4G        5.6G

**Comment by githubsaturn** [comment]
get the logs for this by running `docker service logs captain-captain` and see what you see in the logs. It's likely that certbot somehow hangs.

**Comment by githubsaturn** [comment]
Also, create another app, like `abc123` enable https, and delete the app.
Now recreate it and try to enable SSL again. Does it have the same problem?

**Comment by cbudtz** [comment]
> get the logs for this by running docker service logs captain-captain and see what you see in the logs. It's likely that certbot somehow hangs.

captain-captain.1.fhj3bjx6mz7v@ubuntu-2gb-nbg1-1    | August 13th 2023, 7:09:10.606 am    Verifying Captain owns domain: innocloud.4a4b.dk
captain-captain.1.fhj3bjx6mz7v@ubuntu-2gb-nbg1-1    | POST /api/v2/user/apps/appDefinitions/enablebasedomainssl - - ms - -


> Also, create another app, like `abc123` enable https, and delete the app.
> Now recreate it and try to enable SSL again. Does it have the same problem?

Works for all other subdomain names - its just innocloud thats 'stuck...

**Comment by githubsaturn** [comment]
It's because this domain points to a different address. 

innocloud.4a4b.dk points to 130.225.170.197
but anything-else.4a4b.dk points to 88.99.226.150

Assuming 88.99.226.150 is your server IP, you can see that the DNS domain is pointing to a wrong IP. 

![image](https://github.com/caprover/caprover/assets/10582082/0b382285-73fa-4903-9bf8-7a16daeffd4d)
![image](https://github.com/caprover/caprover/assets/10582082/da37878f-fdbc-4fbe-ace0-0422561e744c)

**Comment by cbudtz** [comment]
Ahh - seems that I was at fault with the DNS. Makes sense - but hard to track. Thanks for your help. As a quirky side effect I had to delete and recreate some of the other applications that refused to work afterwards. Have no Idea why...
