### ISSUE TITLE
[Question] How to handle > 1000 (websocket) connections in an app?

### ISSUE THREAD

**Issue by viktorvsk** [caprover/caprover#1834]
I have an app in caprover that handles (long-running) websocket connections. And when app gets around 1000 connections, connections start dropping. Whatever I've tried in adjusting kernel settings, service objects, nginx configs etc — nothing helps.

Its not an app-specific problem because if I run connection-emulator-script on the host machine directly on app container (bypassing nginx) — 2000 connections are created immediately. [Details on SO](https://stackoverflow.com/questions/76884636/nginx-in-docker-cant-handle-1000-websocket-connections)

**I understand this is not a Caprover issue**, but it seems to me it should be very important to understand for those who want to use Caprover in production and in case in requires changes to `captain-nginx` service, it could be documented additionally (or even something to be incorporated into UI at some point)

Also, I've searched through all the docs and issues and haven't found anything even remotely related so maybe its me missing something very obvious?  Or is it just it's not very noticeable for HTTP requests and not many people deal with web sockets?

P.S. I also checked with [websocket echo server](https://hub.docker.com/r/jmalloc/echo-server) instead of my app and got the same behavior

P.S.S. I believe, this issue should be easily reproducible:

1. Install Caprover as usual
2. Create `ws-echo` app like this one https://hub.docker.com/r/jmalloc/echo-server
3. Ensure it works: run `wscat -c ws://echo-server.ROOT_DOMAIN.com` and then prompt anything and get it back right away
4. Run scrip that simulates thousands of connections, like this one (Ruby):

```ruby
require 'faye/websocket'
require 'concurrent'
require 'json'

threads_per_process = 1000
websocket_url = "ws://echo-server.ROOT_DOMAIN"

def create_websocket_connection(url)
  EM.run do
    ws = Faye::WebSocket::Client.new(url)

    ws.on :open do
      puts "WebSocket connection opened"
      ws.send("Hello, WebSockets")
    end

    ws.on :message do |event|
      # puts "Received message: #{event.data}"
    end

    ws.on :close do |event|
      puts "WebSocket connection closed: code=#{event.code}, reason=#{event.reason}"
      EM.stop
    end
  end
end

threads_pool = Concurrent::ThreadPoolExecutor.new(max_threads: threads_per_process)

threads_per_process.times do
  fork do
    sleep(0.01) # introduce delay if needed, 10ms in this case
    create_websocket_connection(websocket_url)
  end
end

threads_pool.shutdown
threads_pool.wait_for_termination

```

5. Verify that in a minute or so you will have all connections disconnected

**Comment by maietta** [comment]
You might need to tweak the proxy_buffers and proxy_buffer_size settings in your Nginx configuration.

**Comment by viktorvsk** [comment]
> You might need to tweak the proxy_buffers and proxy_buffer_size settings in your Nginx configuration.

I've tried with `proxy_buffering off;` so I believe this is not the reason

**Comment by viktorvsk** [comment]
Sometimes it looks like some kind of a "ban" for too many requests (which I'm doing from a single IP). However, its a fresh caprover install, reproducible on 2 different providers and I believe default caprover templates don't have anything regarding limits and as far as I know there are not default limits in nginx itself

**Comment by maietta** [comment]
As far as I know, there aren't any limits imposed anywhere in Nginx or Caprover for websockets connections.

Do you have fail2ban or crowdsec installed on the host, or perhaps a web application firewall between your host and the visitors?

**Comment by viktorvsk** [comment]
No, fresh install, different hosting providers

**Comment by maietta** [comment]
> No, fresh install, different hosting providers

Okay. That's an interesting problem. What would happen if you scaled your app to more than one instance. Could the number of websocket connections be increased this way? There's some issues that might need to be addressed to ensure sticky sessions, but that's relatively trivial if you went this route.

**Comment by viktorvsk** [comment]
> Okay. That's an interesting problem. What would happen if you scaled your app to more than one instance? Could the number of websocket connections be increased this way? There's some issues that might need to be addressed to ensure sticky sessions, but that's relatively trivial if you went this route.

There will be no sense to use caprover in this way if I have to scale nginx load balancers. If I add another server to cluster and put my app on different machine - nothing changes. And using a server for only 500 connections is something I would like to avoid

**Comment by viktorvsk** [comment]
@maietta I've updated a question with details on how to easily reproduce it in case you are interested

**Comment by maietta** [comment]
You could join the Slack channel and post your question here. That should put more eyes on the problem. I don't think I will have the ability to help with this today.

You can find the Slack link at the top of CapRover.com page.

Because this not a CapRover specific issue, this issue is likely to get closed, but the Slack channel may offer a path to a solution if others join in on the conversation.

**Comment by viktorvsk** [comment]
sorry, that's my bad.
Never do performance testing from your local environment, NEVER. Always plan the capacity, use remote servers and when doubt pay attention to CLIENTS (who performs testing) and not SERVERS (who are the subjects of testing)

**Comment by conradfr** [comment]
Did you find anything to improve the situation? It seems I get the same problem with a Phoenix Channels app.

The thing is, it affects all apps and I start getting random errors 500.
