### ISSUE TITLE
Give users Real IP to the container

### ISSUE THREAD

**Issue by delasource** [caprover/caprover#1839]
I'm not 100% sure but pretty sure it's a setting with docker. But since it's default with caprover, i'd like to talk about it here.

Reproduce: 
1. Create an app and use this docker image: https://github.com/brndnmtthws/nginx-echo-headers (which basically just echoes all http request headers)
2. Open the app in the browser and see the "x-real-ip" as well as the "x-forwarded-for" header is `172.18.0.1` (which is the docker gateway)

This is bad, since the app should actually know the real ip of the user (for example apps like matomo or plausible are more or less useless without that).

This is related to the overlay network configuration, i think. Any ideas how this may be configured, so that the containers get the actual real ip?

**Comment by githubsaturn** [comment]
This was fixed a long time ago when when moved to host ports for nginx. I just tried the echo server and it seems to be working just fine:
http://test-echo.server.demo.caprover.com/

![image](https://github.com/caprover/caprover/assets/10582082/07457131-9098-4200-a24b-8f362b8a3e4f)

**Comment by githubsaturn** [comment]
Here is when the change was introduced: https://github.com/caprover/caprover/blob/master/CHANGELOG.md#v072---2018-05-16

**Comment by githubsaturn** [comment]
It is likely that you have a special networking condition where the request is passed through another layer before it makes it to your CapRover machine.

**Comment by delasource** [comment]
That may be true. How can i find that out? docker inspect docker_gwbridge ?

I installed the server half a year ago and did not (knowingly) have a specific network config

**Comment by githubsaturn** [comment]
You can verify this by simply running a docker service outside of CapRover using `docker service create --name test-nginx -p 8080:8080 brndnmtthws/nginx-echo-headers`

**Comment by delasource** [comment]
do i have to add the container to a network? the overlay network? because it is not reachable on port 8080 from the outside (ufw firewall allowed!)

**Comment by githubsaturn** [comment]
no, you don't need to do anything. Looks like you have a network issue on your VPS... Probably a cloudbase firewall that sits outside of ufw perhaps?
Anyways, this is running completely out of CapRover as it's just a plain Docker service.... Try stackoverflow for this type of problems. it's usually much more effective

**Comment by delasource** [comment]
i was able to narrow it down. in my country there is something called dual-stack lite, which is basically internet providers, giving access via ipv6 to users and not ipv4, since there are too few ipv4 adresses available.

So clients, that access the caprover server via ipv6 (yes my server does have an ipv6 address configured correctly) will appear to applications as "172.18.0.1"

**Comment by githubsaturn** [comment]
Good find!
