### ISSUE TITLE
could we add nixpacks as a deployment option?

### ISSUE THREAD

**Issue by chaycee** [caprover/caprover#1840]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by githubsaturn** [comment]
Please fill out info in the future: 
![image](https://github.com/caprover/caprover/assets/10582082/41dfb605-c001-480c-bf57-589bb137d7d5)

In this case, it is useful to explain why the current methods won't work for this usecase. Also, nixpacks are far less popular than other deployment options
