### ISSUE TITLE
[Deployment Issue] Build failed with a specific folder name

### ISSUE THREAD

**Issue by Jhereck** [caprover/caprover#1841]
Hi,

I'm using CapRover with a full stack (front Angular, back Spring Boot maven + Python api) et got a very strange pb.

All is configured with Github webhooks, and deployments start with captain-def-files when a push occurs on branchs, and all was working for months.

My pb is my backend is no more building correctly since the push of a commit yesterday (last good build was 3 days ago, errors "cannot find symbol" and "./mvnw clean install' returned a non-zero code: 1" since), despite the fact that they were no pb before.

The project is building correctly in local, and same in local Docker container from a dockerFile.

I tried all sort of stuff (convert CRLF EOF in LF cause i'm on Windows, update mvn etc : 1,5 days searching you can imagine. Full description available there : https://stackoverflow.com/questions/76922571/caprover-docker-deploy-error-cannot-find-symbol-and-mvnw-clean-install), and this morning i tried to copy my local folder in another, change the capitain-file accordingly and pushed it AND IT WORKED (original folder was called "backend", the new one "backend_" and it's a simple copy / paste with no modifications at all).

Do you have an idea what the pb can be ?

My "new" captain-def-file :

```
{
	"schemaVersion": 2,
	"dockerfileLines": [
		"FROM eclipse-temurin:17-jdk-jammy as builder",
		"WORKDIR /app",
		"COPY ./backend_/.mvn/ .mvn",
		"COPY ./backend_/mvnw ./backend_/pom.xml ./",
		"RUN chmod +x ./mvnw",
		"RUN ./mvnw dependency:go-offline",
		"COPY ./backend_/./src ./src",
		"RUN ./mvnw clean install -B -ntp -q",
		"FROM eclipse-temurin:17-jre-jammy",
		"WORKDIR /app",
		"EXPOSE 3001",
		"COPY --from=builder /app/target/*.jar /app/*.jar",
		"ENTRYPOINT [ \"java\", \"-Dspring.profiles.active=staging\", \"-jar\", \"/app/*.jar\" ]"
	]
}
```
Thanks !

**Comment by githubsaturn** [comment]
> last good build was 3 days ago, errors "cannot find symbol" and "./mvnw clean install' returned a non-zero code: 1" since

If you revert to that build, can you build successfully?

**Comment by Jhereck** [comment]
I tried to revert to last working build of course, and the error is unfortunatly present too.

**Comment by githubsaturn** [comment]
That should not be possible - unless some other config changed.

Make sure you use the right captain-definition file (in case you have a customized path for it)

Also, instead of using `dockerfileLines` simply use `dockerfilePath` - this will help you avoid any typos.
https://caprover.com/docs/captain-definition-file.html#use-dockerfile-in-captain-definition


If your local Docker can build successfully, your remote version will be able to build too.

**Comment by Jhereck** [comment]
Ok thanks for your response i finally found the pb : it was in my repo, i needed to delete the Backend repo localy, push to delete it on the remote, copy / paste localy and then push again to have a clean copy on the remote and tadam ! Pb solved ! :)

(pb a problem of file ending a the beginning).

Thanks for your time ! :)
