### ISSUE TITLE
Deleting Apps and Reinstalling Apps - Memory Issues

### ISSUE THREAD

**Issue by webclinic017** [caprover/caprover#1843]
I installed Caprover in ubuntu in a small vps, it installed well, ran well, until I saw the disk memory reaching the limit, as one app logs said no space to write. now I deleted other apps and tried reinstalling the apps but it wont allow saying name db exit etc

I rebooted and also checked the file size, it remained the same, even after all apps are deleted

Is it that even after deleting apps - the whole data/images arent deleted - even after rebooting

**Comment by githubsaturn** [comment]
@webclinic017 - have you tried the disk cleanup functionality on the settings tab?

**Comment by STOCKZE** [comment]
Apologies - it did fix after deleting from the disk cleanup -- but would be better if we had a single click complete delete or with a checkbox

**Comment by webclinic017** [comment]
Apologies - it did fix after deleting from the disk cleanup -- but would be better if we had a single click complete delete or with a checkbox

**Comment by githubsaturn** [comment]
It's already a feature request, but at the top of the list
https://github.com/caprover/caprover/issues/457
