### ISSUE TITLE
How can I customize CapRover homepage

### ISSUE THREAD

**Issue by cary-hu** [caprover/caprover#1844]
After deploy caprover to my server, the root domain will redirect me to caprover homepage:

In official demo, it's https://server.demo.caprover.com/
![image](https://github.com/caprover/caprover/assets/41052104/3c80bc61-bb56-4c6c-9b9b-0086c1c804e7)

And this URL is not under a valid SSL cert,
![image](https://github.com/caprover/caprover/assets/41052104/0a36dfc0-15b4-46c3-974a-9e46d73cca2e)

 how can i fix the SSL issue, and how can I update the home page?

**Comment by githubsaturn** [comment]
Root domain is only used for wild card entry and your system setup. You can technically create a new app and point the root domain itself to that app.

**Comment by githubsaturn** [comment]
SSL issue is expected because this domain is NOT connected to any app at the moment.
