### ISSUE TITLE
[Question] Running multiple servers, how to select where to install a new app 

### ISSUE THREAD

**Issue by NilsTessier** [caprover/caprover#1845]
in cluster mode , i have 2 worker , one with lots of ram and big processor and another with large storage amount.
i wan't to install the one click Minio app on the server that as a lot of storage. How can i do that ? 
or is there a way to "migrate" the app to the storage server after install ?

**Comment by githubsaturn** [comment]
Migration is definitely dependent on what app. But generally speaking if you don't need to keep the data you can change the node id at any point. 

If you want to specify what node to use, you shouldn't use the one click app. Alternative that you can use one click app, but then manually change the node id.
