### ISSUE TITLE
[Question] n8n version 1+ upgrade

### ISSUE THREAD

**Issue by ewallz** [caprover/caprover#1847]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Hi, i'm using the oneclick app to deploy the latest version of n8n (version 1.3.1) but having write permissions issue for the persistent volume. Since ver1+, they change the process to run as user 'node' instead of root. So now the issue for n8n version above 1+, the data cannot persist since all the writing done by node but the container run as root. Any idea on how to overcome this??

**Comment by maietta** [comment]
This doesn't sound like a CapRover specific issue, but rather it seems, as described an application specific issue.

If I'm understanding this right, the newer version of your app might be expecting not only different file permissions, but potentially a different path for files and your persistent storage path must be re-assigned to the correct new path in the container.

**Comment by githubsaturn** [comment]
+1 to what @maietta  said!

With regards to the permission issues, you can always find the actual path of the volume on the host by running `docker volume inspect <your-vol-name>` and get to the path and run `chmod` and `chown` to fit your needs.

Alternatively, you can reach out to n8n forum for the app specific questions.
