### ISSUE TITLE
[Deployment Issue] ECR docker registry authentication issue in deployment

### ISSUE THREAD

**Issue by codefalcon95** [caprover/caprover#1848]
Hi team,

Thank you very much for this great project. 

What is the problem?

We are currently working on our delivery pipeline to deploy our app to our Caprover setup. We are building our image on Github and pushing the Image to our private Aws ECR. 

We setup our Remote Docker registry on Caprover from the Cluster tab to our AWS ECR, which was added successfully, please find image attached

<img width="746" alt="image" src="https://github.com/caprover/caprover/assets/36840643/6bcf7c10-b634-4e4b-b397-00f0525c7a2b">

We were able to verify that we can pull this image on our local machines , but Caprover is unable to use the authenticated information from the Remote Docker registry when we running a deployment with the image , please find text below as well

```
Build started for genti-test
An explicit image name was provided (xxxxxxxxxxx.xxx.ecr.us-east-2.amazonaws.com/genti-testing:latest). Therefore, no build process is needed.
Pulling this image: xxxxxxxxxxxxx.xxxxx.ecr.us-east-2.amazonaws.com/genti-testing:latest This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 500) server error - Head "https://xxxxxxxxxxxx.xxxxx.ecr.us-east-2.amazonaws.com/v2/genti-testing/manifests/latest": no basic auth credentials
```

Steps to reproduce the problem:

1. Add Aws Ecr private registry 
2. Build an image and trigger a deployment using image name

**Comment by githubsaturn** [comment]
Looks like AWS password gets updated frequently. Not sure why they do this!... But here is a workaround to overcome that:
https://github.com/caprover/caprover/issues/1476
