### ISSUE TITLE
[Question] Add instructions for how to disable analytics

### ISSUE THREAD

**Issue by khromov** [caprover/caprover#1853]
In the changed terms and conditions there is mention of "passing an env variable CAPROVER_DISABLE_ANALYTICS=true to CapRover service"

But the CapRover service is not exposed in the admin panel, so presumably you need to go to some file on the server to modify it manually? Can step by step instructions be added for this? 

Also, there is no info about *what* data is collected. This is required in many jurisdictions, it's not enough to say that the data is not "private", each type of data need to be listed as well as the purpose for processing of each piece of data.

Ref:
https://github.com/caprover/caprover/commit/ea1b06a1a6c1d6d153348572bb274bb22cd31b77#diff-a5de87ba41b59b2126e322f27474babe4136f6dec9d8fbb669bfbbafa305c96aR24

**Comment by githubsaturn** [comment]
@khromov it's just a Docker command. Just add `-e CAPROVER_DISABLE_ANALYTICS=true` to the installation line or run `docker service update -e CAPROVER_DISABLE_ANALYTICS=true captain-captain`

> Also, there is no info about what data is collected. This is required in many jurisdictions

The entire data collection is open source. But I'll call out these in more details. Thanks for the info.

**Comment by githubsaturn** [comment]
@khromov  - I've added the info here:
https://github.com/caprover/caprover/commit/b0178e1f66abeb25d4086252d4e3052131911cbd

If there is anything missing, please feel free to leave a comment and I'll do my best to address that ASAP.
