### ISSUE TITLE
[Question] email address for pro subscription

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#1856]
I understand why Google login is used for authentication to get into the pro account page, but when entering details for the actual subscription I'd like to use a different email address... will this cause any problems or are these completely separate?

**Comment by githubsaturn** [comment]
It shouldn't. Please use a separate email and report if it causes any issues. Happy to refund if any issues arise.

**Comment by drmrbrewer** [comment]
Just tried to do this, and notice that it actually doesn't let you edit the email address in the subscription sign-up panel... it must be taken from the google login used for the main page and cannot be changed.

**Comment by githubsaturn** [comment]
The payment doesn't go through?

**Comment by drmrbrewer** [comment]
The email field is pre-filled but non editable.  I haven't yet got as far as actually trying to pay.

**Comment by drmrbrewer** [comment]
@githubsaturn never mind, I've just used the gmail address for the subscription, but maybe for future subscribers it would be nice to be able to specify a non-gmail address.  Congrats BTW, you deserve some payback for your work on this amazing project and the patient support you provide.
