### ISSUE TITLE
Error Malformatted SSH path

### ISSUE THREAD

**Issue by craines** [caprover/caprover#1863]
Deployment error after updating to version 1.11.0

After the update all my apps started giving the error:

```
------------------------- Tue Aug 29 2023 17:51:06 GMT+0000 (Coordinated Universal Time)
Build started for trade-miles-api
Build has failed!
----------------------
Deploy failed!
Error: Malformatted SSH path: gitlab.com/xxxxxx/xxxxxx/xxxxx.git
```

**Comment by githubsaturn** [comment]
AH thanks for the report! It's very likely due to this PR:
https://github.com/caprover/caprover/pull/1254

I'll fix ASAP.

**Comment by githubsaturn** [comment]
And this is why I don't like regex! :face_with_head_bandage: :face_with_spiral_eyes: 
So hard to understand and get them right!

Apologies for the error. It looks like the new regex fails to recognize the path with 3 parts, i.e. `username/repo/subrepo` 

I fixed this for now, feel free to [update to edge](https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version) to temporarily resolve the issue. I'll probably cut a hotfix for this depending on the extent of the issue.
