### ISSUE TITLE
[Feature] Add support for Fossil VCS

### ISSUE THREAD

**Issue by louis77** [caprover/caprover#1865]
The [Fossil VCS](https://fossil-scm.org) is becoming increasingly popular as a replacement to Git. VSCode also has an excellent extension to fully integrate Fossil into the Source Control management. 

I would like the CapRover CLI to add support to deploy Fossil-based repositories when using the `caprover deploy` command. Thanks to Fossil's Git-export capabilities, this could easily be implemented on top of the existing Git-based workflow.

This is how it could be done:

1. When `caprover deploy` is run, it checks if the current directory is a Git repository. 
2. If not, check if it is a Fossil-based working tree, i.e. by calling `fossil info`
3. If (2) applies, CapRover can call the `fossil git export` command, which creates a Git clone of the current Fossil working tree
4. From there, CapRover can go on and do the usual Git workflow (compressing the repo into a tar etc.). 
5. Since `fossil` always exports to a Git branch called `trunk`, Caprover could just use that and omit the usual branch prompt
6. The exported version of Git repo could stay, next time `caprover deploy` is run the Fossil export would be even faster

This way, nothing has to be changed on the server side. It would be purely an added feature of the CLI.

An alternative would be to write a shell script that essentially does exactly that:

1. Do a Fossil->Git export
2. Run `caprover deploy`

**Comment by khromov** [comment]
Would the most straightforward alternative perhaps be to use a CI tool like Jenkins or CircleCI to handle the Fossil-specific stuff and then run `caprover deploy` once you have a proper Git repo?
