### ISSUE TITLE
CapRover is not working after server restart

### ISSUE THREAD

**Issue by renatocaliari** [caprover/caprover#1866]
After restarting my VPS server on Hetzner running `sudo reboot`, CapRover stopped working. 
And I don't know how to start it again.

From what I saw, captain-nginx is not running. Please see below the details that I was able to list.

I don't have experience in maintaining and configuring servers. It's been an adventure trying to maintain CapRover and applications on the Hetzner VPS that I recently set up.

I would like help in figuring out the reason why it's not working anymore and what steps I can take to fix it.

##  `docker service ls`
![Screenshot 2023-08-30 09 10 32](https://github.com/caprover/caprover/assets/1719651/d9348a45-492a-440c-bb39-d8db1bce3b58)

## `docker service logs captain-nginx --since 5m --follow`
![Screenshot 2023-08-30 08 53 18](https://github.com/caprover/caprover/assets/1719651/9bb63745-04b0-4edd-ac05-0b2105fa3587)

**Comment by githubsaturn** [comment]
Did you edit any of the nginx configs recently? Try running this:
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by githubsaturn** [comment]
You must have made some changes in nginx config, that broke nginx... but it doesn't show up until to restart unfortunately... that's why running that command fixed the issue
