### ISSUE TITLE
Fresh Digital Ocean droplet doesn't work

### ISSUE THREAD

**Issue by joshfester** [caprover/caprover#1867]
## What is the problem?

I created a droplet using the CapRover marketplace app. After creating the server, there's a "Getting Started" link. When I click that link, it opens a sidebar with a "Quick Access to CapRover" button. Clicking that button takes me to http://my-ip:3000/ where I get ERR_CONNECTION_REFUSED. Seems like the port is blocked or something. I've tried it a few different times with the same result. I also tried using the "Create a droplet" button in the CapRover docs.

## If applicable, content of `captain-definition` file:

Not sure about this. This was my first attempt to try out CapRover

## Steps to reproduce the problem:

Create a droplet on Digital Ocean using the CapRover image/app from the marketplace.

## Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

```
Linux rails-caprover 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
              total        used        free      shared  buff/cache   available
Mem:          964Mi       211Mi       120Mi       1.0Mi       633Mi       606Mi
Swap:            0B          0B          0B
```

**Comment by JacobSamro** [comment]
Have you configured the firewall ?

```
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;
```

**Comment by joshfester** [comment]
@JacobSamro Yes, still same issue after that

**Comment by JacobSamro** [comment]
You can try these steps : https://caprover.com/docs/troubleshooting.html

**Comment by githubsaturn** [comment]
Run docker service ls

**Comment by joshfester** [comment]
@JacobSamro I tried the first step:

`docker service ps captain-captain --no-trunc`

and this was the output:

`Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.`

@githubsaturn I received that same output from `docker service ls`

**Comment by githubsaturn** [comment]
Somehow the installation has failed, try running this line:

https://caprover.com/docs/get-started.html#step-1-caprover-installation

**Comment by githubsaturn** [comment]
Probably a digital ocean image bug! I just resubmitted a new version that takes a few days to get approved. Once it's approved, it should work again just fine.
