### ISSUE TITLE
Caprover v1.10.1 memory leak

### ISSUE THREAD

**Issue by draded** [caprover/caprover#1869]
What is the problem?
I am running an Ubuntu 18.04 server with Caprover on it and Docker v20.10.12. Every 16-24h the Caprover container  caprover/caprover:1.10.1 has a memory leak and my server goes into OOM killer mode and kills dockerd along with all containers and processes. I am currently positive it is leaking because through using `docker inspect -f '{{.State.Pid}}' {CONTAINER_ID}` to get the PID, I used `grep VmPeak /proc/{PID}/status` to get its peak memory usage and it was ~11GB, while I have 8GB of memory on the server. During the spike of ~11GB my server starts swapping memory and the CPU and disk go into 100% usage until the OOM killer does away with dockerd.

If applicable, content of `captain-definition` file:
No

Steps to reproduce the problem:
Cannot help anyone reproduce it, I need help retrieving the logs first since I don't know how to get them at all. Once dockerd crashes, the files from the crashed containers are lost and only the new ones after the dockerd restart are available. So if you could give me some help there I would be glad to share any other info I have with you. If this is a duplicate report of something that is already fixed, feel free to close the issue, I am planning to upgrade to the newest version soon.

**Comment by githubsaturn** [comment]
@draded - thanks for the report. But two things make me thinking that it could be a different leak that is killing your server.

1)
I'm unsure if I can trust grep VmPeak with the PID from docker. I just tested this on my of my instances that has 2GB of RAM, and here is the results that I've got:
```bash
ID=`docker container ls --filter="name=captain-captain" --format="{{.ID}}"`
PID=`docker inspect -f '{{.State.Pid}}' $ID`
grep VmPeak /proc/$PID/status

>>>>>>>>> VmPeak:	21505784 kB
```

It reports 21gb of RAM!! This is practically impossible to achieve on a system with 2GB of RAM and only 10GB of storage (it could not be even a swap memory)


2)
1.10.1 Had been in production for almost 2 years... If there was any memory leak issues, it would have been reported by tens if not hundreds of users. 



So based on these, I am thinking there is something else on your machine that is eating up your memory. Definitely not ruling out the possibility of any memory leak in CapRover, but the evidence does not suggest that.

**Comment by draded** [comment]
Thank you, @githubsaturn, very much for the promptly response. 
Given what I read, I agree that my assessment was faulty and that I jumped to conclusions too quickly regarding this issue. I personally have been using in production for more than a year and never had problems before this one. I will continue to investigate this issue, and if nothing comes up in a few days that can pinpoint the issue to Caprover specifically, I will close the issue if that is OK with you. 

Nevertheless, thank you for actively working on this project and taking good care of it!

**Comment by githubsaturn** [comment]
Thanks! I'll close the issue but continue to monitor. Please comment here if anything comes up and we can reopen it.
