### ISSUE TITLE
multiple urls per port support

### ISSUE THREAD

**Issue by Geczy** [caprover/caprover#1870]
https://captain.server.demo.caprover.com/#/apps/details/demo-php

saw the demo but saw can only input one url and can't map it to a port

do i have to modify the nginx template myself to allow support for more ? 

my container uses multiple ports, how do i expose them each ? https://github.com/dotabod/backend/blob/master/docker-compose.yml#L35-L49 https://github.com/dotabod/backend/blob/master/services/nginx/default.conf#L47-L91

**Comment by githubsaturn** [comment]
One app is mapped to one port on CapRover. The workaround for apps with multiple ports needing to be exposed as HTTP ports is to use a one click app called `nginx reverse proxy`

For example you have two ports `5010 => events` and `5011 => hook`. Here is what you should do:
- Set up your app and set http port to 5010
- Your app will only be used for the "events" endpoint
- Click on one click apps, and choose `nginx reverse proxy`
- For upstream, use `http://srv-captain--yourmainapp:5011`
- Now this new app can be used for hooks.

No need for custom nginx templating.
