### ISSUE TITLE
Caprover v1.11.0 Can't pass Gitlab creds

### ISSUE THREAD

**Issue by baryman** [caprover/caprover#1871]
What is the problem?
Can't pass Gitlab creds to "Deploy from Github/Bitbucket/Gitlab"

If applicable, content of `captain-definition` file:
No

Steps to reproduce the problem:

1. Go to your app
2. Then go to "Deployment" tab
3. Pass "Repository", "Branch", "Username" , "Password" (try pass SSH instead username-password) and click "Save & Update"
4. Show alert with content "Something bad happend"

Output of the following command on your server:
```
$  docker service logs captain-captain --since 5m
```
show me error
```
 TypeError: Cannot read properties of undefined (reading 'getAppPushWebhookToken')
captain-captain.1.l2i3vi9bvk7r@baryman    | TypeError: Cannot read properties of undefined (reading 'getAppPushWebhookToken')
captain-captain.1.l2i3vi9bvk7r@baryman    |     at /usr/src/app/built/datastore/AppsDataStore.js:458:22
captain-captain.1.l2i3vi9bvk7r@baryman    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
captain-captain.1.l2i3vi9bvk7r@baryman    | POST /api/v2/user/apps/appDefinitions/update 500 0.972 ms - 21
```

**Comment by githubsaturn** [comment]
Weird! Previously there was a report of this that went away on its own. 
https://github.com/caprover/caprover/issues/1822

Can you try rebooting your instance?

**Comment by baryman** [comment]
@githubsaturn I reboot my VM and this solved my problem. Thank you!
How can I reboot instance without reboot my VM?

**Comment by githubsaturn** [comment]
You can simply run `docker service update captain-captain --force`
