### ISSUE TITLE
[BUG]: Typeerror in `'getAppPushWebhookToken'`

### ISSUE THREAD

**Issue by koolamusic** [caprover/caprover#1877]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

When trying to setup GIT on the app dashboard, I get a 500 error, however looking at the caprover logs, this is the error trace
```
TypeError: Cannot read properties of undefined (reading 'getAppPushWebhookToken')
TypeError: Cannot read properties of undefined (reading 'getAppPushWebhookToken')
    at /usr/src/app/built/datastore/AppsDataStore.js:458:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If applicable, content of `captain-definition` file:
N/A

Steps to reproduce the problem:
1. Create an app
2. Deploy demo app
3. Setup GIT in deployment section

You can

Output of the following command on your server:
Linux ip-xxxx-xxxx-xxxx.2.internal 5.15.43-20.123.amzn2022.x86_64 #1 SMP Thu May 26 17:03:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
uname -a && lsb_release -a && free -h
```

**Comment by githubsaturn** [comment]
It's already fixed, we'll release a hotfix soon!
https://github.com/caprover/caprover/commit/cb489b26637c6e3fab762eebf3b613d7e89a140a
