### ISSUE TITLE
How to reset local users?

### ISSUE THREAD

**Issue by aychernov** [caprover/caprover#1879]
How to reset or delete all users and re-binding ip and DNS record for serversetup?
<img width="776" alt="Снимок экрана 2023-09-15 в 11 04 14" src="https://github.com/caprover/caprover/assets/67840786/85de0e14-a228-4546-ae43-66f39b390c35">

**Comment by githubsaturn** [comment]
You can run `caprover logout` on your local machine.

If you want to purge and delete the CapRover installation on server, please follow the guide here:
https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain
