### ISSUE TITLE
[Question] Self-signed certificate to be accessible via HTTPS

### ISSUE THREAD

**Issue by MYerouPaleBlue** [caprover/caprover#1880]
Hello,

First of all, great work with CapRover!

The LetsEncrypt integration is excellent when running CapRover a publicly accessible network. But when running it in an intranet it's impossible to use. Can CapRover (and the apps hosted on CapRover) use a self-signed certificate to access them via HTTPS? I tried to modify the Nginx config to do that without any success.

Once again, thank you for your work.

**Comment by githubsaturn** [comment]
> Can CapRover (and the apps hosted on CapRover) use a self-signed certificate to access them via HTTPS? 

It's definitely doable, but... you're on your own. There is to built in support for uploading certificates and managing them. 

But if you're comfortable with nginx configuration and making your own edits, you can definitely do this:
https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by MYerouPaleBlue** [comment]
Quick thank you for the fast response! I will give it a try; I missed that part in the documentation.
