### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by aychernov** [caprover/caprover#1884]
serversetup works fine, then
https://captain.cap.domain.ru - didnt load.
**BUT** https:// [anything] .cap.domain.ru **LOAD**
I`m miss undertanding why like that
Can anyone help with this? domain.ru and my IP works fine and load blue blank page from CapRover

What i need check?

**Comment by githubsaturn** [comment]
> https://captain.cap.domain.ru/ - didnt load.


You have to be more specific. Does the connection fail? Or the SSL cert? or neight?

Run this and copy the exact output here.
```
curl -v https://captain.cap.domain.ru
```

**Comment by aychernov** [comment]
> Run this and copy the exact output here.
I`m get this yesterday: 
<img width="788" alt="Снимок экрана 2023-09-16 в 20 06 00" src="https://github.com/caprover/caprover/assets/67840786/c92d7a87-9573-418c-a328-733c04d58dca">
So strange..(

But with curl: `
curl -v https://captain.cap.qwerasdf.ru
* Could not resolve host: captain.cap.qwerasdf.ru
* Closing connection 0
curl: (6) Could not resolve host: captain.cap.qwerasdf.ru
`
My server dns config: 
<img width="762" alt="Снимок экрана 2023-09-17 в 13 15 23" src="https://github.com/caprover/caprover/assets/67840786/0ddae8d1-c3bf-44a0-b31f-560240c783cf">

curl -v IP work fine

A few days ago I successfully used capRover, but decided to do everything from scratch again

**Comment by maietta** [comment]
For whatever it's worth, it seems that many well-known DNS providers are no longer able to, or are silently no longer resolving dns for the .ru gTLD.

You may need to use a different and neutral, name server provider for your domain.

This may be a combination of issues, but I think mainly politically rooted, where dns providers and name sever providers vendors decide to block Russian domains and services.

I don't know what's keeping Russians from using other gTLDs...

There are many examples of public statements by vendors signaling no longer supporting .ru domains.

**Comment by aychernov** [comment]
> There are many examples of public statements by vendors signaling no longer supporting .ru domains.
I`m tried another DNS provider and yep, it`s look fine. 
BUT i`m cannot load Sample One Click App => Infinite loader((

**Comment by githubsaturn** [comment]
One click app is hosted on github. It's quite possible that Github doesn't allow incoming request from your VPS (which I assume is hosted in Russia).

**Comment by aychernov** [comment]
> One click app is hosted on github. It's quite possible that Github doesn't allow incoming request from your VPS (which I assume is hosted in Russia).

Yep(
Okay i`ll try to change domain from another country. Thanks a lot! And thanks for this application =)

**Comment by githubsaturn** [comment]
Domain change won't actually help. You'll have to change your VPS. The one click app list is fetched from github by your VPS. So if the IP address of your VPS is in Russia, it's likely that github is blocking it.
