### ISSUE TITLE
Caprover restarted and now my postgresql DB  is not working.

### ISSUE THREAD

**Issue by contentsr** [caprover/caprover#1885]
App logs:-

PostgreSQL Database directory appears to contain a database; Skipping initialization
FATAL: database files are incompatible with server
 DETAIL: The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).

**Comment by maietta** [comment]
Firstly, back up your data volume! Don't say I didn't warn ya...

You can downgrade the docker image used to be the one that is known to work with that database. You can do so using the UI, under the deployment tab for your app. You'll want to find the docker image from docker up and reference it.

It almost sounds like your app wasn't tagged to a specific version when deployed, but instead, used "latest". This is bad. In production, deployed apps should always be tagged to the specific images.

**Comment by contentsr** [comment]
Can you guide me, please? How to back up and downgrade the docker image? Can I destroy the current image and use a fresh docker image with a specific version of Postgres and then use the previous backup to restore data?

**Comment by githubsaturn** [comment]
Simply go to deployment tab > deploy using ` Method 6: Deploy via ImageName` > use this image: `postgres:15`

**Comment by contentsr** [comment]
> Simply go to deployment tab > deploy using ` Method 6: Deploy via ImageName` > use this image: `postgres:15` and hit deploy.

Thank you andd how to back up data volumn?

**Comment by githubsaturn** [comment]
https://caprover.com/docs/backup-and-restore.html#what-is-restored


![image](https://github.com/caprover/caprover/assets/10582082/6ac0c2a2-2731-4303-9122-84e734e1d1e7)
