### ISSUE TITLE
Nginx custom config is deleted on caprover update

### ISSUE THREAD

**Issue by frederikhors** [caprover/caprover#1888]
I updated from `v1.11.0` to `v1.11.1` and my [custom nginx configuration](https://github.com/caprover/caprover/issues/1694#issuecomment-1465303530) was completely deleted and nginx was not working.

I think the update should consider, respect or if not valid anymore warn user of incompatible custom config.

**Comment by githubsaturn** [comment]
The update should NOT change your nginx configuration at all. I'm not sure what caused that config to get purged, but it's not something that the update did (unless there is some weird bug that I do not see).

You can look at the hotfix for yourself. There is absolutely nothing in the update that would clear the custom nginx config:

https://github.com/caprover/caprover/pull/1886/files

**Comment by githubsaturn** [comment]
Are you sure that in between you didn't take any other actions?

If the entire custom nginx config was deleted, the only two ways are:
- it was manually cleaned and saved at some point
- or this script was ran on the server: https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui

**Comment by frederikhors** [comment]
I don't think it was the single 1.11.1 hotfix but rather the update process perhaps.

No script launched. Only the update directly from the dashboard. After 60 seconds I saw that docker was continuously closing and relaunching nginx.

**Comment by githubsaturn** [comment]
> update process perhaps

Update process is just changing the image from `caprover/caprover:oldversion` to `caprover/caprover:newversion`


Closing and relaunching nginx is expected, but the custom configs are stored in a config file in `/captain/data/` directory and it should not be impacted by the update.

My guess is that a disk failure coincided with the update process, and it was the disk failure that caused the config to get purged.

**Comment by githubsaturn** [comment]
To confirm, let's try to reproduce:
- Manually roll back to 1.11.0  by running `docker service update captain-captain --image caprover/caprover:1.11.0`
- Set up your custom config and make sure it works
- Just to confirm, manually restart CapRover by `docker service update captain-captain --force`
- Confirm that the configs are still there
- Now go in the settings and update your CapRover version
- Wait until the update is done. 
- Check the custom nginx config.

**Comment by frederikhors** [comment]
I cannot try right now but I will.

**Comment by githubsaturn** [comment]
I'll try it out now.

**Comment by frederikhors** [comment]
I had this config you suggested before the update: https://github.com/caprover/caprover/issues/1694#issuecomment-1465303530.

**Comment by githubsaturn** [comment]
Just tried it out, and yes, confirmed, it worked as expected. Nothing was removed. I'll close this issue for now, but if you were able to reproduce it on your side, please comment and we'll investigate why it is happening on your instance.

**Comment by frederikhors** [comment]
Ok.
