### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by rklos** [caprover/caprover#1889]
**Is your feature request related to a problem? Please describe.**
Since version 1.11.0 we have an option to add tags to services. The problem is, that we cannot sort or search by those tags. This will improve user experience when there are dozens of services on the list.

**Describe the solution you'd like**
We need an option to search by tags alongside name.
![CleanShot 2023-09-17 at 14 12 14@2x](https://github.com/caprover/caprover/assets/34719093/9bcd757e-c045-4b63-8181-1ff42d8f9c3c)

**Comment by githubsaturn** [comment]
You certainly can search by tags! Just click on the tag! 
Or type `tag:changedetector` in the search bar


![image](https://github.com/caprover/caprover/assets/10582082/c32e2813-813c-4844-be42-7e307c224c6f)

**Comment by githubsaturn** [comment]
Feel free to comment / reopen if this doesn't work.
