### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by JuanM2020** [caprover/caprover#1896]
---

What is the problem?

Generated rsa secret and public key. clicked force build and getting the following error. something wrong with libcrypto?
Add the public key to GitHub in the repo Deploy keys and tried SSH keys too. This is for a private repo.

Ubuntu 22.04

> Fri Sep 22 2023 19:46:50 GMT+0000 (Coordinated Universal Time)
> Build started for xxxxx-xxxx-xxxxx
> Build has failed!
> Deploy failed!
> Error: Cloning into '/captain/temp/image_raw/xxxxx-xxxx-xxxxx/10/source_files'...
> Load key "/captain/temp/xxxxx-xxxx-xxxxx": error in libcrypto
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by githubsaturn** [comment]
@JuanM2020 

A common issue is typo, or similar human mistakes. Try to manually run `git clone` with the key that you generated to see if it works.


For example, there MUST be an empty line at the end of the SSH key
https://github.com/caprover/caprover/issues/1265#issuecomment-973651341

**Comment by githubsaturn** [comment]
Feel free to reopen if the issue is not fixed.

**Comment by JuanM2020** [comment]
@githubsaturn That was the issue! I would definitely recommended adding a check that automatically adds it or noting it in the documentation as I saw no mention of the requirement previously.

**Comment by githubsaturn** [comment]
Already done! 
https://github.com/caprover/caprover/commit/2915f70081948e144f3ddcd85f70735f52771ed0

**Comment by FiretronP75** [comment]
@githubsaturn I just had this issue. Adding an empty line fixed it. Is that commit in the stable release? If it is, it does not seem to be working. What release is it in?

**Comment by githubsaturn** [comment]
Not on stable version yet:
https://github.com/caprover/caprover/blob/master/CHANGELOG.md#next-version---available-as-edge

We don't have enough additional features to cut a new release, but once we do, we'll cut a new release
