### ISSUE TITLE
Change port 3000?

### ISSUE THREAD

**Issue by jon-bit** [caprover/caprover#1898]
Please clearly state your question:
How do I change the port from 3000 to something else? I looked a lot on the internet but none of the things I found are working. I don't want to delete cap rover (unless the containers will be here after remaking the image) but if I don't  have the images I already created I would not be able to do it because I have already put in to much time and energy to do it. Does anyone know if I could or how I would achieve this?

**Comment by githubsaturn** [comment]
Short answer: you can't.

Why do you need to change this port though? It's a temporary port that is used for the initial set up. Once the domain name is configured, you won't even use port 3000. Only ports used after the set up is completed are 80/443

**Comment by jon-bit** [comment]
Their is a app I want to run on port 3000 but to run it in a container I would need port 3000. Is this just not a possibility?

**Comment by githubsaturn** [comment]
I see. Yes, you can do that. Not for the initial set up like I said. But once you've set up CapRover so that it only uses ports 80 and 443, you can simply run the following command to free up port 3000. And you can use port 3000 for other use cases:

```
docker service update --publish-rm 3000 captain-captain
```

**Comment by jon-bit** [comment]
OK but after that How do I get to the GUI interface?

**Comment by githubsaturn** [comment]
Using `http://captain.rootdomain.com` 

After running `serversetup` command explained here: https://caprover.com/docs/get-started.html#step-3-install-caprover-cli

**Comment by jon-bit** [comment]
And it will not remove my containers I have already made their?

**Comment by githubsaturn** [comment]
No.

**Comment by jon-bit** [comment]
OK case close. THANKS!

**Comment by skiv71** [comment]
I did the docker service update --publish-rm 3000 captain-captain and rebooted but 3000 is still being used, so I can't push...

CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                    PORTS                                                                      NAMES
089b5674fe7f   caprover/certbot-sleeping:v1.6.0   "/bin/sh -c 'sleep 9…"   31 seconds ago   Up 26 seconds             80/tcp, 443/tcp                                                            captain-certbot.1.x0gzebvt24x9croatzhfnh04u
54a3fc191e43   nginx:1.24                         "/docker-entrypoint.…"   44 seconds ago   Up 43 seconds             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   captain-nginx.1.zhpjczehyvu7b4gouhvsb3x2c
c2584a42ba9b   caprover/caprover:1.11.1           "docker-entrypoint.s…"   55 seconds ago   Up 51 seconds             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                  captain-captain.1.s5ia7g3iqnturmr3e2n3jq5kh
31b934b2fa32   img-captain-ipfs:1                 "/bin/sh /data/ipfs-…"   55 seconds ago   Up 50 seconds (healthy)   4001/tcp, 5001/tcp, 8080-8081/tcp, 4001/udp                                srv-captain--ipfs.1.q2fkcs07kenwefe3pde4xaniu
0074d126265a   img-captain-gateway:0              "/docker-entrypoint.…"   55 seconds ago   Up 51 seconds             80/tcp                                                                     srv-captain--gateway.1.1qqy574d0dr64tsemwkislqft

**Comment by githubsaturn** [comment]
@skiv71 - what do you see when you run this:
```
docker service update --publish-rm 3000 captain-captain
docker service inspect captain-captain--pretty
```

**Comment by skiv71** [comment]
@githubsaturn 

I get this following output: -

ID:             yq2df0qvlxcjcwa6a2e73mj29
Name:           captain-captain
Service Mode:   Replicated
 Replicas:      1
Placement:
 Constraints:   [node.id == nhjyg3lnrmlzmslh0phpfnufj]
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         caprover/caprover:1.11.1
 Env:           IS_CAPTAIN_INSTANCE=1 
Mounts:
 Target:        /captain
  Source:       /captain
  ReadOnly:     false
  Type:         bind
 Target:        /var/run/docker.sock
  Source:       /var/run/docker.sock
  ReadOnly:     false
  Type:         bind
Secrets:
 Target:        captain-salt
  Source:       captain-salt
Log Driver:
 Name:          json-file
 LogOpts:
  max-size:       512m

Resources:
Networks: captain-overlay-network 
Endpoint Mode:  vip
Ports:
 PublishedPort = 3000
  Protocol = tcp
  TargetPort = 3000
  PublishMode = host

**Comment by skiv71** [comment]
Just did some more debugging, listed services: -

oot@production:~# docker service ls
ID             NAME                   MODE         REPLICAS   IMAGE                              PORTS
yq2df0qvlxcj   captain-captain        replicated   1/1        caprover/caprover:1.11.1           
wzb6kce3m6xc   captain-certbot        replicated   1/1        caprover/certbot-sleeping:v1.6.0   
o4d6dby99zd5   captain-nginx          replicated   1/1        nginx:1.24                         
vkrz0b363slc   srv-captain--gateway   replicated   1/1        img-captain-gateway:0              
ubt12iacb6dy   srv-captain--ipfs      replicated   1/1        img-captain-ipfs:1                 *:4001->4001/tcp, *:5001->5001/tcp, *:4001->4001/udp, *:5001->5001/udp
root@production:~#

**Comment by skiv71** [comment]
Also tried a remote curl to captain.<host>.<domain>:3000 which redirects to https://captain.<host>.<domain>

So, is that the nginx?

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/issues/1898#issuecomment-1846512111


What's the output after the first command?

**Comment by skiv71** [comment]
captain-captain
overall progress: 0 out of 1 tasks
1/1:
overall progress: 1 out of 1 tasks
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 5 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 4 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 3 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 2 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Waiting 1 seconds to verify that tasks are stable...
verify: Service converged

**Comment by githubsaturn** [comment]
You have a Docker installation problem. After running `docker service update --publish-rm 3000 captain-captain` the port should be removed. See below for the example:


```
➜  ~ docker service update --publish-rm 3000 captain-captain
captain-captain
overall progress: 0 out of 1 tasks 
1/1: ready     [======================================>            ] overall progress: 1 out of 1 tasks 
1/1: running   
verify: Service converged 
➜  ~ docker service inspect captain-captain --pretty

ID:		h11voun39dvzonoq3l0ujsb7x
Name:		captain-captain
Labels:
 registry-added
Service Mode:	Replicated
 Replicas:	1
UpdateStatus:
 State:		completed
 Started:	32 seconds ago
 Completed:	12 seconds ago
 Message:	update completed
Placement:
 Constraints:	[node.id == pp749r4hlvfo69dcma0qzirev]
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		caprover/caprover:latest@sha256:905815f252fda652c99739214361ab1501b525f3063fa68b28bb19767a8b0247
 Env:		DEMO_MODE_ADMIN_IP=99.152.115.107 IS_CAPTAIN_INSTANCE=1 IS_DEMO_MODE=true 
Mounts:
 Target:	/captain
  Source:	/captain
  ReadOnly:	false
  Type:		bind
 Target:	/var/run/docker.sock
  Source:	/var/run/docker.sock
  ReadOnly:	false
  Type:		bind
Secrets:
 Target:	captain-salt
  Source:	captain-salt
Log Driver:
 Name:		json-file
 LogOpts:
  max-size:       512m

Resources:
Networks: captain-overlay-network 
Endpoint Mode:	vip


```

**Comment by githubsaturn** [comment]
You have a Docker installation problem. After running `docker service update --publish-rm 3000 captain-captain` the port should be removed. See below for the example:


```
➜  ~ docker service update --publish-rm 3000 captain-captain
captain-captain
overall progress: 0 out of 1 tasks 
1/1: ready     [======================================>            ] overall progress: 1 out of 1 tasks 
1/1: running   
verify: Service converged 
➜  ~ docker service inspect captain-captain --pretty

ID:		h11voun39dvzonoq3l0ujsb7x
Name:		captain-captain
Labels:
 registry-added
Service Mode:	Replicated
 Replicas:	1
UpdateStatus:
 State:		completed
 Started:	32 seconds ago
 Completed:	12 seconds ago
 Message:	update completed
Placement:
 Constraints:	[node.id == pp749r4hlvfo69dcma0qzirev]
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		caprover/caprover:latest@sha256:905815f252fda652c99739214361ab1501b525f3063fa68b28bb19767a8b0247
 Env:		DEMO_MODE_ADMIN_IP=199.102.118.177 IS_CAPTAIN_INSTANCE=1 IS_DEMO_MODE=true 
Mounts:
 Target:	/captain
  Source:	/captain
  ReadOnly:	false
  Type:		bind
 Target:	/var/run/docker.sock
  Source:	/var/run/docker.sock
  ReadOnly:	false
  Type:		bind
Secrets:
 Target:	captain-salt
  Source:	captain-salt
Log Driver:
 Name:		json-file
 LogOpts:
  max-size:       512m

Resources:
Networks: captain-overlay-network 
Endpoint Mode:	vip


```

**Comment by skiv71** [comment]
I've just created a new VM (Ubuntu 22.04 LTS), installed docker, then caprover, did setup, console all working... and ran the same commands... But 3000 is still up and showing in the service inspect.

**Comment by githubsaturn** [comment]
@skiv71 - this is really not even CapRover at this point, it's just pure Docker. 

Running `--publish-rm` really should remove the service's port. It's fully outside of CapRover. I recommend reaching out to [Docker's github page](https://github.com/moby/moby). They may be able to help what's going on here. From what I see, everything should just work fine.

**Comment by skiv71** [comment]
I was wondering this... Thanks for the help

**Comment by skiv71** [comment]
Hi,

I've created an issue on moby https://github.com/moby/moby/issues/46921... They made a comment that the service containers are using host ports?

Basically, there are no ports to remove?

**Comment by githubsaturn** [comment]
oh I see! It's not that there are no ports to be removed. It's because the port is `host` mode. They are saying that if you run this command it should work:
```bash
docker service update --publish-rm mode=host,target=3000 captain-captain
```
