### ISSUE TITLE
Error: Port seems to be closed: 80

### ISSUE THREAD

**Issue by lcepaper** [caprover/caprover#1899]
Please forgive me for seeking help with some minor issues. I'm following the CapRover tutorial documentation, and I've been encountering an error when trying to install CapRover using Docker. The error message is consistently "Error: Port seems to be closed: 80." I've installed Docker version 19.03.15 on my Ubuntu 20.04 system, and when I run the command docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover, I receive this error. I've double-checked that my firewall is disabled, and port 80 is not in use. I've also attempted to solve the problem by using the command echo "{\"skipVerifyingDomains\":\"true\"}" > /captain/data/config-override.json, but it hasn't had any effect. I'm a novice and not very experienced with these tools, so I would appreciate any assistance in analyzing the root cause of this issue. Thank you for your understanding.

**Comment by githubsaturn** [comment]
This errors means that CapRover can't connect to port 80. Makes sure the port is indeed open on firewall. If you're sure about that, you can just bypass it via passings `-e MAIN_NODE_IP=127.0.0.1`

**Comment by githubsaturn** [comment]
Does this fix the issue?

**Comment by buglinjo** [comment]
Did not fix it for me. Installing cap rover on macOS using the script:
`docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -v /Users/USERNAME/.captain:/captain caprover/caprover`

Output:
```
Captain Starting ...
Overriding skipVerifyingDomains from /captain/data/config-override.json
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
     
 
 
 
 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 33671 MB
Pulling: nginx:1.24
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v1.6.0
October 2nd 2023, 2:46:06.953 am    Fresh installation!
October 2nd 2023, 2:46:06.955 am    Starting swarm at 127.0.0.1:2377
Swarm started: tt5g6hnorjarah8ci4spn39jl
*** CapRover is initializing ***
Please wait at least 60 seconds before trying to access CapRover.
```

Nothing happens afterwards. The container is exited.

**Comment by githubsaturn** [comment]
@buglinjo - It's expected for the installer container to exit.
Can you run `docker service ls` and paste the results here?

**Comment by paluigi** [comment]
@lcepaper where did you try to install Caprover?
On some cloud provider (for instance, Oracle Cloud) you need to open the necessary ports also on the networking configuration, by default most inbound ports are closed.

**Comment by buglinjo** [comment]
@githubsaturn sorry for the delayed response. Here's output:
![image](https://github.com/caprover/caprover/assets/1254208/413be7d4-37d0-4052-8ecf-4490b7c919fd)

No container is running though.
![image](https://github.com/caprover/caprover/assets/1254208/f804cd3e-e1d2-4789-b42b-70b2acbc007e)

**Comment by githubsaturn** [comment]
What you run initially is the caprover installer. The installer does the following:
- Ensures the prerequisites are satisfied (ports, versions etc)
- Sets up Swarm
- Initializes the `captain-captain` service

By changing the installer mapper, you can't change the mapping of the actual service. You cannot / should not change the host path as other containers look in the exact same path.

**Comment by ramirorodriguez-arg** [comment]
> Please forgive me for seeking help with some minor issues. I'm following the CapRover tutorial documentation, and I've been encountering an error when trying to install CapRover using Docker. The error message is consistently "Error: Port seems to be closed: 80." I've installed Docker version 19.03.15 on my Ubuntu 20.04 system, and when I run the command docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover, I receive this error. I've double-checked that my firewall is disabled, and port 80 is not in use. I've also attempted to solve the problem by using the command echo "{"skipVerifyingDomains":"true"}" > /captain/data/config-override.json, but it hasn't had any effect. I'm a novice and not very experienced with these tools, so I would appreciate any assistance in analyzing the root cause of this issue. Thank you for your understanding.

How did you solved it?

**Comment by githubsaturn** [comment]
Try this:
https://github.com/caprover/caprover/issues/1899#issuecomment-1739533625

**Comment by jektvik** [comment]
What is the check which is being run here -> i remember this problem many times, so i usually bypass it like you suggest. But it's getting annoying having to do this every time and also wondering if indeed everything is succiciently opened up.
What is the check which is being run for this proxy here, and why does it fail even if the ports are open ?

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/blob/master/src/utils/CaptainInstaller.ts#L112-L187

Here is the check. Basically a minimal server is set up on ports 80/443/3000 and then CapRover, from within the container, tries to fetch those IP:port combinations. This can fail if the requests from outside can reach the container, but the requests from within the container are getting blocked. There are a million reasons for this mostly related to the network topology. 

Do you have a custom set up (like a virtual box using proxmox or a home lab), or do you use standard VPS by DigitalOcean, Hetzner, Vultr, and such?

**Comment by jektvik** [comment]
This makes sense.
See upon digging deeper i can see the issue in my case is related to the
router.

Im running this on my home lab. I've got port forwarding set up  etc but it
seems that the hairpinning feature doesn't work for port 80 properly as the
router hijacks that request, whatever I try in the config, and redirects me
to it's own admin panel. Other ports are fine. That's of course internally.
When I call externally it works well.
