### ISSUE TITLE
CapRover >=1.11 embeds nonconsensual phone-home spyware.

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#1902]
It's really shameful that you feel entitled to surveillance of the users of this open source software.

The exfiltration of usage data in the form of nonconsensual phone-home surveillance added in 1.11 is unethical.

You must obtain consent from a user of the software before transmitting data to you about their usage.  Otherwise, you're just a spy.

Please fix this user-hostile malware to conform to ethical standards.  If you think your users want this to happen, then you can just ask them during install.  I think you won't be surprised to find that most users do not want your software to place them under surveillance.

I'm quite interested in testing out how many anonymous reports per second can be ingested by the `https://analytics-v1.caprover.com` API.   You want some open source surveillance data?  I think we can provide you with some open source surveillance data.

**Comment by githubsaturn** [comment]
Thanks for comment. Fortunately, all assumptions in this comment are factually incorrect. Try running CapRover:
![image](https://github.com/caprover/caprover/assets/10582082/c1cd17f9-1606-4c3d-9da0-ff2a1e39d85d)


Oh yes, I need to read Terms and Conditions:

![image](https://github.com/caprover/caprover/assets/10582082/920d3ca5-f69c-4c3a-94c7-84751653e760)

And yes, there is a clear mention of this. Plus a clear instructions to disable this BEFORE or AFTER installation. 



Also, your comments violates the Code of Conducts by attacking and spreading wrong information. Hence I am banning you from making further false accusations.

![image](https://github.com/caprover/caprover/assets/10582082/703dff76-7d01-4e4c-b6ad-f75c6c2f02fb)

**Comment by githubsaturn** [comment]
Last not least, threatening to DDOS is never a good strategy if you're truly coming from a good place.
