### ISSUE TITLE
update netdata 

### ISSUE THREAD

**Issue by mredodos** [caprover/caprover#1904]
hi, how can i update netdata? 

![image](https://github.com/caprover/caprover/assets/42175654/9f384b20-7d46-4733-afa9-d6509f850795)

**Comment by githubsaturn** [comment]
Netdata is built--in. If you use a different version, you don't get the capabilities of using env vars. But you feel you're comfortable doing so, you can always override the default netdata image by overriding the associated config:
https://caprover.com/docs/troubleshooting.html#customize-config-settings

**Comment by mredodos** [comment]
hi, thx for answere i dont want lost capabilities, you're not going to update it?

**Comment by githubsaturn** [comment]
It gets updated every now and then. But if you want you can always open a pull request.
