### ISSUE TITLE
[Deployment Issue] cant deploy angular app

### ISSUE THREAD

**Issue by therepo90** [caprover/caprover#1908]
Im trying to deploy an angular universal frontend app.
Ive tried a couple of deployment methods, all of them are failing:

1. build on caprover using branch-> it hangs and end in 502
2. build locally and push to global registry and use imagename -> 504 timeout
3. build locally and put built content in tar file. But cant wrap my head around how to create captain definition because I dont want to build anything. I just want to use node image and just copy everything and rune node main.js
captain definition
{
  "schemaVersion": 2,
  "dockerfilePath": "./ssr.tar.dockerfile"
 }
dockerfile
FROM node:16-alpine
CMD [ "node", "dist/stocks-filter-fe/server/main.js" ]

How to deploy a long build deployment?

**Comment by therepo90** [comment]
I solved my issue building it with .tar on my local machine, the deploying with -t option with the solution above, except that i copied the correct folder, cause 'dist' was not copied

FROM node:16-alpine
WORKDIR /
COPY . ./dist
CMD [ "node", "dist/stocks-filter-fe/server/main.js" ]

**Comment by githubsaturn** [comment]
Glad you solved the issue!

There are many tutorials on how to deploy various applications with Docker. Just as a note, CapRover is simply a Docker wrapper, so once you have a correct Dockerfile that can be used to deployed locally, you can deploy using CapRover. 

The only difference is the fact that some folders are git committed, like `dist`, you have to have proper `RUN npm build....` command in your Dockerfile.
