### ISSUE TITLE
Custom Header is not working with Caprover.

### ISSUE THREAD

**Issue by contentsr** [caprover/caprover#1912]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
custom header (api_key: "xyz...sfsdf") passed with API is not appearing in Caprover. It's working on other APP Hosting platforms, such as Vercel, why?

**Comment by githubsaturn** [comment]
It's the famous underscore issue with nginx:
https://stackoverflow.com/questions/26938604/get-headers-with-an-underscore-on-nginx
