### ISSUE TITLE
[Question] Does CapRover not support local Gitea via IP?

### ISSUE THREAD

**Issue by rondDev** [caprover/caprover#1919]
I have installed CapRover with a [local install](https://caprover.com/docs/run-locally.html#install-caprover-on-a-private-local-network) and attempted to create an app and supply it with an IP to my Gitea instance, but this gives me the error:
`1000 : Missing required Github/BitBucket/Gitlab field`

How would I be able to use my local gitea instance and supply it to CapRover without publicly exposing it?

**Comment by githubsaturn** [comment]
You need to make sure you have branch, repo, user/pass (or sshKey). One of these is missing:

See this: 
https://github.com/caprover/caprover/blob/e08c55db8926ea6e818fd3e2dbb53cc75c417b37/src/routes/user/apps/appdefinition/AppDefinitionRouter.ts#L363-L380
