### ISSUE TITLE
focalboard websocket connection lost

### ISSUE THREAD

**Issue by mredodos** [caprover/caprover#1920]
with last version of focalboard and postgres db 

![image](https://github.com/caprover/caprover/assets/42175654/2dcb9180-1d2a-46b6-a5dd-948bd6dad753)

https://www.awesomescreenshot.com/video/21602261?key=356fa2d592a190e10793d935162783ea

is like some missconfig 

i see here some nginx config from focalboard https://www.focalboard.com/download/personal-edition/ubuntu/#configure-nginx

but i dont understand what i need to do in caprover exaclty

**Comment by githubsaturn** [comment]
This is a post installation issue, you need to reach out to their forum. CapRover is simply an installation tool. The nginx configuration linked above technically can be done in a CapRover environment, but definitely not supported in the UI. You can click on EDIT NGINX CONFIGURATIONS in the app, and edit any parameters, but it's an advanced operations and if you're not familiar with nginx, it is quite possible that you break your nginx configuration. 

https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![image](https://github.com/caprover/caprover/assets/10582082/96cd08b3-a09c-4267-b514-12326a05096c)
