### ISSUE TITLE
1107 : Verification Failed. on app poste.io

### ISSUE THREAD

**Issue by mredodos** [caprover/caprover#1921]
i cant activate https on that app why? return alway 1107 : Verification Failed.

**Comment by githubsaturn** [comment]
I assume you're referring to the Poste.io one click app.

If you followed the instructions here: https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/poste-io.yml#L44-L53

it means you've change the https handling so that it's done by poste.io, not CapRover.

**Comment by mredodos** [comment]
in the DNS instructions miss some information about DMARC you need put in the host "_dmarc"

i had follow all the instructions and it seems the ssl is active but the domain point always on http if i try to go on https return 

![image](https://github.com/caprover/caprover/assets/42175654/7fb97393-d1cb-43b1-a216-8165d27b3ab6)

i see http env variable with OFF i i switch to ON the entire site crash and return always blu screen

**Comment by githubsaturn** [comment]
It's because you have changed the nginx configuration. CapRover only works with the default configuration. Can you take a screenshot of your http settings of your Poste.io app in CapRover dashboard?

**Comment by mredodos** [comment]
![Screenshot_20231016_075142_Chrome](https://github.com/caprover/caprover/assets/42175654/a8d74f99-a7db-45ba-b0ee-a28dcc6b645c)
![Screenshot_20231016_075147_Chrome](https://github.com/caprover/caprover/assets/42175654/b8d42813-b613-4485-b0d2-a14a38c1ccb5)
![Screenshot_20231016_075319_Chrome](https://github.com/caprover/caprover/assets/42175654/e18914e4-530d-440d-80ba-decce2b7bb6c)



`<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {


	<%
	if (s.redirectToPath) {
	%>
	    return 302 <%-s.redirectToPath%>;
	<%
	} else {
	%>

		    <%
		    if (s.httpBasicAuthPath) {
		    %>
			    auth_basic           "Restricted Access";
			    auth_basic_user_file <%-s.httpBasicAuthPath%>; 
		    <%
		    }
		    %>

			    proxy_pass $upstream;
			    proxy_set_header Host $host;
			    proxy_set_header X-Real-IP $remote_addr;
			    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			    proxy_set_header X-Forwarded-Proto $scheme;

		    <%
		    if (s.websocketSupport) {
		    %>
			    proxy_set_header Upgrade $http_upgrade;
			    proxy_set_header Connection "upgrade";
			    proxy_http_version 1.1;
		    <%
		    }
		    %>
    
    
	<%
	}
	%>
	
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            proxy_pass $upstream;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
`

**Comment by thgh** [comment]
I have struggled with poste.io too, will post my config later

**Comment by githubsaturn** [comment]
@mredodos here is the problem:
```
        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            proxy_pass $upstream;
        }
```

you're passing the cert check to poste.io. 

To put it in simple terms, you cannot have both poste.io and CapRover manage your SSL certs. If you want poste.io to manage your certs, CapRover cannot help setting up your certs.

**Comment by mredodos** [comment]
> @mredodos here is the problem:
> 
> ```
>         # Used by Lets Encrypt
>         location /.well-known/acme-challenge/ {
>             proxy_pass $upstream;
>         }
> ```
> 
> you're passing the cert check to poste.io.
> 
> To put it in simple terms, you cannot have both poste.io and CapRover manage your SSL certs. If you want poste.io to manage your certs, CapRover cannot help setting up your certs.

yes because i had follow the instructions 👯

**Comment by githubsaturn** [comment]
Here:
https://github.com/caprover/one-click-apps/pull/754

**Comment by mredodos** [comment]
ok thx
