### ISSUE TITLE
CapRover don't start containers

### ISSUE THREAD

**Issue by bbaltatu** [caprover/caprover#1923]
Hi,
I don't know why but caprover stop working after a while.
The services are now working but the apps that are defined and can be found in /captain/data/config-caprover.json are not starting. It is any way for forcing CapRover to load containers?

**Comment by githubsaturn** [comment]
CapRover doesn't run containers, docker does. 

Run this: 
```
docker service ls
```

What does it print?

**Comment by bbaltatu** [comment]
Hi
3 service running
![image](https://github.com/caprover/caprover/assets/11313025/18069d3c-0439-4b68-9daa-058f9f20db98)

**Comment by githubsaturn** [comment]
Your apps are fully deleted from Docker swarm. Did you do anything when this happened? e.g. left your machine off for a long time, or anything else?

You can try clicking on Save & Restart button on each app to see if it comes back up.

**Comment by capssantos** [comment]
Also, I'm facing the same issue, no changes have been made on caprover.

![image](https://github.com/caprover/caprover/assets/9909752/a2f5befd-8d13-4c4d-88f3-d58125a9c881)

**Comment by githubsaturn** [comment]
@capssantos your screenshot shows everything is running smoothly. What's the issue?

**Comment by capssantos** [comment]
@githubsaturn 

Caprover keeps restarting the container so I can't access it, I've already carried out the troubleshooting without success

**Comment by githubsaturn** [comment]
Can you copy the logs for captain-captain here?

**Comment by capssantos** [comment]
@githubsaturn 

Thank you, after updating the server and running the troubleshooting commands from the documentation again, access and SSL normalized.

Thanks again.
