### ISSUE TITLE
[Deployment Issue] Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

### ISSUE THREAD

**Issue by rschaerer** [caprover/caprover#1927]
I updated to the latest caprover version yesterday and after starting it normally my disk got full. Now after making free space on the disk, I get this error, when I try to `docker service ps captain-captain --no-trunc`:

`Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.`

:question: How can I proceed and get my CapRover instance back and running?

**Comment by githubsaturn** [comment]
This is not a CapRover issue, it looks your entire Docker swarm has gone down due to the system failure. Very likely it's irrecoverable. But if you're lucky, try to see if your apps are still in CapRover's config file:
```bash
cat /captain/data/config-captain.json
```

**Comment by rijavecb** [comment]
I'm running into the same issue since earlier today. It seems that netdata has filled the disk starting early today. 

```
3989a38c5617   caprover/netdata:v1.8.0                      "/run.sh"                1               48.3GB    5 months ago   Exited (137) 16 minutes ago   captain-netdata-container
```

![image](https://github.com/caprover/caprover/assets/15850530/2c7802fc-ab2c-4605-b38c-ddf04b8040dd)

I've removed that container a bit earlier, hoping that would fix the issue and get the CapRover running but I get the same swarm error when I run the same command:

```
root@docker-ce-something-caprover:~# docker service ps captain-captain --no-trunc
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

**Comment by githubsaturn** [comment]
That's very useful!

Take a copy of that file. Make sure you back it up somewhere safe. 

Then reinstall caprover from scratch. Once all the swarm containers are initiated, copy over your backed up file and override the existing file. Then simply restart CapRover. 


The one thing that won't work is your password. Follow the instructions how to reset your password.

**Comment by rijavecb** [comment]
Thank you so much for the help, @githubsaturn! I've saved the file just to have it, but also decided to nuke the VPS and start fresh, so I also reinstalled CapRover on another subdomain. I'll keep netdata off for now, just in case, as I was barely using it before anyways.

Thank you for creating and maintaining CapRover. It's great and I love using it 😌

**Comment by githubsaturn** [comment]
Oh no! You shouldn't have nuked your VPS. There are other files in /captain/data directory that are needed for CapRover to run. Specifically the SSL certificates. 
I'm glad you didn't have anything critical on the VPS :) but yea, if you want to take a backup, the entire directory is important to back up. 

PS: thanks for the kind words!
