### ISSUE TITLE
[Deployment Issue] ERR_CONNECTION_REFUSED after reboot

### ISSUE THREAD

**Issue by navin-hariharan** [caprover/caprover#1944]
![image](https://github.com/caprover/caprover/assets/42506955/b96ace1d-4c43-4f47-9ccc-fb0f4900658d)

Getting this error after I have rebooted my oracle instance!

**Comment by githubsaturn** [comment]
It looks like you have a separate nginx installed on your host that after reboot has taken over the port 80. 
Please uninstall that, and things will work fine. You can verify this by running `docker service ls` - right now you will see 0/1 in front of captain-nginx, but after you fix the nginx issue, you will see 1/1.


![image](https://github.com/caprover/caprover/assets/10582082/c3caf58f-9274-453c-83a0-15fbfc8cfb3e)
