### ISSUE TITLE
arm cpu Compatibility 

### ISSUE THREAD

**Issue by Tannyll** [caprover/caprover#1947]
**When will Caprover run on arm processors?**

 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
   Total RAM 25153 MB

**Comment by githubsaturn** [comment]
You already can!
https://caprover.com/docs/troubleshooting.html#arm-processor


The warning is already removed and will be available in the next release:
https://github.com/caprover/caprover/commit/10ea8dbf71e38c1e99441a0a9c202c076c8b1569
