### ISSUE TITLE
Ablity to stop and restart containers

### ISSUE THREAD

**Issue by TheProcedural** [caprover/caprover#1949]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to just stop an application (container) and I can't.

**Describe the solution you'd like**
The ability to stop apps (docker containers)

**Describe alternatives you've considered**
None, I've been manually doing it from the terminal, which defeats the purpose of using CapRover

**Additional context**
No need

**Comment by Vdauphin** [comment]
Hello,
As a trick, you can set the number of instance to `0` instead of `1` in Apps Configs

**Comment by githubsaturn** [comment]
^ this is the right approach! Setting the instance count to 0 effectively stops the app. Stop / Start in the context of Docker Swarm make little sense. They are used for single container management.
