### ISSUE TITLE
[Deployment Issue] on port 3000

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#1952]
Followed this closed ticket https://github.com/caprover/caprover/issues/1898 but it does not appear to work

**Comment by skiv71** [comment]
ID:             yq2df0qvlxcjcwa6a2e73mj29
Name:           captain-captain
Service Mode:   Replicated
 Replicas:      1
Placement:
 Constraints:   [node.id == nhjyg3lnrmlzmslh0phpfnufj]
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         caprover/caprover:1.11.1
 Env:           IS_CAPTAIN_INSTANCE=1 
Mounts:
 Target:        /captain
  Source:       /captain
  ReadOnly:     false
  Type:         bind
 Target:        /var/run/docker.sock
  Source:       /var/run/docker.sock
  ReadOnly:     false
  Type:         bind
Secrets:
 Target:        captain-salt
  Source:       captain-salt
Log Driver:
 Name:          json-file
 LogOpts:
  max-size:       512m

Resources:
Networks: captain-overlay-network 
Endpoint Mode:  vip
Ports:
 PublishedPort = 3000
  Protocol = tcp
  TargetPort = 3000
  PublishMode = host

**Comment by githubsaturn** [comment]
Let's continue the discussion in the other thread.
