### ISSUE TITLE
[Deployment Issue] Once click apps giving permission denied error

### ISSUE THREAD

**Issue by AhsanSarwar45** [caprover/caprover#1953]
What is the problem?
Whenever I try setting up any one-click app, I get the following error in the registering step:
`Failed: Error: Push failed: {"message":"denied: permission_denied: The token provided does not match expected scopes."}denied: permission_denied: The token provided does not match expected scopes.`

Tried it with a few apps, including MySQL, PostgreSQL, Excalidraw etc.

If applicable, content of `captain-definition` file:
None

Steps to reproduce the problem:
- Click on any one-click app
- Enter settings
- ![image](https://github.com/caprover/caprover/assets/41967492/cbbd0767-f697-452f-98fd-de705b3f3ee0)
- Click deploy
- ![image](https://github.com/caprover/caprover/assets/41967492/b4f92c83-8767-416d-9a6f-6467a1b7d76c)

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
```
Linux serverzero 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
               total        used        free      shared  buff/cache   available
Mem:           7.8Gi       602Mi       2.6Gi       2.0Mi       4.6Gi       6.9Gi
Swap:             0B          0B          0B
```

**Comment by githubsaturn** [comment]
Go to Cluster > Docker Registry > and disabled default push.

The reason you're seeing this error is that you have set up a push registry that cannot accept any images.
