### ISSUE TITLE
[Deployment Issue] Restart caprover after update failure

### ISSUE THREAD

**Issue by blackwiz4rd** [caprover/caprover#1954]
Hello all,

after updating docker, it now fails to run. The captain dashboard was no longer visibile, however I was able to run the docker containers that were started from it. In an attempt to try and restart captain, I have also stopped the containers (I believe).
Can anyone help me in restarting the containers/restarting captain dashboard back to normal?
I probably messed something up with swarm orchestrator

```
docker ps # shows no containers from caprover
docker images # shows my custom contaners starting with img-captain-*
e.g. 
img-captain-freelancetracker-django
caprover/certbot-sleeping
caprover/caprover
```

What I've been running in an attempt to fix:
```
 1910  docker service rm captain-captain
 1911  docker swarm leave --force
 1914  docker swarm init

docker service create captain-captain
image captain-captain:latest could not be accessed on a registry to record
its digest. Each node will access captain-captain:latest independently,
possibly leading to different nodes running different
versions of the image.

dj8ock4iw7fenvse2yj1mmso8
overall progress: 0 out of 1 tasks 
1/1: preparing 
```

Regards,
Luca.

**Comment by githubsaturn** [comment]
You have a system failure (disk failure). Definitely your old password does not work. But if you're lucky enough, you can get the dashboard up and running

Step 1- clean up your swarm:
```
docker swarm leave --force
```

Step 2- install CapRover using the installation command (NOT docker service create)
https://caprover.com/docs/get-started.html#step-1-caprover-installation

**Comment by blackwiz4rd** [comment]
Hello thanks for the help, I'm stuck here after running your command and this:
` docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

Captain Starting ...
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
     


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7624f6bc
`

**Comment by githubsaturn** [comment]
Your docker image and/or docker installation is corrupted. Try running this:

```
docker image rm caprover/caprover
docker pull caprover/caprover
docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

If this doesn't work, your host disk is corrupted.

**Comment by blackwiz4rd** [comment]
Still the same, however, I don't think it's downloading the image again but it looks like it's using the cached image.
Should I run this to clear the cache? Would this remove my other cached images which also have relevant data for me?
```
docker system prune -a
```

**Comment by blackwiz4rd** [comment]
I think we were missing:
  ```
  docker image prune
  ```.
But the output is still the same :(.

**Comment by blackwiz4rd** [comment]
I have some more interesting news, after building the image from repo (to make sure it was not something dealing with docker's cache) and starting it in the same way as the docs, I have the same issue:
```
docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover-custom
```

**Comment by githubsaturn** [comment]
By running that line it's only the installer that is using the custom image. CapRover internally sets up the docker service using the official image referenced here:
https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L18

**Comment by blackwiz4rd** [comment]
After tagging the image with `caprover/caprover` I still have the same result. I don't think it's using the cached image from docker at this point?
```
docker images | grep caprover
caprover/caprover-custom                            latest               3a61961f0e9c   11 hours ago     641MB
caprover/caprover                                   latest               3a61961f0e9c   11 hours ago     641MB

docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
Captain Starting ...
Installing Captain Service ...


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7494869c
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
```

**Comment by githubsaturn** [comment]
This must be a docker or a host issue. 

Can you reproduce this on a brand new server?

**Comment by blackwiz4rd** [comment]
I can try, but it will take a while because I have lots of configurations to transfer. Anyway, I tried with a docker re-install and we are still at the same point :/.

**Comment by blackwiz4rd** [comment]
Hello,
I've finally found a workaround. The issue is probably related to a system kibrary upgrade which has conflicts with npm:
https://www.reddit.com/r/homebridge/comments/v3b851/getting_fatal_error_in_line_0_failuremessage/
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/ (installing libseccomp2 solved the issue)
https://jackstromberg.com/2021/07/how-to-add-buster-backports-to-a-raspberry-pi/

Thanks a lot for the help.
