### ISSUE TITLE
One-Click Template for docker-compose mangling environmental values

### ISSUE THREAD

**Issue by dreadedhamish** [caprover/caprover#1958]
What is the problem?

Using the One-Click App "Template" to drop in a docker-compose file (with appropriatte caprover modifications):
Using environment variables like this:

service:
   environment:
    - key=value
    - key2=value2

Once installation is complete the environmental variables for the app are using a numeral for the key and "key=value" as the value:
0      key=value
1       key2=value2

I though maybe this was just semantics but my containers wouldn't start becuase the required environmental variables weren't present. Modifying each to correctly list key and pair resolved the issue.

**Comment by githubsaturn** [comment]
Use key value pairs instead of an array for the env vars:

```
        environment:
            KEY:My_value
````

**Comment by dreadedhamish** [comment]
> Use key value pairs instead of an array for the env vars:
> 
> ```
>         environment:
>             KEY:My_value
> ```

Thanks! I didn't know I was using an array, and I think I chop-and-change between the 2 formats often.
