### ISSUE TITLE
Suggestion: service logs via Console

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#196]
I know that the philosophy is not to provide an equivalent of each and every Docker function, but I would find it really useful to be able to view a live tail of the logs for a particular service (i.e. app) via the Captain console.

Basically it would just take the output from the following command and put it into an embedded frame within the app's settings page:

    docker service logs srv-captain--my_cool_app --since 10m --follow --timestamps --raw

You've already provided a very similar capability for the build logs, which seems to provide a dynamically-updated output from the build process within a frame on the app page, so doing the same for a log tail like the above should be easy.

At present, the main thing I find myself needing to do directly (once everything is up and running smoothly) is to take a quick look at the logs from a particular service (app)... and it's a pain having to ssh onto the server, and then run the above command, particularly when one's only access is via a small phone screen when out and about.

**Comment by MeXaaR** [comment]
+1

**Comment by wahkiz** [comment]
+1

**Comment by githubsaturn** [comment]
Done in V1.1.0
https://github.com/caprover/caprover/releases/tag/v1.1.0
