### ISSUE TITLE
Having the same image prefix name in Caprover cluster

### ISSUE THREAD

**Issue by moeIsAwesome** [caprover/caprover#1976]
Regarding CI/CD gitlab deployment. I have two projects. I had a successful deployment for one of my projects.
but for the second one I'm getting this error:
""
Deploy failed!
[585](https://gitlab.com.....-/jobs/5858789550#L585)Error: (HTTP code 404) unexpected - pull access denied for registry.gitlab.com/movies/funmovies/my-build-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[586](https://gitlab.com/.....-/jobs/5858789550#L586)Something bad happened. Cannot deploy movie-app2 at https://captain.caprover.....
"""
These projects are located in different repositories, but both under the /movies/ prefix. (I have a group for my projects).
I assume that when Caprover server tires to pull the images from gitlab container registry, it uses the image prefix to detect the container and since I have two equal image prefixes for my projects it takes the first one by default, and goes to my first project mistakenly.
<img width="1312" alt="image" src="https://github.com/caprover/caprover/assets/99014654/396e8c8e-4f45-41e6-aac3-0cc1b191d3f8">

The first row contains my access token to the first project and the second has the access token for the second project.

I'm saying this because when I use another repository which has a different image prefix, or does not have any image prefix, I do not get this error.

Can anyone confirm that? What is the process to take the correct container registry in repositories?

**Comment by githubsaturn** [comment]
Hi @moeIsAwesome  - as mentioned in the slack thread, you'll need to make your users specific to image prefixes.

If
* user1 has access to `movies/actionmovies`, use `movies/actionmovies` as the image prefix
* user2 has access to `movies/funmovies`, use `movies/funmovies` as the image prefix
