### ISSUE TITLE
Authorisation Provider integration (AWS Cognito, Google Firebase, ...)

### ISSUE THREAD

**Issue by JustinGuese** [caprover/caprover#1977]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**

I bet this isn't new, but something that would make Caprover perfect would be an integration with some kind of user management system... For example I could see a combination of oauth-proxy as a docker container, and then a simple "insert your Cognito creds" in settings, with an addition per app in the "basic auth" area. I might be up for coding, but I don't fully get the cap rover structure yet. Do you have some form of implementation of a user management system with cap rover where I could start off?

**Comment by githubsaturn** [comment]
Thanks for the question. Yes, this has been discussed in the past and we have decided not to integrate it as it does not fit in the simple model of "just works' that CapRover has. The feature set is intentionally being kept small to only support common use cases. 

> CapRover is not an enterprise grade application like Kubernetes. Do not patch it with half-done features that make it look like one - it will eventually fail as we don't have resources to support such features


Another point to keep in mind is that CapRover is designed to be a single user application.

**Comment by JustinGuese** [comment]
alright, sounds like a valid argument ;)! and sure I agree just "bloating it up" would be contrary to the idea of cap rover
