### ISSUE TITLE
portmapping to localhost/ip and UFW

### ISSUE THREAD

**Issue by JustinGuese** [caprover/caprover#1982]
Hey,

I read https://caprover.com/docs/database-connection.html and https://caprover.com/docs/app-configuration.html#port-mapping, but building on that:

**What I want to do:**
My node is in a private network, and my databases are mapped to a port on the machine. Now my plan was to connect to them via the private network, e.g. 10.0.0.23:5432, but have it secured and not reachable over the public ip thanks to UFW (e.g. 195.3.1.23:5432). I know UFW does not work with docker rules and would require iptable modifications instead, or having cap rover run on the private network IP only, but another solution mentioned to circumvent the docker-ufw-problem is to bind the port to the private ip only. With docker run this would be `docker run ... -p 10.0.0.23:5432:5432`

In cap rover I tried typing the exact same thing in the port mapping, but it does not work.
<img width="1056" alt="image" src="https://github.com/caprover/caprover/assets/9588843/1848f415-04c1-4ecf-ba32-92573d70647b">

I can edit the running docker container, or the cap rover config though, so it is possible, so I guess it's just due to a wrong formatting or pasting.

I think this could be a cool solution, also I would recommend mentioning more prominent that every port-mapping is publicly reachable in the UI, even with UFW enabled

**Comment by githubsaturn** [comment]
Only generic port mapping is supported on CapRover UI as of today, but you can definitely look into service override for these special use cases:

https://caprover.com/docs/service-update-override.html#schema
