### ISSUE TITLE
Deploy for localhost

### ISSUE THREAD

**Issue by mihalt** [caprover/caprover#1984]
I am trying to install docker like you said here in troubleshouting 

https://caprover.com/docs/run-locally.html#troubleshooting

I just replace ip to my local network ip in this command `docker run -e ACCEPTED_TERMS=true -e "MAIN_NODE_IP_ADDRESS=192.168.1.2" -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover` and get output like this. 

```
Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html





 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 4031 MB


Are you trying to run CapRover on a local machine or a machine without a public IP?
In that case, you need to add this to your installation command:
    -e MAIN_NODE_IP_ADDRESS='127.0.0.1'



Otherwise, if you are running CapRover on a VPS with public IP:
Your firewall may have been blocking an in-use port: 80
A simple solution on Ubuntu systems is to run "ufw disable" (security risk)
Or [recommended] just allowing necessary ports:
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;


See docs for more details on how to fix firewall issues

Finally, if you are an advanced user, and you want to bypass this check (NOT RECOMMENDED),
you can append the docker command with an addition flag: -e BY_PASS_PROXY_CHECK='TRUE'


Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:149:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

By the way, standard command `docker run -e ACCEPTED_TERMS=true -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` is working for me. But I can't understand what is address of my running in caprover apps from local network if not use custom domain. 

And by the way, when I run
`echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json`

I have error 
```
out-file : Could not find a part of the path 'C:\captain\data\config-override.json'.
At line:1 char:1
+ echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-o ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by githubsaturn** [comment]
Hi @mihalt  - you are trying to run CapRover locally on a windows machine. That adds two complications to the installation. 

CapRover is only tested on Linux systems (particularly Ubuntu). **WSL is not supported**.


When you have a local linux box, you can use 127.0.0.1 as your main IP, and you can access CapRover dashboard from `http://IP-of-your-Ubuntu-box:3000`

**Comment by mihalt** [comment]
> Hi @mihalt - you are trying to run CapRover locally on a windows machine. That adds two complications to the installation.
> 
> CapRover is only tested on Linux systems (particularly Ubuntu). **WSL is not supported**.
> 
> When you have a local linux box, you can use 127.0.0.1 as your main IP, and you can access CapRover dashboard from `http://IP-of-your-Ubuntu-box:3000`
Oh, it is a pity. 

And what about the apps of CapRover? How can I get them from local network?

**Comment by githubsaturn** [comment]
As long as you install CapRover on a linux box, and you have a local DNS server, CapRover assigns your apps specific domains.

**Comment by githubsaturn** [comment]
Otherwise, you can always use the port mapping feature.
