### ISSUE TITLE
Can't get any custom apps to work

### ISSUE THREAD

**Issue by FelixConni** [caprover/caprover#1991]
i am using droplet and ionos dns.

So I got caprover one-click apps working but when I tried to do custom apps it fails
https://github.com/caprover/caprover/tree/master/captain-sample-apps

I downloaded and extraced the .tar and tried "caprover deploy" and it doesn't give me option to choose a custom app?
![image](https://github.com/caprover/caprover/assets/65126243/a118f9a6-dfaa-4b59-aca1-72bd305ca3ee)

I tried uploading just the node.tar file using the ui also doesn't work. 

![image](https://github.com/caprover/caprover/assets/65126243/6a2174b8-75ec-4a36-9527-fe42682545fa)

And when i try to use a gitlab or github repo it says this (and my guess is because it doesnt copy the key properly because i push/pull the key works fine).
![image](https://github.com/caprover/caprover/assets/65126243/a33f1f9a-934f-4b51-ad18-1258030c85c0)

Can someone help me what I am doing wrong?

**Comment by maietta** [comment]
These apps only serve as a guide and cannot be followed exactly given how software and tooling changes over time.

The methods provided for deploying these apps though, remain exactly the same.

This is technically not a CapRover related issue. While I do agree that perhaps it would be wise to periodically update the examples, doing so requires time and effort from volunteers.

**Comment by githubsaturn** [comment]
There are different errors that you're seeing! 

1- you need to make sure your local machine is connected to a server. You can run `caprover login` to do this.


2- these are just warnings, you can ignore them, what's the actual error?


3- yes, this is a key related issue. A common problem is when you forget the trailing empty line etc)

**Comment by FelixConni** [comment]
it would be helpful if those files could be updated for beginners to test their deployment :D

Nice the command "caprover login" worked. 
![image](https://github.com/caprover/caprover/assets/65126243/f2572b0d-b982-409e-82a0-a180721f1976)
Now im getting this issue.
This is a working project and I just want to point the captain file to the docker compose file that's in the same directory.

also how do i properly copy the trailing empty line? 
I am using wsl to ssh to the server and using chrome on windows to open the ui.
and my "local" is in the server because I need access from multiple pcs.

**Comment by FelixConni** [comment]
![image](https://github.com/caprover/caprover/assets/65126243/8ad28d6c-00b7-4c7b-800e-a123f840f07b)
![image](https://github.com/caprover/caprover/assets/65126243/bd360655-9558-40af-b17e-f851aeffdf74)
just want to direct to the docker-compose.dev.yml?

**Comment by FelixConni** [comment]
Where can I get the logs to see what's causing the issue?
The gui just have multiple popups something went wrong?

**Comment by FelixConni** [comment]
k after some time just created a basic react project and well it has more progress so i guess somthing wrong with using docker file.
but i still hve the issue
![image](https://github.com/caprover/caprover/assets/65126243/60fa2c43-be53-4c68-9356-9394c769f0a3)
![image](https://github.com/caprover/caprover/assets/65126243/76b0db3a-9f59-4d43-aca5-f76fd8c5df46)
![image](https://github.com/caprover/caprover/assets/65126243/c385aaf1-f36c-402a-80e2-fefad0531c58)

and the page isn't loading

**Comment by githubsaturn** [comment]
Which sample app are you trying to build?

> Also why does the droplets go to "sleep or some unresponsive after a while" i have to power cycle so i can ssh again?

This is what's causing the issue. You probably are using a very small size Droplet that cannot handle the load of building an image. You probably need to upgrade to at least 2GB of RAM.

**Comment by FelixConni** [comment]
I was using a Docker 23.0.6 on Ubuntu 22.04. also did the do-release-upgrade. 

from the captain-sample-apps i tried building 
- angular-via-caprover.tar
- go-sample.tar
- node.tar
- react-via-caprover.tar

and none of them worked
I also tried to run a fresh projects without any additions that i created using webstorm
- react
- angular
- nodejs

I can try a new droplet with bigger memory tomorrow to see if that helps. 

Also is it possible to use a server (really good amd server) that I have at home running Ubuntu?

**Comment by githubsaturn** [comment]
> Also is it possible to use a server (really good amd server) that I have at home running Ubuntu?

Technically yes, but the set up is much more complex. 
https://caprover.com/docs/run-locally.html

**Comment by githubsaturn** [comment]
@FelixConni  - by the way, all apps you tried building are very heavy during the build time. 


If you want to try a light build app, you can try the PHP app here:
https://github.com/caprover/caprover/blob/master/captain-sample-apps/php.tar

This app can build on a 1gb machine

**Comment by FelixConni** [comment]
how can i copy the ssh key properly so i can directly use github/gitlab repos and also cicd pipeline?

**Comment by githubsaturn** [comment]
Here is the guide:
https://caprover.com/docs/deployment-methods.html#automatic-deploy-using-github-bitbucket-and-etc
