### ISSUE TITLE
Cannot "Enable HTTPS" for app on Caprover instance behind firewall with custom certificates. 1107 error.

### ISSUE THREAD

**Issue by mjmare** [caprover/caprover#1994]
What is the problem?

I want to enable HTTPS for a new app. This fails with a 1107 error.

Context:
The caprover instance cannot be reached from the internet because of a firewall. 
I use custom SSL certificates.
I have a custom Nginx config for captain and for each app. 
All this has worked so far. 

The problem:
I have installed a new app that works on http. Now I want to enable HTTPS through the UI. I get this error:

<img width="1350" alt="Screenshot 2024-01-18 at 13 10 23" src="https://github.com/caprover/caprover/assets/1711378/d7f72666-4bfb-4fd9-9654-8ef8808852d2">

Additional info: 
I had already domain checking: in the Captain container:
```
# cat /captain/data/config-override.json
{"skipVerifyingDomains":"true"}

```
My guess is that Certbot is trying to create or check the certificates. It should not do so. How do I really disable Certbot?

I was wondering how this has succeeded for other apps on the same server in the past. I think the firewall was not active at that time. 

Any help appreciated.

Marcel

----

I'm running Caprover 1.10.1.

The relevant part from the Nginx custom config: 
```
 if (s.hasSsl) {
    %>
        listen              443 ssl http2;
#        ssl_certificate     <%-s.crtPath%>;
#        ssl_certificate_key <%-s.keyPath%>;
# ADDED BY MJM
        ssl_certificate     /nginx-shared/certificates/__actools_nsdsk_nl.crt;
        ssl_certificate_key /nginx-shared/certificates/actools.nsdsk.nl.key;
# ADDED END
    <%
    }
```

```
uname -a && lsb_release -a && free -h
Linux nsdsk-anvil 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       908Mi       172Mi       7.0Mi       882Mi       855Mi
Swap:          2.0Gi       287Mi       1.7Gi
```

**Comment by githubsaturn** [comment]
Thanks for the thorough explanation! 

If you're using custom nginx config, you cannot use the "Enable HTTPs" functionality on the UI. In fact, that button should be called:
```
[Obtain Certbot Certificate and Use it in Nginx Config]
```

**Comment by githubsaturn** [comment]
So in your case, you can manually change 
```
if (s.hasSsl) {
```
to 

```
if (true) {

```

**Comment by mjmare** [comment]
@githubsaturn Thank you! This works. 
Would be nice if the user could "just" disable Letsencrypt, though. I don't trust myself next time to remember what I did....
