### ISSUE TITLE
[Question] Connecting wildcard domain

### ISSUE THREAD

**Issue by dat7e** [caprover/caprover#1995]
Hello,

Is there any way to connect wildcard domain to an app, with SSL support? My multi-tenant frontend app needs all requests `*.example.com` to be routed to `example.com`, where `*` would be the nickname of the customer. I already connected `example.com` and enabled SSL for it. Tried adding `*.example.com` but the UI did not allow me to do so.

I'd appreciate any guidance on this. And thanks for amazing work on Caprover.

**Comment by githubsaturn** [comment]
Short answer No.

CapRover uses http challenge Certbot for issuing SSL certificates. So you can't issue a wildcard certificate for all subdomains.
