### ISSUE TITLE
Unable to SSH to Server after deployment

### ISSUE THREAD

**Issue by cueup** [caprover/caprover#2001]
What is the problem?

I recently deployed caprover successfully and install 3 services
1. public github project using a tar
2. One-click app NocoDB
3. One-click app n8n

The caprover dashboard and app are all available and accessible, however, I can no longer SSH into my server, it just gives a timeout error.

This is the second time this has happened and before I could not gain access to the server no matter what I did. Does anyone have ay idea whats causing this?

captain definition file of github project:
 {
  "schemaVersion": 2,
  "dockerfileLines": [
                        "FROM library/python:3.11.7",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY requirements.txt /usr/src/app/",
                        "COPY translate.py /usr/src/app/",
                        "RUN pip install -r requirements.txt",
                        "CMD [ \"streamlit\", \"run\", \"translate.py\" ]"
                    ]
 }

Setup:
Ubuntu 20.4
1 GB RAM, 2 vCPUs, 40 GB SSD
Deployed on AWS Lightsail

**Comment by githubsaturn** [comment]
CapRover runs in a container, it does not change anything on your host. If you're using a VPS provider, I suggest logging into the recovery console, and debug what's going on. There are a lot of different reasons that this could happen, for example, if your deployment uses a lot of ram, your SSH server might not be able initiate and accept an incoming connection.

But regardless, CapRover is unable to cause this on its own as it runs in a confined container, the only access is to the er API.

**Comment by githubsaturn** [comment]
Thanks for the update!
