### ISSUE TITLE
create domin via api, using axios

### ISSUE THREAD

**Issue by AminAppDevs** [caprover/caprover#2002]
I want to create subdomians for existing app, using axsios, this is my code:
`async createSubdomain() {
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
    const capRoverBaseUrl = 'https://captain.mainroot.com';
    const capRoverApiKey =
      'app auth token';

    const headers = {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${capRoverApiKey}`,
    };

    const app_name = 'menu-master-store'; 
    const custom_domain = 'your-custom-domain.com';

    const addCustomDomainPath = '/api/v2/user/apps/appDefinitions/customdomain';
    const addCustomDomainUrl = `${capRoverBaseUrl}${addCustomDomainPath}`;

    const data = {
      appName: app_name,
      customDomain: custom_domain,
    };

    axios
      .post(addCustomDomainUrl, data, { headers })
      .then((response) => {
        console.log('Custom domain added successfully:', response.data);
      })
      .catch((error) => {
        console.error('Error adding custom domain:', error);
      });
  }`
  -----------------------------------------------------------------
this the error message:
` { status: 1106, description: 'Auth token corrupted', data: {} }`
------------------------------------------------------------------
how can i fix this

**Comment by githubsaturn** [comment]
This is wrong. App auth token is only used for deployment. You need to use the CLI:

https://github.com/caprover/caprover-cli?tab=readme-ov-file#api
