### ISSUE TITLE
Each time my app is deployed I get 502 until I do `Save & Restart` in app configs.

### ISSUE THREAD

**Issue by misaelvillaverde** [caprover/caprover#2006]
What is the problem?
I get 502 on every endpoint each time my app is deployed (Method 3: Deploy from Github)

To fix that, I have to always press the `Save & Restart` button in app configs. After that it is all working.

This started happening after creating my first worker node. Could it be the worker node RAM?

Steps to reproduce the problem:
* Deploy an app with multiple instances.
* Get 502 on every endpoint.
* Manually fix by restarting the app

---
Output of the following command on your server:
`uname -a && lsb_release -a && free -h`

Main node:
```
Linux xxx 5.15.0-1039-gcp #47~20.04.1-Ubuntu SMP Thu Jul 27 22:40:03 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          3.8Gi       933Mi       1.5Gi       2.0Mi       1.5Gi       2.6Gi
Swap:            0B          0B          0B
```

Worker node:
```
Linux xxx 5.15.0-1049-gcp #57~20.04.1-Ubuntu SMP Wed Jan 17 16:04:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          954Mi       281Mi       284Mi       1.0Mi       387Mi       512Mi
Swap:            0B          0B          0B
```

Thank you for this awesome software

**Comment by githubsaturn** [comment]
502 is a generic error, there are a few pointers [here](https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error)

- SSH to your server and view your application logs. Make sure it hasn't crashed and it's running. To view logs, please see the section at the end of this page "[How to view my application's log](https://caprover.com/docs/troubleshooting.html#how-to-view-my-applications-log)"
- If you application logs show that your application is running, the most common case is that your application is binding to a custom port, not port 80. For example, CouchDB runs at port 5984. In this case, go to app's settings on CapRover, go to HTTP Settings, then select 5984 as the "Container Port".
- If your app defines the binding IP address as 127.0.0.1, change it to 0.0.0.0, see [this issue](https://github.com/caprover/caprover/issues/76#issuecomment-481053496) for more details.

Very likely your application isn't running. You can get more information about why your application isn't running via docker commands, e.g. `docker service ps srv-captain--yourappname  --no-trunc`

**Comment by githubsaturn** [comment]
Another possibility is that your main node cannot connect to your worker node. Make sure all ports here are open:
https://caprover.com/docs/firewall.html


Feel free to comment if your issues doesn't get resolved.

**Comment by mqtik** [comment]
@githubsaturn is there a way to restart the proess automatically if it crashes? maybe increase the instanceCount? I have a pdf upload endpoint, and sometimes it crashes until I save & restart.

**Comment by githubsaturn** [comment]
CapRover (actually Docker Swarm) automatically restarts your app when it crashes.

**Comment by mqtik** [comment]
Sorry, I meant when users are seeing the 502 error — it doesn't go away unless I save & restart

**Comment by githubsaturn** [comment]
I see! 

502 is just a generic error that means the container failed to respond. If CapRover automatically restarts the container, the container might end up in an infinite loop.


However, there is a neat way to do this!! And that is HEALTHCHECK in docker. See here for example:
https://github.com/caprover/caprover/issues/661#issuecomment-1889531774


In general, HEALTHCHECK is managed by Docker. Here is a good guide:
https://dockerlabs.collabnix.com/beginners/dockerfile/healthcheck.html

**Comment by mebaysan** [comment]
For my case, nextjs is able to send request to `/bank` but it raises 502 on `/`. I solved by configuring the nginx.


```nginx
server {
    # Other settings...
    
    # Increase buffer sizes for larger headers
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    
    # Continue with the rest of your configuration...
}
```
