### ISSUE TITLE
BuildKit error on deploy

### ISSUE THREAD

**Issue by guzmanf** [caprover/caprover#2012]
my Dockerfile

--- stage 0 ---
FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

error
{"message":"the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled"}

but on clean installation linux (ubuntu 12) and run docker buildx build --progress=plain --no-cache -t tester/ulare-eps .  no problem

whta is teh problem ?

**Comment by githubsaturn** [comment]
CapRover uses `docker build`, the default builder. You're explicitly using `docker buildx`.

Feel free to open a feature request to support BuildKit. 


Workaround is to build your image on another platform. See here: https://github.com/caprover/deploy-from-github?tab=readme-ov-file#example-1---deploy-using-image
