### ISSUE TITLE
Can't join a server with docker swarm AWS EC2

### ISSUE THREAD

**Issue by ozzyoss77** [caprover/caprover#2017]
I can't connect an EC2 server to my Caprover instance via docker swarm join.

WORKER
- AWS EC2 Instance Ubuntu 22.04 LTS with Docker installed
- Security group (WORKER) with ports 80, 443, 22, 3000, and 2377 open on both servers
- UFW with ports 80, 443, 3000, 996, 7946, 4789, 2377/tcp; 7946, 4789, 2377/udp; (open on both servers)

I run the command: `sudo docker swarm join-token worker` on my main Caprover

I run the command on the WORKER: 
`docker swarm join --token SWMTKN-secret-token-here LEADER_EXTERNAL_IP:2377 --advertise-addr WORKER_EXTERNAL_IP:2377`

 it hangs and gives me:
`Error response from daemon: Timeout was reached before node joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.`

Has anyone had the same problem and been able to solve it?

**Comment by githubsaturn** [comment]
From your worker node run this command:

```
telnet LEADER_EXTERNAL_IP 2377
```
Does it work?

**Comment by ozzyoss77** [comment]
It worked now, thank you. Apparently, I made a mistake and didn't allow access to port 2377 of the LEADER unless it was from its own IP.

My bad.
