### ISSUE TITLE
[Question] How to connect a server in react with caprover using proxy?

### ISSUE THREAD

**Issue by RenanZX** [caprover/caprover#2020]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
I’m using a proxy server hosted at caprover with captain local url in my react app: srv-captain–service-api. However, when I set it in my package.json: 

“proxy”: [ “srv-captain–service-api” ]

All the requests to api fail. I can only use the api hosted in caprover if I use the IP and expose the port. Anyone can help me? Is it because the call is on the client side? I don't know how to figure out this problem.

**Comment by githubsaturn** [comment]
Frontend app runs in your browser, not the server, your browser doesn't have access to srv-captain--oneappname
