### ISSUE TITLE
MongoBD in CapRover App cannot connect from local machine

### ISSUE THREAD

**Issue by jhonysouza100** [caprover/caprover#2022]
Hello everyone, When connecting MongoDB Compass, it throws an error message: 

querySrv ENOTFOUND _mongodb._tcp.srv-captain--mongo-db.

Connection URL: `mongodb+srv://root:12345@srv-captain--mongo-db/admin?retryWrites=true&w=majority`

 

Can anyone help me fix this problem?

**Comment by githubsaturn** [comment]
The domain you're using is an internal domain, only visible from within the server. You cannot use this domain to connect from external devices. Use port mapping for that.

**Comment by jhonysouza100** [comment]
I understand, that was my doubt, I was able to solve it by changing the URL string that points to the server IP and adding Port Mapping to the one-click Caprover application.

Solution:
`mongodb://root:1234@24.199.34.12:27017/admin?retryWrites=true&w=majority`

Thank you very much Kasra Bigdeli :)
