### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by prognapratica** [caprover/caprover#2023]
I'm exploring CapRover and seek advice on making it function in a specific scenario.

I've developed a simple demo app with  the following:

```python
#main.py
from tasks import add
if __name__ == '__main__':
    import time
    while True:
        result = add.delay(4, 6)
        print(f"Task ID: {result.id}", flush=True)
        time.sleep(10)
```
```python
# tasks.py
from celery import Celery
import os
url = os.environ.get('REDIS_URL')
celery = Celery('tasks', broker=url)

@celery.task
def add(x, y):
    print(x,y)
    return x + y
```

In this situation, I need to run two commands within the same project: one to start a Python file's execution and another for the Celery worker.

These containers must communicate, as the Celery app requires knowledge of all project functions and access to the same libraries for task execution.

Locally, I run `celery -A task worker` in the virtual environment of my main.py file, followed by `python main.py` and it works seamlessly.

My question is: How can I achieve the same using CapRover? 

Currently, I've created two apps, "cel" and "main," identical except for Dockerfile modifications during deployment. For the Celery app, I adjust the Dockerfile to execute `CMD ["celery", "-A", "tasks", "worker", "--loglevel", "DEBUG"]`, and for the main app, I modify it to `CMD ["python", "main.py"]`.

I'm seeking alternative approaches since code changes require rebuilding both files. 

I observed that Glitchtip, a one-click app, achieves the desired configuration by launching four apps in the deployment: one for the backend, one for Redis, one for Django, and another for Celery.

Thanks in advance.

**Comment by githubsaturn** [comment]
@prognapratica - the problem you're describing isn't specific to CapRover, it's a Docker question. 

Basically there are many ways to do this, e.g.:

1- Run two containers (what you're doing right now)

2- Run one container with a subprocess that runs both processes. 
`run.sh`
```bash
#!/bin/bash

for cmd in "$@"; do {
  echo "Process \"$cmd\" started";
  $cmd & pid=$!
  PID_LIST+=" $pid";
} done

trap "kill $PID_LIST" SIGINT

echo "Parallel processes have started";

# Wait for any process to complete
wait -n

echo
echo "At least one process has completed, terminating others.";

# Kill remaining processes
kill $PID_LIST 2>/dev/null

echo "All processes have been terminated.";
```

```
CMD "run.sh server.sh celery.sh"
```



First approach is cleaner due to the separation of concerns. The second approach is easier to understand as both processes run in one container.
