### ISSUE TITLE
[Question] Configure app CPU and Memory limits

### ISSUE THREAD

**Issue by MarcosFincotto** [caprover/caprover#2026]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Is there any way to configure CPU and memory limits for an application? I tried to find something via dockerfile but I didn't find it ;(

**Comment by githubsaturn** [comment]
https://caprover.com/docs/service-update-override.html#sample-use-cases

**Comment by maietta** [comment]
> Thanks @githubsaturn , 
> I had located this documentation, but I'm not sure how to use it.
> Where should I insert the excerpt:
> 
> TaskTemplate:
>    Resources:
>      Limits:
>        MemoryBytes: 104857600
>        NanoCPUs: 2000000000

This needs to get formatted correctly and set in the Service Override section of your app.
