### ISSUE TITLE
[Feature] Build from personal one click application git repository

### ISSUE THREAD

**Issue by yiiman-dev** [caprover/caprover#2029]
**Is your feature request related to a problem? Please describe.**
Your one click installtion repository is grate, but some corporates have thier private topologies for one click installtions. so if exists options for add another repositories for one click app installtion, then can be very useful for business plan of caprover.

**Describe the solution you'd like**
I suggest create a form in settings to get addetional private or public git repositories that contains a customized fork of one click app project

**Comment by githubsaturn** [comment]
You can build your own one click app repository: 
https://github.com/caprover/one-click-apps?tab=readme-ov-file#build-your-own-one-click-app-repository
