### ISSUE TITLE
[Question] Unable to access CapRover dashboard after domain expiration

### ISSUE THREAD

**Issue by SimbaNinja917** [caprover/caprover#2031]
## Issue Description
I previously had a working CapRover instance accessed via the domain `captain.app.domain.com`. However, my domain `domain.com` expired and I lost access to it. My CapRover instance is hosted on a VPS with IP `xxx.xxx.xxx.254`, and I have root SSH access until this week when my VPS subscription expires. I won't be renewing my VPS as the vendor is a horrible cheap one with 3 years lock-in offers. 

I need to urgently backup the data from my NextCloud instance hosted on CapRover before I lose VPS access. I have already backed up the MySQL databases for Joplin and Wallabag from the SSH access, but I require access to the CapRover dashboard to backup NextCloud.

I purchased a temporary new domain `domain2.com` and set up the DNS records:

`captain.domain2.com` -> `xxx.xxx.xxx.254`
`caprover.domain2.com` -> `xxx.xxx.xxx.254`
`@.domain2.com` -> `xxx.xxx.xxx.254`
However, when I try to access these domains in my browser, I get the error `"the site can't be reached"`. DNS is propagated and pings to `domain2.com` redirect to the `xxx.xxx.xxx.254` IP. 

I followed [the instructions](https://github.com/caprover/caprover/issues/412#issuecomment-484077130) to run `nano /captain/data/config-captain.json` and removed the `nginxBaseConfig` and `nginxCaptainConfig` parameters from the JSON file, but I still cannot access the CapRover dashboard.

I tried to run the `caprover login` on the CLI, 

```
❯ caprover login

Login to a CapRover machine...

? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": https://captain.domain2.com
? CapRover machine password: [hidden]
? CapRover machine name, with whom the login credentials are stored locally: backupconn2

Something bad happened: cannot save backupconn2 at https://captain.domain2.com.
Error: connect ECONNREFUSED xxx.xxx.xxx.254:443
```

Can anyone help ? 

Thank you

**Comment by githubsaturn** [comment]
@SimbaNinja917 - you have FORCE SSL enabled. You also need to disable that in the config-captain file

**Comment by githubsaturn** [comment]
Also, very likely you don't need access to CapRover's dashboard to take a back up of your NextCloud. Just simply use `rsync` to backup your directories:

```
rsync -avz -e ssh user@your-vps-ip:/var/lib/docker/volumes /local/myvolumesbackup
```
