### ISSUE TITLE
OpenVPN fails enabling HTTPS

### ISSUE THREAD

**Issue by dreadedhamish** [caprover/caprover#2034]
I realise the OpenVPN image is deprecated and 3 years old, but without other options I gave it a go.

The instructions state you the first post-install step is enabling HTTPS -  this throws an error:
1107: Verification Failed
The domain correctly resolved to capRover nginx error page.

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

**Comment by dreadedhamish** [comment]
> https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

Thanks. I was thinking as it was something as basic as "enable HTTPS" it wouldn't be a container specific issue.

**Comment by githubsaturn** [comment]
That's right, 1107 specifically is called out in the docs:
https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107
