### ISSUE TITLE
CapRover is no longer open source but still lists open source on the website and documentation.

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#2035]
CapRover is no longer open source as of 20 July 2023.

Two reasons:

1) the code is no longer licensed under the Apache free software license.  The license is now a custom modified version of the Apache license that restricts software freedoms (i.e. makes this proprietary software source-available, not open source).  Additionally, it appears that the codebase was relicensed illegally by the maintainer (i.e. without the consent of all of the copyright holders of the code, as external contributors have not, to the best of my knowledge, assigned their copyright or ability to relicense to the maintainer - CapRover has no CLA).

https://github.com/caprover/caprover/blob/master/LICENSE

2) CapRover now requires the acceptance of an End User License Agreement (EULA, called "Terms and Conditions" by CapRover) to use it.  This EULA was added by the developer (who holds copyright to part of the codebase).  Adding restrictions on the use of previously free software makes this nonfree software (i.e. not open source).

https://github.com/caprover/caprover/blob/master/TERMS_AND_CONDITIONS.md

> By using CapRover you agree to Terms and Conditions, and the license of CapRover.

Before you ask:

Open source does not mean "source code can be downloaded".  Open source means free software, which is not software distributed for free, but software that respects user freedoms.  The license restrictions placed on CapRover make it nonfree software, as well as the EULA acceptance requirement which also makes it nonfree software.

Advertising nonfree software as "open source" is incorrect and erroneous and misleading.  Open source means free software and free software alone.

If you have any further questions about what is and isn't open source, please refer to the following document:

https://opensource.org/osd

Specifically, 3. Derived Works.  Software that restricts modification (such as CapRover) is not open source.

Additionally, 6. No Discrimination Against Fields of Endeavor.  Software that restricts use in commercial enterprises is not open source.

Lastly, 7. Distribution of License.  Open source software licenses must not require user agreement to additional licenses (such as end user license agreements, like the one in CapRover).

**Comment by githubsaturn** [comment]
"Open source" is not trademarked. All open source software come with a license. The word open source is not legally binding to a specific license.
