### ISSUE TITLE
CapRover isn't Open Source, and denies the Open Source Initiative's definition of it

### ISSUE THREAD

**Issue by justinclift** [caprover/caprover#2036]
Apparently @githubsaturn has a better understanding of what "Open Source" means than the Open Source Initiative (OSI), who defined it, and who is largely made up of lawyers and legal experts: https://github.com/caprover/caprover/issues/2035#issuecomment-2026199635

As per the referred comment:

```
"Open source" is not trademarked. All open source software come with a license. The word open source is not
legally binding to a specific license.
```

Are you ***sure*** that's what you want go with @githubsaturn? :wink:

**Comment by githubsaturn** [comment]
I'll send you an email. Please stop spamming :)

**Comment by justinclift** [comment]
I've not created issues here nor commented before.  So I'm definitely not spamming.

**Comment by githubsaturn** [comment]
Apologies. Misread the user name.
