### ISSUE TITLE
[Question] CertBot Docker container using a no longer supported version

### ISSUE THREAD

**Issue by FernandoAFaria** [caprover/caprover#2038]
Hello!

We got a security vulnerability warning with a docker image on Caprover, seems to be certbot.  Its using Alphone 3.12.0 which is End-of-Life as of 04/30/2022

Is there any way to update this?

**Comment by githubsaturn** [comment]
You can simply run `docker service update --image caprover/certbot-sleeping:amd64-v1.14.0 captain-certbot`

But beware that this is an untested version of the image and it may cause issues. Since the container runs in an isolated environment there is little security risk in using the old version.
