### ISSUE TITLE
directory index of "/app/" is forbidden [Question]

### ISSUE THREAD

**Issue by cueup** [caprover/caprover#2039]
I'm trying to deploy a custom php app with the captain-definition file below but I get a 403 Forbidden went I visit the web link and "*1 directory index of "/app/" is forbidden, client: 10.0.1.6, server: _, request: "GET / HTTP/1.0" from the logs.

my custom app has a /app directory in the root which I suspect is the issues. What workaround can I use to fix this?

 {
  "schemaVersion" :2 ,
  "dockerfileLines" :[
                        "FROM  webdevops/php-nginx:7.4-alpine",
                        "ENV PHP_MAX_EXECUTION_TIME 110",
			"COPY ./ /app"
                    ]
 }

**Comment by githubsaturn** [comment]
Does this work outside of CapRover? i.e. if you manually just enter the same dockerfile and run `docker build.....` ?

**Comment by cueup** [comment]
Hey Kasra, I haven't tried that, I'm running the application locally using WAMP.

I was hoping there would be a workaround to deploy on caprover.

**Comment by githubsaturn** [comment]
CapRover simply just runs your Docker image. My guess is that your dockerfile is the culprit. Here is what I suggest:
1- Create a Dockerfile in your project with this content:
```Dockerfile
FROM webdevops/php-nginx:7.4-alpine
ENV PHP_MAX_EXECUTION_TIME 110
COPY ./ /app
```

2- Run:
```
docker built -t test-image .
docker run -p 8080:80 test-image
```

3- Open your browser to http://127.0.0.1:8080 and see if your image works. Once you get this working, your CapRover project also works.

**Comment by cueup** [comment]
After a lot of tinkering, this is what worked in the end. Just in case anyone else faces this issue

                        "FROM webdevops/php-nginx:8.1-alpine",
                        "ENV PHP_MAX_EXECUTION_TIME 110",
                        "COPY ./ /var/www/html",
                        "ENV WEB_DOCUMENT_ROOT=/var/www/html/public",
