### ISSUE TITLE
[Question] how to add mimtype?

### ISSUE THREAD

**Issue by cannap** [caprover/caprover#2041]
hi first of all i want to say thank you this thing is awesome.

Question:
i cannot not ffgure out how to add this 
https://vite-pwa-org.netlify.app/deployment/nginx.html#configure-manifest-webmanifest-mime-type

**Comment by githubsaturn** [comment]
It's really simple!
- Go to your application configuration, under the first tab, click on **Edit Default Nginx Configurations**
- Find this line: `client_max_body_size 500m`
- Add the mime block like this:
```
client_max_body_size 500m;

types {
  application/manifest+json  webmanifest;
}

```
