### ISSUE TITLE
how to secure DB

### ISSUE THREAD

**Issue by wp-coin** [caprover/caprover#2046]
I have successfully installed MariaDB via docker image ``` https://hub.docker.com/r/linuxserver/mariadb  ``` and want to know how to secure the DB

Is there a way to run "mysql_secure_installation"  in caprover?

or are there other methods?

**Comment by githubsaturn** [comment]
This is unrelated to CapRover. But here is some information on this: https://www.reddit.com/r/docker/comments/rhwf28/mysql_secure_installation_on_mariadb_with_docker/
