### ISSUE TITLE
[Deployment Issue] One Click Apps all time loading

### ISSUE THREAD

**Issue by C2C-PAY** [caprover/caprover#2047]
After installation, I can't create one-click apps. After clicking the button I see continuous loading

![image](https://github.com/caprover/caprover/assets/162576041/da0b8225-1bac-4cf7-a708-be60b3b5ffcf)

Last login: Fri Apr 26 01:27:23 2024 from 112.134.156.203
root@cv3615877:~# docker service logs captain-captain --since 5m --follow
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | Captain Starting ...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.235 pm    Emptying generated and temp folders.
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.248 pm    Ensuring directories are available on host. Started.
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.254 pm    Ensuring directories are available on host. Finished.
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.259 pm    Network captain-overlay-network is already attached to service: capt                                                               ain-captain
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.265 pm    captain-captain (service) has already been connected to secret: capt                                                               ain-salt
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.267 pm    Migration not needed, skipping.
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.271 pm    Copying fake certificates...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.276 pm    Updating Load Balancer - Setting up NGINX conf file...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.276 pm    Locking NGINX configuration reloading...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.281 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.285 pm    Captain Nginx is already running..
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.288 pm    Updating NGINX service...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:0                                                               6.297 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               1.299 pm    Pruning containers...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               1.300 pm    NGINX is fully set up and working...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               1.303 pm    Captain Certbot is already running..
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               1.308 pm    Updating Certbot service...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               4.339 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               6.324 pm    Pruning containers...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:1                                                               7.343 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:2                                                               0.349 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:2                                                               3.354 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:2                                                               6.359 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:2                                                               9.362 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:2                                                               9.365 pm    executeCommand Container: captain-certbot certbot certificates --non                                                               -interactive
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:3                                                               0.633 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               0.635 pm    executeCommand Container: captain-certbot certbot certificates --non                                                               -interactive
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               1.326 pm    executeCommand Container: captain-certbot certbot renew --non-intera                                                               ctive
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               2.014 pm    Updating Load Balancer - renewAllCerts
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               2.014 pm    Locking NGINX configuration reloading...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               2.021 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               2.021 pm    sendReloadSignal...
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | April 25th 2024, 10:47:4                                                               2.024 pm    Kill HUP Container: 6001c899fea4d60b3758e745dfb596b77fe12537e6ea58f6                                                               39e2ae0075f9e0cb
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET / 302 2.288 ms - 108
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET / 200 4.581 ms - 591
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /static/js/main.163848a9.js 304 1.784 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /light-theme.css 304 0.603 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /icon-512x512.png 304 0.649 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /dark-theme.css 304 0.586 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /light-theme.css 304 0.488 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /manifest.json 304 0.539 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /icon-512x512.png 304 0.568 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | POST /api/v2/login 200 245.653 ms - 307
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /icon-512x512.png 304 1.394 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/system/info 200 2.113 ms - 156
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/apps/appDefinitions 200 3.297 ms - 2943
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/system/versioninfo 200 767.592 ms - 153
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/repositories 200 2.118 ms - 87
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/template/list - - ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/apps/appDefinitions 304 3.309 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/repositories 304 1.162 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/template/list - - ms - -

**Comment by C2C-PAY** [comment]
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/system/versioninfo 304 1642.563 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/system/versioninfo 304 749.863 ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/template/list - - ms - -
captain-captain.1.ynvlyo1ivrga@cv3615877.novalocal    | GET /api/v2/user/oneclick/template/list - - ms - -

**Comment by githubsaturn** [comment]
@C2C-PAY - very likely your VPS provider is blocking access to the github pages. 

Official one click apps are hosted on the github pages. You can try the demo instance and you'll see that it works fine:

https://captain.server.demo.caprover.com/
password: captain42

**Comment by C2C-PAY** [comment]
> - very likely your VPS provider is blocking access to the github pages.

Sorry, I can't understand. I have .github\workflows in my project and github integration with caprover custer and deployment successful. Not work only one click apps, when i press button i can't see apps list

**Comment by githubsaturn** [comment]
What i mean is that your VPS is blocking access to GitHub pages. What VPS provider are you using? Where's the server located?

**Comment by C2C-PAY** [comment]
Hello. My cloud service is located in Russia. VPS provide: reg.ru

**Comment by C2C-PAY** [comment]
Thanks, I'll set up vps on another provider.
