### ISSUE TITLE
caprover deploy not updating files on the server

### ISSUE THREAD

**Issue by wp-coin** [caprover/caprover#2055]
I have been pushing files updates to the server but no files has been updated

I have been using the same message when committing changes in git

**Comment by githubsaturn** [comment]
The files in "persistent directory" don't get updated - they are overriden by Docker volumes. 

By any chance, do you have any volumes set up on your application?

**Comment by githubsaturn** [comment]
Yes, in that case you can't override the content with image. Those files are mapped to a directory on disk. 

This is not CapRover specific and it's just how docker works:
Read this for example:
https://www.reddit.com/r/docker/comments/h95lxv/comment/fuv3lbh/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

**Comment by githubsaturn** [comment]
> but I originally uploaded my files to the image with Docker file

Like I said, it doesn't matter if you push your files. The files in the volume (aka persistent directory) will be ignored by the image push. They'll continue to be the dame files as the app was first created
