### ISSUE TITLE
[General Question] change captain-overlay-network subnet 

### ISSUE THREAD

**Issue by roominarcom** [caprover/caprover#2056]
Hello
After installing caprover, captain-overlay-network is created with subnet /24
I have done the daemon.json file as below setup
```
{
   "default-address-pools": [
     {
       "base": "10.10.0.0/16",
       "size": 18
     }
   ]
}
```
Then I have run the service `docker restart command`
But again after installation
`docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/ caprover`

The network is like this
`docker network inspect captain-overlay-network
`
```
[
     {
         "Name": "captain-overlay-network",
         "Id": "yxncjvkalfu5bkcasgc2hf9zb",
         "Created": "2024-05-08T06:43:09.438443829Z",
         "Scope": "swarm",
         "Driver": "overlay",
         "EnableIPv6": false,
         "IPAM": {
             "Driver": "default",
             "Options": null,
             "Config": [
                 {
                     "Subnet": "10.0.1.0/24",
                     "Gateway": "10.0.1.1"
                 }
             ]
         },
```
What is the solution to this problem so that I can expand the network to a larger subnet?
thank you

**Comment by githubsaturn** [comment]
There is an override config that you can set `useExistingSwarm` to true and create the swarm cluster and overlay network manually. Then just simply run the installation `docker run....` and it uses the existing settings. 

1- Create swarm
```
docker swarm init --advertise-addr <MANAGER-IP>
```

2- Create overlay network
```
 docker network create --scope=swarm --attachable --subnet=172.28.0.0/16 -d overlay captain-overlay-network
``` 


3- 
```
mkdir -p  /captain/data
echo  "{\"useExistingSwarm\":\"true\"}" >  /captain/data/config-override.json
```

4-
```
docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
