### ISSUE TITLE
How to update the certificate of my self hosted registry?

### ISSUE THREAD

**Issue by Ataye** [caprover/caprover#2059]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

I just attempted to push an app update but got the following error on deployment:

```
Deploy failed!
Error: Push failed:
{"message":"Get \"https://registry.hosting.myserver.au:996/v2/\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-05-11T16:28:14-07:00 is after 2024-05-01T08:25:41Z"}Get "https://registry.hosting.myserver.au:996/v2/": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-05-11T16:28:14-07:00 is after 2024-05-01T08:25:41Z
```
How do i update the cert?  I can't edit under registry conf as `You cannot edit the self hosted registry. It is managed by CapRover.`.

**Comment by githubsaturn** [comment]
Certificate is most likely updated, it's just your service hasn't updated its cache.

Try running 

```
docker service update captain-registry --force
```
