### ISSUE TITLE
[Deployment Issue] persistent storage not available during deployment

### ISSUE THREAD

**Issue by tomaskikutis** [caprover/caprover#2062]
I'm using nextjs which pre-renders routes during deployment. It raises an error that it can't find my sqlite database which I have in a persistent directory. I did run an additional test by adding `RUN ls /` to my docker file and I see that my persistent directory is not printed.

Is there a way to allow deployment process access persistent directories?

**Comment by githubsaturn** [comment]
No, the deployment process is fully isolated from the runtime by design - per 12 factor app:
https://12factor.net/build-release-run
