### ISSUE TITLE
[Deployment Issue] React App Refresh Results in 404 Error Despite Nginx Configuration Modifications

### ISSUE THREAD

**Issue by Hertak** [caprover/caprover#2064]
I have a React application deployed on CapRover that works fine, except when I refresh the page, it results in a 404 error. I have attempted to resolve this by modifying the Nginx configuration, but the issue persists.

Current Nginx Configuration:
`<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>
server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

    client_max_body_size 500m;

    server_name  <%-s.publicDomain%>;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

    location / {

        <%
        if (s.redirectToPath) {
        %>
            return 302 <%-s.redirectToPath%>;
        <%
        } else {
        %>

            <%
            if (s.httpBasicAuthPath) {
            %>
                auth_basic           "Restricted Access";
                auth_basic_user_file <%-s.httpBasicAuthPath%>; 
            <%
            }
            %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            <%
            if (s.websocketSupport) {
            %>
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
            <%
            }
            %>
    
        <%
        }
        %>
    }
    # Redirigir todas las rutas que no sean archivos estáticos a index.html
    location / {
        try_files $uri /index.html$is_args$args =404;
    }

    # Used by Lets Encrypt
    location /.well-known/acme-challenge/ {
        root <%-s.staticWebRoot%>;
    }
    
    # Used by CapRover for health check
    location /.well-known/captain-identifier {
        root <%-s.staticWebRoot%>;
    }

    error_page 502 /captain_502_custom_error_page.html;
    location = /captain_502_custom_error_page.html {
        root <%-s.customErrorPagesDirectory%>;
        internal;
    }
}
`
Steps to Reproduce:

Deploy a React application on CapRover.
Modify the Nginx configuration as shown above.
Access the application and verify it loads correctly.
Refresh the page on any route other than the root.
Expected Behavior:
The page should refresh correctly without any errors.

Actual Behavior:
Refreshing the page results in a 404 error.

Additional Context:

CapRover version: [Specify your CapRover version]
React application is configured to use client-side routing.
Could you please provide guidance on resolving this issue?

Thank you.

**Comment by githubsaturn** [comment]
Checkout this guide to learn how to deploy react app: https://caprover.com/docs/recipe-deploy-create-react-app.html

You do not need to modify the nginx configs.

**Comment by Hertak** [comment]
Thanks for response. The deploy is fine and the app is working very well. The problem is when you navigate to a route like /panel and refresh the page say 404, in local that not happen only in caprover.

**Comment by githubsaturn** [comment]
Even with socialengine/nginx-spa image as per the guide liked above?

**Comment by Hertak** [comment]
My bad, Now is working. Thanks

**Comment by KiNavii** [comment]
How did you solve it, Sir?

**Comment by Hertak** [comment]
> How did you solve it, Sir?

Follow this guide https://caprover.com/docs/recipe-deploy-create-react-app.html
is simple you need deploy the build with the image socialengine/nginx-spa:latest
