### ISSUE TITLE
Problem renewing the ssl certificate from caprover

### ISSUE THREAD

**Issue by xnardo** [caprover/caprover#2065]
**What is the problem?**

Hello, I have been having the following problem for 1 month when trying to activate or renew the certificate. I think I must have a block with letsencrypt. And I think it was because we executed the following command in caprover (since it is the second time that it happens to me, but this time, it did not solve itself):

`docker service update captain-registry --force`

**Issue: Bug:**
`
1107 : Unexpected output when enabling SSL forcode.app.toolmas.com with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None [31mAn unexpected error occurred:[0m [31mrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3bb1443a60>: Failed to establish a new connection: [Errno -3] Try again'))[0m Please see the logfiles in /var/log/letsencrypt for more details.
`
**When i check with `tail /var/log/letsencrypt/letsencrypt.log`**
```
esponse = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3bb1443a60>: Failed to establish a new connection: [Errno -3] Try again'))
2024-05-22 14:30:07,142:ERROR:certbot._internal.log:An unexpected error occurred:
2024-05-22 14:30:07,144:ERROR:certbot._internal.log:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3bb1443a60>: Failed to establish a new connection: [Errno -3] Try again'))
```

Steps to reproduce the problem:

Linux 5.4.0-177-generic #197-Ubuntu SMP Thu Mar 28 22:45:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
              total        used        free      shared  buff/cache   available
Mem:          1.9Gi       618Mi       419Mi        17Mi       932Mi       1.1Gi
Swap:            0B          0B          0B

**Comment by githubsaturn** [comment]
The error is happening outside of CapRover - it's related to certbot. My guess is that you have firewalls that prevents Let's Encrypt servers from reaching out to your machine.

**Comment by githubsaturn** [comment]
See here for a similar issue: https://community.letsencrypt.org/t/renew-cert-max-retries-exceeded-with-url-directory/152265

**Comment by zfcsoftware** [comment]
I had a similar problem and the solutions here didn't work. It worked after I turned off all my Cloudflare rules. If you are having problems, you can turn off Cloudflare proxy and then try it.
