### ISSUE TITLE
[Question] Access CapRover dashboard through a secure connection

### ISSUE THREAD

**Issue by TylerWanta** [caprover/caprover#2067]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
I've previously setup caprover with digital ocean and have been accessing the dashboard by entering the ip + port into my browser. This issue with this is that the connection isn't secure. From my understanding, I should be able to access the caprover dashboard from the root domain entered on the caprover dashboard but without the wildcard, correct? When attempting this the connection is secure but, I just get the blue screen with 'nothing here yet'. All my apps have secure connections, I just need it for the dashboard. What do I need to do to achieve this?

**Comment by githubsaturn** [comment]
You have to run `caprover serversetup` right after installing CapRover. I am guessing you have skipped that part.

Watch this tutorial: https://youtu.be/E16KymP6284?si=2xh3nvj69huokf87&t=334

**Comment by TylerWanta** [comment]
I've already done this. When trying to run it again I get the message `You may have already setup the server with root domain: {domain}! Use caprover login to log into an existing server.`

**Comment by githubsaturn** [comment]
Can you access your domain via captain.root.domain.com ?

**Comment by TylerWanta** [comment]
Ah, just needed to add `captain` to the front. I was only doing `root.domain.com`. Thanks for the help, sorry for the bother.
