### ISSUE TITLE
[Question] Can you use network_mode with CapRover

### ISSUE THREAD

**Issue by dann2g** [caprover/caprover#2071]
Is it possible to use `network_mode` from docker-compose with CapRover?

We're setting up Tailscale to restrict access to some services (as per https://tailscale.com/kb/1282/docker) but the Nginx container is unable to connect to the Tailscale container because `network_mode` is never set.

**Comment by githubsaturn** [comment]
Any property that is supported by docker swarm service is also supported by caprover. 

But in this case, it looks like this property isn't supported by swarm:
https://docs.docker.com/reference/cli/docker/service/create/#network
