### ISSUE TITLE
Recent Webhook malformed jet token

### ISSUE THREAD

**Issue by JustinGuese** [caprover/caprover#2072]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

Recently, my GitHub web hooks are not delivering anymore for the CI/CD pipeline.
This also happens when setting up a new app, so I guess there is something wrong in the background? Did the git web hook message format change?

<img width="1069" alt="image" src="https://github.com/caprover/caprover/assets/9588843/c9d0d5af-239f-4ae2-964a-fb6d60289588">

**Comment by githubsaturn** [comment]
I just created a test app and it works fine. Probably your URL is malformed (copy paste mistake)

Here is the test app:
1) login to 
https://captain.server.demo.caprover.com
password: `captain42`

2) run this command form your local machine and see that the deployed version for the demo app is increasing:
```
curl https://captain.server.demo.caprover.com/api/v2/user/apps/webhooks/triggerbuild\?namespace\=captain\&token\=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuVmVyc2lvbiI6ImJhNzYyZjlmLTQyZDctNGYxOS04MjQyLTY4ZGZkMjNiNDlmOCIsImFwcE5hbWUiOiJ3ZWJob29rLXRlc3QiLCJuYW1lc3BhY2UiOiJjYXB0YWluIn0sImlhdCI6MTcxNzAzNzM5NH0.A-fQDk4zQH2IcNkgoZGFIIfRVsaOJifAqxJV1qYD9cc -X POST
```

**Comment by JustinGuese** [comment]
hmmm I even reinstalled (backup & restore) the cap rover app, but I am still getting 
```
JsonWebTokenError: jwt malformed
    at module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:63:17)
    at /usr/src/app/built/user/Authenticator.js:148:17
    at new Promise (<anonymous>)
    at Authenticator.decodeGenericToken (/usr/src/app/built/user/Authenticator.js:147:16)
    at Authenticator.decodeAppPushWebhookToken (/usr/src/app/built/user/Authenticator.js:117:21)
    at /usr/src/app/built/injection/Injector.js:152:14
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
 ```
in the app

when trying to copy the GitHub call with curl the response of cap rover is {"status":1106,"description":"Auth token corrupted","data":{}}


sooo.... any idea how to "rebuild" the auth token?

**Comment by JustinGuese** [comment]
@githubsaturn okay now it's getting strange, 
I inserted the hook [...]**90LWFpa**W52ZXN0LXdlYnNpdGUtcHJlZmVjdC1hZ2VudCIsIm5hbWVzcGFjZSI6ImNhcHRhaW4ifSwiaWF0IjoxNzEyMzE4NzI0fQ.2CWVhzoR-Uzc5wWS4tnpC8GS4COVX0N5YMbmtwd_sT4
into GitHub. this is saved in the GitHub web hook.

BUT
the actual url/token sent by GitHub is 
[...]**90LWFpa**

is this actually a GitHub error :o ? or a size limit by GitHub web hooks?

**Comment by JustinGuese** [comment]
Damn, it looks like it's really a GitHub bug, as the web hook is cut off after 255 characters!
https://support.github.com/ticket/personal/0/2834287
