### ISSUE TITLE
[Question] Is it possible to share captain overlay network between instances without joining swarm?

### ISSUE THREAD

**Issue by dann2g** [caprover/caprover#2073]
Example:
- Server A and B are part of a swarm
- Server C wants to be able to communicate with A and B via the same captain overlay network as A and B but have its own web interface, run its own services and not pick up tasks from the swarm

Is this possible?

**Comment by githubsaturn** [comment]
Overlay network can only be shared across one cluster of swarm. Because of that, if you want server C to be on the same overlay network, it has to join the same cluster.
