### ISSUE TITLE
It is possible to config all in one nextcloud in caprover?

### ISSUE THREAD

**Issue by xnardo** [caprover/caprover#2076]
Hello! Can I replace the entire nginx configuration block in caprover, as indicated in `all-in-one nextcloud`, or it is better to use the version on One Click Apps?. I ask the question, more than anything because all-in-one has interesting functionalities, but I also see that it can affect the functionality of caprover.

* Instructions of nextcloud > https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

Thanks in advance!

**Comment by Tobi-De** [comment]
Did you manage to get it work ? I tried this myself, in vain

**Comment by xnardo** [comment]
> Were you able to get it to work? I tried myself, to no avail

I couldn't get it to work; it seems to require some special configurations. However, I installed a Nextcloud that seemed complete and well-structured in the usual way from CapRover. Here’s the project > https://hub.docker.com/r/linuxserver/nextcloud

I hope it solves your problem. Cheers!

**Comment by Tobi-De** [comment]
> > Were you able to get it to work? I tried myself, to no avail
> 
> I couldn't get it to work; it seems to require some special configurations. However, I installed a Nextcloud that seemed complete and well-structured in the usual way from CapRover. Here’s the project > https://hub.docker.com/r/linuxserver/nextcloud
> 
> I hope it solves your problem. Cheers!

Is this the AIO version?

**Comment by Tobi-De** [comment]
Oh wow, thanks so much for this @denis-roy! I didn't expect it—this could definitely be a blog post. Great work, really nice step by step guide!
