### ISSUE TITLE
"caprover deploy -t ./deploy.tar" not working

### ISSUE THREAD

**Issue by gangal86** [caprover/caprover#2078]
I need to deploy a static web application. I'm following this guide: [https://caprover.com/docs/recipe-deploy-create-react-app.html](https://caprover.com/docs/recipe-deploy-create-react-app.html)

I'm creating the archive with this command:
`tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./dist/*
`

Then, I'm trying to deploy with:
`caprover deploy -t ./deploy.tar
`

But there's no response in the console. The deployment doesn't happen.

**If I upload the deploy.tar archive through the Caprover web interface, it works fine.**

However, I need the deployment to work from the console.

What could be the problem? Any help would be appreciated!

![2024-06-18_11-17-11](https://github.com/caprover/caprover/assets/20575239/8589d41f-e89c-4475-a9e2-5822801629a7)

**Comment by githubsaturn** [comment]
Are you running on Windows by any chance?

**Comment by gangal86** [comment]
> Are you running on Windows by any chance?

Yes) on Windows 10

**Comment by githubsaturn** [comment]
This is an outstanding issue with Windows shell:
Duplicate of https://github.com/caprover/caprover-cli/issues/40#issuecomment-536588162


I don't have a windows machine, but if you do, feel free to open a pull request to fix. 

PS: some people are saying pressing ENTER twice solves the issue.
