### ISSUE TITLE
Webhook Token too long for Github

### ISSUE THREAD

**Issue by JustinGuese** [caprover/caprover#2079]
Reopening https://github.com/caprover/caprover/issues/2072
as this is a Github limitation

**Comment by JustinGuese** [comment]
is there a way to reduce the size of the token= param in the webhook?

**Comment by githubsaturn** [comment]
I just tried the webhook on github and it doesn't have the length limitation. What issue are you facing?

![image](https://github.com/caprover/caprover/assets/10582082/fd19dcec-5ec2-48e2-bbf7-c7c942116110)
![image](https://github.com/caprover/caprover/assets/10582082/a64ce13d-80aa-467d-a195-62bf9ac40fa8)

**Comment by JustinGuese** [comment]
and your request url is longer than 255 characters?
bc mine gets cut off after 255 characters and cap rover returns the before mentioned 502 "jwt corrupted"

<img width="792" alt="image" src="https://github.com/caprover/caprover/assets/9588843/2afcd1ac-1a19-4bef-ae1f-547d587dda83">

how is this jwt generated? it has nothing to do with the private key I'm pasting into the GitHub repo section, right?

**Comment by githubsaturn** [comment]
Ahhh I was looking at a test instance. I just tried a production one and it failed.... :( 
I don't know when they changed this as it used to work in the past... :facepalm: 

I'll see if we can have a workaround here. I have a few options and I'll update this thread once I have more info.

**Comment by JustinGuese** [comment]
at least a yay for replication :p thanks! maybe the token can be shortened as it's only used by cap rover anyways? or hashed again?

**Comment by githubsaturn** [comment]
Yea this is surely a bug on their end. 

Token shortening requires some non trivial data store schema design. But I just found a temporary solution for this!!

- Create a new app on your CapRover instance (just a empty app)
- Enable HTTPS for the app
- Go to the HTTP Settings of the app and find this line:
```
set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;
```
- Right below this line, add this block
```

        location /mywebhookforapp1 {
            proxy_pass <YOUR WEBHOOK URL>;
           # the semicolon at the end of the URL is important
        }
```
- Now on github, change your webhook URL to `https://youremptyapp.your.domain.com/mywebhookforapp1

**Comment by Boscop** [comment]
It worked for me today with a long token, so I guess GitHub resolved this issue, so this issue can be closed (?)

**Comment by githubsaturn** [comment]
Thanks! Glad that Github got it sorted out! Technically there shouldn't be any limit to the size of URLs, but at very least, [2000 chars](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) is the bare minimum they should support. Glad they fixed it!

**Comment by rburchell** [comment]
This is still mentioned in the docs: https://caprover.com/docs/deployment-methods.html

That could perhaps do with removing, if this is no longer a problem?

**Comment by githubsaturn** [comment]
Removed! Thanks for the reminder.
