### ISSUE TITLE
Feature Request: Ability to Limit Container Bandwidth Usage (or Docker-TC?)

### ISSUE THREAD

**Issue by amirsaam** [caprover/caprover#2082]
**Is your feature request related to a problem? Please describe.**
Some data-centres provide limited bandwidth to VPS or Server, for such problems we need to limit the bandwidth available to certain containers in order to avoid their limitations.

**Describe the solution you'd like**
It would be lovely if we able to apply such limit as like CPU and Ram built-in with Docker but while it is not possible we need to implement solutions like [Docker-TC](https://github.com/lukaszlach/docker-tc)

**Describe alternatives you've considered**
Alternative would be like we install Docker-TC manually and give CapRover a way to communicate with it in the UI.

**Comment by amirsaam** [comment]
Looks like we can actually achieve using Docker-TC in CapRover already with the following snippet, if I am wrong please correct me.

Docker-TC command usage example in CLI:
```bash
docker run -it \
	--net test-net \
	--label "com.docker-tc.enabled=1" \
	--label "com.docker-tc.limit=1mbps" \
	--label "com.docker-tc.delay=100ms" \
	--label "com.docker-tc.loss=50%" \
	--label "com.docker-tc.duplicate=50%" \
	--label "com.docker-tc.corrupt=10%" \
	busybox \
	ping google.com
```

Using the labels from Docker-TC for CapRover existing app in Service Update Override:
```bash
TaskTemplate:
  ContainerSpec:
    Labels:
      com.docker-tc.enabled: 1
      com.docker-tc.limit: 1mbps
      com.docker-tc.delay: 100ms
      com.docker-tc.loss: 50%
      com.docker-tc.duplicate: 50%
      com.docker-tc.corrupt: 10%
```

**Comment by githubsaturn** [comment]
Mapped ports are available on the mesh network. The problem is that CapRover already manages the overlay mesh network for you. And you can't have two overlay mesh networks on the same container (because obviously they could conflict when it comes to port mapping)

**Comment by amirsaam** [comment]
@githubsaturn So, can this feature get implemented into CapRover?

**Comment by githubsaturn** [comment]
If docker supports it natively, yes, technically possible. But looks like there's no native support for docker swarm services

**Comment by amirsaam** [comment]
@githubsaturn I think it is still possible to merge Docker-TC into captain network overlay, but unfortunately I have no knowledge about web-dev.

**Comment by amirsaam** [comment]
Any update?

**Comment by githubsaturn** [comment]
Not sure what update you're looking for. This is a question for Docker-TC project. 

Docker-TC claims that it supports Docker swarm. If it does, then it should work with CapRover as well.

https://github.com/lukaszlach/docker-tc?tab=readme-ov-file#deploy-on-swarm


CapRover simply uses `captain-overlay-network` so that containers can communicate with each other. If Docker-TC can automatically take over this, and edits the network, then it should work with CapRover. But regardless, there is nothing CapRover specific about this.

**Comment by thgh** [comment]
It's natively available in Docker Swarm:
https://docs.docker.com/engine/api/v1.46/#tag/Service/operation/ServiceCreate
`TaskTemplate.Resources.Limits.MemoryBytes`

e.g. in [hivepanel](https://github.com/thgh/hivepanel)
<img width="362" alt="Screenshot 2024-07-24 at 09 44 34" src="https://github.com/user-attachments/assets/51b5cd8e-08b2-464d-94a0-57ccb628fbf2">
