### ISSUE TITLE
[Deployment Issue] How to Deploy an App with Git LFS Resources

### ISSUE THREAD

**Issue by Enferium** [caprover/caprover#2084]
Hello !

I'm deploying an app with Git LFS assets inside the repo, but it seems that LFS isn't working. 
I'm building directly from a Git repository with SSH key authentication, and I do not find LFS-stored files in the resulting Docker image.

How do you enable Git LFS when building an app?

I've tried to enable it directly on the host, but I think everything happens inside a container.

**Comment by githubsaturn** [comment]
Correct, the base docker image is not using the host git. It has its own. You can extend the image and enable it, but the easier approach is to not use git as your deployment method. Move to CI/CD if you're using LFS.
