### ISSUE TITLE
WordPress Deployment Config

### ISSUE THREAD

**Issue by cueup** [caprover/caprover#2087]
Is there an image version for WP that works best with caprover?

I've just deployed by WP site using image 6.5.5

the site works  at the caprover server domain e.g. wpsite.myserver.com

but when I add connect my domain and enable https then visit the domain, it keeps redirecting to above domain and gives the message nothing is here. 

The deployment logs gives this error: **apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.1.57. Set the 'ServerName' directive globally to suppress this message**

@githubsaturn any idea? Would below be the fix or is something else going on?

https://askubuntu.com/questions/454497/apache2-could-not-reliably-determine-the-servers-fully-qualified-domain-name

**Comment by githubsaturn** [comment]
Redirect is a wordpress feature. See this related issue: https://github.com/caprover/caprover/issues/559

* Deploy Wordpress and make sure it works at wpsite.myserver.com
* Add a custom domain (don't enable redirect on CapRover)
* Login to WordPress, go to Settings and change the URL accordingly.
* Confirm the new URL works.
* Enable HTTPS and done.

![image](https://github.com/caprover/caprover/assets/10582082/04b5ce3e-1acc-45b7-8725-5961977634a3)

**Comment by githubsaturn** [comment]
Let me know if this doesn't resolve the issue and I'll reopen the thread.

**Comment by cueup** [comment]
Thanks @githubsaturn - thats worked.

However, when I set the WWW CNAME in my DNS to wpsite.myserver.com it doesn't got to the root domain it just say nothing here.
