### ISSUE TITLE
customized 502 error page

### ISSUE THREAD

**Issue by psanghvi17** [caprover/caprover#2090]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
Customized page has a CSS file and a few images, which does not render.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

**Comment by githubsaturn** [comment]
This section is empty "Steps to reproduce the problem"

Can you please provide more details?

**Comment by githubsaturn** [comment]
Closed due to inactivity.
