### ISSUE TITLE
Caprover restarts itself when app build fails

### ISSUE THREAD

**Issue by ugurrdemirel** [caprover/caprover#2092]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
When I deploy a new version of my application named “x” with CapRover, and this deployment fails within Docker (specifically, an error occurs during the Next.js build), CapRover and all related applications (x, y, z) restart themselves. In this situation, if I am on the CapRover web interface, I see a “Something bad happened” error and it asks me to log in again. Because all applications restart, I experience downtime in all my other apps (x, y, z) for a moment. As far as I know all apps deployed with caprover are independent but this issue happens somehow.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1. Deploy app using Github Actions with `caprover/deploy-from-github@v1.0.1`
2. Docker image build fails because of app's build step
3. Issue happens

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

```
Linux caprover 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
               total        used        free      shared  buff/cache   available
Mem:           125Gi       3.2Gi       4.3Gi        20Mi       118Gi       121Gi
Swap:          8.0Gi       3.0Mi       8.0Gi
```

**Comment by githubsaturn** [comment]
What's your experiencing is very likely due to resources constraints on your server. The build process is a very intensive operation for CPU and RAM. What is happening is that your server runs out of resources and reboots. 

You should look into building your application on a CI CD platform. 
https://caprover.com/docs/ci-cd-integration.html
