### ISSUE TITLE
An error occurred in the root domain certificate

### ISSUE THREAD

**Issue by allmors** [caprover/caprover#2095]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

The certificate of my root domain suddenly expired and became the certificate of caprover.com.
![image](https://github.com/user-attachments/assets/80270540-beff-45b6-a020-9e1693deb9a7)

But I checked and found that my root domain certificate has not expired.
![image](https://github.com/user-attachments/assets/ab75669e-8997-466d-9594-1c86e5c89278)

In addition, I tried restarting caprover, but to no avail

Does anyone know how to fix it?
My other applications deployed based on caprover are normal, but there is a problem with the certificate of the root application.

**Comment by githubsaturn** [comment]
Your URL is wrong, it should start with captain. Not caprover.
