### ISSUE TITLE
[Question] Setting sysctl values

### ISSUE THREAD

**Issue by eni9889** [caprover/caprover#2098]
First off thank you so much for this amazing tool. It has made my life so much simpler.

I am running postgres for my servers but I need to set sysctl to the following: 

net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 5

And I have done this on the host up it looks like the running docker containers do not pick up this change. How can I set this for the containers as well?

**Comment by githubsaturn** [comment]
Hi @eni9889 and thanks for your message!

The issue you're facing is not specific to CapRover. This is how Docker works. Specifically in your case, you can try running this. It may or may not work. Docker swarm networking completely bypasses the host network namespace, and uses its own.

```
docker service update \
--sysctl-add net.ipv4.tcp_keepalive_time=60 \
--sysctl-add net.ipv4.tcp_keepalive_intvl=10 \
--sysctl-add net.ipv4.tcp_keepalive_probes=5 \
srv-captain--yourpostgressappname
``
