### ISSUE TITLE
Chatwoot - SSL Certificate Invalid and "Nothing here yet :/" Message for Password Reset Link

### ISSUE THREAD

**Issue by hnmendes** [caprover/caprover#2099]
### Description
I've deployed the Chatwoot application using CapRover. The setup seems correct, and HTTPS is functioning. However, when a new agent receives an email to set up their account and clicks on the link, they are redirected to a page showing "Nothing here yet :/" with an invalid SSL certificate warning.

### Steps to Reproduce
1. Deploy Chatwoot on CapRover.
2. Ensure that HTTPS is set up and functioning properly.
3. Invite a new agent to create an account, which sends an email.
4. Click on the password reset link in the email, e.g., https://mydomain.com/app/auth/password/edit?reset_password_token=userToken

### Expected Behavior
The user should be redirected to a secure page where they can reset their password without any SSL certificate errors.

### Actual Behavior
The user is redirected to a page displaying "Nothing here yet :/" and a browser warning about an invalid SSL certificate.

### NGINX Configuration
Here is my current NGINX configuration for mydomain.com:

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;
        underscores_in_headers on;
        server_name  <%-s.publicDomain%>;

        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

        <%
        if (s.redirectToPath) {
        %>
            return 302 <%-s.redirectToPath%>;
        <%
        } else {
        %>

            <%
            if (s.httpBasicAuthPath) {
            %>
                auth_basic           "Restricted Access";
                auth_basic_user_file <%-s.httpBasicAuthPath%>; 
            <%
            }
            %>

                proxy_pass $upstream;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

            <%
            if (s.websocketSupport) {
            %>
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
            <%
            }
            %>

        <%
        }
        %>

        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
            root <%-s.customErrorPagesDirectory%>;
            internal;
        }
}
```

### Environment Details
CapRover version: 1.11.1
Chatwoot version: 3.11.0
Server OS: Ubuntu 22.04

### Additional Information
- SSL certificate for mydomain.com was obtained through Let's Encrypt.
- The certificate appears to be correctly configured but results in an invalid certificate error when accessing the reset password link.
- No apparent errors in the NGINX logs or Chatwoot logs relevant to this issue.

### Request for Help
Any guidance on resolving the SSL certificate issue and the "Nothing here yet :/" message when accessing the password reset link would be greatly appreciated.

**Comment by githubsaturn** [comment]
Hi @hnmendes  - one click apps are maintained by the community and not part the core service. 
See here: https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md

![image](https://github.com/user-attachments/assets/ea0a0516-35ea-431b-b923-4a7bdb941080)

**Comment by githubsaturn** [comment]
In this case, you can comment here: https://github.com/caprover/one-click-apps/pull/974
