### ISSUE TITLE
Run locally with another domain than captain.localhost 

### ISSUE THREAD

**Issue by uebmaster** [caprover/caprover#2102]
I've installed caprover locally, but i want to know if is posible change the domain "captain.localhost" to another different, in my work we have a SSL Certicate from Verisign and i want to use it locally, editing my /etc/hosts to pointing at caprover server.

Is this posible?

Thanks in advance.

PS: Sorry for my bad english.

**Comment by githubsaturn** [comment]
Yes, surely you can. After installing CapRover, you can change the domain name on dashboard


![image](https://github.com/user-attachments/assets/951825c7-272e-48b1-94f4-f7ee2b24b795)
