### ISSUE TITLE
Update Readme for Zero Downtime Deployment

### ISSUE THREAD

**Issue by eni9889** [caprover/caprover#2104]
By adding the following to the service update you can have Zero Downtime Deployments:

```
{
  "UpdateConfig": {
    "FailureAction": "rollback",
    "Order": "start-first",
    "Delay": 10000000000
  },
  "TaskTemplate": {
    "ContainerSpec": {
      "HealthCheck": {
        "StartPeriod": 5000000000,
        "Timeout" : 60000000000,
        "Interval" : 5000000000,
        "Retries" : 30,
        "Test": [
          "CMD",
          "curl",
          "--fail",
          "http://0.0.0.0:3000/healthcheck"
        ]
      },
      "Sysctls": {
        "net.ipv4.tcp_keepalive_time": "60",
        "net.ipv4.tcp_keepalive_intvl": "10",
        "net.ipv4.tcp_keepalive_probes": "5"
      }
    },
    "Resources": {
      "Limits": {
        "MemoryBytes": 2147483648,
        "NanoCPUs": 1000000000
      }
    }
  }
}
```

Obviously the health-check path must match your own health-check path.

**Comment by githubsaturn** [comment]
Thanks for the snippet. You actually don't need any of these. The only one that matters is the Healthcheck - that should/can be in your Dockerfile. 


Unfortunately, there is no one-size-fits all solution. For example, you're assuming there is a /healthcheck endpoint and it's running on port 3000 which is not always the case, sometimes health check requires different configs: https://github.com/caprover/caprover/discussions/1287#discussioncomment-6486935. Also you're assuming curl is installed, which is not always the case, example: https://github.com/caprover/caprover/issues/661#issuecomment-1975026104

**Comment by githubsaturn** [comment]
Sysctls and Resources in your JSON aren't really needed for zero downtime, they are fairly unrelated.

`UpdateConfig` is somewhat related, but CapRover automatically sets that for you to `start-first` if your application is stateless.
