### ISSUE TITLE
Iran/Tehran timezone missing from Disk Cleanup scheduler

### ISSUE THREAD

**Issue by ariaieboy** [caprover/caprover#2110]
Iran/Tehran timezone missing from the Disk Cleanup scheduler

**Comment by khromov** [comment]
Not only individual cities but entire timezones are missing, for example Paris/Germany/Stockholm (GMT+0200) are missing completely. 

<img width="461" alt="Screenshot 2024-08-18 at 01 46 27" src="https://github.com/user-attachments/assets/1d714843-5f8a-45c7-b718-783da5cd245c">

**Comment by githubsaturn** [comment]
I've excluded daylight saving enabeld timezones for simplicity, but it looks like some regions only have DST enabled :man_facepalming:

**Comment by githubsaturn** [comment]
Well... live and learn...

Fixed!

**Comment by githubsaturn** [comment]
Thank for the prompt report!
