### ISSUE TITLE
[Question] Unclear upgrade instructions for 1.12.0.

### ISSUE THREAD

**Issue by stefanbohacek** [caprover/caprover#2111]
The 1.12.0 upgrade shows a note:

> Version 1.12.0 changes:
> **IMPORTANT**: this version bumps the minimum Docker API to 1.43. Please run `docker version | grep API` before upgrading your CapRover installation.

When I run `docker version | grep API`, I get:

> API version:       1.41
> API version:      1.41 (minimum version 1.12)

It is not clear whether installing the upgrade automatically updates the Docker version as needed (presumably no), and if not, which version I can safely upgrade to without breaking anything.

On https://caprover.com/docs/get-started.html it says:

> Recommended Stack: CapRover is tested on Ubuntu 20.04 and Docker 19.03.

I am currently on Docker version 20.10.9.

Could we please get some clarification on this?

Thank you!

**Comment by githubsaturn** [comment]
Thanks for the reminder to fix the minimum version on the site! Just fixed! 

Your version needs an update. More details:

You need version 25+ for your docker engine. Docker has weird versioning! There is a Docker API version and Docker engine version. You have:
- Docker engine: 20.10.9
- Docker API: 1.41

CapRover needs 1.43 which I believe is available in 25.0 onwards. To update your docker installation, just run the typical linux update commands, e.g. for Ubuntu:
```
apt update
apt upgrade
```

**Comment by stefanbohacek** [comment]
Perfect, thank you so much!

And thank you for the fast response!
