### ISSUE TITLE
latest update prevents apps log console from being resized

### ISSUE THREAD

**Issue by erickythierry** [caprover/caprover#2112]
I updated caprover to version 1.12.0 which adds, among other things, the option to search app logs. I found it very useful and a valid update. However, now I can't resize the size of the log box.

I have other servers that are on the previous version and I can still resize

Could it be a bug in my installation or a bug in the new version after this component update?

**Comment by githubsaturn** [comment]
Thanks for the report. It's surely a bug and wasn't intended :disappointed:

**Comment by erickythierry** [comment]
> Thanks for the report. It's surely a bug and wasn't intended 😞

Thanks for the quick response. Could you tell me how I can update? I saw that the resize correction was made.

**Comment by githubsaturn** [comment]
You can wait for the next version, or you can move to edge version if you really want this bug fixed as soon as possible.

https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version
