### ISSUE TITLE
How to access an app from behind firewall only?

### ISSUE THREAD

**Issue by VictorioBerra** [caprover/caprover#2113]
I used One Click to install Adminer, I would like to access Adminer from my development PC only using Tailscale. I added a port mapping and it works great, I can do hostname:1234 and get to Adminer.

Is there a way to remove it from NGINX? I assume maybe I can edit the NGNIX config to hide the service from the internet. I am not an NGINX expert though.

What config do I need to not break NGINX and hide Adminer from the internet?

**Comment by githubsaturn** [comment]
![image](https://github.com/user-attachments/assets/892f8889-6325-4ebb-9d77-4247ea018bcb)
