### ISSUE TITLE
Bumping the version of a One Click deployment?

### ISSUE THREAD

**Issue by VictorioBerra** [caprover/caprover#2114]
I installed KeyCloak via One Click, it asked me what version of KeyCloak I wanted so I put "25.0". When done it created a KeyCloak container and keycloak-db Postgres container.

In the future, if KeyCloak releases v26, how do I bump my image version to 26? I want to keep all my data and have KeyCloak apply its migrations against the existing DB. I just want to make sure I am not locked-in when I use OneClick otherwise I might as well be using CapRovers other deployment options so I have more control.

**Comment by githubsaturn** [comment]
One click apps are no different than using other deployment options except they automate the creation process for you. 

With KeyCloak specifically, it's one of the most complex one click apps with a customized Dockerfile:
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/keycloak.yml#L24-L39

That means a simple image update won't work. 

There is a lot more details here:
https://caprover.com/docs/one-click-apps.html#upgrading-one-click-apps

**Comment by githubsaturn** [comment]
Looking at their official docs, it looks like creating customized image isn't really necessary.... 
https://www.keycloak.org/server/containers

I'm not sure why the contributor who added keycloak decided to go down the complex route (there might be valid reasons behind it). But if you want feel free to open a PR and simplify the KeyClock one click app definition and use the prebuilt image:
https://www.keycloak.org/getting-started/getting-started-docker

**Comment by VictorioBerra** [comment]
@githubsaturn  yeah it seems unnecessarily complex. Also I am trying to follow these best practices and struggling:

https://www.keycloak.org/server/reverseproxy

Basically I want to go to hostname:8080/admin on my dev machine (with Tailscale) to access the admin  UI and then id edit the NGINX config to deny access to /admin and other paths outlined in the docs.

The problem im having is hostname:8080 is redirecting to keycloak.server.domain.com:80

I cannot figure out what is causing the redirect since I am trying to access an exposed port and should not be going through NGINX...

**Comment by githubsaturn** [comment]
redirect is very likely happening at the application layer (keycloak)
