### ISSUE TITLE
Is it possible to specify run arguments without a custom dockerfile?

### ISSUE THREAD

**Issue by VictorioBerra** [caprover/caprover#2115]
I see I can deploy an image, I can set env vars, I have almost all I need except I cant specify run arguments for the image.

Do I have to use a custom docker file to do that?

**Comment by githubsaturn** [comment]
What do you mean by arguments? Are you referring to ARG in Dockerfile, or arguments that you can pass to CMD?

Can you give me an example?

**Comment by VictorioBerra** [comment]
@githubsaturn Something like this:

![image](https://github.com/user-attachments/assets/80d933b1-1368-4059-a228-b2cc6bfaf08a)

Arguments could be: `quay.io/keycloak/keycloak:25.0.2 start-dev`

**Comment by githubsaturn** [comment]
oh, `start-dev` is the command override. You can pass that in your docker compose one click app, here is an example:

https://docs.docker.com/compose/compose-file/05-services/#command
