### ISSUE TITLE
Missing timezone setting and change apps date format

### ISSUE THREAD

**Issue by wojtishek** [caprover/caprover#2118]
Hey there, 

I hope it's the right type of question here :)

After last update I've found two issues:
- I am unable to find Europe/Prague in the timezone settings for cron
- app last deployed date format changed do mm/dd/yy with 12-hour format, I'm pretty sure Caprover respected locale settings before update

Is this issue or am I missing something?
thanks in advance

<img width="227" alt="Snímek obrazovky 2024-08-20 v 18 09 07" src="https://github.com/user-attachments/assets/18740131-f9a3-4d61-bcb6-6cf2c9b88184">
<img width="319" alt="Snímek obrazovky 2024-08-20 v 18 08 58" src="https://github.com/user-attachments/assets/7c2f6df5-87c6-494e-ad2c-20766320cefa">

**Comment by wojtishek** [comment]
ahh, sry, timezone setting are solved here https://github.com/caprover/caprover/issues/2110

**Comment by githubsaturn** [comment]
Yes, timezone issue is fixed. And the time was changed to be slightly shorter (changed YYYY to YY, and HHMMSS to HHMM

**Comment by wojtishek** [comment]
@githubsaturn thanks for reply.

About the time, I am pretty sure the date format was totally different. I've started new instance with 1.11.1 version and the format is respecting my locale settings, as can be seen on attached image.

![Snímek obrazovky 2024-08-21 v 9 34 34](https://github.com/user-attachments/assets/464830fd-94e2-4ee9-9b54-dd3dc5b41c6e)

**Comment by wojtishek** [comment]
I've tried edge version of Caprover, and timezone selection has strange behavior, one gif per thousand words 😄
![2024-08-21 21 07 30](https://github.com/user-attachments/assets/fd095058-d2b4-44f1-90c5-c087a4028092)

**Comment by githubsaturn** [comment]
@wojtishek - yes, previously it was using the locale from the browser, now it's hardcoded:
https://github.com/caprover/caprover-frontend/commit/89516709d5462c38554cae5b62845432adf3f88a#diff-2ba5420178d10856faa0cf75fdd3067012468feb88949c8104de5fd794c60179


I see your point, but I'm not sure if going back to the old generic browser format is the best option either, because it was just ugly with the seconds and long format date... I wish Moment had a way to respect the ordering for the locale.

**Comment by githubsaturn** [comment]
Regarding the autofill, yea that looks strange! I'll look into it.

**Comment by githubsaturn** [comment]
Oh well... there is a reason it's called edge and not a stable version :grin: 

Thanks for the report. It's fixed. You can pull the edge image again and check again.
