### ISSUE TITLE
Delete the app-backend/dist folder from git and add it to .gitignore

### ISSUE THREAD

**Issue by mathiasm74** [caprover/caprover#212]
Files that are the product of the build process should not be version-controlled, as these are recreated on demand from source by running the build scripts.

Also add .DS_Store to .gitignore to keep Mac-owners from polluting the repo.

**Comment by githubsaturn** [comment]
Removing build artifacts requires us to change the deploy to docker hub script: https://github.com/githubsaturn/captainduckduck/blob/master/app-backend/deploy-to-docker-hub.js
