### ISSUE TITLE
[Deployment Issue]  I can't access the caprover domain

### ISSUE THREAD

**Issue by DaniHRE** [caprover/caprover#2122]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I can't access the caprover domain captain.hcdevs.online

only by captain.hcdevs.online:3000

**Comment by githubsaturn** [comment]
Have you set up your instance? Use:
```
caprover serversetup
```

**Comment by DaniHRE** [comment]
Yes, I ran this command and filled in everything that was requested.

![image](https://github.com/user-attachments/assets/9e2e0125-b25d-4135-98ca-38cb303ff340)
![image](https://github.com/user-attachments/assets/4333958e-2356-4f40-a9b3-2308efb4cad6)

I didn't do anything other than upload caprover and configure my domain to point to caprover

**Comment by githubsaturn** [comment]
There's no public DNS for this domain:

https://mxtoolbox.com/supertool3?abt_id=AB-631B&abt_var=Variation&run=toolpage&action=a%3acaptain.hcdeys.online

**Comment by githubsaturn** [comment]
Do you have a local DNS server?

**Comment by DaniHRE** [comment]
I Have a cloudflare dns

**Comment by githubsaturn** [comment]
It doesn't work as you can see in the link above. You need to have DNS record to point the domain

**Comment by githubsaturn** [comment]
Oh wait. There's a typo

**Comment by githubsaturn** [comment]
So it looks like your port forwarding isn't working for port 80. Either there is a misconfiguration on your end, or your ISP does not allow incoming port 80.

**Comment by DaniHRE** [comment]
Ill try to check my port fowarding settings...

**Comment by DaniHRE** [comment]
The problem is related to my ISP, blocks the 80 and 443 ports.
Thats the reason why when i try to access captain.hcdevs.online:3000 it works. cause por 3000 is allowed by ISP

**Comment by DaniHRE** [comment]
I checked with my ISP and they said I can only have port 80 or 443 with a business plan or a plan that has a Fixed IP.
Is there a workaround to be able to use the caprover with a tunnel, maybe a cloudflare tunnel or something like that?
@githubsaturn

**Comment by githubsaturn** [comment]
Running on any other ports or running behind tunnels is not officially supported. Some people hacked pieces to make it work. But it's fragile and not supported.
