### ISSUE TITLE
[Deployment Issue] what is appending captain to my webseite when deployed using github workflow

### ISSUE THREAD

**Issue by sanfx** [caprover/caprover#2126]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

while the github workflow works , something is prefixing the **captain** before the top level domain.

![Screenshot 2024-08-28 97de506](https://github.com/user-attachments/assets/f7df93f0-8db7-453a-8179-d68613982d7b)

If applicable, content of `captain-definition` file:
```
{
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

Steps to reproduce the problem:

Use this `captain-definition` file

use this dockerfile for testing:

```
FROM python:3.10-slim
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code
RUN pip3 install -r requirements.txt
ADD . /code
EXPOSE 8090
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["sh", "entrypoint.sh"]

```

Output of the following command on your server:

```
Linux caprover1111onubuntu2004-s-1vcpu-1gb-blr1-01 5.4.0-162-generic #179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
              total        used        free      shared  buff/cache   available
Mem:          965Mi       472Mi       132Mi       1.0Mi       360Mi       333Mi
Swap:            0B          0B          0B

```

**Comment by githubsaturn** [comment]
Adding `captain.` is expected.

For example, for `server.demo.caprover.com` root domain, the app sits at `captain.server.demo.caprover.com`
[captain.server.demo.caprover.com](https://captain.server.demo.caprover.com)

**Comment by sanfx** [comment]
yes I go this sorted out, and the github actions work fine. however and do not error.
however in the caprover I do not see the commit hash the way I see when I use caprover deploy cli.

Although the github actions seems to work fine I do not see the app updating .

**Comment by githubsaturn** [comment]
Hmmm can you share the screenshots of the last lines of your Github Action and a screenshot of your app build history?
