### ISSUE TITLE
Log Search filter crash on invalid Regex

### ISSUE THREAD

**Issue by cpecorari** [caprover/caprover#2128]
Hi,

Updated to latest version 1.12.0, thanks for the great upgrades ! 
Keep getting few issues here and there, waiting for next update (like un-resizable log window).

Right now having some kind of bug i could not find already in github issues :
When filtering logs with a Regexp, sometimes malformed, it does crash the UI. 
I understand we should not type in malformed Regexp, but hey, we are humans... And sometimes typing the Regex is necessarily wrong for 1 or 2 chars before the Regex is completely typed in.

For example just try `/*/` will crash.

**Comment by githubsaturn** [comment]
Thanks!
