### ISSUE TITLE
[Deployment Issue] After deploying a new version of Strapi on CapRover, the old version is still being displayed

### ISSUE THREAD

**Issue by Hertak** [caprover/caprover#2136]
I am using Strapi with CapRover for deployment, and everything works fine initially. However, when I update my Strapi app locally and deploy the new version with the cli on CapRover, the website still shows the old version, even though the deployment appears successful.

Here’s what I have tried so far:

Cleared the browser cache and tested in incognito mode.
Restarted the app from the CapRover dashboard.
Checked the CapRover logs for any errors.
Verified the deployment process, ensuring that the new image replaces the old one.
Checked if Strapi caching is causing the issue, but I’m not using any cache-related middleware or plugins.
Confirmed that the npm run build command was executed to build the new version before deployment.
Despite these steps, the old version of the site remains visible after deploying the new one. What could be causing this issue, and how can I resolve it?

Any advice would be appreciated!

**Comment by githubsaturn** [comment]
Not sure how Strapi works under the hood. But are you by any chance mapping a persistent directory where the source code reside? In that case that directory will be overridden by whatever is on the disk.

**Comment by edolix** [comment]
@Hertak i'm deploying several Strapi apps on CapRover and i never had this issue. Like @githubsaturn said, double check persistent directories/volumes making sure to not override the source code 👍

**Comment by Hertak** [comment]
Thanks for response, m bad. I make the persistent directory Root and i need only uploads, thanks

**Comment by githubsaturn** [comment]
Glad it worked out! 

@edolix  - thanks for the help!
