### ISSUE TITLE
Deploy from GitHub with token instead of username/password?

### ISSUE THREAD

**Issue by Boscop** [caprover/caprover#2140]
Would it be possible to deploy from GitHub with a token instead of username/password?
So that the token has limited scopes, e.g. read-only, and **only** on the repo of the app that should be deployed?
It would be more secure because if someone gets ahold of the token, they can only read this one repo, not modify it, and can't do any changes to the GH account or read other private repos.

This can be implemented similar to how shortcut.com's GitHub integration works, it also only needs read-only access and automatically updates based on triggers like pushing to a branch.

**Comment by Boscop** [comment]
Ah, I found this, that seems to do what I want :)
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys

---

Previously I only saw this: https://caprover.com/docs/best-practices.html#use-service-accounts-for-git
> It is always a good practice to create a service account (bot account) on GitHub and etc, and give that account specific permission (read only) to certain repositories only. Such that if that account was compromised, your main owner account remains intact and you can remove the compromised account from the repo.

I understood this to mean that I'd have to create a fully separate GH user account, which would be a more cumbersome solution..

**Comment by githubsaturn** [comment]
Yes, deploy keys are the best method.
