### ISSUE TITLE
Matomo One-click app fails with Failed: Error: Push failed: Error: (HTTP code 400) bad parameter - invalid reference format

### ISSUE THREAD

**Issue by Boscop** [caprover/caprover#2142]
What is the problem?
<img width="714" alt="image" src="https://github.com/user-attachments/assets/a05c7e63-37ee-468b-8408-751b7300e622">

Steps to reproduce the problem:
One-click deploy Matomo:

<img width="531" alt="image" src="https://github.com/user-attachments/assets/ae391f0d-832a-43e1-8083-8e9e302bbb49">

I get:
> Failed: Error: Push failed: Error: (HTTP code 400) bad parameter - invalid reference format

Output of the following command on your server:
```
uname -a && lsb_release -a && free -h
```
```
$ uname -a && lsb_release -a && free -h
Linux amd-instance 6.8.0-1005-oracle #5-Ubuntu SMP Sat Apr 20 01:13:25 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
               total        used        free      shared  buff/cache   available
Mem:           958Mi       518Mi        74Mi       540Ki       523Mi       440Mi
Swap:          2.0Gi       219Mi       1.8Gi
```

**Comment by githubsaturn** [comment]
Do you have a Docker registry set up? Is it a 3rd party registry or selfhosted?

Try disabling it and deploy again.

**Comment by Boscop** [comment]
Thanks for your fast reply :)

Yes, I have the [GitHub package registry as remote registry, but that's for being able to push my app to CapRover via GH action](https://github.com/marketplace/actions/build-docker-and-deploy-to-caprover#unauthorized-error-message-on-caprover) (because building on the CapRover VM takes 1h 15m to build, and in a GH runner it only takes 12m), but this registry should have no bearing on one-click apps like Matomo, because they should just be pulled, never pushed to my GH registry, right?

<img width="664" alt="image" src="https://github.com/user-attachments/assets/64d70c60-59ab-4bce-bdf6-066e627ed259">

What should I disable, the GitHub registry?

**Comment by githubsaturn** [comment]
By default when you add a registry, it'll be used to push images to as well. 

In the same section that you screenshotted, you should see a default push registry, and that's where you should select **disabled**.

**Comment by Boscop** [comment]
Ah, I didn't have to remove the registry to make it work, I just had to disable push to it:

<img width="390" alt="image" src="https://github.com/user-attachments/assets/94942fb5-8fa6-411e-a5ca-3bb1a7a00021">

Now Matomo was deployed. 


But when I visit its site, I get `NGINX 502 Error :/`, and in app logs, I see:
```
2024-09-14T16:24:06.949195555Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.1.39. Set the 'ServerName' directive globally to suppress this message
2024-09-14T16:24:07.012013738Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.1.39. Set the 'ServerName' directive globally to suppress this message
2024-09-14T16:24:07.198826963Z [Sat Sep 14 16:24:07.198677 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.23 configured -- resuming normal operations
2024-09-14T16:24:07.200106461Z [Sat Sep 14 16:24:07.199976 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by githubsaturn** [comment]
Now that's out of CapRover's scope. CapRover is simply an installation helper for templetized dockerfile / compose. 

One click apps are community maintained, feel free to reach out to the person who added Matomo https://github.com/caprover/one-click-apps/pull/408

Or reach out to the developers of Matomo to sort it out.

**Comment by Boscop** [comment]
Ok thanks!

Btw, Matomo works now, the issue fixed itself for some unknown reason..

But I also tried to install Windmill, and got HTTP 504 gateway timeout, any idea why that could be? :)

<img width="421" alt="image" src="https://github.com/user-attachments/assets/f11a5216-6acd-4afd-8bbd-77bdde2cb8cb">

**Comment by Boscop** [comment]
I tried again, and it failed at the last step :/

Is there a way to get more error details?

<img width="423" alt="image" src="https://github.com/user-attachments/assets/24a0f1d1-59db-4e6b-a98f-99682d5c4175">

**Comment by githubsaturn** [comment]
504 is simply a timeout. Very likely your server is being a bit slow to pull the image from the server. Not sure if the image is too large or your server has connectivity issues. You can get the detailed logs by running this:
```
docker service logs captain-captain --follow
```
