### ISSUE TITLE
Configuring CapRover behind HAProxy managed by pfSense

### ISSUE THREAD

**Issue by ahgsql** [caprover/caprover#2146]
Issue: Configuring CapRover behind HAProxy managed by pfSense
Environment

CapRover Version: 1.12
Host OS: Ubuntu Server 22.04
Router/Firewall: pfSense with HAProxy

Description
I'm experiencing difficulties in correctly configuring CapRover to work behind HAProxy managed by pfSense. While I can access the CapRover panel, there are issues with proper traffic routing and HTTPS enablement.

Current Setup

pfSense is running HAProxy for reverse proxy.
CapRover is installed on an Ubuntu Server VM (IP: 10.0.0.200).
Ports 80 and 443 are forwarded from the router to the VM.
Created acme certificates with pfSense.

![image](https://github.com/user-attachments/assets/6302975c-4435-4ce3-8b6e-aa6b3615ad29)

*.aligulec.dev was pointing to my static ip adress..

ACL:

![image](https://github.com/user-attachments/assets/6302ecc0-200d-4188-acb7-ae6c238445b4)

action:
![image](https://github.com/user-attachments/assets/86273306-d70e-4f15-905d-170d3ccba478)

WAN FRONTEND:
![image](https://github.com/user-attachments/assets/ecce5a85-6838-4d8b-9f49-a084f6bf43cb)

Main Issues

HAProxy Configuration: Unsure if the HAProxy settings in pfSense are correctly configured to route traffic to CapRover.
Ubuntu Server Configuration: The Ubuntu server with CapRover may not be properly configured to accept connections through HAProxy.
HTTPS Enablement: When trying to enable HTTPS in CapRover, Let's Encrypt fails to validate the domain.

Error Message (when enabling HTTPS)
Copy1107 : Unexpected output when enabling SSL for domain.com  with ACME Certbot
...
Detail: Invalid response from http://captain.domain.com/.well-known/acme-challenge/1veaP1HWEC4IjurrEgswAFVq3L2l6-x5CTzg5mRFuLg: 404
...
Questions

What is the correct HAProxy configuration in pfSense to properly route traffic to CapRover?
Are there any specific settings needed on the Ubuntu server to work correctly with HAProxy?
How can I ensure that the ACME challenge for Let's Encrypt is correctly handled through this setup?
Are there any known limitations or special considerations when running CapRover behind HAProxy on pfSense?

Attempted Solutions

Configured HAProxy in pfSense to forward requests to the VM's IP.
Verified that ports 80 and 443 are open and properly forwarded.
Attempted to manually test ACME challenge path accessibility.

Additional Information Needed

Are there any specific logs from pfSense or HAProxy that would be helpful to diagnose this issue?
What additional configuration details from CapRover, Ubuntu Server, or pfSense would be useful to provide?

Any guidance on correctly setting up this environment or tro

**Comment by githubsaturn** [comment]
This is really a HAProxy question not CapRover. 

Note that for CapRover to work properly you need to have ports 80 and 443 exposed to public without any SSL termination in the middle.

**Comment by githubsaturn** [comment]
FWIW I just tried your https website and it works just fine:
![image](https://github.com/user-attachments/assets/55b50f8c-6b24-42fc-ad33-57fead6be2d6)

**Comment by ahgsql** [comment]
Strangely, today an example test app is working in between page refreshes.

Some times ıts falling nothing here yet page, and some times CSS or js files not able to load.

https://test.aligulec.dev


![ezgif-4-2e6f8c4f85.gif](https://github.com/user-attachments/assets/32dbbe68-aab9-40cb-b619-c7f224c45dfe)



Another issue: cant enable SSL for root domain, it gives an error like Certbot cant see/acme_challenge/.... Path

i am using acme certificates issued bu pfsense service menu

**Comment by ahgsql** [comment]
> This is really a HAProxy question not CapRover.
> 
> Note that for CapRover to work properly you need to have ports 80 and 443 exposed to public without any SSL termination in the middle.

How to make sure there is no ssl termination in the middle?

**Comment by githubsaturn** [comment]
This is certainly not CapRover related. Very likely you have set up your HAProxy to "load balance" and it's sending the request to different downstreams. It's quite obvious by the randomness of your set results (sometimes it works sometimes it doesn't). 


This is not related to CapRover. To make sure CapRover works properly, you need to make sure you have set up HAProxy so that it only routes to a specific node.
