### ISSUE TITLE
[Question] Caprover installation on Ubuntu 24

### ISSUE THREAD

**Issue by Jhereck** [caprover/caprover#2147]
Hi,

I tried two times to install caprover on Ubuntu 24 servers : install is fine till the https step. 

Caprover is then running in loop and did not manage to validate the cert.

I had no time to investigate and reboot the serv with ubuntu 22, but just wondering if someone else already had this pb, and maybe found a solution ? :)

Thanks !

**Comment by githubsaturn** [comment]
> Caprover is then running in loop and did not manage to validate the cert

What do you mean by this? Can you get the logs of the server while it's trying to issue the certificate to see what's going on?

```
docker service logs captain-captain --since 5m 
```

**Comment by Jhereck** [comment]
Ok just tried another time with no luck : CR is installed but i can't login for the first time.

Tried the command you give and an recurring error is appearing : "Error: (HTTP code 500) server error - Cannot kill container: 61e6b251cda654d2a3ac07bb91cec934a4dc23bb2432fb59646397819ad82817: Cannot kill container 61e6b251cda654d2a3ac07bb91cec934a4dc23bb2432fb59646397819ad82817: unknown error after kill: runc did not terminate successfully: exit status 1: unable to signal init: permission denied".

**Comment by Jhereck** [comment]
Ok found the solution : i was using an old cloud-init using docker.io package to initialize the instance, and i realize that it's an unofficial package and so not fully supported.

So just follow the docker process to uninstall it and re install docker the official way and voila : no more pb :)

Thanks for your time and work @githubsaturn and my bad for the false alert !
