### ISSUE TITLE
Enabling SSL for Apps Manually or Forcely

### ISSUE THREAD

**Issue by ahgsql** [caprover/caprover#2149]
What is the problem?

I have Caprover behind HaProxy. HaProxy and pfSense Acme is handling SSL Certificates .

Thus, i cant enable HTTPS for root domain, which ends up cant enable app https.

Error while enabling HTTPS for root domain:

1107 : Unexpected output when enabling SSL for captain.aligulec.dev with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Requesting a certificate for captain.aligulec.dev Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems: Domain: captain.aligulec.dev Type: unauthorized Detail: 85.105.184.50: Invalid response from http://captain.aligulec.dev/.well-known/acme-challenge/t8VuE_cwqcEGKiiUvW5ordUaBejy-XQ7SFvl0nfrZqs: 404 Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet. [31mSome challenges have failed.[0m Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

Some apps using origin as base url and for example, google Auth callbacks traded as "http://app.domain.com", my app works on https with no problem, but app thinks its http, not https. So my question is:

how to enable HTTPS for apps even root domain is not treated as Https?

**Comment by githubsaturn** [comment]
Hi @ahgsql  - as mentioned previously, CapRover is not designed to handle these cases. SSL should not be terminated before it reaches CapRover. 

https://github.com/caprover/caprover/issues/2146#issuecomment-2351216033


> for CapRover to work properly you need to have ports 80 and 443 exposed to public without any SSL termination in the middle.


If you want to add SSL termination, you'll be breaking this requirement, and thus it's not guaranteed to work properly.

**Comment by ahgsql** [comment]
OKAY, i got it its not bug of caprover, but i am new to pfSense and other proxy stuff. I am tired up from VDS providers and got physical server and setup it with help of friends.

I just want to ask, how to be sure there is no ssl termination in pfSense or Haproxy? My 80 and 443 is already exposed to public and my apps are working now properly. 

Some apps uses .env variables to determine public url, that case i can manually add http(S) to variable and everything works perfectly. But other apps needs to be ssl enabled even i can run that app under pfSense certificate.

**Comment by githubsaturn** [comment]
> I just want to ask, how to be sure there is no ssl termination in pfSense or Haproxy?

You just said in your first comment:
_HaProxy and pfSense Acme is handling SSL Certificates_


Handling SSL certificate is the SSL termination.
