### ISSUE TITLE
Upgrade 1.11.1 or 1.12.0 Force build fails

### ISSUE THREAD

**Issue by LBDeve** [caprover/caprover#2150]
I use Force Build with SSH to update my app.    

_What is the problem?_

After using the Install Update from with the Setting section in CR, my Force Build throws the following error:

Happens on updating any of CR versions to 1.11.x or greater.   Using the docker service update command I can go back to 1.10.1 and then it works everytime.

_If applicable, content of `captain-definition` file:_     Don't know what to include here

_Steps to reproduce the problem:_

Use the Install update or  docker service update captain-captain --image caprover/caprover:1.10.1

_Output of the following command on your server:_

```

Build started for hkw
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/hkw/11/source_files'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.  
```
Ubuntu 22.04.5 LTS
Digital Ocean 
2 AMD vCPUs/4GB RAM

**Comment by githubsaturn** [comment]
There has been some changes between those versions. 
https://github.com/caprover/caprover/compare/v1.10.1...v1.11.1#diff-6553cdfb728c78bb37938149c9e94c5296b16894aee6ef2a0c6df2773a1238ab


Can you please create a test private repository a test pair of keys to share so I can test and verify.

**Comment by LBDeve** [comment]
Love too…

 

Just not sure how to do it…

 

private repository?

 

SSH Keys?  Or API Key?

 

Sorry for my ignorance….

**Comment by githubsaturn** [comment]
Spoke to @LBDeve on Slack - turned out the issue is that the private keys are passphrase protected. Still a mystery why the old version of CapRover was able to use them (perhaps because password was just an empty string), regardless, this was a bug and not a feature. 


Separate I'll create an issue to warn the user if the passphrase is encrypted (-----BEGIN ENCRYPTED PRIVATE KEY-----)
