### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by robertsilen** [caprover/caprover#2156]
Is MariaDB supported? Any reason not to add a mention of it to the README?

**Comment by githubsaturn** [comment]
Hi @robertsilen  - Absolutely yes! 

CapRover supports all Dockerized applications! It's only a handful of applications that are listed in the readme as an example. There are over 300 one click apps that CapRover supports. On top of this, CapRover supports custom docker images (so basically anything!)

**Comment by githubsaturn** [comment]
Feel free to open a PR to add MariaDB to the list on readme!
