### ISSUE TITLE
How to serve static files? 

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#2162]
Hi there, i have read this https://caprover.com/docs/nginx-customization.html#custom-files-and-directories
but i still cannot get nginx to serve static tiles. 

what i have done: 

1. create new app
2. added text.txt to /captain/data/nginx-shared/dgmTiles/text.txt
3. changed nginx config (added this to the end of the file: 
 ```
 location /dgmTiles/ {
    autoindex on;
    alias /nginx-shared/dgmTiles/;
}
```
4. tried to access the file via: 
https://appname.domain.io/dgmTiles/text.txt

5. i get 404 Not Found- nginx, and in the log this line: 
`2024-10-14T12:30:33.617035378Z 2024/10/14 12:30:33 [error] 7#7: *1 open() "/usr/share/nginx/html/dgmTiles" failed (2: No such file or directory), client: 10.0.1.10, server: localhost, request: "GET /dgmTiles HTTP/1.0", host: "appname.domain.io"
`

so it does not find the file, but what am i doing wrong here?

**Comment by githubsaturn** [comment]
What do you see when you run this command:
```
docker exec -it $(docker ps --filter name=captain-nginx -q) ls -lah /nginx-shared/dgmTiles
```

**Comment by githubsaturn** [comment]
Ah actually just noticed it! You have a trailing `/` at the end!

Change to 
```
location /dgmTiles {
   autoindex on;
   alias /nginx-shared/dgmTiles;
}
``

Here is a proof it works: http://test-static-file.server.demo.caprover.com/dgmTiles/

**Comment by githubsaturn** [comment]
You can log in to the [demo instance](https://captain.server.demo.caprover.com/#/login) (password captain42) and check the configs:
