### ISSUE TITLE
Dates to use browser or standard format

### ISSUE THREAD

**Issue by ivnnv** [caprover/caprover#2185]
**Is your feature request related to a problem? Please describe.**
Both a feature request and a problem, deploy dates are shown in american format, which is extremely confusing for non-american people as something like
![Screenshot 2024-11-03 at 19 47 53](https://github.com/user-attachments/assets/37ec0319-adf3-48ac-80ee-edfa2eb998e9)
will read as "eleven of march of 2024", when its actually "three of november of 2024"

**Describe the solution you'd like**
This and other dates to localize using the browser configuration or just use non-opinionated standard `YYYY/MM/DD`

UPDATE: In case you were wondering, my locale is correctly set, and it correctly transforms dates coming as `YYYY/MM/DD`:
![Screenshot 2024-11-03 at 20 02 17](https://github.com/user-attachments/assets/04ef2e15-d2ec-4bbe-9b50-3c4719e2634f)

I had a quick look at the frontend and maybe moment is not doing its job well here:
https://github.com/caprover/caprover-frontend/blob/master/src/containers/global/Timestamp.tsx#L12

**Comment by githubsaturn** [comment]
What version you're on?

**Comment by ivnnv** [comment]
Hi @githubsaturn, thanks for the prompt response, Ive updated the main comment with extra context:

Im in the latest version:
```
Current Version: 1.13.1

Latest Stable Version: 1.13.1

Your CapRover is the latest version.
```

**Comment by githubsaturn** [comment]
Yes, this was supposed to fix that :/
https://github.com/caprover/caprover-frontend/commit/d4848eb4af21053799cde4f4d0c511402e7839cc

**Comment by ivnnv** [comment]
This is interesting, my system (macOS) and browser _language_ are indeed set to english as primary, but my OS date format is indeed set as `DD/MM/YYYY` (Im spanish so thats more natural for me), which seems what `Date.toLocaleString()` internally uses to make it work properly, but not moment localization shortcuts.

![Screenshot 2024-11-03 at 23 28 26](https://github.com/user-attachments/assets/c5302d99-7bfa-421f-9470-4ada46a154a3)

Is it really that long `toLocaleString()`? it seems it only adds the seconds (`03/11/2024, 23:25:07`), which could be removed.
![Screenshot 2024-11-03 at 23 38 59](https://github.com/user-attachments/assets/94599e02-b50b-4a03-b023-78b8afb47159)

**Comment by githubsaturn** [comment]
Yea, perhaps something like this could work:
```js
const date = new Date();
const options = {
  year: 'numeric',
  month: 'numeric',
  day: 'numeric',
  hour: '2-digit',
  minute: '2-digit'
};

const formattedDate = date.toLocaleString('default', options);
console.log(formattedDate);
```

**Comment by ivnnv** [comment]
https://github.com/caprover/caprover-frontend/pull/169

**Comment by githubsaturn** [comment]
Thanks!
