### ISSUE TITLE
Deploy app on custom port (app1.domain.com:8600)

### ISSUE THREAD

**Issue by karcot97** [caprover/caprover#2186]
Hi,

## Issue: Hosting an App on a Custom Port Behind a VPN with Rover

I’m working on hosting an application with Rover, and it’s running well on the default HTTP/HTTPS ports. We have deployed several apps used internally on caprover. However, my server is inside a VPN, and the typical HTTP/HTTPS ports are blocked by the firewall.

To make a new app we are building publicly accessible, I want to open a custom port, say 8600, and have my new app listen on this port to respond to requests. The goal is to enable users to access it via a URL like app.domain.com:8600. However, I’m struggling to configure CapRover to allow this setup.

Could someone guide me on configuring CapRover to handle https requests for my new app on a custom port like 8600?

Thank you for the help!

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/issues/1166#issuecomment-2430704491

The functionality only exists on the `edge` version currently. See above commnet.

**Comment by karcot97** [comment]
Hi,

thanks for responding back! But this will launch an entirely new caprover instance listening on different http/https ports. 

What I want is to have **one** caprover instance and-
1. some of the apps are served on a port that’s reserved for the users of my vpn only 
2. some of the apps that’s visible for the entire world

**Comment by githubsaturn** [comment]
That's not possible. NGINX only listens to 1 port by default. You cannot have:
```
privateapp1.domain.com
privateapp2.domain.com
// and:
app1.domain.com:8080
app2.domain.com:8080
app3.domain.com:8080
```


But you can have
```
privateapp1.domain.com
privateapp2.domain.com
// and:
app1.domain.com:8081
app2.domain.com:8082
app3.domain.com:8083
```

**Comment by karcot97** [comment]
Hi,

Yes the latter is what I want to achieve. I tried port mapping but couldn’t figure it out. Do I have to provide both the **port mapping** in the App Configs and the **container port** in the https settings pages or do I have to leave the **container port** option of the https setting page blank for this setup?

**Comment by githubsaturn** [comment]
You just need to provide port mapping in the App Config. Like this:
Just make sure your container port is the correct port that your container is listening to.

![image](https://github.com/user-attachments/assets/086d7373-9e29-44d3-b58c-16fa41564988)
