### ISSUE TITLE
No Line Wrap Allowed In Deploy Docker Textarea

### ISSUE THREAD

**Issue by ToS0** [caprover/caprover#2187]
In the UI of the latest CR version the Deploy Docker textarea includes `white-space: nowrap;` which does not allow carriage returns nor copy & paste of multi line Docker files.

**Comment by githubsaturn** [comment]
Are you using Firefox?
https://github.com/caprover/caprover/issues/2179

**Comment by ToS0** [comment]
Your are right, didn't find that one! Thanks!
