### ISSUE TITLE
[Deployment Issue] Poste.io Container shutting down every night "user initiated"

### ISSUE THREAD

**Issue by xXKynarethXx** [caprover/caprover#2191]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
I am using poste.io for deploying my mailserver stack with caprover.
When deploying plain poste.io on a fresh server without caprover, there aren't any issues.

But during runtime at night, every night at the same time, poste.io is shutting down "user initiated".

Logs:
`2024-11-11T11:00:17.192167376Z  2024-11-11T11:00:17.192252667Z  2024-11-11T11:00:17.229039323Z 2024-11-11 12:00:17 #1907(main) <9b4caf>; main; main: rspamd 3.10.1 is loading configuration, build id: release 2024-11-11T11:00:17.349399867Z [services.d] done. 2024-11-11T23:00:04.790264960Z [!] WARNING: User-initiated shutdown. 2024-11-11T23:00:04.918367451Z [cont-finish.d] executing container finish scripts... 2024-11-11T23:00:04.957664387Z [cont-finish.d] done. 2024-11-11T23:00:04.972567651Z [s6-finish] syncing disks. 2024-11-11T23:00:05.013520750Z [s6-finish] sending all processes the TERM signal. 2024-11-11T23:00:08.064003513Z [s6-finish] sending all processes the KILL signal and exiting`

I added the following preDeployScript as described in the installation process:
```
var preDeployFunction = function (captainAppObj, dockerUpdateObject) {
    return Promise.resolve()
        .then(function(){

            var ports =  dockerUpdateObject.EndpointSpec.Ports;
            if (ports)
            {
	            for (i = 0; i < ports.length; i++) { 
				  ports[i].PublishMode = 'host'
		    }
            }

            return dockerUpdateObject;
        });
};

```

`HTTPS` is turned off in the env vars.
`VIRTUAL_HOST`, `LETSENCRYPT_HOST` & `LETSENCRYPT_EMAIL` are set in env.
rDNS is also set with the same value as `VIRTUAL_HOST`, `LETSENCRYPT_HOST`.

A simple restart of the container usually fixes the problem and everything is fine (until the next night).

Steps to reproduce the problem:
- deploy poste.io with the caprover template
- wait until night time
- processes shut down with logs mentioned above

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h

Linux redacted 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:           15Gi       5,0Gi       6,4Gi        22Mi       4,2Gi        10Gi
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/blob/master/.github/ISSUE_TEMPLATE/app_issue.md 

![image](https://github.com/user-attachments/assets/f3b9c114-4fc0-44e7-822f-83517d4a5686)
