### ISSUE TITLE
2FA TOTP default displayed input for login

### ISSUE THREAD

**Issue by cpecorari** [caprover/caprover#2202]
Hey,

Great upgrades in CapRover lastly, especially in Pro version and the 2FA feature !

Just a minor feature that could really enhance my day to day use of Caprover, when i have to login to my 4 Caprover servers, i need to enter a password (even a wrong one) just to then have the OTP input appear. 
As i use a password manager that handles my OTP code generation AND input in web browser, i need to click it twice... 

A great feature would be some kind of option to have OTP input displayed by default, so a one click (or even better, a no-click-login with my password manager) !
It could be either an option in dashboard settings, or a detected required OTP for server that would display input by default.

I think i detailed enough process and this is a quite "simple" UX feature, maybe more complicated in the internals, i dont really have time to go further but would open a PR if i had more time for this, sorry !

Cheers

**Comment by githubsaturn** [comment]
Hi @cpecorari  - thanks for the feedback. The current pattern is the common practice. Pretty much all web apps use a two layer auth layer. First you have to enter your password, then you'll be prompted to enter OTP. Majority of major apps, websites use this practice to login. This is partially due to security and API design. Until you hit the login API, you wouldn't know if OTP is enabled or not.

**Comment by cpecorari** [comment]
Hi and thanks for that explanation, but i guess then we should NOT be able to enter any wrong password to display OTP input ? 
Except if that's an issue on my server, there's something wrong... Should i open a new issue ?

**Comment by cpecorari** [comment]
Bump ...

**Comment by githubsaturn** [comment]
Ah yes, that's just an addiction level of security. Using this approach, you do not give the opportunity to the attacker to know that the password is correct.

**Comment by cpecorari** [comment]
Ok thanks for this answer, but then you give an attacker the information that there is a 2FA... A bit contradictory isn't it ?

**Comment by githubsaturn** [comment]
Fair. But passwords are much more likely to be leaked. The fact that your have 2FA enabled is little to no help to the attacker. Unless I'm missing something?

**Comment by cpecorari** [comment]
No, you're right, i mean, i agree with you, i was just insisting on the fact that "default displayed OTP input" is of very little help to an attacker, which you just confirmed, but anyway, if everything's okay as it is now, lets keep it that way !
Thanks for the discussion,
Cheers :)
