### ISSUE TITLE
Preserve Data in Working Directory During Captain Deployments

### ISSUE THREAD

**Issue by himanshutecstub** [caprover/caprover#2203]
Hello,

I configured Captain for my project, and it is working fine. However, I have encountered an issue related to the working directory.

I stored some project-related data in the working directory, but when I deploy again from GitLab, Captain builds a new container, and all the previous data is lost.

**Steps to Reproduce:**
- Configure a project in Captain and deploy it.
- Save some data in the working directory of the running container.
- Trigger a new deployment

Question:
How can I save the previous data before the new container is built? Is there a way to persist data across deployments?

**Comment by githubsaturn** [comment]
https://caprover.com/docs/persistent-apps.html#persistent-apps

**Comment by himanshutecstub** [comment]
I already created APP. So how can i change that Persistent setting?

**Comment by githubsaturn** [comment]
Unfortunately due to design limitations, you can only set an app as persistent when you first create the app. You can create a new app, copy the env vars (if any), and delete the old one. If you want, you can rename the new app to the original name after you deleted the old app.
