### ISSUE TITLE
[Question] How to delete a project?

### ISSUE THREAD

**Issue by ToasterWithTheBread** [caprover/caprover#2207]
Hey guys, just reinstalled CapRover after taking a hiatus and using Proxmox, I see projects were added and I created a few just to mess with them, but I don't see a button to delete the projects? Thanks in advance.

**Comment by Lxcasx** [comment]
Hey,

You must click on the list icon at the top right of the table. Then you can select the projects you want to delete and then delete them using the delete button.
![Screenshot 2024-11-27 at 11 36 04 AM](https://github.com/user-attachments/assets/b734dff8-ff9e-417d-9577-d84547104571)
