### ISSUE TITLE
[Question] How to check for specific app mem usage graph?

### ISSUE THREAD

**Issue by therepo90** [caprover/caprover#2209]
Netgraph doesnt provide such solution. Id like to know which app takes how many ram.

**Comment by githubsaturn** [comment]
From the command line `docker stats`

Also, NetData shows this information. Here is screenshot from the demo instance

![image](https://github.com/user-attachments/assets/7a271fba-d018-4e18-9954-14b73488ec4e)

**Comment by therepo90** [comment]
Looks like in previous caprover versions it was not visible, thank you.
