### ISSUE TITLE
[documentation] Clarification about changes to environment variables

### ISSUE THREAD

**Issue by mathiasm74** [caprover/caprover#221]
It would be helpful if the CDD app config UI clarified that changing the value of an environment variable does not in fact reconfig to the (one-click) app. I.e. changing the MONGO_INITDB_ROOT_USERNAME or MONGO_INITDB_ROOT_PASSWORD variables does not change the username and password of the mongodb instance.

**Comment by githubsaturn** [comment]
I agree. It's confusing. We'll have to move the environmental variables to the dockerfileLines instead of exposing them to the user.

**Comment by devxpy** [comment]
Adding support for a `.env` file would be great.

dockerfileLines are pushed into version control, and you don't want things like passwords in version control.

[Here is a talk regarding this](https://www.youtube.com/watch?v=2uaTPmNvH0I)

**Comment by mathiasm74** [comment]
> dockerfileLines are pushed into version control, and you don't want things like passwords in version control.

Yeah, I agree we don't want that. And I don't particularity mind exposing the variables to the user of the web UI (in fact I think that's where there should be managed, same as Heroku does), as long as it's clear that changing the values has no other effect on the system (I got confused thinking that the password the MongoDB instance **expected** would change, when in fact that's a completely separate setting).

**Comment by devxpy** [comment]
`.env` files are rather easy to manage as compared to a webUI. 

Basically,
- create a `.env` file on your local development
- use environment variables for thing like API keys, right from the start (all languages have support for this dotenv files. Like [python](https://github.com/theskumar/python-dotenv), [nodejs](https://www.npmjs.com/package/dotenv)/
- put this `.env` file into `.gitignore`
- just upload `.env` file to captain when deploying.

**Comment by mathiasm74** [comment]
> This would save a lot of configuration time, since you'll have the same env on both development and production

Yes, although I would have assumed most of the time this is **not** what you want (e.g. I don't want the sandbox to be configured to use the production DB or billing system). Also, make sure you stay true to the ambition of providing a super-easy way to deploy services. I feel relying on configuration files takes you further from your ambition of being an easy to use Heroku-replacement.

**Comment by githubsaturn** [comment]
> dockerfileLines are pushed into version control, and you don't want things like passwords in version control.

No. They are not pushed to version control. This issue is related to one-click apps. One-click apps are built on the server and the image stays on the server. 

This is issue is to address the following scenario:
- User creates a one-click MySQL instance.
- In one-click app wizard, user selects `password123` as their password
- User connects to it and everything works fine
- Later, user decides to change the password. They go to the app's settings page and see a field named MYSQL_PASSWORD or something similar. They assume that changing this would change the password of MySQL database. This assumption is wrong. And it's not related to how CaptainDuckDuck deploy apps. It's related to how MySQL docker image was created Docker team. For example see this line:
https://github.com/docker-library/mysql/blob/fc3e856313423dc2d6a8d74cfd6b678582090fc7/8.0/docker-entrypoint.sh#L100

It only uses the environmental variable if `"$DATADIR/mysql"` does not exit.

**Comment by devxpy** [comment]
Ah okay, thanks for the explanation.

**Comment by yusef-ho** [comment]
@devxpy Hello, can you describe how to upload .env only in captainduckduck. Thanks

**Comment by devxpy** [comment]
@yusef-ho just upload it along with your code, and make the code locate and load it. You could also have the bash startup script load it up. It’s all upto you. 

In python I use a package called python-decouple which loads up the env vars from the file. Other languages have similar packages available.

**Comment by rafiqlightwala** [comment]
I want to change username and password of MongoDB instance and like mentioned in this thread, I tried changing the environment variable. As mentioned above it didn't work. Can someone actually point out how this user / pass can actually be changed?

**Comment by githubsaturn** [comment]
You need to run MongoDB shell command. To do this, you need to connect to your MongoDB instance with a client. The easiest one is MongoDB-Express which is available as a one-click app in CapRover. After installing this app and making sure that it's connected to your MongoDB instance, you can run MongoDB commands, for example, you can change password by running `changeUserPassword` command, see this for example: https://stackoverflow.com/questions/16302417/changing-the-password-in-mongodb-for-existing-user
