### ISSUE TITLE
[Question] Project names are not unique

### ISSUE THREAD

**Issue by ihsaddamhussain** [caprover/caprover#2218]
Hi, project creation over api or UI allows duplicate entries. You can create the same project name multiple times. Shouldn't this be unique ? I know the project ids are unique UIDs but it would be better off having unique names as well

**Comment by githubsaturn** [comment]
no, they don't need to be unique - this is to allow project structures like this:
```yml
client-1
   project-1
   project-2
client-2
   project-1
   project-2
```

In the future versions, the project selector will be more aligned with this
https://github.com/caprover/caprover-frontend/pull/174

![image](https://github.com/user-attachments/assets/972b0df8-682c-4498-9079-8841db664cd2)
