### ISSUE TITLE
[Question] TCP Forwarding possible?

### ISSUE THREAD

**Issue by eikaramba** [caprover/caprover#2221]
I searched but haven't found an answer to my question. It seems that i cannot define a tcp stream? the use case is that for one of my apps i need to accept raw tcp connections.
https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

**Comment by githubsaturn** [comment]
For raw TCP streams, you can just simply use port mapping under App Config.

https://caprover.com/docs/app-configuration.html#port-mapping

**Comment by githubsaturn** [comment]
The only downside is that it doesn't go through nginx which is not needed unless you want to have multiple instances of the same app and you want to loadbalance across those.
