### ISSUE TITLE
[Deployment Issue] Parsing Error: Template version field is empty!

### ISSUE THREAD

**Issue by carsaig** [caprover/caprover#2227]
What is the problem?
If I could tell! Any deployment fails with a parsing error of the captain-definition file. Clean install of docker on clean VPS latest ubuntu. Nothing special. It is NOT related to the files I am uploading, nor to the local machine I am using. The logs indicate that the parsing of the file is broken. Either it is CapRovers' fault or some weird incompatibility with packages. The edge build didn't fix anything. The captain-definition is located in the root of the repo, the JSON is valid. An example html file added for the sake of it, no more.

If applicable, content of `captain-definition` file:

```
 {
    "schemaVersion": 2,
    "templateId": "static"
   } 
```

Steps to reproduce the problem:
Deployment request via Github or manual tar archive upload, via CLI or UI, doesn't matter.

Output of the following command on your server:
caprover deploy
```
Error: Template version field is empty!
captain-captain.1.rw59gqitr4ly@host    | Error: Template version field is empty!
captain-captain.1.rw59gqitr4ly@host    |     at ApiStatusCodes.createError (/usr/src/app/built/api/ApiStatusCodes.js:11:16)
captain-captain.1.rw59gqitr4ly@host    |     at TemplateHelper.getDockerfileContentFromTemplateTag (/usr/src/app/built/user/TemplateHelper.js:55:44)
captain-captain.1.rw59gqitr4ly@host    |     at /usr/src/app/built/user/ImageMaker.js:300:55
captain-captain.1.rw59gqitr4ly@host    | GET /api/v2/user/apps/appData/test 200 1.536 ms - 502

```

**Comment by githubsaturn** [comment]
Where did you get this from?? This is not a valid value:

"templateId": "static"

**Comment by carsaig** [comment]
good question, dug up somewhere as there is absolutely nothing on the official docs regarding a simple static website. I'd be grateful to find a reliable source. Or I'm blind and very grateful, if someone points me in the right direction.

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/discussions/1734

Here is the simplest approach

**Comment by carsaig** [comment]
> #1734
> 
> Here is the simplest approach

Good lord. Unknown to me, thanks for the fast response and sorry for the inconvenience. Deployment success, you already closed the issue - good.
