### ISSUE TITLE
[Technical Support] Add domains programmatically to an app

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#229]
I have a SASS (software as a service platform), which requires me to add a new domain manually to captain's app every-time i sell to a new customer.

I have a django webserver which also does verify the domain at it's own level and doesn't allow stranger domains to access the website, if someone tries to do so.

So It has become redundant for me to enter the domain both in my django webapp and captain's app.

Is there a way to allow all domains or add domains programmatically.?

**Comment by githubsaturn** [comment]
Yes. CaptainDuckDuck has a REST api which is being used for:
App creation
App modifications
App deployment

Just open Chrome's dev panel and look at the http requests as they are being executed.

**Comment by githubsaturn** [comment]
This file should be a clear guide on the API end points of CaptainDuckDuck.

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/blob/master/app-frontend/src/js/captain/apiManager.js

**Comment by s-kris** [comment]
Leaving the new link here in case somebody visits this issue

https://github.com/caprover/caprover-frontend/blob/master/src/api/ApiManager.ts

**Comment by vohzd** [comment]
Also, if this helps, I managed to acheive this by invoking the caprover-cli via 
https://github.com/caprover/caprover-cli

```
const { exec } = require("child_process");
exec(`caprover api \
      -u "https://captain.domain.io" \
      -p "password" \
      -t "/user/apps/appDefinitions/register" \
      -m "POST" \
      -d '{ "appName": "${ options.appName }", "hasPersistentData": false}' \
    `);
```

Bit more hacky, but works nonetheless!
