### ISSUE TITLE
Cannot load netdata

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#248]
Any idea why I'm suddenly seeing the following error in the browser window that opens up when I hit the `Open NetData` button?

    Something went wrong... err: 
     Error: getaddrinfo ENOTFOUND captain-netdata-container captain-netdata-container:19999

**Comment by githubsaturn** [comment]
Before anything, can you please run the following commands and paste the information here?
```
docker inspect captain-netdata-container
docker inspect $(docker ps --filter name=captain-captain -q)
```

Solution 1)
```
docker service update captain-captain --force
```

If it doesn't work, proceed to solution 2)
Turn off NetData from the dashboard, wait for 15 seconds, and turn it back on again.

Please let me know which (if any) solution resolved the issue.

**Comment by drmrbrewer** [comment]
The output from the requested commands is at the bottom of this post (I forgot how to nest away a long block of code).

**Solution (1)**

I tried that already, and tried it again... doesn't help.

**Solution (2)**

When I first pressed `Turn off NetData` I got a red popup saying `Error please try again` _(why?)_
So, I tried again, and got: `Success NetData is turned off`.

Then I waited, logged out/in, and hit `Start NetData Engine`.

I get: `Success, NetData is successfully updated`.  BUT the page I return to still has only `Start NetData Engine` button, not `Turn on` and `Turn off` buttons.  However, I'm not worried because this happens quite often... I just navigate to a different tab and back again, and the `Turn on` and `Turn off` buttons are there.  I mention this here more to question why this happens (fairly frequently).  Seems like a check to the server (to see if NetData is installed) fails or something?

Anyhow, `Open NetData` now works.  So, solution (2) worked.

**Commands run**

	# docker inspect captain-netdata-container
	[]
	Error: No such object: captain-netdata-container

	# docker inspect $(docker ps --filter name=captain-captain -q)
	[
		{
			"Id": "07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff",
			"Created": "2018-06-25T06:00:58.477581588Z",
			"Path": "npm",
			"Args": [
				"start"
			],
			"State": {
				"Status": "running",
				"Running": true,
				"Paused": false,
				"Restarting": false,
				"OOMKilled": false,
				"Dead": false,
				"Pid": 20139,
				"ExitCode": 0,
				"Error": "",
				"StartedAt": "2018-06-25T06:00:59.942125286Z",
				"FinishedAt": "0001-01-01T00:00:00Z"
			},
			"Image": "sha256:66f553cb41f6c37eee435a2f3639f704540c9c4cb722f4cd56a21f60bf587679",
			"ResolvConfPath": "/var/lib/docker/containers/07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff/resolv.conf",
			"HostnamePath": "/var/lib/docker/containers/07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff/hostname",
			"HostsPath": "/var/lib/docker/containers/07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff/hosts",
			"LogPath": "/var/lib/docker/containers/07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff/07ee740b9db4a85628bc56113f4b6687e10ef1ab8ee0395115d1a5ce98621aff-json.log",
			"Name": "/captain-captain.1.2h2li46ero7umqo9qjzoaujsa",
			"RestartCount": 0,
			"Driver": "overlay2",
			"Platform": "linux",
			"MountLabel": "",
			"ProcessLabel": "",
			"AppArmorProfile": "docker-default",
			"ExecIDs": null,
			"HostConfig": {
				"Binds": null,
				"ContainerIDFile": "",
				"LogConfig": {
					"Type": "json-file",
					"Config": {
						"max-size": "512m"
					}
				},
				"NetworkMode": "default",
				"PortBindings": {},
				"RestartPolicy": {
					"Name": "",
					"MaximumRetryCount": 0
				},
				"AutoRemove": false,
				"VolumeDriver": "",
				"VolumesFrom": null,
				"CapAdd": null,
				"CapDrop": null,
				"Dns": null,
				"DnsOptions": null,
				"DnsSearch": null,
				"ExtraHosts": null,
				"GroupAdd": null,
				"IpcMode": "shareable",
				"Cgroup": "",
				"Links": null,
				"OomScoreAdj": 0,
				"PidMode": "",
				"Privileged": false,
				"PublishAllPorts": false,
				"ReadonlyRootfs": false,
				"SecurityOpt": null,
				"UTSMode": "",
				"UsernsMode": "",
				"ShmSize": 67108864,
				"Runtime": "runc",
				"ConsoleSize": [
					0,
					0
				],
				"Isolation": "default",
				"CpuShares": 0,
				"Memory": 0,
				"NanoCpus": 0,
				"CgroupParent": "",
				"BlkioWeight": 0,
				"BlkioWeightDevice": null,
				"BlkioDeviceReadBps": null,
				"BlkioDeviceWriteBps": null,
				"BlkioDeviceReadIOps": null,
				"BlkioDeviceWriteIOps": null,
				"CpuPeriod": 0,
				"CpuQuota": 0,
				"CpuRealtimePeriod": 0,
				"CpuRealtimeRuntime": 0,
				"CpusetCpus": "",
				"CpusetMems": "",
				"Devices": null,
				"DeviceCgroupRules": null,
				"DiskQuota": 0,
				"KernelMemory": 0,
				"MemoryReservation": 0,
				"MemorySwap": 0,
				"MemorySwappiness": null,
				"OomKillDisable": false,
				"PidsLimit": 0,
				"Ulimits": null,
				"CpuCount": 0,
				"CpuPercent": 0,
				"IOMaximumIOps": 0,
				"IOMaximumBandwidth": 0,
				"Mounts": [
					{
						"Type": "bind",
						"Source": "/captain",
						"Target": "/captain"
					},
					{
						"Type": "bind",
						"Source": "/var/run/docker.sock",
						"Target": "/var/run/docker.sock"
					}
				]
			},
			"GraphDriver": {
				"Data": {
					"LowerDir": "/var/lib/docker/overlay2/fd87fb6013e0bcfb3ce3f60621165f4d330dfb2cd5ccdc15da804e4cf71b0ee0-init/diff:/var/lib/docker/overlay2/773f7fbebf30b9255defa19a22c09c6290e2ac92df50062befacb9c51b7905b5/diff:/var/lib/docker/overlay2/9b702cd9bfce5ff3cd16f382c4bcd1d0a513b2d379fd1d7dcbaaaff1581a717e/diff:/var/lib/docker/overlay2/708f6e282212d3d177699e5b0edd21d095534e6259354cb82b92c2937d7ecb11/diff:/var/lib/docker/overlay2/23d9d39087054e5d56873cb30c4e861f0ee9813ff9ddad34818474c7cb39f05b/diff:/var/lib/docker/overlay2/03d7b8af4f0f6960eb831dd132437830835d1977c088cc8b8471b377e2819a0e/diff:/var/lib/docker/overlay2/4d52692498ad69fd6277e46f455e059f5a6efd4246f4a5a56b93904eb272a436/diff:/var/lib/docker/overlay2/0d43aaf2e6bb348d4923a4f3cbb3aa27e6f01ad35eb22ccd0af59b970c655192/diff:/var/lib/docker/overlay2/da495dbb2aab0dbd8bbd13041132acc15a6c795ca8d693ca5082200a4070e149/diff:/var/lib/docker/overlay2/e252d743592ac9c4e4513d52ed0379996c6baefab13dc94047bbe68cd1bf9119/diff:/var/lib/docker/overlay2/b75acb44e018d4b94dd81eaa8889af87b0609b6226fc7473a91f8c80e3d7ba63/diff:/var/lib/docker/overlay2/1b0ad50db0c160a42819ab297ff7c26e9816add8efb0b7abce95fc770b905359/diff:/var/lib/docker/overlay2/111f00001cf491263699e7676147d8dbd596b0e8a6bb15af47691f2391c4767c/diff",
					"MergedDir": "/var/lib/docker/overlay2/fd87fb6013e0bcfb3ce3f60621165f4d330dfb2cd5ccdc15da804e4cf71b0ee0/merged",
					"UpperDir": "/var/lib/docker/overlay2/fd87fb6013e0bcfb3ce3f60621165f4d330dfb2cd5ccdc15da804e4cf71b0ee0/diff",
					"WorkDir": "/var/lib/docker/overlay2/fd87fb6013e0bcfb3ce3f60621165f4d330dfb2cd5ccdc15da804e4cf71b0ee0/work"
				},
				"Name": "overlay2"
			},
			"Mounts": [
				{
					"Type": "bind",
					"Source": "/captain",
					"Destination": "/captain",
					"Mode": "",
					"RW": true,
					"Propagation": "rprivate"
				},
				{
					"Type": "bind",
					"Source": "/var/run/docker.sock",
					"Destination": "/var/run/docker.sock",
					"Mode": "",
					"RW": true,
					"Propagation": "rprivate"
				}
			],
			"Config": {
				"Hostname": "07ee740b9db4",
				"Domainname": "",
				"User": "",
				"AttachStdin": false,
				"AttachStdout": false,
				"AttachStderr": false,
				"ExposedPorts": {
					"3000/tcp": {}
				},
				"Tty": false,
				"OpenStdin": false,
				"StdinOnce": false,
				"Env": [
					"IS_CAPTAIN_INSTANCE=1",
					"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
					"NPM_CONFIG_LOGLEVEL=info",
					"NODE_VERSION=8.7.0",
					"YARN_VERSION=1.2.0",
					"NODE_ENV=production",
					"PORT=3000"
				],
				"Cmd": [
					"npm",
					"start"
				],
				"ArgsEscaped": true,
				"Image": "dockersaturn/captainduckduck:0.7.2",
				"Volumes": null,
				"WorkingDir": "/usr/src/app",
				"Entrypoint": null,
				"OnBuild": null,
				"Labels": {
					"com.docker.swarm.node.id": "xi0d26dfgcqaysrjscwtey3b8",
					"com.docker.swarm.service.id": "w4fjluwvvekzrvd0rwoy8jrp3",
					"com.docker.swarm.service.name": "captain-captain",
					"com.docker.swarm.task": "",
					"com.docker.swarm.task.id": "2h2li46ero7umqo9qjzoaujsa",
					"com.docker.swarm.task.name": "captain-captain.1.2h2li46ero7umqo9qjzoaujsa",
					"randomLabelForceUpdate": "bb5b6c75-d2a6-42e4-b07d-d6f9216837af"
				}
			},
			"NetworkSettings": {
				"Bridge": "",
				"SandboxID": "69cb544f5b5c58bbf98e4d94573aff3498bf230a7e99fef689a29db6ad892891",
				"HairpinMode": false,
				"LinkLocalIPv6Address": "",
				"LinkLocalIPv6PrefixLen": 0,
				"Ports": {
					"3000/tcp": null
				},
				"SandboxKey": "/var/run/docker/netns/69cb544f5b5c",
				"SecondaryIPAddresses": null,
				"SecondaryIPv6Addresses": null,
				"EndpointID": "",
				"Gateway": "",
				"GlobalIPv6Address": "",
				"GlobalIPv6PrefixLen": 0,
				"IPAddress": "",
				"IPPrefixLen": 0,
				"IPv6Gateway": "",
				"MacAddress": "",
				"Networks": {
					"captain-overlay-network": {
						"IPAMConfig": {
							"IPv4Address": "10.0.0.73"
						},
						"Links": null,
						"Aliases": [
							"07ee740b9db4"
						],
						"NetworkID": "yew84jdf2gz3zbpujwse3ltvx",
						"EndpointID": "2298acaeb4dc4279a172c980a51911673de3eb1db87b4b18b379956d19b41125",
						"Gateway": "",
						"IPAddress": "10.0.0.73",
						"IPPrefixLen": 24,
						"IPv6Gateway": "",
						"GlobalIPv6Address": "",
						"GlobalIPv6PrefixLen": 0,
						"MacAddress": "02:42:0a:00:00:49",
						"DriverOpts": null
					},
					"ingress": {
						"IPAMConfig": {
							"IPv4Address": "10.255.32.182"
						},
						"Links": null,
						"Aliases": [
							"07ee740b9db4"
						],
						"NetworkID": "tt7doeqt4tlffpq1i88k5b6cu",
						"EndpointID": "71970a6cf88894b22ee94477b7ce0a8a561ff985f99957397d3659614e8f2ae7",
						"Gateway": "",
						"IPAddress": "10.255.32.182",
						"IPPrefixLen": 16,
						"IPv6Gateway": "",
						"GlobalIPv6Address": "",
						"GlobalIPv6PrefixLen": 0,
						"MacAddress": "02:42:0a:ff:20:b6",
						"DriverOpts": null
					}
				}
			}
		}
	]

**Comment by githubsaturn** [comment]
I'll review the code and write up some more data collection steps for you so that the next time it happens, you can collect more data which hopefully helps in pinning down the issue.

**Comment by weikangchia** [comment]
Hi I am having the same issue here, but none of the 2 solution work for me

```
[
    {
        "Id": "f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3",
        "Created": "2018-07-08T13:17:48.547146001Z",
        "Path": "/run.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 28542,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-07-08T13:17:49.114198774Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:61ea36e03dce965e648333979341e9f82d5b2b098b24cb29abd8ea9794fa00c6",
        "ResolvConfPath": "/var/lib/docker/containers/f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3/hostname",
        "HostsPath": "/var/lib/docker/containers/f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3/hosts",
        "LogPath": "/var/lib/docker/containers/f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3/f686bb57ed55be8e9d187db0bd26b721c00b87a21dd9b33f99c009cc7dcbf7f3-json.log",
        "Name": "/captain-netdata-container",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/proc:/host/proc:ro",
                "/sys:/host/sys:ro",
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "512m"
                }
            },
            "NetworkMode": "captain-overlay-network",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "SYS_PTRACE"
            ],
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/979521e7a6c672a866dc12e4ded33cf315a1b81f78be7b802402115cf4314432-init/diff:/var/lib/docker/overlay2/babd8533ee93a62c984aafb36cdb19678b05d22bb73dc24a5006cd1dd547d1a5/diff:/var/lib/docker/overlay2/0886a2e23427f639aead8555ae870e5666e4f9d95534899d29098434883eaeb8/diff:/var/lib/docker/overlay2/c6e51936faf953ff76f44da51d781fd8ac22a736f1e49a898579a45334f5870c/diff:/var/lib/docker/overlay2/db5c3724d797daa33d4f675d3b994a6ea341a8735a6fab386cb2d5050179cef1/diff:/var/lib/docker/overlay2/bef10806b605ff8e6e360f681dd44bb0d9e4c2ccb1dcd7f35b2ab3ac20cb98f6/diff",
                "MergedDir": "/var/lib/docker/overlay2/979521e7a6c672a866dc12e4ded33cf315a1b81f78be7b802402115cf4314432/merged",
                "UpperDir": "/var/lib/docker/overlay2/979521e7a6c672a866dc12e4ded33cf315a1b81f78be7b802402115cf4314432/diff",
                "WorkDir": "/var/lib/docker/overlay2/979521e7a6c672a866dc12e4ded33cf315a1b81f78be7b802402115cf4314432/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/proc",
                "Destination": "/host/proc",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sys",
                "Destination": "/host/sys",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "f686bb57ed55",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "19999/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SLACK_WEBHOOK_URL=",
                "SLACK_CHANNEL=",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NETDATA_PORT=19999",
                "SSMTP_TLS=YES",
                "SSMTP_SERVER=smtp.gmail.com",
                "SSMTP_PORT=587",
                "SSMTP_HOSTNAME=localhost"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "titpetric/netdata:1.8",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/run.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b5ff0f3705ecc9fe5e8fa677b5601afc1cc0e5e6513e905951eb39558759edc7",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "19999/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/b5ff0f3705ec",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "captain-overlay-network": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.0.24"
                    },
                    "Links": null,
                    "Aliases": [
                        "f686bb57ed55"
                    ],
                    "NetworkID": "t8942snthsy3p970w5yjli2ql",
                    "EndpointID": "352d4b2ae08de07e36deb77661c5280379bbded1049d02324f2774acde64e86d",
                    "Gateway": "",
                    "IPAddress": "10.0.0.24",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:18",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by githubsaturn** [comment]
That's bizarre. Solution 2 should always work. Is this something that just started to happen or you never been able to NetData at all?

Do you use a local use or a VPS provider? If a VPS provider, who do you use and what's the OS & version on your VPS?

**Comment by weikangchia** [comment]
Finally, solve it! I restart my EC2 instance and it works. Really ❤️captainduckduck

**Comment by githubsaturn** [comment]
With v1.0.0 this should not happen anymore. Feel free to reopen if the issue still exists.
