### ISSUE TITLE
Easier setting of config variables

### ISSUE THREAD

**Issue by paulvoe** [caprover/caprover#256]
Feature request:
It would be nice if one could upload a file or something like that to set the config variables in an app.
Setting every single one by hand can be very exhausting when deploying multiple apps with large configuration.

Love Captainduckduck, thanks and keep up the great work!

**Comment by pouledodue** [comment]
in some frameworks it is handled by the web GUI. When you paste something like
```
HOST=blabla
USER=john
PASSWD=doe
```
or
```
HOST:blabla
USER:john
PASSWD:die
```
Then the webpage form autocreate a list of pre-filled input widgets

**Comment by derek-adair** [comment]
Boy oh boy i'd like to discourage this feature.  It's not a good convention to encourage, by ANY means.  Its not a good idea to have say... HOST/USER/PASSWD written down in your app or committed.

**Comment by derek-adair** [comment]
Let me put it another way;

One of the main utilities of this feature is so you DONT put that in code.

**Comment by pouledodue** [comment]
he does not want them written he wants a way to set multiple easily

**Comment by derek-adair** [comment]
Ahhh I see.  That makes sense.

**Comment by githubsaturn** [comment]
Done in v1.0.0
 https://github.com/caprover/caprover/releases/tag/v1.0.0

**Comment by derek-adair** [comment]
SO STOKED.
