### ISSUE TITLE
Building Client and Server code together in one app.

### ISSUE THREAD

**Issue by billyl** [caprover/caprover#263]
I'm just starting out to become a fullstack developer so I am not sure if this is the right place to post it. Please give me some pointers or a lead if possible.

**What is the problem?** 

I am following Stephen Grider's tutorial on how to become a full stack developer. In his tutorials, he uses Heroku, but I chose CaptainDuckDuck for deployment (that's why we are all here right?)

My project structure looks like this:

.
├── captain-definition
├── client
│   ├── README.md
│   ├── etc
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── public
│   └── src
├── config
│   ├── dev.js
│   ├── keys.js
│   └── prod.js
├── db
│   ├── knex.js
│   ├── migrations
│   └── seeds
├── index.js
├── knexfile.js
├── node_modules
├── package-lock.json
├── package.json
├── routes
│   └── authRoutes.js
└── services
    └── passport.js

Essentially my goal is to build the client (react) project into it's own js and copy it to the same directory as the main project to serve.

How it is done in the tutorial is through this line in the package.json script:

"scripts": {
    "start": "node index.js",
    "server": "nodemon index.js",
    "client": "npm run start --prefix client",
    "dev": "concurrently \"npm run server\" \"npm run client\"",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"  },

I've tried replacing heroku-postbuild with postinstall (npm) and it claims about not finding the files.

Also tried playing with the captain-definition file below but its not working. Am I supposed to make this in to 2 seperate apps and connect them? I much prefer dumping them together.

Here's my captain definition file

{
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "FROM node:8.7.0-alpine",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./src/client/package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
			"COPY ./src /usr/src/app",
			"COPY ./src/package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./src /usr/src/app",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16.04
- RAM? 1gb
Digital Ocean base VPS

**Comment by githubsaturn** [comment]
The working version of captain-definition file depends on your exact use case and commands that are defined in your package.json file. Please create a sample app on github so I can write up a working captain-definition file. But, in general, steps are:
- Copy the frontend code to a directory and build it
- Copy the backend code to a directory and build it
- Copy the built frontend code to the `public` directory of the backend code


For example:
```
 {
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "FROM node:8.7.0-alpine",
                        "RUN mkdir -p /usr/src/frontend",
                        "COPY ./src/client /usr/src/frontend",
                        "WORKDIR /usr/src/frontend",
                        "RUN npm install && npm cache clean --force",
                        "RUN npm build   ## THIS IS THE COMMAND THAT BUILDS FRONTEND CODE, IT MIGHT BE DIFFERENT DEPENDING YOUR PACKAGE.JSON",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./src/package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./src /usr/src/app",
                        "RUN cp /usr/src/frontend/dist /usr/src/app/public/  ## DIRECTORIES MAY CHANGE DEPENDING ON YOUR PACKAGE.JSON CONFIG",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

**Comment by billyl** [comment]
I'm on the last step of copying over the build folder to the main one but i'm having some trouble:

This is my captain-definition:

> {
>  "schemaVersion":1 ,
>  "dockerfileLines" :[
>                        "FROM node:8.7.0-alpine",
>                        "RUN mkdir -p /usr/src/frontend",
>                        "COPY ./src/client /usr/src/frontend",
>                        "WORKDIR /usr/src/frontend",
>                        "RUN npm install && npm cache clean --force",
>                        "RUN npm run build   ## THIS IS THE COMMAND THAT BUILDS FRONTEND CODE, IT MIGHT BE DIFFERENT DEPENDING YOUR PACKAGE.JSON",
>                        "RUN mkdir -p /usr/src/app",
>                        "WORKDIR /usr/src/app",
>                        "COPY ./src/package.json /usr/src/app/",
>                        "RUN npm install && npm cache clean --force",
>                        "COPY ./src /usr/src/app",
>                        "RUN ls /usr/src/frontend/",
>                        "RUN ls /usr/src/frontend/build",
>                        "RUN ls /usr/src/frontend/build/static",
>                        "COPY /usr/src/frontend/build /usr/src/app/  ## DIRECTORIES MAY CHANGE DEPENDING ON YOUR PACKAGE.JSON CONFIG",
>                        "ENV NODE_ENV production",
>                        "ENV PORT 80",
>                        "EXPOSE 80",
>                        "CMD [ \"npm\", \"start\" ]"
>                    ]
> }


> ---> 3dafa9a9d71a
> Step 12/19 : RUN ls /usr/src/frontend/
> 
> ---> Running in b22db3ae338d
> README.md
> build
> node_modules
> package-lock.json
> package.json
> public
> src
> Removing intermediate container b22db3ae338d
> ---> 0823e0f1bece
> Step 13/19 : RUN ls /usr/src/frontend/build
> 
> ---> Running in 62fee60560b5
> asset-manifest.json
> favicon.ico
> index.html
> manifest.json
> service-worker.js
> static
> Removing intermediate container 62fee60560b5
> ---> b24c76ee7dd1
> Step 14/19 : RUN ls /usr/src/frontend/build/static
> 
> ---> Running in e81af2926fba
> css
> js
> media
> Removing intermediate container e81af2926fba
> ---> d62666f6256e
> Step 15/19 : COPY /usr/src/frontend/build /usr/src/app/  ## DIRECTORIES MAY CHANGE DEPENDING ON YOUR PACKAGE.JSON CONFIG
> 
> {"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder417567379/usr/src/frontend/build: no such file or directory"}
> COPY failed: stat /var/lib/docker/tmp/docker-builder417567379/usr/src/frontend/build: no such file or directory
> ----------------------
> Deploy failed!
> Error: {"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder417567379/usr/src/frontend/build: no such file or directory"}
> COPY failed: stat /var/lib/docker/tmp/docker-builder417567379/usr/src/frontend/build: no such file or directory


The code is built but the directory does not exist when I try to copy it to the main folder?

**Comment by githubsaturn** [comment]
Support for plain  dockerfile support is added in v1.0.0

**Comment by kristijanPetr** [comment]
Hey  @githubsaturn  i think this is relevant issue to ask: 
I have similar structure where i'm serving both backend and frontend( pre-built and served) 
but how can i use cached version if no changes are made on frontend side to prevent re-building same code again?

**Comment by githubsaturn** [comment]
@kristijanPetr 
This issue is about custom build step for a Dockerfile. But your concern is regard to caching layer. Docker performs caching by default. It invalidates the cache at the layer where the first change it appears. Therefore, if you want to cache your front end. You need to update your Dockerfile to do these in order:
1- Copy the source code ONLY for frontend
2- Build the "built" artifact for frontend
3- Copy the source code for the backend
4- Build the "built" artifact for the backend
5- Copy the frontend into the correct directory to be served by the backend.

The exact commands and behavior is totally dependent on your specific directory structure and how Docker performs caching.
