### ISSUE TITLE
Laravel Sample

### ISSUE THREAD

**Issue by monoland** [caprover/caprover#285]
What is the problem?
laravel include CLI (artisan) for first setup and run composer install/update for vendor download.
how to do this in captainduckduck.

**Comment by david-szabo97** [comment]
@monoland This might help: https://buddy.works/guides/laravel-in-docker

**Comment by chocochrispi** [comment]
I hope this help..
----------------------------
captain-definition

{
  "schemaVersion" :2 ,
  "dockerfilePath" :"./myDockerFile"
 }


------------------------------
myDockerFile

FROM php:7
RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mbstring
WORKDIR /app
COPY . /app
RUN composer install

CMD php artisan serve --host=0.0.0.0 --port=8181
EXPOSE 8181

------------------------------

Setup App in Caprover

Container HTTP Port 8181
Define APP_KEY in Environmental Variables

**Comment by githubsaturn** [comment]
# Working Sample:


Added Laravel Sample to samples directory:
https://github.com/caprover/caprover/tree/master/captain-sample-apps
