### ISSUE TITLE
Add option for simple pasword protection of exposed web-apps

### ISSUE THREAD

**Issue by rschaerer** [caprover/caprover#336]
I suggest adding the option for protecting access to exposed web-apps with a password.

# :dart: Desired outcome

## :computer: Backend GUI of captainduckduck

A user can check the checkbox `Enable password protection for accessing this web-app` in the captain GUI settings of an app under the section `HTTP (web app) Settings`.

After pressing `Save & Update Configuration` a random password will be shown right below the checkbox. If needed a random username will be displayed as well. Password and username might be optionally user editable.

The user can disable the password protection at any times.

## :iphone: When accessing the exposed web-app

Enabling password protection restricts access to the exposed web-app on http (and https if enabled) by showing a password dialog or input field on a landing page when opening the exposed web-app url or any connected domain in the browser.

# :bulb: implementation ideas

* use nginx [auth_basic](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html)

# :question: Open questions

* What happens when Port Mapping is enabled in the app?

# :mega: Why could this feature be useful to users?

Some examples why this feature is handy for captain users:

* When they want to protect their one click app phpmyadmin from being accessed and used by a random person.
* When they want to setup their one click app wordpress as not public exposed cms for generating static sites with a plugin like [Simply Static](https://wordpress.org/plugins/simply-static/) or [WP Static Site Generator](https://de.wordpress.org/plugins/static-html-output-plugin/).
* and many more... :heart:

**Comment by rschaerer** [comment]
> What if we just deploy your app on internal network.

This is another feasible implementation which might be easier to add as new feature.

However I think this approach lacks two benefits which I was thinking about: the app is still **accessible from the outside** ( :one: ) by **anyone** ( :two: ) which has the credentials.

This raises the following questions:

:one: What does the deploying user do to access the web-app deployed on the internal network only?

* Use a ssh tunnel?
* Other easy methods?

:two: How can the web-app be exposed to another person than the deploying user?

* I have no idea about that

**Comment by iamrommel** [comment]
I think the auth should be controlled by the app itself. Another layer of
auth on the top of auth of app is redundant and weird design. Imagine i
will always login twice using different credentilas on single app. Which is
really weird UX to me

**Comment by githubsaturn** [comment]
Implemented in v1.4.0

**Comment by derek-adair** [comment]
>I think the auth should be controlled by the app itself. Another layer of
auth on the top of auth of app is redundant and weird design. Imagine i
will always login twice using different credentilas on single app. Which is
really weird UX to me

You are thinking about this wrong.  HTTPauth is wonderful for private demonstrations or as a workaround for single page apps that do not have auth built in.  An example of the latter is [jekyll-admin](https://github.com/jekyll/jekyll-admin).  The way in which jekyll-admin suggests self hosting their app is to [use httpauth](https://jekyll.github.io/jekyll-admin/self-hosting).

----------
Thanks for this @githubsaturn I use it for several projects.
