### ISSUE TITLE
NGINX (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by hdriqi** [caprover/caprover#350]
Hi, I just successfully deploy my application to captainduckduck.

The application is running properly, I can even ping my application inside NGINX container. but when I access it using NGINX, it throws error connecting to upstream.

Any solutions?

**Comment by githubsaturn** [comment]
That seems like an upstream container issue. Are you getting a 502 error?

>  I can even ping my application inside NGINX container

When you say ping, how are you pinging your application? Like `curl http://srv-captain--yourappname` ?

**Comment by githubsaturn** [comment]
PS: Can you please copy the entire line for `111: Connection refused` ?

**Comment by hdriqi** [comment]
@githubsaturn I execute bash on nginx container, and install ping command.

**Comment by hdriqi** [comment]
@githubsaturn ah after google better keyword, found the solution. I dont know why it works when I create new upstream block

`upstream localdomain {
    server <%-s.localDomain%>:8000;
}`

**Comment by githubsaturn** [comment]
Troubleshooting for 502 is here: https://captainduckduck.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

**Comment by githubsaturn** [comment]
Glad that you solved your issue!
