### ISSUE TITLE
Persistent data with host path not possible

### ISSUE THREAD

**Issue by MeXaaR** [caprover/caprover#351]
Hi everyone, I encountered an issue on the new V1 (amazing work by the way)

**What is the problem?**
Every time I want to set my persistent data on my host instead of a volume, I have this error message poping up
`1000 : Invalid volume name: undefined`

Steps to reproduce the problem:
Deploy any persistent data app like nextcloud and try setting the volume to somewhere specific in your host. For me, it was: `/home/nextcloud-storage` wich is not empty but I tried with another empty folder and same problem

Answers to the following questions where applicable:
RAM: 15.66 GB
OS: linux
CPU: 4 cores
Architecture: x86_64

**Comment by githubsaturn** [comment]
Thanks for reporting this. Fixed in https://github.com/caprover/caprover/commit/b841f029255845ab3c7b58645c18d502d0de17f4


If you want, you can upgrade to edge version to have this issue resolved immediately.
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version
