### ISSUE TITLE
Manual add oneclick app

### ISSUE THREAD

**Issue by Gliba** [caprover/caprover#353]
Can i create oneclick app manually?

**Comment by githubsaturn** [comment]
I am not sure if I understand you correct. You either want to deploy an app that is not present, or you want to add a new app to the drop down list. Either way:

1) You want to deploy a new app that is not currently present as a one-click app:
In this case, just find the docker image for that app. For example, if you want to deploy mariadb as a new app use this: https://hub.docker.com/_/mariadb

More details: https://caprover.com/docs/one-click-apps.html#what-about-other-apps


2) If you want to add a new image as a public one click app, create a pull request for this repository:
https://github.com/caprover/one-click-apps/tree/master/public/v1/apps
