### ISSUE TITLE
Custom production build script like Heroku. i.e) React-boilerplate deployment

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [caprover/caprover#354]
**Is your feature request related to a problem? Please describe.**

Hi, I'd like to suggest something heroku does such as running custom script "npm run start:prod && npm run build" etc. I don't know how to deploy react-boilerplate using caprover since there are some custom steps that are required. Please look at how react-boilerpalte deploys to heroku, 
https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/deployment.md
```
Step 1: Create a Procfile with the following line: web: npm run start:prod. We do this because Heroku runs npm run start by default, so we need this setting to override the default run command.

Step 2: Install the Node.js buildpack for your Heroku app by running the following command: heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v91 -a [your app name]. Make sure to replace #v91 with whatever the latest buildpack is, which you can find here.

Step 3: Add this line to your package.json file in the scripts area: "heroku-postbuild": "npm run build",. This is so Heroku can build your production assets when deploying (more of which you can read about here). Then, adjust the prebuild script in your package.json file so it looks like this: "prebuild": "npm run build:clean", to avoid having Heroku attempt to run Jest tests (which are unsupported with this buildpack).

Step 4: Run heroku config:set NPM_CONFIG_PRODUCTION=false so that Heroku can compile the NPM modules included in your devDependencies (since many of these packages are required for the build process).

Step 5: Follow the standard Heroku deploy process:

git add .
git commit -m 'Made some epic changes as per usual'
git push heroku master
```

**Describe the solution you'd like**
implementing captain-file to include custom build script

**Describe alternatives you've considered**
Perhaps this can be achieved using Dockerization. 

**Additional context**

**Comment by githubsaturn** [comment]
Have your looked at this?
https://caprover.com/docs/captain-definition-file.html#advanced-version

There are multiple ways to deploy React App with CapRover, There is a sample app and also there is a line by line tutorial here:

https://caprover.com/docs/recipe-deploy-create-react-app.html
