### ISSUE TITLE
Error removing port mapping

### ISSUE THREAD

**Issue by gabrielgradinaru** [caprover/caprover#355]
What is the problem?

Encountered error while trying to remove a port mapping for an app

Steps to reproduce the problem:
1. Configure a port mapping and save it
2. Try to delete the port mapping

Expected result:
Port mapping should be deleted successfully

Actual result:
- "Something bad happened" error in frontend
- Frontend sent deleted port as `0`
example: `"ports":[{"hostPort":3306,"containerPort":3306},{"hostPort":0,"containerPort":0}]`
- Error details in backend:
````
captain-captain.1.vt808sdloel7@ip-172-31-41-69    | POST /api/v2/user/apps/appDefinitions/update 500 1.477 ms - 21
captain-captain.1.vt808sdloel7@ip-172-31-41-69    | January 28th 2019, 7:14:21.751 pm    Error: Host or container port is missing
captain-captain.1.vt808sdloel7@ip-172-31-41-69    | Error: Host or container port is missing
captain-captain.1.vt808sdloel7@ip-172-31-41-69    |     at /usr/src/app/built/datastore/AppsDataStore.js:75:31
captain-captain.1.vt808sdloel7@ip-172-31-41-69    |     at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by githubsaturn** [comment]
Thanks for the detailed info. It's been fixed. You can try using the edge version:
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version

Or wait until the next release.

**Comment by gabrielgradinaru** [comment]
Thank you for the fast fix. It looks like there are some issues with the edge version:
```
root@ip-172-31-41-69:~# docker service update captain-captain --image caprover/caprover-edge:0.0.1
captain-captain
overall progress: 0 out of 1 tasks 
1/1: No such image: caprover/caprover-edge:0.0.1@sha256:51b5c7c62330ba2e5cf0681… 
service update paused: update paused due to failure or early termination of task oneeazy9huwjo9mc4kfjvckrm
```

**Comment by githubsaturn** [comment]
No, edge image is good. I just tested it.

Can you please try running
```
docker pull caprover/caprover-edge:0.0.1
```

If it succeeds then try running
```
 docker service update captain-captain --image caprover/caprover-edge:0.0.1
```

**Comment by gabrielgradinaru** [comment]
My bad, it looks like I did not have enough disk space and the `docker service update` error was not very useful here.
Seems that everything works fine, I guess we should close this issue.
