### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by robgraeber** [caprover/caprover#356]
Hey dude I tried the new release and it looks really good. I've used dokku, exoframe, kubernetes before and this is by far my favorite. Overall this looks solid and I plan to port my apps over. 

If you're interested these are the things I thought could be low hanging fruit to improve it:
- If no captain-definition file is found, default to using the ./Dockerfile
- A way to support mono-repos with more than 1 Dockerfile or captain-definition.
- A click to deploy from git button, next to the webhook section.
- Editing the root domain name (In my case I used a random domain to test on and now that I like it I want to use my actual domain)
- Login persistence on the admin page
- Hide the git password client-side
- Have IP whitelist for the admin page so you can put it behind a vpn (Should have a config file in /captain so you can ssh and change it if you get locked out)
- Make the admin UI more responsive for mobile

Is there anything you think would be easy for me to implement?

**Comment by githubsaturn** [comment]
- If no captain-definition file is found, default to using the ./Dockerfile
> Good suggestion! Will do!

- A way to support mono-repos with more than 1 Dockerfile or captain-definition.
> This is a can of worm! Mono repos are anti pattern. No other Most PaaS do not support them as a single app that gets split into two in the backend. You can always have a mono repo with 2 services that run in the same docker container. This is totally fine.


- A click to deploy from git button, next to the webhook section.
> Clarify please?


- Editing the root domain name (In my case I used a random domain to test on and now that I like it I want to use my actual domain)
> Root domain is not too important. You can always attach more domains to your apps. Reason behind not providing the ability for editing it is the confusion is causes with all the already activated HTTPS URLs. Open to discussion on this one.


- Login persistence on the admin page
> This is by design. Login persistence requires cookies. Usage of cookies are limited only to NetData dashboard. Not having cookies for admin page means one less security hole to be worried about. With modern browsers saved password capabilities, this is now has even a lower priority. 


- Hide the git password client-side
> Google chrome will autofill the password field with the dashboard password if this field has the type of `password`... smh... Having said that, we can add a hide/show button.


- Have IP whitelist for the admin page so you can put it behind a vpn (Should have a config file in /captain so you can ssh and change it if you get locked out)
> Nginx config file for dashboard and apps are completely customizable, you can go to settings and add your whitelist IP address there (and any other customization that you might need)


- Make the admin UI more responsive for mobile
> In progress by a contributor! Hopefully soon will be ready!

**Comment by githubsaturn** [comment]
+ Thanks for your kind words :smile:

**Comment by robgraeber** [comment]
Hey @githubsaturn thanks for the reply!

> A way to support mono-repos with more than 1 Dockerfile or captain-definition.
>
> This is a can of worms! Mono repos are anti pattern. No other Most PaaS do not support them as a single app that gets split into two in the backend. You can always have a mono repo with 2 services that run in the same docker container. This is totally fine.

I’d argue that mono repos by themselves aren’t bad, it’s monoliths that are the anti pattern. I was hoping having a field in the UI for a “captain-definition file path” would be lightweight to implement. Heroku / Dokku / App engine approach it by letting you define multiple processes in a config file and then you scale them independently but that seemed like a can of worms.

> A click to deploy from git button, next to the webhook section.
> 
> Clarify please? What does that button do?

Basically like how the git webhooks triggers a git pull and build, it’d be nice to have a button that manually triggers the git pull and build.

> Hide the git password client-side
>
> Google chrome will autofill the password field with the dashboard password if this field has the type > of password... smh... Having said that, we can add a hide/show button.

What about a simple client-side patch that, if the password exists, it prefills it as ●●●●●●●?

> Nginx config file for dashboard and apps are completely customizable, you can go to settings and add your whitelist IP address there (and any other customization that you might need)

Thanks that’s a good suggestion. Would you accept a PR if I wrote a guide for it?

> Login persistence on the admin page
>
> This is by design. Login persistence requires cookies. Usage of cookies are limited only to NetData dashboard. Not having cookies for admin page means one less security hole to be worried about. With modern browsers saved password capabilities, this is now has even a lower priority.

What if the auth token was stored in session storage?

**Comment by githubsaturn** [comment]
> I’d argue that mono repos by themselves aren’t bad, it’s monoliths that are the anti pattern. I was hoping having a field in the UI for a “captain-definition file path” would be lightweight to implement. Heroku / Dokku / App engine approach it by letting you define multiple processes in a config file and then you scale them independently but that seemed like a can of worms.

I see what you're saying! My main argument with MonoRepos is stemmed from the assumption that a single push will cause 2 (or more) separate builds - which is completely wrong. But what you're saying makes sense. We use a single repo that can be deployed to multiple apps, but each app knows the specific place where it should find its own captain-definition. Great suggestion!

> Basically like how the git webhooks triggers a git pull and build, it’d be nice to have a button that manually triggers the git pull and build. Heroku has something similar and it works pretty nicely.

I see, like a "force build from git" button... Okay, makes sense. What is the use case for this button?

> What about a simple client-side patch that, if the password exists, it prefills it as ●●●●●●●?

It'll cause problems as client side we use a two way binding. A simple hide/show is an industry standard.

> What if the auth token was stored in session storage?

I don't have much experience with session storage. Is it considered a "secure" store? Also, AFAIK it only solves the problem with the soft refresh. New tabs and new windows will still get logged out.

**Comment by m0xx** [comment]
I'm interested by the proposed solution that offer the possibility to specify a captain-definition per apps. 

I have multiple project structured as a multi service in a monorepo and no CI / CD has a perfect solution for this yet. Usually I assign a config-file per branch and the proposed solution would be perfect. 

Let me knows if I can help

**Comment by robgraeber** [comment]
> I see, like a "force build from git" button... Okay, makes sense. What is the use case for this button?

It's nice when you're setting up your app initially. If you do have the ./Dockerfile be the default then a lot of people be able to deploy their app with no code changes and only a few clicks in the UI! You could also have a dev environment with auto-deploy on, and a prod environment that's only deployed manually.

> It'll cause problems as client side we use a two way binding. A simple hide/show is an industry standard.
I'm just thinking it's not important to display the password again after it's saved. I know caprover is single user but it'd nice to not expose more data than you have to.

> I don't have much experience with session storage. Is it considered a "secure" store? Also, AFAIK it only solves the problem with the soft refresh. New tabs and new windows will still get logged out.

Not worrying about CSRF attacks is the main thing, you could use local storage too I'd just recommend the session life not be too long otherwise anyone with access to your computer can access it.

**Comment by githubsaturn** [comment]
I'll prioritize these and have them done. There are some items here that require some consideration. But most of these are small changes.


PS: Regarding the write-up for whitelisting IPs, please go ahead and create a PR if you'd like. Website repo is https://github.com/caprover/caprover-website

**Comment by robgraeber** [comment]
The git configs probably need a field for ssh keys too, I just noticed that username + password doesn't work if 2FA is enabled.

**Comment by githubsaturn** [comment]
Common practice is to use a service account. Create a service account with read only access to particular repositories of choice. This way, if your server gets compromised, your own SSH key and password are safe.

**Comment by robgraeber** [comment]
Hmm I suppose that works but requires a bunch of extra steps when starting out. Another option is deploy keys, looks like github/bitbucket/gitlab all support generating read-only deploy keys on a per-repo basis which seems like the perfect fit.

**Comment by githubsaturn** [comment]
@robgraeber 
Most of your suggestions are now deployed as v1.2.0  https://github.com/caprover/caprover/releases/tag/v1.2.0

PS: regarding deploy keys, yes, I think it's a good idea. I wasn't too sure if I can specify a specific key per git clone, but apparently it's possible: https://stackoverflow.com/a/29754018/3236788

Will close this issue for now as it's cluttered with multiple issues. Feel free to create individual issues for all other suggestions that you have.

**Comment by robgraeber** [comment]
@githubsaturn awesome! I confirmed all the new features work as expected
