### ISSUE TITLE
Migration script

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#358]
Really keen to upgrade to CapRover!  Any idea as to when the migration script will be ready?  https://caprover.com/docs/cdd-migration.html

**Comment by drmrbrewer** [comment]
Scrub that.  Probably I'd upgrade anyway by spinning up a completely fresh server, based on CapRover, and switching to that, rather than converting the existing Captain server to CapRover.  So, I guess a migration script is not so necessary.

**Comment by githubsaturn** [comment]
It'll be ready very very soon! Final testing in progress...
