### ISSUE TITLE
versions in config-captain.json

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#359]
My `config-captain.json` file is getting ever bigger.  Question is... is there really a need for all of the entries in the `versions` element?

    "versions": [
        {
                "version": 0,
                "timeStamp": "2018-01-31T20:55:54.507Z"
        },
        {
                "version": 1,
                "timeStamp": "2018-01-31T21:00:51.759Z",
                "gitHash": "dc49fc547eaa14ee5784364af40645fd9aaf24a8"
        },
        ...
        ...

Can I cull these at all?

**Comment by githubsaturn** [comment]
It's a deploy history. CapRover adds the feature for one click rollbacks. Now all these information is being used. If it really bothers you, you can cleanup the config file and restart your captain-captain. But it really shouldn't be an issue. Each deploy is around 150 bytes. If you deploy 2 times a day for 365 days for 10 apps, it adds around 1 MB to your config file. This shouldn't be an issue.

**Comment by githubsaturn** [comment]
There is a lot that has changed in startup procedure. One thing that I personally noticed was the delay caused by upgrading Certbot (LetsEncrypt Client) from v0.17 to v0.29. It used to be ready in a fraction of a second, now it takes ~10 sec or more to spin up. That could be the cause of the delay.

**Comment by githubsaturn** [comment]
Regarding rollback, yes, any version can be rolled back to. Unless you had deleted the image. Even so, it's a deployment history. It's better to keep it. Trying to rollback to an image that was manually deleted doesn't break your app, it just doesn't work, the rollback will gracefully fail.

**Comment by drmrbrewer** [comment]
At what point in the process does the Certbot upgrade take place?

Regarding rollback, I tend to clear out images on a fairly regular basis to keep storage in check, and would only see real value in rolling back to the previous version (after a bad deploy) or maybe two or three at the most.  My main app now has 670 version entries in the conf file... I would never ever ever consider rolling back 670 versions even if I could.

**Comment by githubsaturn** [comment]
> At what point in the process does the Certbot upgrade take place?

Start up. It's not the "upgrade" that takes time, it's the start up process of Certbot and having it connect to CapRover.

> Regarding rollback, I tend to clear out images on a fairly regular basis to keep storage in check, and would only see real value in rolling back to the previous version (after a bad deploy) or maybe two or three at the most. My main app now has 670 version entries in the conf file... I would never ever ever consider rolling back 670 versions even if I could.

Fair enough. Like I said, as part of your script, you can remove the unwanted elements of the "versions". I've made some changes to CapRover to ensure that it can handle missing elements of versions gracefully. It will cause no problem.

**Comment by drmrbrewer** [comment]
@githubsaturn I still think it would be nice to have an automated way to clean up the deployment history :)  It doesn't take up much disk space, but if nothing else it just clutters up the config file and when I'm looking through the config file (to plan my next customisation :) all this history just gets in the way... I know that I'm never going to go back more than a couple of versions, not least because I'm using a self-hosted registry and the images are cleaned out on a regular basis (e.g. when I spin up a new server) so keeping this history seems pointless.  Yes it's possible to edit the file manually, but it would be nice to have an option to clear out any history older than e.g. 6 months... that would keep things in check.

**Comment by githubsaturn** [comment]
The version history is capped at 50 by default:
https://github.com/caprover/caprover/blob/6fdcb8b1e4aa4e2acafb02ec5914b3e9bfba4c4e/src/utils/CaptainConstants.ts#L27-L29

You can override it via [config override](https://caprover.com/docs/troubleshooting.html#customize-config-settings)
