### ISSUE TITLE
Strapi (One-Click App) not working

### ISSUE THREAD

**Issue by bilalajanjua** [caprover/caprover#363]
**What is the problem?**

Actually, i am trying to install Strapi through One Click Apps. It installed successfully and the database is running fine as well. 

But when i go to the link, it always shows `NGINX 502 Error :/` error. I already checked the application logs for both database and strapi core app.

Here is the snippet of log:

`-02-05T09:22:06.204220313Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8`
`-02-05T09:19:25.266142546Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8`
`2019-02-05T09:19:25.266886391Z `
`2019-02-05T09:22:06.204943955Z `
`2019-02-05T09:22:06.910462428Z Lets configurate the connection to your database:`
`2019-02-05T09:19:25.904669264Z Lets configurate the connection to your database:`
`2019-02-05T09:19:25.904922644Z Database determined by CLI args: mongo`
`2019-02-05T09:22:06.910649322Z Database determined by CLI args: mongo`
`2019-02-05T09:22:08.340745820Z `
`2019-02-05T09:19:27.337311879Z `
`2019-02-05T09:19:27.337492425Z b3 Testing database connection...`
`2019-02-05T09:22:08.340923622Z b3 Testing database connection...`
`2019-02-05T09:20:08.797701904Z The app has been connected to the database successfully!`
`2019-02-05T09:20:08.798500173Z `
`2019-02-05T09:20:08.803095593Z p Application generation:` 

It keeps on repeating this. It connects to the database successfully and then display `Application Generation`  message and then after few seconds repeat the same. I tried installing the mongodb seperately through one click installer and with different versions too, but the problem persists. 

**Answers to the following questions where applicable:**
**- Your OS and version?** Ubuntu 16.04 - Docker 17.12.0 
**- RAM?** DigitalOcean 1GB Droplet

**Comment by iamrommel** [comment]
I can confirm that this is happening to my caprover too!

I filed the issue from https://github.com/caprover/one-click-apps/issues/21

But that is the same log that i'm getting. I tried also using the tag
"latest" but got the same error

*Rommel C. Manalo*

**Comment by bilalajanjua** [comment]
@iamrommel Yeah i also tried changing Strapi version too. I upgraded from CaptainDuckDuck today, and spent like 2 hours trying to setup strapi but no luck. 

P.S. I didn't try installing strapi manually on CaptainDuckDuck either.

**Comment by githubsaturn** [comment]
I just tested Strapi One Click App, and everything worked fine. As far as CapRover job is involved, your Strapi instance is created. The crash happens within Strapi, it's not a CapRover issue. My best guess is that you might be running out of RAM.

Try adding more RAM to your machine and retry. My machine has 4GB of RAM, but I guess even 2GB should solve the problem. Also, try adding more swap memory to your instance.

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by bilalajanjua** [comment]
I resized the droplet to 2GB RAM and it worked!

But there is still an issue with the latest tag of docker image, error is `./strapi.sh: wait: line 1: Illegal number:`.

I hope in the future update of Strapi docker image, it will be fixed. I am closing this issue as i think it i resolved.

**Solution: **Increase the RAM of the server to at least 2GB.

**Comment by githubsaturn** [comment]
Maybe we should make this clear in the instructions of Strapi one click app.

@iamrommel
Can you please create a PR for it?

**Comment by bilalajanjua** [comment]
For @iamrommel and others who are still struggling to install Strapi on CapRover. I have finally found a solution. 

**With this solution you can run strapi on 1GB DigitalOcean instance too.** 👍 

**Here are the Steps:**

1. Install MongoDB (4) using One Click Installer on CapRover. Make sure to add env variable: `MONGO_INITDB_DATABASE  = strapi`. 
2. Create a New App inside CapRover, make sure to check the "Has Persistent Data" Checkbox. (I named the app "strapi"). 
3. Do the following Configurations in strapi app you just created:
    In `HTTP Settings`, **Set Container HTTP Post = 1337**,
    In `App Configs -> Environmental Variables`, set the following env variables:
    **DATABASE_HOST=srv-captain--alamantours-strapi-mongo
    DATABASE_PORT=27017
    DATABASE_USERNAME=<YOUR_MONGODB_USERNAME_FROM_STEP_1>
    DATABASE_PASSWORD=<YOUR_MONGODB_PASSWORD_FROM_STEP_1>
    DATABASE_NAME=<YOUR_MONGODB_INITDB_DATABASE_FROM_STEP_1>
    DATABASE_AUTHENTICATION_DATABASE=admin**
    
    In `App Configs -> Persistent Directories`, click "Add Persistent Directory":
    **Path in App = /api**, **Label = strapi-app**.
    Click on **Save & Update**.
4. Go to **Deployment** Tab in same strapi app and paste the following code under **Method 5: Deploy captain-definition file**:
    `{
  "schemaVersion": 2,
  "imageName": "jujiyangasli/strapi-docker"
 }`. and click **Deploy Now**.
    (Thanks to @juji for building the strapi image) 

That's it, the image will be deployed and the packages will be installed automatically. You can see the App Logs under **Deployment** tab too. Once it's done, you can access the app using the link provided in the **HTTP Settings** tab.  

---------------------------------------------------------------------------------------------------------------

@githubsaturn  Regarding one click app, when i tried upgrading the RAM to 2GB, it worked once. But after that, no new apps were installing for me. Even i tried changing the size of swap memory plus resizing the RAM to 4GB too, but it didn't work. It kept on showing me this: `./strapi.sh: wait: line 1: Illegal number:`. It is clear that the error is with Strapi docker image and not with the CapRover, and in the above method, i used the pre built image (by your suggestion on referenced issue) and it worked. So, maybe you can update the strapi one click app config to use the pre built image so that we can install new strapi apps by one click without following all the steps above everytime.

BTW, @githubsaturn Thank you so much for your efforts in building such an amazing PaaS tool. 💯

**Comment by FloMaetschke** [comment]
@bilalajanjua I have tried your solution and strapi starts up. - Nice.

But when i try the strapi tutorial i am unable to upload media files. In results in an error.
Any idea why this happens?

**Comment by bilalajanjua** [comment]
@FloMaetschke I faced the same issue because the uploads directory was missing. 

- Access the server via SSH.
- Goto `/var/lib/docker/volumes/<STRAPI_VOLUME>/_data/public/` and create an empty directory **uploads**. 
- Restart the app and it should work.

I'll update the image to the latest version and fix this issue too so you won't have to do it manually.

**Comment by githubsaturn** [comment]
**IMPORANT**
FYI - until Strapi fixes their problem you can use **this solution** https://github.com/caprover/caprover/issues/376#issuecomment-468132563

**Comment by githubsaturn** [comment]
# ---- Update ----

Since strapi doesn't seem to be very active in addressing their issues. I change the default implementation of strapi in CapRover and fixed the problem. No custom template is needed anymore.

**Comment by negati-ve** [comment]
One click strapi installs new codebase with only mongo

For folks who want to run their existing Strapi code base with an existing/separate Db container (Postgres, etc)

Just make a captain-definition file with the following content in your existing codebase
```
{
	"schemaVersion" : 2,
	"dockerfileLines": [
		"FROM strapi/strapi",
		"COPY ./ /srv/app",
		"EXPOSE 1337"
	]
}
```

PS. since Strapi has breaking changes almost every couple of months, we tend to run it in development mode

Hope this helps someone
@githubsaturn Thank you for building this beautiful platform

**Comment by matepaiva** [comment]
Hello, @negati-ve. I created the captain-definition as you recommended and the app is running. I can see via logs that the container is alright. But I can't access the web app.

So, it runs the Strapi server successfully, the database, etc. I also made a hello world example to test Nginx and it works. But when I try to access the Strapi endpoint, I get an Nginx 502 error. The request doesn't even touch the Strapi application (no access log), and the error appears only in the Nginx log. I think it has something to do with reverse proxy, but I am out of ideas about how to fix it.

The error in nginx:
```
2020/04/21 09:31:55 [error] 66#66: *33788 connect() failed (111: Connection refused) while connecting to upstream, client: 109.49.184.101, server: strapi.borashop.app, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.0.0.18:1337/favicon.ico", host: "strapi.borashop.app", referrer: "https://strapi.borashop.app/"
```

In Caprover web interface I have these settings:
- HTTP Settings » Container HTTP Port: 1337
- App Config » Port Mapping: 1337/1337

The latest logs in Strapi:
```
2020-04-20T22:04:14.238897613Z One more thing...
2020-04-20T22:04:14.239025086Z Create your first administrator 💻 by going to the administration panel at:
2020-04-20T22:04:14.239115563Z 
2020-04-20T22:04:14.239611696Z ┌─────────────────────────────┐
2020-04-20T22:04:14.239624411Z │ http://localhost:1337/admin │
2020-04-20T22:04:14.239627527Z └─────────────────────────────┘
2020-04-20T22:04:14.239746477Z 
2020-04-20T22:04:14.895126013Z [2020-04-20T22:04:14.894Z] debug HEAD /admin (12 ms) 200
2020-04-20T22:04:14.898086745Z [2020-04-20T22:04:14.897Z] info ⏳ Opening the admin panel...
```

Also, I wrote down the diffs between the default Nginx conf and the recommended Nginx conf by Strapi. Especially in the `location /` section. Below you see what is different between them (what one has that the other doesn't have)

1. Default Nginx conf file (currently being used):
```
location / {
  proxy_pass $upstream;
  proxy_set_header Host $host;
}
```

2. Strapi recommended nginx conf (https://strapi.io/documentation/3.0.0-beta.x/deployment/nginx-proxy.html):
```
location / {
  proxy_pass http://strapi;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Server $host;
  proxy_pass_request_headers on;
}
``` 

Do you have any clue what I need to change to make it work? I feel it's almost there, only missing some config. 

Thank you very much :)

**Comment by matepaiva** [comment]
Hello, please can anybody help?
