### ISSUE TITLE
[Deployment Issue] How to connect to created mySQL server from external app?

### ISSUE THREAD

**Issue by junaid33** [caprover/caprover#364]
**IMPORTANT:** DO NOT POST issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

I am trying to connect my created mySQL DB on Caprover to Prisma.io, but it keeps failing to recognize the DB. The app is exposed and I am linking directly to [appname].[app].fakeurl.com. When I go the that URL, I see NGINX 502 Error :/.

If applicable, content of `captain-definition` file:

Default one click app for mySQL

Steps to reproduce the problem:

Create a mySQL DB and try to link to external service or Prisma.

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
Does this answer your questions?
https://github.com/caprover/caprover/issues/145#issuecomment-360335470

**Comment by githubsaturn** [comment]
Also, you can read the docs:
https://caprover.com/docs/one-click-apps.html#connecting-to-databases

**Comment by hdriqi** [comment]
@githubsaturn hi, this is a little out of topic but for mongodb, it has configuration for bindIp only to localhost (for security purpose i think). perhaps we can create CLI to do port-forwarding (tunneling through ssh) to connect to app "locally".

**Comment by githubsaturn** [comment]
You don't need bindIp setting for MongoDB. CapRover uses docker for containerization. Each app runs in its own container and is only available tonother apps on the same CapRover cluster. CapRover uses a private network to connect all apps.


If you don't know what containerization is, think of it as multiple separate machines on a private network. Other machines can connect to your MongoDB machine and their IP is not localhost. Instead, it's just a private IP on a network.

**Comment by hdriqi** [comment]
@githubsaturn ah i see, thanks for the confirmation.

**Comment by githubsaturn** [comment]
@junaid33 

I hope my comment has answered your question. If it is not clear, please feel free to comment here again.

**Comment by buglinjo** [comment]
So there's no way to connect to DB without exposing it with `DataGrip` or `Sequel Pro` or similar app with ssh right? (I'm pretty new with Docker and CapRover)

**Comment by rylax** [comment]
> So there's no way to connect to DB without exposing its URL with `DataGrip` or `Sequel Pro` or similar app with ssh right? (I'm pretty new with Docker and CapRover)

Any answer on this?

**Comment by githubsaturn** [comment]
https://caprover.com/docs/database-connection.html

**Comment by newsaeta** [comment]
Hi, I'm trying the tool, but I can't access a database (mysql) externally. I have configured a firewall, I have even modified my.cnf, to allow external connections and I can't. Are there any limitations?

**Comment by githubsaturn** [comment]
There are no limitations on CapRover. Maybe your VPS provider has firewall rules that overwrite the settings on the OS.

**Comment by newsaeta** [comment]
Hi, thanks for your quick response. In my vps I have added the rules in the firewall. I have access to everything except the database. I can't access it from any external client.
![2022-11-27 17_05_33-Data Sources and Drivers](https://user-images.githubusercontent.com/29634448/204145042-56637b3b-7e78-4d2b-82c4-81b9d9e326bc.png)

**Comment by githubsaturn** [comment]
Check your configs. What does this print? (run on server)
```
docker service inspect srv-captain--yourdatabase-appname --pretty
```

Then run this on your local machine:
```
nc -zvw10 <your VPS publicIP> 3306
```
Or if you don't have `nc` installed on your local machine, try this:
```
curl <your VPS publicIP>:3306
```

**Comment by newsaeta** [comment]
Hi,
curl <ip vps>:3306
response: curl: (1) Received HTTP/0.9 when not allowed
------------------

Docker inspect

[
    {
        "Id": "69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3",
        "Created": "2022-11-27T12:39:52.541260202Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "mysqld"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 28663,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-11-27T12:39:56.945804003Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:eef0fab001e8dea739d538688b09e162bf54dd6c2bc04066bff99b5335cd6223",
        "ResolvConfPath": "/var/lib/docker/containers/69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3/hostname",
        "HostsPath": "/var/lib/docker/containers/69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3/hosts",
        "LogPath": "/var/lib/docker/containers/69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3/69666eb25783a8219b844e93db27a6bd9158faabc1886f130062fb1e7e4946b3-json.log",
        "Name": "/srv-captain--estethic-db.1.ym1ot756ms9snwxgl4949olr9",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "512m"
                }
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "default",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "captain--estethic-db-data",
                    "Target": "/var/lib/mysql"
                },
                {
                    "Type": "volume",
                    "Source": "captain--estethic-db-config",
                    "Target": "/etc/mysql"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/e23e995b0626a9ad0a777efcd3870bcb01fbe824c91f13a581c22a42ebab6990-init/diff:/var/lib/docker/overlay2/f634de8cc9df96e1a5a757fe463e51b8a894c4fb1d1a99966e79c8131ab1bfa6/diff:/var/lib/docker/overlay2/00e7b42550745bd54b2c5afa59ce9ebe8a0d9c84e31ce0ec0283bff4cb3e54be/diff:/var/lib/docker/overlay2/51eccfe15b181b4dd473f5f65abd6c4ba3a80521276d416705bc775dc08f44d8/diff:/var/lib/docker/overlay2/1bc0626871219a5e8af174540ea927b92a8b1546c2af432ef9cb0cc353cc5704/diff:/var/lib/docker/overlay2/ad820dfdbc1cefb2383bc3dfb0ece67a4f2dc2f6c27663391522eeaeeed8fcd1/diff:/var/lib/docker/overlay2/3c878d9cc1d8c69b672b26d9dcd910a71879fe08f62bbef173d3fd11d9a073ce/diff:/var/lib/docker/overlay2/e306178ab71cb1d58c6e93908092cbbf1fab734daa610f17f20e6c9b35c6cfc7/diff:/var/lib/docker/overlay2/891d8c42897853e95f98d4fe49f686f46d37180616e791ed6e76dc9cdc262d30/diff:/var/lib/docker/overlay2/2995831d32cc1e5d1cf6242b864ea9902a3f5f3ffe7c899bcf12a453f7ff0dcf/diff:/var/lib/docker/overlay2/bac829be829404233d3375f91a2c2a281d86ab25235075c27d9cb8c60b2552fd/diff:/var/lib/docker/overlay2/e26611cd5a789540a9e7d2e6f280c771cdb98479d70010dc84eae6d19ed2802a/diff",
                "MergedDir": "/var/lib/docker/overlay2/e23e995b0626a9ad0a777efcd3870bcb01fbe824c91f13a581c22a42ebab6990/merged",
                "UpperDir": "/var/lib/docker/overlay2/e23e995b0626a9ad0a777efcd3870bcb01fbe824c91f13a581c22a42ebab6990/diff",
                "WorkDir": "/var/lib/docker/overlay2/e23e995b0626a9ad0a777efcd3870bcb01fbe824c91f13a581c22a42ebab6990/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "captain--estethic-db-data",
                "Source": "/var/lib/docker/volumes/captain--estethic-db-data/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "captain--estethic-db-config",
                "Source": "/var/lib/docker/volumes/captain--estethic-db-config/_data",
                "Destination": "/etc/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "69666eb25783",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "33060/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXXXXX",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.14",
                "MYSQL_MAJOR=5.7",
                "MYSQL_VERSION=5.7.40-1.el7",
                "MYSQL_SHELL_VERSION=8.0.31-1.el7"
            ],
            "Cmd": [
                "mysqld"
            ],
            "Image": "mysql:5.7",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "l175kj0x70oxorxis70vsrv1d",
                "com.docker.swarm.service.id": "q6m8hfx0ii4lijwgpni092fm4",
                "com.docker.swarm.service.name": "srv-captain--estethic-db",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "ym1ot756ms9snwxgl4949olr9",
                "com.docker.swarm.task.name": "srv-captain--estethic-db.1.ym1ot756ms9snwxgl4949olr9",
                "randomLabelForceUpdate": "23bc9820-7ba0-473d-b072-d5362a85aab6"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "15195aac5ed7be146c5d582420da000182dda5ae58e532be7dbea73c59af57df",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": null,
                "33060/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/15195aac5ed7",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "captain-overlay-network": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.1.104"
                    },
                    "Links": null,
                    "Aliases": [
                        "69666eb25783"
                    ],
                    "NetworkID": "qxxdl2m4akq039n9i7qvdhi03",
                    "EndpointID": "f9f973ae0641b6f3402fc975018f222d31b06e93bd01e6170dab9bef5abf68ef",
                    "Gateway": "",
                    "IPAddress": "10.0.1.104",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:01:68",
                    "DriverOpts": null
                },
                "ingress": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.0.80"
                    },
                    "Links": null,
                    "Aliases": [
                        "69666eb25783"
                    ],
                    "NetworkID": "yokwlj0v40z1d560o7yjhtm1w",
                    "EndpointID": "89ecf9f0f9549942ae506955cafa9f57a02086c7a4df983909059bf436558654",
                    "Gateway": "",
                    "IPAddress": "10.0.0.80",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:50",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by newsaeta** [comment]
![image](https://user-images.githubusercontent.com/29634448/204146463-e59cd8f7-4453-4322-953b-ba0c7e958818.png)

**Comment by newsaeta** [comment]
nc -zvw10 <my vps ip> 3306
Respons Connection to <my vps ip> 3306 port [tcp/mysql] succeeded!

**Comment by githubsaturn** [comment]
So yea, as you can see, your connection is just successful, there is an issue with your local client trying to connect.

**Comment by newsaeta** [comment]
I have tried with Jetbrains DataGrip, and I have also tried with HeidiSQL

**Comment by newsaeta** [comment]
I have already found the problem, I was trying to access the database through the name in docker. But I had to do it through the ip. My big mistake.
Thank you very much for the help

**Comment by smyja** [comment]
> Hi, thanks for your quick response. In my vps I have added the rules in the firewall. I have access to everything except the database. I can't access it from any external client. ![2022-11-27 17_05_33-Data Sources and Drivers](https://user-images.githubusercontent.com/29634448/204145042-56637b3b-7e78-4d2b-82c4-81b9d9e326bc.png)
> 
> ![image](https://user-images.githubusercontent.com/29634448/204145120-b22e16e8-1563-4e5f-af88-c162567bb370.png)
This image resolved my issue, the two ports needed to be the same
