### ISSUE TITLE
[Deployment Issue] Adding file from host system to the container

### ISSUE THREAD

**Issue by macieklad** [caprover/caprover#365]
Hello, I'm currently developing a project which is being deployed to two environments: staging and production. I needed to provide some configuration at the build time, specifically env variables which are loaded by app.

The problem is, I cannot do so by providing them through admin panel, because they're set after the container is built. Then I thought about providing needed files on each server, which would then be copied into container, resulting in distinct configurations, but the captain is limiting the build context of docker, so I cannot access the filesystem to copy files, and providing any commands to docker is not an option too, as far as docs are concerned, if I am right. 

Lastly I thought about having multiple captain definition files locally, but they still need to be added to the repository, and rotated with env files accordingly to the deployment target. 

So my question is, is there a way to provide captain with some files at the build time, or any other way to do it properly ? I ended up with captain definition file below for the last version. 

Thank you for your support.

```
 {
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "FROM node:8.7.0-alpine",
                        "RUN mkdir -p /usr/src/app",
                        "ENV NODE_ENV staging",
                        "COPY ./src/config/staging/.env /usr/src/app/.env",
                        "WORKDIR /usr/src/app",
                        "COPY ./src /usr/src/app",
                        "RUN npm install",
                        "RUN npm run build",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

**Comment by githubsaturn** [comment]
Here is what you should do:

- Create two captain-definition files. `captain-definition.prod` and `captain-definition.staging`
- Change this line `"COPY ./src/config/staging/.env /usr/src/app/.env",` 
  - For `captain-definition.staging`: `"COPY ./src/config/staging/.env /usr/src/app/.env",` 
  - For `captain-definition.prod`: `"COPY ./src/config/prod/.env /usr/src/app/.env",` 
- In your production app, go to dashboard, go to app settings, go to deployment tab, at the bottom of the page, change default captain-definition to `captain-definition.prod`. Then do a similar thing for your staging app.


Your captain-definition looks good. You also need to make sure that you have these two files in your repository: `src/config/prod/.env` `src/config/staging/.env`
