### ISSUE TITLE
[Deployment Issue] GitLab private registry auth issue

### ISSUE THREAD

**Issue by devilcoders** [caprover/caprover#370]
What is the problem?

It's impossible to deploy an image from GitLab.com private registry. Setting up remote registry in cluster section doesn't help.

Here's the log output:

```
-------------------------
Sun Feb 10 2019 18:47:53 GMT+0000 (Coordinated Universal Time)
Build started for frontend An explicit image name was provided (registry.gitlab.com/handshake/handshake-se/frontend:latest).
Therefore, no build process is needed. Pulling this image: registry.gitlab.com/handshake/handshake-se/frontend:latest
This process might take a few minutes. Build has failed! 
----------------------
Deploy failed! Error: (HTTP code 500) server error - 
Get https://registry.gitlab.com/v2/handshake/handshake-se/frontend/manifests/latest: denied: access forbidden
```

Steps to reproduce the problem:

1. Build a docker image and store it on gitlab.com with
   `docker build -t registry.gitlab.com/<org>/<repo>/<image-name>:latest .`
2. Try to deploy it.

**Comment by githubsaturn** [comment]
Thanks for reporting this, it turned out to be a bug. Fixed in https://github.com/caprover/caprover/commit/1df46a7a4bb6760eed45cf023aab51ba77bf580e

Hotfix (v1.2.1) will be release in a few hours.

**Comment by crawfordleeds** [comment]
I'm having the identical issue using the cli v2.1.1: `docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG`.

I'm also using CapRover v1.8.0 on DigitalOcean in case that's of importance. Try to follow the [CI/CD Integration Guide](https://caprover.com/docs/ci-cd-integration.html).

Are there any other reports of this bug popping up? I'm new to CapRover, does anyone have any advice to debug?
