### ISSUE TITLE
1001 : Captain is not ready yet...

### ISSUE THREAD

**Issue by Two-Two-One** [caprover/caprover#377]
Please advise on how to go about this error

**Comment by githubsaturn** [comment]
It means that it hasn't finished booting up. Wait about 60 seconds and retry. If the issue persists, it means that CapRover cannot finish its start-up process. In that case, SSH to server and get the logs of CapRover from:
```
docker service logs captain-captain --since 5m
```

Please, copy and paste logs here for debugging.

**Comment by Two-Two-One** [comment]
<pre>captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:10.687 am    </font>Updating Certbot service...
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:13.711 am    </font>Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:16.716 am    </font>Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:19.722 am    </font>Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:22.727 am    </font>Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:25.738 am    </font>Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:28.746 am    </font>Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:31.757 am    </font>Retrying to get containerId for captain-certbot retry count:6
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:34.769 am    </font>Retrying to get containerId for captain-certbot retry count:7
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:37.779 am    </font>Retrying to get containerId for captain-certbot retry count:8
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:40.783 am    </font>Retrying to get containerId for captain-certbot retry count:9
captain-captain.1.qezlt7w6pt0f@toos    | <font color="#06989A">March 2nd 2019, 11:16:40.790 am    </font>Error: No containerId is found
captain-captain.1.qezlt7w6pt0f@toos    | Error: No containerId is found
captain-captain.1.qezlt7w6pt0f@toos    |     at /usr/src/app/built/docker/DockerApi.js:646:19
captain-captain.1.qezlt7w6pt0f@toos    |     at process._tickCallback (internal/process/next_tick.js:68:7)
</pre>

**Comment by Two-Two-One** [comment]
D                          NAME                    IMAGE                     NODE                DESIRED STATE       CURRENT STATE                 ERROR               PORTS
i4ap1n3e8xf8ah5fcq5gwjw0r   captain-captain.1       caprover/caprover:1.2.1   toos                Ready               Preparing 3 seconds ago                           
wimlsjws68ey4ji4rwdw7eer4    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 3 seconds ago                            
cunzwgge4bnpmsff996ljiwsm    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 56 seconds ago                           
iffox33a1uh2pw97lygd4uv7h    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete about a minute ago                       
qezlt7w6pt0fvhztufm71neba    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 2 minutes ago

**Comment by githubsaturn** [comment]
Certbot fails to run and it keeps restarting your CapRover.

What is your system spec? OS, RAM? VPS provider?

Also, run
```
docker service ps captain-certbot --no-trunc
```
and
```
docker service logs captain-certbot 
```

**Comment by githubsaturn** [comment]
Also, the logs that you copied is a truncated, can you please copy the lines before `Updating Certbot service` as well. Say 20 last lines before `Updating Certbot service`

**Comment by Two-Two-One** [comment]
ubuntu 18.04 desktop, 8gb of ram

ID                          NAME                    IMAGE                     NODE                DESIRED STATE       CURRENT STATE             ERROR               PORTS
p3zyehjzkw5jns8dvduxm067u   captain-captain.1       caprover/caprover:1.2.1   toos                Running             Running 39 seconds ago                        
lkdbhp55gbw6f92wg8d04gslg    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 50 seconds ago                       
i4ap1n3e8xf8ah5fcq5gwjw0r    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 50 seconds ago                       
wimlsjws68ey4ji4rwdw7eer4    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 50 seconds ago                       
cunzwgge4bnpmsff996ljiwsm    \_ captain-captain.1   caprover/caprover:1.2.1   toos                Shutdown            Complete 50 seconds ago                       
root@toos:/home/toos# docker service logs captain-captain --since 60m
captain-captain.1.ar1noivmeind@toos    | 
captain-captain.1.ar1noivmeind@toos    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.ar1noivmeind@toos    | > node ./bin/www
captain-captain.1.ar1noivmeind@toos    | 
captain-captain.1.ar1noivmeind@toos    | Captain Starting ...
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.805 pm    Emptying generated and temp folders.
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.813 pm    Ensuring directories are available on host. Started.
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.819 pm    Ensuring directories are available on host. Finished.
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.823 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.829 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.834 pm    Setting up NGINX conf file...
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.836 pm    Locking NGINX configuration reloading...
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.839 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.842 pm    Captain Nginx is already running.. 
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.845 pm    Updating NGINX service...
captain-captain.1.ar1noivmeind@toos    | March 2nd 2019, 5:37:07.855 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.q1jg2ef3c93g@toos    | 
captain-captain.1.q1jg2ef3c93g@toos    | > caprover@0.0.0 start /usr/src/app
captain-captain.1.q1jg2ef3c93g@toos    | > node ./bin/www
captain-captain.1.q1jg2ef3c93g@toos    | 
captain-captain.1.q1jg2ef3c93g@toos    | Captain Starting ...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.151 pm    Emptying generated and temp folders.
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.158 pm    Ensuring directories are available on host. Started.
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.165 pm    Ensuring directories are available on host. Finished.
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.171 pm    Network captain-overlay-network is already attached to service: captain-captain
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.178 pm    captain-captain (service) has already been connected to secret: captain-salt
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.185 pm    Setting up NGINX conf file...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.186 pm    Locking NGINX configuration reloading...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.190 pm    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.193 pm    Captain Nginx is already running.. 
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.196 pm    Updating NGINX service...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:15.205 pm    Waiting for 5 seconds for nginx reload to take into effect
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:20.212 pm    NGINX is fully set up and working...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:20.215 pm    Migration not needed, skipping.
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:20.220 pm    Captain Certbot is already running.. 
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:20.224 pm    Updating Certbot service...
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:23.243 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:26.254 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:29.258 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:32.262 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:35.268 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:38.275 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.q1jg2ef3c93g@toos    | GET / 200 6.053 ms - 2220
captain-captain.1.q1jg2ef3c93g@toos    | GET /static/css/main.c84fca49.chunk.css 200 13.183 ms - 1053
captain-captain.1.q1jg2ef3c93g@toos    | GET /static/js/main.cb91aff8.chunk.js 200 9.626 ms - 142121
captain-captain.1.q1jg2ef3c93g@toos    | GET /static/css/1.4003da56.chunk.css 200 14.358 ms - 288772
captain-captain.1.q1jg2ef3c93g@toos    | GET /static/js/1.71a308c8.chunk.js 200 8.170 ms - 1374327
captain-captain.1.q1jg2ef3c93g@toos    | GET /icon-512x512.png 200 8.232 ms - 59672
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:41.283 pm    Retrying to get containerId for captain-certbot retry count:6
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:44.289 pm    Retrying to get containerId for captain-certbot retry count:7
captain-captain.1.q1jg2ef3c93g@toos    | POST /api/v2/login 200 20.473 ms - 59
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:47.295 pm    Retrying to get containerId for captain-certbot retry count:8
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:50.301 pm    Retrying to get containerId for captain-certbot retry count:9
captain-captain.1.q1jg2ef3c93g@toos    | March 2nd 2019, 5:36:50.303 pm    Error: No containerId is found
captain-captain.1.q1jg2ef3c93g@toos    | Error: No containerId is found
captain-captain.1.q1jg2ef3c93g@toos    |     at /usr/src/app/built/docker/DockerApi.js:646:19
captain-captain.1.q1jg2ef3c93g@toos    |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by githubsaturn** [comment]
You forgot to run `docker service ps captain-certbot --no-trunc`

**Comment by Two-Two-One** [comment]
ID                          NAME                    IMAGE                               NODE                DESIRED STATE       CURRENT STATE                 ERROR                                                PORTS
1ej9ifkbjfaymbkiwmicnzh9q   captain-certbot.1       caprover/certbot-sleeping:v0.29.1   toos                Running             Preparing 9 seconds ago                                                            
lvfgvsdsqklgh11al2gffh8hf    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   toos                Shutdown            Shutdown 8 seconds ago                                                             
t6olkiwwuk4etcyc3mus8581p    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   toos                Shutdown            Shutdown about a minute ago                                                        
y8tmpeavdy547ch6ceywgc1u4    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   toos                Shutdown            Rejected about a minute ago   "No such image: caprover/certbot-sleeping:v0.29.1"   
6kzcjykm5mijppc3e6jf4rwck    \_ captain-certbot.1   caprover/certbot-sleeping:v0.29.1   toos                Shutdown            Shutdown about a minute ago                                                        
root@toos:/hom

**Comment by githubsaturn** [comment]
Alright, this is the cause: `No such image: caprover/certbot-sleeping:v0.29.1`

There is a problem with your Docker installation, it failed to load this image. But the image indeed exists:
https://hub.docker.com/r/caprover/certbot-sleeping

Regardless, this is a Docker issue and not a CapRover issue. See this for example:
https://github.com/moby/moby/issues/34351


Potential Solution 1)
Uninstall Docker and reinstall


Potential Solution 2)
Run `docker pull caprover/certbot-sleeping:v0.29.1`  to manually pull the image.

**Comment by Two-Two-One** [comment]
It has worked
