### ISSUE TITLE
Cannot set new webhook for github deployment

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#378]
Having a slight panic, rebuilding server after the main one failed.  Restore from backup has gone mostly OK, except that I'm need to get a new webhook for one of the apps, so that I can add it to the github repo.  But when I go on the deployment tab of the app concerned, it just takes me to a blank page... not the page where I can find the webhook to use.  Any ideas?

**Comment by githubsaturn** [comment]
Can you inspect the network on Chrome? To see what's happening? 

PS: the quickest disaster recovery might be to edit config file and remove the app. Restart caprover and create the app from scratch.

**Comment by githubsaturn** [comment]
The deployment page should never be blank.

**Comment by drmrbrewer** [comment]
I can't see anything on the network tab, but in console I get the following when I click on the Deployment tab of the app:

TypeError: Cannot read property 'repo' of undefined
    at t.value (Deployment.tsx:241)
    at si (react-dom.production.min.js:3447)
    at li (react-dom.production.min.js:3438)
    at hi (react-dom.production.min.js:3617)
    at Qi (react-dom.production.min.js:4685)
    at $i (react-dom.production.min.js:4706)
    at jc (react-dom.production.min.js:5099)
    at Hc (react-dom.production.min.js:5066)
    at Dc (react-dom.production.min.js:5481)
    at kn (react-dom.production.min.js:1731)

**Comment by drmrbrewer** [comment]
I've managed to switch to sending requests to another server, so panic averted to some extent.  Maybe best is to do what you say and just delete the app and start again.

**Comment by githubsaturn** [comment]
Ah that's making sense now. On mobile right now, but will provide more details in a few hours here. 

If you're in rush the quickest method is to do what I said above. Or wait an hour or two until I look into this and provide a probably better solution.

**Comment by drmrbrewer** [comment]
No hurry, thanks Kasra.  I've managed to get things back up and limping along.  A few loose ends to tidy up (quite a few actually) but at least the core functionality is back.

**Comment by githubsaturn** [comment]
I am not too sure about the details of your backup/restoration process. But from the look of it, your config file ended up with a non-null `appPushWebhook` but broken repo info.

To fix, you can simply remove `appPushWebhook` from the problematic app in the config file and restart CapRover.

PS: with v1.3 backup/restoration will be natively supported. It will be available soon. Once it's released, give it a real spin to make sure it's working as expected.

**Comment by drmrbrewer** [comment]
Ah, OK.  In my current backup/restore scripts I ensure that the `appPushWebhook` is set to an empty object, as follows:

      "appPushWebhook": {},

This is as per [this advice](https://github.com/caprover/caprover/issues/187#issuecomment-400872764).  But if I delete that line completely, and restart CapRover, sure enough I can now get to the Deployment page.  I guess that's where the 'undefined' error noted above results from?  CapRover is maybe attempting to read from the empty object, getting `undefined` from it, and then attempting to read other properties from `undefined`... and probably Captain had a check to avoid this?  Shall I change my scripts to remove the `appPushWebhook` line completely, or will you update CapRover to avoid the `undefined` issue?

Incidentally, in [this help section](https://caprover.com/docs/troubleshooting.html#how-to-restart-caprover) the suggestion is that you can restart CapRover by clicking "SAVE AND UPDATE CONFIGURATIONS" on "your app" page... is this right?  What app needs to be selected to update *CapRover* (rather than one of your own apps)?

**Comment by githubsaturn** [comment]
Change your script to remove appPushWebhook completely.


And that advice for restarting CapRover is an error in the docs and should be removed. 👍
