### ISSUE TITLE
Determining nginx upstream values for websocket sticky sessions 

### ISSUE THREAD

**Issue by uncvrd** [caprover/caprover#379]
I am working on an application that uses `socket.io`, I have it working perfectly on localhost, but when I deploy to caprover, I see a client side error of: `Error during WebSocket handshake: Unexpected response code: 400`. Since caprover is the awesome cheaper alternative to Heroku, I searched for socket.io deployments on heroku and found this:

> Apps using Socket.io should enable session affinity. If you plan to use node’s Cluster module or to scale your app to multiple dynos, you should also follow Socket.io’s multiple-nodes instructions.

Where session affinity is defined as:

> Session affinity, sometimes referred to as sticky sessions, is a platform feature that associates all HTTP requests coming from an end-user with a single application instance (web dyno).

Thus, my search for finding how to set up sticky sessions commenced. There's a nice article direct from socket.io explaining how to do so here: https://socket.io/docs/using-multiple-nodes/

After adding the `transports` option to my socket:

`const io = require('socket.io')(http, { transports: [ 'websocket' ] });`

I need to update my nginx config from my caprover dashboard. I am left slightly confused as to what I place as my variables and ports for the upstream section mentioned in the socket article. In the example provided they set:

```
upstream nodes {
    # enable sticky session based on IP
    ip_hash;

    server app01:3000;
    server app02:3000;
    server app03:3000;
  }
```

For my caprover app nginx, what goes in place of the `app01`? 

Is it my api url: https://releasehub.api.unearthapp.io?
My digital ocean ip?
My internal node app variable name: srv-captain--releasehub? 

As for the port, what do I place there? I don't have any ports mapped for the node app, and the default port is 80. 

Thanks for any insight!!

**Comment by githubsaturn** [comment]
Open your app's settings, edit default nginx config and add these flags:


```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
```



Here in this block:
```
location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```


From https://github.com/socketio/socket.io/issues/1942#issuecomment-82352072


Let me now if the problem still exists.

**Comment by uncvrd** [comment]
@githubsaturn making some progress I think, but not there yet, I updated my `location /` context in **CapRover Config Location in nginx container**:

```
        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

I am now presented with the following errors in my browser console:

`GET https://releasehub.api.unearthapp.io/socket.io/?EIO=3&transport=polling&t=Mar-crr 400 (Bad Request)`

And

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

What am I missing? Thanks!!

**Comment by githubsaturn** [comment]
No, you shouldn't change `CapRover Config Location in nginx container`

- Go to apps from the left side menu
- Click on your app (`releasehub` ?)
- The first tab is HTTP Settings
- There is a button called `Edit Default Nginx Configurations`
- Make your changes there.

**Comment by githubsaturn** [comment]
To revert your changes that you applied to global settings, just remove both `Base Config Location in nginx container` and `CapRover Config Location in nginx container` COMPLETELY, and click on Save and Update.

**Comment by uncvrd** [comment]
@githubsaturn ah good catch, okay so now my `releasehub` default Nginx config looks like:

```
        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

Same error still persists unfortunately: `GET https://releasehub.api.unearthapp.io/socket.io/?EIO=3&transport=polling&t=Mar-crr 400 (Bad Request)`.

As for reverting global changes, removing those 3 lines and saving will not fix? You are saying to remove **all** code within the text boxes for `Base Config Location in nginx container` and `CapRover Config Location in nginx container` so they're completely empty and then click save & update?

**Comment by uncvrd** [comment]
@githubsaturn I added the following line on my serverside node.js code and it appears to work..

`io.set('transports', ["websocket", "polling"]);`

Re my global config mess up earlier, I just want to make sure I fixed those properly before ending this thread.

**Comment by githubsaturn** [comment]
In terms of websockets, these 3 lines should be enough as far as I know:
```
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
```

Why it didn't quite work for you is a bit of mystery. You might have had some bugs in your code. I'll try to put together a barebone websocket app.


> As for reverting global changes, removing those 3 lines and saving will not fix? You are saying to remove **all** code within the text boxes for `Base Config Location in nginx container` and `CapRover Config Location in nginx container` so they're completely empty and then click save & update?

Yes, remove everything and save. Not even a single space character.

**Comment by uncvrd** [comment]
@githubsaturn I believe there is a discrepancy between barebones websockets and _socket.io_. So I guess those traditional transport options are necessary for the socket.io npm package compared to traditional websocket. Still new so might be way off haha. Maybe try to set up using socket.io on your barebones node server, let me know!

Ok, I'll remove everything from those inputs and click save & updated. Thanks!

**Comment by mromanuk** [comment]
I have `io.set('transports', ["websocket", "polling"]);`

and it works with those 3 lines! ^_^

**Comment by jappyjan** [comment]
i'm currently facing the same issues...
did you solve this problem @uncvrd ?
