### ISSUE TITLE
How to avoid docker caching while deploying 

### ISSUE THREAD

**Issue by Ashar2shahid** [caprover/caprover#381]
I am trying to deploy my application, using both a docker file and the CLI tool and I keep running into caching problem. Here is the contents of my captain file 

     
         
         "schemaVersion": 2,      
         "dockerfileLines": [
                        "FROM library/node:10-alpine",
                        "RUN apk update && apk upgrade && apk add --no-cache git",
                        "ENV NODE_ENV production",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "RUN git clone -b development my-repo",
                        "RUN mv amuconnect-react-client client",
                        "WORKDIR /usr/src/app/client",
                        "RUN npm install && npm cache clean --force",
                        "RUN npm run build",
                        "WORKDIR /usr/src/app",
                        "COPY ./ /usr/src/app",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]

As you can see there are commands like git clone and npm install that get cached when I redeploy my application and the latest version is not used instead the cached version is used. The same thing happens when I use dockerfile  and use method 4 of deployment. I keep running into it caching issues

```
FROM library/node:10-alpine
RUN apk update && apk upgrade && apk add --no-cache git
ENV NODE_ENV production
RUN mkdir -p /usr/src
WORKDIR /usr/src
RUN git clone -b development myrepo
RUN mv amuconnect app
WORKDIR /usr/src/app
RUN npm install && npm cache clean --force
RUN git clone -b development myrepo2
RUN mv amuconnect-react-client client
WORKDIR /usr/src/app/client
RUN npm install && npm cache clean --force
RUN npm run build
WORKDIR /usr/src/app
ENV PORT 80
EXPOSE 80
CMD [ "npm", "start" ]
```

I tried building the image myself with the new version tag but I dont know how to add it to caprover, since when i stop the current running container, it auto starts again. 

Any help would be appreciated, Thank you

**Comment by githubsaturn** [comment]
Before this line `RUN git clone -b development myrepo` add an ADD statement, like `ADD https://www.google.com /time.now`, So your Dockerfile becomes:

```
FROM library/node:10-alpine
RUN apk update && apk upgrade && apk add --no-cache git
ENV NODE_ENV production
RUN mkdir -p /usr/src
WORKDIR /usr/src
#  - - - - - - - - - - This quick hack invalidates the cache - - - - - - - - - - 
ADD https://www.google.com /time.now
RUN git clone -b development myrepo
RUN mv amuconnect app
WORKDIR /usr/src/app
RUN npm install && npm cache clean --force
RUN git clone -b development myrepo2
RUN mv amuconnect-react-client client
WORKDIR /usr/src/app/client
RUN npm install && npm cache clean --force
RUN npm run build
WORKDIR /usr/src/app
ENV PORT 80
EXPOSE 80
CMD [ "npm", "start" ]
```

**Comment by Ashar2shahid** [comment]
Thank you, this fixed it 👍

**Comment by Ashar2shahid** [comment]
although, i would like to know how does one use their own local image stored on the same machine as the docker instance.

**Comment by githubsaturn** [comment]
I can't understand your question. Do you mean building the image locally and pushing it to the server?

**Comment by Ashar2shahid** [comment]
yes

**Comment by githubsaturn** [comment]
You need to use `imageName`. See `docker deploy --help` for details. Your high level flow:
- On your local machine:
 ```
docker build -t dockerhubuser/myimage:v1.2.3 .
docker push myimage:v1.2.3
caprover deploy --imageName dockerhubuser/myimage:v1.2.3
```


This assumes that you have a working knowledge of Docker. Also
- Make sure to increment version `v1.2.3` otherwise if you use the same version, your app doesn't get update.
- keep in mind that if `dockerhubuser/myimage:v1.2.3` is hosted on a private Docker Registry, you first need to provide credentials to CapRover. Do so by navigating to CLUSTER and then click on ADD REMOTE REGISTRY. Make sure to disable DEFAULT PUSH REGISTRY after you set the remote repository. Otherwise, any image that is built on the server will be pushed to the registry.

**Comment by Ashar2shahid** [comment]
Thanks alot for your help 👍, when I get the time, i think ill help add these details to the official documentation
