### ISSUE TITLE
changing the URL of the application deployed with One click

### ISSUE THREAD

**Issue by Ashar2shahid** [caprover/caprover#382]
For example, I deployed a one click wordpress application with name news. Now i need the domain to be news.mydomain.com . Instead it is news-wordpress.mydomain.com, with no option to change it.

**Comment by Ashar2shahid** [comment]
Also an option to make it mydomain.com/news would be awesome too. I went throught the list of issues #138 
seems like it solves that but it didn't work.

```
 location /news{
        rewrite ^/news (.*) /$1 break;
        proxy_pass srv-captain--news-wordpress
    }
```
after adding it to my ngix configuration.

**Comment by githubsaturn** [comment]
You cannot, you should not change the default domain name. It's always `yourappname.root.domain.com`

You can always add many custom domains to your app though.

See https://caprover.com/docs/best-practices.html#hidden-root-domain

If you do this, then your default domain is `news-wordpress.something.root.domain.com`. Then you can go ahead and add as many custom domains as you want. You custom domain can be `news.domain.com`

**Comment by githubsaturn** [comment]
On the other hand if you want subroutes like `mydomain.com/news`. This is the process:

- Make sure your root domain is deep:  https://caprover.com/docs/best-practices.html#hidden-root-domain
- Create 2 wordpress apps, wp1 and wp2
- Assume you want to access them using `domain.com/app1` and `domain.com/app1`
- Create a "rerouting" app. Just simply create an app on dashboard panel, do not deploy any images for this app.
- Set custom domain for rerouting app to be `domain.com` 
- Now go to rerouting app's page, go to HTTP SETTINGS tab, then click on EDIT NGINX CONFIG and add this block:
```
 location /app1{
        rewrite ^/app2 (.*) /$1 break;
        proxy_pass srv-captain--wp1-wordpress
    }
 location /app2{
        rewrite ^/app2 (.*) /$1 break;
        proxy_pass srv-captain--wp2-wordpress
    }
```
Make sure this block is added in the right location, which is just below `set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;`

**Comment by githubsaturn** [comment]
PS: This was really an nginx question, please know that you need to know how to work with nginx before debugging issues that this rerouting can cause.

**Comment by Ashar2shahid** [comment]
Thank you for taking your time to answer your the question. I will go through this and post the results
