### ISSUE TITLE
Let's Encrypt Wildcard Cert

### ISSUE THREAD

**Issue by brewmanandi** [caprover/caprover#387]
I'd like to enable wildcard subdomain support for an app deployed on my CapRover instance with SSL. I already configured NGINGX to listen to all subdomains like this:

I added *. to the server_name
`server_name  <%-s.publicDomain%> *.<%-s.publicDomain%>;`

I am setting a variable
`set $subdomain "";
    if ($host ~ ^(.*)\.example\.com$) {
        set $subdomain $1;
    }
`

and adding the variable to the request

`proxy_set_header    X-Subdomain     $subdomain;`

What's missing now is to add a wildcard Let's Encrypt certificate to this app. Anybody has steps to achieve this? Of course it would be super awesome to integrate this into the dashboard.

**Comment by githubsaturn** [comment]
I believe this is what you're looking for:
https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by brewmanandi** [comment]
Hi, thanks. What I am actually looking for is a programmatic way to add domain aliases to an app. I would really like to have a CapRover API Key and an endpoint for this functionality. With a second endpoint I would like to trigger the Let's Encrypt process and with a third I would like to force https. Any chance?

**Comment by githubsaturn** [comment]
I see. This is not specific to wildcard DNS, but anyways, we don't have programmatic way yet. In near future, it'll come to CLI though.

**Comment by valoricDe** [comment]
Hi there, I did the same for the nginx configuration. But how does the certificate creation work for the wildcard domain?

**Comment by githubsaturn** [comment]
@valoricDe CapRover isn't a nameserver and therefore doesn't support generating wildcard domain certificates.

**Comment by githubsaturn** [comment]
This issue should have been close a long time ago as the CLI tool now supports [direct interaction with the API](https://github.com/caprover/caprover-cli#api)

**Comment by valoricDe** [comment]
For anyone wondering why caprover would need to be a nameserver to create wildcard domains: 
https://letsencrypt.org/de/docs/challenge-types/
Wildcard domains require a DNS-01 challange. In order to provide this caprover would need to be able to control the nameserver the domain runs on to create a TXT entry
