### ISSUE TITLE
Unable to find image 'caprover/caprove:latest' locally

### ISSUE THREAD

**Issue by basil2style** [caprover/caprover#388]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Whenever I try to run 'sudo docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprove', I am getting an error, 'Unable to find image 'caprover/caprove:latest' locally'. Docker is running and all other things are working fine.
I am using Mac OS X 10.13.6.
Thanks

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
sudo docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprove

Answers to the following questions where applicable:
- Your OS and version? Mac OS X 10.13.6
- RAM?      - 8GB

**Comment by githubsaturn** [comment]
This is really a Docker issue. The image indeed exists and it's publicly available:
https://hub.docker.com/r/caprover/caprover/tags

I would suggest you open an issue with them. Maybe your Docker installation is broken.

As a quick work-around you can pull images manually:
```
docker pull caprover/caprove:1.3.0
docker pull caprover/caprove:latest
docker pull caprover/caprover-placeholder-app
docker pull caprover/certbot-sleeping:v0.29.1
docker pull nginx:1

**Comment by githubsaturn** [comment]
Or wait! There is a typo in your command!
```
caprover/caprove:latest
```

the second caprover is missing an "r"

**Comment by basil2style** [comment]
Thanks @githubsaturn , I fixed the issue by: 
 _sudo mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover_
