### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by NoahFlowa** [caprover/caprover#390]
**IMPORTANT:** DO NOT POST issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Getting 403 Forbidden when trying to access my app.  It says I cant access ' / ' and its using port 80 even though I have SSL installed from LetsEncrypt.  Also, Im new to caprover, can I just not use this for static sites or is this more for the React/Angular devs?

If applicable, content of `captain-definition` file:
{
  "schemaVersion": 2,
  "templateId": "php/7"
}

Steps to reproduce the problem:
Go to chatversityapp.com

Answers to the following questions where applicable:
- Your OS and version?
Using Digital Ocean Marketplace Droplet.
- RAM?
Have 2GB, not even using 20%

**Comment by githubsaturn** [comment]
>  Im new to caprover, can I just not use this for static sites or is this more for the React/Angular devs?

CapRover is based on Docker. There is next to nothing that cannot be Dockerized. I noticed that you're using a php base image, you can try the php sample app to see how it's done. 
https://github.com/caprover/caprover/blob/master/captain-sample-apps/php.tar


My "guess" is that you probably have a .htaccess or some other access modifier that disallows access to your root `/`. Does you app work anywhere else?

**Comment by githubsaturn** [comment]
Also, try `http://chatversityapp.com/index.php`

**Comment by githubsaturn** [comment]
I see that your app is running. Congrats!


Closing this issue.
