### ISSUE TITLE
Allow OneClick Apps to be deployed from a personal repo

### ISSUE THREAD

**Issue by AnsonT** [caprover/caprover#395]
Allow the user to specify a different github repo to get one-click-apps from. This will allow the user to have personal one-click deployments that may not be ready to be published in the common repo.

**Comment by githubsaturn** [comment]
There is already an option for custom templates. The last option in the dropdown is `>>TEMPLATE<<` which you can select and copy and paste a custom made template.

Regarding serving from personal repos, it's not quite possible. It's not just the repo. The official repo gets built and published as a website. So serving from repo is not possible. Serving from personal website is possible, but considering the effort of publish a website vs just copy and pasting the template, it seems like the easier approach is the copy-paste approach.
