### ISSUE TITLE
Deploying via webhook initially reports failed deploy but later changes its mind

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#397]
I saw this a moment ago when a build was initiated via a change to a github repo linked to captain via a webhook:

![image](https://user-images.githubusercontent.com/9009792/55105476-882d6800-50c4-11e9-9d4a-a5060ed91852.png)

But the build completed fine some moments later, replacing the details for the same version number with something valid:

![image](https://user-images.githubusercontent.com/9009792/55105626-de9aa680-50c4-11e9-89c7-bc897bbd79fd.png)

I assume it shouldn't have reported a failed deploy to start with?

**Comment by githubsaturn** [comment]
I don't think it failed and it restarted the build out of the blue, right? It must be just the active build and the spinner that top should be visible.

There is still some improvements that can be made there to make this more clear that the build hasn't failed.

**Comment by rivonia** [comment]
No, so far as I can tell, the build was fine from start to finish.

**Comment by drmrbrewer** [comment]
No, so far as I can tell, the build was fine from start to finish.

**Comment by drmrbrewer** [comment]
Having said that, there was a short delay at the start, after the first indication appeared in the deploy panel that a build had started, before the build really seemed to kick off.

**Comment by githubsaturn** [comment]
> Having said that, there was a short delay at the start, after the first indication appeared in the deploy panel that a build had started, before the build really seemed to kick off.

Yes, refresh build status runs on an interval of a few seconds.
