### ISSUE TITLE
Domain wildcard setup

### ISSUE THREAD

**Issue by MeXaaR** [caprover/caprover#399]
**Hello everyone**

**What is the problem?**
I went on DigitalOcean to setup a CapRover instance and setup my domain name ( let say mydomain.com). I am redirected on mydomain.com instead of captain.mydomain.com

**Steps to reproduce the problem:**
install Caprover
setup your dns
add you domain in caprover (no CLI just with the interface)
enable https
force https 
and then you are redirected on the  domain you entered.

This is no biggy, but this is still a bug ;)

**Comment by githubsaturn** [comment]
Thanks @MeXaaR

So just to be clear:
- You entered domain.com as your root domain on the web dashboard
- clicked on enable https
- clicked on force https
- got redirected to domain.com
- you had to manually go to captain.domain.com and everything else was working fine.


Is this correct?

**Comment by MeXaaR** [comment]
Yes exactly. I tried it twice from the beginning and same thing happened

**Comment by githubsaturn** [comment]
Fixed. Will be released as v1.4

https://github.com/caprover/caprover-frontend/commit/65571a6db7e58af06c059740094edff3d013e84c
