### ISSUE TITLE
add read-only option at persistent directories

### ISSUE THREAD

**Issue by nicosmaris** [caprover/caprover#400]
**Is your feature request related to a problem? Please describe.**

I cannot make more complicated setups of custom nextcloud images based on the following.

https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml#L37

**Describe the solution you'd like**

Create a persistent directory at the caprover UI that is read only.

**Describe alternatives you've considered**

Migrating from caprover to docker-compose

**Additional context**

-

**Comment by githubsaturn** [comment]
Currently not all config parameters are supported in CapRover. This is by design to keep the UI simple.

If keeping the mount directory readonly is essential to your application, you can always use Predeploy functions. It allows to modify the service update object in any way that you want. https://caprover.com/docs/pre-deploy-script.html


There is also an active conversation on how to make these customizations easier in the future: https://github.com/caprover/caprover/issues/404#issuecomment-480111153

**Comment by nicosmaris** [comment]
Thanks for clarifying on the design choices.

Maybe supporting [docker stacks](https://docs.docker.com/get-started/part5/) is a better fit in the future as I wouldn't encourage [enhancing the pre-deploy script](https://xkcd.com/927).

**Comment by sneak** [comment]
@githubsaturn Is there any example code for how to amend the service update object for volumes like this?  I've never touched the docker API and don't know the shape (I checked the docs but they're confusing).

**Comment by githubsaturn** [comment]
@sneak 

it's pretty simple, have a look at this section for the structure of the service object:
https://docs.docker.com/engine/api/v1.30/#operation/ServiceCreate

Specifically, to set a volume or multiple volumes to read only you have to create something like this:

```
var preDeployFunction = function(captainAppObj, dockerUpdateObject) {
  return Promise.resolve()
    .then(function() {

      var mounts = dockerUpdateObject.TaskTemplate.ContainerSpec.Mounts;
      for (i = 0; i < mounts.length; i++) {
        var m = mounts[i]
        if (m.Target === "/some/path/in/container") {
          m.ReadOnly = true;
        }
      }
      return dockerUpdateObject;
    });
};
```

Now, click on Save and Update and you should be good! To confirm run `docker service inspect --pretty srv-captain-yourappname` and look for the volume.

PS: the script above is untested, but it should give you the idea.

**Comment by sneak** [comment]
Awesome, thank you! I’ll screw around with it and get it working. I’m going to try to ro mount the LE cert dir into some of my non-http services (eg ADC, irc, and znc) so they can use valid TLS instead of being self-signed. 

If I get it working I’ll post some recipes here.

**Comment by locvfx** [comment]
Awesome, thank you @githubsaturn
Here is my pre-deploy script for systemd enabled app

Path in App /sys/fs/cgroup
Path in Host /sys/fs/cgroup


```
var preDeployFunction = function(captainAppObj, dockerUpdateObject) {
  return Promise.resolve()
    .then(function() {

      var mounts = dockerUpdateObject.TaskTemplate.ContainerSpec.Mounts;
      for (i = 0; i < mounts.length; i++) {
        var m = mounts[i];
        if (m.Target === "/sys/fs/cgroup") {
          m.ReadOnly = true;
        }
      }
      return dockerUpdateObject;
    });
};
```

**Comment by 4abhinavjain** [comment]
> Awesome, thank you @githubsaturn Here is my pre-deploy script for systemd enabled app
> 
> Path in App /sys/fs/cgroup Path in Host /sys/fs/cgroup
> 
> Path in App /run Path in Host /run
> 
> Pre-Deploy Script
> 
> ```
> var preDeployFunction = function(captainAppObj, dockerUpdateObject) {
>   return Promise.resolve()
>     .then(function() {
> 
>       var mounts = dockerUpdateObject.TaskTemplate.ContainerSpec.Mounts;
>       for (i = 0; i < mounts.length; i++) {
>         var m = mounts[i];
>         if (m.Target === "/sys/fs/cgroup") {
>           m.ReadOnly = true;
>         }
>       }
>       return dockerUpdateObject;
>     });
> };
> ```

Hi locvfx, how did you deploy systemd-enabled apps? I think I am missing something in my docker installation? I am getting the following error-

**1000: Invalid volume name: /sys/fs/cgroup**

![image](https://user-images.githubusercontent.com/34500467/143843553-54684843-5a6c-45f5-b418-b4901bbff105.png)

**Comment by githubsaturn** [comment]
@4abhinavjain  - you need to click on "Set Specific Host Path". `/sys/fs/cgroup` is not a "label"

**Comment by 4abhinavjain** [comment]
> 

My bad, thanks for highlighting. It must have changed after I added the script.
