### ISSUE TITLE
Support app renaming 

### ISSUE THREAD

**Issue by dennisschott** [caprover/caprover#402]
Hey guys,

could you add app renaming please?
It would be amazing to have the chance to rename an app.

Background:
I renamed a project and the app name in CapRover doesn't fit the new app name.

Greetings,
Dennis

**Comment by prabirshrestha** [comment]
👍 I too face this issue sometimes.

**Comment by hamza-younas94** [comment]
App rename feature added in Latest CapRover Version: 1.4.0

**Comment by githubsaturn** [comment]
No. It hasn't been implemented yet. Probably you're confused with app description that's editable.

**Comment by hamza-younas94** [comment]
Sorry, my mistake

**Comment by githubsaturn** [comment]
Done. This feature is now available in 1.5.0
