### ISSUE TITLE
additional data fields for comments, owner etc.

### ISSUE THREAD

**Issue by tlwt** [caprover/caprover#403]
**Is your feature request related to a problem? Please describe.**
Amongst the development team we share an instance of caprover. We'd like to put down some comments on the deployed services like who set them up and why.

**Describe the solution you'd like**
The solution could be as simple as assigning env variables in the app config section (which we are misusing now), but any update leads to a restart (i guess).

**Describe alternatives you've considered**
see above

**Additional context**
none

**Comment by githubsaturn** [comment]
Implemented and will be released as v1.4.0.

The "restart" still happens as we currently don't have a separation between container updates and metadata update. This will change in the future and restart only happens if there is a change in container config and the restart is needed.
