### ISSUE TITLE
OneClickApps Pre-deploy Script/Hostname

### ISSUE THREAD

**Issue by tuefekci** [caprover/caprover#404]
**Is your feature request related to a problem? Please describe.**

I would like contribute more and started setting up some oneclick definitions than i realised there is an issue with some Images from different Vendors for this Example im using https://github.com/jhuckaby/Cronicle which runs perfectly fine in caprover but is not deployable via OneClickApps because it needs a setted hostname for the container which is not great but not really changeable without making a custom image which has it problems.

We had this before as an issue here https://github.com/caprover/caprover/issues/250

The other case is this request https://github.com/caprover/one-click-apps/issues/37 for Docker Mailserver which also runs perfectly fine with caprover but is mostly useless to implement as an oneclick cause it needs it setup.sh utitlity to be of any use so for example to be able to generate users etc. via the caprover interface there would be the need to attasch an pre deploy script. 

**Describe the solution you'd like**

let us set a pre-deploy script in the OneClick definition.

This probably can have bad effects or lead to misuse which can make problems but i dont see another way to handle all of this together.

**Describe alternatives you've considered**

let the Hostname be confiquirable or assigned automaticly to the default domain for the container (which probably can make problems in multi instance deployments im not sure) which solves atleast the cronicle problem which at the moment is not really solveable without manually updating the container the pre deploy script would than need to be manually set by the user which is safer but less comfortable.

**Additional context**

Im probably able to implement all of this myself but its not worth much if it doesnt get merged or there are issues im not aware of so i would like to have a discussion before i start to invest time into implementation.

Thanks.

**Comment by githubsaturn** [comment]
Customization of Docker containers has always been a challenge. We definitely don't want to bring all and ever single config parameters of Docker containers to the UI. That's the job for a "Docker GUI" application, such as portrainer. 

Predeploy function was created to address this need. But it's too generic and too complicated. It was a quick solution to fix everything. But looking at it now, I think we can do better. We can leave Predeploy function for more advanced config changes that requires logic switching based on some external factor.

But if all we want is to override some parameters in a Docker service, such as volumes (https://github.com/caprover/caprover/issues/400), and the ones that you mentioned, I think it's better to define an override object.

- In app config section, there is a free-text input for "Override Docker Service Config", user can enter a JSON object, for example:
```
{
     "TaskTemplate" : {
               "ContainerSpec" : {
                          "Hostname" :  "myawesomehost"
               }
      }
}
```

This override values get applied after just before predeploy function is getting called. Using this override method, we can eliminate the need to use complicated predeploy functions for a lot of cases.
