### ISSUE TITLE
Deploy from Github not being picked up after updating 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by Thibstars** [caprover/caprover#405]
Initially I was using CapRover 1.3.0 and had setup github deployment. Builds were properly initiated when a new commit was pushed to master.

I then updated to version 1.4.0 and didn't edit any deploy settings. After the update deploys where not being triggered automatically anymore (I have to initiate forced builds now).

Answers to the following questions where applicable:
- Your OS and version? Ubuntu Docker 18.09.2 (Digital Ocean)
- RAM? 2GB

**Comment by githubsaturn** [comment]
Hi @Thibstars 

Thanks for reporting this. Are you able to reproduce this problem reliably. I am a bit unsure whether this issue is actually valid or not. 

When you click on "Force Build" it actually simulates an HTTP call (similar to what github sends) to the CapRover backend. So if the "Force Build" works, I can't think of any valid case where the auto deploy doesn't work.

Please verify this one more time and if it turns out to be a valid issue, I'll look into this. 

Thanks.

**Comment by Thibstars** [comment]
Hi @githubsaturn 

Well, so far I could only check with one app, as that's the only one currently under active development. It is also difficult to reproduce, as it involves performing an update...

However, I checked multiple times with one app, even waited a day for a commit to be detected, but no success.

Maybe I can reset my deployment settings, but I thought I'd let you know I encountered this.

Regards,
Thibault

**Comment by githubsaturn** [comment]
Thanks again for reporting this. I'll keep this issue open to see if you or other encounter this issue.

**Comment by Thibstars** [comment]
Additional note: as DigitalOcean has migrated my droplet server, the whole instance got turned off and on again. This didn't affect the status of this issue in any way.

**Comment by githubsaturn** [comment]
Does it mean that you are still experiencing the problem? Github events are not being picked up by CapRover?

**Comment by Thibstars** [comment]
That is correct.

**Comment by githubsaturn** [comment]
I'd say the best option is to reset your deployment settings.
- Remove the github webhook, then "Save & Update"
- Add the webhook data again, then "Save & Update"
- Copy and Paste the "new" webhook to github.

Let me know if this doesn't work, and I'll write down a few steps to debug this further.

**Comment by Thibstars** [comment]
Thanks for the help. It seemed that somehow my webhook got removed on github... I re-added it and the ping works, so I'll assume that I'm good now.

Thanks for the swift follow-up!
