### ISSUE TITLE
Auto Deployment Notification 

### ISSUE THREAD

**Issue by hamza-younas94** [caprover/caprover#406]
HI,

I am thinking if we set up one of our application with git  for continuous deployment and multiple user push new code every hour so there should any kind of notification on success and failures like NetData notification.

Why i am saying because no one want to login in Dashboard every time to see whats going on like net data monitor and inform via notification.

**Comment by githubsaturn** [comment]
We already have a hook for pre-deploy custom scripts:
https://caprover.com/docs/pre-deploy-script.html

You can register an account on an email service like Mailgun, or an SMS service like Twilio and just send an http request to their API to fire an email or SMS or any other notifications that you desire.

**Comment by hamza-younas94** [comment]
@githubsaturn i am talking about notification like get notification on Slack or any other source like Net Data. i dont think this in some way related to pre deploy script.

**Comment by githubsaturn** [comment]
it is related. Notification from tools like slack are nothing more than an HTTP request to a Slack webhook. You can do this by sending an HTTP request to Slack inside your predeploy function.

**Comment by jappyjan** [comment]
what i'm missing in the pre-deploy script is access to some build metrics.

e.g.

- build start time
- build end time
- build success status
- error message/stack-trace on failure

**Comment by alexander-potemkin** [comment]
+
I'm also looking for a post-deployment script - I'm doing ChatOps thing and on other systems, I used to have actually a post-deployment report - if it was successful or not, if not - I want the logs for deployment.

It would be also nice to have a notification via Telegram or Slack in case of the runtime issues (with logs) - VERY handy at development.

Any chances to get that?

**Comment by githubsaturn** [comment]
It's on the radar. At some point, we'll have this: https://github.com/caprover/caprover/issues/727

**Comment by alexander-potemkin** [comment]
Thank you. Ideally, I would love to help a pre and post-deployment steps, or something like BitRise offers for they CI/CD.
Do you have any, probably - very rough, estimates?

**Comment by githubsaturn** [comment]
It's one of the top requested features, so hopefully in the next release. Depending on how much free time I get on my hand, maybe before summer.

**Comment by alexander-potemkin** [comment]
Thank you, appreciate it, and wish you a smooth and nice implementation! Love your product, a lot!

**Comment by louis-l** [comment]
Im looking for something similar to this. 

I have a Laravel app, and my approach (does not work at the moment) is to create an artisan command to push Slack notification. then call that command in `entrypoint.sh` file.

My entrypoint.sh file looks like this:

```
...

echo "🎬 send deploy success notification"
php artisan deploy:notification
```

However, it does not work at all after deployment.

I have tried to call the command manually (by ssh to the container) and it works. I even tried to write some logs in the artisan command to see if that even gets called or not after deployment. But nothing is written to log file.

Can anyone shed some light on this?

Thanks

**Comment by alexander-potemkin** [comment]
Hi @githubsaturn ! I understand you running it all best efforts, but your project is so cool I can't stop to use it, and get it more and more in use.

Is there happen to be any updates on this feature? It's like really a very missing thing in my production setup now.

**Comment by githubsaturn** [comment]
I've been too busy lately. But perhaps later in the summer I may have more bandwidth to add some new features.

**Comment by alexander-potemkin** [comment]
Thank you! Have a good summer!
