### ISSUE TITLE
It would be nice if we could modify NodeJS project start scripts

### ISSUE THREAD

**Issue by buglinjo** [caprover/caprover#407]
I'm having a problem with React project deployment. As we know React uses `npm run build` for production use. CapRover is running `npm start` automatically which is setting node environment to `development`. 

It would be nice if we could modify that in UI and set start scripts.

**Comment by githubsaturn** [comment]
You can definitely customize start script. If you want any customization, you can use custom Dockerfile:
https://caprover.com/docs/captain-definition-file.html#advanced-version
or
https://caprover.com/docs/captain-definition-file.html#use-dockerfile-in-captain-definition


Alternatively, we have a specific tutorial for React apps:
https://caprover.com/docs/recipe-deploy-create-react-app.html
