### ISSUE TITLE
captain42 does not work for new installations

### ISSUE THREAD

**Issue by samuelcecilio** [caprover/caprover#408]
What is the problem?

- The default password `captain42` does not work for new installations.
- Yesterday I repeated this same process on multiple servers and it worked perfectly.

Steps to reproduce the problem:

- Deploy and config a new server on Vultr (firewall, etc).
- Install docker and caprover.

Answers to the following questions where applicable:
- Ubuntu 18.04
- 2Gb

![img](https://user-images.githubusercontent.com/30150045/55897349-bae06180-5b96-11e9-8aa5-834abfb87565.PNG)

![img2](https://user-images.githubusercontent.com/30150045/55897366-c0d64280-5b96-11e9-9cdd-98c915bb21be.PNG)

**Comment by githubsaturn** [comment]
You can set a custom password by adding  `-e DEFAULT_PASSWORD='custompassword' ` to your installation script. Are you using this flag? 

Try using this flag to see if your custom password works. Your installation script will be:

```
docker run -e DEFAULT_PASSWORD='custompassword'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

And your password will be `custompassword`

**Comment by githubsaturn** [comment]
Also, can you try using Chrome?

**Comment by samuelcecilio** [comment]
In this screenshot I used chrome. I also tested with firefox.

**Comment by samuelcecilio** [comment]
It worked. Strange, on both servers I had done a clean install with Ubuntu 18.04 2Gb on Vultr (Docker 18.09.4) and `captain42` did not work.

```
docker service rm $(docker service ls -q)
docker swarm leave --force
docker system prune -a
rm -rf /captain

docker run -e DEFAULT_PASSWORD='please'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

**Comment by githubsaturn** [comment]
I just tried on [PlayWithDocker ](https://caprover.com/docs/play-with-docker.html) and captain42 worked fine. 

It is very unlikely, but some bad actor may have changed your password before you had a chance to change it! This is so very unlikely though. They need to know that you were installing CapRover on that particular server. Anyways, setting a custom default password is always a better option.

**Comment by samuelcecilio** [comment]
Very funny. Maybe because I was in public network. Anyway, thanks for the help (and patience when trying to reproduce).
