### ISSUE TITLE
Best way to create a duplicate environment?

### ISSUE THREAD

**Issue by tomexx** [caprover/caprover#409]
Hi,

what is the best way to duplicate an environment (e.g. for testing production before upgrading an actual production instance)?

I am using Scaleway VPS and I have an option to create a duplicate of the instance. However if I use custom domain and I force HTTPS, I am not able to login to Captain anymore. Is there a workaround for this?

Thank you

**Comment by githubsaturn** [comment]
See [Keeping Old Server](https://caprover.com/docs/backup-and-restore.html#keeping-old-server). Ignore the parts about creating and restoring backup as you're using ScaleWay to replicate your environment, not CapRover built-in backup.

Let me know if any of this is not clear and I can provide more details.

**Comment by githubsaturn** [comment]
Resolving this issue. Please feel free to comment if there is still any questions.
