### ISSUE TITLE
Backup of Databases

### ISSUE THREAD

**Issue by hamza-younas94** [caprover/caprover#410]
I was going through HeroKu documentation and i found great backup features of Database. Is is possble near future?  like heroku backup ?

heroku pg:backups:capture
heroku pg:backups:download

**Comment by githubsaturn** [comment]
For volumes you can use a third party solution:
>  Persistent Directories: Some apps, like databases, have a persistent directory. Since each database has its own backup mechanism. It is recommended to use the proper method of backup for your specific database, like mongodump for MongoDB or mysqldump for MySQL and etc. This is the best approach for databases as it does not cause a down time. The other approach is to create a snapshot of volumes. This approach is generic and works on pretty much everything. For example, you can use this 3rd Party Project. However, before running this, to avoid data corruption, you need to make sure that your containers are stopped docker service ls --format {{.Name}} | while read in; do docker service scale "$in"=0; done and then take a snapshot then resume all services docker service ls --format {{.Name}} | while read in; do docker service scale "$in"=1; done. In near future, CapRover will have a built-in solution like this.

See https://caprover.com/docs/backup-and-restore.html

**Comment by githubsaturn** [comment]
Tool for creating backup of volumes: https://github.com/loomchild/volume-backup

**Comment by hamza-younas94** [comment]
i have checked it but not nearly like to heroku backup. Volume Backup is a completely different thing;

**Comment by bleg** [comment]
If anyone else is having a problem to backup a postgres to S3 I found a very easy way to do it.
1. Create a new app this will be your backup app with a cron
2. Go to deploy with docker file and add:
FROM schickling/postgres-backup-s3:latest
3. In app configs set your environment variables according to the instructions here:
https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3

**Comment by itxtoledo** [comment]
> If anyone else is having a problem to backup a postgres to S3 I found a very easy way to do it.
> 
> 1. Create a new app this will be your backup app with a cron
> 2. Go to deploy with docker file and add:
>    FROM schickling/postgres-backup-s3:latest
> 3. In app configs set your environment variables according to the instructions here:
>    https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3

thank you
