### ISSUE TITLE
What's correctly way to install the php extensions and reload the Nginx server in a container?

### ISSUE THREAD

**Issue by alebak** [caprover/caprover#411]
What is the problem?

I have uploaded Joomla in tar package using CapRover web dashboard but when I try to install, Joomla say me that MySQLi is missing.

So I go to SSH console and I enter to container using this:

docker exec -it <container> bash

and then execute this command:

docker-php-ext-install mysqli && docker-php-ext-enable mysqli

But nginx don't take this extension or module. What's correctly way to install any php extension using CapRover web dashboard?

If applicable, content of `captain-definition` file:

{
    "schemaVersion": 2,
    "templateId": "php/7.2.1"
}

Steps to reproduce the problem:

Answers to the following questions where applicable:

- Your OS and version?
Ubuntu 18.04

- RAM?
1 GB

Hosted in DigitalOcean

![Joomla  Web Installer](https://user-images.githubusercontent.com/6515879/56236494-5cf8c180-604f-11e9-9f43-92d954380996.png)

**Comment by githubsaturn** [comment]
Simple way
Joomla it self has a Docker implementation: https://hub.docker.com/_/joomla/

To deploy Joomla:
- Create a one-click app for MySQL version 5.6
- Create another app (with persistence) and call it `joomla-main`
- Go to App Config for `joola-main` and set the following variables
   -  `JOOMLA_DB_HOST`   value: `srv-captain--yourmysqlappname` 
   -  `JOOMLA_DB_PASSWORD`   value: `the password you selected for MySQL one-click app`
- Click and Save and Update
- Next, go to Deployment tab, and copy and paste this `captain-definition` content (method 5)
```
 {
  "schemaVersion": 2,
  "imageName": "joomla:3-apache"
 }
```
- Finally, go to App Config tab again, and click on *Add Persistent Directory*
    - Path in App : `/var/www/html`    label:   `joomla-data`
- Click Save & Update

Done!

I haven't tested this and it works.

**Comment by githubsaturn** [comment]
Method 2:
If you want to go with your own approach and install the PHP extensions manually, you can create your own dockerfile and use the Dockerfile in captain-definition: https://caprover.com/docs/captain-definition-file.html#use-dockerfile-in-captain-definition

Your Dockerfile will be something like this:

```
FROM php:7-apache
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-install mysqli && docker-php-ext-enable mysqli

COPY ./ /var/www/html/
```

Use this method only if you are good with Docker stuff. It's more complicated that the method described above.

Please let me know if you are still facing problems.

**Comment by alebak** [comment]
¡Thank you for answer @githubsaturn!

I'm not sure of method 1 because many template providers offer with a quickstart Joomla package.

The method 2 it's the better option but I have deployed my Joomla project without these instructions into captain-definition file then... How to install and enable PHP extensions using the terminal?

I have ran this `docker-php-ext-install mysqli && docker-php-ext-enable mysqli `and doesn't work. Not loads the extension.

What am I forgetting? Restart the Nginx server?

**Comment by githubsaturn** [comment]
@alebak 

Docker filesystem is "ephemeral"... Meaning that after every restarts it resets to its original state. Therefore even if you install the extension using `docker exec -it ....`, after a single restart you will lose your changes.

If you want the installation of extensions to be "permanent", it must be in Dockerfiles (or captain-definition). 

The method that you're trying to use (`docker exec -it...`) will never survive a container restart. It will get reverted to the original container every time....

The recommended method is method 1. CapRover is built on Docker, and method 1 is the proper Docker way.


Also:
>I'm not sure of method 1 because many template providers offer with a quickstart Joomla package.

The image that I am using in method 1 is the official Joomla image.


Hope this answers your question.

**Comment by alebak** [comment]
Ok! I'm understanding... So, how to create a Captain definition file that contains these extensions?

Main requirements: Zlib Compression Support, XML Support, INI Parser Support, JSON Support, Mcrypt Support, MB Language = Default

Optionals requirements: https://docs.joomla.org/Optional_Technical_Requirements

**Comment by githubsaturn** [comment]
Have your captain-definition like this:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./myDockerFile"
 }
```

Then, also, create a file called `Dockerfile` with this content:
```
FROM php:7-apache
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-install mysqli && docker-php-ext-enable mysqli

COPY ./ /var/www/html/
```

I am not specifically familiar with your requirements:
> Main requirements: Zlib Compression Support, XML Support, INI Parser Support, JSON Support, Mcrypt Support, MB Language = Default

Having said that, you just need to find the proper installation commands for those requirements and add them to your Dockerfile. StackOverflow is usually the best place to ask these questions. On stackoverflow, ask how to add support for "Zlib Compression Support" given this Dockerfile, (make sure to copy and paste your Dockerfile content in your stackoverflow questions).

**Comment by alebak** [comment]
Let me see if I understand you... 

if I want to deploy Joomla using TAR method, Should I including captain-definition file and Dockerfile inside TAR file? Is it correctly?

On this subject:

> I am not specifically familiar with your requirements...

Only are php extensions.

**Comment by githubsaturn** [comment]
> if I want to deploy Joomla using TAR method, Should I including captain-definition file and Dockerfile inside TAR file? Is it correctly?

Yes, also keep the files that you originally had in the tarfile (your first comment).

Give it a shot and let me know.


Side note: Just to understand your requirement correctly. Why don't you want to use the simple method? (https://github.com/caprover/caprover/issues/411#issuecomment-483933417)?

**Comment by alebak** [comment]
> Side note: Just to understand your requirement correctly. Why don't you want to use the simple method? (#411 (comment))?

No, both methods are ok, but the problem that I having is installing and enabling the php extensions that Joomla requires.

I will try including captain-definition file and dockerfile into TAR file.

**Comment by githubsaturn** [comment]
Resolving this issue. Please let me know if the issue hasn't been resolved yet.

**Comment by Cristy94** [comment]
I have the same issue with WordPress and enabling pdo_mysql PHP extension. If I understand right, the "correct" way to do it is to modify the official WordPress APP package, create my own, write my own docker config to install the extensions and upload the tar file? Doesn't this defeat the purpose of CapRover of being able to set up apps easily just by using the interface?

Is there a way to simply append docker/bash commands from the app menu in caprover? So you can tell it "after the container is created, run those commands/set those settings"? This would also allow for persistently storing specific configuration per app easily.

**Comment by Cristy94** [comment]
> Is there a way to simply append docker/bash commands from the app menu in caprover? So you can tell it "after the container is created, run those commands/set those settings"? This would also allow for persistently storing specific configuration per app easily.

Nevermind, this is indeed possible.

Go to your App->Deployment ->  Method 4: Deploy plain Dockerfile

And you can "extend" the base image:

```
FROM wordpress:6.0.1
RUN docker-php-ext-install pdo_mysql
```
