### ISSUE TITLE
Fix mistake on customised NGINX file by the shell ?

### ISSUE THREAD

**Issue by qmidy** [caprover/caprover#412]
What is the problem?

Hi,

I did a mistake in my NGINX config file and so once the container is launched, it logs the error... This is fine...

The only problem I got is that i'd like to put back the default NGINX confi or at least access to the current file to modify it... I don't how to do that.

https://caprover.com/docs/nginx-customization.html

I tried to access it by here... But the containers are always restarting so I got kicked.

I've already made a lot of modifications in my NGINX so I'd love to be able to only modify it :)

Steps to reproduce the problem:

1 - Go to captain.root

2 - Modify the NGINX and made mistakes in it.

3 - Go to www.root and cry

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 18.04
- RAM ? 2 Gb

**Comment by qmidy** [comment]
I tried to restart CapRover and it's not changing anything. 

https://caprover.com/docs/troubleshooting.html

**Comment by githubsaturn** [comment]
Restart is not going to help. Do this:

- SSH to server
- Run `docker service scale captain-captain=0`
- Run `cp /captain/data/config-captain.json  /captain/data/backup-config-captain.json 
- Run `nano /captain/data/config-captain.json`
- Remove these two parameters from the json: `nginxBaseConfig` and `nginxCaptainConfig`, they should be toward the end of the JSON. Be careful with deleting, make sure the structure of JSON is valid, remove associated commas (`,`) as well.
- Run `docker service scale captain-captain=1`
- Hopefully your problem should be solve and you can be happy.


Please let me know if this solves your problem.

**Comment by qmidy** [comment]
FIRST OF ALLL !!! MANY THANKS :) (Merci beaucoup)

I changed a little bit these steps (but because i know where i made the mistake)

- SSH to server

- Run docker service scale captain-captain=0

- Run cp /captain/data/config-captain.json /captain/data/backup-config-captain.json

- Run nano /captain/data/config-captain.json

- At the end of the file, i correct the nginxBaseConfig

- Save the file

- Run docker service scale captain-captain=1

Happiness is real !

**Comment by bevinhex** [comment]
Can't find anything like 'nginxBaseConfig' within 'config-captain.json'

**Comment by githubsaturn** [comment]
Did you modify the root nginx config or an nginx config related to one particular app?

**Comment by bevinhex** [comment]
Sorry, for the late reply, was modifying nginx for particular app, then messed up whole nginx, then captain-captain service tries to check ssl certificate, due to no nginx functional, it keeps restarting as well
I didn't find 'nginxBaseConfig' anywhere, however I found something starts with 'Nginx*' within /captain/data/config-captain.json file, after removing all lines like that restored nginx to default.
Now my server is running fine, thank you.

**Comment by frederic117** [comment]
Hello,
i try to use this fix :
https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui
but i run it i get this : 
![image (2)](https://user-images.githubusercontent.com/28898064/101203503-0d736900-366b-11eb-9a91-5a3e9cce52f7.png)
Anyone can help me ?

Thanks a lot in advance

**Comment by githubsaturn** [comment]
Looks like you're running into the docker limit issue. 
- Create an account on Docker Hub
- `docker login` and enter your username/password
- Then retry

**Comment by frederic117** [comment]
thanks it work
