### ISSUE TITLE
[Deployment Issue] Failing to verify root domain

### ISSUE THREAD

**Issue by HansKristoffer** [caprover/caprover#413]
**What is the problem?**
I'm trying to install CapRover and connecting it to my domain, but I have problem with verifying it. The DNS is setup with an A-record with a wilcard (*.server.domain.com) which works through a browser (i can see a webpage from CapRover as a response). I can also through the domain see the admin panel on port 3000. The problem is, that when I'm trying to verify the root domain through the CapRover CLI I get a verification error, saying that CapRover "Error Code: 1107: Verification Failed". In the logs for the CapRover docker I can see that CapRover gets the request, but is then throwing an "Verification Failed". When I copy the link CapRover generate to verify the domain, and open it in a browser, it automatically downloads a "captain-identifier" file.

**Info**
Docker version: _19.09.5_
CapRover start command: _docker run -e MAIN_NODE_IP_ADDRESS='10.100.1.102' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover_
OS: _Ubuntu 18.04_
Router: _Port 80, 443, and 3000 are all forwarded to the server through the firewall (tcp only)_

The system is running on a VM with the IP 10.100.1.102

I have searched the internet and GitHub all day, but after trying for about 13 hours, I think I need external help... 

![Skærmbillede 2019-04-21 kl  00 47 57](https://user-images.githubusercontent.com/8282066/56463224-0cc38b80-63d0-11e9-9767-2383d737325b.png)
![Skærmbillede 2019-04-21 kl  00 49 41](https://user-images.githubusercontent.com/8282066/56463225-0cc38b80-63d0-11e9-9850-c90f903ed5a2.png)

**Comment by githubsaturn** [comment]
You don't need `MAIN_NODE_IP_ADDRESS` unless you're trying to install CapRover on a private network.

From your screenshot, I am seeing that you're using `5.186.58.132` as IP - which is a public IP and your server seems accessible from `5.186.58.132:3000`. 

So, try removing `MAIN_NODE_IP_ADDRESS` from the installation command, and things should work. Unless, you have a very special setup where `5.186.58.132` is a main server and you've installed Docker on a VM on that server.

If you're setup is a VM on a main server:
In this case, things get complicated and you cannot verify the domain. You have to override the verification precheck. Specifically override `skipVerifyingDomains` to `true`. Read [here](https://caprover.com/docs/troubleshooting.html#customize-config-settings) for instructions on how to override the prechecks. Let me know this solves your problem

**Comment by githubsaturn** [comment]
Closing this ticket as resolved. Please feel free to comment if the issue still isn't resolved.
