### ISSUE TITLE
how to disable direct access to a web site by ip address

### ISSUE THREAD

**Issue by l-lawliett** [caprover/caprover#414]
I am trying to configure the nginx conf file to block direct ip access but am failing to do so.
I av try to remove the -s.publicDomain or `  if ($http_host != "YOUR.DOMAIN") {
        return 403;
    }` butnothing seem to work.

**Comment by githubsaturn** [comment]
What do you mean by "block direct ip access"? What do you want to block? The CapRover dashboard or your apps?

**Comment by l-lawliett** [comment]
Like if I type my IP address in the browser I go to page that says "Nothing here yet :/" and the header title is Powered by Caprover how do i remove that page from my ip

**Comment by githubsaturn** [comment]
That's the default "catch-all" page. Go to settings, edit nginx (CapRover Config Location in nginx container). You will see a block that says: `Default catch-all page. e.g. if you enter SOME-RANDOM-CHARS.captainroot.domain.com`

DO NOT remove this catch-all. Custom domain verification relies on this catch all. However, it you're bother by "nothing here yet". You can simply find this block in catch-all section:
```
        location / {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }
```
and change it to this:
```
        location /.well-known/captain-identifier {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }
```

**Comment by l-lawliett** [comment]
Can this be done from the caprover for I don't see what you are reffering to I check the Http Settings

**Comment by githubsaturn** [comment]
Login to CapRover dashboard. Go to settings from the left hand menu. Find nginx config section. Click on edit default nginx config.

**Comment by ComputerCarl** [comment]
I am trying to use these instructions to change the catch all/create a custom 404 but I am having trouble understanding. if I create a web app named `catch-all`, which would be at `srv-captain--catch-all`, I would change the lines to read;
```
        location /.well-known/srv-captain--catch-all {
            root   <%-captain.defaultHtmlDir%>;
            index  index.html index.htm;
        }
```

This does not work for me.

**Comment by githubsaturn** [comment]
You shouldn't create a catch app web app. Catch all is being handled by CapRover. It's being used by CapRover for domain verification.

**Comment by posburn** [comment]
Using /.well-known/srv-captain--catch-all worked well for me. Thanks.
