### ISSUE TITLE
[Deployment Issue] - Multiple WordPress

### ISSUE THREAD

**Issue by AbdulSammad200** [caprover/caprover#415]
**IMPORTANT:** DO NOT POST issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Wordpress app giving 502 and logs are giving this error:
2019-04-22T09:08:41.866666876Z Warning: mysqli::__construct(): (HY000/1130): Host '10.0.0.2' is not allowed to connect to this MySQL server in Standard input code on line 22
2019-04-22T09:08:44.867975540Z 

If applicable, content of `captain-definition` file:
no captain-definition file was uploaded

Steps to reproduce the problem:
• Install wordpress using one click apps
• Wordpress will run fine
• Create another app and install wordpress with one click install
• New app won't run and who the error above

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu18.x
- RAM?
1 GB

**Comment by githubsaturn** [comment]
You may be using a stale volume. Remove your second WordPress and re-create it using a different name, like `second-wp-test`

Make sure you do not use a name that you previously used.

**Comment by githubsaturn** [comment]
Resolving this ticket. Feel free to comment if it's still a problem.
