### ISSUE TITLE
[Feature Request] Custom OneClickApp repository

### ISSUE THREAD

**Issue by Yub0** [caprover/caprover#416]
Hello,

I think it's good idea to add custom caprover one click app repository.

**Comment by githubsaturn** [comment]
What's the use case for this? Keep in mind, you can always use the `>> TEMPLATE <<` option from the one-click apps dropdown to use a customize one-click app template.

**Comment by Yub0** [comment]
I want to create own template to deploy private apps, internal use

**Comment by githubsaturn** [comment]
This is implemented and will be released in the next version.
https://github.com/caprover/caprover/issues/691
