### ISSUE TITLE
Ruby template for 2.6.3

### ISSUE THREAD

**Issue by Yub0** [caprover/caprover#418]
Hello,

I would like to know if is it possible to create ruby-rack template for ruby 2.6.3
I tested this, but i've got an error. Can we add version ?

Thanks

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover/commit/d9486fe81c73b003e6cd8d7eda0446faab0d8565

Will be released in the next version. Meanwhile, can use a simple Dockerfile:
```
{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM ruby:2.6.3-alpine",
    "RUN apk update && apk upgrade && apk add --no-cache make g++ git postgresql-dev",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",
    "COPY ./Gemfile /usr/src/app/",
    "RUN bundle install",
    "COPY ./ /usr/src/app",
    "ENV RACK_ENV production",
    "EXPOSE 80",
    "CMD [\"rackup\", \"config.ru\", \"--host\", \"0.0.0.0\", \"--port\", \"80\"]"
  ]
}
```
