### ISSUE TITLE
Remote registry causing a requested access to the resource is denied for CapRover image name convention

### ISSUE THREAD

**Issue by gregperes** [caprover/caprover#420]
Hello guys,

I'm using docker hub in CapRover and I'm getting this error while trying to push images 
requested access to the resource is denied
I realize that image names with double hyphen "-" cause this.

Can anyone help me?

Thanks!

**Comment by githubsaturn** [comment]
This is a bug in Docker Hub. Please report in their issue tracker. 

Double hyphens should be allowed as they are valid image names. https://github.com/docker/distribution/issues/1056

**Comment by githubsaturn** [comment]
Please update here when Docker team gets back to you. I am hoping they are not just blindly disallowing all double hyphens in Docker. If that's the case, we need a major refactoring to do on CapRover.

**Comment by githubsaturn** [comment]
Fixed: https://github.com/caprover/caprover/issues/454#issuecomment-517948742
