### ISSUE TITLE
How to change a created sub-domain?

### ISSUE THREAD

**Issue by softagon** [caprover/caprover#421]
Hi guys,

I have created the app  'wordpress' and the caprover make **something-wodpress.myserver.com**.  How can i remove the wordpress from the subdomain ? 

Kind regards,

Hermes

**Comment by githubsaturn** [comment]
Hi,

You shouldn't rely on the app name for your URL. Instead you should pick a deeper root domain for your CapRover, for example, use `capserver.domain.com` as your root domain. Then your wordpress becomes available as `something-wodpress.capserver.domain.com`. Now you can go ahead and Connect New Domains to this app:

![image](https://user-images.githubusercontent.com/10582082/57020953-c8aa6500-6bdf-11e9-873c-3a511172baaf.png)


You can add `mysite.domain.com` or `something.domain.com` or `anotherdomain.com` as custom domain to this app.

PS: you can change your root domain at any time, however, you may have to manually click on "Enable HTTPS" and "Force HTTPS" for your root domain.

Hope this answers your question, if it's still unclear, please let me know.

**Comment by atominvention** [comment]
I have created an app and want to connect new domain just like your example above.
For example, the app I created generated a domain like this:
myapp.server.mydomain.com

I want to connect this domain to:
myapp.mydomain.com

I created an A DNS record for myapp pointing to the server IP.
Then I input the domain and click connect new domain, it shows "1107 : Verification Failed."
Any ideas?

**Comment by githubsaturn** [comment]
First, confirm that all of the following conditions are correct:
- You have a root domain and your dashboard is accessible from `captain.server.domain.com`
- You have created an app called `myapp`. It is accessible from `myapp.server.domain.com`
- You changed your DNS settings for `myapp.domain.com` to point to IP of server.
- In your browser go to `myapp.domain.com`, you should see the default "Nothing Here" page.

If all the above statements are correct, the only other problem is the DNS propagation. It takes up to 24hr for DNS records to update. Please wait 1 day and retry. If it still doesn't work, please leave another comment here.
