### ISSUE TITLE
ssh connection error while trying to add a node

### ISSUE THREAD

**Issue by Schickedanz** [caprover/caprover#422]
I would like to run caprover with two nodes (one master and one worker) on some fresh initialized Ubuntu 16.4 vps's.
The docker setup runs without any error, caprover installation works like a charm afterwards and to be sure I deactivated the firewall on both systems (ufw disable).
I choose to run the registry locally (on master) and now I am trying to add a worker node by providing the necessary IP's and the worker privat key to caprover with no luck .
The system always gives me a nasty  "1000: SSH Connection error!"
Any Idea what could be wrong? Any help is really appreciated

**Comment by Schickedanz** [comment]
Solved: missed the step "ssh-copy-id" from master to client - works now perfectly

**Comment by r-chris** [comment]
Another example why documentation for this could need some improvement: https://github.com/caprover/caprover-website/pull/32
