### ISSUE TITLE
[Feature Request] Ability to pause an App

### ISSUE THREAD

**Issue by amanvishnani** [caprover/caprover#424]
When trying out multiple apps on a small instance of around 1GB memory one might consider pausing/freezing the app to free up memory for other apps.

A feature that can shut down the containers from the UI can be much more effective than terminating applications.

**Comment by githubsaturn** [comment]
It's already available. Navigate to App Config tab and change the instance count to `0`. When you want to resume the app, change instant count to `1` again.
