### ISSUE TITLE
AWS ECR Docker Registry don't work with '--' in ImageMaker.ts

### ISSUE THREAD

**Issue by rlanhellas** [caprover/caprover#425]
I'm trying to deploy my Image to AWS ECR but ImageMaker.ts use an invalid format of imageName:

```
const baseImageNameWithoutVerAndReg =
            'img-' + this.namespace + '--' + appName // img-captain--myapp
```

The '--' is not permitted by AWS. So, my suggestion is change to '-' or create a new param to let choose the separator between prefix and suffix.

**Comment by githubsaturn** [comment]
Same as
https://github.com/caprover/caprover/issues/420


Recently docker registries started applying this bizarre restriction. We'll have to change our separator.
