### ISSUE TITLE
Can't expose MySQL 3306 port

### ISSUE THREAD

**Issue by buglinjo** [caprover/caprover#426]
I'm trying to expose 3306 port to connect to MySQL client with SSH to my server. 
I have created MySQL One-Click-App and on `docker ps` it says: `3306/tcp, 33060/tcp`, so it's not exposed. I went to control panel and tried `Port Mapping`

![image](https://user-images.githubusercontent.com/1254208/57389890-1e0ae700-7189-11e9-947b-97e4c2423ac5.png)

After restarting the container it still says: `3306/tcp, 33060/tcp` instead of ` 0.0.0.0:3307->3306/tcp 33060/tcp`.

Is there a way to change the container startup script? I just want to add `-p 3307:3306` in arguments before starting the container.

**Comment by buglinjo** [comment]
Ohh, it's so weird... even though it does not say in `docker ps` but port mapping worked. I was able to connect to DB!

**Comment by githubsaturn** [comment]
The Port mapping is at Service level. You can view the mapped port via `docker service ls`
