### ISSUE TITLE
[Feature Request]Create New Cluster Node from DigitalOcean

### ISSUE THREAD

**Issue by acercobra** [caprover/caprover#427]
This is a ticket to track the progress of this feature. I will try to add this feature in my spare time for everyone like me that wish there was a way to spin off a new node from inside CapRover :)

**Is your feature request related to a problem? Please describe.**
I wish there was a way to create new nodes and added directly to CapRover from within the WebUI.

**Describe the solution you'd like**
In the cluster tab, we should be able to add DigitalOcean api key and allow the user to startup a new DigitalOcean Droplet from inside the webUI and add it to the LeadNode cluster.

**Describe alternatives you've considered**
Right now, the only alternative i can see is to go into the DigitalOcean and manually startup a new Droplet and then add it to the CapRover via the Cluster tab.

**Comment by acercobra** [comment]
Here some screenshots of what I have done so far. The idea is to make it generic enough that we can add other host providers like Linode, etc.. This feature is still in super early beta but i hope to get it done and working in like 3 weeks from now (I have full time job so i can't spend so much time on this project :)). All Suggestion are welcome :)

**My Plan**

- Add ability to save your Api Access for DigitalOcean. [_**Mostly Done**_]
- Get DigitalOcean Host Providing working. **AKA**: _Starting a droplet, installing caprover server, linking the leader node to the new started server._
- Add ability to choose which host plan to use to start the server.
- Change the button from "Add DigitalOcean Host" to something more generic like "Add Host Provider"
- Add Support for at-least one other host provider. Most likely "Linode"

![Screen Shot 2019-05-12 at 8 08 20 PM](https://user-images.githubusercontent.com/1417584/57589482-06699080-74f2-11e9-82cb-52938bfc871f.png)
![Screen Shot 2019-05-12 at 8 08 44 PM](https://user-images.githubusercontent.com/1417584/57589483-06699080-74f2-11e9-8d5a-7f4be7329f76.png)
![Screen Shot 2019-05-12 at 8 09 11 PM](https://user-images.githubusercontent.com/1417584/57589484-06699080-74f2-11e9-8541-9e8f21825a8f.png)
![Screen Shot 2019-05-12 at 8 09 26 PM](https://user-images.githubusercontent.com/1417584/57589485-06699080-74f2-11e9-9a2b-7335a066fd24.png)

**Comment by githubsaturn** [comment]
Great start!

Few thoughts:
- The host configuration only contains the host auth token, right? The actual node details still live under Nodes section?
- How do we make it clear that to add a Node, you don't "have to" have a preconfigured host config? Adding nodes using the plain and simple way works as well.
- Minor: Host Configuration is sort of misleading... Maybe VPS provider config or something similar?

**Comment by acercobra** [comment]
@githubsaturn Thanks for the feedback.

> The host configuration only contains the host auth token, right? The actual node details still live under Nodes section?

- Yeah, Only the host auth token will live in that section. I was planning to add an action button (_the little cloud button you see in the screenshot_) to allow the user to spin up a new node for that VPS provider from there. They will also be able to spin a new node from the Nodes section as-well. Still planning out on how that will look.

> How do we make it clear that to add a Node, you don't "have to" have a preconfigured host config? Adding nodes using the plain and simple way works as well.

- This one is a really good question and i don't know at the time on how to answer it (lol). I guess i can add a header text like how the "Docker Registry Configuration" section has stating that "adding Host Providers are optional"

> Minor: "Host Configuration" is sort of misleading... Maybe VPS provider config or something similar?

- I was thinking the same thing but couldn't decided on a good title/name for the section. So far the names i thought of are "VPS Host Providers", "Server Providers", or just simple "Hosts". If anyone has any suggestion on a good name that everyone likes, i can start using that instead.

> Change "Add Digital Ocean" button to something more generic, like "Add a VPS Provider Auth" or something similar. Then have the VPS Provider as a dropdown inside the dialog popup. Currently, the only item available is DigitalOcean.

- Yeah, I am already in the progress of doing just that. The text of the button for now will say "Add Host" until I decide on a name for the section.

> Make sure that the software architecture is built in a modular and extensible way such that adding new VPS providers are doable. In fact, I suggest adding at least one other provider to the list to make sure that we've built the system around this generic enough that supports extension.

- Yeah, I been duplicating the architecture used for the "Docker Registry Configuration" section to keep it consistent and familiar for anyone that is going to work on this later on. For the supported VPS providers, i decided to use "DigitalOcean" and "Linode" just to make sure that easy enough to add new host later on.

**Comment by pouledodue** [comment]
Adding Hetzner would be awesome

**Comment by 0c370t** [comment]
Will size/datacenter/image selection be included with this? It would be significantly more useful if you can select what size to spin up, instead of having 100 $5 hosts on DO; or having all your droplets in NYC3.

**Comment by githubsaturn** [comment]
I forgot to close this issue. This will be part of a bigger plan for a centralized manager that will be coming soon.
