### ISSUE TITLE
npm module - Client

### ISSUE THREAD

**Issue by pmc-sstaehle** [caprover/caprover#430]
Another idea would be to have a nodejs based cli client such as dockerode (https://www.npmjs.com/package/dockerode) for example.
I would really like to create an (node-) application with which i could manage the caprover api. With this you could create awesome things.

Cheers!

**Comment by Hazzard17h** [comment]
Already exists, see https://github.com/caprover/caprover-cli

**Comment by pmc-sstaehle** [comment]
Thanks for your reply, I know about caprover-cli. But my question was to have something available in node? Or am I missing somthing? In want to be able to develop these calls for example in a nest.js project and access the functions from there (like in dockerode). 
In my undestanding you can the caprover-cli "manually" but I want to send these commads as well "programmatically".

**Comment by Hazzard17h** [comment]
At this time there's not an npm package that can be imported and used in your own project, other than caprover-cli.
You could look into caprover-cli code to extract API definitions you need, or do something like `exec('caprover deploy ...', (err, stdout, stderr) => { ... })`.
Probably the best choice would be to refactor caprover-cli, to provide a node API surface, that is than used from the cli and also could be used by external programs importing the package.

**Comment by githubsaturn** [comment]
CapRover has an open API, it's not "officially" documented, but it's fairly easy to understand:
https://github.com/caprover/caprover-frontend/blob/master/src/api/ApiManager.ts

Anyways, regarding this issue, as @Hazzard17h mentioned, you can always do `exec('caprover deploy ...', (err, stdout, stderr) => { ... })`

Hopefully in near future, CLI will allow for custom API calls. That feature, combined with `exec` technique mentioned above, can be used to create any custom calls directly from a custom node code.

**Comment by githubsaturn** [comment]
This issue should have been closed a while ago as the CLI now supports direct API interactions: https://github.com/caprover/caprover-cli#api
