### ISSUE TITLE
[Deployment Issue] Change redis databases limit

### ISSUE THREAD

**Issue by aromero86** [caprover/caprover#431]
Hi guys, 

I'm new with Caprover. I am deploying a **Redis DB** (one click app) and I see I can set some **ENVIRONMENT VARIABLES**. I need change the databases limit (in redis.conf, I can change it with `databases`) but I can not find how to do it with **Caprover**. 

I tried with `REDIS_DATABASES` and `DATABASES` but I can't find the correct keyword.

Thank you and sorry about my poor english

**Comment by githubsaturn** [comment]
Redis one click app is nothing more than redis Docker image:
https://hub.docker.com/_/redis


To modify the redis.conf file, do this:
1) Create a `redis.conf` file and place it in an empty directory
2) Create a file called `Dockerfile` with this content:
```
FROM redis
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
```
Place this file next to the `redis.conf` file in the directory.
3) Create a `captain-definition` file with this content:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```
4) Ensure that the directory is a git directory by running
```
git init
git add -A
git commit -m "initial commit"
```
5) Deploy using `caprover deploy`


If you have any problem, please write another comment here.

**Comment by aromero86** [comment]
Hi @githubsaturn, thank you. Finally got what I wanted. I just had to publish this Dockerfile (Caprover deploy method 4)

```
FROM redis:5
CMD [ "redis-server", "--databases", "50", "--requirepass", "MYSTRONGPASSWORD" ]
```

Thank you! 😃
