### ISSUE TITLE
How do i deploy an app under a different route rather than at a subdomain?

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover#432]
So I have a backend and a frontend server and I'm looking into deploying it.

I currently have my custom nginx reverse proxy config which does the following

```nginx
        location / {
                proxy_pass                      http://localhost:3000/;
        }

        location /api {
                proxy_pass                      http://localhost:8000/;
        }
 ```

So I can access my backend by going to `my-app.my-domain.com/api` and my frontend at `my-app.my-domain.com/`

How can I do the same using caprover? I would rather not want to have `backend-my-app.my-domain.com` and `my-app.my-domain.com`.

**Comment by githubsaturn** [comment]
By default the proxy path for CapRover is defined using a variable called "upstream", specifically, in your frontend app's settings, you have default nginx config as:

```
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```

Change this to the following:
```
        set $upstreamfrontend http://<%-s.localDomain%>:<%-s.containerHttpPort%>;
        set $upstreambackend http://srv-captain--my-backend:8000;

        location / {
            proxy_pass $upstreamfrontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api {
            proxy_pass $upstreambackend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```

Notice how we used `srv-captain-my-backend`. In general, all apps should be prefixed with `srv-captain--` when they are referenced to in nginx config.

**Comment by githubsaturn** [comment]
If you need more details, please let me know.

**Comment by fr3fou** [comment]
Where would I configure this? In a per app basis? Or in the global nginx config?

**Comment by fr3fou** [comment]
Also would there be any plans in the future for such configuration to be easily set from the dashboard?

**Comment by githubsaturn** [comment]
> Where would I configure this? In a per app basis? Or in the global nginx config?

In app. Specifically, since you want root `/` to be served as your frontend, I would recommend you only change the frontend config. Simply go to app and click on Edit Default Nginx Configurations.


> Also would there be any plans in the future for such configuration to be easily set from the dashboard?

No, because there are infinite number of ways that users may want to configure their app and having a specific UI element for each configuration is confusing. Other services, such as Heroku, also avoid having such a control. In contrast to Heroku UI, CapRover allows the nginx config to be completely customizable - if the default nginx config is not something that satisfies the need of the user, they can always modify the details to achieve what they want.

**Comment by fr3fou** [comment]
Thanks for the extremely fast replies! I'll try to deploy my app using CapRover today!

**Comment by fr3fou** [comment]
So this doesn't seem to be working. I can get the request to be `proxy_pass`-ed to the backend, but it doesn't append any parameters after the `/api/`.

For example 
`GET https://my-domain.com/api/ -> http://srv-captain--my-backend:8000`
^this works fine, however
`GET https://my-domain.com/api/categories -> http://srv-captain--my-backend:8000`
^this doesn't work, the `/categories` doesn't get sent through.

Here's my nginx config:
```nginx
        set $upstreamfrontend http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {
            proxy_pass 		 		$upstreamfrontend;
            proxy_set_header 		Host $host;
            proxy_set_header 		X-Real-IP $remote_addr;
            proxy_set_header 		X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header 		X-Forwarded-Proto $scheme;
        }

        location /api/ {
        	proxy_pass 				http://srv-captain--luncherbox-backend:8000/;
			proxy_http_version		1.1;
			proxy_set_header		Upgrade                 $http_upgrade;
			proxy_set_header		Connection              "upgrade";
			proxy_set_header		Host                    $host;
			proxy_set_header		X-Real-IP               $remote_addr;
			proxy_set_header		X-Forwarded-For         $proxy_add_x_forwarded_for;
        }
```

**Comment by fr3fou** [comment]
I've tried other combinations such as

```nginx
location /api {
	proxy_pass 				http://srv-captain--luncherbox-backend:8000/	
}
```

```nginx
location /api {
	proxy_pass 				http://srv-captain--luncherbox-backend:8000	
}
```

```nginx
location /api {
	proxy_pass 				http://srv-captain--luncherbox-backend:8000/
}
```

*notice the trailing slashes*

**Comment by fr3fou** [comment]
OK what

for some reason after retrying all of the aforementioned combinations, it suddenly works (?????????????????)

**Comment by derek-adair** [comment]
>for some reason after retrying all of the aforementioned combinations, it suddenly works

Welcome to sys admin.  probably something either cached or not building.
