### ISSUE TITLE
Build angular app in separate node

### ISSUE THREAD

**Issue by aromero86** [caprover/caprover#436]
Hi guys, first of all, sorry about my poor english...

We are creating a web app using a NodeJS backend and two frontend projects with angular. Also we need Redis, MySQL & Mongo. My idea is use Caprover and create two environments (stagging-production). I want use autodeploy from github for angular projects but building is slow (the project is big) and requires a lot of resources. I'm using [this repo](https://github.com/JacobSamro/caprover-angular-sample) as example: 

I'm worried about use same machine for building app and serve all apps. These compilations could slow down my environment. 

Can I use a cluster separate node only for angular builds?.  Any idea/workaround for this?

Thank you

**Comment by qmidy** [comment]
Hi,

Have you tried this ?

--> https://www.agiratech.com/how-to-deploy-angular-application-to-heroku/

The idea is to push the dist from 'ng build' and an express server in front of it.
The server.js will forward the requests to the dist.

So you just have to build a classic Node docker image.

NB : the article is for Heroku, but Caprover works the same.

**Comment by aromero86** [comment]
I tried something similar, bu this requires:
1. Local building
2. Bin files on repo

Thank you for response 😃

**Comment by qmidy** [comment]
Yes you'll need to build locally... But you'll save resources for build on the server. 

It's not the perfect solution I know haha

**Comment by aromero86** [comment]
I see @githubsaturn marked "Build on a different machine" as done in Github project. Where can I find info about this?

**Comment by githubsaturn** [comment]
Does this answer your question?
https://caprover.com/docs/recipe-deploy-create-react-app.html

Using this technique, you can build on your local machine and send the built package to the server.


Regarding this:
> I see @githubsaturn marked "Build on a different machine" as done in Github project. Where can I find info about this?

Yes, this is done, as one of the possibilities to be used in Captain Definition file is `imageName`. This method is more advanced, but the steps are like this:
- You have a build pipeline (Continuous Integration CI) like TeamCity or Jenkins where you can build a Docker image
- You have a private Docker repository where your private images are built and pushed to that repository
- You have setup your private repository in your CapRover dashboard such that it has access to the private docker repository.

Then you push your new changes to your git repo (github, bitbucket, gitlab and etc... Your CI picks up the change and builds and pushes your docker image to your private repo, also it sends a signal to CapRover to build using the new `imageName` defined in captain definition. 


This method is more advanced and only suggested if you are comfortable with theses steps.

**Comment by aromero86** [comment]
I understand. I'll try second option. It seems interesting. Thank you

**Comment by aromero86** [comment]
Hi guys,

   we finally use **Gitlab CI**. Our custom runner build the app and uses **Caprover Cli** to upload it

Thank you

**Comment by derek-adair** [comment]
SOOO brilliant.  Was just wondering how to do something like this.

**Comment by derek-adair** [comment]
[Relevant docs](https://caprover.com/docs/deployment-methods.html#automatic-deploy-using-github-bitbucket-and-etc)
