### ISSUE TITLE
502 from all apps not on the manager in cluster mode

### ISSUE THREAD

**Issue by airways** [caprover/caprover#438]
What is the problem?
All services which are placed on nodes other than the manager node in our 3 node cluster return a 502 error when we attempt to access the services via HTTP.

If applicable, content of `captain-definition` file:

This occurs with all apps we deploy to the cluster, including all one click apps such as adminer.

Steps to reproduce the problem:
1. Create single node cluster
2. Deploy apps to it
3. See that they work
4. Add second and third cluster node according to instructions: https://caprover.com/docs/app-scaling-and-cluster.html
5. Scale apps to 0, then back to 1 to get them moved onto other nodes in the swarm -- or deploy a new app
6. Apps deployed to nodes other than the manager always return 502

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 16.04.2 LTS
No firewall enabled

- RAM?
Node 1:
```
              total        used        free      shared  buff/cache   available
Mem:           7.8G        346M        2.3G         89M        5.2G        7.0G
Swap:            0B          0B          0B
```

Node 2:
```
              total        used        free      shared  buff/cache   available
Mem:           7.8G        173M        2.6G         19M        5.0G        7.3G
Swap:            0B          0B          0B
```

Node 3:
```
              total        used        free      shared  buff/cache   available
Mem:           7.8G        157M        4.2G        8.7M        3.5G        7.3G
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
This only happens if firewall is enabled. Are you sure the OS level firewall is disabled?

Just to be sure, run this command on all nodes (manager and other nodes)
```
ufw disable
```

**Comment by airways** [comment]
Use was definitely inactive. But, I think _maybe_ the issue was AWS Security Groups having the same effect — ports 80 and 443 were allowed only from my own IP and from the security group itself — which would seem to be sufficient but it’s possible something else was going on as well. I found this out finally while attempting to setup a larger single node CapRover machine on the same account to see if performance would be acceptable and if we could sidestep the cluster issues. I’m planning to try a new cluster armed with the idea that our security groups aren’t setup properly still, and see if it solves the issue noted here.

**Comment by githubsaturn** [comment]
Yes, it well could be the unique AWS security groups. Unfortunately, the VPS is completely unaware of AWS security group as they are not part of the OS level settings. This can cause problems. I suggest you try reproducing the environment on a more flexible environment, DigitalOcean for example, and if everything went smoothly, then you can conclude that it's indeed AWS specific problem.
