### ISSUE TITLE
[Feature Request] Enable websockets from UI

### ISSUE THREAD

**Issue by SkaterDad** [caprover/caprover#439]
Thanks for this awesome project!  I had been trying to setup a docker swarm server myself, and deployments and config management were really tripping me up.  👍 

As I was setting up a Node server, I needed websockets, so I used the option to modify the default nginx config and added the two headers.

How would you feel about exposing that as a simple checkbox option in the UI?
```
[ ] Enable websockets
```

Which would then apply these headers?
```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
```

**Comment by githubsaturn** [comment]
Done (https://github.com/caprover/caprover/pull/476), thanks to @sean-nicholas 

Will be released with v1.5.0. Currently available on edge version: https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version

**Comment by drmrbrewer** [comment]
@githubsaturn I note that v1.5.0 is now released.

I'm adding the above two lines to my custom nginx config, but with one extra... see [here](https://github.com/caprover/caprover/issues/186#issuecomment-367943102).  Do I still need the custom config, or can I use the new UI checkbox?  Not sure of the significance of the extra line I'm using that's not apparently applied with the new checkbox:

    proxy_http_version 1.1;

**Comment by githubsaturn** [comment]
The http version is also added as part of this feature, so you should be good to go:

https://github.com/caprover/caprover/blob/d7ab3013df0522aa87567fa250a6ee40d24136f7/template/server-block-conf.ejs#L84
