### ISSUE TITLE
[Feature Request] Detect and Use Keybase for Git

### ISSUE THREAD

**Issue by DonaldKBrown** [caprover/caprover#440]
**Is your feature request related to a problem? Please describe.**
Most of my repositories are stored inside encrypted Git repositories created through Keybase. As such, I have to deploy to CapRover using the `caprover deploy` command after my git pushes. This is fine, but it would make it just a tiny bit smoother if I could just push to the repository and have CapRover kick off the build process like it would if I were using GitHub or BitBucket.

**Describe the solution you'd like**
I would like if CapRover could detect a running Keybase installation and give options to connect to one of those detected repositories for deployment through git.

**Describe alternatives you've considered**
Right now, I'm using the plainly obvious alternative of just using `caprover deploy`. My only other alternative would be switching to an alternate Git provider and not using Keybase.
*Edit:* I suppose I could also just add a pre-push hook so that the deploy runs with each push, but this is still a feature request I would like to see :)

**Comment by golyalpha** [comment]
I feel like the GitHub/BitBucket integration relies on webhooks or some other way these service notify CapRover that the repo has been updated, and AFAIK Keybase's Git repositories have no such functionality.
