### ISSUE TITLE
Multiple Dockerfiles / captain-definition in a single project

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#441]
Hey there! Thanks for this wonderful project!
 
I'm trying to deploy a django app with celery workers.

I wish to use separate caprover apps for the celery worker and the django app.

Since both apps share the same codebase, I was hoping to just create 2 separate dockerfiles for each of them.

So, both dockerfiles will be identical excpet the last line.

*celeryDockerfile*
```
...
CMD ./run_celery.sh
```

*djangoDockerfile*
```
...
CMD ./run_django.sh
```

What would be the recommended way to do this in caprover?

---

In case you're not familiar with the celery thing, think of it as a normal web server, but with different workers that need to be deployed separately for the app to work as a whole.

**Comment by githubsaturn** [comment]
You're on the right track. Just create two separate captain-definition and two separate app. When you run `caprover deploy` depending on what app you're deploying, it'll pick the right captain-definition.

Since you almost always need to deploy these two together, I suggest you write a small bash file which runs the two deploy for you, something like:
```
#!/bin/sh
caprover deploy --appName celery-app-name --host ..... --pass ....--branch ....
caprover deploy --appName django-app-name  --host ..... --pass ....--branch ....
```

**Comment by devxpy** [comment]
Awesome, thanks!

**Comment by devxpy** [comment]
FTR, I ended up using this -


```
for service in "django" "celery"; do
    echo  -e "\ndeploy service: $service \n"
    echo "CMD ./runserver.sh $service" >> Dockerfile
    caprover deploy --appName service
    sed -i.tmp '$ d' ./Dockerfile
done

rm Dockerfile.tmp
```

**Comment by devxpy** [comment]
Is there any way I can do this by not maintaining two branches? Feels like a lot of work...

**Comment by githubsaturn** [comment]
Why would you need multiple branches? Just have two captain-definition files:

https://github.com/caprover/caprover-cli/issues/17#issuecomment-500136010

**Comment by devxpy** [comment]
Oh right, I thought you used the --branch switch for that purpose. Thanks again!

**Comment by devxpy** [comment]
I wonder if there's a possibility of integrating [dockerfile-template](https://www.npmjs.com/package/dockerfile-template) into caprover.
