### ISSUE TITLE
[Deployment Issue] Minio one click app has weird behavior

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#443]
Hey there!

I'm trying to deploy the minIO on-click app.

I am able to access the web UI very well.

The problem arises when I try to use any of the CLI tools (awscli/mc).

```
$ aws --debug --endpoint-url https://smallchange-storage.smallchange.jaagalabs.com s3 ls
```

So, If I try to use the automatic port forwarding done by caprover (i.e. 9000 -> 80), the CLI hangs, and eventually  crashes with the following exception

```
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x10f7c5630>: Failed to establish a new connection: [Errno 61] Connection refused
```

---

But the interesting part of it is that when I use the "port forwarding" feature, it works just fine!

![image](https://user-images.githubusercontent.com/19492893/59156407-4c495280-8ab8-11e9-8345-b83b72ba7d9d.png)

```
$ aws --debug --endpoint-url http://smallchange-storage.smallchange.jaagalabs.com:9000 s3 ls
```

---

Is there any inherent difference between the port forwarding caprover automatically does for you, and the manual port forwarding? 

What do you think could be the cause of this inconsistent behavior?

**Comment by devxpy** [comment]
I created a new DO machine, re-deployed, and it works fine. Must be some issue with a specific config that I messed with.

**Comment by devxpy** [comment]
Weird! looks like the same exact problem has re-surfaced on the new server as well :(

**Comment by devxpy** [comment]
I have bug deeper using the `mc` CLI, and the server seems to exhibit 3 different behaviors!

- Raw, 9000 container to host:

```
$ mc config host add minio http://smallchange.jaagalabs.com:9000 admin adminadmin
Added `minio` successfully.
$ mc ls minio
[2019-06-09 19:07:08 IST]      0B testbucket/
```

- Captain forwarded port, over http

```
$ mc config host add minio http://minitotest.smallchange.jaagalabs.com admin adminadmin
$ mc --debug ls minio
mc: <DEBUG> GET / HTTP/1.1
Host: minitotest.smallchange.jaagalabs.com
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.28 mc/2019-06-07T00:01:32Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190609T133918Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2401
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: text/html
Date: Sun, 09 Jun 2019 13:39:19 GMT
Etag: "5cfcdbe6-961"
Last-Modified: Sun, 09 Jun 2019 10:13:58 GMT
Server: nginx/1.17.0

mc: <DEBUG> Response Time:  256.245417ms

mc: <DEBUG> GET / HTTP/1.1
Host: minitotest.smallchange.jaagalabs.com
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.28 mc/2019-06-07T00:01:32Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190609T133919Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2401
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: text/html
Date: Sun, 09 Jun 2019 13:39:19 GMT
Etag: "5cfcdbe6-961"
Last-Modified: Sun, 09 Jun 2019 10:13:58 GMT
Server: nginx/1.17.0

mc: <DEBUG> Response Time:  8.311784ms

mc: <ERROR> Unable to list folder. XML syntax error on line 5: unquoted or missing attribute value in element
 (1) ls.go:135 cmd.doList(..) Tags: [http://minitotest.smallchange.jaagalabs.com/]
 (0) client-s3.go:1783 cmd.(*s3Client).listInRoutine(..)
 Release-Tag:RELEASE.2019-06-07T00-01-32Z | Commit:b85dabd6b410 | Host:Devs-MacBook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.12.5 | Mem:1.6 MB/72 MB | Heap:1.6 MB/66 MB
```

- Captain forwarded port, over https

```
$  mc config host add minio https://miniotest.smallchange.jaagalabs.com admin adminadmin
$ mc --debug ls minio
mc: <DEBUG> GET / HTTP/1.1
Host: miniotest.smallchange.jaagalabs.com
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.28 mc/2019-06-07T00:01:32Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190609T134655Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 09 Jun 2019 13:46:55 GMT
Server: nginx/1.17.0
Vary: Origin
X-Amz-Request-Id: 15A68BC8C4C803B3
X-Minio-Deployment-Id: 0c5d2304-86fd-4c68-b4ed-3847c43ab61a
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1m0.279302919s

mc: <DEBUG> GET / HTTP/1.1
Host: miniotest.smallchange.jaagalabs.com
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.28 mc/2019-06-07T00:01:32Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20190609/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190609T134755Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 09 Jun 2019 13:47:55 GMT
Server: nginx/1.17.0
Vary: Origin
X-Amz-Request-Id: 15A68BD6C44C58A1
X-Minio-Deployment-Id: 0c5d2304-86fd-4c68-b4ed-3847c43ab61a
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1m0.120733705s

mc: <ERROR> Unable to list folder. unexpected EOF
 (1) ls.go:135 cmd.doList(..) Tags: [https://miniotest.smallchange.jaagalabs.com/]
 (0) client-s3.go:1783 cmd.(*s3Client).listInRoutine(..)
 Release-Tag:RELEASE.2019-06-07T00-01-32Z | Commit:b85dabd6b410 | Host:Devs-MacBook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.12.5 | Mem:1.7 MB/72 MB | Heap:1.7 MB/66 MB
```

**Comment by githubsaturn** [comment]
> Is there any inherent difference between the port forwarding caprover automatically does for you, and the manual port forwarding?

Can you elaborate on this please? I don't quite understand what you mean by automatic port forwarding.

**Comment by devxpy** [comment]
Oh just this 

![image](https://user-images.githubusercontent.com/19492893/59162034-f4d2d300-8b07-11e9-97d0-e7e6d1daf090.png)

Like the port forwarding from container's `9000` to port `80` of the captain assigned subdomain.

**Comment by githubsaturn** [comment]
The container HTTP port is being used by nginx. When you use the Container HTTP Port, this is what happens:

User --->>> port 80 of sever --->>> port 80 of nginx ----->>> port 9000 of the container

When you use raw port forwarding:
User --->>> port 9000 of sever --->>> port 9000 of the container


In the "manual" port forwarding scenario, you basically completely bypass the nginx layer.

About https:
If https is being managed by your container (your keys are managed by Minio for example), you have to use manual port forwarding. This way you are completely bypassing the nginx https termination layer.

**Comment by devxpy** [comment]
That makes sense. 

Any clue as to why minio cannot communicate through the nginx layer?

I actually talked to a friend that tried the same, and it seems to work for him. Have you tried the same?

I would be totally happy to have https managed by caprover.

**Comment by githubsaturn** [comment]
Well, there is nothing specific that come to my mind. But it could be maximum file size that's being allowed to pass through nginx layer. Or some specific headers that are being set by nginx or something else...

> I actually talked to a friend that tried the same, and it seems to work for him. Have you tried the same?

No I haven't used Minio's CLI.

**Comment by devxpy** [comment]
> No I haven't used Minio's CLI.

So awscli works for you?

**Comment by githubsaturn** [comment]
I haven't used any cli s

**Comment by devxpy** [comment]
Could you please try, and tell me?

aws cli is pretty simple to get up and running

```
$ pip install awscli
$ aws configure
AWS Access Key ID [None]: Q3AM3UQ867SPQQA43P2F
AWS Secret Access Key [None]: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
Default region name [None]: ENTER
Default output format [None]: ENTER
$ aws --endpoint-url https://play.min.io:9000 s3 ls
```

**Comment by githubsaturn** [comment]
Don't have access to laptop at the moment. Will test in next few days

**Comment by BrynjarM** [comment]
The aws cli works fine for me, maybe you are hitting the issue with minio restarting every 3 min (see https://github.com/minio/minio/issues/5057).

I had to disable the health checks in order to get it to stay up 
`docker service update srv-captain--minio --no-healthcheck`
