### ISSUE TITLE
[Feature Suggestion] A file manager/editor for persistent volumes

### ISSUE THREAD

**Issue by ComputerCarl** [caprover/caprover#444]
**Is your feature request related to a problem? Please describe.**
When changes are needed to a file, or upload/download, connecting via SSH is inconvenient.

**Describe the solution you'd like**
Relating to the Persistent Directories in the App Configs sections, it is sometimes necessary to access the data/files in those directories. Having a file manager with upload/download and text editing capabilities, like modifying an INI or HTML file would be super fast and easy.

**Describe alternatives you've considered**
SSH works fine - just not as slick.

**Comment by githubsaturn** [comment]
There are many webbased file managers that you can use. CapRover allows for any 3rd party app installation. Just have a look at these:

https://github.com/prasathmani/tinyfilemanager
https://github.com/kalcaddle/KodExplorer
https://github.com/LTD-Beget/sprutio
https://github.com/filebrowser/filebrowser
https://github.com/mickael-kerjean/filestash
https://filerun.com/
https://extplorer.net/


All you need to do is to install them! These are also good suggestion to be converted to one-click apps.

**Comment by devxpy** [comment]
@githubsaturn I would like to add on this request and maybe allow whole docker containers to be browsed by us. 

But how would one go about doing this?

I guess the original request could be implemented by just doing -

```
"volumes": [
    "/var/lib/docker/volumes:<path in file manager container>",
]                
```

--- 

We could, in theory, explore the fs of a running container by just `exec -it bash` into containers and trying to do something from there. (as suggested by [this](https://stackoverflow.com/questions/20813486/exploring-docker-containers-file-system) SO thread)

**Comment by githubsaturn** [comment]
File Browser is now available as a one click app.

**Comment by drmrbrewer** [comment]
@githubsaturn nice addition.  So if I want to have the filebrowser open up in e.g. `/var/lib/docker/volumes/captain--my-workspace/_data/` then I specify this where?

**Comment by githubsaturn** [comment]
@drmrbrewer 
I've tried to make this clear in the start/end instructions of FileBrowser. Let me know if it's unclear:
https://github.com/caprover/one-click-apps/blob/master/public/v2/apps/filebrowser.json#L28-L29

Also, feel free to edit and add more details as it helps others too.

**Comment by drmrbrewer** [comment]
OK I get it.  It's just a case of selecting `Set specific host path` for the `/srv` mapping and putting `/var/lib/docker/volumes/captain--my-workspace/_data/`.

**Comment by drmrbrewer** [comment]
I just deployed another filebrowser app... did you change the help text that appears at the end of the deploy process?  I don't remember it being quite so informative, even a couple of hours ago...

**Comment by githubsaturn** [comment]
Yes - I just added a bit more info: https://github.com/caprover/one-click-apps/commit/d21bf463aa4380463610c0a9092a858c1dd5e6b2
