### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by rafamel** [caprover/caprover#445]
**Is your feature request related to a problem?**
The official caprover image can't run on ARM. Attempts at building CapRover result in containers that exit immediately.

**Describe the solution you'd like**
An officially supported ARM build.

**Describe alternatives you've considered**
I've tried to build from source via `dockerfile-captain.release`: 

```$ docker build -t caprover -f dockerfile-captain.release .``` 

This has been done both for the master branch `HEAD` and on tag `v1.4.0`, both with the exact same result:

```
$ sudo docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover

> caprover@0.0.0 start /usr/src/app
> node ./bin/www

Captain Starting ...
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
>>>> Checking System Compatibility <<<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
******* Warning *******   With less than 1GB RAM, Docker builds might fail, see CapRover system requirements.
June 10th 2019, 6:09:19.982 pm    Fresh installation!
June 10th 2019, 6:09:19.990 pm    Starting swarm at 127.0.0.1:2377
Swarm started: cjivif7y8jdnmisepchqltb87
```

After that, the container stops. This is happening on a Raspberry Pi w/ the latest Raspbian (Debian distro).

**Comment by githubsaturn** [comment]
The reason behind that is that the original Docker container is just an installer. It then installs the main container using this line:
https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L18

So to fix:

- Check out the code.
- Navigate to this file: https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L18
and edit the `publishedNameOnDockerHub` variable from `caprover/caprover` to `caprover-arm-local`.
- Run `docker build -t caprover-arm-local -f dockerfile-captain.release .`
- Now run:
```
docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover-arm-local
```

**Comment by githubsaturn** [comment]
Please report back the result here. I am curious to see how it performs on Raspberry Pi.

**Comment by rafamel** [comment]
HI @githubsaturn , thanks for the prompt response! Sadly I'm getting exactly the same result after modifying the source and building it. Any idea as to what could be going on?

**Comment by golyalpha** [comment]
I'm having a simmilar issue, but instead of modifying the file, I tagged the image the same way it would be tagged for docker hub.
Running the installer outputs this:
```
> caprover@0.0.0 start /usr/src/app
> node ./bin/www

Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html





 >>>> Checking System Compatibility <<<<
   Docker Version passed.
   Ubuntu detected.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
******* Warning *******   With less than 1GB RAM, Docker builds might fail, see CapRover system requirements.
June 15th 2019, 8:40:38.281 pm    Fresh installation!
June 15th 2019, 8:40:38.292 pm    Starting swarm at 10.0.0.3:2377
Swarm started: m67jdcx6uhcapba5jcsa5wlx7
```

**Comment by golyalpha** [comment]
Following the instructions posted yields the exact same result.

**Comment by danielivert** [comment]
I managed to install it on a RPi 3 B+ a couple of months ago.
It wasn't a very fast experience and most of the times it crashed. Not to mention that the letsencrypt service never worked properly.

I'm thinking on trying again, but this time with a RPi 4. Maybe the 4GB of RAM can make a difference on performance and running docker, if it runs properly it would be great for having a RPi caprover cluster at home.

**Comment by golyalpha** [comment]
@danielivert Anything you did that we aren't to make it work?

**Comment by golyalpha** [comment]
So, I decided to try it again, on a fresh instal of Ubuntu on my SBC. This is the output:
```
$ docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover-arm

> caprover@0.0.0 start /usr/src/app
> node ./bin/www

Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html





 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
******* Warning *******    Default CapRover is compiled for X86 CPU. To use CapRover on other CPUs you can build from the source code
   Total RAM 1031 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v0.29.1
November 22nd 2019, 12:06:08.606 pm    Fresh installation!
November 22nd 2019, 12:06:08.618 pm    Starting swarm at 127.0.0.1:2377
Swarm started: y5jvgwlc5nq42qefd9d9cw6t9
*** CapRover is initializing ***
Please wait at least 60 seconds before trying to access CapRover.
```

Docker ps reports no running containers.

**Comment by golyalpha** [comment]
Figured it out.
You have to make sure that version in CaptainConstants is either "latest" or that you tag the arm built image with the same version.
It also requires rebuilding of caprover/certbot-sleeping for arm.

**Comment by golyalpha** [comment]
After an investigation into the source:
1. The CapRover Image tag has to match the version specified in the constants file.
2. A rebuild of certbot and certbot-sleeping is also required.

**Comment by golyalpha** [comment]
With the relatively high complexity required to get this working, it might be worth adding instructions to the documentation, or using docker's manifests to provide images for multiple architectures (ideally both)

**Comment by j2l** [comment]
Thanks @golyalpha for this. 
I was bumping my head on the wall and I guess I'll stop trying to install caprover on my rock64 until you or someone makes it easier to deploy.

**Comment by golyalpha** [comment]
Here's what you need to do:
1. `git clone https://github.com/caprover/caprover.git`
2. Build the caprover image:
2.1. `cd caprover` and run `git checkout v1.5.2` (recommended)
2.2. Run `docker build -t caprover/caprover:1.5.2 -f dockerfile-captain.release .`
Note: It is important to tag the image with the same version specified in `src/utils/CaptainConstants.ts` (currently on line 20) - if you ran the checkout in the previous step, you should be fine running the command as is.
3. Don't run caprover yet. You're gonna need to rebuild caprover/certbot-sleeping for that:
3.1. Find out the certbot image tag for your architecture
3.2. Create a dockerfile-certbot with the following contents:
```Dockerfile
FROM certbot:arm64v8-latest

ENTRYPOINT sleep 9999d
```
Make sure to replace `arm64v8-latest` with whatever's the architecture tag you're building on.

3.3. Finally, build the caprover/certbot-sleeping with: `docker build -t caprover/certbot-sleeping:v0.29.1 -f dockerfile-certbot .`

4. Now you should be able to run the caprover container with:
```
docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover:1.5.2
```

Note, these instructions are slightly different from what I've personally done (but should work just fine, as far as I know) and are extremely likely to have details change as new releases come out. (hence why I recommended checking out the v1.5.2 tag)

**Comment by j2l** [comment]
Fantastic! Thank you!
Meanwhile I found 2 images caprover-arm on dockerhub (did you try them?). Can't make it work because of a firewall issue (iptables vs firewalld vs webmin flush all rules)

**Comment by golyalpha** [comment]
Oh, right, yeah, I also had a port 3000 issue. Solved it by just downloading ufw, opening up the required ports (http, https, ssh, plus other ports in the docs) and enabling it.

**Comment by golyalpha** [comment]
@githubsaturn I volunteer my Rock64 board to building ARM64 versions of CapRover's images, so we don't have to deal with this stuff, if you need. (RPi3s should work aswell, considering they use 64bit ARM CPUs, we just had to use 32bit linux builds on them for a while)

**Comment by githubsaturn** [comment]
@golyalpha - thanks for the offer! Do you want to be the maintainer of the ARM version? I can add a bit of documentation to the website to refer people to your builds.

We'll move to multi-arch builds once it's no longer [an experimental feature](https://engineering.docker.com/2019/04/multi-arch-images/)

**Comment by golyalpha** [comment]
I mean, to be fair, the "official" docker images are using the multi-arch builds, but sure. I'm down for it.

**Comment by githubsaturn** [comment]
Yes, that's correct. Once the QEMU approach is standardized, it's much easier to produce the multi-arch images. I haven't dug much into it, but currently there is a manifest file that you can provide to encapsulate multiple images under the same tag. Compare [nginx](https://hub.docker.com/v2/repositories/library/nginx/tags/) with [CapRover](https://hub.docker.com/v2/repositories/caprover/caprover/tags/). Last time I looked into it, the process was a bit too complicated. Maybe it has changed since then. I'll look into it again at some point.

Let me know once you have a simple README.md or some sort of repo that I can link to in the documentation website.

**Comment by golyalpha** [comment]
I don't think a separate git repo will be needed for the builds. I'll just mirror your builds under my namespace, just built for arm64.

**Comment by golyalpha** [comment]
@githubsaturn 
The ARM build of the image is live. Currently testing it. The master image is booting up fine as of right now.
https://hub.docker.com/repository/docker/golyalpha/caprover

**Comment by golyalpha** [comment]
So, I just finished my testing. And it seems that caprover is fully working (more so than my previous build anyways).

Rebuilt everything, from caprover itself, through netdata, all the way to the blank app template. And everything is working as expected.

**Comment by rafamel** [comment]
This is such great news @golyalpha! Thanks for taking the time to look into this. I believe they're published as private at the moment, could you make them public? I'll be giving it a test run in no time!

**Comment by golyalpha** [comment]
![image](https://user-images.githubusercontent.com/8203992/69493079-8d88bf80-0eaa-11ea-89cf-d223db7c40fb.png)
All the docker images should be public.

**Comment by golyalpha** [comment]
I'm currently reworking my build bot (the one I used to patch, build and publish the docker images) to accept patches from a git repo I just put up here on GitHub, instead of from it's own resources. That way, when you make changes to code that would break my patches (bumping image versions, etc.), we both can make a new patch for the arm builds.

**Comment by j2l** [comment]
Wow! I never expected this need to be filled so fast. 
Thank you @golyalpha ! I really appreciate 
Magic of open source is here!

**Comment by j2l** [comment]
Oops, I also can't run this docker image.
It's on docker hub but:
```
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain golyalpha/caprover
Unable to find image 'golyalpha/caprover:latest' locally
docker: Error response from daemon: manifest for golyalpha/caprover:latest not found: manifest unknown: manifest unknown.

```

**Comment by golyalpha** [comment]
Oh, that's because it's not tagged with latest.
Try to run it with golyalpha/caprover:1.5.2

**Comment by j2l** [comment]
Yes! Thank you for doing "docker for the dummy" like me :)

Still got my firewall issue:
webmin firewalld rules "apply" button flushes iptables rich-rules
So I add 80 to both iptables and firewalld (it worked for other docker
containers' ports), it's still not working for 80
Stopped firewalld, still not working
No other container is running on 80
iptables:
*IN_public_allow*   Accept If protocol is TCP and destination port is 80
and state of connection is NEW
and reboot, still not working.
BTW, adding another firewall like ufw is not the best option I think.
I stopped firewalld, rebooted (flushes all rules, everything open in
iptables) and I still get:
```
Installation failed.
Error: Port seems to be closed: 80
```
Did you ever got this behavior?

**Comment by j2l** [comment]
```
iptables -S
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-N f2b-sshd
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9000 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A f2b-sshd -j RETURN

```

**Comment by githubsaturn** [comment]
@j2l I assume your RPie doesn't have a public IP network interface. In that case, you may want to follow the steps here:


Particularly you'll need to add `  -e MAIN_NODE_IP_ADDRESS=127.0.0.1` to your `docker run` command.

**Comment by j2l** [comment]
Thanks @githubsaturn , indeed I'm on the LAN, 
By opening and changing port, it throws the same message about port 80:
`docker run -e MAIN_NODE_IP_ADDRESS='192.168.1.25' -p 81:80 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain golyalpha/caprover:1.5.2`
results in 
```
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/built/utils/CaptainInstaller.js:148:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
So I wondered if this error is not a generic fallback error for something else.
I tried `docker run -d -p 80:80 hypriot/rpi-busybox-httpd` and it works fine, website available!
So it's definitely not a firewall issue and there's something else wrong but I only get this error message.
Do you know some useful commands I could run to dig it?

**Comment by githubsaturn** [comment]
You shouldn't change the port

**Comment by j2l** [comment]
I understand your point, it was just to test it. 
Http protocol can run on any port, not just 80, the error is hard-coded while it should pick the used port.
And most important, the install "port" error is not about my ports but something else.

**Comment by githubsaturn** [comment]
Http can run on any port, but CapRover is a webserver that only runs on port 80. It's an intentional limitation to work with let's encrypt and other stuff. If you want to change the port, feel free to clone the repo and recompile.

**Comment by kristijanPetr** [comment]
Hi , 
First of all thanks @golyalpha  for making guide how to install on RP3+, but unfortunately when i run 
`docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain golyalpha/caprover:1.5.2`
I am getting error: `standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by jekusz** [comment]
Hmm,
have been trying this on ubuntu 20.04 and docker 19.03.8
and this command passes completely silently, no container starts:
```
root@ubuntu:/# docker run -it -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain golyalpha/caprover:1.5.2
root@ubuntu:/# docker container list
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@ubuntu:/#
```

**Comment by golyalpha** [comment]
Hmm, that *is* weird. I have built one of the latest tags recently, without issue. Either way, the run command should not pass silently at all. Can you run `docker ps -a` for me?

**Comment by golyalpha** [comment]
@kristijanPetr Sorry for the delay. Are you still having the problem? And if you do, are you sure you're using the build for 64bit ARM, it's possible you're trying to run it on the 32bit build, which is why it's failing (as that's what the error message is telling me)

**Comment by jekusz** [comment]
@golyalpha 
Reg ubuntu 18.04, have spent plenty time trying to get ubuntu 1804 running on the PI but due to that my setup is headless only (it has micro HDMI ports only) it was taking too much time and eventually had to give up.
Reg the other thing:
```
root@ubuntu:/home/ubuntu# docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS                            PORTS               NAMES
0b18d3973a84        golyalpha/caprover:1.5.2   "docker-entrypoint.s…"   About a minute ago   Exited (133) About a minute ago                       serene_bell
4bd41af684fe        hello-world                "/hello"                 5 minutes ago        Exited (0) 5 minutes ago                              thirsty_mirzakhani
root@ubuntu:/home/ubuntu# docker logs 0b18d3973a84
root@ubuntu:/home/ubuntu#
```

**Comment by golyalpha** [comment]
That exit code corresponds with the process receiving a SIGTRAP signal.
That is truly weird, and unfortunately not something I can help with based
on the current information.

**Comment by golyalpha** [comment]
As for the 1804 setup, I can't exactly get a 2004 version running on my
board, as it's not a RPi, and there's not a 2004 build for it, and I'm not
exactly in the mood for that (plus if I was, is probably be building
alpine, rather than Ubuntu)

**Comment by golyalpha** [comment]
I've also just realized, how much RAM and swap do you have?

**Comment by jekusz** [comment]
4 GB ram,
0 swap

**Comment by golyalpha** [comment]
Hmm, weird, that should be fine then... What does `uname -pmi` print?

**Comment by jekusz** [comment]
aarch64 aarch64 aarch64

**Comment by golyalpha** [comment]
Yeah, I genuinely have no idea why it's crashing at all.

**Comment by jekusz** [comment]
Seems the kernel updates in 2004 to 5.4 since version 4.15 released in 18.04 LTS could that be it ?

**Comment by golyalpha** [comment]
Not really sure if kernel change will break containers... It's more likely it would break applications inside it, but it shouldn't break things like building containers and what not.

By the way, did you check out the latest tag, or did you build from master? If you built from master, try to do `git checkout v1.6.1`, and build that. Either way, I just built the new version, and am pushing it up on Docker right about now. (golyalpha/caprover:1.6.1)

**Comment by jekusz** [comment]
Okay, I've tried running your 1.6.1 image and the result is the same. Silent death.

When it comes to building I've tried as per your instructions:

1. git clone https://github.com/caprover/caprover.git
2. Build the caprover image:
3. cd caprover and run git checkout v1.6.1 (recommended)
4. Run docker build -t caprover/caprover:1.6.1 -f dockerfile-captain.release .

But again the npm install step goes: Aborted (core dumped), How does one debug this ?

**Comment by maietta** [comment]
> Okay, I've tried running your 1.6.1 image and the result is the same. Silent death.
> 
> When it comes to building I've tried as per your instructions:
> 
> 1. git clone https://github.com/caprover/caprover.git
> 2. Build the caprover image:
> 3. cd caprover and run git checkout v1.6.1 (recommended)
> 4. Run docker build -t caprover/caprover:1.6.1 -f dockerfile-captain.release .
> 
> But again the npm install step goes: Aborted (core dumped), How does one debug this ?

Which version of NodeJS and NPM are you running?

node -v
npm -v

Maybe you need to get NPM updated? If so, this is now I know how to do it.

npm -g install npm@latest
npm -v

Then try again. If it aborts again, can you get the output and dump it here?

**Comment by jekusz** [comment]
@maietta the error happens during docker build so its not on the host, see further up ive pasted the exact output.

**Comment by maietta** [comment]
Ah, okay. Let me see if I can replicate over here real quick. Brb.

**Comment by maietta** [comment]
Okay, so I was able to build from a Windows 10 Pro environment running Docker Desktop which is configured to run Linux via the Hyper-V system. (Essentially, a real x86 Linux distro). I can repeat this again on a Linux VPS matching your specific distribution if needed.

Are you by chance building this from an ARM system?

Also which version of docker are you using?

**Comment by jekusz** [comment]
Please see https://github.com/caprover/caprover/issues/445#issuecomment-629830621

**Comment by maietta** [comment]
> Please see [#445 (comment)](https://github.com/caprover/caprover/issues/445#issuecomment-629830621)

Thank you. I wish i would have seen this before. I won't be able to help here as I don't have this environment available to me, I apologize. Hope you get this sorted out soon. I'll keep watching though.

**Comment by golyalpha** [comment]
@jekusz I had the same issue on my end, with npm. But in my case, it was running out of memory and created a 4GB swap file to fix that. I guess you can try that, but no idea if it'll work.

**Comment by jekusz** [comment]
Dont exactly get all the tech talk in the references but by the sound of it it was a problem with nodejs and has been reported and patched. Dont know exactly how far they've got with rolling the fix out, and to which node versions will it apply (possibly above 14 somewhere). See comments under OP here: https://stackoverflow.com/questions/61608561/cannot-run-npm-install-in-docker-on-raspberry-pi?noredirect=1#comment109503327_61608561
Personally I've ended up downgrading to ubuntu 1804 which made the problem go away. (now am getting annoyed by 'port timed out: 80' even tho its open but that's another discussion altogether)

**Comment by golyalpha** [comment]
Right, that npm thing might be an issue that should be opened up separately. As for the port 80 thing, try to open the ports using ufw (if it's not installed, install it unless you wanna go an try to play around with iptables). I had the exact same issue, and installing ufw and opening the ports through it seemed to fix it, even though from what I've seen, iptables should never have been blocking those ports.

**Comment by jekusz** [comment]
I am forwarding. Been testing with nginx and it seems I can reach the server port 80 port from every other machine(on my network **and** outside of it) except for from the server itself (when using the public IP), the curl times out.

**Comment by golyalpha** [comment]
Hmm, sounds like you need to enable loopback (some routers/gateways actually require you to specifically setup LAN Loopback on the port forwards in order to be able to access the ports on the public IP from inside the network)

**Comment by jekusz** [comment]
I think it's a hairpinning type of issue. I can't change such a setting on my router. But it's a cheap one.

**Comment by golyalpha** [comment]
You might need to recreate the portforward, some settings may only be available while creating the forward, but not while editing it.

**Comment by m4rcster** [comment]
@golyalpha will you update your ARM Build to 1.7.1?

**Comment by golyalpha** [comment]
@m4rcster How quickly do you need it?

**Comment by m4rcster** [comment]
> @m4rcster How quickly do you need it?

@golyalpha  No Rush, when you have a spare minute would be great. 🙏

**Comment by golyalpha** [comment]
Aight. I'll look at what needs to be patched etc., and try to build it later today.

**Comment by golyalpha** [comment]
Alright, sorry it took so long @m4rcster, currently running the caprover build, once I'm done with the certbot sleeping build (since that has been updated as well), I'll push both up to Docker and post here it's done.

**Comment by golyalpha** [comment]
Alright, had some unexpected issues trying to get certbot-sleeping to run successfully, but the images are now up on Docker Hub and available for use.

Please do not use the caprover:latest image, that is still 1.6.1

**Comment by marcusique** [comment]
> Hmm, weird, that should be fine then... What does `uname -pmi` print?

I'm having the same issue as @jekusz and the above mention command yields the following for me:

`armv7l unknown unknown`

Any way to fix this?

**Comment by githubsaturn** [comment]
Since it turned out that folks at Docker don't have any intention of removing the experimental flag for `buildx` , I've decided to bite the bullet and just go with it. 

Starting now, we have mutliarch docker images. No need to use any arch specific image names/tags. CapRover images are now built using mutiarch build process and they are all tagged with the same tag. 

**IMPORTANT ASK**
Please if you have an arm machine (RPie, Rock64 or etc) lying around, try out the **edge version**  before and report if you're having problems:

```
docker run -p 80:80 -p 443:443 -p 3000:3000 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /captain:/captain \
        caprover/caprover-edge
```

It is highly recommended that you create at least 1gb of swap:
```
cd /var && \
touch swap.img && \
chmod 600 swap.img && \
dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 && \
mkswap /var/swap.img && \
swapon /var/swap.img && \
free && \
echo "/var/swap.img    none    swap    sw    0    0" >> /etc/fstab && \
free
```

Note that currently only edge image is built on arm - starting the next version (whether 1.8.1 or 1.9.0) we'll have arm variants.

![image](https://user-images.githubusercontent.com/10582082/91244776-36ef3100-e71b-11ea-955e-c09f70d506c6.png)

**Comment by golyalpha** [comment]
I may (!) try it out later today. I would try it out right now, but am at work, and my ISP's apparently dropped of the face of the earth.

**Comment by neojp** [comment]
@githubsaturn I tried it and running `caprover/caprover-edge` and it stopped soon after.
![image](https://user-images.githubusercontent.com/127994/96743081-9d967100-1391-11eb-957d-aa15f694b8d7.png)

**Comment by githubsaturn** [comment]
@neojp what do you mean by it stopped? Can you get the logs?
```
docker service logs captain-captain --since 5m
```

**Comment by neojp** [comment]
I think I found my mistake. I was using a path in my volume, but it looks like this container itself creates other containers and that's why things failed. Once I changed the volume back to `/captain` everything started working. This might be worth having in the docs.

![image](https://user-images.githubusercontent.com/127994/96870331-bf99fd00-143e-11eb-8a9f-c5f900315c0a.png)

**Comment by a-musing-moose** [comment]
@githubsaturn I tried edge last night as you instructed on a small cluster of Raspberry Pi4 with 8GB of RAM each. Installation worked flawlessly and I was able to get up an running a minutes with my first service deployed as well as adding a couple more devices and making it an actual cluster.

Excellent work! Can't wait for this to hit the stable release.

**Comment by johncronan** [comment]
@neojp, whatever that problem is with changing the local path for the /captain volume... it also prevents running locally on recent versions of MacOS, where the filesystem root is normally readonly, so that directory can't be created.
