### ISSUE TITLE
Logs for stopped images

### ISSUE THREAD

**Issue by brewmanandi** [caprover/caprover#446]
Hi,

I am regularly deploying new versions of images for my containers in caprover. Now I want to see the log files of the stopped images but the logs I get are just for the current instance. I checked on web dashboard, with container logs and even in /var/lib/docker/containers/*.
When trying to find the log path via docker service inspect I see no entry for "LogPath".
Any ideas?

**Comment by githubsaturn** [comment]
CapRover runs a "prune" that cleans up all stopped containers. Without this prune, the stale containers would fill up your storage. This prune is necessary in order to keep the storage use under control.
