### ISSUE TITLE
Is there a way to expose local port and not as webapp?

### ISSUE THREAD

**Issue by buglinjo** [caprover/caprover#447]
I'm trying to have caprover on existing server where Nginx is already installed without docker. Is there a way to create apps in caprover and not expose as web apps, but only port of the container. I'll manage Nginx proxy and domain control myself.

**Comment by githubsaturn** [comment]
CapRover is a bundle and it's not currently possible to decompose this bundle and don't have the nginx part. There are other parts of the stack that rely on this. For example, when you access the dashboard via `captain.domain.com`, your request is being routed via nginx.

Your best alternative is to install a VM on your server and run CapRover in the VM. Keep in mind that this option is only available if you have access to a physical server which can host VMs. Also, installing CapRover on VM is not as straightforward as installing CapRover on a fully fledged server.
