### ISSUE TITLE
Frequent "Something Bad Happened" Errors

### ISSUE THREAD

**Issue by ComputerCarl** [caprover/caprover#448]
Fairly often, I will receive error popups which read "Something Bad Happened". The VPS becomes unresponsive, I cannot SSH into the machine and have to restart the VPS..
Linode 2GB VPS, Deb 9, average CPU load ~10%
Nothing running in production yet.

Where can I find the logs indicated what is crashing the system?

![image](https://user-images.githubusercontent.com/29293242/59965833-363c8880-94e1-11e9-8de4-65e05745533d.png)

**Comment by githubsaturn** [comment]
This is most probably because your web server keeps getting restarted over and over again. The reason behind restart might vary. However it is very likely that your server runs out of memory due to a particular application taking up all memory. 

what are the applications that you're running on this web server?

**Comment by ComputerCarl** [comment]
I would like to migrate my entire infrastructure over. Currently, I have Gitea, WordPress, a Node app, Verdaccio, Matomo *running* on the VPS (which really aren't in production so nothing big).
![image](https://user-images.githubusercontent.com/29293242/60047042-beb05a00-9696-11e9-8446-154a093f1f9d.png)
As you can see, there is ~4% CPU load, I try to adjust some ENV settings on a Node app, and the VPS locked. It also may lock while adding or configuring any number of apps.

It may be the (main) web server killing the system, but where do I find this out?
![image](https://user-images.githubusercontent.com/29293242/60047212-22d31e00-9697-11e9-90b8-8c2ed5deaf94.png)

I cannot access SSH or the Web interface. After rebooting, the app logs seem to be empty.

**Comment by githubsaturn** [comment]
Is this still an issue. Do you have a reproducible case for this?

**Comment by ComputerCarl** [comment]
I have increased the resources of the VPS and refrained from building Node/React apps on the server when possible. This seems to have stopped it from crashing.

**Comment by githubsaturn** [comment]
Good suggestion! Added here: https://caprover.com/docs/troubleshooting.html#something-bad-happened
