### ISSUE TITLE
[Deployment Issue] Error 1107 on HTTPS activation

### ISSUE THREAD

**Issue by Dazorn96** [caprover/caprover#449]
Hi,
i created a caprover (ubuntu) instance with digitalocean and i did to start my app.
Now, i want to enable HTTPS for it, but i got that error when trying:
![image](https://user-images.githubusercontent.com/10536581/59982418-5cae1100-9612-11e9-9f9d-2a7f9406d2fd.png)
What's the problem?
Thanks

**Comment by githubsaturn** [comment]
Just to be clear, this happened for one of your apps, after HTTPS for the dashboard was successfully enabled?

Did you remove some of the directories after installation?

**Comment by bevinhex** [comment]
This is happening on drone-gitea as well, didn't remove anything, fresh installation is giving 1107

**Comment by bevinhex** [comment]
update, in my case, nginx service was not running properly, due to wrong configuration issues, stopped 'captain-captain' 'captain-nginx' service, corrected nginx problems from /captain/data/captain-config.json, now nginx runs nicely, afer that , letsEncrypt is doing fine.

**Comment by bevinhex** [comment]
maybe adding a validation option on nginx configuration would be a good idea, so that custom changes won't break running nginx.

**Comment by githubsaturn** [comment]
nginx does not offer any validator the config. Plus, the config can have a valid syntax, but it might have conflicts with domain names and or ports. 

It's assumed that a user who manually modifies the config is an experienced user and knows what they are doing. That's why, by default, the nginx configs are completely hidden.

**Comment by Mistifiou** [comment]
Hi,
I think I encountered same error (on gitlab).  
To reproduce:
- Create an app on caprover without enabling https globally an rely it to gitlab webhook on some branch
- Enable https globally on caprover
- Try to push something on repo

I have another app running well. I created it after enabling https.  
Tryied to restart captain-captain but didn't worked
