### ISSUE TITLE
.cpignore file

### ISSUE THREAD

**Issue by boraikizoglu** [caprover/caprover#451]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to deploy a Typescript application using CLI. CLI pushes the committed files but I don’t want to commit every time I deploy a new version for my development server.

I want to compile Typescript code locally and want to push the compiled dist folder but dist folder is ignored by git so caprover ignores the dist folder too.

**Describe the solution you'd like**

Elasticbeanstalk has an .ebignore file. We could create a .cpignore so that .git and caprover push logic could be decoupled.

**Additional context**
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html

**Comment by githubsaturn** [comment]
CapRover uses `git archive` therefore whatever git sees CapRover sees too. To answer your problem, you have two solutions:

1) Use Docker to build your dist on the server, something like this:
```
FROM node:10-alpine
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install && \
     npm cache clean --force && \
     npm run build
CMD ["npm", "start"]
```


2) Build on local machine and use tar to send specific files to the server. This approach has less load on the server:
See https://caprover.com/docs/recipe-deploy-create-react-app.html
