### ISSUE TITLE
Does increasing container instance count really scale up

### ISSUE THREAD

**Issue by iamrommel** [caprover/caprover#453]
Does really adding instance really scale up the performance? I did load testing for my app, I initially have 1 instance then do the load testing using jmeter and save my result.

Then I make it to 15 instance, do run the same load testing scenario and compare the result with previous one. There is no significant difference on the result, i still have close values of % of error (because of server timeout). I'm only using single server with 2cpu and 4gb of memory. I checked with netdata and seems i'm not yet maxing out my resources with the 15intances. 

But my doubts is that increase on instance count does not work.

By the way i tried the load testing on my developer machine which has 16gb or memory and 8cpus, there are no errors, all test sample of jmeter runs successfully.

Here is the sample netdata screenshot
![image](https://user-images.githubusercontent.com/177265/60286765-c5fb9000-9942-11e9-95dd-ba8f842fc793.png)

**Comment by githubsaturn** [comment]
Increasing instance counts simply increases number of processes that your application is running on. If you application is designed such that even a single process can make complete use of the entire machine, then increasing instance count really doesn't help. But if your application is limited, for example it can only use one single core of your CPU, then increasing instance count enables you to utilise all cores.
