### ISSUE TITLE
[Deployment Issue] How do Environment Variables work?

### ISSUE THREAD

**Issue by RollingGoron** [caprover/caprover#458]
Can someone explain how to use them? I understand they can be used to inject username/password/build settings etc... but I don't know HOW to reference them when I add them as a Kay/Value. 

Here is my use case. I'm using Kotlin+Springboot to build a webservice. I would like to define prod/dev environments based on an Environment Variable so my prod data doesn't get touched with dev data. Springboot includes a built in Environment Variable, `SPRING_PROFILES_ACTIVE`, which defines which properties file to use.

Is it possible to inject the ` SPRING_PROFILES_ACTIVE` : `prod` and `SPRING_PROFILES_ACTIVE` : `dev` via the Environment Variables section of my CapRover app?

**Comment by githubsaturn** [comment]
I assume `SPRING_PROFILES_ACTIVE` is a runtime environment variable. In that case, yest, you can definitely leverage the env vars that you see on the dashboard.

On the other hand, if the environmental variable is a build time environmental variable, you need to inject it to your docker file as `ENV VARIABLE_NAME VARIABLE_VALUE`
