### ISSUE TITLE
Environmental Variables not work in PHP app

### ISSUE THREAD

**Issue by a-maggi** [caprover/caprover#459]
**What is the problem?**

My app failed because not receibed the environment variable that need. 

The app is running in Laravel framework.

**Steps to reproduce the problem:**

1- Deploy the image Laravel
2- Set the variables. In the image you can see the key variable, needed for start the app.

![image](https://user-images.githubusercontent.com/47649911/60909885-bb4fcd80-a255-11e9-8f08-58728d886ff2.png)

3- Go to the website and see error 500.

![image](https://user-images.githubusercontent.com/47649911/60909910-c7d42600-a255-11e9-9ad2-7a98b18b8559.png)

4- In the logs, you can see the app cannot get the key variable and because that crash the app.

![image](https://user-images.githubusercontent.com/47649911/60909991-fe11a580-a255-11e9-81f1-7a941cbac234.png)

**Comment by osmanzeki** [comment]
I'm wondering, this works fine with Laravel projects on my end. What do you have at this line in your project:
https://github.com/laravel/laravel/blob/master/config/app.php#L122

Also, do you have a `.env` file commited into your deployed project? I'm not 100% sure, but if you do, it might override the ENV values set by CapRover. Again, not sure in what order those are evaluated in the end.

Also, you should probably hide you APP_KEY, that value is used for encryption of your sessions, etc, better not to share publicly (although this does not affect hash for passwords, just other types of encryption in the framework).

**Comment by a-maggi** [comment]
Hi @osmanzeki , thanks for the help.

This line in my app.php is the same as official repo.

![image](https://user-images.githubusercontent.com/47649911/60915713-e7be1680-a262-11e9-8b0e-4b832e3b7d0b.png)

In a beginning I have the .env file, but was removed because I see the variables set in caprover not overwrite the variables in .env. 

when I deleted this file I realized that the problem was not that it did not overwrite the variables, but that it never really takes them. That's why the application fails when the .env file does not exist.

**Comment by githubsaturn** [comment]
I just tried with a plain PHP file like this:
```
        <?php 

        echo getenv();

        ?>
```

And it worked great. You may be having a typo, either in your variable name, or your command. Perhaps, you should try `getenv` instead of `env`

**Comment by a-maggi** [comment]
Hi,

I try use getenv instead of env in the DB_HOST param but not worked 👎 

In the config file of database.php I put:

![image](https://user-images.githubusercontent.com/47649911/61192677-a8416100-a68c-11e9-88ae-b8a6c2259269.png)


In Cap Rover set the variable:

![image](https://user-images.githubusercontent.com/47649911/61192688-bbecc780-a68c-11e9-8bfe-aa89e4f252d4.png)

But when go to the app, I see get the param of the file .env inside of container and not the variable and set in Cap Rover:

![image](https://user-images.githubusercontent.com/47649911/61192715-ec346600-a68c-11e9-999c-3503e6f39037.png)

Thanks for the help!

**Comment by a-maggi** [comment]
Issue resolved! I run inside the laravel container the next command for clear the config cache and work 👍 

php artisan config:cache

Thanks.
