### ISSUE TITLE
Symlink seem not working in nginx

### ISSUE THREAD

**Issue by a-maggi** [caprover/caprover#460]
**What is the problem?**

Symlink folder for static assets not work in Nginx, always show me the explorer a  404 error.

**Steps to reproduce the problem:**

For make the symlink use the follow command:

 ln -s  /captain/data/nginx-shared/www/all-gamez.com/storage/app/public  /captain/data/nginx-shared/www/all-gamez.com/public/storages

**Comment by githubsaturn** [comment]
`/captain/data/nginx-shared` is the host path of `nginx-shared` directory.

However, `nginx` process sees `nginx-shared` at the root location `/nginx-shared`

In other words:
`/captain/data/nginx-shared` in host is mapped to `/nginx-shared` in nginx container.
