### ISSUE TITLE
Version 0.7.3 Unable to update root domain

### ISSUE THREAD

**Issue by weiweitoo** [caprover/caprover#461]
Cannot update root domain in captainduckduck 0.7.3 version. It does not allow to edit the field and update domain

![image](https://user-images.githubusercontent.com/25069837/61023911-5d022680-a3de-11e9-9249-4c858d8ca0b2.png)

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 16.04 LTS(Xenial Xerus) and Docker engine 17.12.0-ce
- RAM?
2048MB

**Comment by githubsaturn** [comment]
This feature was added in 1.3.0.
> Ability to change the root domain post installation

https://github.com/caprover/caprover/blob/master/CHANGELOG.md#130---2019-03-04

Please update to the latest version.
