### ISSUE TITLE
Unable to deploy from GitHub using SSH Key

### ISSUE THREAD

**Issue by Jamesyps** [caprover/caprover#464]
**What is the problem?**

I've set up a new app to deploy from a private GitHub repository, entering the details and providing the contents of `id_rsa` in the private key textarea.

In GitHub I have added the corresponding `id_rsa.pub` as a deploy key onto the repository. When clicking build the result is:

```
------------------------- Wed Jul 24 2019 06:23:37 GMT+0000 (Coordinated Universal Time)
Build started for satis
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/satis/6/source_files'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is there a step I am missing out here?

**If applicable, content of `captain-definition` file:**

```
{
    "schemaVersion": 2,
    "dockerfilePath": "./Dockerfile"
}
```

**Steps to reproduce the problem:**

1. Generating new key: `ssh-keygen`
2. Copy contents: `cat ~/.ssh/id_rsa`
3. Paste into the SSH key field in CapRover
4. Copy contents of pubkey: `cat ~/.ssh/id_rsa.pub`
5. Add public key to repository deploy key on GitHub.
6. Click save and then force deploy.

**Answers to the following questions where applicable:**
- Ubuntu 18.04
- 2GB ram
- Digital Ocean Droplet.

Thanks for your assistance.

**Comment by githubsaturn** [comment]
What format do you use when entering "Repository" field in the deployment tab?
Do you use the exact format as `github.com/someusername/somereponame` ?

**Comment by Jamesyps** [comment]
Yes, this is the repository string:

```
github.com/Jamesyps/Redfinch-Satis
```

**Comment by githubsaturn** [comment]
Then you're doing it right. I just retried it and it worked well. The only difference is that I used an online SSH key generator: https://8gwifi.org/sshfunctions.jsp but it shouldn't make any difference.

Are you on the latest version, 1.4.0?

**Comment by Jamesyps** [comment]
Yes, 1.4.0.

It looks like there must have been an issue with the keys I generated, using the tool you've linked to the connection is now working perfectly.

Thanks for your help!

**Comment by sneak** [comment]
FYI @githubsaturn that URL https://8gwifi.org/sshfunctions.jsp - it doesn't generate the SSH keys clientside in the browser - those are generated on the server and sent down.  The server could be logging all of them.

**Comment by githubsaturn** [comment]
@sneak that's 100% correct and those keys should only be used for demo purposes.

**Comment by sneak** [comment]
FYI a good command line for outputting the required key (it has to be in PEM format, and `ssh-keygen` doesn't use that anymore by default) is as follows:

```
ssh-keygen -m PEM -t rsa -b 4096 -C "caprover" -f ./key -q -N ""
```

**Comment by maietta** [comment]
This drove me nuts. I have confirmed that the PEM formatted key was the correct way and was accepted by Github. This was not in their documents.

**Comment by joshh71390** [comment]
> 

in that case where can i put all my bank info?

**Comment by JustinGuese** [comment]
can confirm, the ssh generate key command in the docs doesn't work, please add @sneak 's solution to the doku or even in the app itself... this is embarrassing that this is an issue since 2021 and no one fixed it

**Comment by vinaydate** [comment]
> @JustinGuese - docs are editable. I suggest you edit the docs if you find any other mistakes.
> 
> ![image](https://user-images.githubusercontent.com/10582082/255213974-51149cbb-a4a4-4da0-9cc0-29baa038ae89.png)

Created a PR with working ssh-keygen command as suggested [here](https://github.com/caprover/caprover/issues/464#issuecomment-588590305)
