### ISSUE TITLE
Some Domain Alias may not be added

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#465]
Im trying to add some Aliases to my CapRover Applications.
All are subdomains of a domain which is NOT the caprover root domain.

Some of them work perfectly but some throw the "verification failed" error.

I have no clue why this is happening...

I'm using a wildcard operator on the DNS entry, and if i'm opening the subdomains in the browser im greeted with the caprover "nothing here yet" page, which mean: my DNS entry work.

the working domains & subdomains are:
student.<domain>
<domain>

the non-working are:
teacher.<domain>
api.<domain>

**Comment by githubsaturn** [comment]
As long as the URLs are not already used, this shouldn't happen. Can you try getting the logs during the verification?

Simply run the following after immediately after your verification failed and copy the logs here.
```
docker service logs captain-captain --since 5m
```

**Comment by jappyjan** [comment]
this may be closed. i just retryed now and it worked... maybe a just a little hickup from the server?
