### ISSUE TITLE
How enable websockets when using https? 

### ISSUE THREAD

**Issue by bizmedia** [caprover/caprover#466]
How enable websockets when using https? ws://servername:4000 works fine, but I want use wss://servername instead.

**Comment by githubsaturn** [comment]
wss uses https, port 443. If your websocker runs fine on `ws://domainname.com` you should be able to use `wss://domainname.com` if you have enabled HTTPS. 

But you're using PORT 4000 which is not a default port. HTTPS runs on port 443. You cannot use port mapping to use port 443 as it will completely break https in your server.
