### ISSUE TITLE
NetData addiotional mounted storages

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#468]
I'm currently running CapRover on a Server VPS with only 20GB of internal storage (absolutely enough for my applications) which is connected to a 250GB Storage Server (mounted @ /mnt/storagespace)

Is there a way to enable NetData monitoring for that external storage?

Right now i get a notification when my main storage (20GB) is about to fill up, i would like to receive an notification like that for my external storage as well.

**Comment by githubsaturn** [comment]
NetData is a separate project and maintained on its own. The built-in version of NetData in CapRover has default options, but you can always install your own customized version of NetData and run it beside CapRover. For customization details, look into NetData project documentation: https://github.com/netdata/netdata
