### ISSUE TITLE
[Deployment Issue] Gitlab won't load when configuring GITLAB_OMNIBUS_CONFIG to use https

### ISSUE THREAD

**Issue by MyndPhreak** [caprover/caprover#469]
What is the problem?
Gitlab will not load when GITLAB_OMNIBUS_CONFIG is set to include https in the external_url. Setting HTTPS in Caprover will allow Gitlab to be accessible via HTTPS, however it will not allow cloning or other URL related things via HTTPS due to Gitlab only detecting HTTP.

If applicable, content of `captain-definition` file:
Regular one-click app from the repository.

Steps to reproduce the problem:
Deploy Gitlab, set GITLAB_OMNIBUS_CONFIG to external_url 'https://git.example.com'. This will cause Gitlab to go in an endless loop of trying to pull LetsEncrypt certificates but fails. Setting external_url in the gitlab.rb without using GITLAB_OMNIBUS_CONFIG and then running gitlab-ctl reconfigure will cause the website to throw a 502 error.

Answers to the following questions where applicable:
- Captain running on Ubuntu 18.04
- 64BG RAM

**Comment by githubsaturn** [comment]
This is a question for gitlab community. Gitlab Docker image is being maintained by gitlab team. I suggest you open an issue with them asking for help on how to setup external_url behind a nginx reverse proxy that terminates HTTPS. Gitlab team should be able to point you to the right direction. 

My "guess" is that gitlab internally tries to setup HTTPS certs and it assumes that it can use SSL for HTTPS. However, in CapRover, HTTPS is being fully managed by CapRover via an nginx reverse proxy. Gitlab must have an option for this. Putting gitlab behind a reverse proxy is a common practice.

**Comment by colarocker** [comment]
GITLAB_OMNIBUS_CONFIG:
 `external_url 'https://your.adress.com/'; nginx['listen_port'] = 80; nginx['listen_https'] = false` 
works for me (even tho i think the webinterface is now a littlebit less responsive / slower.)

**Comment by forgulencia** [comment]
> GITLAB_OMNIBUS_CONFIG: `external_url 'https://your.adress.com/'; nginx['listen_port'] = 80; nginx['listen_https'] = false` works for me (even tho i think the webinterface is now a littlebit less responsive / slower.)

You literally saved my day. Thank you.
