### ISSUE TITLE
Repository information is not saved if pass/user is not provided

### ISSUE THREAD

**Issue by mariogrip** [caprover/caprover#473]
Repository information is not saved if pass/user is not provided. As all our repositories are open we wont need login into to clone. Nor does it give any sort of error when trying to save. 

Steps to reproduce:
In apps deployment settings, Enter just url and branch for git, press save.

**Comment by githubsaturn** [comment]
Just enter a username with a `anything` as a password. The password doesn't need to be the real password.

**Comment by mariogrip** [comment]
> Just enter a username with a `anything` as a password. The password doesn't need to be the real password.

Sure this works as a workaround. but it isn't really "user friendly". It does not give any sort of error or anything that somethings not right when not providing with pass/user.
