### ISSUE TITLE
How to pull from a private/custom Docker repo?

### ISSUE THREAD

**Issue by marcopeg** [caprover/caprover#474]
Hello,
How do I setup CapRover to pull from a GitLab private image repository?

Thanks!

**Comment by githubsaturn** [comment]
You can add the private registry creds to CapRover.

Cluster > Add remote registry > (enter your creds)

You can disable the default push registry if you don't want to push your built images to your private registry. It saves time and resource during deployment. Pushing the built images to a remote registry is only needed when CapRover is running as a cluster. Single server deployment don't need a default push registry.
