### ISSUE TITLE
Warning that persistent volume exists.

### ISSUE THREAD

**Issue by ComputerCarl** [caprover/caprover#475]
**Is your feature request related to a problem? Please describe.**
I created a persistent app and when I viewed the domain, it had the content of another app. It took me a minute to figure out that I had labeled a Persistent Directory the same as another app.

**Describe the solution you'd like**
Perhaps a warning that the label/volume you are trying to create already exists.

**Comment by githubsaturn** [comment]
It's not possible to do this in a clean, neat, and reliable way. Not all volumes are created by CapRover. Also, in case of one-click apps, they'll get named dynamically by using the template. 

We _can_ implement a half-working solution only in the Apps Config page, but it'll do more damage than good.
