### ISSUE TITLE
Automatic detection of repos with a `captain-definition` file

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover#477]
I'd like to propse a much faster way of deploying, it's similiar to [zeit's now](https://now.sh).

- Create a GitHub application, with which people will sign in through their instance
- Give permissions for all of the repos
- Just create a `captain-definition` and push

Ideally at this point, the CapRover instance will have noticed that you pushed a commit with a `captain-definition` and set up all of the webhooks / automatic deployment configurtion needed.

Also what would be a good solution to this:
![](https://i.imgur.com/Y8UMXE3.png)

How would a user configure that path *without* having to edit it from the frontend?
How about CapRover automatically find its path to the `captain-definition` file?

**Comment by githubsaturn** [comment]
> How about CapRover automatically find its path to the captain-definition file?

This is not possible. In fact, one of the main reasons that the path to captain-definition exists, is the situation where multiple captain-definition files exist in the app, perhaps one for staging, one for production.

> How would a user configure that path without having to edit it from the frontend?

This path, similar to other configs such as env vars, volume and etc are part of the app configuration. I am not sure what you're suggesting here if it's not configurable via the frontend.

**Comment by fr3fou** [comment]
> This path, similar to other configs such as env vars, volume and etc are part of the app configuration. I am not sure what you're suggesting here if it's not configurable via the frontend.

I'm suggesting to figure out a solution that doesn't involve the frontend. Ideally it would make the frontend *optional*

**Comment by githubsaturn** [comment]
> Create a GitHub application, with which people will sign in through their instance

This is not possible to do with an open source version. It requires a central app that github app connects to. Github app cannot connect to multiple backends. This feature, similar to other features, such as 2 factor SMS auth and etc, could be part of a future managed version, not the self-hosted version.

**Comment by fr3fou** [comment]
What about giving the user the ability to set this up themselves? So they would create the GitHub app themselves and hook it up. I've seen this done in other projects

**Comment by githubsaturn** [comment]
Can you point out an example?

**Comment by fr3fou** [comment]
Sure, [disintegration/bebop](https://github.com/disintegration/bebop)
