### ISSUE TITLE
[Deployment Issue] Ability to expose user's original source IP to containers

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#479]
This is directly related to - https://github.com/moby/moby/issues/25526.

---

Apps deployed with caprover don't have the original source IP of a connection. Every request appears as if it's coming from the same IP (e.g. `10.255.0.2`).

This breaks a certain class of apps, as they cannot differentiate between different user IPs.

---

In my specific use-case, poste.io's spam filter breaks, rendering the mail server un-usable, because the spam filter thinks all mails are spam.

Relevant doc -  https://poste.io/doc/network-schemes

> SPAM filters, karma system, relaying itself needs to see real source IP. Lot of containerized network schemes has problem with loosing real source IP due packet manipulation. While processing at HTTP(s) ports are built to be tolerant to not know real IP and can be reverse-proxied, hiding souce IP to core mailserver ports can get your mailserver to state of open relay

**Comment by githubsaturn** [comment]
What's the suggested solution here?

CapRover is built on top of Docker, therefore, it inherits the limitations that come with Docker. There are cases where CapRover retrofitted the behavior. For example, HTTP requests are properly being marked with `x-forwarded-for` header with the actual original IP. But if you're using port forwarding, you're bypassing the nginx layer, therefore you lose the origin IP as mentioned here: https://github.com/moby/moby/issues/25526

**Comment by devxpy** [comment]
I don't have a solution, sorry. I was just hoping to spark discussion :-)

I am not very familiar with nginx, but do you think there could be a way to use nginx as middle man for non-HTTP request also, but still preserve the original IP?

[This](https://www.nginx.com/blog/ip-transparency-direct-server-return-nginx-plus-transparent-proxy/#ip-transparency) article seems to suggest something along these lines.

**Comment by githubsaturn** [comment]
You can use the nginx as a TCP layer, without involving HTTP. However, the HTTP headers, including `x-forwarded-for` as the name suggests, are only available with HTTP requests.

As for solution, as you've seen it yourself in that moby thread, it's a problem with Docker swarm network. Until they come up with a solution, this is something that cannot be avoided.

**Comment by devxpy** [comment]
Alright, thanks for the input.

Will update this if I can figure out some sort of hack.

**Comment by githubsaturn** [comment]
As a hack, you can try this snippet as your pre deploy script for poste.io, it may work:
```
var preDeployFunction = function (captainAppObj, dockerUpdateObject) {
    return Promise.resolve()
        .then(function(){

            var ports =  dockerUpdateObject.EndpointSpec.Ports;
            if (ports)
            {
	            for (i = 0; i < ports.length; i++) { 
				  ports.PublishMode = 'host'
				}
            }

            return dockerUpdateObject;
        });
};
```

**Comment by devxpy** [comment]
Wow, that works instantly. Thank you so much!

Will update the poste.io one-click-app.

**Comment by githubsaturn** [comment]
One click apps don't accept pre-deploy scripts. Pre-deploy scripts are meant be rarely used. Maybe just a add a comment to the `instructions.end` part of the one-click app and link to this discussion, so people know what to do next.

**Comment by locvfx** [comment]
I'm lost, I don't know what to do with that pro-deploy script.
AfterI pasted it in the pre-deploy section and saved, the service could not start.

**Comment by githubsaturn** [comment]
Did you copy the exact snippet as mentioned in this comment? https://github.com/caprover/caprover/issues/479#issuecomment-520902309

**Comment by KoenvdStroom** [comment]
I have the same problem as mentioned 2 comments above. When I dont have the predeploy script it gives the following error in my browser: https://img.kvds.dev/i/VopHR.png
And when I do use the predeploy script it logs the following in the logs and then the logs go completely blank as if it is going to start any moment, but is just doesn't start and gives a 502 error on the page.


2021-08-01T14:13:32.244748763Z [!] WARNING: User-initiated shutdown.
2021-08-01T14:13:32.266084963Z [cont-finish.d] executing container finish scripts...
2021-08-01T14:13:32.272828627Z [cont-finish.d] done.
2021-08-01T14:13:32.275260780Z [s6-finish] syncing disks.
2021-08-01T14:13:32.281490840Z [s6-finish] sending all processes the TERM signal.
2021-08-01T14:13:35.288304141Z [s6-finish] sending all processes the KILL signal and exiting.

**Comment by FrinkMan** [comment]
I don't like reopening old issues, but the pre-deploy script doesn't seem to be changing the network driver mode... I've checked with by following the docker service logs, and logging the dockerUpdateObject before the script returns it, and it is setting the PublishMode of each port to host, but when I check the logs in Poste, it's still showing the IP as my Docker IP... any suggestions?

**Comment by colarocker** [comment]
i used the recently proposed solution from the moby issue, DIRD: [https://github.com/newsnowlabs/docker-ingress-routing-daemon](https://github.com/newsnowlabs/docker-ingress-routing-daemon), works like a charm. single node here, this is an example for my poste.io container (srv-captain--mail): `sudo ./docker-ingress-routing-daemon --install --preexisting --ingress-gateway-ips 10.0.0.2 --services srv-captain--mail --tcp-ports 25,110,143,465,587,993,995,4190 --udp-ports 25,110,143,465,587,993,995,4190`
