### ISSUE TITLE
[Deployment Issue] Timeout while building - crashes server (possible bug?)

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#480]
What is the problem?
* *SOMETIMES*... Caprover times out.  
  * When it times out, *SOMETIMES* it crashes my server.
  * *SOMETIMES* its just a timeout after which I can cancel and i'm prompted to re-auth.

This has only happened on one of my apps, which is building using create-react-app and npm.   But this is the app I also deploy the most, by a long shot.   It *seems* to happen once, when I deploy my first app for the day; leading me to believe it is something with the authentication process... but thats a COMPLETE shot in the dark. 

It's POSSIBLE i'm running out of ram (2GB), but i'm only running 4 containers;
3x gunicorn
1x nginx static file host

All run fine when i'm not building this one app.

**Dockerfile:**
```
# base image
FROM node:10.15 as build

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./studio/ /usr/src/app/
RUN yarn install
RUN npm run build

FROM nginx
COPY ./vhosts.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
```

Steps to reproduce the problem:
1. Deploy the Dockerfile after a significant amount of time.

Answers to the following questions where applicable:
- Your OS and version? Ubuntu for AWS image...
$>lsb_release
LSB Version:core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.
20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-a
md64:security-9.20160110ubuntu0.2-noarch

- RAM?
**2G**

**Comment by githubsaturn** [comment]
What exactly do you mean by timeout? Are you seeing a frozen HTTP request? The build process is asynchronous. 

What's happening here is probably VPS running out of RAM. The fact that it happens after a long period, suggests that after RAM is being used by other applications, Docker process runs out of memory. 

The build process for nodejs applications can be surprisingly resource heavy. I suggest you look into other offloading the build process to somewhere else to reduce the load on your CapRover server.

There are two ways to achieve this:
- Go all the way and implement a proper build pipeline, for example, Gitlab: https://github.com/caprover/caprover/issues/436
- Partial build on local machine, and deploy on CapRover: https://caprover.com/docs/recipe-deploy-create-react-app.html

**Comment by derek-adair** [comment]
WHAT fucking 8GB? thats insanity.  JS devs... you so silly.

looking at netsuite the ram consumption is @ 72%.  Is there any other way to diagnose RAM issues through caprover?

I'll try a couple more things but it really is probably a RAM thing now that i am looking at the stats.  There is also a specific error that happens that I forgot to copy, i'll put that here to hopefully help others if they run into it.

Switching to external build is inevitable for me so maybe i'll set that up.

ALSO - it'd be rad to support full local builds somehow.  But that is probably really complicated...

**Comment by derek-adair** [comment]
Or even a configurable "build node" where I can spin up an ec2 instance for building that meets the build required resources.

**Comment by derek-adair** [comment]
Ya so my server spiked to about 92% ram consumption in the build.  PROBABLY not ideal.

**Comment by githubsaturn** [comment]
yup - 92% usage of RAM is definitely a red flag. Your best option at this point is to offload your build process to a 3rd party provider to hefty amount of RAM.

> ALSO - it'd be rad to support full local builds somehow. But that is probably really complicated...

This requires a dependency of Docker, not possible to bundle it with the npm package.

**Comment by derek-adair** [comment]
I'm not sure I follow.  I was envisioning something like how gitlab lets you use your own server as a builder.  It also probably wouldn't make sense w/o a registry to push to (like gitlab). So... probably a large endeavor.

I'll probably just fully integrate w/ gitlab CI.

**Comment by githubsaturn** [comment]
Not sure what you're suggesting here.

You have:
- Your CapRover server.
- Your local machine.

You can build on either of these two machines. By default you use CapRover server. I thought what you were suggesting was to add the ability to build on local machine (your laptop) and push it to CapRover. This, as I said above, requires a dependency on Docker, not everyone has Docker on their laptops and bundling Docker with CapRover CLI is not possible.

Another option is to build on a 3rd server, dedicated for building. This is also possible using Jenkins and other types of build tools.

**Comment by derek-adair** [comment]
Right, i was really suggesting the 3rd server.  But thats probably just best left to jenkins and the like.
