### ISSUE TITLE
Root Domain Configuration - Verification Failed

### ISSUE THREAD

**Issue by suphero** [caprover/caprover#482]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I cannot configure root domain. I am getting "Verification Failed" message.

Steps to reproduce the problem:
- Go to Dashboard
- Set Root Configuration Url
- Press "Update Domain" button

Answers to the following questions where applicable:
- Your OS and version: Ubuntu 18.04.2
- RAM: 1 GB
- Source/Location: AWS/Ohio
- Version: 1.5.2

**Comment by githubsaturn** [comment]
Your DNS settings might have not been propagated completely. Use this tool:
https://dnschecker.org

If you set `*.root.domain.com` to be pointing to your server's IP, enter `random.root.domain.com` in the box in DNS Checker linked above to check the DNS. Does it look okay?

**Comment by suphero** [comment]
I have checked my DNS settings. It looks propagated.
<img width="1255" alt="Screen Shot 2019-08-15 at 18 43 44" src="https://user-images.githubusercontent.com/846531/63107085-f64bcc00-bf8c-11e9-8c91-bba2f9ae4637.png">

But I am still getting same error.
<img width="1104" alt="Screen Shot 2019-08-15 at 18 44 02" src="https://user-images.githubusercontent.com/846531/63107120-06fc4200-bf8d-11e9-8d25-d4f72cb699fa.png">

**Comment by githubsaturn** [comment]
Everything looks good. One possibility is that your server may have had the wrong DNS cached.

Try rebooting your server and retry again. If not solved, get the server logs so we can look at it:

To get the logs:
- Enter the root domain and get the error message (similar to the screenshot above)
- Right after the error, on your server, run `docker service logs captain-captain --since 2m` to get the logs for the last 2 minutes. Now, copy the logs here so we can look at it.

**Comment by githubsaturn** [comment]
Wait a second, I just tried `http://random.heroku.harunsokullu.com/` and I don't see the default CapRover page. Did you follow the standard installation flow as described in the docs?

**Comment by suphero** [comment]
I just reboot my server and now I configured root domain url. I think the problem was about firewall on the AWS side. I wasn't having these issues with DigitalOcean :(. Thank you for the support.
