### ISSUE TITLE
Gracefully migrate traffic during deployment

### ISSUE THREAD

**Issue by aberba** [caprover/caprover#483]
When I have requests being processed and I deploy a new build, CapRover terminates them immediately. 

I would like to see CapRover **wait** until those being processed are finished **whilst blocking any incoming request**. And them kill the current app **only when all active requests have finished being processed**. 

This feature is [well supported in something like app engine](https://cloud.google.com/appengine/docs/standard/python/migrating-traffic) and prevent unexpected client action failures due to immediate termination of process by CapRover during deployment as [explained here](https://www.quora.com/What-are-the-disadvantages-of-using-Google-Cloud-App-Engines-Traffic-migration-functionality-when-deploying-a-new-version)

It doesn't need to support everything...just the basic traffic migration as proposed above.

**Comment by githubsaturn** [comment]
CapRover does wait for the new container to start up before it kills the previous container.

With regards to requests, yes, there might be a small portion of request that fail during the transition. But that's the responsibility of a resilient client code to handle failed requests and retry them.

As for implementing this naively on CapRover, it requires the knowledge of whether a request is being processed, this is only possible if routing layer was via CapRover, however, routing layer is done via nginx and nginx doesn't expose the details about each individual request. Implementing this is way out of scope for this project.
