### ISSUE TITLE
Constantly getting Error Code: 1113  Message: Too many wrong passwords... Wait for 30 seconds and retry.

### ISSUE THREAD

**Issue by solomon23** [caprover/caprover#485]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Often when i login i get the error:
Error Code: 1113  Message: Too many wrong passwords... Wait for 30 seconds and retry.

I'm able to login to the website but from the console using ` caprover serversetup` it returns me that every time

I'm also see caprover crash because i'm running out of memory I think.  It starts giving me a loop of the wrong password wait 30 second error.  

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version?
ubuntu 18.04
- RAM?
1gb

**Comment by solomon23** [comment]
I have a guess that what's happening is the crash is causing my cookie token to become invalid.  After the crash I keep getting the 30s error on the client even after i'm able to login through the website.

I logged out of the console and and tried to log back in and kept getting the 30s error.  Eventually it let me in though.  I would suspect there's a few issues with how that error gets displayed but one of them is related to the server crashing

**Comment by solomon23** [comment]
Here's another repro that gives you similar problems:
Log out of the website UI
login and makes sure remember me is turned off
try to login - often times you'll get the 30s warning right then
if you can login - open the dev console
refresh your browser
you'll see in your console "Password is incorrect" and the login page will show
Try to login
you'll get the 30s warning

**Comment by githubsaturn** [comment]
As the error suggests, the problem is that the password is entered wrong so many times. This is implemented to avoid brute force attacks.

Are you sure you're not under brute force attack? I've tried your repro method, and I wasn't able to see the problem. Regarding the error in the console, it's expected for the first refresh. You're refreshing an "authenticated" page, and you'll lose your aut token upon browser refresh. Therefore an authentication error is thrown and you'll get redirected to the login page.

I'll keep the issue open to see if anyone else is experiencing the same problem.

**Comment by sneak** [comment]
I'm having the problem.  Looking in the logs I'm definitely under a brute force attack from the internet.  That shouldn't prevent me, a legitimate administrator, from logging in - that's a clear DoS bug.

**Comment by sneak** [comment]
I ran into this issue.  I had a window open on another computer on my LAN, when I stopped and restarted docker, the clientside js was constantly trying to refresh the build logs and used an old session token, and triggered this, making me unable to log in from my computer downstairs.

I think perhaps the client app should keep an authentication failure count for looping api requests and bounce back to the login page (and stop all log-fetching and appdata-fetching loops, obvs) by itself.

**Comment by githubsaturn** [comment]
Good call @sneak 

I'll fix that.

**Comment by sneak** [comment]
Be careful you don’t make it too hair-trigger though, otherwise a momentary network failure on the build page would annoyingly log you out. Maybe after 10 or 15 consecutive failures or something.

**Comment by githubsaturn** [comment]
> Be careful you don’t make it too hair-trigger though, otherwise a momentary network failure on the build page would annoyingly log you out. Maybe after 10 or 15 consecutive failures or something.

Yes - definitely.

Just to make sure I understood your case correctly:
The window that you had left open was somehow using a wrong password? Did you change the password in between?

I am thinking if it's just an old session token, it won't cause "Too Many Wrong Password" error.

**Comment by sneak** [comment]
No, I didn’t change the password, but I did stop docker, edit the config json, and restart it.
