### ISSUE TITLE
Question: How to deploy using Gitlab CI/CD ?

### ISSUE THREAD

**Issue by cocodrino** [caprover/caprover#491]
hi guys, I'm interested in use gitlab ci/cd to deploy my project in my server, after run the test if all them pass then deploy...I know that exist a little small documentation talking about github/bitbucket hooks, but I think that it's not exactly what I am looking for...thank you so much guys, keep the good work

**Comment by o2b-nolan** [comment]
Hello :)

After running your tests, you can simply call Webhook provided by Caprover with curl.
Try using the variable system provided by gitlab CI/CD to avoid putting this kind of information in your sources.

It should look like this:
![idea64_qh4SNYhdS6](https://user-images.githubusercontent.com/54771141/64077491-476bf780-ccd1-11e9-8591-8a3fb4d58b26.png)

**Comment by githubsaturn** [comment]
There is now a guide on the website for gitlab: https://caprover.com/docs/ci-cd-integration.html
