### ISSUE TITLE
[Deployment Issue] Dashboard not working on new install

### ISSUE THREAD

**Issue by Rillian-Grant** [caprover/caprover#501]
What is the problem?
When I run `docker run -e MAIN_NODE_IP_ADDRESS='127.0.0.1' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` It finishes without any errors. However I cannot view the dashboard and it does not seem like the port 3000 is in use by any container. After fiddling around for a bit and deleting containers and recreating them it started to say that port 3000 was in use in the output when I tried to reinstall caprover with the above command. I ran netstat and found that it was in use by dockerd but no container was using it.

Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 18.04
- RAM?
6GB

**Comment by lzzy12** [comment]
Same happening to me too except for the fact that I'm deploying on GCP VM. It finishes without any error. But when I visit http://server-ip:3000 I get refused connection. I'm sure, I've enabled port 3000 in the firewall

**Comment by githubsaturn** [comment]
@Rillian-Grant 
Are you using snap version by any chance?

**Comment by golyalpha** [comment]
Same's happening here, running on ARM64, docker's installed following instructions on Docker's website (through apt)
