### ISSUE TITLE
out of memory protection

### ISSUE THREAD

**Issue by mxdpeep** [caprover/caprover#506]
I have tried to install **adminer** on a low RAM node with other two apps, got an installation error -> **out of memory**. Uninstall didn't work, `docker ps` got me error too. Finally `ps axu` from cli worked, manual kill for docker process needed this time.

So I assume we need some sort of a protection so that a node can have a last resort safe pool to make administration working from UI.

**Comment by pouledodue** [comment]
this.
I dream of a paas with oom protection

**Comment by githubsaturn** [comment]
If you're referring to Docker memory reservation, both captain engine and nginx containers are already flagged with some memory reserved for them:
https://github.com/caprover/caprover/blob/e38d54674485ebbe040f6551e4f687e509655b4b/src/utils/CaptainInstaller.ts#L369-L371

and 

https://github.com/caprover/caprover/blob/0381533ddb61650c763e7897c2744f72eac2d125/src/user/system/LoadBalancerManager.ts#L520-L522

But this is not a silver bullet as the OS might not be able supply the requested reserved memory at all. However, this is as far as we can go. If there is any other flag that I am not aware of, please let me know and we'll add it to the Docker service JSON.
