### ISSUE TITLE
[Deployment Issue] Verification failed

### ISSUE THREAD

**Issue by dg-otrs** [caprover/caprover#507]
Hey Guys,

not sure how to handle this issue. My DNS entry works well... configured as described in the docu.

What is the problem?

Restart of captain fails because of:

captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | Captain Starting ...
...
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:38.447 pm    NGINX is fully set up and working...
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:38.449 pm    Migration not needed, skipping.
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:38.452 pm    Captain Certbot is already running..
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:38.455 pm    Updating Certbot service...
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:38.498 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:40.540 pm    Ensuring Docker Registry is running...
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:40.697 pm    Captain Registry is already running..
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:40.699 pm    Updating Certbot service...
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:40.764 pm    **** Captain is initialized and ready to serve you! ****
captain-captain.1.1qzl07hc3y7r@my.domain.cn.com    | September 11th 2019, 7:12:41.778 pm    Error: Wrapped: Verification Failed for xx.xx.xx.com

Steps to reproduce the problem:
Well running caprover instance was restarted

**Comment by solomon23** [comment]
Can you give us a few pieces of info to help troubleshoot this
1. can you ping the url it's trying to verify from the captain box and verify it's the correct ip
2. how did you install caprover ?
3. which os/version are you running on ?
4. what version of docker are you using?
5. just to confirm the `xx.xx.xx.com` wasn't the domain in the logs.  You removed that for privacy reason - correct?

Thanks !

**Comment by dg-otrs** [comment]
I have removed now /captain/* and reinstalled with --dns for the docker run command. runs for now... lets see!

**Comment by githubsaturn** [comment]
@dg-otrs 

Great. Can you please provide more details for other users that might face the same problem?
