### ISSUE TITLE
Enable websocket support from config

### ISSUE THREAD

**Issue by devxpy** [caprover/caprover#510]
While creating a template for [droppy](https://github.com/silverwind/droppy), I noticed that my config doesn't work out of the box, and I have to manually tick the "Enable websocket" checkbox. 

It would be nice to have this configure-able in the one-click app template, similar to how `containerHttpPort` works.

**Comment by abs0lom** [comment]
+1 this feature would be useful

**Comment by fiblan** [comment]
duplicated #852
