### ISSUE TITLE
[Feature Request] Plugin System

### ISSUE THREAD

**Issue by sean-nicholas** [caprover/caprover#514]
**Is your feature request related to a problem? Please describe.**
Some of the feature requests here on github are getting closed because they are out-of-scope. Which is perfectly fine because the goal is to keep caprover simple.

Some out-of-scope feature requests:
https://github.com/caprover/caprover/issues/497
https://github.com/caprover/caprover/issues/492
https://github.com/caprover/caprover/issues/400

**Describe the solution you'd like**
A plugin system could open caprover in a way that other developers could add their own features.

Caveats: 
- Adding a plugin system in hindsight could be pretty tedious
- Probably some parts of caprover need to be rewritten
- I have no idea how one could extend react with custom components that are loaded at runtime

Benefits:
- Obviously caprover can support more features while still maintaining its slim core product
- Other developers can share their extensions and help other people with the same problem
- Caprover gets even more traction because it supports more edge cases

**Describe alternatives you've considered**
An alternative is forking caprover but you don't want to have an ecosystem with many forks. Furthermore, this would not create a "market" for extensions. You could not combine two different features because they are buried in two different forks.

**Comment by githubsaturn** [comment]
It's impossible to provide a generic plug-in system in a way that can address all requests from everyone.  Having said that, we already do have some capabilities for anyone who's willing to customize CapRover. 

- multiuser case: write your own authentication system and sit between CapRover API and the end user.
- any customization to docker services: there's a predeploy function that can be used.

**Comment by sean-nicholas** [comment]
Yeah, I think you are right. Plugin systems are very hard to design well and probably a major rewrite would be needed. Just wanted to hear your opinion on that topic. And the alternatives exist as you pointed out. Didn't think of a proxy between caprover and the end user. That's a pretty good idea. Thx :)

**Comment by ckc** [comment]
How about the LDAP like integration? It's useful for internal dev team, it's better than only passphrase

**Comment by iBobik** [comment]
Do you have recommendation to some proxy for this use-case? Something easilly configurable, deployable to caprover, something where I can create tokens and supported actions for them.

I would like to run `caprover deploy` in GitLab CI, but with credentials allowing to deploy only to specific app, or app namespace (for review apps).

I could image it can be "coded" in e.g. nginx config, but I would prefer something more simple. :-)

**Comment by githubsaturn** [comment]
There is a feature request for this: https://github.com/caprover/caprover/issues/698

We'll get to it at some point.
