### ISSUE TITLE
Expiry of LetsEncrypt Certificates

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#517]
FIRST: I actually don't know if this is a bug or if i did not found the right documentation to the problem..

What is the problem?

I just received E-Mails from LetsEncrypt stating that my Certificates are going to expire soon and that i would have to renew them.

How do i renew certificates which have been auto-created by caprover?
Is this even possible?
Will caprover renew them by itself? if so: when?

Answers to the following questions where applicable:
- Linux/Debian
- 4GB

**Comment by githubsaturn** [comment]
CapRover automatically renews your certificates. The reason that you received some emails saying that you need to renew your certificates could be that you created some apps with those names and then you deleted them, and then you might have recreated them.

Every 24hr all your certificates are checked for expiry and will automatically be renewed.

**Comment by jappyjan** [comment]
Exactly what I did!
Nice to hear that. Thanks a lot.

Am 04.10.2019 16:01 schrieb Kasra Bigdeli <notifications@github.com>:

CapRover automatically renews your certificates. The reason that you received some emails saying that you need to renew your certificates could be that you created some apps with those names and then you deleted them, and then you might have recreated them.

Every 24hr all your certificates are checked for expiry and will automatically be renewed.

**Comment by mathiasfoster** [comment]
Reopening this issue — I received an email from Let's Encrypt saying that the certificate for a domain on an active project is expiring in 8 days.
Caprover is on a Digital Ocean VM, I set it up not with the one-click install but by following the setup instructions in the documentation.
What could I investigate to see what is happening?

**Comment by githubsaturn** [comment]
The common case is that you've previously used the same domain name and then removed the server and started a new one. 

Simply just check your SSL expiry date using an online tool like this:
https://www.sslshopper.com/ssl-checker.html#hostname=captain.server.demo.caprover.com

Does it say the domain expires in 8 days?

**Comment by mathiasfoster** [comment]
Thank you, that is exactly what it is!

To save you from answering this question, I've taken the liberty of submitting a pull request adding this to the documentation: https://github.com/caprover/caprover-website/pull/101
