### ISSUE TITLE
Integrating WordPress with React Website within CapRover

### ISSUE THREAD

**Issue by ngvntoan** [caprover/caprover#519]
Dear Team,

First of all, I want to say thank you so much for your contributes. This is a wonderful project, help me save a lot of money.

I have a problem that intergating a Wordpress website (http://mydomain.com/blog) with current site (http://mydomain.com, written by React), two website deployed using CapRover (host by Digital Ocean).

I want Wordpress & React site are using same domain but different sub folder (Wordpress ending with /blog). I found a solution from wordpress.org https://codex.wordpress.org/Integrating_Wordpress_with_Your_Website, but I don't know how to do this within CapRover?

Thanks in advance,
ToanNV

**Comment by githubsaturn** [comment]
You need to configure custom nginx configs: https://github.com/caprover/caprover/issues/432
