### ISSUE TITLE
[Deployment Issue] - 500 error

### ISSUE THREAD

**Issue by jajoosam** [caprover/caprover#520]
What is the problem?
When I deploy, I get this error:

```
Something bad happened: cannot deploy skrrt at capalot.
500 - "<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.17.4</center>\r\n</body>\r\n</html>\r\n"
```

If applicable, content of `captain-definition` file:
```
{
 "schemaVersion" :2 ,
 "templateId" :"python-django/3.6.3"
}
```

I don't know what the problem is - not able to update any of my apps 😕

**Comment by jajoosam** [comment]
My caprover instance doesn't even load: https://captain.hub.jajoo.fun

**Comment by githubsaturn** [comment]
Your CapRover server is not running. Have you previously been able to access the dashboard?

If not, read the docs.

If you have previously been able to access the dashboard, and it's not working anymore, run the following commands and copy the output here to get some insight as to what's happening:

```
docker service ls
```

and 

```
docker service logs captain-captain --since 5m
```

**Comment by jajoosam** [comment]
Yes - my bad.

The problem was that my VM ran out of storage 😕

Thanks for your help :)
