### ISSUE TITLE
Pre deploy script metrics

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#521]
Hello guys,

Is it possible to get access to build metrics (success, duration, commit hash, log, etc.) From inside the pre-deploy script?

This would solve the problem of not knowing if a build, triggered by a git push finished successfully or failed without signing in to the dashboard.

This way, I could write a pre-deploy script which would for example send me a slack notification that build has failed or succeeded and append the failure log if it fails

**Comment by githubsaturn** [comment]
pre-deploy functions are invoked right after deploying the new service (after the build process) is done and won't get invoked if the build has failed.

In general, for the metric notifications, it's more flexible to use standard metric aggregation techniques, such as log parsing. CapRover publishes a pretty verbose log. You can write a separate service that picks up the log and sends appropriate notifications when certain events happen.

Alternatively, you can use log processor services like DataDog.

**Comment by jappyjan** [comment]
thanks for the quick reply,

may you point me to the directory where caprover is saving it's build-log files? i just don't find them...
and the official documentation only mentions how to acces the live logs of running containers...

**Comment by githubsaturn** [comment]
The build logs aren't saved, they are held in memory - they are reported back via an API. I was referring to the logs for captain-captain service.
