### ISSUE TITLE
[Deployment Issue] How to add additional volume post deploy

### ISSUE THREAD

**Issue by pbajno** [caprover/caprover#522]
I have set up a new app, added additional domain and it works. I've set up a Let's encrypt certificate with your automation. But there is one problem. I would like to map volume /app-data to /usr/share/nginx/html so my static html page is visible, but I dont see option to do it. Only do set up:
Env Variable and Port mappings. How can I map this?

**Comment by githubsaturn** [comment]
When you create an app, you have an option to create an app wity persistent data. 


Only apps with persistent data can have volume mapping.

**Comment by pbajno** [comment]
Can I add this option now?

**Comment by githubsaturn** [comment]
No, it's an option at the creation time.

**Comment by pbajno** [comment]
Can you maybe add this as a feature request for this? To add volume mappings afterwards? Is this possible? I added new website using nginx proxy and cannot even upload my website because the path to nginx/html is not accessible to me.

**Comment by githubsaturn** [comment]
No, this was a conscious decision to make it available at creation time only. There are fundamental differences between apps with persistence and regular apps, in terms of replication, placement and etc. 


Removing the old app, and creating a new one isn't a complex process and should take less than a minute.

**Comment by pbajno** [comment]
Okay that explains. I just wanted to solve it without creating new request to Let's Encrypt for SSL cerificate. But I guess I can copy existing one.
