### ISSUE TITLE
Domain verification fails, but passes at https://mxtoolbox.com/domain/streamcloud.us/

### ISSUE THREAD

**Issue by streamlifetv** [caprover/caprover#524]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Cannot verify that streamcloud.us points to your server IP.

If applicable, content of `captain-definition` file:

Any work around?

Steps to reproduce the problem:

Answers to the following questions if applicable:
- Your OS and version?
- RAM?
UBUNTU 18.04 32GIG RAM

**Comment by githubsaturn** [comment]
Try somerandom.you.domain.com and if you see the CapRover page, your dns is okay. But it might have been cached by your machine. Wait 24hr and retry. If it doesn't work, try this last resort:


https://github.com/caprover/caprover/issues/413

**Comment by streamlifetv** [comment]
I tried to do the skipVerifyingDomains to true, here: root@server1:/captain/data# dir
config-captain.json config-override.json <<<< Here is how I set that up:

config-override.json

{
"defaultMaxLogSize":"128m"
}

{
"skipVerifyingDomains":"true"
}

I then restarted caprover, however same problem could not verify. I tried to go to the port here:

http://192.99.0.76:3000/ java has to be enabled - I have multiple servers hoping to get them all operating on caprover. DNS issues seem to kill progress. Any help would be much appreciated!

**Comment by githubsaturn** [comment]
What's the domain address that you're trying to connect?

Assuming you've pointed *. something.domain.com to 192.99.0.76, open your browser and type:

Captain.something.domain.com


What do you see on the browser?

**Comment by streamlifetv** [comment]
http://captain.server1.streamcloud.us/

Does not resolve.  However when I use port I get this: You need to enable JavaScript to run this app.  I get this: You need to enable JavaScript to run this app.   Going to look into this but verification fails, would be nice if you had a CLOUDFLARE api that way we could change ip/domain immediately no wait.

**Comment by streamlifetv** [comment]
I thought I had installed JAVA...but had to reinstall: java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

I MIGHT START OVER...reinstall server.  I would like to not have to wait for domain verification, wish we had a cloudflare api installed so can set up domains and have the api work directly with cloudflare.  DOMAINS, PORTS, and ROUTING ISSUES if we could get all that instantly then wow that would be powerful for being able to resolve conflicts with in one management package!  I need the powerful open source programs that we can load into containers.  JITSI, ANT MEDIA, OPENVCX, OPENFIRE, also a remote server access to some of these snap ubuntu open source programs.  I need to launch tv stations/channels and looking at ace streamer which is P2P bittorrent for eventually setting up decentralized nodes so we can get around high cost delivery solutions.  Thanks!  John

**Comment by githubsaturn** [comment]
You need to read the Getting Started section from the docs: 
https://caprover.com/docs/get-started.html#step-2-connect-root-domain


You have not setup your domain correctly:
https://mxtoolbox.com/SuperTool.aspx?action=a%3acaptain.server1.streamcloud.us&run=toolpage

**Comment by streamlifetv** [comment]
I reinstalled server:  Setup CapRover machine on your server...

? have you already started CapRover container on your server? Yes
? IP address of your server: 192.99.0.76
? CapRover server root domain: broadcast.streamlife.live

Cannot verify that broadcast.streamlife.live points to your server IP.
Are you sure that you setup your DNS to point "*.broadcast.streamlife.live" to 192.99.0.76?
Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.

Error Code: 1107  Message: Verification Failed.

root@broadcast:/captain# 
I was not able to get direct connect from Godaddy that even shows up any A record over 24 hours later!  So, I have to go with cloudflare I can put captain in front of the this is what I get:
https://dnschecker.org/#A/captain.broadcast.streamlife.live

Will TRY again:  NO GO....
Setup CapRover machine on your server...

? have you already started CapRover container on your server? Yes
? IP address of your server: 192.99.0.76
? CapRover server root domain: captain.broadcast.streamlife.live

Cannot verify that captain.broadcast.streamlife.live points to your server IP.
Are you sure that you setup your DNS to point "*.captain.broadcast.streamlife.live" to 192.99.0.76?
Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.

Error Code: 1107  Message: Verification Failed.

root@broadcast:/captain# hostname -f
broadcast.streamlife.live
root@broadcast:/captain# 

HOW CAN I JUST BYPASS THIS DOMAIN NAME AND USE MY IP ADDRESS:3000?  

We need the integration of CLOUDFLARE api then it is quick and we can build out network, thanks, John

**Comment by streamlifetv** [comment]
http://192.99.0.76:3000/     >>>>You need to enable JavaScript to run this app.

**Comment by streamlifetv** [comment]
Third time I have reinstalled server....I added the domains to HOSTS file, here they are with CAPROVER installed but domain fails but as you can see they are working:

https://broadcast.streamlife.live/     <<<works as in we see the blue screen from CAPROVER
https://captain.broadcast.streamlife.live/ <<<<<<does not work
https://streamlife.live/    <<<<<<works blue CAPROVER screen

HOSTS FILE:
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost   ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
192.99.0.76     broadcast.streamlife.live       broadcast
192.99.0.76     captain.broadcast.streamlife.live
192.99.0.76     streamlife.live




SO HOW CAN I GET THIS TO ACCEPT MY DOMAIN, OR WHERE DO I PUT DOMAIN IN THE CODE????  This is taking way to long and your software is very important for my project.  What we need is an input screen for domain name, and the port should just work once installed so we can get started.  But, definitely we need CLOUDFLARE API soon!  Thanks, John

**Comment by streamlifetv** [comment]
nslookup broadcast.streamlife.live
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	broadcast.streamlife.live
Address: 104.24.118.233
Name:	broadcast.streamlife.live
Address: 104.24.119.233
Name:	broadcast.streamlife.live
Address: 2606:4700:30::6818:76e9
Name:	broadcast.streamlife.live
Address: 2606:4700:30::6818:77e9

**Comment by githubsaturn** [comment]
Reach out to GoDaddy support to get your DNS set up properly. The issue that you're facing is unrelated to CapRover. You need to setup a wild card entry in your DNS - such that:

`<ANYTHING>.streamlife.live` will show your the blue CapRover page.

ONLY AFTER you have set up your DNS correctly, you can use CapRover.

**Comment by streamlifetv** [comment]
Ok, I will try that!  I noticed that cloudflare is showing up everywhere now the third day and godaddy is dead,,not sure why...but I will look into it.  Thanks!  Your program is cutting edge in thinking, I just wish we had a cloudflare api which is what I am looking into now.  Because it would be instant, not wait, I can change a server very quickly if hacked.  That is what you want!

**Comment by streamlifetv** [comment]
Ok, I will try that!  I noticed that cloudflare is showing up everywhere now the third day and godaddy is dead,,not sure why...but I will look into it.  Thanks!  Your program is cutting edge in thinking, I just wish we had a cloudflare api which is what I am looking into now.  Because it would be instant, not wait, I can change a server very quickly if hacked.  That is what you want!  check this out: https://github.com/streamlifetv/acme.sh

**Comment by streamlifetv** [comment]
I ment to show you this:  https://github.com/Neilpang/acme.sh/wiki/dnsapi  <<<<CLOUDFLARE API TOKEN

**Comment by githubsaturn** [comment]
Yea - we might add something like that in the future.

**Comment by githubsaturn** [comment]
In fact, other people have made their own customized deployers in the past. The API is open source, so feel free to develop your own CapRover deployment system.
