### ISSUE TITLE
[Deployment Issue] Use ends to distinguish between staging and production server

### ISSUE THREAD

**Issue by funkhauscreative** [caprover/caprover#525]
Hi there,

we use two different cap rover servers, one for staging and the other one for production. What we want to deploy is a Django App that uses different settings depending on the environment.

One of our build steps is the following Docker RUN command:

*RUN cd /usr/src/app && python3 manage.py migrate --no-input*

The problem is that we set our environment though a environment variable in caprover. But these envs are ignored until the build has finished.

So we end up with build failed, because in the above example the server can't find the different database configuration that the production staging/production server has.

Whats the best solution to automate this? Right now I can't think of a way to deploy the same app to different environments and distinguish them already in the build phase.

Feature request: We could probably erase the line of code from our captain definition file. But therefore it would be super handy to have a new caprover cli command that opens a terminal for a specific caprover app. Like:

caprover terminal --server captain-01 --app myapp

Thanks in advance!

**Comment by iamrommel** [comment]
I use two branches
beta branch --> beta caprover serve
master branche --> prod caprover

On caprover deployment,  i used **Method 3: Deploy from Github/Bitbucket/Gitlab**
and set the branches for each server

![image](https://user-images.githubusercontent.com/177265/67258248-3914ad80-f4c2-11e9-8a14-0322f1aa9b90.png)

**Comment by githubsaturn** [comment]
On top of what @iamrommel  is suggesting, if you need to use two different Dockerfiles for production and staging, you can customize your `captain-definition` relative path. Set your staging path to `captain-definition.staging` and your production app to `captain-definition.production`. This will allow you to have different commands for production and staging.

As for your second question regarding something like "caprover terminal --server captain-01 --app myapp", we cannot do this cleanly. CapRover API is on HTTP, and getting an output of command via HTTP isn't very smooth. However, you can simply do the following:

```
ssh -t root@123.123.123.123 'CONTAINER_ID=$(docker inspect --format {{.Status.ContainerStatus.ContainerID}} $(docker service ps -q srv-captain--myappname -f "desired-state=running")) && echo $CONTAINER_ID && docker exec -it $CONTAINER_ID date --help'
```
The command is a bit long, but you should only need to change these:
- `123.123.123.123` to your server's IP address
- `myappname` to your app name. Keep `srv-captain--` prefix as is.
- Change `date --help` to `cd /usr/src/app && python3 manage.py migrate --no-input` or anything else.
