### ISSUE TITLE
[Deployment Issue] Elasticsearch

### ISSUE THREAD

**Issue by Abfelbaum** [caprover/caprover#526]
What is the problem?
I want to deploy Elasticsearch (6.7.1) with the fusionauth one click app but it fails starting with the following error message:
```
2019-10-23T20:29:50.481534818Z [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

If applicable, content of `captain-definition` file:
I used the fusionauth one click app, but the error can be reproduced with the elasticsearch one click app too

Steps to reproduce the problem:
1. Create new one click app and select elasticsearch
2. Select Version, I tried it with 6.3.2, 6.7.1 and 7.4.1
3. Elasticsearch won't start

Answers to the following questions if applicable:
- Your OS and version?
Debian 10, docker 19.03.3
- RAM?
16GB

**Comment by githubsaturn** [comment]
This is an elastic search specific issue. I believe you can modify the memory like this:

https://github.com/caprover/one-click-apps/blob/340f984c8fe884c896bb3f1dd8c607843e8cdabc/public/v2/apps/elasticsearch.json#L27
