### ISSUE TITLE
Environment variables with dash on the name does not work on nodejs 10+

### ISSUE THREAD

**Issue by iamrommel** [caprover/caprover#528]
--------------------------------------------------------------------------
What is the problem?
I tried to deployed an app (jsReport) using nodejs 8.+and configure the environment variables from the Caprover UI. It happens that jsReport named it's environment variables like this `extensions_mongodb-store_uri`, as you can see the `mongo-store` has dash between them. I tried to console.log(process.env) and it's perfect, it appears as "extensions_mongodb-store_uri" on the logs.

Now because I want the latest and the fastest, i decided to use Node 12, the jsReport works fine on my development machine, the environment variables with dash logs on my console as i expected. But when i deployed it to CapRover server with the captain definition as shown on figure 2, the environment variables `extensions_mongodb-store_uri` is missing! When i downgraded to nodejs 10 still it does not work. 

So it works on my dev (take note i just run here plain nodejs environment and NOT CapRover on local) but not on CapRover server.

If applicable, content of `captain-definition` file:
Figure 1: This is the working captain definition file because i was using node 8+ here
```
{
  "schemaVersion" :2 ,
  "dockerfileLines" :[
                            "FROM node:8.11.1",
                         "RUN mkdir -p /usr/src/app",
                         "WORKDIR /usr/src/app",
                         "COPY package.json package-lock.json* ./",
                        "RUN npm cache clean --force && npm install",
                         "COPY ./ /usr/src/app",
                         "EXPOSE 80",
                         "CMD [ \"npm\", \"start\" ]"
                    ]
 }

```

Figure 2: Captain defnition, i just changed teh FROM part to latest nodejs
```
{
  "schemaVersion" :2 ,
  "dockerfileLines" :[
                          "FROM node:12.13.0",
                         "RUN mkdir -p /usr/src/app",
                         "WORKDIR /usr/src/app",
                         "COPY package.json package-lock.json* ./",
                         "RUN npm cache clean --force && npm install",
                         "COPY ./ /usr/src/app",
                         "EXPOSE 80",
                         "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

Steps to reproduce the problem:
Just create a simple node js and with environment variables with dash on the name, and tried to deployed to different nodejs environment (nodejs 8 vs nodejs 10 & 12).  Display it thru console.log(process.env) and you should see if the env variables with dash will show or not.

**Comment by githubsaturn** [comment]
When you use node 10+, does your environmental variables show up in docker services correctly? Run this:

```
docker service inspect srv-captain-appname --pretty
```

**Comment by iamrommel** [comment]
Yes it is on the environment variables
Here is the snippet for the inspect using node10+

```
ContainerSpec:             
Image:         img-captain-payroll-report-01:2                                                                 
Env:           extensions_mongodb-store_uri=mongodb://something.com/payroll?authSource=admin extensions_mongodb-store_prefix=jsreport_ extensions_authentication_admin_username=admin 
```

**Comment by githubsaturn** [comment]
This is a docker/nodejs bug then. Unrelated to CapRover. Please file a bug report on docker repository. And please link this issue to it.
