### ISSUE TITLE
Strange behaviour causing containers to run on older, deleted images

### ISSUE THREAD

**Issue by rymdluo** [caprover/caprover#530]
## Problem:
I noticed strange behaviour that is causing my containers to use older versions of images that.. should not happen. Basically, my containers started to use old images (that ought to have been deleted already) instead of the latest deployed image.

The behaviour creates two issues.
1. Rebuilding sometimes works, but after a while the containers (without any interference) will revert to the same of using old images. 
2. Rebuilding pushes the old images immediately

## Setup:
5 nodes (3 assigned manager, 2 worker)

## Notes:
1. I use caprover for development of ML models which are computationally and memory intensive, and I regularly build new images for testing. I use the following commands to clean out the registry, old containers and images.
```
rm -rf /captain/data/registry/docker/registry/v2
docker service update captain-registry --force
docker container prune --force
docker image prune --all --force
```

2. I further note that at the time I was reviewing this, the "original node" used to setup caprover is no longer the elected Leader. I gather that at some point the original node either went down or was too busy. This could have been a factor to the current strange behaviour.

At this time, the problem continues to persist even when I have gone through all my nodes to wipe unused images. The elected leader is presently still not on the original node.

3. Swap space was allocated to all nodes, a point to consider if resource jam.

## Logs:
I'm not sure there are any relevant logs for this, but this is an example of building a new image, which resulted in the same behaviour.
```
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:33.931 am    Ensure service inited and Updated for: ml1-nn
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:33.933 am    Check if service is running: srv-captain--ml1-nn
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:33.992 am    Service is already running: srv-captain--ml1-nn
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:33.992 am    Updating service srv-captain--ml1-nn with image registry.removed.com:996/captain/img-captain-ml1-nn:27
captain-captain.1.w2pqfamsppaa@    | GET /api/v2/user/apps/appData/ml1-nn 200 1.606 ms - 7583
captain-captain.1.w2pqfamsppaa@    | GET /api/v2/user/apps/appDefinitions 200 2.569 ms - 32866
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:36.220 am    Updating Load Balancer
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:36.221 am    Locking NGINX configuration reloading...
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:36.253 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:36.253 am    sendReloadSignal...
captain-captain.1.w2pqfamsppaa@    | November 6th 2019, 4:58:36.336 am    Kill HUP Container: 21a9c8c47529df2a38e2d87f1cbcbecaa9d008ef35696112cb9bcebefc654d7a
```

## Musings:
At this time, I am likely going to do a clean slate and see if the issue persists. Caprover (or the underlying docker) was behaving very well up to the point where I think I was pushing my node resources to the limit via dask though it is only a suspicion.

**Comment by githubsaturn** [comment]
How do you know it's an old image? Are you looking at `image-name:1234` where `1234` is the version name?

**Comment by rymdluo** [comment]
Thanks for responding, I know it's an old image because the debug log produces code that have been removed or commented out for days.

To update, I have not done a clean slate and instead tried to look around further and it seems (not 100% certain) that some old replicas were not deleted by docker swarm. When I removed the stale replicas it seemed to go back to working order, though it happened shortly after again- with docker showing 5/4 replicas in the network.

My response to the above was to updating services to `--replicas-max-per-node` and set `limit-cpu` to limit the cpu resources to these containers which are computationally intensive. This seems to have resulted in stability so far. At this point I suspect this has little to do with CapRover, and more of resource optimization/containers hogging resources preventing docker swarm to do its job.

**Comment by githubsaturn** [comment]
Yes - the chance of this being related to CapRover is pretty slim. Still, I am interested in finding out what's causing this. There is an automatic roll-back behavior defined in Docker swarm. However, it only kicks in if your newly deployed image fails to startup properly or keeps crashing right after starting up.

**Comment by rymdluo** [comment]
So far, it seems like the strange behaviour is persisting- though I have now seen that it might be because Docker swarm is not able to shutdown all the old replicas, thus creating an excess of 5/4 e.g. replicas. Shutting down all instances by setting to 0 and then enabling again after rebuilding an image seems to work best. I've also noticed that the behaviour isn't only on apps with >1 replicas/instances. So far it looks like this is only on apps without persistent directories, I've not tested this on persistent apps.

I would also note that I have the habit of stacking up multiple builds while they are building since the feature was added to CapRover, it is possible that it could be related. I do recall also changing (or attempting to change) number of app instances while stacking builds.

@githubsaturn Is there a quick way to effect a reinstall, or restart all docker services without going through the backup and restoration process?

**Comment by githubsaturn** [comment]
Depends what you mean by uninstalling and reinstalling. You can simply restart all services via
```
docker service update --force $(docker service ls -q)
```

PS: The excess replica is expected. CapRover uses "startFirst" mode for updating apps without persistent directories. On the other hand for apps with persistent directories, CapRover uses stopFirst mode to make sure that data doesn't get corrupted when two instances tries to write on the same file.

This should not be related to queued builds. The queue mechanics is simply being done via CapRover without Docker intervention. 


Just keep in mind that the image update process is not a quick process. Docker swarm might take a minute or two to stabilize all the instances on all nodes.

**Comment by rymdluo** [comment]
I think I may have found the quirk. One of my nodes seems to be failing to shutdown, where the command to shutdown the container is rejected. The reason being "missing registry" or something like that.

This is based on a fresh install with only one manager node. The problematic node is a worker node and it always seems to happen on the same node.
