### ISSUE TITLE
caprover default nginx config carves out too much for letsencrypt under .well-known

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#532]
What is the problem?

My app's healthcheck is at `/.well-known/healthcheck.json`.

AFAIK, only `/.well-known/acme-challenge/` is needed for LE certs.  The location stanza in the vhost config is too broad. 

Steps to reproduce the problem:

Try to serve app content under `/.well-known/`

**Comment by githubsaturn** [comment]
Yes, we should move to try_files

As a workaround, you can manually change the config to use try_files: https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#trying-several-options

**Comment by sneak** [comment]
This also makes using Mastodon fail, as it needs `/.well-known/webfinger` and `/.well-known/host-meta` to work.  Currently mucking around with try_files to work around it.

**Comment by githubsaturn** [comment]
Reduced the scope of `.well-known` in the config: https://github.com/caprover/caprover/commit/33a195a941d87ef143c4c69d39d2edf13b8ee6c5
