### ISSUE TITLE
Changing Public IP Breaks CapRover

### ISSUE THREAD

**Issue by cshivers** [caprover/caprover#534]
I'm sure there is a work-around for this, but I'm still investigating. However, if your public IP changes, then you can no longer access the WebUI for CapRover. I assume this has to do w/ the environment variable that gets passed into the CapRover docker image, however I'm not savvy with docker enough (at the moment) to figure out how to change this. I've tried to re-setup using the CLI but it of course thinks that there is already an instance running.

It'd be nice if there was a CLI option or even a web option that allowed changing the IP.

To reproduce using DigitalOcean, configure CapRover using a public IP. Then, assign it a FloatingIP and point your DNS entries to the new IP.

Also, I'll note that I've never been able to access via IP:3000. Thus, I can't even use that in the interim.

**Comment by githubsaturn** [comment]
CapRover doesn't store the public IP. My guess is that by changing your IP to a floating IP, the network interface changes resulting in docker network to break.

Try rebooting the server to see if it fixes the issue.

If not, get CapRover logs upon startup and copy them here for more investigation.

**Comment by cshivers** [comment]
Ah, so when the CLI asks for the IP initially, that's to create the network? I'm sure that's it. Thanks for the quick response. I love the app so far.

**Comment by githubsaturn** [comment]
When the CLI asks for the IP, it uses the IP to connect to the server and make it ready for the setup process.
