### ISSUE TITLE
rewriting history seems to make caprover fail to fetch new code on build via webhook

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#535]
If i `git commit --amend` and `git push origin master --force` (to github), caprover builds with my previous version's code, not the newly force-pushed code.

I would expect caprover to re-clone on any webhook, to start fresh.

**Comment by githubsaturn** [comment]
CapRover does clone the repo: https://github.com/caprover/caprover/blob/533ea28a1ecc0a561da811277b01f2702d685514/src/utils/GitHelper.ts#L68

**Comment by sneak** [comment]
user error, sorry for the noise.  (was using `--amend` and not `--amend -a`, oops)
