### ISSUE TITLE
Ability to "turn off" app

### ISSUE THREAD

**Issue by cshivers** [caprover/caprover#536]
Is there a 'clean' way to disable an app temporarily from the UI? For testing, I've built an "under construction" image that I use to give the facade that it's under maintenance. Then, after make some changes I simply re-deploy the main image again.

It would be nice to have this ability, especially if using it in a development region when restarting the failing image isn't desirable.

Thanks! Great application.

**Comment by githubsaturn** [comment]
Two methods:

Pause the app by changing the instance count to zero. 

Deploy a placeholder static page app. See php app in the sample directory as an example.
