### ISSUE TITLE
Can't SSH deploy with Gitlab

### ISSUE THREAD

**Issue by cattoshi** [caprover/caprover#538]
**What is the problem?**
Can't deploy app with gitlab and SSH keys. I can't use username and password on Caprover because I have 2FA.

**Steps to reproduce the problem:**
I have a private Gitlab repo. I have generated ssh keys with the command:

`ssh-keygen -t ed25519 -C "key name"`

as adviced by https://gitlab.com/help/ssh/README#generating-a-new-ssh-key-pair. I added a blank password to the generated key (just hit enter).

I then added the .pub content to Gitlab's > _User Settings > SSH Keys_, and the corresponding private key content pasted to Caprover's > _Apps > app_name > Deployment tab > _Method 3: SSH key__ . On the 'Repository' field I added 'https://gitlab.com/myusername/deploy-test', and on 'Branch' the name of my release branch 'release'.

Clicked the blue button 'Save & Update' and pasted the generated webhook URL at Gitlab's _repo_name > Settings > Integrations > URL._ Have checked 'Push Events', and in the input text box below I entered the name of my release branch 'release'. I also checked 'Enable SSL verification'. Those are the only checked things. Hit 'Add webhook' and successfully test with 200 response.

Go back to Caprover > Deploy tab in the app, hit the grey button 'Force Deploy'. The logs show the deploy failed. The icon in the deploy list is gray. The logs are:

```
------------------------- Fri Nov 08 2019 20:38:54 GMT+0000 (Coordinated Universal Time)
Build started for deploy-test
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/deploy-test/17/source_files'...
Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 
```

Answers to the following questions where applicable:
- **Your OS and version?** Ubuntu 18.04.3 LTS
- **RAM?** 1GB

I already have SSH access for other private repos and I can log in correctly manually.

**Comment by githubsaturn** [comment]
Most likely there is an issue with the keys you generated. This issue has been brought up in the past and turned out to be a problem with the keys. See this for example: https://github.com/caprover/caprover/issues/464


Use this online tool to generate the keys for the test purpose: https://8gwifi.org/sshfunctions.jsp
Use: RSA / 1024

Also make sure that the private key that you copy to the CapRover dashboard has a correct formatting, it should start with `-----BEGIN RSA PRIVATE KEY-----`

**Comment by cattoshi** [comment]
I see, but on issue #464 at the end it is not specified what key types worked with Caprover.

I fixed this as follows, first I used the adviced method to generate an ssh key pair here: https://gitlab.com/help/ssh/README#generating-a-new-ssh-key-pair, but the catch is the key must be in the legacy PEM format:

`ssh-keygen -t rsa -b 4096 -m pem -C "my new key"`

see documentation for this here: https://man.openbsd.org/ssh-keygen#m

with that key format everything works fine.

**Comment by cattoshi** [comment]
I also changed the way I added the key, I now use the _repo page > Settings > Repository > Deploy Keys_.

**Comment by cattoshi** [comment]
I also wouldn't touch online keys/crypto generators because I wouldn't trust them to be secure.
