### ISSUE TITLE
Can't get webhook to work

### ISSUE THREAD

**Issue by TobiasWehrum** [caprover/caprover#539]
Hello,

I'm using CapRover 1.5.2 and I'm trying to get a bitbucket.org repository to build on push via webhook.

On push, no build is triggered and Bitbucket reports the following answer to the webhook:
```
{
  "status": 1102,
  "description": "Empty namespace",
  "data": {}
}
```

"Force build" works, so I assume the SSH credentials and access to the repository works at least.

I've already got that working once before a few months ago with a different CapRover installation and the same bitbucket.org repository and I'm not sure what I'm doing wrong this time.

**Comment by githubsaturn** [comment]
Are you sure you're using the correct webhook URL. There is a namespace query parameter in the webhook for namespace:

Your webhook should look like this:

```
https://captain.something.domain.com/api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=abcdabcdabcd......
```

**Comment by TobiasWehrum** [comment]
Yes. Here is a slightly censored version of the the webhook I'm using:

`https://captain.[mysubdomain].[domain].de/api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuVmVyc2lvbiI6ImI1ODE3ZjhjLWViZDctNGQxNS05ZjkyLTUzODUwODQ3MDNkYy[etc pp]`

By the way, what should happen when I just open the URL in a browser? As far as I can see the namespace is even inside the query parameter, yet I still get the "empty namespace" response I showed in my last post.

**Comment by githubsaturn** [comment]
>  what should happen when I just open the URL in a browser? 
You will see a Not Found error. The URL only responds to POST request.

Your URL formatting seems ok. And because the "Force Build" button works, we can tell both the URL and the access keys are working fine. When you click on Force Build button, the browser simply sends a POST request to the webhook URL - similar to the request that bitbucket is supposed to send when it triggers the push.

The fact that you're experiencing an error is bizarre - if in fact you're using the same URL in your bitbucket webhook URL config. Can you try manually firing the webhook request?
```
curl -X POST "https://your-webhook-URL"

# Make sure you use the double quotes, ", on both sides of your URL
```
Does this work?

**Comment by TobiasWehrum** [comment]
> You will see a Not Found error. The URL only responds to POST request.

That is not what happens for me. I also get the same result in the browser:

```
{
    "status": 1102,
    "description": "Empty namespace",
    "data": {}
}
```

I don't have curl installed, but I used Postman to send a POST request. Exactly the same result. (And the same result for a GET request, btw.)

There shouldn't be a way for me to mistype the URL either. I get it by clicking into the webhook URL field on the CapRover panel which makes CapRover automatically copy it to the clipboard.

**Comment by githubsaturn** [comment]
The only way that you can get into this situation is that somehow your token is broken. Run this on your server:
```
docker service logs captain-captain --follow --since 1m
```

While the SSH window is open, copy and paste the URL in the browser. Do you see any of these in the logs?
```
JsonWebTokenError: invalid signature
```
or 
```
JsonWebTokenError: Error: Token corrupted
```

**Comment by TobiasWehrum** [comment]
No, I don't get that, but I get this:

```
November 10th 2019, 10:25:44.771 pm    Error: App ([old-app-name]) could not be found. Make sure that you have created the app.
Error: App ([old-app-name]) could not be found. Make sure that you have created the app.
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
    at /usr/src/app/built/datastore/AppsDataStore.js:208:38
November 10th 2019, 10:25:44.774 pm    Error: Empty namespace
Error: Empty namespace
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
    at Function.getAuthenticator (/usr/src/app/built/user/Authenticator.js:162:34)
    at /usr/src/app/built/injection/Injector.js:41:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/built/injection/Injector.js:114:13
```

[old-app-name] is the name that I created the app with. I have since changed it to another name. Maybe that helps?

**Comment by TobiasWehrum** [comment]
Yeah, changing it back to the old name works.

I think I also used "Force Build" when it was still the old name.

**Comment by githubsaturn** [comment]
There was a PR to generate new webhook after app rename: https://github.com/caprover/caprover/pull/499

I guess there must be a bug in the PR - please rename to the old name and check if the webhook works. Upon renaming the webhook URL might change, make sure to use the newly generated one.

**Comment by githubsaturn** [comment]
Ah... My bad -- the PR that linked above hasn't been released yet. It'll be released in November. You can use the edge version for now: 
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version

Once the new version is released you can revert back to the stable build.
