### ISSUE TITLE
[Question] Where do I set the timezone?

### ISSUE THREAD

**Issue by Tuginho** [caprover/caprover#540]
I can't find a solution yet to set the timezone inside a docker container over caprover. 
I just know a solution with build-args but didn't find something about in documentation.

Container date: Tue Nov 12 12:32:56 UTC 2019
Host Date: Tue Nov 12 13:32:56 CET 2019

**Comment by githubsaturn** [comment]
You can use a customized dockerfile. See this for details on what lines need to be added to your Dockerfile:

https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by synetalsolutions** [comment]
I have deployed  my custom node.js code and I want to run cron job inside how can i change container time.
When I run 

docker exec 1ac931afd9bf date

Tue Nov 26 08:43:23 UTC 2019

**Comment by githubsaturn** [comment]
@synetalsolutions  did you look at the link I posted above?

**Comment by synetalsolutions** [comment]
Yes i did it is prebuild images like ubuntu and other os and i am running
node.js application it doesn't have /etc/timezone or any other related
files.

**Comment by githubsaturn** [comment]
You need to add the related lines to your Dockerfile.

**Comment by synetalsolutions** [comment]
New YML lines when we build the code from bitbucket?

**Comment by Tuginho** [comment]
Here is my Dockerfile:

```
# Base image
FROM node:12.10.0

# Creating a directory inside the base image and defining as the base directory
WORKDIR /app

# Copying the files of the root directory into the base directory
ADD . /app

# Set TimeZone correctly
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Installing the project dependencies
RUN npm install

# Starting the pm2 process and keeping the docker container alive
CMD npm start

# Exposing the RestAPI port
EXPOSE 4320

```

**Comment by synetalsolutions** [comment]
> Here is my Dockerfile:
> 
> ```
> # Base image
> FROM node:12.10.0
> 
> # Creating a directory inside the base image and defining as the base directory
> WORKDIR /app
> 
> # Copying the files of the root directory into the base directory
> ADD . /app
> 
> # Set TimeZone correctly
> ENV TZ=Europe/Berlin
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> 
> 
> # Installing the project dependencies
> RUN npm install
> 
> # Starting the pm2 process and keeping the docker container alive
> CMD npm start
> 
> # Exposing the RestAPI port
> EXPOSE 4320
> ```

I still have little confusion where  I need to add  this config do i need to create a new container or i need to add this  code inside my app code.?

**Comment by githubsaturn** [comment]
Delete your `captain-definition` file and create a file called `Dockerfile` - make sure the capitalization and the spelling is correct.

The content of Dockerfile should be this:

```
FROM node:10-alpine
ENC NODE_ENV production
ENV PORT 80

# Set TimeZone correctly
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
# Bundle app source
COPY . /usr/src/app
EXPOSE 80
CMD [ "npm", "start" ] 
```

**Comment by synetalsolutions** [comment]
> Delete your `captain-definition` file and create a file called `Dockerfile` - make sure the capitalization and the spelling is correct.
> 
> The content of Dockerfile should be this:
> 
> ```
> FROM node:10-alpine
> ENC NODE_ENV production
> ENV PORT 80
> 
> # Set TimeZone correctly
> ENV TZ=Europe/Berlin
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> 
> 
> # Create app directory
> RUN mkdir -p /usr/src/app
> WORKDIR /usr/src/app
> # Install app dependencies
> COPY package.json /usr/src/app/
> RUN npm install
> # Bundle app source
> COPY . /usr/src/app
> EXPOSE 80
> CMD [ "npm", "start" ] 
> ```

Ok that worked but there is two issue 
1. Cannot parse {"stream":"Step 1/12 : FROM node:10-alpine"}
{"stream":"\n"}

2.Need to replace it **ENC** NODE_ENV production with **ENV** NODE_ENV production

**Comment by githubsaturn** [comment]
Remove -alpine postfix and retry

**Comment by dedfft** [comment]
I have added 
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
But still get the difference of like 5 hours. And if i remove these 2 lines, same time(
Any idea?
