### ISSUE TITLE
Clustering Databases

### ISSUE THREAD

**Issue by sicutdeux** [caprover/caprover#543]
Hi, sorry i didn't know where to put the actual question, but here it goes, i'm interested on using captover for a project, but there is something that baffles me, i have search but couldn't find an answer anywhere.

It's about MongoDB, if i install a cluster with 3 vm's, and my project has 3 instances, i need MongoDB, there is a way to make a cluster on mongodb as well inside the cluster, or how do i do that for CapRover, my intent is having HA not only for the php application but for the mongodb as well? does caprover does the replica set for me? or just use an external mongodb cluster?

Thanks.

**Comment by githubsaturn** [comment]
CapRover creates individual instances of MongoDB for you. But configuration changes and turning the 3 individual MongoDB instances into a cluster needs to be done by you.
