### ISSUE TITLE
[Deployment Issue] Pretty urls server side configuration for an angularjs app

### ISSUE THREAD

**Issue by unexpectedShr3k** [caprover/caprover#544]
**What is the problem?**
I need to configure nginx for my angularjs app to show pretty urls (without the **#!** part, also called [html5mode](https://docs.angularjs.org/api/ng/provider/$locationProvider#html5Mode)). A server side configuration is needed in nginx files for that specific app. 

How can I define app specific nginx configurations?

Specifically, I need to add something like this for one specific app:
```

server {
    server_name my-app;
    
    index index.html;

    root /path/to/app;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
```
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

Should I just copypaste my nginx `upstream {}` and `server {}` blocks into  `/etc/nginx/conf.d/captain-root.conf `?

**Comment by githubsaturn** [comment]
You can use this captain definition file: https://caprover.com/docs/recipe-deploy-create-react-app.html#create-captain-definition


It'll have a baked in config

**Comment by unexpectedShr3k** [comment]
@githubsaturn thanks! how can I use custom service configuration like secrets, networks, constraints? should I use captain-definition file or one click app templates?

my idea is I want custom secrets, constraints etc and at the same time ability to automatically push from remote repository with webhooks, but one click apps require an existing image for the template, and captain-definition doesn't allow specifying service configuration, afaik.

So should I try to build locally the image and push to my caprover self hosted remotely, and then use a one click template, or is there other way around?
