### ISSUE TITLE
Force HTTPS on custom domain gives too many redirects

### ISSUE THREAD

**Issue by MarcelWeidum** [caprover/caprover#546]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
If I force HTTPS on a custom domain it gives in browser error: ERR_TOO_MANY_REDIRECTS.

If applicable, content of `captain-definition` file:
```
{
    "schemaVersion" :2 ,
    "templateId" :"php/7.1.10"
}
```

Steps to reproduce the problem:
Connect custom domain. Enable HTTPS. Than select 'Force HTTPS'.

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16.04
- RAM? 8gb

**Comment by MarcelWeidum** [comment]
It had to do with cloudflare. Closing.

**Comment by ravikiranp123** [comment]
Hey! How did you fix this issue? Disable proxy?

**Comment by MarcelWeidum** [comment]
@ravikiranp123 disable https and force redirect on cloudflare, or on caprover. You can't have SSL on both.

**Comment by innneang** [comment]
You can have both. Just select Full(Strict) mode in cloudflare. it will use Let's encrypt between cloudflare and your server , and use cloudflare certificate between cloudflare and user.

**Comment by manuman94** [comment]
For me I was getting TOO MANY REDIRECTS error using Wordpress and forcing HTTPS.

I found the solution here: https://wordpress.stackexchange.com/a/196220/111217

I hope this helps someone in my situation.
