### ISSUE TITLE
How do I add env vars accessible by process.env in node apps

### ISSUE THREAD

**Issue by Mylab6** [caprover/caprover#547]
What is the problem?
I can not access app variables in process.env , after defining them as app config values 

If applicable, content of `captain-definition` file:
{
    "schemaVersion": 2,
    "dockerfileLines": [
        "FROM node:latest",
        "COPY . /app",
        "WORKDIR /app",
           "RUN yarn",
        "CMD yarn serve",
        "EXPOSE 8080"
    ]
}

Steps to reproduce the problem:
Attempt to log process.env.VAR_NAME , in a node app after setting it in the App Config . Notice the var does not log . 

NOTE: I'm not too experienced with docker, let me know if I'm just not doing something right .,

**Comment by githubsaturn** [comment]
In the dashboard, click on the app, under apps config tab, you can add environmental variables.
