### ISSUE TITLE
[Deployment Issue] Previous deploys not turning off

### ISSUE THREAD

**Issue by lzzy12** [caprover/caprover#548]
What is the problem?

I deployed a telegram bot on caprover with the CLI. 
If applicable, content of `captain-definition` file:
```
{
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
}
```

The Dockerfile looks like this:
```
FROM python:3.8-slim-buster

WORKDIR /usr/src/app
RUN chmod 777 /usr/src/app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update
RUN apt-get install -y aria2

CMD ["bash","start.sh"]
```

The first time I deploy it, the bot works flawlessly, however when I try to deploy the bot again with some codes changed, it clashes with the old instance of bot meaning that the previous instance of the bot is still running. I would like to stop the previous instance of the bot first, then only start with the new code.

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 18.04
- RAM? 1-GB

**Comment by lzzy12** [comment]
I also ssh my VM and ran ```sudo docker ps -a``` and it shows 2 containers running of the same app

**Comment by githubsaturn** [comment]
Docker automatically stops the first container. 

Can you run `docker service ls` to see if there's actually a mismatch in number of containers?

**Comment by lzzy12** [comment]
@githubsaturn Here's the output
```ID                  NAME                        MODE                REPLICAS            IMAGE                               PORTS
ui7wq7kau83l        captain-captain             replicated          1/1                 caprover/caprover:1.5.2             *:3000->3000/tcp
sutp0dz8xhef        captain-certbot             replicated          1/1                 caprover/certbot-sleeping:v0.29.1   
mao44i8yfd14        captain-nginx               replicated          1/1                 nginx:1                             
ym7p10q3zt33        srv-captain--mirrorbot      replicated          1/1                 img-captain-mirrorbot:13            
zkpg087oujqh        srv-captain--wp-db          replicated          1/1                 mysql:5.7                           
rrcru9cqrczz        srv-captain--wp-wordpress   replicated          1/1                 wordpress:4.9
```

**Comment by lzzy12** [comment]
I can see only one container here, however it does still clashes with the old instance of the bot as I get error from the telegram API:
```telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running```

**Comment by githubsaturn** [comment]
There's a short period during the update where both instances are running. But other than that, things should be stable. 


If you don't even want that short period of conflict, you can try creating a persistent app. Persistent apps use "StopFirst" strategy for updates.

**Comment by lzzy12** [comment]
@githubsaturn I had checked "have persistent data" during creating the app but never added persistent path. Is it necessary to add it for the "StopFirst" strategy to work?

**Comment by githubsaturn** [comment]
No, it won't be necessary

**Comment by lzzy12** [comment]
@githubsaturn well then I'm afraid, I'm still getting the clash (My app was already a persistent app). Is there something else I can try? 
![Screenshot_20191118-194237_Chrome](https://user-images.githubusercontent.com/26739338/69059486-a5d88480-0a3b-11ea-91ec-1169d15121ed.png)

**Comment by githubsaturn** [comment]
What's the output of `docker ps`?

**Comment by lzzy12** [comment]
Seems, it's not happening anymore. I will let you know by tomorrow. Thanks for support
