### ISSUE TITLE
[Deployment Issue] App deployment using SSH fails

### ISSUE THREAD

**Issue by golyalpha** [caprover/caprover#551]
What is the problem?

Deployment fails with "Host key verification failed"

Steps to reproduce the problem:

Setup deployment from a git repo (I used gitlab) using SSH keys.
Try to deploy.

Answers to the following questions if applicable:
- Your OS and version: Ubuntu 18.04 ARM64
- RAM: 0.96 GB as reported by CapRover

Already tried to work around that with global host keys file, but it didn't work.

Build log:
```
------------------------- Sat Nov 23 2019 09:07:34 GMT+0000 (Coordinated Universal Time)
Build started for dev-website
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/dev-website/8/source_files'...
Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by githubsaturn** [comment]
I've just tested on my instance and it worked with both Gitlab and Github. 

There is a step right before cloning that adds the remote SSH key to the known_host file:
https://github.com/caprover/caprover/blob/22ab9b49a6dbe9446f4340d87095db32a43f05e1/src/utils/GitHelper.ts#L63-L67


Do you enter your repo path correctly? Do you use RSA key? Your repo section should be like this:
![image](https://user-images.githubusercontent.com/10582082/69480294-4a5c1d00-0dd4-11ea-9613-c2ca88d5b2ee.png)

**Comment by golyalpha** [comment]
Well, no, I input it like I was input to URL into the git clone command: `git@gitlab.com:user/project.git`

Inputing the http style URL without the protocol and .git worked.

**Comment by githubsaturn** [comment]
Great!
But I'll Keep this issue open anyways to cleanup the URL if it starts with `git@`

**Comment by golyalpha** [comment]
(and ends with `.git`)
