### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by tonxxd** [caprover/caprover#552]
I am trying to deploy an app that uses opencv4nodejs
When npm starts compiling opencv it goes out of memory. Is there a way I can deploy a prebuilt image (built on my computer) or increase memory limit during deployment?

This is the error
cc1plus: out of memory allocating 67108744 bytes after a total of 9256960 bytes

After this error, deployment ends successfully but I cannot access OpenCV from my node app since it wasn't compiled.

This is my dockerfile

```
FROM m03geek/ffmpeg-opencv-dlib-node:alpine
RUN apk update && apk add -u --no-cache python make g++
WORKDIR /app
COPY ./package.json /app/package.json
RUN npm install -g nodemon  && npm install
COPY ./src /app/src
CMD ["nodemon", "-L", "./src/server.js"]
```

package.json has just opencv4nodejs and some other small packages

Hardware is 2vcpu 2gb ram instance on scaleway

Thanks!

**Comment by githubsaturn** [comment]
You can build the image locally on your own machine, then push it to a Docker registry, like Docker Hub, and then deploy using `--imageName` option

From `caprover deploy --help`
```
Usage: deploy [options]
       deploy -d
       deploy -c file
       deploy [-c file] [-n name] [-a app] [-b branch | -t tarFile | -i image]
       deploy [-c file] -u url [-p password] [-n name] [-a app] [-b branch | -t tarFile | -i image]
  Use --caproverName to use an already logged in CapRover machine
  Use --caproverUrl and --caproverPassword to login on the fly to a CapRover machine, if also --caproverName is present, login credetials are stored locally
  Use one among --branch, --tarFile, --imageName

Deploy your app to a specific CapRover machine. You'll be prompted for missing parameters.

Options:
  -d, --default                   use previously entered values for the current directory, no others options are considered
  -c, --configFile <value>        path of the file where all parameters are defined in JSON or YAML format
                                    see others options to know config file parameters' names
                                    this is mainly for automation purposes, see docs (env: CAPROVER_CONFIG_FILE)
  -u, --caproverUrl <value>       CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain" (env: CAPROVER_URL)
  -h, --host <value>              same as --caproverUrl
  -p, --caproverPassword <value>  CapRover machine password (env: CAPROVER_PASSWORD)
  --pass <value>                  same as --caproverPassword
  -n, --caproverName <value>      CapRover machine name, to load/store credentials (env: CAPROVER_NAME)
  -a, --caproverApp <value>       app name to deploy to (env: CAPROVER_APP)
  --appName <value>               same as --caproverApp
  -b, --branch <value>            git branch name to be deployed, current directory must be git root directory (env: CAPROVER_BRANCH)
  -t, --tarFile <value>           tar file to be uploaded, must contain captain-definition file (env: CAPROVER_TAR_FILE)
  -i, --imageName <value>         image name to be deployed, it should either exist on server, or it has to be public, or on a private repository that CapRover has access to (env: CAPROVER_IMAGE_NAME)
  -h, --help                      output usage information
```

**Comment by DestinTech** [comment]
> You can build the image locally on your own machine, then push it to a Docker registry, like Docker Hub, and then deploy using `--imageName` option
> 
> From `caprover deploy --help`
> 
> ```
> Usage: deploy [options]
>        deploy -d
>        deploy -c file
>        deploy [-c file] [-n name] [-a app] [-b branch | -t tarFile | -i image]
>        deploy [-c file] -u url [-p password] [-n name] [-a app] [-b branch | -t tarFile | -i image]
>   Use --caproverName to use an already logged in CapRover machine
>   Use --caproverUrl and --caproverPassword to login on the fly to a CapRover machine, if also --caproverName is present, login credetials are stored locally
>   Use one among --branch, --tarFile, --imageName
> 
> Deploy your app to a specific CapRover machine. You'll be prompted for missing parameters.
> 
> Options:
>   -d, --default                   use previously entered values for the current directory, no others options are considered
>   -c, --configFile <value>        path of the file where all parameters are defined in JSON or YAML format
>                                     see others options to know config file parameters' names
>                                     this is mainly for automation purposes, see docs (env: CAPROVER_CONFIG_FILE)
>   -u, --caproverUrl <value>       CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain" (env: CAPROVER_URL)
>   -h, --host <value>              same as --caproverUrl
>   -p, --caproverPassword <value>  CapRover machine password (env: CAPROVER_PASSWORD)
>   --pass <value>                  same as --caproverPassword
>   -n, --caproverName <value>      CapRover machine name, to load/store credentials (env: CAPROVER_NAME)
>   -a, --caproverApp <value>       app name to deploy to (env: CAPROVER_APP)
>   --appName <value>               same as --caproverApp
>   -b, --branch <value>            git branch name to be deployed, current directory must be git root directory (env: CAPROVER_BRANCH)
>   -t, --tarFile <value>           tar file to be uploaded, must contain captain-definition file (env: CAPROVER_TAR_FILE)
>   -i, --imageName <value>         image name to be deployed, it should either exist on server, or it has to be public, or on a private repository that CapRover has access to (env: CAPROVER_IMAGE_NAME)
>   -h, --help                      output usage information
> ```

Would there be a way to restrict ram usage of the docker container during the build process, or potentially offload to a single worker node?  I recently came across this issue and it isn't feasible for me to build locally as it causes a delay in my development pipeline. Thank you!

**Comment by githubsaturn** [comment]
You can leverage a CI/CD pipeline: https://caprover.com/docs/ci-cd-integration.html

**Comment by DestinTech** [comment]
> You can leverage a CI/CD pipeline: https://caprover.com/docs/ci-cd-integration.html

I had issues with that implementation method. for example, I was attempting to use gitlab but the 'pull' mirror functionality is a paid service. I'd have to implement a workaround for that as they only have an annual license. I'd pay monthly but that's not an option.

I'm not sure if a fix is feasible but I figured I'd bring it up as it was a blocker in deploying easily. I plan to use this project long-term and I am more than willing to explore and test solutions.

This bug causes OOM errors taking down the service it was hosting, confusing the average developer, at least momentarily, along with slowing down an individual by causing them to find a workaround. 
 
 My current workaround is to use the one-click-apps drone.io and gitea as a CI/CD pipeline and mirror but again, this caused more than a few hours of trouble for me, from trying to understand why my deployment wasn't working, only receiving 'something bad happened' error, finding a report of the bug, trying to figure out a workaround, trying gitlab, being unhappy with the paid feature, etc. 
 
 I don't mean to rant, but I figure this is the best option out there, and I really would love to contribute to fixing this. 
 
 Docker has '-m or --memory=' to limit memory usage, is there a way in the app config for me to use it? Service Update Override potentially?

**Comment by githubsaturn** [comment]
"Service Update Override" is for the service itself, not the build process. Even if you limit CapRover's container, that won't help, because the built context is outside of CapRover.

If you want to add the override functionality, you can add it here: https://github.com/caprover/caprover/blob/master/src/docker/DockerApi.ts#L268-L271

It's not that hard. You'd need to add the overrideOptions as an optional parameter to [configs](https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L17-L49), then read the value and spread it in the options if it exists.

**Comment by DestinTech** [comment]
> "Service Update Override" is for the service itself, not the build process. Even if you limit CapRover's container, that won't help, because the built context is outside of CapRover.

Awesome I'll take a look at this and submit a PR! Thanks for the guidance!
