### ISSUE TITLE
netdata image in use is spyware

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#553]
https://github.com/titpetric/netdata/blob/master/releases/latest/scripts/build.sh#L31

The netdata image that's being used in CapRover doesn't pass the needed `--disable-telemetry` flag into the installer script when building the image, so the image contains the netdata on-by-default spyware, as documented here:

https://docs.netdata.cloud/docs/anonymous-statistics/

These statistics are not and can not be anonymous, as they include an IP address, which is a unique identifier.

Please do not embed spyware in CapRover.

**Comment by sneak** [comment]
I submitted a PR to that image:

https://github.com/titpetric/netdata/pull/91

**Comment by githubsaturn** [comment]
Please use words carefully. You're accusing NetData of being a spyware. Analytics, as long as they're anonymous, are an integral part of any software. According to PII definitions, IP alone doesn't count as PII.

**Comment by sneak** [comment]
> Analytics, as long as they're anonymous, are an integral part of any software.

This is an objectively false statement.

Much software, netdata included, works fine without analytics.  It is absolutely not *integral*.

> According to PII definitions, IP alone doesn't count as PII.

This is another objectively false statement.

https://www.irishtimes.com/business/technology/european-court-of-justice-rules-ip-addresses-are-personal-data-1.2835704

Any tool that phones home to transmit telemetry *without notifying the user* or *allowing them an opportunity to opt out* is, by definition, spyware - it spies on the user for the benefit of the developer, at the expense of the user's privacy.

**Comment by githubsaturn** [comment]
1) By simply using CapRover, you're pulling data from dockerhub, they do have your IP.

2) spyware is a strong accusation for IP collection.

3) netdata isn't an integral part of CapRover. Posting this here is completely misleading.

**Comment by sneak** [comment]
Connecting to DockerHub is essential to functionality (i.e. downloading the `nginx` container), and does not transmit system information *beyond* IP address to them - it doesn't even tell them the accessing client is CapRover.  It's not an information leak.

I encourage you to go and read the link; NetData is collecting a lot more than just IPs.  Google is receiving all of that additional data, *plus* the IP address.  At no point are NetData users (or CapRover users) notified of this, or given an opportunity to opt out or prevent this data from being transmitted (perhaps against their will, as it was in my case).  That's clearly spyware.

**Comment by sneak** [comment]
I'm not sure what your objection to patching out NetData's spyware (when embedded into CapRover) is.

**Comment by githubsaturn** [comment]
I don't have an objection with regards to patching the 3rd party container. 

What I opposed with, was speeding the "fear of being watched" and using the term "spyware". Regardless, like you tweeted yourself, if you look at software world these days. Any software is a spyware as it transmit your IP, user agent and etc (excluding cookies as they can actually contain personal data). Spreading fear like this will benefit no one IMO. But we need people like you to advocate for privacy anyways, so keep up the good work.

**Comment by sneak** [comment]
No, the vast majority of the software on my system does not phone home or spy on me.  Don't use "everyone else was doing it" as an excuse; *not* everyone else is doing it. The unethical ones are.

**Comment by sneak** [comment]
It sounds like you didn't realize that you had embedded spyware; it's a bad situation for a developer who has built a tool that helps people host things for themselves - you go to all that trouble and end up leaking your data to Google after all!

Let's just get it fixed in CapRover so that doesn't happen anymore.  Take ownership of the failure.

**Comment by sneak** [comment]
Please reopen this issue; CapRover as it is shipping right now phones user configuration data back to Google as soon as NetData is enabled.

**Comment by githubsaturn** [comment]
Without a simple usage analytics, NetData folks would have been able to secure funding so that they can build such a great product for us to use for free. So if anything is unethical, it is to quote their product as a spyware. Anyways, this conversation isn't going anywhere.
I added a bit to the NetData page to address your concern: https://github.com/caprover/caprover-frontend/commit/d577e941e25e64c2ca3a00fc63b24c1b2b527185

More aggressively, I'll add notes to the docs to address your privacy concerns. NetData isn't the only app that possibly sends your IP. There is, certbot, a million one-click apps, there is Docker itself and etc.

**Comment by sneak** [comment]
Certbot requires talking to an API to function and perform the task that certbot does. NetData works absolutely fine with 100% functionality without its telemetry functioning. They are nothing alike. 

From https://en.wikipedia.org/wiki/Spyware :

> Spyware is a software that aims to gather information about a person or organization, sometimes without their knowledge, and send such information to another entity without the consumer's consent. 

NetData did precisely that, without my knowledge and without my consent. It fits the textbook definition of spyware. It’s fact, not hyperbole.
