### ISSUE TITLE
Strapi One-Click-Install didn't work

### ISSUE THREAD

**Issue by ventouris** [caprover/caprover#555]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
When I try to install Strapi through the one-click-install, the installation finishes but when I try to open the /admin, it just redirects you to the index.php page.

Steps to reproduce the problem:
Just install a new strapi and try to reach /admin page

Answers to the following questions where applicable:
- Ubuntu 18.04
- 2GB Ram

**Comment by ventouris** [comment]
Is there anything I can do to help more? Extra debugging? Specific log files?

**Comment by githubsaturn** [comment]
Can you get the logs of drone-gitea and copy it here? You can get it from the deployment tab.

**Comment by khromov** [comment]
Having a similar issue. Deployed Strapi through one-click install but when I go to the domain and am at the welcome screen, the "Create your first administrator" URL links to `http://localhost:1337/admin` instead of the correct location.

**Comment by githubsaturn** [comment]
Do you change the version when deploying or use the default version in One-Click app. I just tried it and it was successful. Here is also the logs from my testing:
![image](https://user-images.githubusercontent.com/10582082/71050052-2ad5bd00-2112-11ea-9a6c-7825da07f956.png)

Does your log match this?
