### ISSUE TITLE
[Deployment Issue] One-Click Install of drone-gitea fails.

### ISSUE THREAD

**Issue by aniketpanjwani** [caprover/caprover#556]
_What is the problem?_

I've succesfully installed Gitea using the one-click install on a fresh install of CapRover. When I try to install drone-gitea using the one-click Install, I get the following error at the 7th step: "Failed: Error: Request failed with status code 500" .

_If applicable, content of `captain-definition` file:_

N/A

_Steps to reproduce the problem:_
1. Install Gitea using the one-click installer, at http://git-gitea.app.example.com
2. Click on "Registration" on Gitea's home page and go through initial configuration.
3. Enable HTTPS for Gitea in settings in CapRover.
3. Attempt to install drone-gitea with the following configuration options:
+ DRONE_GITEA_SERVER: https://git-gitea.app.example.com
+ DRONE_SERVER_HOST: git-gitea.app.example.com
+ secret for linking drone and agent: some randomly generated string from openssl
4. Click "deploy" and get failure message.

_Answers to the following questions if applicable:_
_- Your OS and version?_
Ubuntu 16.04
_- RAM?_
4 GB

**Comment by githubsaturn** [comment]
Can' you get the logs of strapi and copy it here?

**Comment by aniketpanjwani** [comment]
Sorry for the delay - I'll do this tonight.

**Comment by bgervan** [comment]
I think I resolved already with changing the default version on one click app. 
https://github.com/caprover/one-click-apps/issues/113
Am I right?
