### ISSUE TITLE
[Feature Request] Temporary Disable Sites / Enable Maintenance Site/Mode

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#558]
**Is your feature request related to a problem? Please describe.**
Sometime an application breaks and should not be available for public and instead should show an informational site, telling the user that the page currently is not available due to maintenance

**Describe the solution you'd like**
a toggle switch in the configuration of an application with two text fields, one to set the content-type of the maintenance response and one to set its body.

so you could for example send a custom html maintenance page or a json object with an maintenance message instead of your application.

**Describe alternatives you've considered**
non found so far

**Comment by githubsaturn** [comment]
There are multiple solutions for this already:
- One click rollbacks: if you deployed a buggy version you can quickly roll back to the previous version. 
- set instance count to zero. 
- create a custom branded "under construction" page and simply deploy it with PHP template. Note that the PHP template can be used for static pages as well.
