### ISSUE TITLE
WordPress installation with custom domain bugged

### ISSUE THREAD

**Issue by lzzy12** [caprover/caprover#559]
----------------------------------------------------------------------

What is the problem?
I have a WordPress installation (one click app) on my server at https://wp-wordpress.apps.iamshivam.ml
I set the custom domain for it to be https://iamshivam.ml (the same domain which is used by Caprover). However many times while navigating through my wp installation, it redirects me to the original domain provided by caprover i.e. https://wp-wordpress.apps.iamshivam.ml domain. I wouldn't want this to happen.

Steps to reproduce the problem:
Do a fresh wp installation
Set custom domain
Navigate through the app (via custom domain)

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 18.04
- RAM? 2GB

**Comment by githubsaturn** [comment]
It's not relevant to CapRover. The issue you're facing is because of a setting in WordPress. 

You have to change the URL in general settings of WordPress.

**Comment by lzzy12** [comment]
Apologies. I blame the lack of coffee for my stupid issue :)
