### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::80

### ISSUE THREAD

**Issue by ElectricReality** [caprover/caprover#560]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
For some reason error ```Error: listen EADDRINUSE: address already in use :::80``` randomly for no reason at all. I dont know the source. Using ```node:latest```

If applicable, content of `captain-definition` file:
```
 {
  "schemaVersion": 2,
  "dockerfileLines": [
                        "FROM node:latest",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./ /usr/src/app",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

Steps to reproduce the problem:
1. Run a web app on nodejs
2. Randomly ```Error: listen EADDRINUSE: address already in use :::80``` will pop up.

Answers to the following questions where applicable:
- Ubuntu 18.04 LTS
- 4gb?

**Comment by githubsaturn** [comment]
What do you mean by randomly the error pops up? Does it show up in your application log? System logs? CapRover UI?

When does it appear? When you install CapRover? When you deploy an app? While the app is running?

**Comment by ElectricReality** [comment]
On application logs

**Comment by githubsaturn** [comment]
Do you have a reproducible case for this? Can you reproduce this using the sample app:
https://github.com/caprover/caprover/blob/master/captain-sample-apps/node.tar

**Comment by ElectricReality** [comment]
Im currently uploading it right now. Ill update once it sends an error again.
