### ISSUE TITLE
Update old and insecure TLS versions

### ISSUE THREAD

**Issue by bahadirh** [caprover/caprover#562]
When doing tests for my CapRover domain on [SSL Labs](https://www.ssllabs.com/ssltest/), I noticed the default TLS versions are 1.0 and 1.1, which aren't considered secure and will cause the score to be capped to B from January 2020.

I would suggest changing TLS versions to 1.2 and 1.3, which are considered ok in SSL Labs. I've done that manually by updating nginx config from `mydomain/#/settings`, but it would be better if that was default out-of-the-box.

**Comment by githubsaturn** [comment]
Will update using Mozilla Intermediate configurations:
```
# generated 2019-12-07, https://ssl-config.mozilla.org/#server=nginx&server-version=1.17.0&config=intermediate&hsts=false&ocsp=false
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /path/to/signed_cert_plus_intermediates;
    ssl_certificate_key /path/to/private_key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam.pem
    ssl_dhparam /path/to/dhparam.pem;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
}
```

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/caprover/commit/256959f9ce56dd2f8ed46cafed5b4173cdcb0641

**Comment by drmrbrewer** [comment]
@githubsaturn does this mean that it is not possible by default to connect to a node instance deployed via caprover from a client running TLS 1.0?

**Comment by githubsaturn** [comment]
That's correct - the default value is `ssl_protocols TLSv1 TLSv1.1 TLSv1.2;` which supports all 3 versions.You can read more about it [here](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols).

Note that, like all other configs, you can edit this config and customize it to match your requirement. This commit only changes the default behvaior.

**Comment by githubsaturn** [comment]
You probably have edited the nginx configuration. I just double checked a demo app and it looks fine:
https://www.ssllabs.com/ssltest/analyze.html?d=demo-php.server.demo.caprover.com
