### ISSUE TITLE
[Deployment Issue] How to expose port range, not individually...

### ISSUE THREAD

**Issue by rizkyramadhan** [caprover/caprover#563]
I cant expose port range like :

docker run -p 7000-8000:7000-8000

**Comment by githubsaturn** [comment]
Did you look at the app page on your dashboard? Specifically the config tab?

**Comment by rizkyramadhan** [comment]
![image](https://user-images.githubusercontent.com/126301/70382925-38af7380-1997-11ea-81b6-9f4d91df69ae.png)
I mean port-range, for example if want to expose port 7000 until 8000, do i have to put 1000 lines to that ui ?

**Comment by githubsaturn** [comment]
I see. Port rage support is a docker CLI syntactic sugar for individual ports. Docker API (this is what CapRover uses) doesn't support port ranges. See [here](https://github.com/moby/moby/issues/30560#issuecomment-400185685)
