### ISSUE TITLE
Plex/Emby: Video Acceleration API

### ISSUE THREAD

**Issue by nullsumme** [caprover/caprover#564]
I have a Plex/Emby container and want to use hardware acceleration. For this I have to pass a additional parameter to docker:

--device /dev/dri/renderD128:/dev/dri/renderD128

**Comment by githubsaturn** [comment]
The `--device` flag is only available in plain docker containers using [docker run](https://docs.docker.com/engine/reference/commandline/run/) command.

CapRover uses [docker service](https://docs.docker.com/engine/reference/commandline/service_update/) which unfortunately doesn't support `--device` flag.
