### ISSUE TITLE
Disabling external access for Default Push Registry?

### ISSUE THREAD

**Issue by khromov** [caprover/caprover#566]
**Is your feature request related to a problem? Please describe.**
It seems like if you create a Default Push Registry it is exposed on port 996 globally to the world.

Since the password for this registry isn't available anywhere in the web gui, nor does it actually specify that there is a password at all, it makes me a bit unsure how secure this is?

**Describe the solution you'd like**
Allow users to disable the external access for the Default Push Registry by clicking a button in the admin gui.

**Describe alternatives you've considered**
Handy users could use an iptables rule to block the access.

**Additional context**
N/A

**Comment by githubsaturn** [comment]
Container registry needs to be visible to other nodes to function properly. If we disable the external access, we effectively removed the basic functionality of the registry.
