### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by marcelodelta** [caprover/caprover#568]
What is the problem?

> caprover@0.0.0 start /usr/src/app
> node ./bin/www

Captain Starting ...
Installing Captain Service ...
     
 Installation of CapRover is starting...     
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html
     
     
 
 
 
 >>> Checking System Compatibility <<<
   Docker Version passed.
******* Warning *******    CapRover and Docker work best on Ubuntu - specially when it comes to storage drivers.
   X86 CPU detected.
   Total RAM 2096 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v0.29.1
December 22nd 2019, 8:35:52.066 am    Fresh installation!
December 22nd 2019, 8:35:52.070 am    Starting swarm at 186.224.25.70:2377
Installation failed.
{ Error: (HTTP code 503) unexpected - This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one. 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: undefined,
  statusCode: 503,
  json:
   { message:
      'This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.' } }

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
docker run -e BY_PASS_PROXY_CHECK='TRUE'   -p 80:80 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/files/CapRover:/captain caprover/caprover

Answers to the following questions where applicable:
- Your OS and version?
MAC OS 
- RAM?
8GB

**Comment by vohzd** [comment]
Looks like you've already installed this once before. Try these to put it back to how it was;

`docker swarm leave`
`docker system purge -a`

Then try again

**Comment by githubsaturn** [comment]
@vohzd is correct. Also, you may need to "force" leave the swarm:
```
docker swarm leave --force
```

**Comment by marcelodelta** [comment]
Does not Work! =(

**Comment by githubsaturn** [comment]
@marcelodelta what do you see after running the command below
?
```
docker swarm leave --force
```

**Comment by marcelodelta** [comment]
Yes.

% docker swarm leave --force
Node left the swarm.

**Comment by marcelodelta** [comment]
X86 CPU detected.
   Total RAM 2096 MB
Pulling: nginx:1
Pulling: caprover/caprover-placeholder-app:latest
Pulling: caprover/certbot-sleeping:v0.29.1
December 23rd 2019, 12:45:02.599 am    Fresh installation!
December 23rd 2019, 12:45:02.602 am    Starting swarm at 186.224.25.70:2377
Swarm started: s21bzqxn724xwp9pkneynnca0
*** CapRover is initializing ***
Please wait at least 60 seconds before trying to access CapRover.

Just after the container stops

**Comment by githubsaturn** [comment]
Okay, so now you're seeing a different error.. The container stops because you're probably running it on a local machine, not a server, correct?

Note that CapRover is designed to be installed on a server, not a local machine, the process for the local installation is outlined here: https://caprover.com/docs/run-locally.html

**Comment by marcelodelta** [comment]
Got it. I will do the process again, right?

Thank you so much for your attention. We find this project excellent for solutions of this level. We believe we will make donations to the team.

Hugs.

**Comment by githubsaturn** [comment]
> Got it. I will do the process again, right?

On server, yes, all you need to do is to run the installation script and it'll do everything automatically.

**Comment by negati-ve** [comment]
did you get it running on mac?

Seems like captain needs /captain writable 
which isn't writable on mac

**Comment by githubsaturn** [comment]
@negati-ve why do you need ro run this on Mac?

**Comment by manuman94** [comment]
Hey there!

I have the same issue with this configuration:
- Local machine with a public ip (router has forwarded all ports to that machine).
- Firewall ports opened. 
- Domain pointing to the machine's public IP. 

I checked that all is working because if I launch a basic hello world container in port 80, 443 and others I can access by using the domain and subdomains (example.captain.mydomain.com)

Still caprover installation stops the container after pulling all and starting Docker swarm node. 

Is that configuration far from a real server? I followed the local guide but with no success.

Please, any help here?

**Comment by maietta** [comment]
@manuman94,

Which operating system and version are you using?

Also, how was Docker installed?

**Comment by manuman94** [comment]
I forgot to mention, I'm using Windows 11.

But as this is based on Docker, is this important? I mapped the Docker socket to the caprover container the way that works in Windows.

And I installed Docker using WSL 2 backend.

Thanks!

**Comment by githubsaturn** [comment]
Yes. It's important. Mapped volumes, etc are built for Linux, specially Ubuntu.

**Comment by manuman94** [comment]
Thanks for your help!

Would it work if I install Ubuntu under WSL 2 and then caprover?

**Comment by maietta** [comment]
> Thanks for your help!
> 
> Would it work if I install Ubuntu under WSL 2 and then caprover?

I've never tried to install CapRover under WSL2 but I don't see why it wouldn't work.. but I am going to guess the same rules apply for default OS used and the correct Docker installation.

I would stick with either Debian 11, Ubuntu 20.04 LTS or 22.04 LTS and the get.docker.com convenience script.

**Comment by manuman94** [comment]
Hey there! Thank you all for your support. 

I managed to make Caprover work on WSL 2 under Ubuntu. It was pretty easy, and I could use my current Docker for Desktop installation (marking in the settings the Ubuntu integration). It works like a charm.

Thanks again, keep doing it ;)
