### ISSUE TITLE
"Cannot parse" when deploing from plain Dockerfile

### ISSUE THREAD

**Issue by kbzowski** [caprover/caprover#570]
When trying to deploy from any docker file directly, for example: 
`FROM rocketchat/rocket.chat:2.4.0-rc.0`

Build logs show:

> ------------------------- Mon Dec 23 2019 08:17:00 GMT+0000 (Coordinated Universal Time)
Build started for chat
Cannot parse {"stream":"Step 1/1 : FROM rocketchat/rocket.chat:2.4.0-rc.0"}
{"stream":"\n"}

But everything looks to work fine. So the error doesn't seem to pose any problems except for that information. What does it mean. Cannot do something indicates a problem, but is there any?

Answers to the following questions where applicable:
Caprover: 1.6.0

**Comment by githubsaturn** [comment]
Thanks for reporting this. It appears to be bug somewhere upstream where build logs aren't emitted correctly in the new version of Docker. But like what you said, there is no serious consequences to this. It's patched in https://github.com/caprover/caprover/commit/ff3b001bba543cb85251b45806c8287c5a7ebc4e
