### ISSUE TITLE
[Deployment Issue] 504 Gateway Timeout 

### ISSUE THREAD

**Issue by anisbhsl** [caprover/caprover#571]
**What is the problem?**
I am receiving 504 Gateway Time-Out while hitting an API endpoint. The docker container works fine locally. 

Whenever, I am hitting an endpoint e.g.: ```/search?queryparams```, the local instance of docker container works well but deployed version shows Gateway time-out. 

My captain definition file is as follows:
```
{
      "schemaVersion":2,
      "imageName":"anisbhsl/<container-name>"
}
```
***App Config***
Port Mapping:
Server Port: ```5000``` Container Port: ```5000```

***HTTP Settings***
Container HTTP Port: ```5000```

**Comment by githubsaturn** [comment]
You should either remove port mapping if you're using a custom http container port.

**Comment by githubsaturn** [comment]
Assuming you use something like `docker run -p 5000:5000 ....` when you run your container locally, then just simply set the **Container HTTP Port** to `5000` and clear all the port mappings.

**Comment by s-kris** [comment]
I'm having a similar issue. The docker image was deployed via: 
```
{
 "schemaVersion": 2,
 "imageName": "spaceuptech/space-cloud"
}
```
As mentioned above, I didn't set any PORT_MAPPINGS in App Configs. I had only set the Container HTTP Port to 4122.

**Comment by anisbhsl** [comment]
Same here! My problem hasn't been solved either. The docker container works fine locally but it shows Gateway timeout in Caprover.
Note: Deployed app works fine for requests which take short time to respond but throws timeout to requests that take a while to process.

**Comment by s-kris** [comment]
This is very strange but the gateway error is thrown when I use apollo react client in my gatsbyjs front-end. I just tested with axios and it's working fine.

**Comment by githubsaturn** [comment]
1- Do you have a reproducible case? Is it simply just matter of deploying `spaceuptech/space-cloud` image? Does this simply cause gateway timeout?

2- Did you look at nginx logs? what does it say?

**Comment by githubsaturn** [comment]
I just tried the space-cloud image and it's working fine. All I did was to set a container port to 4122 and set the `DEV` env var to `true`

![image](https://user-images.githubusercontent.com/10582082/71545398-90b71580-2958-11ea-8487-fff70041a679.png)

**Comment by s-kris** [comment]
Hey @githubsaturn, thanks for your reply. But as I said here https://github.com/caprover/caprover/issues/571#issuecomment-569422654, it seems to be an issue with apollo. The same api-endpoint when hit with axios, returns the data as expected.

**Comment by anisbhsl** [comment]
Hey @githubsaturn, is there any way to change nginx configuration for request timeout safely? I tried to change the config but it resulted whole cluster crash for a moment. I changed this ``` keepalive_timeout  65;``` in ```/etc/nginx/nginx.conf```

**Comment by githubsaturn** [comment]
@anisbhsl 
Did you change it through the **settings** tab on the web dashboard? It's a safe way of customizing the nginx config. As long as you don't make any typo errors and make the config invalid, it should work.
