### ISSUE TITLE
[Deployment Issue] --advertise-addr is sometimes required for joining worker nodes

### ISSUE THREAD

**Issue by cattoshi** [caprover/caprover#572]
**What is the problem?**

I had to manually join a worker node with `--advertise-addr <WORKER_EXTERNAL_IP>:2377` for the worker services to be discoverable by manager nodes. Checked external firewalls and security groups but that tweak only was able to solve the problem.

**Steps to reproduce the problem:**

Join a node as worker from Caprover gui, allocate a service to the worker node only. The service becomes non discoverable by the manager.

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 18.04
- Caprover version: 1.6.0
- Docker version: 19.03.1

**Comment by cattoshi** [comment]
changed title since I do have two interfaces (my bad). Would still be great to do that by default so we can use the cool shiny gui.

**Comment by sicutdeux** [comment]
Bump on this!, this saved my life.

**Comment by githubsaturn** [comment]
Implemented and available on `edge` version. Will be part of 1.8 release
