### ISSUE TITLE
Support setting custom port and username for cluster joins

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover#574]
This is a follow up on: https://github.com/caprover/caprover/issues/497
Currently, the GUI assumes the remote username is `root` and ssh is working on port `22`. This is generally true, however, by allowing this fields as editable fields, we should allow users to customize these if they need to. 

We also need to make sure that the fields have default values set to `root` and `22` for username and port, respectively. 

Side note: another improvement that we can make in this area is to set a default value for the manager node's IP - we should be able to extract this info.

**Comment by mukeshwani** [comment]
Ah, this could be the issue I'm running into. I'm using Lightsail servers with CapRover and seems that the Cluster GUI assumes I have root user. In face, the Lightsail Ubuntu servers' username is 'ubuntu' and likely why I'm not able to see the second node. It tells me that the node is setup successfully but I don't see in in the Dashboard at all. Your note above may the be issue.

**Comment by mukeshwani** [comment]
For other coming to this post. Workaround:

docker swarm join-token worker # run on main node
docker swarm join --token YOURTOKEN HOST:IP # on new node (keep in mind the first command may produce a custom port which you may need to enable)

However, how to verify the apps are deployed to the second node? There were comments somewhere that you can see the IP of the App in the App page, but I don't see it.

**Comment by githubsaturn** [comment]
@mukeshwani  - you can get the processes on the nodes by running 
```
docker node ps --filter desired-state=Running
```

**Comment by mukeshwani** [comment]
Thanks!
