### ISSUE TITLE
[Deployment Issue] Unable to deploy from GitHub Docker registry

### ISSUE THREAD

**Issue by khromov** [caprover/caprover#576]
> What is the problem?

I can't deploy from a private Docker registry (the GitHub one).

I have added the GitHub repo under "Cluster > Docker Registries":
![2020-01-04 05_48_11-Window](https://user-images.githubusercontent.com/1207507/71759938-dbcfac00-2eb5-11ea-930d-bfb9e54655ab.png)

I have verified that I can log in using the provided credentials on another machine using `docker login` and pull the image in question.

I'm trying to deploy using the full path to the image including the registry:

![2020-01-04 05_49_20-Window](https://user-images.githubusercontent.com/1207507/71759944-03267900-2eb6-11ea-9717-7504628fb74a.png)

However, deployment fails:

```
------------------------- Sat Jan 04 2020 04:50:00 GMT+0000 (Coordinated Universal Time)
Build started for test-from-github-repository
Step 1/1 : FROM docker.pkg.github.com/khromov/docker-node-hello-world/docker-node-hello-world:master

{"message":"Get https://docker.pkg.github.com/v2/khromov/docker-node-hello-world/docker-node-hello-world/manifests/master: no basic auth credentials"}
Get https://docker.pkg.github.com/v2/khromov/docker-node-hello-world/docker-node-hello-world/manifests/master: no basic auth credentials
Build has failed!
```

Using CapRover 1.6.1

Any idea what is wrong? It looks like CapRover isn't providing the credentials I configured for the private registry.

**Comment by khromov** [comment]
Found a workaround by SSH:ing into the command line and manually running `docker login docker.pkg.github.com`, logging in and then restarting the node. Still not sure why it didn't work just from adding the registry in CapRover though.

**Comment by githubsaturn** [comment]
The private registries is only being provided to the direct image name deploys - not the Dockerfile. Instead of deploying
```
FROM docker.pkg.github.com/khromov/docker-node-hello-world/docker-node-hello-world:master
```

You should simply use this:
```
{"schemaVersion":2,"imageName":"docker.pkg.github.com/khromov/docker-node-hello-world/docker-node-hello-world:master"}
```

This should work. Please try and let me know if it doesn't work.

**Comment by frederikhors** [comment]
@githubsaturn as explained https://github.com/caprover/caprover/issues/1552#issuecomment-1449116855 only method 4 works (with the internal caprover's Docker registry). If I use: `{"schemaVersion":2,"imageName":"docker.pkg.github.com/khromov/docker-node-hello-world/docker-node-hello-world:master"}` the error is the same: `no basic auth credentials`.

**Comment by githubsaturn** [comment]
@frederikhors  - have you added your registry under the cluster tab? I have an instance with this config and it works just fine:

![image](https://user-images.githubusercontent.com/10582082/222062029-b7eb4e00-7958-4209-99b5-4e778a9134cd.png)

**Comment by githubsaturn** [comment]
The only thing to note is that, instead of password, you should use github token. It starts with `ghp_`

**Comment by frederikhors** [comment]
@githubsaturn sorry for the confusion. I'm talking about using the CapRover's internal Docker registry. Everything works if I use method 4.
