### ISSUE TITLE
Docker iptables and ufw

### ISSUE THREAD

**Issue by dg-otrs** [caprover/caprover#579]
Hey,

not really sure if this may need to be applied on caprover installations? https://github.com/chaifeng/ufw-docker -> Docker and UFW Security Flaw

Does this effects caprover?

Cheers

Dennis

**Comment by githubsaturn** [comment]
> Does this affect CapRover?

No. 

But it does affect how all Docker applications work. Essentially, ufw rules are bypassed when you forward/expose a port. Arguably, 99.9% of the times, this is actually what you want. 

With regards to CapRover, this doesn't impose any security risk. But let's say, you forward port 7777 of your host to port 6666 of your container. This will bypass ufw rules, meaning that it will expose your 7777 port regardless of your ufw settings. By default no ports on CapRover is exposed other than the ports that are needed for CapRover, https://caprover.com/docs/firewall.html#docsNav

**Comment by dg-otrs** [comment]
Good explanation! Got you and full with you. 

Thanks!

btw love your tool!

**Comment by thomascenni** [comment]
Hi all, I would like to reopen this discussion. I have a Caprover installation running and followed the guide for block all the ports with ufw:
https://caprover.com/docs/firewall.html#docsNav
I installed a PostgreSQL server, and mapped the 5432 container port to the server port number 5400 (as example).
I can connect to my PostgreSQL instance directly on port 5400 from my development machine !
**I do not want that**. 

I'd like to connect to my db instance only via a SSH tunnel, don't want to expose the port on the Internet.
Is there any particular setting to allow this ?

**Comment by githubsaturn** [comment]
@thomascenni 

A few things:

Regarding:
> I installed a PostgreSQL server, and mapped the 5432 container port to the server port number 5400 (as example).
I can connect to my PostgreSQL instance directly on port 5400 from my development machine !
I do not want that.

This has **nothing to do with CapRover**. This is how Docker overlay network works. You should not enable port mapping unless you want it to be accessible from the outside.


If you want it to be accessible only via SSH tunnel, follow the guide here: https://caprover.com/docs/database-connection.html#external-connections


**You must install the SSH app**. You cannot use the sshd on your host network to connect to the database. You must SSH to inside a container and that container can talk to the database container.

Hope this diagram helps:
```



     HOST SYSTEM
    +-----------------------------------------------------------------+
    |                                 +-------------------+           |
    |                                 |                   |           |
    |                                 |  SSHD ON HOST     |           |
    |                                 +-------------------+           |
    |   DOCKER SYSTEM                                                 |
    | +-------------------------------------------------------------+ |
    | |                                                             | |
    | |                                                             | |
    | |    +----------------+         +--------------------+        | |
    | |    |                |         |                    |        | |
    | |    |  SSH Container |         | Database Container |        | |
    | |    |                +-------->+                    |        | |
    | |    +-----^----------+         +--------------------+        | |
    | |          |                                                  | |
    | |          |                                                  | |
    | +-------------------------------------------------------------+ |
    |            |                                                    |
    +-----------------------------------------------------------------+
                 |
                 |
                 |
                 |
                 |
                 |
       +-----------+
       |    YOU    |
       +-----------+
```

**Comment by thomascenni** [comment]
Dear @githubsaturn,
Thanks for your explanation, now it's clear, the diagram was very helpful.
I installed the SSH one click app and I am able to tunnel into the database.

Just one more comment regarding the docs:
https://caprover.com/docs/database-connection.html#external-connections

> By default it uses port 4646. Make sure this port is allowed to pass through your firewall.

There is no need to allow this port on ufw because, as you also wrote, ufw rules are bypassed when you forward/expose a port, and this is done by the SSH one click app.
Thanks,
Thomas

**Comment by githubsaturn** [comment]
> There is no need to allow this port on ufw because, as you also wrote, ufw rules are bypassed when you forward/expose a port

ufw rules are bypassed. But there are other types of firewalls. If you have a firewall on your router, it will not get bypassed by port mapping.

**Comment by bibstha** [comment]
If you are using public cloud servers like hetzner, digitalocean or linodes, these services provide free firewalls. One should turn them on to prevent accidental access if you need to open up the ports to public ports
