### ISSUE TITLE
Enable delete for self hosted docker registry

### ISSUE THREAD

**Issue by invisal** [caprover/caprover#580]
**Is your feature request related to a problem? Please describe.**
There is no way to clear unused image in the self-hosted registry. The size of the image could build up quickly if we have many app inside the cluster and frequently change on each of those app.

**Describe the solution you'd like**

- I think we can enable `REGISTRY_STORAGE_DELETE_ENABLED=true` when we start the registry. (https://github.com/caprover/caprover/blob/dc2a5b65928934ac8380401498714cb2abe09a68/src/user/system/SelfHostedDockerRegistry.ts#L92)
- Add API to list of repository in the private registry
- Add API for list image in each repository in the private registry
- Add API to delete the image in the private registry.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by githubsaturn** [comment]
Good suggestion. We'll add the flag to be able to remove the images.

With regards to the API,  docker registry already has an API that you can use. Maybe we should add one of the docker image GUI apps as a one click app to make this even easier.

**Comment by invisal** [comment]
>  Good suggestion. We'll add the flag to be able to remove the images.

Thanks. I can help with this issue. This should be a good starting point for me to get started contributing.

> Maybe we should add one of the docker image GUI apps as a one click app to make this even easier.

I don't know if it is possible to do it from One Click App as you need username and password to access to the registry and it is encrypted within the Caprover.

**Comment by githubsaturn** [comment]
> I don't know if it is possible to do it from One Click App as you need username and password to access to the registry and it is encrypted within the Caprover.

Currently the password isn't visible to the user as the password cannot be changed. But we can change the UI on the frontend to allow displaying a readonly password

**Comment by invisal** [comment]
In order to enable self hosted registry, it requires us to enable root SSL and registry SSL. It seem it is not possible to ask letencrypt to generate certificate for localhost.

While I finish the code, but I don't know how to test if my code is correct.

**Comment by githubsaturn** [comment]
>  It seem it is not possible to ask letencrypt to generate certificate for localhost

Of course, localhost is not a publicly accessible domain. Let's Encrypt only works on public domains. It is outlined here: https://caprover.com/docs/run-locally.html#setup

**Comment by githubsaturn** [comment]
`REGISTRY_STORAGE_DELETE_ENABLED=true` is added to the selfhosted registry. It'll be part of the next release.

**Comment by ApexaGlobal** [comment]
May I ask how this works? I have 2 nodes and it's using self hosted registry. Now I want to delete unused images which I don't know how to.
Can anyone help?

**Comment by chiragshahklc** [comment]
May I ask how this works? I have 2 nodes and it's using self hosted registry. Now I want to delete unused images which I don't know how to.
Can anyone help?

**Comment by githubsaturn** [comment]
@chiragshahklc the selfhosted registry is just a standard Docker registry image. You can consult Docker registry API docs to learn how to delete images:
- https://stackoverflow.com/questions/32563780/why-cant-i-delete-a-layer-in-my-private-docker-registryv2
- https://medium.com/@cnadeau_/private-docker-registry-part-1-basic-local-example-c409582e0e3f
- https://www.reddit.com/r/docker/comments/95mhdg/how_to_delete_images_in_a_private_v2_repository/

Alternatively you can deploy a UI for your Docker registry:
- https://hub.docker.com/r/evedel/bow/
- https://github.com/Joxit/docker-registry-ui
- https://github.com/atcol/docker-registry-ui
- https://github.com/genuinetools/reg
- https://github.com/parabuzzle/craneoperator

**Comment by rymdluo** [comment]
@githubsaturn I looked at the links and tried `docker exec CONTAINER_ID registry bin/registry garbage-collect /etc/docker/registry/config.yml -m`, which yielded: `5055 blobs marked, 0 blobs and 0 manifests eligible for deletion`

I'm not sure where to go on from here. @chiragshahklc Did you manage to move forward with deleting unused images from the registry?

**Comment by chiragshahklc** [comment]
Every weekend, I delete unused images and container which including untagged and tangled. I couldn't work it with UI. Single command seems good to me. Although do read about it on docker docs before using.
```bash
docker system prune -a
```
This has worked fine for me without any issue.

Reference: https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by githubsaturn** [comment]
`docker system prune -a` is **extremely dangerous. Use with caution!**
First, it doesn't delete images from the registry. It only deletes the unused images on Docker on the machine that this command runs on.
Second, if you have any service with persistent volumes attached, it may delete the volume if, at the time you run this command, the container is paused or crashed.
