### ISSUE TITLE
[Feature Request] Volumes/Database Backup Button

### ISSUE THREAD

**Issue by bgervan** [caprover/caprover#581]
**Is your feature request related to a problem? Please describe.**
There is no general solution for backing up volumes and databases. You have to login via SSH and run a bunch of command to make it. 

**Describe the solution you'd like**
It would be great, if I can define my own backup script on GUI, and also run it via button or set a cron job from there to run every x day. Separate console output log for the backup scripts.
Also there could be templates for simple volumes, different types of databases. It would speed up the writing process. 
With this approach, I could automate complete backup-restore solution, even with S3 storage if I want. 
For example:
`docker service ls --format {{.Name}} | while read in; do docker service scale "$in"=0; done`
`***DO THE BACKUP SOMEHOW***`
`docker service ls --format {{.Name}} | while read in; do docker service scale "$in"=1; done`

**Additional context**
The idea is not fully defined yet. 
Maybe a storage driver have advantage, but that's a different approach to make it easier.
For example: https://github.com/blockbridge/blockbridge-docker-volume
For this, the volume creation would change, and I am not sure that Caprover create all volumes. But for that case, this would make it easier.

**Comment by githubsaturn** [comment]
This was previously discussed as a no go https://github.com/caprover/caprover/issues/187#issuecomment-366563188


The reason behind that is the complexity of taking snapshots of live volumes which can definitely cause data corruption. Having this kind of limited solutions is worse than having none as the users might think they actually have a back-up solution only to find out later that their backed up data is corrupted. 

Volume backup solutions are applicable specific. For example databases have dump command, CMSs have s3 adapters. Creating a generic solution that works for everything without breaking the data is next to impossible.

**Comment by githubsaturn** [comment]
We already have a script that you can run on your server to backup your volumes:

https://github.com/caprover/caprover/blob/master/dev-scripts/backup-vols.sh

This script turns off the services before taking snapshots to avoid data corruption. 

This is intentionally left as a separate script and not part of the gui due to the complexities of backup that i mentioned above.

**Comment by bgervan** [comment]
Thanks for the detailed reply. I didn't know about the dev scripts. 

I see that it could cause data corruption, but in the example, I turn off the service. 

> Volume backup solutions are applicable specific. For example databases have dump command, CMSs have s3 adapters. Creating a generic solution that works for everything without breaking the data is next to impossible.

That's why I suggested a script input to define the specific actions. I mean the User has to define the backup actions for every app, the templates only there to have a skeleton.

**Comment by githubsaturn** [comment]
The script input wouldn't be a plausible solution here. Well in fact, it will possible. But that part of the script is the meat of the process. 

Other than than, the backup script that linked above is mostly what you want. It takes care of backing up, and restoring. And it also has a default behavior for shutting down the containers before backing up.
