### ISSUE TITLE
[Deployment Issue] (Question) How to add persistent volume in One-click App

### ISSUE THREAD

**Issue by locvfx** [caprover/caprover#582]
**What is the problem?**
I can't figure out how to add Persistent Volume in One-click App (PHPMyAdmin). After I deployed the app, The Persistent volume does not exist in the Dashboard

Please, if someone can answer my question please help. I'm still looking around the Wiki and search on Google. Thank you

**Comment by githubsaturn** [comment]
Whether or not the app can have persistent volume is defined at the creation time and cannot be changed afterwards. 

If you want to add volumes to phpmyadmin, simply create the app manually:
- create a new app with persistent data checked
- go to the app, add this environmental variable:
`PMA_ARBITRARY` with value of `1`
- click on SAVE button and then
- go to deploy panel
- navigate to deploy with Dockerfile
- enter `FROM phpmyadmin/phpmyadmin:4.8` and click deploy.

This is the manual translation of one click app:
https://github.com/caprover/one-click-apps/blob/master/public/v2/apps/phpmyadmin.json

**Comment by locvfx** [comment]
I found a solution. I edited /captain/data/config-captain.json 

Change the value in that container: 
"hasPersistentData": true

And then restart the Application

**Comment by tschannik** [comment]
@locvfx 
Just tried your solution but it seems that with my custom one-click-app i still don't have a persistant volume. 

@githubsaturn in my opinion it would be a great addition to have an option to include it in the yml config if you'd need a persistant volume for a one-click-app

**Comment by bibstha** [comment]
@githubsaturn would it be possible to add an option to add persistent volume to an already configured app? Just like changing any other config (eg: ENV variable), this could restart the app. There are times when I have a running app served on some URL and then I need persistent volume. Right now, I would have to copy all the config (ENV var) and the deployment image. 
Curious to know what the limitations are right now.

**Comment by githubsaturn** [comment]
Feel free to open a feature request.
