### ISSUE TITLE
NGINX fails to resolve on cluster during server restart

### ISSUE THREAD

**Issue by ultimateprogramer** [caprover/caprover#584]
**What is the problem?**
I recently setup a 2 machine cluster on caprover. The machines on the cluster unfortunately were shut down, when restarting the machines, I noticed that containers hosted on the worker node were sending a 504 Gateway Timeout (through NGINX). NGINX would only render for containers hosted on the leader node.

**If applicable, content of `captain-definition` file:**

N/A

**Steps to reproduce the problem:**

* Install a Caprover Cluster.
* Deploy some apps.
* Shut down cluster VMs.
* On restart, containers on worker node will give a 504 Gateway timeout.

**Answers to the following questions where applicable:**
- Your OS and version? Ubuntu 16.04 on both machines
- RAM? 7.5 GB on each node.

**Comment by githubsaturn** [comment]
The leader node cannot reach the worker node. It could be due many factors, make sure all necessary ports are open on all nodes:
https://caprover.com/docs/firewall.html

Note that if you're using a VPS provider which has firewall overrides (like AWS security groups) that override the local firewall rules on your system, you'll have to adjust those as well.

If after checking the ports, you still have problems run `docker node ls` on your leader node and make sure all your nodes are accessible.

**Comment by ultimateprogramer** [comment]
Both ufw and firewall settings seem OK. But I have researched this issue and the error I get is this one from the logs:

```
2020/01/20 09:10:09 [error] 6#6: *373 upstream timed out (110: Connection timed out) while connecting to upstream, client: xx.xx.xxx.xx, server: xx.xxx.xxx.com, request: “GET / HTTP/1.1”, upstream: “http://10.xx.xx.xx:8280/”, host: “xxx.xxx.xxx.com”
```

Any insights will be highly appreciated.

**Comment by githubsaturn** [comment]
This is most likely a firewall issue. Anyways, try these:
- Run `docker service ls` and copy the output here. Make sure that all your services are running.
- If nothing is unusual from the previous command and you see that your service that has problems running with 1/1 instance, move on and run the following command and copy the output here for debugging.
```
docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh -c \
   'curl -v http://srv-captain--yourappname:8280/'
```

MAKE SURE to replace `yourappname` above with your own appname

**Comment by ultimateprogramer** [comment]
I will run tests for 2 docker containers on the worker VM and the output is as so:

I will only post the lines relevant to the app(s) in interest (and abstract the app names):

command: `docker service ls`

```
ititpfxvwm57        srv-captain--xxx                    replicated          1/1                 registry.xxx.xxxxx.com:996/captain/img-captain-xxx:1                    *:4545->4545/tcp, *:8080->8080/tcp, *:4545->4545/udp, *:8080->8080/udp
```
```
wakw55pk4kc3        srv-captain--xxx                  replicated          1/1                 registry.xxx.xxxxx.com:996/captain/img-captain-xxx:1                  *:8280->8280/tcp, *:8280->8280/udp
```
When running the command: `docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh -c    'curl -v http://srv-captain--xxx:xxxx/`

Both of these apps present:
```
*   Trying 10.0.1.70...
* TCP_NODELAY set
* connect to 10.0.1.70 port 8280 failed: Connection timed out
* Failed to connect to srv-captain--xxx port 8280: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to srv-captain--xxx port 8280: Connection timed out
```
and..
```
*   Trying 10.0.1.223...
* TCP_NODELAY set
* connect to 10.0.1.223 port 8080 failed: Connection timed out
* Failed to connect to srv-captain--xxx port 8080: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to srv-captain--xxx port 8080: Connection timed out
```

**Comment by githubsaturn** [comment]
This is a port issue. Make sure all ports are open: https://caprover.com/docs/firewall.html
Either you have a blocking firewall that don't have all the ports open, or you have a firewall setup that you're not aware of.


As your can see in your last output:
```
curl: (7) Failed to connect to srv-captain--xxx port 8080: Connection timed out
```
The connection to your app was unsuccessful even without CapRover in the mix. It's definitely a firewall/docker problem, and unrelated to CapRover, see this for example: https://serverfault.com/a/986274

Run the same setup on two sets of public servers without any additional firewall (DigitalOcaen is the easiest) and you won't have any problems.
