### ISSUE TITLE
Integration: Uptimerobot

### ISSUE THREAD

**Issue by manjeshpv** [caprover/caprover#585]
Uptimerobot is a free service,

For every api service I create in nodejs, I will add monitoring with uptime robot

Thanks for caprover reduced my 90% efforts by automating 

**Solution**:
Integrating with https://uptimerobot.com/api -> New Monitor API

1. Enable Uptimerobot button in Apps page
2. To set API Key: In settings page one input box

@ringods @ariarijp @chelarua

I will start working on it and I will share pull request soon.  someone interested Pls join

**Comment by githubsaturn** [comment]
It's a 3rd party API and we'll not support it.
