### ISSUE TITLE
Multiple instance Count

### ISSUE THREAD

**Issue by synetalsolutions** [caprover/caprover#587]
When we choose 3 Instance count the instance not connect to database means login and signup not working.

And also no log generating in console.

**Comment by githubsaturn** [comment]
More information is needed. Are you increasing count of a web app or database, or a one-click app?

What is the issue that you're facing with regards to connection? Time out or address not resolved?

**Comment by synetalsolutions** [comment]
I am using web app when i choose instance count 3. App is not able to connect to database.

**Comment by githubsaturn** [comment]
What do you mean by login not working? You cannot log in to CapRover dashboard?

**Comment by synetalsolutions** [comment]
We have created a Node.js app and mongodb dashboard so one container has mongodb and one is node.js which is our application so when we try to do instance count 3 app is not able to connect to mongodb however in the log it says mongodb connected but when we try to login with our credentials on our app it not proceed. Don't what is the exact issue it is working fine in single instance count.

**Comment by jpolvora** [comment]
it's not related to caprover, but how you've designed your app. It appears that your issue is related how session state is stored. You must use a database or external storage to store sessions.  Because memory on app instances are isolated, so if a request hit one instance of your app, the other instances have not knowledge about the session info/cookie/etc.

**Comment by synetalsolutions** [comment]
I am using mongodb database to store the sessions if it is wrong why it is working in single instance count.

**Comment by jpolvora** [comment]
verify if the session secret is the same shared across all app instances.

**Comment by synetalsolutions** [comment]
we are building our node.js app via bitbucket so when we do force build all the instance redeploy. It should work don't what is the exact issue.

**Comment by githubsaturn** [comment]
As @jpolvora mentioned, this is most likely your application bug. As per your previous comment there is nothing in the logs. And the connection to the database is going okay. There could be a million different reasons as to why your multiple instances don't work.

One example is that if you hold a random session key in the memory cache of your application. In this case, due to the fact that the memory of instances won't be shared with each other, the other instances aren't able to read the same memory cache. 

**Unless you provide a log that indicates what is wrong with your service, it's impossible to debug the situation.**

**Comment by synetalsolutions** [comment]
`CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                      NAMES
7259bbec7f4e        img-captain-dhangames-panel:222       "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        5000/tcp                                   srv-captain--dhangames-panel.3.9nku3pasgfedm65zc84u2uftg
6b0238e80bd6        img-captain-dhangames-panel:222       "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        5000/tcp                                   srv-captain--dhangames-panel.1.vjtnue54pv5o3kvqskk5zhh2t
62c7fe1051e2        img-captain-dhangames-panel:222       "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        5000/tcp                                   srv-captain--dhangames-panel.2.y37k69g4nb89mt8vmu6qs43u9
74dbd5f9d00d        img-captain-dhangames-chatpanel:160   "docker-entrypoint.s…"   30 hours ago        Up 30 hours         5000/tcp                                   srv-captain--dhangames-chatpanel.1.rd6nqsgvvbsmlz2r9kl9q0pqh
c816b552dd3d        caprover/certbot-sleeping:v0.29.1     "/bin/sh -c 'sleep 9…"   2 weeks ago         Up 2 weeks          80/tcp, 443/tcp                            captain-certbot.1.skjek07zupprs9ahy3v9rlq9t
b635ab577ae1        nginx:1                               "nginx -g 'daemon of…"   2 weeks ago         Up 2 weeks          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   captain-nginx.1.3h15hb9jktnkcbq3k54yee29j
a77f4a397f68        caprover/caprover:1.6.1               "docker-entrypoint.s…"   2 weeks ago         Up 2 weeks          3000/tcp                                   captain-captain.1.unizh65blnuih3qdtkxxexuxe
eb50f3b5dc29        a0e2e64ac939                          "docker-entrypoint.s…"   4 weeks ago         Up 4 weeks          27017/tcp                                  srv-captain--dhangames-chatdb.1.x1rdjl3751fj4x1v4w7ch126v
3678e19237e4        titpetric/netdata:1.8                 "/run.sh"                5 weeks ago         Up 5 weeks          19999/tcp                                  captain-netdata-container
cc2434a0278e        a0e2e64ac939                          "docker-entrypoint.s…"   5 weeks ago         Up 5 weeks          27017/tcp                                  srv-captain--dhangame-db.1.xj186rtwe8go5a9qznoafz99q`

This is my nginx config file and node.js running on port 5000 

Setting Contain HTTP Port is 5000

**Comment by synetalsolutions** [comment]
![Annotation 2020-01-26 233134](https://user-images.githubusercontent.com/32237609/73139443-0fa48880-4094-11ea-9a96-0b0554f28f35.png)


This all are my containers running currently instance count is 3

**Comment by githubsaturn** [comment]
This is not logs. Run `docker container logs CONTAINER_ID` to get logs of each container. Then, look for logs where YOUR CODE is complaining if something is wrong.

**Comment by synetalsolutions** [comment]
root@server:~# docker container logs 98ee2b6e2dc0

> dashboard-new@1.0.0 start /usr/src/app
> node app.js

Running on PORT 5000
Mongo Connected
root@server:~# docker container logs b7759c1ee3f0

> dashboard-new@1.0.0 start /usr/src/app
> node app.js

Running on PORT 5000
Mongo Connected
root@server:~# docker container logs 393f76016205

> dashboard-new@1.0.0 start /usr/src/app
> node app.js

Running on PORT 5000
Mongo Connected
root@server:~#

All three container are connected to mongodb.

**Comment by githubsaturn** [comment]
There you go. So this is not a CapRover bug. So what's the issue here?

**Comment by synetalsolutions** [comment]
When I pass the credentials to my admin panel it just reload but when i set instance count to 1 it work without any issue.

**Comment by githubsaturn** [comment]
Then add some logging and find out what's the issue. As I mentioned above: **Unless you provide a log that indicates what is wrong with your service, it's impossible to debug the situation.**

Closing this issue as it's completely irrelevant to CapRover.
