### ISSUE TITLE
Database Cluster

### ISSUE THREAD

**Issue by Mochaka** [caprover/caprover#588]
Would it be possible to get One-Click of a MariaDB cluster going?

https://github.com/colinmollenhour/mariadb-galera-swarm

I've got this running on my swarm, just thought it might be nice to have it in the UI.

This docker allows you to have MariaDB (MySQL) installed on each node, and they sync with each other so each node has the same data.

**Comment by cattoshi** [comment]
Swarm services allow for a global deploy option. Wouldn't this be cool to have in the ui? Currently we can only specify the id of one node, but for services like metrics and notifications as well as this db it would be nice to have a global option in the ui imo.

**Comment by githubsaturn** [comment]
These are two different questions, and I'll answer them separately:

- MariaDB cluster:
This and MongoDB cluster have come up in the past, but the reality is when you get into the state where you need a cluster, you probably need a lot more customization along with this.
Not sure if it's true for MariaDB cluster, but theoretically, it's possible to create a one click app for a 3-leg cluster for MongoDB using pure docker-compose. However, it'll be very inefficient and you need to configure lots of parameters in order for it to work based on your needs. Reflecting all the custom parameters in the UI isn't maintainable on CapRover long term. Therefore, we only port over the simple things to the UI.

- Global Deploy:
This is definitely doable, but it requires custom modification of predeploy function:
https://caprover.com/docs/pre-deploy-script.html

It allows you to modify [Docker Swarm Service Object](https://docs.docker.com/engine/api/v1.30/#operation/ServiceUpdate) which is basically the lowest level access possible. You can do whatever you want.

**Comment by cattoshi** [comment]
@githubsaturn yes anything can be done in predeploy but how do we know a function would be better as an improvement in the gui? A global checkbox for metrics would be a very generic use case.

**Comment by githubsaturn** [comment]
@cattoshi I'm sorry - I have to the bad guy here gate keeping what goes in. Everyone sees their use-case as a common use-case. But at the end of the day, this is a one-man project and I have to be able to maintain it long run as a lot of people/companies are using this in their production environment. To keep the project within a manageable scope, we have to offload lots of configs to "custom" configuration. This example is about `global` option, but there is a ton more examples that is considered "generic": read-only volumes, reserved RAM/CPU, limiting RAM/CPU, node placement constraints, custom DNS address, health-command and timeout, custom networks, rollback strategy... This list never ends :) And all of these customization configs have their own usage and they are "widely" used.

**Comment by cattoshi** [comment]
@githubsaturn don't worry :) you're not the bad guy. I'm ok with using my custom config and is rather simple.
