### ISSUE TITLE
PlayWithDocker Demo ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by OmgImAlexis** [caprover/caprover#589]
What is the problem?
I can't view any apps on the PWD demo. I get this error ERR_INCOMPLETE_CHUNKED_ENCODING I can open the file that's throwing this though. Seems to mainly be js files.

Steps to reproduce the problem:
Follow the PWD demo guide and then install an app.

**Comment by githubsaturn** [comment]
When you say install app, are you referring to the sample tarfile apps? Or oneclick apps?

Also:
- which app?
- the error is during upload/setup? Or when you want to access the app?

**Comment by OmgImAlexis** [comment]
One click apps.

**Comment by githubsaturn** [comment]
I can't reproduce the issue. It's possible that the issue is due some settings on your machine. See this: https://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error

Use google Chrome as your browser 
Try another machine if possible.
Try another browser like Firefox
Try incognito mode

**Comment by OmgImAlexis** [comment]
The accepted answer points it to being a server side issue. Not sure why you seem to think it's the client side. Did you not read your own link?

https://stackoverflow.com/a/29969400/2311366

Seeing the same issue across the board with all browsers, etc.

**Comment by githubsaturn** [comment]
I'll keep this issue open for a few days to see if anyone else is encountering this issue.

**Comment by githubsaturn** [comment]
@OmgImAlexis 

Is there any particular app that's acting up? Can you provide an example that you tried and it didn't work?

**Comment by githubsaturn** [comment]
I just checked Adminer and WordPress again and they both worked fine. Can you please retry?
