### ISSUE TITLE
Sample apps should be added as source

### ISSUE THREAD

**Issue by OmgImAlexis** [caprover/caprover#590]
Instead of adding the `.tar` for each sample app the source should be added and the `.tar` files created on release and then just added as extra files. Users can then view the release page to download the apps.

**Comment by OmgImAlexis** [comment]
This is likely relevant https://stackoverflow.com/a/15983139/2311366

**Comment by githubsaturn** [comment]
These are "example" apps and it's in tar format intentionally so that the users can simply upload these without having to install CLI. There's a goal to break up these samples into their own repository at some point. But for now, as long as they're hosted on the main repo, they'll be in tar file.

**Comment by OmgImAlexis** [comment]
Okay but why not at least move them to the releases. It makes it harder to know what changes you’ve done to the sample apps.

**Comment by githubsaturn** [comment]
I think you're misunderstanding what sample apps are. They are just example apps to show you how to work with CapRover. They are not part of the release process. 

Why do you think you need to know when they get updated?

**Comment by OmgImAlexis** [comment]
No I'm not, you're misunderstanding how typical users use software.

A sample app I expect to be updated as time goes on, looking at the node apps for example it looks like they were written by someone that used ES5. I would have hoped to see a newer more modern approach. Same thing for Python 2.7 ending and Python 3 being the new recommended version.

People will end up using this kind of thing for training, etc. meaning people will end up using the sample apps more than you'd expect. It makes more sense to have them versioned and updated instead of just throwing a tar into a dir.

"They are not part of the release process." You don't say. That's kinda my point.

**Comment by githubsaturn** [comment]
Node sample app shows how you would deploy a "node" app with CapRover. It doesn't matter if it's es5 es6 or whatever. It's the point of CapRover. You can deploy any version of node.

**Comment by OmgImAlexis** [comment]
Yep, just skip over the whole thing I said. I'm done with this.
