### ISSUE TITLE
Matomo One-click app fails

### ISSUE THREAD

**Issue by chocochrispi** [caprover/caprover#597]
_What is the problem?_
When I click on the Matomo button on the One-click app menu I get "Something bad happened"
It is the only app doing it. 

Steps to reproduce the problem:
Click on the Matomo button

Caprover 1.6.1
RAM: 7.75 GB
OS: linux
CPU: 4 cores
Architecture: x86_64
Docker Version: 19.03.5

**Comment by githubsaturn** [comment]
You probably have a browser extension that blocks it (some sort of ad/analytics/tracking blocker). Try incognito mode on Chrome.

**Comment by chocochrispi** [comment]
You are right 👍 

Thank you
