### ISSUE TITLE
contributor request

### ISSUE THREAD

**Issue by oda-alexandre** [caprover/caprover#598]
Hello, I would like to become a contributor to the project, I like your work and would like to make my contribution. You can look at my projects developed on my profile and see an already ready one click app "odoo" an ERP that I would like to bring you. I have other one click app projects to suggest later. I am devsecops ethical hacker. You will find my info on my github profile.

**Comment by githubsaturn** [comment]
Hi @oda-alexandre 

First, please have a look at the [Pull Request Template](https://github.com/caprover/caprover/blob/master/.github/pull_request_template.md) and feel free to create a pull request.

There are multiple things that you can work on:

- Adding/updating the documentation, Creating tutorials, for example [this](https://github.com/caprover/caprover/issues/491)
- Frontend enhancement like [this](https://github.com/caprover/caprover-frontend/issues/39)
- Backend enhancement like [this](https://github.com/caprover/caprover/issues/533)

**Comment by oda-alexandre** [comment]
> Hi @oda-alexandre
> 
> First, please have a look at the [Pull Request Template](https://github.com/caprover/caprover/blob/master/.github/pull_request_template.md) and feel free to create a pull request.
> 
> There are multiple things that you can work on:
> 
> * Adding/updating the documentation, Creating tutorials, for example [this](https://github.com/caprover/caprover/issues/491)
> * Frontend enhancement like [this](https://github.com/caprover/caprover-frontend/issues/39)
> * Backend enhancement like [this](https://github.com/caprover/caprover/issues/533)

Ok, thank's
