### ISSUE TITLE
CPU spikes during npm install

### ISSUE THREAD

**Issue by ekersten** [caprover/caprover#599]
This may be a total beginner question but here I go anyway.

I have a locally developed Laravel application which has nodejs mainly to compile SCSS and stuff like that.

I've managed to setup automatic deployments using github hooks in order to avoid having to upload the tar file via the console.

My starting point is a docker image created by me pushed to docker hub (ekersten/nginx-php72-node10x) on which I run this Dockerfile

```
FROM ekersten/nginx-php72-node10x

COPY ./src /var/www/html
COPY docker-entry.sh /

WORKDIR /var/www/html

RUN composer install
RUN npm i

# Expose port 80 and start php-fpm server
EXPOSE 80
CMD ["/docker-entry.sh"]
```

Everything seems to go OK up until the `npm i` line. Then I start seeing the "Something went wrong"  toast message. As fas as I could investigate it seems that the server is restarting from exceeding CPU usage.

![image](https://user-images.githubusercontent.com/1256078/74870238-2dce7300-5338-11ea-81b0-9d195cc8a17a.png)

This is running on the most basic DigitalOcean droplet with Caprover installed from their marketplace and the updated to v1.6.1.

Do you have any suggestion as how to mitigate this? This is a very common application structure we use here and I would love to incorporate Caprover to our workflow.

Thanks in advance for reading all this. Any help is appreciated.

**Comment by githubsaturn** [comment]
Unfortunately, `npm install` can be very resource intensive. There isn't much that can be done on CapRover end. However, there might be some workaround:

Option 1)
Build on your machine and deploy the "built artifact". This will give your the fastest build time. There is a [static react app tutorial](https://caprover.com/docs/recipe-deploy-create-react-app.html) on the website which uses the same technique. Yours will be similar to this approach with some modifications. Let me know if you need more details on how to do this for your app.

Option 2) 
Use resource limiting flags for node process, e.g., change `npm i` to:
```
# Install app dependencies
COPY package.json /usr/src/app/
RUN /usr/bin/node \
  --max_semi_space_size=1 \
  --max_old_space_size=198 \
  --max_executable_size=148 \
  /usr/bin/npm install
```

See [here](https://github.com/npm/npm/issues/9884#issuecomment-244532323) for more details.

**Comment by ekersten** [comment]
@githubsaturn just a quick question following your answer.

i've seen examples that copy either composer.json and/or package.json, install dependencies and then copy the application itself. Does this come with a performance advantage or is it just a convention?

Thanks for your replies.

**Comment by githubsaturn** [comment]
Docker caches build layers. Let's say you have
```
FROM node # layer 1
COPY package.json . # layer 2
RUN npm install # layer 3
COPY ./src . # layer 4
```

If you make a change in your own code (layer 4) and redeploy the app, Docker uses cached layer 1 and 2 and 3. And only rebuilds layer 4.

If you make a change in your package.json file, Docker rebuilds, layer 2, 3 and 4. And only uses cached version of layer 1. 

It's more likely for your source code to change. Therefore you copy your source code at the last step to take advantage of caching.
