### ISSUE TITLE
[Deployment Issue] Verification failed 1107

### ISSUE THREAD

**Issue by tim-hub** [caprover/caprover#600]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Cannot veirify the domain.

If applicable, content of `captain-definition` file:

none

Steps to reproduce the problem:

simply follow the tutorial

Answers to the following questions where applicable:
- Your OS and version?
- RAM?
ubuntu 18.04 x86
2G ram

## log in docker service
```
February 20th 2020, 7:55:03.915 pm    Error: Verification Failed.
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    | Error: Verification Failed.
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:88:43)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Request.emit (events.js:189:13)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at ClientRequest.emit (events.js:189:13)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Socket.socketErrorListener (_http_client.js:392:9)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Socket.emit (events.js:189:13)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at emitErrorNT (internal/streams/destroy.js:82:8)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    | POST /api/v2/user/system/changerootdomain 200 20032.204 ms - 62
```

## log in client
```
Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.

Error Code: 1107  Message: Verification Failed.
```

the domain is name can be pinged through local machine, and prrety sure the DNS is set correctly.

**Comment by tim-hub** [comment]
can the `stm.mydomain.com` can be visited and see the caprover ui

**Comment by githubsaturn** [comment]
@tim-hub  

1) Have you done a wildcard domain setup? If your domain is domain.com, have you setup *.domain.com to point to CapRover server, or *.something.domain.com? 

2) There is a line that is omitted from the output you copied:

```February 20th 2020, 7:55:03.915 pm    Error: Verification Failed.
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    | Error: Verification Failed.
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:88:43)
```

The line should be `Sending request to http://something.other.com/.well-known/captain-identifier`. Please include this line.

**Comment by tim-hub** [comment]
> @tim-hub
> 
>     1. Have you done a wildcard domain setup? If your domain is domain.com, have you setup *.domain.com to point to CapRover server, or *.something.domain.com?
> 
>     2. There is a line that is omitted from the output you copied:
> 
> 
> ```
> captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    | Error: Verification Failed.
> captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
> captain-captain.1.j35hjr5gnb8b@ip-10-0-1-88    |     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:88:43)
> ```
> 
> The line should be `Sending request to http://something.other.com/.well-known/captain-identifier`. Please include this line.

it is `*.something.domain.com`

`Sending request to http://something.other.com/.well-known/captain-identifier` I forgot to include this line, but I tried to visit it through browser, I can get the identity file, this really confused me.

it should not be different between visit it through browser or cli?

**Comment by githubsaturn** [comment]
The only difference is that the verification is done from inside a container. It is a smooth process unless you have an unusual IP table on your OS. 

Last resort, if you are sure that the domain is indeed mapped correctly, but yet it fails to be verified, you can turn off that check by setting `skipVerifyingDomains` to `true`. Simply do this:
```
touch /captain/data/config-override.json
nano /captain/data/config-override.json
# enter this: 
# {"skipVerifyingDomains":"true"}
# ctrl+x to close the file and save
docker service update captain-captain --force
```
This will disable the extra verification that CapRover runs.

**Comment by tim-hub** [comment]
> The only difference is that the verification is done from inside a container. It is a smooth process unless you have an unusual IP table on your OS.
> 
> Last resort, if you are sure that the domain is indeed mapped correctly, but yet it fails to be verified, you can turn off that check by setting `skipVerifyingDomains` to `true`. Simply do this:
> 
> ```
> touch /captain/data/config-override.json
> nano /captain/data/config-override.json
> # enter this: 
> # {"skipVerifyingDomains":"true"}
> # ctrl+x to close the file and save
> docker service update captain-captain --force
> ```
> 
> This will disable the extra verification that CapRover runs.

thanks,
I will try.

I am not 100% sure, because I am using cloudflare for the CDN, I remembered before there is some error when renew let's encrypt certification, I have to turn some thing off to make it works.

I disabled the proxy and cloduflare ssl, maybe more stuff to disable?

I am not sure. do you hear about similar issued related to CDN or SSL for caprover set up?

**Comment by tim-hub** [comment]
thanks so much, I skip the verification, and deployed my first sample app, looks so good @githubsaturn
