### ISSUE TITLE
Deployment of a Meteor App

### ISSUE THREAD

**Issue by al222** [caprover/caprover#601]
Hi, It's less an issue than a question, sorry...
I am not very clear about the simplest way to deploy a Meteor App with CapRover, except creating a Node server and using it as any other Nodes server there is.
Can you point me to the right direction?
In advance thank you very much.

**Comment by githubsaturn** [comment]
Take a look at this: https://github.com/githubsaturn/meteor-captainduckduck

If you need more detailed help, try StackOverflow or search for **Meteor Docker**


CapRover deployments are done via Docker.
