### ISSUE TITLE
Allow Docker timestamps to be disabled

### ISSUE THREAD

**Issue by OmgImAlexis** [caprover/caprover#602]
Currently this value is hardcoded meaning if your app also logs a timestamp you end up with something like this. If I disable my own logger's timestamp I'm still stuck with the Docker one as it can't be overridden.

```
2020-02-25T04:17:30.118464903Z Tue, 25 Feb 2020 04:17:30 GMT vault:server Listening on port 80
```

https://github.com/caprover/caprover/blob/de54d34f3a214a7f5fc34f19614d83c8f5cf80a4/src/docker/DockerApi.ts#L1555

**Comment by githubsaturn** [comment]
Added to configs that can be [overridden](https://caprover.com/docs/troubleshooting.html#customize-config-settings)

Will be part of the next release.
