### ISSUE TITLE
unable to attach new node 

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#603]
I'm having the exact same problem as #264 ...
in 264 there is no solution mentioned... please help.

**Comment by githubsaturn** [comment]
This seems to be an SSH issue, not a CapRover issue. To confirm, are you able to SSH into your second box from the first box?

CapRover IP address is the address of your main node.
New node IP address is the address of your new node.
SSH private key is the one that starts with `-----BEGIN RSA PRIVATE KEY----`

Make sure your SSH port 22 is open **on your second node**


Can you please confirm?

**Comment by r-chris** [comment]
As I noticed quite a few people ran into this issue, I updated the documentation (Ref: https://github.com/caprover/caprover-website/pull/32)
