### ISSUE TITLE
Serverless Functionality

### ISSUE THREAD

**Issue by wbrawner** [caprover/caprover#604]
**Is your feature request related to a problem? Please describe.**
Some of the apps I'm running take a lot of resources but I don't need them running 24/7. 

**Describe the solution you'd like**
Much like Heroku's free plan, it would be nice to have a setting to allow certain apps to be shut off after a defined period of inactivity and then automatically turned back up to 1 instance once they're accessed.

**Describe alternatives you've considered**
I installed iron-io/iron-functions to achieve similar functionality within caprover, but the authentication isn't quite what I had hoped for. I would like to have something more like Caprover where the access to create new functions is restricted to admin users while the access to use them can still be open.

**Comment by githubsaturn** [comment]
While I understand the use-case here, this is totally out of scope of CapRover. Heroku provides such a functionality by intercepting the HTTP requests and keeps a LRU cache of the apps. Introducing such system is its own project and doesn't fit within CapRover scope. 

Serverless functionality is however is achievable via many open source solutions. I recommend looking into https://github.com/openfaas/faas

**Comment by prabirshrestha** [comment]
Another simple and lightweight one is this. https://github.com/metrue/fx

Might be having one click templates for these would be useful given serverless is very popular.
