### ISSUE TITLE
Workaround for managing an app which deployed out of captain

### ISSUE THREAD

**Issue by bgervan** [caprover/caprover#605]
**Is your feature request related to a problem? Please describe.**
If there is a really complicated app, which has many services, and installable only via script.

**Describe the solution you'd like**
I would like a way of add and manage apps. Like portainer list all running containers etc. 

**Additional context**
I ran into this, when I tried to deploy openfaas. 

Is there any solution or workaround for this?

**Comment by githubsaturn** [comment]
You answered yourself :) potrainer is the best solution. It's available as a one click app on CapRover.

**Comment by bgervan** [comment]
And what if I want to generate certs, add url-s for that services inside captain?

**Comment by githubsaturn** [comment]
Then you have to create apps within CapRover. 

Another option is to just create an http forwarder inside CapRover that manages the domain and ssl and it'll forward the request to another container which is created outside of CapRover. 

Look into nginx reverse proxy one-click app.

**Comment by bgervan** [comment]
Thanks :)
