### ISSUE TITLE
[Deployment Issue] Server has two public IPs, Could not launch caprover container (Fresh installation)

### ISSUE THREAD

**Issue by locvfx** [caprover/caprover#610]
What is the problem?
I performed fresh installation on a new VPS (has two public IPs), failed to launch caprover container 
Error: Could not find Public IP

Steps to reproduce the problem:
It was fine on a VPS with single public IP. I purchased another VPS with two public IPs, failed to setup caprover

Answers to the following questions if applicable:
- Your OS and version? Centos 7
- RAM? 8GB

Error log:
![caprover-error](https://user-images.githubusercontent.com/884997/75967217-77a58480-5f06-11ea-8bb2-5b22bbb35308.JPG)

**Comment by githubsaturn** [comment]
1) Who do you use for your VPS provider?
2) What command did you use to install CapRover. You seem to be trying to install CLI on your server! CLI is meant to be used on your local machine.

**Comment by locvfx** [comment]
> 1. Who do you use for your VPS provider?
> 2. What command did you use to install CapRover. You seem to be trying to install CLI on your server! CLI is meant to be used on your local machine.

1. https://servarica.com
2. Here are steps I installed Caprover
```
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=2376/tcp;
firewall-cmd --permanent --add-port=2377/tcp;
firewall-cmd --permanent --add-port=7946/tcp;
firewall-cmd --permanent --add-port=7946/tcp;
firewall-cmd --permanent --add-port=4789/tcp;
firewall-cmd --permanent --add-port=996/tcp;
firewall-cmd --permanent --add-port=7946/udp;
firewall-cmd --permanent --add-port=4789/udp;
firewall-cmd --permanent --add-port=2377/udp;
firewall-cmd --permanent --add-port=9000/tcp
firewall-cmd --permanent --add-port=3000/tcp
firewall-cmd --reload
yum install npm -y
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
npm install -g caprover
caprover serversetup
```
Failed at docker run 

But I did successfully setup Caprover when only one primary IP attached to the server. But if there are two IPs address attached, docker can't connect to the outer world. 
**Error: Couldn't find your IP**

**Comment by githubsaturn** [comment]
Yes, two public IP on a single CapRover instance is definitely not something that we designed for and might cause problems. 

Having said that, you can add the following environmental variable to docker run command to enforce a particular IP:
MAIN_NODE_IP_ADDRESS


PS: unrelated to the problem: your installation script is incorrect. You shouldn't install npm CapRover on the server! It should be on your local machine. Please follow the official guide.
