### ISSUE TITLE
No logs showing at present

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#612]
I'm 99.95% sure this is nothing to do with CapRover, but at present there is nothing showing in the App Logs panel of the Deployment tab, for any app.  And running `docker service logs srv-captain--myapp` on the command line shows nothing too.  Any ideas?  This open issue seems relevant: https://github.com/moby/moby/issues/33183

**Comment by githubsaturn** [comment]
"Usually" the swarm manager is the culprit and a reboot will fix the issue.

Service logs are unfortunately not 100% reliable. We've seen instances where the service log API (the one CapRover uses on the dashboard) returns nothing, but `docker service logs` command does! It's quite inconsistent across the board.

The only pseudo-solution that might work is system reboot.

**Comment by githubsaturn** [comment]
Maybe try this solution: https://github.com/moby/moby/issues/33183#issuecomment-374690565

**Comment by drmrbrewer** [comment]
Thanks for the suggestion, but still nothing :(  maybe reboot is the next step... hopefully all the services come back up!

**Comment by drmrbrewer** [comment]
Just FYI a restart worked, and all services came back up.  I'm curious to know how this restart resiliency is achieved.  It happened again since (server was going mental) and sure enough everything came back up fine without intervention, including CapRover.

**Comment by githubsaturn** [comment]
It's a feature of docker swarm. Any Docker swarm service is automatically started again after a restart by docker swarm engine.
