### ISSUE TITLE
Setting non-existent path breaks app

### ISSUE THREAD

**Issue by hjyoung1** [caprover/caprover#614]
What is the problem?

Setting non-existent path for persistent directory breaks app.

If applicable, content of `captain-definition` file:

Happens with all app (default too) 

Steps to reproduce the problem:

Create new app with "has persistent data" ticked. 
Open app details goto app configs add new persistent directory. 
Click on "set specific host path" 
Now add any non-existent path in host 
Eg. 
Path in app = /data 
Path on host = /notavailabledirectory
Save. 
Now try check log it's blank. Check app in docker it's showing exited. Deploying anything doesn't work now. 

Answers to the following questions where applicable:
- Your OS and version? 
Ubuntu 18.04.
Docker version :- 19.03.6,
CapRover tried stable and edge. 
- RAM?
2gb

**Comment by githubsaturn** [comment]
This is expected behavior. You cannot set a non existent path on a docker service. 

There's even a popup when you hover over the input for the specific path on host about this requirement.

**Comment by githubsaturn** [comment]
No - CapRover passes this information to Docker. 

CapRover itself is running inside a container and have no knowledge of whether a directory exists on the host or not.
