### ISSUE TITLE
Add "Deploy from github" feature

### ISSUE THREAD

**Issue by prabirshrestha** [caprover/caprover#615]
I was playing with [rio](https://github.com/rancher/rio) which is similar to caprover but for kubernetes.  

One feature I missed from rio was how easy it was to get started with a github repo including private repos i.e. `rio run -n cd-demo -p 8080 https://github.com/rancher/rio-demo`

![image](https://user-images.githubusercontent.com/287744/76167499-55894d80-6124-11ea-8330-3092b7d16d38.png)

I would love to have a "Deploy from github" button which in the above screenshot which does the following. Rio seems to be using github personal access token which has access to repros and webhooks. Currently filing in this is quite complicated.

![image](https://user-images.githubusercontent.com/287744/76167621-350dc300-6125-11ea-8e14-cae96cc57e35.png)

It also has concept of `Riofile` which is similar to captain definition. https://github.com/rancher/rio/blob/master/docs/riofile.md. It will be good if CaptainDefinition could be exteneded to fill out all caprover.

```json
{
	"schemaVersion": 2,
	"dockerfilePath": "./Dockerfile",
	"containerHttpPort": "80",
	"forceHttpsRedirect": true,
	"websocketSupport: true,
	"instanceCount": 1
}
```

Also if captain-definition doesn't exist would be good if it just default to `Dockerfile` similar to rio.

**Comment by githubsaturn** [comment]
If you're talking about integrating github APIs and automatically fetching your repos and etc, we won't be doing that as it won't be maintainable.

On the other hand, if you are referring to a handy way to create apps and setup config values through command like, it's already doable via `caprover api` [command](https://github.com/caprover/caprover-cli#api). Using the raw API, you can create apps, setup config variables and etc. You can chain a few command together in a simple bash script to achieve what you're looking for.
