### ISSUE TITLE
secret management

### ISSUE THREAD

**Issue by prabirshrestha** [caprover/caprover#616]
Currently if I'm running some apps or db that requires secret I need to use the environment variable which is in plain text and comes back to the client in the caprover dashboard.

Would it be possible to have some sort of secret management in caprover?

![image](https://user-images.githubusercontent.com/287744/76167941-b9f9dc00-6127-11ea-9d67-cb0d8d96c0d9.png)

Here are few options I can think of.

1. Roll your own simple secret management. 
2. Use well known existing secret manager such as [Terraform vault](https://www.vaultproject.io/). This could be first class similar to how netdata is currently used.

If you are going with 1. another option would be to make the apis similar to Terraform's Vault so you only implement basic http endpoints to get and set the values. https://www.vaultproject.io/api-docs/. If the user wants to have a full blown vault manager they can then use Terraform Vault and change the vault url to point to their docker instance of Terraform vault in caprover settings. Then for environment variable section you could have "from vault" checkbox. Also note that vault might contain json or binaries such as ssl certs and keys, ssh pub/private key and so on instead of just plain text.

To get secret it would be. 

```
curl \
    -H "X-Vault-Token: f3b09679-3001-009d-2b80-9c306ab81aa6" \
    -X GET \
    http://127.0.0.1:8200/v1/secret/foo
```

To list secrets it would be.

```
curl \
    -H "X-Vault-Token: f3b09679-3001-009d-2b80-9c306ab81aa6" \
    -X LIST \
    http://127.0.0.1:8200/v1/secret/
```

To write secret it would be

```
 curl \
    -H "X-Vault-Token: f3b09679-3001-009d-2b80-9c306ab81aa6" \
    -H "Content-Type: application/json" \
    -X POST \
    -d '{"value":"bar"}' \
    http://127.0.0.1:8200/v1/secret/baz
```

If possible I would also like to have some sort of created and expiration date so I can frequently rotate my secrets.

**Comment by prabirshrestha** [comment]
Another option is to use Docker swarm secrets. https://docs.docker.com/engine/swarm/secrets/

**Comment by githubsaturn** [comment]
Environmental variables are an acceptable way of configuring your auth keys, even enterprise solutions like Heroku use environmental variables. But I agree, they are not the highest security level.

But if you really need to take the next step and use high-level security, Docker swarm offers Docker secrets (as you found it as well). While there is no UI on CapRover for secrets (they are seldom used), you can use predeploy function to use them:
```
var preDeployFunction = function (captainAppObj, dockerUpdateObject) {
    return Promise.resolve()
        .then(function(){

            dockerUpdateObject.TaskTemplate.ContainerSpec.Secrets =
                     [{
                            File: {
                                Name: "my-secret-name",
                                UID: '0',
                                GID: '0',
                                Mode: 292
                            },
                            SecretID: "secret-id-from-docker",
                            SecretName: "my-secret-name",
                        }];

            return dockerUpdateObject;
        });
};

```
