### ISSUE TITLE
[Deployment Issue]  How to provide docker run command args

### ISSUE THREAD

**Issue by rizkyramadhan** [caprover/caprover#617]
I am trying to deploy postgresql with ssl. 

After googling I found [this gist](https://gist.github.com/mrw34/c97bb03ea1054afb551886ffc8b63c3b). 

from there, it looks like we have to provide ssl_cert_file and ssl_key_file command args

```
docker run -d --name postgres postgres:12-alpine \
   -c ssl=on \
   -c ssl_cert_file=/var/lib/postgresql/server.crt \
   -c ssl_key_file=/var/lib/postgresql/server.key
```

How to provide run command args in caprover ?

**Comment by githubsaturn** [comment]
All you need is to create a custom Dockerfile:
```
FROM postgres:12-alpine
CMD ["postgres", "-c", "ssl=on", "-c", "ssl_cert_file=/var/lib/postgresql/server.crt", "-c", "ssl_key_file=/var/lib/postgresql/server.key" ]
```
