### ISSUE TITLE
Allow ws timeout to be set

### ISSUE THREAD

**Issue by OmgImAlexis** [caprover/caprover#618]
**Is your feature request related to a problem? Please describe.**
Currently after about 60s all of my idle ws connections get killed.

**Describe the solution you'd like**
A way to either update that value.

**Additional context**
These are the values that need to be added/updated.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout

```
proxy_connect_timeout 7d;
proxy_send_timeout 7d;
proxy_read_timeout 7d;
```

**Comment by githubsaturn** [comment]
Go to your app and click on EDIT NGINX CONFIG, the make modifications if needed.

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/76813809-79f1c380-67cf-11ea-9502-4ad9a3920a61.png)
