### ISSUE TITLE
Run commands from dashboard

### ISSUE THREAD

**Issue by fastengineer** [caprover/caprover#625]
`heroku run bash`
`heroku run rails db:migrate`
`heroku run rails console`

I am using different computers which not my own. So I need this feature exactly. I can not ssh from public computer.

**Comment by githubsaturn** [comment]
This is done intentionally - CapRover api is based on http REST protocol which won't be very effective with running an interactive terminal. 

Also, please note that CapRover goal is to provide a thin layer around Docker and nginx. Additional functionalities can be achieved via different tools, for example, in this case, you can make use of portrainer which is available as a one-click app.
