### ISSUE TITLE
Show container distributing across clusters in dashboard

### ISSUE THREAD

**Issue by fastengineer** [caprover/caprover#626]
I'm confused about selecting cluster for X operation. I want to check logs of container. But I don't know where is it.

**Comment by githubsaturn** [comment]
Can you please provide more info on what you mean by "selecting cluster for X operation" ?

Applications logs can be found here: https://caprover.com/docs/troubleshooting.html#how-to-view-my-applications-log

**Comment by fastengineer** [comment]
X was yesterday
- Deleting cluster
- SSH into container

**Comment by githubsaturn** [comment]
If by "Deleting cluster" you mean deleting a service (which can have multiple replicas), you can do so by navigating to the apps page, and click on the delete button.

If you want to delete your Docker Swarm cluster, simply follow the [uninstall steps](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain)

With regards to SSH to the container, you can simply run:

```
ssh root@123.123.123.123
docker exec -it $(docker ps --filter name=srv-captain--myappname -q) /bin/sh
```
