### ISSUE TITLE
One-click deploy from code repo

### ISSUE THREAD

**Issue by s-kris** [caprover/caprover#628]
Ability to deploy an app from repo using 'deploy from github/gitlab etc..' would be really helpful. 

Example: 
![image](https://user-images.githubusercontent.com/3975305/77039372-cdd0f800-69db-11ea-8d87-7087f5094cbe.png)

**Comment by githubsaturn** [comment]
Duplicate: https://github.com/caprover/caprover/issues/615

TLDR: Integrating with third party proprietary APIs is a huge maintanance cost that we cannot bear at this point. Also, it's already possible to do this via CLI using a simple bash script using `caprover api` that will automate the API calls.

**Comment by s-kris** [comment]
Okay, thank you!
