### ISSUE TITLE
Add new node - Timed out while waiting for handshake

### ISSUE THREAD

**Issue by KonradHolubek** [caprover/caprover#629]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Cannot add new node

1- I added local docker registry
2- I created a new server, with docker installed
3- I created a ssh key on my second server
4- I copied my ssh private key from the second server
5- I disabled all firewall ports for server one and for server 2
6- I added the ip address of server two and ip address of server one
7- I added the ssh key of server two
I get the error : 1000 : SSH Connection error!!. 

Here is the output of my server one log
```
captain-captain.1.ozubrvbjm54y@caprover    | March 20th 2020, 1:37:30.918 pm    Error: Timed out while waiting for handshake
captain-captain.1.ozubrvbjm54y@caprover    | Error: Timed out while waiting for handshake
captain-captain.1.ozubrvbjm54y@caprover    |     at Timeout._onTimeout (/usr/src/app/node_modules/ssh2/lib/client.js:695:19)
captain-captain.1.ozubrvbjm54y@caprover    |     at ontimeout (timers.js:436:11)
captain-captain.1.ozubrvbjm54y@caprover    |     at tryOnTimeout (timers.js:300:5)
captain-captain.1.ozubrvbjm54y@caprover    |     at listOnTimeout (timers.js:263:5)
captain-captain.1.ozubrvbjm54y@caprover    |     at Timer.processTimers (timers.js:223:10)
captain-captain.1.ozubrvbjm54y@caprover    | March 20th 2020, 1:37:30.918 pm    Error: SSH Connection error!!
captain-captain.1.ozubrvbjm54y@caprover    | Error: SSH Connection error!!
captain-captain.1.ozubrvbjm54y@caprover    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)
captain-captain.1.ozubrvbjm54y@caprover    |     at Client.<anonymous> (/usr/src/app/built/docker/DockerUtils.js:20:43)
captain-captain.1.ozubrvbjm54y@caprover    |     at Client.emit (events.js:198:13)
captain-captain.1.ozubrvbjm54y@caprover    |     at Timeout._onTimeout (/usr/src/app/node_modules/ssh2/lib/client.js:697:14)
captain-captain.1.ozubrvbjm54y@caprover    |     at ontimeout (timers.js:436:11)
captain-captain.1.ozubrvbjm54y@caprover    |     at tryOnTimeout (timers.js:300:5)
captain-captain.1.ozubrvbjm54y@caprover    |     at listOnTimeout (timers.js:263:5)
captain-captain.1.ozubrvbjm54y@caprover    |     at Timer.processTimers (timers.js:223:10)
captain-captain.1.ozubrvbjm54y@caprover    | POST /api/v2/user/system/nodes 200 20007.233 ms - 64
```
Please advise

**Comment by githubsaturn** [comment]
This is an SSH issue. Usually the problem is firewall, but you mentioned that you have disabled the firewall.

Can you try to see if you have access to the second server?

- SSH to server A
- While on server A, run this command:
```
nc -zvw3 <IP_ADDRESS_OF_SERVER_B> 22
```

I assume your SSH port isn't customized, and it's at default 22?

**Comment by KonradHolubek** [comment]
The result : 
Connection to <IP> 22 port [tcp/ssh] succeeded!

**Comment by githubsaturn** [comment]
Okay, I think you may have problems with your SSH key setup. How do you SSH to server B? Don't you already have a public key and private key?

**Comment by KonradHolubek** [comment]
Indeed, I was not adding the public key to the other server. So, in summary, this is what I did
1-created ssh private on server A (Main node)
2-copied ssh public key of server A
3- added ssh public key of server A to server B
4-added ssh private key of server A to caprover configuration (**is this correct because [here](https://caprover.com/docs/app-scaling-and-cluster.html) it is written the opposite ?!**)
5-entered the IP of server A and server B to caprover configuration
and it worked !

---
Now, I have a second question/issue : I'm new to clusters and nodes. By adding a server B/worker, I was hoping to solve my disk space issue. Indeed, I am trying to install an app from a docker image, and I am still getting the following error during deploy: 
`Build started for redash
An explicit image name was provided (redash/redash). Therefore, no build process is needed.
Pulling this image: redash/redash This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
[truncated] 

failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/python2.7/site-packages/clidriver/lib/icc/libgsk8cms_64.so: no space left on device
`

**Comment by githubsaturn** [comment]
There are certain things that will happen on the main node. Image building is one of them. Therefore, adding a new node won't help with the disk space related to the image.

However, adding new node does help with disk space, if the disk is being consumed by a volume.

But in general, it's much more manageable to increase the disk space on your main node. You only need a second node if you cannot scale your main node vertically anymore.

Hope this explains the situation. Let me know if there is still any unclear

**Comment by r-chris** [comment]
I ran into the same issue and updated the documentation slightly. The PR is here: https://github.com/caprover/caprover-website/pull/32
