### ISSUE TITLE
gRPC support?

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover#631]
Nginx introduced support for gRPC back in 2018 - https://www.nginx.com/blog/nginx-1-13-10-grpc/
However it involves doing some things manually in the config.
I was wondering if it is possible to make gRPC apps easily deployable on caprover.

**Comment by githubsaturn** [comment]
It won't be coming to the UI as this is a very special usage of nginx. However, there is always a possibility for the users to manually customize the config.

**Comment by valensto** [comment]
@fr3fou do you have tips to manually change the config ?
