### ISSUE TITLE
Suddenly unable to read logs

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#636]
What is the problem?
*all* of my projects are unable to read from the logs.

Steps to reproduce the problem:
#/apps/details/ shows the following in each app (same hash and everything)
```
Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node ju07ert0pqwz8btbt3zv8ksqx is not available
```
This is a long-standing install of caprover, unsure how long this has been going on... but i was the target of a brute force attack, so its possible some log file somewhere is bloated.

**Comment by githubsaturn** [comment]
Unfortunately, this is an existing issue with docker. Many factors can cause this problem, for example see this one:
https://github.com/moby/moby/issues/35011

If you search within Docker repository, there are numerous cases like this. Unfortunately Docker maintainers haven't fixed this issue yet. 


Usually a reboot resolves the problem. Other than that, it's pretty out of our hand to create a fix for this.

**Comment by derek-adair** [comment]
Yup! reboot fixed it. Thanks dude.

**Comment by borjarobert** [comment]
Just in case anyone stumbles with the same problem, in the link provided by @githubsaturn they speak of a fix.
Running `docker swarm ca --rotate` on the manager node makes the logs available again.
I personally run it daily with cron.
