### ISSUE TITLE
idea: one-click-app definition file variable that autogenerates a random string

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#637]
# Problem

It would be cool to allow users to deploy one-click-apps without having to manually specify some long random string for the database secret.

# Solution

A special `$$cap_random_<len>` that gets replaced with a `<len>` chars random string (probably a-z0-9 is fine) in a one-click-app definition file (random per instantiation, not deploy).  For safety, len should probably work below 20.

Then I could use these as default values in thigns like `$$cap_pg_pass`, for example.

**Comment by githubsaturn** [comment]
Implemented as `$$cap_gen_random_hex(length)` and will be available in the next release
