### ISSUE TITLE
Mongo connection issues

### ISSUE THREAD

**Issue by clementvp** [caprover/caprover#638]
Hello, noob question, but i can't connect my node JS app (with mongoose) and my mongo db.
Documentation are very quiet, and the example at the mongo installation end is buggy and outdated.

So, i have a mongo one-click app installed:

MONGO_INITDB_ROOT_USERNAME : root
MONGO_INITDB_ROOT_PASSWORD : 123456

"Your app is internally available as srv-captain--mongo to other Captain apps."

Ok so my mongoose connect url is:

mongodb://srv-captain--mongo/mydatabase?authSource=admin

My app is an express app, mongoose can connect BUT i have errors during mongoose calls:

command find requires authentication
command insert requires authentication

If i try this connection url :

mongodb://root:123456@srv-captain--mongo/mydatabase?authSource=admin

My app can't connect to my mongo container.

What i need to do ?

(Sorry for my english, not my first language)

**Comment by clementvp** [comment]
Ok so... i'm SO stupid ! 
The tag for the mongo was an old one, Try with latest work like a charm.

mongodb://root:123456@srv-captain--mongo/mydatabase?authSource=admin

Is the right url. I'm closing this.
Sorry again.

Long live caprover.

**Comment by a6un** [comment]
Hi All, when connecting nodejs app to mongo, it is throwing error message like " MongooseServerSelectionError: getaddrinfo ENOTFOUND srv-captain--prod-db srv-captain--prod-db:27017".

MONGO_INITDB_ROOT_USERNAME : root
MONGO_INITDB_ROOT_PASSWORD : 123456

Connection URL: **mongodb://root:123456@srv-captain--mongo/mydatabase?authSource=admin**

can anyone help me to fix this issue?

**Comment by clementvp** [comment]
@a6un did you tried to get the latest version of mongo ?
In the field MongoDB Version during the installation  try to enter the latest version of the docker image. 
https://hub.docker.com/_/mongo?tab=tags

**Comment by a6un** [comment]
@clementvp  I resolved this issue. Some commands are missed in node js. Now it is working. Thanks for your valuable time.

**Comment by hugoblanc** [comment]
In my case using v 5.0 of mongo docker image cause the ENOTFOUND error. 
I finally used v4.4 and suddendly it works
