### ISSUE TITLE
Context in captain-defintion

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#639]
**Is your feature request related to a problem? Please describe.**
I would like to structure my directory like so...

./
./ops/Dockerfile
./ops/captain-definition
./src/mycode

**Describe the solution you'd like**
in docker-compose we can set build paranters:
```
build:
  context: ./src/
  dockerfile: ./ops/Dockerfile
```

**Comment by githubsaturn** [comment]
You can already do this. Place your captain-definition in `./ops/captain-definition` and set the `captain-definition` location in your apps settings, DEPLOYMENT tab.

![image](https://user-images.githubusercontent.com/10582082/77858277-7c411e00-71d0-11ea-8035-c6eb2fa6656d.png)


Then, use this content for your captain-definition:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./ops/Dockerfile"
 }
```

**Comment by derek-adair** [comment]
oh shit! thanks.  I feel like every request i have is already hidden somewhere :P
