### ISSUE TITLE
Single Page App Design - can't figure out how to access my api via https on subdomain

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#640]
I have a noob question on how I might achieve a single page app deployment, and grant it access to my api (preferably via subdomain).

## Setup
Two caprover apps:
1. myapp.com -> single page app served w/ static [nginx conf](https://github.com/derek-adair/django-redux/blob/master/ui/vhosts.conf)
2. api.myapp.com -> small django api (currently just the development server)

## The Problem
1. accessing https://myapp.com works
2. accessing https//api.myapp.com works
3. accessing https://api.myapp.com from https://myapp.com via ajax fails differently depending on browser:
   - Chrome:  `net::ERR_CERT_AUTHORITY_INVALID`
   - Firefox: `An error occurred:: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT` (also complains about cors)
   - Edge: `Network Error` - still shows 200 success status oddly.

-----------

1. Should i be somehow proxying requests via srv-captain--MY-APP?
2. Is this an app level nginx config issue?
3. Do i somehow share certs between apps?
4. Is this just not caprover related at all?

**Comment by derek-adair** [comment]
Also not sure if this should be a deployment issue tag

**Comment by githubsaturn** [comment]
CapRover uses self signed certs if you try to access a "non-registered domain" that points to CapRover. For example https://asdfjahsfdjhalsjfdh.root.domain.com will result in the self signed cert error. 

My guess is that you have a typo in your your ajax call and you're not really calling the right URL. Double check this and make sure it's correct. If it is, then it's weird! Next step, connect your apit.myapp.com to another random domain like `api.anotherdomain.com` and retry your experiment. Does this work?

**Comment by derek-adair** [comment]
I dont wanna talk about this ever again.

**Comment by derek-adair** [comment]
Also thanks for taking the time to look at my ridiculous problems.  (it was a url typo)
