### ISSUE TITLE
cannot cancel building process of images

### ISSUE THREAD

**Issue by bahadirh** [caprover/caprover#641]
I have a simple app with GitHub integration where the app is built by using the Dockerfile within the repo. I accidentally changed the last line of the Dockerfile to `RUN` command, instead of `CMD`, and the build step couldn't finish. 

The issue is, I couldn't find any way to stop that build process and deploy another newer version of the app. It kept saying 'A build is in progress.' and I couldn't even delete the app because of that, so I was stuck with an app trying to build a buggy Docker image.

The Dockerfile:
```dockerfile
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
RUN python manage.py runserver 0.0.0.0:8000
```

I've Portainer deployed with Caprover as well and found a container named as one of those Docker's default names. I thought it should be the one where the build was undertaken and it was. I force-stopped it and the build stopped. I assume that Caprover is capable of detecting whether the container building the image to deploy is still running, but there isn't a way to stop that container from the interface, but sometimes that might be required.

My suggestion is that a timeout might be added to the build process and after that, Caprover itself stops the container building the app image. Adding a button to cancel the build might be even better.

**Comment by githubsaturn** [comment]
You can simply cancel the build by restarting the service. `docker service update captain-captain --force`

Timeout isn't really an option as there are builds that take up to 30min-1hr.

**Comment by Boscop** [comment]
@githubsaturn I did `docker service update captain-captain --force` to cancel a build.
Now how can I clean up the build artifacts that the unfinished build left behind?

**Comment by githubsaturn** [comment]
If it's a lingering build artifact, docker takes care of the clean up. For old images:
* Login to CapRover
* Navigate to settings
* Scroll down to "Disk Cleanup" section and clean up the disk
