### ISSUE TITLE
Ability to disable default app domain if custom domain added

### ISSUE THREAD

**Issue by AlexxNB** [caprover/caprover#642]
**Problem:**
I have an app on https://myapp.xyz.domain.com, then I decided to add another one domain https://myapp.com. Now webapp will be accessible by both URLs.  But I want, that ONLY https://myapp.com will open my app. 

**Suggestion:**
![изображение](https://user-images.githubusercontent.com/10389013/78142005-fd005400-7434-11ea-8f84-a967f98b90d0.png)

Add checkbox like "Enable access" for each domain and check only needed. Unchecked URL will show 404 error.

Even when there will be only one default domain it is useful for quick disable/enable access by browser.

**Comment by githubsaturn** [comment]
You can have redirect logic in your application to redirect it to any URL you want. The answer is usually, if you don't want a URL, simply don't use it. It's not a security risk, or any other concern. It adds zero real value. Established products, like Heroku or Google's firebase don't have this functionality for disabling the default links neither. It simply has no real value. See this interface for Firebase for example:

![Untitled](https://user-images.githubusercontent.com/10582082/78195162-02699880-744d-11ea-91d0-cb1d177eb3b6.jpg)

**Comment by abartier** [comment]
@AlexxNB I was looking for the same thing. As I didn't want to handle it at the application level I put this in the nginx config (of the app): 

` if ($host !~ ^(good-domain.com|good-domain-2.com)$ ) { return 404; }`

It's in the server block.

**Comment by ideacatlab** [comment]
It's actually make pretty much sense to disable this url because it can hurt you're SEO, as google bots will crawl you links and will find double content on different page. Google bots don't give a damn or they don't ask if maybe this is  a website generated with caprover or firebase, or if firebase have that function. If you build a online store and you will not make the appropriate config to hide or redirect those script will sure affect your canonical URL's.

**Comment by josselinlbe** [comment]
+1 @ideacatlab

**Comment by maietta** [comment]
Another option is to use a domain with a TLD such as .dev or .app. SSL's are required in order for these work and search engines won't ever attempt to index content via http but instead, only ever attempt via https. This means, it will never reach your default endpoints unless you have a wildcard SSL configured for it, which most people won't ever have for their Caprover installations.

What's nice about this solution is there is nothing else to configure than to simply choose an an SSL compulsory domain TLD for Caprover. I took the opportunity to place apps in production under a .app domain and development/testing apps hosted under a .dev domain to make things a bit easier to organize.

Just an idea, in case anyone might be setting up Caprover for the first time or decides to change things up a bit.

**Comment by jus3q** [comment]
@maietta Will I be able to access my apps on my .dev domain over http?  For example I setup an app at new-app.my-domain.dev  From my cap-rover dashboard can I go to open the app link which only has been setup with http.  Will I be able to see the app or will the .dev TLD prevent the connection?

**Comment by maietta** [comment]
Hi @jus3q.

The .dev TLD, just like some other top level domains like .app do require an SSL before the browser will access the content.

When setting up Caprover, yo will be issued a self-signed SSL which isn't trusted by the browsers but it will let you access the user interface so you can begin tinkering around with things.

See https://blog.nameshield.com/blog/2018/04/19/google-makes-https-hsts-encryption-mandatory-for-its-45-new-tlds/

**Comment by ideacatlab** [comment]
You should redirect other domain than the desire to 404, You can use placing this in the server block of the nginx config. |

server {
    if ($host !~ ^(domain.com)$ ) {
        return 404;
       }

**Comment by darrylmorley** [comment]
> @AlexxNB I was looking for the same thing. As I didn't want to handle it at the application level I put this in the nginx config (of the app):
> 
> ` if ($host !~ ^(good-domain.com|good-domain-2.com)$ ) { return 404; }`
> 
> It's in the server block.

I'm not getting a 404 when using this rule, although I should?
