### ISSUE TITLE
Firefox web socket 

### ISSUE THREAD

**Issue by clementvp** [caprover/caprover#643]
I'm using the Hasura one click app (a graphql server), with graphql subscription (over websocket).

The websocket support is enable on the dashboard app.

I'm able to perform subscriptions (with appol-graphql) with Chrome and everything works like a charm.
BUT in Firefox the browser console say it can't establish a connexion at the ws adress.

I try installing just a fresh hasura on a digital ocean droplet and everything work out of the box (both on chrome and firefox). But when i install Hasura on a Caprover instance (tried on 3 dedicated server), everytime i ran into this weird behavior with subscriptions.

I repeat myself the websocket support is enable on the app dashboard.

Maybe a Nginx configuration to add ? (I'm noob with nginx). A bug in Firefox ?

**Comment by githubsaturn** [comment]
CapRover uses simple websocket config on nginx:
https://github.com/caprover/caprover/blob/cbf8a39d87a4c6bbe86e6f849c57a367b5dd642a/template/server-block-conf.ejs#L85-L93

The issue that you're experiencing is not related to CapRover, it's either related to Hasura or nginx. I suggest posting this question on Hasura's github issues, or StackOverflow - you will definitely get a right answer. I suggest you also post the snippet above which shows the nginx configuration that you're using.
