### ISSUE TITLE
[Deployment Issue] How to resolve EXPOSE 3000 defined app on github

### ISSUE THREAD

**Issue by ckc** [caprover/caprover#644]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

I understand this most related docker, lots of app (especially NodeJS) defined 3000 port, so I hope to know how smoothly Deploy from Github?

--------------------------------------------------------------------------

What is the problem?

For example, I want to deploy this app [outline](https://github.com/outline/outline)
It's defined `EXPOSE 3000` 
I deploy success, but I found 3000 was used globally by CapRover; 
Then I found nginx 500 error

May I know is there any pre-config or overwrite after the deployment to prevent this conflict?
Only fork the the repo for myself?

Easier made whole nginx down, it is a pain point to me. I need back and forth to do [this](https://caprover.com/docs/troubleshooting.html#ive-made-a-change-to-the-nginx-config-that-broke-the-admin-ui)

I am confuse with should I change **Container HTTP Port** or use **Port Mapping**

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1. Create A New App from dashboard
2. Method 3 Deploy from Github of Deployment tab, then **save and update**
3. **Force Build** success

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 1804
- RAM? 1GB

Build log
```

------------------------- Sun Apr 05 2020 09:08:35 GMT+0000 (Coordinated Universal Time)
Build started for outline
Step 1/11 : FROM node:12-alpine

---> f77abbe89ac1
Step 2/11 : ENV PATH /opt/outline/node_modules/.bin:/opt/node_modules/.bin:$PATH

---> Using cache
---> 39994deb94ab
Step 3/11 : ENV NODE_PATH /opt/outline/node_modules:/opt/node_modules

---> Using cache
---> 886349b27b95
Step 4/11 : ENV APP_PATH /opt/outline

---> Using cache
---> 6e27769564fe
Step 5/11 : RUN mkdir -p $APP_PATH

---> Using cache
---> 6f4f2fcaf507
Step 6/11 : WORKDIR $APP_PATH

---> Using cache
---> b5c0f3efa0c2
Step 7/11 : COPY . $APP_PATH

---> 534cc2b18a98
Step 8/11 : RUN yarn install --pure-lockfile

---> Running in 9d8c899c1052
yarn install v1.22.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "rich-markdown-editor > @domoinc/slate-edit-table@0.22.2" has incorrect peer dependency "slate@^0.44.6".

warning "rich-markdown-editor > @tommoor/slate-edit-list@0.19.0-0" has incorrect peer dependency "slate@^0.40.0".

warning "rich-markdown-editor > @wikifactory/slate-edit-blockquote@0.7.1" has incorrect peer dependency "slate@^0.44.9".

warning "rich-markdown-editor > @wikifactory/slate-edit-code@0.16.0" has incorrect peer dependency "slate@^0.44.9".

warning "rich-markdown-editor > @wikifactory/slate-trailing-block@0.6.0" has incorrect peer dependency "slate@^0.44.9".

warning "rich-markdown-editor > golery-slate-prism@0.6.0-golery.2" has incorrect peer dependency "slate@^0.44.6".

warning "rich-markdown-editor > react-medium-image-zoom@3.1.2" has unmet peer dependency "prop-types@^15.5.8".

warning "rich-markdown-editor > slate-instant-replace@0.1.14" has incorrect peer dependency "slate@^0.44.6".

warning "rich-markdown-editor > slate-react > slate-plain-serializer@0.7.10" has incorrect peer dependency "slate@>=0.46.0".

[5/5] Building fresh packages...
Done in 49.12s.
Removing intermediate container 9d8c899c1052
---> fa220d4526f5
Step 9/11 : RUN cp -r /opt/outline/node_modules /opt/node_modules

---> Running in 4fe43434a903
Removing intermediate container 4fe43434a903
---> 6b51b70c7d0a
Step 10/11 : CMD yarn build && yarn start

---> Running in 3ecbe8c41914
Removing intermediate container 3ecbe8c41914
---> f31ba6a64b57
Step 11/11 : EXPOSE 3000

---> Running in 0425104ffdc6
Removing intermediate container 0425104ffdc6
---> c0518b78a6a2
Successfully built c0518b78a6a2
Successfully tagged img-captain-outline:latest
Build has finished successfully!

```

**Comment by githubsaturn** [comment]
The fact that `EXPOSE 3000` is in the Dockerfile, doesn't mean that you'll face a conflict. You can have many apps in different containers that run on port 3000. To route to different apps, you can either let nginx handle that, or you can map different ports of host. For example

```
Host Port 4001 ===> App1 Port 3000
```
```
Host Port 4002 ===> App2 Port 3000
```
```
app3.root.domain.com ===> App3 Port 3000 (Set Container HTTP Port in HTTP Settings to 3000)
```


With regards to the problem you're seeing with OUTLINE, I think the problem lies somewhere else. perhaps the [environmental variables](https://github.com/outline/outline/blob/master/.env.sample)? They need connection path to s3, postgres and redis... 


Hope this answers your question. Let me know if you still have questions.

**Comment by ckc** [comment]
> The fact that `EXPOSE 3000` is in the Dockerfile, **doesn't mean that you'll face a conflict**. You can have many apps in different containers that run on port 3000. To route to different apps, you can either let nginx handle that, or you can map different ports of host. For example
> 
> ```
> Host Port 4001 ===> App1 Port 3000
> ```
> 
> ```
> Host Port 4002 ===> App2 Port 3000
> ```
> 
> ```
> app3.root.domain.com ===> App3 Port 3000 (Set Container HTTP Port in HTTP Settings to 3000)
> ```
> 
> With regards to the problem you're seeing with OUTLINE, I think the problem lies somewhere else. perhaps the [environmental variables](https://github.com/outline/outline/blob/master/.env.sample)? They need connection path to s3, postgres and redis...
> 
> Hope this answers your question. Let me know if you still have questions.

Just found most likely memory isn't enough   
Nginx still made all down, like few years ago I used for web server lol

Thanks your prompt reply and clarified me
AND your good product :)
