### ISSUE TITLE
[Deployment Issue] Problem delivering gzip files from Vue app

### ISSUE THREAD

**Issue by xanxuz** [caprover/caprover#646]
### What is the problem?

I have not been able to enable the delivery of all the gzip files (chunks files, svg. etc) that my vue app generates (I'm using webpack plugin to compress), even if I have placed the variable "gzip_static on" in the app's nginx configuration file in caprover.

I even tried doing the same as you did here #344 

Output of vue-app build
![image](https://user-images.githubusercontent.com/11968584/78807081-8feb4200-7991-11ea-874b-88f0c25e25d5.png)

![image](https://user-images.githubusercontent.com/11968584/78806983-6d592900-7991-11ea-98c9-305bfcaec841.png)

The only file that it gets delivered with content-encoding: gzip it's the index.html file.

![image](https://user-images.githubusercontent.com/11968584/78806686-06d40b00-7991-11ea-9beb-2c0deabb602f.png)

I even tried with a fresh vue project and it happens the same.

### Steps to reproduce the problem:

1- Create vue project with vue cli 3 with basic preset or any other
```bash
vue create vue-app
```

2- Add the compression-webpack-plugin dependency to vue app
```bash
yarn add -D compression-webpack-plugin
```

3-Add a vue.config.js file and configure the webpack plugin to create the gzip of the project files (
I tried putting this plugin thinking that the error could be that the server was not compressing the files): 
```javascript
// vue.config.js file

const CompressionPlugin = require('compression-webpack-plugin')

module.exports = {
  chainWebpack: (config) => {
    config.plugin('CompressionPlugin').use(CompressionPlugin)
  }
}
```

4- Add captain, dockerfile and default config files for the app's deploy

```json
// captain-definition

{
  "schemaVersion": 2,
  "dockerfilePath" :"./Dockerfile"
}
```

```dockerfile
# Dockerfile

# build environment
FROM node:13.7.0-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install @vue/cli -g --silent
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.17.8-alpine
RUN rm -rf /etc/nginx/conf.d
RUN mkdir -p /etc/nginx/conf.d
COPY default.conf /etc/nginx/conf.d/
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

```nginx
server {
  listen 80;
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
```

// Now we will upload the project to caprover through a webhook
5- We create the project in gitlab
6- We upload the local vue project to the gitlab repository

// Now create the app in caprover
7- We add the app vue-app in caprover
8- Enable https
9- Add the repository address, branch and ssl key on **Deployment** tab
10- Save and copy the url to add it in the **Webhooks** section of gitlab
11- We force the build in caprover to deploy the application
12- Add gzip on and gzip_static on to serve the gzip files created in the vue app build (This is done in the default Nginx from the caprover vue-app section)

![image](https://user-images.githubusercontent.com/11968584/78805721-c45dfe80-798f-11ea-8774-27f8a9efcfa0.png)

___

I've tried everything to make it work, it would be a great help if you could take a look at it, I'm almost sure it must be something super obvious 😅

**Comment by githubsaturn** [comment]
Have a look at the architecture of CapRover:
![image](https://user-images.githubusercontent.com/10582082/78844286-576c5800-79d3-11ea-9750-22181351f751.png)

The app you're deploying is also an nginx server. So basically this is your flow:

```
User =====> CapRover nginx (1) ====>>> your nginx (2) ====> Your static content (3)
```

First thing to know is that it doesn't matter if your nginx (2) does gzip processing or not. It also doesn't matter if your static content is gzipped. The only thing that matters in the nginx config used by CapRover (this is where you added `gzip_static on`...)

Secondly, the fact that you have gzip for static content in your CapRover nginx config doesn't make any difference. Try adding `gzip_proxied any;` to the config.

**Comment by valoricDe** [comment]
Hi @githubsaturn, for my understanding (1) just passes everything it get's from let's say port 80 to the outside world. And therefore you need to define `gzip_proxied any;` in (2) so that is also compresses requests coming from (1).

Or is (1) processing everything which comes from (2). And (1) says, ohh it's a proxied request coming from (2) and I have `gzip_proxied any`. Ok guys let him through to the outside world with gzip

**Comment by githubsaturn** [comment]
It's the latter. See nginx documentations for more details: http://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by literakl** [comment]
Accept encoding is missing in a request from your browser .

**Comment by alpharder** [comment]
By default Nginx uses HTTP 1.0 for proxying, also by default it only enables Gzip for HTTP 1.1.

Set these at Caprover nginx template:
```
gzip on;
gzip_proxied any;
proxy_http_version 1.1;
```
