### ISSUE TITLE
CLI during serversetup stops at 'Error: StatusCodeError: 302 - undefined'

### ISSUE THREAD

**Issue by jekusz** [caprover/caprover#647]
What is the problem?
CLI won't connect to server

Steps to reproduce the problem:

1. - Install clean droplet on digitalocean
2. - Update docker and caprover
3. - Setup domain and enable http and force https
4. - Install caprover cli on development machine
5. - Attempt setup by 'caprover serversetup'
6. - Enter your ip -> hit enter
7. - Observe error 'Error: StatusCodeError: 302 - undefined'

MY understanding is that the cli doesn't handle the redirect to https at all at this step

Answers to the following questions where applicable:

Your OS and version? windows 10
RAM? 16gb

Edit:
I've now found that this has been reported before (even though searched deeply in GH issues previously humph) but closed. I feel this subject deserves either an update of the 'getting started' docs, or handling of the error in the CLI.

**Comment by githubsaturn** [comment]
The problem is that you manually setup your server and then you are retrying the setup on CLI.

The "Getting Started" section doesn't guide the user to manually set the HTTPS and FORCE HTTPS using the web gui.

https://caprover.com/docs/get-started.html#caprover-setup

**Comment by githubsaturn** [comment]
Feel free to update the Getting Started page by opening a new PR on the documentation repo if you think there is something missing there:
https://github.com/caprover/caprover-website/blob/master/docs/get-started.md

**Comment by jekusz** [comment]
"The very first thing that CapRover needs is a root domain"
It's quite easy to carry through with the prompts from the dashboard before hitting the getting started docs. A race condition if you will.
Please see PR at: 
https://github.com/caprover/caprover-website/pull/23

**Comment by mdwekat** [comment]
@githubsaturn In the case of wanting to connect the CLI to a different machine after forcing the HTTPS, what we should do?

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover-cli#login

**Comment by ryancwalsh** [comment]
Thanks for this issue, @jektvik . 

Thanks for the tip, @githubsaturn .

I haven't gotten my first Next.js app deployed yet, but at least `caprover deploy` isn't throwing this error anymore after I used `caprover login`.
