### ISSUE TITLE
Update failed(?) containers not reachable

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#649]
What is the problem?

1. I started a Caprover Update via the "Updata available" Button in the caprover UI.
2. I left the desktop.
3. Came back about ten minutes later.
4. UI was gone, instead i only saw a blank page..
5. Refresh didn't help.
6. Restartet Server (Hardware) -> Didn't help.
7. Tried "docker service update captain-captain"
8. Got Error: `service update paused: update paused due to failure or early termination of task wd2guxqbqi2kc4ijsitapvsvy`
9. Same with `docker service update captain-captain --image caprover/caprover:latest`

Steps to reproduce the problem:
propably not reproducible :D
just click the update button.

Answers to the following questions where applicable:
- Ubuntu 16.04 (xenial)
- 4GB

**Comment by jappyjan** [comment]
oh and this is the output of "docker service ps captain-captain"

root@v220190710104794014:~# docker service ps captain-captain
ID                  NAME                    IMAGE                      NODE                  DESIRED STATE       CURRENT STATE                  ERROR                              PORTS
r5oi636069gd        captain-captain.1       caprover/caprover:latest   v220190710104794014   Running             Preparing about a minute ago                                      
fno0pbdkfylv         \_ captain-captain.1   caprover/caprover:latest   v220190710104794014   Shutdown            Rejected about a minute ago    "No such image: caprover/capro…"   
1hwws4jtiuq1         \_ captain-captain.1   caprover/caprover:latest   v220190710104794014   Shutdown            Rejected about a minute ago    "No such image: caprover/capro…"   
ns3zwolvzw5h         \_ captain-captain.1   caprover/caprover:latest   v220190710104794014   Shutdown            Rejected 3 minutes ago         "No such image: caprover/capro…"   
yg0j857yyg6p         \_ captain-captain.1   caprover/caprover:latest   v220190710104794014   Shutdown            Rejected 3 minutes ago         "No such image: caprover/capro…"   
root@v220190710104794014:~#

**Comment by githubsaturn** [comment]
"No such image" error on a public image is usually a bad docker installation. Try reinstalling your docker. Do not use docker from snap. Use official docker installation guide.

**Comment by jappyjan** [comment]
the error actually references a local copy (with hash at the end of the name)

my docker instance is NOT installed via snap. i followed the official installation guide.

all other containers seem to run just fine btw.

**Comment by githubsaturn** [comment]
Does your disk have enough space? Have a look at this for example: https://github.com/caprover/caprover/issues/355#issuecomment-458826098
