### ISSUE TITLE
[Feature Request] Custom SSL Certificate

### ISSUE THREAD

**Issue by hesa2020** [caprover/caprover#650]
**Is your feature request related to a problem? Please describe.**
Since LetsEncrypt is still relatively new, it is not always "whitelisted" on some old systems and therefor gets blocked.

**Describe the solution you'd like**
When in the app "App Configs" we should be able to check an option to "Override certificate paths". And then we can upload or paste in textbox the CA, CRT, Key for a custom SSL certificate.

**Describe alternatives you've considered**
Alternative would be to upload the certificate directly on the server "host" files and hardcore the paths in the nginx configuration file.

**Additional context**
Nothing more to say about this.

**Comment by githubsaturn** [comment]
Duplicate: https://github.com/caprover/caprover/issues/265#issuecomment-416652296

Such rarely-used feature won't be surfaced in CapRover UI. This is by design and it's intended behavior in order to keep the UI simple and clean for common use cases.
