### ISSUE TITLE
[Feature Request] User Management

### ISSUE THREAD

**Issue by hesa2020** [caprover/caprover#651]
**Is your feature request related to a problem? Please describe.**
Would like to share some Apps from my server with other developers without having them to view my other apps ( And my github password )

Yes if you can make the github password field a one time input that would be great, if root account show github password else show dots, if password is not dots ( &bull; ) then change it.

**Describe the solution you'd like**
Global simple user management with read/write/master permission for Apps ( and a root account )

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by githubsaturn** [comment]
Duplicated: https://github.com/caprover/caprover/issues/492
