### ISSUE TITLE
[Feature request] API

### ISSUE THREAD

**Issue by hesa2020** [caprover/caprover#652]
**Is your feature request related to a problem? Please describe.**
Im unable to automatically deploy new CapRover apps from an external system.
I dont know if deploying new docker container automatically gets picked by caprover.

**Describe the solution you'd like**
Would like a simple API ( with user management from my previous feature request ) to allow 
- Creating/Editing/Removing apps ( blank and from template ) with the configuration available in the current UI.
- Adding/Editing/Removing users ( from root account )
- Managing cluster
- Get App container statistic ( ram usage, disk space using, cpu usage )
- Get Server statistics ( ram, disk, cpu, network bandwith )

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by githubsaturn** [comment]
I am not sure if I entirely understand this:
> I dont know if deploying new docker container automatically gets picked by caprover

If you're referring to CI/CD systems, there are numours ways that people use CI/CD. Webhooks are one way:
https://medium.com/staminacake/peaceful-cd-to-dev-server-with-caprover-docker-and-aws-3b86b0bced41

You can also use CapRover api via the CLI:
https://github.com/caprover/caprover-cli#api
