### ISSUE TITLE
[Feature Request] Notifications

### ISSUE THREAD

**Issue by hesa2020** [caprover/caprover#653]
**Is your feature request related to a problem? Please describe.**
At the moment its hard to know when an app got updated ( automatically ) and when a build is "running" ( Build is completed but app is booting, i know this would be tricky, but maybe check if app is listening on the ports provided )

**Describe the solution you'd like**
Configurable notifications ( to email, maybe allow us to integrate easily some "plugin" services like twilio for sms )

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by githubsaturn** [comment]
There are two things that you're referring to:
1) The build process notification: 
This can be achieve via a custom [predeploy script](https://caprover.com/docs/pre-deploy-script.html)

2) The health of the app:
This is completely out of CapRover's world, you can use a 3rd party service like Pingdom or Uptime Robot or etc.
