### ISSUE TITLE
Help: nginx and caprover not scaling/starting up

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#657]
My server had a bit of a meltdown.  Usually it all starts up again fine after a reboot.  This time is isn't.

I can still open a basic console onto the server after the reboot.  What I see with `docker service ls` is:

![image](https://user-images.githubusercontent.com/9009792/79861240-fded2b80-83cb-11ea-9a3a-1578ea577154.png)

Can't seem to scale caprover (or anything else for the matter) up:

![image](https://user-images.githubusercontent.com/9009792/79861360-33921480-83cc-11ea-8ed3-f8a71df08113.png)

It just hangs there.  Any nuclear options to get all of these services back up and running?

Same with attempted restart... just hangs:

![image](https://user-images.githubusercontent.com/9009792/79862350-deef9900-83cd-11ea-84cd-525e218c1c74.png)

Thanks!

**Comment by drmrbrewer** [comment]
OK slowly but surely, after several reboots, it's all come back up.  Still interested to hear what you would have done in this situation...!

**Comment by githubsaturn** [comment]
You could run `docker service ps captain-captain --no-trunc` to see more details on why the service can't scale to `1`. But this is most likely a disk issue. Either you're running out of disk on your `/var` directory, or your disk is corrupted. Since after a few reboots things started working, it seems like it's the latter, corrupted disk, and keep in mind it may happen again on this server.

**Comment by drmrbrewer** [comment]
Thanks for the tips.  I think there is enough disk space, so perhaps it is corrupted...

**Comment by drmrbrewer** [comment]
FYI you were correct... 

> keep in mind it may happen again on this server

The server limped along for a bit longer, surviving another couple of restarts... but finally there was one occasion when it just wouldn't re-start correctly despite numerous attempts.  So I put it to rest in favour of a shiny new one.
