### ISSUE TITLE
Cannot cancel build process

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#659]
My app building process annoyingly hangs (I think during the installation of docker-ce) because it is expecting user input (despite using `apt-get install -y`):

![image](https://user-images.githubusercontent.com/9009792/80231998-17040f80-864c-11ea-8aec-936e28118d92.png)

I've tried what is suggested in [this issue](https://github.com/caprover/caprover/issues/641)... but restarting the service (either via command line or via console) doesn't stop build process.

How do I get out of this stalemate?  And prevent it in future...

**Comment by klickers** [comment]
Are you by any chance able to revert to original state (or a previous deployment)?  That worked when my app was running a loop after deployment, but I'm not sure if it'll work halfway through build process.

**Comment by drmrbrewer** [comment]
Thing is, I'd like to revert to the current version, which isn't possible.  It seems to me that it would be good to have an Abort Deploy button or similar.

**Comment by githubsaturn** [comment]
There is no abort API with docker. However, simply restarting captain-captain would abort the build.

**Comment by drmrbrewer** [comment]
@githubsaturn ah sorry, I misunderstood the post to which I linked... the suggestion there was indeed to restart the service captain-captain, rather than the service to which you're trying to deploy.  Restarting captain works, thanks.
