### ISSUE TITLE
nginx -t before applying changes to nginx.conf

### ISSUE THREAD

**Issue by teyc** [caprover/caprover#660]
**Is your feature request related to a problem? Please describe.**
I really like caprover! Getting nginx configuration right is somewhat of a black art for inexperienced people like me, and wedging the caprover UI is not the same level of user friendliness that caprover is known for.

**Describe the solution you'd like**
Ideally before applying the changes, I'd like caprover to `nginx -t` and see if there are any potential problems with the configuration.

**Comment by Alfagun74** [comment]
definitely a good one!

**Comment by thgh** [comment]
I had a custom nginx config referencing a `srv-captain--api` URL which broke after renaming the app. So ideally it also runs `nginx -t` before changing the name of an app.

**Comment by githubsaturn** [comment]
Done. Will be available in the next build. 


RE: renaming
This is not something that `nginx -t` can covert. The domains are resolved in real time. As far as `nginx -t` is concerned, there is no syntax errors.
