### ISSUE TITLE
Is there a way to cancel builds in progress?

### ISSUE THREAD

**Issue by rphly** [caprover/caprover#662]
Currently, when I build a project, I'd have to wait for it to finish before rebuilding even if I've caught a mistake and would like to abort. 

There are instances as well when the build process does not end- particularly when there are errors in my application and... I am unable to stop the build process without killing the DO droplet and starting up again.

**Comment by githubsaturn** [comment]
Please see
https://github.com/caprover/caprover/issues/641#issuecomment-606612814
and
https://github.com/caprover/caprover/issues/659#issuecomment-619155081
