### ISSUE TITLE
More flexible command for deploying dockerfile

### ISSUE THREAD

**Issue by margani** [caprover/caprover#664]
**Is your feature request related to a problem? Please describe.**
There are limited arguments for deploying a dockerfile. When I run `caprover deploy`, I can't specify `--build-arg`, or `--no-cache` to the docker build command.

**Describe the solution you'd like**
`caprover deploy` is fine but the `captain-definition` file is better to accept extra arguments for the docker build image command.

**Describe alternatives you've considered**
at the moment I don't have any solution, even using `export myArg=something` before running `caprover deploy` doesn't fix it. and I have no solution for `--no-cache` argument of docker.

**Additional context**
I don't want to set my arguments inside the dockerfile as they are secrets.

**Comment by golyalpha** [comment]
If you have issues with deploying an app that requires secrets, maybe it's ok to set environment variables in the CapRover WebUI for those secrets?

**Comment by margani** [comment]
The secrets are required for building the app inside the dockerfile not for the application itself. Something like PAT for Azure Artifacts.

**Comment by golyalpha** [comment]
So you mean like secrets for downloading dependencies and what not, if I understand correctly?

**Comment by margani** [comment]
I can't put the secret inside the image, but at the moment I have a script to create a folder ready for `caprover deploy`, but I was wondering instead we could find a way to respect the build arguments.

**Comment by golyalpha** [comment]
Well, again, using build arguments to specify a build secret inside a captain-definition file inside a repo is not something that should be considered acceptable, as that means you're storing secrets inside a git repo. This is an issue. Just do a BigQuery search for bitcoin private keys (all of which will be drained already) inside *public* repositories on GitHub.

IMO, the secrets required for your build should be as far away from the application source code as possible.

**Comment by golyalpha** [comment]
What I think is acceptable is setting build arguments from caprover (WebUI or API) itself, rather than any file inside the application's repository.

**Comment by githubsaturn** [comment]
Thanks for the discussion here. 
You can use the environmental variables to pass `--build-arg`. By default, all your environmental variables are available in your build context.

**Comment by margani** [comment]
So I created a bug [here](https://github.com/caprover/caprover/issues/675)
