### ISSUE TITLE
Execute command from one container to another

### ISSUE THREAD

**Issue by KonradHolubek** [caprover/caprover#668]
What is the problem?
I'm trying to access containerB from container A

Steps to reproduce the problem:
I know I can enter containerB and execute commands from host, using sudo docker exec -u 0 -it <name containerB>. However, is there a way to execute commands between containers ?

Can you please tell me if this is possible and how to do it ? 

Thank you. 

Konrad

**Comment by githubsaturn** [comment]
This is not a CapRover question, it's a Docker question, see here for example: https://forums.docker.com/t/execute-command-from-a-container-to-another-container/19492/5

Short answer: it is possible, but it's not quite complicated and requires customize the container.
