### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by Burdzi0** [caprover/caprover#672]
What is the problem?
Using https://caprover.com/docs/cli-commands.html I tried to configure caprover on my VPS. I installed caprover and configured it.  I cannot finish "caprover login" on my local machine.

Root domain: https://burdzi0.best
Domain to login - http://captain.burdzi0.best/ (changed password)

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
```sh
➜ caprover login


------------
CapRover CLI has recently been refactored. Please report potential bugs here: https://github.com/caprover/caprover-cli/issues
------------


Login to a CapRover machine...

? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": https://captain.burdzi0.best
? CapRover machine password: [hidden]
? CapRover machine name, with whom the login credentials are stored locally: captain-01

Something bad happened: cannot save captain-01 at https://captain.burdzi0.best.
Error: self signed certificate
```

Answers to the following questions if applicable:
- Your OS and version?
Type: Leader (Main Node)
State: ready
Status: active
RAM: 1.91 GB
OS: linux (Ubuntu 16.04)
CPU: 1 cores
Architecture: x86_64

Hostname: XXXXXXX
Docker Version: 19.03.8
- RAM?
VPS 2GB

**Comment by githubsaturn** [comment]
CapRover local installations are mostly for development. If you really need to use self-signed certs, you can add them to your trusted certs. This is different depending on your OS.

**Comment by abulka** [comment]
So I can't login to my caprover local VM to do a deploy, without setting up some sort of self-signed certificate? I'm on a Mac, and even if I generate 
`certificate.p12, private.pem, and certificate.pem` files what do I do with them?  How does caprover CLI know about them?

**Comment by githubsaturn** [comment]
No. You do not need any selfsigned certs etc. If you're using CapRover on your local network. You don't need to enable HTTPs.

Just install CapRover like this:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker run -e MAIN_NODE_IP_ADDRESS=192.168.1.12 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

Replace `192.168.1.12` with whatever IP your local VM is connected as. 

More details here: https://caprover.com/docs/run-locally.html#install-caprover-on-a-private-local-network

**Comment by abulka** [comment]
@githubsaturn Yes, that's exactly how I installed caprover (in a Vagrant VM which has an IP address that I used for the caprover install). Note I have `/etc/hosts` containing `192.168.0.219    captain.caproverinstance.local` and I set the root domain to `caproverinstance.local` via the dashboard.  Dashboard works and 3rds party apps work. 

Now I want to deploy my own apps but can't use the caprover CLI because `caprover login` fails with the same certificate error as the OP of this thread.

```
% caprover login


Login to a CapRover machine...

? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": https://captain.caproverinstance.local
? CapRover machine password: [hidden]
? CapRover machine name, with whom the login credentials are stored locally: captain-01

Something bad happened: cannot save captain-01 at https://captain.caproverinstance.local.
Error: self-signed certificate
```

**Comment by githubsaturn** [comment]
You're entering https when trying to log in:
```
https://captain.caproverinstance.local
```

You should try `http://captain.caproverinstance.local`
