### ISSUE TITLE
[Deployment Issue] Laravel 7.0 + vuejs using Dockerfile,  502 error

### ISSUE THREAD

**Issue by jigzstar** [caprover/caprover#673]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I having a problem deploying a Laravel + vuejs application. I am using the Dockerfile guidelines provided in the examples. When I run a ```caprover deploy``` using the example app, I am able to get to the Laravel welcome screen. When I run it within my application, I get a 502 error.

Is there something i'm missing? 

1. I also noticed that in both the example (laravel project) and my project, that the /var/www folder and contents are all owned by root:root in the container. Is that something that needs to be set in  caprover?  When using default docker / docker-compose, I had to specifically set those to be owned by the www:www user.
1. It seems not be setting the right IP address for the container, nginx is trying the upstream of 10.0.0.30:80, when the ip is actually 10.0.0.25 (see below). I'm just wondering how comes, it works for the sample laravel application.

Thanks in advance.

Error in captain-nginx:
[error] 25#25: *53768 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xx.xx.xxx server: csa.apps.tichico.co, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.0.0.30:80/favicon.ico", host: "csa.apps.tichico.co", referrer: "http://csa.apps.tichico.co/"

/etc/nginx/conf.d/captain.conf
```
set $upstream http://srv-captain--csa:80;
```
docker network insect captain-overlay-network
```json
            "c6e5cf53297f2d02b54ae700b0bba33999875439d37948a46b7f199b05e0f59f": {
                "Name": "srv-captain--csa.1.s7qlqe7f2egttgbx4oxry5ee0",
                "EndpointID": "f41f261e92cfb4dcce8ad5ac2595abfd6b7b6cc3ca4c522a1395fd340119c989",
                "MacAddress": "02:42:0a:00:00:19",
                "IPv4Address": "10.0.0.25/24",
                "IPv6Address": ""
            },
```
docker ps
![image](https://user-images.githubusercontent.com/197836/81821803-4cd83d80-9500-11ea-9a22-7d98ea849a20.png)

ps aux inside the container
![image](https://user-images.githubusercontent.com/197836/81821678-21ede980-9500-11ea-8c49-a6b7e78f6acf.png)

netstat inside container
![image](https://user-images.githubusercontent.com/197836/81821439-d76c6d00-94ff-11ea-8900-e586d49c6cd3.png)

If applicable, content of `captain-definition` file:

```
 {
  "schemaVersion" :2 ,
  "dockerfilePath" : "./Dockerfile.caprover"
 }
```

Dockerfile
```Dockerfile

FROM php:7.2-fpm

# Copy composer.lock and composer.json
COPY ./composer.lock ./composer.json /var/www/
COPY ./deployment-config/caprover/docker-entry.sh /
RUN chmod +x /docker-entry.sh

# Set working directory
WORKDIR /var/www

# Update packages

RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - \
    && apt-get update \
    && apt-get install -y build-essential \
    locales \
    zip \
    vim \
    unzip \
    nodejs netcat libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev git \
    && apt-get clean

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd


# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
# RUN docker-php-ext-install pdo_mysql pdo_pgsql mbstring zip exif pcntl
# RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
# RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory
COPY . /var/www/
RUN ls /var/www

# COPY --chown=www:www . /var/www

COPY ./deployment-config/caprover/configuration/nginx/conf.d/ /etc/nginx/conf.d/
RUN ls /etc/nginx/conf.d

COPY ./deployment-config/caprover/configuration/php/local.ini /usr/local/etc/php/conf.d/local.ini
RUN ls /usr/local/etc/php/conf.d
RUN cat /usr/local/etc/php/conf.d/local.ini

RUN rm -rf /etc/nginx/sites-enabled
RUN mkdir -p /etc/nginx/sites-enabled

RUN chmod -R 777 /var/www/storage

# RUN composer install
# Change current user to www
# USER www

# Expose port 9000 and start php-fpm server
EXPOSE 80
CMD ["/docker-entry.sh"]
```

Steps to reproduce the problem:

1.  Start a new laravel 7.0 project, with vuejs and node modules
1. Goto the successfully deployed url.

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by joakim-emagine** [comment]
Small update on the issue, I restarted the app via the dashboard, the new internal ip is 10.0.0.33, however, ping from inside the captain-nginx container it still resolves to 10.0.0.30.

**Comment by jigzstar** [comment]
I got it to work! I was missing the "ngnix" server in the app's container. I stupidly thought it would have worked without it, since captain-ngnix is already proxying connections to the container.

**Comment by faierbol** [comment]
Hi @jigzstar can you please let me know the deploy steps and config files for deploying laravel? i am struggling for 1 week to deploy my app with no success :(

**Comment by githubsaturn** [comment]
@faierbol 
I suggest you first try deploying your application on "pure" Docker, and then migrate to CapRover. All you need a Dockerfile.

What is the problem that prevents you from deploying?

**Comment by faierbol** [comment]
Hi @githubsaturn i get 403 Forbidden error
my captain-definition:
 {
  "schemaVersion" :2 ,
  "dockerfileLines" :[
                        "FROM  webdevops/php-nginx:7.4-alpine",
                        "ENV PHP_MAX_EXECUTION_TIME 110",
                        "COPY ./main_app /var/www/html",
                        "COPY ./php.ini opt/docker/etc/php/php.ini"
                    ]
 }

**Comment by faierbol** [comment]
File and folder permissions
/bootstrap        775
/storage          775 (recursively)

**Comment by githubsaturn** [comment]
Yea this is a pure Docker issue and it's specific to your app. Have a look at this as your starting point. It's a widely used template for Laravel on CapRover. https://github.com/jackbrycesmith/laravel-caprover-template

**Comment by faierbol** [comment]
thx for the suggestion but i would like to use nginx instead of caddy :(
