### ISSUE TITLE
Persistent data and multiple physical instances

### ISSUE THREAD

**Issue by roshanjonah** [caprover/caprover#674]
Imagine if I had 2 DigitalOcean instances that I use to set up and push my WordPress app which has persistent data. Would persistent data be stored only one server 1 or would it be copied over to server 2? And if a user uploads an image to Server 1, what happens then?

**Comment by githubsaturn** [comment]
There two types of apps when you create an app on CapRover. Regular apps and apps with persistent data. The main difference between these types is that apps with persistent data are locked down on the node once you attach a persistent volume to it. 

WordPress specifically has two apps, wordpress php and mysql database, both have persistent data. Your MySql may be on node 1 and your wordpress php may end up on node 2. Hence the persistent data for MySql gets stored on node 2 and your wordpress data gets stored on node 1. if you want, you can manually specify the node where node where you want to host your persistent app by going to apps settings > App Config > Node ID.

**Comment by Berndinox** [comment]
Is, like in kubernetes, a dynamic volume provisioned for the data?

**Comment by githubsaturn** [comment]
CapRover uses simple Docker volumes which means that the data is only available at that particular node.
