### ISSUE TITLE
Environment variables as build-time variables

### ISSUE THREAD

**Issue by margani** [caprover/caprover#675]
What is the problem?
In [here](https://github.com/caprover/caprover/issues/664) @githubsaturn said:
> By default, all your environmental variables are available in your build context.

But I think it's not working.

Content of `captain-definition` file:
```
{
    "schemaVersion": 2,
    "dockerfilePath": "./dockerfile"
}
```
Content of `dockerfile` file:
```
FROM alpine:latest
RUN env | sort
RUN echo "value for MyEnvVar: [${MyEnvVar}]"
ENTRYPOINT [ "tail -f /dev/null" ]
```

Steps to reproduce the problem:
First set an environment variable:
`export MyEnvVar="Test"`
And then simply run `caprover deploy`, and the output is:
```
Deploying test to http://captain.captain.localhost...

Uploading [====================] 100%  (ETA 0.0s)
Upload done.

This might take several minutes. PLEASE BE PATIENT...

⠋ Building your source code...
------------------------- Fri May 15 2020 05:50:34 GMT+0000 (Coordinated Universal Time)
⠴ Building your source code...
Step 1/4 : FROM alpine:latest
⠏ Building your source code...
---> f70734b6a266
Step 2/4 : RUN env | sort

---> Running in 672c3c3f8aba
HOME=/root
HOSTNAME=672c3c3f8aba
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
Removing intermediate container 672c3c3f8aba
---> 80671c207ea4
Step 3/4 : RUN echo "value for MyEnvVar: [${MyEnvVar}]"
⠼ Building your source code...
---> Running in 22bdb84d51fc
value for MyEnvVar: []
Removing intermediate container 22bdb84d51fc
---> b04018d5d063
Step 4/4 : ENTRYPOINT [ "tail -f /dev/null" ]

---> Running in 8b1a488f79ef
Removing intermediate container 8b1a488f79ef
---> e3bc53906e57
Successfully built e3bc53906e57
Successfully tagged img-captain-test:latest
Build has finished successfully!

Deployed successfully test
App is available at http://test.captain.localhost
```
`MyEnvVar` doesn't have a value in build time.

I think what is said about build arguments:
> all your environmental variables are available in your build context.
by `your environment variables`, it means the environment variables inside the docker container, not the environment variables inside the host machine.

- OS: Ubuntu 18.04.2
- 16GB
- CapRover version: 1.6.1
- Docker version 19.03.6, build 369ce74a3c

**Comment by githubsaturn** [comment]
How do you set the environmental variable? In order for the environmental variable to be present in the build context, you have to set it in the app config in CapRover. Host env variables will not be imported to build context.

**Comment by margani** [comment]
Thank you @githubsaturn 
Do you mean https://caprover.com/docs/app-configuration.html
?
So I need to create the app and set the app config, then it will be available during build of docker image?

**Comment by githubsaturn** [comment]
Yes, the environmental variables defined under app configs are available as env vars both during building process, and also during runtime of the container.

**Comment by margani** [comment]
Thank you.

**Comment by louis-l** [comment]
Hi @githubsaturn 

I have a similar issue and found this post.
I set the env key and value in my app config, but the Dockerfile does not receive the value properly.

Here is my config in CapRover GUI:
![config](https://user-images.githubusercontent.com/10172565/101269430-fc3d7000-37c2-11eb-95e6-696b55baba5a.png)

And here is on of the lines in my Dockerfile:

```
RUN echo "value for NOVA_GIT_COMPOSER_TOKEN: [${NOVA_GIT_COMPOSER_TOKEN}]"
```

But when deploying, the build output is

```
value for NOVA_GIT_COMPOSER_TOKEN: []
```

Do I miss anything here?

**Comment by githubsaturn** [comment]
Environmental variables are available as "arguments" during the build process. So you need to add two lines to your Dockerfile:
```
ARG NOVA_GIT_COMPOSER_TOKEN=DEFAULT_WRONG
ENV NOVA_GIT_COMPOSER_TOKEN=${NOVA_GIT_COMPOSER_TOKEN}

RUN echo "value for NOVA_GIT_COMPOSER_TOKEN: [${NOVA_GIT_COMPOSER_TOKEN}]"

```

**Comment by louis-l** [comment]
> Environmental variables are available as "arguments" during the build process. So you need to add two lines to your Dockerfile:
> 
> ```
> ARG NOVA_GIT_COMPOSER_TOKEN=DEFAULT_WRONG
> ENV NOVA_GIT_COMPOSER_TOKEN=${NOVA_GIT_COMPOSER_TOKEN}
> 
> RUN echo "value for NOVA_GIT_COMPOSER_TOKEN: [${NOVA_GIT_COMPOSER_TOKEN}]"
> ```

Thank you @githubsaturn 
It works 👍
