### ISSUE TITLE
default to https

### ISSUE THREAD

**Issue by prabirshrestha** [caprover/caprover#676]
Is it possible to have a global config that says enable https by default? Every time I create an app the first thing I do is enable https.

**Comment by githubsaturn** [comment]
This is really a custom behavior specific to your work flow. I understand the use case for this, but this is essentially two separate actions. Lots of people with custom workflow utilize the CLI `caprover api` command and perform multiple actions at once. The error handling is also different from usecase to usecase. If you're interested in the CLI solution, see more details here: https://github.com/caprover/caprover-cli#api
