### ISSUE TITLE
[Deployment Issue] Default server changed from nginx to apache for Wordpress One Click App

### ISSUE THREAD

**Issue by tosinamuda** [caprover/caprover#677]
What is the problem?
The default server for Wordpress one click app changed to Nginx after running volumes and mounting to a local Wordpress folder

I will like to have the default server changed back to nginx.

Steps to reproduce the problem:
1. Prune volumes
2. Use a specific folder instead of label volume

Answers to the following questions if applicable:
- Your OS and version? Digitalocean Ubuntu 20 droplet
- RAM? 4gb

**Comment by githubsaturn** [comment]
One click app setup should be used as is. You can access the directory where the data is store by running `docker volume ls` and `docker volume inspect your-vol-name`.

**Comment by tosinamuda** [comment]
Even when one click app setup is used as it is. The default server was still apache and not nginx

**Comment by githubsaturn** [comment]
I now understand what you're trying to achieve. This goes to the architecture of CapRover. We use nginx as a router to route between apps, we don't share the nginx instance. The built-in wordpress is using Apache, hence the route will be:

```

  +--------------+      +----------------------+
  |              |      |                      |
  |    nginx     +----->+  Apache - WordPress  |
  |              |      |                      |
  +--------------+      +---------^------------+
                                | |
                                | |
                        +-------v--------------+
                        |                      |
                        |       MySQL          |
                        |                      |
                        +----------------------+
```

If you want to replace Apache-WordPress with nginx-WordPress, you can build your own docker image and deploy it.

**Comment by SwapRane12** [comment]
> Even when one click app setup is used as it is. The default server was still apache and not nginx

I implemented wordpress fpm with nginx into a one-click app PR in underway. until then
Login to your CapRover dashboard
Go to apps and click on One-Click Apps/Databases
Select >> TEMPLATE << at the bottom of the dropdown list
Copy and paste following code into the text area, and click NEXT.
Enter values and make sure it's working as expected.
`$$cap_appname-wordpress:
        image: wordpress:$$cap_wp_version
        volumes:
            - $$cap_appname-wp-data:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: $$cap_db_host:3306
            WORDPRESS_DB_NAME: $$cap_db_name
            WORDPRESS_TABLE_PREFIX: $$cap_db_prefix
            WORDPRESS_DB_USER: $$cap_db_user
            WORDPRESS_DB_PASSWORD: $$cap_db_pass
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-nginx:
        image: raulr/nginx-wordpress
        volumes:
            - $$cap_appname-wp-data:/var/www/html
        environment:
            POST_MAX_SIZE: 128m
            WP_CONTAINER_NAME: srv-captain--$$cap_appname-wordpress`

**Comment by SwapRane12** [comment]
Login to your CapRover dashboard
Go to apps and click on One-Click Apps/Databases
Select >> TEMPLATE << at the bottom of the dropdown list
Copy and paste following code into the text area, and click NEXT.
Enter values and and deploy.
`captainVersion: 4
services:
    $$cap_appname-wordpress:
        image: wordpress:$$cap_wp_version
        volumes:
            - $$cap_appname-wp-data:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: $$cap_db_host:3306
            WORDPRESS_DB_NAME: $$cap_db_name
            WORDPRESS_TABLE_PREFIX: $$cap_db_prefix
            WORDPRESS_DB_USER: $$cap_db_user
            WORDPRESS_DB_PASSWORD: $$cap_db_pass
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-nginx:
        image: raulr/nginx-wordpress
        volumes:
            - $$cap_appname-wp-data:/var/www/html
        environment:
            POST_MAX_SIZE: 128m
            WP_CONTAINER_NAME: srv-captain--$$cap_appname-wordpress
caproverOneClickApp:
    variables:
        - description: Database host
          defaultValue: srv-captain--xxx
          id: $$cap_db_host
          label: Database Host
        - description: Database name
          defaultValue: wordpress
          id: $$cap_db_name
          label: DB Name
        - description: Table prefix used by this Wordpress
          defaultValue: WP_
          id: $$cap_db_prefix
          label: Table Prefix
        - id: $$cap_db_user
          label: Database user
          defaultValue: wordpressuser
        - id: $$cap_db_pass
          label: Database password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_wp_version
          label: WordPress Version
          defaultValue: 5.4.0
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/wordpress/tags/
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            WordPress is an online, open source website creation tool written in PHP. But in non-geek speak, it’s probably the easiest and most powerful blogging and website content management system (or CMS) in existence today.
             Enter your WordPress Configuration parameters and click on next. A WordPress container will be created for you. The process will take about a minute for the process to finish. 
            Note: This app is intended for advanced users who'd like to have a central DB in a single container for multiple WP's. You should start by configuring your DB first and then comeback with all the DB Information.
        end: >-
            Wordpress is deployed and available as $$cap_appname-wordpress . 
             IMPORTANT: It will take up to 2 minutes for WordPress to be ready. Before that, you might see a 502 error page.
            . Remember that this app will not create a Database by itself. You need to provide all that information.
    displayName: WordPress - No Database
    isOfficial: true
    description: This will create a WordPress only. You will need to create and configure the database information manually. Intended for advanced users.
    documentation: Taken from https://docs.docker.com/compose/wordpress/. Port mapping removed from WP as it is no longer needed`
