### ISSUE TITLE
[Question] How can I set gitlab host URL for run CI/CD without getting unkown host when whe runner try to clone de repo?

### ISSUE THREAD

**Issue by DavyGuedes** [caprover/caprover#678]
[Question] How can I set gitlab host URL for run CI/CD without getting an unkown host when the runner tries to clone de repository?
Hello sir,

I'm having trouble when trying to define a runner for gitlab CI/CD. What is happen is the gitlab instance is using the container ID for its own url host and when the runner job is trying to clone any repository from the gitlab instance, it tries to use the container ID as url host instead gitlab instance URL.
Can you help me?
Thanks in advance!

**Comment by githubsaturn** [comment]
Hi @DavyGuedes 

The question you have is related to gitlab, not CapRover. Please note that CapRover is a proxy that runs other applications as a Docker container. In this case, you're running a gitlab container via Docker. Try asking your question in Gitlab forums: https://forum.gitlab.com/

My guess is that it has something to do with `GITLAB_OMNIBUS_CONFIG` variable, but again, you'll get a better answer if you ask this question in gitlab forum.
