### ISSUE TITLE
bug(deployment) : Method 5 strange behaviour, data not saved

### ISSUE THREAD

**Issue by PierreBrisorgueil** [caprover/caprover#680]
Hello, thx for this work!  

just a strange behavior
- last release
- fresh Debian 10 install 
- last docker

when I set my deployment information with Method5, after a success deploy the textarea of method 5 is empty again

```
 {
  "schemaVersion": 2,
  "imageName": "ghost:latest"
 }
```

btw, it could be nice to be able to save our own template for regular deploy

**Comment by githubsaturn** [comment]
Method 5 is really a helper method to call the API. Saving the data in that context doesn't make sense. The API call results in a image update, and that's where the data is being "saved". There are many different methods for deployments, all of them, at the end of the day, get converted to an "image update" action. 

With regards to saving your own template, it's in the pipeline, we'll implement that soon.

**Comment by PierreBrisorgueil** [comment]
Hum okok I understand!

Great news !
