### ISSUE TITLE
HTTPS issue  certbot register

### ISSUE THREAD

**Issue by PierreBrisorgueil** [caprover/caprover#681]
hum when i try to add https on a sub domain (wildcard ok, domain ok, all map with the server), i have this issue : 

```
 1107 : Unexpected output when enabling SSL for xxxx.com with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log
 Plugins selected: Authenticator webroot, Installer None
 You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.
```

probably related to something like this  https://github.com/mail-in-a-box/mailinabox/issues/1528

We are talking about a domain already signed before with letsencrypt, maybe it's related to certbot register or something similar in order to renew them

**Comment by githubsaturn** [comment]
Is it a new install? Or an existing install and this issue just started to happen?

**Comment by PierreBrisorgueil** [comment]
Hello, new install, new server, old domain switched

**Comment by githubsaturn** [comment]
I just tested this on a new instance and wasn't able to reproduce the problem. Are you sure you didn't accidentally delete `/captain` directory? Or maybe unmount the volume if you're using a different volume?

If none of these are the problem, please retry on a new VPS. What's your OS version and Docker version?

**Comment by PierreBrisorgueil** [comment]
thx for your time, hum sure, I looked for info on Certbot in it.

Hmm, I try this as soon as possible! 

Docker 19.x
Debian 10

**Comment by douglasjunior** [comment]
We are receiving this message too when click in "Enable HTTPS" after "Connect New Domain":

> 1107 : Unexpected output when enabling SSL for <my.domain.com> with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.

It is a clean installation, we have not found where we can configure this in the web interface.

I thought about entering the certbot container and registering manually, but I think the problem could return if the container is recreated in the future.

**Comment by githubsaturn** [comment]
@douglasjunior when your run `caprover serversetup` it asks for your email address and sets up the account for you. 

Was CapRover able to finish the serversetup and enable SSL on your root domain?


CapRover mounts volumes to your certbot container so that the account information is persisted on disk. It's mounted at `ll /captain/data/letencrypt`. Can you confirm that your volume setup is working properly?

**Comment by douglasjunior** [comment]
Hi @githubsaturn, thanks for the quick response.

You are right, we are skipped the step 3 (Install CapRover CLI) of the Get Started. Initially we thought that this step would be used only during the deployment. We went straight to the configuration on the web interface.

Now we run the `caprover serversetup`, enter the IP, domain and email. However, we received a CSFR validation error. (a red html code).

However, when we try to run the setup again, we get the message "You may have already setup the server with root domain".

Ok, now when a run `caprover login` we were able to log in successfully, and the root domain now appears in the web interface.

However, when we try to click on "Enable Https" we continue to receive the same message:

> Authenticator webroot, Installer None You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.

Coincidentally, we also used Debian 10 with Docker 19.03.

**Comment by douglasjunior** [comment]
The directory `/captain` seems to be ok:

![image](https://user-images.githubusercontent.com/1512341/86392197-6cbeee80-bc71-11ea-929c-27d264a9c61c.png)

And the `/captain/data/letencrypt` too:

![image](https://user-images.githubusercontent.com/1512341/86392233-7d6f6480-bc71-11ea-9170-e19188c76e08.png)

**Comment by douglasjunior** [comment]
I entered the `caprover/certbot-sleeping` container and ran a `certbot register` and it worked. Now it looks like everything is working.

**Comment by githubsaturn** [comment]
@douglasjunior yea it works, but you shouldn't have needed it to begin with. Next time, all you need to do is to run `caprover serversetup` and CapRover takes care of that for you.

**Comment by douglasjunior** [comment]
Understood, thank you very much for your help, and thank you for maintaining this wonderful tool.

I just made my contribution to OpenCollective, you guys deserve a lot!
