### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by wadeziegler** [caprover/caprover#682]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I have been running CDD for about one year. Recently, I receive "Something bad happened" after logging in and "Check for updates" shows "An error has occurred." I checked the CDD logs and found this gets logged each time I reload "Check for updates":
captain-captain.1.kovvvl60ad14@caprover    | May 21st 2020, 12:55:40.375 pm    Error: certificate has expired
captain-captain.1.kovvvl60ad14@caprover    | Error: certificate has expired
captain-captain.1.kovvvl60ad14@caprover    |     at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
captain-captain.1.kovvvl60ad14@caprover    |     at TLSSocket.emit (events.js:198:13)
captain-captain.1.kovvvl60ad14@caprover    |     at TLSSocket._finishInit (_tls_wrap.js:636:8)
captain-captain.1.kovvvl60ad14@caprover    | GET /api/v2/user/system/versioninfo 500 224.433 ms - 21

I ran certbot manually and restarted CDD. There are no expired certs per certbot output. What could be expired?

**Comment by wadeziegler** [comment]
I checked the code and found that this endpoint has an invalid certificate in VersionManager.ts. So, I'm not sure what the work-around is until this cert is updated on caprover.com.

api.v2.caprover.com/v2/versionInfo?currentVersion=1.5.3

**Comment by githubsaturn** [comment]
You're on an old version. Update your CapRover instance and the error will be gone.

**Comment by wadeziegler** [comment]
Is there a way to upgrade CapRover to the latest stable version from the
command line? I do not see it in the docs.

**Comment by githubsaturn** [comment]
The easiest way to update is to go to settings and update from there. Unless you're using an edge image which doesn't update. In that case, use the CLI to update
```
docker pull caprover/caprover:latest
docker service update captain-captain --image caprover/caprover:latest --force
```
