### ISSUE TITLE
How to reverse proxy other containers not managed by CapRover?

### ISSUE THREAD

**Issue by davidmpa** [caprover/caprover#685]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

I have a container called `container-001` that has mapping `8081:8080`, so I can access the web server in it via `http://mydomain.com:8081`. Due to some issues it's not an option to deploy the container with CapRover, so it's launched with Docker Compose.

This doesn't feel clean and I want to avoid exposing port 8081 externally, only use CapRover to reverse proxy this container and enable HTTPS for `https://my-server.mydomain.com`.

I tried to set up a nginx One-Click application with CapRover but don't understand how I can connect it to `container-001` which is not managed by CapRover.

How can I set up a reverse proxy for other containers not managed by CapRover inside CapRover?

**Comment by githubsaturn** [comment]
It should be possible.

1) Make sure your container is attached to CapRover overlay network `captain-overlay-network`
2) Create the nginx reverser proxy app
3) for upstream domain use `http://container-001:8080`

**Comment by davidmpa** [comment]
@githubsaturn Sorry to bother again, but how should I attach my container to `captain-overlay-network` with Docker compose?

I found [this example](https://gist.github.com/winggundamth/0efc3a18c12b7f35e45a), but not sure where I should specify `captain-overlay-network`. Haven't found much documentation on this.

**Comment by githubsaturn** [comment]
Try this: https://docs.docker.com/compose/networking/#use-a-pre-existing-network

**Comment by davidmpa** [comment]
Thank you, it worked!!

**Comment by Alfagun74** [comment]
I put my non caprover service into the captain-overlay-network network but my NGINX Reverse Proxy just gives me a 504 Gateway Timeout after a minute. I cant reach the site. Any Ideas why? (Service is working fine and accessible from outside)

**Comment by githubsaturn** [comment]
Try shelling into nginx container and curl to the service name to see if it's accessible

**Comment by Alfagun74** [comment]
Thanks @githubsaturn. The problem was i was trying to use an external port instead of the internal one.

**Comment by burak-sayici** [comment]
Hello @githubsaturn 

I have 2 computers on my network and one of them has caprover installed. I want to redirect the domain from caprover to my other computer using reverse proxy. I think I will have a problem with the same network. If I added another docker container I would add " - captain-overlay-network" but I want to redirect to another physical computer on my network. How can I do this?
Example: caprover is installed at (192.168.1.10).
I created a new reverse proxy application (test.testttt.com.tr)
I want to forward this address to a physical address on the same network (192.168.1.30:2080) 
Unfortunately, when I type "http://192.168.1.30:2080" into the reverse proxy application, I cannot access it. What can I do?

**Comment by githubsaturn** [comment]
@burak-sayici - your approach is correct. But likely you have a firewall rule that prevents that connection. To confirm this, try shelling into a container on your CapRover server and see if you can curl into the other IP.
```
docker exec -it $(docker ps --filter name=captain-captain -q) curl http://192.168.1.30:2080 -v
```
