### ISSUE TITLE
query param to know wich version deploy

### ISSUE THREAD

**Issue by LiquidITGuy** [caprover/caprover#687]
**Is your feature request related to a problem? Please describe.**
Yes : as a user of gitlab for autodeployment, I'm really sad that the webhook cannot take commit hash number or tag. When I'm making my automation on my 3 environnements, I cannot decorelate the production from the branch or make easy roleback. (having master at c means i have to deploy c and cannot deploy c on preproduction and b on production) (or roleback from c to b if there are to many regressions reported by my tools

**Describe the solution you'd like**
adding a query param with commit hash would be great

**Describe alternatives you've considered**
any other way to identify wich version to deploy (tag for exemple) on query params

**Comment by githubsaturn** [comment]
This will cause redundancy as the webhook internally knows what branch to pull. Having a commit hash pollutes the API by resulting in a  "priority-based" selection that will cause problems down the line.

The way this should be being handled is by having multiple branches, for example:
```
- production
- staging
- development
```
You first merge your branch into `staging` and if you're happy with the result, you merge it into `production`.
