### ISSUE TITLE
new one app model variable/function 

### ISSUE THREAD

**Issue by LiquidITGuy** [caprover/caprover#689]
**Is your feature request related to a problem? Please describe.**
not so much but a little bit :D 
as a user, it's boring to complete the useless passwords (I mean, the dataBase Password is useless as a end user, I just need the password main app for a lot of application (at least the one who takes the db configuration on env vars))
But as developper, I cannot put a default password (not secure) for this db.

**Describe the solution you'd like**
I would like to have a $$cap_random_1, $$cap_random_2, $$cap_random_X variables who are random fields who can be use as password by default 
(the 1, 2, 3...) would be used to : 
- use the same password for the db and the main container to configure the db
- to be shown at the end if the user need it once or for information

**Describe alternatives you've considered**
new variables attributes ?

**Comment by githubsaturn** [comment]
See https://github.com/caprover/caprover/issues/637
