### ISSUE TITLE
How can I use my CloudFlare SSL in an app [Question]

### ISSUE THREAD

**Issue by ulises-castro** [caprover/caprover#692]
I tried configuring my CF ssl into my app but it didn't work.
I change SSL directories in Nginx app (captain/data/nginx-share/ key/pem file).
        listen              443 ssl;
        ssl_certificate     /captain/data/nginx-shared/mysite.crt;
        ssl_certificate_key /captain/data/nginx-shared/mysite.key;
And CF is just saying "Invalid SSL Certificate"

Could anyone help me?

**Comment by githubsaturn** [comment]
` /captain/data/nginx-shared` is mapped to `/nginx-shared` inside the container. Change your instructions to 
```
ssl_certificate /nginx-shared/mysite.crt;
ssl_certificate_key /nginx-shared/mysite.key;
```
