### ISSUE TITLE
Restart containers in regular intervals

### ISSUE THREAD

**Issue by JosXa** [caprover/caprover#696]
As Caprover's goal is to be as simple and low-effort as possible for the end-user, I think it would be a good idea to have an option of automatically recycling the docker containers e.g. every day. 
I have seen memory leaks in the prebuilt one-click apps, and it looks like they keep filling up my available RAM and the next day I come back to my instance it's barely usable anymore (4 GB on Scaleway in my case). 

The same thing goes for "homemade" applications, where this feature can be helpful to force yourself to build properly-architected stateless apps that can survive and possibly load balance/fail over if one instance goes down or gets reset. Essentially Caprover would help you with chaos testing. In times of containerization it seems like a very standard pattern to me to rather recycle applications regularly than spend hours and hours trying to debug small memory leaks (especially for apps that you don't own).

Maybe this is already possible, if so please enlighten me :)

**Comment by JosXa** [comment]
I suppose I could somehow script this myself if the API has an endpoint for setting the instance count? 🤔

**Comment by githubsaturn** [comment]
This is not something that we would integrate into CapRover core. It's very usecase specific and it's a result of a memory leak bug in those apps (or maybe simply caching...). Regardless, this is something you can simply achieve by running a simple script like this on a cron job:

```
#!/bin/bash
all_services=$(docker service ls --format {{.Name}})
for srv in $all_services
do
  docker service update $srv --force
done

```
