### ISSUE TITLE
Hiding server information for better security

### ISSUE THREAD

**Issue by davidmpa** [caprover/caprover#697]
How can I hide server information (nginx version, OS version, ...) from the public, if someone tries to attack my server?

I have 2 questions that are more specific:

1. If I visit a not yet configured subdomain captured by the wildcard, CapRover will display an App Not Found page. 
  1.1 How can I configure CapRover to not resolve the subdomains not assigned to apps at all?
  1.2 How can I customize the error page?
2. The server responses with my nginx version in the `Server` header. How can I disable this? Are there more I can do to reduce the information an attacker can get from probing the website?

I think answers to these questions can also make good guides in the documentation :)

(Sorry if the questions are trivial, I'm still new to the backend world)

**Comment by davidmpa** [comment]
I found [this post](https://serverfault.com/questions/214242/can-i-hide-all-server-os-info/1015876) that suggests adding `more_clear_headers Server;` to the nginx configuration file. However the nginx version used by CapRover is not compiled with this feature, and simply adding this line will make CapRover infinitely restart.

Someone suggests installing [`libnginx-mod-http-headers-more-filter`](https://serverfault.com/questions/214242/can-i-hide-all-server-os-info/1015876#comment1278273_766634) package. Could you add this package to the Docker image of CapRover?

**Comment by githubsaturn** [comment]
You can do all of these by modifying NGINX Configurations. Navigate to Settings > NGINX Configurations > Load Default and Edit. Note that this is an advanced process and if you make a mistake your entire instance will be inaccessible.

**Comment by davidmpa** [comment]
@githubsaturn Thank you for the reply! While `server_tokens off;` does work, which hides the version number but not the server type, `more_clear_headers Server;` does not, which requires the [`libnginx-mod-http-headers-more-filter`](https://serverfault.com/questions/214242/can-i-hide-all-server-os-info/1015876#comment1278273_766634) apt package to be installed.

Could you add this package to the Docker image of CapRover? It allows a lot of freedom to customize the HTTP headers nginx responses.

**Comment by githubsaturn** [comment]
CapRover uses official images and we won't add extra functionalities based on one-off needs, please see [scope and goals](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope)

Having said that, you can customize the nginx image with any module that you'd like by overriding the configs, see here: https://caprover.com/docs/troubleshooting.html#customize-config-settings

**Comment by HeaPengVeng** [comment]
hello do we have a solution for this yet?
