### ISSUE TITLE
Renaming an app deletes it randomly

### ISSUE THREAD

**Issue by s-kris** [caprover/caprover#701]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

This happened randomly few times. But I'm not able to reproduce consistently.
Given how it deletes the entire app upon renaming I think it's worth while to have a look.

Thank you. 

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version? 
Ubuntu 18.04
- RAM?
4GB

**Comment by githubsaturn** [comment]
@s-kris two thanks for filing this issue: 
* When this happens, do you get a success message saying that `AppName is renamed` or a failure? 
* When this happens, please take a dump of the logs to see what's going on:
```
docker service logs captain-captain --since 5m
```

**Comment by s-kris** [comment]
1. No message at all. Just redirection to apps page.
2. Sure. I'll post it here.

Thank you!

**Comment by JosXa** [comment]
I've also had this happen. It's probably reproducible if you try often enough

**Comment by githubsaturn** [comment]
Anything in particular about this?
- Did it have a persistent volume?
- Was it during a deployment?
- Was it done quickly after another action (less than 5sec apart)?
- Anything else?

**Comment by githubsaturn** [comment]
Also **please get the log** when this happens
```
docker service logs captain-captain --since 5m
```

**Comment by githubsaturn** [comment]
Thanks for the logs! Definitely useful! Found the issue, fixed it, and fixed a few other potential bugs!!
