### ISSUE TITLE
Sample apps don't work

### ISSUE THREAD

**Issue by creativefisher** [caprover/caprover#702]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Whenever I try to upload any of the tar files from sample apps in this repositury, I get this error:

Build has failed!
----------------------
Deploy failed!
Error: TAR_BAD_ARCHIVE: Unrecognized archive format

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
@creativefisher 

Which ones are you trying and how are you trying them? I just tried php, node and python. All 3 of them worked fine. For example for php one, do this:

- Download the tar from this link: https://github.com/caprover/caprover/raw/master/captain-sample-apps/php.tar
- Navigate to your dashboard, go to `Deployment` tab. Select your tar file that you just downloaded and click on `Upload & Deploy` button:
![image](https://user-images.githubusercontent.com/10582082/84339356-48895980-ab6c-11ea-9464-758ad4525fec.png)

Does this resolve your issue?

**Comment by githubsaturn** [comment]
Feel free to reopen if the issue still exists

**Comment by evangineer** [comment]
I ended up here 4 years later, because I had the same issue.

The [instructions given here](https://caprover.com/docs/get-started.html#step-5-deploy-the-test-app) don't match the instructions you gave.

What causes the confusion is the wording:

> Then, download any of the test apps [here](https://github.com/caprover/caprover/tree/master/captain-sample-apps), **unzip** the content.

So of course, I downloaded `ruby-rack.tar` and tried to untar it:

```
root@Ubuntu-2204-jammy-amd64-base ~/captain-examples # tar vxf ruby-rack.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
At this point, I'm wondering what's going on:

```
root@Ubuntu-2204-jammy-amd64-base ~/captain-examples # file ruby-rack.tar
ruby-rack.tar: JSON data
```

That's when I decided to search Issues.

Now I have uploaded the file and it's successfully built.

Please rewrite Step 5 to be clear and unambiguous.

**Comment by evangineer** [comment]
Hah, on closer examination I found the problem.

https://github.com/caprover/caprover/blob/master/captain-sample-apps/nginx-php-advanced.tar

isn't the same as

https://github.com/caprover/caprover/raw/master/captain-sample-apps/nginx-php-advanced.tar
