### ISSUE TITLE
Expose terminal access to each app through the web browser

### ISSUE THREAD

**Issue by r-chris** [caprover/caprover#705]
**Is your feature request related to a problem? Please describe.**
I just finished setting up poste.io (as a one click app) and was asked to set the password for the admin on my first visit to the app page. I did that, but managed to have a typo in the password (or maybe I simply can't remember what I intended to type there).

Either way, I am now looking for a way to access the container contents with ease to change the relevant config files as this particular password was not defined through environment properties.

**Describe the solution you'd like**
I would like to be able to access the app through an in-browser terminal.

**Describe alternatives you've considered**
If SSH was enabled in that app container, I assume I could have just used that.

I can also SSH into the CapRover master node and attach a terminal to that docker container instance and find the relevant config file that way, but now I have to remember the right syntax to attach myself to a running docker container.

Please let me know if this is considered too complex / unmaintainable of if you think this might be a considerable useful feature.

**Comment by githubsaturn** [comment]
This has been discussed in the past. For example see this: https://github.com/caprover/caprover/issues/625

In short, interactive command line won't work nicely with a pull based API. Use portrainer in parallel with CapRover for these use cases.

**Comment by r-chris** [comment]
Good to know - thanks for the quick feedback!
