### ISSUE TITLE
[Question] How to verify cluster is working?

### ISSUE THREAD

**Issue by nahtnam** [caprover/caprover#710]
Hello, I want to start off by saying I love caprover, its amazing! Two question:

1. I have successfully set up a cluster, but how can I verify that traffic is actually going to it? I added a worker node, and upped my deployment count to `3`.
2. How do I know when a deployment is done? It seems like when I run the deploy command, it just says that the build was pushed to the registry. But I assume that it takes some time for the servers to download the build and start it. Is there a way to make it so that the `deploy` command waits for the x nodes are up (like in kubernetes)?

**Comment by githubsaturn** [comment]
The process is asynchronous so there is "wait" involved. Also, at any point in time, the distribution of the services on nodes can change in the background. For example, if one node is overloaded, one of your services may die and get created on another node automatically.

How to know if you cluster is working fine:
1- Run `docker service ps srv-captain--yourappname` and view the output. More details [here](https://docs.docker.com/engine/reference/commandline/service_ps/)

2- Write a simple app that outputs the IP address of the node it's sitting on, then scale it to 5 or more and keep refreshing your webpage to view the UI. The reported IP changes every now and then. When using this method, make sure to use full refresh (ctrl+shift+R), regular refresh (ctrl+R) takes you to the same instance every time.
