### ISSUE TITLE
[Question] password change option via cli

### ISSUE THREAD

**Issue by technluxinc** [caprover/caprover#712]
please add password change option via cli or add random password option because of captain42 default password if some one found open port they can access server without any permission until the password change so if you add any of this 2 option that would be great

**Comment by githubsaturn** [comment]
It's already available. You can set a custom password by adding  `-e DEFAULT_PASSWORD='custompassword' ` to your installation script:

```
docker run -e DEFAULT_PASSWORD='custompassword'  -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

And your password will be `custompassword` right after installation. Then during `serversetup` you can change it to a super secure password.
