### ISSUE TITLE
[Question] Accesing NetData without caprover ui

### ISSUE THREAD

**Issue by jappyjan** [caprover/caprover#714]
I would like to use the iPad App "NetData" (inofficial NetData Client) to connect to the NetData instance of my caprover.
What are the credentials I need to use? Or is this not possible at all?

![48D40CE3-E5FF-4614-AE39-40CF606E966E](https://user-images.githubusercontent.com/10154260/84769594-66284a00-afd6-11ea-857a-f309839e9d4e.png)

![ADD90093-8475-4618-9F21-BACCE407FD22](https://user-images.githubusercontent.com/10154260/84769981-10a06d00-afd7-11ea-9f02-b2c800a28a56.jpeg)

**Comment by githubsaturn** [comment]
NetData on CapRover is authenticated via CapRover's authentication pipe. The authentication that this unofficial app is using is perhaps the simple http auth which is definitely less secure.

Keep in mind that you can always run containers in parallel to CapRover without effecting CapRover inner workings. So if you want to run another instance of NetData on your machine which is not authenticated by CapRover you can do so.
