### ISSUE TITLE
[Question] Is it expected that the app instance count does not update automatically when changed externally?

### ISSUE THREAD

**Issue by r-chris** [caprover/caprover#715]
CapRover allows the user to change the instance count of an app. Is this metric stored somewhere "inside" of CapRover or how is it determined?

For example - how does CapRover know how many instances of an app should be present after a restart of the main CapRover server?

I am asking this, because I came across your recommendation to use portainer for more detailed inside into the current state of the docker swarm. In portainer I noticed that when changing the instance count through CapRover, it also changes inside portainer (e.g. from 1 to 3) - so far so good!

However, when I tried this the other way around (change it from 3 to 2) inside portainer, the instance count is still shown as 3 inside of CapRover. In reality, there are in fact only 2 instances of my app running, but CapRover is still showing "Instance Count: 3".

I understand that this may be expected behaviour?

**Comment by githubsaturn** [comment]
CapRover keeps a copy of some parameters of your service. It syncs them one way - not two ways. In general, swarm parameters are:
1) Either controlled by CapRover - they get re-set every time you click on `Save & Update` button.
2) They are not controlled by CapRover - you  can change them outside of CapRover and CapRover does not override them.

**Comment by r-chris** [comment]
Thanks that clears things up for me!
