### ISSUE TITLE
[Question] What is the maximum number of a single app's custom domains?

### ISSUE THREAD

**Issue by hoangtuan151** [caprover/caprover#716]
Hi team,

Many many thanks for your awesome project.
I've read the docs, but cant find out:
1. What is the maximum number of a single app's custom domains?
2. Is it possible to edit app' setting via API (e.g. invoke an API endpoint to add a custom domain to the app without the need to access Dashboard)?

Pls help me clarify. Thanks in advanced!

**Comment by githubsaturn** [comment]
1. There is no limit imposed by CapRover.
2. Yes, but it's not officially supported. All actions taken by the web UI and command line tool are doable via directly calling the API: https://github.com/caprover/caprover-cli#api
