### ISSUE TITLE
[Question] Deploy application using multi-stage Dockerfile

### ISSUE THREAD

**Issue by mmenozzi** [caprover/caprover#717]
Hi all,
is it possible to deploy an app using a specific stage of a [multi-stage](https://docs.docker.com/develop/develop-images/multistage-build/) Dockerfile?

For example I'd like to deploy an application using the `sylius_php` stage of [this Dockerfile](https://github.com/Sylius/Sylius-Standard/blob/1.7/Dockerfile). 

It would be great if given this `captain-definition`:
```json
{
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile",
  "dockerfileTarget": "sylius_php"
}
```
CapRover would run the following build:
```
docker build --target sylius_php -t my-sylius-php:latest ./Dockerfile
```

**Comment by githubsaturn** [comment]
You can use multistage dockerfiles, but we won't be exposing special use-case flags such as `target` isn't part of the roadmap.

**Comment by mmenozzi** [comment]
Ok thank you!
