### ISSUE TITLE
Dashboard only shows "Captain Root Domain Configurations"

### ISSUE THREAD

**Issue by banagale** [caprover/caprover#719]
First, thanks for working on this. I'm used to rolling my own servers and only recently had to seriously use heroku for client and watch how bad the costs scale. Hoping caprover can be useful to me.

**What is the problem?**
The option to change root domain configurations should not be the first thing shown to a user in the dashboard for the `captain.rootdomain` web app.  This should instead be in some a settings tab, since it is not dashboard information.

**Background:**
Granted, this was my first experience with caprover so I did not know what I was doing other than following the docs.  

I finished `caprover serversetup` and the final output is `CapRover server setup completed: it is available as my-capname at https://captain.foo.mydomain.com`

And then, I proceeded to that address and it worked, which was great. However, then I saw the Domain Configurations UI. 

The way this UI looks, it appears as though you need to complete another step before you see a "dashboard."  However, it is pretty common for web apps to sort of wizard you through steps. And because it is called a Dashboard, I thought perhaps I did need to re-establish the root domain to "see the real dashboard."

When I entered the already linked root domain this warning was shown:

<img width="399" alt="Screen Shot 2020-06-23 at 5 07 54 PM" src="https://user-images.githubusercontent.com/1409710/85496109-9e102e00-b590-11ea-946e-53d4474c92c8.png">

You might think this would stop someone, and I did worry enough ask in Slack about whether I should proceed or not. But I wanted to get to using this thing, and it does say it can be re-enabled.

However, what I found was that by using the same root domain I broke ssl and there was no clear path to fixing it. I've tried various ways to get my setup into a good state again but am now stuck trying to set up this staging domain. 

I searched past tickets and found #299. And apparently the UI controls. Someone on slack mentioned the root domain controls were previously disabled but were re-enabled.

I'm unclear on how to clear out my local CLI, even after npm uninstalling and reinstalling the CLI to try to wipe out what I had done.

As a reference, in trying to right this ship I encountered both `Error Code: 1105  Message: Password is incorrect.` and `Something bad happened: cannot save ... at ... Error: self signed certificate`. 

Due to various mishaps. I noticed a ticket #672 referencing the self signed certificate. I don't know about that fellow but I was not trying to self-sign. This appeared to be some conflict related to trying to fix my ssl.

--

**Steps to reproduce the problem:**
 - Install Caprover DO image
 - Set up DNS entries as docs indicate
 - Run `caprover serversetup`
 - Visit domain and be confused at what's on dashboard 
 - Enter root domain used in CLI setup.
 -> Broken ssl, unclear how to completely start over what you screwed up-state.

**Comment by githubsaturn** [comment]
Thanks for the suggestion. A few notes:
- You can clear your local data by running `caprover logout`
- You can manually reset the SSL settings on your server by running this:
```
docker service scale captain-captain=0

nano /captain/data/config-captain.json
# find "forceRootSsl" and change it to "false" - make sure your customDomain is correct.

docker service scale captain-captain=1
```

**Comment by githubsaturn** [comment]
An additional message is added and will be part of the next release
![image](https://user-images.githubusercontent.com/10582082/85925697-2b40d480-b868-11ea-945e-6b42f2f5fb96.png)
