### ISSUE TITLE
Redismod fails to deploy after port remapping

### ISSUE THREAD

**Issue by ronalddas** [caprover/caprover#720]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Am trying to deploy redismod image, using the official [Dockerfile](https://raw.githubusercontent.com/RedisLabs/redismod/master/Dockerfile). After the App has been deployed , The container is up and running fine, redis is ready to accept connections.  
But when I do a custom port mapping (say serverport:6379 and containerportL6379), the container shutdowns.  
I dont have any other redis instances running on the server
Example Log line  
```
1:M 24 Jun 2020 14:19:20.392 * Ready to accept connections
1:signal-handler (1593008445) Received SIGTERM scheduling shutdown...
1:M 24 Jun 2020 14:20:45.837 # User requested shutdown...
1:M 24 Jun 2020 14:20:45.837 # Redis is now ready to exit, bye bye...
```

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

1. Create a new App (without persistent data)
2. Deploy app using above linked dockerfile
3. Do a custom port mapping

Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 20.04
- RAM?
8GB

Edit;
I just tried setting the port-mapping first and then building using the dockerfile, in that case the container didn't receive SIGTERM and i was able to connect to redis via my local machine.

**Comment by githubsaturn** [comment]
Does your container wakes up again after your set the port mapping or it just dies permanently?

If it dies for a bit and wakes up again, then this is expected. This is how Docker updates the services. Every time your click on `update and save` button CapRover call `docker service update.... ` which effectively restarts your container with the new configuration.

**Comment by githubsaturn** [comment]
Closing as stale. Feel free to reopen with more details
