### ISSUE TITLE
Can't access swarm web app between machines or from domain

### ISSUE THREAD

**Issue by geoge23** [caprover/caprover#721]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

I apologize if this is a simple fix or expected behavior, I'm a docker noob in general. I added 2 additional swarm nodes through the web interface and deployed two new apps, which appeared in the ```docker container ps``` of my first node and second nodes respectively. The first app is a discord.js bot that does not handle any incoming requests, which functions as expected. The second one is a web app that cannot be accessed from another computer or from its assigned domains. When accessing the container at ```app.example.com```, the NGINX container logs
`2020/06/25 03:45:44 [error] 60#60: *4623 srv-captain--test could not be resolved (110: Operation timed out), client: 192.168.69.118, server: app.example.com, request: "GET / HTTP/1.1", host: "app.example.com"
128.14.134.134 `
and returns a 502 error.
The web app container produces the expected logs and can be pinged on the peer it is running on, but not others in the swarm.

`docker network ls` produces 
NETWORK ID          NAME                      DRIVER              SCOPE
64c004ae93b3        bridge                    bridge              local
nbq3lcljxrjv        captain-overlay-network   overlay             swarm
12ed1ce62407        docker_gwbridge           bridge              local
635b9118aa15        host                      host                local
ul7htgqz7lth        ingress                   overlay             swarm
b8ada95d3a8a        none                      null                local

and `docker network inspect caprover-overlay-network` produces [this](https://pastebin.com/y4460BTp) on the leader node and [this](https://pastebin.com/Q1DWFiHE) on the other node

Steps to reproduce the problem:

1. Create a registry and add a node to the swarm
2. Deploy an app that is created on the second node
3. Attempt to access the app from its URL

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu Server 20.04 LTS w/ Docker v19.03.11

**Comment by githubsaturn** [comment]
Do you have all the following ports open on both nodes?

```
ufw allow 7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;
```

**Comment by githubsaturn** [comment]
Closing as stale. Feel free to reopen with more info.
