### ISSUE TITLE
[Question] What is your view on the future of docker swarm?

### ISSUE THREAD

**Issue by r-chris** [caprover/caprover#722]
We are in the process of moving a client from a deprecated CloudFoundry environment to a new service provider. We very much like CapRover and would like to use it. However, we are a bit concerned about the future of "docker swarm". What is your view on the future of CapRover in relation to the statements Mirantis has made regarding the future of docker swarm?

In case they retire docker swarm in 1.5 years, would that essentially be the end of CapRover as well?

According to Mirantis, they [would like to continue to maintain it](https://www.mirantis.com/blog/mirantis-will-continue-to-support-and-develop-docker-swarm/), but they also said that [Kubernetes is going to be the future](https://www.mirantis.com/blog/mirantis-acquires-docker-enterprise-platform-business/). Most recently Mirantis talked about the pros and cons of [switching from Docker Swarm to Kubernetes](https://www.mirantis.com/blog/swarm-to-kubernetes/).

**Comment by githubsaturn** [comment]
There is nothing in the short term roadmap to migrate to k8s. Having said that, it's not a hard no. When the time comes, we might migrate to k8s. In that case, we probably provide instructions to a painless migration. But for now, Docker swarm is a much better choice for CapRover due to its simplicity.

**Comment by r-chris** [comment]
Thanks - that makes sense to me!

**Comment by Berndinox** [comment]
"is a much better choice for CapRover due to its simplicity."

However, Kubernetes would be much better choice related to scaling.
CapRover on K8s would be perfect.

**Comment by coderofsalvation** [comment]
Maybe podman could help out here, it's API is backwardscompatible with docker & docker-compose (and adds extra features):

https://www.redhat.com/sysadmin/compose-kubernetes-podman

**Comment by Berndinox** [comment]
Knative!
