### ISSUE TITLE
[Deployment Issue] Nginx.conf not updating?

### ISSUE THREAD

**Issue by Nezia1** [caprover/caprover#723]
## What is the problem?
I modified the nginx.conf file using the web dashboard template. I tried to add a redirect from my www domain to my non www domain but it's not working. It doesn't seem to register the config file, I went to check in the container and it didn't show the line I added (I added the lines all the way to the top, above the ejs if statement). However, when I check inside the /captain/generated/nginx/nginx.conf file, it shows the lines, but not redirecting.

## Steps to reproduce the problem:
- Deploy an application with Caprover
- Add these lines at the top of your nginx.conf using the web dashboard:
```nginx
server {
    listen 80;
    server_name www.example.com;
    return 301 $scheme://example.com$request_uri;
}
```

## Answers to the following questions if applicable:
- Your OS and version?
Ubuntu 18.04
- RAM?
1GB

**Comment by githubsaturn** [comment]
> I modified the nginx.conf file using the web dashboard template

There are 3 different nginx configs. There are 2 under settings, and there is one per application. Apps > your app > nginx.

Which one did you modify? Please include your entire nginx config block here for debugging.

**Comment by Nezia1** [comment]
I modified the one under my app. This is the nginx config I'm using: 
```nginx
server {
    listen 80;
    server_name www.example.com;
    return 301 $scheme://example.com$request_uri;
}

<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri$is_args$query_string;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;

        ssl_session_cache   shared:SSL:20m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;


        # Mozilla Intermediate configuration. tweak to your needs.
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
```

**Comment by Nezia1** [comment]
Also on a side note, I have a Vue.JS application using history mode, and I tried adding the block to redirect all requests that aren't static files to index.html and it didn't change anything either.

**Comment by githubsaturn** [comment]
@Nezia1 I just tried this and it works fine. Try these steps:
- Create a new app
- Add this bit to the top of the config:
```
server {
    listen 80;
    server_name www.example.com;
    return 301 $scheme://example.com$request_uri;
}
```
- Make sure `www.example.com` points to the IP address of your CapRover
- Then navigate to `www.example.com`

**Comment by Nezia1** [comment]
It doesn't work for some reason, the redirect doesn't work. I tried putting it inside the if s.forceSsl block and it does not redirect either. What could be wrong?

**Comment by Nezia1** [comment]
Maybe it's because of my Dockerfile? Could the nginx command be wrong and not read the config file from the captain folder? This is my Dockerfile: 
```dockerfile
FROM node:lts-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine as production
COPY --from=builder /app/public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by Nezia1** [comment]
Okay so it worked after I removed the two last lines, since I figured it would interfere with CapRover's way of handling Nginx, however when I go to https://www.example.com, it doesn't redirect me, only when I go to www.example.com.

**Comment by githubsaturn** [comment]
Of course `https` shouldn't work because you haven't created an SSL certificate for that domain.

A few points here:
You dockerfile should be taken out of the picture, that's why I asked you to create a **new app** and [perform theses actions](https://github.com/caprover/caprover/issues/723#issuecomment-651463001)

If you want HTTPS to also redirect, it's very simple, do this:
- Revert all your previous custom nginx settings.
- Create a new app, call it `dummy-redirect`
- Connect `www.example.com` to this app
- Enable HTTPS for `www.example.com`
- Enable `Force HTTPS by redirecting all HTTP traffic to HTTPS`
- Edit Custom Nginx Config for `dummy-redirect`, and find this block towards the bottom:
```
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
```
- Delete this block and just replace it with one line:
```
    return 301 https://example.com$request_uri;
```

**Comment by Nezia1** [comment]
Thanks, it ended up working!
