### ISSUE TITLE
[Deployment Issue] - One-click app customization in JSON template

### ISSUE THREAD

**Issue by thomascenni** [caprover/caprover#725]
**What is the problem?**
I want to extend an existing image (Bitnami CouchDB) via a one click app template.
The Docker file is very simple:

```
FROM bitnami/couchdb:3.1.0
COPY local.ini /opt/bitnami/couchdb/etc/local.d/
```

where local.ini is a file available in the host machine with the new configuration and contains something like this:

```
[couch_httpd_auth]
timeout = 432000 ;
```

Looking at the examples for one-click apps available [here](https://github.com/caprover/one-click-apps/tree/master/public/v2/apps), I understand that the COPY command won't be accepted because the JSON template is something standalone.
For this reason, I decided to use the RUN command with the 'echo' function to write the file inside the container, so my one-click app template is translated in something like this:

```
{
    "captainVersion": "2",
    "documentation": "Taken from https://hub.docker.com/r/bitnami/couchdb/",
    "description": "Apache CouchDB is an open-source document-oriented NoSQL database, implemented in Erlang",
    "displayName": "Bitnami CouchDB",
    "dockerCompose": {
        "version": "3.3",
        "services": {
            "$$cap_appname": {
                "image": "bitnami/couchdb:$$cap_couchdb_version",
                "dockerfileLines": [
                    "FROM bitnami/couchdb:$$cap_couchdb_version",
                    "RUN echo '[couch_httpd_auth]' > /opt/bitnami/couchdb/etc/local.d/local.ini",
                    "RUN echo 'timeout = 432000 ' >> /opt/bitnami/couchdb/etc/local.d/local.ini"
                ],
...
```

When I deploy the template, basically only the FROM command is executed, because I cannot see in CouchDB interface the customization I put; the log in Caprover says:
```
------------------------- Fri Jun 26 2020 17:27:54 GMT+0000 (Coordinated Universal Time)
Build started for test106
An explicit image name was provided (bitnami/couchdb:3.1.0). Therefore, no build process is needed.
Pulling this image: bitnami/couchdb:3.1.0 This process might take a few minutes.
Build has finished successfully!
```
Did I miss something ?
Thanks in advance.

**Comment by githubsaturn** [comment]
Remove this line `"image": "bitnami/couchdb:$$cap_couchdb_version",`

When "image" is present,  "dockerfileLines" is ignored.

**Comment by thomascenni** [comment]
> Remove this line `"image": "bitnami/couchdb:$$cap_couchdb_version",`
> 
> When "image" is present, "dockerfileLines" is ignored.

Thank you very much, it was so simple at the end.
+1 for Caprover product!
