### ISSUE TITLE
Error Code: 1107  Message: Verification Failed.

### ISSUE THREAD

**Issue by wilfredinni** [caprover/caprover#730]
What is the problem?
`caprover serversetup `wont verify my domain (wich looks ok in https://mxtoolbox.com/)

Steps to reproduce the problem:
Create a Caprover droplet from digitalocean marketplace, install Caprover CLI and ran` caprover serversetup`

![image](https://user-images.githubusercontent.com/23016174/86282024-74688f80-bbac-11ea-8eb7-e2d4d5536868.png)

- Your OS and version?
Ubuntu 18.04
- RAM?
1GB

**Comment by githubsaturn** [comment]
CapRover simply makes a request to `http://RANDOM-UUID.root.domain.com` to verify your root domain. Are you sure that you assigned a wildcard entry to this IP?

**Comment by wilfredinni** [comment]
this is the setup of the domain
![image](https://user-images.githubusercontent.com/23016174/86305726-63397600-bbe0-11ea-8cd9-9aae5acb3287.png)

and the the browser
![image](https://user-images.githubusercontent.com/23016174/86305766-83693500-bbe0-11ea-8333-fd256249edb3.png)

I may be missing something, but I have been following the docs.

**Comment by githubsaturn** [comment]
That's not correct. What docs are you following?

See the official docs [here](https://caprover.com/docs/get-started.html#step-2-connect-root-domain)

> To confirm, go to https://mxtoolbox.com/DNSLookup.aspx and enter randomthing123.something.mydomain.com and check if IP address resolves to the IP you set in your DNS. Note that randomthing123 is needed because you set a wildcard entry in your DNS by setting *.something as your host, not something.


As mentioned in the docs you have to set `*.something.domain.com`.

**Comment by wilfredinni** [comment]
ok, my fault... tried to do it in a rush. Sorry to make you lose your time. Thank you!

**Comment by githubsaturn** [comment]
No worries - once you set up the wildcard, everything should work. Feel free to reopen if you still have issues.
