### ISSUE TITLE
[Question] Deployed app using cert issued by CapRover.com not LetsEncrypt

### ISSUE THREAD

**Issue by DailenG** [caprover/caprover#739]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: I tested deploying an app by trying out Droppy, I'm unable to visit via Firefox because of a certificate issue and HSTS is enabled. When I checked the cert, it shows it was issued by CapRover.com not by LetsEncrypt. I don't see any options to change certs or any indication of why it would be using that cert as opposed to one issued by LetsEncrypt.

**Comment by githubsaturn** [comment]
You're seeing [the fake certificate](https://github.com/caprover/caprover/blob/master/template/fake-certs-src/nginx.crt) that CapRover uses just to block the unassigned domains. You need to enable HTTPS for your domains before enabling Force to HTTPS options:
![image](https://user-images.githubusercontent.com/10582082/86492694-f4256400-bd3c-11ea-8dbe-c22363cea291.png)

Did you do thise?

**Comment by DailenG** [comment]
I didn't do anything to it, I just installed the app and tried it straight out of the box so to say. HTTPS was working for the root domain. I must have got the impression that HTTPS would be enabled by default. It looks like the app enforces it's own HTTP to HTTPS redirect so that's probably what made it more confusing.

**Comment by DailenG** [comment]
Okay so after enabling HTTPS it's now working, thanks for the assist 😎
