### ISSUE TITLE
Private Key Encryption and Environment Variables Hiding

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover#742]
**Is your feature request related to a problem? Please describe.**
Private keys are exposed / visible in the dashboard with no way to prevent that. Should the password to the dashboard be brute-forced, it could lead to security vulnerabilities. The same problem occurs with environment variables; platforms such as Travis CI make sure to hide the variables in their dashboard once they've been added.

![image](https://user-images.githubusercontent.com/1344906/86507568-e2e26300-bde1-11ea-9c07-8cee3fc75109.png)

![image](https://user-images.githubusercontent.com/1344906/86507438-ec1f0000-bde0-11ea-94b0-e5cc512ac21a.png)

![image](https://user-images.githubusercontent.com/1344906/86507578-fee60480-bde1-11ea-8908-ff8de8b90871.png)

**Describe the solution you'd like**
Once a private key has been entered, it should get removed from the dashboard and optionally encrypted using GPG, then stored on disk. As for the environment variables, they should be hidden in the dashboard once added.

**Describe alternatives you've considered**
This could be prevented for most use cases if there was support for deploying through GitHub or GitLab, but as discussed before in #615 and other related issues, this is beyond the scope of this project unfortunately. Another suggestion that could aid in security is #493.

**Comment by githubsaturn** [comment]
> Should the password to the dashboard be brute-forced, it could lead to security vulnerabilities

If you password is leaked - you have bigger problems! Not showing the env vars on the dashboard does NOT provide any security benefit in that case. 

Heroku for example displays your env variables on the dashboard. Hiding environmental variables on the dashboard is not a security enhancement, it's the **false** feeling of security enhancement. 


I'm gonna make it very clean why it doesn't add ANY security benefit:
Imagine I am the bad actor and I have access to your dashboard. Even without the variables displayed on the dashboard I can extract them. How? Here:
- Write a small problem that prints all env variables and deploy it as the image to your app
- Look at the logs and there you go! Found all secrets!
You might say, okay, why don't we be super fancy and block logs from being transmitted to the web app. That is also breakable:
- Write an app to capture all requests and puts them in a db
- Deploy that app to your own server
- Now write a small program to read and send all env vars and keys and publish them to your request saving app!
- Now you have all the secrets!

**Comment by fr3fou** [comment]
I agree with your points regarding the environment variables, but what about the private key issue?

**Comment by githubsaturn** [comment]
Same with private keys, it's a little bit fancier, but still vulnerable:
Keys are saved in in `/captain/data/config-captain.json` file and are fully encrypted in case the "content" gets compromised, the decryption key is a Docker secret and stored securely in Docker swarm. But if the main access is compromised:
- Bind to Docker socket
- Bind to `/captain` directory
- Now that you have access access to Docker sockets, you can get all Docker "encrypted secrets"
- Use the key to decrypt all secure content of `/captain/data/config-captain.json`
