### ISSUE TITLE
[Question] Connect to apps created from one-click from host

### ISSUE THREAD

**Issue by wiradikusuma** [caprover/caprover#746]
I have successfully installed CapRover using Docker Desktop in Windows 10 and WSL 2. I have created some apps from one-click, namely PostgreSQL and Redis.

My question: How do I connect to that PostgreSQL instance using e.g DBeaver in the host system (Windows 10)?

Upon creating the instance, I did see `Postgres is deployed and available as srv-captain--pg-db:5432 to other apps. For example with NodeJS...` but I can't even ping `srv-captain--pg-db`.

**Comment by githubsaturn** [comment]
Are you sure you don't have a typo? Are you using the right service name? You can get the service name via `docker service ls`.

Login to the [demo website](https://captain.server.demo.caprover.com) and navigate to `wordpress-wordpress`. You can see under app config that it's using `srv-captain--wordpress-db`.

Two potential problems: either you have a typo, or on windows, Docker DNS is misbehaving.

**Comment by wiradikusuma** [comment]
I'm not talking about container-to-container, what I want is from the Windows host ("external world") to the containers.

Section "Allowing Containers to Talk to Each Other + the Outside World" in https://nickjanetakis.com/blog/docker-tip-59-difference-between-exposing-and-publishing-ports is what I'm looking for.

**Comment by githubsaturn** [comment]
Port mapping: https://caprover.com/docs/database-connection.html#external-connections

**Comment by wiradikusuma** [comment]
Exactly what I'm looking for. Thank you!
