### ISSUE TITLE
nginx URL size limit

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#747]
I am running a node app (with express) that receives GET requests... I am finding that when the URL reaches a certain size, nginx chokes.  Empirically this seems to be around 5kb but some references out there suggest that the default is 8kb (e.g. [here](https://medium.com/aviabird/413-414-request-url-entity-too-large-error-nginx-b6dcece6f5dd)).  What is the size limit for nginx in CapRover?  And how do I change it for a specific app?  It's not crucial, because I can use POST instead of GET but I'm partly curious how to do it.

**Comment by githubsaturn** [comment]
All nginx configs for CapRover are in these 3:
- base: https://github.com/caprover/caprover/blob/master/template/base-nginx-conf.ejs
- dashboard and registry: https://github.com/caprover/caprover/blob/master/template/root-nginx-conf.ejs
- each app: https://github.com/caprover/caprover/blob/master/template/server-block-conf.ejs

The only customization that I see that's somewhat related to the URL length is `    server_names_hash_bucket_size 128;` which increases the maximum size for the domain name. Other than than, if you have any app specific customization, you can definitely make the change in your nginx config in for a specific app.

**Comment by githubsaturn** [comment]
If that's what you decide to do, navigate to your app, under HTTP settings > Edit Nginx Configuration and find [this block](https://github.com/caprover/caprover/blob/master/template/server-block-conf.ejs#L69-L73)

Add your customization above or below this block.

**Comment by drmrbrewer** [comment]
Hmm, can't find a way to increase the URL length limit.  Maybe it's not an nginx limit but a node/express limit.

Try [this url](https://test.mercury.cloud3squared.com/testing/N4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMN4Ig7glgJg5gpgFwMIg7glgJg5gpgFwMN4Ig7glgJg5gpgFwMIg7glgJg5gpgFwMN4Ig7glgJghfuejinmnda)... it loads fine... but add one more character at the end and it fails.

All this express route is doing is:

    res.send(`param length: ${req.params.param.length}`);

**Comment by githubsaturn** [comment]
According to [nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers), you can put `large_client_header_buffers` in http or server block. So if you want it to be app specific, you should not have it in the place that I mentioned in my [first comment](https://github.com/caprover/caprover/issues/747#issuecomment-653930045) on this thread. Because that's inside `location` block.

Instead, it should be inside the server block, so the line after `server_name  <%-s.publicDomain%>;` should work.

**Comment by drmrbrewer** [comment]
Thanks.  It's interesting because doing that had no effect.  But I think it may not be a limitation being imposed by nginx, but rather a limitation being imposed by the browser.  

For instance, browsing to [this URL](https://test.cloud3squared.com/testing/N4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJg5gpgFwMoBN4Ig7glgJsidfisjdpktr_last_one) in Edge is fine... the entire parameter is received and the length is correct.  But add any extra characters at the end, and it doesn't choke... but the parameter is truncated at length 2044.

With Chrome it seems that you get get up to length 5179 without any problems (the link in my earlier post), and adding one more character makes the request fail unlike Edge.

So it seems that it is a limitation of the browser.  In my case the URL is being called from within an Android WebView, so based on Chromium... I guess that I must look there to see what limit is imposed.

**Comment by githubsaturn** [comment]
Yea that may be right. I suggest reaching out to nginx forums for finding the root cause.
