### ISSUE TITLE
[Deployment Issue]Wiki.js not generating db

### ISSUE THREAD

**Issue by millernw** [caprover/caprover#748]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
When attempting to deploy a Wiki.js one-click app within Caprover I get db connection errors. If it's supposed to create a Mariadb it's not doing it. I tried to create a separate app (a Mariadb app) and connect the two but still received a lot of errors. 

Based on this video, showing a deployment of Wordpress, it seems like this deployment should build the needed Mariadb for the app: https://www.youtube.com/watch?v=XDrTmGSDW3s

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
Install Wiki.js one-click app, watch the deployment app logs and you'll see the errors. Also, no other apps (e.g. MariaDb) are created and/or linked to the wiki.js app.

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
Please retry and feel free to reopen the issue if it's not fixed yet.

**Comment by millernw** [comment]
Working perfectly now. Great job and thank you!
