### ISSUE TITLE
[Question] How can I connect caprover netdata to Prometheus?

### ISSUE THREAD

**Issue by RodolfoSilva** [caprover/caprover#750]
Hey @githubsaturn,

Do you have any examples of how to connect an external prometheus to caprover's netdata?
Is there a way to access specific IP access in caprover's netdata configuration, so that it is possible to read the metrics?

Netdata provide this:

https://learn.netdata.cloud/docs/agent/netdata-security#fine-grained-access-control

```
[web]
    allow connections from = localhost 192.168.* 1.2.3.4 homeip.net
```

But how can I do this in caprover?

**Comment by githubsaturn** [comment]
You can customize config settings for CapRover: https://caprover.com/docs/troubleshooting.html#customize-config-settings

Specifically `netDataImageName`. You can rebuild an image that matches your very specific needs and use that Docker image.

**Comment by laruche** [comment]
@RodolfoSilva did you have an example ?
