### ISSUE TITLE
Can't access Caprover Dashboard

### ISSUE THREAD

**Issue by dixytudla** [caprover/caprover#752]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Hi Everyone, 

Super noob question. Sorry if it sounds silly but I'm really new to this. Hope someone can help. I installed caprover through digital ocean successfully. I was able to access the dashboard until yesterday but now it's giving me "This site can’t provide a secure connection" error. I think it may have been from allowing the Force HTTPS option. I enabled this to allow my Facebook app to get verified. 

Is there a way to disable the Force HTTPS option through an SSH connection? I appreciate you guys pointing me to the right direction. Looking forward to any help. Thanks.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1. Go to http://<myip address>:3000 on an internet browser
2. "This site can’t provide a secure connection" pops up

Answers to the following questions where applicable:
- Your OS and version? : Ubuntu 18.04
- RAM? Digitalocean VM

**Comment by githubsaturn** [comment]
Did you assign a root domain to your app? If you enabled HTTPS, it means you have. In that case access your dashboard from `captain.root.domain.com`. Avoid using port 3000.

Feel free to comment if you still have questions.

**Comment by dixytudla** [comment]
Oh wow that was simple enough! Thank you so much for the help, I'm now able to sign in. Sent from my Huawei phone-------- Original message --------From: Kasra Bigdeli <notifications@github.com>Date: Thu, 9 Jul 2020, 6:35 amTo: caprover/caprover <caprover@noreply.github.com>Cc: dixytudla <dixytudla@luckyprints.com.ph>, Author <author@noreply.github.com>Subject: Re: [caprover/caprover] Can't access Caprover Dashboard (#752)
Did you assign a root domain to your app? If you enabled HTTPS, it means you have. In that case access your dashboard from captain.root.domain.com. Avoid using port 3000.
Feel free to comment if you still have questions.
