### ISSUE TITLE
[Question] What is the best way to stop a current caprover container and start it again on a different port?

### ISSUE THREAD

**Issue by unlimitedcoder2** [caprover/caprover#753]
I have tried stopping and removing all containers, 
![image](https://user-images.githubusercontent.com/16884313/86923377-db92c080-c125-11ea-98f8-5f2dfd9fff50.png)
![image](https://user-images.githubusercontent.com/16884313/86923529-1268d680-c126-11ea-95db-50223c3f3a1d.png)

but they just come back. Since it is not possible to change the mapping of the ports on a running docker container. What is the best way to change caprover to not listen on port 80/443?

**Comment by githubsaturn** [comment]
`nginx` listens to port 80 and 443 for Let's Encrypt to work. You cannot use CapRover with any other ports.

**Comment by unlimitedcoder2** [comment]
I wanted to use an nginx server that was running on the server not in a container but that would require caprover to listen on another port so I can pass all the requests that do not match the ones in the nginx to the one that caprover has so it would be running on 80 anyway.

**Comment by githubsaturn** [comment]
CapRover as it stands is not designed to be working like that. You are welcome to fork the project and rebuild the Docker image with new ports - but you might face other problems.
