### ISSUE TITLE
Fail PCI Compliance due to "Nothing here yet" page as default on ip address

### ISSUE THREAD

**Issue by thuperthecret2** [caprover/caprover#756]
My question is, is there a way to have a default app show up other than the "Nothing here yet" page when accessing the IP address?  And can this be accomplished without messing up the Let's Encrypt functionality, or without blocking access to captain.root.domain.com?

I have apps deployed properly and working, but when I try to pass PCI compliance with a network vulnerability scan on my web app URL (ie myappname.root.domain.com), the test actually goes to the IP address of my URL, which ends up at the "Nothing here yet" page.  This gives a number of compliance failures due to it hitting the caprover ssl certificate instead of my app's Let's Encrypt certificate.  The validation failures include SSL validity length (the caprover SSL certificate is valid until 2029 which is too long), the SSL certificate is self-signed, there is no HTTP Security Header detected (on both 80 and 443), the signature verification failed (not trusted Certificate Authority), and Improper Certificate Usage.  Also it says there are non-compliant external links (caprover.com) which comes from the "Read Docs" button on the page.

Thanks!

**Comment by githubsaturn** [comment]
Nginx config is completely customizable if you really need it:

- Go to settings
- Edit nginx
- Under **CapRover Config Location in nginx container** (the second block) , find this server block:
```
# Default catch-all page
```

Now you can change the server to return whatever page you want - or redirect to another page. It's just an nginx config.
