### ISSUE TITLE
[Question] Use something.mydomain.com instead of *.something.mydomain.com for my app

### ISSUE THREAD

**Issue by wiradikusuma** [caprover/caprover#759]
I have successfully deployed an app at http://myproject-backend.something.mydomain.com and now I want to make it available _only_ at https://something.mydomain.com/ — how to make that happen?

In my DNS, I have both:

	A Record: *.something -> MYIP
	A Record: something -> MYIP

I tried adding `something.mydomain.com` in `HTTP Settings` page but I always get this error:

	1107 : Verification Failed

And opening `something.mydomain.com` from the browser gives me this:

	Nothing here yet :/

**Comment by githubsaturn** [comment]
Wait a few hours and try again. If it still fails, you can temporarily disable domain verification:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by wiradikusuma** [comment]
Thanks, patience is a virtue :)

How do I _remove_ the default `myproject-backend.something.mydomain.com`?

**Comment by githubsaturn** [comment]
There is no support for native support for "removing" the default domain as it adds zero value and occupies space in the UI. If you're really interested, you can edit your nginx config to make that change. More details: https://github.com/caprover/caprover/issues/642#issuecomment-607535047
