### ISSUE TITLE
[Question] Same repository with different deploy options

### ISSUE THREAD

**Issue by Jonatha-Varjao** [caprover/caprover#760]
Amazin project @githubsaturn !

I have one question, One repository has my standard RESTFUL API and also, some celery workers, I created the CI grabbing the push changes in GitHub and deploy is done perfectly, the problem now is to set up the workers using the same repository, basically what I need is to point to another dockerfile, DockerfileAPI and DockerfileCelery something like that

I tried to read the docs, find some common issue but no success. Any help, direction is a blessing!

Thx !

**Comment by githubsaturn** [comment]
You can have multiple `captain-definition` files in your repository. Each of them can point to a different Dockerfile.

To set the location of the `captain-definition` file for a particular app, navigate to the `Deployment` tab for your app, and at the bottom of your page, you can change the path of `captain-definition`

![image](https://user-images.githubusercontent.com/10582082/87096693-5e447a00-c211-11ea-9031-794ddac07430.png)

**Comment by Jonatha-Varjao** [comment]
It was in the front of my eyes this hole time !
Thx
