### ISSUE TITLE
No such image

### ISSUE THREAD

**Issue by LHz7ak** [caprover/caprover#762]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
I've had numerous problems with Caprover so I clicked on the link update. How I have a "502 Bad Gateway" on the captain website and when I do "docker service update captain-captain --force" in terminal I get "
1/1: No such image: caprover/caprover:1.7.1
service update paused: update paused due to failure or early termination of task"

What should I do next ? Re-install caprover ? 

Steps to reproduce the problem:
Click "update" on the captain website

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
This is not a CapRover problem. Most probably your server is running out of disk or etc.

Run
```
docker pull caprover/caprover:1.7.1
```

Does this work?

**Comment by LHz7ak** [comment]
Thanks, it worked. Indeed, it was a disk space issue.
