### ISSUE TITLE
Where are Nginx files located

### ISSUE THREAD

**Issue by LHz7ak** [caprover/caprover#763]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
I am unable to locate the nginx files as described here : https://caprover.com/docs/nginx-customization.html

Can you please advise ? 

Konrad

**Comment by githubsaturn** [comment]
nginx config files are "inside" the container. The only directory that you can use to inject more files in the container is `/captain/data/nginx-shared` on the host which is mapped to `/nginx-shared` in the container.
https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by LHz7ak** [comment]
When you say "inside container" do you mean "Application Specific Config File (/etc/nginx/conf.d/captain.conf inside container)." ? If so, if I take any the example of one of my containers, this is what I see under /etc
<img width="1341" alt="Capture d’écran 2020-07-14 à 17 23 08" src="https://user-images.githubusercontent.com/4387078/87444141-b1924000-c5f6-11ea-8894-40132abf77bd.png">

As you can see, there is no nginx folder....

**Comment by githubsaturn** [comment]
On your server run `ls /captain/generated/nginx`, you should see the files. But this directory is generated on every restart. If you want to make any modification to your nginx configs you have to make the config change from your CapRover panel. Navigate to Settings and edit your nginx config there.

**Comment by terion-name** [comment]
@githubsaturn  /captain/generated/nginx contains only dhparam.pem file and nothing more. where are generated nginx files is still inknown

**Comment by githubsaturn** [comment]
See the comment above. They are in /captain/generated/nginx
