### ISSUE TITLE
[Deployment Issue] -  NextCloud

### ISSUE THREAD

**Issue by HulaCloud** [caprover/caprover#765]
What is the problem?

NEXTCLOUD errors -- "Your web server is not properly set up to resolve "/.well-known/caldav". and "Your web server is not properly set up to resolve "/.well-known/carddav".

Steps to reproduce the problem:

Deploy latest NEXTCLOUD image on DigitalOcean with the CapRover 1-click install

- Your OS and version?
- RAM?

4 GB Memory / 80 GB Disk / LON1 - CapRover 1.7.1 on Ubuntu 18.04

How do I fix these in the CapRover environment?

My DNS looks like this -- https://captain.cp.domain.ltd

The only reference I have is -- if you are running NGINX, make sure `location = /.well-known/carddav {` and `location = /.well-known/caldav {` are properly configured as described in [Nginx configuration](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html), adapt to use a subfolder if necessary.

**Comment by githubsaturn** [comment]
This is really a NextCloud question. You can edit your nginx config by navigating to Apps > your-nextcloud-app > http settings,
then click on EDIT DEFAULT NGINX CONFIGURATIONS.

Then look for this block (towards the bottom)
```
        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
```

And above this block add these:
```
    location = /.well-known/carddav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
```

Let me know if it doesn't work.

**Comment by HulaCloud** [comment]
Thank you so much for trying to help me.  I do appreciate it.  

And I can understand why you think that, but it really isn't a Nextcloud question. 

From past experience, if it were plain vanilla NginX running Nextcloud I would not have had to manually add those lines to the config file. But if I had needed to, I knew how to do it, and presumably it would have worked.  

However, adding them as and where you suggest via CapRover, as I had already tried, doesn't work. So, that was my logic for thinking it was a CapRover issue. 

Either way, it doesn't resolve the issue and Nextcloud is still showing the same errors. 

What else can I try?

Terence.

**Comment by githubsaturn** [comment]
Okay, I'll look into this.

What are the steps to reproduce the problem? Is it as simple as this:
- Install NextCloud One-Click App
- Navigate to the next cloud URL and see the error?

Where is the error shows up? On the web interface of NextCloud or in the logs?

**Comment by HulaCloud** [comment]
Steps to reproduce the errors...

1) Create CapRover droplet from DigitalOcean Marketplace

2) Deploy Nextcloud 1-Click App

3) Login to Nextcloud as admin user

4) Go to Settings > Overview > Security & setup warnings

This, by far, one of the best Nextcloud installs I have seen (and I have seen a few), but it still has this problem which, because I am new to CapRover, I don't know how to fix.

Terence

**Comment by githubsaturn** [comment]
I just tried it and was able to resolve the issue by adding the configs to nginx:
![image](https://user-images.githubusercontent.com/10582082/87841553-21612e80-c874-11ea-9cdb-d9fa87b058b6.png)


The configs added to nginx are:

```
    location = /.well-known/carddav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }

    location = /.well-known/caldav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
```

**Comment by HulaCloud** [comment]
![screencapture-vpc-hulacloud-host-settings-admin-overview-2020-07-18-09_20_53](https://user-images.githubusercontent.com/4005326/87848413-2d7ed780-c8d8-11ea-868d-79dcb072bf06.png)

![screencapture-captain-cp-hulacloud-host-2020-07-18-09_17_35](https://user-images.githubusercontent.com/4005326/87848440-6cad2880-c8d8-11ea-9219-a1d230eb5e3c.png)

So, that's strange for a couple of reasons. 

1. As you can see I have already set up my NginX config with those lines in Apps > Your Apps > [select]> HTTP Settings, but it seems to have no effect on the application. whereas, further down I have added the line `add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;` and that works fine.

2. Your install is not showing the availability of Nextcloud 19.0.1 for some reason.

Here is the complete file so that you can see if I have made any syntax mistakes -- [https://pastebin.com/yQECmpaL](https://pastebin.com/yQECmpaL)

Terence.

**Comment by githubsaturn** [comment]
Ah okay, you added the config to HTTP server block - that block is just a redirector. You should have added it to the second block:
```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri$is_args$query_string;
        }
    }
    
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Nextcloud
        location = /.well-known/carddav {
             return 301 $scheme://$host:$server_port/remote.php/dav;
        }

        location = /.well-known/caldav {
             return 301 $scheme://$host:$server_port/remote.php/dav;
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
```

**Comment by githubsaturn** [comment]
Does this help?

**Comment by HulaCloud** [comment]
Sure does. Works perfectly now. Just got to figure out how to write a www-data crontab in that deployment and we're home and dry. Many thanks.

**Comment by HulaCloud** [comment]
> I think `add_header Strict-Transport-Security "max-age=15552000;` must be in the first block [not too sure about this]

The instruction from Nextcloud was that it had to be directly below `proxy_set_header X-Forwarded-Proto $scheme;`

**Comment by githubsaturn** [comment]
> The instruction from Nextcloud was that it had to be directly below proxy_set_header X-Forwarded-Proto $scheme;

Yes - you're correct. It should be below `proxy_set_header`.

**Comment by xXKynarethXx** [comment]
Hey, I am reopening to collect all relevant information in one ticket, if that's not okay for you I will reopen another one :)
I get an error in nextcloud (freshly installed): 
There are some warnings regarding your setup.
The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
Missing index "cards_abiduri" in table "oc_cards".

**Comment by githubsaturn** [comment]
Hi @xXKynarethXx 

One click apps in CapRover are community maintained. Feel free to find the PR that last updated NextCloud substantially and comment on that. Otherwise, you can file an issue on one click apps repo here: https://github.com/caprover/one-click-apps

Or use our slack channel (find the link at the bottom of https://caprover.com/ )
