### ISSUE TITLE
Support for docker-compose

### ISSUE THREAD

**Issue by koolamusic** [caprover/caprover#768]
I noticed that one click apps are some sort of docker compose files, and was wondering can it be possible to define a `docker-compose` to deploy a project on caprover, or would the resolve be break each image into separate `Dockerfiles` and deploy with captain

**Comment by githubsaturn** [comment]
See here: https://github.com/caprover/caprover/issues/11#issuecomment-652071100

**Comment by koolamusic** [comment]
sharp. 

The project I had in mind was Cube, link below
https://github.com/cube-js/cube.js

Should I open a new issue to add this to one-click apps?

**Comment by githubsaturn** [comment]
Sure. Please create an issue on one click apps repo
