### ISSUE TITLE
[Question] end to end apps shared database

### ISSUE THREAD

**Issue by solidstudio** [caprover/caprover#769]
Hi it seems the one click apps are not suitable for end to end apps.

For example the hasura app has 2 containers hasura and postgres but really you would want something to handle authentication like fusionauth etc but this has its own postgres container.

Would you not want to share the db for both hasura and fusionauth?

Would it be best as a user to create a new template or use separate databases for each one click app?

**Comment by githubsaturn** [comment]
One click apps are intended for out of the box solution. It is impossible to address all combinations of the applications out there. But, there are multiple oneclick apps that were created as their ready to counterpart but without database. For example, there is a normal WordPress and there is WordPress without database. Of course, setting these up are a little bit more complex.

Hasura and fusion auth don't have the "without database" variant yet. Feel free to create a one click app for them and open a PR here: https://github.com/caprover/one-click-apps
