### ISSUE TITLE
[Question] - Sometimes nginx returns 500

### ISSUE THREAD

**Issue by Jonatha-Varjao** [caprover/caprover#771]
When the app is in a "idle" state, sometimes the requests return a 500 with a 
```json
{
  "message": "Internal Server Error"
}
```
But after this error, when I repeat the request, it works fine.

Any ideas?
I'm using Flask with its default WSGI server, I didn't test this issue using a more robust WSGI HTTP Server like Gunicorn.
I tried to check if there's some issue related but no success.

Regards

**Comment by githubsaturn** [comment]
There are many reasons why an app can return a 500 status code, but it's all related to your own app.

A common case that results in 500 on idle apps is the fact that the database connection might have gotten disconnected. Make sure if you have a database connection, you have connection error handling and retrying mechanism in place.

Also, to find out why your app results in 500, you should look into the logs of your app. Either on CapRover dashboard, or using
```
# showing logs for your app in the last 10 min
docker service logs srv-captain--yourappname --since 10m
```

**Comment by Jonatha-Varjao** [comment]
hmmm....my app is receiving the request
![app](https://user-images.githubusercontent.com/24946916/88562651-52c1c300-d007-11ea-884f-362b7821d2fb.png)
but nginx is returning 200
```json
{
  "message": "Internal Server Error"
}
``` 
Checked the database, everything is fine, any other ideas ?

**Comment by githubsaturn** [comment]
So your app returns 200, but nginx converts 200 to 500? Is that the case?

You can get nginx logs by 
```
docker service logs captain-nginx --since 10m
```
to see what's going on and what's causing the 500

**Comment by Jonatha-Varjao** [comment]
it was a DNS problem related :hurtrealbad:
