### ISSUE TITLE
[Deployment Issue] Deploy Rails with mysql issue

### ISSUE THREAD

**Issue by faierbol** [caprover/caprover#774]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Error when running -> bundle exec rake db:structure:load  RAILS_ENV=production
Mysql2::Error: Unknown MySQL server host 'srv-captain--ielo-staging-db'

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by faierbol** [comment]
I have open the 3306 port on digitalocean ubuntu droplet,
Tried as well to use : srv-captain--ielo-staging-db but the same error

**Comment by faierbol** [comment]
i have solved the main issue by completely disabling the ubuntu firewall and creating port mapping, but now i receive the following error:
Mysql2::Error: Access denied for user 'root'@'10.0.0.2'
the username and password are correct, i have double and triple check it

**Comment by githubsaturn** [comment]
A few points:
- If you're connecting to your db from your local machine, yes, you do need port mapping.
- If you're facing an authentication issue, it's mostly because you're not setting the correct username/password on your local environment.

**Comment by faierbol** [comment]
Hi @githubsaturn thanks for your input. 
Indeed the first issue was with port mapping, we solved that, but for the second error we double checked the credentials (user, password) we even added a simple pass like dbpass for example and it still fails with Mysql2::Error: Access denied for user 'root'@'10.0.0.2'

**Comment by faierbol** [comment]
what we try to achieve is to deploy sharetribe community edition https://github.com/sharetribe/sharetribe on caprover

**Comment by githubsaturn** [comment]
Try this:
- Deploy a simply MySQL database (without any app) to your server
- Add port mapping to map a random port on the server to port "3306" of the container. Make sure the port is not in conflict with another mapped port.
- Try to access the database using a mysql GUI from your desktop (e.g. https://www.mysql.com/products/workbench/)

**Comment by githubsaturn** [comment]
Closing this issue. Feel free to reopen if the issue still persists.
