### ISSUE TITLE
How to set up CapRover installation (via Docker) on other port than 3000?

### ISSUE THREAD

**Issue by victormaths** [caprover/caprover#776]
What is the problem?

I want to set up CapRover on other port via the command below:
`
docker run -p 80:80 -p 443:443 -p 3030:3030 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover -e PORT=3030`

But i getting stuck on this error below:
![image](https://user-images.githubusercontent.com/14543600/89113086-9ae74800-d442-11ea-8386-08e7f868e163.png)

My port 3000 has been used by other application. 
Any ideas?

**Comment by githubsaturn** [comment]
CapRover ports aren't configurable just by changing the docker command. The first container is just an installer container which then sets up a few other container. To start CapRover on a different port, you ideally have to recompile CapRover. But this method may also work:

```
mkdir -p   /captain/data
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json

docker swarm init
docker service create --name captain-captain --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock   --mount type=bind,source=/captain,destination=/captain -e IS_CAPTAIN_INSTANCE='1' -p 3030:3000 caprover/caprover
```

Note that CapRover cli assumes the default port 3000, you cannot use `caprover serversetup` using the CLLI. Instead, you need to finishing setting up your server on web GUI:
- Assume a root domain
- Enable HTTPS for the root domain
- Enforce HTTPS on the root domain
All these actions can be done on CapRover web dashboard.

Then use `caprover login` from your local machine to use the CLI.
