### ISSUE TITLE
[Question] How to change default /captain source directory for localhost install

### ISSUE THREAD

**Issue by gmerrall** [caprover/caprover#780]
I'm checking out CapRover on my Mac and have followed the [local install instructions](https://caprover.com/docs/run-locally.html) on the site.  I did note the command line is

`docker run -e MAIN_NODE_IP_ADDRESS=127.0.0.1 -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

while issue #352 says the volume parameter shouldn't be included.

On my Mac I'm unable to create /captain and would prefer $HOME/captain mapped to /captain in the container but this doesn't seem possible. e.g. -v $HOME/captain:/captain

Any advice on how to achieve this would be great.

**Comment by githubsaturn** [comment]
CapRover local install instructions are only for linux installation and mainly for testing and development. 

Currently there is no way to set the custom mounting directory other than rebuilding the image, it's [defined as a constant](https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L5).

You have a few options at this point:
- clone the repo, edit the constant, and rebuild the image with `docker build -t yourtag -f dockerfile-captain.release .`
This approach may or may not work. As Docker on Mac might behave differently on other aspects as well.
- Simply use an ubuntu VM on your Mac
- If you're only testing out, you can follow [these steps](https://caprover.com/docs/play-with-docker.html). Note that one click apps may/may not work if you're using PlayWithDocker, but other than that, things should be fairly functional as a real setup.
