### ISSUE TITLE
Handle Routing in Caprover With Docker Routing Mesh

### ISSUE THREAD

**Issue by chris-rutherfurd** [caprover/caprover#782]
**Is your feature request related to a problem? Please describe.**
Having all connections into CapRover being handled through the leader before being routed to the appropriate container provides a single fault domain.

**Describe the solution you'd like**
It would be good if routing in CapRover could be handled via Swarm Mode routing mesh so that all worker nodes could be added to the DNS root domain entry for the CapRover cluster. Swarm Mode routing mesh would not only eliminate the single fault domain of the leader in the routing layer but would also enable a more resilient and capable scaling capability. CapRover already enables scaling capabilities by enabling an admin to scale up and down the number of instances for a given container, adopting routing mesh seems the next logical step. By enabling this it would allow the leader node in a swarm to not be required to directly handle public connections which would in turn increase the stability of the leader (especially in single leader clusters) preventing a large number of requests from causing load issues on the leader. In order to provide DNS based routing instead of just port based routing non http ports could be directed straight to the appropriate containers and a single container instance could be run on each of the worker nodes in the swarm routing mesh running nginx as the proxy, to forward the http request to the appropriate container based on the domain instead of the port.

**Describe alternatives you've considered**
There are a few existing docker images for edge routing instances which in effect replicate routing mesh but these don't seem to work effectively as the connections all still route through the leader node as opposed to directly on the worker nodes.

**Additional context**
Originally swarm mode was an independent install on top of Docker but has not been integrated as part of the main docker server and can be configured from the command line...

ie...
```
$ docker service create \
    -- name <service-name> \
    -- publish published=<published-port>,target=<container-port>\
    <image>
```

**Comment by githubsaturn** [comment]
We did consider this originally. There are two problems:
- With mesh routing, [the origin IP gets lost](https://github.com/moby/moby/issues/25526). Having origin IP is crucial for many applications.
- Second problem is the persistent content in `/captain` directory. This includes the SSL certs, application configs and etc. In order to support this, we need a resilient multiway rsync behavior across all manager nodes and this is very tricky to be accomplished successfully. Suggestions and contributions are welcome!

**Comment by chris-rutherfurd** [comment]
There is an open source docker image called traefik which is a reverse proxy and load balancer and auto configures based on docker tags. It could be configured as a global service would spin up a single container instance per docker server and then route to the various images based on tags. The routing mesh could be used to route all port 80 and 443 connections to all the traefik instances which would provide fault resiliency so that if an instance fails and needs to be restarted traffic can be routed around it while it is being restarted, plus traefik handles let's encrypt heaps termination. I'm looking further into how it could be tied in and experimenting on a vanilla docker swarm but could work, just need to see how it handles let's encrypt replication across instances.

**Comment by githubsaturn** [comment]
I am aware of traefik. Integrating traefik with CapRover is essentially like rewriting CapRover. It handles Let'sEncrypt integration and etc. In all fairness, if you plan to use traefik, there is not much value to be added by CapRover, maybe some image building and domain assignment which can be done through other means.
