### ISSUE TITLE
[Deployment Issue] Force HTTPS causing 502 errors on new deploys

### ISSUE THREAD

**Issue by dan-dr** [caprover/caprover#783]
What is the problem?
When I use the "Force HTTPS by redirecting all HTTP traffic to HTTPS" option on new deploys, I'm getting 502 on both http and https. Old deploys are working correctly.

If applicable, content of `captain-definition` file:
Using one click apps (sentry, bitwarden)

Steps to reproduce the problem:
1. One-click install app
2. Add new domain.
3. Enable HTTPS for new domain
4. Check "Force HTTPS by redirecting all HTTP traffic to HTTPS".
5. go to http(s)://newdomain.com and see 502.

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 18.04
- RAM? ~20GB

**Comment by dan-dr** [comment]
log from captain-nginx (changed actual domain to mydomain.com for privacy):
`2020/08/08 09:57:12 [error] 99#99: *362307 srv-captain--bitwarden could not be resolved (3: Host not found), client: 53.129.131.132, server: bitwarden.mydomain.com, request: "GET / HTTP/2.0", host: "bitwarden.mydomain.com"`

**Comment by githubsaturn** [comment]
Forcing HTTPs has nothing to do with 502. It's weird that you're getting this error after you enabled the FORCE HTTPS option. 
- Does the error go away if you disable FORCE HTTPS?
- Is the service running? run `docker service ps srv-captain--bitwarden --no-trunc`

**Comment by oogdigital** [comment]
Have exactly the same issue with Shopware-1-click. Works fine as long having not pushed Enable HTTPS  and Force HTTPS and with Standard config as given. After enabling https and and forcing a 502 is shown.

**Comment by githubsaturn** [comment]
@oogdigital 

Click on Edit Nginx configuration, find this:
```
        location / {
            return 302 https://$http_host$request_uri$is_args$query_string;
        }
```

and change it to 
```
        location / {
            return 302 https://$http_host$request_uri;
        }
```

Does it resolve the issue?

**Comment by oogdigital** [comment]
No, didnt. I think, that i probably has to do with symfony and trusted proxies. Shopware is build in symfony.

https://symfony.com/doc/current/deployment/proxies.html 9

Config TrustedProxies via environment

https://github.com/shopware/development/blob/master/public/index.php#L30 6

**Comment by githubsaturn** [comment]
Reach out to Shopware community. They might have a simple solution for this.

**Comment by oogdigital** [comment]
;) than shopware should probably removed from available auto-deploy Apps. But I will try.

**Comment by githubsaturn** [comment]
Yeah I think one of their members actually added this app to one click apps, so they should be able to fix it.

**Comment by githubsaturn** [comment]
@shyim

**Comment by shyim** [comment]
Hmm normally when `x-forwarded-proto: https` is send. It should work by default. I will look into default headers

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/112364452-d1761980-8cd6-11eb-8651-6862bca5bf3e.png)

Mostly the users forgot to have an https url here

**Comment by oogdigital** [comment]
@shyim thanks!!! I was really looking for a solution on Caprover, nginx, symfony and so on.... In the end it was really just adding the HTTPS URL in shopware itself. Anyway ton do this also in any config file with command line? 

Thank you!!!

**Comment by shyim** [comment]
When the APP_URL in the installation contains https this issues should not happen.  Afterwards changing it isn't possible in Shopware, cause you can have many domains 😅
