### ISSUE TITLE
Port 3000 is not exposed

### ISSUE THREAD

**Issue by adrianbaumgart** [caprover/caprover#785]
**What is the problem?**

Port 3000 is not exposed; Can't connect to server for setup.
I ran `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` to install CapRover and the installation finishes but I can't connect to IP:3000 (to setup the server via the cli).

Logs after the installation:
<img width="1392" alt="Screen Shot 2020-08-09 at 16 53 29" src="https://user-images.githubusercontent.com/28984823/89735160-dac0b780-da60-11ea-8557-8a3966a09c17.png">

`docker ps`:

<img width="1791" alt="Screen Shot 2020-08-09 at 16 54 28" src="https://user-images.githubusercontent.com/28984823/89735181-fdeb6700-da60-11ea-8b56-4cbc4d84edb1.png">

`caprover serversetup`:

<img width="1392" alt="Screen Shot 2020-08-09 at 16 55 56" src="https://user-images.githubusercontent.com/28984823/89735237-4e62c480-da61-11ea-95b6-5af93f0f9a3d.png">

`curl 127.0.0.1:3000`:

```
root@acfe69:~# curl 127.0.0.1:3000
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
root@acfe69:~# 
```

**If applicable, content of `captain-definition` file:**

n/a

**Steps to reproduce the problem:**

- Get a new server
- Run `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`

**Answers to the following questions where applicable:**
- Your OS and version: Ubuntu 18.04.4
- RAM = 3GB

**Comment by githubsaturn** [comment]
Do you have the port open?
```
ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;
```

**Comment by adrianbaumgart** [comment]
@githubsaturn I disabled ufw but I also tried the installation with ufw enabled and these ports allowed.

I'm trying out [Signaltransmitter](https://signaltransmitter.de/en/)(SSD LXC vServer). I used another VPS provider before and everything worked. Signaltransmitter says that docker runs just fine and I tested it with MariaDB (without CapRover), and it worked (port 3306 exposed).

**Comment by githubsaturn** [comment]
I was gonna suggest you test it out on another provider. But you already did, and things worked fine there. 

One possibility is that the VPS provider you're using is doing something funky with port 3000 in particular. First [uninstall CapRover completely](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain), and then try this:
```
docker run -p 3000:80 nginx 
```

**Comment by adrianbaumgart** [comment]
`docker run -p 3000:80 nginx` works just fine, the default nginx website loads. I also tried the CapRover-edge to test if something changed, but that doesn't work either...

**Comment by githubsaturn** [comment]
That's interesting. Maybe Signaltransmitter has an issue with Docker swarm overlay network. Try reinstalling CapRover, then run
```
docker service update --publish-rm 3000 captain-captain
# wait 10 sec
docker service update --publish-add published=3000,target=3000,mode=host captain-captain
```

**Comment by adrianbaumgart** [comment]
Oh my god it worked. Thank you! (I didn't finish the setup yet because it says that the root domain doesn't point to the IP address but the website works)

**Comment by githubsaturn** [comment]
So yea, there is an issue with the kernel that Signaltransmitter is using. I've seen problems like this with providers who modify the Linux kernel. This fixes the problem for CapRover, but for all other apps that you install on this instance, you probably run into the same issue if you want to use port mapping. Either use a standard Kernel, if they have it, or use another provider if you think you'll need port mapping.

**Comment by adrianbaumgart** [comment]
hmm yeah... They do have an option to choose a kernel with their KVM vServers but I currently use a SSD LXC vServer.
This could actually be a problem with the mail server which needs port mapping, I'll look into it and probably use another provider. Thank you for the help! (can I close the issue?)
