### ISSUE TITLE
[Question] Dockerignore Support

### ISSUE THREAD

**Issue by jacklimwenjie** [caprover/caprover#787]
Is there a `.dockerignore` support for Captain Rover? 

I was deploying a NodeJS app by using the tarball method, I was compressing all project local folders and files into the tarball, and so the tarball includes `node_modules` and `.dockerignore`. 

One thing to note is I'm using `dockerfilePath` to specify the `Dockerfile`. With this, I was expecting Captain Rover to read the `Dockerfile`, along with the `.dockerignore` file. 

However, apparently the `node_modules` folder is still being copied over in `COPY . /app` docker command. This caused the build to be broken. 

To mitigate this, I had to explicitly exclude `node_modules` from the tarball. 

Is there any way to better handle this?

**Comment by githubsaturn** [comment]
When you use `caprover deploy`, CapRover excludes all `.gitignore` files when you create a tarball. 

When you manually create a tar file, you have to manually exclude the files that you don't want to be present in your tarball. Or you can use git to create a tarball (this is what CapRover uses under the hood):
```
git archive --format tar --output ./mytarfile.tar master
```


On a separate note, if are okay with node_modules to be included in the tarball, but you just want to make sure that it doesn't make it to the docker image, you can definitely use `dockerignore`. Make sure `.dockerignore` is at the base of your project alongside with `captain-definition` file. It should not be in a nested directory.

**Comment by therohitdas** [comment]
I used the .dockerignore file alongside the captain-definition file, but it did not work.
