### ISSUE TITLE
MongoDB TLS/SSL [Question]

### ISSUE THREAD

**Issue by cleverbeagle** [caprover/caprover#790]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

Hi there. I'm trying to understand how SSL/TLS is working with the one-click MongoDB install. I've got HTTPS set up via the HTTP Settings tab for the app and can confirm connections via the browser are being force-redirected to HTTPS.

I'm also able to connect to MongoDB via a GUI (Studio 3T). When I do this, if I check the SSL settings it doesn't seem to work but if I leave those off and just use my root user/pass, it seems to work.

Is it safe to assume that CapRover is properly securing the connection between the server and the running MongoDB server if I've properly configured HTTPS in the HTTP Settings for the app (as well as the root domain for CapRover itself)?

**Comment by githubsaturn** [comment]
> Is it safe to assume that CapRover is properly securing the connection between the server and the running MongoDB server if I've properly configured HTTPS in the HTTP Settings for the app (as well as the root domain for CapRover itself)?

No, it's not correct. HTTPS is different from SSL. HTTPS is a protocol built on top of SSL. MongoDB does not use HTTPS, it uses SSL/TLS. 

If you want to connect to your database from an external point (like your local machine), read [here](https://caprover.com/docs/database-connection.html#external-connections).

If you really want to use SSL/TLS, you need to configure your MongoDB instance to use an SSL cert. See [here](https://dacurry-tns.github.io/deploying-apereo-cas/high-avail_mongodb_configure-mongodb-to-use-tls-ssl.html) for example.

**Comment by 3rickDJ** [comment]
So, does CapRover is not capable of managing one-click apps (databases) with SSL/TLS out of the box?
I've been researching in the docs. I haven't found it. I'm asking because coolify has something for that. I was wondering how hard would that be in theory to implement?
Any takes?...
