### ISSUE TITLE
Support docker swarm update configuration

### ISSUE THREAD

**Issue by alex-red** [caprover/caprover#791]
Hi all, loving Caprover so far and it seems to have everything I need except one config that I think would be great to have: the ability to set the UpdateConfig for service updates. Being able to set the delay between updates would help with having zero downtime in images that take a bit longer to startup. 

Something simple like in portainer would be nice:
![image](https://user-images.githubusercontent.com/6088384/89945734-0b2e6000-dbdf-11ea-9223-7ae141901a3f.png)

Let me know if this has already been addresssed elsewhere (couldn't find anything through the search), and I would be happy to contribute to this as well.

**Comment by githubsaturn** [comment]
This is not something that we'll be porting over directly to the UI, see the [project scope here](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope).
> The goal is to make the common use-cases exposed via simple controls on UI while allowing further customizations to be done through hooks and scripts. If a new feature is doable via the existing features, or a basic tool, do not add it to CapRover. We do not want to bloat this application. One example is: "Add a flag to customize the placement constraints of containers". This is definitely doable in Docker, but we don't want to mirror every single functionality of Docker to CapRover. If we do that, CapRover becomes a very hard to maintain project. Instead we should add customization hooks for these advanced and rare use cases. 

------------

Having said that, there are a few ways to achieve this:
- Install portainer from one click apps, and make fine adjustments to your service. CapRover only changes a handful of flags on Docker service, the rest will be left untouched.
- You can use Docker CLI `docker service update....` to update your service, similar to the first option.
- Last option is to simply use a [predeploy script](https://caprover.com/docs/pre-deploy-script.html). This is the swiss army of the methods. You can even make changes to the changes that CapRover has already applied. Here is the flow:

```
Service's current state => CapRover makes changes => Predeploy script (if any) makes changes => docker service update
```

Feel free to comment if you have any other questions.
