### ISSUE TITLE
[Deployment Issue] Laravel app deploy NGINX 502 Error

### ISSUE THREAD

**Issue by faierbol** [caprover/caprover#794]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

i am trying to use nginx as a web server for my laravel app but it seems that i am doing something wrong
currently the app is working with caddy but i would like to use nginx.
Any help will be much appreciated. 

If applicable, content of `captain-definition` file:

```
{
  "schemaVersion" :2 ,
  "dockerfilePath" : "Dockerfile"
 }
```

Docker file:

```
FROM php:7.4-fpm

# Set working directory
ENV LARAVEL_PATH=/srv/app
WORKDIR $LARAVEL_PATH

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential cron curl locales zip unzip git vim

# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN npm install

# Setup cron job
RUN (crontab -l ; echo "* * * * * /usr/local/bin/php /srv/app/artisan schedule:run >> /dev/null 2>&1") | crontab

# Install supervisord
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord

# Install caddy
COPY --from=caddy:2.0.0 /usr/bin/caddy /usr/local/bin/caddy

# Install PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions intl bcmath gd pdo_mysql pdo_pgsql opcache redis uuid exif pcntl zip mbstring tokenizer mysqli gmp imagick openssl tokenizer xml ctype json
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer & app dependencies
COPY --from=composer:1.10.5 /usr/bin/composer /usr/local/bin/composer
COPY composer.json composer.json
COPY composer.lock composer.lock
# TODO remove prestissimo when composer hits v2
RUN composer global require hirak/prestissimo --no-plugins --no-scripts
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader && rm -rf /root/.composer

# Copy app
COPY --chown=www-data:www-data . $LARAVEL_PATH/
COPY ./.deploy/config/php/local.ini /usr/local/etc/php/conf.d/local.ini
RUN chmod -R 777 $LARAVEL_PATH/storage

# Set any ENVs
ARG APP_KEY=${APP_KEY}
ARG APP_NAME=${APP_NAME}
ARG APP_URL=${APP_URL}
ARG APP_ENV=${APP_ENV}
ARG APP_DEBUG=${APP_DEBUG}

ARG LOG_CHANNEL=${LOG_CHANNEL}

ARG DB_CONNECTION=${DB_CONNECTION}
ARG DB_HOST=${DB_HOST}
ARG DB_PORT=${DB_PORT}
ARG DB_DATABASE=${DB_DATABASE}
ARG DB_USERNAME=${DB_USERNAME}
ARG DB_PASSWORD=${DB_PASSWORD}

ARG BROADCAST_DRIVER=${BROADCAST_DRIVER}
ARG CACHE_DRIVER=${CACHE_DRIVER}
ARG QUEUE_CONNECTION=${QUEUE_CONNECTION}
ARG SESSION_DRIVER=${SESSION_DRIVER}
ARG SESSION_LIFETIME=${SESSION_LIFETIME}

ARG REDIS_HOST=${REDIS_HOST}
ARG REDIS_PASSWORD=${REDIS_PASSWORD}
ARG REDIS_PORT=${REDIS_PORT}

ARG MAIL_MAILER=${MAIL_MAILER}
ARG MAIL_HOST=${MAIL_HOST}
ARG MAIL_PORT=${MAIL_PORT}
ARG MAIL_USERNAME=${MAIL_USERNAME}
ARG MAIL_PASSWORD=${MAIL_PASSWORD}
ARG MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
ARG MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
ARG MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
ARG MAIL_FROM_NAME=${APP_NAME}

ARG PUSHER_APP_ID=${PUSHER_APP_ID}
ARG PUSHER_APP_KEY=${PUSHER_APP_KEY}
ARG PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
ARG PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}


# Start app
EXPOSE 9000
COPY ./.deploy/entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

Steps to reproduce the problem:

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
Port 9000 that you're exposing is an fpm port. **CapRover Nginx needs an HTTP port**. 

You either need to use Caddy inside your container, like [this](https://github.com/jackbrycesmith/laravel-caprover-template), or another nginx, like [this](https://github.com/caprover/caprover/blob/master/captain-sample-apps/nginx-php-advanced.tar). The php nginx example is advanced and if you are not familiar with how it works, I suggest you stick with Caddy solution.

**Comment by faierbol** [comment]
Hi @githubsaturn thank you for your response. So this means I cannot use the caprover nginx and instead I need to install nginx on the app/ image and add a custom nginx config file?

**Comment by githubsaturn** [comment]
You might be able to. But that requires heavily customizing your nginx config, see [this example](https://github.com/JoshuaWalsh/docker-nginx-for-php-fpm/blob/master/nginx-for-php-fpm/default.conf#L22-L52).

You can to `Apps > Your Laravel app > HTTP Settings > Edit Nginx Config` and edit the config in a way that works for your application. But keep in mind, it's an advanced process. If you misconfigure your nginx, you run the chance of breaking your entire setup.

**Comment by faierbol** [comment]
Okay, thx for the input, i will try
