### ISSUE TITLE
I need order of deployment

### ISSUE THREAD

**Issue by alexk345** [caprover/caprover#795]
I want to start docker container apps after mongo installed and port is binded. at present  i need to rebuild the server again to make it connect to mongo. caprover has to have flag on app to say its database and port. so caprover can check this when it gets reply it can start other apps.

**Comment by githubsaturn** [comment]
Is this comment different from the one that was previously replied to? https://github.com/caprover/caprover/issues/793#issuecomment-672792207

**Comment by vohzd** [comment]
@alexk345 please kindly read the documentation, if you have any questions, read it again.
