### ISSUE TITLE
is there an easy way to clone an existing app and just be prompted to set a new name ?

### ISSUE THREAD

**Issue by jpolvora** [caprover/caprover#801]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**
I'm thinking about select an existing app and copy definition/variables/settings/etc

**Describe the solution you'd like**
The solution is put a button inside app definition so I can click and be prompted to fill the name

**Describe alternatives you've considered**
Sometimes is tedious to create an app from scratch, and copy settings manually from an existing app.

**Additional context**
I have an app that is kind of a reusable template, so I need a way to facilitate creating a new app based on an existing.

**Comment by githubsaturn** [comment]
This may work for a very simple case, but it'll create more confusion than benefit for other apps. For example, if you have an app that has a port mapping, or has a volume mapping, the duplicated app will have port or volume conflict with the original app.

Alternative solution:
You should look into creating your own one click app. See more details here: https://github.com/caprover/one-click-apps
