### ISSUE TITLE
Adding VPS recommendation to the docs

### ISSUE THREAD

**Issue by divjakLab** [caprover/caprover#802]
Could you add recommended VPS providers to the Docs? I know I saw them in one of the Issue and when I needed to check next time I had hard time finding it again.

**Comment by githubsaturn** [comment]
There is really no preferred VPS provider at this point for CapRover. CapRover is mostly tested on DigitalOcean, but that doesn't mean that other providers won't work. As long as they have a healthy Docker installation, it should be fine.

There are some providers that have modified their linux kernel that causes issues with Docker. For example, I think 
- [OVH was one of them](https://github.com/caprover/caprover/issues/14#issuecomment-345447689). 
- [Linode is another one](https://github.com/docker/machine/issues/2753#issuecomment-171822791).
- AWS is fine, it just requires lots of setup and firewall adjustment. If you're familiar with AWS ecosystem, it shouldn't be a problem.

Other than these, people have used many other hosting services successfully. You can join our #hosting [Slack channel](https://caprover.slack.com/messages)
