### ISSUE TITLE
Private npm modules

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#806]
Hi, I've looked, but been unable to find out how to get similar functionality to what heroku provides. Namely, to use a .npmrc and be able to access private registry modules. Bit of a deal breaker. Thanks

**Comment by skiv71** [comment]
Thank you for the quick response... and it makes perfect sense... however, I've avoided docker up to now, and no idea where to place such a file... but the NPM_TOKEN is exactly as per heroku, so makes sense

**Comment by skiv71** [comment]
Also, on an unrelated note... since vscode and other editors assist with code when the correct suffix is selected... would it not be a good idea to rename the captain-definition to a *.json file... (maybe even one with a shorter name) hehe.

**Comment by githubsaturn** [comment]
You can place `Dockerfile` at the root of your directory, next to `package.json` and next to `captain-definition` file. By the way, you have to change your `captain-definition` file to this:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```
Make sure you get the capitalization right. `Dockerfile`.

Regarding the extension, yes, it'd be a good idea. But ideally, you shouldn't need to touch that once it's set to the content I mentioned above. All your future changes will be done in Dockerfile.

**Comment by skiv71** [comment]
Since that captain file seems mandatory, why can it not be created via a caprover 'create / init' etc. like you can do with heroku?

I'm still lost on the Dockerfile... I assumed I'd have to create such a file server side on my VPS?

Sorry, I'm not usually this dumb regarding sofware and alike (i write smart contracts and all sorts)... but never needed to spin a docker up (up till now)

**Comment by githubsaturn** [comment]
You don't need to create `Dockerfile` on your server. It's just a file like `.npmrc`. Where do you create your `.npmrc` file? It's akin to that. Does that help?

**Comment by skiv71** [comment]
Ok, I think so... I created the .npmrc (just like heroku), tick... amended the captain file but then on deploy, new error "Error: One, and only one, of these properties should be present in captain-definition: templateId, imageName, dockerfilePath, or, dockerfileLines"

**Comment by githubsaturn** [comment]
Your `captain-definition` file content must be exactly what I mentioned above:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

**Comment by skiv71** [comment]
{
  "schemaVersion": 2,
  "templateId": "node/13.11.0",
  "dockerfilePath": "./Dockerfile"
}

**Comment by skiv71** [comment]
Oh, I see your captain file has no node specification?

**Comment by githubsaturn** [comment]
Remove `templateId` .

templateId is a shortcut for a "default" Dockerfile. In you case, you wanted to use a private module, hence, we had to use a customized version of Dockerfile.

If you want to change the node version to 13, you just need to change the first line of Dockerfile `FROM node:14-alpine` - change this to `FROM node:13-alpine`

**Comment by skiv71** [comment]
Ah yea, I see now... Thanks

**Comment by skiv71** [comment]
Strange, I'm seeing this warning... [Warning] One or more build-args [NPM_TOKEN] were not consumed

**Comment by skiv71** [comment]
Oh, seems I don't need the app specific args key/value pair like heroku?

**Comment by githubsaturn** [comment]
My bad - I forgot one line - I should have added `ARG NPM_TOKEN  ` in the Dockerfile. I've updated the Dockerfile above: https://github.com/caprover/caprover/issues/806#issuecomment-678814546

**Comment by skiv71** [comment]
Yea, that makes more sense.... but somehow, it was working for me with the original DF and no NPM_TOKEN... as if with just plain .npmrc

**Comment by skiv71** [comment]
Yea, I've just done some testing and I can confirm, the presence of .npmrc at the time of npm install seems to make things work just fine :)

**Comment by githubsaturn** [comment]
Nice! Good to know!
