### ISSUE TITLE
Order of deployment apps need to change. 

### ISSUE THREAD

**Issue by alexk345** [caprover/caprover#807]
Wanted to start my apps after mono started and mongo is listening. Or apps has a delay  then other apps can start.
best is wait and communicate to database port using curl and once get reply and start other apps. it could be mongo or mysql or any database app. May be flag for database  app and port info should be entered when app is installed. so caprover check port before start other apps.

**Comment by githubsaturn** [comment]
This is the third instance that you're asking the same question. Please read the response in the previous postings:

https://github.com/caprover/caprover/issues/795
and 
https://github.com/caprover/caprover/issues/793
