### ISSUE TITLE
[Question] Docker run flags

### ISSUE THREAD

**Issue by Jonatha-Varjao** [caprover/caprover#808]
I was looking, probably the pre-deploy script is my lead, but I need to add ```--gpu=all``` when the ```docker run``` is executed

How can I achieve that ?

**Comment by Jonatha-Varjao** [comment]
Some context, I have a ML prediction service, I running in RAM and also need to scale up using the vRAM, to maximize the usage of the VM, it holds 2 containers in RAM and probably will hold one in vRAM, the communication is based on AMQP só the round robin in rabbitmq will send one message to each consumer that it's plugged.
I just need this fine tunning flag to execute one in GPU and create another app with the default docker run to use the RAM

**Comment by githubsaturn** [comment]
Less than ideal solution:
Alternatively, you can manually run your container without using CapRover. You can still use CapRover for all other containers that do not require that flag. You can comminucate between CapRover containers and the manually created containers as long as your manually created container is attached to `captain-overlay-network` via something like
```
docker run --network captain-overlay-network  mycontainer
```
