### ISSUE TITLE
May I know any mechanism related resource control?

### ISSUE THREAD

**Issue by ckc** [caprover/caprover#809]
For my earlier issue #669 , I know it's look like Docker related issue
As per your mentioned, so I also ask for [Moby](https://github.com/moby/moby/issues/41179#issuecomment-654100456)

But for my understanding, the pipeline is under caprover? Like my title mentioned, I hope to know any thing **should I need to do to prevent RAM/storage exceed** or **any control to activate auto terminate the built failed tasks pipelines** for reduce down affected? 

I am new to container, and Caprover absolutely good and fit my need; I really deploy my app thru Caprover 

Thanks

**Comment by githubsaturn** [comment]
> I hope to know any thing should I need to do to prevent RAM/storage exceed or any control to activate auto terminate the built failed tasks pipelines for reduce down affected?

What exactly are you hoping to do to avoid RAM/storage exceed? These are a few best practices that you can follow:
- Best option, you can avoid building on your CapRover machine completely, and have the build step to be done on a CI/CD pipeline: https://caprover.com/docs/ci-cd-integration.html
- Another option is to set up alerts from your VPS provider when you're running out of disk.

**Comment by ckc** [comment]
Thanks Kasra prompt response,
It's good understand these two prevention

I think most user adopted Caprover mostly caused new to docker container/ hard to familiarize with commands

At the same time, no a picture to know app(s) resource comsuming in the host overall, or even specific app; Or even able set a maximum threshold limit it somehow like current RAM/storage over 90%, then stop anymore new app create.

Last one more pair question, may I know any plan for implement to Kubernetes? And is it any paid customization? (or good also be a contributor)


Look forward to see Caprover to a higher milestone

**Comment by githubsaturn** [comment]
> At the same time, no a picture to know app(s) resource comsuming in the host overall, or even specific app

Resource monitoring is a whole other dimension for which you should use other tools such as NetData. 

> Last one more pair question, may I know any plan for implement to Kubernetes? And is it any paid customization? (or good also be a contributor)

Not in near future. Swarm serves the purpose at this point.


We constantly monitor the issues raised by users and adopt the most recurring ones.
