### ISSUE TITLE
NetData tool exposed to public

### ISSUE THREAD

**Issue by orbing** [caprover/caprover#810]
Going to the netdata url `https://domain.net.au/net-data-monitor/` while logged out gives public full access to the tool. Though this should be reported here.

**Comment by githubsaturn** [comment]
It's exposed to the public. The difference is that it uses cookies instead of in-memory variable. Hence you're able to access it after you logged in. 

Can you try accessing it using incognito mode or another browser?

**Comment by githubsaturn** [comment]
Found a case where logout didn't clear the cookie - but again, the URL is not exposed to the public. Let me know if you find otherwise.
