### ISSUE TITLE
Upgrade failed - UI returns 502 - Containers still running

### ISSUE THREAD

**Issue by cbudtz** [caprover/caprover#811]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Tried to upgrade via UI to 1.8 - resulted in 502 Bad gateway on captain.caprover.{mydomain}

If applicable, content of `captain-definition` file:
not applicable

Steps to reproduce the problem:
try to upgrade from earlier version

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16.04 LTS
- RAM? 4 GB

**Comment by githubsaturn** [comment]
Does this help? https://github.com/caprover/caprover/issues/797

**Comment by cbudtz** [comment]
tnx for the quick reply - took a look at docker: 
4lfuv9bviqt7izta8wt96tprj   captain-captain.1       caprover/caprover:1.8.0   diplom-e18          Ready               Preparing 1 second ago                                                  
waqx1v228fk0xm2788wjk7tcj    \_ captain-captain.1   caprover/caprover:1.8.0   diplom-e18          Shutdown            Rejected 1 second ago     "No such image                                : caprover/caprover:1.8.0"
mrvesm4ixlyk4s2olgultxs50    \_ captain-captain.1   caprover/caprover:1.8.0   diplom-e18          Shutdown            Rejected 9 seconds ago    "No such image                                : caprover/caprover:1.8.0"
- Looks like youre solution could be right ;) - Will give it a shot

**Comment by cbudtz** [comment]
Seems it is another problem...
~$ docker pull caprover/caprover:1.8.0

write /var/lib/docker/tmp/GetImageBlob053027116: no space left on device
