### ISSUE TITLE
Caanot get oneclickapps.

### ISSUE THREAD

**Issue by tim-hub** [caprover/caprover#812]
```
   | August 27th 2020, 5:35:44.125 am    Error: getaddrinfo EAI_AGAIN oneclickapps.caprover.com
    | Error: getaddrinfo EAI_AGAIN oneclickapps.caprover.com
    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
   | GET /api/v2/user/oneclick/template/list 200 20023.738 ms - 90
```
--------------------------------------------------------------------------

What is the problem?

Cannot oneclickapps.

- I tried  open the link manually, https://oneclickapps.caprover.com/  it returns 404.
- api.v2.caprover.com is the same 404

Steps to reproduce the problem:

- `sudo docker service logs captain-captain`
- click **one click apps** at dashboard

Answers to the following questions where applicable:
- Your OS and version? Ubuntu
- RAM? 2G

**Comment by githubsaturn** [comment]
https://oneclickapps.caprover.com/ returning 404 isn't unexpected, see https://oneclickapps.caprover.com/v2/autoGeneratedList.json for example which doesn't return 404.

EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

Somehow your CapRover container cannot reach the internet. Either you disable internet for your CapRover container, or your machine has outgoing firewalls.

Try this:
1) 
SSH to your machine and run:
```
curl https://oneclickapps.caprover.com/v2/autoGeneratedList.json
```
If you get a response back, try rebooting your machine and try to see if the problem is resolved. If rebooting doesn't resolve the issue, then move on to step 2
If you don't get a response, then it means your machine doesn't have network connectivity. 

2)
Run 
```
docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh
## wait a second until you are inside caprover container
curl https://oneclickapps.caprover.com/v2/autoGeneratedList.json
```
If you don't get a response, then it means your docker container doesn't have network connectivity. Run:
```
docker service inspect captain-captain
```

**Comment by tim-hub** [comment]
> https://oneclickapps.caprover.com/ returning 404 isn't unexpected, see https://oneclickapps.caprover.com/v2/autoGeneratedList.json for example which doesn't return 404.
> 
> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.
> 
> Somehow your CapRover container cannot reach the internet. Either you disable internet for your CapRover container, or your machine has outgoing firewalls.
> 
> Try this:
> 1)
> SSH to your machine and run:
> 
> ```
> curl https://oneclickapps.caprover.com/v2/autoGeneratedList.json
> ```
> 
> If you get a response back, try rebooting your machine and try to see if the problem is resolved. If rebooting doesn't resolve the issue, then move on to step 2
> If you don't get a response, then it means your machine doesn't have network connectivity.
> 
> 
> Run
> 
> ```
> docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh
> ## wait a second until you are inside caprover container
> curl https://oneclickapps.caprover.com/v2/autoGeneratedList.json
> ```
> 
> If you don't get a response, then it means your docker container doesn't have network connectivity. Run:
> 
> ```
> docker service inspect captain-captain
> ```

thanks so much for the help.



I did 1 and 2, I do get the response from the caprover apps.

but on the dashboard, I still cannot see any apps.


after I run `docker service inspect captain-captain`



I got 

```
  "Placement": {
                    "Constraints": [
                        "node.id == st96dfx69p0v8hcd7bvqwlrhg"
                    ],
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "Networks": [
                    {
                        "Target": "kj0a995rgren3mmumnjm2k0pb"
                    }
                ],
                "LogDriver": {
                    "Name": "json-file",
                    "Options": {
                        "max-size": "512m"
                    }
                },
                "ForceUpdate": 1,
                "Runtime": "container"

```

**Comment by githubsaturn** [comment]
This is extremely bizarre. Are you sure you followed (2) correctly? i.e. you were able to curl from within the container?

Try updating your instance manually and see if the problem goes away:
```
docker service update captain-captain --image caprover/caprover:1.8.0
```

**Comment by githubsaturn** [comment]
Also what VPS are you using?

**Comment by tim-hub** [comment]
> This is extremely bizarre. Are you sure you followed (2) correctly? i.e. you were able to curl from within the container?
> 
> Try updating your instance manually and see if the problem goes away:
> ```
> docker service update captain-captain --image caprover/caprover:1.8.0
> ```

Yes, I am sure.

I am using aws ec2, and I am certain that firewall/security group enable allow the ports caprover required.

**Comment by githubsaturn** [comment]
I really have no idea how you can curl from inside your container, but the nodejs process fails to load the exact same domain. And it's only happening for you, no one else is having this issue. 

1- Did you try rebooting your system? Did it help?
2- Did you try updating CapRover via command line. Did it help?
3- Can you reproduce the issue on another AWS EC2 machine? Or it's just this one VPS that's exhibiting a problem?
