### ISSUE TITLE
Need order of app running

### ISSUE THREAD

**Issue by alexk345** [caprover/caprover#813]
My app had to be re deployed to connect to mongo. I added issue few times it got deleted. whats going on?
Database app has to be started first and other apps has to be started after db connection established. so basically app should have delay or db app has port info for caprover to check port before deploy other apps after database app deployed fully.

**Comment by githubsaturn** [comment]
Unfortunately, you'll be blocked from posting any more issues. You've been spamming with repeated issues:
https://github.com/caprover/caprover/issues/807
https://github.com/caprover/caprover/issues/795
https://github.com/caprover/caprover/issues/793
