### ISSUE TITLE
[Update failed] Client version is too new.

### ISSUE THREAD

**Issue by hesa2020** [caprover/caprover#814]
--------------------------------------------------------------------------

What is the problem?
I updated from the UI because it said Update available and i havent updated the server in a while.
Now captain wont boot.

Look screenshot:
[Image](https://i.imgur.com/ozlifHO.png)

**Comment by githubsaturn** [comment]
Please see here: https://github.com/caprover/caprover/issues/797

**Comment by githubsaturn** [comment]
This was clearly mentioned in the release notes. Not sure why many missed it.

![image](https://user-images.githubusercontent.com/10582082/91626173-cf372100-e97a-11ea-8976-c33f1cbb92a9.png)

**Comment by hesa2020** [comment]
Because i clicked "Update now" or what ever the button is from the GUI lol.
Because you should add a requirement checkup when clicking on that button that show an alert or actually prevent upgrading.
