### ISSUE TITLE
[Deployment Issue]

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#815]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

I'm seeing a warning for config vars not being used, i.e. process.env[arg], where they clearly are because are required for my connection to firebase.

I'm accessing them via destructuring...

var {
    FB_CLIENT_EMAIL: client_email,
    FB_PRIVATE_KEY,
    FB_PROJECT_ID: project_id,
    PORT,
} = process.env

If applicable, content of `captain-definition` file:

n/a

Steps to reproduce the problem:

see above

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

Digital Ocean 2c vCPU, 4gb RAM (but not relevant)

**Comment by skiv71** [comment]
Just a point to note, I export these env vars via a config.js into my main index.js - does it think that because they are not referenced in that file, they are not used?

I just tried it without destructuring... so what mechanism does caprover employ to make this decision? I realise its only a warning but shouldn't be there.

**Comment by skiv71** [comment]
It seems this might have something to do with these ENV 'ARG_NAME' 'ARG_VAL' not being present in my './Dockerfile'?

It i put them in there, I end up committing private data?

**Comment by githubsaturn** [comment]
You can ignore that warning. CapRover passes your env vars to your build process in case they are required when you build your application. Docker sees a bunch of variables and notices they are not being used in the build process, hence it displays the warning message. It's just an informational warning.
