### ISSUE TITLE
[Deployment Issue] MongoDB Cluster

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#818]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

When deploying a 1 click mongo app, in an effort to run a custom docker (and cmd args), I've had to delete the existing app... and when I re-created a new app, same name, the new one will not start.

On investigating syslog, I can see constant messages where caprover is requesting logs for a non existant container.

Just trying to reboot the whole server and try again.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
You don't need to get syslog. You can use docker command to view your [application logs](https://caprover.com/docs/troubleshooting.html#how-to-view-my-applications-log).

So, to debug, follow these steps:
```
# examine to see if your mongodb service is running. If you see "up a few seconds ago" it means it keeps getting restarted
docker service ls

# view your mongodb logs
docker service logs srv-captain--mymongodb --since 10m 

```

**Comment by skiv71** [comment]
Just did a reboot, created a new mongo 1 click app, deployed, logs says its listening... which it says it is... but docker run <image> mongo fails to connect, and the syslog is again trying to find logs for a non existant container. I do hope I don't have to bin this whole VM, as I've sent its public IP upstream to a provider I need to access (for whitelisting)

**Comment by skiv71** [comment]
I can see from the webUI (and docker container ls) that the container is running for 5 mins now.

Every 3 seconds ...

Sep  1 03:09:33 ubuntu-s-2vcpu-4gb-nyc1-01 dockerd[749]: time="2020-09-01T03:09:33.673323423Z" level=error msg="logs call failed" error="failed getting container logs: No such container: srv-captain--db-main.1.slflu8pxz28kq16a24oeix0ql" module=node/agent/taskmanager node.id=v30coa2ztieozlurxqih9dawz

CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                      NAMES
a9f5bb942413        mongo:4                            "docker-entrypoint.s…"   7 minutes ago       Up 6 minutes        27017/tcp                                  srv-captain--db-main.1.l1i1naios23ud5k6ou7257r50
f57e9e5d0ef2        caprover/certbot-sleeping:v1.5.0   "/bin/sh -c 'sleep 9…"   10 minutes ago      Up 10 minutes       80/tcp, 443/tcp                            captain-certbot.1.v93frfbosp9jojspwd5jhs8ka
65116d87fdc1        nginx:1                            "/docker-entrypoint.…"   10 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   captain-nginx.1.uhmwj70oevlsonepi7dn1nl0h
7d40813cbec7        caprover/caprover:1.8.0            "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes       3000/tcp                                   captain-captain.1.cdxosxx4r3g5un5qm6fi0w01d
a51a74d394fe        img-captain-api:19                 "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes       80/tcp                                     srv-captain--api.1.w3ejcv5tg7hjvavv06pohbqfn
root@ubuntu-s-2vcpu-4gb-nyc1-01:~#

**Comment by githubsaturn** [comment]
"failed getting container logs" isn't really an important issue. It's either CapRover or NetData trying to fetch an old container. It's not the problem here.

So your MongoDB is running. That's good news. But why you can't connect to it could be due to a few reasons. Most likely you didn't delete the volume, or Docker failed to remove the volume. Hence when you created a new container with the same name, the old volume got attached and cause issues.

**Comment by githubsaturn** [comment]
Try this: 
- Delete your MongoDB
- Create a new one with a new name

**Comment by skiv71** [comment]
I've already done this over 6 times...

**Comment by githubsaturn** [comment]
With a new name? Okay then, how are you trying to connect to the MongoDB container?

**Comment by skiv71** [comment]
Ok, created a completely new one, managed to connect via docker lt command and enabled port forwarding on both,  - can access both from localhost.  Still seeing the 3 secondly log requests for a non existant container

**Comment by skiv71** [comment]
Ok, those log warnings have died, and I now have 2 mongo's up... and one spun back up with the custom Dockerfile, running replSet and directoryperdb.

First problem (not strictly caprover, but painful) is that caprover spins up the instance, with default settings, creates the auth in admin db... but to restart in per folder db, you have to really clear all records, which loses the auth - which i can reset manually.

Secondly, I wanted to test connectivitly, between A and B, via a ping, but i get the error about $PATH, no ping exec.

I need to configure replicaSet via rs.conf but not sure (but assuming) that the srv--captain-<app name> would end up the host name.

**Comment by skiv71** [comment]
Think I've just stumbled upon the original problem and not sure how to get around it without a reboot. If (like I just did) forget to clear all the existing data prior to restarting after changing to replicaSet, mongodb fails to start and repeatedly crashes.

Stopping it via reducing instances to 0 (and then back to 1) doesn't restart it whatever I do...

**Comment by skiv71** [comment]
Ok, think I'm on the last hurdle, cannot see where this would be set... but I think I need to tell the mongodb docker instances to use the host network (or at least dns) so the replicaset nodes can resolve each other.

**Comment by githubsaturn** [comment]
The hostname for your services would be `srv-captain--yourapp1` `srv-captain--yourapp2` etc... Note that you only need port mapping when connecting from localhost. If you want to connect to two MongoDB instances from another MongoDB instance, it will be something like:

```
srv-captain--mongo1:27017
and
srv-captain--mongo2:27017
```
Note that for both cases the port is the default container port, not the "host" port that they can be potentially mapped to.

------------

PS:

> Still seeing the 3 secondly log requests for a non existant container. Ok, those log warnings have died

Like I said, this is a different issue and it's not related to your MongoDB installation. It often shows up and has no adverse effect. You can simply ignore it.

**Comment by skiv71** [comment]
Thanks for the help regarding host names. I've managed to change the primary member of each mongo to itself... but when I try and add *--my-db to *--db-main it complains it cannot reach it (or resolve it)

**Comment by skiv71** [comment]
It's cool... another my bad - I ran rs.initiate() on the proposed secondary, which is a primary only command

**Comment by skiv71** [comment]
Ok, think I'm almost beat with this... I can get 3 mongodb containers working, replicaset, but when i enable auth on the secondary and arbiter, the primary cannot reach them. I realise this is not really a caprover issue, but its still annoying. I see references on the internet to using a --keyfile for auth.. I sort of assumed once they've sync'd with no auth, they would share the same admin db and know each others credentials

**Comment by skiv71** [comment]
I'm not sure where I'd put this keyfile, I assume in ..../volumes/<container>, but not sure if its *-data or *-config

**Comment by githubsaturn** [comment]
This is really a MongoDB question, `*-data` maps to `/data/db` and `*-config` maps to `/data/configdb`

**Comment by githubsaturn** [comment]
> I realise this is not really a caprover issue, but its still annoying

I agree that it's annoying. This is why we didn't include MongoDB cluster as a one click app. It has many quirks that you have to be aware of for each use case.
