### ISSUE TITLE
How i can use consola for execute the same action that "Save & Update" and "Backups"?

### ISSUE THREAD

**Issue by xnardo** [caprover/caprover#821]
Hello! It is possible to execute one command from console, that execute the same action in the GUI ("Save & update" and "Backups"), why this i thing is very necessary:

1. To allow to create an cron-job to create backups of caprover.
2. Possibility to change the parameters of one app in /captain/data/config-captain.json and re-deploy. This could be great, for example for change one app to other server (no random) automatically and other things. Before i try to use `docker service update`, but i can not find the way to update the node of one app with this command.

Thanks for your collaboration!

**Comment by githubsaturn** [comment]
Not officially supported, but you can use `caprover api` command: https://github.com/caprover/caprover-cli#api
