### ISSUE TITLE
Does CapRover provide trusted certificates for https if it's able to verify the domain? (I get self-signed ones if I skip the verify)

### ISSUE THREAD

**Issue by eugali** [caprover/caprover#822]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

**Comment by githubsaturn** [comment]
Yes - CapRover uses Certbot / Let's Encrypt under the hood to get valid certs.

**Comment by eugali** [comment]
Thank you for your quick answer. I am on EC2, Elastic IP and public interface. How can I make the verify work? Everything is correct, but still hangs during setup and skip that part is not an option unfortunately

**Comment by githubsaturn** [comment]
There are a few tutorials on the web for CapRover on AWS
- https://fuzzyblog.io/blog/caprover/2019/11/10/using-caprover-on-aws.html
- https://medium.com/staminacake/peaceful-cd-to-dev-server-with-caprover-docker-and-aws-3b86b0bced41
- https://www.youtube.com/watch?v=cNT9xAILrCs

You need to make sure that you have "wildcard domain" i.e. you have to setup your DNS such that:
`*.something.domain.com` resolves to the IP address of your box.

**Comment by eugali** [comment]
It looks like the certificate for captain.subdomain.domain.io is from Let's Encrypt, but the application.subdomain.domain.io is still the self signed CapRover's one. I followed these steps:

- Setup skipping the SSL check
- Forced https which made possible to deploy the app
- Pressing "Enable HTTPS" in the application domain -> 1107 error after a while

During the "Enable HTTPS" process I experience different 502 bad gateway errors. 

I have investigated a bit more around the Google Domains issues with the DNS challenge. It looks like the new version of ACME uses the TXT records through the DNS APIs that are not provided by Google Domains. It's required to use Google Cloud DNS service. 

The mxtoolsbox give me the right ip for any *.subdomain.domain.io, is there any way I can get valuable logs or do manual operations to fix this issue?

**Comment by githubsaturn** [comment]
I am not sure if I understand your steps:

> Setup skipping the SSL check

What does this mean?


> Forced https which made possible to deploy the app

Force HTTPS in the root domain or the app itself? And also what do you mean by "made possible to deploy the app"? Why is deploying the app related to HTTPS?

**Comment by eugali** [comment]
These are the steps:

- "docker run etc" command in the EC2 machine
- A record in Google Domains already set to the Elastic IP
- "caprover serversetup" run locally
- "caprover serversetup" fails the domain check
- edit the override-config file to make CLI skip the domain check
- have the captain.subdomain.domain.io dashboard working
- create a new app
- try to deploy to the new app with "caprover deploy" already configured
- "caprover deploy" fails because it requires Captain dashboard to be HTTPS
- Force HTTPS from the dashboard
- deploy successfully the app
- "Enable HTTPS" in the app's specific dashboard
- 1107 verification failed

After these steps I have seen that the "captain.subdomain.domain.io" certificate is from Let'sEncrypt, while the app one is from CapRover

My question is: how is it possible that the dashboard has the right certificate, while the app has not?

**Comment by eugali** [comment]
P.s. when I check the reverse dns lookup starting from the IP it gives back the AWS default dns -> ec2-xx-xx-xx-xx.eu-west-1.compute.amazonaws.com

could this affect somehow the DNS challenge?

**Comment by githubsaturn** [comment]
> Force HTTPS from the dashboard

1- Why do you have to do this manually? Didn't you use `caprover serversetup` to setup your instance? In that case, it automatically enables HTTPS and FORCE HTTPS for you.

> 1107 verification failed

2- Do you still have the override config or you deleted it? It is not possible to get 1107 error if you have the `skipVerifyingDomains` flag enabled.


----
> My first question is: how is it possible that the dashboard has the right certificate, while the app has not?

Dashboard and your app are two different domains, they don't share the SSL certificate. 

> My second question is: how can I determine where is effectively the error?

3- 
You need to confirm a few things:
- Do you have HTTPS enabled for your dashboard? i.e. can you access `httpS://captain.sub.domain.com`? If yes, go to next step:
- Create an app, with a unique name, like `test1234`
- Click on the link that opens the app. It opens `http://test1234.sub.domain.com`. Do you see NOTHING IS HERE or the place holder app? Place holder app is a CSS animation screen (flashlight moving around). If you see placeholder app, move on to the next step.
- Click on ENABLE HTTPS button for `test1234` and open the link again, it should open `httpS://test1234.sub.domain.com`. Does this work? What do you see?

**Comment by eugali** [comment]
1) During "caprover serversetup" I wasn't able to get through the verification step, hence I disabled it, run it and re-enabled it
2) I have had the "S" in the "captain" subdomain and its certificate was from Let's Encrypt
3) I have had the "S" in the application subdomain but was from CapRover
4) I have done this configuration many times from scratch and managed to make everything work, but I have seen that if I skip the SSL check I get the self-signed certificate which is not usable my some of my clients

Ae you saying that I could get the Let's Encrypt certificate even if I skip the SSL check? 

P.s. at the moment it's almost 24 hours since I created the new AWS Route 53 domain. I deleted everything again to get the SSL check directly from "caprover serversetup". The dns lockup gives the public IP address of my EC2 machine and the dashboard works. The reverse dns lockup gives back the AWS EC2 IP address as "xx-xx-xx-xx.compute.aws"

**Comment by githubsaturn** [comment]
> Ae you saying that I could get the Let's Encrypt certificate even if I skip the SSL check?

There is no "Skip SSL"!!! The only skip is `skipVerifyingDomains` - this is an internal step by CapRover. It has nothing to do with Let's Encrypt.

**Comment by eugali** [comment]
Sorry, I meant "skipVerifyingDomains". If I skip it, can I get a LetsEncrypt certificate for the application or is that verification mandatory?

**Comment by githubsaturn** [comment]
If you skip it, you will get a LetsEncrypt certificate for the application when you click on ENABLE HTTPS.

**Comment by eugali** [comment]
Solved, I get the right certificate in the app as well, thank you very much for your support!

Just out of curiosity, why are you asking for domain verification if it could be skipped?

**Comment by githubsaturn** [comment]
> Just out of curiosity, why are you asking for domain verification if it could be skipped?

Domain verification is done locally by your own instance. When you skip this step, basically you're telling CapRover that "**I know what I am doing, please be silent**". When you skip the domain verification, you can add any domain, like `domain123456787987.com` without even assigning the A record to the IP address of your server. In that case, you can successfully attach this domain, but it won't work when you're trying to access the domain. Also when enabling HTTPS you will receive an obscure error which is hard to understand. 

The purpose of that check is to avoid these common mistakes.
