### ISSUE TITLE
emulate firebase hosting, nginx?

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#826]
Hi, I want to create an app to serve some static vue.js app.

I'm thinking a dockerfile using nginx, where it uses a dist folder and copies it to nginx root hosting path.

Am i right?

If so, is there an example of the dockerfile which would do this, for caprover?

Thanks

**Comment by vohzd** [comment]
Hello,

If it helps, I've deployed a Vue app using this exact method.

Please take a look here, and let me know if you need anything explaining;
https://github.com/vohzd/skatelocate/tree/master/dist

**Comment by skiv71** [comment]
Thanks for that, seems just like what I need... I'll try and knock something out.

Caprover rulez

**Comment by skiv71** [comment]
Still new to docker, so run into problems already...

"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder549369491/default.conf: no such file or directory"}
COPY failed: stat /var/lib/docker/tmp/docker-builder549369491/default.conf: no such file or directory
Build has failed!

What am I missing please?

**Comment by githubsaturn** [comment]
@skiv71 
You need to copy Dockerfile, captain-definition, and default.conf file from here: https://github.com/vohzd/skatelocate/tree/master/dist

**Comment by skiv71** [comment]
Oops, my bad... missed that *.conf file :)

Thanks!
