### ISSUE TITLE
[Deployment Issue] Can't connect to internal apps

### ISSUE THREAD

**Issue by otaviobps** [caprover/caprover#827]
I'm running a nodejs app, using Express. It's configured to listen to port 3333.

The app is running fine, and I'm not exposing it to the internet. I have another micro-service, also running on port 3333 but on another caprover container. I'm trying to connect to the first micro-service using the `http://srv-captain--backend/api/internal` notation.

The problem is that I get a 500 error. I tried different combinations, and all of them fail:

>http://srv-captain--backend/api/internal: `connect ECONNREFUSED 10.0.1.15:80`
>srv-captain--backend/api/internal: `connect ECONNREFUSED 127.0.0.1:80`
>http://srv-captain--backend:3333/api/internal: `Request failed with status code 400: Error: connect ECONNREFUSED 127.0.0.1:80`
>srv-captain--backend:3333/api/internal: `connect EINVAL 0.0.13.5:80 - Local (0.0.0.0:0)`

I have another micro-service running an instance of MongoDB, not exposed to the internet, and I can connect to it just fine using the `srv-captain--mongo-database` IP.

I started the `bash` on the container requesting the connection, and I could `ping` to the `backend` container only when using this notation:

```
/usr/src/app # ping srv-captain--backend
PING srv-captain--backend (10.0.1.15): 56 data bytes
64 bytes from 10.0.1.15: seq=0 ttl=255 time=0.151 ms
64 bytes from 10.0.1.15: seq=1 ttl=255 time=0.061 ms
64 bytes from 10.0.1.15: seq=2 ttl=255 time=0.073 ms
64 bytes from 10.0.1.15: seq=3 ttl=255 time=0.062 ms
64 bytes from 10.0.1.15: seq=4 ttl=255 time=0.070 ms
64 bytes from 10.0.1.15: seq=5 ttl=255 time=0.075 ms
```

When I added the `http://`, then ping failed:
```
/usr/src/app # ping http://srv-captain--backend
ping: bad port spec 'http://srv-captain--backend'
```

It seems that when I try to connect to the `backend` container with the `http://srv-captain--backend/api/internal` URL, it finds the IP of the container, but the connection fail.

It seems a port forwarding issue, because the second container is trying to connect to port 80 on first container, which is listening to port 3333. I think docker isn't forwarding the request from port 80 to port 3333, but where can I set the port to redirect to?

What am I missing?

**Comment by otaviobps** [comment]
After searching a lot it was a problem with my implementation. I'm closing this issue

**Comment by githubsaturn** [comment]
Glad you solved the issue. To provide more context:

> It seems a port forwarding issue, because the second container is trying to connect to port 80 on first container, which is listening to port 3333. I think docker isn't forwarding the request from port 80 to port 3333, but where can I set the port to redirect to?

CapRover uses nginx to bind 3333 to 80 for external requests but for interenal request you have to specify the port as you are directly connecting to the other container without using nginx. So simply just use `http://srv-captain--backend:3333/api/internal`

**Comment by joshamaju** [comment]
I ran into the same problem. The doc says I don't have to provide the port

> For example, if you want your NodeJS app to access your MongoDB database, and you do not need to access your MongoDB from your laptop, you don't need Port Mapping. Instead, you can use the fully qualified name for the MongoDB instance which is srv-captain--mongodb-app-name (replace mongodb-app-name with the app name you used).

[Link](https://arc.net/l/quote/yuzfnvjz)
