### ISSUE TITLE
Embedding build metadata into resulting deployed app

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#828]
Hi, when I used to deploy my web app to firebase, I used to run a build script, post compilation, which used to insert the actual git branch and commit.

Since caprover deploys from the latest commit, even though I run my build script, the actual deployed is prior the build meta data being inserted - so in effect its always 1 step behind.

Wondered if anyone had any thoughts? Good or bad appreciated :)

**Comment by githubsaturn** [comment]
Committing to build artifact is generally not a good practice. The build artifact should be a reproducible output from a build script.

Feel free to share an example and provide more context if you need more guidance.
