### ISSUE TITLE
jsconfig.json paths

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#829]
Hi, does anyone know how to make the node build process aware of vscode path aliases defined in the above config file?

I'd like to use them, as I do in my client side, parcel bundled code... but node sure about this one :-/

**Comment by githubsaturn** [comment]
Can you provide an example?

**Comment by skiv71** [comment]
Sure...

This feature is made possible by vscode and its jsconfig.json / tsconfig.json and widely used.

{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "shared/*": [
                "./src/api/v1/shared/*"
            ]
        },
        "target": "es6",
        "module": "commonjs"
    },
    "exclude": ["node_modules"]
}

The above allows you to require('shared/utils'), as opposed to require('../../../../../shared') // depending where you are in your folder structure.

Now, this only allows for code creation convenience and requires support at build level.

In the case of parcel.js (mainly for client side builds), it supports the addition of 'alias' root property in the package.json, which it uses when it finds a 'presumed' alias path (due to it not being present i think).

From here, I'm not sure how this could be implemented for node builds, maybe preinstall?

I see there are quite a few npm modules which implement config files for path alias, and decorators.

**Comment by githubsaturn** [comment]
It's a committed file, hence it will be available during build. It depends how you build your application:

- If you build on server, just make sure you are running the exact same commands during Docker build as you would run locally. See here for an example: https://github.com/anhvietcr/reactjs-parcel-docker-example

- if you build your code on the local machine, and just deploy the built artifact to the server, like [this example](https://caprover.com/docs/recipe-deploy-create-react-app.html), then you don't need to do anything, these commands won't be running on your server.

Please note that there is nothing specific about CapRover. This is just a build process via Docker.
