### ISSUE TITLE
Allow start-first for apps with volumes attached to them.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [caprover/caprover#830]
Is it possible to override the behaviour outlined in the following comment from #661? File corruption isn't a problem for me when using webapps that rarely write (but still need a persistent volume for some reason)

TLDR:
CapRover does support zero downtime (mostly). What makes you think that CapRover doesn't have zero downtime?

More details:
If you're app doesn't use a volume, CapRover uses `start-first` strategy when updating the containers. This means that the newer version of your container will be up and running before the old one is killed. This should give you next-to-zero downtime. There is still a slight chance that your container wakes up but internally it takes some time before it can accept requests. This is out of CapRover's hands.

This strategy is intentionally not applied to apps with volumes attached to them. This is because if multiple instances of the same service are trying to access the same file, this will result in data corruption and failures. For apps with volumes (persistent data), CapRover user `stop-first` strategy. This means that the old container is stopped first, before the new container starts up. This results in a few seconds of downtime.

_Originally posted by @githubsaturn in https://github.com/caprover/caprover/issues/661#issuecomment-619548552_

**Comment by githubsaturn** [comment]
Yes, you can do so by overriding the [Docker service config](https://caprover.com/docs/service-update-override.html).

```
UpdateConfig:
  Order: start-first
```

See Docker docs for more details:
https://docs.docker.com/engine/api/v1.40/#operation/ServiceUpdate
