### ISSUE TITLE
Anyone with experience migrating from Vesta to Caprover?

### ISSUE THREAD

**Issue by designlook** [caprover/caprover#831]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: Just wondering if there's steps I should do to migrate easily

**Comment by githubsaturn** [comment]
Please use our community channels such as Slack to ask community related questions.
