### ISSUE TITLE
Docker housekeeping

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#832]
Hi, just removed a load of old images and docker confirms they are no longer present, but according to the caprover UI, they are still there, and available for roll back.

Is there something else I need to do, other than docker container prune --force && docker image prune -a?

Thanks,

Neil

**Comment by githubsaturn** [comment]
Are you referring to images in Deployment section? These are just version history. If you delete images, your image gets deleted from the disk, but the version history will remain there. If you try to rollback to a deleted image, your rollback will fail.

![image](https://user-images.githubusercontent.com/10582082/93158018-599cb600-f6d9-11ea-958a-7dbfd501dbb9.png)

**Comment by skiv71** [comment]
Ah, yes it is.... and i guessed it would fail... are those historical logs 'forever'?

**Comment by githubsaturn** [comment]
Yes. It keeps last 50 versions.
