### ISSUE TITLE
Best way to load balance CouchDB.

### ISSUE THREAD

**Issue by bilicio** [caprover/caprover#834]
Hi Kasra!

Hope you are fine! Do you know the best way to achieve load balance on couchdb? I know that couch already have replication state and id like to use caprover load balance with that. Im thinking about it but i didnt found a proper way to do that. What i need to do is, when a mobile client tries to get data from couchdb, this requisition is deal by load balancer and forward to the low loaded database. 

and my question is:
If i cluster the caprover1 to caprover2 with the steps you described on docs and enable replication on couchdb do you know if i try to access couchdb1 address it will load balance to couchdb2 if needed?

thank you!!

**Comment by githubsaturn** [comment]
> If i cluster the caprover1 to caprover2 with the steps you described on docs and enable replication on couchdb do you know if i try to access couchdb1 address it will load balance to couchdb2 if needed?

Couchdb is a an application with persistent data. If you add an extra node and spin up another instance on your second node, you effectively have two different CouchDB instances. Scaling DBs is not something that can be done automatically. Each database has its own way of load balancing, but essentially, there is a lot of manual work that is not automated. 

Essentially, you'll have to partition your data and basically design your database cluster yourself. 

Also, see this: https://github.com/caprover/caprover/issues/627#issuecomment-601467636

**Comment by bilicio** [comment]
Thank you Kasra! i know couch have persistent data thats why if i enable replication on couch1 the couch2 will receive all the data from couch1 and write his own persistent data with the same data. this will not worrie me.  what i need to know for sure is, if i cluster the caprover1 to caprover2 and try to access couch on caprover1 it will loadbalance to caprover2 couch2?

**Comment by githubsaturn** [comment]
Are caprover1 and caprover2 two different nodes (servers) ? Is this what you are thinking?

```
      CapRover 1                        CapRover 2

+------------------------+      +-------------------------+
|                        |      |                         |
|                        |      |                         |
|                        |      |                         |
|                        |      |                         |
|                        |      |                         |
|   +-----------------+  |      | +---------------------+ |
|   |                 |  |      | |                     | |
|   |   CouchDB1      |  |      | |     CouchDB2        | |
|   |                 |  |      | |                     | |
|   +-----------------+  |      | +---------------------+ |
|                        |      |                         |
|                        |      |                         |
|                        |      |                         |
|                        |      |                         |
+------------------------+      +-------------------------+
```

**Comment by bilicio** [comment]
yes

**Comment by githubsaturn** [comment]
You can't do this. From my first comment:
> If you add an extra node and spin up another instance on your second node, you effectively have two different CouchDB instances

**Comment by githubsaturn** [comment]
You "can" have this architecture, but when you write, you might write to one DB, and when you read, you might read from the other DB.

**Comment by bilicio** [comment]
i know i will have 2 different couchdb instances, but what i love about couch its his own replication mode. if i set couch1 with the couch2 address it will sync all the data between its two databases. it will replicate all the data and keep each one synced.

**Comment by bilicio** [comment]
i can have a lot of couchdb . i only have problem to use each couch if one of them its overloaded

**Comment by bilicio** [comment]
when i try to read couch that not have the data i want it will search on another replication node for that data and get to me

**Comment by githubsaturn** [comment]
Okay then, yes, if that's the case, nginx automatically load balances between them via round robin.

**Comment by bilicio** [comment]
great!!! thank you! i will make some tests and back to you and maybe write some new features using caprover! 👍

**Comment by githubsaturn** [comment]
Ah, actually that's not possible - because if you have a persistent app, your instances are locked down to one specific node (because the data is on that node).

To achieve what you're trying to do,
- you'd have to manually create CouchDB instances on every node (without CapRover). You'd have to use `global` replication mode so that it gets replicated on each node.
- Attach them to `captain-overlay-network`
- Create an nginx reverse proxy oneclick app on CapRover and have it talk to the couch DB instances 


In general, it's a very complex setup.

**Comment by bilicio** [comment]
oh my.. ok.. i will make some tests to see how it goes. thank you! 👍

**Comment by bilicio** [comment]
Hi Kasra! im making some tests and i found out that i cant access the caprover admin of the cluster. This is how it suppose to work right? only one admin editable caprover on the master. So digging a little bit i thing it might work if i could change the persistent directory of the couchdb on the cluster. So i think maybe on another update give option to change persistent directory of the app on the cluster will work,  because the persistent directory doesn't sync and one time settled it will last forever. :)

**Comment by githubsaturn** [comment]
>  i found out that i cant access the caprover admin of the cluster. This is how it suppose to work right? 

Can you elaborate what you mean by "can't access the caprover admin" ?

**Comment by bilicio** [comment]
Sure! If I try to access the cluster on ipaddress:3000 I didn't see the caprover interface.

**Comment by githubsaturn** [comment]
Correct. `ipaddress:3000` only works for `ipaddress` of the main node. That's because the CapRover service is only on the main node.

**Comment by bilicio** [comment]
Ok! So I think the only option that will work will be different persistent folder for each cluster. This will be too complex for now. Good to know that this might work. I will try this in the future. 👍

**Comment by mqtik** [comment]
Hey @bilicio, did you finally set this up with CapRover?  Or are you using CouchDB clusters connected without it?

**Comment by bilicio** [comment]
Unfortunately I couldn't. I decided to use one couchdb instance only.

**Comment by mqtik** [comment]
Out of curiosity (and I apologize for bothering), under how much stress is that instance, and how well does it perform?
Do you keep sync ON at all times? How many users/databases do you have?
