### ISSUE TITLE
Let'sEncrypt failure to renew

### ISSUE THREAD

**Issue by WriteCodeEveryday** [caprover/caprover#836]
What is the problem?

Let'sEncrypted failed to renew for https://www.miamimobileforensics.com

If applicable, content of `captain-definition` file:

Just a static node app

Steps to reproduce the problem:

Don't check your SSL cert, realize it's expired.

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

Ubuntu 16.04, 512Mb RAM

I'm updating from 1.5.2 to 1.8.0 now but this could be more widespread (or not)

**Comment by githubsaturn** [comment]
There was a bug in versions prior to 1.7.1 which is fixed now:

https://github.com/caprover/caprover/issues/700

**Comment by githubsaturn** [comment]
As a work around, you can simply restart your caprover service:
```
docker service update captain-captain --force
```
This should resolve the issue for older versions.
