### ISSUE TITLE
[Question] .env file support, or any alternative

### ISSUE THREAD

**Issue by GavinRay97** [caprover/caprover#837]
I read through a couple of issues which were related to environment management, and two issues which brought up `.env` file support but wasn't able to make out a clear answer.

Is it possible to use `.env` files, or otherwise set the runtime environment for Docker services before deploying? I can't deploy first and then set the environment for my apps because they'll fail on startup without the proper values present unfortunately.

Thank you, and sorry if this has been answered before =)

**Comment by githubsaturn** [comment]
There is an env var section in app config that you can use to set runtime environmental variable. If you switch to bulk mode, you can copy and paste your `.env` file content.

![image](https://user-images.githubusercontent.com/10582082/93690520-473ec580-faa7-11ea-8b9c-6e3d92210f47.png)

**Comment by agungroyat** [comment]
> 
> 
> There is an env var section in app config that you can use to set runtime environmental variable. If you switch to bulk mode, you can copy and paste your `.env` file content.
> 
> ![image](https://user-images.githubusercontent.com/10582082/93690520-473ec580-faa7-11ea-8b9c-6e3d92210f47.png)

Is it possible to set the environment variable value to refer to the other's value? like this,

![image](https://user-images.githubusercontent.com/13929765/127986975-edaea9bd-b7b3-4970-940d-eb521d174185.png)

**Comment by githubsaturn** [comment]
No
