### ISSUE TITLE
Security concern about UFW and Docker

### ISSUE THREAD

**Issue by hokamc** [caprover/caprover#839]
Seems that docker actually bypasses UFW and directly change iptables, this mean UFW rules didn't work on container publish port. Do you have any workaround to help other users not to fall in this pitfall?

**Comment by githubsaturn** [comment]
This is not CapRover specific. Please use Docker forums for Docker related questions: https://github.com/moby/moby/

Looks like there are ways to circumvent this: https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/
But please do this at your own risk.
