### ISSUE TITLE
Nextcloud, container to container access

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#841]
Hi, I need local file storage for my app, so I've installed nextcloud.

I'm unable to have my node app connect, which I've debugged to domain white listing.

All docs mention adding my caprover docker node app's domain name into the config.php, but I see in the actual app config part of the web UI (caprover), its also listed there.

I thought if I added mine onto there, it would work, but it doesn't appear to make a difference.

Is the persistent storage config update the way to go?

Thanks

**Comment by skiv71** [comment]
Even with my config/config.php amended to include my 'srv-captain--api' (the hostname for my node app), nextcloud refuses my connection attemps :(

**Comment by skiv71** [comment]
Also tried adding the entire docker local subnet '10.0.1.*', but this also fails. The logs for the actual nextcloud app don't reveal anything about the config options, so its hard to tell if its even being used

**Comment by skiv71** [comment]
Ok, just a heads up. I had to resort to using the fqdn (external app name) to connect my node app to the nextcloud instance.

So, no srv-captain--<app> access, no matter what changes I made to the config.php

**Comment by githubsaturn** [comment]
Like what you said, it's a config on NextCloud app. I suggest reaching out to their team. There is no configuration on CapRover that can impact this.
