### ISSUE TITLE
Containers not starting after reboot

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#842]
Hi,

In an effort to debug another issue, I just did a reboot of my server, and all but 3 containers (which provide the database feature via mongodb) have started.

I'm checking the docker ps output and its not even trying to start them.

The instance count in the UI is 1 for all 3...

What gives?

**Comment by skiv71** [comment]
Still new to docker, but from what I'm seeing, the containers for my db instances don't even exist anymore, and that's why they are not starting.

More worrying, 2 out of the 3 images which pertain to these containers are not present.

I did do a recent prune etc... but that was some time ago, and prior to this recent reboot, all was well.

What the... help

**Comment by skiv71** [comment]
Well, no idea what happened, but with the volume data still intact, I used the dockerfile (which is the same for all) and deployed via the UI on each manually. I seem to be back up. Wish I knew how those containers were destroyed.... they were in use before the reboot

**Comment by githubsaturn** [comment]
> I did do a recent prune etc... but that was some time ago, and prior to this recent reboot, all was well.

This is it. Docker has an issue with pruning locally built images: https://github.com/moby/moby/issues/36295

That's why we have the image clean up in settings:
![image](https://user-images.githubusercontent.com/10582082/94218934-958f0280-feb3-11ea-830d-b98ff3cedd09.png)

**Comment by githubsaturn** [comment]
When your containers aren't running you can check 
```
docker service ls
``` 
and 
```
docker service ps srv-captain--yourappname --no-trunc
```
to get more info
