### ISSUE TITLE
[Question] Enable GitHub Sponsors?

### ISSUE THREAD

**Issue by AnandChowdhary** [caprover/caprover#843]
Would love it if you can sign up for Github Sponsors. I'm sure plenty of people would love to sponsor Caprover on methods other than the OpenCollective. 😄

**Comment by githubsaturn** [comment]
Thanks for the suggestion! Github Sponsors aren't available to public yet. They are in beta phase and availability is limited. We might open one when it's available to the public. 

More importantly, non-monetary contributions will go a long way by the way :) blogs, tutorials, talks about CapRover is most welcomed :)
