### ISSUE TITLE
Flask Template or captain-definition?

### ISSUE THREAD

**Issue by mcbuckeye** [caprover/caprover#847]
Hi! Does anyone have a working example of how to deploy the source code from a Python Flask project to CapRover?

Thanks!

**Comment by andrew-ma** [comment]
basically do this https://github.com/caprover/caprover/blob/master/captain-sample-apps/python-django.tar

**Comment by githubsaturn** [comment]
CapRover build system is just plain Docker. You can use any Flask Docker template, like this one: https://github.com/lvthillo/python-flask-docker

Just add a `captain-definition` file with this content:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

**Comment by prakasharyaman** [comment]
@githubsaturn i cant seem to get my web app working from the method you described
i did exactly that but its showing error
<img width="793" alt="image" src="https://user-images.githubusercontent.com/63445447/159900418-3c6b46b4-8732-4a17-b960-3b632a9dc345.png">
help would be appreciated.

**Comment by faisalsayed10** [comment]
facing this exact same issue ^

**Comment by fyunusa** [comment]
> facing this exact same issue ^

Hi, were you able to get the error fixed ?

**Comment by fyunusa** [comment]
> @githubsaturn i cant seem to get my web app working from the method you described i did exactly that but its showing error <img alt="image" width="793" src="https://user-images.githubusercontent.com/63445447/159900418-3c6b46b4-8732-4a17-b960-3b632a9dc345.png"> i dont understand docker that much ,here's what i did 1.downloaded the python-flask-docker 2.add captain-definition 3.zip > tar > and then deploy but it doesnt work help would be appreciated.

Hi, were you able to get this fixed ?
Can you share how please.
