### ISSUE TITLE
Under App configs, can you make an option for the docker restart policies.  Currently I have to use portainer to set the restart policy per container

### ISSUE THREAD

**Issue by andrew-ma** [caprover/caprover#848]
Please read [CapRover goals and scope](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope
) before posting a new feature request.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by githubsaturn** [comment]
CapRover uses Docker swarm. You should not setup change restart policy on container, you should modify the "service".

For all options that are not exposed on CapRover UI, you can use [Service Override](https://caprover.com/docs/service-update-override.html) option.

**Comment by githubsaturn** [comment]
From CapRover goals and scope 

> The goal is to make the common use-cases exposed via simple controls on UI while allowing further customizations to be done through hooks and scripts. If a new feature is doable via the existing features, or a basic tool, do not add it to CapRover. We do not want to bloat this application. One example is: "Add a flag to customize the placement constraints of containers". This is definitely doable in Docker, but we don't want to mirror every single functionality of Docker to CapRover. If we do that, CapRover becomes a very hard to maintain project. Instead we should add customization hooks for these advanced and rare use cases.
