### ISSUE TITLE
[Question] are we using any method to encrypt application communication in a cluster?

### ISSUE THREAD

**Issue by hariprasadiit** [caprover/caprover#851]
Thank you for awesome project. It helps a lot in maintaining our own PaaS.

Please clearly state your question:

I've read in docker docs that, we can use `docker network create --opt encrypted --driver overlay --attachable my-attachable-multi-host-network` to encrypt application data as well. If I understood it correctly, SSL termination happens at the load balancer node, which means that application communication between nodes happens over unencrypted connection.

I've checked the code and couldn't find `--opt encrypted` being used while creating overlay network. any other method is being to encrypt application communication between nodes in a cluster?

**Comment by githubsaturn** [comment]
Not by default, you can do so by creating a custom network and attaching your services to the custom network.
Note that it comes with a nontrivial computational cost, use it only if you really need it.
