### ISSUE TITLE
"Deploy to Caprover" Button

### ISSUE THREAD

**Issue by NeoTheThird** [caprover/caprover#863]
I've seen this button on some projects:

![image](https://user-images.githubusercontent.com/12068939/96379899-c222fb00-118f-11eb-8d38-1354b947bc03.png)

I think it'd be nice to actively promote something like this for caprover. Some low-hanging fruit to get more exposure in readmes of one-click projects. Obviously the button couldn't point to a direct sales thingie like it does for heroku, but it could open a page explaining that project xyz is configured as a caprover one-click app, that caprover is the greatest invention since sliced bread, and how to set it up, show the demo video, etc.

**Comment by githubsaturn** [comment]
The applications developers usually use "Deploy to Heroku" type buttons to simply create an app on the user's Heroku account. All these buttons are backed by a centralized service. 

While I agree that it's a nice thing to have. there is not much value to be added here. Also, there is nothing to be done on CapRover side to enable this. This is purely just a piece of documentation. Currently applications developers host their own documentation like this: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-caprover

**Comment by NeoTheThird** [comment]
> Also, there is nothing to be done on CapRover side to enable this.

True, not caprover itself, rather the [website](https://github.com/caprover/caprover-website). I was just thinking it could generate pages for all one-click apps in the default repo, display some generic info about caprover, the description from the app config, and the app logo. Just to get the word out about caprover. But your call, you're right of course that it wouldn't do anything.
