### ISSUE TITLE
[Question] Is it possible to use CapRover for non-http workloads?

### ISSUE THREAD

**Issue by khromov** [caprover/caprover#865]
Is it possible to expose a Redis or MySQL instance running in Convox to the world? I guess it wouldn't be possible through Nginx but perhaps with some custom CLI commands? (And eventually maybe even through the UI?)

**Comment by githubsaturn** [comment]
Yes, you can use non-http protocols by bypassing nginx. You can do so by port mapping:

https://caprover.com/docs/one-click-apps.html#connecting-remotely
