### ISSUE TITLE
Error after update Caprover via Caprover-dashboard

### ISSUE THREAD

**Issue by kevinvarela** [caprover/caprover#866]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
The problem is when i try access to Caprover dashboard. When open my domain to login is ok, the server show me login input, but when the browser send POST request, Caprover response 502 Bad Gateway from NGINX.
Anytimes show me nginx error without show the login input. After refresh page few times, the server show the login input again.

Apparently Caprover is in a reset Loop.

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:
1- open my Caprover login

Answers to the following questions where applicable:
- Your OS and version? 
- RAM?

Digital Ocean droplet: 1 GB Memory / 25 GB Disk / NYC1 - CapRover 1.3.0 on Ubuntu 18.04 (the version obtained from DigitalOcean I don't know if it's correct) because I update Caprover from Caprover dashboard, I think the last one was installed

### Browser console Errors
![image](https://user-images.githubusercontent.com/11762429/96529412-72116a80-125b-11eb-8321-a328fcf75ce7.png)

### Request when press refresh several times until server response
![image](https://user-images.githubusercontent.com/11762429/96529645-1e535100-125c-11eb-89e1-faa60db5b755.png)

Thank you for all. Regards.

**Comment by githubsaturn** [comment]
Most likely your CapRover is failing its healthcheck and it keeps restarting, get the logs from caprover:

```
docker service logs captain-captain --since 5m
```

**Comment by kevinvarela** [comment]
`captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    | Error: (HTTP code 400) unexpected - client version 1.40 is too new. Maximum supported API version is 1.39 
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:331:7)
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:300:5)
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:275:14)
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at IncomingMessage.emit (events.js:326:22)
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at endReadableNT (_stream_readable.js:1244:12)
captain-captain.1.8nst4sqxvzd0@caprover-ubuntu-s-1vcpu-1gb-nyc1-01    |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
`

**Comment by kevinvarela** [comment]
All time restart and try but show me **Error: (HTTP code 400) unexpected - client version 1.40 is too new. Maximum supported API version is 1.39** is possible rollback client version ? or modify any file to prevent this error ?

What solution do you think is the best way?

**Comment by githubsaturn** [comment]
You can manually rollback if you want:
```
docker service update captain-captain --image caprover/caprover:1.7.1 
```

**Comment by githubsaturn** [comment]
Also this is how you update your Docker: https://github.com/caprover/caprover/issues/797#issuecomment-674392443

**Comment by kevinvarela** [comment]
Thank you for all again. Regards.
