### ISSUE TITLE
One instance per node... perhaps global mode?

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#869]
At present I scale the number of instances of *some* of my apps (those that are more resource intensive) based on the number of nodes in the swarm.  

For example let's say I have one instance of `myapp` and one node in the swarm, when I scale from one to two nodes I increase the instances of `myapp` to two.  

But of course this doesn't guarantee that the two instances will be arranged with one on each of the two nodes, as I would like... sometimes they both end up on the same node, which partially defeats the purpose of scaling up.

In this case "I know better" than docker, and want to insist that there is "at most one instance per node".  This is basically what is asked [here](https://forums.docker.com/t/running-a-container-service-on-every-node-but-only-1-per-node/16583), and the suggestion there is (I think) to use the `global` mode.

As I understand it, using `global` would mean that *every* app would scale up in number corresponding to the number of nodes, not just the ones I want to.

I could live with this, if it was the only option available.  Is this compatible with CapRover?  How would I request `global` mode, and in that case would the "instance count" then apply *per node*?

Or is there a way to achieve this more flexibly, within the CapRover context?

**Comment by githubsaturn** [comment]
I think you can do this by setting `MaxReplicas`. You can do this via [docker CLI](https://docs.docker.com/engine/reference/commandline/service_update/) like this:
![image](https://user-images.githubusercontent.com/10582082/96791349-4a8ae100-13c6-11eb-9a1b-d85269fd563f.png)

Or you can use [service override](https://caprover.com/docs/service-update-override.html):

```
TaskTemplate:
  Placement:
    MaxReplicas: 1
```

**Comment by drmrbrewer** [comment]
Ah great, looks like quite a new option?  

Since I am doing this automatically based on what you do [in here](https://github.com/caprover/caprover/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js), I guess that I can implement this with something like:

    updateService(serviceName, /* ... */, maxReplicas, /* ... */) {
        // ...
        maxReplicas = Number(maxReplicas);
        if ((maxReplicas && maxReplicas > 0) || maxReplicas === 0) {
            updatedData.TaskTemplate.Placement = updatedData.TaskTemplate.Placement || {};
            updatedData.TaskTemplate.Placement.MaxReplicas = maxReplicas;
        }
        // ...
    }

Is that reasonable?  I have allowed `maxReplicas` to be `0` on the basis that there doesn't seem to be any reason why `instanceCount` and `maxReplicas` can't be set such that `N x maxReplicas < instanceCount` (where `N` is the number of nodes)... so maybe `MaxReplicas` can effectively be used to put a lower limit on the number of instances that is requested by `instanceCount`.  Or maybe `instanceCount` trumps `N x maxReplicas`.  Anyway, it's a minor detail because I would always ensure that `N x maxReplicas == instanceCount`.

**Comment by githubsaturn** [comment]
Yea I am not aware of any Docker config that allows such a complex requirement. But feel free to look into placement strategy of Docker. Using the newly added [service override](https://caprover.com/docs/service-update-override.html) functionality, basically whatever is possible in Docker is now possible in CapRover.

And yes, you'd have to upgrade to 1.4

**Comment by drmrbrewer** [comment]
I came across a slight "gotcha" with `MaxReplicas`.  Initially I was setting this to be the maximum number of instances I want per node for a particular service.  Sounded reasonable.  But then I discovered that my new deployments weren't firing up.  Turns out that they were prevented from running because of the `MaxReplicas` constraint.  It seems that I need to set `MaxReplicas` to be **one more than** the maximum I want, because I'm guessing that when you deploy an app, a new instance is created before the old one is destroyed... so you need to go up to one more than your desired max, before dropping back to the right number.  I assume that this is how it works when deploying with CapRover, and that setting `MaxReplicas` to one more than the desired max is the way to go?

**Comment by githubsaturn** [comment]
You can probably do `stop-first` for your update strategy. Similar to `MaxReplicas`, it's something that Docker gives you and you can override it in CapRover using Service Override.

**Comment by drmrbrewer** [comment]
OK thanks.  It seems to me that `start-first` would generally be better, for near-zero downtime.  So maybe I might my abandon `MaxReplicas` idea as providing more downsides than upsides.  :-(

**Comment by VoidMonk** [comment]
Old issue, but fyi, setting both `TaskTemplate>Placement>MaxReplicas:` and `UpdateConfig>Parallelism` to a value of `2` in [Service Update Override](https://caprover.com/docs/service-update-override.html) config seems to ensure that only one service instance is placed on each node, and they're swapped/restarted properly on deployment. Found this clue at https://stackoverflow.com/a/67878294/1157545
