### ISSUE TITLE
Swarm Cluster , worker node is not receiving any request

### ISSUE THREAD

**Issue by rronalddas** [caprover/caprover#870]
Hi, I have setup a cluster of two nodes (Running NodeJS apps), using the `docker swarm join-token worker` flow.
Once I scale up the number of replicas for the given service, new docker containers are created in the worker node, but no http requests are routed to the containers in the worker node, All the requests are going to the containers in the manager node only, which the nginx, captain etc. The NodeJS service has a custom domain attached.

Is any extra nginx configuration needed for requests to be routed to the worker node also?

**Comment by githubsaturn** [comment]
No, by default Docker uses round robin DNS resolution to split the traffic across all nodes. First, make sure you have your firewalls [set up properly](https://caprover.com/docs/firewall.html). Next, to test, do this:
- Create an application with **persistent data**
- Deploy your NodeJS app
- After the deployment is done, navigate to App Config and set the NODE ID to your worker node's ID (from Nodes page)
- Now your nodejs application is on your worker node.

Under this test, is your application able to route the request to the worker node?
