### ISSUE TITLE
[Question] How to increase worker_connections?

### ISSUE THREAD

**Issue by darrist** [caprover/caprover#872]
I'm running latest Caprover on a DigitalOcean instance (4vCPU, 8GB RAM).
The server is constantly looking at at least of external 500 RPM on HTTP requests.

**Problems:**
1. Caprover UI constantly crash on me, either **500 nginx error** or the toast error in UI.
2. Nginx is reporting `worker_connections` on `captain-nginx` is insufficient. Where do I modify this? (Note: all services use default config)

**More Info:**
1. I have a replicate slave server that is connected to the worker pool. It was working OK as I see few Docker container are running there w/o resource exhaustion.
2. I have run `df -h` and `docker stats` and there is no resource exhaustion.

![image](https://user-images.githubusercontent.com/21124691/96860245-1b8f7080-1495-11eb-91f4-fb1cee9815e7.png)

**Comment by githubsaturn** [comment]
CapRover dashboard > Settings > Nginx Configuration
![image](https://user-images.githubusercontent.com/10582082/96939274-9f982700-149a-11eb-8547-9826c69404ad.png)

**Comment by darrist** [comment]
Changing this caused nginx service unable to boot. I had to follow wiki to make a copy of the config in order to reset.

**Comment by githubsaturn** [comment]
What did you change? If your configuration is invalid, then yes, nginx won't be able to start.
