### ISSUE TITLE
Update Manager Node IP? [Question]

### ISSUE THREAD

**Issue by dragonfire1119** [caprover/caprover#874]
How would I go about changing the manager node IP? I have already changed it on the server but portainer shows the wrong IP on the cluster?

**Comment by githubsaturn** [comment]
CapRover does not store the IP address of your manager IP. The IP address that portrainer shows is from Docker swarm's advertising IP. 

After setting up swarm, CapRover does not interfere with Docker swarm IP at all. I don't think Docker itself allows you to change the IP address. You'd have to backup your cluster and restore it on a new cluster. 

But if you find a way to update your Docker advertising address, it'll be completely transparent to CapRover as, like I said, this is not something that CapRover stores or uses.

**Comment by dragonfire1119** [comment]
Could you add a worker node then demote the manager temporarily & change the IP? Then re-promote the node back to the manager? Would this work? Is it a big deal to not have the right IP?

**Comment by githubsaturn** [comment]
> Could you add a worker node then demote the manager temporarily & change the IP? Then re-promote the node back to the manager? Would this work? 

No this doesn't work. You need 50% + 1 of your managers alive for the swarm to function. That means, you need at least 3 managers to perform the solution you suggested.

If you go with 3 manager node solution, you have to move `captain-captain` service manually to the new leader, and you have to copy the content of `/captain` to your new leader node.

**Comment by dragonfire1119** [comment]
@githubsaturn thanks so much for your time. Would the captain folder work in GlusterFS & Docker Volumes? So you don't have to move it to each node or is this not possible?

**Comment by githubsaturn** [comment]
In theory yes, but I personally haven't tried any sort of remote mount myself. I am happy to help you debugging issues if you want to try it out.
