### ISSUE TITLE
Setting up CapRover without a domain e.g just a DigitalOcean public IP address

### ISSUE THREAD

**Issue by thomascgray** [caprover/caprover#875]
Is it possible to setup CapRover without an actual domain name?

The docs seems to suggest its possible; at https://caprover.com/docs/get-started.html#a-domain-name the docs state

> Note that you can use CapRover without a domain too. But you won't be able to setup HTTPS.

However, I don't see it mentioned again, and during the setup in step 3, I'm not sure what to enter for "CapRover server root domain"

I found https://github.com/caprover/caprover/issues/246 but the issue is quite old (and from an old version of the tool?) and the rest of the comments led me to believe it's no longer relevant?

Apologies if this is a duplicate, I couldn't find any other relevant issues.

Thanks for all the hard work! The tool looks fantastic.

**Comment by githubsaturn** [comment]
How are you planning to use CapRover without a domain? You still need a way to access your apps. 

You need a domain anyways, but you may set up a DNS recording locally on your machine that points to that IP address. That way, you can access the instance from your local machine, but nowhere else. 

Regardless, you won't be able to enable HTTPS using a locally set up DNS record. 


Anyways, if you decide to go with this approach:
- After installing CapRover on our server, run:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```
- Set up a local DNS record with wildcard subdomain that points to the IP address of your domain. For example `*.mydomain.server` points to `123.123.123.123`
- Set up CapRover by logging in using the web dashboard `http://IP:3000` 



PS: note that you don't need a "new domain" for CapRover. If you already have a domain that you use for another purpose, you can just use a DNS record from your existing domain. For example, if you already have `awesome.com` you can use `*.myserver.awesome.com` for your CapRover without affecting `awesome.come` or `www.awesome.com`

**Comment by thomascgray** [comment]
Thanks so much for the reply! Will follow the above advice.

> How are you planning to use CapRover without a domain? You still need a way to access your apps.

I'm currently running a static site on a different host (Netlify, to be precise) and wanted to use CapRover to manage my Node API. So my loose plan, at least during prototyping (as I don't have a domain at all yet) was to simply point my React site directly to my IP address for API purposes.

Apologies if I've misunderstood something, and what I'm asking about/attempting is fundamentally unfeasible. Appreciate the response, will certainly be trying it ASAP 👍

**Comment by githubsaturn** [comment]
I see. You won't be able to do that because accessing the IP doesn't take you to any particular apps. When using CapRover, you have multiple apps, at very least, CapRover itself and your API app. You "can" do port mapping to access your app without a domain, but the complexity caused by it makes is not worthy to explore. I suggest, either you buy a domain, or go with a free domain. 

If that's not possible, you can always use a free domain provider like https://nip.io

They provide free dns. If your ip address is 11.22.33.44, you can use a domain like `server.11-22-33-44.nip.io` as your root domain. Note that their service is free, but you can't enable HTTPS with a `nip.io` domain.
