### ISSUE TITLE
Bulk Edit toggle in Apps Config doesn't work

### ISSUE THREAD

**Issue by thomascenni** [caprover/caprover#878]
What is the problem?
I have an app running and I want to bulk edit the environment variables.

Steps to reproduce the problem:
Click the Bulk Edit toggle

![Screen Shot 2020-10-28 at 10 31 28](https://user-images.githubusercontent.com/33039107/97443057-4bad9800-1909-11eb-92b1-ef9ee2d6f7ce.png)

On click, Caprover shows a blank page (I can send a video capture if needed).
These are the errors in the console:

![Screen Shot 2020-10-28 at 10 32 58](https://user-images.githubusercontent.com/33039107/97442783-fb363a80-1908-11eb-812a-6cf73103bf27.png)

Answers to the following questions where applicable:
Caprover v 1.8.0
RAM: 7.79 GB
OS: linux
CPU: 4 cores
Architecture: x86_64
Docker Version: 19.03.12

Other info:
Removing all the variables, the Bulk Edit toogle works and shows the empty textarea.

**Comment by githubsaturn** [comment]
Do you have to set specific env var to reproduce the issue? I don't seem to be able to reproduce the issue.

Can you try reproducing it on the demo instance: https://captain.server.demo.caprover.com

Login with `captain42` as your password and see if the issue exists on WordPress app for example.

**Comment by thomascenni** [comment]
Hi,
I tried adding variables in WordPress app in the demo instance, the issue is not reproducible.
I have other apps with a lot of environment variables, this problem only happens with one particular app.
The app that I am trying to deploy as a one click app is Plausible.io.
I have the YML template, I am pretty sure you'll get the same error if you try.
I cannot test on your demo instance since I am not able to create a new app.
Can you test with this template ?

https://gist.github.com/thomascenni/cd25a5df48935f2d8567b01e6ae6f2ba

Thanks for your support.

**Comment by githubsaturn** [comment]
The issue is the boolean values you are setting for env vars. You should set env vars as strings.

Change "DISABLE_REGISTRATION" and "DISABLE_SUBSCRIPTION" to `'true'` and you'll be fine. You can even see that github yaml parser is parsing the booleans differently: 
![image](https://user-images.githubusercontent.com/10582082/97512555-3152d900-1960-11eb-9c7b-02a631efb30a.png)

**Comment by githubsaturn** [comment]
This issue won't happen if you set the env vars via the dashboard, but just in case, I am adding some guardrails to avoid this issue even with boolean values in env vars in the future.
