### ISSUE TITLE
Cannot read property 'timeStamp' of undefined

### ISSUE THREAD

**Issue by diego-vieira** [caprover/caprover#879]
## What is the problem?
I have just deployed a fresh install of caprover 1.8.0 in a new Ubuntu 18.04 machine.

I was deploying an node app for testing and while it was building went to create a redis app from the app store and it has failed with 504 code.

Refreshed the page and saw the following

<img width="592" alt="Screenshot 2020-10-28 at 17 36 37 793" src="https://user-images.githubusercontent.com/930792/97474742-55082600-1944-11eb-99e7-0789ade0ed2a.png">
<img width="509" alt="Screenshot 2020-10-28 at 17 36 47 418" src="https://user-images.githubusercontent.com/930792/97474748-56395300-1944-11eb-8d26-519feac87e69.png">

I was using persistent login.

Managed to login again after deleting the auth key from localStorage and it looks fine - the app was there.

**Comment by githubsaturn** [comment]
The issue only happens where is an active build process, and it's already fixed: https://github.com/caprover/caprover-frontend/issues/56

Feel free to use the edge version. A new version will be released soon with the fix.
