### ISSUE TITLE
[Question] Effects of updating a captain service's log driver

### ISSUE THREAD

**Issue by berksonj** [caprover/caprover#883]
I am currently attempting to use fluentd as a logging driver for all my docker services.
For my apps, I am using a pre-deploy script to update the corresponding docker service. However, I cannot do this for captain apps such as captain-captain, captain-nginx, and captain-certbot. My solution was to update the service from the Docker CLI:

```bash
sudo docker service update captain-nginx --log-driver "fluentd" --log-opt tag="captain-nginx"
```

I initially tried using Docker's daemon.json, but it seemed that each service was individually overriding this.

However, I am wondering if this will be overridden on updates to Caprover, and if there are any other non-foreseen events.

Thanks,
Jake

**Comment by githubsaturn** [comment]
There are some parameters in each service that CapRover overwrites such as volume and ports. But I don't think log driver gets changed once the service is created. The best way to test is to simply restart the machine. CapRover upgrades are not different from a machine restart.

**Comment by berksonj** [comment]
Thanks! Just rebooted and my log driver settings were maintained.

**Comment by RobersonCosta** [comment]
@berksonj Could you make the predeploy code available? I'm not able to centralize the log using deamon.json configuration

**Comment by berksonj** [comment]
> @berksonj Could you make the predeploy code available? I'm not able to centralize the log using deamon.json configuration

Unfortuantely, I cannot find the original version I wrote, but the below code should assist you.

```js
var { v4: uuid } = require('uuid');

var preDeployFunction = function (captainAppObj, dockerUpdateObject) {
    return Promise.resolve()
        .then(function(){

            dockerUpdateObject.TaskTemplate.ContainerSpec.LogDriver["Name"] = "fluentd"
            return dockerUpdateObject;
        });
};
```

You can see what else you can modify by running `docker inspect srv-captain--APP_NAME` and looking in the `ContainerSpec` sections.

**Comment by ejose19** [comment]
This is what I'm using, as setting inside `ContainerSpec` didn't work

```javascript
function preDeployFunction(capRoverAppObj, dockerUpdateObject) {
  dockerUpdateObject.TaskTemplate.LogDriver = {
    Name: "fluentd",
    Options: {
      "tag": "captain-srv"
    }
  };
  return dockerUpdateObject;
}
```

**Comment by githubsaturn** [comment]
You can also try using `docker service update --log-driver ....  --log-opt ....  srv-captain-yourappname`

**Comment by pcace** [comment]
Hi there, is it still necessary to reboot the whole machine? 
I want to change the logging driver for one individual container wich is already in caprover, so i tried using this script: 

```
function preDeployFunction(capRoverAppObj, dockerUpdateObject) {
  dockerUpdateObject.TaskTemplate.LogDriver = {
    Name: "loki",
    Options: {
      "tag": "captain-srv",
      "loki-url": "http://srv-captain--loki:3100/loki/api/v1/push",
      "loki-retries": "2",
      "loki-batch-size": "400"
    }
  };
  return dockerUpdateObject;
}
```

but it not seems to update: 
```
docker inspect -f '{{.HostConfig.LogConfig.Type}}' 2033541da91d
json-file

```

any idea? rebooting the machine is something i dont want as a solution for this since there are a couple other services running...

**Comment by githubsaturn** [comment]
Try using `docker service update.....` does it work?

**Comment by pcace** [comment]
Hi, thanks a lot for reply! Yes - that works. 
is there a reason why it would not work by the predeploy function, and - will i have to do that manually every time now, or is this a one-time-operation

**Comment by githubsaturn** [comment]
Sorry for the super late response here! 

For things that CapRover doesn't manage actively (like log driver), it's a one time operation. 


For other things that CapRover managers actively (like ports, env vars etc), it has to run every time.


Now, back to the question, "why it doesn't work with predeploy" => I'm not sure, but maybe typo or etc.

Try running `console.log (dockerUpdateObject.TaskTemplate.LogDriver)` just before modifying it and run `docker service logs captain-captain` to make sure you're changing the correct field.
