### ISSUE TITLE
Feature Request: Outbound Webhook On Deploy, including build success/failure status.

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#884]
It would be really nice if CapRover could deliver an outbound webhook (for hooking up to my chat system) on successful deploys, as I trigger deploys automatically from some git repos/branches.  I had one fail recently and had no feedback other than the fact that my app didn't update and I had to log in and check the build logs.

It would be really nice if it could report build success/failure somewhere automatically.

**Comment by githubsaturn** [comment]
Agreed, it's a nice feature. It's already a requested feature here: https://github.com/caprover/caprover/issues/727
