### ISSUE TITLE
User Files not displaying

### ISSUE THREAD

**Issue by WillieIlus** [caprover/caprover#888]
Have successful deployed my app using caprover, and everything works fine except for user images. 

Staticfiles are working alright, static images are fine as well. But user images are not displaying. Have tried figuring how to do it for a week now. 

How do I configure my app to display images uploaded by users?

**Comment by githubsaturn** [comment]
What do you mean by user uploaded images aren't displaying?

Do you have a photo uploading app?

**Comment by WillieIlus** [comment]
Yes here is some part of my project

#model.py
    class Business(models.Model):
        user = models.ForeignKey(User, related_name='added_by', on_delete=models.PROTECT)
        logo = models.ImageField(upload_to="business/logos", blank=True, null=True)
#settings.py

    DEBUG = False

    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
    STATIC_URL = '/static/'
    
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    MEDIA_URL = '/media/'

#urls.py

    urlpatterns = [
                      #path
                  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

and edited my nginx file in my caprover dashboard like this
        location /media {
            root /var/www/biasharahub.com/media;
            #alias /media/;
        }
to no avail.

I temporarily changed my settings.py debug to True and everything is fine on production, though I know it's not recommended.

**Comment by githubsaturn** [comment]
I see. So you're having an issue with your own application. This looks like a bug from within your code. 

What makes you think it's related to CapRover?

**Comment by WillieIlus** [comment]
Sorry, I'm a novice in programming. I thought there was a way to edit nginx to be able to display user uploaded images.

**Comment by WillieIlus** [comment]
I configured nginx on caprover and it now serves files correctly. Sorry for bothering , and thanks so much githusaturn for your time and this great app.

**Comment by rasulkireev** [comment]
Can you please tell me what configuration ended up using? I'm running into a similar issue with serving media files.
