### ISSUE TITLE
Install of custom SSL certificate [Question]

### ISSUE THREAD

**Issue by LaunchedBerry07** [caprover/caprover#889]
I have read the following docs: https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

However, I don't get where I should reference the custom certificate file in the nginx config...

Could someone please help me with this?

Thanks a lot in advance!

**Comment by githubsaturn** [comment]
Is this for one of your apps or for your root `captain.domain.com` dashboard?

**Comment by LaunchedBerry07** [comment]
It's a wildcard certificate to be used with my apps

**Comment by githubsaturn** [comment]
Navigate to "Apps" > Your App > HTTP Settings > Nginx config. Then:
- Change all instances of `s.hasSsl` to `true` 
- Optionally change all instances of `s.forceSsl` to `true`
- Finally, change `ssl_certificate` and `ssl_certificate_key`:
```
        ssl_certificate     /nginx-shared/path/to/cert;
        ssl_certificate_key /nginx-shared/path/to/certkey;
```

Important notes:
- DO NOT use Enable HTTPS button if you go with this approach. 
- You'd have to set these for any new app that you set up.

**Comment by LaunchedBerry07** [comment]
@githubsaturn Oooh! I thought I could just install it once! But, okay, thanks a lot for your fast response!
