### ISSUE TITLE
[Deployment Issue] Self Hosted Gitlab Registry

### ISSUE THREAD

**Issue by getaway44** [caprover/caprover#895]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

I followed this tutorial : https://caprover.com/docs/ci-cd-integration.html
Everything is fine until the last command in the gitlab ci file :
When I run the cli command "caprover deploy" I have got this error : 
Error : (HTTP code 500) server error- Get https://...../image : denied: access forbidden

If applicable, content of `captain-definition` file:

no captain-definition file

Steps to reproduce the problem:

Follow the tutorial with a self-hosted gitlab

Answers to the following questions if applicable:
- Your OS and version? Gitlab Centos 7.3 and caprover CentOS 8
- RAM? 2go for each

**Comment by githubsaturn** [comment]
Have you added gitlab credentials to your CapRover? You've probably didn't follow this:
https://caprover.com/docs/ci-cd-integration.html#5--add-token-to-caprover

**Comment by getaway44** [comment]
Thanks for you help.
I added my credentials. I created a personal access token with the registry rights and added to the remote registry configuration in caprover
I did follow the tutorial and repeat the process many times. I've been very aware of every details.

**Comment by githubsaturn** [comment]
```
server error- Get https://...../image : denied: access forbidden
```

I am assuming that `https://...../image` is actually `registry.gitlab.com` ? Right?
In that case, yes, the only issue is the credentials. Can you write a step-by-step flow that leads to this error?

**Comment by getaway44** [comment]
It is our internal gitlab domain. (self-hosted gitlab)
I know it is an issue with credentials but I cannot find the source of the problem. 

The step-by-step flow is following the tutorial : 

1. Create acces token with read_registry and write_registry rigths. 

2. Add remote registry into caprover with 
- domain : our internal gitlab domain (I can access with a telnet to my `gitlab_domain:resgistry_port` from caprover server)
- user : my gitlab user
- password : acces_token created previously
- image : blank

3. from gitlab ssh  : 
`docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG`

We get the error on this command. The variables used here are created from gitlab global variables exactly like in the tutorials (copy-paste!).

Here are the full logs : 

> CapRover CLI has recently been refactored. Please report potential bugs here: https://github.com/caprover/caprover-cli/issues
>  ------------
>  Preparing deployment to CapRover...
>  Ensuring authentication...
>  Deploying my-test-gitlab-deploy to https://captain.caprover.xxxxx.net...
>  ------------------------- Thu Nov 05 2020 10:38:17 GMT+0000 (Coordinated Universal Time)
>  Build started for my-test-gitlab-deploy
>  An explicit image name was provided (gitlab.xxxxx.net:4567/caprover/project/my-build-image:cfb4a97aceb841ee837f42dc140cf9427f50b60b). Therefore, no build process is needed.
>  Pulling this image: gitlab.xxxxx.net:4567/caprover/project/my-build-image:cfb4a97aceb841ee837f42dc140cf9427f50b60b This process might take a few minutes.
>  Build has failed!
>  ----------------------
>  Deploy failed!
>  Error: (HTTP code 500) server error - Get https://gitlab.xxxxx.net:4567/v2/caprover/project/my-build-image/manifests/cfb4a97aceb841ee837f42dc140cf9427f50b60b: denied: access forbidden
>  Something bad happened. Cannot deploy my-test-gitlab-deploy at https://captain.caprover.xxxxx.net.

**Comment by githubsaturn** [comment]
Ah I see. It's an internal gitlab with custom port... Lots of things can go wrong with an internal setup...  selfsigned ssl (if you have any), network firewalls that block the access from within the container and etc... 

First, let's see if you can manually push/images via Docker (without CapRover at all):
`docker login gitlab.xxxxx.net:4567` on your CapRover server and enter your gitlab creds
```
docker pull alpine:latest
docker tag alpine:latest gitlab.xxxxx.net:4567/myprivateImage
docker push gitlab.xxxxx.net:4567/myprivateImage
docker pull gitlab.xxxxx.net:4567/myprivateImage
```

Does all the above command work without any issues?
If yes, then shell into your CapRover container see if you can telnet to `gitlab.xxxxx.net:4567`. Does this work too?

**Comment by getaway44** [comment]
Thanks for your help. 
For information the gitlab have a Let's Encrypt certificate

So the logs for the firsts commands : 

>[xxxxx@caprover ~]# docker pull alpine:latest
> latest: Pulling from library/alpine
> 188c0c94c7c5: Pull complete
> Digest: sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
> Status: Downloaded newer image for alpine:latest
> docker.io/library/alpine:latest
> [xxxxx@caprover ~]# docker tag alpine:latest gitlab.xxxxxx.net:4567/user/my-project
> [xxxxx@caprover ~]# docker push gitlab.xxxxxx.net:4567/user/my-project
> The push refers to repository [gitlab.xxxxxx.net:4567/user/my-project]
> ace0eda3e3be: Layer already exists
> latest: digest: sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e size: 528
> [xxxxx@caprover ~]# docker pull gitlab.xxxxxx.net:4567/user/my-project
> Using default tag: latest
> latest: Pulling from bseche/test-yohan
> Digest: sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e
> Status: Image is up to date for gitlab.xxxxxx.net:4567/user/my-project:latest
> gitlab.xxxxxx.net:4567/user/my-project:latest

In my gitlab I can access to the previously created image so it's seems to be ok.

Inside my captain-captain container the telnet works fine.

**Comment by githubsaturn** [comment]
Okay, next try this:

Create a new app, go to deployment tab, under Method 6, deploy an image from your private registry, like `gitlab.xxxxxx.net:4567/user/my-project:latest` what do you as the output of the build?

![image](https://user-images.githubusercontent.com/10582082/98445073-9be3e180-20e3-11eb-8eba-772db34b5753.png)

**Comment by SimoFR** [comment]
> Okay, next try this:
> 
> Create a new app, go to deployment tab, under **Method 6**, deploy an image from your private registry, like `gitlab.xxxxxx.net:4567/user/my-project:latest` what do you as the output of the build?
> 
> ![image](https://user-images.githubusercontent.com/10582082/98445073-9be3e180-20e3-11eb-8eba-772db34b5753.png)

Hello,
I am working with Gateway44, and the problem is solved.
I just had to add the port (4567) in the "domain" field of the docker registries declaration.
Thanks for your help

![image](https://user-images.githubusercontent.com/6803763/98678589-13717500-235f-11eb-8b1c-d8891e47883b.png)
