### ISSUE TITLE
[Deployment Issue] 504 Gateway timeout error

### ISSUE THREAD

**Issue by ajitgoel** [caprover/caprover#899]
I am trying to deploy my asp.net core application to Digital Ocean and at the `build source code `step, it throws a `504 gateway time-out `error. What can I do to debug the problem caprover could be having deploying my application to Digital Ocean? If this is a docker issue, I will close the question. 

**captain-definition file:**
```
 {
  "schemaVersion" :2 ,
  "dockerfilePath" :"./server/Dockerfile"
 }
```
- Your OS and version? Windows 10
- RAM? 8 GB
**Dockerfile:**
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["server/InstaTranscribe.Server.csproj", "server/"]
COPY ["client/InstaTranscribe.Client.csproj", "client/"]
RUN dotnet restore "server/InstaTranscribe.Server.csproj"
COPY . .
WORKDIR "/src/server"
RUN dotnet build "InstaTranscribe.Server.csproj" -c Release -o /app/build<=This is the step it is giving a gateway timeout error
FROM build AS publish
RUN dotnet publish "InstaTranscribe.Server.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InstaTranscribe.Server.dll"]
```

**Comment by githubsaturn** [comment]
The build step timeout is nothing to worry about. Probably your build is taking a long time without responding. 

You can view the build logs on the web panel as well:
![image](https://user-images.githubusercontent.com/10582082/98444989-1bbd7c00-20e3-11eb-9112-0d5aaca9e7db.png)


After the deployment, do you see a new successful deployment?

**Comment by ajitgoel** [comment]
Thank you @gethubsaturn, I get a message saying that the build is successful but it does not deploy. Please see below.

![image](https://user-images.githubusercontent.com/6394444/98447180-5f66b480-20e8-11eb-888f-cbdca11c7d5c.png)

If I try to view the application logs using the [link](https://caprover.com/docs/troubleshooting.html#how-to-view-my-applications-log), I see a `segmentation fault`.

![image](https://user-images.githubusercontent.com/6394444/98447194-7c02ec80-20e8-11eb-9f15-d098b5d5c1a9.png)

Any inputs on what could be wrong?

**Comment by ajitgoel** [comment]
This issue can be closed, I was trying to deploy my application on a 1 GB machine, raising the memory to 2 GB fixed the issue. Thank you @githubsaturn for your input. You guys are awesome.
