### ISSUE TITLE
Error: EBUSY: resource busy or locked, rmdir '/captain/generated/static'

### ISSUE THREAD

**Issue by greggameplayer** [caprover/caprover#900]
When starting caprover even when reinstalling it i get on my captain-captain : Error: EBUSY: resource busy or locked, rmdir '/captain/generated/static'

I'm running it on WSL 2 ubuntu with 26876 MB of ram.

**Comment by greggameplayer** [comment]
Ok just restarting docker and WSL 2 ubuntu fixed the problem, weird

**Comment by githubsaturn** [comment]
You're having a mounting issue with Docker. CapRover and Docker work best on vanilla Ubuntu systems.
