### ISSUE TITLE
3bit support, please [Deployment Issue]

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#903]
What is the problem?

I have a 32bit ubutnu 18 computer and need a 32bit build (i386)

Can this be done?

If maintainers can't do it, can I get some help building it on my other 64bit computer so I can build 32bit support (64 bit can build 32bit).

Thanks!

**Comment by githubsaturn** [comment]
Added build for linux/386 for CapRover: https://github.com/caprover/caprover/commit/5f0e47fd39c57990e8d9a751cd9e5e6b48ab3053

But looks like cerbot does't have 32bit images:
https://hub.docker.com/r/certbot/certbot/tags

Feel free to create an issue on their end to create a 32bit image

**Comment by githubsaturn** [comment]
Correction: looks like Node doesn't have 386 base image either. I'll have to revert the above commit.

**Comment by voarsh2** [comment]
Are you saying in the current state of the project, 32bit is impossible?

**Comment by githubsaturn** [comment]
From the looks of it, yes. Looks like Node doesn't have a 32bit image.

**Comment by voarsh2** [comment]
> From the looks of it, yes. Looks like Node doesn't have a 32bit image.

I'll ask them.

This is what certbot said: 

```
Unfortunately we can't re-add support to the Certbot snap because Ubuntu stopped supporting i386 in general.

For now, you can install the Ubuntu python3-certbot package via apt. It's 0.27.0-1, a fairly old version but it should keep working for the remainder of Ubuntu 18.04's life.
```

**Comment by githubsaturn** [comment]
CapRover uses certbot Docker images which I assume are based on Ubuntu 20 - so they won't be able to add the support I guess.
