### ISSUE TITLE
Changing branch name based on webbook or some other method automatically [Question]

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#904]
Would it be possible to deploy (for example) a branch after a specific webhook request?

Or for CapRover to change the branch of the current webhooked branch?

Basically, I don't want to get into GitLab runner and Kubernetes. I've done that.

I just want to be able to build different branches a bit more... automatically without updating the branch name in the container I have.

**Comment by githubsaturn** [comment]
You can specify the branch you want to build in the deployment tab.

**Comment by voarsh2** [comment]
> You can specify the branch you want to build in the deployment tab.

I know that.
I think you misunderstand.
I'm talking about creating a new contain by watching a GitLab project and creating new installations from new branches automatically....

**Comment by githubsaturn** [comment]
I see. No, that's not a built in behavior with CapRover. You can manually use scripts to dynamically create apps using CapRover CLI using `caprover api` [method](https://github.com/caprover/caprover-cli#api). Note that this is not a "fully supported" feature - you'll have to explore the API by yourself.
