### ISSUE TITLE
[Question] Laravel - permission denied when storing files in storage sub folder

### ISSUE THREAD

**Issue by louis-l** [caprover/caprover#907]
Hi there,

Thanks for the awesome package. 
Im using this to deploy my Laravel app and Im running into permission issue.

Im running Laravel 8 and 1 of the controller will dynamically create sub storage folder in "**/storage/app/temp/{date}**" where `{date}` is the current date (e.g. "2020-11-17") to store temporary files. Here is the code:

```
 app('filesystem')->makeDirectory('temp/'.now()->toDateString());
```

However, the created folders get "root" user and group permission. They are supposed to be "www-data" instead.

My Dockerfile is the same as https://github.com/jackbrycesmith/laravel-caprover-template/blob/master/.deploy/Dockerfile 

For now, I have to SSH to the app and manually run `chown -R www-data:www-data temp` to fix this (cause I need it to work asap).

My question is: is there a way to fix this programmatically? (e.g. fix the user/group permission for newly created storage folders)

Thanks.

**Comment by githubsaturn** [comment]
This is a Docker question, not specific to CapRover. You'd get a more detailed response on StackOverflow or the "laravel-caprover-template" repository you mentioned. But to provide more context:

The user your app's process run under is defined in the Dockerfile. For example, you can add this bit to your Dockerfile, just before `ENTRYPOINT`

```
USER www-data
```

This _might_ work or may not work. It really depends on the entrypoint requirements in that Dockerfile.

**Comment by githubsaturn** [comment]
Update: Looks like someone opened a PR that has changed USER to www-data, feel free to have a look here: https://github.com/jackbrycesmith/laravel-caprover-template/pull/5/files
