### ISSUE TITLE
How to run app with privileged param?

### ISSUE THREAD

**Issue by smkamranqadri** [caprover/caprover#909]
I am working on jenkins and it required dind container for pipeline. So questions is how can I run dind app with privileged param since it is only possible with docker run command or docker api?

**Comment by githubsaturn** [comment]
Here is an example for a container that uses Docker API: https://github.com/caprover/one-click-apps/blob/af172b6680583487bdeacf230d7abaf9b57f4811/public/v4/apps/gitlab-runner.yml#L7
