### ISSUE TITLE
Deployment only on change inside specified folder in repository/branch

### ISSUE THREAD

**Issue by FloMaetschke** [caprover/caprover#911]
**Is your feature request related to a problem? Please describe.**
I have mutliple node projects inside one repo and multiple different apps in caprover auto deploy from git.
I just want to update a single app on a push instead of all when changing only code inside one app folder in the repository.

**Describe the solution you'd like**
Add the possibility to only update an app if the change is inside a specified folder/path of the repository.

myrepo/app1  --> only trigger app1
myrepo/app2 --> only trigger app2

**Comment by githubsaturn** [comment]
TLDR: It's not possible.

CapRover doesn't keep the source version of the previous build. It just keep s the built artifact. When a webhook is called, it clones the repo and it triggers a build.

The best way  around this is to change your CI/CD such that it calls the webhook for each app when the app is changed - although I am not even sure how you can do this on the CI/CD side.

**Comment by FloMaetschke** [comment]
Hi,
i am actually using a self made solution using node-red with a simple function like this:

```

function projectHasChanges(project, commits) {
  for (const commit of commits) {
    if (commit.modified && commit.modified.length > 0) {
      if (commit.modified.find(x => x.startsWith(project))) {
        return true;
      }
    }
    if (commit.added && commit.added.length > 0) {
      if (commit.added.find(x => x.startsWith(project))) {
        return true;
      }
    }
    if (commit.removed && commit.removed.length > 0) {
      if (commit.removed.find(x => x.startsWith(project))) {
        return true;
      }
    }
    return false;
  }
}


const commits = msg.payload.commits;

msg.payload=  {
    web : projectHasChanges('web', commits),
    backend : projectHasChanges('backend', commits),
    worker : projectHasChanges('worker', commits),
    workerApi : projectHasChanges('worker-api', commits)
};

return msg;
```

With this, you won't need to keep the source version. Caprover just needs to parse the webhook. An addional simple input-textfield on the deployment page with filterPath or something similiar and its ready to go.

**Comment by githubsaturn** [comment]
Yes, this is going to the specific to "your" solution. It's not a standard solution. Now that you have setup your Node RED. You can easily modify your code such that it call appropriate webhook when each is changed. Something like this:
```js
if (projectHasChanges('web', commits))
    callWebhook(WEB_WEBHOOK_URL)

if (projectHasChanges('backend', commits))
    callWebhook(BACKEND_WEBHOOK_URL)

// and etc...

```

**Comment by FloMaetschke** [comment]
already doing this, but i thought it might by an advancement for caprover to support this directly.

**Comment by githubsaturn** [comment]
It would have been, if this was a standard approach. But it's specific to this use case.
