### ISSUE TITLE
Docker deployment, 80 and 443 utilised already [Deployment Issue]

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#912]
What is the problem?
I am trying to install a docker image but gave up using CapRover interface because then I'd need to clone the repo personally, make some tweaks, and I don't feel comfortable doing that myself.

So, I ran this in my terminal:
```
docker run --privileged=true -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 127.0.0.1:555:443 --name yunohost -t domainelibre/yunohost
```
What I was hoping for was to run my application on port 555.

Correct me if I am wrong, but I can edit the caprover nginx to port forward 555 to 443 for a specific domain?
(this is without installing the nginx reverse proxy app).

Any pointers?

**Comment by githubsaturn** [comment]
As I mentioned previously, CapRover's nginx ports are baked in the code and even if you change them on the docker service, they will revert back to the default one automatically after a restart. 

You cannot change the incoming port of nginx, but for downstream, you can set anything. The downstream could be a Docker container (default case), it could be another port on the same machine, or it could be a remote URL

**Comment by voarsh2** [comment]
I assume this all means it's virtually impossible to run CapRover and smidge program requiring 80/443 ports? To have them working on the same machine. I.e changing what CapRover uses.

**Comment by githubsaturn** [comment]
Correct

**Comment by SaadBazaz** [comment]
How much refactoring would it take to change this behavior? Why is it baked in, in the first place?

**Comment by githubsaturn** [comment]
Not much refactoring is needed. But what's the use case?

CapRover is designed to be used as the frontend loadbalancer, not behind another load balancer. The SSL termination point, the wildcard DNS routing are all the main features of CapRover. By running CapRover at a different port, it means that you're running it behind another loadbalancer, that means you're losing all these features. Unless there is a usecase that I am missing?

**Comment by SaadBazaz** [comment]
I had this small idea, of running Nextcloud + Caprover + JupyterLab on a homelab, so I could create a sort of "Google Cloud" (Nextcloud -> Drive, Caprover -> Firebase, JupyterLab -> Colab) which I could rent out to customers for a subscription fee.

I was just pondering around as to how that'd be possible. Tried running Nextcloud and Caprover together, but got a port conflict. So changed the Nextcloud port for now.

I suppose a huge hurdle in this idea is the multi-user problem in Caprover. Currently looking into creating separate VMs for each user, and running separate Caprover instances in each of them. But I don't know how the domain-ing would work then. 

The idea's a mess but trying to make sense of it :P

**Comment by barbaldo** [comment]
@githubsaturn possibly many people using CapRover for home servers already have something like apache taking port 80 and / or 443, therefore it could be very useful to be able to set them manually. Not very useful enterprise-wise but yeah that's my situation, I'd like to run both apache and CapRover
