### ISSUE TITLE
Cloning docker image - it doesn't start by itself [Deployment Issue]

### ISSUE THREAD

**Issue by voarsh2** [caprover/caprover#913]
What is the problem?

I cloned a docker image and specified ports and it does not run.

Do I need to execute something in bash in the container?
All I see is 
```
Your app will be here!

Go ahead and deploy your app now!
```

**Comment by githubsaturn** [comment]
I am assuming by cloning you mean "pulling" . Then no. It doesn't start automatically.

Step1: create an app
Step2: Navigate to deployment tab for that app and under method 6 enter the image name (for example `nginxdemos/hello:latest`) and click on deploy

![image](https://user-images.githubusercontent.com/10582082/99745389-8d180a00-2aa7-11eb-926d-8398d1e2e9c1.png)

**Comment by voarsh2** [comment]
> Step2: Navigate to deployment tab for that app and under method 6 enter the image name (for example `nginxdemos/hello:latest`) and click on deploy

Thanks.
But I mean, after pressing "Deploy Now" the app doesn't start.

I suppose some apps need the docker cli to pass arguments, etc?

**Comment by githubsaturn** [comment]
It depends on the app. Most apps (almost all of them) should work like this. To test, you can test `nginxdemos/hello:latest` or `nginx` or etc
