### ISSUE TITLE
All Node Ports [Question]

### ISSUE THREAD

**Issue by mehdiamenein** [caprover/caprover#914]
I usually do the steps below when I create a new VM:

1. install & activate ufw, fire2ban
2. change ssh port
3. remove root auth permission
4. remove password authentication

in case of the leader node I did this all and used a passphrase secure ssh to connect to it.

then I made a ssh-key with no passphrase on the vm and used its public key for the other nodes. I wanna do the same 4 steps for them but am not sure if I have to add any other port than these below to the new node (or can remove any of them):

* 3000
* 2377
* 4789

should I add 80, 443 and 996 or they are only necessary for the leader?

I read questions and doc file below, I hope I did not miss any previous question again:
https://github.com/caprover/caprover/issues/629
https://github.com/caprover/caprover/issues/743
https://github.com/caprover/caprover/issues/893
https://caprover.com/docs/firewall.html

thank you again for your wonderful tool.

**side note**
I saw others also requested 2 factor auth for login to the app, will there be any chance to get this feature in near future? 

I implemented 2 factor authentication for laravel & done a couple of nodejs projects in passed few years and am familiar with typescript. If there is any help I can do in this field please let me know

**Comment by githubsaturn** [comment]
The only ports that you need to keep open on non-leader nodes are:
7946 TCP/UDP for Container Network Discovery
4789 TCP/UDP for Container Overlay Network
2377 TCP/UDP for Docker swarm API


> side note
I saw others also requested 2 factor auth for login to the app, will there be any chance to get this feature in near future?
I implemented 2 factor authentication for laravel & done a couple of nodejs projects in passed few years and am familiar with typescript. If there is any help I can do in this field please let me know

The problem is the false sense of security. CapRover's auth token aren't scoped. They are root access auth tokens.
The first step before introducing 2factor auth is to introduce limited scoped auth keys. This is more complex. We might get to it at some point, but not in near future.

**Comment by mehdiamenein** [comment]
Then is there any way (beside manually modifying the nginx) to have captain.somthing.server.domain.com in an entirely different subdomain

like captain.somthing.anotherserver.domain.com

the reason that I ask this is, I want to use cloudflare and I can not use proxy over wildcard unless I am using a enterprise account. I want to have proxy over captain sub-domain only to add page rules to it like security level high and etc.

if I have to modify the nginx file for it, is there any recommended way?

**Comment by githubsaturn** [comment]
Is this what you are trying to do?

User ---https----> cloudflare ---http----> CapRover Server

**Comment by githubsaturn** [comment]
There is a lot of previously asked questions about cloudflare: https://github.com/caprover/caprover/search?q=cloudflare&type=issues

**Comment by mehdiamenein** [comment]
I read the articles and managed to have a scenario like this for a domain:

traffic => cloudflare (Proxy -> SSL Full (Strict)) => CapRover (LetEncrypt) => Wordpress

User ---https----> cloudflare ---https----> CapRover Server

but when I attempt to try the captain sub-domain for this approach it was not allowing me so I though maybe if I can change the captain sub-domain to something else, then it might work.

by somthing else I mean a sub-domain seperated from wildcard

Example:
if now => captain.xyz.domain.com with the A Record *.xyz.domain.com
future => captain.zzz.domain.com instead of captain.xyz.domain.com (with single A Record to it)

**Comment by githubsaturn** [comment]
I see! I honestly didn't know you could have HTTPS between cloudflare to CapRover! So good to know! If you found more details and you felt you want to write a quick write up, I can put it in the docs for other people who are looking into this.

**Comment by mehdiamenein** [comment]
Sure, for now 1 scenario that was tested with wordpress is:

1. I made a WordPress with CapRover (Linked Redis & MySQL in it)
2. made a certificate with LetEncrypt for it
3. Enforced Https on CapRover
4. On cloudflare made a A Record to the ip for my desire domain (EX: A Record for the domain => <caprover-leader-ip>)
5. On CapRover put the domain on app domain input and enabled https for it
6. On CloudFlare put the new domain https to full strict mode & enforced Https

for now the domain is working, it might be better to enforce HTTPS on CapRover and on CloudFlare at the end but still I am not sure enough to share exact steps for it to make a doc file, I will test it with another Laravel app I created next week and see if it can work with the same exact steps

2 things still will be really helpful:
1. I can remove the initial sub-domain that will be created with each app (I mean the one with wild-card => app-name.paas.domain.com)
2. It will be great if captain sub-domain can be seperated from wildcard

* second one will really help cause if the system is under-attack and cloudflare proxy is active you can make a security rule to attend the captain sub-domain with highest priority and even block it during attack. (one other possiblity would be similar to protainer.io where it is on a sperated port and each time I do not have any work with the dashboard I just block that port on my firewall)

I can change this by manually playing with the Nginx files which I prefer not do since it can cause issues if I wanna add other domains later to it
