### ISSUE TITLE
Two postgres containers

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#916]
Not sure how I did this, maybe it was running `docker restart` on the container, but I ended up with two postgres containers:

    # docker ps -f name='srv-captain--postgres13\.'

	CONTAINER ID        IMAGE                                                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
	230947f490fd        registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        5432/tcp            srv-captain--postgres13.1.ojamdpi9ew1gme07fypwhj7lv
	a9dd541ab201        registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   "docker-entrypoint.s…"   12 hours ago        Up 26 minutes       5432/tcp            srv-captain--postgres13.1.mo7x2s9vb7c54qs273dwpcs50

Didn't even know you could have two postgres containers (instance count in CapRover is locked at `1`)...

I have tried restarting the postgres service from the CapRover console to see if I can get back to one container, but it remains at two.  Any hint about how to get back to one?  I'm nervous about just using `docker rm` on one of the containers in case I kill off the wrong one or end up with database corruption (this is the production database).

(All I was trying to do was to increase `max_connections` and `shared_buffers` in the `/var/lib/postgresql/data/postgresql.conf` file within the postgres container and then restart the postgres container...)

EDIT... more info:

	# docker service ps --no-trunc srv-captain--postgres13

	ID                          NAME                            IMAGE                                                                 NODE                 DESIRED STATE       CURRENT STATE                ERROR                                                                                                                             PORTS
	ojamdpi9ew1gme07fypwhj7lv   srv-captain--postgres13.1       registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   myserver-01          Running             Running about an hour ago                                                                                                                                      
	n9mlmo5evg6bm79e36crzyn8z    \_ srv-captain--postgres13.1   registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   myserver-01          Shutdown            Failed about an hour ago     "No such container: srv-captain--postgres13.1.n9mlmo5evg6bm79e36crzyn8z"                                                          
	agompefnnrbt4e0kfvou3zkm7    \_ srv-captain--postgres13.1   registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   myserver-01          Shutdown            Shutdown about an hour ago                                                                                                                                     
	mo7x2s9vb7c54qs273dwpcs50    \_ srv-captain--postgres13.1   registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   myserver-01          Shutdown            Complete 2 hours ago                                                                                                                                           
	59te8tzfgqn590y90c2mscrun    \_ srv-captain--postgres13.1   registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   myserver-01          Shutdown            Rejected 13 hours ago        "mkdir /var/lib/docker/overlay2/8dd894de25f24255aa1beb4feb31fe7674cf1e8534ef88e546d6f3c9a89d7dd6-init: no space left on device" 

    # docker inspect -f "{{.Status.ContainerStatus.ContainerID}}" ojamdpi9ew1gme07fypwhj7lv

    230947f490fda84a128be307dc24b90ae2ab4fadd1f6b363527b16973cabe0a6

So I think it is fairly safe to remove the other container with `docker rm a9dd541ab201`... but still not sure how it got to this state and why that container has a status of `Up` :-/

EDIT2: I was brave and did a `docker stop a9dd541ab201`... weirdly both that container *and* the other `230947f490fd` were stopped as a result, and another started in their place:

	docker ps -f name='srv-captain--postgres13\.'

	CONTAINER ID        IMAGE                                                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
	3916e56887bd        registry.myserver.mydomain.com:996/captain/img-captain-postgres13:2   "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        5432/tcp            srv-captain--postgres13.1.il4aga71o3tvxsapdl2czhp6n

I then did a `docker container prune` which cleared out both stopped containers, and all seems to be back to normal hopefully.

Now I just need to figure out how to change `max_connections` and `shared_buffers` without messing it up like this again!

Possibly the only thing I did wrong was to restart the postgres *container* (after changing these parameters in `postgresql.conf`) rather than the postgres *service*?

i.e. I should have maybe done:

    docker service update srv-captain--postgres13 --force

instead of e.g. `docker restart 5j3n4l0j90fd` ??

**Comment by githubsaturn** [comment]
Yes, usually `docker service update srv-captain--postgres13 --force` is the preferred way. But the other way shouldn't result in 2 containers... Looks like a bug in Docker swarm scheduler to be honest. I feel like recently there is a surge of bugs in Docker swarm. I hope they start resolving these issues.
