### ISSUE TITLE
[Question]  How do I actually use the reverse proxy function of Caprover?

### ISSUE THREAD

**Issue by UNlDAN** [caprover/caprover#919]
I got caprover running, but I am trying to figure out how to use the reverse proxy function. It just seems too complicated to me, and there is not many words about it in the documentation.

Actually, does Caprover do what I am asking for (If I have localhost:2000 and want it at subdomain.mydoimain.tld)? Or am I using the wrong tool for the job?

**Comment by githubsaturn** [comment]
If you want to host an application on your local machine and expose it to the internet, CapRover is not necessarily the right tool for you. Look into "ngrok" perhaps.

**Comment by githubsaturn** [comment]
CapRover allows you to host your applications in the cloud on servers.
