### ISSUE TITLE
Support docker configs

### ISSUE THREAD

**Issue by Yajo** [caprover/caprover#920]
**Is your feature request related to a problem? Please describe.**
Yes, I want to package an app that requires a config file. Current spec doesn't support that.

**Describe the solution you'd like**
Docker supports [swarm configs](https://docs.docker.com/engine/swarm/configs/). These are also [supported in Docker Compose file v3](https://docs.docker.com/compose/compose-file/#configs). It should be usable in one click app definitions too.

**Describe alternatives you've considered**
- Use some ugly workarounds like adding an entrypoint that reads an env variable and writes it to a config file on disk, or adding a sidecar container that writes the config.
- Deploy the stack directly with `docker stack deploy`, which supports this.
- Use an alternate packaging format, such as https://github.com/docker/app, which supports the full docker-compose v3 spec.

**Comment by githubsaturn** [comment]
https://github.com/caprover/caprover/issues/921#issuecomment-732948515

**Comment by Yajo** [comment]
I understand that caprover doesn't want to support *all* things Docker does... but I do think it should support *this* one thing.

Not all apps can be configured with env variables or CLI flags (which I am reading now that aren't supported either :thinking:).

**Comment by Yajo** [comment]
To make previous statement more clear, I'm trying to fix https://github.com/caprover/one-click-apps/issues/283, but it won't support env-variable settings as you can see in https://github.com/matrix-org/synapse/issues/7758#issuecomment-652975077.

So, without a way to put config files somewhere, caprover is limiting the amount of apps that can be packaged.

**Comment by githubsaturn** [comment]
> but I do think it should support this one thing

The problem is that it's not this one thing. Config is required for synapse, `host` or `shm_size` is required for another app.

**Comment by githubsaturn** [comment]
Having said that, what can be done as a more holistic solution is to automatically create [service override](https://caprover.com/docs/service-update-override.html) for all the attributes in one-click apps that are not used by CapRover. That way, we would cover everything. Feel free to open another issue to track that.
