### ISSUE TITLE
pass git revision to docker build as build arg?

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#922]
I'm trying to expose the git revision of a build to a program so it can report it in errors, et c.

It would be useful to expose the current git revision in a build arg such as `CAPROVER_GIT_COMMIT_SHA` or something during automatic webhook git build, so that the Dockerfile can do something with it (such as echo it to a file in the built image, so that the program can pick it up and read it).

In the Makefiles I normally use for generating such an id, I use the command: `git describe --always --dirty=-dirty`.

**Comment by githubsaturn** [comment]
Good suggestion! Thanks!

In the meantime, you may already be able to do that by adding this to your Dockerfile:

```Dockerfile
RUN mkdir -p /git-source
COPY ./.git  /git-source
WORKDIR /git-source
RUN git rev-parse HEAD > /githash 
WORKDIR /
RUN rm -rf  /git-source

## At this point, /githash file contains the hash of your git commit, so you can just read it, load it into an env var and etc...
```

The code above is totally untested, but it should give you the idea.

**Comment by sneak** [comment]
That's what I ended up doing.  I wasn't sure if caprover was going to expose `./.git` in the build context it sends, but it looks like it does.

**Comment by matt-oakes** [comment]
I wasn't able to get this working with the method described above as the `.git` file is not included in the tarball when `git archive` is run.

I have opened a very simple PR which automatically sets the environment variable with the git commit hash that is being used to build it #1049
