### ISSUE TITLE
[Question] Does this auto restart apps when they crash?

### ISSUE THREAD

**Issue by seiyria** [caprover/caprover#923]
I haven't been able to figure this out or find this in the issue tracker. When my apps crash, there are no logs in caprover's output area, and the app is simply crashed. I can force build to re-deploy it, but I can't see any crash logs if any, so I'd have to log into the server to check what went wrong. 

It doesn't seem to auto restart my apps on crash, either, but is there some configuration setting I can set to do so?

**Comment by githubsaturn** [comment]
When you say crash, are you referring to a build failure or a runtime crash? 

In the second case, runtime crash, Docker swarm simply restarts your service. You can see this by running
```
docker service ls
```
that displays the currently running instances and desired instances.

**Comment by seiyria** [comment]
I believe it's a runtime crash, but I don't ever see any logs and hit restart build and then it comes back up. I've had to do a few manual restarts since starting to use caprover so that's why I wanted to ask. Is there a case where it would not restart automatically?

**Comment by githubsaturn** [comment]
>  I believe it's a runtime crash, but I don't ever see any logs and hit restart build and then it comes back up

There are two logs on the panel on CapRover, the top window is the build logs panel, and the panel below the deployment history is the app runtime logs.

![image](https://user-images.githubusercontent.com/10582082/100556126-eb927480-326d-11eb-83d4-98f5f4ed01ed.png)


> Is there a case where it would not restart automatically?

No. Unless it's a startup crash where your container cannot be booted up. If your container crashes on startup and it keeps getting restarted immediately, it'll be eating up your system. So to avoid this, there is a slight delay of a few seconds. Note that the container scheduling process is completely done by Docker swarm. CapRover is just a thin layer on top of Docker swarm.

**Comment by seiyria** [comment]
I see. Well, I'll definitely check in next time and see if there are any docker logs before I restart via caprover. This time, the App Logs area was completely empty and the app was not started, despite having been running earlier today. So I'm not sure what's up, but it's good to know it restarts my apps automatically, thanks!

**Comment by githubsaturn** [comment]
If you have a case where your app doesn't get restarted after a crash, gather output from the following commands and post it on Docker's github issues for them to look into.

```
docker service ls
docker service inspect srv-captain--your-app-name
```
