### ISSUE TITLE
[Question] Elasticsearch Cluster Formation

### ISSUE THREAD

**Issue by dragonfire1119** [caprover/caprover#924]
I keep getting `master not discovered yet: have discovered` & it doesn't see my master with the IP behind: srv-captain--elasticsearch. I went in the docker container and tried to curl the IP that it's trying to connect to & it times out.

If I curl the ``srv-captain--elasticsearch:9300`` from inside any container it works.

```
discovery.seed_hosts=srv-captain--elasticsearch,srv-captain--elasticsearch-2
```

I figured out that the IP is different on the advertised one so it's failing on follow up connection. Not having luck on changing the advertised IP on /_cat/nodes.

Tried to change ``network.host=srv-captain--elasticsearch`` but failing to start on 9300 port.

Thanks for any help!

**Comment by nstCactus** [comment]
Did you manage to get this to work?

**Comment by dragonfire1119** [comment]
@nstCactus I did get this to work but would not recommend doing it. I had a lot of disconnections with adding data.
