### ISSUE TITLE
[Question] Is Caprover suitable for untrusted users with monitoring?

### ISSUE THREAD

**Issue by elitwo** [caprover/caprover#926]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

So a service like Heroku allows virtually unverified users to deploy their applications. Obviously, those users are in a sandbox, and they can not just escape and takeover the server. Is this also the case for Caprover? If not, what work would I need to do in order to make it this way?

**Comment by elitwo** [comment]
To specify why I am asking: I'm not trying to start a Heroku competitor or anything. I just need a few users, that are not entirely trusted, not being able to access my server as root.

**Comment by githubsaturn** [comment]
Short answer: No.

CapRover apps (docker apps in general) can have root access to your host.
