### ISSUE TITLE
Manaully add worker and manager to cluster [Question]

### ISSUE THREAD

**Issue by mehdiamenein** [caprover/caprover#927]
Hi there, one question, in case that I add a worker or manager to the cluster with the docker swarm command instead of providing the private key to the leader node, will I miss any functionality or feature?

Like first login to the leader then run the 2 command below:

$ docker swarm join-token manager
$ docker swarm join-token worker

and then login to the other nodes and apply the command manually. (I checked this process on a test machine and the node was added successfully)

however I am not sure if I am missing any particular functionality of caprover by doing this

**Comment by githubsaturn** [comment]
No - you can simply bypass CapRover and manually add/remove nodes.
