### ISSUE TITLE
Converting Persistent to Non-persistent apps

### ISSUE THREAD

**Issue by joeinnes** [caprover/caprover#928]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

After following the instructions [here](https://caprover.com/docs/persistent-apps.html) to remove persistence from an app after converting it to use S3 for storage, how do I get CapRover to remove the tick on the dashboard, and remove the placement constraint (which is still there if I inspect the service)?

Is there a way to do that without deleting and recreating the app?

**Comment by githubsaturn** [comment]
No, there is no way to edit the app and remove the persistency check. Persistent apps are fundamentally different from stateless apps. There are anchored to a node as soon as they are created. You can "manually" edit the config file at `/captain/data/config-captain.json` and remove the persistency boolean, but it has no effects as the app is still anchored to a node.

So the proper way is to create a new app and delete the old one.
