### ISSUE TITLE
NetData version

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#933]
I've noticed that when I install NetData manually (as described [here](https://github.com/caprover/caprover/issues/122#issuecomment-357461340)) I get NetData version `1.19.0`, but with a fresh install of CapRover the version of NetData being used is still `1.8.0`.  Is it possible for this to be updated?

**Comment by githubsaturn** [comment]
The latest version doesn't have the capability to set the configs using env var. CapRover version is based on a [forked version](https://github.com/titpetric/netdata) which is no longer being updated.

Here is CapRover version if you're interested in taking the work in updating it: https://github.com/caprover/netdata-docker
The build and deployment is automated.
