### ISSUE TITLE
toomanyrequests (even with a mirror setup)

### ISSUE THREAD

**Issue by slava-vishnyakov** [caprover/caprover#935]
I'm trying to deploy an app via a custom one-click template (it's pretty simple, just image: postgres:13) and I'm getting: ```toomanyrequests: You have reached your pull rate limit``` on `postgres:13` image, however when I run `sudo docker pull postgres:13` the same image from the same server - it works just fine, no errors:

```
$ sudo docker pull postgres:13
13: Pulling from library/postgres
Digest: sha256:839d6212e7aadb9612fd216374279b72f494c9c4ec517b8e98d768ac9dd74a15
Status: Image is up to date for postgres:13
docker.io/library/postgres:13
```

To avoid the limits, I have done `echo '{"registry-mirrors": ["https://mirror.gcr.io"]}' | sudo tee /etc/docker/daemon.json` (see [here](https://cloud.google.com/container-registry/docs/pulling-cached-images)) and restarted the docker service, so again `sudo docker pull postgres:13` works just fine, but it fails when trying to use the template one-click app with the same image.

I also think that it's weird that I even stumble into this problem, since I'm not even requesting any new images, it should have already been cached multiple times.

Why does the template deploy fail?

P.S. The error when deploying is also pretty cryptic:

![image](https://user-images.githubusercontent.com/817931/101782879-9cb8ca80-3b0a-11eb-9d0b-1e17a78c7cde.png)

![image](https://user-images.githubusercontent.com/817931/101782901-a0e4e800-3b0a-11eb-8719-8fa78bb3acd2.png)

Maybe it should be handled more gracefully?

Thanks!

From logs:

```
Error: (HTTP code 500) server error - toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:328:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
```

**Comment by githubsaturn** [comment]
Curious to know how you solved your issue. Lately, I have seen lots of people are facing the issue with the ridiculously low limit of Docker Hub.

**Comment by slava-vishnyakov** [comment]
I think Google's mirror helped (see [here](https://cloud.google.com/container-registry/docs/pulling-cached-images)), but I can't be sure.
