### ISSUE TITLE
Service logs stopped working

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#936]
I know this is a docker problem, [reported by others here](https://github.com/moby/moby/issues/33183), but I wonder how the proposed "solution" works in the context of CapRover.  The suggestion (other than to re-boot the server which I am reluctant to do) is that demoting and then re-promoting the leader node makes the service logs kick back in.  In the context of CapRover, I have a single Manager node (on which my persistent volumes are and key services like postgres), and I scale up to create one or more Worker nodes depending on need (I do this automated but it's basically the same as scaling from the CapRover console).  Can I promote a Worker to being a temporary Manager, then demote the original Manager to a Worker then back to a Manager (and demote the temporary Manager back to a Worker)??  I am not experienced enough with docker to know how this will affect access to key persistent volumes on the current Manager node.

**Comment by githubsaturn** [comment]
Yes, you can do this with CapRover as well. But I suggest pausing CapRover before you do this. 
Also - I believe you cannot shutdown a manager node if you only have two managers, you need N/2+1 managers up otherwise your cluster will shut down

So your process will be:
- `docker service scale captain-captain=0` 
- Add two more managers to your cluster
- Demote the main node
- Promote the main node
- Demote other two managers
- `docker service scale captain-captain=1`

**Comment by drmrbrewer** [comment]
Thanks.  

> Add two more managers to your cluster

Is there any difference between using 'join as a manager node' in the console:

![image](https://user-images.githubusercontent.com/9009792/102017170-29f35d80-3d5d-11eb-8ca0-a404c34a531a.png)

and joining two nodes as workers and then promoting these to manager?

**Comment by githubsaturn** [comment]
No, there is no difference.

**Comment by drmrbrewer** [comment]
Seem to have got the swarm into a bit of a jam here :-/

    ID                            HOSTNAME     STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
    rxuh3m42jlh97nw6f6occvnh3     mercury-01   Down      Active                          20.10.1
    0famr9ze1n9z0yp2tpg3pdxvu     mercury-06   Down      Active                          20.10.1
    dkyedgl80k6k6dc0oh3tsd989 *   mercury-07   Ready     Active         Leader           20.10.1

Host `mercury-01` was the `Leader` (and has all the persistent volumes on it etc).  The other two were workers.  I promoted the two workers to manager, and demoted `mercury-01`.  Now both `01` and `06` are showing as `Down` ... wasn't expecting that.  Not sure how to get them back to `Ready`!

**Comment by githubsaturn** [comment]
Not sure what happened here. Maybe folks at [Docker's github](https://github.com/moby/moby) are able to help.

But personally, in these scenarios, I first try to add more temporary managers to the leader node to get it up and if mercury-06 doesn't have any persistent data on it, swarm will automatically reassign the services to other nodes.

**Comment by drmrbrewer** [comment]
Think I need to read up more on docker swarms before attempting this again :-)  The swarm still seems to be working, just about, though auto scaling (adding new nodes) isn't going so well.  Persistent resources (mainly postgres) on mercury-01 still seem to be fine, despite this node having a status of Down.  In the meantime, I've spun up a new server and will switch over to that, then have a play around with the mutant swarm I just created to learn a bit more about it all.

**Comment by githubsaturn** [comment]
I suggest playing around with https://labs.play-with-docker.com which gives you a nice playground to play with promote, demote and other docker swarm functionality to get a better understanding of what they do.

**Comment by drmrbrewer** [comment]
Good tip, thanks!
