### ISSUE TITLE
Images get lost in every update

### ISSUE THREAD

**Issue by WillieIlus** [caprover/caprover#938]
My website looses user uploaded images after update, and I'm not sure on a way to prevent it. The website is small so before any update I download the images first, then upload it in django admin. I know it's not best practice and will give me headache if the website grows. 

Is there a way to update code without loosing images? I asked in stackoverflow but no answer.

**Comment by githubsaturn** [comment]
https://caprover.com/docs/persistent-apps.html#persistent-apps

You have to use a persistent app, and create a volume where "Container Path" is the directory where files are uploaded.

This is called "Docker Volume"

**Comment by WillieIlus** [comment]
Thanks so much, I have created a new app with persistent data. In the app config I added persistent directories. (Path in app- no change, label- media,  and let caprover manage path) I there's something I'm doing wrong or not doing totally.  Since I still loose user files. 

Media root on my django project is media. Is there a tutorial on how to solve this. I get lost when I read docs. Thanks

**Comment by githubsaturn** [comment]
I am not familiar with Django apps. Perhaps post your question on stackoverflow.

Note that there is nothing "caprover" specific about this. You just need find the right path for the persistent directory path in the app.

If you're using Django template ID, your app is at `/usr/src/app` - hence your user uploaded files can be at `/usr/src/app/media` (I am not too sure about `media` part - this is where you need to ask someone who's familiar with Django.

**Comment by WillieIlus** [comment]
Thanks so much now its working out well.
