### ISSUE TITLE
Error restarting captain service: invalid mount config for type "bind": bind source path does not exist: /captain

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#939]
As first reported [here](https://github.com/caprover/caprover/issues/934#issuecomment-744037075), when restarting the `captain-captain` service I get the error message:

    # docker service update captain-captain --force
    captain-captain
    overall progress: 0 out of 1 tasks 
    1/1: invalid mount config for type "bind": bind source path does not exist: /ca… 
    service update paused: update paused due to failure or early termination of task mqo2k39bax94y6fiq7boxxtge

    # docker inspect mqo2k39bax94y6fiq7boxxtge
	[
		{
			"ID": "mqo2k39bax94y6fiq7boxxtge",
			"Version": {
				"Index": 6414
			},
			"CreatedAt": "2020-12-14T11:33:49.885809541Z",
			"UpdatedAt": "2020-12-14T11:33:53.874682066Z",
			"Labels": {},
			"Spec": {
				"ContainerSpec": {
					"Image": "caprover/caprover:1.8.2",
					"Labels": {
						"randomLabelForceUpdate": "a69331cd-26d7-48fa-885c-09764d34590d"
					},
					"Env": [
						"IS_CAPTAIN_INSTANCE=1"
					],
					"Mounts": [
						{
							"Type": "bind",
							"Source": "/captain",
							"Target": "/captain"
						},
						{
							"Type": "bind",
							"Source": "/var/run/docker.sock",
							"Target": "/var/run/docker.sock"
						}
					],
					"Secrets": [
						{
							"File": {
								"Name": "captain-salt",
								"UID": "0",
								"GID": "0",
								"Mode": 292
							},
							"SecretID": "4xcfmp7sb7svbbvizi7esqq2g",
							"SecretName": "captain-salt"
						}
					],
					"Isolation": "default"
				},
				"Resources": {},
				"Placement": {},
				"Networks": [
					{
						"Target": "l72bcdxl39ml3rqy34at66i9j"
					}
				],
				"LogDriver": {
					"Name": "json-file",
					"Options": {
						"max-size": "512m"
					}
				},
				"ForceUpdate": 2
			},
			"ServiceID": "bmmywzo2q3pwnyr9axogqcstk",
			"Slot": 1,
			"NodeID": "qb6aoiimqev3085ohqdqqqq8r",
			"Status": {
				"Timestamp": "2020-12-14T11:33:51.724750057Z",
				"State": "rejected",
				"Message": "preparing",
				"Err": "invalid mount config for type \"bind\": bind source path does not exist: /captain",
				"ContainerStatus": {
					"ContainerID": "",
					"PID": 0,
					"ExitCode": 0
				},
				"PortStatus": {}
			},
			"DesiredState": "shutdown",
			"NetworksAttachments": [
				{
					"Network": {
						"ID": "jtz0r9wgyowgb3p9pp4iycuhs",
						"Version": {
							"Index": 6
						},
						"CreatedAt": "2020-12-14T08:21:48.466538766Z",
						"UpdatedAt": "2020-12-14T08:21:48.476601998Z",
						"Spec": {
							"Name": "ingress",
							"Labels": {},
							"DriverConfiguration": {},
							"Ingress": true,
							"IPAMOptions": {
								"Driver": {}
							},
							"Scope": "swarm"
						},
						"DriverState": {
							"Name": "overlay",
							"Options": {
								"com.docker.network.driver.overlay.vxlanid_list": "4096"
							}
						},
						"IPAMOptions": {
							"Driver": {
								"Name": "default"
							},
							"Configs": [
								{
									"Subnet": "10.0.0.0/24",
									"Gateway": "10.0.0.1"
								}
							]
						}
					},
					"Addresses": [
						"10.0.0.137/24"
					]
				},
				{
					"Network": {
						"ID": "l72bcdxl39ml3rqy34at66i9j",
						"Version": {
							"Index": 20
						},
						"CreatedAt": "2020-12-14T08:21:53.716044946Z",
						"UpdatedAt": "2020-12-14T08:21:53.716829392Z",
						"Spec": {
							"Name": "captain-overlay-network",
							"Labels": {},
							"DriverConfiguration": {
								"Name": "overlay"
							},
							"Attachable": true,
							"Scope": "swarm"
						},
						"DriverState": {
							"Name": "overlay",
							"Options": {
								"com.docker.network.driver.overlay.vxlanid_list": "4097"
							}
						},
						"IPAMOptions": {
							"Driver": {
								"Name": "default"
							},
							"Configs": [
								{
									"Subnet": "10.0.1.0/24",
									"Gateway": "10.0.1.1"
								}
							]
						}
					},
					"Addresses": [
						"10.0.1.194/24"
					]
				}
			]
		}
	]

And yes, `/captain` *does* exist.  This happens even after a full re-build of this server from scratch.  If it's a Docker issue, it's not one that has happened before now... I'm using `Docker version 19.03.13, build 4484c46d9d`.

**Comment by githubsaturn** [comment]
Just tried this on a machine with the same Docker version and it worked fine:
```
root@scw-5e9dd2:~# docker -v
Docker version 19.03.13, build 4484c46d9d
root@scw-5e9dd2:~# docker service update captain-captain --force
captain-captain
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged 
root@scw-5e9dd2:~# 
```

------



To debug, try running this:
```
docker run -v /captain:/captain alpine
```

Does it throw an error or gracefully exits?


If it gracefully exits, try this:

```
docker service create \
  --name my-service \
  --mount type=bind,source=/captain=/captain \
  nginx:alpine

## Ensure your service is up and running:
docker service ls

## Try to restart the service:
docker service update my-service --force

```
Does this work?

**Comment by drmrbrewer** [comment]
# docker run -v /captain:/captain alpine
    Unable to find image 'alpine:latest' locally
    latest: Pulling from library/alpine
    05e7bc50f07f: Pull complete 
    Digest: sha256:a126728cb7db157f0deb377bcba3c5e473e612d7bafc27f6bb4e5e083f9f08c2
    Status: Downloaded newer image for alpine:latest

**Comment by githubsaturn** [comment]
> Maybe this is why? 

No, they are equivalent. 

> BTW with the suggested installation line above, you don't need to pre-pend with mkdir /captain &&

Correct. `docker run  -v /captain:/captain` implicitly creates the directory if it does not exist


----------------

>
```
# docker service update my-service --force
my-service
overall progress: 0 out of 1 tasks 
1/1: invalid mount config for type "bind": bind source path does not exist: /ca… 
service update paused: update paused due to failure or early termination of task 558g0zr1avci3khcnhse4c4pg
```
So this error happening with any service, not just CapRover. I suggest collect your system info and just log a bug at https://github.com/moby/moby

**Comment by drmrbrewer** [comment]
So it turns out that the docker version I was using (`19.03.13, build 4484c46d9d`) is not the latest.  I had been installing the `edge` version (see [here](https://download.docker.com/linux/ubuntu/dists/focal/edge/)) rather than the `stable` version (see [here](https://download.docker.com/linux/ubuntu/dists/focal/stable/)), originally because the `stable` version wasn't working with a new version of Ubuntu I wanted to use.  Now I have reverted to using the `stable` version, which is in fact newer than the `edge` version!

With the `stable` version of docker installed, I see:

    # docker -v
    Docker version 20.10.1, build 831ebea

    # docker service update captain-captain --force
    captain-captain
    overall progress: 1 out of 1 tasks 
    1/1: running   [==================================================>] 
    verify: Service converged

So, whatever docker bug it was, it no longer seems to exist.

**Comment by drmrbrewer** [comment]
@githubsaturn I'm seeing this problem again, this time with the latest stable version of docker:

	# docker -v
	Docker version 20.10.10, build b485636

Scale captain to 0:

	# docker service scale captain-captain=0
	captain-captain scaled to 0
	overall progress: 0 out of 0 tasks 
	verify: Service converged

Then scale back to 1:

	# docker service scale captain-captain=1
	captain-captain scaled to 1
	overall progress: 0 out of 1 tasks 
	1/1: invalid mount config for type "bind": bind source path does not exist: /ca… 

After a few retries, the scale operation does succeed... not sure why it would have a problem at first but then succeed only a minute later?

	# docker service ps captain-captain
	ID             NAME                    IMAGE                      NODE         DESIRED STATE   CURRENT STATE             ERROR                              PORTS
	1qhb2dm2tesr   captain-captain.1       caprover/caprover:1.10.1   myserver-01   Running         Running 15 seconds ago                                       *:3000->3000/tcp,*:3000->3000/tcp
	0wvot12eqrch    \_ captain-captain.1   caprover/caprover:1.10.1   myserver-09   Shutdown        Rejected 26 seconds ago   "invalid mount config for type…"   
	kxcdgomoyjnf    \_ captain-captain.1   caprover/caprover:1.10.1   myserver-09   Shutdown        Rejected 30 seconds ago   "invalid mount config for type…"   
	y4zz5o84i2c6    \_ captain-captain.1   caprover/caprover:1.10.1   myserver-09   Shutdown        Rejected 36 seconds ago   "invalid mount config for type…"   
	ub4oyk0xaby7    \_ captain-captain.1   caprover/caprover:1.10.1   myserver-09   Shutdown        Rejected 40 seconds ago   "invalid mount config for type…"

Probably this is not an issue with CapRover, but just mentioning it again in case it chimes with anything you've heard of?

Actually, looking at the rejections above, they are in relation to `myserver-09` which is a worker node:

	ID                            HOSTNAME      STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
	ametebh8so9ew0nvuuhc8cjes *   myserver-01   Ready     Active         Leader           20.10.10
	sqhwk5xwtjr3een2hc4fd0fh0     myserver-09   Ready     Active                          20.10.10
	5pycfkqi03idedoa3dukc9qg8     myserver-10   Ready     Active                          20.10.10

Isn't it odd that anything relating to `captain-captain` should be on anything but the manager node?

**Comment by githubsaturn** [comment]
Docker swarm scheduler should never schedule captain-captain service on any node but your main node. This is done via a Node ID constraint. Can you run `docker service inspect captain-captain --pretty` and `docker node ls` and print the output here?

**Comment by drmrbrewer** [comment]
# docker service inspect captain-captain --pretty

	ID:             ltp31w98swytmzkvi3g4ghfby
	Name:           captain-captain
	Service Mode:   Replicated
	 Replicas:      1
	Placement:
	UpdateConfig:
	 Parallelism:   1
	 On failure:    pause
	 Monitoring Period: 5s
	 Max failure ratio: 0
	 Update order:      stop-first
	RollbackConfig:
	 Parallelism:   1
	 On failure:    pause
	 Monitoring Period: 5s
	 Max failure ratio: 0
	 Rollback order:    stop-first
	ContainerSpec:
	 Image:         caprover/caprover:1.10.1
	 Env:           IS_CAPTAIN_INSTANCE=1 
	Mounts:
	 Target:        /captain
	  Source:       /captain
	  ReadOnly:     false
	  Type:         bind
	 Target:        /var/run/docker.sock
	  Source:       /var/run/docker.sock
	  ReadOnly:     false
	  Type:         bind
	Secrets:
	 Target:        captain-salt
	  Source:       captain-salt
	Log Driver:
	 Name:          json-file
	 LogOpts:
	  max-size:       512m

	Resources:
	Networks: captain-overlay-network 
	Endpoint Mode:  vip
	Ports:
	 PublishedPort = 3000
	  Protocol = tcp
	  TargetPort = 3000
	  PublishMode = host


	# docker node ls
	ID                            HOSTNAME     STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
	pw0nvuuhametbbh8so9c8cjes *   mercury-01   Ready     Active         Leader           20.10.10
	n2hc4fd0fh0sqhwk5xwtjr3pe     mercury-09   Ready     Active                          20.10.10
	kqi03idtdo5pycfa3dukc9qg8     mercury-10   Ready     Active                          20.10.10

**Comment by githubsaturn** [comment]
That's really bizarre. The constraint ID must be there and it's set as the first step of installation. 
https://github.com/caprover/caprover/blob/34490eee3cce5edf12dcc4469529a0fcab789d8c/src/utils/CaptainInstaller.ts#L358-L370


Did you do anything specific to this cluster? Backup/restore? Snapshot etc?

**Comment by drmrbrewer** [comment]
Well I do backup my caprover config, so that when I spin up a new server I can easily restore everything.  I'm using a "manual" approach that is discussed in the following: https://github.com/caprover/caprover/issues/187.  As part of the restore (which is all scripted) I do use `jq` to modify `/captain/data/config-captain.json` to set the node id of the persistent apps to that of the manager node, but I do not touch anything associated with `captain` itself... is that node id even stored in the config file?

**Comment by githubsaturn** [comment]
That explains it. Node ID is not stored in config file.

When you have a fresh install of CapRover (no manual restore, just a fresh brand new install), then the node ID constraint is there. But depending on what you do during backup and restore, the node ID constraint might not get transferred.

If you use [the built in backup](https://caprover.com/docs/backup-and-restore.html), the node ID will be converted to the new node ID automatically.

**Comment by drmrbrewer** [comment]
But I *am* doing a fresh install of CapRover... all I do after that is scale it to 0, change those node ids in the config file and a couple of other things, and then scale CapRover back to 1.

**Comment by githubsaturn** [comment]
Hmm.. okay, that shouldn't be a problem then. Can you run `docker service inspect captain-captain --pretty` right after the installation is done to see if there is the constraint in the config?

**Comment by drmrbrewer** [comment]
OK.  Where is the constraint stored?  I'll have to double check if I'm restoring anything else other than just the config file, and maybe it comes from there.

**Comment by githubsaturn** [comment]
> Where is the constraint stored? 

Docker swarm stores it, CapRover doesn't store it at all.

**Comment by drmrbrewer** [comment]
Hmm.  OK.  BTW what I'm back up (and restoring) is via: `tar --exclude='/captain/generated' --exclude='/captain/temp' --exclude='/captain/data/registry/docker/registry/v2' --exclude='/captain/data/letencrypt/etc/csr/*' --exclude='/captain/data/letencrypt/etc/keys/*'`

**Comment by drmrbrewer** [comment]
Having refreshed my memory about the backup/restore, I really can't see what might be causing this on my side... I really am just installing caprover as per [your guide](https://caprover.com/docs/get-started.html) and then scaling to 0, tweaking the config, and scaling back to 1.  That's it.

**Comment by drmrbrewer** [comment]
What is the best way to correct things now, to add the placement constraint for the current setup?

**Comment by githubsaturn** [comment]
> I really can't see what might be causing this on my side

I agree, there is no reason for the constraint ID to disappear. Can you try reproducing this to see at what stage the constraint ID gets dropped?
* Install Caprover using the official guide => check to see constraint ID is there
* Scale captain-captain to 0 => check to see constraint ID is there
* Run backup script => check to see constraint ID is there
* Scale captain-captain to 1 => check to see constraint ID is there

> What is the best way to correct things now, to add the placement constraint for the current setup?

Yes, just simply add the node is constraint to the service and you'll be good to go. `docker service update --constraint-add ... `

**Comment by drmrbrewer** [comment]
> Can you try reproducing this

OK I'll see what I can do.  I should note that I have also implemented auto-scaling, so that if server load gets too high then I spin up another, and scale up some services too (based on code from caprover), but I don't knowingly change any constraints associated with captain itself.  Perhaps something strange is happening in there (but it hasn't in the past).  I'll check it out.

> simply add the node is constraint to the service

The following seems to have done the trick:

    # docker service update --constraint-add "node.id == pw0nvuuhametbbh8so9c8cjes" captain-captain

**Comment by drmrbrewer** [comment]
As expected, I can't recreate this by spinning up a new server, installing caprover, and performing each of the steps as you suggest... after each step the placement constraint remains.  I suppose it's possible that something went wrong during one of the scale up/down operations to add/remove servers, leaving the captain service with an empty placement constraint.

Even if so, is it possible for captain to be self-healing in some way, to add back the placement constraint, e.g. when it is restarted?

**Comment by githubsaturn** [comment]
Self healing in this case could be dangerous. That's why the node is locked down during installation.

Just scaling up and down won't impact docker service configs. The only possible scenario is that captain-captain service was either manually created through `docker service create` or manually modified through  `docker service update`.... or [in thoery] some black docker swarm magic when the original node disappears from the Swarm...

**Comment by drmrbrewer** [comment]
OK I need to look carefully through my code for scaling services up/down because I am pretty sure now that this must be where the placement constraint on captain is lost.  I have based my code on [this](https://github.com/caprover/caprover/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js) including a cut-down version of `updateService()` but as mentioned before I can't imagine why I would be touching captain with this.  Will dig into it.

**Comment by githubsaturn** [comment]
This is the important part in that method that ensures all old configs are by default included in the new config:
https://github.com/caprover/caprover/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1072-L1076

Also this bit is the part that takes care of constraints:
https://github.com/caprover/caprover/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1084-L1096

**Comment by drmrbrewer** [comment]
OK of course it was my own stupid bug 🤦‍♂️.  I am calling `updateService()` to do the scaling of `captain` from `1` to `0` and then back to `1`.  I am also calling `updateService()` to do the scaling of my normal services (apps)... as well as trying to be clever about using placement constraints for those services to move load off the manager node if a worker node is available.  As part of that "clever" bit (for which, read "not so clever" instead) I was managing to set the placement constraint of `captain` to `[]`... d'oh!

**Comment by githubsaturn** [comment]
Glad it's sorted out now!

**Comment by drmrbrewer** [comment]
Having sorted out the placement constraint issue, I'm now seeing the following strange warning on restarting captain:

![image](https://user-images.githubusercontent.com/9009792/142934587-8d3c4c7e-2d1e-406d-ab97-dcc68de4e936.png)

It does quickly sort itself out and continue with the process.  But why the (truncated) warning?

	# docker service inspect captain-captain --pretty                                                                        

	ID:             ltp31w98swytmzkvi3g4ghfby
	Name:           captain-captain
	Service Mode:   Replicated
	 Replicas:      1
	UpdateStatus:
	 State:         completed
	 Started:       About a minute ago
	 Completed:     55 seconds ago
	 Message:       update completed
	Placement:
	 Constraints:   [node.id == pw0nvuuhametbbh8so9c8cjes]
	UpdateConfig:
	 Parallelism:   1
	 On failure:    pause
	 Monitoring Period: 5s
	 Max failure ratio: 0
	 Update order:      stop-first
	RollbackConfig:
	 Parallelism:   1
	 On failure:    pause
	 Monitoring Period: 5s
	 Max failure ratio: 0
	 Rollback order:    stop-first
	ContainerSpec:
	 Image:         caprover/caprover:1.10.1
	 Env:           IS_CAPTAIN_INSTANCE=1 
	Mounts:
	 Target:        /captain
	  Source:       /captain
	  ReadOnly:     false
	  Type:         bind
	 Target:        /var/run/docker.sock
	  Source:       /var/run/docker.sock
	  ReadOnly:     false
	  Type:         bind
	Secrets:
	 Target:        captain-salt
	  Source:       captain-salt
	Log Driver:
	 Name:          json-file
	 LogOpts:
	  max-size:       512m

	Resources:
	Networks: captain-overlay-network 
	Endpoint Mode:  vip
	Ports:
	 PublishedPort = 3000
	  Protocol = tcp
	  TargetPort = 3000
	  PublishMode = host 

and:

	# docker node ls
	ID                            HOSTNAME     STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
	pw0nvuuhametbbh8so9c8cjes *   mercury-01   Ready     Active         Leader           20.10.10
	636wz4900yj2edcov3zn0rd77     mercury-02   Ready     Active                          20.10.11
	lvvq79ckvq5vuietqwefkybb4     mercury-03   Ready     Active                          20.10.11

**Comment by githubsaturn** [comment]
Not sure how you got yourself into that situation. But the fact that it goes away automatically suggests to me that it's a Docker caching issue of some sort. 

You may wanna first research on how to get the proper logs (what is `host-mo...`), then it'll give you a better idea on what's going on.

**Comment by drmrbrewer** [comment]
> You may wanna first research on how to get the proper logs (what is `host-mo...`),

Seems like a difficult question to answer... [no answers yet](https://stackoverflow.com/q/70083932/4070848).  Shouldn't be difficult to see non-truncated log messages in docker, surely?

**Comment by githubsaturn** [comment]
Try something like this: https://github.com/moby/moby/issues/25332#issuecomment-236957778

For docker update you may want to add `--detach` to unblock your terminal to be able to run `docker service ps captain-captain`

**Comment by drmrbrewer** [comment]
OK I see what you did there with `--detach` so that I can actually catch the message before it disappears... turns out the full message is `no suitable node (scheduling constraints not satisfied on 1 node; host-mode port already in use on 1 node)`:

	# docker inspect i423g9x2cjbz
	[
		{
			"ID": "i423g9x2cjbzauai8dc20ekvh",
			"Version": {
				"Index": 354118
			},
			"CreatedAt": "2021-11-26T20:45:52.989575358Z",
			"UpdatedAt": "2021-11-26T20:45:53.04445744Z",
			"Labels": {},
			"Spec": {
				"ContainerSpec": {
					"Image": "caprover/caprover:1.10.1",
					"Labels": {
						"randomLabelForceUpdate": "ef2e8d6d-09ef-4187-a455-d34d2b68f39a"
					},
					"Env": [
						"IS_CAPTAIN_INSTANCE=1"
					],
					"Mounts": [
						{
							"Type": "bind",
							"Source": "/captain",
							"Target": "/captain"
						},
						{
							"Type": "bind",
							"Source": "/var/run/docker.sock",
							"Target": "/var/run/docker.sock"
						}
					],
					"Secrets": [
						{
							"File": {
								"Name": "captain-salt",
								"UID": "0",
								"GID": "0",
								"Mode": 292
							},
							"SecretID": "mqek0xbnre0cax5y1odlnvpz4",
							"SecretName": "captain-salt"
						}
					],
					"Isolation": "default"
				},
				"Resources": {},
				"Placement": {
					"Constraints": [
						"node.id == saly236rp4c5yhue6v0od3hl0"
					]
				},
				"Networks": [
					{
						"Target": "4zolfjk39jwqy44mhvwe9jzrb"
					}
				],
				"LogDriver": {
					"Name": "json-file",
					"Options": {
						"max-size": "512m"
					}
				},
				"ForceUpdate": 3
			},
			"ServiceID": "ld3emarhvj8mvudbren3pakji",
			"Slot": 1,
			"Status": {
				"Timestamp": "2021-11-26T20:45:53.044369454Z",
				"State": "pending",
				"Message": "pending task scheduling",
				"Err": "no suitable node (scheduling constraints not satisfied on 1 node; host-mode port already in use on 1 node)",
				"PortStatus": {}
			},
			"DesiredState": "ready",
			"NetworksAttachments": [
				{
					"Network": {
						"ID": "4zolfjk39jwqy44mhvwe9jzrb",
						"Version": {
							"Index": 20
						},
						"CreatedAt": "2021-11-25T13:14:57.402705196Z",
						"UpdatedAt": "2021-11-25T13:14:57.404371418Z",
						"Spec": {
							"Name": "captain-overlay-network",
							"Labels": {},
							"DriverConfiguration": {
								"Name": "overlay"
							},
							"Attachable": true,
							"Scope": "swarm"
						},
						"DriverState": {
							"Name": "overlay",
							"Options": {
								"com.docker.network.driver.overlay.vxlanid_list": "4097"
							}
						},
						"IPAMOptions": {
							"Driver": {
								"Name": "default"
							},
							"Configs": [
								{
									"Subnet": "10.0.1.0/24",
									"Gateway": "10.0.1.1"
								}
							]
						}
					},
					"Addresses": [
						"10.0.1.173/24"
					]
				}
			]
		}
	]

Any ideas off-hand?  I couldn't see anything definitive from some googling.  BTW this server is a completely fresh installation of everything since the last time I saw the message... I was hoping that this would fix it, but it didn't... the message is still appearing.

Is there anything bad about calling the `DockerApi.updateService()` function to scale `captain-captain`, using an `instanceCount` of `0` or `1`... that part of the function is unchanged compared to your original.

**Comment by githubsaturn** [comment]
My guess is that Docker is not stopping the old instance before it schedules the new one even though you're using `stop-first`... 

As a workaround, you can scale the service to `0` instances, then update if needed, then scale it back to `1`

**Comment by drmrbrewer** [comment]
Sounds like a reasonable guess... so it's just (another) docker bug, then.  I can confirm that the following gives no error messages or warnings:

    # docker service scale captain-captain=0
    # docker service update captain-captain --force
    # docker service scale captain-captain=1
