### ISSUE TITLE
Nginx Timeout Configuration not working for App

### ISSUE THREAD

**Issue by sameerkumar18** [caprover/caprover#940]
**What is the problem?**
Hi, I'm unable to set the HTTP request timeout setting from the Nginx configuration
I'm running a single Flask, Python app, just one app
I've read the [docs](https://caprover.com/docs/nginx-customization.html#docsNav) and to my understanding - if I add the Nginx timeout attributes in the _Application Specific Config File_  from the Caprover App Dashboard - It should work, which isn't. 
After changing the configuration, the HTTP Request still gets a 1 mins timeout error. 
(PS: Nature of the request is such that it is expected to take not less than 2 mins, and all other requests that take a couple of seconds to respond are working totally fine)

Here's the Nginx Configuration for the App - 
![Screenshot 2020-12-15 at 9 12 32 PM](https://user-images.githubusercontent.com/15978864/102237075-438dd400-3f1a-11eb-96b5-7ea307e698c7.png)

**If applicable, content of `captain-definition` file:**
```
{
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
}
```

**Dockerfile**
```FROM python:3.6-slim
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app
RUN pip3 install -r requirements.txt
ADD . /app
EXPOSE 5000
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["sh", "entrypoint.sh"]
```

**Steps to reproduce the problem:**

Answers to the following questions where applicable:
- Ubuntu 18.04
- 1 GB

Please help me if I'm missing something

Thanks in Advance :)

**Comment by githubsaturn** [comment]
You are placing your time out in the "redirect" section. 

Move your timeout variables just above `client_max_body_size` towards the end of the config:

https://github.com/caprover/caprover/blob/320bb2b0aeed3ef5cfd05c38eef6f7ac98c1b88d/template/server-block-conf.ejs#L45-L57
