### ISSUE TITLE
getting 502 error on every build

### ISSUE THREAD

**Issue by bilicio** [caprover/caprover#941]
What is the problem?
Im trying to deploy app and im getting 502 error. i tried to get log from docker but the ssh stuck on command "docker service logs srv-captain--my-app --since 60m --follow" it wont show me anything. this same app i could deploy without errors on caprover version 1.8.0, im only getting errors on the new version 1.8.2.

If applicable, content of `captain-definition` file:
{
 "schemaVersion" :2 ,
 "templateId" :"node/12.14.1"
}

Steps to reproduce the problem:
ive made the caprover deploy
choose the server
i dont get any errors
and the page 502 shows up.

Answers to the following questions if applicable:
- Your OS and version?
- ubuntu 16.04
- docker 19.03.13-ce
- RAM?
- 1gb

how do i install old caprover versions? 
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover@1.8.0 work?

**Comment by joshh71390** [comment]
the problem is people put out broken software then spend so much time trying to give workarounds instead of just making the program good to bein with...

**Comment by maietta** [comment]
> 

To @bilicio,

I know this topic was closed, but someone else decided to give their opinion on this despite the issue having been closed. For others who may find this issue in search results, I'll explain the issue:

You're problem is at minimum, you did not correctly reference the docker iamge you wanted. You cannot use @ symbol here. The syntax requires you replace @ with a ":" as in "caprover/caprover:1.8.0".

To @joshh71390,

Please explain why you think the software is broken. I'm more than glad to get a better explanation than a blanket statement of your opinion but the opinion by itself is totally useless to solving issues.
