### ISSUE TITLE
[Deployment Issue] Server without public IP with correct port redirection gives 504 error

### ISSUE THREAD

**Issue by Ratatinator97** [caprover/caprover#949]
What is the problem?
When I try to deploy some one-click-apps, I have an 504 error during the Deployment of the specific app.
My host machine is behind a router and doesn't have a public IP as it is in a standard LAN. I have enabled port redirection on my router for ports : `ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;` . I launched caprover with the command : `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover` As I am in a LAN do I need to add an additional parameter as for [here](https://caprover.com/docs/run-locally.html) ?

Steps to reproduce the problem:

- Install caprover on a machine without public IP address
- Add port redirection
- Launch caprover with `docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover`
- Try to install Nextcloud for example

Answers to the following questions if applicable:
- Your OS and version: Fedora server (latest)
- RAM: 8GB

![504error_caprover](https://user-images.githubusercontent.com/45072484/102997853-501bb900-4526-11eb-9fda-e201bb0d8a4d.png)

**Comment by githubsaturn** [comment]
504 is a timeout error. I am guessing your internet connection is not too fast. 

To fix this particular error, first manually pull the image, then go ahead and deploy the image. That way CapRover uses the locally cached version and you won't have a timeout problem.

```
docker pull jupyter/datascience-notebook:9f9e5ca8fe5a
```
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/jupyter-lab.yml#L12
