### ISSUE TITLE
[Deployment Issue] Enabling Force HTTPS or Websocket support breaks the app with 502 error

### ISSUE THREAD

**Issue by entrptaher** [caprover/caprover#950]
Any app we deploy works fine right until we click the force https checkbox. The nginx logs reveals a bit more information about it,

```
 20#20: *27 srv-captain--team could not be resolved (3: Host not found)
```

There are 49 closed issues marked with 502 error in this repo and none mentions this behavior.

The `docker service ls` shows there is indeed this service and reachable from other apps (just not from caprover nginx)

```
root@caprover-ubuntu-s-1vcpu-1gb-nyc1-01:~# docker service ls
ID                  NAME                                MODE                REPLICAS            IMAGE                                                                              PORTS
uhubhysokt8a        captain-captain                     replicated          1/1                 caprover/caprover:1.8.2                                                            *:3000->3000/tcp
307ams1ijsxs        captain-certbot                     replicated          1/1                 caprover/certbot-sleeping:v1.6.0                                                   
zm0ep133i3u6        captain-nginx                       replicated          1/1                 nginx:1                                                                            
hhpkvefv4lzp        srv-captain--bar-foo-baz-postgres   replicated          1/1                 postgres@sha256:110d3325db02daa6e1541fdd37725fcbecb7d51411229d922562f208c51d35cc   
jdsgr0wjacim        srv-captain--best-postgres          replicated          1/1                 postgres@sha256:110d3325db02daa6e1541fdd37725fcbecb7d51411229d922562f208c51d35cc   
f1bwg6g45pdr        srv-captain--team                   replicated          1/1                 img-captain-team:1                                                                 
u7633hft3it0        srv-captain--team-postgres          replicated          1/1                 postgres@sha256:110d3325db02daa6e1541fdd37725fcbecb7d51411229d922562f208c51d35cc
```

**Comment by githubsaturn** [comment]
```
 20#20: *27 srv-captain--team could not be resolved (3: Host not found)
```
has nothing to do with forcing HTTPS - it's typically a sign of Docker network problem.

Do you have mutliple nodes or a single node? How are you reproducing the issue?

You can view the `demo-nodejs` app on the [demo instance](https://captain.server.demo.caprover.com) (password: **captain42**) that has both websocket and force HTTPS enabled and it seems to be working fine.

**Comment by entrptaher** [comment]
I'm just testing it out in a digitalocean server. The problem is appearing with a mattermost app (but I got same problem with few other apps as well).

I see this in the docker service ls right when I updated the force https.

```
Dec 23 19:03:46 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:46.060092739Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Dec 23 19:03:46 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:46.060628999Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Dec 23 19:03:46 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:46.060780816Z" level=error msg="pulling image failed" error="pull access denied for img-captain-team, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=kfnes3mujbogktufuua8gpn0p service.id=f1bwg6g45pdrvv8temnoow527 task.id=uc5d59idud26i7i1t4yblsbsd
Dec 23 19:03:46 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:46.144434028Z" level=warning msg="failed to deactivate service binding for container srv-captain--team.1.n0nt0dzu832b1flnzzezn6u1n" error="No such container: srv-captain--team.1.n0nt0dzu832b1flnzzezn6u1n" module=node/agent node.id=kfnes3mujbogktufuua8gpn0p
Dec 23 19:03:49 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:49.077664608Z" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 4e942cf277457d0fc8e65febd20d9fd0f075bfe2c918544a033a7cbf9e02d0eb i31w1kn1uy62vsb4sfdiy5i0k err:cannot delete entry endpoint_table with network id i31w1kn1uy62vsb4sfdiy5i0k and key 4e942cf277457d0fc8e65febd20d9fd0f075bfe2c918544a033a7cbf9e02d0eb does not exist or is already being deleted"
Dec 23 19:03:49 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:49.077703276Z" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster srv-captain--team 4e942cf277457d0fc8e65febd20d9fd0f075bfe2c918544a033a7cbf9e02d0eb aborted c.serviceBindings[skey] !ok"
Dec 23 19:03:49 caprover-ubuntu-s-1vcpu-1gb-nyc1-01 dockerd[913]: time="2020-12-23T19:03:49.078571365Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

And the image actually exists,
```
root@caprover-ubuntu-s-1vcpu-1gb-nyc1-01:/captain/generated/nginx/conf.d# docker image ls | grep img-captain-team
img-captain-team                     1                   45f4772c0a52        3 hours ago         390MB
img-captain-team                     latest              45f4772c0a52        3 hours ago         390MB
img-captain-team                     0                   895d05795b96        6 weeks ago         21.8MB
img-captain-team-postgres            0                   895d05795b96        6 weeks ago         21.8MB
img-captain-team-postgres            latest              895d05795b96        6 weeks ago         21.8MB
```

Let me find the service details,
```
➜  docker service ls | grep team
f1bwg6g45pdr        srv-captain--team                   replicated          0/1                 img-captain-team:1                                                                 
u7633hft3it0        srv-captain--team-postgres          replicated          1/1                 postgres@sha256:110d3325db02daa6e1541fdd37725fcbecb7d51411229d922562f208c51d35cc
```

If I manually try to restart it (scale it), this is shown in stuck mode,
```
➜  ~ docker service scale srv-captain--team=1
srv-captain--team scaled to 1
overall progress: 0 out of 1 tasks 
1/1: starting  [============================================>      ]
```

**Comment by githubsaturn** [comment]
> Do you have mutliple nodes or a single node? How are you reproducing the issue?

**Comment by entrptaher** [comment]
It's a single node. 

This is exactly like the issue https://github.com/caprover/caprover/issues/783, and the error does not go away even if I turn the HTTPS off after that.

**Comment by githubsaturn** [comment]
Please try this:
- Create a new app from scratch
- Go to deployment tab and from " Method 6: Deploy via ImageName" deploy a test image: `nginx:alpine`
- Wait until it's deployed
- Make sure you can load it in the browser
- Enable HTTPS
- Make sure you can load it in the browser
- Force HTTPS and websocket
- Make sure you can load it in the browser (make sure you refresh the page so that you are not getting any cached results)
- Add some random env vars to your app (from the App Config tab) and Update & Save
- Make sure you can load it in the browser 

Does at any point the app fails to load?

**Comment by entrptaher** [comment]
There were two errors.

One was produced by adding cloudflare. I had the domain proxied and letsencrypt from caprover were trying to generate certificate. To avoid that, I had to,

1. Disable proxy in cloudflare
2. Enable HTTPS and Force HTTPS in caprover
3. Enable proxy in cloudflare

The second error is pretty much dumb. I saw the [mattermost application in caprover](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/mattermost.yml#L44) is doing this in the image, which waits almost 5 minutes before marking the service as healthy (thus it's stuck in ...starting for almost 5 minutes every time it's restarted).

```
HEALTHCHECK &{["CMD-SHELL" "curl -f http://localhost:8065/api/v4/system/ping || exit 1"] "5m0s" "3s" "0s" '\x00'} 
```

The latest image in [mattermost dockerhub](https://hub.docker.com/layers/mattermost/mattermost-team-edition/master/images/sha256-aa572e8c51bbe845fc78bf5a23a798d979c06306e611d7f309b2450bf9ad1b1e?context=explore) says 30s,
```
 HEALTHCHECK &{["CMD-SHELL" "curl -f http://localhost:8065/api/v4/system/ping || exit 1"] "30s" "10s" '\x00'}
```

The interval were changed later on commit https://github.com/mattermost/mattermost-server/commit/853e955b62bc7cf7827ae324a7e8c03e3bb71216 many months ago.

**Comment by githubsaturn** [comment]
@entrptaher  - are you saying `mattermost` one click app has problems and we have to remote it from the list?

**Comment by entrptaher** [comment]
I am saying we just need to update the caprover application list with newest docker tags.

**Comment by githubsaturn** [comment]
One click apps are community maintained. Feel free to modify, test and create a pull request.
