### ISSUE TITLE
Global Time Zone Setting

### ISSUE THREAD

**Issue by brmo** [caprover/caprover#952]
**Is your feature request related to a problem? Please describe.**
A option to globally set your timezone.

**Describe the solution you'd like**
Have a global setting to set your timezone, so that you are not updating it every time on every new app you install.

**Describe alternatives you've considered**
I don't see one.

**Comment by githubsaturn** [comment]
Are you setting up timezone in Dockerfile?

**Comment by brmo** [comment]
It is set up on the host. But when you deploy a new app from the one-click-apps for instance, some of them ask for a timezone. There is always a default there, like Europe/Brussels if I recall correctly.

In my opinion, on the Settings page, there should be a form field there to set a global timezone there that would auto-inject that default into the one-click-apps form field box.

**Comment by githubsaturn** [comment]
I see. You're referring to timezone which is available in some of the one click apps, like [this one](https://github.com/caprover/one-click-apps/blob/2c748879a887c220a1a0c8d79ad19dbf24324dbc/public/v4/apps/dokuwiki.yml#L28-L32).

Unfortunately, there is no standard way of setting timezone in one click apps. It is vendor specific. Each one click app maintainer uses a different env var for timezone.

**Comment by brmo** [comment]
I'm my opinion not necessarily. CapRover should use the default value as what is defined for the default. But if a setting is made where I select my time zone, it should simply fill in the value on the one click app installation form. I am not talking about the docker files or the templates, but rather the webpage where you are deploying a app.

**Comment by brmo** [comment]
For example, screenshot attached. The setting on the setting page would just override the text in the timezone box. That's it. 
![Screenshot_20201230-223122806](https://user-images.githubusercontent.com/1124581/103397842-f2bbd500-4aee-11eb-885f-f4dc905c4dab.jpg)

**Comment by githubsaturn** [comment]
I totally understand what the proposed solution is. But I am saying is that there is no common way for the one click apps to understand this is a timezone and it can be inferred. Time zones come in many forms and they are just yet-another environmental variable when setting up a one click app. Unless you have a solution that I am aware of?
