### ISSUE TITLE
[Question] Correct Cloudflare SSL Mode? (handshake failure)

### ISSUE THREAD

**Issue by creepinson** [caprover/caprover#953]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:

I keep getting the following after it says enabling ssl...
```
Error: RequestError: Error: write EPROTO 140242471868288:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 40
```

I've tried cloudflare's Full, Off and Flexible modes and neither of them work. Not sure what to do here.. I also had to manually assign each app including captain itself a cname record because cloudflare proxying doesn't work with *.app.example.com urls, only *.example.com. I have to use cloudflare proxying or else it won't resolve my domain inside my local network (it works on cell service for example)

**Comment by creepinson** [comment]
I saw other issues but I tried using every possible cloudflare mode they have used and none of them work for me. Not sure what the problem is or what this error means.

**Comment by creepinson** [comment]
![image](https://user-images.githubusercontent.com/11761863/103341094-b9c22880-4a3a-11eb-9028-0d1519b3224d.png)
Found this on their forums, this is definitely not a solution to pay $10/month just for this to work on one domain.

**Comment by creepinson** [comment]
Wow, so it kept saying incorrect password without SSL setup and the default password worked fine and I got in... Guess I'll just have to go without ssl for now and forward it somehow until I can find another solution.

**Comment by githubsaturn** [comment]
Using Cloudflare as a routing layer can conflict with the Let's Encrypt instance on CapRover. Hence, I'd recommend just simply use Cloudflare as the DNS provider, not as a router and leave the SSL functionality to be done by CapRover.
