### ISSUE TITLE
MySQL and MongoDB instances run by do-agent user on main server?

### ISSUE THREAD

**Issue by Jaimer** [caprover/caprover#955]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

> I was tracking the memory consumption on my CapRover installation and noticed an mysqld process on the top run by the do-agent user. Also found an mongod process also run by the same user. I killed the mysqld and mongod process but both restarted
>
> There is a third process i assume is the legitimate do-agent process.
>
>I have not installed MySQL or MongoDB on the main server, I also checked the list of installed packages and there is no DB installed.
>I've checked DO's forums and only found a similar issue from 2 years ago with no resolution. ([link](https://www.digitalocean.com/community/questions/do-agent-eats-ram))

```
 4199 do-agent  20   0 1116040 220416  19688 S  0.0 10.8   0:01.16 mysqld
 4459 do-agent  20   0 1581076  99876  29964 S  0.7  4.9   0:03.82 mongod
 8617 do-agent  20   0 1092028  12572   4284 S  0.0  0.6   0:48.05 do-agent
```

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

> Install CapRover from Digital Ocean Marketplace
> Enable Monitoring for the droplet.
> Top

Answers to the following questions where applicable:
- Your OS and version?
- RAM?

> CapRover image from DO marketplace
> Ubuntu 18.04
> 2GB RAM

**Comment by githubsaturn** [comment]
Why is this being reported here? Is this related to CapRover?

**Comment by githubsaturn** [comment]
Looking at DigitalOcean forum, looks like this is a process enabled by DigitalOcean and is not related to CapRover:
https://www.digitalocean.com/community/questions/do-agent-eats-ram

**Comment by Jaimer** [comment]
Sorry, i was investigating some memory issues.

Just for anyone who looks into this the commands show in top are reference to the containers i have online, as i'm a newbie in docker i didn't know this.

The do-agent user, i think is some strange thing happening with the Digital Ocean image.
