### ISSUE TITLE
[Question] Photoprism first login

### ISSUE THREAD

**Issue by crush4** [caprover/caprover#959]
Hello,

I'm trying to install photoprism with the one click installer. After installation it tells me the default admin password is "photoprism". I installed different versions of the app but I'm not able to login with this password. I'm very new to docker and I don't know what I'm doing wrong...

**Comment by githubsaturn** [comment]
One click apps are community maintained. Feel free to ask your question from the contributor who added photoprism:
https://github.com/caprover/one-click-apps/pull/164

Also, you can ask your question in photoprism github page: https://github.com/photoprism/photoprism

CapRover's one click app is just a wrapper for their official docker image: https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/photoprism.yml

**Comment by vohzd** [comment]
Hello @crush4 - You mention you installed a different version of the app from `20200427` which I've justed tested (password is OK).

Please could you let me know which one? I'll give it a test on my CR instance too.

**Comment by crush4** [comment]
Hello @vohzd - With the version 20200427 the password is working but there are missing account settings. I cannot change the default password or create new users etc. So I installed several versions (starting with latest) but none with working default password.

best regards
