### ISSUE TITLE
Cant install Organizr - FPM true/false - error "Invalid value. Does not match Regex:/^(true | false)/"

### ISSUE THREAD

**Issue by PiotrEsse** [caprover/caprover#961]
![2021-01-09 19_52_32-CapRover _ Server Dashboard — Mozilla Firefox](https://user-images.githubusercontent.com/42764623/104106254-bb9ab000-52b4-11eb-9f43-acb74f293e56.png)

What is the problem?

Cant install Organizr. I am getting error: 

Set FPM to True or False:
"Invalid value. Does not match Regex:/^(true | false)/"

Steps to reproduce the problem:
just try to install app

Answers to the following questions where applicable:
- KVM server
- Your OS and version: Ubuntu 18.04
- RAM - 4GB

**Comment by githubsaturn** [comment]
Thanks for reporting! It's now fixed [here](https://github.com/caprover/one-click-apps/commit/957061d4cbe066cd4c743ecc661e768409bac279)

You may still have the cached version. So either wait a few hours and retry. Or if you don't want to wait:
- Click on One Click App
- Type "Template" and click on it
- Copy and paste the content of [this template ](https://raw.githubusercontent.com/caprover/one-click-apps/master/public/v4/apps/organizr.yml)

**Comment by PiotrEsse** [comment]
WOW, amazing. Thank You cpt FLASH ;-D
