### ISSUE TITLE
Why deploy Strapi from local machine? [Question]

### ISSUE THREAD

**Issue by zuktagencia** [caprover/caprover#962]
I need deploy a version Strapi from my local machine on Caprover. But i don't know how the schema script should be.

**Comment by githubsaturn** [comment]
This is a Strapi question, not specific to CapRover.

One click apps in general are maintained by the community. In case of Strapi, the one click app is simply a [container that runs Strapi](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/strapi.yml#L3-L31). Read Strapi documentations for the schema and ask this question in their forums or [github issues](https://github.com/strapi/strapi/issues).
