### ISSUE TITLE
Server setup, error getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by TheMole3** [caprover/caprover#967]
When I install caprover with the install script on my Ubuntu 20.0.4 Server and try to setup the server with the cli I get an error after typing in my email for the ssl
`Error: RequestError: Error: getaddrinfo ENOTFOUND captain.bar.mydomain.tdl`

**Comment by githubsaturn** [comment]
Do you see `Enabling SSL... Takes a few seconds...` ? Can you please post the entire log? 

The error is self explanatory. Your local machine fails to resolve `captain.bar.mydomain.tdl`. It may be a temporary DNS issue or such. The reason that I am asking for the entire logs is that it should fail before enabled HTTPS if that's the case.
