### ISSUE TITLE
[Deployment Issue] Can't reach remote host on port 25 from container

### ISSUE THREAD

**Issue by BetaHuhn** [caprover/caprover#968]
Hey, I setup Caprover today on a second server and ran into a problem.

One of my containers needs to connect to a remote machine on port 25. On my first Caprover installation this works fine, but on the second one I setup today it doesn't work.

I tried to connect to the host via telnet inside the container:

```
telnet xx.xx.xx.xx 25
```

and I immediately got the error `telnet: Unable to connect to remote host: Connection refused`. After some tinkering I got to the point where it at least tried to connect and didn't fail instantly, but then after a while it timed out.

Other ports like 80 work, and the command above works fine if I run it directly on the host instead of from the container.

To my understanding simple port forwarding from the host to the container is not the problem as I am online trying to connect to a specific port on the remote machine, right? I have port 25 open in my firewall. My guess is that I need to open the port in the overlay network somehow?

I am sorry if this doesn't belong here, but I've been sitting at it for hours and couldn't find any solutions. I am new to Docker and don't have much experience with something like this. As this works on my first server, but not on the second I believe it has something to do with Caprover. The first server was a fresh installation via the DigitalOcean one-click app, whereas on the second server I installed Caprover after I had previously used the server for other things. Maybe something got messed up during or after the installation.

Thanks!

**Comment by BetaHuhn** [comment]
I just tried to add a simple Node.js app which connects to MongoDB Atlas Database and it could not connect to the db. 

How can I verify if the overlay network is still working correct? Do I have to reinstall everything?

**Comment by githubsaturn** [comment]
I am not sure if I understand correctly.
- Are you trying to connect from a container to some other (non CapRover) remote machine like a hosted database somewhere?
- Or are you trying to connect to a container (CapRover managed) from another machine?

**Comment by BetaHuhn** [comment]
I am trying to connect from a container to some other (non CapRover) remote machine. It works on one of my Caprover installations, but not on the other one. 

I can connect on port 80, but not on port 25.

**Comment by githubsaturn** [comment]
CapRover doesn't impose any outgoing connection restrictions. It's likely that you have an outgoining restriction rule in your firewalls.

SSH to your server and:
1- Run `telnet <ip> 25`  Can you connect?
2- Shell into your container, then run  `telnet <ip> 25`  from inside the container. Does this work?

To shell into your container: https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container

**Comment by githubsaturn** [comment]
If you have `ufw`, you can check your firewall rules by running `ufw status`

**Comment by BetaHuhn** [comment]
I did all of that already.

On the host `telnet <ip> 25` connects, inside the container `telnet <ip> 25` times out.

`ufw status` returns:

```
22/tcp                     LIMIT       Anywhere                  
2375/tcp                   ALLOW       Anywhere                  
2376/tcp                   ALLOW       Anywhere                  
51820/udp                  ALLOW       Anywhere                  
80,443,996,2377,3000,4789,7946/tcp ALLOW       Anywhere                  
2377,4789,7946/udp         ALLOW       Anywhere                  
25                         ALLOW       Anywhere                  
2377,4789,7946/tcp         ALLOW       Anywhere                  
22/tcp (v6)                LIMIT       Anywhere (v6)             
2375/tcp (v6)              ALLOW       Anywhere (v6)             
2376/tcp (v6)              ALLOW       Anywhere (v6)             
51820/udp (v6)             ALLOW       Anywhere (v6)             
80,443,996,2377,3000,4789,7946/tcp (v6) ALLOW       Anywhere (v6)             
2377,4789,7946/udp (v6)    ALLOW       Anywhere (v6)             

53,113,123/udp             ALLOW OUT   Anywhere                  
25                         ALLOW OUT   Anywhere                  
27015:27017/tcp            ALLOW OUT   Anywhere                  
25 (v6)                    ALLOW OUT   Anywhere (v6)             
27015:27017/tcp (v6)       ALLOW OUT   Anywhere (v6) 
```

**Comment by githubsaturn** [comment]
Try this: disable ufw completely and see if resolves the issue.

If not, this looks like a Docker networking issue, file an issue on [Docker's Github issues](https://github.com/moby/moby/issues). Make sure to copy the output to `docker network inspect captain-overlay-network`

**Comment by BetaHuhn** [comment]
I already tried to disable ufw and it still doesn't work.

I will file an issue over at [Moby](https://github.com/moby/moby/issues). 

Thank you for your help anyway!
