### ISSUE TITLE
[Question] Downloading a generated SSL certificate and key

### ISSUE THREAD

**Issue by henriquelalves** [caprover/caprover#971]
I currently have a Game Server running as a CapRover application, and I need to set it up as a secure WebSocket (wss://). I setup the CapRover Application to use HTTPS and enabled WebSockets, but I need CapRover's generated App certificate so I can use it in the Game Server application setup (when I deploy the server, it only runs a linux executable in a Docker image - the executable itself needs the .crt and .key files to enable WSS connections, and I believe they must be the same as the Web App). Is there a way to download the certificate and key of my CapRover app? I believe I found the generated .pem files in `/captain/data/letencrypt/etc`, but they are hashed and I don't know which of them corresponds to the one App I want.

**Comment by henriquelalves** [comment]
Just adding to the context of the problem, I could connect clients with this Game Server no problem when using normal WebSocket connections (ws://); but I'm having problems migrating the browser client to Itch.io, as it does not allow connections without certificates.

**Comment by githubsaturn** [comment]
CapRover uses certbot under the hood: https://certbot.eff.org/docs/using.html#

The certs are in `/captain/data/letencrypt/etc/live/your.domain.com/*`. But the `/live` directory content is soft linked to `/archive` directory. Make sure you map the entire `/captain` directory to `/captain` directory in your app if you want to use the same soft links.

Here is an example:
```
root@caprover:/captain/data/letencrypt/etc/live/captain.demo.domain.com# ls -la
total 20
drwxr-xr-x 2 root root 4096 Dec  15 21:16 ./
drwx------ 6 root root 4096 Jul  8  2020 ../
-rw-r--r-- 1 root root  692 Feb 19  2019 README
lrwxrwxrwx 1 root root   57 Dec  7 23:16 cert.pem -> ../../archive/captain.demo.domain.com/cert11.pem
lrwxrwxrwx 1 root root   58 Dec  7 23:16 chain.pem -> ../../archive/captain.demo.domain.com/chain11.pem
lrwxrwxrwx 1 root root   62 Dec  7 23:16 fullchain.pem -> ../../archive/captain.demo.domain.com/fullchain11.pem
lrwxrwxrwx 1 root root   60 Dec  7 23:16 privkey.pem -> ../../archive/captain.demo.domain.com/privkey11.pem
```

**Comment by henriquelalves** [comment]
Just a heads-up for anyone looking for this, I extracted the .crt and .key files from the corresponding .pem files in the webapp directory, and after setting up the Game Server with them, I was successfully able to connect clients with "wss://", and the Itch.io browser client is now working.

**Comment by githubsaturn** [comment]
Be careful if you are extracting the certs. They have limited life time. Let'sEncrypt certs expire 3 months after creation. CapRover automatically renews the certs for you, but if you have making a separate copy, those won't get updated.
