### ISSUE TITLE
[Question] Recommended Architecture/Configuration

### ISSUE THREAD

**Issue by Tam2** [caprover/caprover#972]
I currently host around ~100 client node.js applications on a single host, looking to move them over to caprover to make deployment easier to manage, i had a question around the best way to architecture/configure caprover servers

I will start off with a single caprover server to replace my existing one, when i need to deploy a second server to increase capacity would that be added as a slave to the primary via cluster or as a completely independent deployment? 

If as a cluster does caprover determine which node to deploy the application to automatically? But i assume all traffic would still need to be routed through the master caprover node nginx instance first?

**Comment by githubsaturn** [comment]
> If as a cluster does caprover determine which node to deploy the application to automatically? But i assume all traffic would still need to be routed through the master caprover node nginx instance first?

Your assumptions are all correct. All requests will go to the main node, then get routed to worker nodes. 
Also, it's not CapRover that manages the cluster, it's Docker swarm under the hood. CapRover just provides a nice interface for you to interact with it.

**Comment by Tam2** [comment]
Once you get to a certain size and have multiple nodes attached to the master what's the solution to handle the traffic as a single master may not be able to handle all traffic

> Are you able to have multiple masters and then use an external load balancer to send traffic between them?

**Comment by githubsaturn** [comment]
The traffic routing is very lightweight compared to actual NodeJS application. If you reach a point where your nginx server can't handle your traffic, it's the time to graduate from CapRover. Here is an example of [server sizing for nginx](https://www.nginx.com/resources/datasheets/nginx-plus-sizing-guide/). You can server 1 million requests per second on a 32core 8gb RAM machine.

![image](https://user-images.githubusercontent.com/10582082/104660918-7ea83200-5695-11eb-83f6-046bee6fbabc.png)

**Comment by nfodor** [comment]
But, still a lot, even way less, in TPS, once served over SSL which is a common use case: 48k TPS
