### ISSUE TITLE
Reconfiguring cloned instance

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#973]
Hi,

I've spun up a clone of an existing / working set up and sorted out my A records.

I'm unable to access the captain.<dns> at this stage, due to the cloned instance thinking its the original and DNS pointing to its new IP.

As I recall, you initially configure the caprover instance via port 3000, but once dns is sorted, that's disabled?

I don't want to destroy or effect any of the caprover apps, just make it accessible in the same way the 'main' is.

Any tips on how to proceed?

Thanks

Neil

**Comment by skiv71** [comment]
It appears, that with cloned instance up (#2), it takes down my (#1), so I've had to poweroff this VM instance until I can resolve / edit / reconfigure...

**Comment by githubsaturn** [comment]
When you say "clone" are you talking about a cloned disk, or a backed up instance using CapRover's [built in backup](https://caprover.com/docs/backup-and-restore.html)?

**Comment by skiv71** [comment]
No, I created a duplicate VPS (DO droplet) via snapshot.

I've assigned new public DNS (for the new public IP), so that this new host (testing) is gonna be do2.<domain>.<tld>.

But, the newly cloned instance still thinks its the primary (original) and so needs its public DNS etc. updating.

I do recall seeing a caprover specific instance / folder somewhere... hoping I can amend a config somewhere, if only to revert actual public dns config, (i.e. expose 3000) so I can redo it.

**Comment by githubsaturn** [comment]
This is not a supported behavior. But there are a few things you can do. It might work
```
docker service scale captain-captain=0

# Remove force SSL and remove has SSL, manually change the root domain
nano /captain/data/config-captain.json

docker service scale captain-captain=1
```

Now try to connect to your new domain in your browser http://captain.do2.....

**Comment by skiv71** [comment]
Yes, I saw that it wasn't supported, but due to the complexities of the caprover apps, it seemed like the lesser task.

I was able to get it working... I editied the /captain/config-xxxx.json file, to disable all SSL (captain) and disabled all web access on affected apps.

I then restarted, cleaned out letsencrypt, and reconfigured from the regular captain.* admin page... then re-enabled.

All appears well.

Just need to figure out pushing the git forks to the different server... (and flip between).

**Comment by skiv71** [comment]
Just a question, with regard to destination server... i see the cli is the way to go... but assuming different forks, going to different servers... and the presence of server designation in a committed config file... would this be a good suggestion (assuming I've missed its actual implementation)?

**Comment by githubsaturn** [comment]
What git forks? Do you mean you have separate repositories and you want to deploy them to different servers? Why is that an issue?

**Comment by skiv71** [comment]
Sorry, I'm probably not explaining myself properly.

I want to deploy 'master' to the existing, and deploy the 'test' branch to the new do2 server.

I see caprover supports server url in the deploy, which i currently do via an npm run deploy script command, so I thought I could use that direct each branch to their respective server.

Or, am I making a mountain out of a mole hill?

**Comment by githubsaturn** [comment]
Okay so you want to deploy different branches (not forks) to different servers.

Yes, you can do that using `--caproverName` or `--caproverUrl`. For example:
```
caprover deploy --default --branch master --caproverName mydo1
# and 
caprover deploy --default --branch test --caproverName mydo2
```

**Comment by skiv71** [comment]
Hi, I'm embarrassed to say the migration hasn't worked correctly, at least for publicly served containers.

Seems the certbot container is not accessible by captain-captain...

Retrying to get containerId for captain-certbot retry count:1

I've tried to recover / fix via the guidance here...  

https://caprover.com/docs/troubleshooting.html#cannot-verify-domain

but not I cannot access anything.

Previously, all was working apart from public apps, and i thought I could delete and recreated, but i got the 1107 verification error.

Must be an easier way to create a staging server from cloning a VM and reconfiguring dns... :(

**Comment by skiv71** [comment]
Do I need create a new / virgin caprover instance on this machine?

I have many apps, which would be a pain to re-create manually, especially those which are databases...

**Comment by githubsaturn** [comment]
```
Retrying to get containerId for captain-certbot retry count:1
```
Retrying is a normal behavior. Your logs should be something like:
```
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:11.673 pm    Captain Certbot is already running.. 
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:11.689 pm    Updating Certbot service...
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:15.035 pm    Retrying to get containerId for captain-certbot retry count:0
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:16.868 pm    Pruning containers...
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:18.057 pm    Retrying to get containerId for captain-certbot retry count:1
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:21.067 pm    Retrying to get containerId for captain-certbot retry count:2
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:24.075 pm    Retrying to get containerId for captain-certbot retry count:3
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:27.080 pm    Retrying to get containerId for captain-certbot retry count:4
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:30.086 pm    Retrying to get containerId for captain-certbot retry count:5
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:30.096 pm    executeCommand Container: captain-certbot certbot certificates --non-interactive 
captain-captain.1.wd2wx5t9b0yq@caprover-demo    | January 18th 2021, 4:08:31.487 pm    **** Captain is initialized and ready to serve you! ****
```

**Comment by skiv71** [comment]
I do have that, but eventually an error is thrown, a process / library with
modem.js referenced. At the moment, I'm having to use the staging server is
non SSL mode.

**Comment by skiv71** [comment]
So, I have this working in a non SSL fashion... What files can I clear etc. so revive SSL function? I need to reset all the letsencrypt

**Comment by skiv71** [comment]
Not sure what's happened, but yet again, this cloned instance has somehow interferred with the primary instance.

Getting to be a pain this...

Am I really gonna have to start from scratch in creation a cloned, staging server?

**Comment by skiv71** [comment]
I'm losing the will to live here... Please, someone help me clear ALL letsencrypt information / data... as it simply isn't working

**Comment by githubsaturn** [comment]
@skiv71 

* To create a staging environment, you can either start a new server from scratch. Or use the [built-in backup system](https://caprover.com/docs/backup-and-restore.html) (you have to copy the volume contents if you have a persistent app). The cloned image is not a supported behavior [as I said above](https://github.com/caprover/caprover/issues/973#issuecomment-760550625).


> clear ALL letsencrypt information / data

All let's encrypt data reside in `/captain/data/letencrypt` directory. You can remove this directory and restart your server. But again, this is not a supported behavior. You'd be in a much better shape if you follow the guidelines and standard procedures.

**Comment by githubsaturn** [comment]
If you need further hourly consultation for your specific needs, please feel free to contact contractors from this list: https://caprover.com/docs/support.html#need-hourly-consultation

**Comment by skiv71** [comment]
I've understood what you've said... but what I cannot wrap my head around is this.

Why, when the cloned instance reboots, does it take down the source instance?

**Comment by skiv71** [comment]
I've deleted LE, rebooted, restored http access, enabled https... and the primary site loads as "insecure"... and attempts to make any apps https, fail with nginx "nothing here".

**Comment by githubsaturn** [comment]
> Why, when the cloned instance reboots, does it take down the source instance?

The cloned server shouldn't take down the first server unless they are using the same domain name (at least at some point). And let's encrypt confuses which server is the "legit server". But it is just s guess, but it sounds like what you're experiencing. 

From the looks of it, you're better off just recreating everything from scratch. Or hire a contractor to sort this out for you. Or you can do some more readings on how [Let's Encrypt](https://certbot.eff.org/) work and try to troubleshoot it yourself.

**Comment by skiv71** [comment]
All DNS is correct... But at 'some' point (initial cloning) there was some overlap.

After removing LE and re-enabling, I appear to have sorted the issues... apart from google chrome insists the site's SSL is insecure, whereas FF reports all ok.

Not sure if chrome is caching

**Comment by githubsaturn** [comment]
You can use SSL Labs. It's much more reliable: https://www.ssllabs.com/ssltest
