### ISSUE TITLE
[Question] Is it possible to setup connection pooling for my PSQL server?

### ISSUE THREAD

**Issue by opensourcekam** [caprover/caprover#975]
I'm using prisma 2 and i'm noticing issues when more users connect to my app. Is it simple a matter of CPU or is there some type of special config i'd need to enable more concurrent connections?

**Comment by githubsaturn** [comment]
That'd be a prisma question. Please repost this question on Prisma's forums, e.g.: https://github.com/prisma/prisma

CapRover apps are simply just a Docker container for the applications. There is nothing specific to CapRover.
