### ISSUE TITLE
[Question] Configure IP-based restriction while still allowing certbot challenges

### ISSUE THREAD

**Issue by JosXa** [caprover/caprover#976]
I was wondering what would be a good way to restrict access to my instance by default, only allowing my own static IP address through. When simply blocking all incoming requests from unknown IPs in my VPS's firewall settings, certbot won't work (by design). As, to my knowledge, it is not possible to change the default app-specific nginx template to add an IP range, I was wondering if there's a hack I could do to allow the well-known endpoints through (to **every app**) while still blocking IPs at the nginx root level config..? Essentially path-based route filtering for wildcard domains?

I'm open for any other suggestions though, what I'd like to achieve is to improve the security of my system with tons of apps running without having to configure each and every one of them manually.

**Comment by githubsaturn** [comment]
> As, to my knowledge, it is not possible to change the default app-specific nginx template to add an IP range

Is this really not possible? I haven't tried it, but I believe you should be able to add IP range to `location` context. Hence you can only limit `location /` but leave `location /.well-known/acme-challenge/` untouched. So something like this:
```
....
.......
.........
  location / {
        allow  123.123.123.123/24;
        deny   all;
.........
.......
....
```

**Comment by JosXa** [comment]
The wording here explicitly meant #977, which I created some minutes later :)
And yep, I would have no issues whatsoever if it was easy or elegant for me to go through all the apps and add that configuration. Though then I'll also need to add it in captain dashboard and as soon as there's a change it's gonna be madness :D

The best thing I was hoping for would be "yo nginx, wouldya block all requests that ain't in `{my IPs}` and ain't going to `.well-known`"?

**Comment by githubsaturn** [comment]
Yes, unfortunately, you can't specify a location context in nginx outside of a server context. This means, you have to specify exclusion of `./well-known` for each app specifically. And yes, #977 would definitely be a huge help if you want to do this for all apps.

I am closing this in favor of #977 to consolidate the issues.

**Comment by JosXa** [comment]
Sounds good to me 👍
