### ISSUE TITLE
Ability to change app-specific nginx default template

### ISSUE THREAD

**Issue by JosXa** [caprover/caprover#977]
I would like to change some nginx options for ALL of my applications.

Reasons include:

- Needing to use the same certificate for every app (#887)
- Default IP checks per application (#976)
- Bulk configure nginx settings that depend on the name, settings, etc. of a specific app

With lots of apps (many kept archived/for future reference with 0 instances), it will be too tedious to change the nginx configuration of every single one. In addition, I find it ugly when the app overview greets me with a huge textarea of settings, where you can't know what's been changed and what's been left default and you have to read through the thing before you make any connectivity changes. Thus it would be awesome to just change the base somewhere in a persistent fashion.

My suggestion would be to add this as a third globally configurable file under Settings? Or is there already a better way to patch the base template?

**Comment by githubsaturn** [comment]
Good suggestion! This is definitely a missing piece. We probably won't port this to UI as it's not a very common use case, but rather, we'll make this available through some override files in `/captain/data` directory.

**Comment by JosXa** [comment]
@githubsaturn Could you give me a rough tl;dr of where to look to give this a shot myself? That would be my first contribution, but I think I'd be up for it :)

**Comment by githubsaturn** [comment]
It's super simple. Here is where the template gets loaded: https://github.com/caprover/caprover/blob/19626ce29d63283c3dddd42feffbe5d7272def03/src/datastore/DataStore.ts#L32-L35

All you need to do is to check if `/captain/data/server-block-conf-override.ejs` exists, load it. Otherwise, fallback to the default template. It's should be just a few lines. Just make sure you sue "sync" operations as it's not part of the promise chain.

**Comment by kaaax0815** [comment]
+1
When editing the /captain/generated it gets overridden by reboot.😥

**Comment by kaaax0815** [comment]
@githubsaturn @JosXa When will it get added as a Feature?

**Comment by githubsaturn** [comment]
It's not a top requested feature, so it's not a top priority. But I might find a simple solution that reduces the dev cost.

**Comment by kaaax0815** [comment]
Status after almost 2 months?

**Comment by Kilerd** [comment]
wondering what's the status of the issue?
