### ISSUE TITLE
Slow queries with postgresql

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#978]
Rather than using the postgresql one-click app, I am using the following Dockerfile to create postgresql instances:

	FROM postgres:13.1
	RUN apt-get update \
	 && apt-get install -y --no-install-recommends \
			curl \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*
	RUN mkdir /root/exe
	COPY ./exe /root/exe

All I am really doing is ensuring that `curl` is installed, which I use to back up the database on an ongoing basis.

But I'm finding some odd behaviour, with very slow queries (up to several seconds).  I have determined that these slow queries only happen when (a) there are two or more nodes in the swarm; and (b) the instance requesting data from the postgres database is on a worker node (i.e. not on the same node as the postgres instance).

The difference in query time is stark: several seconds in some cases (with db and app on different nodes) vs a few milliseconds (with db and app on same node).  This is the case even when the nodes are in the same datacentre!  And it makes no difference to query times if I put my worker nodes in a completely different datacentre to the main node, in a completely different country!  In fact, sometimes the query time _drops_!

I find this very surprising, but it is clear from the metrics... query time drops down instantly to near-zero when the number of nodes in the swarm drops down to 1, and then back up to several seconds when nodes goes up to 2.  I'm using New Relic to monitor these query times.  It seems that query time in this context includes the time take to get the data from the db node to the requesting node.  

Here is one example where the query time drops from 0.6s (which was lower than it had been earlier) to a few ms, just before 11:50pm, which is when the number of nodes in the swarm dropped from 2 to 1:

![SmartSelect_20210118-235942_Chrome](https://user-images.githubusercontent.com/9009792/105074749-b130a100-5a80-11eb-95db-d3bf38864b75.jpg)

Is there anything in the way I'm using CapRover to create postgres instances that could be causing this?  In my node-postgres query I am specifying the `host` as the service name `my-postgres-service` and it is routed to the right place:

    const { Pool } = require('pg');
    const pool = new Pool({ host: 'my-postgres-service', /* ... */ });
    const res = await pool.query(`SELECT * FROM mytable WHERE key=${lookupKey};`)

It almost seems like the requests sent to the postgres app are not being routed internally within the swarm, but routed outside the swarm like any external request, given that queries even between nodes on the same datacentre take so long.

Anything I can do to change load balancing or something?  Any hints welcome!

**Comment by githubsaturn** [comment]
> Is there anything in the way I'm using CapRover to create postgres instances that could be causing this? 

I don't see anything specific that alerts me. I am assuming `my-postgres-service` is actually `srv-captain--yourpostgs`, right? In that case, the request will have to route through the mesh overlay network. Several seconds is just way too much for a simple query.

You can create a github issue on [Docker's github page](https://github.com/moby/moby) ask on stackoverflow.

To help people understand the problem, attach outputs of these commands:
```
docker service inspect srv-captain-your-nodejs --pretty
docker service inspect srv-captain-your-postgres --pretty
docker network inspect captain-overlay-network
```

There are some stackoverflow/github questions that point the same issue. Note that it shouldn't be specific to Postgres.
- https://stackoverflow.com/questions/64193796/docker-swarm-http-requests-work-very-slow-on-overlay-network
- https://github.com/moby/moby/issues/36998

**Comment by drmrbrewer** [comment]
I posted an issue over on the moby github page with more info, but with 3.8k open issues I'm not holding out much hope.  Have done a lot more googling on this and still can't figure out what might be going on :(

**Comment by drmrbrewer** [comment]
@githubsaturn is it possible to customise the 'mtu' of the overlay network with CapRover?  I'm still getting hugely different performance for node-to-node communications compared to communications within the same node (see the issue I posted on the moby github repo), and I'm wondering if increasing 'mtu' might help.  See [here](https://github.com/moby/moby/issues/37855#issuecomment-561437543) and [here](https://github.com/moby/libnetwork/issues/1478#issuecomment-250403016).  I think this would also require increasing the max 'mtu' on the actual interface, because so far as I can tell they are all set to 1500, and that's where I might come unstuck too with my ambitions vs my abilities.

**Comment by githubsaturn** [comment]
1- Definitely prefer Ubuntu 18 over 20. There are a number of inefficiencies with Docker on Ubuntu 20. Plus Ubuntu 18 is fully supported until 2023.

2- Docker network doesn't allow your to "update" a network. But all CapRover services are bound to the network using its name. So it theory you may be able to do:
```
docker network rm captain-overlay-network

docker network create ...... captain-overlay-network ## modify as needed

Reboot your machine
```

**WARNING: this is untested and might break your cluster. Make sure you test this on a test cluster.**

**Comment by drmrbrewer** [comment]
> Definitely prefer Ubuntu 18 over 20

Correct again.  See my updated issue on moby.  In short, moving everything back to Ubuntu 18.04 has resulted in much better performance.  That was literally the only change.  Fingers crossed that they manage to fix things for Ubuntu 20.04 before too long.

**Comment by githubsaturn** [comment]
Good to hear that it is resolved. Yes, we have it also in the docs: https://caprover.com/docs/get-started.html#b2-server-specs

![image](https://user-images.githubusercontent.com/10582082/105788257-20f5ce80-5f4e-11eb-953e-570dfb404011.png)

**Comment by githubsaturn** [comment]
Closing as it's being tracked in Docker's project.
