### ISSUE TITLE
Mass 502 until reboot every few days

### ISSUE THREAD

**Issue by Saik0Shinigami** [caprover/caprover#979]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
Every few days the primary reverse proxy appears to fail throwing every app into 502. This specific instance of caprover has been running for about 6 months now. Start earlier this month, every 3-4 days the main reverse proxy appears to fail and 502 every app in the process, even though the apps appear to continue to work on their own (eg. teamspeak that doesn't present an http site, but instead it's own port will continue to function). Another oddity of it is that every http-based app will get the fancy blue 502 screen presented by caprover but the primary captain.domain.tld will be a plain white 502 screen. Rebooting resolves the issue temporarily, all services function after the respawning all the containers/processes until it inevitably dies again.

If applicable, content of `captain-definition` file:
N/A

Steps to reproduce the problem:
Just let it run for a few days. Usually around 3-4.

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 18.04.5 LTS
- RAM?
16 GB of Ram

**Comment by githubsaturn** [comment]
Somehow your `captain-captain` keeps getting restarted. We need more logs to investigate this. Please include output of 
```
docker service ls
docker service ps --no-trunc captain-captain
docker service logs captain-captain --tail=500
```

**Comment by Saik0Shinigami** [comment]
So I've piped all output into files in case you need the full files for all in case you need full output, but wary of posting it here publicly since it shows domains, services, containers, etc...

docker service ls:
Shows all my containers, system currently works as I just rebooted it this morning (literally just before originally posting) so I don't think this output is really useful for you. captain-captain is currently running

docker service ps --no-trunc captain-captain :
"task non-zero exit(255)" (3 times, 10 hours ago, 5 days ago, 9 days ago) 
and "No such container : captain-captain.1.twhzcxo <more gibberish matching the container itself hash>" (Just once 9 days ago)

docker service logs captain-captain --tail=500 : 
Only appears to contain logs from most recent startup, not prior container hash numbers. (eg. current hash is qy2cq.... No logs from when it was twhzcxo... exists in here or otherwise. No failure stats or anything obvious. Already attached, Finished, or "not needed" for basically everything. Does this log rotate? should I be looking somewhere for older logs?

Assuming time in the last command is in GMT, it lines up with the reboot of the whole system 10 hours ago. And currently works fine, but will probably fail again in a couple of days.

I guess next time it happens I'll try to capture the output of the last command for you before restarting the system. Unless if you know if there's rotated logs somewhere specific.

**Comment by Saik0Shinigami** [comment]
So just like clockwork... Just happened moments ago (maybe 10 minutes ago at most)... Services relying on ports 80 and 443 are all dead (not being reversed proxied, ports that are outright forwarded appear to still work, teamspeak for instance.

>So, next time it happens run docker service ls

![image](https://user-images.githubusercontent.com/37313164/105638176-80f55380-5e2e-11eb-989a-3a7588365686.png)
Appears to be running still.

>Also run sudo docker ps

![image](https://user-images.githubusercontent.com/37313164/105638203-a6825d00-5e2e-11eb-8205-d3d615dae56d.png)
4 days ago being last reboot.

Also ran all the commands from previous request... 
>docker service logs captain-captain --tail=500

Completely locks up. Nothing ever generates or shows.
But it's not a system lockup...
![image](https://user-images.githubusercontent.com/37313164/105638280-10026b80-5e2f-11eb-8ffa-172539e95ed4.png)

Also tried restarting the container or stopping it... giving each about 2 minutes to complete... once again it's unresponsive and never completes.
![image](https://user-images.githubusercontent.com/37313164/105638438-d4b46c80-5e2f-11eb-82be-15a671ad0830.png)


Starting to look/feel like maybe it's not a captain issue but something with docker itself that only affects certain containers?  I'm not sure exactly what's going on but it's only affecting the reverse proxy and docker itself isn't playing nice with retrieving information on the containers after it happens.

I know it's effectively the same as a restart, but a `sudo systemctl restart docker.socket docker.service` works to gain everything back to functional state. And now it will probably take another 3-4 days before I can probe any further.

Looks like docker service logs allows you to tail the file using `-f`.. I'll let that sit on the console and maybe catch that last few lines before it goes unresponsive next time.

**Comment by githubsaturn** [comment]
A few points:
1- 

If you want to restart a container, don't use `docker restart/stop`, instead use 
```
docker service update SERVICE_NAME --force
```
SERVICE_NAME can be `captain-captain` `captain-nginx` or `srv-captain--appname`


2-
It indeed looks like your Docker engine is being the issue here. 


3-
The issue is probably related to the overlay network. The containers that directly forward a port do not use the overlay network.


4-
To make sure you get the proper information when this happens again, also get the logs and state for nginx:
```
docker service ps --no-trunc captain-nginx
docker service logs captain-nginx --tail=500
```

If this doesn't show anything either, then it's surely your Docker engine being unhappy.
