### ISSUE TITLE
[Question] How do I access Caprover on the network?

### ISSUE THREAD

**Issue by obizbu** [caprover/caprover#981]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question:
Goal: Install Caprover on one machine on my network (running Ubuntu 20.04) (the SERVER), and have any other machine on the same network (CLIENT) access Caprover and the applications deployed using Caprover

Progress: Got Caprover installed, was able to access SERVERADDRESS:3000 to get to the admin interface. Was able to manually set the root domain to captain.localhost and was able to then login using the CLI putting the host as captain.captain.localhost (all as described in the docs). 
I also followed the instructions to update /etc/hosts, /etc/NetworkManager/dnsmasq.d/dnsmasq-localhost.conf and the directions listed on the attached Stack Exchange page. When I do nslookup captain.localhost or random.captain.localhost on the server, they all resolve to the same SERVERADDRESS

Problem: While I am still able to access the Caprover home page on the CLIENT, I can only access it by going to SERVERADDRESS:3000. I cannot access it via captain.SERVERADDRESS (gives a site cannot be reached error) or captain.captain.SERVERADDRESS. This isssue also occurs if I try to access any app (e.g. appname.captain.SERVERADDRESS or appname.SERVERADDRESS). So I have Caprover all set up and working, but just can't actually use it :). 
Note - I did try to update the root domain (using the Caprover UI in a browser on CLIENT) to captain.SERVERADDRESS, but that did not seem to solve the problem.

Thanks in advance for any help. Once I get this sorted out, I'd be happy to update the docs.

**Comment by githubsaturn** [comment]
What's the output of this command?
```bash
cat /captain/data/config-captain.json | grep customDomain
```

**Comment by obizbu** [comment]
> What's the output of this command?
> 
> ```shell
> cat /captain/data/config-captain.json | grep customDomain
> ```
```
USERNAME@SERVERNAME:/$ sudo cat /captain/data/config-captain.json | grep customDomain
	"customDomain": "captain.localhost"
```

**Comment by githubsaturn** [comment]
So the domain hasn't been updated. Now reading your comment again, I think your network looks like this, right?
```

                   +-------------------------+
                   |                         |
                   |        ROUTER           |
                   |                         |
           +--------------------------------------+
           |                    |                 |
           |                    |                 |
           |                    |                 |
    +------v------+      +------v------+   +------v------+
    |             |      |             |   |             |
    |  CapRover   |      |    Laptop1  |   |  Laptop2    |
    |  Server     |      |             |   |             |
    |             |      +-------------+   +-------------+
    |             |
    |             |
    |             |
    |             |
    |             |
    +-------------+
```

If that's the case, then you can't set the server DNS on the server and expect the laptops to understand the DNS. In this case, you have to add a local DNS record either on ALL of your machines (all laptops) or if you router has the functionality (not all routers do), you can set your DNS entry in your router.

Feel free to let me know if you need more details.

**Comment by githubsaturn** [comment]
Alternatively, if you are not sure how to do this, you can probably use `nip.io`.

Assuming your CapRover server is at `192.168.1.99`, go to your `http://192.168.1.99:3000` and update the domain to `192-168-1-99.nip.io`

**Comment by obizbu** [comment]
Yep - that's right on the network structure. But I am only trying to access from Laptop1 (not all devices on network). 

I've updated Laptop1's DNS settings to point to my server machine (which is running Caprover as well as dnsmasq). But I think there is an issue there that is preventing this from working. There is also a question that describes my situation exactly on Stack Exchange (https://serverfault.com/questions/1050625/setting-up-a-client-to-use-a-local-dns-server). 

nip.io seems promising, but I was hoping to do this with limited reliance on external services (seems like nip.io relies on PowerDNS).

**Comment by githubsaturn** [comment]
If you only need to access it from one machine, it should be simple and just updating the DNS setting on your local laptop should be enough. What do you see when you run this?
```
curl -v captain.captain.SERVERADDRESS
```

**Comment by obizbu** [comment]
Here's what I see:

```
LAPTOPID:~ USERNAME$ curl -v captain.captain.SERVERADDRESS
* Rebuilt URL to: captain.captain.SERVERADDRESS/
* Could not resolve host: captain.captain.SERVERADDRESS
* Closing connection 0
* ```

**Comment by githubsaturn** [comment]
> I've updated Laptop1's DNS settings to point to my server machine

Based on the curl that you updated above, it doesn't look like you've updated your DNS entry correctly on your laptop. Try adding this line to you `/etc/hosts` file:
```
192.168.xxx.xxx   captain.myserver.local
```

Replace `192.168.xxx.xxx` with your correct IP address for your server, then re-run:
```
curl -v captain.myserver.local
```
