### ISSUE TITLE
[Question] You have reached your pull rate limit

### ISSUE THREAD

**Issue by crush4** [caprover/caprover#984]
Hello,

I'm trying to install caprover on my VPS but I'm getting "reached pull rate limit error":

```
Captain Starting ...
Installing Captain Service ...

 Installation of CapRover is starting...
For troubleshooting, please see: https://caprover.com/docs/troubleshooting.html

 >>> Checking System Compatibility <<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 33730 MB
Pulling: nginx:1
Installation failed.
Error: (HTTP code 500) server error - toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:328:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  reason: 'server error',
  statusCode: 500,
  json: null
}
```

What can I do? I have an dockerhub pro account but don't know how to login for the install...

best regards

**Comment by githubsaturn** [comment]
You can't log in before installation is done, but you can log in after the installation, see details here: https://github.com/caprover/caprover/issues/906


For the installation you need to have at least some capacity to pull the base images (CapRover + nginx + certbot).

The limit is 100 pulls per six hours, so you just need to pull these base images, and once it's done, you can log in and use your credentials with CapRover.

For the base images, you can also try using a mirror. Run this:
```
echo '{"registry-mirrors": ["https://mirror.gcr.io"]}' | sudo tee /etc/docker/daemon.json

service docker restart # or reboot the VPS by running "reboot"
```

**Comment by maietta** [comment]
This is not a problem associated with Caprover but instead directly with Docker Hub where docker images are pulled from by default: See https://www.docker.com/increase-rate-limits.

If you are feeling a bit more adventurous, you can build your own images from official sources and host them on your own container registry. This is what I ended up having to do because even with a Pro account I was still hitting limits with no response from Docker after several days for a resolution.

**Comment by githubsaturn** [comment]
There are other issues where people talk about potential solutions:
https://github.com/caprover/caprover/issues/906
https://github.com/caprover/caprover/issues/956
https://github.com/caprover/caprover/issues/963
