### ISSUE TITLE
[Question] Nginx healthcheck failed 

### ISSUE THREAD

**Issue by OB3RG** [caprover/caprover#986]
I'm setting up CapRover on a VM inside a private openstack cloud to simplify deployments for our developers until we have the need to pay for a kubernetes cluster. 

Previously I've setup Caprover on Digitalocean without any problems and in my homelab server. 
The openstack network configuration is pretty simple with a private subnet and then the instances have floating ips to give them external access. 

I've had no problems running `caprover serversetup` command. 
I can access the GUI on the domain i setup. It's setup as a wildcard *.rover.DOMAIN dns record as per the documentation. 

The problem now is that caprover logs NGINX health check failed and when the retries are up it restarts the container basically making it unusable. 
I've tried disable any firewalls and security groups on the network, but still no dice. 

![cap problem](https://user-images.githubusercontent.com/3993447/106266316-900e4400-6228-11eb-84c2-4acb111480c5.png)

The weird part is that i see the healthchecks getting logged in the nginx service 
![nginx-service](https://user-images.githubusercontent.com/3993447/106266707-0f9c1300-6229-11eb-918e-66baa991c6e5.png)

But still Caprovers NGINX health check fails. 

Some VM info
* Ubuntu 18.04 (tried 20.04 as well, same problem) 
* Docker 19.03.6

Anyone got any idea to why this is happening?

**Comment by githubsaturn** [comment]
Can you curl from inside `captain-captain` container to this URL?
```
curl -v captain.rover.YOURDOMAIN.com/.well-known/captain-identifier-healthcheck
```
What do you see?


---
PS: as a temporary solution you can do this:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by OB3RG** [comment]
When i do the curl towards the .well-known url i get a 200 OK the first time. If i do it a second time it timeouts 

Doing the curl from my machine i get 404, but that is maybe the intent.

**Comment by githubsaturn** [comment]
> When i do the curl towards the .well-known url i get a 200 OK the first time. If i do it a second time it timeouts

So this is the problem. As for what is causing it, there are many possibilities depending on your network layout. It is weird that you're getting a 200 the first time and the subsequent ones fails.

If you're interested in getting to the bottom of this, I suggest you manually setup an nginx service (port forward 8080=>80) and another dummy service. Then shell into the dummy service and run
```
curl -v captain.rover.YOURDOMAIN.com:8080
```
to see if you can reproduce the issue on another port.

**Comment by githubsaturn** [comment]
Closing as stale. Feel free to reopen if you the problem persists.

**Comment by valoricDe** [comment]
@githubsaturn Hi I also got this problem. I see that nginx latest image is 3 days old. And my nginx logs have at the beginning these lines:
```
...
/docker-entrypoint.sh: Configuration complete; ready for start up
captain-nginx.1.ry4kngspbcmy@v2202002110089109390    | 2021/02/12 13:21:15 [warn] 1#1: conflicting server name "tunnel-frp.captain.valoric.de" on 0.0.0.0:80, ignored
captain-nginx.1.ry4kngspbcmy@v2202002110089109390    | nginx: [warn] conflicting server name "tunnel-frp.captain.valoric.de" on 0.0.0.0:80, ignored
...
```
Although I haven't touched the app for ages and kept the default nginx configuration for this app.
But in general the nginx is running.
When I curl from inside captain container I get this response:

```
root@6b9f199c94a1:/usr/src/app# curl -v -i captain.captain.valoric.de/.well-known/captain-identifier-healthcheck
*   Trying 5.45.110.88...
* TCP_NODELAY set
* Connected to captain.captain.valoric.de (5.45.110.88) port 80 (#0)
> GET /.well-known/captain-identifier-healthcheck HTTP/1.1
> Host: captain.captain.valoric.de
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Connection #0 to host captain.captain.valoric.de left intact
???root@6b9f199c94a1:/usr/src/app#
```
Strange that there is no response code or headers

**Comment by githubsaturn** [comment]
Something changed in your Docker's network config that prevents the container to call itself.... You can suppress this just by running these two lines:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

**Comment by rklos** [comment]
I have had a similar problem.

Tip for future myself and other folks:
the problem was caused by closed 80 and 443 ports in the firewall (Linux).

I don't know why is that, because out-of-the-box Docker bypasses system's firewall 🤷

**Comment by ErtugrulBEKTIK** [comment]
I had same problem also. The docker network not worked as expected. It was not related to Caprover.

The reason of not working docker network is my VPS Provider Hostinger. They use an optimized Ubuntu version and it does not compatible with docker. I used Debian instead of Ubuntu and install Caprover. The problem was fixed.
