### ISSUE TITLE
how to deploy nest js application?

### ISSUE THREAD

**Issue by webafra** [caprover/caprover#987]
hi .

i want deploy nestJs app on caprover , But I do not know how to write a docker file for this.

http://nestjs.com/

```
# build environment
FROM node:14.15.4-slim as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY . /usr/src/app
RUN npm install
RUN npm run build
RUN npm start

# production environment
FROM nginx:stable-perl
EXPOSE 3000
```

please help me.
thanks

**Comment by githubsaturn** [comment]
You can search for "NestJS Docker". Here is an example: https://dev.to/abbasogaji/how-to-dockerize-your-nestjs-app-for-production-2lmf

**Comment by webafra** [comment]
@githubsaturn thanks.
I studied education.

No need to use Nginx?
No need for reverse proxy settings for WebSocket?

**Comment by githubsaturn** [comment]
CapRover handles the http routing for you. Deploying a nestjs application is no different than any other nodejs application.
