### ISSUE TITLE
Deploying Rails app from a private repository

### ISSUE THREAD

**Issue by tobmatth** [caprover/caprover#988]
I'm trying to deploy a Rails application from a private repository with dependent containers (Postgres, Redis, App, Sidekiq), so I've set up a one-click repository and created a template. However, I'm stuck on how to clone the repo to the container (as I would have to pass the deployment key somehow to CapRover) while also being able to use CapRovers Webhook functionality to rebuild the containers on push.

Any hints very welcome!

**Comment by githubsaturn** [comment]
I am not sure if I totally understand the question here. 

If you're asking if there is a way to include webhook functionality in one click apps, that's not possible. 

Think of One Click apps as `apt install mysql` and such. 

If you want to build from a repo, you can set up your apps manually and link each of your apps to the respective git repository.

**Comment by tobmatth** [comment]
I think my problem is having different Dockerfiles per container, while deploying from the same repository. Let's assume I setup two different apps and I want to use the same repository for both. However, each container needs to run a different main process, e.g. 

`CMD bundle exec rails s -b 0.0.0.0 -p 3000` for the application server
`CMD bundle exec sidekiq -C config/sidekiq.yml` for background processing

Is this possible somehow?

**Comment by githubsaturn** [comment]
Yes, it is possible:

This is how you would do it for a one click app:
https://github.com/caprover/one-click-apps/blob/aff4fb58fe48a8fe72251f61b11e8d25af3b5dac/public/v4/apps/chatwoot.yml#L25-L63


For non click apps (the ones that don't have docker image ready), you just need to define two `captain-definition` files, like
```
captain-definition-web
captain-definition-sidekiq
```
And point to the right dockerfile, for example:
```
 {
  "schemaVersion": 2,
  "dockerfilePath": "./dockerfile.web"
 }
```

You can customize you captain-definition path on Deploy tab at the bottom of the page:
![image](https://user-images.githubusercontent.com/10582082/106388661-9c6fd980-63ad-11eb-90fd-215cbad28b7c.png)

**Comment by tobmatth** [comment]
Perfect, thank you very much
