### ISSUE TITLE
Fallback to `Dockerfile` if `captain-definition` doesn't exist in the `captain-definition Relative Path` setting

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover#989]
**Is your feature request related to a problem? Please describe.**

Having to create a `captain-definition` just to point it to a `Dockerfile` can be annoying. I personally always deploy using Dockerfiles. 

If I have several projects that I want to deploy from a monorepo, I have to create N amount of `captain-definition` files.
![image](https://user-images.githubusercontent.com/1344906/106451790-bf72ba00-648f-11eb-9d42-cd92c4209aff.png)
Caprover provides an option to deploy monorepos from here:

![image](https://user-images.githubusercontent.com/1344906/106451937-e3360000-648f-11eb-8731-560f159c2b44.png)

however, this only looks for `captain-definition`, it doesn't fallback to a `Dockerfile` if it exists.

**Describe the solution you'd like**
Caprover should look for an existing `Dockerfile` in the provided directory.

**Describe alternatives you've considered**
Creating a `captain-definition` every time which can be annoying.

**Comment by githubsaturn** [comment]
CapRover fallsback to Dockerfile in `captain-definition` does not exist for "default" case, but not for custom `captain-definition` paths, this is explicit by design.

**Comment by githubsaturn** [comment]
CapRover design is simple for default, explicit and concrete for customized cases.

**Comment by fr3fou** [comment]
> CapRover fallsback to Dockerfile in `captain-definition` does not exist for "default" case, but not for custom `captain-definition` paths, this is explicit by design.

would you at least be able to support providing a custom path *to* a Dockerfile? i.e be able to do this
![image](https://user-images.githubusercontent.com/1344906/106468169-416ddd80-64a6-11eb-93ea-7d34123f51d9.png)
Currently doing this fails as it tries to parse a JSON file.

**Comment by githubsaturn** [comment]
No this is the path to `captain-definition`. There would be no way to detect if this was intentionally pointed to a plain file (as opposed to json) or it was a mistake.

The only way that such a solution would work is to add yet another box for `Dockerfile path` which makes things even more complex. 

Also, keep in mind that currently the context for the docker build process is the root directory. If we want to directly point to a Dockerfile inside a directory, another change that would be needed to avoid confusion is to make the docker build process context aware such that operations like `COPY` don't require user to enter the directory that they are residing it.

**Comment by githubsaturn** [comment]
>  make the docker build process context aware

And this would unfortunately be a breaking change and it breaks existing build processes.
