### ISSUE TITLE
Which ports I can firewall on public interface?

### ISSUE THREAD

**Issue by alexander-potemkin** [caprover/caprover#990]
I've checked the issues, but haven't found the appropriate one.

--------------------------------------------------------------------------

CapRover requires quite a lot of ports to be opened after the installation (https://caprover.com/docs/firewall.html):

80 TCP for regular HTTP connections
443 TCP for secure HTTPS connections
3000 TCP for initial Captain Installation (can be blocked once Captain is attached to a domain)
7946 TCP/UDP for Container Network Discovery
4789 TCP/UDP for Container Overlay Network
2377 TCP/UDP for Docker swarm API
996 TCP for secure HTTPS connections specific to Docker Registry

Can I block all of them but 443 from public access / on my public interface, if CapRover is only providing an access to the web service on HTTPS?

If so - it could be nice to upgrade the documentation.
If not - could you please, let me know the reason, so that I would better understand things and probably come with a better idea? =)

Thank you in advance!

**Comment by githubsaturn** [comment]
The reason for each port is outlined in the docs as you copied:

> 3000 TCP for initial Captain Installation (can be blocked once Captain is attached to a domain) 

Self explanatory

> 7946 TCP/UDP for Container Network Discovery
4789 TCP/UDP for Container Overlay Network
2377 TCP/UDP for Docker swarm API

If you're not using swarm (i.e., you have one single node), you can block these


> 996 TCP for secure HTTPS connections specific to Docker Registry

If you're not using self hosted Docker Registry, you can block 996

-----

80 and 443 must be kept open for HTTP and HTTPS connections

**Comment by alexander-potemkin** [comment]
Yes, I read the names of the services, but without knowing how things build, I can not know how it works and how it will affect work, hence the question.

So, basically, I can close any ports other than 80 and 443 from the outside internet?

If so, I believe it makes sense to outline that on the documentation, as the docs and CapRover setup instruction states that those ports have to be opened to the Internet, which means security risk.

**Comment by githubsaturn** [comment]
If you have a Docker swarm you cannot close these:
7946 TCP/UDP for Container Network Discovery
4789 TCP/UDP for Container Overlay Network
2377 TCP/UDP for Docker swarm API

If you have a Docker registry, you cannot close 996.

The only port that can be closed post installation for all setups is port 3000.

**Comment by githubsaturn** [comment]
Feel free to add these to the docs, they are editable.

**Comment by alexander-potemkin** [comment]
Please, forgive me, but why do I need all those ports to be available for public Internet?

**Comment by githubsaturn** [comment]
If you have a docker cluster, you need all nodes to be able to talk to each other.

**Comment by alexander-potemkin** [comment]
Got it. So, 80 and 443 ports has to be accessible to the outside world for obvious reasons, but others has to be opened only to the access from the other CapRover nodes (if any)?

**Comment by githubsaturn** [comment]
Yes

**Comment by alexander-potemkin** [comment]
Thank you!
