### ISSUE TITLE
Integration of nginx New Relic monitoring

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#991]
Is it possible to integrate [New Relic nginx monitoring](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration) into CapRover?

I've no idea whether it will be of any help, but I've been [trying to figure out](https://discuss.newrelic.com/t/what-is-other-in-transaction-breakdown/38456/7) why a significant chunk of my app's time seems to be allocated to a catch-all "Other" category.  I can't see what this Other category might relate to within the processes carried out (from end to end) in the handling of the node express route concerned, and am wondering whether it might "outside" the route itself and perhaps some waiting time relating to nginx.  Probably barking up the wrong tree.  

I do have quite a few "Waiting Requests" as shown in the Load Balancer section of the CapRover console but from some googling I don't think that is necessarily a problem, and may just be connections that are being kept alive after they are done (`keepalive_timeout` is set to `65s` it appears), so these are not "waiting" as such (or rather not keeping some other process waiting).

**Comment by githubsaturn** [comment]
I am not sure what the Relic integration requires you to do. From skimming their page, it looks like they require you to expose the status page. CapRover already does that:
https://github.com/caprover/caprover/blob/eaa0e710324aaf5f3529496d0f147783a62b1702/template/root-nginx-conf.ejs#L15-L27


But I am not sure what else it requires.


Also, not sure if this is your bottleneck, but you can try changing connections and worker processes:
https://github.com/caprover/caprover/blob/eaa0e710324aaf5f3529496d0f147783a62b1702/template/base-nginx-conf.ejs#L1-L10

**Comment by drmrbrewer** [comment]
I changed `worker_processes` to `auto`, which should amount to changing it to `8` because I have 8 CPU cores on the server (I confirmed this by also setting it explicitly to `8`).  Doesn't seem to make any difference... still I have a mysteriously large "Other" chunk on my metrics chart :-(  For one of the routes it is a major part of the overall timing (in yellow):

![image](https://user-images.githubusercontent.com/9009792/106632516-be1bbd00-6575-11eb-9383-612128191945.png)

On the Load Balancer page of CapRover) I have roughly 480 "Active Connections" at any one time, of which 20 are "Active Requests" (reading/writing) and 460 are "Waiting Requests", so I guess having 8 CPUs and 1 `worker_processes` and 1024 `worker_connections` should be sufficient, without bottleneck.

Incidentally:

(1) even the [official nginx blog](https://www.nginx.com/blog/tuning-nginx/) recommends setting `worker_processes` to `auto`, which makes me wonder why the default is set to `1`... to quote from this blog: "`worker_processes` – The number of NGINX worker processes (the default is 1).  In most cases, running one worker process per CPU core works well, and we recommend setting this directive to auto to achieve that."

(2) On the Settings page of CapRover, having edited the nginx config, it's not clear how to revert to the default config.  The equivalent option on the app-specifc page notes that `To revert to default, simply remove all the content.`.  I assume it's the same on the main Settings page?  Perhaps useful to add a similar statement on that page too?

(3) Having edited the nginx config and hit Save, the following message appears:

![image](https://user-images.githubusercontent.com/9009792/106631920-21f1b600-6575-11eb-84e8-8721ad389006.png)

It refers to restarting in 30 seconds, but the countdown timer actually starts at 60 seconds.

**Comment by githubsaturn** [comment]
RE 1:
1 should be fine in most cases. nginx is in fact very light and fast. It's unlikely that it requires any more than 1 process. There are some cases where maybe `auto` is better (some heavy decryption on nginx, or 1000s of domains and mostly static content and etc...)


RE 2:
Please create an issue for this so we can address it at some point.


RE 3:
Please create an issue for this so we can address it at some point.


RE 4:
Yes, but it comes at the cost of probably some slower future connections for your clients. I am not an nginx expert, so take this with grain salt.

**Comment by drmrbrewer** [comment]
It sounds like nginx is lightweight and quick, and probably isn't the reason for the mysterious Other group, particularly since disabling `keepalive_timeout` massively reduces the waiting requests without any effect (I thought it might be that).  I'll probably revert to the default nginx config (not least because using a custom config means that I don't take advantage of changes made by you to the default in future).  Feel free to close this issue, thanks.
