### ISSUE TITLE
[Question] Cloudflare Access Integration

### ISSUE THREAD

**Issue by ElectricReality** [caprover/caprover#993]
Good Day! I have been trying to get a full Cloudflare Access-CapRover integration working. The only problem is that the login request does not include certain headers integral to Cloudflare Access. For those who got this working, how'd you do it?

Thank you!

**Comment by githubsaturn** [comment]
What are the headers that are missing?

PS: for community questions, please reach out to our Slack channel.

**Comment by ElectricReality** [comment]
According to CF Access' [Documentation](https://developers.cloudflare.com/access/setting-up-access/cors#cors-requests-that-do-not-require-options-simple-requests), ``CF_authorization`` header cookie is from the request. 

```
POST /api/v2/login HTTP/2
Host: captain.example.com
User-Agent: secret
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json;charset=utf-8
x-namespace: captain
Content-Length: 24
Origin: https://captain.example.com
DNT: 1
Connection: keep-alive
Referer: https://captain.example.xyz/
Cookie: __cfduid=SECRET; CF_Binding=SECRET
TE: Trailers
```

**Comment by githubsaturn** [comment]
Okay, so it's not a separate header, it's just a cookie. 

CapRover doesn't do anything specific to block cookies and etc. If it's received by the client, it'll be passed to upstream.
