### ISSUE TITLE
temporary-captain-to-deploy.tar location

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover#996]
Hi, I want to commit to github and its complaining about my large (> 100mb) *.tar file.

Where does this file exist? I need to remove (or can I .gitignore it?)

Thanks

Neil

**Comment by githubsaturn** [comment]
It's the file that gets created when you run `caprover deploy` and it get deleted right after that. You won't need to commit this file.

This file gets created at the root of your directory and can be added to gitignore. But you don't need to, as the file gets deleted when `caprover deploy` finishes. Perhaps there is something that prevents that file from getting deleted. 

Regardless, you can add it to your gitignore.
