### ISSUE TITLE
Please, add support to cyrillic domain names

### ISSUE THREAD

**Issue by sergerodin** [caprover/caprover#997]
While trying to add something like вашдомен.рф via Caprover admin interface, I see the error message: “1104 : Domain name is not accepted. Please use alphanumerical domains such as myapp.google123.ca”. Using the ASCII DNS name format won't help either.

Those domains are much in use in Russia but I see no way to manage them via Caprover.

**Comment by githubsaturn** [comment]
@sergerodin the ascii equivalent should work, doesn't it?

Can you try `xn--80adhe8ahe2f.xn--p1ai` ? this is the ascii equivalent of `вашдомен.рф`

**Comment by sergerodin** [comment]
@githubsaturn thanks for your reply. 

ASCII works indeed! 
I have probably tried it with ‘http://‘ prefix and that's the real reason it was not accepted.
