### ISSUE TITLE
Enable https on app only works if https is enabled on dashboard. Not asking for Email for letsencrypt

### ISSUE THREAD

**Issue by rolandmueller** [caprover/caprover#998]
### What is the problem?

When you enable https on an app without before enabling https on the Caprover dashboard, an error message appears and then disappears immediately with the following content:

"1107 : Unexpected output when enabling SSL for www.yourdomain.com with ACME Certbot Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None [31mYou should register before running non-interactively, or provide —agree-tos and —email <email_address> flags." 

The solution is to first enable https on the dashboard. There you are asked for your email for letsencrypt. Afterwards you can enable https on your app.

### Suggested improvements:
* Change the error message (e.g. "first enable https on the dashboard) and change the duration how long the error message appears, or
* Ask for the email for letsencrypt also when you only enable https on an app

### Steps to reproduce the problem:
1. Fresh installation of Caprover with a unused domain
2. Create an app (e.g. one-click installation of Wordpress)
3. Enable https on the app 

Thank you again for your great work!

**Comment by githubsaturn** [comment]
Thanks!
