### ISSUE TITLE
Dealing with persistent folders

### ISSUE THREAD

**Issue by bilicio** [caprover/caprover#999]
**Is your feature request related to a problem? Please describe.**
Its hard to deal with persistent directories, every time i need to do a clean build, i have to ssh my virtual machine, stop docker, remove persistent directories and restart the server. Even after i did that i cant use the old directory's label. I need to change the label to a different name, if i dont do that my application wont start.

**Describe the solution you'd like**
A simple button to clean the files inside the persistent folder. 

**Describe alternatives you've considered**
just the above.

**Additional context**

**Comment by githubsaturn** [comment]
> every time i need to do a clean build, i have to ssh my virtual machine, stop docker, remove persistent directories and restart the server

Why do you need to do this? What's the use case?

**Comment by bilicio** [comment]
Hi kasra! Im using persistent database on the persistent folder, and sometimes I need to clean the whole database because the schema changes and need a full rebuild. I need to clean the folder for images too, when all images change and I don't want to keep the old ones when I make the full app rebuilded.

**Comment by githubsaturn** [comment]
That sounds like a special use case for your flow. But still, there is no need for stopping docker and restarting the server. 

You can simply add a line to your Dockerfile to clean up the directories on start up if the schema changes or etc.

Alternatively you can simply have a simply script to do this for you, e.g.:
`cleanup.sh`
```bash
#!/bin/bash

# cleanup volumes
ssh root@123.123.123.123 rm -rf /var/lib/docker/volumes/captain--yourvolumename1/_data/*
ssh root@123.123.123.123 rm -rf /var/lib/docker/volumes/captain--yourvolumename2/_data/*


# restart service
ssh root@123.123.123.123 docker service update srv-captain--yourappname --force
```

**Comment by bilicio** [comment]
Nice script ! One question, this works for folder in use? Because I need to stop docker when it's said that the folder is in use.

**Comment by githubsaturn** [comment]
Yes.

**Comment by bilicio** [comment]
Awesome! I will try that! Thank you!
